### ISSUE TITLE
Graphql transform generates wrong schema.

### ISSUE THREAD

**Issue by lenarmazitov** [aws-amplify/amplify-cli#1732] opened 2019-06-26 15:57 UTC
We have schema described in Graphql transform syntax:

```
type User @model @key(fields: ["owner"]) @auth(
  rules: [
    {allow: owner},
    {allow: groups, groupsField: "groups", operations: [read]}
  ]) {
  owner: ID!
  groups: [String]
}
```
When we push this schema, we expect that **CreateUserInput** will be:
```
input CreateUserInput {
  owner: ID!
  groups: [String]
}
```
But actually we have:
```
input CreateUserInput {
  owner: ID!
  groups: String
}
```

And this is not only about schema, also we have same in generated API.js:
```
export type CreateUserInput = {|
  owner: string,
  groups?: ?string,
|};
```
And in graphql/schema.json: 
```
       {
          "name" : "groups",
          "description" : null,
          "type" : {
            "kind" : "SCALAR",
            "name" : "String",
            "ofType" : null
          },
          "defaultValue" : null
        }
```

**To Reproduce**
- amplify add api
- insert above schema
- amplify push

**Comment by attilah** [comment] 2019-06-27 15:26
@lenarmazitov I was not able to reproduce it with the latest version (1.7.6). Could you please check and confirm that it works with the latest version on your end as well?

I'm closing the issue, but if it still exist for you please feel free to reopen at a later time.

**Closed by attilah** 2019-06-27 15:26 UTC
Labels: bug, graphql-transformer
