### ISSUE TITLE
Simpler Way to Configure Lambda Triggers for Cognito

### ISSUE THREAD

**Issue by exaucae** [aws-amplify/amplify-cli#12608] opened 2023-05-10 09:08 UTC
### Amplify CLI Version

11.1.1

### Question

I want to add a [PostConfirmation lambda trigger](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-post-confirmation.html) to Cognito. 

So far [the amplify documentation](https://docs.amplify.aws/cli/usage/lambda-triggers/#set-up-lambda-triggers) says nothing about which command to use for that. To achieve it, I've gone through `amplify update auth`. It came to me that I need to reach the last question: `Do you want to configure lambda triggers for cognito ?` before selecting a trigger. 

Consequently, **I (may) override other configs depending on my answers to intermediate questions. That's not the initial aim.** It rather adds noise to the primary goal (see https://github.com/aws-amplify/amplify-cli/issues/620#issuecomment-658841064) and adds cognitive load ( see https://github.com/aws-amplify/amplify-cli/issues/620#issuecomment-660091045).

This situation becomes  critical in a shared-codebase: someone unexpectedly overrides Cognito Resources when trying to add a trigger.

 
````
> amplify update auth
Please note that certain attributes may not be overwritten if you choose to use defaults settings.

You have configured resources that might depend on this Cognito resource.  Updating this Cognito resource could have unintended side effects. 

Using service: Cognito, provided by: awscloudformation
 What do you want to do? Walkthrough all the auth configurations
 Select the authentication/authorization services that you want to use: User Sign-Up
, Sign-In, connected with AWS IAM controls (Enables per-user Storage features for im
ages or other content, Analytics, and more)
 Allow unauthenticated logins? (Provides scoped down permissions that you can contro
l via AWS IAM) No
 Do you want to enable 3rd party authentication providers in your identity pool? No
 Do you want to add User Pool Groups? No
 Do you want to add an admin queries API? No
 Multifactor authentication (MFA) user login options: OFF
 Email based user registration/forgot password: Enabled (Requires per-user email ent
ry at registration)
 Specify an email verification subject: Your verification code
 Specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? No
 Specify the app's refresh token expiration period (in days): 30
 Do you want to specify the user attributes this app can read and write? No
 Do you want to enable any of the following capabilities? 
 Do you want to use an OAuth flow? No
? Do you want to configure Lambda Triggers for Cognito? Yes
? Which triggers do you want to enable for Cognito 
 ◯ Post Authentication
❯◉ Post Confirmation
 ◯ Pre Authentication
 ◉ Pre Sign-up
 ◯ Verify Auth Challenge Response
 ◯ Pre Token Generation
 ◯ Learn More
(Move up and down to reveal more choices)

````

## Suggestion

I'd expect a simpler way to add lambda triggers, as: `aws update auth --lambda-triggers`. This command would directly prompt the question: `Which triggers do you want to enable for Cognito ?`

I've also seen [a compeling proposal](https://github.com/aws-amplify/amplify-cli/issues/620#issuecomment-580509386) to have lambda triggers in the list after running `amplify auth update`:

````
$ amplify auth update

Using service: Cognito, provided by: awscloudformation
 What do you want to do? (Use arrow keys)
❯ Apply default configuration without Social Provider (Federation)
  Walkthrough all the auth configurations
  Add/Edit signin and signout redirect URIs
  Update OAuth social providers
  Add/Update lambda triggers                 // ***** something like this *****
  Create or update Cognito user pool groups
  Create or update Admin queries API
````

I'm also open to existing esier ways to create lambda triggers via the CLI.

**Comment by josefaidt** [comment] 2023-05-10 17:04
Hey @exaucae :wave: thanks for raising this, and we think this is a great idea! We're going to mark this as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/6700 and close in favor of tracking the existing feature request. Please subscribe to #6700 for further updates

**Closed by josefaidt** 2023-05-10 17:04 UTC
Labels: functions, auth, feature-request
