### ISSUE TITLE
Error Adding and Updating API with amplify-cli version 4.12.0

### ISSUE THREAD

**Issue by elimence** [aws-amplify/amplify-cli#3186] opened 2020-01-14 18:06 UTC
**Describe the bug**
After upgrading to amplify-cli version 4.12, `amplify api add` and `amplify api update` no longer work.
Init command works as expected.

**Amplify CLI Version**
`4.12.0`

**To Reproduce**
> `amplify api add`

```
? Please select from one of the below mentioned services: GraphQL
SyntaxError: Unexpected identifier
    at serviceQuestions (/Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/provider-utils/awscloudformation/index.js:13:10)
    at Object.addResource (/Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/provider-utils/awscloudformation/index.js:54:10)
    at /Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/commands/api/add.js:24:35
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.executeAmplifyCommand (/Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/index.js:176:3)
There was an error adding the API resource
```

`amplify api update`

```
? Please select from one of the below mentioned services: GraphQL
Unexpected token ','
SyntaxError: Unexpected token ','
    at Object.updateResource (/Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/provider-utils/awscloudformation/index.js:109:10)
    at /Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/commands/api/update.js:19:35
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.executeAmplifyCommand (/Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/index.js:176:3)
```

**Expected behavior**
Be able to add or update api as is expected.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. `v13.2.0`

**Additional context**
Looks like downgrading to cli version 3.7 makes the error go away. I can verify if this is relevant.
I tested with a fresh project and an existing one and got the same errors.

**Comment by elimence** [comment] 2020-01-14 18:36
On version `4.5` I get this error
```
? Please select from one of the below mentioned services: GraphQL
/Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js:1
import { getDataStoreLearnMore } from '../sync-conflict-handler-assets/syncAssets';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (vm.js:376:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
There was an error adding the API resource
```

**Comment by nikhname** [comment] 2020-01-14 18:45
@elimence Did you install the CLI using yarn or npm?

**Comment by elimence** [comment] 2020-01-15 05:37
@nikhname I used npm

**Comment by elimence** [comment] 2020-01-15 06:38
For most of the versions I tried installing (except 4.9), I got this log messages

```
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/Users/elimence/.nvm/versions/node/v13.2.0/bin/node" "/Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/fsevents
gyp ERR! node -v v13.2.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok

> @aws-amplify/cli@4.0.0 postinstall /Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli
> node scripts/post-install.js

Ignore installation errors for optional dependencies: gyp, fs-ext
```

So I installed command line tools and the failing commands work now.

**Comment by HoraceShmorace** [comment] 2020-01-20 23:13
Please reopen this. I have the same environment/versions, and get the same exact errors.

The previous version of amplify cli was working without command line tools installed. If it's now required, it should be called out.

That being said, I installed command line tools, and I get the same exact errors.

**Comment by HoraceShmorace** [comment] 2020-01-20 23:37
Note, I tested most other resources, and so far it only happens with a GraphQL API.

**Comment by HoraceShmorace** [comment] 2020-01-26 22:57
Here's another example, showing that it happens regardless of project (note the versions in my local environment):
![image](https://user-images.githubusercontent.com/543024/73143203-37302c80-4065-11ea-8122-30ea9bd154ae.png)

**Comment by HoraceShmorace** [comment] 2020-01-26 23:31
I've upgraded to 4.13.1 and the problem is gone. I'll leave it to you, @nikhname, whether you want to close this.

**Closed** 2020-01-26 23:47 UTC
Labels: not-reproducable, platform
