### ISSUE TITLE
Specific Fn::GetAtt format breaks the Amplify CLI

### ISSUE THREAD

**Issue by flyck** [aws-amplify/amplify-cli#5241] opened 2020-09-03 13:24 UTC
**Describe the bug**
Calling Fn::GetAtt with a string argument instead of a list of two Strings breaks the amplify-cli without any helpful debugging info. `{ "Fn::GetAtt": "MyQueue.Arn"}` breaks everything while `{ "Fn::GetAtt": ["MyQueue", "Arn"]}` works. Meanwhile both versions work in CloudFormation. Since there is no debug info and the same template works in CloudFormation this took me quite some time to pin down.

**Amplify CLI Version**
4.28.2

**To Reproduce**
* Create a custom CloudFormation template according to the instructions here: https://docs.amplify.aws/cli/usage/customcf
* template.json:
```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Parameters": {
    "env": {
      "Type": "String",
      "Description": "Amplify Environment"
    }
  },
  "Resources" : {
    "MyQueue" : {
      "Type" : "AWS::SQS::Queue",
      "Properties" : {
         "QueueName" : "SampleQueue"
      }
    }
  },
  "Outputs": {
    "Queuename": {
      "Value": { "Fn::GetAtt": "MyQueue.Arn"}
    }
  }
}
```
* Run `amplify push`
* Amplify Errors as follows
```
Invalid CloudFormation template: .../template.json
✖ An error occurred when pushing the resources to the cloud

toGet.slice(...).join is not a function
An error occurred during the push operation: toGet.slice(...).join is not a function
```

**Expected behavior**
Either a more detailed error message or a bug fix to have these templates deployed successfully. 

**Desktop (please complete the following information):**
 - Mac: 10.14.6
 - Node Version: v14.1.0

**Comment by akshbhu** [comment] 2020-09-03 23:41
Hi @BubblesToTheLimit 

Yes, I have reproduced this, both the format works in AWS console .The  Problem is arising due to cfn-lint which we use to validate CFN templates. The string format of ```Fn::GetAtt```  complaining in validation. As based on ```Fn::GetAtt``` documentation this it takes only array format here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html.

I am not sure if this is recent change in CFN to take both array and string format. We are looking into it.
For the workaround you can continue to use array format.

**Comment by kaustavghosh06** [comment] 2021-02-05 21:35
@flyck We've mad cfn-lint liniting as a warning and not an error and your push shouldn't fail hopefully if you're using the latest version of the CLI. Could you please give it a shot and let me know if this works for you?
Closing this issue for now.

**Closed by kaustavghosh06** 2021-02-05 21:35 UTC
Labels: bug, cloudformation

**Comment by mattfysh** [comment] 2021-03-06 04:03
I just installed the latest CLI version published 8 hours ago, and then a few of my cloudformation templates were updated when I next ran an `amplify env pull`. The most changes appear to be in the CF file for cognito/auth (YML). This file now fails `cfn-lint` validation when I run `amplify push`

**Comment by narciso-dev** [comment] 2021-03-07 15:14
+1

**Comment by dmsolutionz** [comment] 2021-03-08 11:23
> @flyck We've made cfn-lint liniting as a warning and not an error and your push shouldn't fail hopefully if you're using the latest version of the CLI. Could you please give it a shot and let me know if this works for you?
> Closing this issue for now.

This is now broken again within `4.45.0`

**Comment by CharlieDigital** [comment] 2021-03-08 16:23
Adding to this discussion; updated this morning to `4.45.0` and also running into the same issue.

```
Invalid CloudFormation template: C:\Users\{...}\amplify\backend\auth\{...}\{...}-cloudformation-template.yml
toGet.slice(...).join is not a function
```

**Comment by evanmcd** [comment] 2021-03-08 17:23
I was getting the same error. Fortunately, my git rollback to the previous version of the template.yml file fixed the error.

**Comment by hisham** [comment] 2021-03-08 23:11
+1. Tried to open a new bug request but there's new long form that need to be filled out....

**Comment by 24601** [comment] 2021-03-08 23:59
+1, another failure, we made no changes except new versions of CLI

**Comment by Tritium7** [comment] 2021-03-09 10:26
+1

I updated the Amplify CLI to --> 4.45.0 , and it prompted that the nodejs runtime needs to be updated in 'auth' category YAML template, so I updated it.

After the push, the amplify gave this error message:

```
Invalid CloudFormation template: 
c:\...\PROJECT\amplify\backend\auth\RESOURCENAME\RESOURCENAME-cloudformation-template.yml
toGet.slice(...).join is not a function
```

Despite the message, the update was successful, and I could confirm the changes with the console.

**Comment by kaustavghosh06** [comment] 2021-03-09 17:59
We've root-caused the issue and here's the fix for it - https://github.com/aws-amplify/amplify-cli/pull/6834. We're working on getting a release out with the fix for this as we speak.

**Comment by drdrwhite** [comment] 2021-03-11 10:48
+1 here

Do we have a recommend workaround (including rolling back) for this, please?

**Comment by macsj200** [comment] 2021-04-05 16:01
+1
