### ISSUE TITLE
amplify configure: "aws_access_key_id" and "aws_secret_access_key" have replaced to `true` and name of my profile wrapped with doublequote

### ISSUE THREAD

**Issue by geoseong** [aws-amplify/amplify-cli#3000] opened 2019-12-14 14:13 UTC
**Describe the bug**
I have several profiles in `.aws/credentials`.
after I use cli `amplify configure` and create a new IAM user,
some of my existed profile's **aws_access_key_id** and **aws_secret_access_key** have replaced to `true`
and also wrapped with doublequote except IAM user which is newly created
I attached this situation in `Screenshots` section

**Amplify CLI Version**
4.6.0

**To Reproduce**
1. $ amplify configure
2. add new IAM user

**Expected behavior**
- input several profiles in `.aws/credentials`.
- use `amplify configure` cli and create a new IAM user called `aws-gs`
- check  **aws_access_key_id** and **aws_secret_access_key** have replaced to `true` and also name of my profile wrapped with doublequote

**Screenshots**
```
"[404hunter-root]"=true
aws_access_key_id=****
aws_secret_access_key=****
"[404hunter-geoseong]"=true
"[ideasam-geoseong]"=true
"[changsoft-geoseong]"=true

[default]
aws_access_key_id=****
aws_secret_access_key=****

[aws-gs]
aws_access_key_id=****
aws_secret_access_key=****

```

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v10.15.3

**Comment by yuth** [comment] 2019-12-16 23:09
@geoseong I could not reproduce this. Could you share the name of the profiles you had before running `amplify configure`

**Comment by geoseong** [comment] 2019-12-18 04:40
@yuth 
name of the profiles is in `Screenshots` section posted above here.
I haven't backed up my `credentials` file so I recovered and tried to reproduce this issue, that problem haven't occured...
it is weird... can you provide code path which handle aws profile in amplify-cli?

**Comment by yuth** [comment] 2019-12-18 18:11
The code that updates the credentials should be somewhere in this file 
https://github.com/aws-amplify/amplify-cli/blob/dcee2aab12b40562d1c6f0d260b830ca4ab0bedd/packages/amplify-provider-awscloudformation/lib/system-config-manager.js#L14-L59

**Comment by kaustavghosh06** [comment] 2019-12-19 00:50
@geoseong We weren't able to reproduce this issue. If you're able to reproduce this issue with any other profile name, please let us know. Closing this issue for now.

**Closed by kaustavghosh06** 2019-12-19 00:50 UTC
Labels: not-reproducable, pending-triage, platform
