### ISSUE TITLE
Recent fixes #7874, breaks publish

### ISSUE THREAD

**Issue by Wignesh** [aws-amplify/amplify-cli#8105] opened 2021-09-06 12:04 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.16.0

### Amplify CLI Version

5.4.0

### What operating system are you using?

Ubuntu

### Amplify Categories

hosting

### Amplify Commands

publish

### Describe the bug

When running `amplify publish --yes`, on headless mode show's 

> You have already connected branches to your Amplify Console app. Please visit the Amplify Console to manage your branches.

### Expected behavior

Should deploy the changes

### Reproduction steps

1. `amplify pull`
2. `amplify publish`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line

amplify publish --yes

You have already connected branches to your Amplify Console app. Please visit the Amplify Console to manage your branches.
```

</details>

**Comment by cjihrig** [comment] 2021-09-06 14:54
Thanks for reporting this. I'm going to close this issue as a duplicate of #8092. Please follow along there for updates.

**Closed by cjihrig** 2021-09-06 14:54 UTC
