### ISSUE TITLE
Amplify headless pull results in SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by cfitzpatrickbardess** [aws-amplify/amplify-cli#10071] opened 2022-03-25 19:00 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli@latest

### If applicable, what version of Node.js are you using?

16.x

### Amplify CLI Version

7.6.26

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

auth, api, hosting

### Amplify Commands

pull

### Describe the bug

When using the following bash script with GitHub Actions to pull the amplify environment, the following error is produced:
SyntaxError: Unexpected token 'export'

```
#!/bin/bash
set -e
IFS='|'

VUECONFIG="{\
\"SourceDir\":\"src\",\
\"DistributionDir\":\"dist\",\
\"BuildCommand\":\"npm.cmd run-script build\",\
\"StartCommand\":\"npm.cmd run-script start\"\
}"

AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":false,\
\"accessKeyId\":\"xxx\",\
\"secretAccessKey\":\"xxx\",\
\"region\":\"us-east-1\"\
}"

AMPLIFY="{\
\"projectName\":\"xx\",\
\"appId\":\"xx\",\
\"envName\":\"xx\",\
\"defaultEditor\":\"vscode\"\
}"

FRONTEND="{\
\"frontend\":\"javascript\",\
\"framework\":\"vue\",\
\"config\":$VUECONFIG\
}"

PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"

AUTHCONFIG="{\
\"userPoolId\": \"$user_pool_id\",\
\"webClientId\": \"$web_client_id\",\
\"nativeClientId\": \"$web_client_id\",\
}"

CATEGORIES="{\
\"auth\":$AUTHCONFIG\
}"

CODEGEN="{\
\"generateCode\":true,\
\"codeLanguage\":\"javascript\",\
\"fileNamePattern\":\"src/graphql/**/*.js\",\
\"generatedFileName\":\"API\",\
\"generateDocs\":true\
}"

echo "${AMPLIFY}"
echo "${FRONTEND}"
echo "${PROVIDERS}"
echo "${CATEGORIES}"

amplify pull --amplify $AMPLIFY --frontend $FRONTEND --providers $PROVIDERS --categories $CATEGORIES --yes
```

This results in the following:

```
Amplify AppID found: d1s9d54cg64wus. Amplify App name is: synergy
Backend environment cicd found in Amplify Console app: synergy
Failed to pull the backend.
Unexpected token 'export'
/home/runner/work/Synergy-UI/Synergy-UI/synergy/src/aws-exports.js:23
export default awsmobile;
^^^^^^

SyntaxError: Unexpected token 'export'
    at compileFunction (<anonymous>)
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at getCurrentAWSExports (/opt/hostedtoolcache/node/16.14.0/x64/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/lib/frontend-config-creator.js:281:18)
    at getAWSExports (/opt/hostedtoolcache/node/16.14.0/x64/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/lib/frontend-config-creator.js:146:35)
    at createAWSExports (/opt/hostedtoolcache/node/16.14.0/x64/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/lib/frontend-config-creator.js:138:31)
    at Object.createFrontendConfigs (/opt/hostedtoolcache/node/16.14.0/x64/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/index.js:47:16)
    at AmplifyToolkit.onCategoryOutputsChange [as _onCategoryOutputsChange] (/opt/hostedtoolcache/node/16.14.0/x64/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/on-category-outputs-change.ts:21:33)
    at generateFiles (/opt/hostedtoolcache/node/16.14.0/x64/lib/node_modules/@aws-amplify/cli/src/attach-backend-steps/a40-generateFiles.ts:44:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at attachBackend (/opt/hostedtoolcache/node/16.14.0/x64/lib/node_modules/@aws-amplify/cli/src/attach-backend.ts:30:5)
    at Object.run (/opt/hostedtoolcache/node/16.14.0/x64/lib/node_modules/@aws-amplify/cli/src/commands/pull.ts:63:5)
    at Object.executeAmplifyCommand (/opt/hostedtoolcache/node/16.14.0/x64/lib/node_modules/@aws-amplify/cli/src/index.ts:373:5)
    at executePluginModuleCommand (/opt/hostedtoolcache/node/16.14.0/x64/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:[178](https://github.com/Devron-ai/Synergy-UI/runs/5695557464?check_suite_focus=true#step:4:178):3)
    at executeCommand (/opt/hostedtoolcache/node/16.14.0/x64/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/opt/hostedtoolcache/node/16.14.0/x64/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)
```

### Expected behavior

I expect the amplify environment to be pulled with no errors

### Reproduction steps

1. Create an amplify app with auth, hosting and api
2. Run the headless script with GitHub Actions

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment] 2022-03-25 20:08
Hey @cfitzpatrickbardess thanks for the clarification! For what it's worth the error we would receive from that type of project would be different (`🛑 An error occurred during the push operation: require() of ES Module`). Let me take a further look at this one 🙂

**Comment by josefaidt** [comment] 2022-03-25 21:00
Hey @cfitzpatrickbardess to clarify, is `aws-exports.js` committed to git? If so, was it modified at all? If not, is this a publicly viewable repository? I would like to take a further look at the project configuration as I was unable to reproduce this

**Comment by cfitzpatrickbardess** [comment] 2022-03-25 21:05
Hi @josefaidt, the repository isn't public unfortunately. I have not tested the headless init, but I can set up an empty branch and try. I will keep you updated.

**Comment by josefaidt** [comment] 2022-03-25 21:49
related: https://github.com/aws-amplify/amplify-cli/issues/9951

**Comment by cfitzpatrickbardess** [comment] 2022-03-28 15:11
Good morning @josefaidt. I changed the command to init and received the following error ```
- Initializing your environment: cicd
- Building resource auth/synergy9cd20dc0
- Building resource api/SynergyAPI
✔ Initialized provider successfully.
✖ There was an error initializing your environment.
```

I then added deletion of the amplify directory and aws-exports.js file to my headless script and I'm now able to pull the environment and publish.

**Comment by josefaidt** [comment] 2022-03-28 19:12
Hey @cfitzpatrickbardess glad to hear you're up and running! Can you clarify this note?

> I then added deletion of the amplify directory and aws-exports.js file to my headless script and I'm now able to pull the environment and publish.

Was the workaround here to delete the existing `amplify` and `aws-exports.js` files from our local filesystem?

**Comment by josefaidt** [comment] 2022-03-31 13:24
Hey y'all I was able to reproduce this issue and added my notes to this issue: https://github.com/aws-amplify/amplify-cli/issues/10101#issuecomment-1084571355

Marking this as a duplicate bug 🙂

**Comment by cfitzpatrickbardess** [comment] 2022-03-31 13:29
> Hey @cfitzpatrickbardess glad to hear you're up and running! Can you clarify this note?
> 
> > I then added deletion of the amplify directory and aws-exports.js file to my headless script and I'm now able to pull the environment and publish.
> 
> Was the workaround here to delete the existing `amplify` and `aws-exports.js` files from our local filesystem?

Hi @josefaidt, yes, when I added steps to my headless script to remove the existing amplify directory and aws-exports.js file from the project, I was able to run the pull command successfully.

**Comment by josefaidt** [comment] 2023-06-27 20:26
Closing as this was completed and #10101 was resolved

**Closed by josefaidt** 2023-06-27 20:26 UTC
Labels: bug, platform, duplicate, p2
