### ISSUE TITLE
Platform with type "Windows_NT" and architecture "ia32" is not supported by @aws-amplify/cli.

### ISSUE THREAD

**Issue by gramkrishna** [aws-amplify/amplify-cli#13417] opened 2023-11-19 08:09 UTC
### How did you install the Amplify CLI?

using npm and curl

### If applicable, what version of Node.js are you using?

v18.15.0

### Amplify CLI Version

that also throws above error

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No, it is the first step. I am surprised, if amplify is not for Windows NT or for ia32 which is like 99% of the PCs and laptops, what have you made it for?

### Describe the bug

I installed using the given npm command. npm install -g @aws-amplify/cli and see 26 packaged deployed. The moment I type amplify configure or anything with amplify ( say amplify -v) it throws the above error. packages

### Expected behavior

amplify configure should run

### Reproduction steps

> npm install -g @aws-amplify/cli
> amplify -v 
> amplify configure

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment] 2023-11-20 15:06
Hey @gramkrishna, thank you for reaching out. The issue is similar to https://github.com/aws-amplify/amplify-cli/issues/10295 and https://github.com/aws-amplify/amplify-cli/issues/10405. 
From https://github.com/aws-amplify/amplify-cli/blob/7fbf29f56eb7335d20de0b5526fbed7795a2af09/packages/amplify-cli-npm/binary.ts#L22C13-L22C13 ,Amplify CLI currently expects Windows NT x64.
Marking as duplicate and closing.

**Closed by ykethan** 2023-11-20 15:06 UTC
Labels: pending-triage
