### ISSUE TITLE
Amplify push fails on - HostedUIProvidersCustomResourceInputs Custom::LambdaCallout

### ISSUE THREAD

**Issue by ptejada** [aws-amplify/amplify-cli#8149] opened 2021-09-10 05:32 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### If applicable, what version of Node.js are you using?

v14.16.1

### Amplify CLI Version

5.5.0

### What operating system are you using?

Windows (WSL - Ubuntu)

### Amplify Categories

auth, function, api

### Amplify Commands

push

### Describe the bug

When I try to run amplify push the deployment fails on `HostedUIProvidersCustomResourceInputs Custom::LambdaCallout`. The error links to a Cloud Watch log stream which shows this error

```
INFO	InvalidParameterException: client_id, client_secret and authorize_scopes are all required idp details.
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
```

### Expected behavior

The command `amplify push` should be successful. It is not even clear why a resource I did not even update locally was been updated in the deployment

### Reproduction steps

1. Create a Next.js application in the Amplify Console.
2. Add functions and/or API resources from CLI
2. Enable the Auth component with the Google provider from the Console.
4. Pull changes with CLI.
5. Make some update to function or graphql schema.
6. Attempt to push local edits and deployment will fail with the issue described above.

### GraphQL schema(s)

N/A

### Log output

<details>

```
INFO	InvalidParameterException: client_id, client_secret and authorize_scopes are all required idp details.
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
```

</details>

### Manual solution

I found issue #6880  and got the hint to look for the OAuth provider credentials in `~/.aws/amplify/deployment-secrets.json`. I confirmed that the file only had the provider name and not the credentials

```json
"<auth resource name>": {
    "hostedUIProviderCreds": "[{\"ProviderName\":\"Google\"}]"
 }
```

I then reviewed the resource CF template to figure out what the expected fields for the Google provider were. I added the `client_id` and `client_secret` fields. The end result was:

```json
"<auth resource name>": {
    "hostedUIProviderCreds": "[{\"ProviderName\":\"Google\", \"client_id\":\"<CLIENT_ID>\", \"cl
ient_secret\":\"<SECRET>\"}]"
 }
```

After applying this update to the  `~/.aws/amplify/deployment-secrets.json` the `amplify push` command was successful.

**Comment by artidata** [comment] 2021-11-27 16:25
I had the same error report but totally different reproduction step. Possibly, it was caused by upgrading to `amplify cli 7.5.3`.  It is in `cli.json` file instead of `deployment-secrets.json`. Re-running `amplify update auth` command which eventually remove the `hostedUIProviderCreds` key pair line works for me.

**Comment by ammarkarachi** [comment] 2022-02-28 22:21
This should be fixed in the latest version

**Closed** 2022-03-14 21:27 UTC
Labels: bug, auth, p1
