### ISSUE TITLE
Add error messaging when attempting to add >33 models

### ISSUE THREAD

**Issue by johnpc** [aws-amplify/amplify-cli#9431] opened 2022-01-05 17:01 UTC
### Is this feature request related to a new or existing Amplify category?

api

### Is this related to another service?

AppSync

### Describe the feature you'd like to request

Currently, there is an AppSync limitation where there is a hard cap of 100 subscriptions. Each model creates 3 subscriptions. This means apps created using amplify cli can have a maximum of 33 models. Given that this is a known limitation, we should add error messaging to users attempting to create more than 33 models, and provide guidance on collapsing the models down to 33 or fewer.

The current error message users get is not descriptive or actionable:

```
ERR: "Service: AmazonDeepdish; Status Code: 409; Error Code: ConcurrentModificationException; Request ID: aaf0773d-e100-430a-b6c4-a0bd3373a2c3; Proxy: null)
```

### Describe the solution you'd like

A human-readable and actionable error message in this case

### Describe alternatives you've considered

N/A

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cjihrig** [comment] 2022-01-25 23:45
Closing this as the issue is believed to have been fixed on the service side.

**Closed by cjihrig** 2022-01-25 23:45 UTC
Labels: bug, graphql-transformer
