### ISSUE TITLE
number of issues  in resources provisioning for me-south-1

### ISSUE THREAD

**Issue by enlife6** [aws-amplify/amplify-cli#6706] opened 2021-02-22 23:30 UTC
**Describe the bug**
There are apparently list of issues when it comes to using the me-south-1 resources :

1- I can't do "add codegen" for AppSync from that region

2- I can't find  me-south-1 my region in "Choose AWS Region " list

3- If I create AppSyncAPI on  the console and try to link datasources from other regions, I get the list of regions but me-south-1 is not even listed ....

So because of the above issues I simply can't use DynamoDB resource from that region ..!

**Amplify CLI Version**
4.44.0

**Desktop (please complete the following information):**

- OS: [e.g. Mac/Windows/Ubuntu]
- Mac
- Node Version. You can use `node -v` to check the node version on your system
- v14.15.3

**Comment by edwardfoyle** [comment] 2021-02-23 00:52
Closing as a dupe of https://github.com/aws-amplify/amplify-cli/issues/6671

**Closed by edwardfoyle** 2021-02-23 00:52 UTC
