### ISSUE TITLE
amplify mock function myPreSignup errors with: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by kjetilge** [aws-amplify/amplify-cli#4761] opened 2020-07-07 18:20 UTC
**Describe the bug**
When running ```amplify mock function myPreSignup``` on a fresh untouched PreSignup function I get the error:
```Cannot read property 'filter' of undefined```

I suspect this error came with the latest CLI version.

**Amplify CLI Version**
4.23.0

**To Reproduce**
Create an AUTH with PreSignup function then run:
```amplify mock function yourPreSignup```

**Expected behavior**
It should not result in error.

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version 10.17.0

**Comment by jhockett** [comment] 2020-07-07 19:08
Hi @kjetilge, I was able to reproduce this. Thanks for the bug report! I'll take this to the team to begin investigating the root cause.

**Comment by kjetilge** [comment] 2020-07-07 19:18
Great!😃

**Comment by jhockett** [comment] 2020-07-08 00:44
A fix has been merged and will go out in the next release

**Comment by berenddeboer** [comment] 2020-07-08 22:27
What's going on guys? All last couple of releases are broken.

**Comment by byennen** [comment] 2020-07-08 23:55
same issue after upgrading to 4.23.0; rolling back!

**Comment by arvenom** [comment] 2020-08-24 10:22
Any updates on this?

**Comment by jhockett** [comment] 2020-08-24 16:27
> Any updates on this?

The bug fix went out several versions ago. Are you still experiencing the issue @arvenom ?

**Comment by kjetilge** [comment] 2020-09-29 17:28
This is still a problem in version 4.29.3. Hope this can be fixed soon.

**Comment by kjetilge** [comment] 2020-09-29 17:36
@jhockett - could you have another look at this ?

**Comment by jhockett** [comment] 2020-09-29 18:34
Hi @kjetilge, I'm working on another project at the moment, but I will make sure the team is aware. Did this bug just re-appear in 4.29.3?

**Comment by kjetilge** [comment] 2020-09-29 19:16
> Hi @kjetilge, I'm working on another project at the moment, but I will make sure the team is aware. Did this bug just re-appear in 4.29.3?

I have not tried it in a while so I don't know.
Also if I try to run this code: 
```
// index.js
console.log('Hello')
callback(null, event);
```
I get the same error text (in red) and no "Hello"

However, if I try to update the function and give it permission to access api read, then it behaves like this:
```
amplify mock function myPreSignup
? Provide the path to the event JSON object relative to /Users/kjetilge/Lokale filer/GitHub/my/amplify/backend/function/myPreSignup src/event.json
Could not find ref for "modules". Using unsubstituted value.
Could not find ref for "DOMAINWHITELIST". Using unsubstituted value.
Could not find ref for "DOMAINBLACKLIST". Using unsubstituted value.
Starting execution...
myPreSignup failed with the following error:
Command failed with exit code 1: xx/xx/ execute.js
Hello

{"result":{"request":{"userAttributes":{"email":"testEmail@domain.com"}},"response":{}},"error":null}
Finished execution.
Hello
```

So then at least it runs, but it can't be published because it will produce a circular dependancy.

There is som sort of an instruction in the beginning og this file taht goes like this:
```
/*
  this file will loop through all js modules which are uploaded to the lambda resource,
  provided that the file names (without extension) are included in the "MODULES" env variable.
  "MODULES" is a comma-delimmited string.
*/
```

Maybe this means I somehow should provide a list of files (maybe "filter" is upposed to be used on it?).
But I don't know how to achieve that.

**Comment by akshbhu** [comment] 2020-10-01 18:42
Hi All

I have merged the fix for this and it will be available in next release. I ma closing this isssue , feel free to open if you face any concerns

**Closed by akshbhu** 2020-10-01 18:42 UTC
Labels: bug, mock
