### ISSUE TITLE
Amplify CLI install fails on node 10.15.0 also on 11

### ISSUE THREAD

**Issue by jimlack** [aws-amplify/amplify-cli#668] opened 2019-01-07 20:56 UTC
**Describe the bug**
The CLI fails to install

**To Reproduce**
MacOS Mojave v10.14.1
Node stable version v10.15.0
Npm v6.4.1

npm install -g @aws-amplify/cli
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for package

npm ERR! A complete log of this run can be found in:
npm ERR!

**Expected behavior**
A clean install

**Desktop (please complete the following information):**
 MacOS Mojave v10.14.1

**Comment by kaustavghosh06** [comment] 2019-01-07 21:03
Duplicate of #667 
This happened just a few hours back when a dependency package was unpublished from npm.
We're trying to mitigate the issue ASAP.

**Comment by kaustavghosh06** [comment] 2019-01-07 21:15
@jimlack  looks like npm put back the package "package" and I was able to install the CLI successfully again after not able to install it for the last hour. 
Guess, it was a momentary npm glitch.

**Closed by kaustavghosh06** 2019-01-07 21:15 UTC
Labels: bug
