### ISSUE TITLE
unable to 'amplify push' after 'amplify add function' with access to storage(S3) resource 

### ISSUE THREAD

**Issue by tkang** [aws-amplify/amplify-cli#6651] opened 2021-02-17 11:13 UTC
**Describe the bug**

'amplify push' fails after 'amplify add function' with access to storage, api, and auth.

It fails with following message.

```
CREATE_FAILED               functiontranslatedev3330067dnode2 AWS::CloudFormation::Stack Wed Feb 17 2021 20:00:56 GMT+0900 (Korean Standard Time) Template format error: Unresolved resource dependencies [storagetranslatedevBucketName] in the Resources block of the template
```
- It looks like there is an issue with configuring env for bucketName to be accessed by the lambda.
- I tried 'amplify add function' with access to api and auth only (e.g. excluding storage) and it works successfully.

**Amplify CLI Version**
4.44.0

**To Reproduce**

```bash
taehokan ~/Personal/translate-dev (master*) $ amplify add function
? Select which capability you want to add: Lambda function (serverless function)
? Provide an AWS Lambda function name: translatedev3330067dnode2
? Choose the runtime that you want to use: NodeJS
? Choose the function template that you want to use: Hello World

Available advanced settings:
- Resource access permissions
- Scheduled recurring invocation
- Lambda layers configuration

? Do you want to configure advanced settings? Yes
? Do you want to access other resources in this project from your Lambda function? Yes
? Select the categories you want this function to have access to. auth, api, storage
? Select the operations you want to permit on translatedev299c33b0 create, read, update, delete
? Select the operations you want to permit on translatedev Query, Mutation, Subscription
? Storage has 2 resources in this project. Select the one you would like your Lambda to access translatedev, Post:@model(appsync)
? Select the operations you want to permit on translatedev create, read, update, delete
? Select the operations you want to permit on Post:@model(appsync) create, read, update, delete

You can access the following resource attributes as environment variables from your Lambda function
	API_TRANSLATEDEV_GRAPHQLAPIENDPOINTOUTPUT
	API_TRANSLATEDEV_GRAPHQLAPIIDOUTPUT
	API_TRANSLATEDEV_POSTTABLE_ARN
	API_TRANSLATEDEV_POSTTABLE_NAME
	AUTH_TRANSLATEDEV299C33B0_USERPOOLID
	ENV
	REGION
	STORAGE_TRANSLATEDEV_BUCKETNAME
? Do you want to invoke this function on a recurring schedule? No
? Do you want to configure Lambda layers for this function? No
? Do you want to edit the local lambda function now? Yes
Please edit the file in your editor: /Users/taehokan/Personal/translate-dev/amplify/backend/function/translatedev3330067dnode2/src/index.js
? Press enter to continue
Successfully added resource translatedev3330067dnode2 locally.

Next steps:
Check out sample function code generated in <project-dir>/amplify/backend/function/translatedev3330067dnode2/src
"amplify function build" builds all of your functions currently in the project
"amplify mock function <functionName>" runs your function locally
"amplify push" builds all of your local backend resources and provisions them in the cloud
"amplify publish" builds all of your local backend and front-end resources (if you added hosting category) and provisions them in the cloud
```

```bash
⠦ Updating resources in the cloud. This may take a few minutes...
...
...

UPDATE_ROLLBACK_IN_PROGRESS amplify-translatedev-dev-150414   AWS::CloudFormation::Stack Wed Feb 17 2021 20:00:57 GMT+0900 (Korean Standard Time) The following resource(s) failed to create: [functiontranslatedev3330067dnode2].
UPDATE_COMPLETE             functiontranslatedevcee6354dnode  AWS::CloudFormation::Stack Wed Feb 17 2021 20:00:56 GMT+0900 (Korean Standard Time)

CREATE_FAILED               functiontranslatedev3330067dnode2 AWS::CloudFormation::Stack Wed Feb 17 2021 20:00:56 GMT+0900 (Korean Standard Time) Template format error: Unresolved resource dependencies [storagetranslatedevBucketName] in the Resources block of the template

UPDATE_IN_PROGRESS          functiontranslatedevcee6354dnode  AWS::CloudFormation::Stack Wed Feb 17 2021 20:00:56 GMT+0900 (Korean Standard Time)
CREATE_IN_PROGRESS          functiontranslatedev3330067dnode2 AWS::CloudFormation::Stack Wed Feb 17 2021 20:00:56 GMT+0900 (Korean Standard Time)

...
...
Following resources failed

✖ An error occurred when pushing the resources to the cloud

```

Steps to reproduce the behavior or terminal output if applicable

**Expected behavior**

'amplify push' should succeed

**Screenshots**

**Desktop (please complete the following information):**

- OS: Mac OS (Big Sur)
- Node : v15.0.1
- npm : 7.0.3

**Comment by edwardfoyle** [comment] 2021-02-17 20:18
Hi @tkang I'm unable to reproduce this starting from a new project. The steps I took were:
```sh
yes '' | amplify init
amplify add api // graphql with todo template
amplify add storage // s3, go through auth flow and select all defaults
amplify add function // grant permissions as you described above
amplify push --yes
```
The push was successful.

Can you share The contents of the "dependsOn" for the function in your `amplify-meta.json` file?

**Comment by tkang** [comment] 2021-02-18 00:48
Before 'amplify add function' with access to storage, api, and auth.

**Comment by tkang** [comment] 2021-02-18 00:56
Hi @edwardfoyle Thanks for your quick reply!

I ran 'amplify add function' with access to api and storage and the following is a part of amplify-meta.json it generated.

```
{
...

 "function": {
    "translatedevcfa7452fnode": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "api",
          "resourceName": "translatedev",
          "attributes": [
            "GraphQLAPIIdOutput",
            "GraphQLAPIEndpointOutput"
          ]
        }
      ]
    }
  }

}

```

It looks like category: storage is missing in "dependsOn"

**Comment by edwardfoyle** [comment] 2021-02-18 20:15
@tkang Yes looks like that is missing. If you run `amplify update function` and go through the flow to update resource permissions and add the table does this fix the issue? (Make sure that you leave all existing permissions selected when going through the update flow). And can you ensure that the `amplify-meta.json` file has the storage resource in it?

You can manually fix this issue by adding the following block to the "dependsOn" list for the function
```json
{
  "category": "storage",
  "resourceName": "<replace with storage resource name>",
  "attributes": [
    "BucketName"
  ]
}
```
But I'm not sure why it's not being added automatically

**Comment by tkang** [comment] 2021-02-19 17:34
@edwardfoyle Thank you again for your response.

I tried `amplify update function` and went through the steps once again but it still didn't update `amplify-meta.json` file accordingly. 

Note : With updating `amplify-meta.json` file manually, I was able to do `amplify push` successfully.

**Comment by edwardfoyle** [comment] 2021-02-19 22:19
@tkang glad that got you unblocked! I'm still unable to reproduce the behavior you're seeing though. Is there anything unique about your function or storage configuration? Can you share the entire "function" and "storage" blocks from your `amplify-meta.json` file?

**Comment by tkang** [comment] 2021-02-21 15:07
@edwardfoyle Here is my `amplify-meta.json` file after I did `amplify add function` with access to storage and api. Please note this file is before I manually added a category = storage block in "dependsOn" 

```
"storage": {
    "translatedev": {
      "service": "S3",
      "providerPlugin": "awscloudformation",
      "providerMetadata": {
        "s3TemplateURL": "https://s3.amazonaws.com/amplify-translatedev-dev-150414-deployment/amplify-cfn-templates/storage/s3-cloudformation-template.json",
        "logicalId": "storagetranslatedev"
      },
      "lastPushTimeStamp": "2021-02-21T15:01:40.066Z",
      "output": {
        "BucketName": "translatedev7c1ca49bfadd4025955ed7321f8eca10150414-dev",
        "Region": "ap-northeast-2"
      },
      "lastPushDirHash": "Ho8oYfJH+LLHdbuqKZi5p/7Od24="
    }
  },
  "function": {
    "translatedev2b19aebf": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "api",
          "resourceName": "translatedev",
          "attributes": [
            "GraphQLAPIIdOutput",
            "GraphQLAPIEndpointOutput"
          ]
        }
      ]
    }
  }
```

**Comment by tkang** [comment] 2021-02-23 09:09
@edwardfoyle I think this issue has got something to do with the order amplify resources get added and pushed with 'amplfy add' and 'amplify push' commands. In another project, api category gets missing in 'dependsOn'. 

Here are the steps I took
amplify add storage => amplify push => amplify add api => amplify push
amplify add function (with access to storage and api) => check amplify-meta.json file 

```
"function": {
    "awsaimldemoe5ef67f6rekognition": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "storage",
          "resourceName": "awsaimldemo",
          "attributes": [
            "BucketName"
          ]
        }
      ]
    }
  }
```

I hope this helps :-)

**Comment by edwardfoyle** [comment] 2021-03-04 21:30
@tkang Thanks for the detailed steps. Interestingly, I wasn't able to repro this with storage and api as you described above but I was able to repro when trying to add analytics as a dependency of a function. So there's definitely something going on here. Marking as a bug and we will investigate further.

**Closed** 2021-05-07 17:38 UTC
Labels: bug, functions
