### ISSUE TITLE
Appsync console then integrate using Amplify CLI gives error on `amplify add codegen --apiID xxxxxxxx` with UnexpectedToken o

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-cli#2472] opened 2019-10-01 22:12 UTC
**Describe the bug**
When I create a new app using AppSync Console, and then I create a new iOS app locally, and follow the steps to `amplify init` and then codegen, it fails with an error "Unexpected token o in JSON at position 1"

**To Reproduce**
Set up:
- Amplify CLI version 3.9.0

1. Went to AppSync console
2. Clicked on Create API -> under Start from a sample project, select Event App. -> Start
3. Clicked on the name of the Project on the left side.
4. The instructions for iOS says
```
npm install -g @aws-amplify/cli // skipped this step
amplify init // did this
amplify add codegen --apiId xxxxxxxxxxxxxxxxxxxx // fails here
amplify codegen // amplify is broken here already, does not recognize that an amplify project
````
and there is a button to download the Config.

When I ran `amplify add codegen --apiID xxxxxxxxxxx` , I got the error 
```
✔ Getting API details
✖ Getting API details
Unexpected token o in JSON at position 1
```

Can you provide some guidance on how I can successfully codegen the app I made in AppSync console?

So what I think what is happening here is inconsistency between the AppSync Console version of Amplify CLI and the Amplify CLI version I have installed (3.9.0).
If this is true, where/how do I keep this in sync?

**Expected behavior**
Expected code to have been generated for the AppSync scheme

**Desktop (please complete the following information):**
 - OS: iOS 13
 - Amplify CLI Version  3.9.0
 - AppSync console - Not sure where to check

Thanks,
Michael

**Comment by nikhname** [comment] 2019-10-01 22:38
This is a duplicate of #2360. The fix has been merged and released version 3.10.0. Feel free to re-open/comment if you're still experiencing with this version.

**Closed by nikhname** 2019-10-01 22:38 UTC
Labels: code-gen, duplicate
