### ISSUE TITLE
Amplify update auth - does not work

### ISSUE THREAD

**Issue by nadzic** [aws-amplify/amplify-cli#13078] opened 2023-08-05 06:22 UTC
### How did you install the Amplify CLI?

sudo npm install amplify

### If applicable, what version of Node.js are you using?

v18.17.0

### Amplify CLI Version

12.2.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

My deployment on amplify just started failing and here is the log:

...
2023-07-30T11:18:06.435Z [INFO]: 🛑 Auth triggers have been configured using an older version of the CLI and must be migrated before they can be deployed.
2023-07-30T11:18:06.435Z [INFO]: Resolution: Run "amplify update auth" and select "yes" to the migration prompt. Then retry the deployment using "amplify push".
                                 Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
2023-07-30T11:18:06.444Z [INFO]: 
2023-07-30T11:18:06.445Z [INFO]: Session Identifier: 0a412122-199f-4361-a578-78e3ea30012c
2023-07-30T11:18:06.469Z [ERROR]: !!! Build failed
2023-07-30T11:18:06.469Z [ERROR]: !!! Non-Zero Exit Code detected
2023-07-30T11:18:06.469Z [INFO]: # Starting environment caching...
2023-07-30T11:18:06.469Z [INFO]: # Uploading environment cache artifact...
2023-07-30T11:18:06.540Z [INFO]: # Uploaded environment cache artifact
2023-07-30T11:18:06.540Z [INFO]: # Environment caching completed
Terminating logging...

It looks like `amplify update` needs to be done, but when I run it, I get following error:

`Error updating the Cognito trigger: The "path" argument must be of type string. Received undefined`

### Expected behavior

Amplify update needs to work normally, so right now we cannot update triggers.

### Reproduction steps

1. Run sudo amplify update auth
2. Select: Apply default configuration without Social Provider (Federation)
3. Enter URL, Subject, Body Text

and gets error:

Error updating the Cognito trigger: The "path" argument must be of type string. Received undefined

### Project Identifier

Project Identifier: 277e04d4c8c29e7767a630177599f562

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment] 2023-08-07 19:30
Hey @nadzic :wave: thanks for raising this! While we begin to look at this in more depth I have a few follow-up questions:

- if you add `--debug` to the command, does it print a stack trace? If so, can you share that here?
- does the outcome of the command change if you run without `sudo`?

**Comment by nadzic** [comment] 2023-08-16 15:50
Hi @josefaidt thanks for coming back.

- Adding `--debug` I get the same error? You mean adding --debug when running: `amplify update auth --debug`, or something like this?
- We also tried without sudo, the same thing
- I'm not sure how to check from what version I'm migrating from - Could you collaborate on this? I'm currently using version: `12.2.3`

**Comment by nadzic** [comment] 2023-08-16 15:53
Tried to update to 12.2.5, but still getting this one for example:

<img width="949" alt="Screenshot 2023-08-16 at 17 52 15" src="https://github.com/aws-amplify/amplify-cli/assets/6192073/cb4ad26e-d1cd-4d51-85e0-a65f2b77fe16">

**Comment by josefaidt** [comment] 2023-08-18 17:08
Hey @nadzic ,

> Adding --debug I get the same error? You mean adding --debug when running: amplify update auth --debug, or something like this?

Yes

> I'm not sure how to check from what version I'm migrating from - Could you collaborate on this? I'm currently using version: 12.2.3

Apologies for the confusion. I see this line from the pasted output in the original report

```
2023-07-30T11:18:06.435Z [INFO]: Resolution: Run "amplify update auth" and select "yes" to the migration prompt. Then retry the deployment using "amplify push".
```

Which leads me to believe auth was originally created with CLI <v7, and needs to be migrated. Are you able to run `amplify update auth` to migrate? Although looking at the screenshot in your latest comment it does not appear to prompt you.

**Comment by nadzic** [comment] 2023-08-20 07:13
Hi @josefaidt, thanks for helping with this. 

Yes it is opening prompt, but then it crashes.

Would you mind to jump on a quick google hangouts next week? Maybe just share time and email and I'm going to send you an invite.

We're blocked with deployment. 😐

**Comment by josefaidt** [comment] 2023-08-23 19:22
Hey @nadzic thanks for hopping on a call with me yesterday! To recap, there was a partially migrated auth resource due to the error experienced in the original report. We removed the partial migration's files (including `cli-inputs.json`, etc.), downgraded CLI versions to 11.0.3 and redeployed with Hosting.

Marking as investigating for the failed migration

**Comment by josefaidt** [comment] 2023-10-03 19:10
Hey @nadzic apologies for the delay here, but unfortunately I have not been able to reproduce this migration issue. I'll close this issue for now since we were able to find a suitable workaround, however will keep this in mind in the event another report arises.

**Closed by josefaidt** 2023-10-03 19:10 UTC
Labels: investigating, auth, pending-triage
