### ISSUE TITLE
Amplify pull brings back deleted functions

### ISSUE THREAD

**Issue by kldeb** [aws-amplify/amplify-cli#8625] opened 2021-11-02 00:48 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v12.13.0

### Amplify CLI Version

6.3.1

### What operating system are you using?

mac

### Amplify Categories

auth, storage, function, api

### Amplify Commands

pull

### Describe the bug

We trimmed down our codebase to remove functionality that is going out in the next release of our product. We removed multiple functions. When we run `amplify pull` two of the functions are added back to the project and schema changes (`@key` directives) are changed to what appears to be a precious version

### Expected behavior

amplify pull does not bring back resources and code that was removed. 

### Reproduction steps

1. create and amplify project, 
2. add functions
3. amplify push
4. delete function
5. amplify push
6. amplify pull
7. see deleted function come back

At least that is what is happening in this project. 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by johnpc** [comment] 2022-01-14 21:43
I was not able to reproduce this issue. Are you deleting the function with `amplify remove function`?

**Comment by josefaidt** [comment] 2022-01-21 20:06
Hey @kldeb are you still experiencing this issue? If so, to echo @johnpc 's comment above how are you deleting the functions?

**Comment by kldeb** [comment] 2022-01-21 21:49
yes, deleting functions using `amplify remove function`

**Comment by jhockett** [comment] 2022-01-27 00:29
@kldeb were the deleted functions deployed with the CLI directly or via CI/CD?

**Comment by kldeb** [comment] 2022-01-27 20:43
cli

**Comment by jhockett** [comment] 2022-01-27 22:23
@kldeb do you see the deleted functions present in the Lambda Console for the given environment?

**Comment by brandonfonseca** [comment] 2022-02-23 06:25
Hello,

I am also having this issue! Is there any fix yet?

The functions are removed from my code and removed from the cloud (I checked Cloudformation and Lambda on the AWS Console and these functions are gone). However, every time that I perform an `amplify pull` these lambda functions come back into my code (under `src/backend/function`). This is a pretty breaking issue.

Thanks!

**Comment by jhockett** [comment] 2022-02-23 19:12
Hi @brandonfonseca, we haven't been able to reproduce the issue so unfortunately no update yet. Do you remember how you initially created the functions? What steps did you take to remove the functions from your project?

**Comment by brandonfonseca** [comment] 2022-02-23 20:21
Hi @jhockett, thanks for the response. The functions were initially created using `amplify function add` and were removed using `amplify function remove` as per the documentation instructions.

**Comment by jhockett** [comment] 2022-02-23 23:06
@brandonfonseca can you send us your `amplify/` folder at amplify-cli@amazon.com so that we can investigate? Please include the issue number in the title and be sure to redact anything sensitive.

**Comment by biller-aivy** [comment] 2022-03-13 22:05
There Are some Files in the s3 deployment Buckets which brings some old Functions back. You have to find an delete this Files, than it's fixed.

**Comment by josefaidt** [comment] 2022-04-11 19:40
Hey @kldeb :wave: are you still experiencing this issue?

**Comment by kldeb** [comment] 2022-04-26 14:19
We are no longer using amplify to deploy our back end.

**Comment by josefaidt** [comment] 2022-05-23 20:30
I attempted to reproduce this again by using the Amplify Hosting CI/CD pipeline and git-connected workflow to no avail. Folks in the thread if you are still experiencing this issue and are able to provide minimal reproduction steps we can re-open this issue to investigate further, however I will close this for now.

**Closed by josefaidt** 2022-05-23 20:30 UTC
Labels: pending-triage, not-reproducible, platform-pull
