### ISSUE TITLE
Ability to reindex Elastic Search from CLI

### ISSUE THREAD

**Issue by GeorgeBellTMH** [aws-amplify/amplify-cli#5422] opened 2020-09-27 20:14 UTC
It would be nice if we had ability to reindex the Elastic search indexes from the CLI:

Suggested command:

amplify api --reindex [modelName|all]

Process would be do:
1) Create new indexes from existing amplify table (option is available to do all, or specific models)
2) Some sort of sanity check to ensure there are the correct number of items
3) Swap/Rename the indexes in elastic search
4) Delete the old index

(Created in response to comments in: #78)

**Comment by SwaySway** [comment] 2020-10-05 22:02
@GeorgeBellTMH One way to do this today would be to delete that index and back fill. We have a sample backfill script here: https://docs.amplify.aws/cli/graphql-transformer/directives#backfill-your-elasticsearch-index-from-your-dynamodb-table

We do have a feature request open for making sure that a user of the CLI has the option to re-index the cluster when changing types for example. Please follow this issue for updates: https://github.com/aws-amplify/amplify-cli/issues/3340

Closing this issue as a duplicate of #3340

**Closed by SwaySway** 2020-10-05 22:02 UTC
Labels: @searchable, enhancement

**Comment by GeorgeBellTMH** [comment] 2020-10-05 22:07
I know about the script, this ticket was to make the script part of the cli since this is a thing that occasionally users of the cli need to do when things break...downloading and installing a bunch of other dependencies and configuration seems like a bad user experience when it could all just be done via the cli.
