### ISSUE TITLE
amplify init does not initialize a cloud project in Amplify Console when using region eu-north-1

### ISSUE THREAD

**Issue by micsafi** [aws-amplify/amplify-cli#5521] opened 2020-10-08 06:15 UTC
**Describe the bug**
`amplify init` does not initialize a cloud project in AWS Amplify Console when using a AWS profile which has a default region as eu-north-1. 

**Amplify CLI Version**
4.29.4

**To Reproduce**
1. Create a AWS profile which is has a default region of eu-north-1. This profile needs to be created manually because`aws configure` does not support region eu-north-1 (see issue [5513](https://github.com/aws-amplify/amplify-cli/issues/5513)).
2. Run `amplify init` without options in our project.
3. When prompted, select the AWS profile you created in step 1.
4. Once init has finished, go to Amplify Console and check that the cloud project is not  there.

**Expected behavior**
The `init` should initialize a cloud project  in Amplify console when used in any region which supports Amplify (like eu-north-1).

**Desktop (please complete the following information):**
 - OS: macOS Catalina v. 10.15.6 (19G2021)
 - node version 14.13.0

**Additional context**

**Comment by kaustavghosh06** [comment] 2020-10-08 06:36
Closing as duplicate of #5513

**Closed by kaustavghosh06** 2020-10-08 06:36 UTC

**Comment by micsafi** [comment] 2020-10-08 06:53
@kaustavghosh06 If you look at the issue description, this is a different issue from #5513. They are both linked to same region, but the issue itself is different and could require complete different fix.

**Comment by kaustavghosh06** [comment] 2020-10-08 07:16
@micsafi The reason/root-cause is the same for both the issues. We do not officially support "eu-north-1" region with the Amplify CLI just yet. Once we officially support it, both the issues you've opened would be resolved.

**Comment by micsafi** [comment] 2020-10-08 07:19
> @micsafi The reason/root-cause is the same for both the issues. We do not officially support "eu-north-1" region with the Amplify CLI just yet. Once we officially support it, both the issues you've opened would be resolved.

OK, thanks for the clarification!
