### ISSUE TITLE
PostConfirmation Add User to Group trigger has inadequate IAM role permissions

### ISSUE THREAD

**Issue by BruceWheaton** [aws-amplify/amplify-cli#8012] opened 2021-08-23 18:34 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### Amplify CLI Version

5.3.0

### What operating system are you using?

Windows

### Amplify Categories

auth

### Amplify Commands

add

### Describe the bug

When a postconfirmation trigger is adding by going through a manual auth configuration, the lambda does get created (I got hit by the async bug in this area a month or so ago), a lambda is created, it is correctly assigned to the cognito trigger, and everything else seems fine, but the created IAM role does not have access to the cognito pool ARN.

### Expected behavior

The created IAM role should have an extra role with something like:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "cognito-idp:CreateGroup",
                "cognito-idp:AdminAddUserToGroup",
                "cognito-idp:GetGroup"
            ],
            "Resource": "arn:aws:cognito-idp:us-west-etc"
        }
    ]
}

### Reproduction steps

Create a new amplify project
Define 1-n groups
amplify add auth, manual, 
select add postconfirmation trigger, add to group, pick a group

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by pjsandwich** [comment] 2021-08-24 15:58
I'm also having this issue. The sign up flow works, but I don't receive the confirmation email, user is UNCONFIRMED in the cognito user pool. While attempting to manually confirm the user as an experiment to learn more about the issue, I receive this error:

```
PostConfirmation failed with error User: arn:aws:sts::<number>:assumed-role/<userpool>PostConfirmation-dev/<userpool>PostConfirmation-dev is not authorized to perform: cognito-idp:CreateGroup on resource: arn:aws:cognito-idp:us-west-2:<number>:userpool/us-west-2_<key>. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: UserLambdaValidationException; Request ID: <req_id>; Proxy: null)
```

While the user still doesn't receive the confirmation email and the error indicates that manually confirming the user failed, when I go back to the user pool the user is CONFIRMED, and contrary to what the [amplify docs advertise](https://docs.amplify.aws/cli/usage/lambda-triggers/#add-user-to-group), a cognito group is not created and the user is not added to any group.

**Comment by attilah** [comment] 2021-08-24 20:19
Duplicate of #7582

**Closed by attilah** 2021-08-24 20:19 UTC
Labels: auth, duplicate

**Comment by pjsandwich** [comment] 2021-08-25 13:06
@BruceWheaton, that would be great, still unsure what the fix is
