### ISSUE TITLE
lambda trigger not working 

### ISSUE THREAD

**Issue by nwokdean** [aws-amplify/amplify-cli#9838] opened 2022-02-23 16:09 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

 4.3.14

### What operating system are you using?

windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

CORs added 

### Amplify Categories

auth, storage, api, hosting, notifications

### Amplify Commands

env

### Describe the bug

My lambda function is not triggering once a file has been loaded to the app and placed in s3. 

### Expected behavior

Function should automatically trigger 

### Reproduction steps

Loading a file
Looking in s3, 
Triggering lambda 

(might be something in python) because in UAT we have tested and it works. Also, manually triggering lambda runs the project perfectly.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

nothing 

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

No additional information

**Comment by sachscode** [comment] 2022-02-25 20:03
Hi @nwokdean 
Please visit the AWS S3 console for your S3 bucket and navigate to the "Event Notifications" section of the page. Here, could you please confirm if there is a lambda trigger configured for all object creation/removal events .

**Comment by nwokdean** [comment] 2022-03-03 22:30
Yes, we checked, and it is there. When we run automation manually, this is the error recieved: 
{ "status": "Error", "data": { "errors": [ { "errorType": "UnauthorizedException", "message": "Permission denied" } ] } } 

Payload: 
{"action": "query","input":{"id": "3ac1c3c5-4960-4bcc-a170-05560f6868cf"},"query": "GET_QUEUE_DETAILS"} 

Queue ID: 3ac1c3c5-4960-4bcc-a170-05560f6868cf 

Error Message:

**Comment by ykethan** [comment] 2022-03-24 15:27
Hey @nwokdean just wanted to follow-up on this one and see if you could share me the information.

**Comment by ykethan** [comment] 2022-03-25 13:57
Confirmed the issue was occurring due to the parameters to the Lambda function.
closing the issue, please do reach out to us again.

**Closed by ykethan** 2022-03-25 13:57 UTC
Labels: storage, pending-close-response-required, pending-triage
