### ISSUE TITLE
Mocking functions that depends on Lambda Layers

### ISSUE THREAD

**Issue by rafaelfaria** [aws-amplify/amplify-cli#10854] opened 2022-08-07 06:03 UTC
### Is this related to another service?

cli

### Describe the feature you'd like to request

I understand today there is no way to test the lambda layers locally, but the experience of developing lambda functions where you have 25 and all of them depend on layers, it's painful.

I would love to understand if there is anything in the roadmap to help developers to overcome this challenge. 

Every time I made a change, I need to push it to the environment to test it, and despite the push takes almost 15 min now. Meaning it's HARD to do any testing and make sure that things won't break.

### Describe the solution you'd like

Being able to mock the functions and test it as it would work in the cloud.

### Describe alternatives you've considered

As mentioned in the description, in order to test, I actually need to push it to the cloud and hope things work. 
I have been writing unit tests to try minimise the regression issues and get confidence in order to test.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment] 2023-01-31 21:19
Marking as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/4826, and closing in favor of tracking the existing item

**Closed by josefaidt** 2023-01-31 21:19 UTC
Labels: functions, feature-request, duplicate, p3
