### ISSUE TITLE
'amplify init' UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by sar** [aws-amplify/amplify-cli#6681] opened 2021-02-19 17:53 UTC
**Describe the bug**
`yarn` variant of `@aws-amplify/cli` does not render `type: string[]` options of `amplify init` command and throws  exception `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined`

**Amplify CLI Version** `4.44.0`

**To Reproduce**
```bash
> amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project amplifycliaction
? Enter a name for the environment prod
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building       # List is not propagated to the terminal

(node:540213) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
    at ListPrompt.getCurrentValue (/usr/local/share/.config/yarn/global/node_modules/inquirer/lib/prompts/list.js:148:53)
    at MapSubscriber._next (/usr/local/share/.config/yarn/global/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/usr/local/share/.config/yarn/global/node_modules/rxjs/internal/Subscriber.js:66:18)
    at TakeSubscriber._next (/usr/local/share/.config/yarn/global/node_modules/rxjs/internal/operators/take.js:54:30)
    at TakeSubscriber.Subscriber.next (/usr/local/share/.config/yarn/global/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Interface.handler (/usr/local/share/.config/yarn/global/node_modules/rxjs/internal/observable/fromEvent.js:22:28)
    at Interface.emit (events.js:326:22)
    at Interface.EventEmitter.emit (domain.js:483:12)
    at Interface._onLine (readline.js:329:10)
    at Interface._line (readline.js:658:8)
(node:540213) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:540213) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Expected behavior**
``? Choose the type of app that you're building       # List is not propagated to the terminal``

CLI option should render list of application types for selection but throws an unhandled exception. Issue is only replicable when installed with `yarn global`.

**Desktop (please complete the following information):**
- OS: `ubuntu, kernel 5.8.18`
- Node Version. `v12.20.2`

**Log output**
```log
2021-02-19T17:38:18.211Z|info : amplify status core  
2021-02-19T17:42:14.779Z|info : amplify init core  
2021-02-19T17:46:49.339Z|info : amplify version core  {"version":true,"yes":false}
```

**Comment by yuth** [comment] 2021-02-19 19:40
@sar is the Amplify CLI installed globally by using the following yarn command 
```
yarn global add @aws-amplify/cli
```

**Comment by sar** [comment] 2021-02-19 19:54
> @sar is the Amplify CLI installed globally by using the following yarn command
> 
> ```
> yarn global add @aws-amplify/cli
> ```

Correct. I was able to replicate on multiple new containers, installed with `yarn` (clean caches) but not `npm`. Seems like a dependency is getting missed.

**Comment by yuth** [comment] 2021-02-19 20:06
Could you share the `plugin.json` file which should be located in `<home-dir>/.amplify/plugins.json`

**Comment by sar** [comment] 2021-02-19 20:17
> Could you share the `plugin.json` file which should be located in `<home-dir>/.amplify/plugins.json`

```json
{
  "pluginDirectories": [
    "cli-local-node-modules",
    "cli-parent-directory",
    "global-node-modules"
  ],
  "pluginPrefixes": [
    "amplify-"
  ],
  "userAddedLocations": [],
  "lastScanTime": "2021-02-18T14:35:35.277Z",
  "maxScanIntervalInSeconds": 86400,
  "plugins": {
    "core": [
      {
        "packageName": "@aws-amplify/cli",
        "packageVersion": "4.44.0",
        "packageLocation": "/usr/local/share/.config/yarn/global/node_modules/@aws-amplify/cli/",
        "manifest": {
          "name": "core",
          "type": "core",
          "commands": [
            "categories",
            "configure",
            "console",
            "delete",
            "env",
            "help",
            "init",
            "logout",
            "migrate",
            "plugin",
            "publish",
            "push",
            "pull",
            "run",
            "status",
            "uninstall",
            "upgrade",
            "version"
          ],
          "commandAliases": {
            "h": "help",
            "serve": "run",
            "ls": "status"
          }
        }
      }
    ]
  },
  "excluded": {}
}
```

**Comment by yuth** [comment] 2021-02-19 20:26
From the `plugin.json` it looks like the CLI is not able to find the plugins needed by CLI. What version of yarn do you have running?

**Comment by attilah** [comment] 2021-02-20 00:10
While waiting on a response I found the root cause with @yuth, which is the CLI cannot find any registered frontend plugins, which probably means a corrupt or unsupported installation of the CLI. Creating a PR for the better DX for this case.

**Comment by volkanunsal** [comment] 2021-02-24 01:45
@attilah I tried your code changes in my environment, but they don't work for me. It just stops with a different error now.

![Screen Shot 2021-02-23 at 8 43 53 PM](https://user-images.githubusercontent.com/151600/108932825-02035e80-7618-11eb-9f20-ccba5b9843a3.png)

**Comment by attilah** [comment] 2021-02-24 05:35
@volkanunsal the PR was solving the problem of giving a better error message instead of the stacktrace hell as it comes from a dependency. Your problem is something local.

As @yuth asked can you tell what version of `yarn` are you using? We only testing/supporting yarn classic (1.x) at the moment.

Could you remove the CLI from yarn global and try to give it a go and tell us what is the result:
```sh
$ npm install -g @aws-amplify/cli
$ amplify plugin scan

And then check what is in `plugin.json` and if amplify works or not.

**Comment by volkanunsal** [comment] 2021-02-24 12:11
Ah, ok. I figured the problem might be with `yarn`. I'll just use `npm` for the time being. Thanks.

**Comment by attilah** [comment] 2021-02-24 16:03
Closing the issue as it is solved for customer.

**Closed by attilah** 2021-02-24 16:03 UTC
Labels: pending-response, pending-triage, platform
