### ISSUE TITLE
Adding model triggers to Lambda 

### ISSUE THREAD

**Issue by lseemann** [aws-amplify/amplify-cli#7106] opened 2021-04-15 20:27 UTC
**Is your feature request related to a problem? Please describe.**
After creating a [DynamoDB Lambda trigger](https://docs.amplify.aws/cli/usage/lambda-triggers#dynamodb-lambda-triggers), there does not appear to be a way to add additional models as triggers. I am stuck with the models I selected when creating the function.

**Describe the solution you'd like**
`amplify function update` should, when applied to a Dynamo DB Lambda function, prompt the user to add or subtract from the graphql model(s) that will trigger the Lambda.

**Describe alternatives you've considered**
Manually edit the `*-cloudformation-template.json` for the trigger, but that is hazardous and likely to be overwritten in the future.

**Comment by jhockett** [comment] 2021-04-15 20:37
Hi @lseemann, thanks for filing this! I'm marking this as an enhancement because this builds on an existing feature.

**Comment by jhockett** [comment] 2021-04-19 22:52
Hi @lseemann, I didn't realize, but this is a duplicate of https://github.com/aws-amplify/amplify-cli/issues/6883. Closing this issue, please follow along 6883 for further updates.

**Closed by jhockett** 2021-04-19 22:52 UTC
Labels: enhancement, functions
