### ISSUE TITLE
why will Category Providers be deleted?

### ISSUE THREAD

**Issue by cyrfer** [aws-amplify/amplify-cli#5340] opened 2020-09-16 20:12 UTC
I am nervous to deploy with `amplify push` since `DELETE` just appeared and I have no idea why. I'm not sure what caused this. I recently upgraded the CLI version, as well as created a new environment, but now I have my original environment checked out again.

I see this:

```bash
$ amplify status
Scanning for plugins...
Plugin scan successful

Current Environment: dev

| Category  | Resource name   | Operation | Provider plugin   |
| --------- | --------------- | --------- | ----------------- |
| Function  | l12nAPI         | Update    | awscloudformation |
| Providers | categories      | Delete    |                   |
```

**Which Category is your question related to?**
Providers

**Amplify CLI Version** 
4.29.2

**What AWS Services are you utilizing?**
many

**Provide additional details e.g. code snippets**

**Comment by renebrandel** [comment] 2020-09-16 20:22
@cyrfer - can I just confirm the rough workflow you've went through to reach this state?
1. `amplify init`
2. `amplify add function`
3. `amplify push`
4. `amplify update function`
5. `amplify push`

**Comment by cyrfer** [comment] 2020-09-16 20:24
@renebrandel yes, but with the extra env i mentioned:

1. amplify init (dev)
2. amplify add X/Y/Z
3. amplify push/publish
4. amplify env add (dev2)
5. amplify push
6. amplify env checkout dev
7. amplify status

**Comment by UnleashedMind** [comment] 2020-09-16 20:25
Did you manually update the amplify-meta.json file in the `amplify/backen` folder?

**Comment by cyrfer** [comment] 2020-09-16 20:25
no

**Comment by renebrandel** [comment] 2020-09-16 20:28
thanks we're trying to repro it. In the example above, we see it's happening with functions. Does this also apply with other categories?

**Comment by cyrfer** [comment] 2020-09-16 20:31
@renebrandel I do use one function for my graphql api.

**Comment by UnleashedMind** [comment] 2020-09-16 20:51
Not able to reproduce with only the function category added. 
Could you send us (amplify-cli@amazon.com) a copy of these files so we can investigate further?

`amplify/#current-cloud-backend/amplify-meta.json`
`amplify/#current-cloud-backend/backend-config.json`
`amplify/backend/amplify-meta.json`
`amplify/backend/backend-config.json`
`amplify/team-provider-info.json`

**Comment by nikhname** [comment] 2020-09-16 21:36
@cyrfer A zip file of your project sent to amplify-cli@amazon.com would also be useful to help us reproduce this.

**Comment by cyrfer** [comment] 2020-09-16 21:38
I'll email the files. I'm not comfortable providing a zip of an entire application.

**Comment by cyrfer** [comment] 2020-09-16 22:00
I sent the files.

One more idea, my memory is fuzzy but this might be closer to what I did:

1. cd PROJECT && amplify init (dev)
2. amplify add X/Y/Z
3. amplify push/publish
4. cd .. && git clone git+ssh://PROJECT PROJECT2 && cd PROJECT2
5. amplify env add (dev2)
6. amplify push
7. amplify env checkout dev
8. cd ../PROJECT && amplify status. (back in original clone)

**Comment by UnleashedMind** [comment] 2020-09-16 22:15
could you explain what step 4 is for?
we noticed there's a "security" category in the files, is that an in-house plugin that your team is using?
The `providers` field in the `#current-cloud-backend/amplify-meta.json` file incorrectly has the contents of the `providers` field in the `team-provider-info.json` file, it might have been incorrectly copied over in some custom scripts.

**Comment by cyrfer** [comment] 2020-09-16 22:59
@UnleashedMind the "security" category not a plugin, its just a make-believe category (a folder) so I could add my own cloudformation template, which makes a SecurityGroup resource.

I don't have any custom scripts that are modifying these files.

I did notice that the git diff shows a ton of whitespace modifications. I'm guess that's your scripts, not mine. Maybe I overlooked a line that was removed since the whitespace diff was so noisy.

How can I fix it?

**Comment by cyrfer** [comment] 2020-09-16 23:10
@UnleashedMind step 4,
> cd .. && git clone git+ssh://PROJECT PROJECT2 && cd PROJECT2

 was because I had a lot of local changes in my clone and I needed a quick way to test running `amplify publish` because S3 did not contain the react code I expected my users to see. 

Now that I think about it, I probably have 4 & 5 reversed. I probably did something like *this:

1. cd PROJECT && amplify init (dev)
2. amplify add X/Y/Z
3. amplify push/publish
4. *amplify env add (dev2)
5. *amplify push
6. *cd .. && git clone git+ssh://PROJECT PROJECT2 && cd PROJECT2
7. *amplify init (dev)
8. *cd ../PROJECT && amplify env checkout dev
9. amplify status. (back in original clone)

I ended up not chickening out using `amplify publish` in the extra clone because I was worried it could do more damage than good right before a demo. I'm going to delete the extra clone now.

I mentioned this extra clone because I'm not sure if it could impact the other clone. I don't see why it would but maybe it could.

**Comment by UnleashedMind** [comment] 2020-09-16 23:19
Please check your email, let's set up a meeting and find the best way to restore your project.

**Comment by cyrfer** [comment] 2020-09-17 00:30
I just got back to working on this after some meetings.

I did the following and now my project looks normal.

1. git stash pop (undo from 5b above)
2. amplify env checkout charmodel (charmodel=dev2 from above)

I noticed that `amplify env list` depends on the files locally, not what is defined in the cloud, which is kind of nice since I don't care about Amplify Console, but it a little confusing when compared to other parts of Amplify.

For example, before `git stash pop` (reinstating my stashed changes) I saw this:

```bash
$ amplify env list

| Environments |
| ------------ |
| *dev          |
| qa           |
| prod         |
```

and after `git stash pop` & `amplify env checkout charmodel` I see the new environment I expected (charmodel=dev2 from above)

```bash
$ amplify env list

| Environments |
| ------------ |
| dev          |
| qa           |
| prod         |
| *charmodel   |
```

I'm no longer in fear of the deploy behavior as I don't see the word `Delete` on the status feedback. I'm glad I hesitated as I have no idea what would have happened.

@UnleashedMind @renebrandel Thanks for the great support. We can close this issue if you like. Feel free to reach out if you have more questions. I'll update this ticket if there is unexpected behavior related to it, but I am hopeful there won't be.

```$ amplify status

Current Environment: charmodel

| Category | Resource name   | Operation | Provider plugin   |
| -------- | --------------- | --------- | ----------------- |
| Security | l12n            | No Change | awscloudformation |
| Api      | l12n            | No Change | awscloudformation |
| Function | l12nAPI         | No Change | awscloudformation |
| Hosting  | S3AndCloudFront | No Change | awscloudformation |
```

**Comment by UnleashedMind** [comment] 2020-09-17 00:40
I'm glad your project is back to normal. 
I'm going to close the issue now. Feel free to open another issue if needed.

**Comment by cyrfer** [comment] 2020-09-17 19:35
@UnleashedMind @renebrandel 

FYI, when I tried to migrate my feature environment into my dev environment, I got the scary message again. I would love to know how to fix it.

1. amplify env add charmodel
2. amplify push
3. amplify env checkout dev
4. amplify status

```bash
$ amplify status

Current Environment: dev

| Category  | Resource name   | Operation | Provider plugin   |
| --------- | --------------- | --------- | ----------------- |
| Api       | l12n            | Update    | awscloudformation |
| Function  | l12nAPI         | Update    | awscloudformation |
| Providers | categories      | Delete    |                   |
| Security  | l12n            | No Change | awscloudformation |
| Hosting   | S3AndCloudFront | No Change | awscloudformation |
```

**Comment by cyrfer** [comment] 2020-09-17 21:20
I was able to navigate the latest scare using `amplify pull`, like this:

amplify env add (charmodel)
amplify push
amplify env checkout dev
amplify status (scared me)
amplify pull
amplify status (no longer scared, but git showed changes)
git checkout -- .
amplify push (to change dev)

**Comment by hisham** [comment] 2020-09-18 04:25
I'm getting this as well: 


```
| Category  | Resource name                             | Operation | Provider plugin   |
| --------- | ----------------------------------------- | --------- | ----------------- |
| Function  | <readact>                              | Update    | awscloudformation |
| Function  | <readact>          | Update    | awscloudformation |
| Function  | <readact>            | Update    | awscloudformation |
| Function  |<readact>                      | Update    | awscloudformation |
| Function  | <readact>         | Update    | awscloudformation |
| Function  | <readact>         | Update    | awscloudformation |
| Function  | <readact> | Update    | awscloudformation |
| Providers | categories                                | Delete    |                   |
| Api       | <readact>                           | No Change | awscloudformation |
| Api       | <readact>                      | No Change | awscloudformation |
| Auth      | <readact>                            | No Change | awscloudformation |
```

**Comment by hisham** [comment] 2020-09-18 04:38
@UnleashedMind I just sent my files as well if amplify cli wants to investigate further. 

The only common thing I see between me and @cyrfer is I was also using git stash I believe and switching between branches. But wasn't trying to do anything out of the ordinary...

**Comment by hisham** [comment] 2020-09-18 04:42
Doing `amplify pull` in root dir resolved it for me.

**Comment by cyrfer** [comment] 2020-09-18 08:11
@UnleashedMind @renebrandel 
Ug this is so frustrating. I keep getting into situations where amplify says it will delete the Providers category. This time all I did was add more [customCF](https://docs.amplify.aws/cli/usage/customcf). Fine, I finally let amplify win and hopefully this Provider category is gone forever now. Please explain what can be done to remedy this if I did something wrong.

After allowing amplify to delete the Providers category, I (re)added my [customCF](https://docs.amplify.aws/cli/usage/customcf), but `amplify push` won't recognize the new template, which is a [problem I've faced before](https://github.com/aws-amplify/amplify-cli/issues/4006) but using `amplify pull` & then editing `backend-config.json` still shows no changes and `amplify push` just exits. How is a person supposed to deploy anything like this?

**Comment by hisham** [comment] 2020-09-21 15:23
This issue just popped up again with me. Doing amplify pull resolved it.

**Comment by UnleashedMind** [comment] 2020-09-21 17:28
@cyrfer any updates after Friday's meeting?

**Comment by cyrfer** [comment] 2020-09-22 01:33
@UnleashedMind Thanks for checking up on me. I finally figured out the right zip command. The folder context was critical when zipping. Without it, `amplify push` was giving errors like:
> An error occurred during the push operation: File at path: '/Users/cyrfer/project/amplify/#current-cloud-backend/amplify-meta.json' does not exist

due to `amplify push` creating the following structure locally:
> amplify/#current-cloud-backend/#current-cloud-backend/amplify-meta.json

So now I have a recipe. Fix my amplify-meta.json file when it "becomes" corrupted.

```bash
1. cd project/amplify/\#current-cloud-backend/
2. zip -r \#current-cloud-backend.zip .
3. aws s3 cp \#current-cloud-backend.zip s3://deployment-bucket/    # visible in amplify-meta.json
4. cd ../.. && amplify push
```

I had to do the steps above one more time when I realized that the `build-config.json` I put on S3 already had my new resources declared, but they had not been pushed to the real cloud yet. That, and remembering to run `amplify env checkout dev` finally got `amplify push` to recognize the changed files for the custom CF. My Custom CF additions are moving forward again.

In the meeting you described the steps the CLI goes through when comparing the cloud status to the local status. I think that should be documented clearly with references to the code responsible for those steps. The open source community will be able to self-serve and even contribute easier if the process is clear.

Thanks!

**Comment by cyrfer** [comment] 2020-09-22 05:14
@UnleashedMind Here is the only reference I can find about using the `team` file for environment-specific parameters.
https://github.com/aws-amplify/amplify-cli/issues/3240#issuecomment-577832717

**Comment by cyrfer** [comment] 2020-09-24 15:23
I think this ticket can be closed. My main takeaway is that ANY time I modify `backend-config.json` I must run `amplify env checkout <current>` to get `amplify status` to recognize the change.

**Comment by hisham** [comment] 2020-09-24 16:17
Ok but I never touched backend-config.json myself on my part, so not sure why I was seeing this issue. Anyways if I see it again I'll comment here or open another issue. Thanks!

**Comment by cyrfer** [comment] 2020-09-24 17:16
@hisham that's right - I forgot about the initial problem. I think I didn't cause it either, but rather some part of the CLI messed up `amplify-meta.json`.

The trick to solving the issue where a mysterious category named "providers" was listed as being DELETED by `amplify status` was a yet-to-be-documented hack [documented above](https://github.com/aws-amplify/amplify-cli/issues/5340#issuecomment-696465876), beginning with `Fix my amplify-meta.json`.

**Comment by cyrfer** [comment] 2020-11-02 23:52
I plan to continue updating this thread every time this is a problem.

Please, Amplify Team, figure out a better solution!

Following my tried and true steps, [documented above](https://github.com/aws-amplify/amplify-cli/issues/5340#issuecomment-696465876), I somehow resulted in the following issue:

```bash
$ amplify status

Current Environment: dev

| Category  | Resource name   | Operation | Provider plugin   |
| --------- | --------------- | --------- | ----------------- |
| Function  | omitted1    | Create    | awscloudformation |
| Function  | omitted2          | Update    | awscloudformation |
| Providers | categories      | Delete    |                   |
| Api       | omitted3       | No Change | awscloudformation |
| Hosting   | S3AndCloudFront | No Change | awscloudformation |
```

**Comment by julien-tamade** [comment] 2020-11-06 18:43
I'm also running into this Providers categories delete issue. It happened when I switched to a different environment and then switched back to my production environment. I've been running amplify pull to get rid of it, but I also noticed it shows up if I run amplify env checkout prod.

**Comment by cyrfer** [comment] 2020-11-10 17:10
@julien-tamade me too! I'm seeing the issue when I switch to my prod environment. Both my non-prod environments (dev & qa) deployed without a hitch this time, but then I saw this problem when switching to my prod env (which uses a different aws profile for the access to the separate account).

**Comment by julien-tamade** [comment] 2020-11-11 23:51
@cyrfer do you have any idea if it's ok to push with that in the status? Or if that will totally mess things up? Trying to figure out how i'm gonna merge my dev changes because if I checkout prod, then that will be in there until i run pull. But if I pull it will overwrite the changes I was trying to merge.

**Comment by cyrfer** [comment] 2020-11-12 16:55
@julien-tamade I think I tried that once, and I don't remember the outcome. I think my deploy did not succeed but I don't remember for sure.

You should try the steps I documented above. It's pretty easy to fix it.
https://github.com/aws-amplify/amplify-cli/issues/5340#issuecomment-696465876

**Comment by julien-tamade** [comment] 2020-11-12 22:05
thanks @cyrfer I just wanted to make sure that actually removing the categories wouldn't break my backend. Essentially they are there but unnecessary so we just want to remove, correct?

**Comment by cyrfer** [comment] 2020-11-16 18:00
@julien-tamade yes, exactly.

**Comment by kylekirkby** [comment] 2020-11-26 20:47
I'm also getting this:

```

Pre-pull status:

Current Environment: develop

| Category                       | Resource name                          | Operation | Provider plugin   |
| ------------------------------ | -------------------------------------- | --------- | ----------------- |
| Providers                      | categories                             | Delete    |                   |
```

Is this something to be concerned about? All I have done is checkout a new branch and pulled my develop environment.

**Comment by cyrfer** [comment] 2020-11-26 22:02
@kylekirkby I think it might prevent you to push, but I'm not sure.

**Comment by kylekirkby** [comment] 2020-11-27 09:39
> @kylekirkby I think it might prevent you to push, but I'm not sure.

Everything worked fine in the end after pushing. Just seems strange 🤷‍♂️

**Comment by PatrykMilewski** [comment] 2020-12-02 15:08
We are having the same problem, after upgrade from 4.19.0 -> 4.37.0, however we didn't ever used Providers categories whatever it is.

After pushing changes, nothing was actually deleted.

**Comment by kaustavghosh06** [comment] 2020-12-24 21:08
Yeah, nothing should get deleted, but we're unable to reproduce this display issue on our end.

**Comment by martysweet** [comment] 2021-01-06 06:36
I was able to reproduce this against one environment by using Node v12.19.0, switching to Node v13.14.0 seems to have fixed it. A providers.categories section was present in my #current-cloud-back-end/amplify-meta.json file.

**Comment by cyrfer** [comment] 2021-01-08 00:47
@martysweet thanks for tracking that down! Does Amplify have a recommended Node environment?

**Comment by SwaySway** [comment] 2021-01-09 01:25
@cyrfer Did you switch node versions? If so did this issue occur again?
> Does Amplify have a recommended Node environment?
We don't have a specific version we recommend outside of the minimum requirement being Node.js version 10.x.

**Comment by mgacy** [comment] 2021-02-01 18:27
Using Node v14.4.0; I encountered this issue after an upgrade from 4.27 -> 4.41.2. Steps:

- modify schema and `CustomResources.json` on `dev` environment
- `amplify push` (no problems)
- `amplify env checkout master`
- `amplify status`

Notes:

- `amplify-meta.json` has the extra "providers.categories" key
- I used the same profile for both environments
- subsequent `amplify pull` did not resolve

**Comment by attilah** [comment] 2021-02-01 21:56
@cyrfer @mgacy do you have a current environment/files where you could reproduce it? and could share those files with the team?

**Comment by mgacy** [comment] 2021-02-01 23:41
@attilah Sent requested files to amplify-cli@amazon.com

**Comment by ahtokca** [comment] 2021-02-05 21:36
Got the same issue after upgrading 4.28.2 to 4.41.2

**Closed** 2021-04-16 17:05 UTC
Labels: bug, not-reproducable, pending-close-response-required, platform
