### ISSUE TITLE
Cognito User Pool and Lambda Triggers disconnect.

### ISSUE THREAD

**Issue by phanviet** [aws-amplify/amplify-cli#7588] opened 2021-06-23 08:15 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v12.21.0

### Amplify CLI Version

5.0.1

### What operating system are you using?

Mac

### Amplify Categories

auth

### Amplify Commands

add, push

### Describe the bug

1. Create Cognito User Pool (no Identity Pool) + Triggers through Amplify CLI `amplify add auth`
2. Result: Create User Pool + Lambda Triggers linked together.
3. Add S3: `amplify add storage`, Amplify CLI auto inject Identity Pool
4. `amplify push`
5. Result: Create User Pool + Lambda Triggers disconnect together.

### Expected behavior

User Pool + Lambda Triggers should still keep connection.

### Reproduction steps

As describe section

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment] 2021-06-23 13:14
Hey @phanviet :wave: thanks for raising this. It appears to be a duplicate of https://github.com/aws-amplify/amplify-cli/issues/7561 and is being actively investigated by the team. Are you seeing the triggers are not being connected to the Cognito resource after pushing?

**Comment by attilah** [comment] 2021-06-23 22:21
Closing in favor of #7561 as the root cause is the same.

**Closed by attilah** 2021-06-23 22:21 UTC
Labels: auth, bug, duplicate
