### ISSUE TITLE
cannot pull down lamda functions with command amplify pull --appId d4emwdhqyyg0k --envName dev

### ISSUE THREAD

**Issue by ttataroglou** [aws-amplify/amplify-cli#10991] opened 2022-09-05 23:50 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-adminui/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-adminui/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

ap-southeast-2

### Environment name

d4emwdhqyyg0k

### What operating system are you using?

Windows 10

### Describe the bug

Cannot pull down lambda functions used by amplify app, also my cli defaults to javascript when using node.js not sure if that would cause an issue

### Expected behavior

can see aws lambda functions in visual studio code

### Reproduction steps

1.Open command prompt
2. Change to dev folder
3. Enter amplify pull --appId d4emwdhqyyg0k --envName dev

**Comment by letsbelopez** [comment] 2022-09-08 18:56
Transferring to CLI because customer is having issues using amplify pull.

**Comment by josefaidt** [comment] 2022-09-09 14:35
Hey @ttataroglou :wave: thanks for raising this! To get a better understanding of the issue can you post a minimal reproduction to help us recreate the issue on our side? Please consider providing additional details, such as error messages, CLI version, how you installed the CLI, etc.

**Comment by josefaidt** [comment] 2022-11-02 00:17
Closing due to inactivity. @ttataroglou if you are still experiencing this issue please reply back to this thread with the relevant details and we can re-open to investigate further

**Closed by josefaidt** 2022-11-02 00:17 UTC
Labels: pending-close-response-required, pending-triage
