### ISSUE TITLE
configure REST API with Cognito User Pools Authorization

### ISSUE THREAD

**Issue by gaochenyue** [aws-amplify/amplify-cli#3058] opened 2019-12-21 17:47 UTC
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**
I'm creating a REST API backed with a lambda function. It set the API Gateway with IAM auth by default and there is no way to choose Cognito User Pools Auth. You do have a workaround [Cognito User Pools Authorization](https://aws-amplify.github.io/docs/js/api#cognito-user-pools-authorization), but it is a manual operation and it doesn't work with local debug

**Describe the solution you'd like**
I will be able to manage Cognito User Pools Auth for REST API with Amplify CLI. Also I can local debug the REST API.

**Describe alternatives you've considered**
not sure

**Additional context**
no

**Comment by SwaySway** [comment] 2020-04-15 20:07
Closing as a duplicate of #3390

**Closed by SwaySway** 2020-04-15 20:07 UTC
Labels: REST API, feature-request
