### ISSUE TITLE
Amplify storage with override fails due to semi deployment

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/amplify-cli#10018] opened 2022-03-18 18:25 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify CLI Version

7.6.25

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Amplify Categories

storage

### Amplify Commands

add, override, push

### Describe the bug

When overriding the storage the policy(for example) has mistake in it or is incorrect. The deployment will go through and output the syntax error but the deployment will continue to create the s3 bucket. causing the next deployment to fail as resource was already created in the previous deployment.

### Expected behavior

Expect the deployment to not continue with s3 creation or delete the s3 bucket on failure.

### Reproduction steps

1. `amplify add storage` (select first option for images etc)
2. add override storage using `amplify override storage `
3. write a incorrect override policy for storage. example as follows:

```ts
export function override(resources: AmplifyS3ResourceTemplate) {
    resources.s3AuthPublicPolicy.policyDocument.Statement =  [
        ...resources.s3AuthPublicPolicy.policyDocument.Statement,
        {
            Action: [ "s3:PutObject","s3:PutObjectAcl","s3:GetObject"],
        }
    ]
}
```
4. `amplify push`
fails with the following

`-- Syntax errors in policy` (expected)
observe the deployment going through (example s3 creation)
Note: fixing the override will not mitigate the issue, tested this as well.

5. `amplify push` again. we will see the s3 already present error as follows

`CREATE_FAILED      S3Bucket AWS::S3::Bucket  needtodelete-dev already exists`

**Continuation**
On additional testing

a. do `amplify pull` and observe the override and storage files disappear.
b. `amplify delete` to delete project
c. see orphaned resources such as s3 bucket still present in the console.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment] 2022-08-29 18:54
closing as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/6777

**Closed by josefaidt** 2022-08-29 18:54 UTC
Labels: bug, storage, duplicate, p3, ops-deploy
