### ISSUE TITLE
Better Change Log Writing

### ISSUE THREAD

**Issue by gakinson** [aws-amplify/amplify-cli#10926] opened 2022-08-23 16:40 UTC
### Is this feature request related to a new or existing Amplify category?

auth, storage, function, api, analytics, hosting, notifications, interactions, predictions, xr

### Describe the feature you'd like to request

I was wondering if the team could write more informative changelog releases, I look at the changelog to see what changes are coming out to help determine if we should update our amplify cli version. When I see a change log like the one at https://github.com/aws-amplify/amplify-cli/releases/tag/v9.0.0 and it says Breaking Change with no actual description, it make is harder for us to actually update because we do not know if there actually is a breaking change and if it will affect out applications.

Also, I may be way off base here and there may be better documentation I am unaware of. If so, let me know where that may be.

### Describe the solution you'd like

Better change log writing

### Describe alternatives you've considered

Diving into all your changes 

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment] 2022-09-20 17:49
Hey @gakinson :wave: thanks for raising this! After revisiting a few of the feature requests around improving the changelog and release notes, I'm going to close this issue as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/2574. Please subscribe to #2574 for further updates

**Closed by josefaidt** 2022-09-20 17:49 UTC
Labels: feature-request, documentation
