### ISSUE TITLE
While using Amplify DataStore, Android Studio cannot find nodejs installed in the system.

### ISSUE THREAD

**Issue by Jay2113** [aws-amplify/amplify-cli#3745] opened 2020-03-23 12:42 UTC
**Describe the bug**
I have created an Android App and I am trying to integrate Amplify DataStore into it. In the process, while trying to run the modelgen task from Android Studio I am observing an error saying Nodejs is not found.

**Amplify CLI Version**
4.16.1

**To Reproduce**
Create a basic Android App and try to integrate Amplify DataStore. Reference: https://aws-amplify.github.io/docs/android/datastore  

**Expected behavior**
Modelgen task should go through and create model files successfully.
 
**Screenshots**
Here are the Build logs:
Executing tasks: [clean, :app:assembleDebug] in project C:\Users\User\AndroidStudioProjects\AltorRide

Gradle Daemon started in 3 s 742 ms

> Configure project :
Node is not installed. Visit https://nodejs.org/en/download/ to install it

> Task :clean UP-TO-DATE
> Task :app:clean
> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:generateDebugBuildConfig
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:mainApkListPersistenceDebug
> Task :app:generateDebugResValues
> Task :app:generateDebugResources
> Task :app:injectCrashlyticsMappingFileIdDebug

> Task :app:processDebugGoogleServices
Parsing json file: C:\Users\User\AndroidStudioProjects\AltorRide\app\google-services.json

> Task :app:javaPreCompileDebug
> Task :app:mergeDebugResources
> Task :app:createDebugCompatibleScreenManifests
> Task :app:extractDeepLinksDebug

> Task :app:processDebugManifest
C:\Users\User\AndroidStudioProjects\AltorRide\app\src\main\AndroidManifest.xml:24:9-31:50 Warning:
	activity#com.google.firebase.auth.internal.FederatedSignInActivity@android:launchMode was tagged at AndroidManifest.xml:24 to replace other declarations but no other declaration present

> Task :app:processDebugResources

> Task :app:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :app:compileDebugSources
> Task :app:mergeDebugShaders
> Task :app:compileDebugShaders
> Task :app:generateDebugAssets
> Task :app:mergeDebugAssets
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:checkDebugDuplicateClasses
> Task :app:mergeDebugJavaResource
> Task :app:dexBuilderDebug
> Task :app:desugarDebugFileDependencies
> Task :app:mergeDebugJniLibFolders
> Task :app:validateSigningDebug
> Task :app:mergeDebugNativeLibs
> Task :app:stripDebugDebugSymbols
> Task :app:multiDexListDebug
> Task :app:mergeDexDebug
> Task :app:packageDebug
> Task :app:assembleDebug

BUILD SUCCESSFUL in 5m 49s
28 actionable tasks: 27 executed, 1 up-to-date

Here are the modelgen logs:
[modelgen logs.txt](https://github.com/aws-amplify/amplify-cli/files/4369350/modelgen.logs.txt)

**Desktop (please complete the following information):**
 - OS: Windows 7 Ultimate SP1
 - Node Version: 12.16.1
 - NPM Version: 6.13.4

**Comment by alan-cooney** [comment] 2020-03-30 06:55
Did you ever resolve this?

**Comment by nikhname** [comment] 2020-03-30 19:45
@Jay2113 Which version of amplify-tools-gradle-plugin are you using?

**Comment by Jay2113** [comment] 2020-04-01 17:17
Hi @alan-cooney 
Can you please confirm the version of amplify-tools-gradle-plugin that you are using?

**Comment by zilonkaj** [comment] 2020-04-02 22:36
I am also having this issue with version 0.2.1 of the gradle plugin. This is on the latest Android Studio on Windows 10.

**Comment by nikhname** [comment] 2020-04-03 20:23
Hi @zilonkaj, just to clarify you are seeing the node is not installed error message? What is the output when you enter ```which node``` ?

**Comment by nikhname** [comment] 2020-04-03 20:51
This seems to be an issue on windows. As a workaround, you can run ```npx amplify-app --platform --android``` to set up the amplify project and then ```amplify codegen models``` to generate models

**Comment by sayantapadar** [comment] 2020-04-05 13:49
@nikhname I used Ubuntu 18.04.4 LTS to build the project, and everything worked fine. So yes it is a Windows bug it seems.

**Comment by nikhname** [comment] 2020-05-22 16:09
Closed by https://github.com/aws-amplify/amplify-android/pull/505

**Closed by nikhname** 2020-05-22 16:09 UTC
Labels: amplify-app, bug, windows

**Comment by ParryPatel021** [comment] 2020-06-27 11:04
@sayantapadar I am using the same system as your's but I am having this issue.
It occurs when I try to run my Android Project.
Do you have any idea?
Please share some work around

**Comment by sayantapadar** [comment] 2020-06-27 17:20
@ParryPatel021 I'm afraid I was unable to find a solution in my Windows system, even after trying all possible remedies. I moved to a linux based system - in my case Ubuntu 18.04. Over there, simply following the getting started doc worked perfectly for me.

**Comment by ParryPatel021** [comment] 2020-06-29 04:28
Okay @sayantapadar Thank for the reply, I will again go through the Getting started doc from the begin

**Comment by jamesonwilliams** [comment] 2020-07-01 04:36
Looks like a duplicate of https://github.com/aws-amplify/amplify-android/issues/531
