### ISSUE TITLE
amplify-xcode does not escape path names

### ISSUE THREAD

**Issue by apanju** [aws-amplify/amplify-cli#13079] opened 2023-08-05 10:44 UTC
### How did you install the Amplify CLI?

npm

### Amplify CLI Version

12.2.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no manual changes were made

### Describe the bug

My XCode project path contains a space
amplify init mostly worked, but failed on the last step: amplify-xcode import-config

solution was to escape the path with single quotes

### Expected behavior

the path in the arguments would be esclosed with single quotes to avoid spaces in the path causing issues

### Reproduction steps

create an xcode project with a space in the file path
run amplify init on the new project

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment] 2023-08-07 19:21
Hey @apanju :wave: thanks for raising this! This is a duplicate of https://github.com/aws-amplify/amplify-cli/issues/12593, and the fix will be available in the next CLI release 🎉 

I'll mark this as a duplicate bug report and close in favor of tracking the existing item.

**Closed by josefaidt** 2023-08-07 19:21 UTC
Labels: pending-triage
