### ISSUE TITLE
amplify push fails when adding sortField to an existing @connection

### ISSUE THREAD

**Issue by azahran007** [aws-amplify/amplify-cli#1239] opened 2019-04-09 21:55 UTC
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
GraphQL annotated template

** What AWS Services are you utilizing? **
AppSync, DynamoDB, Lambda, APIGateway,Cognito

** Provide additional details e.g. code snippets **
I am trying to update a GraphQL template, adding sortField: "createdAt" to the connection, it compiles succesfully but during the amplify push I get the following error:

Cannot update GSI's properties other than Provisioned Throughput. You can create a new GSI with a different name.

Is there a workaround? I tried deleting the existing GSI hoping it would be recreated with the right sorting, but all the resolvers for that table failed and push still fails. I also tried recreating the GSI manually with "createdAt" as the sort field, and that still doesn't work.

**Comment by mikeparisstuff** [comment] 2019-04-12 19:33
This is known issue. Currently when deploying changes to @connection fields that will result in a DynamoDB table GSI schema change you need to first delete the connection, push, and then re-add the connection. There is an open discussion here #1062 where we are working towards a design that solves these issues introduced by CFN update stack limitations such as this one from DynamoDB.

**Comment by mikeparisstuff** [comment] 2019-04-12 19:34
Duplicate of #902. Also see #1062.

**Closed by mikeparisstuff** 2019-04-12 19:34 UTC
Labels: duplicate, graphql-transformer
