### ISSUE TITLE
Graphql documentation example doesn't work

### ISSUE THREAD

**Issue by Bulletninja** [aws-amplify/amplify-cli#4072] opened 2020-04-25 04:14 UTC
**Describe the bug**
Added a lambda with this code as a reference
(GRAPHQL from lambda example)
https://aws-amplify.github.io/docs/cli-toolchain/quickstart#graphql-from-lambda
(of course the generated env variable names are based on the names of my apis)

**Amplify CLI Version**
4.18.1

**To Reproduce**
Just use the example code in the link and then run 
`amplify mock`

**Expected behavior**
Expected being able to create an entry in the corresponding table,
running a query from a lambda created via amplify cli.

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Node Version: v10.18.1

**Additional context**
First i tried to run it as is. But later noticed the env variables were empty, then i hardcoded
`appsyncUrl`, `region` and `apiKey`

it gets to some point in here:
``` 
const data = await new Promise((resolve, reject) => {
      const httpRequest = https.request(
        { ...req, host: endpoint },
        (result) => {
          console.log({ result });
          result.on("data", (data) => {
            resolve(JSON.parse(data.toString()));
          });
        }
      );

      httpRequest.write(req.body);
      httpRequest.end();
    });
```
After a while it complaints with this:
```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 192.168.0.173:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
Emitted 'error' event at:
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

tried changing the https to http. Got the same error but with port 80 (of course! 😆)

**Comment by kaustavghosh06** [comment] 2020-08-14 01:57
@Bulletninja Is it just a mock issue are you seeing a similar behavior in the cloud (in Lambda) as well?

**Comment by Bulletninja** [comment] 2020-08-14 15:10
Just in mock

**Comment by nikhname** [comment] 2020-10-21 23:37
I was not able to reproduce this with 4.30.0. Please comment if this is still an issue.

**Comment by kaustavghosh06** [comment] 2020-10-24 22:15
Closing this issue due to lack of reproducibility. Please let us know if you're facing this issue with the latest version of the CLI.

**Closed by kaustavghosh06** 2020-10-24 22:15 UTC
Labels: mock, pending-close-response-required, pending-triage
