### ISSUE TITLE
@aws-amplify/cli@10.6.2 breaks the build: "No CloudFormation template found" for Cognito Trigger lambda functions

### ISSUE THREAD

**Issue by jevakallio** [aws-amplify/amplify-cli#11825] opened 2023-01-23 13:23 UTC
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16

### Amplify CLI Version

10.6.2

### What operating system are you using?

MacOS locally, also happens on Amplify CI standard Linux build image

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No.

### Describe the bug

After Amplify CI upgraded `@aws-amplify/cli` to version `10.6.2`, our build started to fail with the following error:
```
2023-01-23T11:59:44.913Z [WARNING]: ✖ There was an error initializing your environment.
2023-01-23T11:59:44.918Z [INFO]: 🛑 No CloudFormation template found at /codebuild/output/src794822960/src/poetics/amplify/backend/function/CognitoCustomMessage/CognitoCustomMessage-cloudformation-template.json
```

The same issue can be replicated by upgrading tot `10.6.2` locally on my development machine.

Unsure if this is relevant, but the file that it's looking for has a different name in our project (as generated by the Amplify project scaffold ages ago):

```diff
- amplify/backend/function/CognitoCustomMessage/CognitoCustomMessage-cloudformation-template.json
+ amplify/backend/function/CognitoCustomMessage/poetics28e16a8dCustomMessage-cloudformation-template.json
```

Where `poetics28e16a8d` is the name of our Cognito auth resource.

Downgrading `@aws-amplify/cli` to version `10.6.1` fixed the issue, both locally and in CI by overriding the version in Build Image settings `Live package updates` section.

Having a quick browse of the `10.6.2` release notes, this line looks suspicious:
https://github.com/aws-amplify/amplify-cli/commit/fdcb20afffdb6b9d163d60c98f52da253ba04e77#diff-113485343220ae9dc8efa3c39035b1ba034a31e5ac212bb6a1b557a9550cebfcR16

```js
      const templateSourceFilePath = path.join(pathManager.getBackendDirPath(), AmplifyCategories.FUNCTION, functionName, `${functionName}-cloudformation-template.json`);
      const { cfnTemplate } = readCFNTemplate(templateSourceFilePath);
```

Here, the `${functionName}-cloudformation-template.json` interpolation would produce exactly the file name that is not matching. It's not clear to me if the logic in this interpolation is incorrect, or if the `functionName` is being reported incorrectly.

For all our generated Cognito trigger functions, the file CloudFormation template file name appears to be like:
```
${authResourceName}${functionName}-cloudformation-template.json
```

Hope this helps!

### Expected behavior

Build doesn't fail

### Reproduction steps

I haven't tried to reproduce this on a new project, but I would try something like:

- Create new Amplify project
- Add Cognito Auth with triggers
- Run `amplify push`

Unless the project template has been changed to name the Cognito Trigger lambda without the Auth resource prefix, this should probably fail

### Project Identifier

277e04d4c8c29e7767a630177599f562

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by akshbhu** [comment] 2023-01-23 21:36
Hi @jevakallio 

I wasn't able to reproduce this locally with repro steps.

Though I found something in your code as you mentioned 10.6.2 updated the functions paths  as below:  
```
- amplify/backend/function/CognitoCustomMessage/CognitoCustomMessage-cloudformation-template.json
+ amplify/backend/function/CognitoCustomMessage/poetics28e16a8dCustomMessage-cloudformation-template.json


Expected Trigger ResourceName: poetics28e16a8dCustomMessage

Cx Trigger ResourceName: CognitoCustomMessage

```

In `backend-config.json` all the triggerNames are similar to above pattern.

This is my experimental backend config file: 
```
{
  "auth": {
    "testtrigger32877fe392877fe39": {
      "customAuth": false,
      "dependsOn": [
        {
          "attributes": [
            "Arn",
            "Name"
          ],
          "category": "function",
          "resourceName": "testtrigger32877fe392877fe39CustomMessage",
          "triggerProvider": "Cognito"
        },
        {
          "attributes": [
            "Arn",
            "Name"
          ],
          "category": "function",
          "resourceName": "testtrigger32877fe392877fe39PostConfirmation",
          "triggerProvider": "Cognito"
        }
      ],
      "frontendAuthConfig": {
        "mfaConfiguration": "OFF",
        "mfaTypes": [
          "SMS"
        ],
        "passwordProtectionSettings": {
          "passwordPolicyCharacters": [],
          "passwordPolicyMinLength": 8
        },
        "signupAttributes": [
          "EMAIL"
        ],
        "socialProviders": [],
        "usernameAttributes": [],
        "verificationMechanisms": [
          "EMAIL"
        ]
      },
      "providerPlugin": "awscloudformation",
      "service": "Cognito"
    }
  },
  "function": {
    "testtrigger32877fe392877fe39CustomMessage": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda"
    },
    "testtrigger32877fe392877fe39PostConfirmation": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda"
    }
  },
  "parameters": {
    "AMPLIFY_function_testtrigger32877fe392877fe39CustomMessage_EMAILMESSAGE": {
      "usedBy": [
        {
          "category": "function",
          "resourceName": "testtrigger32877fe392877fe39CustomMessage"
        }
      ]
    },
    "AMPLIFY_function_testtrigger32877fe392877fe39CustomMessage_EMAILSUBJECT": {
      "usedBy": [
        {
          "category": "function",
          "resourceName": "testtrigger32877fe392877fe39CustomMessage"
        }
      ]
    },
    "AMPLIFY_function_testtrigger32877fe392877fe39CustomMessage_REDIRECTURL": {
      "usedBy": [
        {
          "category": "function",
          "resourceName": "testtrigger32877fe392877fe39CustomMessage"
        }
      ]
    },
    "AMPLIFY_function_testtrigger32877fe392877fe39PostConfirmation_GROUP": {
      "usedBy": [
        {
          "category": "function",
          "resourceName": "testtrigger32877fe392877fe39PostConfirmation"
        }
      ]
    }
  }
}
```

As you can see triggers are` <authResourceName>-<CustomMessage>` which is different in the `backend-config.json` shared using project identifier.

I have some questions:

1. Do you have which version were these triggers created ?
2. When you mentioned 10.6.1 fixes the issue on hosting and local , Does this fixes the naming of the trigger resource file locally ?
3. Can you try adding one more trigger using ```amplify update auth``` with latest amplify cli version and check under which name the trigger is created

**Comment by jevakallio** [comment] 2023-01-24 12:47
Hi!

You're right, in our backend-config.json, the referenced function resource names are not prefixed as in your experimental file:
```
  "auth": {
    "poetics28e16a8d": {
      "customAuth": false,
      "dependsOn": [
        {
          "attributes": [
            "Arn",
            "Name"
          ],
          "category": "function",
          "resourceName": "CognitoCustomMessage",
          "triggerProvider": "Cognito"
        },
```

1. I don't know what exact version of the CLI created the files, since at that time Amplify didn't add the `Description` field to the CloudFormation template. The files were created on Nov 5 2022, the first time the `Description` field appears is Nov 22, 2022 (~2 weeks later) with version 7.4.5:
```
"Description": "{\"createdOn\":\"Mac\",\"createdBy\":\"Amplify\",\"createdWith\":\"7.4.5\",\"stackType\":\"function-Lambda\",\"metadata\":{}}",
```

2. There is no change in the naming of the trigger resource file between running on 10.6.1 and 10.6.2 -- the difference is that on 10.6.1 you don't yet run the `readCFNTemplate` function which throws the error, so it bypasses the error for now.

3. I'm a little hestitant to run `amplify update auth` at this time. In the past when I've ran this command, it's messed up our project to an unworkable state that was hard to recover from. Before I run it, I'll need to create a new throwaway environment which in our case takes a few manual steps that I don't have time for today. Will do this when I have time to loop back to addressing the root cause of this issue.

**Comment by jevakallio** [comment] 2023-02-01 19:20
I've ran `amplify update auth` to no effect.

I've also tried to update my `backend-config.json` with the auth resource prefixed names as per your `testtrigger` project, but the same issue persists.

**Comment by fooman** [comment] 2023-02-02 06:51
Ran into the same error message
```
No CloudFormation template found at /codebuild/output/src908609996/src/connect-amplify/amplify/backend/function/signuphandler/signuphandler-cloudformation-template.json
```

The checked in file is `amplify/backend/function/signuphandler/signUpHandler-cloudformation-template.json` so it is   
`signUpHandler-cloudformation-template.json` vs. 
`signuphandler-cloudformation-template.json`

**Comment by jevakallio** [comment] 2023-02-06 18:16
I can confirm this issue is now resolved by renaming the CloudFormation files for the trigger lambdas to match the ones in `amplify-meta.json`.

Build and deploy works now on 10.7.1, so for my part we can close this issue. Keeping open now as @fooman above has reported a similar problem.

**Comment by tomaszczechowski** [comment] 2023-02-07 15:55
Had the same issue. After renaming the cloud formation file in the lambda according to `amplify-meta.json`, the issue is gone.

**Comment by josefaidt** [comment] 2023-03-06 20:35
Closing as this issue has since been resolved. When modifying a Cognito trigger's directory name to use a more recognizable name it was found later versions of Amplify CLI were attempting to reference the auto-generated resource names. After renaming the directories to match the names shown in `amplify/backend/amplify-meta.json` this issue was resolved.

**Closed by josefaidt** 2023-03-06 20:35 UTC
Labels: pending-triage
