### ISSUE TITLE
[DX issue] Invalid configuration settings when using Amplify Headless CLI commands, but it doesn't tell you whats invalid

### ISSUE THREAD

**Issue by omenking** [aws-amplify/amplify-cli#11777] opened 2023-01-13 18:34 UTC
### Amplify CLI Version

10.6.1

### Question

```json
{
  "amplify": {
    "projectName": "myproject",
    "envName": "dev",
    "defaultEditor": "code"

  },
  "frontend": {
    "frontend": "javascript",
    "framework": "react",
    "config": {
      "SourceDir": "src",
      "DistributionDir": "build",
      "BuildCommand": "npm run-script build",
      "StartCommand": "npm run-script start"
    }
  },
  "providers": {
    "awscloudformation": {
      "configLevel": "project",
      "useProfile": false,
      "profileName": "default",
      "accessKeyId": "$key",
      "secretAccessKey": "$secret",
      "region": "us-east-1"
    }
  }
}
```

```
amplify init --frontend  $(jq -n --arg key "" --arg secret "" -f amplify-conf.json | jq -c '.frontend')\
             --amplify   $(jq -n --arg key "" --arg secret "" -f amplify-conf.json | jq -c '.amplify') \
             --providers $(jq -n --arg key $AWS_ACCESS_KEY_ID --arg secret $AWS_ACCESS_KEY_ID -f amplify-conf.json | jq -c '.providers')
```

```
Project information
| Name: cruddurcognito
| Environment: dev
| Default editor: Visual Studio Code
| App type: javascript
| Javascript framework: react
| Source Directory Path: src
| Distribution Directory Path: build
| Build Command: npm run-script build
| Start Command: npm run-script start

? Initialize the project with the above configuration? Yes
Invalid configuration settings!
? Do you want to retry configuration? (y/N) 
```

My configuration is invalid.... but it doesn't tell me what, so how do I determine that?

<img width="492" alt="Screen Shot 2023-01-13 at 1 33 18 PM" src="https://user-images.githubusercontent.com/7776/212393783-ca08f07a-8609-4ff5-8c07-fb449274c1f9.png">

**Comment by omenking** [comment] 2023-01-13 18:44
Also I want to point that I am using the same parameters just translated to JQ (so same json output) and it makes me think that maybe the provided example in the documentation will not work either...

<img width="735" alt="Screen Shot 2023-01-13 at 1 43 23 PM" src="https://user-images.githubusercontent.com/7776/212395406-e355685d-037a-4df7-8c09-48e8e2a1dc0e.png">

**Comment by omenking** [comment] 2023-01-13 18:55
I think this is what validates the config because I see `awsConfigInfo.configValidated = false;` which is what trigger that message.

```js
async function validateConfig(context: $TSContext) {
  const { awsConfigInfo } = context.exeInfo;
  awsConfigInfo.configValidated = false;
  if (awsConfigInfo.configLevel === 'general' || awsConfigInfo.configLevel === 'amplifyAdmin') {
    awsConfigInfo.configValidated = true;
  } else if (awsConfigInfo.config) {
    if (awsConfigInfo.config.useProfile) {
      if (awsConfigInfo.config.profileName && awsConfigInfo.config.profileName.length > 0) {
        awsConfigInfo.configValidated = true;
      }
    } else {
      awsConfigInfo.configValidated =
        awsConfigInfo.config.accessKeyId &&
        awsConfigInfo.config.accessKeyId !== constants.DefaultAWSAccessKeyId &&
        awsConfigInfo.config.secretAccessKey &&
        awsConfigInfo.config.secretAccessKey !== constants.DefaultAWSSecretAccessKey &&
        awsConfigInfo.config.region &&
        awsRegions.regions.includes(awsConfigInfo.config.region);
      const sts = new STS({
        credentials: {
          accessKeyId: awsConfigInfo.config.accessKeyId,
          secretAccessKey: awsConfigInfo.config.secretAccessKey,
          sessionToken: awsConfigInfo.config.sessionToken,
        },
      });
      try {
        await sts.getCallerIdentity({}).promise();
      } catch (err) {
        awsConfigInfo.configValidated = false;
      }
    }
  }
  return context;
}
```
Looking at the code maybe its an issues with my AWS Credentials. I'll install the AWS CLI in my environment and do an sts call to see if that's all valid

**Comment by omenking** [comment] 2023-01-13 19:15
I was hoping I could find out to edit this code and throw in console logs but idea where how to do that.
So I'm going to have to blindly guess what its problem is  😑

**Comment by omenking** [comment] 2023-01-13 19:17
here I can see multiple people experiencing the same issue, but the ticket is locked and there was no improvement made here.
https://github.com/aws-amplify/amplify-cli/issues/4128

**Comment by omenking** [comment] 2023-01-13 20:08
Okay so I can't just open `node_modules` to inject logging I have to use the developer environment:

```
git clone https://github.com/[username]/amplify-cli.git
cd amplify-cli
yarn setup-dev
```

Make changes to the code.
To update the code you can do
```
npm run build
```

<img width="526" alt="Screen Shot 2023-01-13 at 3 08 25 PM" src="https://user-images.githubusercontent.com/7776/212410285-29a74840-e435-437c-a1bd-9c0813578001.png">

**Comment by omenking** [comment] 2023-01-13 20:45
Okay so using the CLI with the same credentials:

```
aws sts get-caller-identity
{
    "UserId": "REDACTED",
    "Account": "REDACTED",
    "Arn": "arn:aws:iam::REDACTED:user/andrewbrown"
}
```

Works no problem

However this call to STS in the code:
```
      const sts = new STS({
        credentials: {
          accessKeyId: awsConfigInfo.config.accessKeyId,
          secretAccessKey: awsConfigInfo.config.secretAccessKey,
          sessionToken: awsConfigInfo.config.sessionToken,
        },
      });
      try {
        await sts.getCallerIdentity({}).promise();
      } catch (err) {
        context.print.green(err);
        context.print.green(`99: STS Get Caller Identity Call failed`)
        awsConfigInfo.configValidated = false;
      }
```

Is resulting in this error, hmmm
```
SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
    at Request.extractError (/workspace/cruddur-workspace/amplify-cli/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/workspace/cruddur-workspace/amplify-cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/workspace/cruddur-workspace/amplify-cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/workspace/cruddur-workspace/amplify-cli/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/workspace/cruddur-workspace/amplify-cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/workspace/cruddur-workspace/amplify-cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /workspace/cruddur-workspace/amplify-cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/workspace/cruddur-workspace/amplify-cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/workspace/cruddur-workspace/amplify-cli/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/workspace/cruddur-workspace/amplify-cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/workspace/cruddur-workspace/amplify-cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/workspace/cruddur-workspace/amplify-cli/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/workspace/cruddur-workspace/amplify-cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/workspace/cruddur-workspace/amplify-cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /workspace/cruddur-workspace/amplify-cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/workspace/cruddur-workspace/amplify-cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/workspace/cruddur-workspace/amplify-cli/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/workspace/cruddur-workspace/amplify-cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/workspace/cruddur-workspace/amplify-cli/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/workspace/cruddur-workspace/amplify-cli/node_modules/aws-sdk/lib/event_listeners.js:380:13)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'SignatureDoesNotMatch',
  time: 2023-01-13T20:42:46.963Z,
  requestId: 'ffd2a68e-6c6c-4973-ae11-d3035e32694d',
  statusCode: 403,
  retryable: false,
  retryDelay: 30.538420783654452
}
```

**Comment by omenking** [comment] 2023-01-13 20:51
Okay so I figured it out:

context.print.yellow(`accessKeyId: ${awsConfigInfo.config.accessKeyId}`);
context.print.yellow(`secretAccessKey: ${awsConfigInfo.config.secretAccessKey}`);
context.print.yellow(`secretAccessionToken: ${awsConfigInfo.config.secretAccessionToken}`);
      
So my env var for my secret is incorrectly set.
I wish this error message told us "its failing on STS, so please check your inputted key and secret"

**Comment by omenking** [comment] 2023-01-13 21:01
There we go
```
amplify init --frontend  $(jq -n --arg key "" --arg secret "" -f amplify-conf.json | jq -c '.frontend')\
             --amplify   $(jq -n --arg key "" --arg secret "" -f amplify-conf.json | jq -c '.amplify') \
             --providers $(jq -n --arg key $AWS_ACCESS_KEY_ID --arg secret $AWS_SECRET_ACCESS_KEY -f amplify-conf.json | jq -c '.providers')
             ```

**Comment by josefaidt** [comment] 2023-01-17 23:26
Hey @omenking :wave: thanks for raising this and apologies for the delay! While I think this is a great feature request to improve the logging, were you able to get this resolved and init a project with temporary credentials?

**Comment by josefaidt** [comment] 2023-01-31 21:40
Marking as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/10484, please subscribe to #10484 for further updates

**Closed by josefaidt** 2023-01-31 21:40 UTC
Labels: feature-request, pending-response, platform-config
