### ISSUE TITLE
Maximum policy size of 10240 bytes exceeded for role

### ISSUE THREAD

**Issue by sergiorodriguez82** [aws-amplify/amplify-cli#8550] opened 2021-10-26 01:51 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v12.16.1

### Amplify CLI Version

6.3.1

### What operating system are you using?

MAC

### Amplify Categories

function, api

### Amplify Commands

add, push

### Describe the bug

Hello, I have a lambda trigger that works as an audit function for my api tables. This trigger is called anytime a table is updated.
I have created the trigger with no problems using the cli, I select the model tables that I want to use, and everyting is ok.
Last week we add a couple of models. In this case, there is no way to update the trigger, so I deleted it and then re-created again.

Im getting this when pushing...
`UPDATE_FAILED functiontp2AuditTrace AWS::CloudFormation::Stack Mon Oct 25 2021 20:42:29 GMT-0500 (GMT-05:00) Embedded stack arn:aws:cloudformation:us-east-2:704766592508:stack/amplify-trialpal2web-uat-103736-functiontp2AuditTrace-1XSZMVK6PZLG9/a73100c0-35fc-11ec-ae5e-027d72036f18 was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to create: [LambdaTriggerPolicySymptomsInstanceMedicationInstance, LambdaTriggerPolicyConfDictionary]. 
`

### Expected behavior

As befero, all tables attached with the lambda function

### Reproduction steps

1. Create a model with more than 50 entities
2. Add lambda function (lambda trigger) to be called on each model

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
CREATE_FAILED               LambdaTriggerPolicyConfDictionary                                   AWS::IAM::Policy           Mon Oct 25 2021 20:42:25 GMT-0500 (GMT-05:00) Maximum policy size of 10240 bytes exceeded for role trialpal2webLambdaRoleb974c471-uat (Service: AmazonIdentityManagement; Status Code: 409; Error Code: LimitExceeded; Request ID: 49f810c5-b878-46cc-8640-2e3c501fb6c7; Proxy: null)
CREATE_FAILED               LambdaTriggerPolicySymptomsInstanceMedicationInstance               AWS::IAM::Policy           Mon Oct 25 2021 20:42:25 GMT-0500 (GMT-05:00) Maximum policy size of 10240 bytes exceeded for role trialpal2webLambdaRoleb974c471-uat (Service: AmazonIdentityManagement; Status Code: 409; Error Code: LimitExceeded; Request ID: a7c44f5b-3216-443f-82ad-e00b21d94346; Proxy: null)



```

</details>

### Additional information

This issue (or a similar one) was reported here 
https://github.com/aws-amplify/amplify-cli/issues/4004

**Comment by cjihrig** [comment] 2021-11-01 21:00
@thibaultdalban are you saying that you're exceeding the limit in a REST API, or is this related only to functions. As you pointed out, Amplify does have policy slicing in place for REST and GraphQL APIs.

**Comment by thibaultdalban** [comment] 2021-11-02 06:04
@cjihrig my issue is on REST apis only. The policy slicing is not in place for group role.

**Comment by sergiorodriguez82** [comment] 2021-11-16 14:59
> amplify push --minfiy

It doesn't work, any workaround? We need to add to all of our model entities

**Comment by sergiorodriguez82** [comment] 2021-12-09 15:53
Any news? We have 43 models/tables this quota should be reviewed, I think amplify has the potential to do much more robust systems not only Todo's examples!

**Comment by sergiorodriguez82** [comment] 2022-06-02 19:24
Any news regarding this policy limit?

**Comment by josefaidt** [comment] 2022-12-06 21:31
Hey folks apologies for the delay in responses here but we will close this as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/3815 in favor of tracking the existing item

**Closed by josefaidt** 2022-12-06 21:31 UTC
Labels: functions, feature-request, duplicate, p3
