### ISSUE TITLE
User setup fails with "Root stack creation failed: IncompleteSignature"

### ISSUE THREAD

**Issue by mlynch** [aws-amplify/amplify-cli#191] opened 2018-09-21 20:22 UTC
**Describe the bug**

When running `amplify init`, if you fail to provide the access key and secret key when choosing the set up a new user (for example, accidentally hitting "enter" without pasting the secret key first), then the next time you run `amplify init` and choose to *not* set up a new user, `init` fails as soon as you provide the secret key and does not ever prompt for the profile name.

**To Reproduce**
See above

**Expected behavior**
Should prompt for the profile name if the create user flow failed to reach that step the first time around

**Screenshots**
```
Using default provider awscloudformation
AWS access credentials can not be detected.
? Setup new user No

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? accessKeyId:   REDACTED**********
? secretAccessKey:  REDACTED********************
? region:  us-west-2
⠋ Initializing project in the cloud...An error occurred when creating the CloudFormation stack
✖ Root stack creation failed
```

There's a big `IncompleteSignature` error after this  but I'm not sure what's sensitive or not so I don't want to paste it.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] OS X 

Amplify cli version: 0.1.19

**Additional context**

**Comment by kaustavghosh06** [comment] 2018-09-21 20:45
@mlynch It seems like you don't have any AWS profiles set in your system and because of which its directly asking you to enter your access key and secret key. If it detected any existing profiles, it would have given you a list to choose from. Also, it looks like the accesskey and secret key provided doesn't have the permissions/policies to execute Cloudformation operations and that might have caused the cloudformation create execution to error out.

As recommended in our documentation out here -> https://aws-amplify.github.io/media/get_started , the correct flow would be to run the `amplify configure` command to start with, which would create an IAM user with the appropriate policies/permissions for the CLI to work with and then run `amplify init`. You would be able to select the newly created AWS profile (which has the appropriate policies required by the CLI) in this flow.

**Comment by mlynch** [comment] 2018-09-21 20:49
To be more clear, the issue is related to the disconnect between having the `amplify init` command walk me through setting up a new user, having that process fail half-way through (because I failed to enter the secret key), then not letting me set the profile the next time I run the command and select that I already have a user.

I'll push the `configure` flow for now just wanted to point out the UX issue

**Comment by kaustavghosh06** [comment] 2018-09-21 20:54
Ah, I see it now. I was able to reproduce it. 
I'll mark this as a bug and we'll work on fixing it. Thanks for pointing this out.

**Comment by iraklivaurea** [comment] 2018-10-10 14:55
Hi @kaustavghosh06 do you have any updates on this ? 
I'm having the same issue when I'm running `amplify init` in my iOS project, providing credentials via console and then I get this: 
`Initializing project in the cloud...An error occurred when creating the CloudFormation stack
✖ Root stack creation failed
init failed`

I checked CloudFormation stack create permission, and my user has it. 
<img width="741" alt="screen shot 2018-10-10 at 6 54 27 pm" src="https://user-images.githubusercontent.com/37742674/46745406-071d1880-ccbe-11e8-8741-2d85ca0e4729.png">

**Comment by kaustavghosh06** [comment] 2018-10-10 14:57
@iraklivaurea Could you send me your entire Cloudformation stacktrace?

**Comment by iraklivaurea** [comment] 2018-10-10 15:02
Sure

`⠼ Initializing project in the cloud...An error occurred when creating the CloudFormation stack
✖ Root stack creation failed
init failed
{ AccessDenied: User: ********** is not authorized to perform: cloudformation:CreateStack on resource: **********
    at Request.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/protocol/query.js:47:29)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/sequential_executor.js:109:20)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/sequential_executor.js:81:10)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/sequential_executor.js:119:18)
  message:
   'User: *************** is not authorized to perform: cloudformation:CreateStack on resource: *****************,
  code: 'AccessDenied',
  time: 2018-10-10T14:37:17.814Z,
  requestId: '*********',
  statusCode: 403,
  retryable: false,
  retryDelay: 58.27828981584724 }
An error occurred when  creating the CloudFormation stack`

@kaustavghosh06  Is this enough ?

**Comment by iraklivaurea** [comment] 2018-10-10 15:03
@kaustavghosh06  sorry for formation ...

**Comment by kaustavghosh06** [comment] 2018-10-10 15:29
@iraklivaurea Did you create the IAM user using the amplify configure command and use the created profilento initialize the project? It looks like an IAM policy issue.

**Comment by iraklivaurea** [comment] 2018-10-10 15:35
IAM was already created, but not using `amplify configure` command.

**Comment by iraklivaurea** [comment] 2018-10-11 07:01
@kaustavghosh06 Thanks

**Comment by b-tiwari** [comment] 2018-11-09 00:37
I am getting the same error
IAM has been created using `amplify configure` , which in fact opens  AWS web console on browser and asks you to create IAM from there.  I believe I have added the policies per what I AWS services want to use , but I am not sure if we need any additional permissions for amplify to successfully init.

I want to use federated identities and probably lambda services from my apps - the policies I have added to IAM are `AmazonCognitoPowerUser`, `AWSLambdaFullAccess`, `AmazonS3FullAccess`. For cloud formation access I have added inline policies as suggested [here](https://stackoverflow.com/a/45447236) . 

But getting the same error. 

Also, is there any documentation about which Permissions we should add to the IAM based on what service we plan to use?

**Comment by Purvik** [comment] 2019-03-05 13:39
@kaustavghosh06  I have configured `amplify configure` and `amplify init`. It has created IAM user on the console but still when I choose profile configured with AccessID and SecretKey It gives me this error. Please help me out.
```
Initializing project in the cloud...An error occurred when creating the CloudFormation stack
× Root stack creation failed
init failed
{ OptInRequired: The AWS Access Key Id needs a subscription for the service
    at Request.extractError (C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\node_modules\aws-sdk\lib\protocol\query.js:50:29)
    at Request.callListeners (C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\node_modules\aws-sdk\lib\request.js:685:12)
    at Request.callListeners (C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
  message: 'The AWS Access Key Id needs a subscription for the service',
  code: 'OptInRequired',
  time: 2019-03-05T13:35:57.743Z,
  requestId: '9b332cdd-3f4b-11e9-bcbc-9791fd214f40',
  statusCode: 403,
  retryable: false,
  retryDelay: 13.349160804712067 }
```

**Comment by kaustavghosh06** [comment] 2019-05-17 17:43
Hey guys, this issue has been fixed with the latest version of the CLI. Please feel free to re-open if you're still seeing this issue.

**Closed by kaustavghosh06** 2019-05-17 17:43 UTC
Labels: configure, enhancement

**Comment by arjunkalburgi** [comment] 2019-05-28 20:01
I'm having this issue, @kaustavghosh06 and I just installed amplify cli minutes ago. 

```
$ npm -v @aws-amplify/cli
6.9.0
```

How do I verify my account?

**Comment by cyrfer** [comment] 2019-06-30 15:47
Reopening.

I used a new project created with `npx create-react-app amplify-test`, followed by `npm install -g @aws-amplify/cli`, and during `amplify init` I selected an existing AWS CLI profile "default".

```

? Please choose the profile you want to use default
✖ Root stack creation failed
init failed
TypeError: Cannot redefine property: default
    at Function.defineProperty (<anonymous>)
    at /Users/jkgrant/.nvm/versions/node/v12.3.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:11:14
    at Array.forEach (<anonymous>)
    at IniLoader.parseFile (/Users/jkgrant/.nvm/versions/node/v12.3.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/shared-ini/ini-loader.
js:8:26)
    at IniLoader.loadFrom (/Users/jkgrant/.nvm/versions/node/v12.3.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:56:30)
    at Config.region (/Users/jkgrant/.nvm/versions/node/v12.3.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/node_loader.js:98:36)
    at Config.set (/Users/jkgrant/.nvm/versions/node/v12.3.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:477:39)
    at Config.<anonymous> (/Users/jkgrant/.nvm/versions/node/v12.3.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:312:12)
    at Config.each (/Users/jkgrant/.nvm/versions/node/v12.3.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/util.js:507:32)
    at new Config (/Users/jkgrant/.nvm/versions/node/v12.3.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:311:19)
```

**Comment by cyrfer** [comment] 2019-06-30 15:48
@kaustavghosh06 I need some help to re-open.

**Comment by demiro** [comment] 2019-07-05 10:19
I have the same problem.... I have the latest version (1.7.8) and did an amplify init on a completely new angular project... selected no profile, entered the accessKey id and secretAccessKey, selected eu-west-2 region and bam...

> Initializing project in the cloud...An error occurred when creating the CloudFormation stack
× Root stack creation failed
init failed
{ Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1051:34)
    at TLSSocket.emit (events.js:189:13)
    at TLSSocket.EventEmitter.emit (domain.js:441:20)
    at TLSSocket._finishInit (_tls_wrap.js:633:8)
  message: 'self signed certificate in certificate chain',
  code: 'NetworkingError',
  region: 'eu-west-2',
  hostname: 'cloudformation.eu-west-2.amazonaws.com',
  retryable: true,
  time: 2019-07-05T10:09:37.407Z }

**Comment by matfolio** [comment] 2019-07-06 10:11
I think Amplify expects you to have had an existing user with AdministrationFullAccess. This should be confirmed before running ` amplify init ` or perhaps when you run the ` amplify init ` you will be prompted if you would be using the default AWS Profile or not. In this case you might have to create the user yourself and attach a policy to the user and paste both the access and secret keys to the respective section on the console. But when you follow the steps to create a user with `amplify configure` it is so easy.

So when that is successful without displaying any error messages then you can proceed with the ` amplify init` to create a valid amplify project.

`amplify status` : to check the validity of your Amplify project.

Well that is the solution to the CloudFormation stack creation issue...

**Comment by larrybotha** [comment] 2019-07-10 18:21
@matfolio probably not great to give the user full administration access, but it's what's at least allowed me to make progress.
