### ISSUE TITLE
Add ability to create Python Functions using the CLI

### ISSUE THREAD

**Issue by dbrunet73** [aws-amplify/amplify-cli#2350] opened 2019-09-19 19:05 UTC
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**
No, it is related to us wanting to be able to use all Lambda Options when creating a function. 

**Describe the solution you'd like**
We would like to be able to choose the type of function we are creating using the CLI, Python, PHP, etc. 

**Describe alternatives you've considered**
Alternatives would be to allow custom resources to be created using the CLI. 

**Additional context**
N/A

**Comment by attilah** [comment] 2019-09-19 20:01
@dbrunet73 thanks for the feature request, I labeled it accordingly.

**Comment by kaustavghosh06** [comment] 2019-09-20 21:39
Duplicate of #1074

**Closed by kaustavghosh06** 2019-09-20 21:39 UTC
Labels: feature-request, platform
