### ISSUE TITLE
How to add username and email as required attribute for signup?

### ISSUE THREAD

**Issue by hackrx** [aws-amplify/amplify-cli#9212] opened 2021-12-03 22:40 UTC
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

Hello there! I want to know if I can 
1. Add username and email both as required attributes for signup (and birthdate too maybe).
2. After the above auth, I want to add Google as a social auth provider (this can be done using " Apply default configuration with Social Provider (Federation) ".
3. Get hostedUI something similar like this [one](https://twitter.com/_Mo_Malaka_/status/1462793473585659912/photo/1) with email, username, birthdate, and password fields (all required) on signup page.

**Amplify CLI Version** 
7.6.2
You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**
Amplify, Appsync, Cognito.

**Comment by hackrx** [comment] 2021-12-04 17:17
Alright, so once you deploy your auth, you can't update the required attributes at the time of signup. 
So I deleted my old auth, and created a new one, with these required attributes: 
```
amplify add auth                                      
Using service: Cognito, provided by: awscloudformation
 The current configured provider is Amazon Cognito. 
 
 Do you want to use the default authentication and security configuration? Default configuration with Social Provider (Federation)
 Warning: you will not be able to edit these selections. 
 How do you want users to be able to sign in? Username
 Do you want to configure advanced settings? Yes, I want to make some additional changes.
 Warning: you will not be able to edit these selections. 
 What attributes are required for signing up? Birthdate (This attribute is not supported by Login With Amazon, Signinwithapple.), Email, Gender (This
 attribute is not supported by Login With Amazon, Signinwithapple.), Name, Phone Number (This attribute is not supported by Facebook, Login With Amazon, Signinwithapple.), Picture (This attribute is not supported by Login With Amazon, Signinwithapple.)
 Do you want to enable any of the following capabilities? 
```
And I also added google as social provider for auth. 
After push, the hosted UI looks like this: 
![image](https://user-images.githubusercontent.com/54453778/144718315-88af8eea-d4b3-4823-a705-3a0e4432ae45.png)
And Sign-up like this: 
![image](https://user-images.githubusercontent.com/54453778/144718337-db32f799-e5ed-4ff7-a61c-5e45af675922.png)

There is no issue with the sign-in flow, but in the signup, as you can see, I have added `birthdate, email, picture, and phone number ` as required attributes, but it is only asking for username, picture, and password. 
Can anyone please help me to fix this, am I missing something?

**Comment by akshbhu** [comment] 2021-12-08 20:09
Hi @hackrx 

this is a bug on our side which is overwriting signup attributes. We have a PR that fixes this issue .

For the workaround , you can use overide feature add these values in the CFN template. 
Take a look here: https://docs.amplify.aws/cli/auth/override/#customize-amplify-generated-cognito-auth-resources

Closing as duplicate of : https://github.com/aws-amplify/amplify-cli/issues/9237
you can follow updates on the above issue

**Closed by akshbhu** 2021-12-08 20:09 UTC
Labels: bug, auth
