### ISSUE TITLE
Amplify commands returning ETIMEDOUT ERROR

### ISSUE THREAD

**Issue by deepbodo** [aws-amplify/amplify-cli#11952] opened 2023-02-09 05:03 UTC
### Amplify CLI Version

V10.6.1

### Question

amplify push
× There was an error pulling the backend environment dev.
🛑 connect ETIMEDOUT 52.219.194.130:443
whenever i try amplify push or publish i get this error. Everything was fine before but recently i reset my network adaptop of win 10 and after that i get this issue.

**Comment by josefaidt** [comment] 2023-02-09 17:09
Hey @deepbodo :wave: thanks for raising this! Are you working behind a corporate proxy or on a VPN?

**Comment by deepbodo** [comment] 2023-02-09 17:36
No.. And i think not only amplify even my npm is giving me ENOTFOUND error

**Comment by josefaidt** [comment] 2023-02-09 17:42
Hey @deepbodo thanks for clarifying. It seems there is an issue with the networking on your laptop, and given this is not an issue specific to Amplify and I am unable to reproduce, I will close this issue.

**Closed by josefaidt** 2023-02-09 17:42 UTC
Labels: question, pending-triage
