### ISSUE TITLE
Error setting up amplify. Project identifier: 6601cd7f3596c446f7015137dbb9fbe4

### ISSUE THREAD

**Issue by talkabouthealth** [aws-amplify/amplify-cli#12866] opened 2023-06-26 21:57 UTC
### How did you install the Amplify CLI?

brew maybe

### Amplify CLI Version

12.0.3

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Describe the bug

Command failed with exit code 64: /Users/xxx/.amplify/lib/aws-amplify-amplify-frontend-ios/resources/amplify-xcode import-config --path=/Users/xxx/My Drive (xxx@xxx.com)/code/sandbox-xcode
Error: 2 unexpected arguments: 'Drive', '(xxx@xxx@xxx.com)/code/sandbox-xcode'
Usage: amplify-xcode import-config [--path <path>]
  See 'amplify-xcode import-config --help' for more information.

### Expected behavior

no errors

### Reproduction steps

amplify init

### Project Identifier

6601cd7f3596c446f7015137dbb9fbe4

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment] 2023-06-28 17:34
Hey @talkabouthealth :wave: thanks for raising this! This appears to be a duplicate of https://github.com/aws-amplify/amplify-cli/issues/12593. I'll close this in favor of tracking the existing issue, but please subscribe/add a 👍 to the existing issue for further updates

**Closed by josefaidt** 2023-06-28 17:34 UTC
Labels: pending-triage
