### ISSUE TITLE
amplify pull fails if .aws/credentials has [sam]

### ISSUE THREAD

**Issue by dilaver** [aws-amplify/amplify-cli#7677] opened 2021-07-06 23:21 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

using curl on 2021-07-06

### If applicable, what version of Node.js are you using?

v14.16.0

### Amplify CLI Version

5.1.0

### What operating system are you using?

Mac

### Amplify Categories

Not applicable

### Amplify Commands

pull

### Describe the bug

```
% amplify pull ....
Opening link: https://us-east-2.admin.amplifyapp.com/admin/..../verify/
⠏ Continue in browser to log in…
2021-07-06T23:12:49.713Z - error: uncaughtException: Failed to receive expected authentication tokens. Error: [TypeError: Cannot redefine property: sam]
...
stack=[Error: Failed to receive expected authentication tokens. Error: [TypeError: Cannot redefine property: sam],     at /snapshot/node_modules/amplify-provider-awscloudformation/lib/utils/admin-login-server.js:100:15,     at processTicksAndRejections (internal/process/task_queues.js:97:5)]
```

### Expected behavior

Expected to get:
```
Successfully received Amplify Admin tokens.
```

### Reproduction steps

1. create section named "sam" in global aws credentials config file
2. amplify pull

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment] 2021-07-12 20:42
Hey @dilaver :wave: thanks for raising this! I was not able to reproduce this with the steps provided on the packaged binary (installed using `curl`) and with only `sam` defined in the global AWS credentials file. Is the username in Admin UI named `sam`? Do you also experience this issue with the [npm distribution](https://www.npmjs.com/package/@aws-amplify/cli)?

**Comment by josefaidt** [comment] 2021-07-12 20:42
Hey @dilaver :wave: thanks for raising this! I was not able to reproduce this with the steps provided on the packaged binary (installed using `curl`) and with only `sam` defined in the global AWS credentials file. Is the username in Admin UI named `sam`? Do you also experience this issue with the [npm distribution](https://www.npmjs.com/package/@aws-amplify/cli)?

**Comment by jhockett** [comment] 2021-07-12 20:51
Hi @dilaver, can you also let us know what browser you are using to authenticate with?

**Comment by josefaidt** [comment] 2021-07-26 16:54
Closing issue, @dilaver if you are still experiencing this issue please reply back to this thread and we can re-open to investigate further! 🙂

**Closed by josefaidt** 2021-07-26 16:54 UTC
Labels: pending-close-response-required, pending-triage, platform
