### ISSUE TITLE
Migration from v6* to v7 latest fails with [authRoleName, unauthRoleName] must have values on AdminQueries API

### ISSUE THREAD

**Issue by frankclaassen** [aws-amplify/amplify-cli#9358] opened 2021-12-21 00:39 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.16.0

### Amplify CLI Version

7.6.4

### What operating system are you using?

Mac

### Amplify Categories

auth, storage, function, api

### Amplify Commands

push

### Describe the bug

As per the documentation to migrate GQL from v1 to v2, I ran amplify migrate api which migrated my gql schema. When trying to run amplify push, it asked to migrate one of 2 rest API's but not the AdminQueries api that was added through amplify auth. When trying to run amplify push, the following error happens which causes push to fail and rollback:

UPDATE_FAILED      apiAdminQueries                AWS::CloudFormation::Stack Mon Dec 20 2021 15:38:14 GMT+0800 (Australian Western Standard Time) Parameters: [authRoleName, unauthRoleName] must have values

### Expected behavior

I expect amplify migrate function to migrate all required categories correctly and not causing failing errors when pushing updates

### Reproduction steps

1. have an existing amplify project created before latest version with auth (including admin queries api), GQL schema, Rest API, Storage, Functions
2. follow GQL migration guide (no custom resolvers etc)
3. try to push changes

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by johnpc** [comment] 2022-01-14 21:26
Can you please provide more details on how to reproduce? I attempted creating a new amplify app using v4 of the cli with all resources you mentioned, then upgraded the cli, migrated the graphql, and I was able to push successfully.

**Comment by cjihrig** [comment] 2022-02-01 19:11
Closing due to a lack of followup, but we can revisit this issue if needed.

**Closed by cjihrig** 2022-02-01 19:11 UTC
Labels: graphql-transformer, migration-issue, pending-response

**Comment by johannchen2021** [comment] 2022-05-26 03:12
@frankclaassen I encounter the same problem after migrate api from v1 to v2. Have you found any solution for the problem?

**Comment by frankclaassen** [comment] 2022-05-26 03:15
@johannchen2021 if I remember correctly I had to update auth after the migration had run to fix it

**Comment by johannchen2021** [comment] 2022-05-26 03:25
@frankclaassen Thanks, when I ran `amplify update auth`, i got this message `Updating imported Auth resource is not supported.`

**Comment by johannchen2021** [comment] 2022-05-26 03:37
but i could run amplify push without problem before the migration to v2
