### ISSUE TITLE
Transform @searchable directive generate wrong VTL response template

### ISSUE THREAD

**Issue by sakhmedbayev** [aws-amplify/amplify-cli#800] opened 2019-01-31 11:31 UTC
**Describe the bug**
 - graphql `sort` variable does not work on autogenerated VTL response template
 - the template also return `null` for the `nextToken` field

**To Reproduce**
1. Make new graphql type with `@model` and `@searchable` directive
2. `amplify push` it
3. Add several records to your DynamoDB
4. check VTL response mapping template for the search query
```
#set( $items = [] )
#foreach( $entry in $context.result.hits.hits )
  #if( !$foreach.hasNext )
    #set( $nextToken = "$entry.sort.get(0)" )
  #end
  $util.qr($items.add($entry.get("_source")))
#end
$util.toJson({
  "items": $items,
  "total": $ctx.result.hits.total,
  "nextToken": $nextToken
})
```
this value `"$entry.sort.get(0)" ` will return as a string for the `nextToken` field

5. try to use `sort` variable on the graphql query
```
{
  "filter": {
    "cleanedContent": {
      "regexp": "someText.*"
    }
  },
  "sort": {
    "field": "myField",
    "direction": "desc"
  }
}
```
 you will get this error:

```
{
  "data": {
    "searchBookEntitys": null
  },
  "errors": [
    {
      "path": [
        "searchBookEntitys"
      ],
      "data": null,
      "errorType": "Elasticsearch:UserIllegalArgumentException",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Elasticsearch responded with an error: Bad Request"
    }
  ]
}
```

**Expected behavior**
`nextToken` and `sort` variable to functiion properly

**Desktop (please complete the following information):**
 - macOS
 - amplify cli version `multienv.39`

**Comment by davidfarinha** [comment] 2019-04-24 20:55
Hello,
I'm also getting the string "$entry.sort.get(0)" incorrectly returned as my the nextToken. Is there any workaround I can use in my custom resolver to fix this in the meantime?

**Comment by SteveHoggNZ** [comment] 2019-04-24 21:11
The quotes need to be removed from around the nextToken

i.e.

```
"$entry.sort.get(0)"
```

Should be:

```
$entry.sort.get(0)
```

You could do a pull request for the fix, or use a custom template for the time being.

**Comment by davidfarinha** [comment] 2019-04-24 22:26
This doesn't seem to work, there's no "sort" field in the Elasticsearch response (see below) so `$entry.sort.get(0)` in the response mapping always causes "nextToken" to be null. 
'
{
    "errors": [],
    "mappingTemplateType": "Response Mapping",
    "path": "[searchUsers]",
    "context": {
        "arguments": {
            "filter": {
                "id": {
                    "ne": "cd82d03b-4d79-4fd4-bfea-b856cb86f3c7"
                }
            }
        },
        "result": {
            "took": 2,
            "timed_out": false,
            "_shards": {
                "total": 5,
                "successful": 5,
                "skipped": 0,
                "failed": 0
            },
            "hits": {
                "total": 30,
                "max_score": 1,
                "hits": [
                    {
                        "_index": "user",
                        "_type": "doc",
                        "_id": "bf37c7a7-00e7-4419-ba05-ffb7370c174a",
                        "_score": 1,
                        "_source": {
                            (user data etc)
                        }
                    },
                    (etc)
                ]
            }
        },
        "stash": {},
        "outErrors": []
    },
    "fieldInError": false
}
'
Apparently [this is a known issue](https://github.com/aws-amplify/amplify-js/issues/2586#issuecomment-464419116).

**Comment by brookslyrette** [comment] 2019-07-24 11:37
Is there a workaround to get sort working for Elasticsearch entities while waiting for this fix?

**Comment by SwaySway** [comment] 2019-08-13 16:21
Closing this issue as the pr has been merged

**Comment by houmark** [comment] 2019-08-18 03:29
@SwaySway These changes seem to have broken sorting for a pretty standard search query for us. We had the below query running for more than a month with no issues, but updating various AWS libraries recently, the query broke.

My query is pretty simple:

```graphql
query SearchApplications {
  searchApplications(
    limit: 999,
    sort: {
      field: createdAt,
      direction: desc
    },
    filter: {
      status: {eq:"NEW"}
    },
  ) {
    nextToken
    items {
      id
      name
      email
      createdAt
    }
  }
}
```

`createdAt` is a required `AWSDateTime` but having that field as the sort field I get this error:

```graphql
{
  "data": {
    "searchApplications": null
  },
  "errors": [
    {
      "path": [
        "searchApplications"
      ],
      "data": null,
      "errorType": "Elasticsearch:UserIllegalArgumentException",
      "errorInfo": null,
      "locations": [
        {
          "line": 81,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Elasticsearch responded with an error: Bad Request"
    }
  ]
}
```

Changing `createdAt` to another field fixes the problem, but I need my items listed by the creation date DESC.

**Comment by SwaySway** [comment] 2019-08-29 18:56
Hi @houmark in the resolver for elasticsearch the response is outputting nextToken in the form of a string (though it should get evaluated at runtime):
- ` #set( $nextToken = "$entry.sort.get(0)" )`  

Can you send an email to amplify-cli@amazon.com with your schema included?
What field are you searching on?
```gql
query SearchToDo {
  searchTodos(
    limit: 100
    sort: {
    field: id
    direction: desc
  }) {
    items {
      name
      createdAt
      description
    }
    nextToken
  }
}
```

**Comment by houmark** [comment] 2019-08-29 19:27
I can send that, but I did a `console.log({nextToken});` of nextToken at runtime and it displays:

`{nextToken: "$entry.sort.get(0)"}`

To be honest, right now I am not sure if my dev is running on 1.12.0 or 2.0.0, considering the issues with the Console. I will return to this as soon as that is solved because this was buggy in 1.12.0 but should be fixed in 2.0.0 right?

**Comment by SwaySway** [comment] 2019-08-29 20:56
Whether the `"$entry.sort.get(0)"` has quotes on it shouldn't effect the variable itself rather within the responses coming from elasticsearch it may not have sort specified in the response.
I want to confirm if this is the case. Are you able to do a query on your dev env on a different field? Also if possible, edit the resolver in the console so the quotations are removed. If they are removed and the value returns null then this is the case.

**Comment by houmark** [comment] 2019-08-29 20:58
Thanks, I will get into this later tonight once I have the Console issue tested because this could be a mix of both. I also have a deadline that I need to meet today, and all these issues have delayed me so much.

**Comment by houmark** [comment] 2019-08-29 23:43
I was looking in the AppSync Console for the search resolver, but I cannot seem to find it. I have not done custom resolvers or modified any resolvers before, so I'm not very familiar with this part.

I entered Schema and on the right side I looked through the list, and while I found a few resolvers, I did not find the search specific one, and many places it will say "Attach" in the Resolver column.

Not sure how I can continue debugging on this part if I cannot find the resolver.

**Comment by SwaySway** [comment] 2019-08-30 00:37
It should in the API your working with under schema from there you can search for resolvers by entering `query`. The resolver datasource would be ElasticSearchDomain. Screenshot included below
![image](https://user-images.githubusercontent.com/7465495/63985256-8dcc1700-ca83-11e9-9196-2f85bfb3cec6.png)

**Comment by SwaySway** [comment] 2019-08-30 00:53
The request resolver is viewable from there it would look something like
```gql
#set( $items = [] )
#foreach( $entry in $context.result.hits.hits )
  #if( !$foreach.hasNext )
    #set( $nextToken = "$entry.sort.get(0)" )
  #end
  $util.qr($items.add($entry.get("_source")))
#end
$util.toJson({
  "items": $items,
  "total": $ctx.result.hits.total,
  "nextToken": $nextToken
})
```

**Comment by houmark** [comment] 2019-08-30 00:54
Found it. The search in that interface is pretty useless. I search for my model name, and expect everything related to that model will show including the ElasticSearchDomain resolver. It did not. I searched for ElasticSearchDomain or just "elastic" and same result, nothing found. Searching "query" did find it though. That UI is also freezing up for close to one minute when loading the Schema the first time. Where should I report both of these?

My ElasticSearchDomain resolver response template is:
```
#set( $items = [] )
#foreach( $entry in $context.result.hits.hits )
  #if( !$foreach.hasNext )
    #set( $nextToken = "$entry.sort.get(0)" )
  #end
  $util.qr($items.add($entry.get("_source")))
#end
$util.toJson({
  "items": $items,
  "total": $ctx.result.hits.total,
  "nextToken": $nextToken
})
```

I wish I had found this resolver before I did the new push (related to the Console issue I have at this time), but I will continue testing once I have confirmed the Console can deploy and I have that solved with a forced API change and push from the CLI.

**Comment by houmark** [comment] 2019-08-30 00:57
> The request resolver is viewable from there it would look something like

I think for less confusion you should refer to this as the "response template" in the ElasticSearchDomain resolver as there's also a "request template".

**Comment by SwaySway** [comment] 2019-08-30 01:03
I believe you can submit a report on the [AppSync Forum](https://forums.aws.amazon.com/forum.jspa?forumID=280&start=0).

If you remove the quotations (save the resolver) and run the query in the console (under Queries). Would it still return null or return a value?

**Comment by houmark** [comment] 2019-08-30 01:18
Result before changing the resolve response template:
<a href="https://cl.ly/a09aea" target="_blank"><img src="https://d3vv6lp55qjaqc.cloudfront.net/items/2W2f121o0m0t2v3y0p0n/Image%202019-08-29%20at%208.14.44%20PM.png" style="display: block;height: auto;width: 100%;"/></a>

After changing it:
<a href="https://cl.ly/37d2b5" target="_blank"><img src="https://d3vv6lp55qjaqc.cloudfront.net/items/2N3F2F0M1g0g0B040G2u/Image%202019-08-29%20at%208.15.19%20PM.png" style="display: block;height: auto;width: 100%;"/></a>

After should not be `null` as there's around 600 items and I was limiting to 10, so I should get a nextToken to be able to fetch more items.

So, what's next?

**Comment by SwaySway** [comment] 2019-08-30 01:26
Could you also share the request mapping template?

**Comment by houmark** [comment] 2019-08-30 01:29
Yes, here you go:

(I modified the name of the numberFields for privacy)

```
#set( $indexPath = "/application/doc/_search" )
#set( $numberFields = ["field1", "field2", "deleted"] )
{
  "version": "2017-02-28",
  "operation": "GET",
  "path": "$indexPath",
  "params": {
      "body":     {
                #if( $context.args.nextToken )"search_after": ["$context.args.nextToken"], #end
                "size": #if( $context.args.limit ) $context.args.limit #else 10 #end,
                "sort": #if( $context.args.sort )
  [#if( !$util.isNullOrEmpty($context.args.sort.field) && !$util.isNullOrEmpty($context.args.sort.direction) )
  {#if($numberFields.contains($context.args.sort.field))                                    
"$context.args.sort.field" #else "${context.args.sort.field}.keyword" #end : {
                                        "order": "$context.args.sort.direction"
                                    }
                                }
#end]
#else
  []
#end,
                "query": #if( $context.args.filter )
$util.transform.toElasticsearchQueryDSL($ctx.args.filter)
#else
{
      "match_all": {}
  }
#end
                }
  }
}
```

**Comment by SwaySway** [comment] 2019-08-30 01:32
Can you provide the query as well?

**Comment by houmark** [comment] 2019-08-30 01:37
Then you'd also need the model I guess?

My query is dynamic and built depending on selections in the UI, but I have the following simple test query:

```graphql
query SearchApplications {
  searchApplications(
    limit: 10,
  ) {
    nextToken
    items {
      id
      firstName
      updatedAt
    }
  }
}
```

**Comment by SwaySway** [comment] 2019-08-30 01:52
What seems to be missing in ES response is the sort list where the first element is used as the nextToken.

Could you send us an email of your schema? amplify-cli@amazon.com
We'll see if we can replicate the issue.
For better error handling I'll submit a PR shortly to remove the quotations.

```json
{
  "_shards": {
    "failed": 0,
    "skipped": 0,
    "successful": 5,
    "total": 5
  },
  "hits": {
    "hits": [
      {
        "_id": "someID",
        "_index": "todo",
        "_score": null,
        "_source": {
          "__typename": "Todo",
          "createdAt": "2019-08-28T20:52:54.623Z",
          "description": "myitemdescription201",
          "id": "...",
          "name": "myitem201",
          "otherField": "2019-08-29",
          "updatedAt": "2019-08-28T20:52:54.623Z"
        },
        "_type": "doc",
        "sort": [
          1567025574623
        ]
      },
     ...
   ]
}
```

**Comment by houmark** [comment] 2019-08-30 01:57
Just schema.graphql right? Will do in a bit! Please reply to the email so I know you got it.

**Comment by houmark** [comment] 2019-08-30 01:59
Email sent!

**Comment by SwaySway** [comment] 2019-08-30 17:25
Hi @houmark could you try the following query?
```gql
query SearchApplications {
  searchApplications(
    sort: {
      field: id
      direction: desc
    }
    limit: 10,
  ) {
    nextToken
    items {
      id
      firstName
      updatedAt
    }
  }
}
```
ES search_after depends on sort (field and direction) in order to return nextToken, which is used to return the next set of results after the index specified in `$entry.sort.get(0)` .
Somethings to follow up from this is add a default option for `sort.field` and `sort.direction` if they are not specified in the query.
In the meantime until #2090 is released you can add the `createdAt` field in the following request resolver template (from the pr) and add that in file within the following path of your amplify project `amplify/backend/api/<api_name>/resolvers/Query.searchApplications.req.vtl`. This will override the created resolver.

```gql
#set( $indexPath = "/application/doc/_search" )
#set( $nonKeywordFields = ["createdAt",....]

{
  "version": "2017-02-28",
  "operation": "GET",
  "path": "$indexPath",
  "params": {
      "body": {
      	#if( $context.args.nextToken )"search_after": ["$context.args.nextToken"], #end
        "size": #if( $context.args.limit ) $context.args.limit #else 10 #end,
        "sort": #if( $context.args.sort )
  			[#if( !$util.isNullOrEmpty($context.args.sort.field) && !$util.isNullOrEmpty($context.args.sort.direction) )
  				{#if($nonKeywordFields.contains($context.args.sort.field))                                    
					"$context.args.sort.field" #else "${context.args.sort.field}.keyword" #end : {
                                        "order": "$context.args.sort.direction"
                                    }
                                }
				#end]
				#else
  				[]
				#end,
		"query": #if( $context.args.filter ) $util.transform.toElasticsearchQueryDSL($ctx.args.filter)
				#else {
                	"match_all": {}
                    }
				#end
			}
  	}
}
```

**Comment by houmark** [comment] 2019-08-30 17:49
@SwaySway The query works and returns a `nextToken` (ID of the last returned record in the current query) and it makes sense. How that was not covered in AWS tests does not make sense though :)

I will continue to change the template and update you again, and as I understand it (please confirm), adding this resolver locally, will also make sure it's not overridden by the default one on every deploy right? This means I can run with this custom resolver until #2090 is released and then remove it after testing that that PR fixes it.

**Comment by houmark** [comment] 2019-08-30 18:15
@SwaySway Question. Do I drop the line:

`#set( $numberFields = ["myField1", "myField2", "deleted"] )`

And if I do, do these fields go into the new line?
`#set( $nonKeywordFields = ["createdAt",....]`

**Comment by SwaySway** [comment] 2019-08-30 18:29
> I will continue to change the template and update you again, and as I understand it (please confirm), adding this resolver locally, will also make sure it's not overridden by the default one on every deploy right? This means I can run with this custom resolver until #2090 is released and then remove it after testing that that PR fixes it.

Yes it will override the resolver generated in `build/`, though it needs the same name for the override to happen. You can confirm this by doing `amplify api gql-compile` and checking the build folder for something like `Query.searchApplications.req.vtl` (basing this name on the query you provided in this thread)

> `#set( $numberFields = ["myField1", "myField2", "deleted"] )`
> 
> And if I do, do these fields go into the new line?
> `#set( $nonKeywordFields = ["createdAt",....]`

You can use the existing request resolver template in your project and add any date fields (from the type that has `@searchable`) in that list, such as createdAt.

**Comment by houmark** [comment] 2019-08-30 18:38
OK, will do. It looks like `$numberFields` is not used in the code though and has been replaced by `$nonKeywordFields`.

**Comment by houmark** [comment] 2019-08-30 20:09
That was a partial success. I got it working and sorting with *some* date fields. And the nextToken seems to be working also — that is when it does not throw an error.

As you can see in the`schema.graphql` I sent in, I have a field called `signupDate` which is `AWSDateTime` just like many other fields in that model.

Sorting using this field breaks my query. I am not sure if this is because this field is not always present in any doc or if there's something else going on specific to my data set. As you can imagine, some fields have been added later, and thus they may not have a value for a few items in the database or maybe Elasticsearch did not catch the addition of this field for some reason?

The error I get when sorting on `signupDate` `desc` (also happens with `asc` of course) — which is not very helpful one:

```
{
  "data": {
    "searchApplications": null
  },
  "errors": [
    {
      "path": [
        "searchApplications"
      ],
      "data": null,
      "errorType": "Elasticsearch:UserIllegalArgumentException",
      "errorInfo": null,
      "locations": [
        {
          "line": 81,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Elasticsearch responded with an error: Bad Request"
    }
  ]
}
```

I will continue to debug on this one, but most other date fields do work, while one or two other date fields are reacting the same as the the `signupDate`. If you have any hints, please do let me know.

**Comment by houmark** [comment] 2019-08-30 20:16
So, looking at `Indices` -> Mappings in the Elasticsearch console I found what seems to be the reason:

```
rejectDate date
signupDate text
submittedAt date
```

As you can see, Elasticsearch thinks `signupDate` is a text field. How it got to that, I don't know. How I change that, I don't know. My production Elasticsearch shows `date` for that field, so this is only affecting my development environment.

Any hints?

**Comment by houmark** [comment] 2019-08-30 20:16
@SwaySway forgot to mention you, but that should not be needed I think...

**Comment by SwaySway** [comment] 2019-08-30 22:04
Within your development environment in the custom resolver you can remove signupDate from the your numberFields list. This would append the `.keyword` to signupDate when doing a query.
As elasticsearch uses the [keyword datatype](https://www.elastic.co/guide/en/elasticsearch/reference/master/keyword.html) when querying on text fields.

**Comment by houmark** [comment] 2019-08-30 22:14
Hmm, I don't have signupDate in the numberFields list anymore. I only have Int type fields.

Is it not possible to update the Mappings to change from text to date?

**Comment by SwaySway** [comment] 2019-08-30 22:42
It is possible to change mapping though this would involve a [reindex](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html) to avoid having issues with your previous entries under that field.

If the field is not in the custom request resolver then it should append the `.keyword`. It could be that es did not register it as a text field. If you add it to the list does the query go through?

**Comment by houmark** [comment] 2019-08-30 23:01
I'm not sure I follow anymore.

The field is not in the `$numberFields` anymore. I don't think it ever was, but can't be sure. **It is in the `$nonKeywordFields` list**  together with about 10 other date fields. All the other ones work.

Can you direct me to where I can verify this better? Not sure where I'd find `.keyword` for example?

Reindex does seem complicated in relation to the way DynamoDB is triggering the data changes.

**Comment by SwaySway** [comment] 2019-08-31 00:21
Are you using the request resolver I provided in the thread above as the custom resolver? (the custom resolver which is overriding the request resolver template). If so try a query with `signUpDate` removed from the `$nonKeywordFields` list. This list should also include the values in previous resolver which used `$numberFields`.

To add some context on keyword:
This is a type which is added to text fields.
For example below is a snippet of a mapping based on a todo schema in elasticsearch
schema
```gql
type Todo @model @searchable {
  id: ID!
  name: String!
  createdAt: AWSDateTime
  description: String
}
```
mapping in elastic search
```
{
  "todo": {
    "mappings": {
      "doc": {
        "properties": {
          "__typename": {
            "fields": {
              "keyword": {
                "ignore_above": 256,
                "type": "keyword"
              }
            },
            "type": "text"
          },
          "createdAt": { # AWSDatetime converted to elasticsearch date
            "type": "date"
          },
          "description": { # String converted to a text type which also includes keyword type
            "fields": {
              "keyword": {
                "ignore_above": 256,
                "type": "keyword"
              }
            },
            "type": "text"
          },
          "id": { # ID type which gets serialized into a string and converted to a text type
            "fields": {
              "keyword": {
                "ignore_above": 256,
                "type": "keyword"
              }
            },
            "type": "text"
          },
...
```
When we are sorting using text fields it is best to use include `sort: id.keyword` in the query against elasticsearch. Some docs which can explain this I've linked below

- ["Use the my_field.keyword field for aggregations, sorting, or in scripts"](https://www.elastic.co/guide/en/elasticsearch/reference/current/fielddata.html#before-enabling-fielddata)
- [ES Docs get mapping api](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-mapping.html)

You can view your mappings from the aws console or calling the service directly using code.
An example would be this gist of a python script which is detailed from aws docs. Which can be used to get the mapping or run a query against es.
 - [es python script](https://gist.github.com/SwaySway/8795ca61f0ca173aa1682179ab63f30e)

**Comment by houmark** [comment] 2019-08-31 00:54
Interesting.

The `.keyword` did not work for me in quick testing. That just breaks the query. Not sure if I am doing it wrong.

I am using the custom resolver from before. Unless CLI 3.0.0 changed or fixed any of this, then none of this would have worked unless I have the custom request template.

I now removed `signupDate` from the  `$nonKeywordFields` array and now it's no longer throwing errors, and that makes sense, since ES thinks this should be a text field.

**BUT**, now `nextToken` is once again `{nextToken: "$entry.sort.get(0)"}` which I believe is wrong as this should always have a value, even if there's only one page (I have only one item in the dev env with  this field, and this is not broken in prod as prod has signupDate correctly as date but I may continue to create more to verify this).

But as I understand this, I need to get ES to see this field as a date field somehow, because as long as it stays text, I will not get it working correctly, and my prod is also correct, so I need this to align up. Thanks for the scripts to read the mappings, I will try them out, but the question remains, how can I force the field keyword / type update without a reindex? Or does any boilerplate code exist to do this?

**Comment by SwaySway** [comment] 2019-09-05 01:12
It's not possible to update the index mapping for an existing field.
As another followup to this is, we will look into adding reindexing when a change in the schema is made.

I created this gist for a [reindexing python script](https://gist.github.com/SwaySway/41548b31f48b00dc18080c08d1583601).
Where I change an index, named todo, mapping field, timeField, from text to date.

**Comment by houmark** [comment] 2019-09-05 01:24
Thanks @SwaySway — that's a decent workaround for now and can at least fix a situation like mine it seems.

One question; My python is no good, but I do have python locally on my Mac. Would that work or should manually create a Lambda and paste in the code and run it from there?

**Comment by SwaySway** [comment] 2019-09-05 17:39
It should work locally as well you can install the dependencies the script has, via pip install, and run it locally. Is the version python3?

**Comment by SwaySway** [comment] 2019-10-03 19:40
Closing this issue as this fixed has been merged and released.

**Closed by SwaySway** 2019-10-03 19:40 UTC
Labels: bug, graphql-transformer

**Comment by jcarreon808** [comment] 2020-05-15 16:51
Having a similar issue with this but the sort field type is type Boolean. I getting results from the first query but the nextToken that is returned is "1" (`nextToken: "1"`) which returns no results on the next query.
