### ISSUE TITLE
Trying to push the new models in AWS amplify. And I never got this error in windows and but in ubuntu this error shows up. 

### ISSUE THREAD

**Issue by sourabpramanik** [aws-amplify/amplify-cli#5772] opened 2020-11-04 04:27 UTC
```
sourab@sourab-HP-245-G4-Notebook-PC:~/projects/chat/xenon-chat0.2$ amplify push
✔ Successfully pulled backend environment dev from the cloud.

Current Environment: dev

| Category | Resource name       | Operation | Provider plugin   |
| -------- | ------------------- | --------- | ----------------- |
| Api      | xenonchat02         | Create    | awscloudformation |
| Auth     | xenonchat02a4fa9757 | No Change | awscloudformation |
? Are you sure you want to continue? Yes

The following types do not have '@auth' enabled. Consider using @auth with @model
	 - User
Learn more about @auth here: https://docs.amplify.aws/cli/graphql-transformer/directives#auth


GraphQL schema compiled successfully.

Edit your schema at /home/sourab/projects/chat/xenon-chat0.2/amplify/backend/api/xenonchat02/schema.graphql or place .graphql files in a directory at /home/sourab/projects/chat/xenon-chat0.2/amplify/backend/api/xenonchat02/schema
? Do you want to update code for your updated GraphQL API Yes
? Do you want to generate GraphQL statements (queries, mutations and subscription) based on your schema types?
This will overwrite your current graphql queries, mutations and subscriptions Yes
⠙ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS amplify-xenonchat02-dev-223755 AWS::CloudFormation::Stack Wed Nov 04 2020 00:19:03 GMT+0530 (India Standard Time) User Initiated
UPDATE_IN_PROGRESS authxenonchat02a4fa9757        AWS::CloudFormation::Stack Wed Nov 04 2020 00:19:09 GMT+0530 (India Standard Time)               
⠙ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE authxenonchat02a4fa9757 AWS::CloudFormation::Stack Wed Nov 04 2020 00:19:10 GMT+0530 (India Standard Time) 
⠋ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS apixenonchat02 AWS::CloudFormation::Stack Wed Nov 04 2020 00:19:12 GMT+0530 (India Standard Time) 
⠴ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS amplify-xenonchat02-dev-223755-apixenonchat02-113O83ENZ7MKU AWS::CloudFormation::Stack Wed Nov 04 2020 00:19:13 GMT+0530 (India Standard Time) User Initiated
⠸ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS User AWS::CloudFormation::Stack Wed Nov 04 2020 00:19:19 GMT+0530 (India Standard Time) 
UPDATE_COMPLETE    User AWS::CloudFormation::Stack Wed Nov 04 2020 00:19:20 GMT+0530 (India Standard Time) 
⠴ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS CustomResourcesjson AWS::CloudFormation::Stack Wed Nov 04 2020 00:19:23 GMT+0530 (India Standard Time) 
⠇ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE CustomResourcesjson AWS::CloudFormation::Stack Wed Nov 04 2020 00:19:23 GMT+0530 (India Standard Time) 
⠧ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE_CLEANUP_IN_PROGRESS amplify-xenonchat02-dev-223755-apixenonchat02-113O83ENZ7MKU AWS::CloudFormation::Stack Wed Nov 04 2020 00:19:26 GMT+0530 (India Standard Time) 
⠼ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE apixenonchat02 AWS::CloudFormation::Stack Wed Nov 04 2020 00:19:35 GMT+0530 (India Standard Time) 
⠴ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE_CLEANUP_IN_PROGRESS amplify-xenonchat02-dev-223755 AWS::CloudFormation::Stack Wed Nov 04 2020 00:19:38 GMT+0530 (India Standard Time) 
⠇ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE apixenonchat02                 AWS::CloudFormation::Stack Wed Nov 04 2020 00:19:49 GMT+0530 (India Standard Time) 
UPDATE_COMPLETE authxenonchat02a4fa9757        AWS::CloudFormation::Stack Wed Nov 04 2020 00:19:50 GMT+0530 (India Standard Time) 
UPDATE_COMPLETE amplify-xenonchat02-dev-223755 AWS::CloudFormation::Stack Wed Nov 04 2020 00:19:51 GMT+0530 (India Standard Time) 
✖ An error occurred when pushing the resources to the cloud

EACCES: permission denied, open '../../../../../graphql/schema.json'
An error occurred during the push operation: EACCES: permission denied, open '../../../../../graphql/schema.json'
```

**Comment by akshbhu** [comment] 2020-11-04 17:18
Hi @sourabpramanik 

Can you check if the folder schema.json user permissions from which you are logged in ?. AFAIK you can use ```chown``` to add permissions to the user for the project folder.
Let me know if this works for you.

One more question , Is this happened for first time on ubuntu or have you uploaded successfully before?

**Comment by sourabpramanik** [comment] 2020-11-10 10:40
First time in Ubuntu

**Comment by iquabius** [comment] 2020-12-12 00:05
I've got a similar error on Elementary OS, a distribution based on Ubuntu 18.04.

The difference is that it's trying to create a `/graphql` directory. Why would it try to create that directory at root level?

```sh
✖ An error occurred when pushing the resources to the cloud

EACCES: permission denied, mkdir '/graphql'
An error occurred during the push operation: EACCES: permission denied, mkdir '/graphql'
```

**Comment by kaustavghosh06** [comment] 2021-01-27 00:06
Closing as duplicate of https://github.com/aws-amplify/amplify-cli/issues/5483
Workaround mentioned here - https://github.com/aws-amplify/amplify-cli/issues/5483#issuecomment-714418681

**Closed by kaustavghosh06** 2021-01-27 00:06 UTC
Labels: pending-response, pending-triage, platform
