### ISSUE TITLE
New angular app throws "TypeError: Cannot read property 'projectPath' of undefined" on amplify init

### ISSUE THREAD

**Issue by Lard4** [aws-amplify/amplify-cli#7060] opened 2021-04-12 03:39 UTC
**Which Category is your question related to?**
amplify init

**Amplify CLI Version** 
4.47.1

**What AWS Services are you utilizing?**
Amplify

**Provide additional details e.g. code snippets**
I created a brand new angular app by doing 
`npx -p @angular/cli ng new amplify-app`

Then changed into that directory. Then, running amplify-init results in the following error:
```
$: amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project amplifyapp
The following configuration will be applied:

Project information
| Name: amplifyapp
| Environment: dev
| Default editor: Visual Studio Code
| App type: javascript
TypeError: Cannot read property 'projectPath' of undefined
    at getAngularConfig (/snapshot/node_modules/amplify-frontend-javascript/lib/framework-config-mapping.js:57:52)
    at getProjectConfiguration (/snapshot/node_modules/amplify-frontend-javascript/lib/framework-config-mapping.js:85:14)
    at Object.displayFrontendDefaults (/snapshot/node_modules/amplify-frontend-javascript/lib/configuration-manager.js:173:32)
    at Object.displayFrontendDefaults (/snapshot/node_modules/amplify-frontend-javascript/index.js:40:24)
    at displayAndSetDefaults (/snapshot/node_modules/@aws-amplify/cli/lib/init-steps/s0-analyzeProject.js:83:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async analyzeProject (/snapshot/node_modules/@aws-amplify/cli/lib/init-steps/s0-analyzeProject.js:99:9)
    at async Object.run (/snapshot/node_modules/@aws-amplify/cli/lib/commands/init.js:29:13)
    at async Object.executeAmplifyCommand (/snapshot/node_modules/@aws-amplify/cli/lib/index.js:236:9)
    at async executePluginModuleCommand (/snapshot/node_modules/@aws-amplify/cli/lib/execution-manager.js:164:5)
    at async Object.executeCommand (/snapshot/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/snapshot/node_modules/@aws-amplify/cli/lib/index.js:112:9)

```

I've been poking at this with my team for hours, and we can't seem to find any fixes. We're running on macOS Big Sur 11.1 and using bash

**Comment by kaustavghosh06** [comment] 2021-04-12 03:57
Closing as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/7060
You can use default mac terminal/zsh to get around this as mentioned in the issue above while we investigate this issue.

**Closed by kaustavghosh06** 2021-04-12 03:57 UTC
Labels: question

**Comment by Lard4** [comment] 2021-04-12 03:58
> duplicate of #7060
this is #7060

**Comment by Lard4** [comment] 2021-04-12 04:01
Also, using zsh does not remedy this. I get the same error.

**Comment by kaustavghosh06** [comment] 2021-04-12 04:04
How did you install the CLI? Was it installed globally using - `npm install -g @aws-amplify/cli` ?

**Comment by Lard4** [comment] 2021-04-12 04:07
Yes, I did `npm install -g @aws-amplify/cli`. My version is up to date too, as `amplify -v` returns 4.47.1

**Comment by kaustavghosh06** [comment] 2021-04-12 04:10
While we investigate this issue, you can install an older version of the CLI using this command - `npm install -g @aws-amplify/cli@4.46.1`
