### ISSUE TITLE
How to add adminQueries for multiple groups in Amplify?

### ISSUE THREAD

**Issue by AshwanthMadhav** [aws-amplify/amplify-cli#6712] opened 2021-02-23 09:12 UTC
When calling an Admin Queries using amplify, it gives an error

`User does not have permissions to perform administrative tasks`
There are two type groups, admins and subAdmins.

When I tried to update the permission for AdminQueries Auth, I can select only one group.

I need to access this AdminQueries using both groups.

Is it possible in Amplify?

**Comment by kldeb** [comment] 2021-02-23 16:48
You can hack the cloud formation template after it's created or the function itself to get it to work. 

You just have to keep track of later updates that could revert your changes and you would have to watch those files.

**Comment by akshbhu** [comment] 2021-02-23 19:12
Hi @AshwanthMadhav 

you can do ```amplify update auth``` and when prompt for:
```
? Select the group to restrict access with: (Use arrow keys)
❯ admin 
  test1 
  test2 
```
select the group that you want to restrict access or you can just select No if you want your adminQueries to access all userPool groups.

**Comment by akshbhu** [comment] 2021-03-02 19:02
Closing as duplicate of https://github.com/aws-amplify/amplify-cli/issues/6716

**Closed by akshbhu** 2021-03-02 19:02 UTC
Labels: auth, enhancement
