### ISSUE TITLE
/src/graphql/subscriptions.ts: Field "onDeleteUserTip" argument "owner" of type "String!" is required but not provided.

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-cli#2807] opened 2019-11-22 06:23 UTC
I have had to remove one or 2 auth directives on models as Amplify breaks saying the policy is too large.
In doing so I now get these errors when the codegen runs:

> > /Ariba/src/graphql/queries.ts: Field "onDeleteDailyPromotions" argument "owner" of type "String!" is required but not provided.
> .../Ariba/src/graphql/queries.ts: Field "onCreateTimeline" argument "owner" of type "String!" is required but not provided.
This is a snippet and this goes on for line after line - I did update amplify cli this morning so I presume thats caused this

I never added the owner field as Amplify is supposed to do that.

Any ideas?

**Comment by oliverandersencox** [comment] 2019-11-22 15:56
@kaustavghosh06 any idea on this, everything pushes fine, but the api codegen always breaks and therefore I cant use any of the models already in my app

**Comment by oliverandersencox** [comment] 2019-11-22 17:12
to get past this i have had to add '(subscriptions: null)' to all my models and it now works which is good for now, but ideally a fix would be great

**Comment by sivajag** [comment] 2019-11-24 16:23
Can you share what is your schema.graphql looks like? I am having similar problem, mainly when I use @auth

**Comment by oliverandersencox** [comment] 2019-11-25 07:38
so it turned out to be another amplify muck up. I added the subscription:null to the directive and it fixed everything but the auth system was still broken.

Running amplify update auth followed by amplify push fixed this.

Let me know if that works.

**Comment by attilah** [comment] 2019-12-09 19:07
Closing as the root cause solved.

**Closed by attilah** 2019-12-09 19:07 UTC

**Comment by oliverandersencox** [comment] 2019-12-21 08:00
@attilah this is still happening for me. I am on the most recent amplify

**Comment by oliverandersencox** [comment] 2020-01-06 20:50
@attilah this is an ongoing problem. Can i get any info as to how to solve this. My model is as follows and I would like to be able to subscribe to message created.

```
type Message @model
  @auth(rules: [
    { allow: owner },
    { allow: groups, groups: ["users"], operations: [read] },
    { allow: public, provider: iam, operations: [read] }
    { allow: owner, ownerField: "author" },
    { allow: owner, ownerField: "user" },
  ])
@key(name: "messageConvoKey", fields: ["messageConversationId", "createdAt"], queryField: "messagesByConvo") 
{
  id: ID!
  messageConversationId: ID!
  conversation: ConvoLink @connection(name: "ConvoMsgs")
  content: String!
  contentType: String
  author: ID!
  user: ID!
  status: String
  createdAt: Float!
  updatedAt: Float!
}
```
