### ISSUE TITLE
CLI change broke clients - Pinpoint GetUserEndpoints

### ISSUE THREAD

**Issue by royjit** [aws-amplify/amplify-cli#6608] opened 2021-02-12 17:05 UTC
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

Pinpoint

**Amplify CLI Version** 

4.41.2

**What AWS Services are you utilizing?**

Pinpoint

**Provide additional details e.g. code snippets**

Customers are enquiring about some recent change in CLI - https://github.com/aws-amplify/amplify-cli/pull/5918
https://github.com/aws-amplify/amplify-ios/issues/946

Can you please provide any documentation or explanation on why this change was made. This has broken the current customer experience, what is the work around.

**Comment by SwaySway** [comment] 2021-02-15 23:28
Closing as duplicate of https://github.com/aws-amplify/amplify-ios/issues/946

**Closed by SwaySway** 2021-02-15 23:28 UTC

**Comment by lawmicha** [comment] 2021-03-01 04:20
can this be reopened? https://github.com/aws-amplify/amplify-ios/issues/946 is tracking the resolution of this issue, not an duplicate
