### ISSUE TITLE
Stop asking social provider keys after amplify pull

### ISSUE THREAD

**Issue by avlonder** [aws-amplify/amplify-cli#6481] opened 2021-01-26 13:37 UTC
If I run *amplify pull*, the CLI asks for social provider ids and secrets, even though they're already set up in the cloud, so I don't see a reason why we should re-submit this.

CLI version: 4.41.2

**Comment by ammarkarachi** [comment] 2021-01-26 16:56
@avlonder This issue looks like a duplicate of https://github.com/aws-amplify/amplify-cli/issues/6430. Please follow that one for updates closing this issue for now

**Closed by ammarkarachi** 2021-01-26 16:56 UTC
Labels: auth, duplicate

**Comment by avlonder** [comment] 2021-01-26 21:07
I agree that there is some similarity between both feature requests, but I think mine is even more basic: if you run *amplify pull*, this means that the backend is already set up and already contains your Oauth credentials, so why should the CLI ask to resubmit them? I fully understand that you're asking the credentials upon running *amplify init*. So I basically disagree with #6430 .

**Comment by mattlanham** [comment] 2021-02-01 13:45
Also experiencing this - surely those keys are stored in AWS and don't need to continually re-entered?

**Comment by PeteDuncanson** [comment] 2021-02-02 11:41
@avlonder for what its worth my issue running init was often when pull failed so I think we are asking for the same thing. I'll make a note on issue #6430 to reflect we want both commands covered. Hows that?
