### ISSUE TITLE
amplify configure silently fails

### ISSUE THREAD

**Issue by jinwood** [aws-amplify/amplify-cli#10601] opened 2022-06-14 20:47 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v16.15.1

### Amplify CLI Version

8.5.0

### What operating system are you using?

MacOS Monterey

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

Not applicable

### Amplify Commands

configure

### Describe the bug

`amplify configure` or any combination of any other `amplify` command silently fails with no output whatsover.

Within existing project:
<img width="475" alt="image" src="https://user-images.githubusercontent.com/6605287/173685135-84c39670-31ac-47d5-a5d5-28da9e129e5c.png">

In any directory:
<img width="475" alt="image" src="https://user-images.githubusercontent.com/6605287/173685225-200e6d54-f93d-418e-8d4c-35ed8f70e8e8.png">
<img width="475" alt="image" src="https://user-images.githubusercontent.com/6605287/173685243-1e151979-9e92-4e3e-b23d-2e51e2e111b8.png">

### Expected behavior

The cli should function as documented.

### Reproduction steps

I am using a 2022 Macbook Pro base configuration 16" with M1 processor. Running native zsh shell and node / cli versions listed above.

1. Install node `brew install node@16`
2. Install cli `npm install -g @aws-amplify/cli`
3. Try above commands and observe the behaviour

**Comment by josefaidt** [comment] 2022-06-14 21:05
Hey @jinwood :wave: thanks for raising this! This appears to be a duplicate of https://github.com/aws-amplify/amplify-cli/issues/10193, can you try the workaround posted in [this comment](https://github.com/aws-amplify/amplify-cli/issues/10193#issuecomment-1132201405)?

```
softwareupdate --install-rosetta
```

**Closed** 2022-06-14 21:14 UTC
Labels: documentation, pending-close-response-required, installation, duplicate
