### ISSUE TITLE
Can't add schedule to a function

### ISSUE THREAD

**Issue by amuresia** [aws-amplify/amplify-cli#3917] opened 2020-04-09 19:02 UTC
I just updated to the latest version of the cli and tried to add a schedule using amplify update function. The push however fails with

```
UPDATE_FAILED               function   AWS::CloudFormation::Stack Thu Apr 09 2020 20:45:23 GMT+0200 (Central European Summer Time) Parameters: [CloudWatchRule] do not exist in the template    
```                
I can confirm that in the template there's a reference to the rule `"ScheduleExpression": { "Ref": "CloudWatchRule" }` but the rule itself is not in the template.

Reference: #1789 
CC: @kaustavghosh06

**Comment by kaustavghosh06** [comment] 2020-04-09 19:12
@amuresia This is a duplicate of #3911 
We're tracking #3911 for this issue.

**Closed by kaustavghosh06** 2020-04-09 19:12 UTC
