### ISSUE TITLE
 Parameters: [unauthRoleName, authRoleName] must have values on `amplify push function`

### ISSUE THREAD

**Issue by MichaelPlan** [aws-amplify/amplify-cli#9484] opened 2022-01-10 21:36 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.18.2

### Amplify CLI Version

7.6.7

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

function

### Amplify Commands

add, push

### Describe the bug

It's not possible to push a new lambda function with CLI.

UPDATE_FAILED      api                    AWS::CloudFormation::Stack Mon Jan 10 2022 22:32:05 GMT+0100 (Central European Standard Time) Parameters: [unauthRoleName, authRoleName] must have values
CREATE_FAILED      functiontest                 AWS::CloudFormation::Stack Mon Jan 10 2022 22:32:06 GMT+0100 (Central European Standard Time) Resource creation cancelled                                
UPDATE_FAILED      AuthTriggerCustomLambdaStack AWS::CloudFormation::Stack Mon Jan 10 2022 22:32:06 GMT+0100 (Central European Standard Time) Resource update cancelled

### Expected behavior

UPDATE_COMPLETE 

### Reproduction steps

1.  amplify add function
2.  choose Lambda function
3.  function name => test
4. runtime => NodeJS
5. function Template => Hello world
6.  advanced settings => No
7.  amplify push function test
8. " Function │ test          │ Create    │ awscloudformation"
9.  continue => Y
10. [unauthRoleName, authRoleName] must have values

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by mkpratt** [comment] 2022-01-11 19:42
I also have been dealing with this exact same issue. Fails with this same error on a few existing and unchanged REST APIs when trying to push a minor update on the GraphQL API
`Parameters: [authRoleName, unauthRoleName] must have values`

Amplify Version 7.6.8

**Comment by josefaidt** [comment] 2022-01-11 21:43
Hey @MichaelPlan :wave: thanks for raising this! From the CloudFormation lines you posted I noticed this is failing for your API, is this a REST API by chance? 

> UPDATE_FAILED api AWS::CloudFormation::Stack Mon Jan 10 2022 22:32:05 GMT+0100 (Central European Standard Time) Parameters: [unauthRoleName, authRoleName] must have values

If so, was this project recently migrated from using an older version of the CLI?

**Comment by MichaelPlan** [comment] 2022-01-18 16:47
@josefaidt yes, the project was recently migrated. The only solution to fix it was to create a complete new project. But after some days working with the new version, I'm now getting this for hours:

A deployment is in progress.
If the prior rollback was aborted, run:
"amplify push --iterative-rollback" to rollback the prior deployment
"amplify push --force" to re-deploy

when try to push anything.

I pulled everything again and made some small changes, but nothing works anymore.
With "amplify push --iterative-rollback" I 'm getting ": ["Index: 1 State: {\"preRollback\":\"previousDeploymentReadyCheck\"} Message: Resource is not in the state stackUpdateComplete"]":

In amplify studio I can see "Deployment completed".

Do you have any solution for the problem? Is it possible to abort a deployment?

**Comment by johnpc** [comment] 2022-01-18 20:16
Did you previously override cloudformation configuration directly?

**Comment by josefaidt** [comment] 2022-02-15 22:51
Closing due to inactivity. @MichaelPlan if you are still experiencing this issue please reply back to this thread and we can re-open to investigate further 🙂

**Comment by LucasKnudsen** [comment] 2022-02-23 07:38
Hey, I'm having similar issues. 

I am on version 7.6.21 and migrated to Transformer v2. 

`amplify push` work fine, but `amplify function push` and `amplify function push locationGeocoder` throws the following error:

```
UPDATE_FAILED      apicondominium                       AWS::CloudFormation::Stack Wed Feb 23 2022 08:26:08 GMT+0100 (Central European Standard Time) Parameters: [unauthRoleName, authRoleName] must have values
```

This is from a newly redeployed Stack as well.

The only place I'm using these values as parameters is within the Geo resource, which was generated by Amplify.

**Comment by josefaidt** [comment] 2022-03-02 21:43
Hey @LucasKnudsen apologies for the delay! I was able to successfully reproduce this with the following steps on the latest version of the Amplify CLI (7.6.22):

1. create a new project with `amplify init -y`
2. add a GraphQL API with `amplify add api`, choose IAM as an auth mode
	a. in my reproduction, I chose Cognito as the default auth mode and IAM as an additional auth mode
3. push with `amplify push -y`
4. add a function with `amplify add function`
5. attempt to push just the new function with `amplify push function <my-function-name>` or `amplify push function`
6. observe error

Marking as a bug 🙂

**Comment by OlgaMaslova** [comment] 2022-06-02 14:34
Hello,

I am experiencing the same bug when trying to push only function. I have the latest version of amplify (8.3.1). Any ideas?

Thanks!

**Comment by mstoyanovv** [comment] 2022-06-10 12:20
> Hello,
> 
> I am experiencing the same bug when trying to push only function. I have the latest version of amplify (8.3.1). Any ideas?
> 
> Thanks!

It happens to me too but in my case I recreated the table that was linked to a given function. After that amplify function push started throwing those errors. Relinking the function to the table by amplify function update might solve it.

**Comment by potatodepaulo** [comment] 2022-06-15 00:46
Also experiencing this bug on pushes for functions.

**Comment by s-ueno** [comment] 2022-06-22 14:52
From the comments, I found that the `amplify push api`,` amplify push function`, and other Backend-only functions have similar errors.

I was able to get around the error and update Backend with `amplify push`.

I hope this obstacle will be remedied.

amplify -v
9.0.0

**Comment by alanblake** [comment] 2022-08-04 05:01
I'm also stuck with this error. 
amplify -v
9.2.0

**Comment by alanblake** [comment] 2022-08-04 06:23
> I'm also stuck with this error. amplify -v 9.2.0

I managed to get past this by doing an amplify pull and then amplify push

**Comment by avinashrgudipati** [comment] 2022-08-07 02:53
Fails for me with `amplify push` from IDE

Fails when I edit schema on Amplify Studio and try to deploy the changes

Fails CI/CD builds

all of this happened after I’ve added a post confirmation trigger. Removing the trigger didn’t seem to help

**Comment by evan1715** [comment] 2022-08-09 22:27
this error is also occurring after
amplify add geo
amplify push

Parameters: [unauthRoleName] must have values

i've tried a thousand different methods and suggestions to get it working, but no go.

**Comment by CodySwannGT** [comment] 2022-08-10 02:15
9.2.0 - same here. can ``amplify push`` but not ``amplify function push``

**Comment by theZ3r0CooL** [comment] 2022-08-22 01:14
> significantly longer

The reason it's failing on other services when calling `amplify push <category>` is because it always does a full push. the only thing specifying the category does; to my understanding, is filter the update table at the start so you only see what matter to you for that push since that list can become quite large. However if you want to speed things up a bit, you can add `--yes` after your pull/push to not pause on that table and have to hit enter.

**Comment by edwardfoyle** [comment] 2022-08-23 18:33
Hi all, so far I'm unable to repro this using v 9.2.1 of the CLI. Is anyone still having this issue on that version?

**Comment by avinashrgudipati** [comment] 2022-08-23 19:35
Still an issue for me with CLI 9.2.1

**Comment by MaximeIJ** [comment] 2022-08-28 05:13
Same, seeing this in CI/CD builds of a custom function. The logs say they patched the CLI to v 9.2.1:
`Done patching NPM package '@aws-amplify/cli' to version 9.2.1`

I'm not seeing the issue from local `amplify push` though

**Comment by miquelvir** [comment] 2022-08-30 18:09
Seeing the issue as well.

**Comment by jbreemhaar** [comment] 2022-09-01 14:18
@edwardfoyle yes, I'm at 9.2.1.

**Comment by javabudd** [comment] 2022-09-03 20:14
seeing the issue as well, `amplify push` leads to an error in both the UI and CLI:
```
AWS::CloudFormation::Stack Sat Sep 03 2022 14:04:58 GMT-0600 (Mountain Daylight Time) Parameters: [unauthRoleName] must have values
```

**Comment by bordernone** [comment] 2022-09-10 16:40
Had a similar issue. Here's my solution https://stackoverflow.com/a/73673509/11135757

**Comment by avinashrgudipati** [comment] 2022-09-19 18:19
> Had a similar issue. Here's my solution https://stackoverflow.com/a/73673509/11135757

It was a nightmare but I did the above and didn’t help me. On CI/CD it specifically says unAuthUserRole issue but on the react app it now says Resource not in StackUpdateComplete. Previously the above was followed by unAuthRole error

**Comment by bordernone** [comment] 2022-09-20 14:53
> > Had a similar issue. Here's my solution https://stackoverflow.com/a/73673509/11135757
> 
> It was a nightmare but I did the above and didn’t help me. On CI/CD it specifically says unAuthUserRole issue but on the react app it now says Resource not in StackUpdateComplete. Previously the above was followed by unAuthRole error

Check if you see the identity pool linked in your "Authentication" section in Amplify Studio. Additionally, you can add StackUpdateComplete to your auth profile.

**Comment by avinashrgudipati** [comment] 2022-09-20 15:10
@bordernone 

I have a cognitive userpool linked. Any idea how I can add the stackUpdateComplete to the auth profile. Thank you for the response

**Comment by bordernone** [comment] 2022-09-20 15:13
> @bordernone
> 
> I have a cognitive userpool linked. Any idea how I can add the stackUpdateComplete to the auth profile. Thank you for the response

My question is does it show that you have an identity pool attached as well? This was the reason I was getting the error. I also had user pool linked but no identity pool was linked to it

**Comment by avinashrgudipati** [comment] 2022-09-20 15:17
Sorry about that. I do not have any identity pool attached. Any steps to attach that would be really appreciated

**Comment by bordernone** [comment] 2022-09-20 15:27
> Sorry about that. I do not have any identity pool attached. Any steps to attach that would be really appreciated

It's actually in that StackOverflow answer I linked above. I will update the answer with more details.

**Comment by avinashrgudipati** [comment] 2022-09-22 18:00
Any update on this? Stuck and I can’t delete any db items from client because I can’t update API

@bordernone did you have a lambda function in your setup?

**Comment by bordernone** [comment] 2022-09-25 18:31
> Any update on this? Stuck and I can’t delete any db items from client because I can’t update API
> 
> @bordernone did you have a lambda function in your setup?

This might help: https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-integrating-user-pools-with-identity-pools.html

Nope I didn't

**Comment by avinashrgudipati** [comment] 2022-09-25 18:40
> > Any update on this? Stuck and I can’t delete any db items from client because I can’t update API
> > @bordernone did you have a lambda function in your setup?
> 
> This might help: https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-integrating-user-pools-with-identity-pools.html
> 
> Nope I didn't

That might be the difference. The issue started happening when I added the function as the OP reported. I will try creating a completely new project without lambda function and try migrating the database

**Comment by javabudd** [comment] 2022-10-02 20:31
experiencing the same bug when attempting to push a new environment importing a cognito user pool...

```
Deployment failed.
Deploying root stack gtart [ =============--------------------------- ] 1/3
        amplify-gtart-staging-142557   AWS::CloudFormation::Stack     UPDATE_ROLLBACK_COMPLETE       Sun Oct 02 2022 14:28:59…
        apigtart                       AWS::CloudFormation::Stack     CREATE_FAILED                  Sun Oct 02 2022 14:28:30…
Deployed api gtart [ ======================================== ] 12/12

🛑 The following resources failed to deploy:
🛑 An error occurred during the push operation: /
Resource is not in the state stackUpdateComplete
```
```
Parameters: [unauthRoleName] must have values
```

**Comment by avinashrgudipati** [comment] 2022-10-02 20:45
I don’t want to jinx my self but I got past this. Unfortunately the solution isn’t pretty. 

@javabudd how did you create auth?

**Comment by javabudd** [comment] 2022-10-02 21:55
> I don’t want to jinx my self but I got past this. Unfortunately the solution isn’t pretty. 
> 
> 
> 
> @javabudd how did you create auth?

I used the UI to attach an existing user pool, if I remove the auth and try again it works.

**Comment by lazpavel** [comment] 2022-11-23 17:42
No longer reproducible with v.10.5.1.

**Closed by lazpavel** 2022-11-23 17:42 UTC
Labels: bug, functions, platform, api-graphql, p1, ops-deploy, regression

**Comment by Abhishek-cmd13** [comment] 2023-01-07 16:24
This issue is not been solved yet.

**Comment by Arnav7501** [comment] 2023-02-05 05:21
issue is still there

**Comment by Arnav7501** [comment] 2023-02-05 05:31
@javabudd how did you remove the auth?

**Comment by avinashrgudipati** [comment] 2023-02-06 06:38
Removing the auth and re-adding didn’t really help me. The best bet for you
and probably the easy one is to create a new environment.

I initially deleted my project and started from scratch but later needed to
add another function and that broke my environment again. I tried creating
a new environment this time which was much easier rather than redoing the
whole thing and that worked.

**Comment by Arnav7501** [comment] 2023-02-06 06:46
yeah you're right a new environment fixed it... unfortunately my app is in production and the new environment doesn't keep the logins so that is an extremely unfortunate bug. I appreciate your help though.

**Comment by josefaidt** [comment] 2023-02-14 17:38
Hey folks :wave: if you are experiencing this error when attempting to push updates to your Amplify project using the latest version of the CLI (10.7.2 at the time of writing), please file a [separate bug report](https://github.com/aws-amplify/amplify-cli/issues/new/choose)

**Comment by kuoaid** [comment] 2024-11-04 23:26
same issue on Amplify push (all). Using the latest CLI.
