### ISSUE TITLE
[Feedback]CORS issue

### ISSUE THREAD

**Issue by Matt-Borack-Climate** [aws-amplify/amplify-cli#12320] opened 2023-03-26 16:54 UTC
**Page**: [`/start/getting-started/data-model/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/react)

**Feedback**:

I needed to create a cors.json file to get it to work. You may want to add instructions for that to the instructions.

**Comment by josefaidt** [comment] 2023-03-27 18:46
Hey @Matt-Borack-Climate :wave: where did you create this `cors.json` file? I'm not able to reproduce this

**Comment by Matt-Borack-Climate** [comment] 2023-03-27 19:13
Hello Josep.

Since the backend needs to respond with the CORS headers, I placed the cors.json file at amplify/backend/api/<name of your project>/cors.json

Within that file I put the following:

{
                "cors": {
                                "allowedOrigins": ["http://localhost:3000"],
                                "allowedHeaders": ["*"],
                                "allowedMethods": ["GET", "POST"],
                                "maxAge": 3000
                }
}

Hope this helps.

Matt

From: josef ***@***.***>
Date: Monday, March 27, 2023 at 11:46 AM
To: aws-amplify/amplify-cli ***@***.***>
Cc: Matt-Borack-Climate ***@***.***>, Mention ***@***.***>
Subject: Re: [aws-amplify/amplify-cli] [Feedback]CORS issue (Issue #12320)

Hey @Matt-Borack-Climate<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMatt-Borack-Climate&data=05%7C01%7C%7Caaa3dee17b954997dd4f08db2ef39245%7Cfcb2b37b5da0466b9b830014b67a7c78%7C0%7C0%7C638155395885764468%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wCL%2FsxqEHosrFMKbhamHtNp62owIOBl0jdmScVHOGFo%3D&reserved=0> 👋 where did you create this cors.json file? I'm not able to reproduce this

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faws-amplify%2Famplify-cli%2Fissues%2F12320%23issuecomment-1485690235&data=05%7C01%7C%7Caaa3dee17b954997dd4f08db2ef39245%7Cfcb2b37b5da0466b9b830014b67a7c78%7C0%7C0%7C638155395885764468%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9wob0NKCocLZin2OXeRS3XzxQZ1DPAwAPOhWZ2mjKTM%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA5F5AHHFLS2HSMA4TEEDJLDW6HOABANCNFSM6AAAAAAWJQJQHE&data=05%7C01%7C%7Caaa3dee17b954997dd4f08db2ef39245%7Cfcb2b37b5da0466b9b830014b67a7c78%7C0%7C0%7C638155395885764468%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1LyOOL52bcOrNUfVhpYrZ3WdENokOiUt2%2B5V%2BOtr%2FA8%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

________________________________

The information contained in this e-mail is for the exclusive use of the intended recipient(s) and may be confidential, proprietary, and/or legally privileged.  Inadvertent disclosure of this message does not constitute a waiver of any privilege.  If you receive this message in error, please do not directly or indirectly use, print, copy, forward, or disclose any part of this message.  Please also delete this e-mail and all copies and notify the sender.  Thank you.

________________________________

**Comment by josefaidt** [comment] 2023-03-27 19:26
Hey @Matt-Borack-Climate thanks for clarifying. Where did you find this guidance, to create this `cors.json` file?

**Comment by Matt-Borack-Climate** [comment] 2023-03-27 19:50
I asked ChaptGPT the following question: “how do I specify CORS settings in an AWS Amplify app?”

Matt

From: josef ***@***.***>
Date: Monday, March 27, 2023 at 11:46 AM
To: aws-amplify/amplify-cli ***@***.***>
Cc: Matt-Borack-Climate ***@***.***>, Mention ***@***.***>
Subject: Re: [aws-amplify/amplify-cli] [Feedback]CORS issue (Issue #12320)

Hey @Matt-Borack-Climate<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMatt-Borack-Climate&data=05%7C01%7C%7Caaa3dee17b954997dd4f08db2ef39245%7Cfcb2b37b5da0466b9b830014b67a7c78%7C0%7C0%7C638155395885764468%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wCL%2FsxqEHosrFMKbhamHtNp62owIOBl0jdmScVHOGFo%3D&reserved=0> 👋 where did you create this cors.json file? I'm not able to reproduce this

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faws-amplify%2Famplify-cli%2Fissues%2F12320%23issuecomment-1485690235&data=05%7C01%7C%7Caaa3dee17b954997dd4f08db2ef39245%7Cfcb2b37b5da0466b9b830014b67a7c78%7C0%7C0%7C638155395885764468%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9wob0NKCocLZin2OXeRS3XzxQZ1DPAwAPOhWZ2mjKTM%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA5F5AHHFLS2HSMA4TEEDJLDW6HOABANCNFSM6AAAAAAWJQJQHE&data=05%7C01%7C%7Caaa3dee17b954997dd4f08db2ef39245%7Cfcb2b37b5da0466b9b830014b67a7c78%7C0%7C0%7C638155395885764468%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1LyOOL52bcOrNUfVhpYrZ3WdENokOiUt2%2B5V%2BOtr%2FA8%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

________________________________

The information contained in this e-mail is for the exclusive use of the intended recipient(s) and may be confidential, proprietary, and/or legally privileged.  Inadvertent disclosure of this message does not constitute a waiver of any privilege.  If you receive this message in error, please do not directly or indirectly use, print, copy, forward, or disclose any part of this message.  Please also delete this e-mail and all copies and notify the sender.  Thank you.

________________________________

**Comment by josefaidt** [comment] 2023-03-27 20:31
Hey @Matt-Borack-Climate thank you for the clarification. Unfortunately we do not support this file, though I'm curious to learn more about the CORS errors you were facing. What were the errors you were facing and were the encountered by following the steps in the linked guide?

**Comment by Matt-Borack-Climate** [comment] 2023-03-27 21:19
Hello Josef

I followed the linked guide closely.

The errors I faced looked like the standard CORS messages I’ve faced in the past, so I didn’t take a screenshot.

I just renamed the “cors.json” file to something like “cors.json-----" and pushed via “amplify push”, but I’m not able to reproduce the CORS errors. I ensured that the Network tab in the Developer Tools is showing calls to AppSync (…appsync-api…amazonaws.com/graphql) and not my localhost when I’m adding new records.

Matt

From: josef ***@***.***>
Date: Monday, March 27, 2023 at 1:31 PM
To: aws-amplify/amplify-cli ***@***.***>
Cc: Matt-Borack-Climate ***@***.***>, Mention ***@***.***>
Subject: Re: [aws-amplify/amplify-cli] [Feedback]CORS issue (Issue #12320)

Hey @Matt-Borack-Climate<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMatt-Borack-Climate&data=05%7C01%7C%7C38eaa77b82aa4bd740a208db2f024516%7Cfcb2b37b5da0466b9b830014b67a7c78%7C0%7C0%7C638155459010807961%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=08GRyMuHsxkWQxczDOTqKOISICSL2RIRaAmkTkxXEtM%3D&reserved=0> thank you for the clarification. Unfortunately we do not support this file, though I'm curious to learn more about the CORS errors you were facing. What were the errors you were facing and were the encountered by following the steps in the linked guide?

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faws-amplify%2Famplify-cli%2Fissues%2F12320%23issuecomment-1485824271&data=05%7C01%7C%7C38eaa77b82aa4bd740a208db2f024516%7Cfcb2b37b5da0466b9b830014b67a7c78%7C0%7C0%7C638155459010807961%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=s4mn1oCM2VafPcCXsJOJFjMueD8Ve3TZfJme0k6eHTU%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA5F5AHHERBZLOY2CDDFHDHDW6H2KVANCNFSM6AAAAAAWJQJQHE&data=05%7C01%7C%7C38eaa77b82aa4bd740a208db2f024516%7Cfcb2b37b5da0466b9b830014b67a7c78%7C0%7C0%7C638155459010807961%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=v7mmPhNqxGj%2FgPr5eHrcM5XMIo0nMdDWv0LAZ4xSbAQ%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

________________________________

The information contained in this e-mail is for the exclusive use of the intended recipient(s) and may be confidential, proprietary, and/or legally privileged.  Inadvertent disclosure of this message does not constitute a waiver of any privilege.  If you receive this message in error, please do not directly or indirectly use, print, copy, forward, or disclose any part of this message.  Please also delete this e-mail and all copies and notify the sender.  Thank you.

________________________________

**Comment by josefaidt** [comment] 2023-03-27 21:25
Hey @Matt-Borack-Climate no worries, I'll close this issue since I am not able to reproduce, but if the issue comes up again please do not hesitate to reach out by replying back to this issue or by filing a [bug report](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=pending-triage&template=1.bug_report.yaml)

**Closed by josefaidt** 2023-03-27 21:25 UTC
Labels: pending-triage, transferred
