### ISSUE TITLE
Auth: Add Federated Identity OIDC Provider to Cognito Pool

### ISSUE THREAD

**Issue by rraczae** [aws-amplify/amplify-cli#7045] opened 2021-04-09 16:25 UTC
I need to add a custom federated oidc provider to my cognito user pool. I can do this easily if I go to the cognito instance directly in the console and set up the OpenID Connect provider however that change is not reflected in amplify.

When I choose the option to add a provider the only options are facebook, google and amazon. Is there something I am missing?

Thanks!

**Which Category is your question related to?**
auth

**Amplify CLI Version** 
4.46.1

**What AWS Services are you utilizing?**
cognito, appsync, datastore, s3, lambda

**Comment by kaustavghosh06** [comment] 2021-04-09 17:20
Closing this as a duplicate of this feature request - https://github.com/aws-amplify/amplify-cli/issues/177
Also, we have an open PR - https://github.com/aws-amplify/amplify-cli/pull/3409 for this which we plan to take a look.

**Comment by ammarkarachi** [comment] 2021-04-09 17:20
@rraczae We don't support this natively but I can mark this as an enhancement request.

**Closed** 2021-04-09 17:20 UTC
Labels: auth, enhancement
