### ISSUE TITLE
Installing the Amplify CLI does not work with npm@7 

### ISSUE THREAD

**Issue by robinvw1** [aws-amplify/amplify-cli#5604] opened 2020-10-16 14:27 UTC
**Describe the bug**
[npm@7](https://blog.npmjs.org/post/631877012766785536/release-v700) was released on 13th October, 2020:
> npm v7 will be shipping with Node.js v15 (a PR to land this work will be opened shortly) & we hope to continue the pace of change/improvement as we head in to this last quarter of the year.

It is not *yet* tagged as `latest` on [npmjs.com/package/npm](https://www.npmjs.com/package/npm).

Nevertheless, I would like to report that the following command results into a silent crash:

```bash
npm install -g @aws-amplify/cli
```

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

```bash
npm install -g npm@7
npm install -g @aws-amplify/cli
```

**Expected behavior**
I expect the installation to finish (and be able to use `amplify` command).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v12.19.0 (LTS)

**Comment by yuth** [comment] 2020-10-16 17:51
@robinvw1  Do you get any specific errors when you try to install the amplify CLI with NPM 7?

**Comment by kaustavghosh06** [comment] 2020-10-24 22:12
Closing the issue due to lack of reproducibility and customer response.

**Closed by kaustavghosh06** 2020-10-24 22:12 UTC
Labels: not-reproducable, pending-close-response-required, platform

**Comment by nipoonp** [comment] 2021-03-31 03:03
try --legacy-peer-deps
ie. npm install react-apollo-hooks --legacy-peer-deps
