### ISSUE TITLE
Support backwards navigation when creating resources

### ISSUE THREAD

**Issue by ugurcemozturk** [aws-amplify/amplify-cli#5391] opened 2020-09-23 21:55 UTC
**Is your feature request related to a problem? Please describe.**
It's usual to make mistakes when creating resources. I'd love to see a 'go back' feature.

**Describe the solution you'd like**
When choosing something from the option list, there could be a 'go back' option. i.e.:
 o Create
 o Read
 o Update
 o Delete
 o Go Back

**Describe alternatives you've considered**
A generic 'go back' key. i.e 'Q' or shortcut as 'CMD/CTRL + Q'

Many thanks!

**Comment by mayteio** [comment] 2020-09-23 23:04
100%, this would be fantastic. I have ctrl+c'd out of so many resource setups I've lost count 😂

**Comment by renebrandel** [comment] 2021-03-26 18:50
Closing as dupe of: https://github.com/aws-amplify/amplify-cli/issues/6367

**Closed by renebrandel** 2021-03-26 18:50 UTC
Labels: enhancement, platform
