### ISSUE TITLE
amplify-appsync-simulator util.isNullOrEmpty returns true for a boolean true value

### ISSUE THREAD

**Issue by rickfoxcroft** [aws-amplify/amplify-cli#4393] opened 2020-05-28 03:38 UTC
When invoking the method with a boolean value of true, true is returned a result. Indicating that arg was equal to null.

eg. $util.isNullOrEmpty(true) === true

**Comment by ammarkarachi** [comment] 2020-06-01 21:44
Closing this duplicate of https://github.com/aws-amplify/amplify-cli/issues/4386

**Closed by ammarkarachi** 2020-06-01 21:44 UTC
Labels: bug, duplicate
