### ISSUE TITLE
Support non-scalars as part a "create" input object

### ISSUE THREAD

**Issue by 0xR** [aws-amplify/amplify-cli#190] opened 2018-09-21 20:08 UTC
I'm trying to create a complex data structure and store it in dynamodb. It will contain maps and lists in DynamoDB term. Or arrays and objects in JS terms.

Since DynamoDB supports this I would like to be able to create these using amplify.

I've tried making the nested data separate `@models` connected by a `@connection` directive. However this forces me to create the nested object in a separate `create` call. I'd also need to remember to delete both the object and the nested attributes at the same time.

Looking at the code I see this line which will only put scalars in the input type:
https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-dynamodb-transformer/src/definitions.ts#L25

**Comment by mikeparisstuff** [comment] 2018-09-24 20:17
This is a relatively simple fix and is a duplicate of https://github.com/aws-amplify/amplify-cli/issues/72. The fix is two fold. 

First change this line https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-dynamodb-transformer/src/definitions.ts#L25 to allow scalars, non @model types, and enums to be included. 

Second, generate input object types for every non @model type that is referenced by an @model type. The optimized version of this would only create input objects for types that are referenced by fields in @model types or are a child of one such type. I.E. you would need to continue to walk any references non @model types to find all other non @model types that they reference. The simple solution to this is to just generate a XInput input object for every non @model type with the appropriate fields. The appropriate fields would be any scalars, enums, or other non @model types. We don't support @connection on non @model types so this is not a concern.

**Comment by kaustavghosh06** [comment] 2018-09-28 19:41
We've merged a fix for this. We'll publish a new version for the CLI on Monday which would have this fix.

**Closed by kaustavghosh06** 2018-09-28 19:41 UTC
Labels: feature request, graphql-transformer
