### ISSUE TITLE
Comment Documentation Schema

### ISSUE THREAD

**Issue by austinamorusocfc** [aws-amplify/amplify-cli#1393] opened 2019-05-03 20:54 UTC
** Which Category is your question related to? **
API GraphQL Schema
** What AWS Services are you utilizing? **
Appsync Schema
** Provide additional details e.g. code snippets **
How to add comments for documentation on schema for usage in appsync graphiql interface. 

```
# A group of Categories e.g. Moments or Powers
type CategoryGroup @model @searchable @versioned @auth(rules: [
    {allow: groups, groups: ["Admin"]},
    {allow: groups, groupsField: "readGroups", queries: [get, list], mutations: null},
    {allow: groups, groupsField: "writeGroups" mutations: [update, delete], queries: null}
]) {
    id: ID!
    name: String!
    description: String!
    categories: [Category] @connection(name: "GroupCategories")
    language: Language!
    readGroups: [String]!
    writeGroups: [String]!
}
```

I had the expectation the comment would be reflected in the compiled schema and then viewable in the appsync schema section of the graphiql interface.

**Comment by lockevi** [comment] 2019-07-18 02:49
I need this feature too !
I spent a whole day for workaround but failed : (

Can you let me know the schedule for this ?

**Comment by VitValchar** [comment] 2019-12-02 15:44
I would like to have this feature as well. It is one of the main features of GraphQL, that you can document your API right in the code, but it is not possible here which makes us use a separate tool for documentation...

**Comment by matwerber1** [comment] 2019-12-15 19:58
+1

**Comment by clinicalinkgithub** [comment] 2020-01-24 19:13
has there been any movement on this?  being ablt to document is a very importal feature of graphql

**Comment by larsvinter** [comment] 2020-04-23 23:27
Any news on this? It really is one of the key features of graphql to be able to document your schema inline...

**Comment by VitValchar** [comment] 2020-06-03 11:48
Hi, I was finally able to resolve this issue. The problem is that in older versions of GraphQL, the field description was done by hash mark `# this is a comment` but in newer versions of GraphQL, it is done by double quotes `"this is a comment"` over the field/type. ( https://github.com/ardatan/graphql-tools/issues/221#issuecomment-425742915 )

So... `amplify api gql-compile` is using the specification of a newer GraphQL version, so you have to use the double-quotes. Those are copied over to `build/schema.graphql`. The AppSync GraphQL server, however, is using an older version of GraphQL that expects the comments to be with hash marks... This results in a funny version mismatch as the description is deployed with the quotes but AppSync does not know what to do with it... I still cannot understand why no one from the Amplify or AWS team did not bring this up sooner.

Anyway, I've created a simple nodejs script that will transform it from one to another. (feel free to use and adjust the script)
```
const fs = require('fs');
const readline = require('readline');
// path to your build/schema.graphql
const schemaPath = "./build/schema.graphql";

async function process() {
    const fileStream = fs.createReadStream(schemaPath);

    const rl = readline.createInterface({
        input: fileStream,
        crlfDelay: Infinity
    });
    let inComment = false;

    let result = "";

    for await (const line of rl) {
        let matchObj;
        if (matchObj = line.match(/^[ ]*"([^"]+?)"$/)) {
            // resolve single line comment
            result += `# ${matchObj[1]}\n`;
        } else if (matchObj = line.match(/^[ ]*"""(.+?)"""$/)) {
            // resolve multiline comment that is on one line
            result += `# ${matchObj[1]}\n`;
        } else if(line.match(/^[ ]*"""$/)) {
            // set multiline comment start/end
            inComment = !inComment;
        } else if(inComment) {
            // resolve multiline comment
            result += `# ${line.trimStart()}\n`;
        } else {
            // copy whatever other line
            result += line + "\n";
        }
    }

    fs.writeFileSync(schemaPath, result);
    console.log("schema.graphql file comments has been transformed successfully.");
}

process();
```

it will transform the schema from this
```
"one line comment"
pk: String!
"""
first line of comment
second line of comment
"""
sk: String!
```
into this
```
# one line comment
pk: String!
# first line of comment
# second line of comment
sk: String!
```

I've created a bash script that runs those commands, so it will transform the descriptions each time I deploy. With this, it works for me pretty fine.
```
amplify api gql-compile
node transform-docs.js
amplify push --yes --no-gql-override
```

**Comment by dtelaroli** [comment] 2020-07-11 02:42
+1

**Comment by pshouseGBC** [comment] 2020-07-30 01:20
+1

**Comment by matart15** [comment] 2022-03-15 04:44
Just a few experiments

```txt
"comment"            - NOT WORK

"""comment"""        - NOT WORK

"""
comment
"""                 - NOT WORK

# comment
# comment            - WORKS. But starting from second line comment gets displayed BIGGER

```


CDK version : 2.16.0 (build 4c77925)

![Screen Shot 2022-03-15 at 13 38 52](https://user-images.githubusercontent.com/17027219/158307665-ac693c39-3685-4965-8915-c0656ff574fd.png)

<img width="368" alt="Screen Shot 2022-03-15 at 13 38 27" src="https://user-images.githubusercontent.com/17027219/158307655-6396b302-a35e-4224-adf3-60112dddc60f.png">

**Comment by josefaidt** [comment] 2022-03-24 22:03
Hey y'all :wave: really appreciate the feedback here and apologies for the delay! Upon further review this appears to require a bug fix from AppSync as noted here https://github.com/aws/aws-appsync-community/issues/38

Closing in favor of tracking favor of tracking AppSync issue 🙂 once the linked issue is resolved we can revisit this issue to ensure docs comments are applied from Amplify deployments

**Closed by josefaidt** 2022-03-24 22:03 UTC
Labels: feature-request, graphql-transformer-v1, graphql-transformer-v2

**Comment by lewisdonovan** [comment] 2022-11-07 05:42
Any update on this? It's kinda nuts that we can't document our APIs.
