### ISSUE TITLE
`amplify import auth` with existing user pool doesn't generate full oauth configuration in aws-imports.js

### ISSUE THREAD

**Issue by harunhasdal** [aws-amplify/amplify-cli#11309] opened 2022-11-02 10:57 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.13.2

### Amplify CLI Version

10.4.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth

### Amplify Commands

init, push

### Describe the bug

I have a user pool created with CDK, configured with an OIDC provider. 

I used `amplify import auth` to use the existing userpool for Amplify Auth.
I've run `amplify push` which generated an `aws-imports.js` file. 

The `aws-imports.js` file doesn't contain all oauth configuration. It is missing client_id, scopes etc.

It only contains the domain:

```
"oauth": {
     "domain": "mydemo.auth.eu-west-1.amazoncognito.com"
 },
```

With this configuration, calls to Auth.federatedSignin({customProvider:'myidp'}) throw an exception as it cannot initialise the `_oauthHandler` properly.

### Expected behavior

Amplify config to be complete so that `Auth.federatedSignin()` with oidc providers work as expected.

### Reproduction steps

1. Create user-pool on AWS using CDK or CloudFormation: create userpool, register OIDC identityprovider, add domain, create userpool client
2. `amplify init` on the webapp
3. `amplify import auth` and select the userpool from the presented list
4. `amplify push -Y` 
5. Configure amplify in the webapp using aws-imports.js and call Auth.federatedSignin({customProvider: 'myidp'})

Verify that the call throws an exception trying to access `oauthSignIn` method on ` _oAuthHandler`
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'oauthSignIn')
    at AuthClass2.<anonymous> (Auth.ts:2364:24)
```

Verify that `aws-imports.js` doesn't contain the full oauth configuration.

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ykethan** [comment] 2022-11-04 20:38
Hey @harunhasdal, thank you for reaching out. This appears to be a duplicate of https://github.com/aws-amplify/amplify-cli/issues/10932. Please feel free in adding any information and subscribing to the issue. Closing the issue to prevent any miscommunication between issues.

**Closed by ykethan** 2022-11-04 20:38 UTC
Labels: auth, pending-triage, import, duplicate
