### ISSUE TITLE
Add User To Dynamo DB in PostConfirmation Cognito Trigger

### ISSUE THREAD

**Issue by rehanbabertkxel** [aws-amplify/amplify-cli#3945] opened 2020-04-12 18:54 UTC
**Which Category is your question related to?**
AWS Amplify, Amplify GraphQL Api, AWS Cognito

**Amplify CLI Version** 
4.13.1

**What AWS Services are you utilizing?**
AWS Amplify, Amplify GraphQL Api, AWS Cognito

**Provide additional details e.g. code snippets**
In the POSTCONFIRMATION trigger lambda function of Cognito, I want to call my APPSYNC GRAPHQL using amplify and API_KEY authentication to add the new user to my Dynamo DB.
Here is what I tried:

1. Amplify update function (Post Confirmation lambda function)
2. Provide access to appsync api.
3. Run "amplify push"

It gave the following error:

"Circular dependency between resources: [apisampleApi, UpdateRolesWithIDPFunctionOutputs, UpdateRolesWithIDPFunction, authsample644f88cf, functionsample644f88cfPostConfirmation]
An error occured during the push operation: Circular dependency
between resources: [apisampleApi, UpdateRolesWithIDPFunctionOutputs, UpdateRolesWithIDPFunction, authsample644f88cf, functionsample644f88cfPostConfirmation]"

Can you please guide me on how to fix this and how to achieve what I am trying to achieve.

**Note:** I do not want to call Dynamo DB directly using aws-sdk.

**Comment by SebSchwartz** [comment] 2020-04-12 19:57
You can find some answers to you problem here: https://github.com/aws-amplify/amplify-cli/issues/3430

**Comment by SwaySway** [comment] 2020-04-13 17:17
Closing as a duplicate of #3430

**Closed by SwaySway** 2020-04-13 17:17 UTC

**Comment by MontoyaAndres** [comment] 2020-06-21 17:24
Any solution? They mentioned how to solve this with cloudformation, but I don't know how to use it... Maybe is there any other way?

**Comment by raffibag** [comment] 2021-04-15 18:37
I've resolved this by manually setting the post-confirmation trigger per the instructions here: https://docs.amplify.aws/guides/functions/cognito-trigger-lambda-dynamodb/q/platform/js

Creating the trigger via the CLI results in the circular dependency issue. Use `amplify add function` to create your trigger and then select it in the Cognito console after you call `amplify push`.
