### ISSUE TITLE
overrid an auto generated pipeline resolver create another function 

### ISSUE THREAD

**Issue by amineProjects** [aws-amplify/amplify-cli#9650] opened 2022-01-29 20:34 UTC
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
I overriden an auto generated pipline resolver (just the res.vtl file) using this gide https://docs.amplify.aws/cli/graphql/custom-business-logic/#override-amplify-generated-resolvers  it overrid it just fine, but  it also created another function with the same res.vtl and $util.toJson({}) for the req.vtl

**Amplify CLI Version** 
7.6.13
You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets**

**Comment by jk171505** [comment] 2022-02-01 16:22
I have the same problem. I'm trying to override `Mutation.createTodo.auth.1.res.vtl` by copying it from `/build/resolvers` to `/resolvers`, but for some reason **an additional function is generated in the pipeline**, and placed right after the one that is generated by default. As a result there are two functions in the pipeline with identical response mapping template.
Looks like some kind of bug, unless there is a way to prevent this slot from being autogenerated.

**Comment by josefaidt** [comment] 2022-02-02 21:14
Hey @amineProjects and @jk171505 :wave: thanks for raising this! I was able to reproduce this behavior with the following steps:

1. create new project with `amplify init -y`
2. add a GraphQL API with default settings and the sample Todo schema
3. copy and paste the `Mutation.createTodo.postAuth.1.req.vtl` resolver from `amplify/backend/api/<api-name>/build/resolvers` to `amplify/backend/api/<api-name>/resolvers`
4. if we modify the template and run `amplify api gql-compile`, we see the resolver appears overridden as the customization is carried to `build/resolvers`
	```diff
    ## [Start] Sandbox Mode Enabled. **
    #if( !$ctx.stash.get("hasAuth") )
      #if( $util.authType() != "API Key Authorization" )
	+   ## my customization
        $util.unauthorized()
      #end
    #end
    $util.toJson({})
    ## [End] Sandbox Mode Enabled. **
	```
5. push resources with `amplify push -y`
6. observe additional resolver is created and added to the `CreateTodo` pipeline

![image](https://user-images.githubusercontent.com/5033303/152238242-9b41624e-95a9-4146-b496-2aa37ac4a887.png)



Marking as a bug 🙂

**Comment by jk171505** [comment] 2022-02-02 21:22
@josefaidt just so you know, this can be observed before push in `/stacks/<ModelName>.json` if you compile it (push is not required).
Thanks for checking this out.

**Closed** 2022-03-28 21:02 UTC
Labels: bug, graphql-transformer-v2, p2
