### ISSUE TITLE
Cannot run pull command

### ISSUE THREAD

**Issue by putikorn** [aws-amplify/amplify-cli#11063] opened 2022-09-25 15:30 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.9.0

### Amplify CLI Version

10.0.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

Not applicable

### Amplify Commands

pull

### Describe the bug

Cannot pull amplify to project. An error messgae is 

Failed to get credentials: User: arn:aws:sts::11111111111111:assumed-role/ap-southeast-1_vwdG8XQs7_Full-access/CognitoIdentityCredentials is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::11111111111111:role/ap-southeast-1_vwdG8XQs7_Full-access

An error just happend a few hours ago. But ,yesterday, when I ran pull command everything is fine.

### Expected behavior

Pull amplify backend to project without error

### Reproduction steps

1. Just run pull command in VS Code terminal

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment] 2022-09-28 15:33
Hey @putikorn :wave: thanks for raising this! From the provided role name ending with `Full-access` it appears you are authenticating with Studio. Can you provide a bit more details around how the application was originally created and the steps taken prior to receiving this error on `amplify pull`? Was this app created using Amplify Studio with an auth resource and then pulled using the provided command?

**Comment by putikorn** [comment] 2022-09-28 16:59
> Hey @putikorn 👋 thanks for raising this! From the provided role name ending with `Full-access` it appears you are authenticating with Studio. Can you provide a bit more details around how the application was originally created and the steps taken prior to receiving this error on `amplify pull`? Was this app created using Amplify Studio with an auth resource and then pulled using the provided command?


I've fixed it already. I create new amplify backend project and found that a role of the new project, in IAM, has new trust policy added compare to a role of old projects which doesn't have below.

{
    "Sid": "SelfAssumeRolePolicy",
    "Effect": "Allow",
    "Principal": {
        "AWS": "arn:aws:iam::111111111111111:role/ap-southeast-1_FSF5CrvkX_Full-access"
    },
    "Action": "sts:AssumeRole"
}

So I added this to all role of old project and error has gone when run pull command.

I think there is something wrong with AWS backend and above is workaround.

**Comment by indiejoseph** [comment] 2022-11-02 02:26
In case anyone encountered this problem, it can be fixed with following steps:
1. Copy the role arn `arn:aws:iam::88888888888888:role/ap-southeast-1_clcRVJkLh_Full-access`
2. Go to IAM -> Roles -> find ap-southeast-1_clcRVJkLh_Full-access
3. Insert below policy into trust relationship

```
 {
            "Sid": "SelfAssumeRolePolicy",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::88888888888888:role/ap-southeast-1_clcRVJkLh_Full-access"
            },
            "Action": "sts:AssumeRole"
}
```

**Comment by parvusville** [comment] 2022-11-02 10:54
I also faced this issue coming back  to a project I haven`t touched in months. Managed to pull the project with workaround above, thanks @indiejoseph  

I dont recall ever seeing this "login with amplify studio" flow before, I wonder when was it introduced?

**Comment by manuelcarriernunes** [comment] 2022-11-05 05:05
Disabling and then enabling Amplify Studio fixed the problem for me.

![image](https://user-images.githubusercontent.com/3910632/200102131-c39afcad-88e4-4e0d-8381-f2bbce1ae642.png)

It may fix things for others too.

**Comment by josefaidt** [comment] 2022-11-30 00:25
Hey @putikorn and folks in the thread, apologies for the delay!! While workarounds have been identified, I'm curious how this issue originally occurred. Was this an older project that you came back to after some time as @parvusville has mentioned?

**Comment by manuelcarriernunes** [comment] 2022-11-30 01:40
> Hey @putikorn and folks in the thread, apologies for the delay!! While workarounds have been identified, I'm curious how this issue originally occurred. Was this an older project that you came back to after some time as @parvusville has mentioned?

This problem occurred with a project I hadn't worked on in months.

**Comment by putikorn** [comment] 2022-11-30 03:17
> Hey @putikorn and folks in the thread, apologies for the delay!! While workarounds have been identified, I'm curious how this issue originally occurred. Was this an older project that you came back to after some time as @parvusville has mentioned?

Yes. It happened to older project but not for new project.

**Comment by josefaidt** [comment] 2022-11-30 20:30
Hey folks thanks for confirming, this was caused by a recent change to Amplify Studio per an [update to IAM role trust policy
 behavior](https://aws.amazon.com/blogs/security/announcing-an-update-to-iam-role-trust-policy-behavior/).

This issue is now resolved for newer projects, and as @manuelcarriernunes mentioned this can be resolved by disabling and re-enabling Amplify Studio from the AWS Console. Closing issue

**Closed by josefaidt** 2022-11-30 20:30 UTC
Labels: pending-triage, platform-pull
