### ISSUE TITLE
Add option to share parameter store secrets across functions

### ISSUE THREAD

**Issue by mtliendo** [aws-amplify/amplify-cli#10520] opened 2022-06-03 12:55 UTC
### Is this feature request related to a new or existing Amplify category?

function

### Is this related to another service?

Parameter Store

### Describe the feature you'd like to request

When creating a secret value in the CLI, I'd like to not have to define the same key/value for functions that make use of it.

### Describe the solution you'd like

When creating a secret value, I'd like the CLI to prompt me into asking if functionB would like to use a secret that is in use by functionA.

### Describe alternatives you've considered

Documentation that shows how two functions can share a secret value by use of a Lambda Layer would be helpful.

### Additional context

This would undoubtedly impact secret naming that currently follows the structure: `/amplify/appID/appEnv/AMPLIFY_funtionName_SECRETNAME`

Perhaps removing the `functionName` portion would suffice.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [X] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment] 2022-06-03 15:43
Hey @mtliendo :wave: thanks for raising this! I think this is a great idea, and as such I've marked this as a feature request 🙂

**Comment by josefaidt** [comment] 2022-06-03 15:45
Upon further inspection, I'll mark this as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/9879 and close in favor of tracking the existing item.

Also related:

- https://github.com/aws-amplify/amplify-cli/issues/8360
- https://github.com/aws-amplify/amplify-cli/issues/9968

**Closed by josefaidt** 2022-06-03 15:45 UTC
Labels: functions, feature-request
