### ISSUE TITLE
amplify mock destroys production DynamoDB tables

### ISSUE THREAD

**Issue by fakedob** [aws-amplify/amplify-cli#7423] opened 2021-05-29 10:12 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v12.16.1

### Amplify CLI Version

4.51.3

### What operating system are you using?

MacOS 11.2.3

### Amplify Categories

api

### Amplify Commands

codegen, env, publish, push

### Describe the bug

There is a (by design) problem we hit with the cli, while using the mock functionality, built in with the cli. What happens is that, when you hit ctrl+C to terminate the process, it somehow uses this input and triggers a delete of the autogenerated resolvers files, that the amplify cli builds (manually schema types that created resolvers are being kept).
Then, when you proceed to publish your changes, what happens next is, that the stack is being uploaded without the deleted resolvers, which then triggers model removal on the servers, basically, it drops the models on the remote and the corresponding DynamoDB tables. Right after the deployment is complete, resolvers are being rebuild, but at this point, your application is broken, as it is missing models in productions…
If you then deploy (simply ‘amplify push’) again, everything is deployed back, except that you have lost the data, of course, what else can go wrong…

### Expected behavior

Either:

1. Do not remove the autogenerated resolvers when exiting the process mock process via ctrl+c.
2. (Better) Execute the internal amplify resolvers build procedure, prior deployment of the stack.

### Reproduction steps

1. Create a simple graphql schema model and run `amplify push`
2. Run `amplify mock` and wait until it loads, then hit ctrl+c to terminate the process (at this point your autogenerated resolvers will disappear).
3. Run `amplify push` again and your remote will drop the models and DynamoDB tables.
4. Run `amplify push` again and your remote will restore your models and DynamoDB tables, but your data will be lost.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Application @model {
  id: ID!
  name: String
}
```

</details>

### Log output

<details>

```
# Put your logs below this line
^C^Aborted!

```

</details>

### Additional information

Another thing, that helped me spot the root cause of this accident (it took me a while to understand how it happened), is that I use to code ith VSCode, and do inline debugging. Unfortunately it stopped working recently, but when I simply terminate the process trough the VSCode interface (without inputting the CTR+C command), it does not remove the resolvers… Another thing is, that I also have input capabilities to the process while “debugging” trough the editor, and if I hit the ctrl+c trough that interface, my resolvers are again being removed.

Only workaround is to run the mock trough the VSCode debugger, which rebuilds the resolvers and then terminate the process via VSCode terminate.

here is a sample of how I run the process trough the editor:

`
{
        "type": "node",
        "request": "launch",
        "name": "Amplify",
        "osx": {
          "program": "`npm root -g`/@aws-amplify/cli/bin/amplify"
        },
        "linux": {
          "program": "`npm root -g`/@aws-amplify/cli/bin/amplify"
        },
        "windows": {
          "program": "C:\\Program Files\\nodejs\\node_modules\\@aws-amplify\\cli\\bin\\amplify"
        },
        "args": [
          "mock",
          "--timeout",
          "30"
        ],
        "console": "integratedTerminal" 
}
`

**Comment by yuth** [comment] 2021-06-01 16:55
I have tried reproducing the issue with the give steps but I could not reproduce this issue. When I do `amplify push` after `^c`ing the mock server, the CLI does not deploy anything as there isn't any change detected. Are there any steps missing?

 > There is a (by design) problem we hit with the cli, while using the mock functionality, built in with the cli. What happens is that, when you hit ctrl+C to terminate the process, it somehow uses this input and triggers a delete of the autogenerated resolvers files, that the amplify cli builds (manually schema types that created resolvers are being kept).

The resolvers generated by mock are in `<project-root>/amplify/backend/api/<api-name>/resolvers` and the files that get uploaded are inside `<project-root>/amplify/backend/api/<api-name>/build/resolvers`. Killing the mock server with `^c` should not cause any impact on deployment.

Do you use any additional flags when running `amplify push`?

**Comment by fakedob** [comment] 2021-06-01 17:58
Hey @yuth , I can share more details on exactly what we do, but I think you are missing a step. In order to observe the behaviour, you may only need to run the mock command and then stop it via "ctrl+c". If you do this and then check the resolvers folder inside your amplify project, it will be missing the autogenerated .vtl files. Once in that state, if you try to push again, you will notice that there are pending changes, event if you havent really done anything to you schema. That is, because the .vtl files are missing, which makes the cli think, you have removed your models. Hope that makes it clear, but if not, I can prepare a quick demo and record it. 

As for the amplify push command, there are no flags added, but also I actually execute publish, since we also deploy our web app via amplify, but that doesnt really make any difference for the actual problem, since the problem is not with pushing the changes, but because mock deletes the vtl files, right after you end the process.

**Comment by fakedob** [comment] 2021-06-01 18:41
I hope you can see it clearly here. When I first run the `amplify init` or push/publish, the missing resolvers are being created. But later when I use the `mock` command, it rebuilds them and deletes them on stop.


https://user-images.githubusercontent.com/8687970/120374115-cddbc000-c321-11eb-92ac-09c221072c20.mp4

**Comment by jhockett** [comment] 2021-06-01 20:50
I was able to reproduce this behavior @fakedob. It happens when you have your schema in the `/schema` folder.

As a temporary workaround, you can put your schema in a `schema.graphql` file in `amplify/backend/api/<api-name>/schema.graphql` until we are able to fix this. Thanks for reporting this issue!

**Comment by fakedob** [comment] 2021-06-02 08:14
> ~I was able to reproduce this behavior~ @fakedob. Thanks for reporting this issue!
> 
> Edit: I spoke too soon. There wasn't any change in my status, no production data was lost, and the behavior I saw is intended.

I do understand this behaviour is intended on the mock command, but unfortunately, if I then push the changes, it will drop the models on the remote and will then recreate them on the same execution, which makes the data disappear on the remote. When then happens, the `amplify push` command rebuilds the .vtl files, after the stack is being uploaded with the missing .vtl files.

**Comment by yuth** [comment] 2021-06-02 16:48
I see the resolvers getting deleted from your video(when you do `git status`). Do you know if the content of the resolver identical to what is auto generated by the transformer? Mock deletes all the resolvers if the content inside `resolver` file is identical to what it would create.

 > if I then push the changes, it will drop the models on the remote and will then recreate them on the same execution, which makes the data disappear on the remote. 

Does this cause the deletion of the DynamoDB table or just missing resolvers?

**Comment by fakedob** [comment] 2021-06-03 08:04
Hey @yuth It looks like it does remove the resolvers, that are identical to the autogenerated (it does not remove the ones that I have customised/edited).
As for the second part, yes it does remove the DynamoDB table, then it creates them with different hash number, so its actually a new table and the old one is being complete removed.

**Comment by josefaidt** [comment] 2021-06-03 21:13
Hey @fakedob I have not been able to reproduce this issue so far with the provided steps.

> it does not remove the ones that I have customised/edited

After editing one of the auto-generated vtl's I did notice the file did not get removed when stopping the mock server (similar to what was described in the original post), however after pushing I did not experience a loss of data. Could you expound on the customizations?

**Comment by yuth** [comment] 2021-06-07 16:59
> As for the second part, yes it does remove the DynamoDB table, then it creates them with different hash number, so its actually a new table and the old one is being complete removed.

GraphQL transformer is designed in such a way that the resolvers are generated for the `@model`s that are annotated in your schema and `@model` directive is the one which controls the creation of the table. Changing/removing the resolvers just change the behavior of GraphQL API behavior but does not cause deletion of any table. So what is not very clear to me from the screencast is if there was any change to schema itself where some `@model` was removed. Could you see if there was any changes in `amplify/backend/api/skinnyott/schema/` folder?

**Comment by fakedob** [comment] 2021-06-07 19:08
Hey, I have been a bit busy, sorry for the delay.
Unfortunately github doesn't allow me to upload a longer video, so I can't show more details, but basically, in my schema folder there is no change either in the file structure or the content of the .grapqhl models. When the problem occurs, it's when the resolvers are missing, I am pretty sure. Then, when the resolvers are missing and I execute `amplify push` I do see a the cli telling me there are pending changes. If I proceed with YES, then after the stack has been uploaded I start seend logs saying "DELETING..." and then "CREATING..." with multiple lines corresponding to the resolvers names that are missing (and corresponding DynamoDB tables). Those are saying just "UPDATING..." when the resolvers have not being deleted prior uploading the changes.
There are couple of things to note, which also may not be clear, I am not sure if this happens everytime, it may happen just sometimes under more complex conditions, I cannot be sure, but I know for sure, that I have observed this behaviour two times, and both times it was when the resolvers were missing, after I have used the mock command and I am sure, that it doesn't happen if I build the resolvers prior pushing the changes (if any).
As far as I understand, you do not observe this behaviour, like, when you are missing the resolvers the cli does not show any pending changes, which makes me wonder why it does on my end. Basically, even if nothing has changes, running and stopping the mock command (which only removes some of the resolvers) does give me pending changes when I run the push command.
With that being said, I see I need to setup a demo, sampling exactly what happens over my screen and put it in a project. I will do my best to do it in the next few days, as soon as I can and will update you back. In the meantime, if I can give you anymore details, just let me know. Thanks.

**Comment by GeorgeBellTMH** [comment] 2021-07-10 07:19
#5972 may have helped...

**Comment by josefaidt** [comment] 2021-08-02 16:39
Hey @fakedob :wave: I wanted to follow-up to see if you are still experiencing this issue and if you were able to create a small demo to reproduce this issue?

**Comment by josefaidt** [comment] 2021-08-12 14:06
Hey @fakedob just wanted to follow-up and see if you were still experiencing this issue and whether you were able to create a demo?

**Comment by kaustavghosh06** [comment] 2021-09-10 16:08
Closing based on last response and no further communication on this. Please let us know if you're still stuck on this issue.

**Closed by kaustavghosh06** 2021-09-10 16:08 UTC
Labels: pending-close-response-required, pending-triage, not-reproducible, mock, api-graphql
