### ISSUE TITLE
Issue with amplify initializing an Angular Project

### ISSUE THREAD

**Issue by ewsams** [aws-amplify/amplify-cli#6250] opened 2020-12-24 02:52 UTC
![image](https://user-images.githubusercontent.com/40345707/103055659-dfe25700-4568-11eb-9381-a4d6bb5358d1.png)
I have tried npm installing amplify-frontend-javascript after the cli. Using the latest amplify version as well on windows.

**Comment by jhockett** [comment] 2020-12-24 03:17
Closing as duplicate of https://github.com/aws-amplify/amplify-cli/issues/6246. Workaround in the comments.

**Closed by jhockett** 2020-12-24 03:17 UTC
