### ISSUE TITLE
Amplify add api: Error: Section 'overrides' is not registered in feature provider

### ISSUE THREAD

**Issue by zirkelc** [aws-amplify/amplify-cli#9258] opened 2021-12-08 16:10 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm install -g

### If applicable, what version of Node.js are you using?

16.13

### Amplify CLI Version

7.6.2

### What operating system are you using?

macOS

### Amplify Categories

api

### Amplify Commands

add

### Describe the bug

In a brand new Amplify project, I did `amplify init` and then `amplify add api` which resulted in the following error:

![2021-12-08_17-03-18](https://user-images.githubusercontent.com/950244/145241719-fab5f312-4778-408b-8eaa-9d5acf701161.png)

The `/amplify/cli.json` file contains the following feature flags:
```json
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "improvepluralization": false,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": true,
      "enableiterativegsiupdates": true,
      "secondarykeyasgsi": true,
      "skipoverridemutationinputtypes": true,
      "transformerversion": 2,
      "suppressschemamigrationprompt": true
    },
    "frontend-ios": {
      "enablexcodeintegration": true
    },
    "auth": {
      "enablecaseinsensitivity": true,
      "useinclusiveterminology": true,
      "breakcirculardependency": true,
      "forcealiasattributes": false,
      "useenabledmfas": true
    },
    "codegen": {
      "useappsyncmodelgenplugin": true,
      "usedocsgeneratorplugin": true,
      "usetypesgeneratorplugin": true,
      "cleangeneratedmodelsdirectory": true,
      "retaincasestyle": true,
      "addtimestampfields": true,
      "handlelistnullabilitytransparently": true,
      "emitauthprovider": true,
      "generateindexrules": true,
      "enabledartnullsafety": true
    },
    "appsync": {
      "generategraphqlpermissions": true
    },
    "latestregionsupport": {
      "pinpoint": 1,
      "translate": 1,
      "transcribe": 1,
      "rekognition": 1,
      "textract": 1,
      "comprehend": 1
    },
    "project": {
      "overrides": true
    }
  }
}
```

### Expected behavior

Add api as expected

### Reproduction steps

1. amplify init
2. amplify add api

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by akshbhu** [comment] 2021-12-08 17:46
We have a PR fixiing htis issue : #9249. You can comment and follow updates on the linked issue.
closing as duplicate of : #9165

**Closed by akshbhu** 2021-12-08 17:46 UTC
