### ISSUE TITLE
Error response on Multi-Auth with api_key

### ISSUE THREAD

**Issue by tw1t611** [aws-amplify/amplify-cli#2372] opened 2019-09-22 16:34 UTC
**Describe the bug**
Hi, I have got an unauthorized error with multi-auth and api key.
The error was thrown, when I got the right data.
The query works using cognito.

Schema:
```gql
type Product
  @model(subscriptions: null)
  @auth(
    rules: [
      { allow: owner }
      { allow: public, queries: [get, list], mutations: null }
    ]
  ) {
  id: ID!
  title: String!
  description: String!
  price: Int
  images: [String] # s3 file names
  webshop: Webshop @connection(name: "WebshopProducts")
}
```
Query:
```js
product = await API.graphql({
        query: getProduct,
        variables: { id: props.page },
        authMode: "API_KEY",
      })
```

Response:
```json
{
   "data":{
      "getProduct":{
         "id":"4a620dc4-42e6-4746-bc96-6a6e5c9253d0",
         "title":"asdf",
         "description":"asdf",
         "price":3,
         "images":[
            "1569168455589-523635.jpg"
         ],
         "webshop":{
            "id":"bd611fe3-1f4b-4d51-8017-ba7904a302ce",
            "user":{
               "email":"client55@protonmail.com",
               "username":"client5"
            },
            "products":{
               "nextToken":null
            },
            "orders":{
               "nextToken":null
            }
         }
      }
   },
   "errors":[
      {
         "path":[
            "getProduct",
            "webshop",
            "orders",
            "nextToken"
         ],
         "data":null,
         "errorType":"Unauthorized",
         "errorInfo":null,
         "locations":[
            {
               "line":18,
               "column":9,
               "sourceName":null
            }
         ],
         "message":"Not Authorized to access nextToken on type ModelOrderConnection"
      }
   ]
}
```

Working cognito query:
```js
product = await API.graphql(
        graphqlOperation(getProduct, { id: props.page })
      )
```

**To Reproduce**
1. Log in with cognito.
2. Create a product.
3. Query the product using the api key.

**Expected behavior**
If the data of the response is correct, there should not be an error thrown.

**Desktop (please complete the following information):**
 - latest Debian
 - latest Chromium
 - amplify-cli 3.2.0

**Comment by kaustavghosh06** [comment] 2019-09-23 19:59
@tw1t611 Could you also provide us with the Webshop @model as well? We would need to take a look at the @auth rules out there as well to root cause this. Thanks!

**Comment by tw1t611** [comment] 2019-09-26 13:39
Hi, sorry I am late.
Here is the schema for the webshop: 
```gql
type Webshop
  @model(subscriptions: null)
  @auth(
    rules: [
      { allow: owner }
      { allow: public, queries: [get], mutations: null }
    ]
  ) {
  id: ID!
  user: User @connection(name: "UserWebshop")
  products: [Product] @connection(name: "WebshopProducts")
  orders: [Order]
    @connection(name: "WebshopOrders")
    @auth(rules: [{ allow: private, operations: [create] }])
}
```

**Comment by tw1t611** [comment] 2019-09-26 16:14
FYI: I found another bug, which may is related to the problem.
The following auth rule allows mutation by the owner as expected.
`@auth(rules: [{ allow: owner }, { allow: public, queries: [get, list] }])`

This auth rule does not allow mutation by the owner, even if it is only restricted to public.
`@auth(rules: [{ allow: owner }, { allow: public, queries: [get, list], mutations: null }])`

The same applies to groups.
`@auth(rules: [{ allow: owner }, { allow: groups, groups: ["Users"], queries: [get, list], mutations: null }])`

**Comment by attilah** [comment] 2019-09-30 15:23
@tw1t611 based on your ```Webshop``` schema, only ```owner```s has access to the list operation on it and I assume that ```public``` has no access to the ```Order``` type. I can't see a rule what would allow ```public``` to access ```Webshop.orders```.

**Comment by tw1t611** [comment] 2019-09-30 20:37
@attilah That seems correct. Sadly my schema changed. Therefor I will check the issue on the new schema as soon as #2439 was merged.
Thank you very much for the fast fix :).

**Comment by attilah** [comment] 2019-10-01 11:08
Closing the issue as the question was answered. Feel free to reopen if something new comes up or open a new issue if it is unrelated.

**Closed by attilah** 2019-10-01 11:08 UTC
Labels: graphql-transformer, pending-response, question
