### ISSUE TITLE
Export Amplify backends to Python CDK not working

### ISSUE THREAD

**Issue by lazpavel** [aws-amplify/amplify-cli#12448] opened 2022-06-07 22:48 UTC
**Initial environment of AWS**

```
Admin:~/environment $ cdk --version
2.3.0 (build beaa5b2)
Admin:~/environment $ amplify --version
bash: amplify: command not found
Admin:~/environment $ npm list
ec2-user@ /home/ec2-user
├── node-cleanup@2.1.2
└── tmp@0.0.33

Admin:~/environment $ python --version
Python 3.7.10
Admin:~/environment $ pip freeze
astroid==2.3.0
aws-cfn-bootstrap==2.0
backcall==0.2.0
botocore==1.23.27
decorator==5.1.0
Django==2.0.2
docutils==0.14
git-remote-codecommit==1.16
ikp3db==1.4.1
importlib-metadata==4.10.0
ipython==7.30.1
isort==4.3.21
jedi==0.18.1
jmespath==0.10.0
lazy-object-proxy==1.7.1
lockfile==0.11.0
matplotlib-inline==0.1.3
mccabe==0.6.1
parso==0.8.3
pbr==5.8.0
pexpect==4.8.0
pickleshare==0.7.5
prompt-toolkit==3.0.24
ptyprocess==0.7.0
Pygments==2.11.1
pylint==2.4.4
pylint-django==2.3.0
pylint-flask==0.6
pylint-plugin-utils==0.7
pystache==0.5.4
python-daemon==2.2.3
python-dateutil==2.8.2
pytz==2021.3
simplejson==3.2.0
six==1.16.0
stevedore==3.5.0
traitlets==5.1.1
typed-ast==1.5.1
typing-extensions==4.0.1
urllib3==1.26.7
virtualenv==16.2.0
virtualenv-clone==0.5.7
virtualenvwrapper==4.8.4
wcwidth==0.2.5
wrapt==1.13.3
zipp==3.7.0
Admin:~/environment $ node -v
v16.13.1
```

**install amplify**
```
Admin:~/environment $ npm install -g @aws-amplify/cli
Admin:~/environment $ npm list
ec2-user@ /home/ec2-user
├── node-cleanup@2.1.2
└── tmp@0.0.33

Admin:~/environment $ npm list -g
/home/ec2-user/.nvm/versions/node/v16.13.1/lib
├── @aws-amplify/cli@7.6.14
├── cdk@2.3.0
├── coffeescript@2.6.1
├── corepack@0.10.0
├── esformatter@0.11.3
├── js-beautify@1.14.0
├── npm@8.1.2
├── prettier@2.5.1
└── typescript@3.7.5
```

**setup amplify project**
```
Admin:~/environment $ mkdir amplify-proj && cd amplify-proj
Admin:~/environment/amplify-proj $ amplify init -y
Admin:~/environment/amplify-proj $ amplify add api && amplify push
Admin:~/environment/amplify-proj $ amplify add api

? Select from one of the below mentioned services: GraphQL
? Here is the GraphQL API that we will create. Select a setting to edit or continue Continue
? Choose a schema template: Single object with fields (e.g., “Todo” with ID, name, description)

⚠️  WARNING: your GraphQL API currently allows public create, read, update, and delete access to all models via an API Key. To configure PRODUCTION-READY authorization rules, review: https://docs.amplify.aws/cli/graphql/authorization-rules

GraphQL schema compiled successfully.

Edit your schema at /home/ec2-user/environment/amplify-proj/amplify/backend/api/amplifyproj/schema.graphql or place .graphql files in a directory at /home/ec2-user/environment/amplify-proj/amplify/backend/api/amplifyproj/schema
? Choose your default editor: Visual Studio Code
Couldn’t find selected code editor (vscode) on your machine.
? Try opening with system-default editor instead? Yes
✅ Successfully added resource amplifyproj locally

✅ Some next steps:
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud
```

**change directory**
`Admin:~/environment/amplify-proj $ cd ../`

**downgrade CDK**
```
Admin:~/environment $ npm uninstall cdk -g
Admin:~/environment $ npm i aws-cdk@1.x -g
```

**setup CDK project**
```
Admin:~/environment $ mkdir cdk-proj && cd cdk-proj
Admin:~/environment/cdk-proj $ cdk init sample-app --language python
Admin:~/environment/cdk-proj (master) $ python -m venv .venv
Admin:~/environment/cdk-proj (master) $ source .venv/bin/activate
(.venv) Admin:~/environment/cdk-proj (master) $ pip install --upgrade pip
(.venv) Admin:~/environment/cdk-proj (master) $ pip install -r requirements.txt
(.venv) Admin:~/environment/cdk-proj (master) $ cdk bootstrap
(.venv) Admin:~/environment/cdk-proj (master) $ cdk deploy
Do you wish to deploy these changes (y/n)? y
# cdk deployment succeed　if there's not amplify exported backend
```

**export amplify backend**
```
(.venv) Admin:~/environment/cdk-proj (master) $ cd ../amplify-proj/
(.venv) Admin:~/environment/amplify-proj $ amplify export --out ../cdk-proj/
```

**install python library**
```
(.venv) Admin:~/environment/cdk-proj (master) $ cd ../cdk-proj/
(.venv) Admin:~/environment/cdk-proj (master) $ pip install aws-amplify.cdk.exported-backend
```
**modify cdk-proj/cdk_proj/cdk_proj_stack.py**
```
from aws_cdk import (
    aws_iam as iam,
    aws_sqs as sqs,
    aws_sns as sns,
    aws_sns_subscriptions as subs,
    core
)
from aws_amplify.cdk.exported_backend import AmplifyExportedBackend


class CdkProjStack(core.Stack):

    def __init__(self, scope: core.Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        queue = sqs.Queue(
            self, "CdkProjQueue",
            visibility_timeout=core.Duration.seconds(300),
        )

        topic = sns.Topic(
            self, "CdkProjTopic"
        )

        topic.add_subscription(subs.SqsSubscription(queue))
        
        AmplifyExportedBackend(self, id="AmplifyExportedBackend",
        path="amplify-export-amplifyproj", amplify_environment="dev")
```

**(FAILURE) CDK DIFF**
```
(.venv) Admin:~/environment/cdk-proj (master) $ cdk diff
jsii.errors.JavaScriptError: 
  TypeError: _.get is not a function
      at AmplifyExportAssetHandler.referenceDeploymentBucket (/tmp/jsii-kernel-MYu61N/node_modules/@aws-amplify/cdk-exported-backend/lib/export-backend-asset-handler/index.js:29:40)
      at new AmplifyExportAssetHandler (/tmp/jsii-kernel-MYu61N/node_modules/@aws-amplify/cdk-exported-backend/lib/export-backend-asset-handler/index.js:25:38)
      at new AmplifyExportedBackend (/tmp/jsii-kernel-MYu61N/node_modules/@aws-amplify/cdk-exported-backend/lib/export-backend.js:33:38)
      at /tmp/tmp6hjkb0zd/lib/program.js:8432:58
      at Kernel._wrapSandboxCode (/tmp/tmp6hjkb0zd/lib/program.js:8860:24)
      at Kernel._create (/tmp/tmp6hjkb0zd/lib/program.js:8432:34)
      at Kernel.create (/tmp/tmp6hjkb0zd/lib/program.js:8173:29)
      at KernelHost.processRequest (/tmp/tmp6hjkb0zd/lib/program.js:9757:36)
      at KernelHost.run (/tmp/tmp6hjkb0zd/lib/program.js:9720:22)
      at Immediate._onImmediate (/tmp/tmp6hjkb0zd/lib/program.js:9721:46)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 9, in <module>
    CdkProjStack(app, "cdk-proj")
  File "/home/ec2-user/environment/cdk-proj/.venv/lib64/python3.7/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/ec2-user/environment/cdk-proj/cdk_proj/cdk_proj_stack.py", line 28, in __init__
    path="amplify-export-amplifyproj", amplify_environment="dev")
  File "/home/ec2-user/environment/cdk-proj/.venv/lib64/python3.7/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/ec2-user/environment/cdk-proj/.venv/lib64/python3.7/site-packages/aws_amplify/cdk/exported_backend/__init__.py", line 286, in __init__
    jsii.create(self.__class__, self, [scope, id, props])
  File "/home/ec2-user/environment/cdk-proj/.venv/lib64/python3.7/site-packages/jsii/_kernel/__init__.py", line 297, in create
    for iface in getattr(klass, "__jsii_ifaces__", [])
  File "/home/ec2-user/environment/cdk-proj/.venv/lib64/python3.7/site-packages/jsii/_kernel/providers/process.py", line 344, in create
    return self._process.send(request, CreateResponse)
  File "/home/ec2-user/environment/cdk-proj/.venv/lib64/python3.7/site-packages/jsii/_kernel/providers/process.py", line 326, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: _.get is not a function
Subprocess exited with error 1
```

**Comment by josefaidt** [comment] 2023-04-13 18:32
Closing as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/12447

**Closed by josefaidt** 2023-04-13 18:32 UTC
Labels: feature-request, transferred, duplicate, export
