### ISSUE TITLE
Manually deleted GSI blocks any push or deploy

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#9106] opened 2021-11-26 20:03 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### Amplify CLI Version

7.5.2

### What operating system are you using?

Windows

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

I've manually deleted my indexes from my DynamoDB table (this was in an effort to speed up deployment, remove the old ones and then just push up my new ones).

This appears to have completely confused Amplify. It can't or won't create the indexes again nor will it recognise the indexes if I manually create them in DynamoDB.

As a result I cannot deploy at all as every time I do it just rollsback.

Main error I've getting is:

 "Cannot perform more than one GSI creation or deletion in a single update"

This is being raised for each table that had the index changes on in my old schema. I've reverted my schema and tried again and still get the same issue. Seems rather that seeing what is actually in DynamoDB its trying to build up what it thinks should be there from some other config/meta file and failing.

I've ensured I have the enableIterativeGsiUpdates feature flag set to true (as documented here https://docs.amplify.aws/cli/graphql/troubleshooting/#deploying-multiple-index-changes-at-once) which should allow me to do multiple GSI updates in one go.

I've tried to run `amplify push --iterative-rollback` too but with no effect, still get the same error.

In its current state I'm completely locked out of any updates to my environment via Amplify.

### Expected behavior

I hoped that it would check to see what indexes already existing in DynamoDB and either created/deleted them as it needed. Instead I think its looking into a file somewhere which no doesn't match reality and falling over as a result. 

### Reproduction steps

Delete multiple indexes from the same table or multiple tables. Attempt to push.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line

#Nothing too crazy, here is an sample of how we are defining our keys etc.

type Round
  @model
  @key(
    name: "byTechnicianByDate"
    fields: ["technicianID", "date"]
    queryField: "roundsByTechnicianByDate"
  )
  @auth(
    rules: [
      { allow: groups, groups: ["admin"] }
      { allow: public, provider: apiKey }
    ]
  ) {
  id: ID!
  date: AWSDateTime
  visits: [ID]
  routeVisitsHash: String
  technicianID: ID
  technician: StaffMember @connection(fields: ["technicianID"])
  earnPerDayTarget: Float!
  status: String #RoundStatus
  areaID: ID!
  routingID: String
  totalRoundDistance: Float
  totalRouteDurationSeconds: Int
  distanceUnit: String
  roundDirection: String # RoundDirection
  notes: String
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

![image](https://user-images.githubusercontent.com/1674590/143625729-e0ae9aef-46ad-40de-a83b-58fe11d7db8b.png)

![image](https://user-images.githubusercontent.com/1674590/143625740-2684b6d2-1264-421b-81a5-bfd873973353.png)

**Comment by sachscode** [comment] 2021-11-28 20:29
@PeteDuncanson 
1. Do you have data in the dynamodb tables ? 
2. Could you please share the contents of the file named deployment-state.json.

**Comment by PeteDuncanson** [comment] 2021-11-28 21:02
@sachscode hi again :)

1. yes we do, don't want to loss it either
2. I'm not pushing from local, this is via the CI. where would I find it?

**Comment by sachscode** [comment] 2021-11-28 21:45
@PeteDuncanson 
Hi again :)
So when you mention "amplify push --iterative-rollback " was this in CI ? 
Since the tables have been deleted manually, amplify seems to be confused because of the drift. 
Can you please try to run iterative-rollback locally. I feel once the drift is fixed, Circle CI should be able to work.

**Comment by PeteDuncanson** [comment] 2021-11-29 11:53
@sachscode ahh sorry for the confusion.

I ran `amplify push --iterative-rollback` locally already (I'm not sure how I would run that via CI?) and it didn't do anything sadly I just get the same error.

I'm with you, I think once its "reset" itself somehow I think it will just work. Trouble is I'm not sure where its getting its data from for what it thinks is already in DynamoDB or not. There must be a meta file somewhere that its using but I don't know which one or how to find it or how to edit it and how to deploy it in such a way to unstick it.

**Comment by sundersc** [comment] 2021-11-30 22:42
Discussed offline - the issue was caused by the drift (manually deleted indexes) in the cloudformation stacks. It was resolved by manually recreating the indexes so that the aws resources are in sync with the amplify project stack.

**Closed by sundersc** 2021-11-30 22:42 UTC
Labels: bug, graphql-transformer
