### ISSUE TITLE
Build tables before lambdas that reference them

### ISSUE THREAD

**Issue by kldeb** [aws-amplify/amplify-cli#7506] opened 2021-06-11 13:49 UTC
### Is this related to a new or existing Amplify category?

storage, function

### Describe the feature you'd like to request

When there are one or more new tables and one or more new lambdas that have been granted access to those tables create the tables first then the lambdas. 

### Describe the solution you'd like

Currently, some of our features have to be deployed in different envs by removing access to new tables that haven't been created it. Would like a flag to deploy CF templates in stages like the multiple key deployment option.

### Describe alternatives you've considered

just editing the lambdas and then adding the access back. Real pain...

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by akshbhu** [comment] 2021-06-14 19:24
Hi 

Let me understand the problem. So when you add a 1 or models to the schema and attach a function to those models ,Does CFN fails to upload that?

Are you getting any error in amplify push related to this?

**Comment by kldeb** [comment] 2021-06-14 21:21
> Let me understand the problem. So when you add a 1 or models to the schema and attach a function to those models ,Does CFN fails to upload that?

Yes. Trying to push a new `@model` that is referenced in a function fails to deploy.
 
> Are you getting any error in amplify push related to this?

Yes, it says the resource doesn't exist when it tries to deploy the lambda.

**Comment by akshbhu** [comment] 2021-06-14 21:25
Yeah this is a duplicate of this issue https://github.com/aws-amplify/amplify-cli/issues/7372. we already have a PR which will address this in nest release.

Closing this in favour of #7372

**Closed by akshbhu** 2021-06-14 21:25 UTC
Labels: feature-request, functions, pending-response

**Comment by danielvouch** [comment] 2021-06-15 11:55
@akshbhu When can we expect this to be released?
