### ISSUE TITLE
Cannot find AppsyncApiId in lambda stack

### ISSUE THREAD

**Issue by ldariozero12** [aws-amplify/amplify-cli#3592] opened 2020-03-05 09:44 UTC
**Describe the bug**
I created a function with `amplify add fuction` and in a question _"Do you want to access other resources created in this project from your Lambda function?"_ i selected `api` with all permission.

**But when run amplify mock it shows the following error**:
```
Failed to parse Lambda function cloudformation in C:\Users\Lucad\lavoro\repo\zero12\test-amplify\amplify\backend\function\test1\test1-cloudformation-template.json

Error: Could not find ref for "apitestGraphQLAPIIdOutput"
Failed to start API Mock endpoint Error: Lambda function test1 does not exist in your project.
Please run amplify add function
```
The fuction-parameters.json of the lambda is the following (it seems correct):

```
{
    "permissions": {
        "api": {
            "test": [
                "create",
                "read",
                "update",
                "delete"
            ]
        }
    }
}
```
And the {name-function}-cloudformation-template.json contains:
```
"Parameters": {
        "env": {
            "Type": "String"
        },
        "apitestGraphQLAPIIdOutput": {
            "Type": "String",
            "Default": "apitestGraphQLAPIIdOutput"
            },
        
        "apitestGraphQLAPIEndpointOutput": {
            "Type": "String",
            "Default": "apitestGraphQLAPIEndpointOutput"
            }
    }
            .....
           ......
          "Variables" : {
                    "ENV": {
                        "Ref": "env"
                    },
                    "REGION": { 
                        "Ref": "AWS::Region"
                    }
                    ,"API_TEST_GRAPHQLAPIIDOUTPUT": {
                        "Ref": "apitestGraphQLAPIIdOutput"
                    }, 
                    "API_TEST_GRAPHQLAPIENDPOINTOUTPUT": {
                              "Ref": "apitestGraphQLAPIEndpointOutput"
                              } 
                }

```
Where are the possible problem?

**Amplify CLI Version**
4.13.4

**Expected behavior**
Access to appSyncID inside the lambda with proccess.env.API_TEST_GRAPHQLAPIIDOUTPUT

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Node Version. 12.14.1

**Comment by nikhname** [comment] 2020-03-05 17:52
@ldariozero12 does this error happen only with mock or when you try to push your resources as well?

**Comment by kaustavghosh06** [comment] 2020-03-06 01:00
This is a  bug and closing this issue as a duplicate of #2690

**Closed by kaustavghosh06** 2020-03-06 01:00 UTC
Labels: mock, pending-triage
