### ISSUE TITLE
Headless `amplify init` fails after upgrading the CLI

### ISSUE THREAD

**Issue by paolo573** [aws-amplify/amplify-cli#7642] opened 2021-07-01 14:04 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

On a `python:3.8.11-slim` Docker container, with `RUN npm install -g @aws-amplify/cli@5.0.2`

### If applicable, what version of Node.js are you using?

v12.22.1

### Amplify CLI Version

5.0.2

### What operating system are you using?

Ubuntu

### Amplify Categories

Not applicable

### Amplify Commands

init

### Describe the bug

Started experiencing a deploy blocker during the headless CLI `amplify init` step, after upgrading Amplify from v4.44.2 yesterday. The `amplify upgrade` command installed v5.0.2, and I updated my Dockerfile to reflect that. 

The command is:

`amplify init --amplify "$AMPLIFY" --frontend "$FRONTEND" --providers "$PROVIDERS" --yes`

Here are the values being passed in: 

$AMPLIFY
`{"projectName":"myProject","envName":"qa","defaultEditor":"none"}`

$FRONTEND
`{"frontend":"javascript","framework":"react","config":{"SourceDir":"src","DistributionDir":"build","BuildCommand":"npm run-script build","StartCommand":"npm run-script start"}}`

$PROVIDERS
`{"awscloudformation":{"configLevel":"project","useProfile":false,"accessKeyId":"ASIA***","secretAccessKey":"***","region":"***"}}`

The output is:
```
Note: It is recommended to run this command from the root of your app directory
Invalid configuration settings!
? Do you want to retry configuration? (y/N) 
```

Seems like it chooses No there, and the next step (amplify env checkout) fails. I confirmed that the pwd is the root of the app directory.

### Expected behavior

Our Headless CLI CI/CD implementation broke after running `amplify upgrade` and updating scripts accordingly. Following advice from past issues like https://github.com/aws-amplify/amplify-cli/issues/6657#issuecomment-781732391 it seems that our configuration is not invalid.

### Reproduction steps

The `amplify init` step is the very first step in the process, so the steps to reproduce are to provision the container and call the init command with the input parameters.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
Note: It is recommended to run this command from the root of your app directory
Invalid configuration settings!
? Do you want to retry configuration? (y/N) 


```

</details>

### Additional information

Perhaps we should be running this on a different base Docker image? Here is our full Dockerfile:

```
FROM python:3.8.11-slim

RUN apt-get update

RUN apt-get install -y curl pipenv git
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash
RUN apt-get install -y nodejs
RUN npm i npm@latest -g
RUN npm install -g @aws-amplify/cli@5.0.2
RUN pip3 install --no-cache-dir awscli
```

**Comment by josefaidt** [comment] 2021-07-01 16:01
Hey @paolo573 :wave: thanks for raising this. I'm unable to reproduce this with the provided Dockerfile and a small init script using the same parameters. It appears this error is coming from an invalid AWS configuration, can you verify the `accessKeyId` and `secretAccessKey` are valid?

**Comment by paolo573** [comment] 2021-07-01 16:51
Thanks for the quick reply @josefaidt,

The error didn't say which part of the config was invalid, so thank you for confirming it means the AWS credentials.

We are using the following AWS Managed Policies:
- AmazonEC2FullAccess
- AWSLambdaVPCAccessExecutionRole
- AdministratorAccess-Amplify

And a customer managed policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "amplify:ListJobs",
                "amplify:CreateDeployment",
                "amplify:StartDeployment",
                "amplify:GetJob"
            ],
            "Resource": "arn:aws:amplify:***:***:apps/*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "cloudfront:GetCloudFrontOriginAccessIdentity"
            ],
            "Resource": "arn:aws:cloudfront::***:origin-access-identity/*"
        },
        {
            "Effect": "Allow",
            "Action": "cognito-idp:UpdateGroup",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "iam:CreatePolicyVersion",
                "iam:DeletePolicyVersion"
            ],
            "Resource": "arn:aws:iam::***:policy/amplify-*"
        },
        {
            "Effect": "Allow",
            "Action": "route53:ListHostedZones",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "sns:GetTopicAttributes",
            "Resource": "arn:aws:sns:***:***:*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetEncryptionConfiguration",
                "s3:PutEncryptionConfiguration"
            ],
            "Resource": "arn:aws:s3:::*"
        }
    ]
}
```

**Comment by cjihrig** [comment] 2021-07-01 20:27
I am also unable to reproduce this issue on v5.0.2 of the CLI. It looks like you are using temporary credentials (`"accessKeyId":"ASIA***"`) - is there any chance those have expired?

I'm attaching a runnable script for reproduction isssues.

<details>
CLI="amplify"

AMPLIFY="{\
\"projectName\":\"myProject\",\
\"envName\":\"qa\",\
\"defaultEditor\":\"none\"\
}"

FRONTEND="{\
\"frontend\":\"javascript\",\
\"framework\":\"react\",\
\"config\": {\
\"SourceDir\":\"src\",\
\"DistributionDir\":\"build\",\
\"BuildCommand\":\"npm run-script build\",\
\"StartCommand\":\"npm run-script start\"\
}\
}"

PROVIDERS="{\
\"awscloudformation\": {\
\"configLevel\":\"project\",\
\"useProfile\":false,\
\"accessKeyId\":\"****\",\
\"secretAccessKey\":\"****\",\
\"region\":\"****\"\
}\
}"

$CLI init --amplify "$AMPLIFY" --frontend "$FRONTEND" --providers "$PROVIDERS" --yes
$CLI -v
</details>

**Comment by cjihrig** [comment] 2021-07-01 20:55
I was just able to reproduce this by using temporary credentials. Labeling this as a bug. As a temporary workaround, please try using a normal access key.

**Comment by paolo573** [comment] 2021-07-01 21:16
@cjihrig thanks for working to reproduce this

In regards to your temporary workaround suggestion: appreciate it but am wondering how long a fix will take, so we can decide on whether to attempt a rollback (can we push a stack with 4.44.2 after `amplify push`ing from 5.0.2? I had pushed manually in nonprod envs to see if the app worked after the upgrade)

This is running in an ephemeral CI pipeline, so, unfortunately, temporary ASIA credentials are what we have provisioned to use

**Comment by paolo573** [comment] 2021-07-01 21:17
> I am also unable to reproduce this issue on v5.0.2 of the CLI. It looks like you are using temporary credentials (`"accessKeyId":"ASIA***"`) - is there any chance those have expired?

No chance - this pipeline was working fine, even in a merge-to-master/deploy pipeline that ran 20 minutes before we started the upgrade branch

**Comment by cjihrig** [comment] 2021-07-07 19:43
@paolo573 I just wanted to update you. Once https://github.com/aws-amplify/amplify-cli/pull/7682 is merged and released, I propose doing the following so that you can upgrade your CLI version while still leveraging temporary credentials:

1. Create a profile in `~/.aws/config` and `~/.aws/credentials`. You can add your temporary `aws_access_key`, `aws_secret_access_key`, and `aws_session_token` here.
2. Update your headless script to: `"configLevel": "general"`, `"useProfile": true`, `"profileName": "yourProfileName"`. This will defer all use of credentials to the AWS SDK, with the profile you just created.

I'm sorry for any inconvenience this caused you.

**Comment by paolo573** [comment] 2021-07-08 14:02
@cjihrig thanks for this follow up!

**Closed** 2021-07-12 18:42 UTC
Labels: bug, headless, init
