### ISSUE TITLE
amplify env checkout never completes (spins forever)

### ISSUE THREAD

**Issue by ahtokca** [aws-amplify/amplify-cli#5825] opened 2020-11-10 08:48 UTC
**Describe the bug**
It looks like something happened to `env checkout` command. I can't checkout environment using any version after 4.28.2.
It just never completes and shows no errors. 

**Amplify CLI Version**
4.29.x, 4.30.x, 4.31.x

**To Reproduce**
when ever I run
```
amplify env checkout ${envName} --providers '{ "awscloudformation": {"configLevel": "project", "useProfile": true, "profileName": "${profileName}"} }'
```
it spins with "Initializing your environment: {...}" forever

**Expected behavior**
Environment get checked out

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v14.0.0

I'm using api, auth, function, storage
Previous issue got closed, I overlooked that sorry: https://github.com/aws-amplify/amplify-cli/issues/5695

Is there any thing I can do to troubleshoot the issue?

**Comment by jhockett** [comment] 2020-11-10 17:28
Closing as duplicate of #5695

**Closed by jhockett** 2020-11-10 17:28 UTC
