### ISSUE TITLE
Unauthorized while performing update mutation on model GraphQL Transformer V2

### ISSUE THREAD

**Issue by shriram192** [aws-amplify/amplify-cli#9883] opened 2022-03-01 16:23 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v17.5.0

### Amplify CLI Version

7.6.22

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Deleted a field from model and updated the GraphQL API Resource ( Appsync ).

### Amplify Categories

auth, api

### Amplify Commands

Not applicable

### Describe the bug

```graphql
type Farmer 
  @model  
  @auth(
    rules: [
      { allow: owner, operations: [create, update, read] },
      { allow: groups, groups: ["Admin"], operations: [read] }
    ])
  {
  identityId: String
  profileImg: String
  name: String!
  mobile: AWSPhone! @primaryKey 
  billing: Shipping
  shipping: [Shipping]
  email: String
  fb: String
  google:String
  cart: [CartItem]
  wishList: [String]
}
```

Issue faced - Unauthorized to run update mutation on the model after being authenticated
This issue is not only being faced with owner auth type but also with group auth type.
Our system is in production and we need immediate resolution for this. Please support as soon as possible.

### Expected behavior

Intended Auth Access - The owner should be able to create, read and update. Admin should. be able to read.

### Reproduction steps

1. Make change to GraphQL schema
2. Perform amplify push
3. Auth Error occurs

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Farmer 
  @model  
  @auth(
    rules: [
      { allow: owner, operations: [create, update, read] },
      { allow: groups, groups: ["Admin"], operations: [read] }
    ])
  {
  identityId: String
  profileImg: String
  name: String!
  mobile: AWSPhone! @primaryKey 
  billing: Shipping
  shipping: [Shipping]
  email: String
  fb: String
  google:String
  cart: [CartItem]
  wishList: [String]
}
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment] 2022-03-01 16:41
possibly related to https://github.com/aws-amplify/amplify-cli/issues/9870

**Comment by josefaidt** [comment] 2022-03-01 17:16
Hey @shriram192 :wave: thanks for raising this! Unfortunately I was not able to reproduce using the following schema:

```graphql
type Todo
  @model
  @auth(
    rules: [
      { allow: owner }
      { allow: groups, groups: ["admins"] }
    ]
  ) {
  id: ID! @primaryKey
  owner: ID
  name: String!
  description: String
}
```

with two users, `admin` and `user`, of which `admin` is a member of the `admins` group. Both `admin` and `user` are able to update records as intended. However, when explicitly granting `update` access the update mutations no longer work:

```graphql
type Todo
  @model
  @searchable
  @auth(
    rules: [
      { allow: owner, operations: [create, update, read] }
      { allow: groups, groups: ["admins"], operations: [read] }
    ]
  ) {
  id: ID! @primaryKey
  owner: ID
  name: String!
  description: String
}
```

It is important to note `create` and `read` are working as expected.

![image](https://user-images.githubusercontent.com/5033303/156216011-6de715e4-9728-4575-b95a-7c705e773180.png)


Marking as a bug 🙂

**Comment by shriram192** [comment] 2022-03-02 00:24
Hi @josefaidt please let us know the estimated time to fix the update mutation bug. 

This bug is killing our business at the moment and we need immediate resolution.

**Comment by shriram192** [comment] 2022-03-02 10:01
@lazpavel can you help us resolve this bug? it's already one day and our system is down. Need resolution ASAP.

**Comment by lazpavel** [comment] 2022-03-02 17:22
Hi @shriram192, we are currently working on a fix, as a workaround until this is released can you downgrade to CLI v7.6.21 or another possible workaround would be to apply the auth rules from the type level to each field

**Comment by shriram192** [comment] 2022-03-03 00:35
Hi @lazpavel downgrading to 7.6.21 does not fix the issue and we cannot apply field level authorisation on that particular model as we need subscriptions to work ( cannot go with off or public ).

**Comment by lazpavel** [comment] 2022-03-03 00:56
@shriram192 can you ensure that after downgrading the schema gets recompiled before `amplify push` by adding a space at the end of the schema file?

**Comment by shriram192** [comment] 2022-03-03 01:15
Hi @lazpavel this resolved our issue at the moment. Thanks for the resolution. Will wait for your indication to bump up the version to 7.6.22

**Comment by IsaacTrevino** [comment] 2022-03-03 23:18
+1
This is a serious problem, though downgrading and `amplify push` solved my issue.

**Comment by mrsimply** [comment] 2022-03-08 08:35
I want to add this also affects `update` operations from **groups**! Granting explicit `update` operations authorization will not work on groups. The generated VTL file is missing the part where `#set( $isAuthorized = true )` is executed.

**Comment by randeepbhatia** [comment] 2022-03-09 02:48
This issue is also happening on 7.3.5. A possible workaround did by changing auth type to APIKey and using that in the interim.

**Comment by josefaidt** [comment] 2022-03-09 13:57
Hey @mrsimply :wave: are you using group claims? What you're experiencing appears similar to the bug documented here https://github.com/aws-amplify/amplify-cli/issues/9370

**Comment by mrsimply** [comment] 2022-03-09 14:59
@josefaidt you are right 🥴 Now I'm facing two issues 😵‍💫

**Closed** 2022-03-14 22:00 UTC
Labels: bug, @auth, duplicate, p2

**Comment by shopizer-ecommerce** [comment] 2022-11-04 03:48
Still the same issue, tried amplify cli versions latest (~10) and 7.6.21 


GraphQL transformer version: 2

amplify-login % amplify --version
7.6.21

I understand that transformer v 2 is the root cause, which version of the cli should i use ?
Is the api key the only way to go ?

**Comment by IsaacTrevino** [comment] 2022-11-04 14:20
There was a change in how VTL files are generated. If a particular group does not have nullification or delete privileges, then they will not be able to perform a mutation. Check the `Mutation.updateXXXXXX.auth.1.res.vtl` file

```vtl
#set($staticGroupRoles=[
{"claim":"cognito:groups","entity":"admins","allowedFields":["id","name","truck","trips","notes","meta"],"nullAllowedFields":["id","name","truck","trips","notes","meta"],"isAuthorizedOnAllFields":true},
{"claim":"Cognito:groups","entity":"management","allowedFields":["id","name","truck","trips","notes","meta"],"nullAllowedFields":[],"isAuthorizedOnAllFields":false},
])
```

If you are trying to modify a field that is not in the `null allowed fields`, then you will return a `Error: User Not Authorized`.

I know this isn't ideal but hopefully a fix in the near future graphql transformer version, but in the mean time try adding delete permission to that group.

**Comment by BoostedPenguin** [comment] 2023-03-01 13:12
> There was a change in how VTL files are generated. If a particular group does not have nullification or delete privileges, then they will not be able to perform a mutation. Check the `Mutation.updateXXXXXX.auth.1.res.vtl` file
> 
> ```velocity
> #set($staticGroupRoles=[
> {"claim":"cognito:groups","entity":"admins","allowedFields":["id","name","truck","trips","notes","meta"],"nullAllowedFields":["id","name","truck","trips","notes","meta"],"isAuthorizedOnAllFields":true},
> {"claim":"Cognito:groups","entity":"management","allowedFields":["id","name","truck","trips","notes","meta"],"nullAllowedFields":[],"isAuthorizedOnAllFields":false},
> ])
> ```
> 
> If you are trying to modify a field that is not in the `null allowed fields`, then you will return a `Error: User Not Authorized`.
> 
> I know this isn't ideal but hopefully a fix in the near future graphql transformer version, but in the mean time try adding delete permission to that group.

This still seems to be an issue with transformer v2 running on amplify cli @8.0.2. Only fix was to add a delete permission for owners and groups.

Has this been fixed with latest amplify cli version?
