### ISSUE TITLE
S3 Bucket Dropped after new Environment Deployed

### ISSUE THREAD

**Issue by jnastaskin** [aws-amplify/amplify-cli#9293] opened 2021-12-10 23:38 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.5

### Amplify CLI Version

7.5.5

### What operating system are you using?

Mac

### Amplify Categories

storage

### Amplify Commands

env, pull, update

### Describe the bug

After creating/deploying a new UAT environment, an S3 storage bucket linked with dev environment is not found/linked.  Post/Get calls to it fail in DEV. However, the UAT bucket resource that got created during the creation of the new UAT env works fine in that env.

The bucket can be found in the codebase and in the backend-config .json file and the resource is found under _amplify/backend/storage_.  However, running amplify update storage produces 'No resources to update. You need to add a resource.'
![image](https://user-images.githubusercontent.com/31951390/145653772-27d216bd-74ee-4bc1-a133-165114e88636.png)

The same holds true After importing it through "amplify import storage".  After running this command however, the bucket now shows in the 'storage' section of amplify studio for this environment.

### Expected behavior

Bucket should remain linked to environment.

### Reproduction steps

1.  Amplify add storage -> create S3 bucket/resource 
2. Create new amplify env and deploy it
3. Check original environment where storage resource was created.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

I also notice that running 'amplify pull' brings an S3 bucket that was previously deleted and doesn't exist in my list of buckets in Amazon S3.

**Comment by jnastaskin** [comment] 2021-12-11 03:29
I'm also seeing S3 buckets in the codebase and AWS S3, but when I run amplify update storage or amplify remove storage it says " No resources added for this category"

**Comment by akshbhu** [comment] 2021-12-13 18:11
Hi @jnastaskin 

We are looking into this.

Can you also paste the output of ```amplify status```  will help in debugging the issue ?

**Comment by jnastaskin** [comment] 2021-12-13 18:19
hi @akshbhu 
here it is
![image](https://user-images.githubusercontent.com/31951390/145866589-6baab9c2-fa45-491f-b8a0-f56b64c2f8bc.png)

**Comment by jnastaskin** [comment] 2021-12-13 18:35
> akshbhu
At this point, I'm really just trying to resolve/figure out why the amplify cli thinks the storage resource doesn't exist even though it's in my codebase and shows up in  the list of buckets in AWS S3

**Comment by akshbhu** [comment] 2021-12-13 19:55
Hi @jnastaskin 

Can you mail us the amplify folder at amplify-cli@amazon.com with issue number as subject?

Make sure to redact any secret info present in the files before sending.

**Comment by jnastaskin** [comment] 2021-12-13 20:15
Hi @akshbhu,
Sure thing!  Sending over now, thank you!

**Comment by jnastaskin** [comment] 2021-12-16 17:20
hi @akshbhu , any updates on this? I haven't heard back yet from anywhere

**Comment by josefaidt** [comment] 2022-02-07 19:55
Hey @jnastaskin :wave: apologies for the delay on this one! Do you remember what steps were taken to reproduce this behavior? Following the posted reproduction steps I was not able to reproduce this issue.

1. create a new project with `amplify init -y`
2. add storage with `amplify add storage` > content > add auth
3. push with `amplify push -y`
4. create a new environment with `amplify env add`
5. push with `amplify push -y`
6. observe s3 bucket exists in the console for both environments
7. checkout previous environment with `amplify env checkout dev`
8. observe `amplify status` displays attached storage resource

**Comment by josefaidt** [comment] 2022-02-15 22:50
Hey @jnastaskin :wave: just wanted to follow-up on this one and see if you are able to identify any inconsistencies with the reproduction steps noted in the comment above versus the steps taken to reproduce this issue?

**Comment by jnastaskin** [comment] 2022-02-16 02:22
Hi @josefaidt , thanks for following up.  The only thing I can think of that differs in your reproduction steps is that we fully provisioned/deployed/built the backend after creating the new env.  I'm not sure if that has any differences than simply doing an amplify push as you have stated.

Perhaps my issue was caused by some other team member doing an amplify push that erased the storage resource in dev...as this issue was written a few months ago I can't remember exactly who was working on what, but do remember at one time that storage resources were getting deleted/overwritten when another team member was doing amplify pushes to a specific unrelated lambda function for some reason....but that's a story for another ticket I suppose.

Hope that info is helpful, I apologize for not being able to provide more.

**Comment by josefaidt** [comment] 2022-03-23 15:54
Hey @jnastaskin apologies for the delay here! Based on the provided update and my inability to reproduce the issue I'll close this for now, however if this issue reappears as you continue working with the project please reply back to this issue with the relevant context and we can re-open this issue to investigate further.

> but do remember at one time that storage resources were getting deleted/overwritten when another team member was doing amplify pushes to a specific unrelated lambda function for some reason

Also if there is any additional context you can provide for this workflow I am certainly willing to dive into this. In the mean time I will keep this in mind as I work through other issues and re-open this issue 🙂

**Closed by josefaidt** 2022-03-23 15:54 UTC
Labels: storage, pending-triage, not-reproducible
