### ISSUE TITLE
Breaking change on @connection directive when "fields" not specified

### ISSUE THREAD

**Issue by paulsson** [aws-amplify/amplify-cli#5015] opened 2020-08-05 04:00 UTC
I believe this is a bug with the version of amplify-cli that the Amplify Console is using for the build process that generates all of my AppSync GraphQL resolvers which is why I am opening this issue in the amplify-cli repo.

**Describe the bug**
Same code is working in production for weeks, but a new deployment using a newer version of the amplify-cli is broken.
The connection directive when used with no "fields" specified always produces Unauthorized error when the connection field is null. Everything including auth works as expected when the connection field is not null (the related database record exists).
The docs show this as the simplest way to use the connection directive in a "has-one" type relationship:
https://docs.amplify.aws/cli/graphql-transformer/directives#has-one

Let's say we have a simple issue tracker app as an example.
```
type Issue @model
  @auth(rules: [
    { allow: groups, groups: ["Admin"], operations: [create, read, update, delete] }
  ]) {
  id: ID!
  title: String!
  description: String!
  closedByUser: User @connection
}
type User @model
  @auth(rules: [
    { allow: groups, groups: ["Admin"], operations: [create, read, update, delete] }
  ]) {
  id: ID!
  username: [String!]!
}
```
The Issue type has an optional 'closedByUser' field because this field will be null until the Issue is closed. This 'closedByUser' field will result in a DynamoDB record with a column/field named 'issueClosedByUserId' when this connection field is set when the issues is closed. Until an issue is closed those DynamoDB records will not have a column/field named 'issueClosedByUserId' which indicates the connection does not exist.
I use Cognito user pool auth, but the auth rules above are simplified and the auth rules don't have anything to do with the behavior being seen.

Now let's say we have this query to 'GetIssue' using a cognito user in the "Admin" cognito group:
```
query GetIssue($id: ID!) {
  getIssue(id: $id) {
    id
    title
    description
    closedByUser {
      id
      username
    }
  }
}
```
Any Issue that does not have the 'closedByUser' connection yet will result in an error being returned in the GraphQL response, like:
```
{
  "data": {
    "getIssue": {
      "id": "",
      "title": "",
      "description": "",
      "closedByUser": null
    }
  },
  "errors": [
    {
      "path": [
        "getIssue",
        "closedByUser"
      ],
      "data": null,
      "errorType": "Unauthorized",
      "errorInfo": null,
      "locations": [
        {
          "line": 31,
          "column": 9,
          "sourceName": null
        }
      ],
      "message": "Not Authorized to access closedByUser on type Issue"
    }
  ]
}
```
This makes no sense because there is no 'closedByUser' record to authorize access to because the issue does not have that field/relationship set yet. It is null, there is nothing to run authorization on.

I have 2 different Amplify environments deployed using the same exact github branch (same code):
- the Amplify env that has been deployed longer (2020-07-17) and used an older amplify-cli version (v4.24.2) works
- the Amplify env that has been deployed most recent (2020-08-04) and used a new amplify-cli version (v4.26.0) is broken

I have dug through some of the recent code changes here in the amplify-cli repo and I am not sure but this recently merged PR may be the culprit although I don't know why it would cause an unauthorized error:
https://github.com/aws-amplify/amplify-cli/pull/4481/files

**Amplify CLI Version**
**WORKING** Amplify env uses amplify-cli **v4.24.2**
```
2020-07-17T18:26:49.699Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
2020-07-17T18:26:59.016Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 1.12.0 to 4.24.2...
2020-07-17T18:27:46.470Z [INFO]: # Done patching NPM package '@aws-amplify/cli'
```

**BROKEN** Amplify env uses amplify-cli **v4.26.0**
```
2020-08-04T16:00:56.779Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
2020-08-04T16:01:06.295Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 1.12.0 to 4.26.0...
2020-08-04T16:02:00.327Z [INFO]: # Done patching NPM package '@aws-amplify/cli'
```

**To Reproduce**
Deploy using schema above.

**Expected behavior**
Return the connection field as null (when no connection relationship is set yet) with no errors in the response.
This was the behavior for many months until recently. Broke between v4.24.2 and v4.26.0.

**Comment by akshbhu** [comment] 2020-08-05 17:22
Hi @paulsson 

I tried the steps of creating an issue without creating a connection with the given schema  and querying with the same query posted and I am not seeing any error in the response. 
```graphql
{
  "data": {
    "getIssue": {
      "title": "test1",
      "description": "test1",
      "closedByUser": null
    }
  }
}
```
This is my Query and Mutation:
```graphql
mutation MyMutation {
  createIssue(input: {title: "test1", description: "test1"}) {
    id
  }
}

query MyQuery {
  getIssue(id: "6e11a6cc-9b6b-4d65-b9e1-aa700c3a49e5") {
    title
    description
    closedByUser {
      id
      username
    }
  }
}
```

Do you made any changes in Schema between those versions or anything I am missing to repro this issue?

**Comment by paulsson-cs** [comment] 2020-08-06 14:05
@akshbhu thanks for looking into this.
Very strangely... I can't get this reproduced anymore.
In order to get all my environments working properly yesterday I set the Amplify console environment variable to use the last known working amplify-cli version 4.24.2:
```
_LIVE_UPDATES: [{"name":"Amplify CLI","pkg":"@aws-amplify/cli","type":"npm","version":"4.24.2"}]
```
This worked and I could see in the Amplify console "Build" -> "Clonging Repository" output:
```
2020-08-05T16:42:49.699Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: '4.24.2'
2020-08-05T16:42:59.016Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 1.12.0 to 4.24.2...
2020-08-05T16:43:46.470Z [INFO]: # Done patching NPM package '@aws-amplify/cli'
```
No errors were returned in my queries as I reported seeing when using "latest" v4.26.0.

After your reply reporting that you could not reproduce these errors I switched my dev Amplify env deployed by Amplify console back to using "latest" which deployed using v4.26.0 which was the amplify-cli version where I was seeing these errors introduced.
```
_LIVE_UPDATES: [{"name":"Amplify CLI","pkg":"@aws-amplify/cli","type":"npm","version":"latest"}]
```
Amplify console reported that it was deploying using v4.26.0:
```
2020-08-05T20:43:19.782Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
2020-08-05T20:43:28.952Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 1.12.0 to 4.26.0...
2020-08-05T20:44:18.101Z [INFO]: # Done patching NPM package '@aws-amplify/cli'
```

Nothing was changed in my code... yet these errors magically disappeared. Very strange!
Any ideas what could have happened? I will update if I find anything else out on my end or if this problem starts up again.

I can tell you that the generated resolver created on 2 different days is not the same (look at end of the below 2 resolver response mapping templates) even though they were both created by amplify-cli v4.26.0:

2020-08-04 v4.26.0:
```
## [Start] Determine request authentication mode **
#if( $util.isNullOrEmpty($authMode) && !$util.isNull($ctx.identity) && !$util.isNull($ctx.identity.sub) && !$util.isNull($ctx.identity.issuer) && !$util.isNull($ctx.identity.username) && !$util.isNull($ctx.identity.claims) && !$util.isNull($ctx.identity.sourceIp) && !$util.isNull($ctx.identity.defaultAuthStrategy) )
  #set( $authMode = "userPools" )
#end
## [End] Determine request authentication mode **
## [Start] Check authMode and execute owner/group checks **
#if( $authMode == "userPools" )
  ## [Start] Static Group Authorization Checks **
  #set($isStaticGroupAuthorized = $util.defaultIfNull(
            $isStaticGroupAuthorized, false))
  ## Authorization rule: { allow: groups, groups: ["Admin"], groupClaim: "cognito:groups" } **
  #set( $userGroups = $util.defaultIfNull($ctx.identity.claims.get("cognito:groups"), []) )
  #set( $allowedGroups = ["Admin"] )
  #foreach( $userGroup in $userGroups )
    #if( $allowedGroups.contains($userGroup) )
      #set( $isStaticGroupAuthorized = true )
      #break
    #end
  #end
  ## [End] Static Group Authorization Checks **


  ## [Start] Dynamic Group Authorization Checks **
  #set( $isDynamicGroupAuthorized = $util.defaultIfNull($isDynamicGroupAuthorized, false) )
  ## Authorization rule: { allow: groups, groupsField: "orgID", groupClaim: "cognito:groups" } **
  #set( $allowedGroups = $util.defaultIfNull($ctx.result.orgID, []) )
  #set( $userGroups = $util.defaultIfNull($ctx.identity.claims.get("cognito:groups"), []) )
  #foreach( $userGroup in $userGroups )
    #if( $util.isList($allowedGroups) )
      #if( $allowedGroups.contains($userGroup) )
        #set( $isDynamicGroupAuthorized = true )
      #end
    #end
    #if( $util.isString($allowedGroups) )
      #if( $allowedGroups == $userGroup )
        #set( $isDynamicGroupAuthorized = true )
      #end
    #end
  #end
  ## Authorization rule: { allow: groups, groupsField: "locationID", groupClaim: "cognito:groups" } **
  #set( $allowedGroups = $util.defaultIfNull($ctx.result.locationID, []) )
  #set( $userGroups = $util.defaultIfNull($ctx.identity.claims.get("cognito:groups"), []) )
  #foreach( $userGroup in $userGroups )
    #if( $util.isList($allowedGroups) )
      #if( $allowedGroups.contains($userGroup) )
        #set( $isDynamicGroupAuthorized = true )
      #end
    #end
    #if( $util.isString($allowedGroups) )
      #if( $allowedGroups == $userGroup )
        #set( $isDynamicGroupAuthorized = true )
      #end
    #end
  #end
  ## [End] Dynamic Group Authorization Checks **


  ## No Owner Authorization Rules **


  ## [Start] Throw if unauthorized **
  #if( !($isStaticGroupAuthorized == true || $isDynamicGroupAuthorized == true || $isOwnerAuthorized == true) )
    $util.unauthorized()
  #end
  ## [End] Throw if unauthorized **
#end
## [End] Check authMode and execute owner/group checks **

#if( $ctx.error )
$util.error($ctx.error.message, $ctx.error.type)
#else
$util.toJson($ctx.result)
#end
```

2020-08-05 v4.26.0 (after switching Amplify console config env var from "4.24.2" back to "latest"):
```
## [Start] Determine request authentication mode **
#if( $util.isNullOrEmpty($authMode) && !$util.isNull($ctx.identity) && !$util.isNull($ctx.identity.sub) && !$util.isNull($ctx.identity.issuer) && !$util.isNull($ctx.identity.username) && !$util.isNull($ctx.identity.claims) && !$util.isNull($ctx.identity.sourceIp) && !$util.isNull($ctx.identity.defaultAuthStrategy) )
  #set( $authMode = "userPools" )
#end
## [End] Determine request authentication mode **
## [Start] Check authMode and execute owner/group checks **
#if( $authMode == "userPools" )
  ## [Start] Static Group Authorization Checks **
  #set($isStaticGroupAuthorized = $util.defaultIfNull(
            $isStaticGroupAuthorized, false))
  ## Authorization rule: { allow: groups, groups: ["Admin"], groupClaim: "cognito:groups" } **
  #set( $userGroups = $util.defaultIfNull($ctx.identity.claims.get("cognito:groups"), []) )
  #set( $allowedGroups = ["Admin"] )
  #foreach( $userGroup in $userGroups )
    #if( $allowedGroups.contains($userGroup) )
      #set( $isStaticGroupAuthorized = true )
      #break
    #end
  #end
  ## [End] Static Group Authorization Checks **


  ## [Start] Dynamic Group Authorization Checks **
  #set( $isDynamicGroupAuthorized = $util.defaultIfNull($isDynamicGroupAuthorized, false) )
  ## Authorization rule: { allow: groups, groupsField: "orgID", groupClaim: "cognito:groups" } **
  #set( $allowedGroups = $util.defaultIfNull($ctx.result.orgID, []) )
  #set( $userGroups = $util.defaultIfNull($ctx.identity.claims.get("cognito:groups"), []) )
  #foreach( $userGroup in $userGroups )
    #if( $util.isList($allowedGroups) )
      #if( $allowedGroups.contains($userGroup) )
        #set( $isDynamicGroupAuthorized = true )
      #end
    #end
    #if( $util.isString($allowedGroups) )
      #if( $allowedGroups == $userGroup )
        #set( $isDynamicGroupAuthorized = true )
      #end
    #end
  #end
  ## Authorization rule: { allow: groups, groupsField: "locationID", groupClaim: "cognito:groups" } **
  #set( $allowedGroups = $util.defaultIfNull($ctx.result.locationID, []) )
  #set( $userGroups = $util.defaultIfNull($ctx.identity.claims.get("cognito:groups"), []) )
  #foreach( $userGroup in $userGroups )
    #if( $util.isList($allowedGroups) )
      #if( $allowedGroups.contains($userGroup) )
        #set( $isDynamicGroupAuthorized = true )
      #end
    #end
    #if( $util.isString($allowedGroups) )
      #if( $allowedGroups == $userGroup )
        #set( $isDynamicGroupAuthorized = true )
      #end
    #end
  #end
  ## [End] Dynamic Group Authorization Checks **


  ## No Owner Authorization Rules **


  ## [Start] Throw if unauthorized **
  #if( !($isStaticGroupAuthorized == true || $isDynamicGroupAuthorized == true || $isOwnerAuthorized == true) )
    $util.unauthorized()
  #end
  ## [End] Throw if unauthorized **
#end
## [End] Check authMode and execute owner/group checks **

$util.toJson($context.result)
```

**Comment by akshbhu** [comment] 2020-08-06 18:07
Hi @paulsson 

Glad to know that it is working for you now. It seems if you aren't facing this issue now , it can be an issue with service.

For now I am closing this issue, but feel free to comment if  the issue persists or you can also open the ticket with the service team.

**Closed by akshbhu** 2020-08-06 18:07 UTC
Labels: @connection, pending-response, pending-triage
