### ISSUE TITLE
error adding the datasource using Aurora

### ISSUE THREAD

**Issue by yahavb** [aws-amplify/amplify-cli#3536] opened 2020-02-28 07:23 UTC
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I am trying to config Appsync with Aurora per https://aws-amplify.github.io/docs/cli-toolchain/graphql#relational-databases 

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
amplify -v
4.13.4

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable
deploy Aurora per the guide (serverless in us-east-1)
`amplify init`
`amplify api add-graphql-datasource`

**Expected behavior**
Data source aurora added and run `amplify push`
Instead, I got
```
amplify api add-graphql-datasource
Using datasource: Aurora Serverless, provided by: awscloudformation
? Provide the region in which your cluster is located: us-east-1
? Select the Aurora Serverless cluster that will be used as the data source for your API: migrationdb
✔ Fetched Aurora Serverless cluster.
? Select the database to use as the datasource: palletdb
GraphQLError: Syntax Error: Unexpected <EOF>
    at syntaxError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/error/syntaxError.js:15:10)
    at Parser.unexpected (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:1463:41)
    at Parser.parseDefinition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:157:16)
    at Parser.many (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:1518:26)
    at Parser.parseDocument (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:111:25)
    at Object.parse (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:36:17)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/commands/api/add-graphql-datasource.js:111:46
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/index.js:176:3)
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:56:7)
There was an error adding the datasource
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: `Mac`
 - Node Version. You can use `node -v` to check the node version on your system
pallet]$node -v
v13.8.0

**Additional context**

**Comment by nikhname** [comment] 2020-02-28 18:41
@yahavb after init you need to run amplify add api before adding the RDS datasource. Please try adding the api first and trying again

**Comment by yahavb** [comment] 2020-02-28 19:08
@nikhname in our case, when we run `amplify init` we have a json file that includes all the components to add under `/amplify/backend` that includes (among other things)

```
    "api": {
        "AppSync": {
            "service": "AppSync",
            "providerPlugin": "awscloudformation",
            "output": {
                "authConfig": {
                    "additionalAuthenticationProviders": [],
                    "defaultAuthentication": {
                        "authenticationType": "AWS_IAM"
                    }
                }
            },
            "rdsInit": true
        }
    },
```

Moreover `amplify status` before I try to add the datasource:

```
Current Environment: ybmigratio

| Category  | Resource name           | Operation | Provider plugin   |
| --------- | ----------------------- | --------- | ----------------- |
| Auth      | Cognito                 | Create    | awscloudformation |
| Analytics | Pinpoint                | Create    | awscloudformation |
| Api       | AppSync                 | Create    | awscloudformation |
| Storage   | S3UserContent           | Create    | awscloudformation |
| Function  | LambdaCategory          | Create    | awscloudformation |
| Function  | LambdaProject           | Create    | awscloudformation |
| Function  | CognitoCustomMessage    | Create    | awscloudformation |
| Function  | CognitoPostConfirmation | Create    | awscloudformation |

```

I suspect add-graphql-datasource does not like the SQL schema when it compare it with the existing GQL schema listed in `/amplify/backend/api/AppSync/schema/*..graphql` 

It will be very helpful if the errors will be more descriptive.

**Comment by nikhname** [comment] 2020-02-28 19:37
Thanks for clarifying, this is a bug and a duplicate of https://github.com/aws-amplify/amplify-cli/issues/3082. We will also work on adding more descriptive error messages when addressing this.

**Closed by nikhname** 2020-02-28 19:37 UTC
Labels: graphql-transformer, pending-response

**Comment by yahavb** [comment] 2020-07-20 04:55
@nikhname any idea when we can use Aurora as documented instead of DynamoDB?
