### ISSUE TITLE
Dynamic Group Authorization with custom claim list of groups problem in GraphQL Transformer v2

### ISSUE THREAD

**Issue by alex-vladut** [aws-amplify/amplify-cli#9328] opened 2021-12-16 16:18 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v14.16.0

### Amplify CLI Version

7.6.3

### What operating system are you using?

MacOS

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

I created a simple multi-tenant application in which a user could be a member of multiple organisations, and this setup worked fine with the Graphql transformer v1. You can find the schema [here](https://github.com/alex-vladut/aws-amplify-auth/blob/main/amplify/backend/api/awsamplifyauth/schema.graphql). I used as well a Cognito pretoken generation trigger that will add a `tenants` custom claim. The authorization is set as follows:

```
  @auth(
    rules: [
      { allow: groups, groupsField: "organisationId", groupClaim: "tenants" }
    ]
  )
```

When I perform a query such as `listOrganisations` I get a DynamoDB error `message=Invalid KeyConditionExpression: Syntax error; token: \"$\", near: \"${\" (Service: DynamoDb, Status Code: 400, Request ID: UUUD253FQJ8GK4DJ4L7UHT7U3NVV4KQNSO5AEMVJF66Q9ASUAAJG, Extended Request ID: null), errorType=DynamoDB:DynamoDbException, data=null, errorInfo=null)"`. I turned on Appsync logs and the resolver seems to populate a context with this filter expression, which clearly doesn't look like a correct DynamoDB filter:

```
            "modelQueryExpression": {
                "expression": "${modelQueryExpression.expression} AND #id = :[\"73c5a663-7294-40b2-b587-0a0213c824c0\",\"a2ea560b-1ff7-4456-829f-d0053a944a9f\"]"
            },
```

Here is a dummy application I put together to reproduce this error: https://github.com/alex-vladut/aws-amplify-auth

### Expected behavior

To successfully apply the authorization check and return all the items the currently authenticated user is allowed to read.

### Reproduction steps

git clone git@github.com:alex-vladut/aws-amplify-auth.git
cd aws-amplify-auth.
npm install
amplify push
npm start
Check the browser's devtools and there should be an error like:
```
{"data":{"listOrganisations":null},"errors":[{"path":["listOrganisations"],"data":null,"errorType":"DynamoDB:DynamoDbException","errorInfo":null,"locations":[{"line":2,"column":3,"sourceName":null}],"message":"Invalid KeyConditionExpression: Syntax error; token: \"$\", near: \"${\" (Service: DynamoDb, Status Code: 400, Request ID: PB9DHULAIC2N4N2H0FONGPA93BVV4KQNSO5AEMVJF66Q9ASUAAJG, Extended Request ID: null)"}]}
```

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line

type User
  @model(queries: { get: "getUser" }, subscriptions: null)
  @auth(rules: [{ allow: owner, ownerField: "id" }]) {
  id: ID! @primaryKey
  email: AWSEmail!
  phone: AWSPhone
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}

type Organisation
  @model(subscriptions: null)
  @auth(
    rules: [
      { allow: owner, ownerField: "createdById", operations: [create] }
      {
        allow: groups
        groupsField: "id"
        groupClaim: "tenants"
        operations: [read, update]
      }
      { allow: private, operations: [delete] }
    ]
  ) {
  id: ID! @primaryKey
  name: String!
  createdById: ID
  createdBy: User @hasOne(fields: ["createdById"])
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}

type UserMembership
  @model(subscriptions: null)
  @auth(
    rules: [
      { allow: groups, groupsField: "organisationId", groupClaim: "tenants" }
      { allow: private, provider: iam }
    ]
  ) {
  id: ID! @primaryKey
  organisationId: ID!
  organisation: Organisation! @hasOne(fields: ["organisationId"])
  userId: ID!
    @index(
      name: "byUser"
      queryField: "userMembershipsByUser"
      sortKeyFields: ["organisationId"]
    )
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by lazpavel** [comment] 2021-12-16 16:44
Hi @alex-vladut, this is a duplicate of https://github.com/aws-amplify/amplify-cli/issues/9222, closing to this one in favor of the one mentioned above.

**Closed by lazpavel** 2021-12-16 16:44 UTC
