### ISSUE TITLE
ENOENT: no such file or directory, open '..\amplify\backend\api\XYZ\build\schema.graphql' An error occurred during the push operation: ENOENT: no such file or directory, open '....amplify\backend\api\XYZ\build\schema.graphql'

### ISSUE THREAD

**Issue by kannieWeesNie** [aws-amplify/amplify-cli#6376] opened 2021-01-13 14:04 UTC
hi
I have built a Vue app using Amplify DataStore. Everything worked then I shut the pc down and started the next morning. Suddenly it won't sync so I run _amplify codegen models_, update the API and run push but still no syncing so I remove the API, add it again and then I start getting **ENOENT: no such file or directory** error when I run push.

So I try and start from scratch and follow these steps:

1. npm install -g @aws-amplify/cli
2. amplify configure
3. npm install -g @vue/cli
4. npm install
5. amplify init
6. I am using my existing Vue app so don't install the Amplify libraries again
7. amplify add api
8. amplify push

It goes through the motions but ends up with:

> ENOENT: no such file or directory, open '...\amplify\backend\api\XYZ\build\schema.graphql'
An error occurred during the push operation: ENOENT: no such file or directory, open '....\amplify\backend\api\XYZ\build\schema.graphql'

where XYZ does not exist. I did, in the past have an api called XYZ but have deleted it ages ago so have no idea why it's looking for XYZ! 

Very confusing! 

Appreciate help overcoming this issue so I can get on with my work.

Thanks

**Comment by kannieWeesNie** [comment] 2021-01-13 14:40
UPDATE:

I created a completely new vue project, following the steps above. I also installed the amplify libraries. I then added the API category and used my schema. After running push I get the exact same error as mentioned above, also looking for the XYZ api!

I then replaced my schema with a simple Todo as per the docs. Again after amplify push, I get the exact same error, looking for the XYZ api!

**Comment by attilah** [comment] 2021-01-13 23:42
@kannieWeesNie what version of the Amplify CLI, Node, OS are you using?

Also is the `amplify api gql-compile` command executes without errors?

The file you see missing is being created during GraphQL compilation, like everything else in that `build` folder.

If you are doing and add api push, remove api, add api sequence, it is always a good think to push between the remove and the new add.

**Comment by egyangel** [comment] 2021-01-14 02:09
same error here where XYZ is the name of the last project i've worked on. 
I've pubblished  auth correctly with out errors but when i try to publish Api it throw the same error.

**Comment by kannieWeesNie** [comment] 2021-01-14 09:52
@attilah thanks for help. Amplify CLI version 4.41.2, node version 12.16.2, windows 10, amplify api gql-compile runs without error.

I don't think that the file is being created during graphql compilations. 

It seems like it is looking for the file....but what I would like to know is where does it get the filename from as it is a completely new Vue app that I am creating. The file in question is an old file from another project which was deleted a while back. There must be a some **config** file somewhere which contains this filename . the config file is then used with all my projects (it seems) and produces this error all the time. Perhaps when I deleted the project containing the file details, I aborted the delete and this information was never deleted, hence it is still referenced when building a new project. 

So the question is, where is this "**config**" file, how can I access it to delete it?

**Comment by attilah** [comment] 2021-01-14 23:53
ah so that referenced file is not within your current working directory? I assume you are using VS Code. For convenience we create a `settings.json` file on the `.vscode` folder to hide files and folder from the `amplify` directory that should not be edited manually, one of the hidden folders is the `.config` folder, which contains information about your local environment and maybe you have leftover files from there because of your copy. Since amplify projects storing local state that can cause problems when a project is copied around I'd suggest to use git for this since those files are ignored and you can clone an amplify project without problems and it will not contain any files that has local path information and such.

**Comment by egyangel** [comment] 2021-01-15 02:57
@attilah thanks for your answer but I can't find anyreference to the app name in the `.config` directory.

what i mean is in my amplify console I've these 2 apps:
1- bookingApp (the old one that I was working on)
2- tuapp (the new one that I'm working on) 


using the commands
 `amplify pull --appId xxxxxxxx  --envName xxxxxx` to set "Tuapp" 
 `amplify add api`
 amplify push 
 
 I get the error  ..\amplify\backend\api\**bookingapp**\build\schema.graphql'
where **Bookingapp** is the name of the old project. 
the correct file that should be looking for is  ..\amplify\backend\api\**tuapp**\build\schema.graphql'. 

Thanks in advance and sorry for my bad english.
ps. I've deleted te directory .idea and  got the same error.

**Comment by kannieWeesNie** [comment] 2021-01-15 07:39
@egyangel hi, i worked around my problem by adding the XYZ api to me new app (amplify add api and then give it the XYZ name) and then it worked. i suppose i could then run amplify remove api (select the XYZ api) to remove the api and then call amplify add api to add the new api (give the new api name)

however this does not solve the cause of the problem, which in my case was, i think, an aborted delete/removal of the api. as the delete was not completed, the info remains in the config file and is used whenever a new api is created. this should not happen.

**Comment by attilah** [comment] 2021-01-15 18:27
@kannieWeesNie yes, aborting an operation can leave the project in an undesired local state, with the problem gone, it is hard to reproduce it.

@egyangel are you pulling into an empty directory? Also which version of the CLI are you using? is gql-compile successfully completes for you?

You like to reuse the same backend for multiple frontends? Because sharing backends and doing push-pull between two Amplify applications is not a supported scenario, help to understand your use case.

**Comment by kannieWeesNie** [comment] 2021-01-16 10:28
@attilah thanks. Amplify should have some sort of check to confirm that after a delete/remove, everything is deleted on completion. If the delete/remove has not been completed but aborted/crashed before ending, surely there must be a way to determine what has been deleted and what remains, and possibly offer a rollback option?

as far as using the same backend?  i did not willingly do that. i created a new vue project using visual studio. as far as i knew, i was creating something from scratch without referencing the previous project settings. why/how does it select the previous project settings/configuration? is it when i select a user profile?

**Comment by attilah** [comment] 2021-02-01 20:19
No, amplify projects are not using any informationg shared based on the profile selected. 

Profile is used only to get credentials and region information that is configured locally on your machine.

Closing the issue as root cause for the original issue is not something we could fix and the follow-up questions were answered. If something new comes up feel free to open a new issue.

**Closed by attilah** 2021-02-01 20:19 UTC
Labels: api-graphql, pending-response, question
