### ISSUE TITLE
hostedUIProviderMetaData for SignInWithApple

### ISSUE THREAD

**Issue by kimfucious** [aws-amplify/amplify-cli#4352] opened 2020-05-21 17:53 UTC
**Which Category is your question related to?**
Auth

**Amplify CLI Version** 
4.19.0

**What AWS Services are you utilizing?**
API, Auth, Lambda, DynamoDB, S3

The following block of code is a snippet from `amplify/backend/auth/myproject12345eb4/paramaters.json`:

```json
  "authProvidersUserPool": ["Google"],
  "hostedUIProviderMeta": "[{\"ProviderName\":\"Google\",\"authorize_scopes\":\"openid email profile\",\"AttributeMapping\":{\"email\":\"email\",\"username\":\"sub\"}} ]",
  "oAuthMetadata": "{\"AllowedOAuthFlows\":[\"code\"],\"AllowedOAuthScopes\":[\"phone\",\"email\",\"openid\",\"profile\",\"aws.cognito.signin.user.admin\"],\"CallbackURLs\":[\"exp://exp.host/@kimfucious/myapp\",\"https://myapp.com/auth-callback\"],\"LogoutURLs\":[\"exp://exp.host/@kimfucious/myapp\",\"https://myapp.com\"]}"
```
I have both Google and SignInWithApple configured in the user pool so as to allow federated/social sign-in.

Google was done via `amplify add auth` and SignInWithApple was created manually, as amplify-cli doesn't support that yet.

The problem is that whenever I do an `amplify push`, SignInWithApple gets deselected in the **Enabled Identity Providers** section of **App client settings** in the user pool.

The **Identity providers** and **Attribute mapping** settings remain untouched (which is good).

I'd like to modify the `parameters.json` file so that the SignInWithApple does not get deselected with every push.

I've tried a few things, but I'm guessing without any docs, so my attempts have been flailing/failing.

Any advice as to how I might achieve this would be very appreciated 🌮 !

**Comment by attilah** [comment] 2020-05-21 22:17
@kimfucious did you try to add the Apple related settings to the `hostedUIProviderMeta` array? the resource processing lambda code creates the providers there, and perhaps the `amplify push` operation overwrite your settings, which is by design.

Can you tell me which exact Cognito property is getting overwritten by the `push` operation? That would help to find a workaround it if possible.

**Comment by kimfucious** [comment] 2020-05-21 22:33
Hi @attilah.  Thanks for the quick response.

I tried a few things including something like this...
```console
  "hostedUIProviderMeta": "[{\"ProviderName\":\"Google\",\"authorize_scopes\":\"openid email profile\",\"AttributeMapping\":{\"email\":\"email\",\"username\":\"sub\"}},{\"ProviderName\":\"SignInWithApple\",\"authorize_scopes\":\"openid email profile\",\"AttributeMapping\":{\"email\":\"email\",\"username\":\"sub\"}} ]",
```
...where I simply copied the `Google` entry and replaced the `ProviderName` with `SignInWithApple`.  I obviously don't actually know what to do here, hence my question.

I did get an error on `amplify push` (using the above and on other attempts) that referred to the lambda you mentioned, but I lost the trace as it when to Cloud Watch.  I'm guessing that error has to do with syntax or a bad property/value.

Unfortunately, I don't know the property value (in code), but the Sign In with Apple property that gets deselected is found in User Pool => App Integration => App client settings.   And it looks like this after a push:

![image](https://user-images.githubusercontent.com/26792769/82612388-f13b3d80-9bec-11ea-9881-dfe6522cd0c3.png)

The deselection occurs in both the `xxx_app_clientWeb` and `xxx_app_client` and need to get selected/saved again in order for users to sign in using Apple.

It would be awesome if I could find out what the right edits are in `parameters.json`, and I appreciate your help!

Kindly let me know if I can provide more info or try something new.

**Comment by kimfucious** [comment] 2020-05-21 22:39
One follow up to this is that some properties are **not** overwritten after a push.

As I mentioned prior, these are the Apple setup in User pool => Federation => Identity providers.
![image](https://user-images.githubusercontent.com/26792769/82612876-2bf1a580-9bee-11ea-92f6-8ea3d992dc4e.png)
This remains selected and the backing settings are left in place.

Also the mappings set in User pool => Federation => Attribute mapping are all left untouched after a push, even when they currently don't match what's in `parameters.json`

For example, the Google settings that I use (below) are more than whats in `parameters.json` and they are left alone:

![image](https://user-images.githubusercontent.com/26792769/82613039-94408700-9bee-11ea-8a42-e6fbd1037532.png)

**Comment by SwaySway** [comment] 2020-05-22 18:18
Hello @kimfucious 
Currently the CLI does not support adding Sign-In with Apple.
This is something we can look into as an enhancement for auth.

**Comment by kimfucious** [comment] 2020-05-22 18:34
Hi @SwaySway, thanks for the clarification.

My initial question was posed, knowing that amplify CLI does not support Sign in with Apple when using `amplify auth add`.  

My hope was to manually update the `parameters.json` file despite this limitation, so that the properties in the user pool do not get overwritten.

At present, every amplify push that involves an update to `auth` will deselect Sign in with Apple in the user pool, which is kind of a pain, because if/when you forget to turn it on, users can't sign in until you do.

If it's a total no-go for now, I get it; however, since Apple now requires the use of Sign in with Apple in many cases, bumping the priority on supporting it would be most likely very appreciated by many Amplify users.

**Comment by dseeker** [comment] 2020-06-24 13:38
Having to deploy multiple environments makes this feature very important. right now we have to manually add the credentials after a new environment is deployed. I understand there is an issue with the keys that makes it harder to solve in CLI, but we could at least be able to configure the parameter programmatically and just paste the key in the UI

**Comment by kimfucious** [comment] 2020-10-04 13:13
Just a note here to state that this problem still exists, and I have a follow-up question.

I've got an app setup with amplify federated Auth, and I've manually configured Sign in with Apple auth in Cognito.

As mentioned prior, this setup gets unchecked in the App Client Settings any time an `amplify push` is run on an environment where the auth has changed.

This essentially prevents the ability for users to sign in with Apple until the checkbox is re-ticked.

So eventhough Amplify might not support Sign in with Apple, Amazon Cognito surely does, and Amplify CLI is actually "breaks" the Cognito setup.

Question:  Wouldn't this be considered a bug, rather than an enhancement, or are you going with the fact that since Amplify CLI is oblivious to Sign In With Apple, it's acceptable to affect Cognito such that it breaks something that's currently functioning there?

**Comment by sregg** [comment] 2021-06-17 03:18
Any news on this?
I'm trying to push a lambda function change and it fails in my dev env but completes in prod.
The CloudWatch log shows this error:
```
{
    "Status": "FAILED",
    "Reason": "See the details in CloudWatch Log Stream: 2021/06/17/[$LATEST]843a87ea44d64eb09cfe9407553d8441",
    "PhysicalResourceId": "2021/06/17/[$LATEST]843a87ea44d64eb09cfe9407553d8441",
    "StackId": "arn:aws:cloudformation:us-east-1:209760867749:stack/amplify-localtennisapp-dev-173117-authlocaltennisapp879bce4a-90PRT9U8LTG2/efd8e0b0-d82c-11ea-8735-0a1f955da693",
    "RequestId": "06b80b4c-fa9f-4d1f-b96b-cb236a0afc2c",
    "LogicalResourceId": "HostedUIProvidersCustomResourceInputs",
    "NoEcho": false,
    "Data": {
        "err": {
            "message": "client_id, client_secret and authorize_scopes are all required idp details.",
            "code": "InvalidParameterException",
            "time": "2021-06-17T02:52:58.927Z",
            "requestId": "e639acde-fe64-4acc-81ee-48bac323d0d9",
            "statusCode": 400,
            "retryable": false,
            "retryDelay": 72.64154040268795
        }
    }
}
```

I didn't know what this had to do with my lambda change but it seemed to be related to social auth.
When I compared my dev and pro Cognito configs on the web, I saw that Sign in with Apple was gone in dev.
Is that the same issue people are experiencing here?
Did people see this `client_id, client_secret and authorize_scopes are all required idp details.` error as well?
I essentially can't push my dev env anymore at the moment :(

**Comment by sregg** [comment] 2021-06-20 14:44
I don't think that `HostedUIProvidersCustomResourceInputs` error was actually linked to SignInWithApple.
I ran `amplify auth update` and entered my Facebook and Google app ids and secrets and I was able to `amplify push` again.
But Sign in with Apple setup is definitely gone after pushing, so this issue is still valid.

**Comment by rajd90** [comment] 2022-02-20 16:38
I think i just had the same issue. I had an error related to `HostedUIProvidersCustomResourceInputs` after an amplify push (which failed). I then noticed that my Sign In With Apple configuration was gone (which had to be done manually). I'm not averse to setting up Sign in with Apple manually, but getting errors on subsequent pushes or losing the configuration of Sign in with Apple is unworkable. 

Either Sign In With Apple needs to be supported via the cli properly (so that it doesn't need to be configured manually in the console) OR we need to make sure it doesn't cause errors after the manual set up.

**Comment by josefaidt** [comment] 2023-02-28 21:32
Closing as this bug is no longer valid in recent versions of the CLI (latest is 10.8.0 at time of writing)

**Closed by josefaidt** 2023-02-28 21:32 UTC
Labels: bug, auth, p2
