### ISSUE TITLE
Push fails when attempting to "Set up OpenSearch for production environments"

### ISSUE THREAD

**Issue by lucasishuman** [aws-amplify/amplify-cli#9860] opened 2022-02-25 17:51 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v17.4.0

### Amplify CLI Version

7.6.22

### What operating system are you using?

Mac v12.2.1

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

I am using Amplify API (GraphQL).

I added @searchable to one of my model to enable OpenSearch.

I want to set up OpenSearch for my "prod" environment as described in the Amplify docs here
https://docs.amplify.aws/cli/graphql/search-and-result-aggregations/#set-up-opensearch-for-production-environments

The instructions in the docs produce an error when I try to push my changes to cloud.

### Expected behavior

I would like the docs to reflect the accurate information (or point to areas in the AWS console to find the correct values for my Amplify instance). I know there is a transition from "Elasticsearch" to "OpenSearch" occurring, but I'm not clear on what values to use currently as none of the combinations I've tried has worked (see Reproduction Steps).

### Reproduction steps

I copied the code directly from the docs into my `team-provider-info.json` file and update the API name.
https://docs.amplify.aws/cli/graphql/search-and-result-aggregations/#set-up-opensearch-for-production-environments

When I try to `amplify push --force` (Amplify doesn't recognize changes on its own so I use `--force`), I receive the following error:

```
UPDATE_FAILED   apimachineapi     AWS::CloudFormation::Stack Fri Feb 25 2022 09:21:59 GMT-0800 (Pacific Standard Time) Parameters: [OpenSearchInstanceType] do not exist in the template
```

I have tried different combinations or search instance type names:
* OpenSearchInstanceType
* ElasticSearchInstanceType
* ElasticsearchInstanceType

The error is the same for all - `[XxxxxxxxInstanceType] do not exist in the template`

I also tried using different type values:
* t2.small.elasticsearch
* t2.small.search

That didn't make a difference.

My Search dashboard says I am using
Engine: Elasticsearch
Version: 7.10
Instance type: t2.small.search

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line

type StrategySession @model @searchable {
  id: ID!
  name: String!
  userState: AWSJSON!
  type: String!
    @index(
      name: "strategySessionsByUpdatedDate"
      queryField: "listStrategySessionsByUpdatedDate"
      sortKeyFields: ["updatedAt"]
    )
  updatedAt: AWSDateTime!
}
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

![image](https://user-images.githubusercontent.com/1753761/155763001-505f14bf-be3b-42b0-b528-e95a04e7301b.png)

**Comment by lucasishuman** [comment] 2022-02-25 17:54
I think this is a duplicate of https://github.com/aws-amplify/amplify-cli/issues/9728 -- please close if appropriate

**Comment by sundersc** [comment] 2022-02-26 05:39
Closing this as duplicate of https://github.com/aws-amplify/amplify-cli/issues/9728.

**Closed by sundersc** 2022-02-26 05:39 UTC
