### ISSUE TITLE
--statement-typename-introspection=false doesnt work

### ISSUE THREAD

**Issue by mnai01** [aws-amplify/amplify-cli#14051] opened 2024-12-29 06:25 UTC
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v20.11.1

### Amplify CLI Version

1.4.5

### What operating system are you using?

Windows 10

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

This command `npx ampx generate graphql-client-code --out ./src/store/api/generated --format graphql-codegen --statement-typename-introspection=false` still generates the __typename value in my API.ts generated file

### Expected behavior

No __typename field should be present in the generated file

### Reproduction steps

1. Add this to your package.json script or run it in your cli  `npx ampx generate graphql-client-code --out ./src/store/api/generated --format graphql-codegen --statement-typename-introspection=false` 

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment] 2024-12-30 21:52
Closing this issue as this appears to be a duplicate of https://github.com/aws-amplify/amplify-codegen/issues/920

**Closed by ykethan** 2024-12-30 21:52 UTC
Labels: pending-triage, duplicate
