### ISSUE TITLE
amplify push produces "Cannot convert undefined or null to object"

### ISSUE THREAD

**Issue by a9udn9u** [aws-amplify/amplify-cli#7694] opened 2021-07-09 18:19 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.2.0

### Amplify CLI Version

5.1.0

### What operating system are you using?

macOS Big Sur

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

`amplify push` produces "Cannot convert undefined or null to object"

### Expected behavior

`amplify push` update my cloud resources

### Reproduction steps

1. Create some GraphQL schema with `amplify add api`
1. Create a custom function with `amplify add function`
   * Make this function depend on `api`, in my case, the function depends on the `GraphQLAPIIdOutput` attribute from `api` (yes I updated `backend-config.json` manually).
1. Delete an existing model in the GraphQL schema.
1. `amplify push`

The exception happens at [this line](https://github.com/aws-amplify/amplify-cli/blob/0c0adfb78350a192d4f44b722d6038b23c505527/packages/amplify-category-function/src/provider-utils/awscloudformation/utils/getDependentFunction.ts#L30) in `amplify-category-function`. For some reason the `function-parameters.json` generated for my function doesn't set the `permissions` property so `selectedCategories` is undefined, when amplify tries to get values from it a TypeError is thrown.

`function-parameters.json` is by default hidden in the vscode project so I never paid attention to it, pretty sure I never updated this file.

After change the function parameters file from `{}` to `{"permissions":{}}` the command succeeded. This bug can be fixed by replacing [this line](https://github.com/aws-amplify/amplify-cli/blob/0c0adfb78350a192d4f44b722d6038b23c505527/packages/amplify-category-function/src/provider-utils/awscloudformation/utils/getDependentFunction.ts#L27) from
```
const selectedCategories = currentParameters.permissions;
```
to
```
const selectedCategories = currentParameters.permissions || {};
```

### GraphQL schema(s)

See "Reproduction steps"

### Log output

See "Reproduction steps"

### Additional information

See "Reproduction steps"

**Comment by cjihrig** [comment] 2021-07-09 18:46
Thank you for reporting this, and the detailed explanation of the cause. I'm going to close this as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/7466. There is also a PR to address this at https://github.com/aws-amplify/amplify-cli/pull/7594.

**Closed by cjihrig** 2021-07-09 18:46 UTC
