### ISSUE TITLE
Geolocation not supported in DataStore

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-cli#3006] opened 2019-12-16 20:20 UTC
**Is your feature request related to a problem? Please describe.**

The AWS instructions for a geolocation solution do not support DataStore because the type Location does not (and should not) have an @model
(https://aws-amplify.github.io/docs/cli-toolchain/graphql?sdk=js#add-a-custom-geolocation-search-resolver-that-targets-an-elasticsearch-domain-created-by-searchable)

**Describe the solution you'd like**

A valid schema.graphql that compiles and deploys successfully in AppSync should compile successfully into models for DataStore

**Describe alternatives you've considered**

I'm not aware of any alternative solution

**Additional context**

There are quite a few people logging various flavours of this same issue, but as yet there is no response to it so somewhat in the dark on this issue. Obviously a critical issue to move past.

**Comment by Soek22** [comment] 2019-12-18 16:34
Related issues:
- https://github.com/aws-amplify/amplify-cli/issues/2988 Amplify codegen models on Datastore cannot generate Type with no @model directive
- https://github.com/aws-amplify/amplify-cli/issues/3026 API amplify codegen models

**Comment by yuth** [comment] 2019-12-18 18:46
Duplicate of #2988

**Closed by yuth** 2019-12-18 18:46 UTC
Labels: DataStore, enhancement
