### ISSUE TITLE
v4.41.2 | Owner field no longer available

### ISSUE THREAD

**Issue by Jordan-Eckowitz** [aws-amplify/amplify-cli#6473] opened 2021-01-25 00:03 UTC
**Describe the bug**
I upgraded the CLI from v4.16.1 to v4.41.2. When I upgraded, the `owner` field disappeared from the schema and available response parameters. 

I noticed that if I set the `auth` directive entirely to owner, i.e. `@auth(rules: [{ allow: owner }])`, then it still works. If its more restrictive, e.g. `@auth(rules: [{ allow: owner, operations: [create, update, delete] }])` then it is no longer available.

**Amplify CLI Version**
v4.41.2

**Comment by ammarkarachi** [comment] 2021-01-26 00:35
@Jordan-Eckowitz what's the error you get when you add operations?

**Comment by Jordan-Eckowitz** [comment] 2021-01-26 15:11
all of my queries that reference the `owner` field were throwing errors, saying something like the parameter doesn't exist

**Comment by ammarkarachi** [comment] 2021-01-26 17:48
@Jordan-Eckowitz Can you share your schema?

**Comment by Jordan-Eckowitz** [comment] 2021-01-26 19:24
@ammarkarachi its quite large and I'd like to keep it private - can you provide an email address (or any other means of private communication) where we can continue this discussion?

**Comment by ammarkarachi** [comment] 2021-01-26 19:28
Sure you can send it over to amplify-cli@amazon.com be sure to have the issue number in the email subject

**Comment by Jordan-Eckowitz** [comment] 2021-01-26 19:40
> Sure you can send it over to [amplify-cli@amazon.com](mailto:amplify-cli@amazon.com) be sure to have the issue number in the email subject

@ammarkarachi sent through an email now with zipped schema files. Email subject is `Issue #6473: v4.41.2 | Owner field no longer available`.

**Comment by ammarkarachi** [comment] 2021-01-26 19:48
@Jordan-Eckowitz Thanks! got it

**Comment by ammarkarachi** [comment] 2021-01-26 21:10
You would need to add the owner field in the query since there is no read operation specified it does not do it automatically. Something that alludes to the behavior can be found here https://docs.amplify.aws/cli/graphql-transformer/auth#authorizing-subscriptions

```
When @auth is used subscriptions have a few subtle behavior differences than queries and mutations based on their event based nature. When protecting a model using the owner auth strategy, each subscription request will require that the user is passed as an argument to the subscription request. If the user field is not passed, the subscription connection will fail. In the case where it is passed, the user will only get notified of updates to records for which they are the owner.
```

I will mark this as a documentation issue to follow up on.

**Comment by Jordan-Eckowitz** [comment] 2021-01-27 16:56
In `v4.16.1` - the version I am currently using, the owner field is automatically added to DynamoDB and added as an optional response parameter without any input required on my end. Its supposed to have an `owner` field added by default but in the new version it's not doing that. 

Here's a link to the Amplify docs (relevant screenshot below):https://docs.amplify.aws/cli/graphql-transformer/auth#owner-authorization

![image](https://user-images.githubusercontent.com/19767538/106025137-76d58e00-6096-11eb-90af-9a71c20b78da.png)

**Comment by Jordan-Eckowitz** [comment] 2021-01-29 20:02
Hi @ammarkarachi - just wanted to follow up and see if what I posted above is clear?

**Comment by jhockett** [comment] 2021-02-01 23:32
Hi @Jordan-Eckowitz, what you posted looks correct. We're investigating this.

**Comment by ammarkarachi** [comment] 2021-02-05 22:46
@Jordan-Eckowitz I am sorry it's not updated in the documentation but a way to possible solving the problem to modify the flag `addmissingownerfields` to true in the file `amplify/cli.json/`

**Comment by Jordan-Eckowitz** [comment] 2021-02-07 19:49
@ammarkarachi does it not make sense to just enable this by default? 

Otherwise everyone who has been using it in the same way I have is going to run into this problem.

**Comment by ammarkarachi** [comment] 2021-02-09 17:11
@Jordan-Eckowitz We will update the documentation to include more detail about for migration cases like yours

**Comment by Jordan-Eckowitz** [comment] 2021-02-10 17:03
Okay - still don't really understand why you don't just keep the existing approach and change the default so users won't have to debug this issue. But I guess its your decision to make.

**Comment by svr4** [comment] 2021-02-12 12:18
Hello, I'm facing a similar issue with amplify v4.41.1. I also used the same auth rules as @Jordan-Eckowitz. I also verified my `amplify/cli.json` and I already had the field `addmissingownerfields` set to `true`.

Has anyone had any luck fixing this issue or have any new suggestions?

**Comment by jehielmartinez** [comment] 2021-02-13 18:18
Facing the same problem all the owner fields disappear at codegen causing errors in the app. Using v4.43.0

**Comment by Jordan-Eckowitz** [comment] 2021-02-16 20:28
Hi @ammarkarachi, can we please get an update from your end. Just want to confirm somebody is addressing this issue...

**Comment by Jordan-Eckowitz** [comment] 2021-02-26 18:25
@jhockett do you have an update on this? Sorry if you're not the right person to ask - it seems nobody is tracking this issue anymore...

**Comment by ammarkarachi** [comment] 2021-02-26 22:12
> Okay - still don't really understand why you don't just keep the existing approach and change the default so users won't have to debug this issue. But I guess its your decision to make.

Hey @Jordan-Eckowitz apologize for the delay in getting back to you. This was done to enable owner auth submodels if there is no read operation specified it does not add it automatically

**Comment by ammarkarachi** [comment] 2021-02-26 22:13
> Hello, I'm facing a similar issue with amplify v4.41.1. I also used the same auth rules as @Jordan-Eckowitz. I also verified my `amplify/cli.json` and I already had the field `addmissingownerfields` set to `true`.
> 
> Has anyone had any luck fixing this issue or have any new suggestions?

Can you share your schema?

**Comment by josefaidt** [comment] 2022-02-24 19:28
Hey @svr4 :wave: apologies for the delay! This documentation has since been added to the feature flags section https://docs.amplify.aws/cli/reference/feature-flags/#addMissingOwnerFields

Are you still experiencing this issue?

**Comment by svr4** [comment] 2022-02-25 13:47
Hello @josefaidt :wave:, no worries. I was able to get the owner field to show up by adding `create` to the list of operations. Thanks for still replying tho :laughing:. Have a good one.

**Comment by josefaidt** [comment] 2022-02-25 14:46
Ah glad to hear it @svr4 , and again apologies for the delay! Closing issue

**Closed by josefaidt** 2022-02-25 14:46 UTC
Labels: documentation, pending-close-response-required, @auth, p2

**Comment by josefaidt** [comment] 2022-03-14 15:20
Hey @BernhardSmuts would you mind creating a new issue with those details? By doing so it will help us gather additional context for this occurrence to better identify the root cause https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml

**Comment by BernhardSmuts** [comment] 2022-03-14 15:47
Done. Please see issue:
#9976
