### ISSUE TITLE
Cannot add API permissions to new lambda function

### ISSUE THREAD

**Issue by kylekirkby** [aws-amplify/amplify-cli#6853] opened 2021-03-10 13:38 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.10.1

### Amplify CLI Version

4.45.0

### What operating system are you using?

Windows/Ubuntu (WLS2)

### Amplify Categories

api

### Amplify Commands

add, push

### Describe the bug

I can no longer add API permissions to a new lambda function. This was working before I "upgraded" to the latest Amplify CLI version... 

```
UPDATE_FAILED   functioncreateNewCompany AWS::CloudFormation::Stack Wed Mar 10 2021 13:33:54 GMT+0000 (Greenwich Mean Time) Output 'ApiId' not found in stack 'arn:aws:cloudformation:us-east-1xxxxxxxxxxx:stack/amplify-resourceshub-develop-xxxxxxx-apiAdminQueries-xxxxxxxxxxxxx/958aae00-6c96-11eb-b487-0e53bf60440d'
```

### Expected behavior

To be able to create a new lambda function with access to my GraphQL API.

### Reproduction steps

1. `amplify add function` and add permissions to access your API instance.
2. `amplify push` and see the stack fail to deploy since an ApiId does not exist. 

### Log output

```
# Put your logs below this line

```

**Comment by attilah** [comment] 2021-03-10 19:39
@kylekirkby could you please add more detailed repro steps to help to get to the bottom of this? What Amplify CLI version was used to create the API and Function? exact resources in project (that's appropriate for the repro), etc. Thanks!

**Comment by kylekirkby** [comment] 2021-03-11 08:52
@attilah - So you need an AdminQueriesAPI (which I believe was created through the auth category). 

I've also got a lambda function that I was trying to add `AdminQueriesAPI ` permissions to. 

When I said it was working, I thought it was the GraphQL API causing the issue (which I've added to functions previously), but it turns out that it was in fact the `AdminQueriesAPI` not exporting the correct Outputs. 

My resources were created with 4.44.x I believe.  I'm not certain about the exact version without digging through previous issues.

**Comment by attilah** [comment] 2021-03-11 21:47
@kylekirkby we would still need the repro steps to able to pin the root cause if you could try to provide those.

in your update failed line I saw `amplify-resourceshub-develop-xxxxxxx-apiAdminQueries-xxxxxxxxxxxxx`, so it is like your `functioncreateNewCompany` referenced somehow AdminQueries via granting permissions for that function. Is it a possible scenario?

**Comment by kylekirkby** [comment] 2021-03-11 21:54
@attilah I tried adding AdminQueriesAPI permissions to the `functioncreateNewCompany` function via `amplify update function` and selecting the API permissions through that menu in the CLI.

If you try adding an AdminQueriesAPI and then trying to grant permission to this API for a lambda function through `amplify update function`, that should do the trick.

**Comment by kylekirkby** [comment] 2021-03-11 21:55
I've moved away from this approach anyway, so doesn't block me but should still be looked at, I believe. I've added the `adminQueriesAPI` functions to a lambda layer so I'm running some Congito admin bits through that.

**Comment by attilah** [comment] 2021-03-11 22:02
@kylekirkby I am happy that you are unblocked, I was able to reproduce the same issue, so I'm marking it as a bug:

`CREATE_FAILED               functionadminqff5fda81    AWS::CloudFormation::Stack Thu Mar 11 2021 13:59:25 GMT-0800 (Pacific Standard Time) Output 'ApiId' not found in stack 'arn:aws:cloudformation:us-west-2:032500605820:stack/amplify-adminq-dev-135206-apiAdminQueries-1A210KE26G6P2/fcf54a30-82b4-11eb-9e22-0203778a50e1'`

Repro:
- amplify init
- add auth -> add AdminQueries
- add function
- update function, grant CRUD to API (AdminQueries)
- push

Output parameters needs to include the `ApiId` to support the CRUD scenario.

**Comment by kylekirkby** [comment] 2021-03-11 22:08
Thanks, @attilah! 🙏

**Comment by kaustavghosh06** [comment] 2021-03-24 01:47
The fix for this has been merged as a part of this PR - https://github.com/aws-amplify/amplify-cli/pull/6935 and would be part of our next release. Closing this issue.

**Closed by kaustavghosh06** 2021-03-24 01:47 UTC
Labels: api-rest, bug, functions
