### ISSUE TITLE
Can't create new env on existing amplify project.

### ISSUE THREAD

**Issue by stephen-optisol** [aws-amplify/amplify-cli#9302] opened 2021-12-13 14:38 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.17.6

### Amplify CLI Version

7.6.3

### What operating system are you using?

Ubuntu

### Amplify Categories

Not applicable

### Amplify Commands

codegen, env, push

### Describe the bug

I can't create new environment on my existing project. It is one year old project. From last week, i can't able to create new env and also, can't able to create custom subscriptions/queries for my amplify graphql queries. Whenever I try to create new environment and try to push the new env on cloud, i'm getting invalid aws cloudformation template error.

I followed the following steps
```
amplify env list
amplify env add ENVNAME
amplify push
```

```
Invalid CloudFormation template: project/amplify/backend/auth/admindee9a4dd/admindee9a4dd-cloudformation-template.yml
toGet.slice(...).join is not a function 
```

If I tries to push the changes on existing env, I didn't get the prompt to update the graphql folder.

### Expected behavior

It should allow me to create a new env and push it to the cloud.

### Reproduction steps

1. amplify init 
2. amplify push 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>
This is the log for newly created env.

```
# Put your logs below this line

? Are you sure you want to continue? Yes
Invalid CloudFormation template: /home/laptop-new-7/workspace/brandscape/brandscape-survey-admin-333/amplify/backend/auth/brandscapeadmindee9a4dd/brandscapeadmindee9a4dd-cloudformation-template.yml
toGet.slice(...).join is not a function

The following types do not have '@auth' enabled. Consider using @auth with @model
	 - Role
	 - User
	 - Project
	 - ProjectUser
	 - Survey
	 - ProjectUserAssignedGroup
	 - ProjectUserGroup
	 - UserAnswerType
	 - ClientComment
	 - UsersSurvey
	 - ClientsSurvey
	 - SurveyNotification
	 - Message
	 - MessageRecipient
	 - Notification
	 - NotificationRecipient
	 - ChatRecentHistory
	 - SurveyVariables
	 - UserVariables
	 - LinkSurveyVariables
	 - SurveyTracking
	 - SurveyUserTracking
Learn more about @auth here: https://docs.amplify.aws/cli-legacy/graphql-transformer/auth

GraphQL schema compiled successfully.

Edit your schema at /home/laptop-new-7/workspace/brandscape/brandscape-survey-admin-333/amplify/backend/api/brandscape/schema.graphql or place .graphql files in a directory at /home/laptop-new-7/workspace/brandscape/brandscape-survey-admin-333/amplify/backend/api/brandscape/schema
? Do you want to generate code for your newly created GraphQL API Yes
? Choose the code generation language target typescript
? Enter the file name pattern of graphql queries, mutations and subscriptions src/graphql/**/*.ts
? Do you want to generate/update all possible GraphQL operations - queries, mutations and subscriptions Yes
? Enter maximum statement depth [increase from default if your schema is deeply nested] 2
? Enter the file name for the generated code src/API.ts
⠼ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS amplify-brandscapeadmin-dev-newtest-175511                 AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:52 GMT+0530 (India Standard Time) User Initiated
CREATE_IN_PROGRESS functionmessageValidation                                  AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:57 GMT+0530 (India Standard Time)               
CREATE_IN_PROGRESS functionRepeatSurveyExecution                              AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:58 GMT+0530 (India Standard Time)               
CREATE_IN_PROGRESS functiondashboardScheduler                                 AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:58 GMT+0530 (India Standard Time)               
CREATE_IN_PROGRESS functionpushNotification                                   AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:58 GMT+0530 (India Standard Time)               
CREATE_IN_PROGRESS functiontriggerUserSurvey                                  AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:58 GMT+0530 (India Standard Time)               
CREATE_IN_PROGRESS functionbrandscapeadmindee9a4ddVerifyAuthChallengeResponse AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:58 GMT+0530 (India Standard Time)               
CREATE_IN_PROGRESS functionsmsNotificationCron                                AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:58 GMT+0530 (India Standard Time)               
CREATE_IN_PROGRESS functionbrandscapeadmindee9a4ddDefineAuthChallenge         AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:58 GMT+0530 (India Standard Time)               
CREATE_IN_PROGRESS functionsurveyValidation                                   AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:58 GMT+0530 (India Standard Time)               
CREATE_IN_PROGRESS functionBrandscapeValidations                              AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:58 GMT+0530 (India Standard Time)               
CREATE_IN_PROGRESS functionbrandscapeadmindee9a4ddCreateAuthChallenge         AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:58 GMT+0530 (India Standard Time)               
CREATE_IN_PROGRESS functionpushNotificationCron                               AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:58 GMT+0530 (India Standard Time)               
CREATE_IN_PROGRESS functiondeleteProjectUser                                  AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:58 GMT+0530 (India Standard Time)               
CREATE_IN_PROGRESS functionemailNotification                                  AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:58 GMT+0530 (India Standard Time)               
UPDATE_IN_PROGRESS UnauthRole                                                 AWS::IAM::Role             Mon Dec 13 2021 18:29:58 GMT+0530 (India Standard Time)               
CREATE_IN_PROGRESS functionrepetativeQuestionCron                             AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:58 GMT+0530 (India Standard Time)               
CREATE_IN_PROGRESS functionemailNotificationCron                              AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:58 GMT+0530 (India Standard Time)               
CREATE_IN_PROGRESS functionsmsNotification                                    AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:58 GMT+0530 (India Standard Time)               
UPDATE_IN_PROGRESS DeploymentBucket                                           AWS::S3::Bucket            Mon Dec 13 2021 18:29:58 GMT+0530 (India Standard Time)               
CREATE_IN_PROGRESS functionPreSignup                                          AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:58 GMT+0530 (India Standard Time)               
CREATE_IN_PROGRESS functionadminNotification                                  AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:58 GMT+0530 (India Standard Time)               
UPDATE_IN_PROGRESS AuthRole                                                   AWS::IAM::Role             Mon Dec 13 2021 18:29:58 GMT+0530 (India Standard Time)               
CREATE_IN_PROGRESS functiondynamoPagination                                   AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:58 GMT+0530 (India Standard Time)               
⠼ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS functionrefreshGlobalVariableCron                          AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:58 GMT+0530 (India Standard Time)                                                                                 
CREATE_IN_PROGRESS functioncognitoCustomMail                                  AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:58 GMT+0530 (India Standard Time)                                                                                 
CREATE_IN_PROGRESS functionS3Triggerb97e218e                                  AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:58 GMT+0530 (India Standard Time)                                                                                 
CREATE_IN_PROGRESS functionmessageNotificationCron                            AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:58 GMT+0530 (India Standard Time)                                                                                 
CREATE_FAILED      functiondashboardScheduler                                 AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Template error: Unable to get mapping for envMap::newtest::SurveyTracking       
CREATE_FAILED      functiontriggerUserSurvey                                  AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Template error: Unable to get mapping for envMap::newtest::apiVersion           
CREATE_FAILED      functionpushNotification                                   AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Template error: Unable to get mapping for envMap::newtest::apiVersion           
CREATE_FAILED      functionemailNotification                                  AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Template error: Unable to get mapping for envMap::newtest::apiVersion           
CREATE_IN_PROGRESS functionbrandscapeadmindee9a4ddVerifyAuthChallengeResponse AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Resource creation Initiated                                                     
CREATE_FAILED      functionBrandscapeValidations                              AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Template error: Unable to get mapping for envMap::newtest::apiVersion           
CREATE_FAILED      functiondynamoPagination                                   AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Template error: Unable to get mapping for envMap::newtest::apiVersion           
CREATE_FAILED      functionmessageValidation                                  AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Template error: Unable to get mapping for envMap::newtest::projectTable         
CREATE_FAILED      functioncognitoCustomMail                                  AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Template error: Unable to get mapping for envMap::newtest::sourceEmail          
CREATE_FAILED      functionrepetativeQuestionCron                             AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Template error: Unable to get mapping for envMap::newtest::apiVersion           
CREATE_IN_PROGRESS functionbrandscapeadmindee9a4ddDefineAuthChallenge         AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Resource creation Initiated                                                     
CREATE_FAILED      functionbrandscapeadmindee9a4ddCreateAuthChallenge         AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Template error: Unable to get mapping for envMap::newtest::sourceEmail          
CREATE_FAILED      functionsmsNotificationCron                                AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Template error: Unable to get mapping for envMap::newtest::apiVersion           
CREATE_FAILED      functionsmsNotification                                    AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Template error: Unable to get mapping for envMap::newtest::apiVersion           
CREATE_FAILED      functionpushNotificationCron                               AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Template error: Unable to get mapping for envMap::newtest::apiVersion           
CREATE_FAILED      functiondeleteProjectUser                                  AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Template error: Unable to get mapping for envMap::newtest::userPoolId           
CREATE_FAILED      functionemailNotificationCron                              AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Template error: Unable to get mapping for envMap::newtest::apiVersion           
CREATE_FAILED      functionRepeatSurveyExecution                              AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Template error: Unable to get mapping for envMap::newtest::apiVersion           
CREATE_FAILED      functionsurveyValidation                                   AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Template error: Unable to get mapping for envMap::newtest::apiVersion           
CREATE_FAILED      functionrefreshGlobalVariableCron                          AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Template error: Unable to get mapping for envMap::newtest::apiVersion           
CREATE_IN_PROGRESS functionPreSignup                                          AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Resource creation Initiated                                                     
CREATE_FAILED      functionbrandscapeadmindee9a4ddVerifyAuthChallengeResponse AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Resource creation cancelled                                                     
UPDATE_FAILED      DeploymentBucket                                           AWS::S3::Bucket            Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Resource update cancelled                                                       
UPDATE_FAILED      UnauthRole                                                 AWS::IAM::Role             Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Resource update cancelled                                                       
UPDATE_FAILED      AuthRole                                                   AWS::IAM::Role             Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Resource update cancelled                                                       
CREATE_FAILED      functionadminNotification                                  AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Template error: Unable to get mapping for envMap::newtest::apiVersion           
CREATE_FAILED      functionPreSignup                                          AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Resource creation cancelled                                                     
CREATE_FAILED      functionbrandscapeadmindee9a4ddDefineAuthChallenge         AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Resource creation cancelled                                                     
CREATE_FAILED      functionS3Triggerb97e218e                                  AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Template error: Unable to get mapping for envMap::newtest::userPoolId           
CREATE_FAILED      functionmessageNotificationCron                            AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) Template error: Unable to get mapping for envMap::newtest::MessageRecipientTable
⠧ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS amplify-brandscapeadmin-dev-newtest-175511-functionbrandscapeadmindee9a4ddDefineAuthCh-1A44S5CM353QJ AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) User Initiated
⠙ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS amplify-brandscapeadmin-dev-newtest-175511-functionbrandscapeadmindee9a4ddVerifyAuthCh-10WMF2ZSH6WVV AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) User Initiated


CREATE_IN_PROGRESS amplify-brandscapeadmin-dev-newtest-175511-functionPreSignup-J82DAWBZXOM8 AWS::CloudFormation::Stack Mon Dec 13 2021 18:29:59 GMT+0530 (India Standard Time) User Initiated
⠼ Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_IN_PROGRESS amplify-brandscapeadmin-dev-newtest-175511 AWS::CloudFormation::Stack Mon Dec 13 2021 18:30:03 GMT+0530 (India Standard Time) The following resource(s) failed to create: [functionrefreshGlobalVariableCron, functionmessageNotificationCron, functionbrandscapeadmindee9a4ddVerifyAuthChallengeResponse, functionmessageValidation, functionsmsNotification, functionPreSignup, functionBrandscapeValidations, functionbrandscapeadmindee9a4ddDefineAuthChallenge, functioncognitoCustomMail, functionsmsNotificationCron, functionbrandscapeadmindee9a4ddCreateAuthChallenge, functiondynamoPagination, functiondashboardScheduler, functionemailNotificationCron, functionpushNotification, functionsurveyValidation, functionemailNotification, functionS3Triggerb97e218e, functiondeleteProjectUser, functionrepetativeQuestionCron, functionadminNotification, functionRepeatSurveyExecution, functionpushNotificationCron, functiontriggerUserSurvey]. The following resource(s) failed to update: [AuthRole, DeploymentBucket, UnauthRole]. 
⠼ Updating resources in the cloud. This may take a few minutes...



```

</details>

**Comment by danielleadams** [comment] 2021-12-13 18:58
@stephen-optisol First, I'd like to focus on the CloudFormation issue. The validation of the CloudFormation files is not passing, which causes the deploy to fail too. However, I am unable to reproduce this with a previously created app + latest Amplify CLI, so this seems to be an issue with your app getting into a breaking state.

If you pull down your application code locally, do the `amplify/backend/auth/brandscapeadmindee9a4dd/brandscapeadmindee9a4dd-cloudformation-template.yml` files have any diffs?

**Comment by stephen-optisol** [comment] 2021-12-14 04:24
@danielleadams there is no change, while I run the amplify pull command. The env is created locally and I try to push it to the cloud, the changes are not pushed to the cloud because of the cloudformation env mapping error

**Comment by danielleadams** [comment] 2021-12-14 17:49
@stephen-optisol thanks. Would you mind sending your `amplify` directory  to amplify-cli@amazon.com so that we can help debug your issue?

**Comment by stephen-optisol** [comment] 2021-12-14 18:00
@danielleadams sure, i will share it. Thanks for your help.

**Comment by stephen-optisol** [comment] 2021-12-14 19:35
@danielleadams I have forwarded the amplify folder to the email.

**Comment by danielleadams** [comment] 2021-12-14 20:07
Hi @stephen-optisol - can you try sending it again? It has not worked the first time. Do you have a file sharing link that you can provide?

**Comment by stephen-optisol** [comment] 2021-12-15 02:11
> Hi @stephen-optisol - can you try sending it again? It has not worked the first time. Do you have a file sharing link that you can provide?

I have shared it again with file url.

**Comment by stephen-optisol** [comment] 2021-12-16 00:13
@danielleadams did you received the code

**Comment by danielleadams** [comment] 2021-12-16 01:25
@stephen-optisol Yep! Thanks for sending it over. We are looking at it and will keep you posted.

**Comment by stephen-optisol** [comment] 2021-12-16 18:03
Thanks for letting me know @danielleadams

**Comment by stephen-optisol** [comment] 2021-12-18 15:13
@danielleadams is there any solution for this issue

**Comment by danielleadams** [comment] 2021-12-21 21:31
@stephen-optisol I was able to reproduce with your code and I can see what the issue is, but I am not sure what the fix is yet.

**Comment by stephen-optisol** [comment] 2021-12-27 02:45
@danielleadams can you suggest any workaround for this issue.

**Comment by josefaidt** [comment] 2022-01-05 21:25
Hey @stephen-optisol :wave: I was also able to reproduce using your project's backend definition, and to mitigate the invalid CloudFormation template for auth we can use the latest CLI to update the resource with `amplify update auth`. This should then prompt us to migrate the auth resource, and upon selecting Y to migrate we can exit the process with ctrl+C.

For the functions' envMap issue, were these modifications manually applied? For example in one function's CloudFormation template we see something along the lines of (changed the email for demo purposes):

```json
"Mappings": {
    "envMap": {
      "dev": {
        "sourceEmail": "me@fake.com"
      },
      "devopstest": {
        "sourceEmail": "me@fake.com"
      }
    }
  },
```

Which will need to be manually updated to support the new environment name. For example if we were to add a new environment named `next`, we'll have to ensure these mappings are also updated with the new env name:

```json
"Mappings": {
    "envMap": {
      "dev": {
        "sourceEmail": "me@fake.com"
      },
      "devopstest": {
        "sourceEmail": "me@fake.com"
      },
      "next": {
        "sourceEmail": "me@fake.com"
      }
    }
  },
```

**Comment by stephen-optisol** [comment] 2022-01-06 05:53
@josefaidt I have cleared the cloudformation template error. The amplify push command is not creating the tables for new env. Without the tables, how can i create the dynamodb tables for newly created environment. The above solution will work for some of the functions. Can you give your suggestion.

**Comment by josefaidt** [comment] 2022-01-07 15:10
Hey @stephen-optisol are these the tables for your GraphQL API models? Are you seeing CloudFormation logs for the tables on push?

**Comment by stephen-optisol** [comment] 2022-01-07 17:26
@josefaidt, Will these mappings update automatically based on the dynamodb table creation? 

![Selection_2022010701](https://user-images.githubusercontent.com/50980397/148582356-a025e9df-ebf3-45cb-81ad-57ec72f6319a.png)

If yes, I don't see any table creation. These errors came whenever i ran amplify push command.

![Selection_2022010702](https://user-images.githubusercontent.com/50980397/148582658-0ca79c82-fe8c-4382-b281-39d257661075.png)

**Comment by josefaidt** [comment] 2022-01-07 19:37
Were those mappings added manually? I don't see `@function` in your schema file.

**Comment by cjihrig** [comment] 2022-02-01 19:09
Closing due to a lack of followup, but we can revisit this issue if needed.

**Closed by cjihrig** 2022-02-01 19:09 UTC
Labels: pending-response, pending-triage
