### ISSUE TITLE
Unable to remove layer

### ISSUE THREAD

**Issue by econtentmaps** [aws-amplify/amplify-cli#6020] opened 2020-12-01 10:32 UTC
**Describe the bug**
I am unable to remove a layer and/or the functions that use it (specifically, AdminQueries and another custom function). I have tried updating the functions that use it to unselect the layer, still not working. I got to this point because I wanted to add a Cognito group using the CLI's update auth feature, but it seems that, after adding a layer to the AdminQueries function, this isn't possible. 

**Amplify CLI Version**
4.37.0

**To Reproduce**
1. Setup amplify and create AdminQueries function/api.
2. Create layer.
3. Update AdminQueries function to use layer
4. Amplify push
5. Add group
6. Amplify push.

Fails, with this error:

```
Following resources failed
✖ An error occurred when pushing the resources to the cloud
Resource is not in the state stackUpdateComplete
An error occurred during the push operation: Resource is not in the state stackUpdateComplete
```

with the following error further up:

```
UPDATE_FAILED               apiskuupwebapp                 AWS::CloudFormation::Stack Tue Dec 01 2020 10:13:48 GMT+0000 (Greenwich Mean Time) Resource update cancelled                                                                                       
UPDATE_FAILED               authuserPoolGroups             AWS::CloudFormation::Stack Tue Dec 01 2020 10:13:48 GMT+0000 (Greenwich Mean Time) Resource update cancelled                                                                                       
UPDATE_FAILED               functionAdminQueries3da53a65   AWS::CloudFormation::Stack Tue Dec 01 2020 10:13:47 **GMT+0000 (Greenwich Mean Time) Parameters: [functionutilsArn] do not exist in the template**     
``` 

My layer is called 'utils', so I thought - aha... The layer is somehow causing the issue. So:

1. Update all functions to remove layer dependency using `amplify update function`
2. Amplify push
3. Amplify remove function and select layer:

This doesn't work and gives me the following error: 

```
Resource cannot be removed because it has a dependency on another resource
Dependency: Lambda:createOrganisation
Error: Resource cannot be removed because it has a dependency on another resource
    at /usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/remove-resource.js:128:31
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/remove-resource.js:124:40
    at Array.forEach (<anonymous>)
    at deleteResourceFiles (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/remove-resource.js:122:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/index.js:193:5)
    at async executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:153:5)
    at async Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:89:9)
An error occurred when removing the function resource
```

**Expected behavior**
I expect to be able to add a group and/or I expect the layer to be removed so that I can work around the first error.

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. 12.18.4

**Comment by jhockett** [comment] 2020-12-01 17:57
Closing this as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/5961.

**Closed by jhockett** 2020-12-01 17:57 UTC
