### ISSUE TITLE
Cloning an environment and fails to deploy via CI

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#9129] opened 2021-11-29 13:52 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### Amplify CLI Version

7.5.4

### What operating system are you using?

Windows

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

In an effort to get around I thought I'd start my environment all over again. I've found the clone button on an existing environment this time so tried using that and cloned my "dev" environment.

I connected my "staging" frontend setup in CI to use the new "staging" backend.

Then I triggered a new build by going to the frontend and clicking "redeploy this version".

The build fails saying:

"Error downloading #current-cloud-backend.zip from deployment bucket: amplify-franchisemanager-staging-130320-deployment, the error is: The specified key does not exist."

Not sure what to do about that one. Not much to be going on with to try to debug it.

### Expected behavior

The cloned environment knows who to set itself up and "just work" or the error at least gives me a pointer on how to go about solving it.

### Reproduction steps

Kind of covered these in the description, sorry.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by PeteDuncanson** [comment] 2021-11-29 14:10
Ok so. I thought I would try to do a `amplify push` locally to see if that would generate something. Trouble is I can't get it to run locally, I can't seem to get to the newly cloned environment. Clone button show here for clarity:

![image](https://user-images.githubusercontent.com/1674590/143882304-de7557cb-dbd1-4c9a-887d-037b04d85bd4.png)

If I run `amplify env list` it only shows the original 2 environments (live and dev) and not the new "staging" one.

So then I grabbed the command to pull it down directly from the backend in Amplify it jumps me to Admin UI to authenticate and choose an environment.

![image](https://user-images.githubusercontent.com/1674590/143882403-fed516ed-037a-412e-8b56-42194477af15.png)

Whatever I choose from the list just causes a reload and back to the same screen.

This whole thing is borked. Along with https://github.com/aws-amplify/amplify-cli/issues/9106 and https://github.com/aws-amplify/amplify-cli/issues/9113 I've not lost 2 full official work days and a lot of my weekend trying to get around these issues. AWS feels like a loaded cocked gun without a safety just waiting to blow my foot off :(

**Comment by Straubulous** [comment] 2021-11-29 21:23
@PeteDuncanson - We'd like to get on a call.  Can you send an email with your availability to: amplify-cli@amazon.com ?

**Comment by PeteDuncanson** [comment] 2021-11-29 21:29
Emailed :)

**Comment by sundersc** [comment] 2021-11-30 22:37
Hey @PeteDuncanson As discussed offline, it looks like it was caused by the invalid project state (because of manually deleted indexes - https://github.com/aws-amplify/amplify-cli/issues/9106). I'm closing this issue as we fixed the environment by manually solving the cloudformation drifts. Please feel free to reopen this one if required.

**Closed by sundersc** 2021-11-30 22:37 UTC
Labels: multienv, pending-triage
