### ISSUE TITLE
New Environment Hung after Creating API models...

### ISSUE THREAD

**Issue by julien-tamade** [aws-amplify/amplify-cli#5796] opened 2020-11-06 06:58 UTC
**Describe the bug**
I'm trying to create a new env based on my prod env. I'm on the prod env and then try to call amplify env add. I follow the configuration and checking status after see all of the resources listed with create next to them. I try to run amplify push and it gets pretty far but then hangs after Creating API models... and never finishes (i let it run all night). CloudFormation says it's deployed, and when I check in the amplify console, it lets my environment and says it's deployed but it also says "No enabled categories."

```

CREATE_COMPLETE CloudWatchEvent AWS::Events::Rule Thu Nov 05 2020 22:37:13 GMT-0800 (Pacific Standard Time) 
⠋ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS PermissionForEventsToInvokeLambda AWS::Lambda::Permission Thu Nov 05 2020 22:37:14 GMT-0800 (Pacific Standard Time) Resource creation Initiated
CREATE_IN_PROGRESS PermissionForEventsToInvokeLambda AWS::Lambda::Permission Thu Nov 05 2020 22:37:14 GMT-0800 (Pacific Standard Time)                            
⠙ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE PermissionForEventsToInvokeLambda AWS::Lambda::Permission Thu Nov 05 2020 22:37:24 GMT-0800 (Pacific Standard Time) 
⠙ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE amplify-tamadeintegrationtes-test-221134-functionStripeSubscriptionChecker-AILSEER9342S AWS::CloudFormation::Stack Thu Nov 05 2020 22:37:26 GMT-0800 (Pacific Standard Time) 
⠸ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE functionStripeSubscriptionChecker AWS::CloudFormation::Stack Thu Nov 05 2020 22:37:43 GMT-0800 (Pacific Standard Time) 
⠼ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE                     amplify-tamadeintegrationtes-test-221134 AWS::CloudFormation::Stack Thu Nov 05 2020 22:37:46 GMT-0800 (Pacific Standard Time) 
UPDATE_COMPLETE_CLEANUP_IN_PROGRESS amplify-tamadeintegrationtes-test-221134 AWS::CloudFormation::Stack Thu Nov 05 2020 22:37:45 GMT-0800 (Pacific Standard Time) 
⠧ Updating resources in the cloud. This may take a few minutes...
Creating API models...
⠸ Updating resources in the cloud. This may take a few minutes...
```

**Amplify CLI Version**
4.29.3

**To Reproduce**
Not sure how to reliably reproduce in a new project, but for me if I create a new environment and try to push I run into this issue.

**Expected behavior**
I would expect the push process not to get hung up on this step.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. 12.16.1

**Additional context**

**Comment by akshbhu** [comment] 2020-11-06 17:15
Hi @julien-tamade 

Not sure if it helps , but Can you try with the latest amplify version 4.32.0?

It seems your schema contains many models , that can be one reason it's taking too much time. Also Can you tell me what categories you added and how many models your schema so that I can try to reproduce on my end?

Let me know if latest version works for you.

**Comment by julien-tamade** [comment] 2020-11-06 17:18
@akshbhu Thanks for your response. I've waited on upgrading because Subscription is reserved as a type name in the newer versions and It won't let me push my API because i have a model named Subscription. I know there was a plan to release a version this week that temporarily resolve that error. Do you know if it has been released yet?

**Comment by akshbhu** [comment] 2020-11-06 17:26
Hi @julien-tamade 

Thanks for quick response. I will check with team and let you know. 
Also can you also give a brief detail about your project so that I can try to reproduce this error?

**Comment by julien-tamade** [comment] 2020-11-06 17:32
Yeah, I'm using auth, api (both api gateway and appsync), function, Analytics, Notifications, storage (s3 and dynamodb). My lambdas are a combo of cognito triggers, custom mutations for appsync, api-gateway endpoints, and dynamodb table triggers. for Auth, I've enabled both email and preferred_username as alias attributes. 

One other thing I noticed, and I'm not sure if this is related, is when I switch back to my prod environment and check status, I see an entry for Category: Providers, Resource name: categories, Operations: Delete. I'm not sure if this is related but also doesn't seem like it should be happening

**Comment by julien-tamade** [comment] 2020-11-06 21:25
@akshbhu would you be able to tell me which version reserved Subscription as a type name and I can try updating to that version? Thanks

**Comment by akshbhu** [comment] 2020-11-08 19:48
Hi @julien-tamade 

Sorry for the delay. We have merged the PR for this change behind a feature flag :https://github.com/aws-amplify/amplify-cli/pull/5745. This is merged in the latest amplify release.

**Comment by julien-tamade** [comment] 2020-11-08 19:52
Thank you @akshbhu! I will try it now. Also I'm not sure if my Category: Providers, Resource name: categories, Operations: Delete is related, but it seems even if I checkout my environment in an empty folder I get this in this issue when checking status. I mentioned it in #5340

**Comment by julien-tamade** [comment] 2020-11-09 06:22
@akshbhu the update seemed to work. Thanks!

**Comment by akshbhu** [comment] 2020-11-09 17:02
@julien-tamade 

Nice to know it worked!!!. For the above issue #5340 , you can comment on the above with the problems and repro steps if possible. 
Closing this issue for now as seems to be solved. If it occurs again feel free to comment and Ill reopen this again.

**Closed by akshbhu** 2020-11-09 17:02 UTC
Labels: api-graphql, pending-response, pending-triage
