### ISSUE TITLE
Amplify CLI should support Secrets Manager Configuration

### ISSUE THREAD

**Issue by ryanhollander** [aws-amplify/amplify-cli#5627] opened 2020-10-19 14:06 UTC
**Is your feature request related to a problem? Please describe.**
It would be nice if we could configure and manage secrets from the Amplify CLI and add them into our lambda functions and pipeline them in graphql/appsync.

**Describe the solution you'd like**
A cli feature to add and manage secrets at the command line. A feature to manage permission to secrets for functions and graphql pipelines (as an appsync function?). Some example code for using this in a function.

**Describe alternatives you've considered**
We do this manually with manual cloudformation.

**Additional context**
A good CLI implementation would be really handy and promote better security practices with Amplify.

Thank you!

**Comment by kaustavghosh06** [comment] 2020-10-24 21:34
@ryanhollander That's a good suggestion. How do you'll use it currently in CloudFormation to pass it to the AppSync resolvers?

**Comment by ryanhollander** [comment] 2020-10-27 13:34
@kaustavghosh06 - I don't currently use this in AppSync, only inside lambda functions. As I was writing this it just occurred to me that it might be useful to support AppSync also. As I think it through I'm not sure of what a valid use case might be inside AppSync. At first I though it might be useful in a pipeline function but now I'm actually thinking about it and I think anything you'd want a secret for should be processed within a lambda function anyway or can be solved using a lambda. Please scrap that idea, it's silly.

**Comment by wethanet** [comment] 2021-02-03 22:26
Access to and configuration of secrets manager from amplify would be a great help

**Comment by gruckion** [comment] 2021-02-08 16:17
I also need this. Will try to remember to come back here and document my solution

**Comment by gruckion** [comment] 2021-02-08 16:18
Containers are now supported with Amplify and they work with secrets manager.

https://docs.amplify.aws/cli/usage/containers

**Comment by CharlieDigital** [comment] 2021-02-17 05:25
@ryanhollander @gruckion I fought this battle today (spent all day getting this to work).

https://charliedigital.com/2021/02/16/aws-appsync-pipeline-resolver-templates-secrets-manager-and-external-http-apis/

My conclusion? It really needs to be way easier and far more streamlined.  My thought is that by making it so inaccessible, it makes it more likely for developers to fall into bad habits and put secrets into code.  Access to Secrets Manager should really be transparent if not somehow configured by default to encourage developers to follow best practices from the start.

**Comment by ryanhollander** [comment] 2021-02-17 14:00
@CharlieDigital @kaustavghosh06 @gruckion Ok so there's a use case for using it an AppSync pipeline after all. 

"I want to call an external REST API using an AppSync HTTP resolver which allows me to call the REST endpoint without writing a Lambda"

@CharlieDigital Interesting article, very informative! Thanks for sharing.

I'm wondering if there are any practical advantages over putting it all in a lambda. You could do all the work in the lambda and call the lambda from an AppSync resolver. The only reason I can think to do it this way is it *might* be slightly faster, but it *might* not.

**Comment by CharlieDigital** [comment] 2021-02-17 14:37
@ryanhollander I have been mulling it over myself and I'd say that:

- Cost is probably a factor in the long (long) run.  AppSync is "$4.00 per million Query and Data Modification Operations" compared to $0.20/million for Lamba but there's no time component to AppSync's cost whereas a Lambda reaching out to an external REST API incurs a time cost component.  The timeout seems to be 30 seconds, which is plenty long enough for any reasonable HTTP request.  Keep in mind that using Lambdas with AppSync means the Lambda cost is additive on top of the AppSync query cost.
- Less repetitive code.  You can "stack" resolvers into different pipelines.  Though you could argue that you're trading off more repetitive configuration and you could potentially put some of the common logic into Lambda layers.
- Once you have 3 of the 6 CloudFormation resources required for Secrets Manager provisioned, each additional operation only requires adding 3 more CF resources (copy paste) and 4 simple VTL files
- Performance.  As you pointed out, it might or might not be faster; can't really tell without more testing.  My intuition is that it will be faster for small workloads whereas a Lambda might perform better for more memory intensive workloads (since you have the option of increasing memory for Lambda and it's not clear if there is a memory ceiling for the resolver; [there are quotas on the template sizes and what not, but no documentation on memory ceiling for functions](https://docs.aws.amazon.com/general/latest/gr/appsync.html))

On the downside:

- Working with VTL is kind of unappetizing, especially if you need to do more complex logic
- Don't have access to richness of Lambda (e.g. importing packages)
- Perhaps a bit less accessible for folks who are not familiar with CloudFormation and VTL (okay, a lot less accessible)

I'm undecided on whether this is worthwhile or not.  In this case, I need to "proxy" a set of external REST API operations behind the AppSync facade.  I could also do this behind one single Lambda which simply takes a generic JSON string parameter that gets parsed in Lambda to decide which call to make.  So on the schema, there's only one GQL operation and then multiplex at Lambda by encoding the actual API operation.

But in any case, I hope this helps someone out there and saves them some time :D

**Comment by ryanhollander** [comment] 2021-02-17 14:48
@CharlieDigital Thanks for humoring me. The cost factor is interesting. My guess is that the performance difference is negligible for most workloads. Of course, you can use lambda's as pipeline functions too, which means you could setup 1 lambda for secrets manager calls and run all calls through that just by passing a key. Much less developer overhead there. Writing lambda's is much easier, less error prone, easier to debug, easier to reason about than VTL, I agree there. Also, fewer limitations and hoop jumping than VTL; VTL is also hard to read.

Powerful stuff, thanks again for sharing.

**Comment by CharlieDigital** [comment] 2021-02-17 15:07
You have me questioning my sanity after spending all day on this.

**Comment by ryanhollander** [comment] 2021-02-17 15:14
Please don't. It is an interesting exercise and we both learned something!

**Comment by armenr** [comment] 2021-04-16 21:41
I'm running into something that's related. I am working through a typical/vanilla workflow:

```
╰─ amplify add video
? Please select from one of the below mentioned services: Video-On-Demand
? Provide a friendly name for your resource to be used as a label for this category in the project: ondemandstreams
? Select a system-provided encoding template, specify an already-created template name:  Default HLS Adaptive Bitrate
? Is this a production enviroment? Yes
? Do you want to protect your content with signed urls? Yes
User: arn:aws:sts::<REDACTED_ACCOUNT_NUMBER>:assumed-role/us-west-2_0dnmPmHoR_Full-access/amplifyadmin is not authorized to perform: secretsmanager:CreateSecret on resource: ondemandstreams-cristina-pem-l9lqgyyj
AccessDeniedException: User: arn:aws:sts::<REDACTED_ACCOUNT_NUMBER>:assumed-role/us-west-2_0dnmPmHoR_Full-access/amplifyadmin is not authorized to perform: secretsmanager:CreateSecret on resource: ondemandstreams-cristina-pem-l9lqgyyj

```

The amplify app in this account (staging) was created/provisioned through a deployment pipeline + CDK from a different account (we call that account "cicd") that I have within my AWS Organization.

How do I solve this programmatically without manually attaching a policy via the IAM console in this account (staging)? I will need to reproduce this configuration many times (let's pretend there will be many instances of this Amplify app being created over time).

**Comment by renebrandel** [comment] 2021-07-06 23:06
Hi folks - we've recently launched secrets support for functions using a SecureString o Parameter Store (to reduce cost for customers) LMK if this resolves this issue.  https://twitter.com/renebrandel/status/1410657171809837059

**Comment by ryanhollander** [comment] 2021-07-06 23:37
@renebrandel I saw this on Twitter, and I'm actually going to use this on a project very soon and will report back with some feedback. At first blush it meets the use case I was interested in when I opened this. Thanks!

**Comment by renebrandel** [comment] 2021-07-23 22:46
Hi @ryanhollander - just checking in if this resolved your issue. I'll close this item for now. Please @-mention me if you believe it doesn't fully complete your use case.

**Closed by renebrandel** 2021-07-23 22:46 UTC
Labels: feature-request, platform
