### ISSUE TITLE
Generate incorrect `DeleteXXInput` type

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#7236] opened 2021-05-03 05:24 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### Amplify CLI Version

4.50.0

### What operating system are you using?

MacOS

### Amplify Categories

api

### Amplify Commands

codegen

### Describe the bug

This schema:
```gql
type Like @model @searchable
@key(fields: ["owner","objectId"])
@auth(rules: [
    { allow: owner }
    { allow: public, operations: [read], provider: apiKey }
])
{
    objectId: ID!
    type: ObjectType!
    owner: String!
}
```

got this ts type:
```ts
export type DeleteLikeInput = {
  id?: string | null,
};
```

where it should be:
```ts
export type DeleteLikeInput = {
    objectId: ID!
    owner: String!
};
```

I could confirm the correct generated type before version 4.50.0.
Now, every model gets this type even if the model doesn't have a `id` field at all.

```ts
export type Delete<ModelName>Input = {
  id?: string | null,
};
```

**Comment by attilah** [comment] 2021-05-03 18:52
@yaquawa This is a duplicate of #7168 and a PR has been merged for it a will be in the next release. Test with the next release of the CLI and if the issue still persist please comment on the original issue.

**Closed by attilah** 2021-05-03 18:52 UTC
Labels: @key, bug, duplicate, graphql-transformer
