### ISSUE TITLE
Adding Admin Queries to Project Only Works if Groups Exist

### ISSUE THREAD

**Issue by TKMApp** [aws-amplify/amplify-cli#7399] opened 2021-05-25 13:55 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.3.0

### Amplify CLI Version

4.51.2

### What operating system are you using?

MacOS - 11.3.1

### Amplify Categories

auth

### Amplify Commands

update

### Describe the bug

If you do not select a group to restrict access to when adding Admin queries API to your project, it will not add the necessary code to your project. If you create groups in Cognito and then restrict access to one of them, it will add the necessary code to your project.

### Expected behavior

If you do not have groups setup in your Cognito or do not want to restrict the Admin queries API at all, you should still be able to add the Admin queries API to your project, and have it unrestricted.

### Reproduction steps

1. From command line type `amplify update auth`
2. Select "Create or update Admin queries API'
3. When it asks 'Do you want to restrict access to the admin queries API to a specific group?" press `n`
4. It says it `Successfully updated auth resource XXX locally`
5. It DOES NOT add the resource to the project at ./Amplify/function/XXX

If you select yes in the step above and select a group, it will add the correct resources locally. I had to create groups just to get the code added to my project. Thank you!

**Comment by josefaidt** [comment] 2021-06-02 16:13
Hey @TKMApp :wave: thanks for opening this. I have been able to reproduce and also noticed if we restrict to a certain group (which will add the resources) then step back through `amplify update auth` to _remove_ the restriction we receive the `Successfully updated auth resource XXX locally` message without the appropriate changes. Marking this as a bug

**Comment by yuth** [comment] 2021-07-02 21:51
This is by design. If the admin query is not restricted with a group and anyone can access the APIs  it goes against the best practice.

**Closed** 2021-07-02 21:51 UTC
Labels: auth, wontfix
