### ISSUE TITLE
ENOENT: no such file or directory, stat .../#current-cloud-backend/<lambda-layer-path>/.../node_gyp_bins/python3

### ISSUE THREAD

**Issue by olehrdk** [aws-amplify/amplify-cli#13762] opened 2024-05-03 12:37 UTC
### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v18.10.0

### Amplify CLI Version

12.11.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

As a workaround made changes described [here](https://gist.github.com/josefaidt/a117076b7bea81e1872e275176dbb23c).
Workaround works but it is annoying to do it every time you push

### Describe the bug

After running `amplify env checkout <env_name>` or `amplify push` I receive an error `Could not initialize platform for <env>: ENOENT: no such file or directory, stat '.../amplify/.temp/#current-cloud-backend/function/<lambda-layer-name>/lib/nodejs/node_modules/bigint-buffer/build/node_gyp_bins/python3' `

### Expected behavior

Expected behavior is to have working checkout and push without doing workaround mentioned above

### Reproduction steps

1. Create lambda layer
2. After adding dependency which contains bigint-buffer dependency - deployment stoped working (@solana/web3.js & @coral-xyz/anchor)
3. `amplify env checkout <env_name>`

### Project Identifier

Project Identifier: 3bc790f8c3b45bfb3ee61223c142b17d

### Log output

<details>

```
# Put your logs below this line
2024-05-03T12:03:13.020Z|info : amplify env core checkout dev 
2024-05-03T12:03:19.360Z|info : amplify-provider-awscloudformation.zip-util.downloadZip.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip"},null])
2024-05-03T12:03:19.367Z|info : amplify-provider-awscloudformation.aws-s3.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]ify-[***]thdapp-[***]ev-[***]444-[***]ment"}])
2024-05-03T12:05:36.724Z|error : Could not initialize platform for 'dev': ENOENT: no such file or directory, stat '.../amplify/.temp/#current-cloud-backend/function/<lambda-layer-name>/lib/nodejs/node_modules/bigint-buffer/build/node_gyp_bins/python3'
ProjectInitFault: Could not initialize platform for 'dev': ENOENT: no such file or directory, stat '.../amplify/.temp/#current-cloud-backend/function/<lambda-layer-name>/lib/nodejs/node_modules/bigint-buffer/build/node_gyp_bins/python3'
```

</details>

### Additional information

Workaround which worked for me is [here](https://gist.github.com/josefaidt/a117076b7bea81e1872e275176dbb23c).
Also tried adding `pre-build.sh` script (deployed it with workaround):
```
cd ./amplify/backend/function/<layer-name>/lib/nodejs
yarn install --no-bin-links
```

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment] 2024-05-03 17:57
Hey @olehrdk, thank you for reaching out. The issue is currently being tracked on https://github.com/aws-amplify/amplify-cli/issues/6144 with comments providing additional information. 
Closing this issue as duplicate to track https://github.com/aws-amplify/amplify-cli/issues/6144

**Closed by ykethan** 2024-05-03 17:57 UTC
Labels: pending-triage
