### ISSUE TITLE
Adding PreSignup lambda trigger through CLI does not setup correctly when pushing to another environment

### ISSUE THREAD

**Issue by connected-swallace** [aws-amplify/amplify-cli#9108] opened 2021-11-26 21:55 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### Amplify CLI Version

6.1.1

### What operating system are you using?

Mac

### Amplify Categories

auth

### Amplify Commands

update

### Describe the bug

So we have several environments. Let's call one `testing` and one `develop`.

In `testing` I have added a PreSignup event trigger through `amplify update auth`.

This then correctly creates the lambda and connects the lambda for the Pre Sign up event trigger in the Cognito User pool for the `testing` environment.

I now commit all my changes to my branch.

However when I go to deploy this same set of changes to another environment `develop` the lambda gets created but when looking at the Cognito User Pool the lambda does not get connected to the Pre Sign up event trigger.

### Expected behavior

The PreSignup event trigger should be connected to the correct lambda from each environment.

### Reproduction steps

See description.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by akshbhu** [comment] 2021-11-29 17:02
hi @connected-swallace 

Is there any error you are facing  with triggers when switching evns.

This is one issue with triggers occurring when initializing environment. : https://github.com/aws-amplify/amplify-cli/issues/9112. Can you check if this is similar error you are getting?

Can you also paste ```backend-config.json``` for the ```develop``` env for which triggers weren't setup correctly after redacting any secret info present?

**Comment by connected-swallace** [comment] 2021-11-30 20:50
Not facing any errors when switching environments, so does not seem related to 9112.

Copy of our backend-config.json (with necessary redactions):
```
{
    "auth": {
      "appname": {
        "service": "Cognito",
        "providerPlugin": "awscloudformation",
        "dependsOn": [
          {
            "category": "function",
            "resourceName": "appnamePreSignup",
            "triggerProvider": "Cognito",
            "attributes": [
              "Arn",
              "Name"
            ]
          }
        ],
        "customAuth": false,
        "frontendAuthConfig": {
            *****
        }
      }
    },
    "api": {
      "appname": {
        "service": "AppSync",
        "providerPlugin": "awscloudformation",
        "output": {
          "authConfig": {
            *****
          }
        }
      }
    },
    "function": {
      "appnamePreSignup": {
        "build": true,
        "providerPlugin": "awscloudformation",
        "service": "Lambda",
        "dependsOn": [
          {
            "category": "api",
            "resourceName": "appname",
            "attributes": [
              "GraphQLAPIIdOutput",
              "GraphQLAPIEndpointOutput",
              "GraphQLAPIKeyOutput"
            ]
          }
        ]
      },
    }
  }
```

**Comment by benjeater** [comment] 2021-12-08 06:58
Same problem here.  Changing to any `env` and running `amplify push` removes all lambda triggers for Cognito in that `env`.

**Comment by Straubulous** [comment] 2021-12-10 18:46
This is a duplicate of f #9112  - if still having issue on latest please create new issue.

**Closed by Straubulous** 2021-12-10 18:46 UTC
Labels: pending-triage
