### ISSUE TITLE
Amplify doesn't update cognito aws-exports after push

### ISSUE THREAD

**Issue by artyom-melnikov** [aws-amplify/amplify-cli#3033] opened 2019-12-19 08:29 UTC
On a project with configured auth:
1. `amplify init` envA
2. `amplify push`
3. `amplify init` envB
4. `amplify push`  - here the appsync endopoints in `aws-exports.js` will be from envB, but cognito data from envA

Amplify 4.6.0

**Comment by kaustavghosh06** [comment] 2019-12-19 21:39
@artyom-melnikov Do you mean "aws_cognito_identity_pool_id" and the ""aws_user_pools_web_client_id" keys which are the same as envA? I tried to reproduce this but wasn't able to. It correctly shows different userpools from the different environments with CLI v4.6.

Can you run "amplify env checkout <envB>" and see if you still see the user pool key from envA in the `aws_exports.js` file?

**Comment by kaustavghosh06** [comment] 2020-01-16 22:41
Closing this issue due to lack of requested information. Please re-open if you're still stuck.

**Closed by kaustavghosh06** 2020-01-16 22:41 UTC
Labels: pending-response, pending-triage, platform

**Comment by jakepgoldman** [comment] 2020-03-09 02:09
Having this same problem. Removed an old environment and created a new one; pushed; but aws-exports does not change to reflect the new user pool/identity.

**Comment by Tilko** [comment] 2020-08-02 19:22
i maybe got the same problem and resolved it with:
amplify console > Backend environments > authentication 
then use the supplied "amplify pull"  and "update" cmd in your CLI

**Comment by yaquawa** [comment] 2021-01-15 11:45
same problem here as @jakepgoldman

**Comment by gbumgard** [comment] 2021-02-18 01:27
Same problem following 'env add', 'env checkout' and 'push' - the cognito user pool app client IDs did not update. Executing an 'amplify pull' fixed it.

**Comment by ctjlewis** [comment] 2021-04-30 05:10
Somehow `aws-exports.js` was not updated by a config change for me. You can flush this by:

```bash
# Pushing up local state
amplify push

# Then, deleting local aws-exports.js
rm src/aws-exports.js

# Then, pulling down remote state, and rewriting aws-exports
amplify pull
```
