### ISSUE TITLE
Graphql Subscriptions Auth not working as expected.

### ISSUE THREAD

**Issue by magjack** [aws-amplify/amplify-cli#3366] opened 2020-02-04 23:13 UTC
** Which Category is your question related to? **
API graphql

** What AWS Services are you utilizing? **
AWS AppSync

** Provide additional details e.g. code snippets **
Using amplify.js 2.2.2 and cli  @aws-amplify/cli@4.13.1

I have a graphql scheme that includes the following:
![image](https://user-images.githubusercontent.com/40371034/73794307-0dcb7b00-47a0-11ea-9a87-642e6688ff8e.png)

Orders are created via a lambda function where the owner is queered and placed in a call. This Lambda then submits an updateOrder after additional mutations. Owner can be seen on dynamo 
![image](https://user-images.githubusercontent.com/40371034/73794447-63078c80-47a0-11ea-8eb7-5890e716852f.png)

On another app with the same backend an onUpdateOrder subscription is created passing the owner id: 
![image](https://user-images.githubusercontent.com/40371034/73794680-df01d480-47a0-11ea-8632-b26d9373fc1e.png)

However the newly created and then updated Order is never returned to the subscription. When the owner auth rule is replaced with a private rule the orders are received however I only ever get the new orderId and no other information despite it being in dynamo. 
![image](https://user-images.githubusercontent.com/40371034/73795485-a7942780-47a2-11ea-8b50-3ecd4443495f.png)

I am asking the following: 
1. Is there an issue with Owner subscription auth if the order is created via a lambda working on IAM auth rule
2. Why are values being returned null with private auth ? What is the subscription message size limit?
3. I have enabled logging on my Appsync to try and debug this issue however I am unsure how to debug the subscription logs. Is there an owner subscription auth example logs that I can follow.

**Comment by magjack** [comment] 2020-02-11 00:21
I can confirm that the issue is that Orders created and updated via a Lambda using the IAM auth rule don't trigger messages to the subscription on an Owner auth rule and null all values bar the ID on a private auth rule. It seems only updates triggered by the Owner of the object result in a proper subscription message. Is this a bug or a desired behaviour? Is there a workaround to allow a user to be able to subscribe to a subscription but not give them create or update permissions?

**Comment by SwaySway** [comment] 2020-02-11 00:57
Hello @magjack yes currently `@auth` uses the mutation rules to check if the same person is allowed to listen to the subscription as well. Though we have been looking at adding listen as an operation to allow users to also listen in to subscriptions.

A quick workaround would be what is the highlighted comment below using cognito and using a cognito group which is allowed to listen to those subscriptions.
https://github.com/aws-amplify/amplify-cli/issues/2636#issuecomment-567286984i

Thank you raising this issue, we've been noticing this has been an ask within the community and we'll put any updates on this on #2636.

Closing as a duplicate of #2636

**Closed by SwaySway** 2020-02-11 00:57 UTC
Labels: graphql-transformer, question

**Comment by magjack** [comment] 2020-02-13 00:13
I get that #2636 covers the issue of a listen function. I think this would be really cool. My main question is now if an owner were to have the listen operation for orders and then an order was created on an lambda with an iam private auth rule giving the owner field the correct value would this appear on the users subcription?
