### ISSUE TITLE
amplify push --y results in FeatureFlags is not initialized error

### ISSUE THREAD

**Issue by karthikmBGO** [aws-amplify/amplify-cli#7507] opened 2021-06-11 17:49 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v15.9.0

### Amplify CLI Version

4.52.0

### What operating system are you using?

Mac

### Amplify Categories

auth

### Amplify Commands

push

### Describe the bug

as per this link - https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-three/?e=gs2020&p=build-a-react-app-two
In the Deploy the authentication service step 

I used amplify add auth in cli to add cognito as the authentication provider for my react app. Next step when pushing changes to cloud using amplify push --y , get this error 

 Category | Resource name              | Operation | Provider plugin   |
| -------- | -------------------------- | --------- | ----------------- |
| Auth     | friendsmoviereview108d712e | Create    | awscloudformation |
✖ An error occurred when pushing the resources to the cloud

FeatureFlags is not initialized
An error occurred during the push operation: FeatureFlags is not initialized

### Expected behavior

Local changes ( addition of cognito as auth provider ) to be pushed up to the cloud ( hosted amplify url ) 

### Reproduction steps

amplify add auth ( choose the default options ) , amplify push --y throws this error

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by jhockett** [comment] 2021-06-11 17:59
Hi @karthikmBGO, do you have a `cli.json` file in your `/amplify` folder? If so, can you share it here?

**Comment by karthikmBGO** [comment] 2021-06-11 18:24
Here is my cli.json contents
******************************
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": false,
      "enableiterativegsiupdates": true,
      "secondarykeyasgsi": true,
      "skipoverridemutationinputtypes": true
    },
    "frontend-ios": {
      "enablexcodeintegration": true
    },
    "auth": {
      "enablecaseinsensitivity": true,
      "useinclusiveterminology": true,
      "breakcirculardependency": true
    },
    "codegen": {
      "useappsyncmodelgenplugin": true,
      "usedocsgeneratorplugin": true,
      "usetypesgeneratorplugin": true,
      "cleangeneratedmodelsdirectory": true,
      "retaincasestyle": true,
      "addtimestampfields": true,
      "handlelistnullabilitytransparently": true
    },
    "appsync": {
      "generategraphqlpermissions": true
    }
  }
}
**************************************************

**Comment by karthikmBGO** [comment] 2021-06-11 21:03
Is there is an issue with the latest amplify cli thats triggering this issue ?

**Comment by jhockett** [comment] 2021-06-11 21:10
Not that we're aware of @karthikmBGO. I just went through the guide you mentioned and was able to push after adding auth on the latest version of the CLI (4.52.0).

**Comment by karthikmBGO** [comment] 2021-06-11 21:16
oh man. Is there any conditions on folder /root folder etc where the amplify push --y should happen from ? Could this be an issue with npm, node or any other tool versions ? All I am trying to do is get the React App added with the sign in sign up functionality from the cognito pool

**Comment by jhockett** [comment] 2021-06-11 21:36
@karthikmBGO, yes there is. `amplify push` and any other project related commands should be run from the root folder of your project.

**Comment by karthikmBGO** [comment] 2021-06-11 21:39
yes , confirmed. this is the folder I am at and running the amplify push --y

**Comment by karthikmBGO** [comment] 2021-06-11 21:39
I am using npm instead of yarn

**Comment by karthikmBGO** [comment] 2021-06-11 21:40
no issues on the cli.json file ?

**Comment by jhockett** [comment] 2021-06-11 22:11
Both npm and yarn should be fine, that shouldn't be an issue. The cli.json file you posted looks good, and is identical to the one in my sample project. The only difference that I can think of is that I'm running the LTS version of NodeJS 14.17.0.

**Comment by jhockett** [comment] 2021-06-11 22:13
Perhaps there's a file permission issue somewhere in your project. @karthikmBGO did you use `sudo` to run any of the commands in the tutorial?

**Comment by jhockett** [comment] 2021-06-11 22:23
@karthikmBGO can you share the file at `~/.amplify/plugins.json` here?

**Comment by karthikmBGO** [comment] 2021-06-11 22:29
{
  "pluginDirectories": [
    "cli-local-node-modules",
    "cli-parent-directory",
    "global-node-modules"
  ],
  "pluginPrefixes": [
    "amplify-"
  ],
  "userAddedLocations": [],
  "lastScanTime": "2021-06-10T22:32:34.910Z",
  "maxScanIntervalInSeconds": 86400,
  "plugins": {
    "core": [
      {
        "packageName": "@aws-amplify/cli",
        "packageVersion": "4.52.0",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/",
        "manifest": {
          "name": "core",
          "type": "core",
          "commands": [
            "categories",
            "configure",
            "console",
            "delete",
            "env",
            "help",
            "init",
            "logout",
            "migrate",
            "plugin",
            "publish",
            "push",
            "pull",
            "run",
            "status",
            "uninstall",
            "upgrade",
            "version"
          ],
          "commandAliases": {
            "h": "help",
            "serve": "run",
            "ls": "status"
          }
        }
      }
    ],
    "analytics": [
      {
        "packageName": "amplify-category-analytics",
        "packageVersion": "2.21.9",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-analytics",
        "manifest": {
          "name": "analytics",
          "type": "category",
          "commands": [
            "add",
            "remove",
            "push",
            "update",
            "console",
            "help"
          ],
          "commandAliases": {
            "configure": "update"
          },
          "eventHandlers": []
        }
      }
    ],
    "api": [
      {
        "packageName": "amplify-category-api",
        "packageVersion": "2.31.10",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api",
        "manifest": {
          "name": "api",
          "type": "category",
          "commands": [
            "add-graphql-datasource",
            "add",
            "console",
            "gql-compile",
            "push",
            "remove",
            "update",
            "help"
          ],
          "commandAliases": {
            "configure": "update"
          },
          "eventHandlers": []
        }
      }
    ],
    "auth": [
      {
        "packageName": "amplify-category-auth",
        "packageVersion": "2.33.0",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth",
        "manifest": {
          "name": "auth",
          "type": "category",
          "commands": [
            "add",
            "console",
            "enable",
            "import",
            "push",
            "remove",
            "update",
            "help"
          ],
          "eventHandlers": []
        }
      }
    ],
    "function": [
      {
        "packageName": "amplify-category-function",
        "packageVersion": "2.31.10",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function",
        "manifest": {
          "name": "function",
          "type": "category",
          "commands": [
            "add",
            "build",
            "console",
            "invoke",
            "push",
            "remove",
            "update",
            "help"
          ],
          "commandAliases": {
            "configure": "update"
          },
          "eventHandlers": []
        }
      }
    ],
    "hosting": [
      {
        "packageName": "amplify-category-hosting",
        "packageVersion": "2.7.9",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-hosting",
        "manifest": {
          "name": "hosting",
          "displayName": "Amazon CloudFront and S3",
          "type": "category",
          "commands": [
            "add",
            "configure",
            "console",
            "push",
            "remove",
            "help"
          ],
          "commandAliases": {
            "enable": "add",
            "update": "configure"
          },
          "services": [
            "S3AndCloudFront"
          ]
        }
      },
      {
        "packageName": "amplify-console-hosting",
        "packageVersion": "1.9.0",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-console-hosting",
        "manifest": {
          "name": "hosting",
          "type": "category",
          "commands": [
            "add",
            "configure",
            "remove",
            "help",
            "serve"
          ],
          "commandAliases": {
            "console": "serve",
            "configure": "update"
          },
          "displayName": "Hosting with Amplify Console (Managed hosting with custom domains, Continuous deployment)",
          "services": [
            "amplifyhosting"
          ]
        }
      },
      {
        "packageName": "amplify-container-hosting",
        "packageVersion": "1.3.10",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-container-hosting",
        "manifest": {
          "name": "hosting",
          "displayName": "Container-based hosting with AWS Fargate",
          "type": "category",
          "commands": [
            "add",
            "configure",
            "console",
            "push",
            "remove",
            "help"
          ],
          "commandAliases": {
            "enable": "add",
            "update": "configure"
          },
          "services": [
            "ElasticContainer"
          ]
        }
      }
    ],
    "interactions": [
      {
        "packageName": "amplify-category-interactions",
        "packageVersion": "2.6.2",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-interactions",
        "manifest": {
          "name": "interactions",
          "aliases": [
            "interaction"
          ],
          "type": "category",
          "commands": [
            "add",
            "push",
            "remove",
            "update",
            "help"
          ],
          "commandAliases": {
            "configure": "update"
          },
          "eventHandlers": []
        }
      }
    ],
    "notifications": [
      {
        "packageName": "amplify-category-notifications",
        "packageVersion": "2.19.2",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-notifications",
        "manifest": {
          "name": "notifications",
          "aliases": [
            "notification"
          ],
          "type": "category",
          "commands": [
            "add",
            "configure",
            "console",
            "remove",
            "status",
            "help"
          ],
          "commandAliases": {
            "enable": "add",
            "update": "configure",
            "disable": "remove",
            "delete": "remove",
            "list": "status",
            "ls": "status"
          },
          "eventHandlers": []
        }
      }
    ],
    "predictions": [
      {
        "packageName": "amplify-category-predictions",
        "packageVersion": "2.9.0",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-predictions",
        "manifest": {
          "name": "predictions",
          "aliases": [
            "Predictions"
          ],
          "type": "category",
          "commands": [
            "add",
            "console",
            "remove",
            "update",
            "help"
          ],
          "commandAliases": {
            "configure": "update"
          },
          "eventHandlers": []
        }
      }
    ],
    "storage": [
      {
        "packageName": "amplify-category-storage",
        "packageVersion": "2.11.10",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage",
        "manifest": {
          "name": "storage",
          "type": "category",
          "commands": [
            "add",
            "import",
            "console",
            "push",
            "remove",
            "update",
            "help"
          ],
          "commandAliases": {
            "configure": "update"
          },
          "eventHandlers": []
        }
      }
    ],
    "xr": [
      {
        "packageName": "amplify-category-xr",
        "packageVersion": "2.8.9",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-xr",
        "manifest": {
          "name": "xr",
          "aliases": [
            "XR"
          ],
          "type": "category",
          "commands": [
            "add",
            "console",
            "push",
            "remove",
            "update",
            "help"
          ],
          "commandAliases": {
            "configure": "update"
          },
          "eventHandlers": []
        }
      }
    ],
    "codegen": [
      {
        "packageName": "amplify-codegen",
        "packageVersion": "2.25.1",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen",
        "manifest": {
          "name": "codegen",
          "type": "util",
          "commands": [
            "add",
            "codegen",
            "configure",
            "remove",
            "statements",
            "types",
            "models"
          ],
          "commandAliases": {
            "update": "configure",
            "statement": "statements",
            "model": "models"
          },
          "eventHandlers": []
        }
      }
    ],
    "functionRuntime": [
      {
        "packageName": "amplify-dotnet-function-runtime-provider",
        "packageVersion": "1.5.4",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-dotnet-function-runtime-provider",
        "manifest": {
          "name": "functionRuntime",
          "type": "util",
          "commands": [],
          "eventHandlers": [],
          "functionRuntime": {
            "pluginId": "amplify-dotnet-function-runtime-provider",
            "conditions": {
              "provider": "awscloudformation",
              "services": [
                "Lambda"
              ]
            },
            "runtimes": [
              {
                "name": ".NET Core 3.1",
                "value": "dotnetcore3.1"
              }
            ]
          }
        }
      },
      {
        "packageName": "amplify-go-function-runtime-provider",
        "packageVersion": "1.8.2",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-go-function-runtime-provider",
        "manifest": {
          "name": "functionRuntime",
          "type": "util",
          "commands": [],
          "eventHandlers": [],
          "functionRuntime": {
            "pluginId": "amplify-go-function-runtime-provider",
            "conditions": {
              "provider": "awscloudformation",
              "services": [
                "Lambda"
              ]
            },
            "runtimes": [
              {
                "name": "Go",
                "value": "go"
              }
            ]
          }
        }
      },
      {
        "packageName": "amplify-java-function-runtime-provider",
        "packageVersion": "1.8.2",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-java-function-runtime-provider",
        "manifest": {
          "name": "functionRuntime",
          "type": "util",
          "commands": [],
          "eventHandlers": [],
          "functionRuntime": {
            "pluginId": "amplify-java-function-runtime-provider",
            "conditions": {
              "provider": "awscloudformation",
              "services": [
                "Lambda"
              ]
            },
            "runtimes": [
              {
                "name": "Java",
                "value": "java"
              }
            ]
          }
        }
      },
      {
        "packageName": "amplify-nodejs-function-runtime-provider",
        "packageVersion": "1.5.5",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider",
        "manifest": {
          "name": "functionRuntime",
          "type": "util",
          "commands": [],
          "eventHandlers": [],
          "functionRuntime": {
            "pluginId": "amplify-nodejs-function-runtime-provider",
            "conditions": {
              "provider": "awscloudformation",
              "services": [
                "Lambda",
                "LambdaLayer"
              ]
            },
            "runtimes": [
              {
                "name": "NodeJS",
                "value": "nodejs"
              }
            ]
          }
        }
      },
      {
        "packageName": "amplify-python-function-runtime-provider",
        "packageVersion": "1.8.2",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-python-function-runtime-provider",
        "manifest": {
          "name": "functionRuntime",
          "type": "util",
          "commands": [],
          "eventHandlers": [],
          "functionRuntime": {
            "pluginId": "amplify-python-function-runtime-provider",
            "conditions": {
              "provider": "awscloudformation",
              "services": [
                "Lambda",
                "LambdaLayer"
              ]
            },
            "runtimes": [
              {
                "name": "Python",
                "value": "python"
              }
            ]
          }
        }
      }
    ],
    "functionTemplate": [
      {
        "packageName": "amplify-dotnet-function-template-provider",
        "packageVersion": "1.5.9",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-dotnet-function-template-provider",
        "manifest": {
          "name": "functionTemplate",
          "type": "util",
          "commands": [],
          "eventHandlers": [],
          "functionTemplate": {
            "conditions": {
              "provider": "awscloudformation",
              "services": [
                "Lambda"
              ],
              "runtime": [
                "dotnetcore3.1"
              ]
            },
            "templates": [
              {
                "name": "Hello World",
                "value": "hello-world"
              },
              {
                "name": "Serverless",
                "value": "serverless"
              },
              {
                "name": "Trigger (DynamoDb, Kinesis)",
                "value": "trigger"
              },
              {
                "name": "CRUD function for DynamoDB (Integration with API Gateway)",
                "value": "crud"
              }
            ]
          }
        }
      },
      {
        "packageName": "amplify-go-function-template-provider",
        "packageVersion": "1.3.7",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-go-function-template-provider",
        "manifest": {
          "name": "functionTemplate",
          "type": "util",
          "commands": [],
          "eventHandlers": [],
          "functionTemplate": {
            "conditions": {
              "provider": "awscloudformation",
              "services": [
                "Lambda"
              ],
              "runtime": "go1.x"
            },
            "templates": [
              {
                "name": "Hello World",
                "value": "hello-world"
              }
            ]
          }
        }
      },
      {
        "packageName": "amplify-java-function-template-provider",
        "packageVersion": "1.5.6",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-java-function-template-provider",
        "manifest": {
          "name": "functionTemplate",
          "type": "util",
          "commands": [],
          "eventHandlers": [],
          "functionTemplate": {
            "conditions": {
              "provider": "awscloudformation",
              "services": [
                "Lambda"
              ],
              "runtime": "java"
            },
            "templates": [
              {
                "name": "Hello World",
                "value": "hello-world"
              }
            ]
          }
        }
      },
      {
        "packageName": "amplify-nodejs-function-template-provider",
        "packageVersion": "1.6.9",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-template-provider",
        "manifest": {
          "name": "functionTemplate",
          "type": "util",
          "commands": [],
          "eventHandlers": [],
          "functionTemplate": {
            "conditions": {
              "provider": "awscloudformation",
              "services": [
                "Lambda"
              ],
              "runtime": "nodejs"
            },
            "templates": [
              {
                "name": "Hello World",
                "value": "hello-world"
              },
              {
                "name": "CRUD function for DynamoDB (Integration with API Gateway)",
                "value": "crud"
              },
              {
                "name": "Serverless ExpressJS function (Integration with API Gateway)",
                "value": "serverless"
              },
              {
                "name": "Lambda trigger",
                "value": "trigger"
              }
            ]
          }
        }
      },
      {
        "packageName": "amplify-python-function-template-provider",
        "packageVersion": "1.3.9",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-python-function-template-provider",
        "manifest": {
          "name": "functionTemplate",
          "type": "util",
          "commands": [],
          "eventHandlers": [],
          "functionTemplate": {
            "conditions": {
              "provider": "awscloudformation",
              "services": [
                "Lambda"
              ],
              "runtime": "python"
            },
            "templates": [
              {
                "name": "Hello World",
                "value": "hello-world"
              }
            ]
          }
        }
      }
    ],
    "android": [
      {
        "packageName": "amplify-frontend-android",
        "packageVersion": "2.15.3",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-android",
        "manifest": {
          "name": "android",
          "type": "frontend",
          "commands": [
            "help"
          ],
          "eventHandlers": []
        }
      }
    ],
    "flutter": [
      {
        "packageName": "amplify-frontend-flutter",
        "packageVersion": "0.4.3",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-flutter",
        "manifest": {
          "name": "flutter",
          "type": "frontend",
          "commands": [
            "help"
          ],
          "eventHandlers": []
        }
      }
    ],
    "ios": [
      {
        "packageName": "amplify-frontend-ios",
        "packageVersion": "2.20.2",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-ios",
        "manifest": {
          "name": "ios",
          "type": "frontend",
          "commands": [
            "help"
          ],
          "eventHandlers": [
            "PostInit",
            "PostCodegenModels",
            "PostPull"
          ]
        }
      }
    ],
    "javascript": [
      {
        "packageName": "amplify-frontend-javascript",
        "packageVersion": "2.22.2",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript",
        "manifest": {
          "name": "javascript",
          "aliases": [
            "js"
          ],
          "type": "frontend",
          "commands": [
            "help"
          ],
          "eventHandlers": []
        }
      }
    ],
    "awscloudformation": [
      {
        "packageName": "amplify-provider-awscloudformation",
        "packageVersion": "4.51.0",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation",
        "manifest": {
          "name": "awscloudformation",
          "aliases": [
            "awscfn",
            "aws"
          ],
          "type": "provider",
          "commands": [
            "configure",
            "console",
            "reset-cache",
            "setupNewUser",
            "help"
          ],
          "commandAliases": {
            "resetCache": "reset-cache",
            "setup-new-user": "setupNewUser",
            "newUser": "setupNewUser",
            "new-user": "setupNewUser"
          }
        }
      },
      {
        "packageName": "amplify-provider-awscloudformation",
        "packageVersion": "4.29.0",
        "packageLocation": "/usr/local/lib/node_modules/amplify-provider-awscloudformation",
        "manifest": {
          "name": "awscloudformation",
          "aliases": [
            "awscfn",
            "aws"
          ],
          "type": "provider",
          "commands": [
            "configure",
            "console",
            "reset-cache",
            "setupNewUser",
            "help"
          ],
          "commandAliases": {
            "resetCache": "reset-cache",
            "setup-new-user": "setupNewUser",
            "newUser": "setupNewUser",
            "new-user": "setupNewUser"
          }
        }
      }
    ],
    "mock": [
      {
        "packageName": "amplify-util-mock",
        "packageVersion": "3.32.0",
        "packageLocation": "/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock",
        "manifest": {
          "name": "mock",
          "type": "util",
          "commands": [
            "api",
            "function",
            "mock",
            "storage",
            "help"
          ],
          "eventHandlers": []
        }
      }
    ]
  },
  "excluded": {}
}

**Comment by jhockett** [comment] 2021-06-11 22:37
@karthikmBGO, everything looks good from what I can see. Can you try uninstalling the CLI and reinstalling?

`npm uninstall -g @aws-amplify/cli`
`npm install -g @aws-amplify/cli`
`amplify -v` // should be 4.52.0
`amplify plugin scan`
Then, from your project's root directory:
`amplify push -y`

**Comment by karthikmBGO** [comment] 2021-06-11 22:42
the npm install and unstall can be run from any folder including project root folder as well I guess ?

**Comment by karthikmBGO** [comment] 2021-06-11 22:44
did the above steps , amplify -v is 4.52.0 , 

amplify push -y still gives this 


Current Environment: staging

| Category | Resource name              | Operation | Provider plugin   |
| -------- | -------------------------- | --------- | ----------------- |
| Auth     | friendsmoviereview108d712e | Create    | awscloudformation |
✖ An error occurred when pushing the resources to the cloud

FeatureFlags is not initialized
An error occurred during the push operation: FeatureFlags is not initialized

**Comment by karthikmBGO** [comment] 2021-06-11 22:47
actually this is the entire output - for amplify push -y when run from the project root

✔ Successfully pulled backend environment staging from the cloud.

Current Environment: staging

| Category | Resource name              | Operation | Provider plugin   |
| -------- | -------------------------- | --------- | ----------------- |
| Auth     | friendsmoviereview108d712e | Create    | awscloudformation |
✖ An error occurred when pushing the resources to the cloud

FeatureFlags is not initialized
An error occurred during the push operation: FeatureFlags is not initialized

**Comment by jhockett** [comment] 2021-06-11 22:50
> the npm install and unstall can be run from any folder including project root folder as well I guess ?

Correct. As long as it's a global installation (which is necessary)

**Comment by karthik2872** [comment] 2021-06-12 04:44
Reinstalled npm and node on my Mac. Now in module 2 -  https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-two/?e=gs2020&p=build-a-react-app-one

was configure is throwing an error - can you please help and point me where the issue is 
***********************************************
Cannot find module 'body-parser'
Require stack:
- /usr/local/lib/node_modules/amplify-provider-awscloudformation/lib/utils/admin-login-server.js
- /usr/local/lib/node_modules/amplify-provider-awscloudformation/lib/admin-login.js
- /usr/local/lib/node_modules/amplify-provider-awscloudformation/lib/utils/admin-helpers.js
- /usr/local/lib/node_modules/amplify-provider-awscloudformation/lib/configuration-manager.js
- /usr/local/lib/node_modules/amplify-provider-awscloudformation/lib/attach-backend.js
- /usr/local/lib/node_modules/amplify-provider-awscloudformation/lib/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/lib/configure-new-user.js
- /usr/local/lib/node_modules/@aws-amplify/cli/lib/commands/configure.js
- /usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/bin/amplify
/usr/local/lib/node_modules/amplify-provider-awscloudformation/lib/utils/admin-login-server.js:1
Error: Cannot find module 'body-parser'
Require stack:
- /usr/local/lib/node_modules/amplify-provider-awscloudformation/lib/utils/admin-login-server.js
- /usr/local/lib/node_modules/amplify-provider-awscloudformation/lib/admin-login.js
- /usr/local/lib/node_modules/amplify-provider-awscloudformation/lib/utils/admin-helpers.js
- /usr/local/lib/node_modules/amplify-provider-awscloudformation/lib/configuration-manager.js
- /usr/local/lib/node_modules/amplify-provider-awscloudformation/lib/attach-backend.js
- /usr/local/lib/node_modules/amplify-provider-awscloudformation/lib/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/lib/configure-new-user.js
- /usr/local/lib/node_modules/@aws-amplify/cli/lib/commands/configure.js
- /usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/bin/amplify
    at Object.<anonymous> (/usr/local/lib/node_modules/amplify-provider-awscloudformation/lib/utils/admin-login-server.js:9:39)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/amplify-provider-awscloudformation/lib/admin-login.js:10:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/amplify-provider-awscloudformation/lib/utils/admin-helpers.js:11:23)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/amplify-provider-awscloudformation/lib/configuration-manager.js:38:25)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/amplify-provider-awscloudformation/lib/attach-backend.js:9:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/amplify-provider-awscloudformation/lib/index.js:4:29)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at /usr/local/lib/node_modules/@aws-amplify/cli/lib/configure-new-user.js:42:26
    at Array.forEach (<anonymous>)
    at Object.configureNewUser (/usr/local/lib/node_modules/@aws-amplify/cli/lib/configure-new-user.js:41:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/commands/configure.js:57:9)
    at async Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:238:9)
    at async executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:164:5)
    at async Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:114:9)
**********************************************************************

**Comment by akshbhu** [comment] 2021-06-14 20:51
Hi @karthik2872  @karthikmBGO 

Can you paste logs for the error in ampify push -y, you can found these at ```~/.amplify/logs/amplify-cli-<issue-date>.log```.

Also second error seems like installation issue , Can you try uninstallng cli and installing it again?

**Comment by karthik2872** [comment] 2021-06-14 21:20
I have installed and reinstalled amplify cli globally and amplify -v shows 4.52.0
The amplify configure is working now - regarding amplify push failure 

These are the logs for 6/11,12

2021-06-11T17:20:18.174Z|info : amplify pull core  {"appId":"[***]tknfbw","envName":"[***]ing","yes":false}
2021-06-11T17:21:55.088Z|info : amplify pull core  {"appId":"[***]tknfbw","envName":"[***]ing","yes":false}
2021-06-11T17:24:25.201Z|info : amplify add auth  
2021-06-11T17:36:15.025Z|info : amplify push core  {"yes":true}
2021-06-11T17:37:09.142Z|info : amplify push core  {"yes":true}
2021-06-11T17:48:48.719Z|info : amplify version core  {"version":true,"yes":false}
2021-06-11T17:49:09.809Z|info : amplify version core  
2021-06-11T18:12:31.585Z|info : amplify push core  {"yes":true}
2021-06-11T18:29:23.807Z|info : amplify push core  {"yes":true}
2021-06-11T21:39:38.354Z|info : amplify push core  {"yes":true}
2021-06-11T21:43:35.562Z|info : amplify version core  {"version":true,"yes":false}
2021-06-11T22:02:48.318Z|info : amplify add auth  
2021-06-11T22:02:57.754Z|info : amplify update auth  
2021-06-11T22:04:47.111Z|info : amplify push core  {"yes":true}
2021-06-11T22:06:22.455Z|info : amplify publish core  {"yes":true}
2021-06-11T22:06:40.838Z|info : amplify help core  
2021-06-11T22:07:06.903Z|info : amplify add hosting  
2021-06-11T22:08:21.553Z|info : amplify publish core  {"yes":true}
2021-06-11T22:42:17.254Z|info : amplify version core  {"version":true,"yes":false}
2021-06-11T22:42:36.486Z|info : amplify push core  {"yes":true}
2021-06-12T00:29:33.986Z|info : amplify push core  
2021-06-12T00:30:16.525Z|info : amplify push core  {"yes":true}
2021-06-12T01:42:16.833Z|info : amplify console core  
2021-06-12T01:42:37.220Z|info : amplify configure core  
2021-06-12T02:05:50.658Z|info : amplify help core  {"g":"aws-amplify","yes":false}
2021-06-12T02:20:03.123Z|info : amplify version core  {"version":true,"yes":false}
2021-06-12T02:28:51.386Z|info : amplify configure core project 
2021-06-12T02:33:59.319Z|info : amplify version core  {"version":true,"yes":false}
2021-06-12T03:19:15.284Z|info : amplify version core  {"version":true,"yes":false}

2021-06-12T04:33:14.074Z|info : amplify version core  {"version":true,"yes":false}
2021-06-12T14:17:26.601Z|info : amplify version core  {"version":true,"yes":false}


2021-06-14T21:10:52.924Z|info : amplify version core  {"version":true,"yes":false}

**Comment by akshbhu** [comment] 2021-06-14 21:32
Is it still stuck with ```FeatureFlags not initialized ``` error after reinstalling amplify?

**Comment by karthik2872** [comment] 2021-06-14 22:12
I am in this step amplify pull --appId d3mo2wp0r6e9my --envName staging

(https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-two/?e=gs2020&p=build-a-react-app-one) 


This is taking me to a browser  https://us-east-1.admin.amplifyapp.com/admin/d3mo2wp0r6e9my/staging/verify/

asking me to sign into amplify backend - WHY SHOULD I SIGN into amplify backend when I am signed into the console already ?

Amplify is lot confusing and nowhere as simple as the instructions are - lots of dependencies and headaches.

**Comment by johnpc** [comment] 2021-07-27 18:38
the user you need to sign in as is the amplify admin ui user you're taking the role of when you pull. So this extra login step is required for AdminUI apps. 

This the original FeatureFlag issue still happening after reinstalling amplify?

**Comment by josefaidt** [comment] 2021-09-02 21:50
Hey @karthik2872 :wave: are you still experiencing this issue after reinstalling Amplify or with the [latest version of the CLI](https://github.com/aws-amplify/amplify-cli/releases/tag/v5.4.0)?

**Comment by karthikmBGO** [comment] 2021-09-04 12:17
I have not had a chance to try this again. I have worked around the need to use amplify the backend by setting up serverless end points over express for my backend apis that need authentication to be passed from client side calls. Using amplify only for the ReactJS front end for my project

**Comment by josefaidt** [comment] 2021-09-09 15:02
Hey @karthik2872 no worries! For the web page (Admin UI) asking to sign in, when Admin UI is enabled for that backend we will need to launch Admin UI from the Console for the first time before authenticating with the CLI if AdminUI is chosen as the preferred authentication method. This is an issue the team is actively tracking!

I'll close this issue for now, but if you experience this issue again with the [latest version of the CLI](https://github.com/aws-amplify/amplify-cli/releases/tag/v5.5.0) please reply back to this thread and we can re-open to investigate further, or file a [new bug report](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml)

**Closed by josefaidt** 2021-09-09 15:02 UTC
Labels: pending-close-response-required, pending-response, pending-triage, not-reproducible
