### ISSUE TITLE
amplify configure command hanging

### ISSUE THREAD

**Issue by walter-scott** [aws-amplify/amplify-cli#1692] opened 2019-06-20 16:50 UTC
**Describe the bug**
When I try to configure amplify, it hangs on creating the IAM. Hanging also happens with init. 

**To Reproduce**
I don't know if you will be able to reproduce it, but this is what I did:
1. `$ npm install -g @aws-amplify/cli`
2. `$ amplify configure` or goto app directory and `$ amplify init`

**Screenshots**
<img width="574" alt="Screen Shot 2019-06-20 at 10 18 38 AM" src="https://user-images.githubusercontent.com/32307401/59865964-fdb97500-934f-11e9-9120-0971958ffb8e.png">

**Desktop:**
 - macOS 10.14.4
 - Safari
 - node v12.4.0
 - npm v6.9.0
 - `$ aws --version`: `aws-cli/1.16.169 Python/3.7.3 Darwin/18.5.0 botocore/1.12.159`

**Additional context**
- my aws cli is configured properly with `$ aws configure`
- the log in to console part works properly in safari
- I tried uninstalling and installing node and npm
- I  tried leaving it alone for a long time
- To terminate either I have to close the terminal window.

**Comment by kaustavghosh06** [comment] 2019-06-20 17:00
This is a duplicate of #1688 
This is due to a recently introduced bug with one of our CLI dependencies - inquirer (https://github.com/SBoudrias/Inquirer.js/issues/811). We've merged a fix for this - https://github.com/aws-amplify/amplify-cli/pull/1690 and publishing to npm a new version NPM.

**Closed by kaustavghosh06** 2019-06-20 17:00 UTC
