### ISSUE TITLE
`total` field of `@searchable` is incorrect.

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#6728] opened 2021-02-24 18:27 UTC
I've see https://github.com/aws-amplify/amplify-cli/pull/2602
The `total` is simply the returned items's length, which makes no sense for everyone. I can get it myself from `data.items.length` from the response.

You should just search for the records that meet the auth requirement using the Search API of ElasticSearch in the first place but not filter them out after the search.

At least, `total` should be the `ctx.result.hits.total`, again, we COULD get the length of items by just refer `data.items.length`, put this as the `total` makes no sense.

**Comment by akshbhu** [comment] 2021-02-25 20:37
Hi @yaquawa 

This seems like a duplicate of this enhancement. For the workaround , you can follow this comment if you want want to customize resolvers to get total hits https://github.com/aws-amplify/amplify-cli/issues/5121#issuecomment-675568032

Closing this issue as a duplicate https://github.com/aws-amplify/amplify-cli/issues/5121

**Closed by akshbhu** 2021-02-25 20:37 UTC
