### ISSUE TITLE
Can't update notifications category

### ISSUE THREAD

**Issue by bmvdeveloper** [aws-amplify/amplify-cli#5639] opened 2020-10-20 07:58 UTC
**Describe the bug**
Cannot update or add a new notification channel via cli.

When running `amplify update notifications` and select `Email` results in `No resources to update.`

When running `amplify add notifications` results in `Notifications is migrated from Mobile Hub and channels cannot be added with Amplify CLI.`

**Amplify CLI Version**
4.30.0

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable
Scenario 1:
- Have notifications setup with APNS (email disabled/not setup)
- Use cli and run `amplify update notifications`
- select Email
See `No resources to update.`

Scenario 2:
- Have notifications setup with APNS (email disabled/not setup)
- Use cli and run `amplify add notifications`
See `Notifications is migrated from Mobile Hub and channels cannot be added with Amplify CLI.`
See `No resources to update.`

**Expected behavior**
I would like to be able to add email as a channel for notifications.

**Screenshots**
Status of the notifications category:
<img width="381" alt="Screen Shot 2020-10-20 at 12 56 13 AM" src="https://user-images.githubusercontent.com/53025018/96557502-32ed1480-126f-11eb-8dcd-e078ad4aca18.png">
Issue seen in console:
<img width="562" alt="Screen Shot 2020-10-20 at 12 54 53 AM" src="https://user-images.githubusercontent.com/53025018/96557506-34b6d800-126f-11eb-81ff-ae5c477dfd16.png">
You can see from console to verify emails are not enabled.
<img width="1364" alt="Screen Shot 2020-10-20 at 12 54 38 AM" src="https://user-images.githubusercontent.com/53025018/96557513-354f6e80-126f-11eb-98eb-1fadef6fecd4.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v12.9.0

**Additional context**

**Comment by UnleashedMind** [comment] 2020-10-22 00:11
Is your project migrated from Mobile Hub as stated in the error message?

**Comment by bmvdeveloper** [comment] 2020-10-22 20:54
No it's not a project that was migrated from Mobile Hub.  Is this category temporary for that purpose?  Or is it there permanently for for applications to have push notifications?

**Comment by UnleashedMind** [comment] 2020-10-22 22:32
I'm not able to reproduce with the latest CLI version though.  Check both `<project-root>/amplify/#current-cloud-backend/amplify-meta.json` and `<project-root>/amplify/backend/amplify-meta.json` files, under `notifications`, there is a resource with `"service": "Pinpoint"`, see if there is a flag `mobileHubMigrated`, if so, could you set it to false and try again?

**Comment by renebrandel** [comment] 2020-10-22 23:45
Hi @bmvdeveloper - we've got a fix in the release pipeline. This is the PR that fixed it. https://github.com/aws-amplify/amplify-cli/pull/5632

**Comment by akshbhu** [comment] 2020-10-22 23:55
Hi @bmvdeveloper 

We have just released the v4.31 which has the fix for the issue. I am closing this issue in favour of #5632.
 If you face this again, feel free to comment and ill open it again.

**Closed by akshbhu** 2020-10-22 23:55 UTC
Labels: bug, notifications
