### ISSUE TITLE
Injecting custom variables into appsync resolver templates

### ISSUE THREAD

**Issue by Jkap7788** [aws-amplify/amplify-cli#2891] opened 2019-12-01 10:32 UTC
**Is your feature request related to a problem? Please describe.**
Hi, 

I would like to create custom http resolvers which invoke aws services directly (e.g step functions).
However as part of the http request, I need to supply resource ARNs.
This becomes difficult when the resource names include the name of the environment as we then need to hard-code the name of the resource and alter it depending on the environment.

**Describe the solution you'd like**
I would like to be able to inject env variables into resolver templates to better support differences in environments as well as avoid hard coding resource names.

**Describe alternatives you've considered**
Instead of writing code in separate request/response template files, include the code directly with the cloudformation appsync::resolver resource.
Then use the cloudformation [!sub](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html) function to inject the resource name.

**Comment by kaustavghosh06** [comment] 2019-12-10 22:49
@Jkap7788 There is a PR out for this - #2553 and this feature request is a duplicate of #2092 
Closing this as a duplicate.

**Closed by kaustavghosh06** 2019-12-10 22:49 UTC
Labels: enhancement, pending-triage
