### ISSUE TITLE
 How disable autoId generation for some of my types

### ISSUE THREAD

**Issue by psycura** [aws-amplify/amplify-cli#134] opened 2018-09-08 11:08 UTC
** Which Category is your question related to? **
API: AppSync

** What AWS Services are you utilizing? **
AppSync

** Provide additional details e.g. code snippets **
I have a type in my schema.graphql, that look like this:
```
type User @model{
    id: ID!
    company: String!
    email: String!
    firstName: String!
    lastName: String!
    logo:String
    site:String!
    role:Int!
    type:String!
    package:Package! @connection(name:"UserPackage")
    customers:[Customer] @connection(name:"UserCustomers")
}
```

After `amplify push api` command, as a result i have a resolver `CreateUser` that looks like this:
```
$util.qr($context.args.input.put("createdAt", $util.time.nowISO8601()))
$util.qr($context.args.input.put("updatedAt", $util.time.nowISO8601()))
$util.qr($context.args.input.put("__typename", "User"))
{
  "version": "2017-02-28",
  "operation": "PutItem",
  "key": {
      "id": {
          "S": "$util.autoId()"
    }
  },
  "attributeValues": $util.dynamodb.toMapValuesJson($context.args.input),
  "condition": {
      "expression": "attribute_not_exists(#id)",
      "expressionNames": {
          "#id": "id"
    }
  }
}
```

I dont want that ID of my user was generated automatically, i want to use `cognitoUser id` (or some another source of ID generation) as an ID on user creation.
So how can i decide or mark in my schema that i dont want to use `$util.autoId()`?
Thank you!

**Comment by mikeparisstuff** [comment] 2018-09-11 19:42
This looks like a duplicate of https://github.com/aws-amplify/amplify-cli/issues/56. If you have any feedback on the proposals there let me know.

**Comment by kaustavghosh06** [comment] 2018-09-28 19:44
This is a duplicate issue. Tracking this issue as  a part of Issue #56

**Closed by kaustavghosh06** 2018-09-28 19:44 UTC
Labels: graphql-transformer, question
