### ISSUE TITLE
ModelTransformer pluralization is incorrect for plural types

### ISSUE THREAD

**Issue by weisisheng** [aws-amplify/amplify-cli#4224] opened 2020-05-09 03:08 UTC
**Describe the bug**
Create a simple graphql schema in schema.graphql.  Perform an amplify push.  react-js app can't find the type in "queries".  When I look in the file, an extra "s" is added to the type name.

**To Reproduce**

1. Go to schema file and create new types
2. Do 'amplify push'
3. React error given, can't find
4. Open queries file, type name is incorrect

**Expected behavior**
Type name is created verbatim and then front end does not have error accessing API

**Code Snippet**

## from schema.graphql
```gql
type TestPursuits @model @auth(rules: [{allow: owner, queries: null}])
{
  id: ID!
  searchName: String!
  posDescr: String!
  candidate: TestCandidates @connection
}
```
## from queries.js, ***note incorrect name transposed 3x but not for filter variable.***

export const listTestPursuitss = /* GraphQL */ `
  query ListTestPursuitss(
    $filter: ModelTestPursuitsFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listTestPursuitss(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        id
        searchName
        posDescr
        candidate {
          id
          name
          email
          posApplied
          owner
        }
        owner
      }
      nextToken
    }
  }
`;

**What is Configured?**
```
const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:0foofoofoo",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_foofooofoooofoofoo",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://foofoofoo.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-fakeApiId123456"
};

export default awsmobile;

```

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages

System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 250.52 MB / 15.39 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 12.16.3 - /usr/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.4 - /usr/bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 76.0
  npmPackages:
    @aws-amplify/analytics: ^3.1.9 => 3.1.9 
    @aws-amplify/api: ^3.1.9 => 3.1.9 
    @aws-amplify/auth: ^3.2.6 => 3.2.6 
    @aws-amplify/core: ^3.2.6 => 3.2.6 
    @aws-amplify/interactions: ^3.1.9 => 3.1.9 
    @aws-amplify/pubsub: ^3.0.10 => 3.0.10 
    @aws-amplify/storage: ^3.1.9 => 3.1.9 
    @aws-amplify/ui: ^2.0.2 => 2.0.2 
    @babel/core: * => 7.9.6 
    @material-ui/core: ^4.9.10 => 4.9.13 
    @material-ui/icons: ^4.9.1 => 4.9.1 
    @react-native-community/netinfo: ^5.5.0 => 5.8.0 
    @types/react: ^16.9.34 => 16.9.34 
    aws-amplify: ^3.0.9 => 3.0.10 
    aws-amplify-react: ^4.1.8 => 4.1.9 
    aws-sdk: ^2.656.0 => 2.673.0 
    chartist: ^0.11.4 => 0.11.4 
    core-js: ^3.6.5 => 3.6.5 
    eslint: 7.0.0 => 7.0.0 
    eslint-config-prettier: ^6.10.1 => 6.11.0 
    eslint-plugin-prettier: ^3.1.3 => 3.1.3 
    formik: ^2.1.4 => 2.1.4 
    gulp: 4.0.2 => 4.0.2 
    gulp-append-prepend: 1.0.8 => 1.0.8 
    history: ^4.10.1 => 4.10.1 
    moment: 2.24.0 => 2.24.0 
    node-sass: ^4.13.1 => 4.14.1 
    notistack: ^0.9.11 => 0.9.11 
    nouislider: ^14.2.0 => 14.4.0 
    perfect-scrollbar: ^1.5.0 => 1.5.0 
    prettier: ^2.0.4 => 2.0.5 
    prop-types: ^15.7.2 => 15.7.2 
    react: ^16.13.1 => 16.13.1 
    react-big-calendar: ^0.24.3 => 0.24.6 
    react-bootstrap-sweetalert: 5.1.9 => 5.1.9 
    react-chartist: ^0.14.3 => 0.14.3 
    react-datetime: 2.16.3 => 2.16.3 
    react-dom: ^16.13.1 => 16.13.1 
    react-google-maps: 9.4.5 => 9.4.5 
    react-jvectormap: ^0.0.16 => 0.0.16 
    react-native: ^0.62.2 => 0.62.2 
    react-router-dom: ^5.1.2 => 5.1.2 
    react-scripts: ^3.4.1 => 3.4.1 
    react-swipeable-views: ^0.13.9 => 0.13.9 
    react-table: ^7.0.4 => 7.0.4 
    react-tagsinput: 3.19.0 => 3.19.0 
    uuid: ^7.0.3 => 7.0.3 
    yup: ^0.28.4 => 0.28.5 
  npmGlobalPackages:
    @aws-amplify/cli: 4.17.2
    @graphql-toolkit/core: 0.9.7
    @graphql-toolkit/graphql-file-loader: 0.9.7
    @graphql-toolkit/json-file-loader: 0.9.7
    @graphql-toolkit/url-loader: 0.9.7
    @serverless/components: 0.1.25
    ajv: 6.10.0
    aws-amplify: 2.2.5
    axios: 0.19.0
    cheerio: 1.0.0-rc.3
    config: 3.2.0
    cordova-res: 0.8.0
    core-js: 3.6.4
    dynamodb-admin: 4.0.0
    expo-cli: 3.3.0
    gatsby-plugin-catch-links: 2.1.2
    gatsby-source-filesystem: 2.1.5
    gatsby-transformer-remark: 2.6.4
    gatsby: 2.15.2
    ghost-cli: 1.13.1
    graphql: 14.6.0
    green-tunnel: 1.7.4
    i: 0.3.6
    inquirer: 7.1.0
    jmespath: 0.15.0
    jshint: 2.10.2
    json-graphql-server: 2.1.3
    lodash: 4.17.14
    mailchimp-api-v3: 1.13.0
    mdanki: 1.0.2
    mdx-deck: 2.5.0
    mkdirp: 1.0.3
    npm: 6.14.2
    postmark-cli: 1.4.7
    postmark: 2.3.5
    react-dom: 16.9.0
    react: 16.9.0
    rels: 0.1.0
    serverless-offline: 5.7.3
    serverless: 1.68.0
    sharp: 0.23.1
    sudo: 1.0.3
    surge: 0.20.5

```

**Comment by weisisheng** [comment] 2020-05-12 00:35
Thanks very much for the timely response.  Lost a patch of hair on that one ;-)

**Comment by attilah** [comment] 2020-06-05 19:50
@weisisheng: what you see is by design as the initial pluralization was just to append an 's' and no external libraries was used. This cannot be fixed without breaking existing customer deployments, once we've feature flags implemented it will be a trivial fix.

**Comment by sharmaaditya570191** [comment] 2021-04-01 16:35
I would like to work on this.

**Comment by codenamegary** [comment] 2021-04-25 01:27
Just ran into this as well. Nice to see a PR is already open!

**Comment by cjihrig** [comment] 2021-07-07 16:38
Closing, as this was released.

**Closed by cjihrig** 2021-07-07 16:38 UTC
Labels: bug, graphql-transformer, referenced-in-release
