### ISSUE TITLE
AWS Amplify CLI Headless mode opening browser window to capture token - CI/CD

### ISSUE THREAD

**Issue by rohit3d2003** [aws-amplify/amplify-cli#13362] opened 2023-10-21 07:03 UTC
### How did you install the Amplify CLI?

npm

### Amplify CLI Version

5.3.11

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

I am using CodeMagic to automate build and deployment of iOS app which is using amplify backend. In order to achieve CI/CD, I have followed below steps:
1. Install amplify using 'npm install -g @aws-amplify/cli'
2. Pull environment specific configuration in a headless mode using below script

```
set -e
IFS='|'

AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":false,\
\"profileName\":\"default\",\
\"accessKeyId\":$AWS_ACCESS_KEY_ID,\
\"secretAccessKey\":$AWS_SECRET_ACCESS_KEY,\
\"region\":\"us-east-1\"\
}"

PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"

AMPLIFY="{\
\"projectName\":$PROJECT_NAME,\
\"appId\":$AMPLIFY_APP_ID,\
\"envName\":\"dev\",\
\"defaultEditor\":\"code\"\
}"

amplify pull \
--amplify $AMPLIFY \
--providers $PROVIDERS \
--yes
```

Issue: Unfortunately in the headless mode, CLI is opening a browser window and stuck on someone clicking 'yes' or 'Copy CLI Key' vs automatically doing it.

### Expected behavior

Token automatically downloaded in headless mode vs asking for a user interactive action to support CI/CD

### Reproduction steps

1. On any new machine, install amplify and run above mentioned script to see browser window coming up

### Log output

<details>

# Put your logs below this line

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment] 2023-10-23 21:20
Hey @rohit3d2003, thank you for reaching out. could you try utilizing the following without the `set -e
IFS='|'`


```
#!/bin/sh

AMPLIFY_APP_ID="<app-id>"

AMPLIFY="{\
\"projectName\":\"10070\",\
\"appId\":\"$AMPLIFY_APP_ID\",\
\"envName\":\"dev\",\
\"defaultEditor\":\"vscode\"\
}"

PROVIDERS="{\
\"awscloudformation\":{\
\"configLevel\":\"project\",\
\"useProfile\":false,\
\"profileName\":\"default\",\
\"accessKeyId\":\"<ID>\",\
\"secretAccessKey\":\"<key>\",\
\"region\":\"us-east-1\"\
}\
}"

amplify pull \
  --providers "$PROVIDERS" \
  --amplify "$AMPLIFY" \
  --yes
```

**Comment by rohit3d2003** [comment] 2023-10-23 23:00
This worked. Wondering what changed in the above

**Comment by ykethan** [comment] 2023-10-24 15:04
@rohit3d2003 believe the issue was caused by the escape characters being utilized such as access credentials and application.
Additionally, I will be closing the issue for now. please feel free on reaching out to us again.

**Closed by ykethan** 2023-10-24 15:04 UTC
Labels: pending-triage, headless
