### ISSUE TITLE
I require a graphQL API maximum statement depth of greater than 10, but when I try to increase it to 12 i get a crash.

### ISSUE THREAD

**Issue by babylon2017** [aws-amplify/amplify-cli#6272] opened 2020-12-28 14:48 UTC
To increate the API statement depth I use:
`Amplify codegene configure`

When I try to increase it to 12 (10 compiles just fine, but is not enough for my nested graphQL API), I get the following error:

```
Downloading the introspection schema⠋ Downloading the introspection schema⠋ Downloading the introspection schema⠋ Downloading the introspection schema⠋ Downloading the introspection schema⠋ Downloading the introspection schema⠋ Downloading the introspe✔ Downloaded the schema
✔ Downloaded the schema
✔ Downloaded the schema
✔ Downloaded the schema
✔ Downloaded the schema
✔ Downloaded the schema
✔ Downloaded the schema
✔ Downloaded the schema
✔ Downloaded the schema
⠋ Generating GraphQL operations
<--- Last few GCs --->

[12878:0x110008000]   188002 ms: Mark-sweep 3938.1 (4126.9) -> 3927.3 (4130.9) MB, 2509.5 / 0.0 ms  (average mu = 0.532, current mu = 0.016) allocation failure scavenge might not succeed
[12878:0x110008000]   190522 ms: Mark-sweep 3943.3 (4130.9) -> 3932.8 (4134.9) MB, 2479.6 / 0.0 ms  (average mu = 0.367, current mu = 0.016) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
 1: 0x1012e2bc5 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x1000a5cb9 node::Abort() [/usr/local/bin/node]
 3: 0x1000a5e1f node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 4: 0x1001e83e7 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x1001e8383 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 6: 0x100397275 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 7: 0x1003f2173 v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [/usr/local/bin/node]
 8: 0x1003d98db void v8::internal::LiveObjectVisitor::VisitBlackObjectsNoFail<v8::internal::EvacuateNewSpaceVisitor, v8::internal::MajorNonAtomicMarkingState>(v8::internal::MemoryChunk*, v8::internal::MajorNonAtomicMarkingState*, v8::internal::EvacuateNewSpaceVisitor*, v8::internal::LiveObjectVisitor::IterationMode) [/usr/local/bin/node]
 9: 0x1003d9505 v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [/usr/local/bin/node]
10: 0x1003d9176 v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [/usr/local/bin/node]
11: 0x1003f6a7e v8::internal::PageEvacuationTask::RunInParallel(v8::internal::ItemParallelJob::Task::Runner) [/usr/local/bin/node]
12: 0x1003b1d22 v8::internal::ItemParallelJob::Task::RunInternal() [/usr/local/bin/node]
13: 0x1003b218f v8::internal::ItemParallelJob::Run() [/usr/local/bin/node]
14: 0x1003db169 void v8::internal::MarkCompactCollectorBase::CreateAndExecuteEvacuationTasks<v8::internal::FullEvacuator, v8::internal::MarkCompactCollector>(v8::internal::MarkCompactCollector*, v8::internal::ItemParallelJob*, v8::internal::MigrationObserver*, long) [/usr/local/bin/node]
15: 0x1003dada1 v8::internal::MarkCompactCollector::EvacuatePagesInParallel() [/usr/local/bin/node]
16: 0x1003c6e67 v8::internal::MarkCompactCollector::Evacuate() [/usr/local/bin/node]
17: 0x1003c46f3 v8::internal::MarkCompactCollector::CollectGarbage() [/usr/local/bin/node]
18: 0x10039793b v8::internal::Heap::MarkCompact() [/usr/local/bin/node]
19: 0x100393ee9 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
20: 0x100391ca1 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
21: 0x1003a053a v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
22: 0x1003a05c1 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
23: 0x100367350 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [/usr/local/bin/node]
24: 0x1005b4b1c v8::internal::Handle<v8::internal::ObjectHashSet> v8::internal::HashTable<v8::internal::ObjectHashSet, v8::internal::ObjectHashSetShape>::New<v8::internal::Isolate>(v8::internal::Isolate*, int, v8::internal::AllocationType, v8::internal::MinimumCapacity) [/usr/local/bin/node]
25: 0x1005953e6 v8::internal::KeyAccumulator::CollectOwnPropertyNames(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSObject>) [/usr/local/bin/node]
26: 0x100592ff1 v8::internal::KeyAccumulator::CollectOwnKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSObject>) [/usr/local/bin/node]
27: 0x10059236b v8::internal::KeyAccumulator::CollectKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSReceiver>) [/usr/local/bin/node]
28: 0x1005917c9 v8::internal::FastKeyAccumulator::GetKeys(v8::internal::GetKeysConversion) [/usr/local/bin/node]
29: 0x1006e1ed7 v8::internal::Runtime_ForInEnumerate(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
30: 0x100a795f9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
31: 0x29f74884ce26 
zsh: abort      amplify codegen
```

**Comment by jamesonwilliams** [comment] 2020-12-29 00:15
Transferred to Amplify CLI issues. Whether or not we support this statement depth, the customer experience here is wrong. CLI should send a friendly message instead of barfing with a cryptic stack trace from a dependency.

**Comment by edwardfoyle** [comment] 2020-12-29 23:08
@babylon2017 Could you provide the relevant parts of your schema and describe how you've configured codegen? I'm unable to reproduce with the following schema and a depth of 12:
```graphql
type Todo @model {
  id: ID!
  name: String!
  description: String
  subTodo: Todo
}

```

**Comment by babylon2017** [comment] 2020-12-30 10:02
@edwardfoyle, The following is and excerpt from my schema. In the schema below, at a statement depth of 10, I query for the ResearchPost by ID, from this I am unable to access HashTags from the tags property of ResearchPost.

`type ResearchPost @model 
@auth(rules: [{ allow: owner, operations: [create, delete, update] }])
{
  id: ID!
  userId: ID!
  title: String!
  description: String
  isPosted: Boolean!
  tags: [Tag] @connection(keyName: "byTag", fields: ["id"])
  groups: [FeedGroupEditor] @connection(keyName: "feedGroupEditorByPost", fields: ["id"]) 
  links: [HyperLink] @connection(keyName: "hyperLinksByPost", fields: ["id"])
  likes: [Like] @connection(keyName: "byLike", fields: ["id"])
  media: [MediaComponent] @connection(keyName: "mediaByPost", fields: ["id"])
  attachments: [Attachment] @connection(keyName: "attachmentsByPost", fields: ["id"])
  author: Person @connection(fields: ["userId"])
  comments: [Comment] @connection(keyName: "byPost", fields: ["id"])
}

type Tag @model @searchable
@auth(rules: [{ allow: owner, operations: [create, delete, update] }])
@key(name: "byTag", fields: ["postID", "hashTagID"])
@key(name: "postByHashTag", fields: ["postID", "hashTagID"], queryField: "postByHashTag")
{
  id: ID!
  hashTagID: ID! 
  postID: ID!
  post: ResearchPost @connection(fields: ["postID"])
  hashTag: HashTag @connection(fields: ["hashTagID"])
}

type HashTag @model @searchable
@auth(rules: [{ allow: owner, operations: [create, delete, update] }])
@key(name: "hashTaByName", fields: ["hashTagName"], queryField: "hashTaByName")
{
  id: ID!
  hashTagName: String
}`

**How I configured codegen:**
I used the following command:
`amplify add api`
At `amplify push`, there were options to create the code for my iOS project written to API.swift.
To increase the statement depth during the project (after deployment), I used:
`amplify codegen configure`

Please let me know if I can provide any further information.

**Comment by edwardfoyle** [comment] 2020-12-31 22:10
Hi @babylon2017 I'm still unable to reproduce this issue. In the original stacktrace you posted I see that JS ran out of heap space. Is it possible that you've configured node to run with a very small amount of memory or perhaps you are running on a machine with limited memory?

**Comment by babylon2017** [comment] 2021-01-02 08:45
Hi @edwardfoyle I am new to AWS Amplify.  When I set up my IOS project I simply followed `Amplify init` instructions.  If what you say is correct, please could you give me some pointers in increasing this memory?  i have had a dig around at the Amplify console but cannot see any options to configure this memory?

**Comment by edwardfoyle** [comment] 2021-01-04 21:31
The node memory isn't an Amplify specific thing and if you aren't aware of any configuration you've changed, then that's likely not the issue.

**Closed** 2021-01-27 01:03 UTC
Labels: graphql-transformer, not-reproducable
