### ISSUE TITLE
Error: Type "ModelFlightConnection" not found in document

### ISSUE THREAD

**Issue by heitorlessa** [aws-amplify/amplify-cli#2631] opened 2019-10-25 14:56 UTC
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

**To Reproduce**

1. Deploy Serverless Airline project: `amplify init --app https://github.com/aws-samples/aws-serverless-airline-booking`
2. In the schema, remove `list queries` from `type Flight`: `@model(subscriptions: null, queries: {get: "flight"}) ` or `@model(subscriptions: null, queries: {list: null})`
3. Run locally: `amplify mock`

**Expected behavior**

Amplify not to error out, and to remove `listFlights` query.

**Error**: `Error: Type "ModelFlightConnection" not found in document.`

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Version [e.g. 22] 10.14.6

**Additional context**

* **Amplify-CLI version**: 3.16.0

**Schema exerpt that works**

```graphql
type Flight 
    @model(subscriptions: null) 
    @key(name: "ByDepartureSchedule", 
        fields: ["departureAirportCode", "arrivalAirportCode", "departureDate"],
        queryField: "getFlightBySchedule")
{
    id: ID!
    departureDate: String!
    departureAirportCode: String!
    departureAirportName: String!
    departureCity: String!
    departureLocale: String!
    arrivalDate: String!
    arrivalAirportCode: String!
    arrivalAirportName: String!
    arrivalCity: String!
    arrivalLocale: String!
    ticketPrice: Int!
    ticketCurrency: String!
    flightNumber: Int!
    seatAllocation: Int!
}
```

**Comment by attilah** [comment] 2019-10-29 13:07
@heitorlessa I think it is a duplicate of #2389, and #2538 will fix it.

**Closed by attilah** 2019-10-29 13:07 UTC
Labels: graphql-transformer, pending-triage
