### ISSUE TITLE
codegen produce an empty src/API.ts

### ISSUE THREAD

**Issue by Kamran21** [aws-amplify/amplify-cli#6269] opened 2020-12-28 16:19 UTC
**Describe the bug**
codegen produce an empty src/API.ts

**Amplify CLI Version**
4.40.1

**To Reproduce**
On ann expo typescript project:
amplify mock locally and also when running amplify codegen  src/API.ts is generated but stays empty

**Expected behavior**
To have all the relevant types inside of API.ts

**Screenshots**
![image](https://user-images.githubusercontent.com/7753930/103227918-dc1b4f80-492f-11eb-9859-d650817646ba.png)

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Node Version: 12.19.0
 - Expo version: 4.0.15

**Additional context**
I needed codegen to work in order to use amplify with the context of typescript however It seems that amplify doesn't make it easy to work with typescript out of the box and solutions like in the articles below should be generated by the amplify automatically:

@dantasfiles [using-typescript-with-aws-amplify-api](https://medium.com/@dantasfiles/using-typescript-with-aws-amplify-api-3788d722869)

@mwarger [aws-amplify-graphql-queries-with-typescript-and-hooks](https://dev.to/mwarger/aws-amplify-graphql-queries-with-typescript-and-hooks-1e2)

@AppField [how-to-use-an-aws-amplify-graphql-api-with-a-react-typescript-frontend](https://dev.to/rmuhlfeldner/how-to-use-an-aws-amplify-graphql-api-with-a-react-typescript-frontend-2g79
)

**Comment by edwardfoyle** [comment] 2020-12-31 21:57
Can you describe how you configured `amplify codegen`? In particular, when running `amplify codegen configure`, ensure that
```
? Enter the file name pattern of graphql queries, mutations and subscriptions
```
is set correctly. The default is `src/graphql/**/*.ts` for typescript projects

**Comment by Kamran21** [comment] 2021-01-01 18:51
Thank you for replying, Your comment helped me noticing the change in the path of the generated graphql, In my case it seems that it is ./graphql/**/*.ts instead of ./src/graphql/**/*.ts.

I am not sure why the default doesn't start with src folder and instead the graphql folder was created at the root instead. 

![Screenshot 2021-01-01 at 18 36 55](https://user-images.githubusercontent.com/7753930/103443517-59143500-4c60-11eb-9b6c-cdeee4a44202.png)

I didn't changed/configure my expo+amplify for it to be like that.
I created a new project in order to test and it seems that by default when running "amplify mock" on a new project it creates the graphql folder in the root and not inside src.  (Seems that it is not what the cli expect, Maybe a bug to be fixed?)

**Comment by enhancement-ventures** [comment] 2021-01-04 15:30
Happens to me too, fresh project

**Comment by edwardfoyle** [comment] 2021-01-05 01:17
I'm unable to repro this in a new project (the default path when I do it is `src/graphql/**/*.ts`). @enhancement-ventures @Kamran21 can you give repro steps starting from `amplify init`?

To work around this issue, you can run `amplify codegen configure` and update the graphql glob pattern to the correct one.

**Comment by Kamran21** [comment] 2021-01-05 12:38
1. I created a new expo project: >`expo init -t expo-template-blank-typescript todo`
2. Run >`amplify init` with the defaults
3. Run >`amplify add api` with the defaults and todo template
4. run >`amplify codegen configure` with the defaults
5. run >`amplify codegen`
6. the result was an empty src/API.ts because by default the graphql  folder was created on the root by default

@edwardfoyle  As I mentioned after I read your fist reply I changed my default path `amplify codegen configure` and it worked when i run again `amplify codegen` and the src/API.ts was created with types. 

More important concern for developers who wants to use typescript and the types exposed is to have a working example in the amplify docs that uses a solution like:

@mwarger aws-amplify-graphql-queries-with-typescript-and-hooks. 

I think that it would be good that the amplify sdk will expose the typescript wrapper hooks like the those in the example above by default when the user select typescript in `amplify codegen configure` 

@edwardfoyle  This is kind of a feature request, Can you bring this concern to Amplify team?

**Comment by edwardfoyle** [comment] 2021-01-05 21:06
@Kamran21 thanks for the repro steps, I was able to get a repro for this. It looks like the root cause of the issue is the "SourceDir" value in `amplify/.config/project-config.json`. Can you confirm if the value for "SourceDir" in that file is "/"?

**Comment by Kamran21** [comment] 2021-01-06 12:01
@edwardfoyle Tnx for the reply, I can't confirm as I don't have the .config folder under amplify:
<img width="1680" alt="Screenshot 2021-01-06 at 12 52 29" src="https://user-images.githubusercontent.com/7753930/103765885-339b7880-501e-11eb-8b78-fc7b4679b6b1.png">

@edwardfoyle What about my other suggestion for amplify package to expose by default some hooks that will make it easier to get response data from query, mutations, subscriptions, on typescript project. Similar to the hooks described on @mwarger [aws-amplify-graphql-queries-with-typescript-and-hooks](https://dev.to/mwarger/aws-amplify-graphql-queries-with-typescript-and-hooks-1e2). article.

**Comment by edwardfoyle** [comment] 2021-01-06 18:55
@Kamran21 can you open a new feature request describing what you'd like to see there?

**Comment by mwarger** [comment] 2021-01-06 23:27
@Kamran21 I'm flattered by the repeated mentions.  I think @ericclemmons had opened up an RFC at one point for something like what you're describing: https://github.com/aws-amplify/amplify-js/issues/4235

Please see the discussion there about it.

**Comment by kaustavghosh06** [comment] 2021-01-29 02:06
@Kamran21 Looks like the fix for the original request was merged and a part of the latest version of the CLI.
Could you please verify and open up new GitHub requests for more improvements and suggestions? Thank you!

**Closed by kaustavghosh06** 2021-01-29 02:06 UTC
Labels: bug, code-gen, pending-release
