### ISSUE TITLE
Individual category `push` commands are equivalent to `amplify push`

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-cli#836] opened 2019-02-07 21:51 UTC
**Describe the bug**
When attempting to push changes to the cloud for individual categories, all categories currently provisioned in the amplify app are pushed instead.

**To Reproduce**
1. Provision multiple categories in an Amplify App
2. Modify multiple categories such that at least two categories are in the `Update` status
3. Attempt to push the changes to just one category, like `amplify api push`
4. You will see that all the categories attempt to update, despite specifying you just want API (or whatever category) to update.

**Expected behavior**
Only changes to API (in this case) should be pushed to the AWS cloud; all other provisioned categories should remain in its current state.

**Screenshots**
![image](https://user-images.githubusercontent.com/22964702/52445327-04092c00-2ae8-11e9-9f7d-34e1b1c85199.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 69

**Comment by jkeys-ecg-nmsu** [comment] 2019-02-08 00:34
@yuth 

1. 0.1.45
2. Yes. My overall template is broken (happened when we briefly tried multienv then reverted to the original CLI) so I was only trying to push schema updates to the cloud.

**Comment by jkeys-ecg-nmsu** [comment] 2019-02-08 17:41
@kaustavghosh06 @yuth in the meantime while this behavior is being resolved, are there any steps that can be taken to repair my overall cloudformation template so that I can do an overall `amplify push`?

**Comment by yuth** [comment] 2019-02-08 20:49
Did migration to multienv succeed? Or was the template broke while migrating?

If it did, then we recommend you keep using multienv as we don't have support for migrating back older version using the CLI.

If you still want to use older version of CLI, you could try editing the cloudformation templates in `<project-root>/backend/<category>/<name>/*-cloudformation-template.yaml>` or `<project-root>/backend/<category>/<name>/*-cloudformation-template.json>` and try removing `env` from `Parameters` section of the CFN template.

**Comment by jkeys-ecg-nmsu** [comment] 2019-02-08 20:58
> Did migration to multienv succeed? Or was the template broke while migrating?
> 
> If it did, then we recommend you keep using multienv as we don't have support for migrating back older version using the CLI.
> 
> If you still want to use older version of CLI, you could try editing the cloudformation templates in `<project-root>/backend/<category>/<name>/*-cloudformation-template.yaml>` or `<project-root>/backend/<category>/<name>/*-cloudformation-template.json>` and try removing `env` from `Parameters` section of the CFN template.

Is there any way to export a clean version of the template with everything in its current (unupdated) status?

**Comment by yuth** [comment] 2019-02-08 21:34
Unfortunately, we don't automatically back it up after migration. 

If you're using a version control systems like git, you could checkout the version that was committed before  migration and pushing that should restore you back to the state before migration

**Comment by jkeys-ecg-nmsu** [comment] 2019-02-09 01:08
I installed the multienv CLI again and push worked fine. Thanks!

I'll leave this issue open to track the category-specific push bug.

**Comment by yuth** [comment] 2019-02-09 01:11
Thank you for confirming that this is not caused by migration. This is in our backlog and we will get this prioritized.

**Comment by bwobbones** [comment] 2019-05-24 05:24
Any updates on this one @yuth?  Its very annoying, my deployment can take up to an hour to get through, even when I only need to to deploy a tiny lambda change.

**Comment by kaustavghosh06** [comment] 2019-08-01 18:43
Hey guys, we enabled individual category and resource name push. Please give it a try by installing the latest version of the CLI.

**Closed by kaustavghosh06** 2019-08-01 18:43 UTC
Labels: bug

**Comment by SteffeyDev** [comment] 2020-01-11 02:27
@kaustavghosh06 was this reverted? In 4.12.0 it still runs the entire deployment, even when pushing an individual category, such as auth or storage, using `amplify <category> push`.

**Comment by mdebo** [comment] 2020-02-11 22:06
@stefangomez @kaustavghosh06 i confirm using cli 4.13.1 version when doing amplify <category> push it still runs the entire deployment.

**Comment by kaustavghosh06** [comment] 2020-02-11 22:10
@mdebo It would be running the Cloudformation deployment - which would include that category and resource - but it updated Cloudformation files are not updated - hence the changes won't take into affect if you do an individual category push.

**Comment by houmark** [comment] 2020-06-06 04:04
More than one year later, this is still an issue. Any progress? Major productivity killer to not be able to push just one function for example.

**Comment by danielmhair** [comment] 2020-08-06 12:01
Any updates?

**Comment by avlonder** [comment] 2021-01-27 21:15
Still an issue with 4.41.2

**Comment by krikork** [comment] 2021-02-12 20:01
Would be great to be able to push individual resources. Comes specially handy if there is a team of people collaborating on a project.
