### ISSUE TITLE
The pipeline req.vtl resolver cannot be overriden with custom req.vtl

### ISSUE THREAD

**Issue by clinicalinkgithub** [aws-amplify/amplify-cli#2074] opened 2019-08-17 16:01 UTC
The pipeline ***.req.vtl resolver cannot be overriden with custom ***.req.vtl when using the @function directive to add lamba resolvers.

see screenshot.

![lambaResolverError](https://user-images.githubusercontent.com/40474055/63214481-b4369d80-c0e6-11e9-8a23-d42eb79cea3a.jpg)

**Comment by clinicalinkgithub** [comment] 2019-08-17 16:25
Also, any pipleline *.req.vtl is  not copied to the /build/pipeline directory at all.
 ==> the compile does not copy any custom pipeline *.reql.vtl template in to the /build/pipeline

![anyPipeplineFunction](https://user-images.githubusercontent.com/40474055/63214734-26f54800-c0ea-11e9-9b33-2064c9deb39b.jpg)

**Comment by attilah** [comment] 2019-08-19 10:25
@clinicalinkgithub thanks for reporting this issue we'll look into it.

**Comment by kaustavghosh06** [comment] 2019-08-22 17:27
@clinicalinkgithub We don't support custom pipeline functions yet. But you can utilize Custom stacks with cutom resolvers to add pipeline resolvers to your API. You can read more about it out here - https://aws-amplify.github.io/docs/cli-toolchain/graphql#custom-resolvers

**Comment by clinicalinkgithub** [comment] 2019-08-22 20:36
the problem is we are using the @function directive. and it creates a invokelambaXXX.vtl pipleline in the puts in the /pipelineresolver directory. The stack that is created for the @function directive looks for the pipelineresolver in the  /pipelineresolver directory. There is no way to override the invokelambda payload currently.  can you modify the stack to place the invokelamba.vtl pipeline resolver in the /resolver directory instead???

**Comment by VitValchar** [comment] 2019-09-19 10:30
@kaustavghosh06 I have the same issue. When I set, for example, this mutation `updateUser(input: InputUpdateUser!): User @function(name: "resolvers-${env}")` will create this pipeline setup automatically:
![image](https://user-images.githubusercontent.com/10848279/65235941-d94c7080-dad7-11e9-9c0d-5acb712d4acd.png)
I can change the two templates marked green (in the build folder, those are stored in `backend/api/[apiname]/build/resolvers`) by copying this file from the build folder into the source folder (`backend/api/[apiname]/resolvers`) and adjusting it. On deploy, this custom template is taken (if exists) instead of generating a default one. The problem is, there is no way to do the same for the two templates marked in red (in the build folder, those are stored in `backend/api/[apiname]/build/pipelineFunctions`). The deploy/build process will always use the default template, so I cannot override it with the custom one.

I'm able to change those templates in the web view, but `amplify push` replaces it with the default template again.

**Comment by riywo** [comment] 2020-01-01 00:19
Same here. My use case is overriding error handling of the function for not passing the raw-level lambda error message to the client. Since function's auto-generated response resolver (which cannot be overridden - the red box in the previous comment) uses [`$util.error()`](https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-function-transformer/src/FunctionTransformer.ts#L154), it seems AppSync returns response there without looking into the pipeline resolver for response (which can be overridden - the green box in the previous comment).

There are lots of useful use cases when the customers want to change how to handle errors of Lambda data source and resolver VTL does support them: https://docs.aws.amazon.com/appsync/latest/devguide/resolver-mapping-template-changelog.html#aws-appsync-resolver-mapping-template-version-2018-05-29

So, if `amplify` CLI supports overriding each function's resolver by putting `pipelineFunctions/*.vtl` just like `resolvers/*.vtl`, it can support various unique use cases.

**Comment by ppattewa** [comment] 2020-03-12 18:28
I have a similar case as riyo mentioned. Also additionally, I want to look at input values sent by client and after changing it (business logic) want to send it as a additional payload item to lambda if possible. Unit resolver is not an option as there is an authorization element as well as the mentioned creation of new field based on different clients inputs. Customizing the before template is possible but not the pipeline req.vtl and hence this value does not go all the way to lambda. Any workarounds?

**Comment by SwaySway** [comment] 2020-06-01 22:47
Closing this issue as you can now override pipeline resolvers and the PR is included in the release.
https://github.com/aws-amplify/amplify-cli/pull/4196

**Closed by SwaySway** 2020-06-01 22:47 UTC
Labels: feature-request, graphql-transformer, pending-review
