### ISSUE TITLE
Failed to pull the backend

### ISSUE THREAD

**Issue by betomoedano** [aws-amplify/amplify-cli#12283] opened 2023-03-22 06:12 UTC
### How did you install the Amplify CLI?

curl -sL https://aws-amplify.github.io/amplify-cli/install | bash && $SHELL

### If applicable, what version of Node.js are you using?

v16.18.1

### Amplify CLI Version

11.0.2

### What operating system are you using?

MacOS Ventura 13.0.1

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

I'm trying to pull a project in a new machine but after entering my credentials got this error

<img width="847" alt="Screenshot 2023-03-21 at 11 06 42 PM" src="https://user-images.githubusercontent.com/43630417/226816612-2d1079d8-d8d3-41ce-8488-261ff2f14d15.png">

### Expected behavior

Pull backend and generate `aws-exports.js` file

### Reproduction steps

1. Install Amplify
2. Clone git repository 
3. Pull amplify project

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by betomoedano** [comment] 2023-03-22 17:14
Hi there, @josefaidt! Thank you for your prompt response.

To give you some more context, the authentication mechanism we chose for this task was the AWS profile, as can be seen in the attached screenshot. As for the credentials, they were set up through the AWS console using an access key and secret access key generated through the IAM service.

<img width="1465" alt="Screenshot 2023-03-22 at 10 11 25 AM" src="https://user-images.githubusercontent.com/43630417/226984140-0bee8b04-c6bd-4a25-be4a-47115a382ab5.png">

**Comment by josefaidt** [comment] 2023-03-22 21:56
Hey @betomoedano thanks for clarifying and for posting the stack trace! I'm curious about the following lines from the stack trace, where `amplify/backend/auth/<name>/parameters.json` is an older file and a sign of an unmigrated auth resource. How old is this project?

Can you also confirm the version of the CLI being used locally? I was not able to reproduce this on Amplify CLI 11.0.2 by pulling a recently-created project with Auth

**Comment by betomoedano** [comment] 2023-03-23 01:11
This is a fairly old project. It's been almost a year since I created it, and I haven't been maintaining it since then. The version of the CLI being used locally is ^7.4.2.

![Screenshot 2023-03-22 at 9 02 56 PM](https://user-images.githubusercontent.com/43630417/227072329-9c0bcbc2-fb9a-4095-8c8e-5d5c529d46c0.png)

I also tried to upgrade the CLI version locally to `11.0.2` but got the exact same error.

**Comment by josefaidt** [comment] 2023-03-28 20:42
Hey @betomoedano thanks for posting that! Did you previously have an auth resource attached to this project? Or was recently added to this project?

Additionally, do you have any issues pulling this project into a separate directory?

**Comment by betomoedano** [comment] 2023-03-28 21:05
Hey @josefaidt thanks for your help! 

- Yes I had an auth resource attached to this project. I was authenticating users with phone number.
- I have tried to pull this project in different directories and even different computers but got the exact same error.

Thanks again for your time.

**Comment by josefaidt** [comment] 2023-03-28 22:21
Hey @betomoedano thanks for clarifying! Was auth intentionally removed from the project, or is this an unexpected side effect of the issue?

**Comment by betomoedano** [comment] 2023-04-17 13:54
Hello @josefaidt, apologies for my delayed response. I have been occupied with several tasks lately.

I was able to resolve the issue by adding auth as a new project. Although I am uncertain about what went wrong previously, I believe the mistake was on my part.

Thank you once again for your valuable assistance.

**Comment by josefaidt** [comment] 2023-04-17 20:15
Hey @betomoedano no worries! Glad to hear you're back up and running despite the oddity! Given I was unsuccessful reproducing this issue I will close this for now, however if this comes up again please do not hesitate to reply to this thread and we can re-open the issue to investigate further

**Closed by josefaidt** 2023-04-17 20:15 UTC
Labels: pending-triage, platform-pull
