### ISSUE TITLE
Error type: MappingTemplate. Message: Expression block '$[query]' requires an expression

### ISSUE THREAD

**Issue by Fitux** [aws-amplify/amplify-cli#9153] opened 2021-11-30 18:42 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

nvm

### Amplify CLI Version

6.3.1

### What operating system are you using?

Windows

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

When running one of the queries generated in my API I do get the following error
Error type: MappingTemplate.
Message: Expression block '$[query]' requires an expression

Here is my code

```
const fetchDeliveries = async (projectNeed) => {
        try {
            const { data } = await API.graphql({
                query: relationshipByProjectNeed,
                variables: {
                    input: {
                        projectneedID: projectNeed.id,
                    }
                },
            });
            console.log('deliveries', data);
        } catch (error) {
            console.error(error);
        }
    };
```

For me this seems to be an error related to the resolvers generated automatically by the aws-amplify/cli
But I'm a little bit lost on what could be the error since the resolver generated looks good

### Expected behavior

The query to be executed and return the expected results

### Reproduction steps

Deploy the schema provided below and try to run the query specified in the code above

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Charge @model @auth(rules: [{allow: private}]) @key(name: "byUser", fields: ["userID"]) {
  id: ID!
  userID: ID
  state: String
  quantity: Int
  currency: String
  type: String
  typeRef: String
  description: String
  chargeDateTime: AWSDateTime
}

type Payment @model @auth(rules: [{allow: private}]) @key(name: "byUser", fields: ["userID"]) {
  id: ID!
  userID: ID
  state: String
  quantity: Int
  currency: String
  type: String
  typeRef: String
  description: String
  expectedDate: AWSDate
  paymentDateTime: AWSDateTime
}

type Delivery @model @auth(rules: [{allow: private}]) @key(name: "byProjectRelationship", fields: ["projectrelationshipID"]) {
  id: ID!
  projectrelationshipID: ID
  deliveryName: String
  expectedDate: AWSDate
  uploadedDate: AWSDate
  fileUrl: AWSURL
  state: String
  description: String
}

type Contract @model @auth(rules: [{allow: private}]) @key(name: "byProjectRelationship", fields: ["projectrelationshipID"]) {
  id: ID!
  projectrelationshipID: ID
  uploadedDate: AWSDate
  fileUrl: AWSURL
  state: String
  description: String
}

type Education @model @auth(rules: [{allow: private}]) @key(name: "byExpert", fields: ["expertID"]) {
  id: ID!
  expertID: ID
  institution: String
  title: String
  beginDate: AWSDate
  endDate: AWSDate
  fieldOfStudy: String
  location: String
}

type Licences @model @auth(rules: [{allow: private}]) @key(name: "byExpert", fields: ["expertID"]) {
  id: ID!
  expertID: ID
  institution: String
  courseName: String
  beginDate: AWSDate
  endDate: AWSDate
  fieldOfStudy: String
  location: String
}

type ProjectRelationship @model @auth(rules: [{allow: private}]) @key(name: "byExpert", fields: ["expertID"], queryField: "relationshipByExpert") @key(name: "byProjectNeed", fields: ["projectneedID"], queryField: "relationshipByProjectNeed") @key(name: "byProject", fields: ["projectID"], queryField: "relationshipByProject") {
  id: ID!
  expertID: ID
  state: String
  rating: Int
  projectneedID: ID
  projectID: ID
  Deliveries: [Delivery] @connection(keyName: "byProjectRelationship", fields: ["id"])
  Contracts: [Contract] @connection(keyName: "byProjectRelationship", fields: ["id"])
  expertCost: Int
  expertRate: Int
  expertHours: String
  expertCurrency: String
}

type Notification @model @auth(rules: [{allow: private}]) @key(name: "byUser", fields: ["userID"]) {
  id: ID!
  userID: ID
  title: String
  message: String
  type: String
  read: Boolean
}

type Experience @model @auth(rules: [{allow: private}]) @key(name: "byExpert", fields: ["expertID"]) {
  id: ID!
  expertID: ID
  title: String
  institution: String
  beginDate: AWSDate
  endDate: AWSDate
  description: String
  type: String
  industry: String
  location: String
  uploadedFiles: [String]
}

type ProjectNeed @model @auth(rules: [{allow: private}]) @key(name: "byProject", fields: ["projectID"]) {
  id: ID!
  projectID: ID
  title: String
  specialty: String
  subspecialty: String
  skills: [String]
  languages: [String]
  duration: String
  budget: Int
  expectedRate: Int
  ProjectRelationships: [ProjectRelationship] @connection(keyName: "byProjectNeed", fields: ["id"])
  currency: String
  state: String
}

type Project @model @auth(rules: [{allow: private}]) @key(name: "byCompany", fields: ["companyID"]) {
  id: ID!
  companyID: ID
  name: String
  description: String
  stage: String
  state: String
  ProjectNeeds: [ProjectNeed] @connection(keyName: "byProject", fields: ["id"])
  ProjectRelationships: [ProjectRelationship] @connection(keyName: "byProject", fields: ["id"])
  imageUrl: AWSURL
}

type Company @model @auth(rules: [{allow: private}]) {
  id: ID!
  name: String
  location: String
  city: String
  employeeRange: String
  type: String
  sector: String
  description: String
  phoneNumber: String
  email: String
  webpage: String
  Enterprise: Enterprise @connection
  Projects: [Project] @connection(keyName: "byCompany", fields: ["id"])
  logoUrl: AWSURL
}

type Enterprise @model @auth(rules: [{allow: private}]) {
  id: ID!
  title: String
  hobbies: [String]
  workingHours: String
  favoriteAnimal: String
  favoriteFood: String
  favoriteCountry: String
  User: User @connection
  Company: Company @connection
}

type Expert @model @auth(rules: [{allow: private}]) {
  id: ID!
  title: String
  rate: Int
  bio: String
  specialty: String
  subspecialty: String
  yearsOfExperience: String
  skills: [String]
  hobbies: [String]
  workingHours: String
  favoriteAnimal: String
  favoriteFood: String
  User: User @connection
  favoriteCountry: String
  Experiences: [Experience] @connection(keyName: "byExpert", fields: ["id"])
  ProjectRelationships: [ProjectRelationship] @connection(keyName: "byExpert", fields: ["id"])
  Licences: [Licences] @connection(keyName: "byExpert", fields: ["id"])
  Educations: [Education] @connection(keyName: "byExpert", fields: ["id"])
  languages: [String]
  currency: String
}

type User @model @key(name: "byUsername", fields: ["username"], queryField: "userByUsername") @auth(rules: [{allow: private}]) {
  id: ID!
  username: String!
  email: String!
  phoneNumber: AWSPhone
  firstName: String
  lastName: String
  profilePicture: AWSURL
  gender: String
  membership: String
  type: String
  active: Boolean
  firstTime: Boolean
  Enterprise: Enterprise @connection
  Expert: Expert @connection
  Notifications: [Notification] @connection(keyName: "byUser", fields: ["id"])
  city: String
  location: String
  linkedInUrl: String
  Charges: [Charge] @connection(keyName: "byUser", fields: ["id"])
  Payments: [Payment] @connection(keyName: "byUser", fields: ["id"])
}

input StripeInput {
  id: ID!
  total: Float
  currency: String
  action: String
  paymentIntentId: String
}

type Mutation {
  processStripePayment(input: StripeInput): String @function(name: "fishnchipsstripefunction-${env}")
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by sundersc** [comment] 2021-11-30 23:30
Hey @Fitux - what does your query `relationshipByProjectNeed` look like?

**Comment by Fitux** [comment] 2021-12-01 00:24
It looks like this

```
export const relationshipByProjectNeed = /* GraphQL */ `
  query RelationshipByProjectNeed(
    $projectneedID: ID
    $sortDirection: ModelSortDirection
    $filter: ModelProjectRelationshipFilterInput
    $limit: Int
    $nextToken: String
  ) {
    relationshipByProjectNeed(
      projectneedID: $projectneedID
      sortDirection: $sortDirection
      filter: $filter
      limit: $limit
      nextToken: $nextToken
    ) {
      items {
        id
        expertID
        state
        rating
        projectneedID
        projectID
        expertCost
        expertRate
        expertHours
        expertCurrency
        createdAt
        updatedAt
        Deliveries {
          nextToken
        }
        Contracts {
          nextToken
        }
      }
      nextToken
    }
  }
`;
```

**Comment by sundersc** [comment] 2021-12-01 07:43
I was able to reproduce the issue using the code you provided. However when I modified the query like this (as per docs), it worked. 
```ts
const { data } = await API.graphql(graphqlOperation(relationshipByProjectNeed, { projectneedID: projectNeed }));
```

**Comment by cjihrig** [comment] 2022-01-05 22:47
Closing due to lack of follow up. If you're still experiencing problems, please open a new issue.

**Closed by cjihrig** 2022-01-05 22:47 UTC
Labels: graphql-transformer, pending-response
