### ISSUE TITLE
Can not add tags to custom AWS resources using CDK

### ISSUE THREAD

**Issue by f-miyu** [aws-amplify/amplify-cli#9830] opened 2022-02-22 16:42 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.3

### Amplify CLI Version

7.6.21

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

custom

### Amplify Commands

push

### Describe the bug

 I have added Tags setting in cdkStack.
```ts
const queue = new sqs.Queue(this, 'Queue', {
    queueName: `queue`
});
    
Tags.of(queue).add('key', 'value');
```

But the the `Tags` property does not contain in the built CloudFormation template file as the following.
```json
"Queue4A7E3555": {
  "Type": "AWS::SQS::Queue",
  "Properties": {
    "QueueName": "queue"
  },
  "UpdateReplacePolicy": "Delete",
  "DeletionPolicy": "Delete"
}
```

`customStack._toCloudFormation()` seems to be called to generate CloudFormation template file ([link](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-category-custom/src/utils/generate-cfn-from-cdk.ts#L20)) but I think `SynthUtils.toCloudFormation(customStack)` should be called instead of it. It can generate the template file which contains Tags property.

### Expected behavior

The built template file contains `Tags` property if Tags is added in CDK.
```json
"Queue4A7E3555": {
  "Type": "AWS::SQS::Queue",
  "Properties": {
    "QueueName": "queue",
    "Tags": [
        {
            "Key": "key",
            "Value": "value"
        }
    ]
  },
  "UpdateReplacePolicy": "Delete",
  "DeletionPolicy": "Delete"
}
```

### Reproduction steps

1. Generate CDK files by `amplify add custom`
2. Edit cdk-stack.ts to add the tag
```ts
Tags.of(scope).add('key', 'value');
```
3. `amplify push`

**Comment by josefaidt** [comment] 2022-02-22 17:32
Hey @f-miyu :wave: thanks for raising this! I was able to successfully reproduce this behavior in a custom CDK resource:

```ts
import * as cdk from '@aws-cdk/core'
import * as AmplifyHelpers from '@aws-amplify/cli-extensibility-helper'
import { AmplifyDependentResourcesAttributes } from '../../types/amplify-dependent-resources-ref'
import * as sqs from '@aws-cdk/aws-sqs'

export class cdkStack extends cdk.Stack {
  constructor(
    scope: cdk.Construct,
    id: string,
    props?: cdk.StackProps,
    amplifyResourceProps?: AmplifyHelpers.AmplifyResourceProps
  ) {
    super(scope, id, props)
    /* Do not remove - Amplify CLI automatically injects the current deployment environment in this input parameter */
    new cdk.CfnParameter(this, 'env', {
      type: 'String',
      description: 'Current Amplify CLI env name',
    })

    const amplifyProjectInfo = AmplifyHelpers.getProjectInfo()
    const sqsQueueResourceNamePrefix = `sqs-queue-${amplifyProjectInfo.projectName}`
    const queue = new sqs.Queue(this, 'sqs-queue', {
      queueName: `${sqsQueueResourceNamePrefix}-${cdk.Fn.ref('env')}`,
    })

    cdk.Tags.of(queue).add('mykey', 'myvalue')
    console.log(queue.stack.tags)
  }
}
```

Upon running `amplify build` we see the console.log output does not contain the new tag `mykey`, and does not get built to the CFN template in the nested `build/` directory. Marking as a bug 🙂

**Comment by marcvberg** [comment] 2022-03-03 17:22
Hi @f-miyu ,

Just to help narrow this down, have you been able to use CDK V1 and create a tagged queue outside of the CLI? I ask because the CDK does have open issues on their GitHub with some other resource types not being able to be tagged, and I believe this might be an issue on that end rather than a CLI component.

**Comment by marcvberg** [comment] 2022-03-04 15:23
To add clarification: `SynthUtils` is a part of the CDK's testing library, I'd prefer us not to lean on their testing utilities in order to get something working

**Comment by f-miyu** [comment] 2022-03-04 16:35
@marcvberg 
I have been able to create a tagged queue using CDK 1.124.0. I still don't think tags can be added with `_toCloudFormation()`.

**Comment by marcvberg** [comment] 2022-03-08 21:59
I attempted to add tags to a queue using the Synthesize process outside of Amplify and was still unable to do so. We will not use `SynthUtils` to implement this as it's a part of their `assert` library, and not made for production CFN stack generation. 

This is an issue with the CDK library and I encourage you to open an issue against their repository.

https://github.com/aws/aws-cdk

**Comment by josefaidt** [comment] 2022-04-15 20:06
Closing due to inactivity. When this issue is addressed by CDK we can re-open to investigate further

**Closed by josefaidt** 2022-04-15 20:06 UTC
Labels: bug, dependency-issue, pending-close-response-required, extensibility, p2
