### ISSUE TITLE
Additional app created after upgrading amplify-cli to 4.x

### ISSUE THREAD

**Issue by heitorlessa** [aws-amplify/amplify-cli#2972] opened 2019-11-29 17:26 UTC
**Describe the bug**
Duplicated App in Amplify Console after upgrading Amplify-CLI to 4.x (4.2 as of now). 

![image](https://user-images.githubusercontent.com/3340292/69883722-48f78c80-12cd-11ea-97f3-8f087a56da02.png)

**To Reproduce**
1. Create a new App within Amplify Console
2. Install Amplify-CLI older than 4, upgrade it and push
3. You should see a duplicated app

**Expected behavior**
Single App

**Additional context**

**Sample code**
Include additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

**Comment by houmark** [comment] 2019-12-12 10:16
I hit something similar while upgrading from 3.16 to 4.6.0. I even read this bug report before and tried my best to avoid it.

This is what I did:

* Upgraded amplify cli in npm
* Did a pull, amplify status, and various stuff to try to get the app ID, nothing really happened
* amplify status was reporting changes (which it had from before the upgrade), so I did an amplify push
* The push was successful, and I checked that the new Managed Policies were created, seemed to work
* After the push finished the team-provider-info.json file now had `AmplifyAppId` added
* Went to the Console to update my live version to 4.6.0
* I committed the team-provider-info file and pushed it to force a build in the Console
* At this point I noticed a new app, no frontend, but the push of my backend was connected to the backend of that app
* The build seemed to work fine both for frontend of backend but I still have two apps
* Went to the CLI and did an amplify pull which kinda errored: 
> Amplify appId mismatch.
> You are currently working in the amplify project with Id d1gmm0yc7cvihe (id changed slightly for privacy)
* At this point it seemed like my only option was to manually update the team-provider-info.json file with the `AmplifyAppId` the Console was giving me for my existing app (not the duplicate)
* Doing a pull after having done that change didn't give any errors.

So now I believe I should be able to push from the CLI without issues and everything seems to be working for now, but my semi loaded duplicate app in the Console persists. Is it safe to delete that app in the Console without deleting any resources?

You guys really need to start documenting upgrades and code your upgrades to handle stuff like this nicer in order to prevent having to experiment with solutions on a PRODUCTION system. I have yet to do a single Amplify CLI upgrade without regressions or nit picks. This time it seems like a nit pick at best, so I guess that's progress?

**Comment by houmark** [comment] 2019-12-18 00:55
@kaustavghosh06 @UnleashedMind 

I'd like clarification on two very basic questions (this does not seem to be documented):

1) Can an Amplify Console app be safely deleted in the UI without any Amplify resources being torn down?

2) Is the recently introduced `AmplifyAppId` consistent between environments or will there be a unique ID per environment (in the same project of course)?

I'm halfway in the process of upgrading from 3.x to latest release in my dev environment, but I don't want to continue to production until I have this cleared out.

**Comment by kaustavghosh06** [comment] 2019-12-20 22:35
Fix for this has been merged and released with v4.7.

**Closed by kaustavghosh06** 2019-12-20 22:35 UTC
Labels: amplify-console, bug

**Comment by amcbb** [comment] 2020-01-14 20:12
We just recently updated from amplify cli 3.14.0 to 4.12.0 and seem to be experiencing this exact issue after the upgrade.

**Comment by houmark** [comment] 2020-01-15 00:57
And AWS devs do not care to respond to my basic questions whether it's 100% safe to remove the extra app created. I would not like to remove it and have resources automatically removed effectively breaking our `prod` environment.

@kaustavghosh06 @UnleashedMind would you please respond at least to point 1 here:  https://github.com/aws-amplify/amplify-cli/issues/2972#issuecomment-566817944.

**Comment by UnleashedMind** [comment] 2020-01-16 00:16
@amcbb 
If you want to add your env to an existing Amplify Console project, you should run the migration workflow on an fully setup project: 
`amplify init --appId <amplify-console-project-appId>`

**Comment by kaustavghosh06** [comment] 2020-01-16 00:59
@houmark Sorry for the late response. Please find responses in-line for your questions

1. Can an Amplify Console app be safely deleted in the UI without any Amplify resources being torn down (a new app with only backend attached was automatically created in the update process, and I'd like to get rid of it)?


Yes, deleting the Amplify Console app in the UI won't delete your resources

2. Is the recently introduced AmplifyAppId consistent between environments or will there be a unique ID per environment (in the same project of course)?

The AmplifyAppID is based on your account/region If you're pushing to the same AWS account and region - your AmplifyAppID would be the same. If you have your environments in different regions/accounts, you'll have a different AmplifyAppID.

**Comment by amcbb** [comment] 2020-01-16 19:23
> @amcbb
> If you want to add your env to an existing Amplify Console project, you should run the migration workflow on a fully setup project (by previous version of the Amplify CLI):
> `amplify init --appId <amplify-console-project-appId>`
Thanks @UnleashedMind.  We were previously using amplify v 3.14.0 before the upgrade, and I missed the below text.  Is it possible to configure something so **no** Amplify Console project is created each time a new environment is init'd (and not added to an existing project through --appId) like before?  If not, this seems like a strange design change to me since team-workflow often has many backend development environments for developers that have no need to be added to Amplify Console projects (whether new or existing apps).

![image](https://user-images.githubusercontent.com/53920004/72555479-a2f6e600-386a-11ea-9129-43643a3b553b.png)

**Comment by julianpinedayyz** [comment] 2020-12-31 01:49
This keeps happening. I just changed the id in the team-provider-info.json and the ran `amplify pull --appId your-amplifyAppId --envName` staging" and works properly.
