### ISSUE TITLE
Unexpected token  in JSON at position 0

### ISSUE THREAD

**Issue by mtaufiq81** [aws-amplify/amplify-cli#6409] opened 2021-01-16 18:56 UTC
Unexpected token  in JSON at position 0 when doing amplify api gql-compile and amplify push

**Amplify CLI Version**
4.41.2

- OS: Mac OS Big SUR

**Comment by ammarkarachi** [comment] 2021-01-19 02:50
@mtaufiq81 If you could share more information like schema or if this issue is something that you are seeing just in the latest version or previous versions too

**Comment by mtaufiq81** [comment] 2021-01-19 08:57
Hi Ammar,

The issue was with the latest version only. Things were fine before the npm update of the cli. However after downgrading the issue still persisted and I can't even add new env. Since I had no there option I started trying new things and in the process I found out that in the #current_backend/build/stack folder was the issue there was no json file issue but I just moved the stack folder and did amplify api gel-compile then replaced the stack folder again and things became okay.

**Comment by mtaufiq81** [comment] 2021-01-19 08:59
I am starting to doubt on amplify reliability for a large scale application due to such issues. I've almost gave up on this the solution came out nothing less than a miracle.

**Comment by kaustavghosh06** [comment] 2021-02-04 01:34
This seems a duplicate of https://github.com/aws-amplify/amplify-cli/issues/6164 and was fixed with CLI v4.40.1

**Comment by ammarkarachi** [comment] 2021-02-04 01:36
@mtaufiq81 Sorry about the delay on getting back to you, Can you share your schema? I will take a look

**Comment by mtaufiq81** [comment] 2021-02-04 10:21
The schema was same as before didn't change anything special however, can't share the schema. But this issue was not with the schema but some half build process which corrupt the #current_backend stacks.

**Closed** 2021-02-04 10:22 UTC
Labels: graphql-transformer, pending-triage
