### ISSUE TITLE
I cannot add Analytics resources to my project

### ISSUE THREAD

**Issue by MiguelFERREIRA-1** [aws-amplify/amplify-cli#10906] opened 2022-08-18 12:52 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.15.1

### Amplify CLI Version

9.1.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual change made

### Amplify Categories

auth, analytics

### Amplify Commands

add

### Describe the bug

When I amplify add analytics to my project, I choose Pinpoint and get this error 
![image](https://user-images.githubusercontent.com/79586891/185398467-d732c661-319e-4e05-b430-25774b2fe325.png)

For information, the auth of this project is handled by importing using the command amplify import auth

### Expected behavior

Allowing the command with currently present auth rules imported

### Reproduction steps

run command amplify init
run command amplify import auth
run command amplify add analytics

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Project Identifier

Project identifier: 2cca28720ab91624ef72f6d7667b5619

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ykethan** [comment] 2022-08-18 17:31
Hey @MiguelFERREIRA-1, Thank you for reporting. I was able to replicate the error by adding a imported auth resource then adding a analytics resource fails. marking this as bug. 

As a workaround we can utilize amplify cognito resource by running `amplify add auth` then add the analytics by running `amplify add analytics`

**Comment by lazpavel** [comment] 2023-03-03 18:00
Hi @MiguelFERREIRA-1, the error you're getting is caused by the fact that analytics resource requires the auth resource to allow unauthenticated users, since this is an imported resource it cannot be modified by Amplify CLI.

You can work around it by changing the configuration of the imported auth resource in the Cognito console, or creating a new auth resource through CLI as mentioned by @ykethan

**Closed by lazpavel** 2023-03-03 18:00 UTC
Labels: bug, auth, analytics, p2
