### ISSUE TITLE
Amplify CLI v8.0.0 breaks CI/CD pipeline for amplify publish

### ISSUE THREAD

**Issue by renegoretzka** [aws-amplify/amplify-cli#10164] opened 2022-04-08 17:56 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

8.0.0

### What operating system are you using?

CodeBuild Docker image

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No changes were made to cloud resources.

### Amplify Categories

hosting

### Amplify Commands

publish

### Describe the bug

During Amplify's CI/CD its trying to use the `amplify publish` command, which should build and publish to cloudfront.
It is getting stuck by a prompt (`Do you still want to publish the frontend? (Y/n)`) during ci/cd for the frontend build phase until timeout, which was not the case in cli version 7.x.x.

It's need to apply two flags now: -y and --force to actually get the build process working again.

It was very hard to investigate, as it also swallows the actual prompt in the logs.

### Expected behavior

Just publish in the ci/cd pipeline without adding flags to the `amplify publish` command like in the previous version.

### Reproduction steps

1. Redeploy hosting environment

### GraphQL schema(s)

n/a

### Log output

<details>

```
                                    + amplify publish -c
2022-04-08T16:52:19.440Z [WARNING]: - Fetching updates to backend environment: dev from the cloud.

```

</details>

### Additional information

Change the `amplify.yml` file which adds the flags -y and --force, so the final command would be `amplify publish -y --force`.

This will break a lot of applications as they deploy with ci/cd and hosting on cloudfront.

Needs urgent fix!

**Comment by Straubulous** [comment] 2022-04-09 19:54
Thank you for reporting @renegoretzka. We're investigating. Also, thank you for mentioning the work around to use  'amplify publish -y --force`

**Comment by johnpc** [comment] 2022-04-11 18:00
The `-y` flag is necessary to bypass this prompt when running `amplify publish` while there are no resource changes. This is not due to v8.0.0. I believe it is a coincidence in your case `amplify publish` was executed for the first time with no changes at the same time v8.0.0 came out.

If _both_ `-y` and `--force` are required, that is not expected as I would hope `-y` would be enough in this case. Have you confirmed both flags are required?

**Comment by renegoretzka** [comment] 2022-06-30 08:31
Hey,

we are still facing the same issue.
We are using our own CloudFront Distribution (on the CLI for hosting we have chosen Amazon CloudFront and S3), so we need to execute `amplify publish` during CodeBuild in the frontend. We want to invalidate our cache, so we need to pass -c as well, but during CodeBuild there is prompt which we wanted to confirm using the -y flag.

So the total command `amplify publish -c -y` is still not working. We are still forced to use `amplify publish -c -y --force` to pass the prompt. But we don't want to do so, because that is going to rebuild our complete backend as well, which was already build during CI/CD.

We are using the latest version (9.0.0) of the CLI during the frontend build, which should already have the PR of John deployed. https://github.com/aws-amplify/amplify-cli/pull/10217

The behaviour did not change at all, so my first comment still persists.

Thank you!
René

**Comment by olivierpichon** [comment] 2022-06-30 10:13
@josefaidt please see this comment: https://github.com/aws-amplify/amplify-cli/issues/10164#issuecomment-1170926359 the issue is still happening unfortunately. Thx a lot!

**Comment by josefaidt** [comment] 2022-06-30 16:43
Hey @renegoretzka and @olivierpichon thank you for the callout! I've reopened this and marked as a regression

**Comment by akshbhu** [comment] 2022-08-24 10:44
Closing in favour of #10774

**Closed by akshbhu** 2022-08-24 10:44 UTC
Labels: bug, platform, p1, regression
