### ISSUE TITLE
ExpressJS Lambda that Amplify CLI creates uses deprecated aws-serverless-express package

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#12657] opened 2023-05-18 22:10 UTC
### Describe the feature you'd like to request

When you add a new REST API with a new Lambda via `amplify add api`, the resulting template code in the new Lambda uses `"aws-serverless-express": "^3.3.5"`, but per https://www.npmjs.com/package/aws-serverless-express, this is a deprecated package to be replaced by https://www.npmjs.com/package/@vendia/serverless-express

### Describe the solution you'd like

Generated code should use the latest supported @vendia/serverless-express package instead of the deprecated aws-serverless-express. 

### Describe alternatives you've considered

Do the upgrade myself, or keep using the deprecated package. 

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment] 2023-05-19 18:37
Hey @hisham :wave: thanks for raising this! I previously marked this as a bug but upon further investigation this appears to be a duplicate of https://github.com/aws-amplify/amplify-cli/issues/10812. I'll close this issue in favor of tracking the existing item and pivot the type to a bug

**Closed by josefaidt** 2023-05-19 18:37 UTC
Labels: bug, functions
