### ISSUE TITLE
.gitignore not created

### ISSUE THREAD

**Issue by alexladerman** [aws-amplify/amplify-cli#3342] opened 2020-02-05 13:40 UTC
I run `amplify init` but no `.gitignore` file is created nor does it append to an existing file if present.

**Comment by UnleashedMind** [comment] 2020-02-05 18:50
@alexladerman 
What Amplify CLI version are you using? and what is your dev box's operating system? 
Did you allow the `amplify init` command to execute to its completion?

**Comment by alexladerman** [comment] 2020-02-07 12:07
@UnleashedMind 4.11

**Comment by kaustavghosh06** [comment] 2020-02-10 05:49
@alexladerman Which OS are you on?

**Comment by alexladerman** [comment] 2020-02-10 08:06
MacOS 10.15.1

**Comment by UnleashedMind** [comment] 2020-02-13 18:57
Did you allow the amplify init command to execute to its completion?
We are not able to reproduce the issue.

**Comment by kaustavghosh06** [comment] 2020-02-17 21:58
Closing this issue due to lack of requested information. Please respond to this issue if you're still stuck.

**Closed by kaustavghosh06** 2020-02-17 21:58 UTC
Labels: not-reproducable, pending-response, pending-triage, platform
