### ISSUE TITLE
Unable to convert \n\n\n\n\n\n\\n\n\n\n{} to Object.

### ISSUE THREAD

**Issue by jk171505** [aws-amplify/amplify-cli#9206] opened 2021-12-03 18:05 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### Amplify CLI Version

7.6.2

### What operating system are you using?

mac

### Amplify Categories

auth, storage, function, api

### Amplify Commands

Not applicable

### Describe the bug

I made 2 changes to the schema after it was published:
1. removed `@hasone` relationship from 2 fields
2. changed the default owner field to some other `username`

`amplify push` works fine, but looks like graphQL api is broken because any query or mutation returns the following error:
```
{
  "data": {
    "listInvestmentTransactions": null
  },
  "errors": [
    {
      "path": [
        "listInvestmentTransactions"
      ],
      "data": null,
      "errorType": "MappingTemplate",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Unable to convert \n\n\n\n\n\n\\n\n\n\n{} to Object."
    }
  ]
}
```

I 

### Expected behavior

graphQL api working properly.

### Reproduction steps

So far the only way to fix this is to de-deploy the app using amplify console (I did setup the CI/CD in a branch before that critical change).
I can then `amplify pull` to get the previously working state, make some changes outside of the schema, push back and and everything works fine. But once I touch the schema i.e. by adding some dummy field like:
```
type Observed @model @auth(rules: [
  { allow: owner },
  { allow: private, provider: iam }
]) {
  ...
  aaa: String
}
```
the graphQL api breaks again...

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Investment @model @auth(rules: [
  { allow: groups, groups: ["Admin"] },
  { allow: groups, groups: ["investor"], operations: [read] },
  { allow: private, provider: iam }
]) {
  id: ID!
  status: String! @index(name: "investmentsByStatus", queryField: "investmentsByStatus")
  name: String
  price: Int!
  fundraisingStartDate: AWSDateTime!
  fundraisingEndDate: AWSDateTime!
  projectEndDate: AWSDateTime!
  description: String
  generalInfo: String
  additionalInfo: String
  businessPlan: AWSJSON!
  portfolio: Boolean
}

type InvestmentTransactions @model @auth(rules: [
  { allow: owner, ownerField: "username", operations: [read, update] },
  { allow: groups, groups: ["investorPlus"], operations: [create, read] },
  { allow: groups, groups: ["Admin"] },
  { allow: private, provider: iam }
]) {
  id: ID! @auth(rules: [
  { allow: owner, ownerField: "username", operations: [read, update] },
  { allow: groups, groups: ["investorPlus"], operations: [create, read] },
  { allow: groups, groups: ["Admin"] },
  { allow: private, provider: iam }
])
  amount: Float! @auth(rules: [
  { allow: owner, ownerField: "username", operations: [read, update] },
  { allow: groups, groups: ["investorPlus"], operations: [create, read] },
  { allow: groups, groups: ["Admin"] },
  { allow: private, provider: iam }
])
  investmentID: ID! @index(name: "transactionsByInvestment", queryField: "transactionsByInvestment") @auth(rules: [
  { allow: owner, ownerField: "username", operations: [read, update] },
  { allow: groups, groups: ["investorPlus"], operations: [create, read] },
  { allow: groups, groups: ["Admin"] },
  { allow: private, provider: iam }
])
  investorID: ID! @index(name: "transactionsByInvestor", queryField: "transactionsByInvestor") @auth(rules: [
  { allow: owner, ownerField: "username", operations: [read, update] },
  { allow: groups, groups: ["investorPlus"], operations: [create, read] },
  { allow: groups, groups: ["Admin"] },
  { allow: private, provider: iam }
])
  transactionDate: AWSDateTime! @index(name: "transactionByTransactionDate", queryField: "transactionByTransactionDate") @auth(rules: [
  { allow: owner, ownerField: "username", operations: [read, update] },
  { allow: groups, groups: ["investorPlus"], operations: [create, read] },
  { allow: groups, groups: ["Admin"] },
  { allow: private, provider: iam }
])
  ***Name: String
  ***Name: String
  ***Name: String
  ***Name: String
  ***OK: Boolean @auth(rules: [
    { allow: groups, groups: ["Admin"] },
    { allow: groups, groups: ["investorPlus"], operations: [read] },
    { allow: private, provider: iam }
  ])
  ***OK: Boolean @auth(rules: [
    { allow: groups, groups: ["Admin"] },
    { allow: groups, groups: ["investorPlus"], operations: [read] },
    { allow: private, provider: iam }
  ])
  ***OK: Boolean @auth(rules: [
    { allow: groups, groups: ["Admin"] },
    { allow: groups, groups: ["investorPlus"], operations: [read] },
    { allow: private, provider: iam }
  ])
  ***OK: Boolean @auth(rules: [
    { allow: groups, groups: ["Admin"] },
    { allow: groups, groups: ["investorPlus"], operations: [read] },
    { allow: private, provider: iam }
  ])
  cancelled: Boolean
  portfolio: Boolean @auth(rules: [{ allow: groups, groups: ["Admin"] }])
  investment: Investment @hasOne(fields: ["investmentID"]) // < ---------------------- removed this relationship
  investor: Investor @hasOne(fields: ["investorID"]) // < ---------------------------- removed this relationship
}

type Investor @model @auth(rules: [
  { allow: owner, ownerField: "username", operations: [create, read, update] },
  { allow: private, provider: iam },
  { allow: groups, groups: ["Admin"] }
]) {
  id: ID!
  firstName: String
  lastName: String
  address: String
  investorID: String! @index(name: "investorByInvestorID", queryField: "getInvestorByInvestorID")
  identityID: String!
  deviceTokens: [String]
  deactivated: Boolean
}

type Observed @model @auth(rules: [
  { allow: owner }, // < ------------------------------ changed default ownder field to ownerField: "username"
  { allow: private, provider: iam }
]) {
  id: ID!
  investorID: ID! @index(name: "observedByInvestor", queryField: "observedByInvestor")
  investmentID: ID! @index(name: "byInvestment", queryField: "observedByInvestment")
  investment: Investment @hasOne(fields: ["investmentID"])
  investor: Investor @hasOne(fields: ["investorID"])
  aaa: String
}

```

</details>

### Log output

<details>

```
# Put your logs below this line
https://d.pr/f/2lHvRz/FWIjOTqZr7

```

</details>

**Comment by cjihrig** [comment] 2021-12-06 18:15
@jk171505 would you be willing to share your project with us via email: amplify-cli@amazon.com

**Comment by jk171505** [comment] 2021-12-06 18:28
@cjihrig do you need access to aws? what's the best/easiest way to share it?

**Comment by cjihrig** [comment] 2021-12-06 18:34
Can you email your project to amplify-cli@amazon.com? We don't need to access your AWS account.

**Comment by jk171505** [comment] 2021-12-06 19:22
@cjihrig shared.

**Comment by cjihrig** [comment] 2021-12-06 20:08
@jk171505 after you make any schema changes and push the API you mentioned that you're running into problems. I noticed that your app was migrated from v1 to v2.

One difference between v1 and v2 is that pluralization is handled differently. You should have received a message about this during migration. I searched your project for "listInvestmentTransactions" and found a number of matches for "listInvestmentTransactionss" (notice the extra "s" on the end). Can you try updating those occurrences to see if it makes a difference.

**Comment by cjihrig** [comment] 2021-12-06 20:52
> everything worked properly till the moment I removed @hasone relationships from InvestmentTransactions model.

Just to confirm, after you ran the v1 to v2 migration (before you removed any relationships), you pushed the v2 project and it worked? If so, if you temporarily add the `@hasOne` relationships back and push again, does it work again?

You could also try testing the API directly in the AppSync console, but you may run into some issues trying to do that with all of the auth in place in the schema.

> How can I fix it now?

Can you try adding the following feature flag to your project's `cli.json` file. It should be added in the `graphqltransformer` section of that file. Once you do that, try generating the client code again.

```
"improvepluralization": true
```

> All of the pluralization issues are either in api/build or src/graphql dir

I see another in `amplify/backend/function/...DDBTransactionTrigger/`

**Comment by jk171505** [comment] 2021-12-06 21:24
> > everything worked properly till the moment I removed @hasone relationships from InvestmentTransactions model.
> 
> Just to confirm, after you ran the v1 to v2 migration (before you removed any relationships), you pushed the v2 project and it worked? If so, if you temporarily add the `@hasOne` relationships back and push again, does it work again?
I tried this - it doesn't work. But if I re-deploy the app in Amplify console it works.

> You could also try testing the API directly in the AppSync console, but you may run into some issues trying to do that with all of the auth in place in the schema.
I did exactly this.
Logged in as an authenticated cognito user that belongs to the user group. It works if I re-deploy the app from Amplify console - in the web app as well as in the AppSync console.
At that point I pull (amplify), make any change in schema.graphql locally, then push - no errors in terminal, looks like push worked. So I try to test if it really works - at this point the bug shows up again - either in the app (web app uses DataStore) or in AppSync console/ The same bug: "Unable to convert \n\n\n\n..."

> 
> > How can I fix it now?
> 
> Can you try adding the following feature flag to your project's `cli.json` file. It should be added in the `graphqltransformer` section of that file. Once you do that, try generating the client code again.
> 
> ```
> "improvepluralization": true
> ```
> 
> > All of the pluralization issues are either in api/build or src/graphql dir
> 
> I see another in `amplify/backend/function/...DDBTransactionTrigger/`
I set the flag and compiled the code and generated using `codegen`, but `listInvestmentTransactionss` is still generated in `schema.json` (inside `backend` dir) and  in `cloudformation-template.json` inside of `awscloudformation/build` directory.
- how to fix it?

**Comment by jk171505** [comment] 2021-12-07 16:42
@cjihrig I created a fresh env today, migrated to v2 and pushed. Then created CI/CD in amplify app and deployed for the first time. Everything worked fine - in AppSync console as well as in the webapp.

The following changes did break the app (the same error):
1. Update of the auth rule in one of the models:
```
type InvestmentTransactions @model @auth(rules: [
  { allow: owner, ownerField: "username", operations: [update] }
  ...
]) {
```
to
```
type InvestmentTransactions @model @auth(rules: [
  { allow: owner, ownerField: "username", operations: [create, read, update] }
  ...
]) {
```
2. compile: `amplify api gql-compile `
3. `amplify push`

I shared the project with created in env via email.

**Comment by cjihrig** [comment] 2021-12-07 17:00
Thank you. I'm looking into your most recent project.

**Comment by cjihrig** [comment] 2021-12-07 21:06
@jk171505 I'm trying to reduce this down a bit since this schema has a lot going on. It seems like it could be an issue with `@auth`, but I'm not sure yet. If you remove all of the models except `InvestmentTransactions` (you'd have to remove the `@hasOne` relationships as well), does that reproduce the issue? If that still reproduces the issue, can you try removing the `@index` directives. If that still reproduces the issue, try removing the field auth, etc.

**Comment by jk171505** [comment] 2021-12-07 21:22
@cjihrig where you able to run this project/ reproduce this bug?

I tried to play with this a bit and removed all field level auth rules from this model but kept model level ones.
Unfortunately during the push I got error saying "Cannot perform more than one GSI creation or deletion in a single update; ConnectionStack failed to update". I tried to revert it, but then started to see this bug:

https://github.com/aws-amplify/amplify-cli/issues/9248

I'm blocked at the moment because of this...

**Comment by jk171505** [comment] 2021-12-09 08:19
@cjihrig I tried what you suggested, but the problem remains.


> If you remove all of the models except `InvestmentTransactions` (you'd have to remove the `@hasOne` relationships as well), does that reproduce the issue? 

yes

> If that still reproduces the issue, can you try removing the `@index` directives.

the same error

> If that still reproduces the issue, try removing the field auth, etc.
removed all field level auth rules, on the model level left `public` access

the same error

After removal last auth rule (model level) I get the warning:
```
⚠️  WARNING: Some types do not have authorization rules configured. That means all create, read, update, and delete operations are denied on these types
```

**Comment by jk171505** [comment] 2021-12-09 17:57
Hi, is there an ETA on this bug?

**Comment by marcvberg** [comment] 2021-12-09 18:32
Hi @jk171505, I've picked this up and I'm looking at it now and will get back to you later today

**Comment by marcvberg** [comment] 2021-12-09 22:05
Was unable to reproduce this today, tomorrow I'm going to try some new strategies to see what I can find.

Do you have your original V1 schema that was migrated? I'm wondering if reproducing this error would be easier if I come from that direction

**Comment by jk171505** [comment] 2021-12-10 09:07
Yes. Shared via email (amplify-cli@amazon.com).

**Comment by jk171505** [comment] 2021-12-10 20:42
Ok, this is strange. Any change in schema pushed via amplify push, despite it is successful, breaks the app (error mentioned at the beginning). A commit of these changes in this branch (which will trigger automatic deployment) and push via git fixes the problem.

The code that I shared recently via email was pushed to aws, then amplify app was set up with CI/CD which triggered initial deployment. So far so good, everything works.
Then local migration to v2, modified auth rules on the model level and added some field level then pushed via amplify, which causes mentioned error.
A commit and push of these changes (via git) —> automatic deployment —> problem disappears.
Repeated the steps above:
ANY change in schema pushed via amplify breaks the app. A commit and push of these changes via git which triggers automatic deploy solves the problem…

**Comment by jk171505** [comment] 2021-12-14 15:59
Any updates on this?

**Comment by jk171505** [comment] 2021-12-27 23:27
Any updates on this?

**Comment by marcvberg** [comment] 2022-01-03 14:54
Sorry about the delay, I believe something is wrong with one or multiple of your resolvers, not necessarily wrong with the state of amplify. I'm going to look at it some more today but I'll be looking at it from a different angle

**Comment by marcvberg** [comment] 2022-01-05 17:37
I used the resolvers you sent in to try and reproduce the issue but still was not able to recreate this error, at this point we haven't been able to reproduce it so we will close this issue if there's no additional information we can use

**Closed** 2022-01-19 20:51 UTC
Labels: graphql-transformer, pending-close-response-required, not-reproducible

**Comment by jk171505** [comment] 2022-02-07 09:12
@marcvberg I have this problem in new project.

**Comment by owenr88** [comment] 2022-02-13 19:17
Hey!

I also have this issue running GraphQL requests on a generated API. Every request is returning the same: 

```
{
  "data": {
    "listThings": null
  },
  "errors": [
    {
      "message": "Unable to convert \n\n\n\n\n\n\\n\n\n\n{} to class com.amazonaws.deepdish.transform.model.lambda.LambdaVersionedConfig.",
      "errorType": "MappingTemplate",
      "data": null,
      "errorInfo": null,
      "path": [
        "listThings"
      ],
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": "GraphQL request"
        }
      ]
    }
  ]
}
```

I have tried:
 
1. Use only one Graphql Type with @model (just an ID field on it)
1. Removing all @auth rules from the type
1. Edited every .req and .res template to just be `$util.toJson({})`

The only thing that fixes it for me is deploying the app via Github to Amplify. The production endpoint and queries all work perfectly. So strange!

Anything else I can try to help you debug @marcvberg ?

Currently running Amplify `v7.6.19`.

**Comment by owenr88** [comment] 2022-02-15 22:33
Got it! There's an unnecessary `\n` [here](https://github.com/aws-amplify/amplify-cli/blob/4cf6274d03a8f53e53c9a3119f08d390783c92fa/packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts#L269) that's causing the template render to fail.

Submitting a PR now.
