### ISSUE TITLE
auth cognito trigger conflict with email verification settings

### ISSUE THREAD

**Issue by pha6d** [aws-amplify/amplify-cli#7659] opened 2021-07-04 09:28 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v14.16.1

### Amplify CLI Version

5.1.0

### What operating system are you using?

Debian

### Amplify Categories

auth, function, api

### Amplify Commands

add

### Describe the bug

I'm adding cognito auth with email verification and a postconfirmation lambda trigger.
cognito auth is currently managed within 2 cloudformations, first one defining userpool, second one updating it to add lambda triggers.

Probleme is cognito updateUserpool API in use within "trigger cloudformation" expects to receive the whole auth conf, where today it receives only "updated" parts .. the triggers.
Adding a lambda trigger today leads a to resetting cognito userpool to default values, meaning for instance disabling email verification.

### Expected behavior

Adding lambda triggers should not reset userpool to default settings.

### Reproduction steps

**amplify init** # using default settings

**amplify add api**
? Please select from one of the below mentioned services: GraphQL
? Provide API name: upgraded
? Choose the default authorization type for the API Amazon Cognito User Pool
Using service: Cognito, provided by: awscloudformation

 The current configured provider is Amazon Cognito.

 Do you want to use the default authentication and security configuration? Manual configuration
 Select the authentication/authorization services that you want to use: User Sign-Up & Sign-In only (Best used with a cloud API only)
 Please provide a friendly name for your resource that will be used to label this category in the project: upgraded7c95c7307c95c730
 Please provide a name for your user pool: upgraded7c95c730_userpool_7c95c730
 Warning: you will not be able to edit these selections.
 How do you want users to be able to sign in? Username
 Do you want to add User Pool Groups? No
 Do you want to add an admin queries API? No
 Multifactor authentication (MFA) user login options: OFF
 Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
 Please specify an email verification subject: Your verification code
 Please specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? No
 Warning: you will not be able to edit these selections.
 What attributes are required for signing up? Email
 Specify the app's refresh token expiration period (in days): 30
 Do you want to specify the user attributes this app can read and write? No
 Do you want to enable any of the following capabilities?
 Do you want to use an OAuth flow? No
? Do you want to configure Lambda Triggers for Cognito? Yes
? Which triggers do you want to enable for Cognito Post Confirmation
? What functionality do you want to use for Post Confirmation Create your own module
Successfully added resource upgraded7c95c7307c95c730PostConfirmation locally.

**amplify push**

# At this step I expect to have both "email verification enabled" and "PostConfirmation" trigger set

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

Assuming we want to keep the split of cloudformations, then the "trigger" one could:
- reuse all parameters given during auth creation to userpool is set as intended 
OR
- starts by describing current userpool state and reinject current state + triggers 

Additionnally the current split in 2 cloudformations complexify update scenarios... currently we have a "choice" between "verifications" and "triggers"

**Comment by pha6d** [comment] 2021-07-09 08:58
#7659

**Comment by cjihrig** [comment] 2021-07-09 18:52
Thanks @pha6d. I'll close this as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/7666.

**Closed by cjihrig** 2021-07-09 18:52 UTC
