### ISSUE TITLE
[Feedback] error when using headless init

### ISSUE THREAD

**Issue by cyrfer** [aws-amplify/amplify-cli#5545] opened 2020-09-25 17:12 UTC
**Page**: [`/cli/usage/headless`](https://docs.amplify.aws/cli/usage/headless)

**Feedback**:

I get this feedback in the CLI after attempting to use the headless init described on this page.

```bash
Note: It is recommended to run this command from the root of your app directory

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

⠧ Initializing your environment: dev(node:89636) UnhandledPromiseRejectionWarning: Error: connect EPERM 52.218.204.177:443 - Local (0.0.0.0:0)
    at internalConnect (net.js:921:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:296:12)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1063:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:10)
(node:89636) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:89636) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠋ Initializing your environment: dev
```

The last line shows a spinner infinitely.
`Initializing your environment: dev`

Here is my script to initialize amplify.
```bash
#!/bin/bash
set -e
IFS='|'

# required
AMPAPPID="${1}"

# dev,qa,prod
AMPENV="${2:-dev}"

# Headless Init resources:
# https://docs.amplify.aws/cli/usage/headless

AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":false,\
\"profileName\":\"default\",\
\"accessKeyId\":\"$AWS_ACCESS_KEY_ID\",\
\"secretAccessKey\":\"$AWS_SECRET_ACCESS_KEY\",\
\"region\":\"$AWS_REGION\"\
}"

AMPLIFY="{\
\"appId\":\"$AMPAPPID\",
\"projectName\":\"l12n\",\
\"envName\":\"$AMPENV\",\
\"defaultEditor\":\"code\"\
}"

REACTCONFIG="{\
\"SourceDir\":\"src\",\
\"DistributionDir\":\"build\",\
\"BuildCommand\":\"npm run-script build\",\
\"StartCommand\":\"npm run-script start\"\
}"

FRONTEND="{\
\"frontend\":\"javascript\",\
\"framework\":\"react\",\
\"config\":$REACTCONFIG\
}"

PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"

amplify init \
--amplify $AMPLIFY \
--frontend $FRONTEND \
--providers $PROVIDERS \
--yes
```

My goal is to run the script above on a Jenkins server. For now, I invoke the script above on my local terminal like this, from `package.json`

```json
  "scripts": {
    "server": "amplify mock",
    "amplify-init-dev": "AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id) AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key) AWS_REGION=$(aws configure get region) ./amplify-init-cicd.sh OMITTED dev",
    "amplify-init-qa": "AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id) AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key) AWS_REGION=$(aws configure get region) ./amplify-init-cicd.sh OMITTED qa",
    "amplify-init-prod": "AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id) AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key) AWS_REGION=$(aws configure get region) ./amplify-init-cicd.sh OMITTED prod",
  }
```

**Comment by ammarkarachi** [comment] 2020-10-09 23:06
@cyrfer What OS, Amplify Version and Node Version are you using?

**Comment by UnleashedMind** [comment] 2020-10-26 17:00
closing the issue for lack of response. 
feel free to open another issue if you are still blocked.

**Comment by cyrfer** [comment] 2020-10-30 01:42
@UnleashedMind @ammarkarachi please reopen. I’m on OS X high Sierra. Node 12. All recent Amplify versions.

**Comment by rajrajhans** [comment] 2021-03-07 21:11
Hey @cyrfer, I tried to reproduce this on Amplify CLI version 4.43.0. I used the same script you provided and the script was executed and it initialized the project without any errors. Could you confirm if you are still facing this issue?

I further searched for the error you mentioned, and it looks like a similar issue - ([1](https://forums.aws.amazon.com/thread.jspa?threadID=299018), [2](https://github.com/aws/aws-sdk-js/issues/3284#issuecomment-762505952)) is known with `aws-sdk-js` that occurs when running the code in an environment that doesn't have profiles configured.

**Comment by cyrfer** [comment] 2021-03-07 21:25
I think the issue was my local environment. I have not attempted this since the initial post. However, many other errors stopped happening when I upgraded my local to newer than node 12. I might revisit this soon.

**Comment by ammarkarachi** [comment] 2021-03-08 17:34
@cyrfer Thanks for the update will close this for now

**Closed by ammarkarachi** 2021-03-08 17:34 UTC
Labels: init, pending-triage, platform
