### ISSUE TITLE
Unable to pull after mobilehub resource migration

### ISSUE THREAD

**Issue by Sam31000** [aws-amplify/amplify-cli#7439] opened 2021-06-02 07:49 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v10.15.3

### Amplify CLI Version

4.52.0

### What operating system are you using?

Mac OS

### Amplify Categories

Not applicable

### Amplify Commands

pull

### Describe the bug

After migrating resources from mobilehub projet to my amplify project I can find all resources on AWS console but I can't pull my project locally to work on my backend.

When I pull my project I got  the error below : 
`amplify pull`
✔ Successfully pulled backend environment staging from the cloud.
✖ There was an error initializing your environment.
Cannot destructure property `provider` of 'undefined' or 'null'.
TypeError: Cannot destructure property `provider` of 'undefined' or 'null'.
    at updateConfigOnEnvInit (/Users/Sam/.nvm/versions/node/v10.15.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/src/provider-utils/awscloudformation/index.js:66:24)
    at /Users/Sam/.nvm/versions/node/v10.15.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/src/index.js:150:28
    at /Users/Sam/.nvm/versions/node/v10.15.3/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
    at process._tickCallback (internal/process/next_tick.js:68:7)

### Expected behavior

I expect to retrieve my backend (lambda functions) locally to work on it.

### Reproduction steps

- Init an amplify project
- Migrate resource from mobilehub projet using https://github.com/awslabs/amplify-mobilehub-migrator
- amplify pull

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
⠋ Fetching updates to backend environment: staging from the cloud.(node:63378) ExperimentalWarning: The fs.promises API is experimental
✔ Successfully pulled backend environment staging from the cloud.
✖ There was an error initializing your environment.
Cannot destructure property `provider` of 'undefined' or 'null'.
TypeError: Cannot destructure property `provider` of 'undefined' or 'null'.
    at updateConfigOnEnvInit (/Users/Sam/.nvm/versions/node/v10.15.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/src/provider-utils/awscloudformation/index.js:66:24)
    at /Users/Sam/.nvm/versions/node/v10.15.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/src/index.js:150:28
    at /Users/Sam/.nvm/versions/node/v10.15.3/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

</details>

**Comment by yuth** [comment] 2021-06-02 20:55
@Sam31000 this is by design. The migrator is to allow you to use resources already created using MobileHub in a Amplify project. You cannot use Amplify CLI to update these resources or any of the multi env related workflow on imported resources.

**Comment by Sam31000** [comment] 2021-06-03 07:41
@yuth Thank you for your answer.

If you can't manage your mobilehub ressources with amplify after a migration what is the aim of the migration ? And how to continue your development if you have a mobilehub project ?

Do you have some best practices to share ?

**Comment by yuth** [comment] 2021-06-04 21:46
@Sam31000 I misspoke. There should not be an error when doing `amplify pull`. Since this is a plugin for Amplify CLI and has a separate repo could you open an issue here https://github.com/awslabs/amplify-mobilehub-migrator

**Comment by Sam31000** [comment] 2021-06-07 08:41
@yuth , I already opened an issue here : https://github.com/awslabs/amplify-mobilehub-migrator/issues/82

But it seems that there is not many people working on this projet.

**Comment by yuth** [comment] 2021-06-07 17:18
thank you. I will inform the people working on that to triage the issue

**Comment by attilah** [comment] 2021-06-11 21:39
Reopening as it is a CLI issue

**Comment by 0xR** [comment] 2021-09-11 18:44
I have the same issue, running amplify 5.5.0

Without amplify pull working the amplify-mobilehub-migrator doesn't seem to do much. I have an empty amplify project.

**Comment by sachscode** [comment] 2022-01-28 19:40
closing this issue, since mobile-hub is no longer supported in AWS.

**Closed by sachscode** 2022-01-28 19:40 UTC
Labels: bug, storage
