### ISSUE TITLE
EventInvokeConfig permissions issue

### ISSUE THREAD

**Issue by charlesfayal** [aws-amplify/amplify-cli#10395] opened 2022-05-05 00:48 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Not applicable

### Amplify Categories

function

### Environment information

<details>

```
# Put output below this line
Standard amplify backend lambda function 
```

</details>

### Describe the bug

If you add EventInvokeConfig to publish to an SNS topic and you add permission in the lambdaexecutionpolicy to publish on SNS it will fail with the error that it needs permissions to invoke SNS. 

### Expected behavior

It creates the permissions first then the EventInvokeConfig

### Reproduction steps

1) Create a Lambda function
2) add a resource for EventInvokeConfig that publishes to an SNS topic OnFailure
3) Try to push

Cloud formation fails

### Code Snippet

```javascript
// Put your code below this line.
    "EventInvokeConfig": {
      "Type": "AWS::Lambda::EventInvokeConfig",
      "Properties": {
        "DestinationConfig": {
          "OnFailure": {
            "Destination": "arn:aws:sns:us-east-1:XXXXXX:SNS_TOPIC"
          }
        },
        "Qualifier": "$LATEST",
        "FunctionName": {
          "Fn::If": [
            "ShouldNotCreateEnvResources",
            "FUNCTION_NAME",
            {
              "Fn::Join": [
                "",
                [
                  "FUNCTION_NAME",
                  "-",
                  {
                    "Ref": "env"
                  }
                ]
              ]
            }
          ]
        }
      }
    }
  },
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by josefaidt** [comment] 2022-05-11 21:44
Hey @charlesfayal :wave: are you adding this snippet to the function's CloudFormation template? If so, leveraging a [CDK custom resource](https://docs.amplify.aws/cli/custom/cdk/) would be a more suitable approach to persist changes across `amplify update function` executions.

As a follow-up, can you post the error message you're receiving when attempting to push?

**Comment by charlesfayal** [comment] 2022-05-17 19:47
Hey @josefaidt,
Thanks for the info. I'll checkout CDK Custom resource.

Error message

`CREATE_FAILED   amplify-heliumwebpage-charles-172737-functionheliumwebpagef5a7398cPreSignup-KG6DBXOYFKSP AWS::CloudFormation::Stack Tue May 17 2022 12:30:35 GMT-0700 (Pacific Daylight Time) The following resource(s) failed to create: [EventSourceMapping]. `

**Comment by charlesfayal** [comment] 2022-05-17 20:03
I'm a bit confused. I'm not trying to create the SNS topic, just have the lambda published to it OnFailure. I already have this SNS topic created manually in AWS. Is using the Custom Resource still the way to go?

**Comment by charlesfayal** [comment] 2022-05-19 16:11
Reason: User: arn:aws:sts::ID:assumed-role/us-east-1_ID_Full-access/amplifyadmin is not authorized to perform: lambda:PutFunctionEventInvokeConfig on resource: arn:aws:lambda:us-east-1:ID:function:functionname:$LATEST because no identity-based policy allows the lambda:PutFunctionEventInvokeConfig action (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: 81b31fc7-2781-4b25-9537-312a33ce8a46; Proxy: null)

Just found this error, looks like it's just that the role doesn't have permission to put the Event Invoke Config on. Is there a reason this isn't in the AdministratorAccess-Amplify?

**Comment by charlesfayal** [comment] 2022-05-19 16:15
Looks like in April UpdateEventSourceMapping was just added

**Comment by charlesfayal** [comment] 2022-05-19 16:55
Once I add permissions to lambda:PutFunctionEventInvokeConfig
I get passed that issue but get:

CREATE_FAILED      EventInvokeConfig   AWS::Lambda::EventInvokeConfig Thu May 19 2022 09:53:47 GMT-0700 (Pacific Daylight Time) The function doesn't exist. (Service: AWSLambdaInternal; Status Code: 404; Error Code: ResourceNotFoundException; Request ID: d21094f2-8b51-48cc-94ab-c8b350b71cdb; Proxy: null)

Again if I create these resource then later go on to add this Resource it works, so it looks like it's trying to add this Event Invoke config before creating the funciton

**Comment by josefaidt** [comment] 2022-05-19 21:24
Hey @charlesfayal I believe you are correct on that final point, which appears to be related to https://github.com/aws-amplify/amplify-cli/issues/10332

**Comment by josefaidt** [comment] 2022-05-23 18:53
Hey @charlesfayal are you still experiencing this issue? We should be able to workaround the CDK resource creation issue by first pushing the function, then pushing the custom CDK resource, however if you are able to workaround this issue we can close as a duplicate of #10332

**Comment by charlesfayal** [comment] 2022-05-24 22:55
Yup still having the issue. I have a work around where I can push the permissions first and then add the OnFailure connection, however, this is really frustrating because we'd need to do this every time we create a new backend env.

@josefaidt I am not using a custom CDK resource. The SNS queue that I am using was manually generated.

**Comment by josefaidt** [comment] 2022-05-25 18:44
Hey @charlesfayal how are the permissions being applied? If the SNS queue exists outside of the project we can likely leverage the `custom-policies.json` file to manually add permissions to the external resource, and then CDK for linking with onFailure

**Comment by charlesfayal** [comment] 2022-06-01 00:20
The permissions are applied to the function in the lambdaexecutionpolicy

`    "lambdaexecutionpolicy": {
      "DependsOn": [
        "LambdaExecutionRole"
      ],
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyName": "lambda-execution-policy",
        "Roles": [
          {
            "Ref": "LambdaExecutionRole"
          }
        ],
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "sns:Publish"
              ],
              "Resource": "*"
            },`

**Comment by josefaidt** [comment] 2022-06-06 17:36
Hey @charlesfayal apologies for the delay here. Can you try granting access through the `custom-policies.json` file and see if that mitigates the issue?

**Comment by josefaidt** [comment] 2022-06-17 19:04
Closing due to inactivity. @charlesfayal if you are still experiencing this issue please reply back and we can re-open to investigate further 🙂

**Closed by josefaidt** 2022-06-17 19:04 UTC
Labels: pending-close-response-required, pending-triage, transferred, ops-deploy
