### ISSUE TITLE
My non-scalar types doesn't show up in my CreateInputs

### ISSUE THREAD

**Issue by sprucify** [aws-amplify/amplify-cli#1419] opened 2019-05-08 14:52 UTC
I have the following table that has a custom scalar `ingredient`:

```
type Ingredient
  @model
{
  id: ID!
  amount: String
  name: String
  unit: String
}

type Recipe 
  @model
{
  id: ID!
  title: String
  key: String
  image: String
  numberOfPersons: Int
  courses: [String]
  time: String
  energy: String
  proteine: String
  carbohydrates: String
  fat: String
  saturatedFat: String
  fibers: String
  salt: String
  sugar: String
  recipeTypes: [String]
  specials: [String]
  containsProducts: [String]
  diet: [String]
  ingredients: [Ingredient] 
  preperation: [String]
  editDate: String
  menuSuggestion: String
}
```

But the `amplify codegen` doesn't create the input class with ingredient in it:

```
export type CreateRecipeInput = {
  id?: string | null;
  title?: string | null;
  key?: string | null;
  image?: string | null;
  numberOfPersons?: number | null;
  courses?: Array<string | null> | null;
  time?: string | null;
  energy?: string | null;
  proteine?: string | null;
  carbohydrates?: string | null;
  fat?: string | null;
  saturatedFat?: string | null;
  fibers?: string | null;
  salt?: string | null;
  sugar?: string | null;
  recipeTypes?: Array<string | null> | null;
  specials?: Array<string | null> | null;
  containsProducts?: Array<string | null> | null;
  diet?: Array<string | null> | null;
  preperation?: Array<string | null> | null;
  editDate?: string | null;
  menuSuggestion?: string | null;
};
```

When I solve this with @connections it will be unnecessary amount of extra queries

**Comment by UnleashedMind** [comment] 2019-05-13 18:55
Thanks @sprucify for the feedbacks. 
Could you provide these information so we can investigate this issue:
- Amplify CLI version you used
- Operating system of your computer

**Comment by kaustavghosh06** [comment] 2019-05-17 19:49
Closing it since this is a duplicate of #1480 
Please take a look at @mikeparisstuff comment/suggestion as to how you can model your schema to avoid this issue.

**Closed by kaustavghosh06** 2019-05-17 19:49 UTC
Labels: code-gen, pending-response, pending-triage
