### ISSUE TITLE
Adding analytics in amplify push to wrong region(us-west-2)

### ISSUE THREAD

**Issue by jonathan-sjkim** [aws-amplify/amplify-cli#7638] opened 2021-07-01 02:10 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm install

### Amplify CLI Version

v10.24.1

### What operating system are you using?

Ubuntu

### Amplify Categories

analytics

### Amplify Commands

add, push

### Describe the bug

Hello. 

I added pinpoint using ```amplify add analytics``` and ```amplify push``` commands in ```ap-northeast-2``` region.

However, the pinpoint is creates in ```us-west-2``` although I configured default region as ```ap-northeast-2```.

I checked ```pinpoint-cloudformation-template.json``` and every region mapping values are mapped to ```us-west-2``` as follow.
```
 "Mappings": {
      "RegionMapping": {
        "us-east-1": {
          "pinpointRegion": "us-east-1"
        },
        "us-east-2": {
          "pinpointRegion": "us-east-1"
        },
        "sa-east-1": {
          "pinpointRegion": "us-east-1"
        },
        "ca-central-1": {
          "pinpointRegion": "us-east-1"
        },
        "us-west-1": {
          "pinpointRegion": "us-west-2"
        },
        "us-west-2": {
          "pinpointRegion": "us-west-2"
        },
        "cn-north-1": {
          "pinpointRegion": "us-west-2"
        },
        "cn-northwest-1": {
          "pinpointRegion": "us-west-2"
        },
        "ap-south-1": {
          "pinpointRegion": "us-west-2"
        },
        "ap-northeast-3": {
          "pinpointRegion": "us-west-2"
        },
        "ap-northeast-2": {
          "pinpointRegion": "us-west-2"
        },
        "ap-southeast-1": {
          "pinpointRegion": "us-west-2"
        },
        "ap-southeast-2": {
          "pinpointRegion": "us-west-2"
        },
        "ap-northeast-1": {
          "pinpointRegion": "us-west-2"
        },
        "eu-central-1": {
          "pinpointRegion": "eu-central-1"
        },
        "eu-west-1": {
          "pinpointRegion": "eu-west-1"
        },
        "eu-west-2": {
          "pinpointRegion": "eu-west-1"
        },
        "eu-west-3": {
          "pinpointRegion": "eu-west-1"
        }
      }
    }
```

Why every region mapping is mapped to ```us-west-2```? I solved this problem with modifying mapped value but I want to know why this is mapped like this. Is there any plan or roadmap to fix this or There are some reason of this?

Thank you.

### Expected behavior

push analytics(pinpoint) to ap-northeast-2

### Reproduction steps

1. amplify add analytics
2. amplify push

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by edwardfoyle** [comment] 2021-07-01 17:47
Closing as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/1965

**Closed by edwardfoyle** 2021-07-01 17:47 UTC
Labels: region support
