### ISSUE TITLE
No option for 'noUpdateBackend' for amplify pull command

### ISSUE THREAD

**Issue by heyheman11** [aws-amplify/amplify-cli#7881] opened 2021-08-04 06:33 UTC
### Describe the feature you'd like to request

This is an issue that relates to re-using backends across apps. We have quite a few apps sharing a singular backend, and currently there is no way to pass an option the cli to demonstrate that you only want to pull the config necessary to re-use it and that you will not be modifying it. I understand a user can do it manually by running `amplify pull` but then they need to go through the entire Q and A, all for the one question that says `? Do you plan on modifying this backend? (Y/n)`.

### Describe the solution you'd like

An ability to pass through `noUpdateBackend` to `amplify pull`. This would look like:

 ```sh
amplify pull --amplify '{ projectName: '', appId: '', envName: '', defaultEditor: '', noUpdateBackend: 'true' }'
```

### Describe alternatives you've considered

I could not automate this script, or look into the aws cli

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by jhockett** [comment] 2021-08-04 18:19
Hi @heyheman11, thanks for pointing out this missing headless functionality and for checking the `I may be able to implement...` box! Let us know if you need some direction or help with anything.

Check out our [contributing guide](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md). It has a link to our community discord server which may be helpful.

Before a feature like this could get merged, we would need to do an API review on our side to decide on the precise flag that gets passed, but that should be straightforward.

**Comment by ChrisSargent** [comment] 2021-08-05 06:22
Looks like a duplicate of #5275

**Comment by jhockett** [comment] 2021-08-05 16:50
Thanks for pointing that out @ChrisSargent, @heyheman11 I'm going to close this issue in favor of #5275, but we still appreciate any community contributions for this issue!

**Closed by jhockett** 2021-08-05 16:50 UTC
Labels: feature-request, platform, headless
