### ISSUE TITLE
JSON Parser error in Amplify

### ISSUE THREAD

**Issue by gitbalaji** [aws-amplify/amplify-cli#6097] opened 2020-12-07 22:13 UTC
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Amplify gives JSON parser error when we deploy the code to new AWS account other than the one thats currently running by just changing deployment option.
**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
4.30.0
**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable
1) Create amplify project with REST API/LAMBDA, GRAPH QL, also has auth functionality.
2) Deploy it an AWS account with Git based deployment.
3) Deploy (amplify push) the app to another AWS account by choosing S3 and Cloudfront as hosting option.
**Expected behavior**
It is expected to deploy without any issues but got below error.

ERROR
--------
✖ An error occurred when pushing the resources to the cloud
Unexpected token u in JSON at position 0
An error occurred during the push operation: Unexpected token u in JSON at position 0

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu] Mac OS Catalina
 - Node Version. You can use `node -v` to check the node version on your system
v14.8.0

**Additional context**
The error is so cryptic that it does not say which JSON the issue occurred.

**Comment by attilah** [comment] 2020-12-07 23:58
@gitbalaji could you please provider more detailed repro steps on what options you chose during resource add, etc, that would make it easier to troubleshoot. Also try with the latest version of the CLI.

From the error message, in one of the JSON files you have "undefined" as content. Could you please send the filename to give an idea to us which files gets this value?

**Comment by amlcodes** [comment] 2020-12-08 01:01
so im on the latest cli an am running into this after creating an app and dev backend with the cli, and then added additional environments in the console, and then checked them out via cli - because apparently multienv is a touchy thing with the previous version. (4.37) now, with .38, I am getting this error when running amplify push - ```'jsonString' argument missing or empty
An error occurred during the push operation: 'jsonString' argument missing or empty```

**Comment by matansagee** [comment] 2020-12-08 12:28
It happens to me also when using other commands relates to `amplify api`

I added a print of the file name that is failing.

![image](https://user-images.githubusercontent.com/8274517/101483947-e1840c00-3926-11eb-9d75-a1718ad09e38.png)

**Comment by attilah** [comment] 2020-12-08 16:21
@matansagee could you please take a look at what is in the `amplify/.config/local-env-info.json` file when this operation fails?

**Comment by attilah** [comment] 2020-12-08 16:22
> so im on the latest cli an am running into this after creating an app and dev backend with the cli, and then added additional environments in the console, and then checked them out via cli - because apparently multienv is a touchy thing with the previous version. (4.37) now, with .38, I am getting this error when running amplify push - `'jsonString' argument missing or empty An error occurred during the push operation: 'jsonString' argument missing or empty`

Thanks I try to reproduce it based on these steps.

**Comment by matansagee** [comment] 2020-12-08 16:26
@attilah Hi! Sure.
![image](https://user-images.githubusercontent.com/8274517/101510658-32582c80-3948-11eb-9421-31e1a9e8d91c.png)

**Comment by attilah** [comment] 2020-12-08 16:52
@matansagee this seems to be intact. Let me try the repro steps from @amlcodes and if cannot repro it, I'll get back to you for more info, please don't delete this env if possible ;-)

**Comment by matansagee** [comment] 2020-12-08 16:58
@attilah Thank you! unfortunately, I can't delete this environment. Let me know if you need anything from me.

**Comment by matansagee** [comment] 2020-12-08 17:08
@attilah It happens also in my production env
![image](https://user-images.githubusercontent.com/8274517/101516847-00e25f80-394e-11eb-878f-4e33f8aef423.png)
![image](https://user-images.githubusercontent.com/8274517/101516872-08096d80-394e-11eb-883f-cd94feca69ea.png)
I did `amplify env pull --restore` and `amplify pull --restore`

**Comment by matansagee** [comment] 2020-12-08 18:31
Adding more information. 
It seems that this bug happens when I'm editing the schema.graphql file in `amplify/backend/api/api name/schema.graphql`

![image](https://user-images.githubusercontent.com/8274517/101525486-65ef8280-3959-11eb-8003-1e3bf8b59f74.png)

**Comment by amlcodes** [comment] 2020-12-08 19:33
i added multiauth and video (which created an api), as well as a couple of auth additions like captcha and adding to group.

**Comment by matansagee** [comment] 2020-12-09 03:48
Hi @attilah !

I was able to debug this issue more. It seems that this command failed while trying to validate the files from the `#`

Here some screenshots.

![image](https://user-images.githubusercontent.com/8274517/101574512-b93bf200-39a6-11eb-8f3a-a1b2666c5b47.png)
![image](https://user-images.githubusercontent.com/8274517/101574653-c527b400-39a6-11eb-9e86-a25440cc3faf.png)
![image](https://user-images.githubusercontent.com/8274517/101575262-f0aa9e80-39a6-11eb-9a5b-879da404a743.png)
![image](https://user-images.githubusercontent.com/8274517/101575462-0029e780-39a7-11eb-9695-7aa721ec3cee.png)
![image](https://user-images.githubusercontent.com/8274517/101576847-6282e800-39a7-11eb-9f7c-1d9adcc27e5c.png)


Should all the files that are in `amplify/backend/api/event/build` be also in `#current-cloud-backend/api/event/build`?

**Comment by attilah** [comment] 2020-12-09 03:56
@matansagee this is awesome, thanks for taking the time. The error happens in when the stacks are being parsed, could you locate which stack file the one that fails? I'd appreciate if you could send the content of the amplify directory to amplify-cli@amazon.com email address. Function sources are not needed but both backend and #current-cloud-backend directories are.

**Comment by matansagee** [comment] 2020-12-09 03:58
Sure. The file that fails is `cloudformation-template.json`. The loadDiffableProject try to read it and fails. 
I will send the amplify content right now. Thanks!

**Comment by matansagee** [comment] 2020-12-09 04:05
@attilah What you see in the console is a result of this console log
![image](https://user-images.githubusercontent.com/8274517/101583655-eb9b1e80-39a9-11eb-9201-7f2305348092.png)

**Comment by attilah** [comment] 2020-12-09 04:36
Ok based on your file snapshot I was able to reproduce both type of errors the `Unexpected token u in JSON at position 0` (before 4.38) and `'jsonString' argument missing or empty` (after 4.38).

This happens because the #current-cloud-backend folder does not have the `api/apiname/build/cloudformation-template.json` file. The problem is easy to fix, but it would be good to figure out how can you end up in a situation like that...

**Comment by PeteDuncanson** [comment] 2020-12-09 10:53
Also experiencing this today after upgrading to 4.38 yesterday. My work mate @JackPenney is having the error too.

Tried to cut and paste the missing cloudformation-template.json over to see if that will be a work around for now but still fails with the same error :(

![image](https://user-images.githubusercontent.com/1674590/101620664-baa00580-3a0c-11eb-9441-bedc1aa11f18.png)

**Comment by PeteDuncanson** [comment] 2020-12-09 13:24
Tried rolling back to v4.37.1 but still can't push as we get this error again (which is why we upgraded to fix) https://github.com/aws-amplify/amplify-cli/issues/4903#issuecomment-668375551

**Comment by atlesp** [comment] 2020-12-09 13:54
This is blocking my team from deploying to TEST, and thus I do not dare to deploy to PROD.

A patch so soon as possible would be nice, since it is not good to not be able to update our app.

**Comment by attilah** [comment] 2020-12-09 14:43
While I created the fix for this particular error the way how the project got into such state still to be determined. @PeteDuncanson @atlesp could you please tell me what was the last version of the CLI that made the last working PUSH operation when the API has changed and was successful? Did it happen from Amplify Console or from a developer machine? Thanks!

Could you also confirm that there is no `cloudformation-template.json` in `#current-cloud-backend/api/<api name>/build` and api/<apiname>/build` directory?

**Comment by PeteDuncanson** [comment] 2020-12-09 14:49
@attilah thanks for looking into this.

Last good push I made was yesterday on v4.37.1 from my developer machine.

Currently have v4.38 installed. I can confirm that when pushing I don't have the `cloudformation-template.json` file in my build folder. Infact the only thing I do have is a `parameters.json` file that is it.

I'm all for getting to the bottom of the cause so keep your queries coming and I'll answer as fast as I can. If you want to do a screen share or similar let me know.

**Comment by matansagee** [comment] 2020-12-09 16:44
Hi @PeteDuncanson! I was able to solve this issue with the assistance of @attilah .

What you should do is download the `#current-cloud-backend.zip` file from your S3 bucket. Add to this folder the `cloudformation-template.json` file you have under `#current-cloud-backend/api/<api name>/build`. Zip it again and upload it to S3 bucket.

After that the `amplify push` should work. Please let me know if that helped you.

**Comment by atlesp** [comment] 2020-12-09 17:01
Currently have v4.38.2 installed. I can confirm that when pushing I don't have the cloudformation-template.json file in my build folder. 

The error was created from the amplify console when a push failed. But I do not think that push contained any api changes. Since the build image pulls the latest version I guess it was running 4.38.0. It failed on Sunday.

I will try the suggested work around tomorrow.

**Comment by PeteDuncanson** [comment] 2020-12-09 17:04
Wonder if this could be related to this other issue I've been having with missing files/folders https://github.com/aws-amplify/amplify-cli/issues/6047

**Comment by attilah** [comment] 2020-12-09 17:58
@PeteDuncanson you want to hop on a call Today? I like to get to the bottom of it as well. Send an email to amplify-cli@amazon.com please and I drop you a chime link.

**Comment by attilah** [comment] 2020-12-09 17:59
> Currently have v4.38.2 installed. I can confirm that when pushing I don't have the cloudformation-template.json file in my build folder.
> 
> The error was created from the amplify console when a push failed. But I do not think that push contained any api changes. Since the build image pulls the latest version I guess it was running 4.38.0. It failed on Sunday.
> 
> I will try the suggested work around tomorrow.

Why was the push failed, how it ended up failing? what was the error?

**Comment by PeteDuncanson** [comment] 2020-12-09 18:01
@attilah on UK time here and got to go do family stuff, happy to jump on tomorrow or @JackPenney might be free to help out.

**Comment by attilah** [comment] 2020-12-09 19:26
> @attilah on UK time here and got to go do family stuff, happy to jump on tomorrow or @JackPenney might be free to help out.

@PeteDuncanson sure, enjoy family time! We can try later.

**Comment by atlesp** [comment] 2020-12-09 21:59
@attilah I have checked the logs now, and I not sure anymore. Sorry for late response but it is late in Norway too now :)

The first build failed on "Parameters: [unauthRoleName, authRoleName] do not exist in the template" but then template file was missing already based on the log:

`
2020-12-08T06:15:46.900Z [INFO]: [33mCould not read cloudformation template at path: /codebuild/output/src165213616/src/Catalog/amplify/backend/api/catalog/build/cloudformation-template.json[39m
`
.......
 
```
2020-12-08T06:16:03.664Z [INFO]: UPDATE_ROLLBACK_IN_PROGRESS amplify-catalog-test-94444 AWS::CloudFormation::Stack Tue Dec 08 2020 06:16:02 GMT+0000 (Coordinated Universal Time) The following resource(s) failed to update: [apicatalog].
                                 UPDATE_FAILED               apicatalog                 AWS::CloudFormation::Stack Tue Dec 08 2020 06:16:00 GMT+0000 (Coordinated Universal Time) Parameters: [unauthRoleName, authRoleName] do not exist in the template
                                 UPDATE_IN_PROGRESS          apicatalog                 AWS::CloudFormation::Stack Tue Dec 08 2020 06:16:00 GMT+0000 (Coordinated Universal Time)
2020-12-0.
```


The last success was built with cli version 4.37.1
`2020-12-06T20:49:01.169Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 1.12.0 to 4.37.1...`
The first failure was with same version:
`2020-12-07T16:21:16.566Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 1.12.0 to 4.37.1...`

**Comment by attilah** [comment] 2020-12-10 00:48
Thanks @matansagee for the troubleshooting, I was able to track down the bug and create the #6133 PR for it.

This issues happens in a rare constellation came with some recent changes. After we merge both PRs regarding this issue, the build pipelines could be unblocked, until then, developer machines can be used to do manual deployment.

The root cause is that Amplify Console CI/CD is doing a pull and a init+pull call during the Build step and pull now involves running code generation for DataStore enabled GraphQL APIs which causes the issue by creating the `build` folder and then normal push will not generate the required artifacts for deployment.

**Comment by atlesp** [comment] 2020-12-10 14:56
@matansagee thank you for describing the manual fix 👍 It made me finally be able to deploy the changes.

@attilah thanks for looking into this issue so quickly. 

How can I deploy the frontend from my developer machine? I have both frontend and backend in the same amplify console app, so they are built and deployed together from the Amplify Console.
When I try `amplify publish` this happens for me:
![image](https://user-images.githubusercontent.com/1275067/101787058-f3b8a280-3afe-11eb-9f44-e7939bdba556.png)

**Comment by PeteDuncanson** [comment] 2020-12-11 14:09
@matansagee @atlesp can you confirm how you deployed manually again, its now working for me as described.

- Download `#current-cloud-backend.zip` from my S3 (the bucket is is in should be called something like "amplify-myapp-live-123456-deployment")
- Extract that somewhere
- Copy the /amplify/#current-cloud-backend/api/<api name>/buildcloudformation-template.json file into my unzipped folder into /api/
- Zip it up again with the same name as the original zip you downloaded (zip the contents not the parent folder!)
- Upload it to the S3 bucket overwriting the original
- run `amplify push` again

At that last step I just hit the same error again, makes sense as I think I'm just pushing up the file I just downloaded???

What am I doing wrong? Been stuck on this all week :(

**Comment by PeteDuncanson** [comment] 2020-12-11 14:28
Ahh sorted it, the file goes into /api/<app-name>/build folder! Thats got it unblocked!

**Closed** 2020-12-11 19:34 UTC
Labels: pending-response, pending-triage, platform

**Comment by vrebo** [comment] 2020-12-15 18:29
@PeteDuncanson where did you find the file `buildcloudformation-template.json`?. 

I can't see it anywhere in the project source code. In my resource api directory I have the following files:

- parameters.json
- schema.graphql
- transform.conf.json

but no `buildcloudformation-template.json`.

**Comment by matansagee** [comment] 2020-12-15 22:47
@vrebo it's in this path - `amplify/backend/api/API_NAME/build/cloudformation-template.json`
the file is `cloudformation-template.json`

**Comment by atlesp** [comment] 2020-12-16 06:02
@attilah is this not in the 4.40 release neither? Looking at the changelog and can not see this fix:
![image](https://user-images.githubusercontent.com/1275067/102310859-1b2ec580-3f6c-11eb-8cf4-ab8cb044a038.png)

We have not been able to deploy to prod due to this issue for almost two weeks now, and that is not good. An ETA for when it will be released would be very helpful when communicating with our customers waiting for updates.
