### ISSUE TITLE
Best Approach for 'heavy' graphql Schema

### ISSUE THREAD

**Issue by MatthieuLab** [aws-amplify/amplify-cli#480] opened 2018-11-20 11:03 UTC
** Which Category is your question related to? **
GraphQL Schema + amplify codegen / transformer

** What AWS Services are you utilizing? **
- AppSync
- Amplify-cli

** Provide additional details e.g. code snippets **
My schema with 12+ @model can not be push due to CloudFormation stack number and/or template size limitation. (2 of them are related to many-to-many relations)

**I can see 3 ways to bypass this problem:**

1. Wait for a release that allow us to push the schema without error (Holy Rollback :))
2. Complete directly the schema on the AppSync console, but there is no amplify pull option to avoid resynchronization problems
3. Create a new Graphql endpoint and later merge my schema to have a more conventional 1 schema/1 endpoint. But amplify does not allow me to create a new one, only update the existing one.

Do you have already solve this kind of problem and what was your feedback?
Thanks

**Comment by MatthieuLab** [comment] 2018-11-27 11:05
Am I the only one having to solve this?

**Comment by mikeparisstuff** [comment] 2018-12-05 02:19
Hey @MatthieuLab. I am actively working on a change that will add support for nested stacks to the transform to solve for this use case. You are not alone as there have been other issues mentioning this in the past (see #185). We have made good progress but this change impacts a lot of different parts and requires refactoring of our tests etc. This change is blocking a number of other features so is a very high priority item.

**Comment by MatthieuLab** [comment] 2018-12-06 11:10
@mikeparisstuff thanks for your feedback. Would love to have an ETA.

So what have my team done to solve this?

1. We update locally our shema.graphql
2. We generate the resolvers and the schema with amplify api gql-compile
3. We copy past the generated schema in the AppSync Console & save it.
4. We update The resolvers for the new model : Query, Mutation. If there is @connection, we also need to update the resolver in the Model Object. All the resolvers are available in the build folder.

If it can help others, it seems to be straight forward and OK. 
Carefull, do not push without -no-gql-override flag

Matthieu
PS: I really hope that we'll be able to also have a 'amplify pull' command.

**Comment by rajababu3** [comment] 2018-12-06 11:17
@MatthieuLab Are you using cloudformation to update the resolvers?

**Comment by MatthieuLab** [comment] 2018-12-06 11:45
> @MatthieuLab Are you using cloudformation to update the resolvers?

@rajababu3 nope, directly the AppSync Console with the Create Resource button to create the DynamoDB table (which I suppose is out of the CloudFormation previously created stack)

**Comment by kaustavghosh06** [comment] 2019-01-07 18:45
Closing this issue since it's a duplicate of #185 and the fix for this issue is currently in PR stage.

**Closed by kaustavghosh06** 2019-01-07 18:45 UTC
Labels: graphql-transformer, question
