### ISSUE TITLE
appsync template site

### ISSUE THREAD

**Issue by amlcodes** [aws-amplify/amplify-cli#765] opened 2019-01-24 22:19 UTC
pushing a graphql template produces error Resource is not in the state stackUpdateComplete. in cloudformation, error is related to template side. 

Is there a fix for this anywhere?

**Comment by kaustavghosh06** [comment] 2019-01-24 22:22
Checkout PR #581 for a solution which we're working on (which you can test out as well).
Closing this issue since its a duplicate of #185

**Closed by kaustavghosh06** 2019-01-24 22:22 UTC
