### ISSUE TITLE
Update(Mutation) returns Unauthorized even though IAM AuthPolicy is specified

### ISSUE THREAD

**Issue by shichi18** [aws-amplify/amplify-cli#9502] opened 2022-01-12 12:28 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.3

### Amplify CLI Version

7.6.8

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth, api

### Amplify Commands

codegen, update

### Describe the bug

I added it with amplify add api (AppSync).
Initially I was using UserPool for login authentication, but I am trying to change to IAM authentication because I need guest login.
I'm also allowing guests with the amplify update api.

The UserPool authentication is working perfectly.
However, when I login with IAM authentication, only the Mutation update function is not available due to an authentication error, even though it is specified in AuthPolicy.
I am able to get it with the get function.

The changes to DynamoDB are returned in a Response like the one below.
The policy is auto-generated by schema, so I think the mutation permissions are set correctly.

Is there any possible cause for this?
Do I need to add the policy somewhere else?
Is there any way to verify that the authorization is set from local?
Is there something wrong with the code?

(It's also strange that two AuthPolicies were generated, 01 and 02, even though they were generated automatically.)

### Expected behavior

When I try to change DyanamoDB, it becomes Unauthorized.

Response(catch error)
```
{
  "data": {
    "updateUsers": null
  },
  "errors": [
    {
      "path": [
        "updateUsers"
      ],
      "data": null,
      "errorType": "Unauthorized",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Not Authorized to access updateUsers on type Mutation"
    }
  ]
}
```

### Reproduction steps

main.ts(ionic - amplify.js)

```
//  "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
Amplify.configure({ ...awsconfig,});
```
↓
```
Amplify.configure({ ...awsconfig,
  aws_appsync_authenticationType: 'AWS_IAM',
});
```

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line

type Users @model
@auth(rules: [
  { allow: owner, ownerField: "id" }
  { allow: groups, groups: ["employee"] }
  { allow: private, provider: iam }
]) {
  id: ID!
  data1: String
  data2: String
  data3: String
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

<img src="https://user-images.githubusercontent.com/32414468/149139376-b91ff5c4-60b5-4a34-80d0-452115dd5e72.png" width = "300" />

**Comment by sundersc** [comment] 2022-01-13 17:45
@shichi18 Can you clarify the below.

> when I login with IAM authentication, only the Mutation update function is not available due to an authentication error, even though it is specified in AuthPolicy

- Do you mean createUsers is working but not the updateUsers?
- Can you share what the AuthPolicy looks like?
- Is the user id you are using to test the access authenticated by Auth (Cognito UserPool)?

**Comment by shichi18** [comment] 2022-01-14 07:55
@sundersc
> Do you mean createUsers is working but not the updateUsers?

Only updateUsers.
I don't think the other Table updates are working either.
Create, delete, and read are working.

> Can you share what the AuthPolicy looks like?

I'm sorry. It's not possible to share in detail, but these was all generated and updated with amplify commands.
All have @model in GraphQL.

> Is the user id you are using to test the access authenticated by Auth (Cognito UserPool)?

It is certified.
I've also done things like creating Cognito from code, and it works.
I can't do Update from Appsync.

By the way,
In the beginning, I was using Amplify.configure only at the beginning of main.ts, but I would like to switch Amplify.configure between IAM and User Pool at the time of login and logout, Is it possible to do this?

**Comment by madahatter** [comment] 2022-01-20 19:10
Having the same problem with Groups in Amplify Mock Api

createUser works, however, when I try to updateUser I get: <Unauthorized on [id, firstName]>

I have fieldLevel auth in place to allow groups "Admin".  Problem occurs when Auth options Groups are set to "Admin"

I am running the newest 7.6.10 version of CLI

Not sure if the same problem occurs when pushed to cloud.

Anyone else experiencing the same?

**Comment by sachscode** [comment] 2022-01-21 19:30
Moving this to pending-triage .

**Comment by sundersc** [comment] 2022-01-28 03:00
> I can't do Update from Appsync.

It may not work from AppSync because of the way IAM private rule work in v2. Have you tried using library? I've tested in a sample app, I'm unable to reproduce it.

**Comment by sundersc** [comment] 2022-01-28 03:02
@madahatter - Your issue might be caused by a different reason. Can you open a new issue and include your schema?

**Comment by sundersc** [comment] 2022-01-28 03:34
@shichi18 - Have you tried this option to use iam auth from AppSync console?
https://docs.amplify.aws/cli/graphql/authorization-rules/#use-iam-authorization-within-the-appsync-console

**Comment by madahatter** [comment] 2022-01-28 15:51
@sundersc thank you for the response!  Much appreciated.

I opened a new thread with my issue here:
https://github.com/aws-amplify/amplify-cli/issues/9635

**Comment by shichi18** [comment] 2022-01-30 13:42
@sundersc 

Thank you!

> Have you tried this option to use iam auth from AppSync console?
> https://docs.amplify.aws/cli/graphql/authorization-rules/#use-iam-authorization-within-the-appsync-console

As a result, I didn't think this was the cause of the problem.

However, I was able to reproduce the phenomenon, so I will describe it below.

Here's how to reproduce it.
In my project, I have "customer" and "employee" groupe in Cognito.
I had added both or one of them to a group in my account.

I deactivated it once to avoid belonging to a group to try to solve the problem.

Then it worked as expected!

Then I added one or both of the groups again and restarted the application, and the "update" that caused the problem did not work. (It may be that other things are also not working, but in my case, "update" was the only thing that did not work.)

By the way, I manually added the policy to the group with both roles generated by Auth.

I don't know if you can reproduce this on your end, but I think this may be a bug.
Or is this the expected behavior?


Here is the final Auth configuration
```
type Users @model
@auth(rules: [
  { allow: private, provider: iam, operations: [create, update, read] }
  { allow: owner, ownerField: "id" }
  { allow: groups, groups: ["employee"] }
  { allow: groups, groups: ["customer"] }
]) {
...
}
```

**Comment by sundersc** [comment] 2022-02-02 00:10
@shichi18 - Thanks for the updates. I was able to reproduce it, marking it as bug.

Here are the steps I've followed to reproduce the issue:
1. Add an api `amplify add api` with Cognito (default) and IAM auth modes.
2. Update auth `amplify update auth` and add user pool groups.
3. Push the resources to the cloud `amplify push`.
4. Create a user, login and check update mutation (using IAM auth) in JS app, it works as expected. 
5. Add user to a group, login and check update mutation (using IAM auth) in JS app, now it throws `401 - Unauthorized error`. (Expected result: Update should work similar to Step 4).

**Schema**
```graphql
type Users @model
@auth(rules: [
  { allow: owner, ownerField: "id" }
  { allow: groups, groups: ["employee"] }
  { allow: private, provider: iam }
  { allow: public, provider: iam }
]) {
  id: ID!
  data1: String
  data2: String
  data3: String
}
```

**Comment by sundersc** [comment] 2022-02-02 20:11
@shichi18 - Couple of things going wrong here,
1. IAM policy for the role used by the user pool group. (Roles attached to user pool groups don't have access to call AppSync service)
2. Error in resolver code. (Correction required to IAM private rule logic)

### IAM policy for the role used by the user pool group
What I have done to resolve this is to take the policy attached to `authRole` and add it to the user pool group's role.

### Error in resolver code
On `Mutation.updateUsers.auth.1.res.vtl`, replace
```
#if( $ctx.identity.userArn == $ctx.stash.authRole )
```
with this
```
#if( ($ctx.identity.userArn == $ctx.stash.authRole) || ($ctx.identity.cognitoIdentityPoolId == "COGNITO ID HERE" && $ctx.identity.cognitoIdentityAuthType == "authenticated") )
```
You can also see this statement in `Subscription.onUpdateUsers.auth.1.req.vtl` for correct logic. Also, you can override the resolver so that the changes doesn't get lost on subsequent push.
https://docs.amplify.aws/cli/graphql/custom-business-logic/#override-amplify-generated-resolvers

We are working on the fix.

**Comment by renebrandel** [comment] 2022-02-03 19:14
I think a couple things need to happen here:

Ideally, what should happens is: we push all authorization logic into the resolver instead of having it be defined in the IAM role.

If that's not possible a another solution could be:
if a static group auth rule is specified, for example `@auth(rules: [{ allow: group, groupName: “Admins”, operations: [create, read, update]}])`

then on `amplify push`, the CLI should check if the group already exists.
-> Does the group exists?
	->No - create the user pool group, and then update its IAM policies.
	->Yes - update IAM policies to match operations

A few edge cases we should handle:
- What if someone removes a group from an auth rule. We shouldn't remove the group itself but rather only its access.
- How does this work with Amplify Studio, which creates user pool groups using SDK calls instead CloudFormation?
- What if a user pool group was created via the Admins Actions API https://docs.amplify.aws/cli/auth/admin/ ? Will it be compatible?
- What if a customer imports an existing user pool via `amplify import auth`?

**Closed** 2022-02-04 21:43 UTC
Labels: bug, graphql-transformer, @auth
