### ISSUE TITLE
GraphQL Transformer issue when using custom @key and @connection

### ISSUE THREAD

**Issue by drochetti** [aws-amplify/amplify-cli#3702] opened 2020-03-19 00:55 UTC
**Problem:**

When defining schemas with custom keys, or explicit keys defined along with a field with a `@connection` directive, the GraphQL transformer expects that the input object of a mutation provide both the id/key and the connected type Input.

**Example:**

- Given the following schema

```graphql
type Post @model {
    id: ID!
    title: String!
    editors: [PostEditor] @connection(keyName: "byPost", fields: ["id"])
}

# Create a join model and disable queries as you don't need them
# and can query through Post.editors and User.posts
type PostEditor
    @model(queries: null)
    @key(name: "byPost", fields: ["postID", "editorID"])
    @key(name: "byEditor", fields: ["editorID", "postID"]) {
    id: ID!
    postID: ID!
    editorID: ID!
    post: Post! @connection(fields: ["postID"])
    editor: User! @connection(fields: ["editorID"])
}

type User @model {
    id: ID!
    username: String!
    posts: [PostEditor] @connection(keyName: "byEditor", fields: ["id"])
}
```

- The GraphQL transformer generates the following `input` for `PostEditor`:

```graphql
input PostEditorInput {
	id: ID!
	postID: ID!
	editorID: ID!
	post: PostInput!
}

# ps: omitting the conflict resolution fields _version, _deleted, _lastChangedAt
# since they are not relevant to this issue
```

A few notes from the generated `input`:

1. `postID` accounts for the connection between `Post` and `PostEditor`, so I believe `post: PostInput!` should not be there, regardless of it's optional or not, given that cascade writes are not supported as of now (is that a fair assumption?)
2. `editorID` is there, but `editor: UserInput!` is not, which seems inconsistent given how `postID` and `post: PostInput!` was handled
3. In a scenario where `postID` and `editorID` were not explicitly defined, I would expect the input to have `postEditorPostId` and `postEditorUserId` automatically generated, but in no scenario `post: PostInput!` should be there. Is that correct?

**Scenario 1: Customs keys**

The expected transformed input is:

```graphql
input PostEditorInput {
	id: ID!
	postID: ID!
	editorID: ID!
}
```

**Scenario 2: Connections with no custom keys**

The expected transformed input is:

```graphql
input PostEditorInput {
	id: ID!
	postEditorPostId: ID!
	postEditorUserId: ID!
}
```

**Possible related issues:**

- https://github.com/aws-amplify/amplify-ios/issues/298

**Comment by yuth** [comment] 2020-03-19 01:03
>     1. `postID` accounts for the connection between `Post` and `PostEditor`, so I believe `post: PostInput!` should not be there, regardless of it's optional or not, given that cascade writes are not supported as of now (is that a fair assumption?)

Yes this is a bug in the graphql-transformer

>     3\. In a scenario where `postID` and `editorID` were not explicitly defined, I would expect the input to have `postEditorPostId` and `postEditorUserId` automatically generated, but in no scenario `post: PostInput!` should be there. Is that correct?

Yes, This should work when using named connections. When using `@connection` with `fields` those fields have to be explicitly defined in the type

**Comment by undefobj** [comment] 2020-04-24 22:33
Duplicate of https://github.com/aws-amplify/amplify-cli/issues/3438

**Comment by attilah** [comment] 2020-05-05 18:42
Closing in favor of #3438

**Closed by attilah** 2020-05-05 18:42 UTC
Labels: bug, graphql-transformer
