### ISSUE TITLE
TS types: Array member can be null on ModelConnection when it should not (bookings: [Booking!] )

### ISSUE THREAD

**Issue by parvusville** [aws-amplify/amplify-cli#9627] opened 2022-01-24 07:33 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-codegen/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-codegen/blob/master/CONTRIBUTING.md#bugs).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v14.17.6

### Amplify CLI Version

7.6.12

### What operating system are you using?

Pop!_OS 21.10

### Amplify Codegen Command

codegen

### Describe the bug

I'm not 100% sure, but this may have started to happen after upgrading CLI to 7.6.11, I also just tried 7.6.12. Not sure what was the version last time before this I made schema changes. 

In my schema I have: 
```graphql
type Company @model(subscriptions: { level: off }) @auth(rules: [{allow: public, operations: [read]}, {allow: groups, groupsField: "groups"}, {allow: private} ]) {
  ...
  bookings: [Booking!] @hasMany(indexName: "byCompany", fields: ["id"])
}
```
Which on `amplify codegen --maxDepth 4` generates TS types:
```graphql
export type Company = {
  ...
  bookings?: ModelBookingConnection | null,
};

export type ModelBookingConnection = {
  ...
  items:  Array<Booking | null >,

};
```

I don't think I have changes anything in the schema, it just started to generate that null yesterday. 

### Expected behavior

Member of the array should not be null, as I have `bookings: [Booking!]` in the schema. I expect the schema below, which it did generate prior yesterday. 
 ```
export type ModelBookingConnection = {
  ...
  items:  Array<Booking>,

};
```

### Reproduction steps

1.  Have similar connection in the schema `  bookings: [Booking!] @hasMany(indexName: "byCompany", fields: ["id"])
`
2. Run `amplify codegen --maxDepth 4`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Company @model(subscriptions: { level: off }) @auth(rules: [{allow: public, operations: [read]}, {allow: groups, groupsField: "groups"}, {allow: private} ]) {
  id: ID!
  name: String!
  businessID: String!
  email: AWSEmail!
  address: String!
  slug: String! @index(name: "bySlug", queryField: "companyBySlug")
  bookings: [Booking!] @hasMany(indexName: "byCompany", fields: ["id"])
  bookingsByAvailable: [Booking!] @hasMany(indexName: "byCompanyByAvailable", fields: ["id"])
  notifications: [Notification!] @hasMany(indexName: "byCompany", fields: ["id"]) @auth(rules: [{allow: groups, groupsField: "groups"}, {allow: private, provider: iam}])
  groups: [String!]!
}

}

type Booking @model(subscriptions: { level: off }) @auth(rules: [{allow: public, operations: [read]}, {allow: groups, groupsField: "groups"}, {allow: private}]) {
  id: ID!
  serviceName: String!
  companyID: ID! @index(name: "byCompany") @index(name: "byCompanyByAvailable", sortKeyFields: ["available"])
  serviceType: String
  dateTime: AWSDateTime!
  length: Int
  price: Int!
  employee: String
  info: String
  available: String!
  customer: Customer @auth(rules: [{allow: groups, groupsField: "groups"}, {allow: private}])
  groups: [String!]!
}

```

</details>

### Log output

<details>

```
# Put your logs below this line
2022-01-24T07:26:23.638Z|info : amplify codegen codegen  {"maxDepth":"4","yes":false}
2022-01-24T07:26:23.674Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}

```

</details>

**Comment by josefaidt** [comment] 2022-02-01 15:24
Hey @parvusville :wave: I was also able to confirm the output of the compilation is generating the `ModelBookingConnection` type without the required field as shown in @phani-srikar 's comment above. Unfortunately there does not appear to be a workaround; marking as a bug 🙂 

1. create a GraphQL API
2. use the following schema
	```graphql
    type Company @model {
      id: ID!
      bookings: [Booking!]! @hasMany(indexName: "byCompany", fields: ["id"])
    }

    type Booking @model {
      id: ID!
      companyID: ID! @index(name: "byCompany")
    }
	```
3. run `amplify api gql-compile`
4. observe malformed output type
	```graphql
    type ModelBookingConnection {
      items: [Booking]!
      nextToken: String
    }
	```

**Comment by cjihrig** [comment] 2022-02-04 22:09
This looks like behavior carried over from the v1 Transformer (I was able to reproduce the issue there as well).

**Comment by cjihrig** [comment] 2022-02-04 22:47
So, this has nothing to do with whether nullability is specified or not in the input schema. The connection type is generated for the list operation of the `@model`.

The code change to make the list entries non-nullable seems pretty straightforward:

```diff
diff --git a/packages/amplify-graphql-model-transformer/src/graphql-types/query.ts b/packages/amplify-graphql-model-transformer/src/graphql-types/query.ts
index b36b1ba17..ae5b8b779 100644
--- a/packages/amplify-graphql-model-transformer/src/graphql-types/query.ts
+++ b/packages/amplify-graphql-model-transformer/src/graphql-types/query.ts
@@ -13,7 +13,7 @@ export const makeListQueryFilterInput = (
 export const makeListQueryModel = (type: ObjectTypeDefinitionNode, modelName: string, isSyncEnabled: boolean): ObjectTypeDefinitionNode => {
   const outputType = ObjectDefinitionWrapper.create(modelName);
 
-  outputType.addField(FieldWrapper.create('items', type.name.value, true, true));
+  outputType.addField(FieldWrapper.create('items', type.name.value, false, true));
   outputType.addField(FieldWrapper.create('nextToken', 'String', true, false));
 
   if (isSyncEnabled) {

```

My biggest concern would be breaking existing code, but I'm not sure that the list operations ever send back null entries anyway.

However, if you would later change your schema to `bookings: [Booking]`, the generated types would not start allowing nulls (and like I said, I'm not sure if we ever return those in lists anyway).

@yuth @lazpavel do you have any thoughts here?

**Comment by lazpavel** [comment] 2022-02-17 22:24
Based on this [PR](https://github.com/aws-amplify/amplify-cli/pull/9310#issue-1080117016) description, having nullable elements is intentional

**Closed by lazpavel** 2022-02-17 22:24 UTC
Labels: bug, graphql-transformer-v2, p4
