### ISSUE TITLE
editing GraphQL schema mid-push causes unexpected behavior on subsequent push attempts

### ISSUE THREAD

**Issue by minganp** [aws-amplify/amplify-cli#10118] opened 2022-04-04 10:22 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli@latest

### Amplify CLI Version

7.6.24

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

api

### Amplify Commands

update

### Describe the bug

After I use Amplify pull command, my schema like this:

```graphql
type Intent @model {
  id: ID!
  datetime: AWSDateTime
  productsID: ID!
  customerId: ID! @ 
  paid: Int
  amount: Float
  product: Products @hasOne(fields: ["id"])
}
```

Obviously, the syntax of graphql is not right. I don't know why like this. But If I changed the schema to :

```graphql
type Intent @model {
  id: ID!
  datetime: AWSDateTime
  productsID: ID!
  customerId: ID!
  paid: Int
  amount: Float
  product: Products @hasOne(fields: ["id"])
}
```

When I use amplify push, I got this

```
🛑 Your GraphQL schema is invalid. Update the schema to use proper syntax and try again.
✖ An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: Syntax Error: Expected Name, found :

GraphQL request:26:7
25 |   customerId: ID! @ 
26 |   paid: Int
   |       ^
27 |   amount: Float
```

It seems that I cannot correct the schema? How can I do with this? 

### Expected behavior

How to update the schema

### Reproduction steps

I cannot recall why the first schema like this. 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment] 2022-04-04 13:22
Hey @minganp :wave: thanks for raising this! Can you confirm whether the `schema.graphql` file in your `#current-cloud-backend` directory has the affected line `customerId: ID! @`? This may be caused by an edit made to the schema mid-push which was then uploaded to current-cloud-backend. On push, the CLI will compile both schema files (in your `amplify/backend/api` folder and `#current-cloud-backend`) which may be causing this error.

If the `schema.graphql` file in your `#current-cloud-backend` is affected the workaround is as follows:

1. navigate to the s3 console and identify the deployment bucket for our app
2. download `#current-cloud-backend.zip`
3. unzip the contents, correct the GraphQL Schema, and re-zip the folder
	1. be sure to not accidentally zip as a nested folder
	2. `unzip "#current-cloud-backend.zip" -d "#current-cloud-backend"`
	3. `mv "#current-cloud-backend.zip" backup.zip`
	4. correct the schema
	5. `cd "#current-cloud-backend"; zip -r "../#current-cloud-backend.zip" *`
4. re-upload the newly zipped archive to our s3 deployment bucket
5. push from local machine with `amplify push --force`
6. observe successful push 🙌

**Comment by josefaidt** [comment] 2022-04-04 17:51
Hey @minganp glad to hear that worked for you! I'll re-open this issue to track as a bug as I do not believe we have this issue specifically documented and tracked.

**Comment by josefaidt** [comment] 2022-04-04 18:16
related https://github.com/aws-amplify/amplify-cli/issues/9961

**Comment by edwardfoyle** [comment] 2022-04-05 21:02
closing as a dupe of https://github.com/aws-amplify/amplify-cli/issues/9961

**Closed by edwardfoyle** 2022-04-05 21:02 UTC
Labels: bug, platform, api-graphql, p2
