### ISSUE TITLE
Should codegen max-depth parameter treat collections differently? 

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#1244] opened 2019-04-10 18:04 UTC
**Describe the bug**
Imagine you have Post model that can have many comments, with the default max-depth of 2, you get the following produced by codegen in typescript: 

```
export type GetPostQuery {
  getPost: { 
     __typename: "Post",
     id: string
    comments: { 
      __typename: "ModelCommentConnection",
      nextToken: string | null
    }
 }
}
```

This is kind of weird. What is the use of nextToken if I don't have items? 

**Describe the solution you'd like**
Should it instead return something like this: 

```
export type GetPostQuery {
  getPost: { 
     __typename: "Post",
     id: string
    comments: { 
      __typename: "ModelCommentConnection",
      items : Array< { .... } >
      nextToken: string | null
    }
 }
}
```

**Describe alternatives you've considered**
Increasing max-depth / using custom queries. 

**Context**
I understand why it's behaving like this. But I figure I'd bring this up for discussion / explicit agreement if that's how you want it to behave.

**Comment by hisham** [comment] 2019-04-10 18:10
Yeah from my point of view this is undesirable behaviour, it makes the appsync api query for items, but that query is useless because you only return __typename and nextToken, if you're going to query for the items then return the items. Increasing max-depth does not resolve the issue as it just punts the problem down a level and makes other queries that do not have collections too deep. 

The original behavior of codgen before you introduced max-depth parameter did not have this issue.

**Comment by jkeys-ecg-nmsu** [comment] 2019-04-11 04:57
@kaustavghosh06 this issue might be alleviated by simply raising the `amplify add api` default for max-depth from 2 to a higher value. The current default only supports a 1-to-many connections on a single root model before running into the issues described here and elsewhere. 

FWIW, with `hosting` and `auth` configured, I have not noticed an appreciable difference in compile and push time between the default and `--max-depth=5` (our current requirement pending refactor).

**Comment by kaustavghosh06** [comment] 2019-09-20 21:34
Closing as this is a duplicate of #1013

**Closed by kaustavghosh06** 2019-09-20 21:34 UTC
Labels: code-gen, feature-request
