### ISSUE TITLE
User cannot create an account with only email/password

### ISSUE THREAD

**Issue by fabientownsend** [aws-amplify/amplify-cli#8159] opened 2021-09-11 11:30 UTC
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.4.2

### Amplify CLI Version

5.5.0

### What operating system are you using?

Mac

### Amplify Categories

auth

### Amplify Commands

Not applicable

### Describe the bug

When trying to create an account with only email/password I have the following message: "Username cannot be of email format, since user pool is configured for email alias"

### Expected behavior

Give the possibility for user to create their account with only an email and password

### Reproduction steps

Initialise the app
``` sh
amplify init

> Choose defaults when prompted
```

Add auth
``` sh
Amplify add auth

? Do you want to use the default authentication and security configuration? Default configuration
? How do you want users to be able to sign in? Email
? Do you want to configure advanced settings? No, I am done.
```

Create the React component:
``` javascript
import { AuthState } from "@aws-amplify/ui-components";
import {
  AmplifySignUp,
  AmplifySignIn,
  AmplifyAuthenticator,
} from "@aws-amplify/ui-react";

const AuthComponent = () => (
 <AmplifyAuthenticator
   initialAuthState={AuthState.SignUp}
   usernameAlias="email"
 >
   <AmplifySignUp
     slot="sign-up"
     usernameAlias="email"
     formFields={[
       {
         type: "email",
         label: "Custom Email Label",
         placeholder: "Custom email placeholder",
         inputProps: { required: true, autocomplete: "username" },
       },
       {
         type: "password",
         label: "Custom Password Label",
         placeholder: "Custom password placeholder",
         inputProps: { required: true, autocomplete: "new-password" },
       },
     ]}
   />
   <AmplifySignIn usernameAlias="email" slot="sign-in" hideSignUp />
 </AmplifyAuthenticator>
 )
```

### Additional information

I raised this issue in this PR as it's when this regression happened: https://github.com/aws-amplify/amplify-cli/pull/7461

Since the change where `AliasAttributes` is used instead of `UsernameAttributes` in the CloudFormation file generated

The following error would be raised: "Username cannot be of email format, since user pool is configured for email alias"

Where a hash (uuid?) would be generated for the username with `UsernameAttributes` it is not the case when using `AliasAttributes`

I'm wondering if the cloud formation generated should have something like, if only one sign-in type selected, use `UserNameAttributes` otherwise use `AliasAttributes` which would have that kind of implementation:

`packages/amplify-category-auth/resources/cloudformation-templates/auth-template.yml.ejs`
``` javascript
<% if (props.aliasAttributes.length === 1 && props.aliasAttributes !== 'username') { %>
  UsernameAttributes: !Ref usernameAttributes
<% } else if (props.aliasAttributes && props.aliasAttributes.length > 1) { %>
  AliasAttributes: !Ref aliasAttributes
<% } %>
```

Note that in the current implementation the following could be deleted as `props.usernameAttributes` would always be set as undefined

``` javascript
<% if (props.usernameAttributes && props.usernameAttributes !== 'username') { %>
  UsernameAttributes: !Ref usernameAttributes
<% } %>
```

Another solution could be to hash the email is hashed when using `AliasAttributes` but as I'm unfamiliar with Amplify and AWS Cognito, I'm not sure where this should happen

Have a great one 👋

**Comment by josefaidt** [comment] 2021-09-13 13:52
Hey @fabientownsend :wave: thanks for taking the time to file this and providing details! This is a duplicate of an existing item that the team is actively tracking, https://github.com/aws-amplify/amplify-cli/issues/7833

Please subscribe to #7833 for further updates. Marking this issue as a duplicate bug and closing. 🙂

**Closed by josefaidt** 2021-09-13 13:52 UTC
