### ISSUE TITLE
AWS Lambda end of support for Node.js 12

### ISSUE THREAD

**Issue by alphonse92** [aws-amplify/amplify-cli#10919] opened 2022-08-20 18:53 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

9.1.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I did not 

### Amplify Categories

auth, function

### Amplify Commands

add

### Describe the bug

I received this email from AWS.

![image](https://user-images.githubusercontent.com/18203585/185761912-72540cdc-7bb4-4a3c-b5df-62b6ded4cc1c.png)

Looking into my lambdas, I noticed the autogenerated amplify lambdas for auth, are using Node 12 for their runtimes:

![image](https://user-images.githubusercontent.com/18203585/185762004-fc53161e-c7ec-43c6-a775-335c89243639.png)

### Expected behavior

Autogenerated Auth lambdas running on correct runtimes

### Reproduction steps

1. amplify add auth
2. Go to lambda's console
3. List your lambdas an order by runtime

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment] 2022-08-20 19:09
Hey @alphonse92 :wave: thanks for raising this! Marking this as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/10894 and https://github.com/aws-amplify/amplify-cli/issues/10887, closing in favor of tracking the existing items

**Closed by josefaidt** 2022-08-20 19:09 UTC
