### ISSUE TITLE
Prevent symlinks unables to deploy some lambdas

### ISSUE THREAD

**Issue by javiermartingonzalez** [aws-amplify/amplify-cli#10471] opened 2022-05-25 09:38 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.13.0

### Amplify CLI Version

8.3.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Build AWS Lambda function with web3 dependency

### Amplify Categories

function

### Amplify Commands

push

### Describe the bug

After the release of Amplify 8.2.0 due to  _fix: prevent symlinks on nodejs package install (#10293)_ change, I'm not able to deploy some of my lambdas.

After that release, Amplify is adding `--no-bin-links` to the installation command. After that my dependency web3 is unable to install. Instalation fails (using or not using Amplify if adding `--no-bin-links` command):

```
bufferutil: Command failed.
Exit code: 1
Command: node-gyp-build
```

### Expected behavior

Lambdas deployed as older versions. I downgrade to version 8.0.1 to be able to deploy my lambdas.

### Reproduction steps

1. Update to Amplify 8.2.0 or later
2. Add web3 dependency to a lambda using `npm install web3`
3. Try to push lambda to backed

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment] 2022-05-25 14:20
Hey @javiermartingonzalez :wave: thanks for raising this! I was able to successfully reproduce this behavior on CLI 8.2.0 and later, and confirmed downgrading to 8.0.1 to push as a workaround (**NOTE**: for projects created with 8.3.0, we will also need to remove the `usesubusernamefordefaultidentityclaim` feature flag when pushing with 8.0.1). Marking as a bug 🙂

**Comment by edwardfoyle** [comment] 2022-07-06 18:48
Hi @javiermartingonzalez this issue can be worked around by running `npm i -g node-gyp-build` before running `amplify build function` or `amplify push`. The issue occurs because `web3` uses the `node-gyp-build` binary when installing which can't be linked with the `--no-bin-links` flag. Installing it globally allows it to be accessed during the install of web3 without linking a new binary.

We aren't going to address this in the `amplify build function` code because sym links in the lambda zip artifact create other issues when packaging the lambda and pulling the project.

**Closed by edwardfoyle** 2022-07-06 18:48 UTC
Labels: bug, functions, p1, regression

**Comment by rafaelfaria** [comment] 2022-10-27 13:35
@edwardfoyle I came across your comment and I have tried your workaround, although it seems to have worked on the previous version of amplify. Not sure if it's just a coincidence, but I have literally just installed the new one and it doesn't seem to be working anymore.

```
$ amplify -v
10.3.2
```

For context, I am using web3 on a layer, so even thou I delete the `node_modules` folder from the `#current-cloud-backend.zip` from the cloud (to fix it) or the local, it still creates again after pushing it again.

any other ideas?

**Comment by martoncsikos** [comment] 2022-12-16 09:26
> We aren't going to address this in the `amplify build function` code because sym links in the lambda zip artifact create other issues when packaging the lambda and pulling the project.

@edwardfoyle Could you point me to some details on what the "other issues" are? I am overriding the `--no-bin-links` behavior in my project and I would like to understand the consequences.
