### ISSUE TITLE
Failed to create amplify stack: SNSRole already exists in stack

### ISSUE THREAD

**Issue by onlybakam** [aws-amplify/amplify-cli#3723] opened 2020-03-20 15:27 UTC
**Describe the bug**

run `amplify add auth`
stack creation fails because an SNS role with the same name  in another amplify stack already exists

this issue has existed for quite some time

**Amplify CLI Version**
4.16.1

**To Reproduce**
i believe this has to do with the naming of the amplify project
if there is a "-" in the project name (and hence the template name), the sns role name is not constructed properly.
i believe there is some splitting and arbitrary indexing going on.
check the logic around how the sns role name is constructed

 https://github.com/aws-amplify/amplify-cli/blob/a4eb66ca1a89ce79e83f551e328c1dc04ba62f7e/packages/amplify-category-auth/provider-utils/awscloudformation/cloudformation-templates/auth-template.yml.ejs#L76

**Expected behavior**
sns role names should be unique across amplify cloudformation stacks

**Comment by kaustavghosh06** [comment] 2020-03-20 16:15
@onlybakam This is a duplicate of #3687 and I'll be looking into it. Closing as duplicate.

**Closed by kaustavghosh06** 2020-03-20 16:15 UTC
