### ISSUE TITLE
AdminQueries Output 'ApiId' not found in stack

### ISSUE THREAD

**Issue by axecopfire** [aws-amplify/amplify-cli#6576] opened 2021-02-09 18:41 UTC
> **Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the
> [Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

I am trying to update a function with permissions to the `AdminQueries` api. The operation fails because the  `AdminQueries` api does not output it's Id.

The error:
```
UPDATE_FAILED   <function name> AWS::CloudFormation::Stack <time> Output 'ApiId' not found in stack 'arn:aws:cloudformation:<regionName>:<accountId>:stack/<projectId>-apiAdminQueries-<uuid>'
```

`Outputs` from `admin-queries-cloudformation-template.json`
```JSON
    "Outputs": {
        "RootUrl": {
            "Description": "Root URL of the API gateway",
            "Value": {"Fn::Join": ["", ["https://", {"Ref": "AdminQueries"}, ".execute-api.", {"Ref": "AWS::Region"}, ".amazonaws.com/", {"Fn::If": ["ShouldNotCreateEnvResources","Prod", {"Ref": "env"} ]}]]}
        },
        "ApiName": {
          "Description": "API Friendly name",
          "Value": "AdminQueries"
        }
    }
```

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
4.41.2

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable
```
$ amplify update function
? Select which capability you want to update: Lambda function (serverless function)
? Select the Lambda function you want to update <function name>
? Which setting do you want to update? Resource access permissions
? Select the category api
? Api has # resources in this project. Select the one you would like your Lambda to access AdminQueries
? Select the operations you want to permit for AdminQueries create, read, update, delete
You can access the following resource attributes as environment variables from your Lambda function
        API_ADMINQUERIES_APIID
        API_ADMINQUERIES_APINAME
```

`amplify push` then fails. 

**Expected behavior**

I expect the cloud formation step to reach `UPDATE_COMPLETE`

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Mac/Windows/Ubuntu]
  - WSL2 
- Node Version. You can use `node -v` to check the node version on your system
  - v14.15.3

**Log output**
Include any relevant log output under `~/.amplify/logs/amplify-cli-<issue-date>.log`

**Additional context**

**Comment by sharmaaditya570191** [comment] 2021-03-05 17:57
I am working on this and I was trying to reproduce your issue. However, I am getting a different error due to a cyclic dependency on the latest Amplify CLI version 4.44.2.
![image](https://user-images.githubusercontent.com/42587159/110153826-8d93a100-7e09-11eb-8fbd-0308541621ee.png)
Finding a fix for this.

**Closed** 2021-03-24 01:12 UTC
Labels: api-rest, bug, functions
