### ISSUE TITLE
Diffs between code in git repo and code retrieved by amplify pull

### ISSUE THREAD

**Issue by lorengordon** [aws-amplify/amplify-cli#4800] opened 2020-07-09 22:27 UTC
**Is your feature request related to a problem? Please describe.**

Running `amplify pull` (or `amplify env checkout <env> --restore` or `amplify env pull`) results in changes due to white space. Very annoying for comparing diffs and working in a cicd workflow.

Seems to primarily affect functions. Using `amplify function add` generates a cloudformation template where spaces are used. After deploying the function with `amplify push`, a subsequent `amplify pull` replaces the source code with a template that uses tabs for white space! There tend to be a handful of other changes as well, as if the template json was prettified.

**Comment by jhockett** [comment] 2020-07-10 18:56
Hi @lorengordon what version of the CLI are you using? You can use `amplify -v` to find out.

**Comment by lorengordon** [comment] 2020-07-10 19:10
@jhockett We started the project a week ago with v4.22.0 and updated to v4.23.0 a few days ago.

**Comment by lorengordon** [comment] 2020-07-11 20:26
I think a cdk provider for amplify could also solve this (https://github.com/aws-amplify/amplify-cli/issues/171), since cdk-generated cfn templates would not need to be committed to the repo.

**Comment by jhockett** [comment] 2020-07-14 17:32
Hi @lorengordon, thanks for the bug report! I was able to reproduce this issue.

**Comment by lorengordon** [comment] 2020-07-14 22:26
Thanks for confirming @jhockett. My workaround for now, is to use Amplify Console to manage all builds... Add `team-provider-info.json` to `.gitignore` and remove it from the repo, and to coach contributors to _never_ run any variation of `amplify push` or `amplify pull` locally. Just let the branch builds and pr previews do the work...

**Comment by attilah** [comment] 2020-09-12 01:34
@lorengordon could you please give it a try with the latest CLI version as I think this is fixed under the changes that involved uniform `JSON` read/write. I was not able to reproduce it with the latest version.

**Comment by lorengordon** [comment] 2020-09-12 01:37
@attilah planning to be working with amplify again this weekend, so good timing! Will let you know

**Comment by lorengordon** [comment] 2020-09-12 01:40
@attilah do you happen to know which pr might have fixed it? I don't see any linked references in this issue...

**Comment by lorengordon** [comment] 2020-09-12 15:56
@attilah I think this is good now. There's still some pain if you used `amplify pull` in an earlier version and committed the code that used tabs as whitespace, because now another `amplify pull` with a more recent version will change them back to spaces. Figure it should be a one time conversion though, so that seems fine.

(I'm testing now with amplify v4.29.1... would still be nice to know which version changed the behavior...)

**Comment by attilah** [comment] 2020-09-14 16:35
@lorengordon one PR I could call out is this: https://github.com/aws-amplify/amplify-cli/pull/5125 that added the state management classes and JSON utility classes. The functions is fixed by some other PR that utilizing the new functions. Closing the issue as it seems to be solved.

**Closed by attilah** 2020-09-14 16:35 UTC
Labels: bug, functions, not-reproducable, pending-response
