### ISSUE TITLE
folderNotFound error

### ISSUE THREAD

**Issue by DiegoMene20** [aws-amplify/amplify-cli#13258] opened 2023-09-22 22:13 UTC
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.18.0

### Amplify CLI Version

12.5.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

When I run amplify pull for my data model it gives me errors and won't import the data models. 

### Expected behavior

I expected the data models to be imported to the Xcode 

### Reproduction steps

1. Run amplify pull --appId ############ --envName staging

### Project Identifier

5632b9076feef78dee88d4ea2f8af772

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment] 2023-09-25 15:11
Hey @DiegoMene20 :wave: thanks for raising this! From the error message it sounds like this may be a duplicate of https://github.com/aws-amplify/amplify-cli/issues/13201, can you confirm this is the case?

**Comment by DiegoMene20** [comment] 2023-09-26 17:52
Yes it does seem like a duplicate. I am
Having the same issue.

**Comment by josefaidt** [comment] 2023-09-27 17:09
Thanks for confirming @DiegoMene20 I'll close this in favor of tracking the existing item. Although a bit concerning, this error pops up after the actual operation has completed (i.e. `amplify pull`), so this can largely be ignored as you work on your app.

**Closed by josefaidt** 2023-09-27 17:09 UTC
Labels: pending-triage, platform-pull
