### ISSUE TITLE
Amplify pull recreates api path 

### ISSUE THREAD

**Issue by johanlantz** [aws-amplify/amplify-cli#6782] opened 2021-03-03 11:49 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v.12.19.0

### Amplify CLI Version

4.44.1

### What operating system are you using?

Mac

### Amplify Categories

auth, storage, function, api

### Amplify Commands

pull

### Describe the bug

My amplify project has a single API, call it myAPI.

At some point when testing, I tried adding a secondary api, call it myAPI2.

In my whole project, I now have no reference to myAPI2, not when searching in VS Code neither in Github. amplify status also does not show myAPI2 and if I do amplify api remove, only myAPI is shown, not myAPI2.

That part looks good. Now the problem is that when I do amplify pull, it recreates the source folder for myAPI2 in
amplify/backend/api/myAPI2 and this path starts to show as "Untracked files" with git.

I have tried rm -rf amplify/backend/api/myAPI2 etc but even when I do that and try amplify push, amplify just says "No changes detected".

Somewhere amplify maintains information about myAPI2 but it is not in my repo, this folder keeps popping up when doing amplify pull.

It's not a critical thing but it is annoying that the code in amplify/backend/api/myAPI2 keep being recreated after each pull

### Expected behavior

I just want that amplify/backend/api/myAPI2 is not recreated when doing amplify pull.

### Reproduction steps

I honestly do not know if it is reproducible. I just want to get rid of the folder for myAPI2 being recreated so any pointer on where this info might be stored if it's not in my repo would be appreciated.

If it is reproducible, perhaps just adding a second api and pushing then trying to remove the second api again might produce the error.

### Log output

na

na

**Comment by edwardfoyle** [comment] 2021-03-03 21:08
@johanlantz I'm assuming these are REST APIs as the CLI should prevent you from creating multiple GraphQL APIs?

It seems like there is still a reference to `myAPI2` somewhere in #current-cloud-backend. After doing a pull can you search in that folder to see if there are any references to the deleted API? If so, you should be able to fix the issue by removing the folder as from `amplify/backend` as you described above, ensure that the API does not show up in the list when running `amplify status` and then push using `amplify push --force`

**Comment by johanlantz** [comment] 2021-03-04 10:12
Hi @edwardfoyle and thanks for the quick reply. Correct, this is a rest API. I only need one, the other one was added when I wanted to test something that I no longer need, so I removed it and as you see in amplify status it is all fine, it only sees the first api called habitsapi. The only issue is that the folder for habitsapi2 keeps getting recreated when doing amplify pull.

You are right in that there is some kind of leftover in #current-cloud-backend that was not found with the normal search, grep caught it though. Following the procedure above however did not help. Please see all the details below, I think it is quite easy to follow. The folder for habitsapi2 keeps getting recreated. Maybe it's enough to delete the folder in #current-cloud-backend but since it is reproducible I will hold for your feedback before touching anything.

```
habits-backend git:(develop) amplify version
4.44.1
➜  habits-backend git:(develop) git status
On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean
➜  habits-backend git:(develop) amplify status

Current Environment: staging

| Category | Resource name                  | Operation | Provider plugin   |
| -------- | ------------------------------ | --------- | ----------------- |
| Storage  | habitsdynamodb                 | No Change | awscloudformation |
| Function | habitsbackend85aa0552          | No Change | awscloudformation |
| Function | habitsusers                    | No Change | awscloudformation |
| Function | habitsbackend899f8454PreSignup | No Change | awscloudformation |
| Function | habitsbackenddatadeletion      | No Change | awscloudformation |
| Function | habitsinsights                 | No Change | awscloudformation |
| Api      | habitsapi                      | No Change | awscloudformation |
| Auth     | habitsbackend899f8454          | No Change | awscloudformation |

REST API endpoint: https://xxx.execute-api.eu-west-1.amazonaws.com/staging

➜  habits-backend git:(develop) grep -rnw amplify -e "habitsapi2"
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:64:      "habitsapi2": {
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:68:          "Name": "habitsapi2",
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:73:              "title": "habitsapi2"
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:574:                                "Ref": "habitsapi2"
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:608:                                "Ref": "habitsapi2"
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:633:            "Ref": "habitsapi2"
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:641:            "Value": {"Fn::Join": ["", ["https://", {"Ref": "habitsapi2"}, ".execute-api.", {"Ref": "AWS::Region"}, ".amazonaws.com/", {"Fn::If": ["ShouldNotCreateEnvResources","Prod", {"Ref": "env"} ]}]]}
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:645:          "Value": "habitsapi2"
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:649:          "Value": {"Ref": "habitsapi2"}
amplify/#current-cloud-backend/api/habitsapi2/api-params.json:18:    "resourceName": "habitsapi2",
amplify/#current-cloud-backend/api/habitsapi2/api-params.json:19:    "apiName": "habitsapi2",
➜  habits-backend git:(develop) ls amplify/backend/api 
habitsapi
➜  habits-backend git:(develop) amplify pull

Pre-pull status:

Current Environment: staging

| Category | Resource name                  | Operation | Provider plugin   |
| -------- | ------------------------------ | --------- | ----------------- |
| Storage  | habitsdynamodb                 | No Change | awscloudformation |
| Function | habitsbackend85aa0552          | No Change | awscloudformation |
| Function | habitsusers                    | No Change | awscloudformation |
| Function | habitsbackend899f8454PreSignup | No Change | awscloudformation |
| Function | habitsbackenddatadeletion      | No Change | awscloudformation |
| Function | habitsinsights                 | No Change | awscloudformation |
| Api      | habitsapi                      | No Change | awscloudformation |
| Auth     | habitsbackend899f8454          | No Change | awscloudformation |

✔ Successfully pulled backend environment staging from the cloud.

Post-pull status:

Current Environment: staging

| Category | Resource name                  | Operation | Provider plugin   |
| -------- | ------------------------------ | --------- | ----------------- |
| Storage  | habitsdynamodb                 | No Change | awscloudformation |
| Function | habitsbackend85aa0552          | No Change | awscloudformation |
| Function | habitsusers                    | No Change | awscloudformation |
| Function | habitsbackend899f8454PreSignup | No Change | awscloudformation |
| Function | habitsbackenddatadeletion      | No Change | awscloudformation |
| Function | habitsinsights                 | No Change | awscloudformation |
| Api      | habitsapi                      | No Change | awscloudformation |
| Auth     | habitsbackend899f8454          | No Change | awscloudformation |

➜  habits-backend git:(develop) ✗ git status
On branch develop
Your branch is up to date with 'origin/develop'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        amplify/backend/api/habitsapi2/

nothing added to commit but untracked files present (use "git add" to track)
➜  habits-backend git:(develop) ✗ rm -rf amplify/backend/api/habitsapi2/
➜  habits-backend git:(develop) git status
On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean
➜  habits-backend git:(develop) amplify push --force
✔ Successfully pulled backend environment staging from the cloud.

Current Environment: staging

| Category | Resource name                  | Operation | Provider plugin   |
| -------- | ------------------------------ | --------- | ----------------- |
| Storage  | habitsdynamodb                 | No Change | awscloudformation |
| Function | habitsbackend85aa0552          | No Change | awscloudformation |
| Function | habitsusers                    | No Change | awscloudformation |
| Function | habitsbackend899f8454PreSignup | No Change | awscloudformation |
| Function | habitsbackenddatadeletion      | No Change | awscloudformation |
| Function | habitsinsights                 | No Change | awscloudformation |
| Api      | habitsapi                      | No Change | awscloudformation |
| Auth     | habitsbackend899f8454          | No Change | awscloudformation |
? Are you sure you want to continue? Yes
✔ All resources are updated in the cloud

REST API endpoint: https://effskwgiud.execute-api.eu-west-1.amazonaws.com/staging

➜  habits-backend git:(develop) git status
On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean
➜  habits-backend git:(develop) amplify status 

Current Environment: staging

| Category | Resource name                  | Operation | Provider plugin   |
| -------- | ------------------------------ | --------- | ----------------- |
| Storage  | habitsdynamodb                 | No Change | awscloudformation |
| Function | habitsbackend85aa0552          | No Change | awscloudformation |
| Function | habitsusers                    | No Change | awscloudformation |
| Function | habitsbackend899f8454PreSignup | No Change | awscloudformation |
| Function | habitsbackenddatadeletion      | No Change | awscloudformation |
| Function | habitsinsights                 | No Change | awscloudformation |
| Api      | habitsapi                      | No Change | awscloudformation |
| Auth     | habitsbackend899f8454          | No Change | awscloudformation |

REST API endpoint: https://xxx.execute-api.eu-west-1.amazonaws.com/staging

➜  habits-backend git:(develop) ls amplify/backend/api 
habitsapi
➜  habits-backend git:(develop) amplify pull

Pre-pull status:

Current Environment: staging

| Category | Resource name                  | Operation | Provider plugin   |
| -------- | ------------------------------ | --------- | ----------------- |
| Storage  | habitsdynamodb                 | No Change | awscloudformation |
| Function | habitsbackend85aa0552          | No Change | awscloudformation |
| Function | habitsusers                    | No Change | awscloudformation |
| Function | habitsbackend899f8454PreSignup | No Change | awscloudformation |
| Function | habitsbackenddatadeletion      | No Change | awscloudformation |
| Function | habitsinsights                 | No Change | awscloudformation |
| Api      | habitsapi                      | No Change | awscloudformation |
| Auth     | habitsbackend899f8454          | No Change | awscloudformation |

✔ Successfully pulled backend environment staging from the cloud.

Post-pull status:

Current Environment: staging

| Category | Resource name                  | Operation | Provider plugin   |
| -------- | ------------------------------ | --------- | ----------------- |
| Storage  | habitsdynamodb                 | No Change | awscloudformation |
| Function | habitsbackend85aa0552          | No Change | awscloudformation |
| Function | habitsusers                    | No Change | awscloudformation |
| Function | habitsbackend899f8454PreSignup | No Change | awscloudformation |
| Function | habitsbackenddatadeletion      | No Change | awscloudformation |
| Function | habitsinsights                 | No Change | awscloudformation |
| Api      | habitsapi                      | No Change | awscloudformation |
| Auth     | habitsbackend899f8454          | No Change | awscloudformation |

➜  habits-backend git:(develop) ✗ git status
On branch develop
Your branch is up to date with 'origin/develop'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        amplify/backend/api/habitsapi2/

nothing added to commit but untracked files present (use "git add" to track)
➜  habits-backend git:(develop) ✗ grep -rnw amplify -e "habitsapi2"     
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:64:      "habitsapi2": {
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:68:          "Name": "habitsapi2",
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:73:              "title": "habitsapi2"
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:574:                                "Ref": "habitsapi2"
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:608:                                "Ref": "habitsapi2"
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:633:            "Ref": "habitsapi2"
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:641:            "Value": {"Fn::Join": ["", ["https://", {"Ref": "habitsapi2"}, ".execute-api.", {"Ref": "AWS::Region"}, ".amazonaws.com/", {"Fn::If": ["ShouldNotCreateEnvResources","Prod", {"Ref": "env"} ]}]]}
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:645:          "Value": "habitsapi2"
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:649:          "Value": {"Ref": "habitsapi2"}
amplify/#current-cloud-backend/api/habitsapi2/api-params.json:18:    "resourceName": "habitsapi2",
amplify/#current-cloud-backend/api/habitsapi2/api-params.json:19:    "apiName": "habitsapi2",
amplify/backend/api/habitsapi2/habitsapi2-cloudformation-template.json:64:      "habitsapi2": {
amplify/backend/api/habitsapi2/habitsapi2-cloudformation-template.json:68:          "Name": "habitsapi2",
amplify/backend/api/habitsapi2/habitsapi2-cloudformation-template.json:73:              "title": "habitsapi2"
amplify/backend/api/habitsapi2/habitsapi2-cloudformation-template.json:574:                                "Ref": "habitsapi2"
amplify/backend/api/habitsapi2/habitsapi2-cloudformation-template.json:608:                                "Ref": "habitsapi2"
amplify/backend/api/habitsapi2/habitsapi2-cloudformation-template.json:633:            "Ref": "habitsapi2"
amplify/backend/api/habitsapi2/habitsapi2-cloudformation-template.json:641:            "Value": {"Fn::Join": ["", ["https://", {"Ref": "habitsapi2"}, ".execute-api.", {"Ref": "AWS::Region"}, ".amazonaws.com/", {"Fn::If": ["ShouldNotCreateEnvResources","Prod", {"Ref": "env"} ]}]]}
amplify/backend/api/habitsapi2/habitsapi2-cloudformation-template.json:645:          "Value": "habitsapi2"
amplify/backend/api/habitsapi2/habitsapi2-cloudformation-template.json:649:          "Value": {"Ref": "habitsapi2"}
amplify/backend/api/habitsapi2/api-params.json:18:    "resourceName": "habitsapi2",
amplify/backend/api/habitsapi2/api-params.json:19:    "apiName": "habitsapi2",
➜  habits-backend git:(develop) ✗ 
```

**Comment by edwardfoyle** [comment] 2021-03-04 20:00
@johanlantz thanks for all the details! Yes it is safe for you to delete the `amplify/#current-cloud-backend/api/habitsapi2` directory. After doing that and pushing you should no longer see any mention of the deleted API. Let me know if that solves it!

**Comment by johanlantz** [comment] 2021-03-05 13:12
@edwardfoyle Thanks for helping, unfortunately, it still comes back after pulling. Please see below, I think I have followed your instructions. Below you see that I delete the folder in #current_cloud-cloud-backend and the grep confirms there is nothing left, then I do amplify push --force and after that, the habitsapi2 is back in the #current_cloud-cloud-backend folder again.

```
➜  habits-backend git:(develop) git status
On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean
➜  habits-backend git:(develop) amplify status

Current Environment: staging

| Category | Resource name                  | Operation | Provider plugin   |
| -------- | ------------------------------ | --------- | ----------------- |
| Storage  | habitsdynamodb                 | No Change | awscloudformation |
| Function | habitsbackend85aa0552          | No Change | awscloudformation |
| Function | habitsusers                    | No Change | awscloudformation |
| Function | habitsbackend899f8454PreSignup | No Change | awscloudformation |
| Function | habitsbackenddatadeletion      | No Change | awscloudformation |
| Function | habitsinsights                 | No Change | awscloudformation |
| Api      | habitsapi                      | No Change | awscloudformation |
| Auth     | habitsbackend899f8454          | No Change | awscloudformation |

REST API endpoint: https://xxx.execute-api.eu-west-1.amazonaws.com/staging

➜  habits-backend git:(develop) grep -rnw amplify -e "habitsapi2"     
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:64:      "habitsapi2": {
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:68:          "Name": "habitsapi2",
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:73:              "title": "habitsapi2"
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:574:                                "Ref": "habitsapi2"
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:608:                                "Ref": "habitsapi2"
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:633:            "Ref": "habitsapi2"
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:641:            "Value": {"Fn::Join": ["", ["https://", {"Ref": "habitsapi2"}, ".execute-api.", {"Ref": "AWS::Region"}, ".amazonaws.com/", {"Fn::If": ["ShouldNotCreateEnvResources","Prod", {"Ref": "env"} ]}]]}
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:645:          "Value": "habitsapi2"
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:649:          "Value": {"Ref": "habitsapi2"}
amplify/#current-cloud-backend/api/habitsapi2/api-params.json:18:    "resourceName": "habitsapi2",
amplify/#current-cloud-backend/api/habitsapi2/api-params.json:19:    "apiName": "habitsapi2",
➜  habits-backend git:(develop) rm -rf amplify/#current-cloud-backend/api/habitsapi2
➜  habits-backend git:(develop) grep -rnw amplify -e "habitsapi2"

JOHAN: Now the habitsapi2 folder is deleted
                   
➜  habits-backend git:(develop) amplify push --force
✔ Successfully pulled backend environment staging from the cloud.

Current Environment: staging

| Category | Resource name                  | Operation | Provider plugin   |
| -------- | ------------------------------ | --------- | ----------------- |
| Storage  | habitsdynamodb                 | No Change | awscloudformation |
| Function | habitsbackend85aa0552          | No Change | awscloudformation |
| Function | habitsusers                    | No Change | awscloudformation |
| Function | habitsbackend899f8454PreSignup | No Change | awscloudformation |
| Function | habitsbackenddatadeletion      | No Change | awscloudformation |
| Function | habitsinsights                 | No Change | awscloudformation |
| Api      | habitsapi                      | No Change | awscloudformation |
| Auth     | habitsbackend899f8454          | No Change | awscloudformation |
? Are you sure you want to continue? Yes
✔ All resources are updated in the cloud

REST API endpoint: https://xxx.execute-api.eu-west-1.amazonaws.com/staging

➜  habits-backend git:(develop) git status
On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean

JOHAN: And here it is back again

➜  habits-backend git:(develop) grep -rnw amplify -e "habitsapi2"
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:64:      "habitsapi2": {
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:68:          "Name": "habitsapi2",
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:73:              "title": "habitsapi2"
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:574:                                "Ref": "habitsapi2"
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:608:                                "Ref": "habitsapi2"
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:633:            "Ref": "habitsapi2"
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:641:            "Value": {"Fn::Join": ["", ["https://", {"Ref": "habitsapi2"}, ".execute-api.", {"Ref": "AWS::Region"}, ".amazonaws.com/", {"Fn::If": ["ShouldNotCreateEnvResources","Prod", {"Ref": "env"} ]}]]}
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:645:          "Value": "habitsapi2"
amplify/#current-cloud-backend/api/habitsapi2/habitsapi2-cloudformation-template.json:649:          "Value": {"Ref": "habitsapi2"}
amplify/#current-cloud-backend/api/habitsapi2/api-params.json:18:    "resourceName": "habitsapi2",
amplify/#current-cloud-backend/api/habitsapi2/api-params.json:19:    "apiName": "habitsapi2",
➜  habits-backend git:(develop) 
```

**Comment by edwardfoyle** [comment] 2021-03-05 16:52
@johanlantz Ah okay, then the issue is the #current-cloud-backend folder in the Amplify deployment bucket still has the deleted API folder as well. You can see when you do a push the first thing that's logged is `Successfully pulled backend environment staging from the cloud.` which is re-adding the resource folder you just deleted. The fix for this is to:
1. Find your project's deployment bucket in the [AWS S3 Console](https://s3.console.aws.amazon.com/s3/buckets) (it will be named `amplify-<project name>-<environment>-<random number>-deployment`)
2. Download the #current-cloud-backend.zip file from the bucket
3. Extract the .zip and remove the deleted resource folder
4. Re-zip the #current-cloud-backend folder (ensure it's the same as the original, just without the deleted resource folder)
5. Upload the new #current-cloud-backend.zip to the deployment bucket, replacing the old #current-cloud-backend.zip file
6. Delete the resource folder in your local #current-cloud-backend (same as you did above)
7. Run `amplify push --force`

You should have a successful push and no longer have the deleted resource

**Comment by johanlantz** [comment] 2021-03-05 19:13
@edwardfoyle Your support is highly appreciated. I understand this is a weird case and that you probably would prefer to spend your time elsewhere.

I  understand the instructions. I got the #current-cloud-backend from the s3 bucket, removed the habitsapi2 folder and uploaded it again, deleted the habitsapi2 locally and did the amplify push --force.

Now, that seemed logical but it blew up my local amplify project. After doing this I started to get errors like:
```
➜  habits-backend git:(develop) amplify status

Current Environment: staging

File at path: `my-backend/amplify/#current-cloud-backend/amplify-meta.json' does not exist
```

and looking in the folder the #current-cloud-backend kept recreating itself inside of itself like #current-cloud-backend/#current-cloud-backend

and even if I moved it so the files were in the correct location, when I did an amplify command, it moved things back so it was #current-cloud-backend/#current-cloud-backend

I triple checked that I zipped my file I uploaded to s3 correctly and it was fine. I managed to revert everything by uploading the original #current-cloud-backend.zip and cloning the project from scrath.

I even tried a second time, but the exact same thing happened. After I uploaded the #current-cloud-backend.zip with habitsapi2 deleted, the local amplify project broke.

No clue where to go from here. Maybe it is better to delete locally only and kill the staging environment and recreate it? I am happy to troubleshoot if it can help improve something but if I am just wasting your time I can take some other approach as well :-)

**Comment by edwardfoyle** [comment] 2021-03-05 20:04
@johanlantz Hmm that's very strange, sorry those steps messed up the project but glad you were able to revert back!

If this is a staging environment that does not contain any production users or data, you could try creating a new environment. Before creating the environment, ensure that your #current-cloud-backend folder doesn't have any mention of the deleted resource. Then run `amplfiy env add`. Double check that #current-cloud-backend still doesn't have any mention of the resource then run `amplify push`. That *should* create a new environment without any reference to the deleted resource

**Comment by johanlantz** [comment] 2021-03-05 21:01
@edwardfoyle Thanks for the instructions, I will have a look next week and let you know.

Again, thanks for the fantastic support, I know this is a weird corner case. Amplify is amazing so this is a small bump compared to everything I have been able to build in just a few weeks with no prior aws experience.

**Comment by edwardfoyle** [comment] 2021-03-09 01:36
Going to close this but if you are still not able to get it sorted out in a new environment, please follow up and we can go from there.

**Closed by edwardfoyle** 2021-03-09 01:36 UTC
Labels: pending-close-response-required, pending-triage, platform

**Comment by johanlantz** [comment] 2021-03-10 11:45
Thanks @edwardfoyle 
I deleted the rouge api as you said and recreated the backend and now it seems fine.
