### ISSUE TITLE
Amplify push not updating Lambda Function Source Code 

### ISSUE THREAD

**Issue by dhruvbansal2** [aws-amplify/amplify-cli#11794] opened 2023-01-17 19:50 UTC
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.18.1

### Amplify CLI Version

9.2.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

N/A

### Describe the bug

I am noticing that when I `amplify push -y` locally (within my Amplify App Directory), the push successfully completes, however the Lambda Function source code is not updated. 

This has not been an issue in the past and seems to be potentially an issue with Amplify CLI 9.2.1

### Expected behavior

Lambda function source code is updated after `amplify push -y`

### Reproduction steps

- Install Amplify CLI 9.2.1
- Ensure there is at least a single Lambda function with code
- Update the code 
- amplify push -y
- The updated code not shown in Lambda function

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment] 2023-01-17 23:16
Hey @dhruvbansal2 :wave: thanks for raising this! Do you experience this issue with the [latest version of Amplify CLI - 10.6.2](https://github.com/aws-amplify/amplify-cli/releases/tag/v10.6.2)? Do you see a recent build zip archive for your function in the deployment bucket of your project? If not, can you post the logs from `~/.amplify/logs` around the time the push occurred?

**Comment by dhruvbansal2** [comment] 2023-01-23 19:09
Hi @josefaidt, unfortunately, we haven't gotten around to upgrading to 10.6.2 yet. 

We tried upgrading to 10.6.1 but ran into a [circular dependency issues]((https://github.com/aws-amplify/amplify-category-api/issues/1093) in our Amplify CI/CD build. 

Whenever I amplify push, I do see a build zip archive for the function in S3, however, the Lambda isn't modified.

**Comment by josefaidt** [comment] 2023-01-24 21:58
Hey @dhruvbansal2 :wave: thanks for clarifying, and no worries! Are you seeing this issue when you push locally as well or is this isolated to builds from Amplify Hosting's CI/CD?

**Comment by dhruvbansal2** [comment] 2023-01-25 18:59
@josefaidt This is only happening locally. The CI/CD pipeline is able to update the Lambdas successfully.

**Comment by josefaidt** [comment] 2023-01-25 19:14
Hey @dhruvbansal2 thanks for clarifying. Unfortunately I am not able to reproduce locally or with the CI/CD pipeline on the latest version of the CLI (10.6.2). Let me take a look at the blocking issue

**Comment by dhruvbansal2** [comment] 2023-01-25 19:22
Thank you @josefaidt ! If the [issue](https://github.com/aws-amplify/amplify-category-api/issues/1093) preventing us from migrating to 10.6.1 is resolved in 10.6.2, then we would be more than happy to move over.

**Comment by dhruvbansal2** [comment] 2023-03-24 20:36
Hi @josefaidt we still do for Amplify cli 9.2.1. 

We are actively monitoring [this issue](https://github.com/aws-amplify/amplify-category-api/issues/1093) to see if we can upgrade to 11.0.3.

To my understanding, 11.0.3 shouldn't see this issue?

**Comment by josefaidt** [comment] 2023-04-10 20:55
Hey @dhruvbansal2 , the linked issue is closed as of late last week and will likely appear in Amplify CLI 11.0.5. I'll mark this issue as `pending-response` and follow up once the release goes out!

**Comment by josefaidt** [comment] 2023-05-02 00:32
Hey @dhruvbansal2 can you try upgrading to CLI 11.1.1 and see if this allows you to push successfully?

**Comment by dhruvbansal2** [comment] 2023-05-03 22:13
Hi @josefaidt it seems people are still running into the [circular dependency issue](https://github.com/aws-amplify/amplify-category-api/issues/1093) with version 11.1.1. 

I'm happy to test it out but we probably can't shift to 11.1.1 until the circular dependency issue is completely resolved

**Comment by josefaidt** [comment] 2023-07-03 20:05
Hey @dhruvbansal2 are you still experiencing this?

**Comment by khayyamkhan** [comment] 2023-08-31 21:19
Not sure if this is related, but I can't see my source code through the AWS browser for lambda functions. Is there any way to be able to edit the code there without having to amplify push?

**Comment by willreillys** [comment] 2023-08-31 23:24
@khayyamkhan Not edit, but you can export it as a zip to verify.

**Comment by josefaidt** [comment] 2023-09-11 23:06
Closing due to inactivity. @khayyamkhan if you are experiencing an issue deploying your Function please open a separate [bug report](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=pending-triage&projects=&template=1.bug_report.yaml). @dhruvbansal2 if you are still experiencing this issue please reply back to this thread and we can re-open to investigate further 🙂

**Closed by josefaidt** 2023-09-11 23:06 UTC
Labels: investigating, functions, pending-response, pending-triage
