### ISSUE TITLE
Generating API with amplify codegen

### ISSUE THREAD

**Issue by vitaliyzolotoy** [aws-amplify/amplify-cli#2950] opened 2019-12-09 11:11 UTC
**Describe the bug**
Getting next error while generating API with `amplify codegen`

`amplify codegen
Downloaded the schema
Code generated successfully and saved in file src/app/API.service.ts
(node:89114) UnhandledPromiseRejectionWarning: SyntaxError: Syntax Error: Expected Name, found ( (187:7)
  185 |   )
  186 | {
> 187 |       (
      |       ^
  188 |       company:$company,
  189 |       showDeleted:$showDeleted
  190 |   )
    at t (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/parser-graphql.js:1:511)
    at Object.parse (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/parser-graphql.js:1:50995)
    at Object.parse (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js:9739:19)
    at coreFormat (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js:13252:23)
    at format (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js:13510:73)
    at formatWithCursor (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js:13526:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js:44207:15
    at Object.format (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js:44226:12)
    at format (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-docs-generator/lib/src/index.ts:111:19)
    at render (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-docs-generator/lib/src/index.ts:78:10)
(node:89114) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:89114) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠸ Generating GraphQL operations^C
`

**Amplify CLI Version**
`4.5.0`

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version `v13.2.0`

**Additional context**

**Comment by attilah** [comment] 2019-12-09 18:54
@vitaliyzolotoy is ```amplify api gql-compile``` succeeds? Please share the generated ```API.service.ts``` as it seems that prettier has some problem with it. Is ```tsc``` able to compile the above file or there is a syntax error in the generated code?

**Comment by vitaliyzolotoy** [comment] 2019-12-10 07:56
`amplify api gql-compile` was succeed. `API.service.ts` was empty

**Comment by vitaliyzolotoy** [comment] 2019-12-11 08:20
`amplify api gql-compile` runs but did not gererate queries and mutations

**Comment by nikhname** [comment] 2019-12-16 18:23
Hi @vitaliyzolotoy could you provide more detailed steps for reproducing this?

**Comment by nikhname** [comment] 2020-01-09 17:44
Closing this issue since I am not able to reproduce this. Please comment if you have more detailed steps for reproducing this version with 4.11.0

**Closed by nikhname** 2020-01-09 17:44 UTC
Labels: bug, code-gen, not-reproducable, pending-response
