### ISSUE TITLE
Auth - Setting Trigger Destroys Verification Settings

### ISSUE THREAD

**Issue by iyz91** [aws-amplify/amplify-cli#7839] opened 2021-07-30 05:03 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

5.1.2

### What operating system are you using?

Windows

### Amplify Categories

auth

### Amplify Commands

update

### Describe the bug

This issue is for both the Amplify and Cognito service teams, related to https://github.com/aws-amplify/amplify-cli/issues/7833, https://github.com/aws-amplify/amplify-cli/issues/7666 and https://github.com/aws-amplify/amplify-js/issues/2906

If you set a trigger (console or CLI), it removes the verification settings (e.g. resets "Which attributes do you want to verify?" to "No verification"). Setting it back to "Email only" then resets the trigger.

The only workaround AFAIK is to call the CLI with cognito-idp update-user-pool to set the desired properties all at once. Unfortunately, this will like keep popping up as the CLI will probably trigger a reset on future pushes. 

Please prioritize these issues, makes Cognito unusable out of the box for common use cases and it was never this bad over the past few years. Thanks.

### Expected behavior

You should be able to set a trigger and/or verification settings without one affecting the other. 

### Reproduction steps

If you set a trigger (console or CLI), it removes the verification settings (e.g. resets "Which attributes do you want to verify?" to "No verification"). Setting it back to "Email only" then resets the trigger.

### GraphQL schema(s)

N/A

### Log output

N/A

**Comment by josefaidt** [comment] 2021-07-30 16:21
Hey @iyz91 :wave: I was able to reproduce the behavior of the attribute switching from "Email" to "No verification" by updating my auth resource with a trigger. However, I was not able to reproduce the trigger resetting. Can you elaborate on that behavior?

Reproduction steps:

1. `amplify add auth`
2. Manual config
   ```
    Do you want to use the default authentication and security configuration? Manual configuration
    Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AWS IAM controls (Enables per
    -user Storage features for images or other content, Analytics, and more)
    Please provide a friendly name for your resource that will be used to label this category in the project: 7839cognitoattrverifb45afcb8b45a
    fcb8
    Please enter a name for your identity pool. 7839cognitoattrverifb45afcb8_identitypool_b45afcb8
    Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) No
    Do you want to enable 3rd party authentication providers in your identity pool? No
    Please provide a name for your user pool: 7839cognitoattrverifb45afcb8_userpool_b45afcb8
    Warning: you will not be able to edit these selections. 
    How do you want users to be able to sign in? Email
    Do you want to add User Pool Groups? No
    Do you want to add an admin queries API? No
    Multifactor authentication (MFA) user login options: OFF
    Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
    Please specify an email verification subject: Your verification code
    Please specify an email verification message: Your verification code is {####}
    Do you want to override the default password policy for this User Pool? No
    Warning: you will not be able to edit these selections. 
    What attributes are required for signing up? Email
    Specify the app's refresh token expiration period (in days): 30
    Do you want to specify the user attributes this app can read and write? No
    Do you want to enable any of the following capabilities? 
    Do you want to use an OAuth flow? No
    ? Do you want to configure Lambda Triggers for Cognito? No
   ```
3. `amplify push -y`, Observe email is set as expected 
![image](https://user-images.githubusercontent.com/5033303/127681728-91379f99-0323-449e-95ef-623fdff04c52.png)
4. `amplify update auth`, add some Cognito Trigger (ex: email allowlist filtering)
5. `amplify push -y`, observe "no verification" is now set 
![image](https://user-images.githubusercontent.com/5033303/127681845-060446eb-cd04-4ddd-99ec-d7e249f335f1.png)

**NOTE:** I was able to re-enable email verification in the Cognito console (after enabling MFA due to configured SMS role), and confirmed it was unaffected by subsequent pushes

**Comment by iyz91** [comment] 2021-07-30 16:33
I just called 'aws cognito-idp update-user-pool --user-pool-id=<user pool id> --account-recovery-setting "RecoveryMechanisms=[{Priority=1,Name=verified_email}]"' and it reset the trigger field. 

The only way that currently works is to call update-user-pool with all the fields specified at once.

**Comment by josefaidt** [comment] 2021-07-30 17:44
Thanks for the information! Just wanted to verify to make sure it wasn't reset by the Amplify CLI 🙂

**Comment by iyz91** [comment] 2021-07-30 17:57
My pleasure and thank you as well. I'll comment back here if the CLI does reset it as well but it seems its some config issue within Cognito itself on top of the CLI issues.

**Comment by ninjaKris** [comment] 2021-07-30 18:22
@josefaidt I am able to reproduce the issue by setting the `Add users to group` in the Post Confirmation trigger via the client

**Comment by josefaidt** [comment] 2021-07-30 18:34
Thank you for confirming you are also experiencing this issue and for providing those details, @ninjaKris!

**Comment by dorontal** [comment] 2021-08-18 00:36
This pull request seems to suggest that it is an Amplify CLI fix, and an easy one. I believe this pull request is the fix, right? 
https://github.com/aws-amplify/amplify-cli/pull/7671

**Comment by akshbhu** [comment] 2021-10-04 15:14
Closing in favour of https://github.com/aws-amplify/amplify-cli/pull/7671

**Closed by akshbhu** 2021-10-04 15:14 UTC
Labels: bug, auth
