### ISSUE TITLE
Amplify push in a new environment is not updating the `aws-exports` file

### ISSUE THREAD

**Issue by phani-srikar** [aws-amplify/amplify-cli#8286] opened 2021-09-27 17:38 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14

### Amplify CLI Version

6.0.1

### What operating system are you using?

MacOS

### Amplify Categories

Not applicable

### Amplify Commands

add, env, push

### Describe the bug

Running `amplify push` in a new environment after `amplify env add <env-name>` does not update the `aws-exports` file.

### Expected behavior

`amplify push` should update the `aws-exports` file.

### Reproduction steps

1. Run `amplify init` in a JS project, followed by `amplify add storage`
2. Run `amplify push` and check the `aws-exports` file is updated correctly.
3. Add a new environment using `amplify env add test` and run `amplify push`
4. The `aws-exports` file is not updated with correct bucket name, it looks like "aws_user_files_s3_bucket": "<name>-dev", instead of "aws_user_files_s3_bucket": "<name>-test".

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment] 2021-09-27 19:44
Hey @phani-srikar :wave: thanks for raising this! I was able to successfully reproduce by following the provided steps. Marking this as a bug 🙂 

As a workaround we can run `amplify env checkout <current-env-name>` to update the `aws-exports` file.

**Comment by lazpavel** [comment] 2022-02-16 00:51
Unable to reproduce with latest CLI. Please reopen if you still experience this issue after upgrading.

**Closed by lazpavel** 2022-02-16 00:51 UTC
Labels: bug, platform-push, p2
