### ISSUE TITLE
Amplify mock Error in version 4.44.0

### ISSUE THREAD

**Issue by AshwanthMadhav** [aws-amplify/amplify-cli#6702] opened 2021-02-22 14:53 UTC
Lambda Data source failed with the following error
TypeError: Cannot destructure property `timeout` of 'undefined' or 'null'.
    at getCancellableTimer (/Users/ashwanthmadhav/.nvm/versions/node/v12.9.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/func/index.ts:73:30)
    at Object.timeConstrainedInvoker (/Users/ashwanthmadhav/.nvm/versions/node/v12.9.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/func/index.ts:65:29)
    at Object.invoke (/Users/ashwanthmadhav/.nvm/versions/node/v12.9.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/api/api.ts:203:22)
    at LambdaDataLoader.<anonymous> (/Users/ashwanthmadhav/.nvm/versions/node/v12.9.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-appsync-simulator/src/data-loader/lambda/index.ts:25:37)
    at step (/Users/ashwanthmadhav/.nvm/versions/node/v12.9.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-appsync-simulator/lib/data-loader/lambda/index.js:33:23)
    at Object.next (/Users/ashwanthmadhav/.nvm/versions/node/v12.9.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-appsync-simulator/lib/data-loader/lambda/index.js:14:53)
    at /Users/ashwanthmadhav/.nvm/versions/node/v12.9.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-appsync-simulator/lib/data-loader/lambda/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/ashwanthmadhav/.nvm/versions/node/v12.9.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-appsync-simulator/lib/data-loader/lambda/index.js:4:12)
    at LambdaDataLoader.load (/Users/ashwanthmadhav/.nvm/versions/node/v12.9.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-appsync-simulator/lib/data-loader/lambda/index.js:56:16)

**Comment by cjihrig** [comment] 2021-02-22 15:34
Duplicate of https://github.com/aws-amplify/amplify-cli/issues/6653? If so, https://github.com/aws-amplify/amplify-cli/pull/6659 landed as a proposed fix.

**Comment by edwardfoyle** [comment] 2021-02-22 18:24
Yes this is a dupe of #6653 and #6659 will fix it in the next release. In the meantime, you can include `--timeout 20` (or whatever timeout you want) when invoking mock to avoid the error

**Closed by edwardfoyle** 2021-02-22 18:24 UTC
