### ISSUE TITLE
env add results in 'Failed to fetch Amplify Admin credentials'

### ISSUE THREAD

**Issue by rogerheykoop** [aws-amplify/amplify-cli#6054] opened 2020-12-03 17:37 UTC
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
When adding a new environment the error 'Failed to fetch Amplify Admin credentials' appears. 

**Amplify CLI Version**
4.37.1

**To Reproduce**
An existing amplify app with a standard 'dev' environment.

```
amplify env add
Initializing new Amplify CLI version...
Done initializing new version.
Scanning for plugins...
Plugin scan successful
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? No
? Enter a name for the environment prod
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

Failed to fetch Amplify Admin credentials
init failed
Error: TypeError: Cannot read property 'idToken' of undefined
    at Object.getAwsConfig (/Users/*****/.nvm/versions/node/v11.15.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/configuration-manager.js:761:13)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)

```

**Expected behavior**
The expected behavior Is the correct adding of the new environment. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS X Big Sur
 - Node Version. 11.15.0 (also tried on 10.x with the same results)

**Comment by jhockett** [comment] 2020-12-03 17:38
Closing as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/6037

**Closed by jhockett** 2020-12-03 17:38 UTC
