### ISSUE TITLE
codegen on pull: Codegen when pulling in another frontend

### ISSUE THREAD

**Issue by SebSchwartz** [aws-amplify/amplify-cli#3334] opened 2020-02-04 09:51 UTC
**Is your feature request related to a problem? Please describe.**
When doing ```amplify pull```, if codegen is present in the main project (also with apiId), execute a codegen il the project that is pulling amplify.

**Describe the solution you'd like**
Would be great if CLI generates all graphql types and statements when pulling in another frontend (even when codegen is added with apiId).

**Comment by kaustavghosh06** [comment] 2021-01-29 02:03
Closing as a duplicate of #5251

**Closed by kaustavghosh06** 2021-01-29 02:03 UTC
Labels: code-gen, feature-request, platform
