### ISSUE TITLE
amplifyPush from amplify.yml fails with ENOENT: no such file or directory, open 'amplify/backend/awscloudformation/build/root-cloudformation-stack.json'

### ISSUE THREAD

**Issue by sky4git** [aws-amplify/amplify-cli#10568] opened 2022-06-12 04:18 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify CLI Version

8.4.0

### What operating system are you using?

amazon linux

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Added Admin API and pushed the changes to my `dev` branch.

### Amplify Categories

auth

### Amplify Commands

push

### Describe the bug

I have added admin queries API. After that, I pushed the changes in my `dev` branch, and amplify console build is failing for the following error. 

```
2022-06-12T02:58:48.817Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
2022-06-12T02:58:49.572Z [WARNING]: ✖ There was an error initializing your environment.
2022-06-12T02:58:49.673Z [INFO]: [31mFailed to pull the backend.[39m
2022-06-12T02:58:49.676Z [WARNING]: - Creating Zip
2022-06-12T02:58:49.700Z [INFO]: 🛑 ENOENT: no such file or directory, open '/codebuild/output/srcXXXXXXX/src/myproject/amplify/backend/awscloudformation/build/root-cloudformation-stack.json'
2022-06-12T02:58:49.700Z [INFO]: Error: ENOENT: no such file or directory, open '/codebuild/output/srcXXXXXXX/src/myproject/amplify/backend/awscloudformation/build/root-cloudformation-stack.json'
                                 at Object.openSync (fs.js:497:3)
                                 at Object.openSync (pkg/prelude/bootstrap.js:739:32)
                                 at Object.readFileSync (fs.js:393:35)
                                 at Object.readFileSync (pkg/prelude/bootstrap.js:1025:36)
                                 at /snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/diagnose.js:131:132
                                 at Array.forEach (<anonymous>)
                                 at createZip (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/diagnose.js:130:15)
                                 at zipSend (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/diagnose.js:88:35)
                                 at reportError (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/diagnose.js:60:15)
                                 at Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:168:46)
                                 at runMicrotasks (<anonymous>)
                                 at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-06-12T02:58:49.718Z [ERROR]: !!! Build failed
2022-06-12T02:58:49.718Z [ERROR]: !!! Non-Zero Exit Code detected
```

### Expected behavior

`amplifyPush --simple` should work normally as `amplify push --yes` for the local environment worked successfully. 

### Reproduction steps

Already described above. 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by bobthemagicman** [comment] 2022-06-13 01:25
I have the same exact issue with a brand new amplify project I am setting up.

**Comment by LokeshBhatt79** [comment] 2022-06-13 10:15
I have the same exact issue with amplify env list command after I upgraded to version 8.4.0

**Comment by josefaidt** [comment] 2022-06-13 13:50
Hey @sky4git :wave: thanks for raising this! I was not able to reproduce this with a new app with a Lambda and Auth (+admin queries) attached to Amplify Hosting, however I do have a few follow-up questions to better understand the context:

- does this only occur in the Hosting builds? are you able to run commands locally, including `amplify push`, without error?
- can you confirm both locally and in Hosting you are using Amplify CLI 8.4.0?
- any further customizations applied to the build process?
- is this `awscloudformation` directory present in your `#current-cloud-backend`?

**Comment by sky4git** [comment] 2022-06-14 01:26
@josefaidt 
- does this only occur in the Hosting builds? are you able to run commands locally, including amplify push, without error? - YES. No error on `amplify push` command from local.
- can you confirm both locally and in Hosting you are using Amplify CLI 8.4.0? - YES
- any further customizations applied to the build process? - Nope
- is this awscloudformation directory present in your #current-cloud-backend? - YES

**Comment by bobthemagicman** [comment] 2022-06-14 02:47
I am not sure if I am supposed to be tagging along here but my answers are the same as @sky4git except I do not have a #current-clout-backend folder in my amplify directory and no matter what series of commands I have run I have never seen one generated. I was using CLI 8.4.0 in both locations but I also tried rolling back to the previous minor version in the console in an effort to debug, I got the same result. I hope this is more helpful than opening my own ticket for an identical issue.

**Comment by stephenc222** [comment] 2022-06-14 04:10
I'm seeing this issue as well, after upgrading Amplify CLI to the latest version.

**Comment by josefaidt** [comment] 2022-06-14 14:19
relevant: https://github.com/aws-amplify/amplify-cli/issues/10582

**Comment by stephenc222** [comment] 2022-06-14 14:29
is there a version of the Amplify CLI that would be worth downgrading to on the Amplify Console in order to workaround this issue, at least temporarily @josefaidt?

**Comment by josefaidt** [comment] 2022-06-14 14:37
Hey @stephenc222 can you try removing this line from your buildspec file (`amplify.yml`)? `envCache --set stackInfo`

**Comment by stephenc222** [comment] 2022-06-14 14:38
@josefaidt sure, let me make that change and attempt a re-deploy.

**Comment by stephenc222** [comment] 2022-06-14 15:09
@josefaidt Attempted a re-deploy, and got the same terminal error output:

```
2022-06-14T15:06:57.536Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
2022-06-14T15:06:57.810Z [WARNING]: ✖ There was an error initializing your environment.
2022-06-14T15:06:57.856Z [INFO]: [31mFailed to pull the backend.[39m
2022-06-14T15:06:57.858Z [WARNING]: - Creating Zip
2022-06-14T15:06:57.877Z [INFO]: 🛑 ENOENT: no such file or directory, open '/codebuild/output/src104800858/src/crypto-clamor/next_web_app/amplify/backend/awscloudformation/build/root-cloudformation-stack.json'
2022-06-14T15:06:57.877Z [INFO]: Error: ENOENT: no such file or directory, open '/codebuild/output/src104800858/src/crypto-clamor/next_web_app/amplify/backend/awscloudformation/build/root-cloudformation-stack.json'
                                 at Object.openSync (fs.js:497:3)
                                 at Object.openSync (pkg/prelude/bootstrap.js:739:32)
                                 at Object.readFileSync (fs.js:393:35)
                                 at Object.readFileSync (pkg/prelude/bootstrap.js:1025:36)
                                 at /snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/diagnose.js:143:132
                                 at Array.forEach (<anonymous>)
                                 at createZip (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/diagnose.js:142:15)
                                 at zipSend (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/diagnose.js:99:35)
                                 at reportError (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/diagnose.js:62:15)
                                 at Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:168:46)
                                 at runMicrotasks (<anonymous>)
                                 at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-06-14T15:06:57.895Z [ERROR]: !!! Build failed
2022-06-14T15:06:57.896Z [ERROR]: !!! Non-Zero Exit Code detected
2022-06-14T15:06:57.896Z [INFO]: # Starting environment caching...
2022-06-14T15:06:57.896Z [INFO]: # Uploading environment cache artifact...
2022-06-14T15:06:57.956Z [INFO]: # Environment caching completed
Terminating logging...
```

**Comment by stephenc222** [comment] 2022-06-14 15:10
I'm optimistic that [this PR](https://github.com/aws-amplify/amplify-cli/pull/10590) may solve this issue?

**Comment by josefaidt** [comment] 2022-06-14 15:53
Hey @stephenc222 thanks for trying that out and great callout with the feature flag. Does your build still error out after bypassing the diagnosis call?

**Comment by stephenc222** [comment] 2022-06-14 15:56
@josefaidt It does, looks like there's an error with importing my "blog" dynamodb table:

```
2022-06-14T15:38:06.007Z [WARNING]: ✖ There was an error initializing your environment.
2022-06-14T15:38:06.051Z [INFO]: [31mFailed to pull the backend.[39m
2022-06-14T15:38:06.053Z [INFO]: 🛑 storage headless expected 1 element for resource: blog, but found: 0
2022-06-14T15:38:06.054Z [INFO]: Error: storage headless expected 1 element for resource: blog, but found: 0
                                 at ensureHeadlessParameters (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-storage/lib/provider-utils/awscloudformation/import/import-dynamodb.js:406:11)
                                 at headlessImport (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-storage/lib/provider-utils/awscloudformation/import/import-dynamodb.js:360:40)
                                 at importedDynamoDBEnvInit (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-storage/lib/provider-utils/awscloudformation/import/import-dynamodb.js:260:12)
                                 at runMicrotasks (<anonymous>)
                                 at processTicksAndRejections (internal/process/task_queues.js:95:5)
                                 at async updateConfigOnEnvInit (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-storage/lib/provider-utils/awscloudformation/index.js:157:9)
                                 at async /snapshot/repo/build/node_modules/@aws-amplify/amplify-category-storage/lib/index.js:352:22
2022-06-14T15:38:06.093Z [ERROR]: !!! Build failed
2022-06-14T15:38:06.094Z [ERROR]: !!! Non-Zero Exit Code detected
2022-06-14T15:38:06.094Z [INFO]: # Starting environment caching...
2022-06-14T15:38:06.094Z [INFO]: # Uploading environment cache artifact...
2022-06-14T15:38:06.165Z [INFO]: # Environment caching completed
```

Ultimately - I'm going to workaround this new import issue (hopefully...) by just re-creating the table within the amplify project. For the context of this table, I don't get any value from importing this table vs creating it within the project and specific for each environment I have

**Comment by josefaidt** [comment] 2022-06-14 15:59
Hey @stephenc222 I do see two tables with the same names in the constructed `pull`/`init` command. Are you seeing something similar in the references stored in your `team-provider-info.json` or `backend-config.json`?

**Comment by stephenc222** [comment] 2022-06-14 16:01
This is what I see in both my `backend-config.json` and `team-provider-info.json`:

```
    "blog": {
      "service": "DynamoDB",
      "serviceType": "imported",
      "providerPlugin": "awscloudformation",
      "dependsOn": []
    }
```

**Comment by stephenc222** [comment] 2022-06-14 17:27
@josefaidt I decided to go with an alternative approach to create the "blog" table as part of the amplify project, and not as an imported resource. From there, I was able to successfully build and deploy from the Amplify Console!

FWIW, I wonder if there's an issue with recently imported storage resources. Not sure. Thanks for your input!

Can this issue be notified when the diagnostic-related bug is fixed? I would like to opt back in to send diagnostics when future errors occur :+1:

**Comment by bobthemagicman** [comment] 2022-06-14 19:24
Similar to above, this revealed the actual error that was happening behind the scenes, not sure it's at all helpful but I will post here for posterity:
`                                                              ## Checking for associated backend environment...
                                                                ## Backend environment association found
2022-06-14T19:10:46.388Z [INFO]: [0mAmplify AppID found: daaj114gsrp5i. Amplify App name is: propertytoolsio[0m
2022-06-14T19:10:46.437Z [INFO]: [0mBackend environment beta found in Amplify Console app: propertytoolsio[0m
2022-06-14T19:10:47.211Z [WARNING]: - Fetching updates to backend environment: beta from the cloud.
2022-06-14T19:10:47.898Z [WARNING]: - Building resource auth/propertytoolsio19dd8f27
2022-06-14T19:10:48.035Z [WARNING]: ✔ Successfully pulled backend environment beta from the cloud.
2022-06-14T19:10:48.041Z [WARNING]: ✖ There was an error initializing your environment.
2022-06-14T19:10:48.048Z [INFO]: [31mFailed to pull the backend.[39m
2022-06-14T19:10:48.050Z [INFO]: 🛑 auth headless is missing the following inputParams facebookAppIdUserPool, facebookAppSecretUserPool, googleAppIdUserPool, googleAppSecretUserPool
2022-06-14T19:10:48.051Z [INFO]: Error: auth headless is missing the following inputParams facebookAppIdUserPool, facebookAppSecretUserPool, googleAppIdUserPool, googleAppSecretUserPool
                                 at updateConfigOnEnvInit (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-auth/lib/provider-utils/awscloudformation/index.js:93:23)
                                 at /snapshot/repo/build/node_modules/@aws-amplify/amplify-category-auth/lib/index.js:278:34
                                 at /snapshot/repo/build/node_modules/promise-sequential/index.js:16:18
                                 at runMicrotasks (<anonymous>)
                                 at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-06-14T19:10:48.066Z [ERROR]: !!! Build failed
2022-06-14T19:10:48.066Z [ERROR]: !!! Non-Zero Exit Code detected
2022-06-14T19:10:48.066Z [INFO]: # Starting environment caching...
2022-06-14T19:10:48.066Z [INFO]: # Environment caching completed
Terminating logging...`

**Comment by sky4git** [comment] 2022-06-21 12:56
> Hey @sky4git 👋 thanks for raising this! I was not able to reproduce this with a new app with a Lambda and Auth (+admin queries) attached to Amplify Hosting, however I do have a few follow-up questions to better understand the context:
> 
> * does this only occur in the Hosting builds? are you able to run commands locally, including `amplify push`, without error?
> * can you confirm both locally and in Hosting you are using Amplify CLI 8.4.0?
> * any further customizations applied to the build process?
> * is this `awscloudformation` directory present in your `#current-cloud-backend`?

My app id is `d1ejtq711s7jra` in `ap-southeast-2`

**Comment by josefaidt** [comment] 2022-06-21 21:47
Hey @bobthemagicman :wave: thanks for chiming in here! From the error it appears we will need a few environment variables set in the Amplify Hosting console https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html#amplify-console-environment-variables

@stephenc222 glad to hear you are back up and running! And yes, please subscribe to https://github.com/aws-amplify/amplify-cli/issues/10581 and https://github.com/aws-amplify/amplify-cli/issues/10582 for further updates regarding the diagnostics issues

**Comment by sky4git** [comment] 2022-06-22 00:49
> "debug": {
>     "shareProjectConfig": false
>   }

My app id is `d1ejtq711s7jra` in `ap-southeast-2`.  I tried ```"debug": {
    "shareProjectConfig": false
  }``` But now I started getting Above mentioned error regarding missing `Error: auth headless is missing the following inputParams googleClientId`  

My `team-provider-info.json` has that value in it. I am not sure where else I need to put it again.

**Comment by sky4git** [comment] 2022-06-22 02:36
> Hey @bobthemagicman 👋 thanks for chiming in here! From the error it appears we will need a few environment variables set in the Amplify Hosting console https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html#amplify-console-environment-variables
> 
> @stephenc222 glad to hear you are back up and running! And yes, please subscribe to #10581 and #10582 for further updates regarding the diagnostics issues

FYI: I already have the following environment variables in Amplify Hosting console
```
AMPLIFY_GOOGLE_CLIENT_ID
AMPLIFY_GOOGLE_CLIENT_SECRET
```

**Comment by sky4git** [comment] 2022-06-22 09:49
My error is fixed by adding `googleClientId` in `cli-input.json`

**Comment by josefaidt** [comment] 2022-06-24 18:22
Hey @sky4git for the environment variable issue would you mind filing an issue on our Hosting repo? https://github.com/aws-amplify/amplify-hosting/issues/new/choose

**Comment by josefaidt** [comment] 2022-06-24 18:23
Closing in favor of tracking root cause bugs #10581 and #10582

**Closed by josefaidt** 2022-06-24 18:23 UTC
Labels: pending-close-response-required, platform, pending-triage

**Comment by olliethedev** [comment] 2022-07-10 16:51
My issue was solved for me after adding 
```
AMPLIFY_GOOGLE_CLIENT_ID
AMPLIFY_GOOGLE_CLIENT_SECRET
```
to the Environment variables in the Amplify Console under App Settings / Environment Variables. 

This is not ideal because I now I have two places to update the ID+Secret per environment, on Amplify Studio Authentication  section and in the Console Environment Variables section.
