### ISSUE TITLE
amplify configure should offer (and recommend) AWS SSO

### ISSUE THREAD

**Issue by dmost714** [aws-amplify/amplify-cli#12172] opened 2023-03-04 15:20 UTC
### Is this feature request related to a new or existing Amplify category?

New category

### Describe the feature you'd like to request

The `amplify configure` comment encourages users to create a new IAM user for use with Amplify. This results in permanent access keys being generated and used.

Instead, this step should guide the user through the creation of an `IAM Identity Center` user.

### Describe the solution you'd like

Update the existing [Amplify Configure](https://docs.amplify.aws/cli/start/install/#option-2-follow-the-instructions) documentation page to warn people of the dangers of creating permanent keys with a link to the old (existing) documentation.

Update the page to explain the benefits of using temporary credentials and walk reader's through creating a SSO user.

### Describe alternatives you've considered

none

### Additional context

Many Amplify developers are new to AWS and just want to be up and running quickly.
Make it easy for them to get started following best practices.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment] 2023-03-09 21:18
Hey @dmost714 :wave: thanks for raising this! The ask for AWS SSO is a duplicate of https://github.com/aws-amplify/amplify-cli/issues/4488, however given this request is under a different context (changing `amplify configure`) I will leave this issue open

**Comment by josefaidt** [comment] 2023-03-09 21:20
also related https://github.com/aws-amplify/amplify-cli/issues/5782

**Comment by josefaidt** [comment] 2023-04-18 20:53
Closing in favor of tracking existing feature-request, #4488

**Closed by josefaidt** 2023-04-18 20:53 UTC
Labels: feature-request, platform, duplicate
