### ISSUE TITLE
Your socket connection to the server was not read from or written to within the timeout period

### ISSUE THREAD

**Issue by MontoyaAndres** [aws-amplify/amplify-cli#8379] opened 2021-10-07 16:26 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.0

### Amplify CLI Version

6.1.1

### What operating system are you using?

Ubuntu

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

I'm trying to upload the changes I made in the schema.graphql but the cli keeps uploading all the time... This does not change until this error appears:

Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed. An error occured during the push operation: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.

### Expected behavior

Upload changes and keep working as usually

### Reproduction steps

I'm just changing the schema. I just added to this table the @connection:

```
customFieldsByEntity: [CustomFieldsByEntity]
    @connection(keyName: "byProductParent", fields: ["id"])
```

```
type ProductParent
  @model
  @retain
  @auth(
    rules: [
      { allow: private, provider: iam, operations: [read, create, update] }
    ]
  )
  @key(name: "byAccount", fields: ["accountId"])
  @key(name: "byVendor", fields: ["vendorId"]) {
  id: ID!
  accountId: ID!
  vendorId: ID!
  externalId: ID
  type: ProductType!
  name: String!
  description: String
  status: ProductStatus!
  position: Int
  storeTime: ConditionEnum!
  maxQuantityShoppingCart: Int
  tags: String
  account: Account @connection(fields: ["accountId"])
  vendor: Vendor @connection(fields: ["vendorId"])
  images: [Image] @connection(keyName: "byProductParent", fields: ["id"])
  overridePositions: [EntityOrderOverrideCatalogue]
    @connection(keyName: "byProductParent", fields: ["id"])
  productVariants: [ProductVariants]
    @connection(keyName: "byProductParent", fields: ["id"])
  priceLists: [PriceProductByList]
    @connection(keyName: "byProductParent", fields: ["id"])
  customFieldsByEntity: [CustomFieldsByEntity]
    @connection(keyName: "byProductParent", fields: ["id"])
}
```

And added the key `byProductParent` to this table:

```
type CustomFieldsByEntity
  @model
  @retain
  @auth(
    rules: [
      { allow: private, provider: iam, operations: [read, create, update] }
    ]
  )
  @key(name: "byCustomField", fields: ["customFieldId"])
  @key(name: "byProduct", fields: ["productId"])
  @key(name: "byProductParent", fields: ["productParentId"])
  @key(name: "byProductVariants", fields: ["productVariantsId"])
  @key(name: "byStore", fields: ["storeId"])
  @key(name: "byVendor", fields: ["vendorId"]) {
  id: ID!
  customFieldId: ID!
  productId: ID
  productParentId: ID
  productVariantsId: ID
  storeId: ID
  vendorId: ID
  value: String
  customField: CustomField @connection(fields: ["customFieldId"])
  product: Product! @connection(fields: ["productId"])
  productParent: ProductParent @connection(fields: ["productParentId"])
  productVariants: ProductVariants @connection(fields: ["productVariantsId"])
  store: Store! @connection(fields: ["storeId"])
  vendor: Vendor! @connection(fields: ["vendorId"])
}
```

### Log output

![image](https://user-images.githubusercontent.com/15065852/136429110-2edce560-de96-475b-9f71-3ea30f6df2d6.png)

**Comment by yuth** [comment] 2021-10-08 23:39
We have multiple reports of this issue but haven't been able to reproduce this. Are you behind a proxy or on a metered connection (which is slow). I am marking this as duplicate of https://github.com/aws-amplify/amplify-cli/issues/4113. Feel free to update that issue with more details

**Closed by yuth** 2021-10-08 23:39 UTC
