### ISSUE TITLE
Missing AdminQueries parameter causing Amplify Push to fail after updating to CLI v4.50.0

### ISSUE THREAD

**Issue by casendler** [aws-amplify/amplify-cli#7206] opened 2021-04-29 03:32 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.16.1

### Amplify CLI Version

4.5

### What operating system are you using?

Mac Big  Sur  11.3

### Amplify Categories

auth, storage, function, api, analytics, hosting, interactions, predictions

### Amplify Commands

push

### Describe the bug

After upgrade to CLI v 4.5 and running amplify push, I receive the error: 

APIGatewayAuthStack        AWS::CloudFormation::Stack Wed Apr 28 2021 23:21:41 GMT-0400 (Eastern Daylight Time) Parameters: [AdminQueries] do not exist in the template 

I tried to manually add the parameter to APIGatewayAuthStack.json as...

 "AdminQueries": {
      "Type": "String"
    }

However, when I re-run 'amplify push' the parameter is removed at the start of the push operation resulting in the same error. I have had the AdminQueries API successfully enabled for a number of months now without issue. 

### Expected behavior

I would expect the parameter to either remain in the template or be automatically added by the CLI if AdminQueries  API is  in use. 

### Reproduction steps

1. Ran npm i -g @aws-amplify/cli  to upgrade from 4.49.0 to 4.50.0
2. Attempted an amplify push command
3. Received the error re: AdminQueries parameter
4. Added the parameter to APIGatewayAuthStack.json
5. parameter was removed  during a subsequent amplify push

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by cjihrig** [comment] 2021-04-29 12:42
Thank you for the report @casendler. I'm going to close this as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/7201, but please feel free to engage there.

**Closed by cjihrig** 2021-04-29 12:42 UTC
