### ISSUE TITLE
Access level no longer applied to the lowest granularity

### ISSUE THREAD

**Issue by krikork** [aws-amplify/amplify-cli#6203] opened 2020-12-16 21:55 UTC
**Which Category is your question related to?**
API

I was updating an existing API to allow users in a particular group to access one of two paths I expose through the API.
Comparing the template to its previous version shows that the path name was removed from the resource to which access is given. This appears less restrictive and potentially less secure than before.

Here's the output from the CLI 
```
$ amplify api update
? Please select from one of the below mentioned services: REST
? Please select the REST API you would want to update coreAPIInstructorProfile
? What would you like to do Update path
? Please select the path you would want to edit /profile
? Provide a path (e.g., /book/{isbn}): /profile
? Choose a Lambda source Use a Lambda function already added in the current Amplify project
? Choose the Lambda function to invoke by this path coreLambdaInstructorProfile
? Restrict API access Yes
? Restrict access by? Both
? Who should have access? Authenticated users only
? What kind of access do you want for Authenticated users? create, read, update, delete
? Select groups: instructors
? What kind of access do you want for instructors users? create, read, update, delete
Successfully updated resource
```

Here's a portion of the diff that was generated:

![Screen Shot 2020-12-16 at 4 38 05 PM](https://user-images.githubusercontent.com/11936077/102410540-af297d00-3fbe-11eb-9335-9d22bf893d04.png)

I had generated the original API template with an older version of the CLI (roughly mid 2020 - not sure which version exactly).

You can see that **/profile** was removed. 

This looks like an
1. Unnecessary change
2. Less granular (and potentially less secure) than the previous implementation

Can you please advise whether this was an intended change and why it was implemented?

**Amplify CLI Version** 
4.39.0

**What AWS Services are you utilizing?**
API Gateway, Lambda, DynamoDB, SNS, Cognito, S3, and others

**Provide additional details e.g. code snippets**

**Comment by akshbhu** [comment] 2021-02-05 19:41
Hi @krikork 

CLosing this as duplicate of #6113. We have raised a PR for this issue and it will be available in next release.

**Closed by akshbhu** 2021-02-05 19:41 UTC
Labels: api-rest, bug
