### ISSUE TITLE
amplify cli outputs gibberish perpetually

### ISSUE THREAD

**Issue by kjetilge** [aws-amplify/amplify-cli#9469] opened 2022-01-09 22:59 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

16.13.1

### Amplify CLI Version

I ran install less than 30 minutes ago. 

### What operating system are you using?

macos 11.6

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

My deployment was hanging after removing some models in the console. In hope of fixing it I ran the cli to try a similar change. I then followed the reccomondation made at the bottom here: [https://github.com/aws-amplify/amplify-adminui/issues/431](url)

### Amplify Categories

auth, function, api

### Amplify Commands

Not applicable

### Describe the bug

What ever command I use with amplify I get this:
![](https://user-images.githubusercontent.com/1749884/148703623-2d3c8133-6ebd-4b9e-a160-2c3478c6366d.png)

I've tried to change the node version and reinstall amplify, but the problem persist. Has anyone else seen something like this ? On the top left there is a reference to one named "carl pilcher". When I google this I get very worrisome results.

https://en-volve.com/2021/12/29/nasa-hires-top-priest-to-prepare-humanity-for-major-life-changing-announcement/
https://neonnettle.com/news/17870-nasa-hires-priest-as-life-changing-discovery-announcement-expected

### Expected behavior

I expected to se readable text.

### Reproduction steps

1. update to the latest amplify cli version (running node version 16.13.0)
2. run any amplify command

### GraphQL schema(s)

<details>

```graphql
# type Invoice @model @auth(rules: [{allow: public}]) {
#   id: ID!
#   customerID: ID @index(name: "byCustomer")
#   gross: Int
#   invoiceText: String
#   yourReference: String
#   productName: String
#   description: String
#   outstandingBalance: String
#   dueDate: AWSDate
# }

# type Customer @model @auth(rules: [{allow: public}]) {
#   id: ID!
#   name: String
#   Invoices: [Invoice] @hasMany(indexName: "byCustomer", fields: ["id"])
# }

input AMPLIFY {
  globalAuthRule: AuthRule = {allow: public}
}

# type User @aws_api_key {
#   hasLicense: Boolean
#   id_token: String!
#   eduOrgLegalName: String!
#   postalAddress: String!
#   orgNumber: Int!
#   displayName: String!
#   orgType: String!
# }

type LicenseUser @model @auth(rules: [{allow: public}]) {
  id: Int                         # licenseUserOrgnummer
  ownerOrgNumber: Int             # kommunen / You
  StartDate: AWSDate
  isGroupLicenseUser: Boolean
  yourRef: String                 # kontakt eller ressursnummer
  contactPerson: String
  contactPersonEmail: AWSEmail
  endUserQuantity: Int
  skolekode: String               # For brukere som ikke bruker feide
}

type FeideCredentials @aws_api_key {
  access_token: String
  token_type: String
  expires_in: Int
  scope: String
  id_token: String
}

type Query @aws_oidc {
  # getUser(code: String): User @function(name: "getFeideUserAuth-${env}") @aws_oidc @aws_api_key
  getFeideCredentials(code: String, redirect_uri: String): FeideCredentials @function(name: "getFeideCredentials-${env}") @aws_oidc @aws_api_key
}

```

</details>

### Log output

<details>

```
kjetilge@Kjetils-iMac-Pro ~ % ~/.amplify/logs/amplify-cli-<issue-date>.log
zsh: no such file or directory: issue-date

```

</details>

**Comment by mgabriele00** [comment] 2022-01-09 23:09
Same here

**Comment by Straubulous** [comment] 2022-01-09 23:21
This is a problem introduced by a dependent package. CLI is working on a patch now.

**Comment by mgabriele00** [comment] 2022-01-09 23:32
It still doesn't work. Also tried to uninstall and install again

**Comment by emmafass** [comment] 2022-01-10 02:02
Having the same problem

**Comment by alice-was-here** [comment] 2022-01-10 02:19
Same issue here.

**Comment by alice-was-here** [comment] 2022-01-10 02:57
FYI to anyone who has arrived here - this issue is almost certainly caused by the marak/faker thing. [More info here](https://www.theverge.com/2022/1/9/22874949/developer-corrupts-open-source-libraries-projects-affected).

**Comment by kennyjacobson** [comment] 2022-01-10 03:30
Same here. Spent so many hours thinking it was my fault and trying everything to fix it. Glad I finally found this.

**Comment by incr3m** [comment] 2022-01-10 03:37
This seems fixed now with  ` npm i @aws-amplify/cli@7.6.7 -g`

**Comment by dutziworks** [comment] 2022-01-10 10:27
> Same here. Spent so many hours thinking it was my fault and trying everything to fix it. Glad I finally found this.

Holy crap, what an idiot.

**Comment by dutziworks** [comment] 2022-01-10 10:28
> FYI to anyone who has arrived here - this issue is almost certainly caused by the marak/faker thing. [More info here](https://www.theverge.com/2022/1/9/22874949/developer-corrupts-open-source-libraries-projects-affected).

Holy crap, what an idiot.

**Comment by josefaidt** [comment] 2022-01-10 15:19
Hey y'all :wave: thanks for raising this! This issue has been fixed with the [latest release of the Amplify CLI, v7.6.7](https://github.com/aws-amplify/amplify-cli/releases/tag/v7.6.7)

For older CLI versions it appears we are able to override the dependency depending on our package manager. For `npm` we can install to a project and add an `overrides` to the `package.json`

```json
"overrides": {                                                                                                    
  "colors": "1.4.0"                                                                                               
},
"devDependencies": {
  "@aws-amplify/cli": "^7.6.3"
}
```

Closing issue as the bug has been resolved 🙂

**Closed by josefaidt** 2022-01-10 15:19 UTC
Labels: bug, dependency-issue

**Comment by laverdet** [comment] 2022-01-10 16:46
We have amplify-cli installed globally since we've run into issues in the past with local installations. We also can't use the newest version of amplify because of other issues. For us, the following worked:
```
npm uninstall @aws-amplify/cli
npm install -g colors@1.4.1 @aws-amplify/cli@7.4.5
```
