### ISSUE TITLE
Cannot return basic types in Mutations

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-cli#3070] opened 2019-12-24 14:00 UTC
**Describe the bug**
Hello,

This is my schema:

```
type Mutation {
    heartbeat: AWSTimestamp
}
```

And this is my request template:
```
#set($id = $context.identity.sub.replace("-",""))
{
  "version": "2018-05-29",
  "statements":  ["UPDATE User SET lastHeartbeat = NOW(3) WHERE userId=UNHEX('$id')",
          "SELECT cast(UNIX_TIMESTAMP(lastHeartbeat) as unsigned) as lastHeartbeat FROM User WHERE userId=UNHEX('$id')"]
}
```

Which generates (I got it using cloudwatch):
```
UPDATE User SET lastHeartbeat = NOW(3) WHERE userId=UNHEX('07aa717db41546398a14385c61a5c923')
SELECT cast(UNIX_TIMESTAMP(lastHeartbeat) as unsigned) as lastHeartbeat FROM User WHERE userId=UNHEX('07aa717db41546398a14385c61a5c923')
```

Seems right. I see the change in the data base done properly. But in the iOS app I receive this error:
`Can't serialize value (/heartbeat) : Unable to serialize `{lastHeartbeat=1577193053}` as a valid timestamp. Ensure that the value provided is an Integer that lies within the limits specified in this scalar's description.`

However, if I modify my schema to this one:

```
type Heartbeat {
    lastHeartbeat: AWSTimestamp
}

type Mutation {
    heartbeat: Heartbeat
}

```
It works perfectly.

So, unless I am missing something, I don't find a way to use a basic type in Mutations in the API.swift file.
Is this a bug? If not, what should I do to use basic types in the returned value when using Mutations?

**Amplify CLI Version**
4.2.0

**To Reproduce**
Create a mutation that returns a basic value, like AWSTimestamp
Generata API.swift with ""amplify api gql-compile""
Try to get that value in the iOS app.

**Expected behavior**
We should be able to read those basic types.

**Desktop (please complete the following information):**
 - OS: Mac.
 - Node Version: v13.2.0

**Comment by SwaySway** [comment] 2021-06-02 01:19
Closing as duplicate of https://github.com/aws-amplify/amplify-cli/issues/2199

**Closed by SwaySway** 2021-06-02 01:19 UTC
Labels: bug, graphql-transformer
