### ISSUE TITLE
Stuck at Edit you schema at or place .graphql files in a directory 

### ISSUE THREAD

**Issue by buixuanhai** [aws-amplify/amplify-cli#3440] opened 2020-02-16 16:40 UTC
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
When run amplify push. It shows message below and hang. It didn't open schema.graphl for do anything else. It' stuck.

> Edit your schema at D:\Code\myapp\amplify\backend\api\myall\schema.graphql or place .graphql files 
in a directory at D:\Code\myapp\amplify\backend\api\myapp\schema

**Amplify CLI Version**
4.13.2

**To Reproduce**
Make some change to schema and amplify push

**Expected behavior**
schema.graphql open to edit or allow to continue to push

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 1909
 - Node Version: 12.14.1

**Comment by ammarkarachi** [comment] 2020-02-19 20:23
@buixuanhai Can you open your code editor from the command line?

**Comment by buixuanhai** [comment] 2020-02-20 06:50
@ammarkarachi Yes, I can.  I am using VSCode so I use `code file_name.js` to open the file.

**Comment by kaustavghosh06** [comment] 2020-02-20 21:50
@buixuanhai We don't open up the editor after push. Can you paste your entire terminal output here?

**Comment by buixuanhai** [comment] 2020-02-23 03:26
![image](https://user-images.githubusercontent.com/9126944/75102979-f6591280-5626-11ea-8e5a-ecec2744c1aa.png)
@kaustavghosh06 Here the console log

**Comment by jhockett** [comment] 2020-03-11 23:32
Hi @buixuanhai, we have been unsuccessful so far trying to reproduce this issue. Have you had any luck since you last posted? Do you still encounter the issue on the newest version of the CLI?

**Comment by jhockett** [comment] 2020-03-18 16:45
I'm closing this issue for now since we cannot reproduce it. Please comment below if you continue to have this issue.

**Closed by jhockett** 2020-03-18 16:45 UTC
Labels: graphql-transformer, not-reproducable, pending-response, pending-triage
