### ISSUE TITLE
`OpenSearchInstanceType` allowed values are unclear

### ISSUE THREAD

**Issue by benjamindoe** [aws-amplify/amplify-cli#9956] opened 2022-03-10 20:05 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.14.0

### Amplify CLI Version

7.6.23

### What operating system are you using?

Manjaro

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

None

### Amplify Categories

auth, storage, function, api

### Amplify Commands

push

### Describe the bug

I am trying to set `OpenSearchInstanceType` in `team-provider-info.json` to a `t3` instance type. I want to note that `t2.medium.elasticsearch` does work.

If I try `t3.medium.search` (This is listed in the `AllowedValues` list in the `build/cloudformation-template.json` file), I receive the following error when pushing:
```
1 validation error detected: Value 't3.medium.search' at 'elasticsearchClusterConfig.instanceType' failed to satisfy constraint: Member must satisfy enum value set: [r6gd.12xlarge.elasticsearch, i3.2xlarge.elasticsearch, ultrawarm1.xlarge.elasticsearch, m5.4xlarge.elasticsearch, t3.xlarge.elasticsearch, m6g.xlarge.elasticsearch, i3.4xlarge.elasticsearch, m3.large.elasticsearch, m6g.12xlarge.elasticsearch, r4.16xlarge.elasticsearch, t2.micro.elasticsearch, m4.large.elasticsearch, r6gd.16xlarge.elasticsearch, d2.2xlarge.elasticsearch, t3.micro.elasticsearch, m5.large.elasticsearch, i3.8xlarge.elasticsearch, i3.large.elasticsearch, d2.4xlarge.elasticsearch, t2.small.elasticsearch, c4.2xlarge.elasticsearch, t3.small.elasticsearch, c5.2xlarge.elasticsearch, c4.4xlarge.elasticsearch, c6g.2xlarge.elasticsearch, d2.8xlarge.elasticsearch, c5.4xlarge.elasticsearch, t4g.medium.elasticsearch, c6g.4xlarge.elasticsearch, c6g.xlarge.elasticsearch, m3.medium.elasticsearch, c6g.12xlarge.elasticsearch, c4.8xlarge.elasticsearch, c4.large.elasticsearch, c5.xlarge.elasticsearch, c5.large.elasticsearch, t4g.small.elasticsearch, c4.xlarge.elasticsearch, c5.9xlarge.elasticsearch, c6g.8xlarge.elasticsearch, c6g.large.elasticsearch, d2.xlarge.elasticsearch, ultrawarm1.medium.elasticsearch, t3.nano.elasticsearch, t3.medium.elasticsearch, m6g.2xlarge.elasticsearch, t2.medium.elasticsearch, t3.2xlarge.elasticsearch, c5.18xlarge.elasticsearch, m6g.4xlarge.elasticsearch, i3.xlarge.elasticsearch, r6gd.2xlarge.elasticsearch, i2.xlarge.elasticsearch, r3.2xlarge.elasticsearch, r4.2xlarge.elasticsearch, m5.xlarge.elasticsearch, m4.10xlarge.elasticsearch, r6gd.4xlarge.elasticsearch, r6g.2xlarge.elasticsearch, r3.4xlarge.elasticsearch, r5.2xlarge.elasticsearch, m5.12xlarge.elasticsearch, m4.xlarge.elasticsearch, m6g.8xlarge.elasticsearch, m6g.large.elasticsearch, r4.4xlarge.elasticsearch, m5.24xlarge.elasticsearch, m3.xlarge.elasticsearch, r6g.4xlarge.elasticsearch, i3.16xlarge.elasticsearch, t3.large.elasticsearch, r5.4xlarge.elasticsearch, ultrawarm1.large.elasticsearch, m3.2xlarge.elasticsearch, r6gd.8xlarge.elasticsearch, r6gd.large.elasticsearch, r6g.xlarge.elasticsearch, r3.8xlarge.elasticsearch, r3.large.elasticsearch, r5.xlarge.elasticsearch, m4.2xlarge.elasticsearch, r6g.12xlarge.elasticsearch, r4.8xlarge.elasticsearch, r4.xlarge.elasticsearch, r4.large.elasticsearch, r5.12xlarge.elasticsearch, m5.2xlarge.elasticsearch, r6gd.xlarge.elasticsearch, r6g.8xlarge.elasticsearch, r6g.large.elasticsearch, i2.2xlarge.elasticsearch, r3.xlarge.elasticsearch, r5.24xlarge.elasticsearch, r5.large.elasticsearch, m4.4xlarge.elasticsearch]
```
If I try `t3.medium.elasticsearch` (Listed in the suggested types of the previous error report), I receive the following error:
```
Parameter 'OpenSearchInstanceType' must be one of AllowedValues
```

### Expected behavior

Either `t3.medium.elasticsearch` or `t3.medium.search` should work but not neither. I can only imagine there are more `AllowedTypes` that are incorrectly listed or even absent.

### Reproduction steps

1. Add GraphQL API with a searchable type
2. set OpenSearchInstanceType `t3.medium.elasticsearch` or `t3.medium.search`
3. Run `amplify push`

**Comment by CodySwannGT** [comment] 2022-03-11 01:24
Related to https://github.com/aws-amplify/amplify-cli/issues/9775

**Comment by sundersc** [comment] 2022-03-12 05:37
As per [this doc](https://aws.amazon.com/opensearch-service/pricing/), t3.medium.search instance type is supported in most of the regions. Could you confirm the below?
- What's the AWS region?
- What's the transformer version?

**Comment by CodySwannGT** [comment] 2022-03-12 06:46
@sundersc us-east-1 and version 1 for me

**Comment by benjamindoe** [comment] 2022-03-14 09:52
@sundersc eu-west-1

**Comment by benjamindoe** [comment] 2022-03-15 16:33
@CodySwannGT If it's blocking your deployment I'd suggest you just use `t2.medium.elasticsearch` while the Amplify team get round to fixing this. I've played around with changing instance sizes between deployments and it seems CFM handles unmounting and mounting drives works quite seemlessly so when `t3.medium.search` is ready I'll be switching to that.

**Comment by CodySwannGT** [comment] 2022-03-15 16:38
@benjamindoe the problem is we paid for a t3.medium.search reserved instance, so if we go with anything else, we're essentially wasting money.

**Comment by benjamindoe** [comment] 2022-03-15 16:39
@CodySwannGT  Ah, that sucks

**Comment by sundersc** [comment] 2022-03-15 20:25
There seems to be some confusion between what instance types documented in OpenSearch docs and what CFN allows. I'm checking with OpenSearch team on this.

**Comment by Straubulous** [comment] 2022-03-25 18:33
The fix for this will also fix https://github.com/aws-amplify/amplify-cli/issues/8572

**Closed** 2022-03-30 16:11 UTC
Labels: bug, @searchable, p2
