### ISSUE TITLE
How do I make Amplify backend deployed by CDK with AmplifyExportedBackend visible in Amplify Console/Studio?

### ISSUE THREAD

**Issue by mmitchan** [aws-amplify/amplify-cli#12342] opened 2023-03-30 13:34 UTC
### Which Specific Feature is your question related to?

Amplify CDK AmplifyExportedBackend visibility in Amplify Console/Studio

### Question

I have successfully deployed my Amplify Stack via CDK using  AmplifyExportedBackend.  I can see all of the components of the stack individually, and I can see the API instructions in AppSync.  However, there is no backend application visible in Amplify Console/Studio.

Is there something that I need to include in my CDK (TypeScript code) to associate the CDK-deployed backend stack with Amplify Console/Studio?

**Comment by ykethan** [comment] 2023-03-31 23:10
duplicate of https://github.com/aws-amplify/amplify-cli/issues/12342, closing this issue to prevent any misinformation.

**Closed by ykethan** 2023-03-31 23:10 UTC
Labels: question, pending-triage, transferred
