### ISSUE TITLE
Parameters shared between multiple lambda functions

### ISSUE THREAD

**Issue by maziarzamani** [aws-amplify/amplify-cli#9456] opened 2022-01-07 13:18 UTC
### Is this feature request related to a new or existing Amplify category?

function

### Is this related to another service?

Lambda

### Describe the feature you'd like to request

I am currently working on a AppSync API with numerous Lambda functions. However I am sharing similar secrets between many of these lambda functions. As far as I can see I need to create a unique secret parameter for each individual lambda function which will cause a massive amount of redundant and duplicated parameters making it cumbersome to do updates.

### Describe the solution you'd like

I would like to be able to add secrets or other variables that can be shared between multiple lambda functions.

Perhaps a solution would be have the ability to add parameters independent from a `function` and then applying the policies from a `function` to the `parameter`. 

### Describe alternatives you've considered

Adding an SSM manually, but this will require setting up policies manually to obtain access to the parameter, which is again not super ideal.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cjihrig** [comment] 2022-01-07 16:17
Thanks for opening this. I'm going to close it as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/8360. Please provide any additional information on that ticket.

**Closed by cjihrig** 2022-01-07 16:17 UTC
Labels: functions, feature-request, duplicate
