### ISSUE TITLE
Failed to authenticate: `Cannot read property 'message' of undefined`

### ISSUE THREAD

**Issue by plisy** [aws-amplify/amplify-cli#10716] opened 2022-07-07 21:32 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

curl

### If applicable, what version of Node.js are you using?

v18.2.0

### Amplify CLI Version

9.1.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

Not applicable

### Amplify Commands

pull

### Describe the bug

Following intro tutorial I tried doing a pull

``` sh
amplify pull --appId <app_id> --envName staging
```

I was presented with a prompt for authentication
```
Confirm login in the browser or manually paste in your CLI login key:
```
and the site was opened `https://us-east-2.admin.amplifyapp.com/admin/<app_id>/staging/verify/?loginVersion=1` in Safari.

After copying and pasting the key I received error

```
Failed to authenticate: Cannot read property 'message' of undefined
```

and a new prompt

```
? Select the authentication method you want to use: Amplify Studio
```

After that I got a new error message 

```
Failed to get credentials: Current environment cannot be determined
Use 'amplify init' in the root of your app directory to initialize your project with Amplify
```

`amplify pull --appId <app_id> --envName staging` now ends up in

```
🛑 File at path: '/Users/plisy/source/plisy/react-amplified/amplify/cli.json' does not exist
Error: File at path: '/Users/plisy/source/plisy/react-amplified/amplify/cli.json' does not exist
    at Function.readJson (/snapshot/repo/build/node_modules/amplify-cli-core/lib/jsonUtilities.js:40:19)
    at StateManager.getData (/snapshot/repo/build/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:309:56)
    at StateManager.getCLIJSON (/snapshot/repo/build/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:254:25)
    at DebugConfig.getCLIJson (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/app-config/debug-config.js:31:48)
    at DebugConfig.writeShareProjectConfig (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/app-config/debug-config.js:44:30)
    at DebugConfig.setAndWriteShareProject (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/app-config/debug-config.js:66:14)
    at reportError (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/diagnose.js:55:49)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:168:13)
```

like #10686 

> The project was initially pulled from a sandbox with `amplify pull --sandboxId <sandbox_id>`

### Expected behavior

Authenticated without errors, things get pulled.

### Reproduction steps

N/A

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by danielleadams** [comment] 2022-07-07 21:51
Hi @plisy - what version of macOS are you using (ie. 12.x or 13.x)? And what processor are you using? (ie. Intel or M1) Thanks!

**Comment by plisy** [comment] 2022-07-07 21:52
M1 Mac 12.3.1 (21E258)

**Comment by Straubulous** [comment] 2022-07-07 22:04
@plisy  - can you run `amplify diagnose --send-report` and post the project ID that is displayed when it is done?

**Comment by plisy** [comment] 2022-07-07 22:07
@Straubulous I don't see a project ID in the output

```
 amplify diagnose --send-report                                                main

Learn more at https://docs.amplify.aws/cli/reference/diagnose/
✔ An unexpected error has occurred, opt in to send an error report to AWS Amplify with non-sensitive project configuration files. Confirm  (y/N) · yes


Learn more at https://docs.amplify.aws/cli/reference/diagnose/

This project has been opted in automatically to share non-sensitive project configuration files. you can opt out by running 'amplify diagnose --auto-send-off'
🛑 File at path: '/Users/plisy/source/plisy/react-amplified/amplify/cli.json' does not exist
Error: File at path: '/Users/plisy/source/plisy/react-amplified/amplify/cli.json' does not exist
    at Function.readJson (/snapshot/repo/build/node_modules/amplify-cli-core/lib/jsonUtilities.js:40:19)
    at StateManager.getData (/snapshot/repo/build/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:309:56)
    at StateManager.getCLIJSON (/snapshot/repo/build/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:254:25)
    at DebugConfig.getCLIJson (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/app-config/debug-config.js:31:48)
    at DebugConfig.writeShareProjectConfig (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/app-config/debug-config.js:44:30)
    at DebugConfig.setAndWriteShareProject (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/app-config/debug-config.js:66:14)
    at reportError (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/diagnose.js:55:49)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:168:13)
```

**Comment by plisy** [comment] 2022-07-07 22:27
I'm also using iTerm (v3.4.16). Might be relevant for the key pasting part of auth.

**Comment by plisy** [comment] 2022-07-07 22:55
@lazpavel when I go through the default MacOS terminal app, not iTerm, things work out.

**Comment by lazpavel** [comment] 2022-07-07 22:59
hey @plisy, thank you for letting us know, I was actually testing in iTerm, do you mind sharing with us your iTerm version? thank you

**Comment by plisy** [comment] 2022-07-07 23:07
Now that I got it working with the default Terminal app, I'm unblocked - even in iTerm, but I still get the `Failed to authenticate: Cannot read property 'message' of undefined` error.

> Pasting with stripped formatting through clipboard manager has no effect. Tried it in case Safari was adding some trash to the key.

**Comment by lazpavel** [comment] 2022-07-07 23:09
as a workaround are you able to set your default browser to something like Firefox or Chrome while running the `amplify pull...` command?

**Comment by plisy** [comment] 2022-07-07 23:38
Yes. That did the job.

**Comment by josefaidt** [comment] 2022-07-15 19:57
Closing due to issue being not reproducible and customer is unblocked

**Closed by josefaidt** 2022-07-15 19:57 UTC
Labels: platform, not-reproducible
