### ISSUE TITLE
golang functions don't build

### ISSUE THREAD

**Issue by jnathanh** [aws-amplify/amplify-cli#3892] opened 2020-04-07 20:05 UTC
**Describe the bug**
golang functions don't build

**Amplify CLI Version**
4.18.0

**To Reproduce**
Create helloworld function
```bash
$ amplify add function
Using service: Lambda, provided by: awscloudformation
? Provide a friendly name for your resource to be used as a label for this category in the project: helloworld
? Provide the AWS Lambda function name: helloworld
? Choose the function runtime that you want to use: Go
Only one template found - using Hello World by default.
? Do you want to access other resources created in this project from your Lambda function? No
? Do you want to invoke this function on a recurring schedule? No
? Do you want to edit the local lambda function now? No
```
try to build:
`$ amplify mock function helloworld`

> .../amplify/backend/function/helloworld/bin-local" already exists and is a directory

`$ amplify build function helloworld`

> .../amplify/backend/function/helloworld/bin" already exists and is a directory

**Expected behavior**
No errors on build

**Desktop:**
 - OS: macOS Catalina 10.15.3
 - Node Version. v13.12.0

**Additional context**
I don't see the conflicting directories the error refers to, so I assume it is created during the build, then deleted

**Comment by SwaySway** [comment] 2020-04-07 20:40
Hello @jnathanh 
Do you have go installed?

**Comment by SwaySway** [comment] 2020-04-07 21:04
Hello @jnathanh what type of message do you see you when you try use `amplify mock function helloworld` ?

**Comment by jnathanh** [comment] 2020-04-08 02:16
@SwaySway I put the error message under both example commands that try to build. For the mock case, it says 

> .../amplify/backend/function/helloworld/bin-local" already exists and is a directory

The full output is

> $ amplify mock function helloworld
? Provide the path to the event JSON object relative to /Users/nhanna/code/go/src/github.com/jnathanh/threes/amplify/backend/function/helloworld src/event.json
Starting execution...
go build command-line-arguments: build output "/Users/nhanna/code/go/src/github.com/jnathanh/threes/amplify/backend/function/helloworld/bin-local" already exists and is a directory
helloworld failed with the following error:
Error: Command failed with exit code 1: go build -o /Users/nhanna/code/go/src/github.com/jnathanh/threes/amplify/backend/function/helloworld/bin-local main.go
    at makeError (/usr/local/Cellar/node/13.12.0/lib/node_modules/@aws-amplify/cli/node_modules/execa/lib/error.js:58:11)
    at Object.module.exports.sync (/usr/local/Cellar/node/13.12.0/lib/node_modules/@aws-amplify/cli/node_modules/execa/index.js:188:17)
    at Object.exports.executeCommand (/usr/local/Cellar/node/13.12.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-go-function-runtime-provider/lib/runtime.js:26:26)
    at Object.exports.buildResourceInternal (/usr/local/Cellar/node/13.12.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-go-function-runtime-provider/lib/runtime.js:85:17)
    at Object.exports.localInvoke (/usr/local/Cellar/node/13.12.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-go-function-runtime-provider/lib/localinvoke.js:52:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /usr/local/Cellar/node/13.12.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/index.js:110:31 {
  shortMessage: 'Command failed with exit code 1: go build -o /Users/nhanna/code/go/src/github.com/jnathanh/threes/amplify/backend/function/helloworld/bin-local main.go',
  command: 'go build -o /Users/nhanna/code/go/src/github.com/jnathanh/threes/amplify/backend/function/helloworld/bin-local main.go',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Finished execution.

**Comment by SwaySway** [comment] 2020-04-13 21:39
I was not able to reproduce this error.
If you delete the `bin` folder in your project and do a rebuild does it recreate it?

**Comment by mkmurali** [comment] 2020-04-16 21:01
I could get the build working by locally updating the runtime.js file directly to fix the path, on mac. Didn't get a chance to fully all other options, so will create a PR once ready. But if you want to try, you may try these changes: https://github.com/mkmurali/amplify-cli/commit/977e7756709a790bd685c9fb4815838956d24db2

**Comment by jnathanh** [comment] 2020-04-19 19:32
> I was not able to reproduce this error.
> If you delete the `bin` folder in your project and do a rebuild does it recreate it?

@SwaySway The `bin` and `bin-local` directories don't exist right after the function is created, only after the first attempt to build. Deleting them then building again also gives the same error.

**Comment by jnathanh** [comment] 2020-04-19 20:10
> I could get the build working by locally updating the runtime.js file directly to fix the path, on mac. Didn't get a chance to fully test all other options, so will create a PR once test if this breaks anything. But @jnathanh if you want to try, you may try these changes: [mkmurali@977e775](https://github.com/mkmurali/amplify-cli/commit/977e7756709a790bd685c9fb4815838956d24db2)

@mkmurali I tried using your fork with the same result as before, however I'm not confident that I executed it properly. How did you run amplify with your fork? I used this command: `npx -p amplify -c "amplify mock function helloworld" github:mkmurali/amplify-cli`

**Comment by mkmurali** [comment] 2020-04-20 17:03
@jnathanh Not sure if there are any issues with resolving amplify dependencies when using npx. I am using the exact same command "amplify mock function <funcname>".  However, I updated the local version of runtime.js file and have been using for both builds and mocks just fine.

**Comment by nhanna-suplari** [comment] 2020-04-21 16:26
@mkmurali k, I ended up just manually editing the code as well and your fix works, for mock and normal builds.

@SwaySway see @mkmurali 's fix. It looks like the target bin folder is pre-created at some point during the build script, but if you pass a directory to the `-o` option of the `go build` command it expects that it has to create the folder or throws the error if the folder already exists. Changing the `-o` to reference a target file appears to work just fine. I'm not sure how this was working for anyone. Probably a change in the `-o` behavior between go versions? I'm running go version go1.12.13 darwin/amd64

**Comment by attilah** [comment] 2020-04-27 16:47
@jnathanh @nhanna-suplari could you please try with go 1.14 in your local environment, as 1.14 was the latest version that was used during development, perhaps the minimum dependency will be changed to 1.14 if go has such path handling issues.

**Closed** 2020-04-27 17:12 UTC
Labels: bug, functions

**Comment by jnathanh** [comment] 2020-05-30 22:24
@attilah sorry for the late response. I confirmed that `go version 1.14.3` and `go version `1.13.10` both worked. I agree it's reasonable to not support archived go versions. Thanks!
