### ISSUE TITLE
Cannot read property 'accessKeyId' of undefined, after latest update

### ISSUE THREAD

**Issue by adcanis** [aws-amplify/amplify-cli#10367] opened 2022-05-05 16:46 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm 

### If applicable, what version of Node.js are you using?

17.7.1

### Amplify CLI Version

8.1.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

N/A

### Amplify Categories

auth, api

### Amplify Commands

pull, push, status

### Describe the bug

After running 
`aws-vault exec foo`
When performing an amplify command, error 
`Failed to get profile: Cannot read property 'accessKeyId' of undefined`
presents itself. 

If I remove aws-vault, and create a credentials file in my `~/.aws` folder and add the credentials there, I get a different error:
`Name: ResourceNotFoundException : Message: User pool **-******-******** does not exist.`

### Expected behavior

The command(s) should work

### Reproduction steps

Using AWS-VAULT 
1. aws-vault exec foo
All commands there after present error

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment] 2022-05-05 16:58
Hey @adcanis :wave: when using the AWS credentials and config files, can you confirm the region is set to the region which the Amplify app is deployed to?

**Comment by josefaidt** [comment] 2022-05-05 17:21
Hey @adcanis thanks for the clarification! In your amplify app's directory what Amplify CLI command are you executing to receive the "user pool ... does not exist" error? Is this on `push`?

**Comment by adcanis** [comment] 2022-05-05 17:23
@josefaidt it doesn't matter what command, even `status`.

**Comment by josefaidt** [comment] 2022-05-05 22:22
Hey @adcanis based on the error for "Cognito does not exist" it appears the Amplify CLI is successfully authenticating however is not able to find the resource in the specified account and region. If this is an existing project you have locally, is it possible the `amplify/.config/local-aws-info.json` file is pointing to a unintended profile for this environment?

```json
{
  "dev": {
    "configLevel": "project",
    "useProfile": true,
    "profileName": "default"
  }
}
```

**Comment by adcanis** [comment] 2022-05-05 23:23
@josefaidt thats just it. Everything is as it should be. Project works as expected, user pool authentication works and all that. I did a bit of updates to the schema today in regards to some resolvers, went to push, updated the cli and then this error

**Comment by josefaidt** [comment] 2022-05-09 18:14
Hey @adcanis can you confirm the Cognito User Pool ID shown in `amplify/backend/amplify-meta.json` at `auth.<resource-name>.output.UserPoolId` matches that of which we are seeing in the Console?

**Comment by adcanis** [comment] 2022-05-09 18:23
@josefaidt my file inside the `backend/auth/appname` is parameters.json which shows the following 
`{
  "authSelections": "userPoolOnly",
  "resourceName": "****************",
  "serviceType": "imported",
  "region": "ca-central-1",
  "authProvidersUserPool": [],
  "requiredAttributes": [],
  "passwordPolicyMinLength": 8,
  "passwordPolicyCharacters": [
    "Requires Lowercase",
    "Requires Uppercase",
    "Requires Numbers",
    "Requires Symbols"
  ],
  "mfaConfiguration": "OPTIONAL",
  "autoVerifiedAttributes": [
    "email"
  ],
  "mfaTypes": [
    "SMS Text Message",
    "TOTP"
  ]
}`

This was the order in my commands prior to the error:

`amplify status` 
no error was received. 
seen the update to the cli and ran the update before pushing the change **should of pushed before**

then I ran `amplify api gql-compile` without issue

went to run `amplify push -y` and received the first error about failed to get accesskeyId. Thats when I unset aws_vault, and exec'd with the credentials as usual. Ran `amplify push -y` again and received the same error. 
After unsetting my aws_vault again, I created the credentials file and added the credentials there which then through the cognito error

**Comment by josefaidt** [comment] 2022-05-10 20:15
Hey @adcanis thanks for the clarification! I was looking to see if we potentially have a mismatch of Cognito ID's in our local copy versus what we're seeing in the AWS Console for Cognito. Do you also have a supplemental `~/.aws/config` that specifies the intended regions for the profiles?

**Comment by adcanis** [comment] 2022-05-10 20:47
So the `~/.aws/config`looks like this 

`

[profile foo ]
output=json
region=ca-central-1

[profile foo-dev]
source_profile=foo 
role_arn=arn:aws:iam::[AWS_ACCOUNT_NUMBER]:role/foo-dev-admin
`

And so on with the subsequent profiles. 
Keep in mind, I wasn't using a credentials file until this error, I was using AWS-vault to set my credentials without issue.

**Comment by josefaidt** [comment] 2022-05-10 21:56
Hey @adcanis to clarify further are you attempting to use temporary credentials with the Amplify CLI?

**Comment by adcanis** [comment] 2022-05-10 21:59
That's how I've always done it yes. At least with this project specifically

**Comment by m98** [comment] 2022-05-10 22:14
I have the same issue. I try to pull and I get the ` Cannot read property 'accessKeyId' of undefined` error!
![image](https://user-images.githubusercontent.com/7496103/167729710-72a73373-c9fd-4910-a905-2ddaab0a853a.png)

I tried to change the credentials with a new one by running `amplify configure` and that did not help either!

**Comment by adcanis** [comment] 2022-05-10 22:15
@m98 dis you update to the latest cli as well?

**Comment by m98** [comment] 2022-05-10 22:30
Yes. I use version 8.1.0 which is the latest version on NPM.

**Comment by m98** [comment] 2022-05-12 15:19
For me, the problem was solved when I deleted the `amplify` directory and `aws-exports.js` (I think only deleting the `amplify` directory should be enough)

**Comment by adcanis** [comment] 2022-05-12 15:22
@m98 Good to know. I will try that today and do a pull. Just to confirm, are you running aws-vault to set temp credentials or are you using a credentials file?

**Comment by adcanis** [comment] 2022-05-13 12:46
@josefaidt @m98 Just wanted to say thanks for all the help. The resolution seems to be to remove the `amplify` directory and `aws-exports.js` file as @m98 mentioned. In my case I did not init, but rather pulled the existing project in.

**Comment by josefaidt** [comment] 2022-05-13 19:37
Hey @adcanis and @m98 that is an interesting find. Are you able to capture the git diff of `amplify/.config/project-info.json`? I'm curious in knowing if we can reproduce this behavior and permanently resolve from our end

**Comment by adcanis** [comment] 2022-05-13 19:44
@josefaidt ill take a look. Funny enough this has opened up an entire other issue. I removed the folder and exports file as stated and ran `amplify pull --appId ******** --envName ***` no more credentials issue. `amplify status` doesn't show the errors and AWS-vault seems to be setting credentials just fine. 

I now get a 400 error on my cognito and all users can't log in. Nothing has changed.

**Comment by vkanagarajan** [comment] 2022-05-16 06:03
amplify status not getting any error 

amplify push
i am getting same error 

Failed to get profile: Cannot read property 'accessKeyId' of undefined

**Comment by josefaidt** [comment] 2022-05-16 20:13
Hey @adcanis thank you for clarifying and I'm glad to hear that you're able to mitigate the issue. For the authentication issue would you mind creating a separate bug report for that? Does the `aws-exports.js` file still point to the older auth resource?

@vkanagarajan can you paste the contents of `amplify/.config/local-aws-info.json` omitting any sensitive information? For example, my sample application's file looks like:

```json
{
  "dev": {
    "configLevel": "project",
    "useProfile": true,
    "profileName": "default"
  }
}
```

**Comment by adcanis** [comment] 2022-05-16 20:29
@josefaidt ill open a new bug report on the cognito front. It appears to be coming from the setTOTP and prefferedMFA function. `aws-exports` is correct depending on what auth I bring in to correct the issue. Thanks for the help!

**Comment by Booligoosh** [comment] 2022-05-17 02:07
Can confirm that deleting the `amplify` directory and then running `amplify pull --appId ******** --envName ***` to grab my backend files again fixed the issue for me with no issues.

**Comment by vkanagarajan** [comment] 2022-05-17 09:25
> 
amplify/.config/local-aws-info.json file i am having this same code 
{
  "dev": {
    "configLevel": "project",
    "useProfile": true,
    "profileName": "default"
  }
}

**Comment by adcanis** [comment] 2022-05-17 09:29
@vkanagarajan have you tried deleting your `amplify` directory, the `aws-exports` file from `src` and running `amplify pull --appID ***** --envName ****`?

**Comment by adcanis** [comment] 2022-05-17 12:19
@scottbw have you ran `unset AWS_VAULT` followed by `aws-vault clear` in-order to remove any temp credentials and session?

**Comment by scottbw** [comment] 2022-05-17 12:31
I've never used aws-vault, so there's nothing to clear.

Steps:
1. Delete everything
2. amplify pull --appId {app} --envName staging
4. amplify pull -y

Result:
⠏ Fetching updates to backend environment: staging from the cloud.? 
Select the authentication method you want to use: AWS profile
Failed to get profile: Cannot read property 'accessKeyId' of undefined

**Comment by adcanis** [comment] 2022-05-17 12:59
@scottbw Can you confirm that your `~/.aws/config` and `~/.aws/credentials` look similar to the following? 

`**~/.aws/config**`
`[profile <YOUR PROFILE NAME>]
output=json
region=<YOUR AWS REGION>
`
_if your using assumed roles ie. dev, qa, production_

`
[profile  <YOUR PROFILE>-dev]
source_profile=<YOUR MAIN PROFILE>
role_arn=arn:aws:iam::********:role/<YOUR_APP-DEV-ADMIN>
`

`**~/.aws/credentials**`
`
[<YOUR PROFILE NAME>]
aws_access_key_id=*************
aws_secret_access_key=***********************
`

**Comment by scottbw** [comment] 2022-05-17 13:02
Correct, thats how they look.

**Comment by vkanagarajan** [comment] 2022-05-17 17:50
> @vkanagarajan have you tried deleting your `amplify` directory, the `aws-exports` file from `src` and running `amplify pull --appID ***** --envName ****`?

amplify pull --appID ***** --envName ****
? Select the authentication method you want to use: (Use arrow keys)
❯ AWS profile 
  AWS access keys 
Which one i have to select  AWS profile  or AWS access keys  ?

**Comment by adcanis** [comment] 2022-05-17 17:52
@vkanagarajan do you not have a credentials and config file set?

**Comment by vkanagarajan** [comment] 2022-05-17 17:56
> @vkanagarajan do you not have a credentials and config file set?

Yes , ~/.aws/config   and ~/.aws/credentials having in my system

**Comment by scottbw** [comment] 2022-05-17 18:47
In  the end, I had to completely get rid of my app's backend in the AWS UI console, and start again from scratch with a brand new backend as I was losing far too much time over this. No idea what went wrong or how it got so badly out of sync.

**Comment by josefaidt** [comment] 2022-05-19 20:47
Hey @vkanagarajan I was able to reproduce this if I point my profileName in `amplify/.config/local-aws-info.json` to a profile name that does not exist on my machine:

```json
{
  "dev": {
    "configLevel": "project",
    "useProfile": true,
    "profileName": "doesnotexist"
  }
}
```

Can you confirm the profile `default` exists within your AWS configuration at `~/.aws/credentials`?

**Comment by vkanagarajan** [comment] 2022-05-20 07:38
I have fixed this issue  created new user and added the access and secret key

**Comment by m98** [comment] 2022-05-20 09:15
@josefaidt In my case, I guess maybe the [AWS Toolkit](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.aws-toolkit-vscode) for my IDE caused this! With that you can rename the credintials! 

It's good to know if other people in this thread who had this issue were also using AWS Toolkit!

**Comment by josefaidt** [comment] 2022-05-25 17:40
Hey @vkanagarajan glad to hear you're back up and running, and thanks @m98 for chiming in here! I'm glad to hear you've found value out of this thread!

Given the issue is now resolved I will close this for now, however if this issue reappears please reply back to this thread and we can re-open to investigate further 🙂

**Comment by slim-elephant** [comment] 2022-08-11 22:57
I faced the same issue, sorted out by doing the following.

Under Amplify -> .config -> local-aws-info.json profile name was defined as ABC whereas new profile I created did not match the name. Simple went to ~/Users/username/.aws/ and changed profile name in credentials and config file to match the project. Or you can do the other way around if profile is being used by multiple projects or define a new profile with matching name,

**Comment by makyfj** [comment] 2022-09-15 17:56
I'm using @aws-amplify/cli v10.0.0. I did `amplify init` and then I selected `credentials` instead of `profile` and finally I inserted my `accessKeyId` and my `secretAccessKeyId`.

**Comment by josefaidt** [comment] 2022-09-19 21:51
Hey folks I've reopened this issue as a feature request to potentially expose a `--profile` flag when using headless CLI locally, as this is failing due to the lack of a `default` profile.

**Comment by nickvankleeck** [comment] 2022-09-23 17:05
The same bug now appears when performing the steps in Module 1 of the AWS tutorial "Deploy a Web Application on AWS Amplify" here: https://aws.amazon.com/getting-started/guides/deploy-webapp-amplify/module-one/.

**Comment by ehounder** [comment] 2022-11-10 03:06
I get this same error with this same tutorial - after creating a new user with all privileges and new accessKeyID:

`Project information
| Name: amplifyapp
| Environment: dev
| Default editor: Visual Studio Code
| App type: javascript
| Javascript framework: react
| Source Directory Path: src
| Distribution Directory Path: build
| Build Command: npm run-script build
| Start Command: npm run-script start

Using default provider  awscloudformation
Failed to get profile: Cannot read property 'accessKeyId' of undefined
xxxyyy@zzzz-MacBook-Pro-2 amplify-app %`

**Comment by letsbelopez** [comment] 2023-01-06 22:26
I'm getting this error in CI/CD pipeline running `amplify-dev pull`.

I have configured my default profile credentials using `aws configure set` command and in my --providers flag I selected to use a profile and use one called default.

**Comment by mguja-fcc** [comment] 2023-02-27 18:58
I am getting the same error ⠋ Fetching AWS Amplify Console domains🛑 Failed to get profile credentials
Cannot read property 'accessKeyId' of undefined when upgraded my Aplify CLI from version 7.6.21 to 10.8.0

**Comment by lazpavel** [comment] 2023-03-14 21:44
Hi @armenr, it looks that in your example you have some extra quotes after the `"awscloudformation":` argument, this command should work for you: 
`amplify pull --providers '{"awscloudformation":{"configLevel":"project","useProfile":true,"profileName":"stelth-dev"}}' --amplify '{"appId":"REDACTED","envName":"develop"}' --yes`

We already support passing profile name as the `profileName` under the `awscloudformation` as documented here: https://docs.amplify.aws/cli/usage/headless/#--providers.

Nonetheless, this error message is terribly misleading, and we need to improve how we parse the command line arguments as a separate task.

As a workaround to generate the correct syntax, I can suggest using the scripts from our documentation page and add `set +x` after `set -e` command to print the executed command after it's assembled.

**Closed by lazpavel** 2023-03-14 21:44 UTC
Labels: feature-request, platform, pending-review, p3

**Comment by DaichiShirakawa** [comment] 2023-04-19 23:55
Hi guyz, I melt 3hours for this fucking problem:

```sh
$ amplify status # same for amplify publish

...

🛑 Failed to get profile credentials
Cannot read property 'accessKeyId' of undefined
```

And finally resolved it as below procedure with my profile set in `~/.aws/credentials`:

```
$ amplify configure project
# > AWS Profile setting
# > Update AWS Profile
# > AWS profile
# > (Select your profile)
```

**Comment by righteousgambit** [comment] 2023-04-24 23:05
ok - I'm using an SSO profile to deploy. I run `amplify init` using a named profile `appdeploy`. No matter whether I call the --profile flag when I run `amplify init` and select `appdeploy` as the aws profile or not...it believes the access_key_id is "undefined". However, when I change the name of that profile to default...all of a sudden it works.


There is clearly an bug for (at least) `amplify init` whereby under certain conditions, it won't recognize any profile other than default.

**Comment by codenimble** [comment] 2025-02-08 22:45
Ugh just ran into this as well.

**Comment by samp-reston** [comment] 2025-04-12 11:14
Still running into this
