### ISSUE TITLE
Build Error when deploying hello world lambda

### ISSUE THREAD

**Issue by hammadj** [aws-amplify/amplify-cli#904] opened 2019-02-20 09:37 UTC
**Describe the bug**
Backend build fails when trying to deploy the hello world Lambda.

**To Reproduce**
- I set up my project with Amplify and connected my GitHub repo to automate deployments.
- The build in the Amplify console succeeded without any issues.
- I added a lambda to my project using `amplify add function` and used the "Hello world function" template
![image](https://user-images.githubusercontent.com/7143583/53081410-0c823f00-34b8-11e9-9167-840023501080.png)
- I made no changes to the template, just pushed the code to github to trigger a build. However, this build failed.
- running `amplify function build` or `amplify function invoke addressAutocomplete` works fine locally

**Expected behaviour**
Build should succeed, especially when I didn't do anything on my own and all the generated code was through the CLI.

**Additional context**
Here was the error in the Backend step of the build in the Amplify console:
```
# Starting phase: build
2019-02-20T09:15:28.775Z [INFO]: # Executing command: export STACKINFO={ "awscloudformation": { "AuthRoleName": "zero-amplify-20190219171557-authRole", "UnauthRoleArn": "arn:aws:iam::171535808574:role/zero-amplify-20190219171557-unauthRole", "AuthRoleArn": "arn:aws:iam::171535808574:role/zero-amplify-20190219171557-authRole", "Region": "ap-southeast-2", "DeploymentBucketName": "zero-amplify-20190219171557-deployment", "UnauthRoleName": "zero-amplify-20190219171557-unauthRole", "StackName": "zero-amplify-20190219171557", "StackId": "arn:aws:cloudformation:ap-southeast-2:171535808574:stack/zero-amplify-20190219171557/b2c16350-34a4-11e9-ba48-028d024c9854" } }
2019-02-20T09:15:28.780Z [INFO]: # Executing command: amplifyPush --environment prod
2019-02-20T09:15:28.782Z [INFO]: # Start initializing Amplify environment: prod
2019-02-20T09:15:28.783Z [INFO]: # Importing Amplify environment: prod (amplify env import)
2019-02-20T09:15:31.404Z [INFO]: Successfully added environment from your project
2019-02-20T09:15:31.412Z [INFO]: # Initializing existing Amplify environment: prod (amplify init)
2019-02-20T09:15:32.814Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2019-02-20T09:15:34.009Z [WARNING]: - Initializing your environment: prod
2019-02-20T09:15:34.226Z [WARNING]: ✖ There was an error initializing your environment.
2019-02-20T09:15:34.226Z [INFO]: init failed
2019-02-20T09:15:34.228Z [INFO]: TypeError: Cannot read property 'addressAutocomplete' of undefined
    at Object.keys.forEach (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initialize-env.js:63:43)
    at Array.forEach (<anonymous>)
    at Object.keys.forEach (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initialize-env.js:62:44)
    at Array.forEach (<anonymous>)
    at S3.then.then.then.then.then (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initialize-env.js:61:32)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
2019-02-20T09:15:34.235Z [ERROR]: !!! Build failed
2019-02-20T09:15:34.235Z [ERROR]: !!! Non-Zero Exit Code detected
2019-02-20T09:15:34.235Z [INFO]: # Starting Environment Caching...
2019-02-20T09:15:34.235Z [INFO]: Uploading environment cache artifact...
2019-02-20T09:15:34.351Z [INFO]: # Environment Caching completed
Terminating logging...
```

**Comment by yuth** [comment] 2019-03-19 23:04
@hammadj looks like this got fixed in https://github.com/aws-amplify/amplify-cli/pull/934. Re-open the issue if you can still reproduce this in the latest version of Amplify CLI

**Closed by yuth** 2019-03-19 23:04 UTC
Labels: amplify-console, bug
