### ISSUE TITLE
Deploy data model failed after amplify push

### ISSUE THREAD

**Issue by harrynguyen2510** [aws-amplify/amplify-cli#13037] opened 2023-07-29 12:04 UTC
### Description

After running command "amplify push" to cloud, when I go to data model to deploy new changes, (edited Schema), I met this issue at the 1st step of Deployment:

`A flag to disable overrides has been detected, please deploy from a different environment. at buildOverrideDir`

I did upgrade to the latest version of Amplify 

Has anyone met this issue?

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Screenshots

![Screenshot 2023-07-29 at 22 02 41](https://github.com/aws-amplify/amplify-flutter/assets/59348244/2b455467-98c4-4c2f-acfc-2f09923e5406)

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.5

### Amplify Flutter Version

12.2.3

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment] 2023-07-31 15:14
Transferring to the CLI team as this does not sound related to the Amplify Flutter libraries.

**Comment by ykethan** [comment] 2023-07-31 17:31
Hey @harrynguyen2510 , the issue appears to be a duplicate of https://github.com/aws-amplify/amplify-studio/issues/1004. In to prevent any miscommunication between issue, I will be closing this issue.

**Closed by ykethan** 2023-07-31 17:31 UTC
Labels: pending-triage, duplicate
