### ISSUE TITLE
Latest amplify changes result in problems with GraphQL schema

### ISSUE THREAD

**Issue by tobon96** [aws-amplify/amplify-cli#2952] opened 2019-12-09 16:53 UTC
**Describe the bug**
Guys, I've been developing a project for the last 3 months. In the schema I had something like this:

type Assessor @model @auth(rules: [{allow: private}]){
   id: ID!
   name: String!
   email: String!
   comments: [Comment!] @connection
}

type Comment @model @auth(rules: [{allow: private}]){
  id: ID!
  content: String!
  type: String!
  datetime: String!
}

Until last week, this worked fine. But after friday this just doesn't work, and I've searched a lot, but found no info. What could it be?

**Amplify CLI Version**
4.5.0

**Expected behavior**
I expect that I could add an array of ID's from the comments

**Comment by attilah** [comment] 2019-12-09 18:28
@tobon96 could you be more specific about the expected behavior? what mutations were working with which version of the CLI and what is different with 4.5.0? That would help to answer your question/problem much faster.

**Comment by kaustavghosh06** [comment] 2019-12-19 18:56
Closing this due to lack of requested information. if you're still stuck with this issue, please comment on this thread and we'll re-open this.

**Closed by kaustavghosh06** 2019-12-19 18:56 UTC
Labels: graphql-transformer, pending-response, question
