### ISSUE TITLE
Could you please make the `nativeClientId` optional in the headless CLI mode?

### ISSUE THREAD

**Issue by m98** [aws-amplify/amplify-cli#10039] opened 2022-03-22 11:15 UTC
### Is this feature request related to a new or existing Amplify category?

auth

### Is this related to another service?

CLI

### Describe the feature you'd like to request

I followed the [Amplify Headless](https://docs.amplify.aws/cli/usage/headless/) mode documentation to create a `headless_pull.sh` file.

In the Cognito user pool, I only have one app client which is for the website. There is no native app. But when I write the `headless_pull.sh`, it says:  **"auth headless is missing the following inputParams nativeClientId"**
<img width="677" alt="image" src="https://user-images.githubusercontent.com/7496103/159468942-95174030-ce46-44a6-bdad-8484ccc549b3.png">

But for my case, I don't need any native app client, so I can't have a `nativeClientId` which is required.

### Describe the solution you'd like

I think it would be great if you can make the native app client (`nativeClientId`) field optional.

### Additional context

Even after adding a `nativeClientId`, I am getting a new error now which I saw it's already [tagged as a bug](https://github.com/aws-amplify/amplify-cli/issues/7821), do you have any workaround for it?
**"OAuth properties for the app clients are not matching."**

<img width="603" alt="image" src="https://user-images.githubusercontent.com/7496103/159469499-54f837ea-20b3-43af-95fc-af69fc6407a4.png">

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment] 2022-03-22 13:55
Hey @m98 :wave: thanks for raising this! This does appear to be a duplicate of the linked issue, #7821 , however as a workaround can you try specifying the same client ID for both app and native to see if that mitigates the issue for now?

**Comment by m98** [comment] 2022-04-12 11:04
I can confirm that using the same (duplicate) id for both web and native App solved the issue. But I hope the fix does not break it! Because I believe many people already have done this to temporarily fix the issue.

**Comment by agnelnieves** [comment] 2023-01-31 16:15
Came into this issue because of the same reason.

**Comment by josefaidt** [comment] 2023-08-22 20:32
Closing in favor of tracking the existing issue, https://github.com/aws-amplify/amplify-cli/issues/7821

**Closed by josefaidt** 2023-08-22 20:32 UTC
Labels: bug, headless, duplicate, p2
