### ISSUE TITLE
Unsupported operation 'BatchPutItem'. Datasource Versioning only supports the following operations (TransactGetItems,PutItem,BatchGetItem,Scan,Query,GetItem,DeleteItem,UpdateItem,Sync)

### ISSUE THREAD

**Issue by sarv-fuse** [aws-amplify/amplify-cli#9727] opened 2022-02-09 10:34 UTC
@nubpro Incidentally, I've recently added DataStore to an existing graphql that had a batch resolver to batch insert items into a Dynamo DB table. The resolver now doesn't work. Are you sure that DataStore supports BatchPutItem?

The error I get from the resolver is: 

> Unsupported operation 'BatchPutItem'. Datasource Versioning only supports the following operations (TransactGetItems,PutItem,BatchGetItem,Scan,Query,GetItem,DeleteItem,UpdateItem,Sync)

The resolver code is:
```
#set($transectSitesData = [])
#foreach($item in ${ctx.args.transectSites})
    $util.qr($item.put("createdAt", $util.time.nowISO8601()))
    $util.qr($item.put("updatedAt", $util.time.nowISO8601()))
    $util.qr($item.put("_lastChangedAt", $util.time.nowISO8601()))
    $util.qr($item.put("__typename", "MyTable"))
    $util.qr($item.put("_version", 1))
    $util.qr($item.put("id", $util.defaultIfNullOrBlank($item.id, $util.autoId())))
    $util.qr($transectSitesData.add($util.dynamodb.toMapValues($item)))
#end
{
  "version": "2018-05-29",
  "operation": "BatchPutItem",
  "tables": {
      "MyTable-API-mydev": $utils.toJson($transectSitesData)
  }
}
```

The only changes I've made in an attempt to resolve the error is to add the _version and _lastChangedAt fields into this template.

_Originally posted by @greendinosaur in https://github.com/aws-amplify/amplify-cli/issues/7185#issuecomment-827121255_

**Comment by sarv-fuse** [comment] 2022-02-09 10:48
i have @model named MyTable 
type mutation batchAddMyTable(myTable:[input]):[MyTable]
updated CustomResources.json file with DataSourceName: MyTableTable, FieldName:batchAddMyTable and soon
i followed [this](https://medium.com/@jan.hesters/creating-graphql-batch-operations-for-aws-amplify-with-appsync-and-cognito-ecee6938e8ee) blog post

**Comment by josefaidt** [comment] 2022-02-15 17:25
Hey @sarv-fuse :wave: would you mind porting this report over to our [bug report template](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml)? This will help us gather additional context around the issue to better understand it and the potential root cause.

Closing issue

**Closed by josefaidt** 2022-02-15 17:25 UTC
