### ISSUE TITLE
Build Fails: Property 'storage' does not exist on type 'AmplifyDependentResourcesAttributes'

### ISSUE THREAD

**Issue by renschler** [aws-amplify/amplify-cli#12205] opened 2023-01-13 08:40 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3vgo587djz6v9

### AWS Region

us-east-1

### Amplify Hosting feature

Backend builds, Build settings

### Describe the bug

My app backend builds successfully locally when I run `amplify build` and `amplify push`.
However when my git commit triggers the CI/CD build process, my backend fails with this error:
```
cdk-stack.ts(70,31): error TS2339: Property 'storage' does not exist on type 'AmplifyDependentResourcesAttributes'.
                                 Resolution: There may be errors in your custom resource file. If so, fix the errors and try again.
```

This seems very similar to this bug which was closed but people later said they had the same issue: https://github.com/aws-amplify/amplify-hosting/issues/2478

I added this to my prebuild commands:
```
version: 1
backend:
  phases:
    preBuild:
      commands:
        - cat amplify/backend/types/amplify-dependent-resources-ref.d.ts
```

and when I look at the output in the build logs, sure enough the 'storage' property does exist.

### Expected behavior

The build should complete successfully.

### Reproduction steps

I have not created a new amplify app to test things from scratch.

I have ~10 function resources, and 4 custom resources, 1 storage resource, 1 api resource, 1 auth resource.

My last successful CI/CD build was on the 6th (at that time I did have the storage resource, but I did not have the custom CDK resources).

My `cdk-stack.ts` for the failing resource looks like this:
```
import * as cdk from 'aws-cdk-lib'
import * as AmplifyHelpers from '@aws-amplify/cli-extensibility-helper'
import { AmplifyDependentResourcesAttributes } from '../../types/amplify-dependent-resources-ref'
import { Construct } from 'constructs'
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb'
import * as iam from 'aws-cdk-lib/aws-iam'
import { readdirSync } from 'fs'
import path from 'path'

.... boiler plate ....

const getDirectories = (source) =>
      readdirSync(source, { withFileTypes: true })
        .filter((dirent) => dirent.isDirectory())
        .map((dirent) => dirent.name)

    const lambdaResourceNames = getDirectories(
      path.resolve('./amplify/backend/function')
    )

    const lambdaDependencies = lambdaResourceNames.map((name) => {
      return {
        category: 'function',
        resourceName: name,
      }
    })

    // Access other Amplify Resources
    const dependencies: AmplifyDependentResourcesAttributes =
      AmplifyHelpers.addResourceDependency(
        this,
        amplifyResourceProps.category,
        amplifyResourceProps.resourceName,
        lambdaDependencies.concat([
          {
            category: 'storage',
            resourceName: 'smwStravaAthleteIds',
          },
        ])
      )

    /* StravaAthleteIds Table */
    const stravaAthleteIdTable = dynamodb.Table.fromTableArn(
      this,
      'smwStravaAthleteIds',
      cdk.Fn.ref(dependencies.storage.smwStravaAthleteIds.Arn)
    )

```

The last line is the one that fails. The `lambdaDependencies` object is an array with my function resources [{category:"function", resourceName:"function-name"}, ...]

Note: I am using cdk v2 following the instructions from this post: https://aws.amazon.com/blogs/mobile/use-aws-cdk-v2-with-the-aws-amplify-cli-extensibility-features-beta/

I have the live package updates set to `Amplify CLI 11.0.0-beta.4`
I also tried `Amplify CLI beta` but that resulted in the same error. As did `Amplify CLI latest`.

Locally I am running Node v16.17.0

### Build Settings

```yaml
version: 1
backend:
  phases:
    preBuild:
      commands:
        - cat amplify/backend/types/amplify-dependent-resources-ref.d.ts
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: out
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line

**CLONING**

2023-01-13T08:17:26.100Z [INFO]: # Cloning repository:
2023-01-13T08:17:28.093Z [INFO]: 
2023-01-13T08:17:28.096Z [INFO]: Cloning into 'smw-next-site'...
2023-01-13T08:17:28.096Z [INFO]: # Switching to commit: 364978d32c7b7d15badd3a6b5e9875594a758a27
2023-01-13T08:17:28.126Z [INFO]: Note: switching to '364978d32c7b7d15badd3a6b5e9875594a758a27'.
                                 You are in 'detached HEAD' state. You can look around, make experimental
                                 changes and commit them, and you can discard any commits you make in this
                                 state without impacting any branches by switching back to a branch.
                                 If you want to create a new branch to retain commits you create, you may
                                 do so (now or later) by using -c with the switch command. Example:
                                 git switch -c <new-branch-name>
                                 Or undo this operation with:
                                 git switch -
                                 Turn off this advice by setting config variable advice.detachedHead to false
                                 HEAD is now at 364978d remove logging
2023-01-13T08:17:28.160Z [INFO]: Successfully cleaned up Git credentials
2023-01-13T08:17:28.160Z [INFO]: # Checking for Git submodules at: /codebuild/output/src200456012/src/smw-next-site/.gitmodules
2023-01-13T08:17:28.171Z [INFO]: # Retrieving environment cache...
2023-01-13T08:17:28.748Z [INFO]: # Retrieved environment cache
2023-01-13T08:17:28.749Z [INFO]: ---- Setting Up SSM Secrets ----
2023-01-13T08:17:28.749Z [INFO]: SSM params {"Path":"/amplify/d3vgo587djz6v9/dev/","WithDecryption":true}
2023-01-13T08:17:28.836Z [INFO]: # Determining if there are buildable backend changes in the amplify directory of the repository...
2023-01-13T08:17:28.875Z [INFO]: # Last built commit: 4b2985746c3000ff1dd280e1f6d5539cd2a9d0d8
2023-01-13T08:17:28.884Z [INFO]: # Differences detected.
2023-01-13T08:17:28.884Z [INFO]: # Continuing with backend build...
2023-01-13T08:17:28.885Z [INFO]: # Defaulting to Node version 16
2023-01-13T08:17:40.306Z [INFO]: # Node version 16 is available for installation
2023-01-13T08:17:40.427Z [INFO]: # Installing Node version 16
2023-01-13T08:17:50.581Z [INFO]: # Now using Node version 16
2023-01-13T08:17:51.436Z [WARNING]: Cannot find module '/root/.nvm/versions/node/v16.19.0/lib/node_modules/@aws-amplify/cli/package.json'
                                    Require stack:
                                    - /snapshot/AWSMobilePioneerExecute/out/index.js
2023-01-13T08:17:51.437Z [INFO]: # Patching NPM package '@aws-amplify/cli' to 11.0.0-beta.4...
2023-01-13T08:17:59.344Z [INFO]: # Done patching NPM package '@aws-amplify/cli' to version 11.0.0-beta.4
2023-01-13T08:17:59.434Z [INFO]: # Retrieving cache...
2023-01-13T08:18:15.526Z [INFO]: # Extracting cache...
2023-01-13T08:18:22.521Z [INFO]: # Extraction completed
2023-01-13T08:18:22.765Z [INFO]: # Retrieved cache


**BACKEND**


                                 # Starting phase: preBuild
                                 # Executing command: cat amplify/backend/types/amplify-dependent-resources-ref.d.ts
2023-01-13T08:06:01.675Z [INFO]: export type AmplifyDependentResourcesAttributes = {
                                 "api": {
                                 "smwuserdata": {
                                 "GraphQLAPIEndpointOutput": "string",
                                 "GraphQLAPIIdOutput": "string"
                                 }
                                 },
                                 "auth": {
                                 "smwnextsite4ce569c9": {
                                 "AppClientID": "string",
                                 "AppClientIDWeb": "string",
                                 "IdentityPoolId": "string",
                                 "IdentityPoolName": "string",
                                 "UserPoolArn": "string",
                                 "UserPoolId": "string",
                                 "UserPoolName": "string"
                                 }
                                 },
                                 "function": {
                                 "oncognitoconfirmation": {
                                 "Arn": "string",
                                 "LambdaExecutionRole": "string",
                                 "LambdaExecutionRoleArn": "string",
                                 "Name": "string",
                                 "Region": "string"
                                 },
                                 "smwCheckPelotonForStravaAutoPost": {
                                 "Arn": "string",
                                 "LambdaExecutionRole": "string",
                                 "LambdaExecutionRoleArn": "string",
                                 "Name": "string",
                                 "Region": "string"
                                 },
                                 "smwCreateStripeBillingSession": {
                                 "Arn": "string",
                                 "LambdaExecutionRole": "string",
                                 "LambdaExecutionRoleArn": "string",
                                 "Name": "string",
                                 "Region": "string"
                                 },
                                 "smwCreateStripeCheckoutSession": {
                                 "Arn": "string",
                                 "LambdaExecutionRole": "string",
                                 "LambdaExecutionRoleArn": "string",
                                 "Name": "string",
                                 "Region": "string"
                                 },
                                 "smwDisconnectStrava": {
                                 "Arn": "string",
                                 "LambdaExecutionRole": "string",
                                 "LambdaExecutionRoleArn": "string",
                                 "Name": "string",
                                 "Region": "string"
                                 },
                                 "smwGetStravaToken": {
                                 "Arn": "string",
                                 "LambdaExecutionRole": "string",
                                 "LambdaExecutionRoleArn": "string",
                                 "Name": "string",
                                 "Region": "string"
                                 },
                                 "smwStripeRevokePartnerPlanPromocode": {
                                 "Arn": "string",
                                 "LambdaExecutionRole": "string",
                                 "LambdaExecutionRoleArn": "string",
                                 "Name": "string",
                                 "Region": "string"
                                 },
                                 "smwStripeWebhookEndpoint": {
                                 "Arn": "string",
                                 "LambdaExecutionRole": "string",
                                 "LambdaExecutionRoleArn": "string",
                                 "Name": "string",
                                 "Region": "string"
                                 },
                                 "smwValidateGarminCredentials": {
                                 "Arn": "string",
                                 "LambdaExecutionRole": "string",
                                 "LambdaExecutionRoleArn": "string",
                                 "Name": "string",
                                 "Region": "string"
                                 },
                                 "smwValidatePelotonCredentials": {
                                 "Arn": "string",
                                 "LambdaExecutionRole": "string",
                                 "LambdaExecutionRoleArn": "string",
                                 "Name": "string",
                                 "Region": "string"
                                 }
                                 },
                                 "storage": {
                                 "smwStravaAthleteIds": {
                                 "Arn": "string",
                                 "Name": "string",
                                 "PartitionKeyName": "string",
                                 "PartitionKeyType": "string",
                                 "Region": "string",
                                 "StreamArn": "string"
                                 }
                                 }
                                 }# Completed phase: preBuild
                                 # Starting phase: build
2023-01-13T08:06:04.271Z [INFO]: [0mAmplify AppID found: d3vgo587djz6v9. Amplify App name is: smwnextsite[0m
2023-01-13T08:06:04.321Z [INFO]: [0mBackend environment dev found in Amplify Console app: smwnextsite[0m
2023-01-13T08:06:05.183Z [WARNING]: - Fetching updates to backend environment: dev from the cloud.
2023-01-13T08:06:06.174Z [WARNING]: - Building resource api/smwuserdata
2023-01-13T08:06:06.973Z [INFO]: ✅ GraphQL schema compiled successfully.
                                 Edit your schema at /codebuild/output/src214970290/src/smw-next-site/amplify/backend/api/smwuserdata/schema.graphql or place .graphql files in a directory at /codebuild/output/src214970290/src/smw-next-site/amplify/backend/api/smwuserdata/schema
2023-01-13T08:06:06.974Z [WARNING]: - Building resource auth/smwnextsite4ce569c9
2023-01-13T08:06:07.041Z [WARNING]: - Building resource custom/smwApiGatewayLambdaEndpoints
2023-01-13T08:06:07.041Z [WARNING]: - Building custom resources
2023-01-13T08:06:24.697Z [WARNING]: - Building resource custom/smwEncryptionKeysAndKeyAccess
2023-01-13T08:06:24.699Z [WARNING]: - Building custom resources
2023-01-13T08:06:36.214Z [WARNING]: - Building resource custom/smwSecretsAndSecretAccess
                                    - Building custom resources
2023-01-13T08:06:47.852Z [WARNING]: - Building resource custom/smwTableAccess
2023-01-13T08:06:47.853Z [WARNING]: - Building custom resources
2023-01-13T08:06:57.830Z [INFO]: 🛑 Failed building resource smwTableAccess
2023-01-13T08:06:57.831Z [WARNING]: ✖ There was an error initializing your environment.
2023-01-13T08:07:00.457Z [INFO]: 🛑 There was an error building the custom resources
                                 Command failed with exit code 2: /codebuild/output/src214970290/src/smw-next-site/amplify/backend/custom/smwTableAccess/node_modules/.bin/tsc
                                 cdk-stack.ts(83,31): error TS2339: Property 'storage' does not exist on type 'AmplifyDependentResourcesAttributes'.
                                 Resolution: There may be errors in your custom resource file. If so, fix the errors and try again.
                                 Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
2023-01-13T08:07:00.459Z [INFO]: 
2023-01-13T08:07:00.459Z [INFO]: Session Identifier: d44f018f-232a-4a11-b554-552598867d88
2023-01-13T08:07:00.489Z [ERROR]: !!! Build failed
2023-01-13T08:07:00.489Z [ERROR]: !!! Non-Zero Exit Code detected
2023-01-13T08:07:00.489Z [INFO]: # Starting environment caching...
2023-01-13T08:07:00.489Z [INFO]: # Uploading environment cache artifact...
2023-01-13T08:07:00.610Z [INFO]: # Uploaded environment cache artifact
2023-01-13T08:07:00.610Z [INFO]: # Environment caching completed
Terminating logging...

```

</details>

### Additional information

When I hardcode the DynamoDB storage resource arn into the failing `cdk-stack.ts` the backend build completes successfully.

Interestingly I see that the storage resource is being built after that custom resource. I wonder if that's why it's failing to recognize the storage property? I don't know how stuff works though...

```
2023-01-13T08:50:42.873Z [WARNING]: - Building resource custom/smwTableAccess
                                    - Building custom resources
2023-01-13T08:50:54.794Z [WARNING]: - Building resource storage/smwStravaAthleteIds
2023-01-13T08:50:54.846Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
```

**Comment by josefaidt** [comment] 2023-03-09 19:46
Hey folks I transferred this to our CLI repo for visibility. Closing as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/11847

**Closed by josefaidt** 2023-03-09 19:46 UTC
Labels: bug, platform, extensibility, duplicate
