### ISSUE TITLE
API Builds failing with unknown type error

### ISSUE THREAD

**Issue by ThePatrickDavis** [aws-amplify/amplify-cli#13643] opened 2024-03-07 17:04 UTC
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18.16.1

### Amplify CLI Version

12.10.1

### What operating system are you using?

Mac OS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

Without making any changes to my schema.graphql file, by builds have started failing across all back-end environments. 

### Expected behavior

Builds without schema changes should successfully complete

### Reproduction steps

1. Make a minor change to trigger a build
2. The build failes

### Project Identifier

13637ff9223ff117318765b2e589e9c9

### Log output

<details>
2024-03-07T02:13:43.591Z [WARNING]: ✖ There was an error initializing your environment.
2024-03-07T02:13:43.598Z [INFO]: 🛑 Unknown type GetInvitationInput
                                 Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
2024-03-07T02:13:43.610Z [INFO]: 
2024-03-07T02:13:43.610Z [INFO]: Session Identifier: 0d0609f4-48ce-4d30-a40b-eaf5cc478c60
</details>

### Additional information

The type in question: 

input GetInvitationInput {
  code: String!
}

This is a custom type used by this custom query: 

type Query {
  getInvitation(input: GetInvitationInput) : InvitationResult
  @auth(rules: [{allow: public}, {allow: private, provider: iam}])
  @function(name: "getInvitation3-${env}")
}

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment] 2024-03-07 17:14
Hey @ThePatrickDavis, thank you for reaching out. The issue is currently being tracked on https://github.com/aws-amplify/amplify-codegen/issues/794. 
Could you try downgrading/setting the Amplify CLI version to v12.10.1

**Comment by ykethan** [comment] 2024-03-07 17:16
Closing this issue to track https://github.com/aws-amplify/amplify-codegen/issues/794.

**Closed by ykethan** 2024-03-07 17:16 UTC
Labels: pending-triage
