### ISSUE TITLE
"Cannot read property 'Mappings' of undefined

### ISSUE THREAD

**Issue by chewypear** [aws-amplify/amplify-cli#3576] opened 2020-03-04 18:16 UTC
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
In API we use graphql and dynamo. In one environment, we can no longer modify API. Even something simple such as adding a new property or making a property non-optional and pushing results in the following error
Cannot read property 'Mappings' of undefined

**Amplify CLI Version**
4.13.4

**To Reproduce**
We haven't been able to create a test project to reproduce this particular issue. Output is: 
TypeError: Cannot read property 'Mappings' of undefined
  at collectTemplates (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/splitStack.ts:135:30)
  at Object.splitStack [as default] (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/splitStack.ts:325:18)
  at TransformFormatter.format (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/TransformFormatter.ts:36:36)
  at GraphQLTransform.transform (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/GraphQLTransform.ts:307:22)
  at _buildProject (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:53:35)

**Expected behavior**
amplify push succeeds, and graphql api is updated

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. v12.4.0

**Additional context**
We are seeing another issue that we don't know if it's related. Autogenerated files like template.json also has a second generated file template2.json. These issues began at the same time.

**Comment by kaustavghosh06** [comment] 2020-03-04 18:22
@chewypear What are you modifying?  The annotated GraphQL schema? In which directory?

**Comment by chewypear** [comment] 2020-03-04 20:42
@kaustavghosh06 - Just doing a simple modification to schema.graphql in /amplify/backend/api/<projname>/schema.graphql

In short, any time amplify sees an 'update' to 'api' and I try to amplify push, the error above results.

**Comment by kaustavghosh06** [comment] 2020-03-04 20:46
@chewypear Would it be possible to share your schema? It's not happening to us with our sample schemas. I'm curious to know if you have custom stacks etc and your schema of course.

**Comment by chewypear** [comment] 2020-03-04 21:06
Unfortunately we can't share the schema publicly. 

But I can confirm that the schema can be pushed to another environment - so amplify push just in a different env.

We don't really have anything custom.

In the failing environment when doing amplify push, we also generate a bunch of stuff in transform.conf.json. This file is empty in the functional environments.

**Comment by nikhname** [comment] 2020-03-05 01:12
@chewypear would you be able to send a zip file of your amplify folder to amplify-cli@amazon.com?
It seems as though a mapping template may be missing

**Comment by attilah** [comment] 2020-03-06 20:51
@chewypear stack mapping is being created during the push and it seems that `transform.conf.json` is the source of the problem, because that is where the stack mapping is stored, I think that file is getting invalid for some reason.

Can you elaborate on this: 
> we also generate a bunch of stuff in transform.conf.json

- What do you generate into that file?
- Which directory can you find that `template2.json`?
- What version of the CLI was used to create the project?
- What version of the CLI you are using during the push?
- Is the same computer and same version of the CLI is used?

Please send in email the problematic `transform.con.json` file to us in email or share here, but replace sensitive content, but make sure to keep the structure.

**Comment by eliasdefaria** [comment] 2020-03-06 21:55
@attilah I work with @chewypear and just sent the email with the transform.conf.json attached. Thank you.

**Comment by attilah** [comment] 2020-03-09 19:19
The root cause of the problem was not related to the CLI itself, but that some text editors are creating duplicate files by altering the filename - copy 1, copy 2, 1, 2, 3, etc suffixes - and those files are being uploaded as part of #current-cloud-backend.zip into the environment's deployment bucket.

Later, on subsequent env checkouts this can produce an incorrect state which makes the push operation fail.

To get to a stable deployment state the following steps could provide a solution:
- Check the deployment bucket's name in `team-provider-info.json` in the project's root directory. Locate the environment's name and the `DeploymentBucketName` value.
- Go to the S3 console and download the existing `#current-cloud-backend.zip` in the root folder as a backup.
- Extract the files of the zip file and look for duplicate filenames like `amplify-meta 2.json`, look in the API folder `api/<api name>` as well for `schema 3.json` and such. Remove these files.
- Create a zip file with the updated content and upload it to the same bucket.
- Locate the same duplicated files in the `amplify` folder, and delete them.
- Checkout the non-working environment with Amplify CLI, make sure you're on a different one. It will do a `pull` operation, so the #current-cloud-backend directory will be overwritten with the previously cleaned up files.
- Execute `amplify push` operation to push local changes to the cloud, the update should execute successfully and stack will be in a stable state.

**Closed by attilah** 2020-03-09 19:19 UTC
Labels: cloudformation, graphql-transformer
