### ISSUE TITLE
Support for 'amplify pull'?

### ISSUE THREAD

**Issue by ginomempin** [aws-amplify/amplify-cli#293] opened 2018-10-11 23:33 UTC
**Is your feature request related to a problem? Please describe.**

I configured a storage resource on my local backend using `amplify storage add` (then followed the steps to setup a NoSQL DB). I then did `amplify push` and it was successful. On the DynamoDB web console, someone then configured the read and write capacity from the default 5 to 10 (or some other value). But on my local backend, in _amplify/storage/<mydb>/<mydb>-cloudformation-template.json_, the `ReadCapacityUnits` and `WriteCapacityUnits` will still be set to `"5"`. It seems there is no way to "pull" the new settings to my local backend.

It's not just the RCU and WCU. It can also apply to other DB settings like Indexes.

**Describe the solution you'd like**

A command like `amplify storage pull` or `amplify storage sync` to sync local resources with cloud resources. Or maybe at least a check to see if cloud and local resources are still in sync.

**Describe alternatives you've considered**

I think the `amplify storage update` can also be improved to allow setting various DB settings from the CLI. Currently, it can only add columns and indexes to the DB. Though, with the number of DB settings, it might not be good for the CLI to be prompting the user with a lot of update options.

It's also possible to just modify the files themselves on my local backend after updating via the web console, but that kind of defeats the purpose of having a CLI tool to automate the work. Plus, I have to be notified that someone modified via the web console.

There is also the option of enforcing project members to use either the CLI **or** the web console, but not both, so as to avoid inconsistencies. But well, some people are averse to using the command line.

**Additional context**

Amplify CLI 0.1.27
macOS High Sierra 10.13.6
AWS DynamoDB on a free tier (still in prototyping)

**Comment by UnleashedMind** [comment] 2018-10-12 07:14
Thank you very much for the feedbacks. 
I'm marking this as a feature request.

**Comment by kylekirkby** [comment] 2019-02-08 14:30
Hey @UnleashedMind, 

Any ideas as to when a feature like this might be added? I've been using the awsmobile-cli npm tool in the interim since this feature works fine on that... 

All the best,

Kyle

**Comment by amlcodes** [comment] 2019-03-18 02:21
@kylekirkby what is the process to do that?

**Comment by UnleashedMind** [comment] 2019-03-21 18:54
Thanks for your continuous support for our products. 
The team hear the requests and is working on it.
This is not a simple problem though, it will be implemented category by category, and their scopes will be expanded iteratively.
You will be updated soon on this.

**Comment by kaustavghosh06** [comment] 2019-05-17 17:42
Closing this as this is a duplicate of #174

**Closed by kaustavghosh06** 2019-05-17 17:42 UTC
Labels: feature-request, storage
