### ISSUE TITLE
Custom::LambdaCallout keeps hanging in multiple envs and commands

### ISSUE THREAD

**Issue by andrewbtp** [aws-amplify/amplify-cli#3173] opened 2020-01-13 03:06 UTC
**Describe the bug**
In my `dev` environment, I tried updating my auth resource to a generic "Default settings with no social federation", and the stack would hang on

Logical ID: `MFALambdaInputs`
Type: `Custom::LambdaCallout`
Status: `UPDATE_IN_PROGRESS`
Line in terminal: `UPDATE_COMPLETE UserPoolClientLogPolicy AWS::IAM::Policy`

I then ran `amplify env remove NONE` to at long last get rid of that old hangover, and again my stack got stuck at

Logical ID: `UpdateRolesWithIDPFunctionOutputs`
Type: `Custom::LambdaCallout`
Status: `DELETE_IN_PROGRESS`

**Amplify CLI Version**
4.12.0

**To Reproduce**
These envs have been around for a few months, so it's tough to figure out what's relevant to this point. Happy to supply any additional env configs, etc.
Dev:
`amplify auth update`
` > Apply default configuration without social provider`
`amplify push`

NONE:
`amplify env checkout <not-NONE>`
`amplify env remove NONE`

**Expected behavior**
I expected my auth to update and not hang. I expected my stack to delete and not hang.

**Desktop (please complete the following information):**
 - OS: Mac
 - Node v10.15.1

**Comment by andrewbtp** [comment] 2020-01-25 17:00
Tried adding some Lambda triggers and this continues to occur. Really concerned about updating prod, would be a big issue if this hangs there.

**Comment by mikedizon** [comment] 2020-01-29 15:42
Seeing this as well. Updated to latest version of amplify-cli.

**Comment by kaustavghosh06** [comment] 2020-02-19 17:29
@andrewbtp Are you still stuck with this? I tried reproducing this but wasn't able to with the latest CLI version.

**Comment by kaustavghosh06** [comment] 2020-02-21 23:26
Closing as this is non-reproducible. If you're stuck and or still have issues with this, please comment on this thread and we'll re-open this for further investigtation.

**Closed by kaustavghosh06** 2020-02-21 23:26 UTC
Labels: pending-response, pending-triage

**Comment by simontegg** [comment] 2020-04-08 05:10
I got the same error with version `4.17.2`

**Comment by pnewhook** [comment] 2021-02-20 17:22
Getting same thing with 4.44.0. Initial push failed an had to manually delete everything. But the "Root Stack for AWS Amplify Console" is stuck in DELETE_IN_PROGRESS because of UpdateRolesWithIDPFunctionOutputs
