### ISSUE TITLE
How to speed up Lambda Layer version deployments?

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#5964] opened 2020-11-25 11:38 UTC
**Which Category is your question related to?**

Lambda Layers and bumping up version numbers of those Layers that are used by the various Lambda functions.

When I make a change to a Layer I have to push it up. Trouble is I nearly always forget to bump up the version number of the functions that use it. During development it is very rare that I don't want to just update all my functions to use the new version (normally because the old one is broken!).

So I push. Realise when I test that my function is still referring to the old Layer, run `amplify update function` to update the layer version for the function and then have to push again.

Trouble is that second push that is seemingly just pushing up a minor config file change spits out output about everything that its updating or touching. Seems to be touching a lot of stuff I just don't think it should be reporting on. This got me thinking is it doing too much un-needed work and can anything be done to shorten the length of time that the push takes (its a killer for developer flow)?

Things I'd like to see it do include:

- When I change a Layer give me the option to update all functions that use it to the new version in one go. Rarely I've seen something similar to this but I think that is when changing access or permissions of the Layer. Could we re-use that if the hash of the deployed files differs to the ones local?
- Similar to above when running `amplify update function` give me the option to update the Layer version on multiple functions in one hit using that funky check list thingy that it does.
- When there is only one small change how come it appears to be UPDATE_IN_PROGRESS'ing on everyone of my DynamoDB Tables, every other function, permissions etc? Is there no way to skip some of those? The status table shows that only my function has been changed so it knows that that is the only bit it needs to deploy, could we not streamline that a little and only push/touch the function updates? Without this a simple version bump has taken 5 minutes via `amplify push --yes` thats a hell of a "compile time".

There might be some magic command line args I can pass in that will do some of these but I can't seem to find any hence this being a Usage Question rather than an issue or feature request. If it can't do what I'm suggesting then maybe we can spin up features or issues as required.

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

4.32.0

**What AWS Services are you utilizing?**

Lambda Layers and Lambda

**Provide additional details e.g. code snippets**

Only one thing changed:
![image](https://user-images.githubusercontent.com/1674590/100222752-7728a000-2f12-11eb-8787-a1919fa87fdf.png)

Yet touching all this stuff (this is just a sample)? Needlessly?
![image](https://user-images.githubusercontent.com/1674590/100222798-860f5280-2f12-11eb-8914-a43d51d458fb.png)

**Comment by ammarkarachi** [comment] 2020-11-25 19:22
@PeteDuncanson I can confirm this is happening we will do a deeper review and see if we can avoid re-pushing resources on function/lambda layer update

**Comment by jhockett** [comment] 2021-05-25 17:20
Hi @PeteDuncanson,

We have an alpha build of our redesign of Lambda layers in Amplify CLI available to try. This includes several bug fixes and new features. It also includes a **one-way migration** step for existing layer resources. Lambda layer resources pushed with this build will not work with any other version of the Amplify CLI.

**DO NOT USE THIS IN PRODUCTION!**

To test it out: `npm i -g @aws-amplify/cli@not-for-production-layers`

Notable changes:

- Complete redesign of layer version tracking. New code does not make assumptions about what layer versions exist in the cloud and always pulls the latest data from the Lambda service
- Option to automatically update dependent functions to the latest deployed Lambda layer version
- Added ability to delete individual layer versions
- Layers now have a dependency installation step that will install dependencies based on what's in `package.json` for NodeJS or `Pipfile` for Python
- Support editing layer version descriptions
- Removes local version state tracking from `amplify-meta.json` and `team-provider-info.json`

We'd love to hear any community feedback!

**Comment by renebrandel** [comment] 2021-06-21 17:41
Hi @PeteDuncanson - we're closing this because of our new lambda layer changes has been released. You can now pin a function to use the latest version changes. Check out the details here:
- https://docs.amplify.aws/cli/migration/lambda-layers-update 
- https://docs.amplify.aws/cli/function/layers

**Closed by renebrandel** 2021-06-21 17:41 UTC
Labels: enhancement, lambda-layers, platform
