### ISSUE TITLE
Amplify mock fails to create local tables

### ISSUE THREAD

**Issue by Rolando-Barbella** [aws-amplify/amplify-cli#7411] opened 2021-05-26 21:43 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm -g

### If applicable, what version of Node.js are you using?

12.13.1

### Amplify CLI Version

4.51.2

### What operating system are you using?

Mac M1

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

After running `amplify mock api`, amplify fails to compile the Graph schema even though says has done it successfully, after a while ( like 10 mins), it does not make a connection with the endpoint. My internet connection is very stable, tried several times but no luck.

<img width="1082" alt="Screenshot 2021-05-23 at 23 32 16" src="https://user-images.githubusercontent.com/6339809/119734296-b0ff4280-be72-11eb-96f2-388d88f3953b.png">

### Expected behavior

I expect amplify to create the local tables and point out to the local URL where I can add mutations and queries

### Reproduction steps

1. npx create-react-app test
2. amplify init
3. amplify add api (Api key was selected)
4. amplify mock api

### GraphQL schema(s)

```graphql

type Blog @model {
  id: ID!
  name: String!
  posts: [Post] @connection(name: "BlogPosts")
}
type Post @model {
  id: ID!
  title: String!
  blog: Blog @connection(name: "BlogPosts")
  comments: [Comment] @connection(name: "PostComments")
}
type Comment @model {
  id: ID!
  content: String
  post: Post @connection(name: "PostComments")
}

```

### Log output

<details>

```
2021-05-26T15:41:33.724Z|info : amplify mock mock  
2021-05-26T20:21:24.975Z|info : amplify version core  
2021-05-26T20:27:57.101Z|info : amplify version core  
2021-05-26T20:32:45.452Z|info : amplify init core  
2021-05-26T20:33:34.250Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-05-26T20:33:34.253Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-west-2"}])
2021-05-26T20:33:34.253Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-05-26T20:33:34.266Z|info : amplify-provider-awscloudformation.amplify-service-permission-check.checkAmplifyServiceIAMPermission.amplifyClient.listApps([])
2021-05-26T20:33:35.120Z|info : amplify-provider-awscloudformation.amplify-service-manager.init.amplifyClient.createApp([{"name":"[***]st","environmentVariables":{"_LIVE_PACKAGE_UPDATES":"[{\"pkg\":\"@aws-amplify/cli\",\"type\":\"npm\",\"version\":\"latest\"}]"}}])
2021-05-26T20:33:37.298Z|info : amplify-provider-awscloudformation.amplify-service-manager.init.amplifyClient.getBackendEnvironment([{"appId":"[***]umm09j","environmentName":"[***]ev"}])
2021-05-26T20:33:38.079Z|error : amplify-provider-awscloudformation.amplify-service-manager.init.amplifyClient.getBackendEnvironment([{"appId":"[***]umm09j","environmentName":"[***]ev"}])
NotFoundException: BackendEnvironment dev does not exist.
2021-05-26T20:33:38.080Z|info : amplify-provider-awscloudformation.amplify-service-manager.init.amplifyClient.getBackendEnvironment([{"appId":"[***]umm09j","environmentName":"[***]ev","stackName":"[***]ify-[***]st-[***]ev-[***]334","deploymentArtifacts":"amplify-test-dev-213334-deployment"}])
2021-05-26T20:33:38.819Z|info : amplify-provider-awscloudformation.aws-cfn.cfnModel.createStack([{"StackName":"[***]ify-[***]st-[***]ev-[***]334","Capabilities":["CAPABILITY_NAMED_IAM","CAPABILITY_AUTO_EXPAND"],"TemplateBody":"{\"AWSTemplateFormatVersion\":\"2010-09-09\",\"Description\":\"Root Stack for AWS Amplify CLI\",\"Parameters\":{\"[***]cketName\":{\"Description\":\"Name of the common deployment bucket provided by the parent stack\",\"Type\":\"String\",\"Default\":\"DeploymentBucket\"},\"[***]eName\":{\"Type\":\"String\",\"Default\":\"AuthRoleName\"},\"[***]leName\":{\"Type\":\"String\",\"Default\":\"UnauthRoleName\"}},\"Resources\":{\"DeploymentBucket\":{\"Type\":\"AWS::S3::Bucket\",\"DeletionPolicy\":\"Retain\",\"Properties\":{\"BucketName\":{\"Ref\":\"DeploymentBucketName\"},\"BucketEncryption\":{\"ServerSideEncryptionConfiguration\":[{\"ServerSideEncryptionByDefault\":{\"SSEAlgorithm\":\"AES256\"}}]}}},\"AuthRole\":{\"Type\":\"AWS::IAM::Role\",\"Properties\":{\"RoleName\":{\"Ref\":\"AuthRoleName\"},\"AssumeRolePolicyDocument\":{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Deny\",\"Principal\":{\"Federated\":\"cognito-identity.amazonaws.com\"},\"Action\":\"sts:AssumeRoleWithWebIdentity\"}]}}},\"UnauthRole\":{\"Type\":\"AWS::IAM::Role\",\"Properties\":{\"RoleName\":{\"Ref\":\"UnauthRoleName\"},\"AssumeRolePolicyDocument\":{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Deny\",\"Principal\":{\"Federated\":\"cognito-identity.amazonaws.com\"},\"Action\":\"sts:AssumeRoleWithWebIdentity\"}]}}}},\"Outputs\":{\"Region\":{\"Description\":\"CloudFormation provider root stack Region\",\"Value\":{\"Ref\":\"AWS::Region\"},\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}-Region\"}}},\"StackName\":{\"Description\":\"CloudFormation provider root stack ID\",\"Value\":{\"Ref\":\"AWS::StackName\"},\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}-StackName\"}}},\"StackId\":{\"Description\":\"CloudFormation provider root stack name\",\"Value\":{\"Ref\":\"AWS::StackId\"},\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}-StackId\"}}},\"DeploymentBucketName\":{\"Description\":\"CloudFormation provider root stack deployment bucket name\",\"Value\":{\"Ref\":\"DeploymentBucketName\"},\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}-DeploymentBucketName\"}}},\"AuthRoleArn\":{\"Value\":{\"Fn::GetAtt\":[\"AuthRole\",\"Arn\"]}},\"UnauthRoleArn\":{\"Value\":{\"Fn::GetAtt\":[\"UnauthRole\",\"Arn\"]}},\"AuthRoleName\":{\"Value\":{\"Ref\":\"AuthRole\"}},\"UnauthRoleName\":{\"Value\":{\"Ref\":\"UnauthRole\"}}}}","Parameters":[{"ParameterKey":"DeploymentBucketName","ParameterValue":"amplify-test-dev-213334-deployment"},{"ParameterKey":"AuthRoleName","ParameterValue":"amplify-test-dev-213334-authRole"},{"ParameterKey":"UnauthRoleName","ParameterValue":"amplify-test-dev-213334-unauthRole"}],"Tags":[{"Key":"[***]tack","Value":"dev"},{"Key":"[***]ication","Value":"test"}]}])
2021-05-26T20:33:40.234Z|info : amplify-provider-awscloudformation.aws-cfn.cfnModel.createStack([{"StackName":"[***]ify-[***]st-[***]ev-[***]334","Capabilities":["CAPABILITY_NAMED_IAM","CAPABILITY_AUTO_EXPAND"],"TemplateBody":"{\"AWSTemplateFormatVersion\":\"2010-09-09\",\"Description\":\"Root Stack for AWS Amplify CLI\",\"Parameters\":{\"[***]cketName\":{\"Description\":\"Name of the common deployment bucket provided by the parent stack\",\"Type\":\"String\",\"Default\":\"DeploymentBucket\"},\"[***]eName\":{\"Type\":\"String\",\"Default\":\"AuthRoleName\"},\"[***]leName\":{\"Type\":\"String\",\"Default\":\"UnauthRoleName\"}},\"Resources\":{\"DeploymentBucket\":{\"Type\":\"AWS::S3::Bucket\",\"DeletionPolicy\":\"Retain\",\"Properties\":{\"BucketName\":{\"Ref\":\"DeploymentBucketName\"},\"BucketEncryption\":{\"ServerSideEncryptionConfiguration\":[{\"ServerSideEncryptionByDefault\":{\"SSEAlgorithm\":\"AES256\"}}]}}},\"AuthRole\":{\"Type\":\"AWS::IAM::Role\",\"Properties\":{\"RoleName\":{\"Ref\":\"AuthRoleName\"},\"AssumeRolePolicyDocument\":{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Deny\",\"Principal\":{\"Federated\":\"cognito-identity.amazonaws.com\"},\"Action\":\"sts:AssumeRoleWithWebIdentity\"}]}}},\"UnauthRole\":{\"Type\":\"AWS::IAM::Role\",\"Properties\":{\"RoleName\":{\"Ref\":\"UnauthRoleName\"},\"AssumeRolePolicyDocument\":{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Deny\",\"Principal\":{\"Federated\":\"cognito-identity.amazonaws.com\"},\"Action\":\"sts:AssumeRoleWithWebIdentity\"}]}}}},\"Outputs\":{\"Region\":{\"Description\":\"CloudFormation provider root stack Region\",\"Value\":{\"Ref\":\"AWS::Region\"},\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}-Region\"}}},\"StackName\":{\"Description\":\"CloudFormation provider root stack ID\",\"Value\":{\"Ref\":\"AWS::StackName\"},\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}-StackName\"}}},\"StackId\":{\"Description\":\"CloudFormation provider root stack name\",\"Value\":{\"Ref\":\"AWS::StackId\"},\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}-StackId\"}}},\"DeploymentBucketName\":{\"Description\":\"CloudFormation provider root stack deployment bucket name\",\"Value\":{\"Ref\":\"DeploymentBucketName\"},\"Export\":{\"Name\":{\"Fn::Sub\":\"${AWS::StackName}-DeploymentBucketName\"}}},\"AuthRoleArn\":{\"Value\":{\"Fn::GetAtt\":[\"AuthRole\",\"Arn\"]}},\"UnauthRoleArn\":{\"Value\":{\"Fn::GetAtt\":[\"UnauthRole\",\"Arn\"]}},\"AuthRoleName\":{\"Value\":{\"Ref\":\"AuthRole\"}},\"UnauthRoleName\":{\"Value\":{\"Ref\":\"UnauthRole\"}}}}","Parameters":[{"ParameterKey":"DeploymentBucketName","ParameterValue":"amplify-test-dev-213334-deployment"},{"ParameterKey":"AuthRoleName","ParameterValue":"amplify-test-dev-213334-authRole"},{"ParameterKey":"UnauthRoleName","ParameterValue":"amplify-test-dev-213334-unauthRole"}],"Tags":[{"Key":"[***]tack","Value":"dev"},{"Key":"[***]ication","Value":"test"}]}])
2021-05-26T20:33:45.258Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]ify-[***]st-[***]ev-[***]334"}])
2021-05-26T20:33:46.140Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]rmation:us-[***]st-[***]23:stack/[***]ify-[***]st-[***]ev-[***]334/[***]da20-[***]61-[***]eb-[***]5c-[***]df3ab"}])
2021-05-26T20:33:50.253Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]ify-[***]st-[***]ev-[***]334"}])
2021-05-26T20:33:51.101Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]rmation:us-[***]st-[***]23:stack/[***]ify-[***]st-[***]ev-[***]334/[***]da20-[***]61-[***]eb-[***]5c-[***]df3ab"}])
2021-05-26T20:33:55.262Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]ify-[***]st-[***]ev-[***]334"}])
2021-05-26T20:33:56.129Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]rmation:us-[***]st-[***]23:stack/[***]ify-[***]st-[***]ev-[***]334/[***]da20-[***]61-[***]eb-[***]5c-[***]df3ab"}])
2021-05-26T20:34:00.258Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]ify-[***]st-[***]ev-[***]334"}])
2021-05-26T20:34:01.144Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]rmation:us-[***]st-[***]23:stack/[***]ify-[***]st-[***]ev-[***]334/[***]da20-[***]61-[***]eb-[***]5c-[***]df3ab"}])
2021-05-26T20:34:05.263Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]ify-[***]st-[***]ev-[***]334"}])
2021-05-26T20:34:06.114Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]rmation:us-[***]st-[***]23:stack/[***]ify-[***]st-[***]ev-[***]334/[***]da20-[***]61-[***]eb-[***]5c-[***]df3ab"}])
2021-05-26T20:34:10.267Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]ify-[***]st-[***]ev-[***]334"}])
2021-05-26T20:34:12.122Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-05-26T20:34:12.122Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-west-2"}])
2021-05-26T20:34:12.123Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-05-26T20:34:12.131Z|info : amplify-provider-awscloudformation.attach-backend.storeCurrentCloudBackend.s3.uploadFile([{"Key":"[***]rent-[***]ud-[***]d.zip"}])
2021-05-26T20:34:12.136Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]ify-[***]st-[***]ev-[***]334-[***]ment"}])
2021-05-26T20:34:13.158Z|info : amplify-provider-awscloudformation.attach-backend.uploadFile.s3.uploadFile([{"Key":"[***]ify-[***]json"}])
2021-05-26T20:34:13.159Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ify-[***]json","Bucket":"[***]ify-[***]st-[***]ev-[***]334-[***]ment"}])
2021-05-26T20:36:34.380Z|info : amplify add api  
2021-05-26T20:42:58.193Z|info : amplify add api  
2021-05-26T20:47:15.262Z|info : amplify api mock  
2021-05-26T20:48:12.056Z|info : amplify api mock 


```

</details>

### Additional information

This issue is somehow related to [this](https://github.com/aws-amplify/amplify-cli/issues/2892) but it was closed

**Comment by SwaySway** [comment] 2021-05-26 22:39
@Rolando-Barbella 
Few questions here

- Are you able to run `amplify api gql-compile`?
- I was not able to repro on v4.51.2 (I am not using an M1 mac)
- Did this work with prior version?

**Comment by josefaidt** [comment] 2021-06-16 19:48
Hey @Rolando-Barbella :wave: unfortunately I have not been able to reproduce this with Node 12, 14, and 16, as well as the noted CLI version and higher (also not on an M1 mac). Are you experiencing this issue in newer Node.js and Amplify CLI versions?

**Comment by danabrams** [comment] 2021-06-29 14:00
This must be an m1 issue, because I'm having the exact same behavior on an m1 with 5.0.2 on Node 16.4.0

**Comment by josefaidt** [comment] 2021-06-29 17:29
Hey @danabrams thanks for the confirmation that you are also experiencing the issue with an M1. Do you perhaps have an Intel-based Mac you could try with to see if you're getting the same error with the same code? \cc @Rolando-Barbella

**Comment by danabrams** [comment] 2021-06-29 17:36
I do but I am traveling with only my m1 until next week.

**Comment by josefaidt** [comment] 2021-06-29 17:39
@danabrams No worries! I should be able to get ahold of someone with an M1 tomorrow to test it out and report back

**Comment by josefaidt** [comment] 2021-06-30 18:00
@danabrams @Rolando-Barbella :wave: what version and distribution of Java are y'all using? Java does not appear to be officially supported and I've seen a few "workaround" distros like Azul's, and I'm curious to hear what y'all are using so we can best emulate the environment.

**Comment by Rolando-Barbella** [comment] 2021-06-30 21:06
Hello @josefaidt sorry for the late reply, when I run `Java --version` I get the following:

```
openjdk version "16" 2021-03-16
OpenJDK Runtime Environment (build 16+14)
OpenJDK 64-Bit Server VM (build 16+14, mixed mode)
```

**Comment by josefaidt** [comment] 2021-06-30 22:02
Hey @Rolando-Barbella thank you for the info! We were able to reproduce the issue with a slightly newer version of openjdk on an M1 Mac, although we do not see the timeout error. I'll mark this as a bug 🙂

Notes for the team:

- Java version
  ```
  openjdk 16.0.1 2021-04-20
  OpenJDK Runtime Environment Zulu16.30+19-CA (build 16.0.1+9)
  OpenJDK 64-Bit Server VM Zulu16.30+19-CA (build 16.0.1+9, mixed mode)
  ```
- no timeout error
- no codegen message
- `amplify/mock-data/dynamodb` directory is created, but not the *.db file
- ports 20003 and 20002 are in use, GraphiQL is started
- GraphiQL shows current auth (auth with user pools is enabled, user pool selection is shown in GraphiQL)
- GraphiQL explorer is empty

**Comment by Rolando-Barbella** [comment] 2021-07-01 13:59
@josefaidt  So glad you managed to reproduce it, M1 machines sometimes can be particular, not the first time I have reported an issue related to some tool, library, and my M1, but I think every day more people are owning this type of new model

**Comment by danabrams** [comment] 2021-07-05 17:26
I can report that on the m1 machine, using openjdk-18 Aarch64 suffers the same problem, but running `amplify mock` on an m1 with openjdk-16 x64 under rosetta does successfully mock.

**Comment by josefaidt** [comment] 2021-07-06 20:38
Hey @danabrams can you post a link to the distribution you're using to successfully mock? Perhaps this is something we can document as a known workaround for those with M1 Macs

**Comment by danabrams** [comment] 2021-07-06 21:56
```
openjdk 16.0.1 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-24)
OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
```
Note: Not a zulu build.

Works well for me on an m1

**Comment by danabrams** [comment] 2021-07-06 21:58
If you want I can contribute a PR documenting it.

**Comment by josefaidt** [comment] 2021-07-07 15:01
Hey @danabrams thank you for the details we were able to confirm mock is working with that distribution on our end as well. I think a PR would be great! I'll go ahead and remove the bug label in favor of adding a note to the docs for M1 Mac owners to use the specific Java version noted above. @Rolando-Barbella could you try this Java version and confirm whether it resolves the issue for you as well?

**Comment by josefaidt** [comment] 2021-07-16 16:50
Hey @Rolando-Barbella :wave: just following-up to see if that Java version mentioned above resolved your issue?

@danabrams are you still willing to make a PR to our docs site to add a note for M1 Mac users?

**Comment by Rolando-Barbella** [comment] 2021-07-17 23:03
Hi, sorry for the slow reply, I'm just not too sure on how to install that version of Java in my machine, I follow the link with it contains a few folder, again not sure what to do after neither I know what would happen with current version I have in my machine

**Comment by josefaidt** [comment] 2021-07-19 19:00
Hey @Rolando-Barbella no worries! The version of Java that resolves the issue appears to be an update to the version you mentioned:

```
openjdk version "16" 2021-03-16
OpenJDK Runtime Environment (build 16+14)
OpenJDK 64-Bit Server VM (build 16+14, mixed mode)
```

which should update to:

```
openjdk 16.0.1 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-24)
OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
```

**Comment by danabrams** [comment] 2021-07-20 21:33
> @danabrams are you still willing to make a PR to our docs site to add a note for M1 Mac users?

Yes, doing so now.

**Comment by josefaidt** [comment] 2021-10-01 21:04
Closing due to merge of documentation note. Thanks again @danabrams for opening that PR! 🙂

**Closed by josefaidt** 2021-10-01 21:04 UTC
Labels: dependency-issue, documentation

**Comment by rdeckj** [comment] 2021-11-03 20:04
I don't think this is purely an apple silicone problem. Members of my team have run across this issue with Macs /w Intel chips and the following versions:

openjdk11
Amplify 6.3.1
Node 16.9.1

Bumping to openjdk 17 solved this problem for us.

**Comment by duranmla** [comment] 2021-12-07 11:41
While the solution proposed works. I had a bit of extra confusion because I didn't know how to work with the JDK link and setup my environment properly as I was fearful of breaking something else. Therefore, here I expect to maybe help to future people like me:

1. Download the JDK version that folks propose above https://github.com/aws-amplify/amplify-cli/issues/7411#issuecomment-875108259
2. Install `jenv` using brew like explained here: https://www.jenv.be
3. Add your current installation of Java to `jenv` using `jenv add`
4. Add the version of Java you download from the link above like `jenv add ~/jdk-16.0.1.jdk/Contents/Home` _(cause I move the download folder to the root)_
5. Set the java version to the one that solves the issue in this case `16.0.1`
6. If you run `java --version` you should see what is suggested here https://github.com/aws-amplify/amplify-cli/issues/7411#issuecomment-882783643
7. Everything should work now and you can switch back to the version of Java you had at any time

Any issues with `jenv`?
- I had to manually create folders for `jenv` using `> mkdir ~/.jenv` and `> mkdir ~/.jenv/versions` like https://github.com/jenv/jenv/issues/167#issuecomment-854474144
- I had to run `jenv doctor` and realise I needed to `echo 'eval "$(jenv init -)"' >> ~/.bash_profile`
- To allow `jenv add $(/usr/libexec/java_home)` to work I had to run the symlink that Homebrew ask me to when `brew info java`

<img width="649" alt="CleanShot 2021-12-07 at 12 40 56@2x" src="https://user-images.githubusercontent.com/1425162/145022943-32a92783-f162-4654-960d-3d2d48c33ef1.png">

Happy coding! 🚀
