### ISSUE TITLE
codegen models fails when can't find file

### ISSUE THREAD

**Issue by amcdnl** [aws-amplify/amplify-cli#4843] opened 2020-07-15 16:01 UTC
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Running `amplify codegen models` produces the following error:

```
➜  my-project git:(master) ✗  amplify codegen models
ENOENT: no such file or directory, open '/Users/me/dev/my-project/amplify/backend/storage/uploads/parameters.json'
Error: ENOENT: no such file or directory, open '/Users/me/dev/my-project/amplify/backend/storage/uploads/parameters.json'
    at Object.openSync (fs.js:461:3)
    at Object.readFileSync (fs.js:364:35)
    at AmplifyToolkit.readJsonFile [as _readJsonFile] (/Users/me/.nvm/versions/node/v14.4.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/read-json-file.js:14:33)
    at getBucketName (/Users/me/.nvm/versions/node/v14.4.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/transform-graphql-schema.js:538:44)
    at transformGraphQLSchema (/Users/me/.nvm/versions/node/v14.4.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/transform-graphql-schema.js:405:38)
    at validateSchema (/Users/me/.nvm/versions/node/v14.4.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/models.js:77:3)
    at Object.generateModels (/Users/me/.nvm/versions/node/v14.4.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/models.js:31:3)
    at Object.run (/Users/me/.nvm/versions/node/v14.4.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/commands/codegen/models.js:9:7)
    at Object.executeAmplifyCommand (/Users/me/.nvm/versions/node/v14.4.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/amplify-plugin-index.js:9:3)
    at executePluginModuleCommand (/Users/me/.nvm/versions/node/v14.4.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:158:7)
```

**Amplify CLI Version**
4.24.0

**To Reproduce**
Run the command

**Expected behavior**
If it can't find a file, it doesn't fail.

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system
MAC OSX
v14.4.0

**Additional context**

**Comment by UnleashedMind** [comment] 2020-07-15 21:31
@amcdnl 
We need more information to investigate this issue. 
What are the resources you added to your project? 
How is your GraphQL API's schema defined? 

If possible, please zip the `amplify` folder of your project and send it over to this email address: `amplify-cli@amazon.com` with title `Re: Github Issue 4843`

**Comment by amcdnl** [comment] 2020-07-15 22:05
No problem -> Let's see if we can figure this out here and if not i can send over the files...

I've split my app into 2 separate git repos - React UI and API Backend. Currently the UI fetches the schema remotely using `amplify codegen` but when I try to run this command I get this failure. The failure is related to backend resources that are not available in the UI project file structure.

cc @gsans

**Comment by UnleashedMind** [comment] 2020-07-15 22:22
I'm not able to reproduce the issue using simple setups and simple schemas. 
what are the other resources you added to your project? is there storage resource?

**Comment by amcdnl** [comment] 2020-07-16 00:26
I mean why is it erroring on a storage resource - thats not even related to the schema generation ?

**Comment by amcdnl** [comment] 2020-07-16 15:27
On a side note, when I run the command in my API project, it gives me this error:

```
➜  api git:(master) ✗ amplify codegen models

GraphQL schema compiled successfully.

Edit your schema at /Users/me/dev/api/amplify/backend/api/api/schema.graphql or place .graphql files in a directory at /Users/me/dev/api/amplify/backend/api/api/schema
DataStore does not support 1 to 1 connection with both sides of connection as optional field
Error: DataStore does not support 1 to 1 connection with both sides of connection as optional field
    at Object.processConnections (/Users/me/.nvm/versions/node/v14.4.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/src/utils/process-connections.ts:201:17)
    at /Users/me/.nvm/versions/node/v14.4.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/src/visitors/appsync-visitor.ts:448:32
    at Array.forEach (<anonymous>)
    at /Users/me/.nvm/versions/node/v14.4.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/src/visitors/appsync-visitor.ts:447:20
    at Array.forEach (<anonymous>)
    at AppSyncModelJavascriptVisitor.processConnectionDirective (/Users/me/.nvm/versions/node/v14.4.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/src/visitors/appsync-visitor.ts:446:34)
    at AppSyncModelJavascriptVisitor.processDirectives (/Users/me/.nvm/versions/node/v14.4.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/src/visitors/appsync-visitor.ts:241:10)
    at AppSyncModelJavascriptVisitor.generate (/Users/me/.nvm/versions/node/v14.4.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/src/visitors/appsync-javascript-visitor.ts:48:10)
    at Object.exports.plugin (/Users/me/.nvm/versions/node/v14.4.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/src/plugin.ts:49:20)
    at Object.executePlugin (/Users/me/.nvm/versions/node/v14.4.0/lib/node_modules/@aws-amplify/cli/node_modules/@graphql-codegen/core/src/execute-plugin.ts:54:12)
```

**Comment by UnleashedMind** [comment] 2020-07-20 20:28
First make sure you API project works then. 
Did you amplify init'ed another project on your UI project? If you are only using the API, you don't need to do it, just run amplify codegen and project the API Id.

**Comment by gsans** [comment] 2020-08-05 09:09
Any updates on this @nikhname?

**Comment by nikhname** [comment] 2020-12-16 00:49
I was not able to reproduce this using basic schemas. @amcdnl could you please send your schema over to amplify-cli@amazon.com?

**Comment by nikhname** [comment] 2020-12-18 18:33
Closing because we were not able to reproduce. Please comment if you have further steps to reproduce.

**Closed by nikhname** 2020-12-18 18:33 UTC
Labels: code-gen, pending-response, pending-triage
