### ISSUE TITLE
Socket connection to the server was not read or written to within the timeout period

### ISSUE THREAD

**Issue by mlynch** [aws-amplify/amplify-cli#462] opened 2018-11-15 17:51 UTC
**Describe the bug**
When running `amplify push`, an error is thrown:

<img width="833" alt="screenshot 2018-11-15 11 50 12" src="https://user-images.githubusercontent.com/11214/48571538-aab8a480-e8cc-11e8-83e3-0af6f09a5612.png">

**To Reproduce**
Unsure how to reproduce. In the example above, it's creating an Api, so possibly related to that.

**Expected behavior**
Push should run and complete

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.13.6
 - Amplify CLI 0.1.34

**Comment by mlynch** [comment] 2018-11-15 17:56
From my quick research, it seems related to S3: 
https://github.com/aws/aws-sdk-js/issues/281

**Comment by kaustavghosh06** [comment] 2018-11-15 17:58
@mlynch I've seen this happen due to no internet/network connection or when there's a proxy in the network blocking access to the AWS services. Can you try to push again (with network connection on) and see if you can reproduce? I'm looking into the above mentioned issue as well

**Comment by mlynch** [comment] 2018-11-15 18:01
My network connection is good, not using any Proxies or anything. Thanks

**Comment by kaustavghosh06** [comment] 2018-11-15 19:02
Interesting. I'm not able to reproduce it with 0.1.34. I'll upgrade the aws-sdk version that we're using since we're using a bit older version and this issue seems to be fixed with the latest version. 
Are you continuously getting this error on a push or is it intermittent?

**Comment by mlynch** [comment] 2018-11-15 19:57
I blew away my amplify folder locally and recreated everything. I gave my API a different name and was able to push it this time.

I wonder if a previous push to create the API got into an inconsistent state and that caused the timeout?

**Comment by kaustavghosh06** [comment] 2018-11-19 20:10
@mlynch  I tried reproducing this by halting my first push and trying to push again the second time (a GraphQL API), but still couldn't reproduce this. I'll keep an eye out for this issue in the future.

**Comment by kaustavghosh06** [comment] 2019-02-20 00:36
@mlynch We've added exponential backoff retry mechanism to our API calls to prevent this behavior. please let me know if you're still seeing this issue with the latest CLI version.

**Closed by kaustavghosh06** 2019-02-20 00:36 UTC
Labels: investigating, storage

**Comment by rahulvyas1** [comment] 2019-10-16 08:28
I am still facing this issue!

**Comment by ThedathUMCG** [comment] 2020-10-02 05:40
I just experienced this issue. I got this error when I try to push some changes I've made in an API. I even cloned the project and tried pushing changes again but error is still there. Please help!
![image](https://user-images.githubusercontent.com/64180356/94891471-cbc61680-049f-11eb-9743-4ca77cba17b7.png)
