### ISSUE TITLE
Amplify creates two GSIs instead of one LSI?

### ISSUE THREAD

**Issue by yammesicka** [aws-amplify/amplify-cli#7658] opened 2021-07-03 18:26 UTC
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**: Amplify, GraphQL Schema, DynamoDB GSI / LSI
**Amplify CLI Version**: 5.1.0
**What AWS Services are you utilizing?**: DynamoDB, AppSync

Hi everyone, thank you for creating this framework.
I'm trying to use the `@key` directive to create indexes in DynamoDB, and I get something that I think(?) can be considered a strange behavior.

Snippet:
```graphql
type TruckStock
    @model(timestamps:{createdAt: "createdAt", updatedAt: "updatedAt"})
    @key(fields: ["truckId", "variantId"])
    @key(name: "byProduct", fields: ["truckId", "productId"], queryField: "listTruckStockByProduct")
    @key(name: "byTruckId", fields: ["truckId"], queryField: "listTruckStockByTruck")
{
    truckId: ID!
    variantId: ID!
    productId: ID!
    quantity: Int!
}
```

I'm trying to achieve the following:
- `truckId` will be the hash value, and `variantId` will be my range value.
- `productId` will be a LSI.
- It will be possible to get all the entries of a specific `truckId` (without querying by productId/variantId).

Currently, Amplify creates 2 GSIs - one for `truckId` and the other for `{hash: truckId, range: productId}`.

Am I doing something wrong? Is there a better way to do this?

Thanks!

**Comment by cjihrig** [comment] 2021-07-08 20:48
Amplify creates a GSI for each [`@key`](https://docs.amplify.aws/cli/graphql-transformer/key) that has a `name`. In your example, a GSI is created for `byProduct` and `byTruckId`, and the unnamed key (`["truckId", "variantId"]`) is the primary.

**Comment by yammesicka** [comment] 2021-07-08 20:57
I found an answer from 2019 that says it is possible to create an [LSI](https://github.com/aws-amplify/amplify-cli/issues/1725#issuecomment-505862542). Is this wrong, or maybe there is another way to create an LSI?

**Comment by cjihrig** [comment] 2021-07-09 20:44
You can technically create an LSI. However, you need to set the [`secondaryKeyAsGSI`](https://docs.amplify.aws/cli/reference/feature-flags#secondaryKeyAsGSI) feature flag to `false` in your project's `cli.json` file. However, it's worth noting that `secondaryKeyAsGSI` is deprecated as of May 1, 2021.

**Comment by yammesicka** [comment] 2021-07-11 09:33
Is there a supported way to create LSI which is not deprecated? :)

**Comment by cjihrig** [comment] 2021-07-12 19:14
@yammesicka not currently. If this is something you need, I'd suggest weighing in on https://github.com/aws-amplify/amplify-cli/issues/6650 with your use case.

**Comment by cjihrig** [comment] 2021-07-12 20:34
Closing this as a duplicate of #6650

**Closed by cjihrig** 2021-07-12 20:34 UTC
Labels: graphql-transformer, question
