### ISSUE TITLE
Running `amplify api gql-compile` results in 'TypeError: Cannot convert undefined or null to object'

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#2390] opened 2019-09-24 15:21 UTC
**Describe the bug**
I recently upgraded to 3.9.0 and now `amplify api gql-compile` results in this error: `TypeError: Cannot convert undefined or null to object`

**Additional context**
Not sure what you need to identify root cause. Happy to provide more info.

**Comment by hisham** [comment] 2019-09-24 15:46
Now I get the error again, after I changed the graphql schema and did a push.

**Comment by kevcam4891** [comment] 2019-09-25 00:18
Yes, `amplify env pull` is the solution to bring things back up to date. Also, what version of amplify-cli are you using? `amplify --version`? I am running into this issue almost never now that I'm using the latest version 3.9. I was using 3.0 when this was happening for me a lot.

**Comment by hisham** [comment] 2019-09-25 02:52
```
> amplify --version
Scanning for plugins...
Plugin scan successful
3.9.0
```

Yeah `amplify env pull` fixes but it seems to re-occur again after push with changed gql schema.

**Comment by SwaySway** [comment] 2019-09-26 22:24
@hisham are you able to share the schema as well?

**Comment by hisham** [comment] 2019-09-26 22:29
@SwaySway sure I just sent it to amplify-cli@amazon.com

**Comment by SwaySway** [comment] 2019-09-26 23:15
@hisham Recieved the schema taking a look. Could you also provide your `.graphqlconfig.yml`? Checking to see if this might be related to #2412, as you mentioned this happened when you updated the enum.

**Comment by hisham** [comment] 2019-09-26 23:33
Sure done.

**Comment by kaustavghosh06** [comment] 2019-10-31 18:02
@hisham We weren't able to reproduce this error with the latest version of the CLI? Is it still a recurring issue for you?

**Comment by hisham** [comment] 2019-11-06 21:49
@kaustavghosh06 I haven't touched the backend part of my app in a while but will be in the coming days. Currently however I am blocked with this bug after upgrading to 3.17: https://github.com/aws-amplify/amplify-cli/issues/2390

**Comment by hisham** [comment] 2019-11-07 18:20
I just got this error again. I don't have exact repro steps. I made changes to graphql, pushed. All was working fine. Then switched to another git branch with slightly different graphql schema, ran compile graphql and got the error.

**Comment by kevcam4891** [comment] 2019-11-11 12:10
`amplify env checkout` has always been my savior after switching branches
and experiencing something like this.

**Comment by hisham** [comment] 2019-12-10 20:50
I'm now getting this error consistently for one of my environments regardless what I do. Not good. Still investigating.

**Comment by hisham** [comment] 2019-12-10 21:04
I'm instrumenting the code and managed to get it to throw a stack trace, it is as follows: 

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /Users/hisham/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:148:43
    at step (/Users/hisham/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:44:23)
    at Object.next (/Users/hisham/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:25:53)
    at fulfilled (/Users/hisham/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:16:58)
```
I'm running amplify v3.17

**Comment by hisham** [comment] 2019-12-10 21:13
So the error happens on this line in amplifyUtils.ts in ensureMissingStackMappings: 

`const outputIdsInStack = Object.keys(lastDeployedStack.Outputs);`

For some reason I have a lastDeployedStack with no Outputs

**Comment by hisham** [comment] 2019-12-10 21:30
So I replaced this: 

`const outputIdsInStack = Object.keys(lastDeployedStack.Outputs);`

with: 

`const outputIdsInStack = lastDeployedStack.Outputs ? Object.keys(lastDeployedStack.Outputs) : [];`

And everything worked correctly. 

Now why do I have a lastDeployedStack with no Outputs? I have no idea..goes beyond my current knowledge of amplify cli and cloudformation stacks.

**Comment by hisham** [comment] 2019-12-10 21:34
@SwaySway hopefully my fix above helps. Everything seems to be working fine now. 

Also interestingly, when I do a `amplify env pull` followed by `amplify api codegen` that `ensureMissingStackMappings ` function is never called. So it's some specific case that calls it. 

Anyways hopefully you guys can make a permanent fix soon.

**Comment by SwaySway** [comment] 2019-12-10 22:54
@hisham Is it possible for you send the updated schema you are using when you are running into this issue? I'd like to see if I can replicate the error to take a deeper look at it.

**Comment by hisham** [comment] 2019-12-10 23:17
Sure I just sent it to amplify-cli@amazon.com.

**Comment by SwaySway** [comment] 2019-12-12 22:36
@hisham I wasn't able to replicate it from the schema itself though since outputs are optional this is something the pr you've added can catch if they don't exist in the stack.

**Comment by SwaySway** [comment] 2019-12-14 01:00
Closing this as the pr has been merged feel free to comment on here if you run into this issue again.

**Closed by SwaySway** 2019-12-14 01:00 UTC
Labels: graphql-transformer, pending-response, pending-triage
