### ISSUE TITLE
Primary Index with a sort key is requiring ID on the create mutation

### ISSUE THREAD

**Issue by malcomm** [aws-amplify/amplify-cli#3349] opened 2020-02-05 19:08 UTC
**Please note:** this is a blocker.

**Describe the bug**

Given the following sample schema:
```gql
type Foo
  @model
  @key(fields: ["id", "updatedAt"])
{
  id: ID!,
  updatedAt: AWSDateTime!
In order to create a Foo, I am required to supply an `id`:
```
```js
export type CreateFooInput = {
  id: string;
  ....
```

`id` should not be supplied on the create.

**Amplify CLI Version**

4.13.1

**To Reproduce**

Create a model with above primary index with a sort key.

**Expected behavior**

```id``` should not be required.

Additional context
#401 
#3348

**Comment by SwaySway** [comment] 2020-02-06 18:35
Closing as duplicate of #3348 as it's addressing the same issue of fields being required.

**Closed by SwaySway** 2020-02-06 18:35 UTC
Labels: graphql-transformer, pending-triage
