### ISSUE TITLE
`amplify mock function` causes undefined error

### ISSUE THREAD

**Issue by benharvie** [aws-amplify/amplify-cli#11754] opened 2023-01-12 01:53 UTC
### How did you install the Amplify CLI?

`npm install -g @aws-amplify/cli@latest`

### If applicable, what version of Node.js are you using?

v16.11.1

### Amplify CLI Version

10.6.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Deleting backend environments in order to recreate them for testing purposes.

### Describe the bug

When running `amplify mock function`, I get this response:

> Cannot read property 'providerController' of undefined

### Expected behavior

Expected a list of lambda functions to be provided, to select which lambda function to mock.

### Reproduction steps

Unable to reproduce in an empty directory, however, in my current project it occurs simply by:

1. `amplify mock function`

The error occurs directly after the command, no lambda functions are listed as would be expected.

### Log output

<details>

```
2023-01-12T01:46:26.232Z|info : amplify function mock  
2023-01-12T01:46:26.296Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
```

</details>

### Additional information

- Every newly created environment gets this error.
- Old environments do not seem to get this error.
- Cloning old and working environments does not seem to resolve the error.

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment] 2023-01-12 16:52
Hey @benharvie :wave: thanks for raising this! I was not able to reproduce this using the provided steps using Amplify CLI 10.6.1, nor when using 10.0.0. Can you try running the same command using the `--debug` flag? Additionally, can you post the project ID output from `amplify diagnose --send-report`?

**Comment by benharvie** [comment] 2023-01-12 17:02
Hey @josefaidt:) running the same command with `--debug` throws the same error with no additional information. I also attempted to send a report but the report seems to fail to send, the output is below:

> amplify diagnose --send-report
> 
> Learn more at https://docs.amplify.aws/cli/reference/diagnose/
> 
> ✅ Report saved: /var/folders/91/xq122gcs2tn6rtjyc2nn9qw40000gn/T/huntr/report-1673542751449.zip
> 
> ⠏ Sending zip
> 
> ✖ Sending zip

**Comment by josefaidt** [comment] 2023-01-12 18:27
Hey @benharvie thanks for clarifying despite the rough experience! Can you walk me through how the function was added and how the project is set up? Was this project recently cloned from git? 

> Deleting backend environments in order to recreate them for testing purposes.

Can you elaborate on this note? Were backend environments deleted from the AWS Amplify console or via the CLI?

As a parting question, would you mind sending a zip archive of your `amplify/` directory to amplify-cli@amazon.com? If so, please be sure to omit any sensitive information

**Comment by benharvie** [comment] 2023-01-12 18:43
That's ok, thanks for the help, it's much appreciated! The function was added via. `amplify add function`, we have been using amplify for some time and this is the first time this has occurred, we haven't done anything out of the ordinary as far as I am aware.

Backend environments were removed via. the AWS Amplify console.

I will send over the .zip created from the `amplify diagnose --send-report` command manually to the email provided.

Thanks again

**Comment by benharvie** [comment] 2023-01-22 01:04
Hi, I just wanted to check in and ensure the email was received successfully.

Thanks

**Comment by josefaidt** [comment] 2023-02-14 22:42
Hey @benharvie apologies for the delay here!! Yes, we received your zip archive, thank you for sending that over. Looking into this a bit further it appears to be erroring here https://github.com/aws-amplify/amplify-cli/blob/dev/packages/amplify-category-function/src/index.ts#L295

Where it is looking to get the `Lambda` service configuration when iterating over your `functions` key in `amplify/backend/amplify-meta.json`. For example, I'm able to reproduce this if I manually change the `service` value in this file:

```diff
"a117541ef2c4d5": {
  "build": true,
  "providerPlugin": "awscloudformation",
- "service": "Lambda"
+ "service": "Lambdafake"
}
```

```
➜  amplify mock function
Cannot read property 'providerController' of undefined
```

Despite this, I do not see the discrepancy in your `amplify-meta.json` file. Do you still experience this issue after running `amplify env checkout <current-env-name>` (which will trigger a refresh on this meta file)? Did this start occurring after deleting the Amplify envs in the AWS Console or after merging a new Function from another env/branch?

**Comment by josefaidt** [comment] 2023-03-21 00:36
Hey @benharvie are you still experiencing this?

**Comment by benharvie** [comment] 2023-03-21 04:27
This issue has fixed itself over time, I no longer experience this error:)

**Comment by josefaidt** [comment] 2023-03-21 15:53
Hey @benharvie thanks for clarifying and glad to hear this is resolved for you! I'll close this issue for now but if something comes up please don't hesitate to reach out!

**Closed by josefaidt** 2023-03-21 15:53 UTC
Labels: functions, pending-triage, mock
