### ISSUE TITLE
AccessDenied: Access Denied when trying to .put or .get on S3

### ISSUE THREAD

**Issue by danmight** [aws-amplify/amplify-cli#4055] opened 2020-03-06 23:14 UTC
**Describe the bug**
When I try to get or put a file on S3 using Storage.put or Storage.get I get an access denied error.

Amplify CLI - 4.13.4
aws-amplify - 2.2.6

**To Reproduce**

I'm using React.

` const awsKey = await Storage.put(fileName, pdfBlob, {level: 'public', type: 'application/json'})`

I have a valid file name and blob. The interesting thing is this code worked before. I deleted my entire amplify instance and rebuilt it and that's when it stopped working. I was also getting a Client Not Authorized Error when I tried to use the IAM authRole  for authentication on API Gateway to call a lambda function. I got around that by making a cognito authorizer and using that as the auth method.

I'm wondering if I'm missing something in the rebuilding that's causing the IAM roles to not work or be invoked.. 

I checked that the IAM roles and the policies that Amplify attaches to the cognito authRole and they are there.

Under "Last Activity" on the authRole in the IAM console it shows no prior activity. It seems like these roles are not being used to authenticate my user to put or get. 

I noticed the same thing when I was struggling with the API Gateway IAM auth issue. I deleted the whole amplify project because I could only get the API Gateway to call a lambda function on my master branch and master environment. All other branch/environment combinations got not authorized error. When I rebuilt it, it stopped working on the master branch as well for the API Gateway, which leads me to believe there's some setting not right but I've checked all the obvious places for permissions and they are all the usual ones auto-generated by amplify that have worked before. 

Debugging Window:
<img width="1103" alt="Screen Shot 2020-03-06 at 4 03 07 PM" src="https://user-images.githubusercontent.com/47647812/76129611-fbbe4180-5fc4-11ea-988e-2e64cfbe79b0.png">

**Comment by akshbhu** [comment] 2020-04-29 21:28
Hi @danielblignaut  and @danmight 

Regarding the ****UserRole** issue** 

 I followed the exact steps mentioned above, I am able to use put and get APIs with out any error. Can you send the amplify folder which has this error so that I can reproduce this to **amplify-cli@amazon.com.**

One more thing you can try is updating amplify-cli version and amplify-js version to latest and try again.

Let me know if this thing works for you.

**Comment by kaustavghosh06** [comment] 2020-04-29 22:10
@danielblignaut @danmight I think the issue is tied to the access policies for the users in a group? You are assuming that the group will inherit all the policies tied to an auth IAM role dy default? That's not the case actually. You'll have to go through the `amplify update storage` flow and select the operations you want a certain group to have access to and that's when the IAM role associated with the user pool group will be updated. Let me know if I'm understanding this incorrectly.

**Comment by akshbhu** [comment] 2020-05-06 21:56
Let me know if above issue is solved. For now I am closing this issue , if you are still stuck , you can comment on this and I will reopen this issue.

**Comment by danielblignaut** [comment] 2020-05-26 07:29
@kaustavghosh06 @akshbhu exactly the reason. It's not necessarily a bug but I feel the workflow could be more intuitive. I'm not sure if there have been changes to the CLI since my last comment but perhaps updating the prompt when you add the storage category and there are user groups, we should notify the user of this? Or perhaps a note in the docs even. I don't mean to open this issue up again unnecessarily. I will run through my amplify settings today and try recreate with screenshots for you if it's still an issue.

**Comment by iThink32** [comment] 2020-12-16 07:56
hey guys I have the same issue , but on my end it works on the simulator but not on a device , I also believe its working as IAM is set up via CLI but fails then run on a device, is there any way I can specify Storage to use Cognito instead of IAM for auth?

**Comment by MontoyaAndres** [comment] 2021-01-13 04:12
I'm facing the same issue, I have updated the Bucket to add a trigger, like this:

```
andres@andres:~/Entrepreneurship/TeVi$ amplify update storage
? Please select from one of the below mentioned services: Content (Images, audio, video, etc.)
? Who should have access: Auth and guest users
? What kind of access do you want for Authenticated users? create/update, read
? What kind of access do you want for Guest users? read
? Do you want to add a Lambda Trigger for your S3 Bucket? Yes
? Select from the following options Create a new function
Successfully added resource S3Triggerde8bc6ca locally
? Do you want to edit the local S3Triggerde8bc6ca lambda function now? No
Successfully updated resource
```

So, I tried to upload an image, logged in as a user, but the lambda throws me this error:

```
2021-01-13T03:38:01.328Z	453e3118-2293-4632-be5e-aed92f7f2a6f	ERROR	{ AccessDenied: Access Denied
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/services/s3.js:700:35)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message: 'Access Denied',
  code: 'AccessDenied',
  region: null,
  time: 2021-01-13T03:38:01.267Z,
  requestId: '223B11A29A616F64',
  extendedRequestId:
   'B+OEiQmGOdHQTCSIqERtk7Dvto+Ohqysz+9tkB6np0u+2vfLLU/pXvGW01r3+J3gvPpjVhO3iGc=',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 45.67291209389794 }
```

So, the lambda is not able to just do a getObject operation :(. How can I resolve it? Thanks.

**Comment by akshbhu** [comment] 2021-01-14 19:13
Hi @MontoyaAndres 

1) Is the user that you logged in with is part of a group?
2) Are you able to upload/get  object to S3(Can you check your bucket after doing an operation)?

To give you some context : S3 Trigger looks for an event for S3 either objectCreated ot Object removed and based on the event, it runs its underlying code.

**Comment by MontoyaAndres** [comment] 2021-01-14 19:58
Hi @akgm3i , the user is not part of any group and yes, I'm able to upload/get content. I have created this issue for more context: https://github.com/aws-amplify/amplify-cli/issues/6375#issue-784776221 but seems is working well, maybe there's something wrong with the permissions 🤔. I'm still looking for it 😪.

**Comment by akshbhu** [comment] 2021-01-14 21:36
Closing this issue as this case not related to this issue(related to permissions). 
Feel free to open a new issue and we can help on that.

**Closed by akshbhu** 2021-01-14 21:36 UTC
Labels: pending-response, pending-triage, storage

**Comment by matansagee** [comment] 2021-02-27 23:37
@akshbhu Hi! I having the same issue with the REST API and API gateway.
When the user is part of a group the request to API gateway is failing, but when I manually remove the group from the Cognito the API is working.

This is when the user is part of a group.
![image](https://user-images.githubusercontent.com/8274517/109403280-3e8dcd80-792a-11eb-8fd4-f1e7acef1918.png)
API gateway logs:
![image](https://user-images.githubusercontent.com/8274517/109403329-92001b80-792a-11eb-9857-a27af0e5bddd.png)



When I remove the group.
![image](https://user-images.githubusercontent.com/8274517/109403319-7a289780-792a-11eb-9dc6-eae77750e727.png)
API gateway logs
![image](https://user-images.githubusercontent.com/8274517/109403337-a6dcaf00-792a-11eb-8f5e-73f6b63e7ec9.png)

The code to call the API

![image](https://user-images.githubusercontent.com/8274517/109403352-cd024f00-792a-11eb-942d-0cddc81d36f3.png)

I have been debugging this issue for the last couple of days, and it seems that the group is the problem.

**Comment by matansagee** [comment] 2021-02-28 00:57
Solved the issue by `amplify api update` and added the group auth to the relevant API

![image](https://user-images.githubusercontent.com/8274517/109404628-e52b9b80-7935-11eb-86e3-db69906e18e9.png)


@akshbhu I think the documentation should be improved to state the authorization hierarchy. First the group, then the user.
