### ISSUE TITLE
Cannot prompt for [Are you sure you want to continue?] in a non-interactive shell

### ISSUE THREAD

**Issue by pratikbalochiya** [aws-amplify/amplify-cli#13390] opened 2023-11-06 12:52 UTC
### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v18.18.0

### Amplify CLI Version

12.7.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Nope

### Describe the bug

🛑 Cannot prompt for [Are you sure you want to continue?] in a non-interactive shell

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: 86c4b04a-1587-4a95-99a2-c8620278d86f
- Creating Zip

✅ Report saved: C:\Users\LPS85\AppData\Local\Temp\PROJECT_NAME\report-1699269479705.zip

- Sending zip
√ Done

Project Identifier: a8002494b1b9b48b96a0bcb0fae0c733

### Expected behavior

It should deploy

### Reproduction steps

🛑 Cannot prompt for [Are you sure you want to continue?] in a non-interactive shell

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: 86c4b04a-1587-4a95-99a2-c8620278d86f
- Creating Zip

✅ Report saved: C:\Users\LPS85\AppData\Local\Temp\PROJECT_NAME\report-1699269479705.zip

- Sending zip
√ Done

Project Identifier: a8002494b1b9b48b96a0bcb0fae0c733

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment] 2023-11-06 16:08
Hey @pratikbalochiya :wave: thanks for raising this! We've had similar reports in the past for shells like Git Bash on Windows. Are you using Git Bash by chance?

**Comment by pratikbalochiya** [comment] 2023-11-07 06:42
Hi @josefaidt , Thanks for your feedback, I checked in all prompts like git bash, command prompt & powershell, Everywhere getting same error

**Comment by ykethan** [comment] 2023-11-07 16:51
Glad to hear you were able to workaround this.
The issue is currently being tracked on https://github.com/aws-amplify/amplify-cli/issues/10552.
Closing this issue.

**Closed by ykethan** 2023-11-07 16:51 UTC
Labels: platform, pending-triage

**Comment by Smith-Steve** [comment] 2024-01-02 17:01
I ran into this same issue with git bash for windows but had a slightly different error. Instead of what this person got, it said, `Cannot prompt for [choose the type of app that you're building] in a non-interactive shell`
[amplify-cli-2023-12-31.log](https://github.com/aws-amplify/amplify-cli/files/13812188/amplify-cli-2023-12-31.log)
[amplify-cli-2024-01-02.log](https://github.com/aws-amplify/amplify-cli/files/13812190/amplify-cli-2024-01-02.log)
[amplify-cli-2024-01-01.log](https://github.com/aws-amplify/amplify-cli/files/13812189/amplify-cli-2024-01-01.log)

I don't know if this is helpful or not, but in Gitbash when you're selecting the options, I've noticed that instead of the selection your making corresponding to the option you selected, it is in fact selecting two options below the option your curser (the type prompt that blinks and looks like "|"). So when I was initially making my selection, I had two move the curser two lines up, into the actual text of the prompt, in order to make my first selection.

I was able to use the same workaround successfully. I attached two logs below.

The session identifier I was returned for my LAST failed attempt (which just took place minutes before I posted this) is c3fe04a5-9f1f-46d6-b814-d726730dddf6

Hope this is helfpul
