### ISSUE TITLE
SMS text message is configured even with only selecting TOTP via Amplify CLI

### ISSUE THREAD

**Issue by sammartinez** [aws-amplify/amplify-cli#3007] opened 2019-12-16 21:28 UTC
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
In configuring TOTP via the CLI, found that even after setting MFA to only TOTP, SMS is still configured.

**Amplify CLI Version**
v4.5.0

**To Reproduce**
Manual setup configuration via terminal

**Expected behavior**
Only TOTP would be set up

**Screenshots**
CLI configuration
![totpsetup](https://user-images.githubusercontent.com/7387880/70944266-91ba7f80-2007-11ea-8794-db3aa829ad75.png)

Cognito
![sms](https://user-images.githubusercontent.com/7387880/70944428-e52ccd80-2007-11ea-9c4f-301def8ea436.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Node Version. v13.3.0

**Additional context**

**Comment by sammartinez** [comment] 2019-12-16 21:31
Current workaround for this is to configure a User Pool manually in order to test a workflow.

**Comment by yuth** [comment] 2019-12-16 23:19
We use custom resource backed with lambda to provision TOTP and the lambda seem to fail if we don't SMS with the following error
```
SMS configuration and Auto verification for phone_number are required when MFA is required/optional 
```

**Comment by sammartinez** [comment] 2019-12-16 23:41
> We use custom resource backed with lambda to provision TOTP and the lambda seem to fail if we don't SMS with the following error
> 
> ```
> SMS configuration and Auto verification for phone_number are required when MFA is required/optional 
> ```

Gotcha @yuth, I mean my workaround is to manually configure a User Pool along with an Identity pool but seems as though the CLI is providing a false assumption by stating that I am only configuring TOTP and getting SMS by default.

**Comment by sammartinez** [comment] 2020-03-06 21:52
Any update on this?

**Comment by sammartinez** [comment] 2020-03-16 23:28
Bumping again.

**Comment by SwaySway** [comment] 2020-08-04 00:19
Adding an update on this thread Cognito now has support for this in CFN via [enabledMFAs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-enabledmfas)

Labeling this as a bug so it can be prioritized.

**Comment by andreluistosato** [comment] 2020-08-05 19:29
I'm having the same issue regarding a cloudformation script to create a cognito user pool with only software mfa

**Comment by UnleashedMind** [comment] 2020-10-14 21:02
Based on the current investigation, this issue should NOT be labeled as an Amplify CLI bug. 
I tried to use the Lambda based custom resource (current implementation) or the new CloudFormation field as suggested by @SwaySway, SMS cannot be turned off through Cloudformation template or direct Cognito API call if MFA is set as required or optional. 

I contacted the Cognito team about the behavior, will update here when I get any update from them. 

The following are the error messages that I got in my investigation when I tried to turn SMS off. 

CREATE_FAILED UserPool                                                                         AWS::Cognito::UserPool     Wed Oct 14 2020 13:32:15 GMT-0700 (Pacific Daylight Time) SMS configuration and Auto verification for phone_number are required when MFA is required/optional (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: xxxxxxxx; Proxy: null)


CREATE_FAILED      UserPool AWS::Cognito::UserPool Wed Oct 14 2020 13:48:01 GMT-0700 (Pacific Daylight Time) Can't turn off SMS_MFA when SMS configuration is set for the user pool with a required or optional MFAConfiguration. (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: InvalidParameterException; Request ID: null; Proxy: null)
CREATE_IN_PROGRESS UserPool AWS::Cognito::UserPool Wed Oct 14 2020 13:47:59 GMT-0700 (Pacific Daylight Time)

**Comment by ericclemmons** [comment] 2021-07-08 20:08
Not stale, as this is still an issue and creating unexpected behavior:
> ![Screen Shot 2021-07-08 at 2 58 39 PM](https://user-images.githubusercontent.com/15182/124983766-3be46880-dfed-11eb-9873-7e3b8bcfea17.png)
 

> ![Screen Shot 2021-07-08 at 3 05 24 PM](https://user-images.githubusercontent.com/15182/124983783-430b7680-dfed-11eb-8236-5fa5186fcc5e.png)

This should stay open until the underlying issue is resolved:
> https://github.com/aws/aws-cdk/issues/11478

**Comment by josefaidt** [comment] 2022-06-24 21:36
Confirmed this issue has since been fixed by creating a user pool using the sample configuration from the comment above and verifying in the console 
<img width="857" alt="image" src="https://user-images.githubusercontent.com/5033303/175696078-76b58d25-e3a4-465a-a3e2-3d82ee2ca511.png">
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/5033303/175696101-5899afef-a373-4112-b353-55a05c29a38c.png">

**Closed by josefaidt** 2022-06-24 21:36 UTC
Labels: dependency-issue, auth, pending-triage
