### ISSUE TITLE
How to get container to use secrets from the correct environment?

### ISSUE THREAD

**Issue by mattfysh** [aws-amplify/amplify-cli#8868] opened 2021-11-15 02:25 UTC
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**

Serverless containers

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

v6.4.0

**What AWS Services are you utilizing?**

Fargate / ECS

**Provide additional details e.g. code snippets**

Referring to the CF template file located at `amplify/backend/api/name/name-cloudformation-template.json`:

The environment is **hard-coded** into the following paths:

* `Resources.TaskDefinition.Properties.ContainerDefinitions[].Secrets`
* `Resources.TaskDefinitionExecutionRoleDefaultPolicyHash.Properties.PolicyDocument.Statement[].Resource`

I am trying to deploy the container to prod, but after checking out & pulling `prod` env, the `dev` environment is still hard coded in those locations.

I then try `amplify push` but the dev secrets are bundled up with the prod task definition.

How can I fix this quickly?

**Comment by mattfysh** [comment] 2021-11-15 02:40
I note another secrets-related bug I raised on Containers recently: https://github.com/aws-amplify/amplify-cli/issues/8384

Sounds like Containers + Secrets need an overhaul

**Comment by mattfysh** [comment] 2021-11-15 02:48
The workaround:

```
Secret configuration detected. Do you wish to store new values in the cloud? Yes
```

Answering yes updated the template file... but the problem is that HARD-CODED values are rendered to the Cloudformation template, they should be parameterized but instead they appear as follows:


```
"ValueFrom": "arn:aws:secretsmanager:*:secret:amplify-*-prod-*-SECRET_NAME-HASH"
```

This is incompatible with git workflows, especially of importance when deploying from CI/CD

**Comment by mattfysh** [comment] 2021-11-21 00:35
Hey amplify team - can I get an ACK on this issue?

**Comment by mattfysh** [comment] 2021-12-21 02:34
Hi all, any updates?

I'm still having to deploy manually, and need to manually update secrets every time to ensure the CF template is properly re-rendered with the right ENV before deploy 

if I'm not careful when deploying manually, I can end up with prod secrets in dev or vice-versa

So this seems like it should be a high-priority bug, considering that container secrets are no longer compatible with the git-based workflow, and that the manual workaround involves quite a risky cost

**Comment by mattfysh** [comment] 2021-12-21 02:42
as a sanity check - can I get someone to agree that environment names should not be getting hard-coded into CF templates?

If I can just get someone to acknowledge that this is definitely a bug then I can relax knowing that a fix will come, eventually.... right? :)

**Comment by pnedelko** [comment] 2021-12-30 09:04
I would like to switch from lambda to containers and seems like I'm immediately blocked by this issue and have to look for workarounds :(. Looks like this bug should have high priority.

**Comment by mattfysh** [comment] 2022-01-04 01:36
Yeah it really is unfortunate, this issue is very serious and has been opened for nearly 2 months with no acknowledgement from the Amplify team, so I'll be leaving AWS as soon as my credits expire.

**Comment by sundersc** [comment] 2022-01-11 19:37
Hi @mattfysh - Sorry about the delayed response on this. I can confirm that the env name is hard-coded on the secrets value, marking it as a bug.

I'm also having issues getting secrets to work with container on the latest cli version. Could you share the `api` folder structure and `docker-compose.yml` file if possible?

**Closed** 2022-01-13 21:43 UTC
Labels: bug, containers

**Comment by sundersc** [comment] 2022-01-13 22:45
@mattfysh We are trying to get this fix on the next release. In your scenario, for each environment for the first time, update the secrets by answering `Yes` to the prompt `Secret configuration detected. Do you wish to store new values in the cloud?`. Any subsequent push will pick up the correct environment secrets value.

**Comment by mattfysh** [comment] 2022-01-13 23:58
Thanks @sundersc  :) much appreciated

Apologies for the delay in getting back to you. The docs are incomplete, is this where you were having trouble? See these issues:

* https://github.com/aws-amplify/amplify-cli/issues/7661
* https://github.com/aws-amplify/docs/issues/3417

**Comment by pnedelko** [comment] 2022-01-14 10:52
@sundersc is it possible to update secret values via cli for an existing env?

**Comment by sundersc** [comment] 2022-01-19 18:43
@pnedelko - Current workflow to update the secrets value for an existing env is as follows.

- Checkout the env.
- Place the secret files with the new values under `secrets` folder.
- On amplify push, answer `y` to `Secret configuration detected. Do you wish to store new values in the cloud?`

**Comment by sundersc** [comment] 2022-01-19 20:03
Thanks @mattfysh. Yes, that was the issue. I've opened a PR [#3951](https://github.com/aws-amplify/docs/pull/3951) to update the example on the docs.
