### ISSUE TITLE
@key throws "Cannot read property name of undefined"

### ISSUE THREAD

**Issue by davekiss** [aws-amplify/amplify-cli#1572] opened 2019-06-04 14:30 UTC
**Describe the bug**
Attempting to add a `@key` directive as described in the documentation does not successfully provision when running `amplify push` using the following schema in my project:

```
type Action
  @model
  @key(fields: ["id"])
  @key(
    name: "ByActionable"
    fields: ["actionableId"]
    queryField: "actionsForActionable"
  )
  @key(name: "ByTitle", fields: ["title"], queryField: "actionsByTitle")
  @key(
    name: "ByActionableByPosition"
    fields: ["actionableId", "position"]
    queryField: "actionsForActionableByPosition"
  )
  @key(
    name: "ByActionableByTitle"
    fields: ["actionableId", "title"]
    queryField: "actionsForActionableByTitle"
  )
  @key(
    name: "ByActionableBySlot"
    fields: ["actionableId", "slot", "position"]
    queryField: "actionsForActionableInSlotByPosition"
  )
  @key(
    name: "ByActionableByHandler"
    fields: ["actionableId", "handledBy"]
    queryField: "actionsForActionableByHandler"
  )
  @key(
    name: "ByActionableBySlotByHandler"
    fields: ["actionableId", "slot", "handledBy"]
    queryField: "actionsForActionableByHandlerInSlot"
  )
  @auth(
    rules: [
      { allow: owner }
      { allow: groups, groups: ["Guests"], operations: [read] }
    ]
  ) {
  id: ID!
  owner: String
  actionableId: ID!
  actionableType: ActionableType!
  title: String
  type: ActionType!
  subtype: String
  slot: ActionSlot!
  handledBy: ActionHandler!
  position: Int!
  triggerAtTimecode: Float
  data: AWSJSON
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
}

enum ActionableType {
  Collection
  Playlist
  Video
  PlaylistVideo
}

enum ActionSlot {
  BEFORE_START_PLAYBACK
  DURING_PLAYBACK
  AFTER_COMPLETE_PLAYBACK
}

enum ActionType {
  SEND_EMAIL
  CONSOLE_LOG
  ALERT
  DISPLAY_INTERSTITIAL
  PERFORM_HTTP_REQUEST
}

enum ActionHandler {
  CLIENT
  SERVER
  CLIENT_AND_SERVER
}
```

Output:

```
$ amplify push --yes

Current Environment: dev

| Category  | Resource name                                  | Operation | Provider plugin   |
| --------- | ---------------------------------------------- | --------- | ----------------- |
| Api       | andoto                                         | Update    | awscloudformation |
Updating input structures for key: {"fields":["id"]}
✖ An error occurred when pushing the resources to the cloud

Cannot read property 'name' of undefined
error Command failed with exit code 1.
```

**Expected behavior**
`amplify push` successfully compiles and provisions changes

**Additional context**
I tried running on both a brand new model and an existing model with no luck.

**Comment by kaustavghosh06** [comment] 2019-06-04 14:31
Which version of the CLI are you using?

**Comment by davekiss** [comment] 2019-06-04 14:35
@kaustavghosh06 1.7.0

**Comment by zfarrell** [comment] 2019-06-04 15:55
I was fighting through this same issue (CLI @ 1.7.0). 

I can reproduce it with this schema: 

```
type Item @model
@key(fields: ["orderId","status"])
{
    orderId: String!
    status: Status!
    createdAt: AWSDateTime!
    name: String!
}
enum Status {
    DELIVERED
    IN_TRANSIT
    PENDING
    UNKNOWN
}
```

it seems to be related to having an `enum` as the sort key. Changing status to `String` resolves the error.

**Comment by davekiss** [comment] 2019-06-04 16:54
Can confirm, changing all field references from `enum` types to `String` allows the compilation to succeed

**Comment by kaustavghosh06** [comment] 2019-06-20 18:12
We've merged the fix for this issue. It would be a part of our next npm release.

**Closed by kaustavghosh06** 2019-06-20 18:12 UTC
Labels: bug, graphql-transformer
