### ISSUE TITLE
TypeError: path must be a string or Buffer

### ISSUE THREAD

**Issue by rajababu3** [aws-amplify/amplify-cli#559] opened 2018-12-07 09:35 UTC
I am getting this error **TypeError: path must be a string or Buffer**

When I run amplify init, It ask all question and then I got this error

`✖ There was an error initializing your environment.
init failed
TypeError: path must be a string or Buffer
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.readFileSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/util.js:95:26)
    at Config.loadFromPath (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/config.js:435:39)
    at Object.loadConfiguration (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/configuration-manager.js:499:24)
    at Object.aws.configureWithCreds.context [as configureWithCreds] (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws.js:4:58)
    at new S3 (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-s3.js:6:16)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initialize-env.js:17:10)
    at Object.initEnv (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/index.js:22:24)
    at initializationTasks.push (/usr/local/lib/node_modules/@aws-amplify/cli/src/lib/initialize-env.js:44:53)` 

After updating cli for mutlienv to latest version, I am getting this error. 
I also downgraded to old version but still it the same issue.

**Comment by yuth** [comment] 2018-12-07 18:23
What's the version of amplify do you have installed? You could get that by running
```bash
$ amplify -v
```

**Comment by UnleashedMind** [comment] 2018-12-07 18:36
Hi @rajababu3 

when you say you 'I also downgraded to old version but still it the same issue.' 
what version is the old version?

**Comment by rajababu3** [comment] 2018-12-07 18:37
Hello @UnleashedMind
It was multienv.1

**Comment by UnleashedMind** [comment] 2018-12-07 18:47
are you running `amplify init` on anew? i.e. the project has not been init'ed with any version of `amplify-cli` before. 
Of you are running it on a project that was already init'ed by an older version of the cli?

**Comment by rajababu3** [comment] 2018-12-07 18:49
I initiated the project with multienv.1 and today upgraded to multienvm.10 and problem started

**Comment by yuth** [comment] 2018-12-07 19:01
@rajababu3 Could you calrify the following:
1. Did you initalize the project with non multienv version of amplify initally? 
```
amplif init (non-multi) -> install multienv.10 -> init (failed) -> install multienv.1 -> init (failed again)
```

2. Also what categories do you have enabled in your project?
3. Whats the version of node
4. How did you install amplify (node or yarn)
5. What OS are you using

**Comment by UnleashedMind** [comment] 2018-12-07 19:19
Hi @rajababu3 

I found the cause of the issue, will send a fix soon. Thanks for the feedbacks.

**Comment by UnleashedMind** [comment] 2018-12-10 22:14
closing this issue for now, the fix has been merged and published

**Closed by UnleashedMind** 2018-12-10 22:14 UTC
Labels: bug, review
