### ISSUE TITLE
Resource cannot be removed (dependency) & Updating imported Auth resource is not supported

### ISSUE THREAD

**Issue by bcs-gbl** [aws-amplify/amplify-cli#9934] opened 2022-03-08 10:12 UTC
**Which Category is your question related to?**

- amplify cli
- amplify update auth
- amplify remove auth
- amplify add auth
- Admin queries API

**Amplify CLI Version**

7.6.22

**What AWS Services are you utilizing?**

- cognito

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**

1. first try:
`amplify auth update`
"Updating imported Auth resource is not supported."

2. second try:
`amplify remove auth`
"Resource cannot be removed because it has a dependency on another resource"

There is a lot of linked resources (~40), millions of db data and a huge amount of lambdas+lambda triggers.
The amplify app runs about 2-3 years and the data aws migration (without developer fees) costs were ~5000 USD, so we do not want to delete, recreate, import every resource.

How to add "another" auth servive or switch and link my services to use the new one without recreate the whole project from zero?

My goal is to add "Admin queries API" but this cannot be solved:

```
amplify auth update
? What do you want to do?
  Apply default configuration with Social Provider (Federation)
  Walkthrough all the auth configurations
  Create or update Cognito user pool groups
❯ Create or update Admin queries API
? Do you want to restrict access to the admin queries API to a specific Group Yes
? Select the group to restrict access with: (Use arrow keys)
❯ admin
  editors
  Enter a custom group
```
([source](https://aws.amazon.com/blogs/mobile/amplify-cli-enables-creating-amazon-cognito-user-pool-groups-configuring-fine-grained-permissions-on-groups-and-adding-user-management-capabilities-to-applications/))

How can i solve this situation?

Thank you for your advice

**Comment by akshbhu** [comment] 2022-03-08 17:52
Hi @bcs-gbl 

It seems like you have a userPool which is imported. Imported userPools are not managed by amplify as there in no CFN file for it . Amplify attaches the imported userPool to backend and generate ```aws-exports.js``` file with its endpoint, userPooIds  and other properties.
 So the operations like update and admin queries wont be allowed on an imported userPool.

Can you tell more about the project and liked resources so that  we can find a suitable solution according to your project ?

**Comment by bcs-gbl** [comment] 2022-03-09 11:43
hi, @akshbhu 

> "It seems like you have a userPool which is imported. Imported userPools are not managed by amplify as there in no CFN file for it "

Yes, it's true and i know it, thank you.

I've found a working solution: 
1. a `lambda function` created to handle/list/delete Cognito users and
2. `@function` added to our graphql schema, so results available through a lambda resolver.
This solution does not require the use of the Admin queries API (amplify auth update command) so everything in our project is OK.

Maybe theres need a new cli auth "switch" tool, that
- help to define and create new (but not linked) auth service,
- and help to replace (and link) from another (maybe imported) auth to other/new

**Comment by akshbhu** [comment] 2022-03-09 14:19
Glad to know you have found a solution.  Admin queries  configure an API Gateway endpoint with a Cognito Authorizer that accepts an Access Token, which is used by a Lambda function to perform actions against the User Pool.

But this way also seems good having a gql endpoint with lambda datasource.

Ill keep this as feature request to have a solution to replace existing userPool with another userPool replacing with all the dependencies  to other services.

**Comment by bcs-gbl** [comment] 2022-04-22 10:50
While if an "import tool" or someting real solution is not available:

1. The following other problem comes up too:

All imported, cognito based authentication triggers and any other auth update (messaging, captcha or 2fa, or other functionality) is not available. Any auth update cannot updates this  from amplify-cli.

**2. I'd like to ask a modification of the cognito documentation:** 

There absolutely needs a huge red warning message: 

if someone creates a cognito pool and connects all the services: like apis, dynamodb tables, Opensearch clusters, triggers, S3 (*everything) to a previously created and imported cognito pool, he/she cannot use amplify-cli to modify all of these later, and must be recreate the whole application, all resources, imports every data.. 

Thats nonsense, but its OK. Only I ask someone to put this "not so negligible" info to the documentation.
Thx,

**Comment by josefaidt** [comment] 2022-08-08 19:16
Closing as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/7835

**Closed by josefaidt** 2022-08-08 19:16 UTC
Labels: auth, feature-request, import, duplicate, p4
