### ISSUE TITLE
An error occurred during the push operation: The specified bucket does not exist error after amplify auth update

### ISSUE THREAD

**Issue by nyholku** [aws-amplify/amplify-cli#7218] opened 2021-04-30 05:10 UTC
Yesterday, after a lot of poking in the dark,  I thought everything was ok with my vue+auth+graphql+hosted zone domain. trial project:

www.romuxis.com

Went to bed happy.

This morning tried the vue/amplify login on my site, got:

User pool client 4kg9ptbanodfdondtn02kb4flp does not exist.

In an attempt to fix that I run:

"amplify auth update"

And then 

"amplify push"

and I got "The specified bucket does not exist" error.

After googling I figured that team-provide-info.json pointed to amplify-romuxisvue-dev-160005-deployment which did not exist.

So I create that.

Now I get:

"An error occurred during the push operation: The specified key does not exist."

After two weeks of struggling with AWS and amplify I'm sort of getting discouraged and frustrated.

Is it just me or what?

Lots of 'follow this path  and magic happens' documentation but nowhere really explained the concepts so that I could actually learn how things work so that I could solve the problems myself by debugging like the pro I am supposed to be. 

Everywhere you get these terms like in this example "User pool client" , never seen that concept in two weeks of "learning".

And the error messages could do with improving.

"specified key does not exist." 
or
"The specified bucket does not exist" 

What key? What bucket? Where was it specified? Where did it not exist?

Error reporting 101...

Leaves me feeling that the web technology is developing at break neck speed and devs are just hacking and patching things up to keep up with the competition...

Ok, enough of that, but help would be appreciated to get me further.

**Comment by nyholku** [comment] 2021-04-30 12:34
Got so frustrated with this that deleted all apps and buckets and tried to re-create my app from Bitbucket repo using AWS Amplify 'Get started'.

Now the app won't even build!

**Comment by siegerts** [comment] 2021-04-30 13:56
Hi @nyholku  😄 - thanks for raising this!  To get a bit more context, do you mind porting this to one of the formatted templates listed here:

- [bug report](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml&title=) or [usage question](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=question&template=3.usage-question.md&title=)

Those have all the required information to help the team determine the best approach to take.

Also, if it's helpful, there is an [Amplify Community Discord](https://discord.com/invite/amplify) server that may be helpful to bounce ideas and meet some folks. It's a really active community and community members are usually always online.

**Comment by nyholku** [comment] 2021-04-30 15:50
Hmm. It was private but I un-ticked the private box, I don't know what else I should do.

Anyway, Friday here and getting late in this timezone so I'll try to post some more details on Monday.

Enjoy your weekend.

**Comment by nyholku** [comment] 2021-05-03 14:03
I tried to figure out how to make my bitbucket public. No luck so far. Should not be that difficult. Almost ready to wipe everything out at this point and try N:th time from scratch....

**Comment by siegerts** [comment] 2021-05-04 00:10
Hi @nyholku, Closing for now since this has taken a different direction. 

If you run in a specific issue regarding the CLI, please open a [new issue](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml&title=) and list out the specific reproduction steps and supporting information.  That will help the team isolate the potential issue.

**Closed by siegerts** 2021-05-04 00:10 UTC
Labels: pending-close-response-required, question
