### ISSUE TITLE
Cannot import graphql autogenerated files

### ISSUE THREAD

**Issue by fatjoni** [aws-amplify/amplify-cli#1646] opened 2019-06-11 07:35 UTC
**Describe the bug**
The graphql folder that is auto generated with queries, mutations and subscriptions cannot be imported to an angular project (angular 7). It throws module not found. Maybe is due to the fact that the generated file exports nothing.
**To Reproduce**
1. amplify add api
2. Try to import from graphql autogenerated modules

**Expected behavior**
To be imported like every other module

**Comment by yuth** [comment] 2019-06-11 18:29
@fatjoni Did you push API changes to the cloud? Also could you share the content in your `<proj-root>/.graphqlconfig.yml`. Please obfuscate sensitive information before sharing it

**Comment by fatjoni** [comment] 2019-06-12 08:18
Here it is the .graphqlconfig.yml

projects:
  carsApiDev:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src\app\API.service.ts
        docsFilePath: src\graphql
Attached is the error, no matter what i try to import it shows module not found even though intelisense guides me to the specific path:
When i open for example the queries.graphql file i see there is no exported member and maybe this is the reason why this error is occurring.
![image](https://user-images.githubusercontent.com/7958688/59334426-bcdfb180-8cfa-11e9-8f9d-a12ce4593fc7.png)

**Comment by yuth** [comment] 2019-06-12 18:11
@fatjoni do you see any error when you run `amplfy codegen statements`. Could you also try to change includes from `src\graphql\**\*.graphql` -> `src/graphql/**/*.graphql` and see if that changes anything

**Comment by fatjoni** [comment] 2019-06-16 18:22
@yuth  when i run amplify codegen statements i get the following:
√ Downloaded the schema
√ Generated GraphQL operations successfully and saved at src\graphql

I am using amplify 1.7.0 on a windows 10 machine

I am not sure i correctly understood your sugestion but if is about using backslashes i tried and it did not work.

**Comment by yuth** [comment] 2019-06-17 16:51
@fatjoni could you share your schema or a sample schema where this can be reproduce this issue.

**Comment by fatjoni** [comment] 2019-06-26 11:51
I noticed this happens when you generate mutations and queries in my project by selecting "angular" in cli.
After i tried to select typescript it was fixed ^_^

**Comment by yuth** [comment] 2019-06-27 18:40
@fatjoni choosing angular as `codeGenTarget` should not change how the statements are generated. Could you share a schmea where I can reproduce this

**Comment by kaustavghosh06** [comment] 2019-07-18 19:57
Closing this issue due to lack of customer response. Please feel free to re-open if you're still stuck on this.

**Closed by kaustavghosh06** 2019-07-18 19:57 UTC
Labels: bug, code-gen

**Comment by Crisp3333** [comment] 2019-08-22 01:21
I am having problems with this, this is not solved. It seems like a bug. currently I will just have to use dynamodb directly and by pass graphql.

**Comment by PatelDipen92** [comment] 2019-11-30 08:43
I am also facing the same issue. I am facing an issue while doing an import same as @fatjoni.
@fatjoni did you fix the issue? If so can you please tell me how?

**Comment by civilatio** [comment] 2019-12-27 09:23
I face the same issue. My schema looks like this:

`type ParkEvent @model {
  id: ID!
  plate: String!
  location: String!
  startTimestamp: Int!
  endTimestamp: Int
}`

and the queries:

`# this is an auto generated file. This will be overwritten
query GetParkEvent($id: ID!) {
  getParkEvent(id: $id) {
    id
    plate
    location
    startTimestamp
    endTimestamp
  }
}
query ListParkEvents(
  $filter: ModelParkEventFilterInput
  $limit: Int
  $nextToken: String
) {
  listParkEvents(filter: $filter, limit: $limit, nextToken: $nextToken) {
    items {
      id
      plate
      location
      startTimestamp
      endTimestamp
    }
    nextToken
  }
}
`
