### ISSUE TITLE
graphqlconfig.yml schemaPath always set to 'src' even if other path specified

### ISSUE THREAD

**Issue by jsgphd** [aws-amplify/amplify-cli#4966] opened 2020-07-29 14:41 UTC
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
when I did an amplify add api for graphql I set my directory to 'app' instead of 'src' and it set the includes to app/graphql/**/*.js which is correct but incorrectly set the schemaPath to src/graphql/schema.json

**Amplify CLI Version**
4.25.0

**To Reproduce**
Try setting a path other than 'src'

**Expected behavior**
Would expect it to set schemaPath to app/graphql/schema.json

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system
ubuntu 20.4

**Additional context**
The work around is to just edit the graphqlconfig.yml after auto-generation of that file.

**Comment by ammarkarachi** [comment] 2020-08-03 21:57
Closing as duplicate of  #2123 follow to receive to updates.

**Closed by ammarkarachi** 2020-08-03 21:57 UTC
Labels: enhancement, graphql-transformer, pending-triage
