### ISSUE TITLE
Single Dynamic group auth with V2 doesn't produce expected results

### ISSUE THREAD

**Issue by AaronK97** [aws-amplify/amplify-cli#9369] opened 2021-12-22 13:32 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.13.0

### Amplify CLI Version

7.6.5

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

An authenticated user in the correct group cannot read data including GSI's.

Possibly related to: https://github.com/aws-amplify/amplify-cli/issues/9220

### Expected behavior

Group data should be returned when a user has the correct cognito:group regardless of their username value

### Reproduction steps

1. amplify add api
2. Create schema below
3. amplify mock api
4. Create 6 users as an `admin` in cognito:groups . 
```graphql
mutation MyMutation {
  a: createUsers(input: {userID: "user1", teamID: "AAA"}) {
    teamID
    userID
    id
  }
  b: createUsers(input: {userID: "user2", teamID: "AAA"}) {
    teamID
    userID
    id
  }
  c: createUsers(input: {userID: "user3", teamID: "AAA"}) {
    teamID
    userID
    id
  }
  d: createUsers(input: {userID: "user4", teamID: "BBB"}) {
    teamID
    userID
    id
  }
  e: createUsers(input: {userID: "user5", teamID: "BBB"}) {
    teamID
    userID
    id
  }
  f: createUsers(input: {userID: "user6", teamID: "BBB"}) {
    teamID
    userID
    id
  }
}
```
5. Change auth to have a cognito:group of "AAA" and a username not affiliated with any of the userIDs above
6. Query listUsers and the GSI listUsersByTeamID
```json
// V2 result 
{
  "data": {
    "listUsers": null,
    "listUsersByTeamID": {
      "items": []
    }
  }
}

// V1 Result
{
  "data": {
    "listUsers": {
      "items": [
        {
          "id": "c882ba27-e536-4bf0-97a2-fd8fcbc123c6",
          "teamID": "AAA",
          "userID": "user1"
        },
        {
          "id": "f5d61dff-9c51-45cd-b29c-f51d96132b1c",
          "teamID": "AAA",
          "userID": "user3"
        },
        {
          "id": "df505430-6cf5-4df6-ba5d-bc4e1326cde8",
          "teamID": "AAA",
          "userID": "user2"
        }
      ]
    },
    "listUsersByTeamID": {
      "items": [
        {
          "id": "c882ba27-e536-4bf0-97a2-fd8fcbc123c6",
          "teamID": "AAA",
          "userID": "user1"
        },
        {
          "id": "f5d61dff-9c51-45cd-b29c-f51d96132b1c",
          "teamID": "AAA",
          "userID": "user3"
        },
        {
          "id": "df505430-6cf5-4df6-ba5d-bc4e1326cde8",
          "teamID": "AAA",
          "userID": "user2"
        }
      ]
    }
  }
}
```

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
# V2 Schema
type Users
  @model(subscriptions: null)
  @auth(
    rules: [
      { allow: owner, ownerField: "userID" }
      { allow: groups, groupsField: "teamID" }
      { allow: groups, groups: ["admin"] }
    ]
  ) {
  id: ID!
  userID: ID!
  teamID: ID! @index(name: "byTeamID", queryField: "listUsersByTeamID")
}

# V1 Schema
type Users
  @model(subscriptions: null)
  @auth(
    rules: [
      { allow: owner, ownerField: "userID" }
      { allow: groups, groupsField: "teamID" }
      { allow: groups, groups: ["admin"] }
    ]
  )
  @key(name: "byTeamID", fields: ["teamID"], queryField: "listUsersByTeamID") {
  id: ID!
  userID: ID!
  teamID: ID!
}

```

</details>

### Log output

<details>

```
# Put your logs below this line
N/A

```

</details>

**Comment by marcvberg** [comment] 2021-12-23 19:51
Closing as a duplicate of #9220

**Closed by marcvberg** 2021-12-23 19:51 UTC
Labels: duplicate
