### ISSUE TITLE
Removing gql model causes 

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-cli#7586] opened 2021-06-23 05:24 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

N/A -- using amplify cli in Amplify console CD

### If applicable, what version of Node.js are you using?

N/A

### Amplify CLI Version

Latest

### What operating system are you using?

N/A

### Amplify Categories

Not applicable

### Amplify Commands

publish

### Describe the bug

I added a simple model:

```gql
type ActivityLogs
  @model
  @searchable
  @auth(
    rules: [{ allow: private, provider: iam }, { allow: private }]
  ) {
  id: ID!
  payload: AWSJSON
  message: String
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
}
```

Then I realized that I should not add that `s` in the name, because the generated queries would be like `searchActivityLogss`, so I decided to remove it first:

```gql
# type ActivityLogs
#   @model
#   @searchable
#   @auth(
#     rules: [{ allow: private, provider: iam }, { allow: private }]
#   ) {
#   id: ID!
#   payload: AWSJSON
#   message: String
#   createdAt: AWSDateTime
#   updatedAt: AWSDateTime
# }
```

Buth when I pushed to the repository which will be picked up by the CI, I encountered an error with it

```
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2021-06-23T05:18:24.645Z [INFO]: [0mAmplify AppID found: myApp. Amplify App name is: myApp[0m
2021-06-23T05:18:24.700Z [INFO]: [0mBackend environment dev found in Amplify Console app: myApp[0m
2021-06-23T05:18:25.891Z [WARNING]: - Fetching updates to backend environment: dev from the cloud.
2021-06-23T05:18:26.538Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
2021-06-23T05:18:26.653Z [INFO]: 
2021-06-23T05:18:30.217Z [INFO]: [33mNote: It is recommended to run this command from the root of your app directory[39m
2021-06-23T05:18:35.675Z [WARNING]: - Initializing your environment: dev
2021-06-23T05:18:36.413Z [WARNING]: ✔ Initialized provider successfully.
2021-06-23T05:18:36.622Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2021-06-23T05:18:36.623Z [WARNING]: ✖ There was an error initializing your environment.
2021-06-23T05:18:36.636Z [INFO]: [0mTypeError: Cannot convert undefined or null to object[0m
                                 [0m    at Function.values (<anonymous>)[0m
                                 [0m    at lambdasWithApiDependency (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/utils/getDependentFunction.ts:30:44)[0m
                                 [0m    at AmplifyToolkit.invokePluginMethod [as _invokePluginMethod] (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/invoke-plugin-method.ts:29:10)[0m
                                 [0m    at Object.ensureValidFunctionModelDependencies (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/utils/remove-dependent-function.ts:18:33)[0m
                                 [0m    at Object.run (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:104:43)[0m
2021-06-23T05:18:36.655Z [ERROR]: !!! Build failed
2021-06-23T05:18:36.656Z [ERROR]: !!! Non-Zero Exit Code detected
2021-06-23T05:18:36.656Z [INFO]: # Starting environment caching...
2021-06-23T05:18:36.656Z [INFO]: # Uploading environment cache artifact...
2021-06-23T05:18:36.743Z [INFO]: # Environment caching completed
Terminating logging...
```

The only clue I have is `TypeError: Cannot convert undefined or null to object` and I've searched around but I could not find a similar issue that has been resolved. Reverting my change causes the process to succeed so it has to do with that model BUT that model is not yet being used anywhere.

And this is the first time this has happened to me, I've done this before but did not encounter this error. I'm unsure if it's relevant but this project used to use v4 and was initialized with v4.

### Expected behavior

It should be able to remove the model successfully.

### Reproduction steps

1. Add a graphql model
2. Remove the model

### GraphQL schema(s)

please see above.

### Log output

Please see above.

**Comment by josefaidt** [comment] 2021-06-23 13:09
Hey @aprilmintacpineda :wave: thanks for raising this. It appears to be a duplicate of https://github.com/aws-amplify/amplify-cli/issues/7466 which I am actively investigating. What version of Node.js are you using?

**Comment by josefaidt** [comment] 2021-06-23 17:44
Closing duplicate issue in favor of tracking https://github.com/aws-amplify/amplify-cli/issues/7466.

**Closed by josefaidt** 2021-06-23 17:44 UTC
Labels: api-graphql, duplicate, investigating, pending-triage
