### ISSUE TITLE
CLI freezes with amplify init on newest version (1.7.4)

### ISSUE THREAD

**Issue by Arc-dev** [aws-amplify/amplify-cli#1689] opened 2019-06-20 15:24 UTC
**Describe the bug**
Hi team,

I've recently updated to CLI version 1.7.4 and I've noticed that when I move on an initial input, such as the screenshot attached, it freezes and I have to crash out of the terminal.

I've confirmed the issue with a few members of the team and we're all experiencing it across environments (Cloud9/Linux server & local MacOS terminal).

**To Reproduce**
Instal latest version of Amplify cli
run "amplify init" and it will freeze after the initial input.

**Expected behavior**
Looks to be a bug with the newest version.

**Screenshots**
<img width="572" alt="Amp-freezes" src="https://user-images.githubusercontent.com/26845162/59860844-9f07f180-9377-11e9-874a-620bfb328194.png">

**Desktop (please complete the following information):**
 - OS: Mac-Os/Linux server

**Additional context**
Looks like there could be a related issue here - 
https://github.com/aws-amplify/amplify-cli/issues/1688

**Comment by kaustavghosh06** [comment] 2019-06-20 15:28
This is a duplicate of #1688. We are working on this and closing this issue in favor of the other duplicate issue.

**Closed by kaustavghosh06** 2019-06-20 15:28 UTC
