### ISSUE TITLE
Schema is not configured for subscriptions

### ISSUE THREAD

**Issue by achutkiran** [aws-amplify/amplify-cli#1434] opened 2019-05-10 19:07 UTC
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
Aws codegen

** What AWS Services are you utilizing? **
AWs appsync
** Provide additional details e.g. code snippets **
When i use amplify codegen i get following error Schema is not configured for subscriptions.
![image](https://user-images.githubusercontent.com/26334163/57550790-fb193800-732c-11e9-827a-05fca60e55d2.png)

**Comment by yuth** [comment] 2019-05-10 23:29
@achutkiran could you share your `.graphqlconfig.yml` file. Make sure that you have obfuscated sensitive information from the file.

Whats the version of Amplify CLI you have installed?

**Comment by achutkiran** [comment] 2019-05-13 14:11
![image](https://user-images.githubusercontent.com/26334163/57628180-0d7ab800-755f-11e9-94ce-6cedd698a63d.png)

**Comment by achutkiran** [comment] 2019-07-29 19:47
@yuth any update? Thanks

**Comment by yuth** [comment] 2019-08-08 19:10
@achutkiran I could not reproduce this issue. Could you please share a mininal schema that is causing this issue. Could you also include the stack trace when the error occurs, preferably the text version of it instead of screenshot

**Comment by kaustavghosh06** [comment] 2019-08-15 17:54
@achutkiran Closing this issue since it's not reproducable with the latest version of the CLI. Please comment on this thread if you're still seeing this issue.

**Closed by kaustavghosh06** 2019-08-15 17:54 UTC
Labels: bug, code-gen
