### ISSUE TITLE
Timeout when running amplify api add-graphql-datasource

### ISSUE THREAD

**Issue by davekiss** [aws-amplify/amplify-cli#1298] opened 2019-04-17 16:04 UTC
**Describe the bug**
I'm trying out the new `add-graphql-datasource` command with a fresh environment. I've gone through the `amplify api add` steps and have not tied it to a datasource, but now when I run `amplify api add-graphql-datasource` I run into a timeout error.

I've created the Aurora Serverless instances as well, following the steps described in the official docs here, including enabling the Data API and adding a few tables. https://aws-amplify.github.io/docs/cli/graphql#automatically-import-existing-datasources

I've also verified that the DB is not paused when attempting to run the `add-graphql-datasource` command

**To Reproduce**
Run `add-graphql-datasource` with a new Aurora Serverless instance ready to be connected to.

**Expected behavior**
I expected to be presented with my Aurora Serverless cluster as described here: https://aws.amazon.com/blogs/mobile/aws-amplify-announces-new-amazon-aurora-serverless-and-graphql-transform-features-for-building-aws-appsync-apis/

`? Select the Aurora Serverless cluster that will be used as the data source for your API (Use arrow keys)`

**Log** (IP modified, just in case)
```
amplify api add-graphql-datasource
Using datasource: Aurora Serverless, provided by: awscloudformation
? Provide the region in which your cluster is located: us-east-1
Error: connect ETIMEDOUT 169.xx.xx.xxx:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
There was an error adding the datasource
```

Happy to provide any additional details you might need

**Comment by ashwindevendran** [comment] 2019-04-19 19:31
Hi, 

You are seeing this timeout when the CLI is attempting to communicate with the Aurora Serverless Cluster. The reason is that Aurora Serverless reduces capacity when 'idle' (no queries/communication/activity with the cluster after X amount of time), so any future calls to the Cluster once it has gone into the idle state takes awhile as the serverless cluster now undergoes a cold-start. One solution is to disallow the automatic reduction of capacity due to inactivity. For instructions on how to do that, please follow the documentation here: https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless.modifying.html

**Comment by BerndWessels** [comment] 2019-04-23 22:27
@ashwindevendran @yuth Hi, sorry but I am getting the same thing and I am sure my cluster and compute is up and running.

```
C:\Users\Admin\Development\amplify>amplify api add-graphql-datasource
Using datasource: Aurora Serverless, provided by: awscloudformation
? Provide the region in which your cluster is located: us-east-1
Error: connect ETIMEDOUT 169.xxx.xxx.xxx:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1083:14)
There was an error adding the datasource
```

**Comment by BerndWessels** [comment] 2019-04-24 02:03
@ashwindevendran @yuth Actually reading the error in more detail `169.254.169.254` seems something seriously weird.

How is `amplify api add-graphql-datasource` supposed to work? Has it ever worked on `Windows 10` ?

```
C:\Users\Admin\Development\amplify>amplify api add-graphql-datasource
Using datasource: Aurora Serverless, provided by: awscloudformation
? Provide the region in which your cluster is located: us-east-1
Error: connect ETIMEDOUT 169.254.169.254:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1083:14)
There was an error adding the datasource

C:\Users\Admin\Development\amplify>amplify -v
1.6.3
```

**Comment by kaustavghosh06** [comment] 2019-07-11 17:29
@davekiss Were you unblocked with @ashwindevendran's response?

**Comment by davekiss** [comment] 2019-07-11 19:22
@kaustavghosh06 I have not tried it again, but I'm positive the instance was not sleeping/inactive when I attempted to get it set up just as @BerndWessels describes

**Comment by kaustavghosh06** [comment] 2019-09-20 21:55
@davekiss Closing this issue since we haven't been able to reproduce this on our end. Please let us know if you're still seeing this.

**Closed by kaustavghosh06** 2019-09-20 21:55 UTC
Labels: documentation, graphql-transformer, pending-response, pending-triage
