### ISSUE TITLE
Removing api key auth from graphql API does not affect 'amplify status' or aws-exports.js

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#4884] opened 2020-07-20 23:55 UTC
**Describe the bug**
Create a graphql api, add cognito as default auth provider, plus api key authentication. Do amplify push. Now remove api key authentication, via amplify api update (update auth settings). amplify/backend/backend-config.json is updated and nothing else. aws-exports.js still has an api key, and amplify push would do nothing since nothing is shown as due for update. 

**Amplify CLI Version**
4.24.3

**Comment by nikhname** [comment] 2020-07-27 22:15
Duplicate of #4914

**Closed by nikhname** 2020-07-27 22:15 UTC
Labels: bug, platform
