### ISSUE TITLE
Lambda layers don't support build options

### ISSUE THREAD

**Issue by mdoesburg** [aws-amplify/amplify-cli#4931] opened 2020-07-24 15:00 UTC
**Describe the bug**
I tried using build options with a Lambda layer so I can use babel. I currently do this for my Lambda functions as well. It is set up the same way as the [documentation](https://docs.amplify.aws/cli/function/build-options). Whenever I run `amplify push`, the script for my Lambda layer in package.json doesn't get executed at all. It works fine for my Lambda functions. Its hard for me to move my functions duplicate code into a lambda layer because of this.

**Amplify CLI Version**
4.24.3

**To Reproduce**
Try using build options with lambda layers.

**Expected behavior**
I expect the script in package.json to be run before amplify push.

**Comment by hisham** [comment] 2020-07-24 17:14
See https://github.com/aws-amplify/amplify-cli/issues/4916. I think this is by design for now. You have to put all your compiled code in lambda layer, not install or processing is done.

**Comment by nikhname** [comment] 2020-07-24 17:20
Yes this is the current intended behavior but a possible enhancement. Closing as a duplicate of #4916

**Closed by nikhname** 2020-07-24 17:20 UTC
Labels: Lambda layers, enhancement, functions
