### ISSUE TITLE
amplify import storage is not working

### ISSUE THREAD

**Issue by enleet** [aws-amplify/amplify-cli#6515] opened 2021-01-30 02:39 UTC
**Which Category is your question related to?**

Importing S3 bucket thru Amplify CLI

**Amplify CLI Version** 
4.41.2

**What AWS Services are you utilizing?**
S3, Amplify

**Provide additional details e.g. code snippets**

Hello,

when I create s3 from amplify CLI using: amplify add storage .. everything works fine and I can upload files.

However, when I import S3 bucket through the command: amplify import storage, then try to upload files from my iOS swift App I always have the Error :"uploaded  Failed StorageError: The HTTP response status code is [403]" .

I tried all the tricks, I set the bucket for "all Public access", set appropriate "Bucket Policy"  and followed the list in : https://aws.amazon.com/premiumsupport/knowledge-center/s3-troubleshoot-403/

with no luck .. still getting 403 error ..

any help in doing trouble shooting what is going on here ?

**Comment by prashanthravir** [comment] 2021-02-03 14:40
I am as we'll facing the similar issue in android.
When I create s3 from amplify CLI using: amplify add storage .. everything works fine and I can upload files.
But importing an existing S3 bucket via amplify import storage in CLI and uploading the file to S3 is throwing me the below error,


 StorageException{message=Something went wrong with your AWS S3 Storage upload file operation, cause=com.amazonaws.AmazonClientException: Failed to get credentials from Cognito Identity, recoverySuggestion=See attached exception for more information and suggestions}
        at com.amplifyframework.storage.s3.operation.AWSS3StorageUploadFileOperation$UploadTransferListener.onError(AWSS3StorageUploadFileOperation.java:207)
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$4.run(TransferStatusUpdater.java:306)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: com.amazonaws.AmazonClientException: Failed to get credentials from Cognito Identity
        at com.amazonaws.mobile.client.AWSMobileClient.getCredentials(AWSMobileClient.java:374)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4907)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1960)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:282)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:114)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:59)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Unauthenticated access is not supported for this identity pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 4821cc66-28a1-4d08-94ca-02a37b0e627f)

**Comment by enleet** [comment] 2021-02-03 22:49
well it has been five days now and we still didn't get an answer !

**Comment by jhockett** [comment] 2021-02-03 23:09
Hi @enleet and @prashanthravir, did you follow this [guide](https://docs.amplify.aws/cli/storage/import#configuring-iam-role-to-use-amplify-recommended-policies) from the docs?

**Comment by enleet** [comment] 2021-02-03 23:11
Yes  I did

**Comment by jhockett** [comment] 2021-02-03 23:14
@enleet did you also import auth, or `amplify add auth`?

**Comment by enleet** [comment] 2021-02-03 23:18
add auth .. should it be import auth ?

**Comment by jhockett** [comment] 2021-02-03 23:32
> add auth .. should it be import auth ?

Both options are fine, I'm just trying to determine the root cause. Can you share a code snippet of where the error occurs?

**Comment by kaustavghosh06** [comment] 2021-02-03 23:33
@enleet Also, did you enable unauthenticated access in the add auth flow?

**Comment by enleet** [comment] 2021-02-03 23:35
sure ..im not near my desk now .. in an hour

**Comment by enleet** [comment] 2021-02-03 23:35
> @enleet Also, did you enable unauthenticated access in the add auth flow?

yes

**Comment by kaustavghosh06** [comment] 2021-02-03 23:42
@enleet Please share the code-snipper + complete error stack. Which SDK/Library are you using on the client?

@prashanthravir Your stack trace mentioned - `Caused by: com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Unauthenticated access is not supported for this identity pool` which can potentially be resolved by running `amplify update auth` and enabling unauthenticated access.

**Comment by enleet** [comment] 2021-02-04 00:47
**The code in swift is :**

 func upload()
    
    {
             let dataString = "My Data"
        let data = dataString.data(using: .utf8)!

        
        Amplify.Storage.uploadData(key: "testFile", data: data, options: nil) { result in
                switch result {
                case .success:
                    print("uploaded succeeded")
                    
                   // self.fetchCurrentAuthSession();
                    
                    
                case .failure(let error):
                    print("uploaded  Failed \(error)")
                }
            }
        
    }


**The error message is** 

uploaded  Failed StorageError: The HTTP response status code is [403].
Recovery suggestion: TODO some status code to recovery message mapper.
For more information on HTTP status codes, take a look at
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

**Comment by prashanthravir** [comment] 2021-02-04 12:11
@kaustavghosh06  thanks I enable unauthenticated access for the Cognito identity pool created when importing S3.
But now I am getting the below error,
2021-02-04 17:37:12.482 20807-20807/com.example.seki E/MyAmplifyApp: Upload failed
    StorageException{message=Something went wrong with your AWS S3 Storage upload file operation, cause=com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 0A46B4A64E8A9AF7), S3 Extended Request ID: +YAMPr+rHRAsUhCTks6LJRtnj9pxM2pz+YucuTBNGn/9MlbRQS7lxFG2mwwPZsmVCpbyKU/TdwM=, recoverySuggestion=See attached exception for more information and suggestions}
        at com.amplifyframework.storage.s3.operation.AWSS3StorageUploadFileOperation$UploadTransferListener.onError(AWSS3StorageUploadFileOperation.java:207)
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$4.run(TransferStatusUpdater.java:306)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 0A46B4A64E8A9AF7), S3 Extended Request ID: +YAMPr+rHRAsUhCTks6LJRtnj9pxM2pz+YucuTBNGn/9MlbRQS7lxFG2mwwPZsmVCpbyKU/TdwM=
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4913)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1960)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:282)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:114)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:59)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2021-02-04 17:37:12.825 20807-20807/com.example.seki E/MyAmplifyApp: Upload failed
    StorageException{message=Storage upload operation was interrupted., cause=null, recoverySuggestion=Please verify that you have a stable internet connection.}
        at com.amplifyframework.storage.s3.operation.AWSS3StorageUploadFileOperation$UploadTransferListener.onStateChanged(AWSS3StorageUploadFileOperation.java:188)
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$2.run(TransferStatusUpdater.java:224)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by enleet** [comment] 2021-02-05 09:26
> @enleet Please share the code-snippet + complete error stack. Which SDK/Library are you using on the client?
> 
> @prashanthravir Your stack trace mentioned - `Caused by: com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Unauthenticated access is not supported for this identity pool` which can potentially be resolved by running `amplify update auth` and enabling unauthenticated access.

Hello..

any other suggestion pls ?

**Comment by prashanthravir** [comment] 2021-02-06 04:38
> > @enleet Please share the code-snippet + complete error stack. Which SDK/Library are you using on the client?
> > @prashanthravir Your stack trace mentioned - `Caused by: com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Unauthenticated access is not supported for this identity pool` which can potentially be resolved by running `amplify update auth` and enabling unauthenticated access.
> 
> Hello..
> 
> any other suggestion pls ?

hi yes - any further idea as to why we are getting this error - I am using amplify CLI in Android project.

**Comment by prashanthravir** [comment] 2021-02-09 09:27
I finally found the step that I was missing  - I should add policy( AmazonS3FullAccess) to my unauthenticated role in my IAM.
@enleet - you can check and see if you have done this.
But this step is there in Mobile SDK related documents, it could have been added to Amplify docs

**Comment by enleet** [comment] 2021-02-20 11:29
> I finally found the step that I was missing - I should add policy( AmazonS3FullAccess) to my unauthenticated role in my IAM.
> @enleet - you can check and see if you have done this.
> But this step is there in Mobile SDK related documents, it could have been added to Amplify docs

Thanks Prash .. yup that was the trick .. many thanks and Yes you are right the documentation is so much confusing

**Closed** 2021-03-01 17:07 UTC
Labels: import, pending-triage, storage
