### ISSUE TITLE
Not able to add annonatated graphql schema file path whlie doing amplify api add

### ISSUE THREAD

**Issue by Rudra815** [aws-amplify/amplify-cli#627] opened 2018-12-25 14:18 UTC
**Describe the bug**
Error: ENOENT: no such file or directory, copyfile '/amplify/backend/api/amplireactappdemo2/schema.graphql' -> '/home/hrudra/amplireactappdemo2/amplify/backend/api/amplireactappdemo2/schema.graphql'
    at Object.copyFileSync (fs.js:1724:3)
    at serviceWalkthrough (/home/hrudra/.nvm/versions/node/v10.14.2/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js:110:8)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**To Reproduce**
do amplify api add and then provide the schema.graphql path
its showing above error

**Expected behavior**
successfully add schema.graphql file path and do amplify publish

**Screenshots**
Please look into attache screen shot and .txt file for detailed error info

**Desktop (please complete the following information):**
 - OS: windows 10 pro using windows subsystem for Linux. 

**Additional context**
[AmplifyAddAPI error.txt](https://github.com/aws-amplify/amplify-cli/files/2708804/AmplifyAddAPI.error.txt)
![screen shot](https://user-images.githubusercontent.com/45593994/50423621-db9dd900-087d-11e9-9d36-349790d657b3.PNG)

**Comment by Rudra815** [comment] 2018-12-26 03:35
Can any one please help me on above issue
Thanks in advance

**Comment by kaustavghosh06** [comment] 2018-12-26 17:08
@Rudra815 Looking at the error, it looks like there is no pre-existing file at this location -> `'/amplify/backend/api/amplireactappdemo2/schema.graphql`. Can you `cat '/amplify/backend/api/amplireactappdemo2/schema.graphql` and see if the Graphql schema exists at the given location?

**Comment by kaustavghosh06** [comment] 2019-02-20 00:55
@Rudra815 Closing this issue due to lack of issue creator response and the inability to reproduce this behavior. Please feel free to re-open this issue if you're still seeing the same problem.

**Closed by kaustavghosh06** 2019-02-20 00:55 UTC
Labels: API, GraphQL, investigating
