### ISSUE TITLE
init failed adding an environment

### ISSUE THREAD

**Issue by waynebrantley** [aws-amplify/amplify-cli#5559] opened 2020-10-12 05:24 UTC
**Describe the bug**
Amplify init of existing project or amplify add env both fail.   

 Successfully created initial AWS cloud resources for deployments.
...several CREATE_COMPLETE lines followed by...
✔ Initialized provider successfully.
✖ There was an error initializing your environment.
init failed
Error: Found a punctuator character '}' when expecting a quoteless string (check your syntax) at line 37,5 >>>    }
  ]
} ...
    at error (/Users/waynebrantley/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:41:11)
    at tfnns (/Users/waynebrantley/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:191:7)
    at value (/Users/waynebrantley/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:395:23)
    at object (/Users/waynebrantley/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:358:23)
    at value (/Users/waynebrantley/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:391:24)
    at array (/Users/waynebrantley/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:304:20)
    at value (/Users/waynebrantley/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:392:24)
    at object (/Users/waynebrantley/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:358:23)
    at legacyRootValue (/Users/waynebrantley/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:428:38)
    at Object.module.exports (/Users/waynebrantley/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:454:23) {
  hint: ''

**Amplify CLI Version**
4.29.6

**To Reproduce**
Clone project to new folder.  Try and create a new environment.  Can pull then try to create or can do init, no matter what it fails.

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. 14.10.1

Not sure what file it is having trouble parsing or how to get more information.

**Comment by waynebrantley** [comment] 2020-10-12 14:46
Using source control changes I was able to determine this came from function-parameters.json was missing the number beside the 'version' for the layer.

Perhaps a good change would be to name the file with the issue when showing the error?

**Comment by yuth** [comment] 2020-10-12 16:49
@waynebrantley thank you for narrowing down the problem. Would it be possible for you to share `function-parameter.json` where the layer version was missing. 

It would be great if you could share the the commands you ran which caused the `function-paramter.json` to get corrupted.

**Comment by waynebrantley** [comment] 2020-10-12 16:56
```
  "lambdaLayers": [
    {
      "type": "ProjectLayer",
      "resourceName": "commonLayer",
      "version": 9
    }
  ]

```
My thought is if you at least listed the filename with the issue, this would be easier to resolve.
It is possible that manual modification may have messed it up at some point....hard to know because does not show up unless changing/init-ing an environment.

**Comment by waynebrantley** [comment] 2020-10-12 16:56
Sorry in the above the '9' was just not there.

**Comment by yuth** [comment] 2020-10-13 00:19
I tried initing multiple env with lambda layer and could not reproduce this.  CLI uses object representation in memory and uses `JSON.stringify` before writing things to disk. I am curious if this was because of manual modification of the file. I am going to mark this as enhancement to show the file name when in stacktrace when CLI fails to parse the JSON content

**Comment by waynebrantley** [comment] 2020-10-13 12:53
@yuth I think just showing the file name would be best at this point.  Thanks.

**Comment by stleon** [comment] 2020-12-11 06:35
the same problem.
```
amplify init                    
Initializing new Amplify CLI version...
Done initializing new version.
Scanning for plugins...
Plugin scan successful
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the environment dev
Using default provider  awscloudformation
init failed
MissingRequiredParameter: Missing required key 'name' in params
    at ParamValidator.fail (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:61:14)
    at ParamValidator.validateMember (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:132:42)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at finish (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:386:7)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:404:9 {
  code: 'MissingRequiredParameter',
  time: 2020-12-11T06:31:32.943Z
}
```

aws-amplify/cli@4.39.0

**Comment by kaustavghosh06** [comment] 2021-01-27 00:53
@waynebrantley Were you able to get past this issue?

**Comment by waynebrantley** [comment] 2021-01-27 02:47
Yes, I was able to.  I suggested that the error messages show the filename with issues to help others in the future.

**Comment by josefaidt** [comment] 2022-12-20 21:40
Closing due to efforts around improving error messages and prevent errors like this from surfacing

**Closed by josefaidt** 2022-12-20 21:40 UTC
Labels: feature-request, platform, not-reproducible
