### ISSUE TITLE
Amplify build failed due to template limit of 460800 bytes

### ISSUE THREAD

**Issue by blairtaylor** [aws-amplify/amplify-cli#4443] opened 2020-06-02 23:44 UTC
Our Amplify build is failing with the following error:

UPDATE FAILED
Template may not exceed 460800 bytes in size

Screenshot attached.
![image (22)](https://user-images.githubusercontent.com/29442183/83580116-2f97fd00-a509-11ea-9031-1f9999b53ad4.png)

Seems to be "Size of a template body in S3 object for a ValidateStack request" in AWS CloudFormation Service Quotas which is not an adjustable limit.

Is there any option to work around this?

**Comment by nikhname** [comment] 2020-06-05 18:03
Closing as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/3265, this is an issue we are tracking and aware of.

**Closed by nikhname** 2020-06-05 18:03 UTC
Labels: cloudformation, enhancement
