### ISSUE TITLE
amplify serve on Windows gives Error: spawn yarn ENOENT 

### ISSUE THREAD

**Issue by alexladerman** [aws-amplify/amplify-cli#3370] opened 2020-02-07 08:25 UTC
**Describe the bug**
`amplify serve` fails on Windows with the following error:

```Error: spawn yarn ENOENT ```

The amplify project was originally initialised with a Mac then cloned to Windows from a git repo.

**Amplify CLI Version**
4.13.1

**To Reproduce**
`amplify serve`. Reproduced on 2 different windows machines.

**Expected behavior**
no error

**Screenshots**
![image](https://user-images.githubusercontent.com/5664560/74012714-31064e00-498b-11ea-8b44-940d9842d941.png)

**Desktop:**
 - OS: Windows 10
 - Node Version. 13.7.0

**Additional context**
We think it's related to npm needing .cmd on windows. See...

https://github.com/aws-amplify/amplify-cli/pull/3100/commits/aac0d8467dc38e7c7a6d2bfd7c0922a81aca2948
https://github.com/aws-amplify/amplify-cli/issues/379
https://github.com/aws-amplify/amplify-cli/issues/379
https://github.com/aws-amplify/amplify-cli/issues/1644

**Comment by UnleashedMind** [comment] 2020-02-07 22:06
@alexladerman 
Thanks for reporting this. This is a known issue. Before we find a good solution to fix it, please manually change the `BuildCommand` and `StartCommand` in the `amplify/.config/project-config.json` file.

**Comment by codecadwallader** [comment] 2020-05-11 19:56
+1 on this issue.  I'm not sure if it's a generic issue for Windows use cases or only when crossing between different operating systems.

In my case I ended up running inside WSL and cleaning up the local-env-info.json as a workaround.. in case that helps anyone else encountering this issue.

**Comment by SwaySway** [comment] 2021-01-22 01:26
@alexladerman Could you try this with the latest version? I was able to reproduce this with version `4.13.1`. Though I was not able to reproduce this with the latest version (currently `4.41.2`)

**Comment by kaustavghosh06** [comment] 2021-01-27 00:50
Closing since this is not reproducible with the latest version of the CLI. Please let us know if you're still seeing this.

**Closed by kaustavghosh06** 2021-01-27 00:50 UTC
Labels: not-reproducable, pending-close-response-required, platform

**Comment by codecadwallader** [comment] 2021-01-27 19:24
I can confirm I *do not* need the `.cmd` workaround anymore that I used to need to run on Windows.  I'm using Amplify `v4.37.0`
