### ISSUE TITLE
Usage of one to many with key directive - getting Global secondary index exception

### ISSUE THREAD

**Issue by gautamkshitij** [aws-amplify/amplify-cli#4154] opened 2020-05-03 05:11 UTC
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

Amplify Schema

**Amplify CLI Version** 
4.18.1
You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets**
# Given a Schema
```gql
type CampaignAdmin @model
@key(fields: ["email"])
{
    email: AWSEmail!
    title: String!
    campaigns: [Campaign] @connection(keyName: "postsByProfile", fields: ["email"])
}


type Campaign @model
@key(name: "postsByProfile", fields: ["userEmail"]) {
    id: ID!
    userEmail: AWSEmail!
    user: CampaignAdmin @connection(fields: ["userEmail"])
    title: String!
    tasks: [Task] @connection(keyName: "commentsByPost", fields: ["id"])
}

type Task @model
@key(name: "commentsByPost", fields: ["postID"]) {
    id: ID!
    postID: ID!
    campaign: Campaign @connection(fields: ["postID"])
    content: String!
}
```
```gql
mutation MyMutation {
  createCampaignAdmin(input: {email: "a@gmail.com", title: "k"}) {
    email
  }
createCampaign(input: {userEmail: "a@gmail.com", title: "POST1", id: "p1"}) {
    id
  }
 createTask(input: {postID: "p1", content: "COMMENT1", id: "c1"}) {
    id
  }
}

query MyQuery {
  getCampaignAdmin(email: "a@gmail.com") {
    campaigns {
      items {
        title
        id
        user {
          email
        }
        tasks {
          items {
            id
            postID
            content
          }
        }
      }
    }
  }
}
```

# Error
```
✔ Generated GraphQL operations successfully and saved at src/graphql
Error while executing Local DynamoDB
{
    "version": "2017-02-28",
    "operation": "Query",
    "query": {
        "expression": "#connectionAttribute = :connectionAttribute",
        "expressionNames": {
            "#connectionAttribute": "taskCampaignId"
        },
        "expressionValues": {
            ":connectionAttribute": {
                "S": "p1"
            }
        }
    },
    "scanIndexForward": true,
    "filter": null,
    "limit": 10,
    "nextToken": null,
    "index": "gsi-CampaignTasks"
}
ValidationException: The table does not have the specified index: gsi-CampaignTasks
    at Request.extractError (/Users/name/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/Users/name/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/name/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/name/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/name/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/name/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/name/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/name/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/name/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/name/.nvm/versions/node/v14.0.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationException',
  time: 2020-05-03T05:07:24.073Z,
  requestId: '07e9b94e-df54-48a0-83f8-1f7aab6a8d3e',
  statusCode: 400,
  retryable: false,
  retryDelay: 49.65671333788136
}
```

# Fix
BTW appologies for the bad key names - i was incrementally editing this example .
https://docs.amplify.aws/cli/graphql-transformer/directives#belongs-to

I did post an issue trying to mimic my schema using the one shown in example https://github.com/aws-amplify/amplify-cli/issues/4154

## Bad Solution (not sure why this work)
if you change `Task` to `Comment` like this - things work :| am I missing something? is there some black magic in keynames? (BTW I did try to change key names too - and I am stuck)

```gql
type CampaignAdmin @model
@key(fields: ["email"])
{
    email: AWSEmail!
    title: String!
    campaigns: [Campaign] @connection(keyName: "postsByProfile", fields: ["email"])
}


type Campaign @model
@key(name: "postsByProfile", fields: ["userEmail"]) {
    id: ID!
    userEmail: AWSEmail!
    user: CampaignAdmin @connection(fields: ["userEmail"])
    title: String!
    comments: [Comment] @connection(keyName: "commentsByPost", fields: ["id"])
}

type Comment @model
@key(name: "commentsByPost", fields: ["postID"]) {
    id: ID!
    postID: ID!
    content: String!
    campaign: Campaign @connection(fields: ["postID"])
}
```

```gql
query MyQuery {
  getCampaignAdmin(email: "a@gmail.com") {
    campaigns {
      items {
        title
        id
        user {
          email
        }
        comments {
          items {
            id
            postID
            content
          }
        }
      }
    }
  }
}
```

```
{
  "data": {
    "getCampaignAdmin": {
      "campaigns": {
        "items": [
          {
            "title": "POST1",
            "id": "p1",
            "user": {
              "email": "a@gmail.com"
            },
            "comments": {
              "items": [
                {
                  "id": "c1",
                  "postID": "p1",
                  "content": "COMMENT1"
                }
              ]
            }
          }
        ]
      }
    }
  }
}
```

**Comment by gautamkshitij** [comment] 2020-05-03 05:44
Ok this is nonsense

```
type CampaignAdmin @model
@key(fields: ["email"])
{
    email: AWSEmail!
    title: String!
    campaigns: [Campaign] @connection(keyName: "postsByProfile", fields: ["email"])
}


type Campaign @model
@key(name: "postsByProfile", fields: ["userEmail"]) {
    id: ID!
    userEmail: AWSEmail!
    user: CampaignAdmin @connection(fields: ["userEmail"])
    title: String!
    task: [Task] @connection(keyName: "taskByPost", fields: ["id"])
}

type Task @model
@key(name: "taskByPost", fields: ["postID"]) {
    id: ID!
    postID: ID!
    content: String!
    campaign: Campaign @connection(fields: ["postID"])
}

```

Changing the name of the key makes it work - Did i not read things correctly? can someone clarify? 


Also this doesn't work if I name `task` as `tasks`  (I wanna name things plural since it's an array)
```
type CampaignAdmin @model
@key(fields: ["email"])
{
    email: AWSEmail!
    title: String!
    campaigns: [Campaign] @connection(keyName: "postsByProfile", fields: ["email"])
}


type Campaign @model
@key(name: "postsByProfile", fields: ["userEmail"]) {
    id: ID!
    userEmail: AWSEmail!
    user: CampaignAdmin @connection(fields: ["userEmail"])
    title: String!
    tasks: [Task] @connection(keyName: "tasksByPost", fields: ["id"])
}

type Task @model
@key(name: "tasksByPost", fields: ["postID"]) {
    id: ID!
    postID: ID!
    content: String!
    campaign: Campaign @connection(fields: ["postID"])
}

```

**Comment by gautamkshitij** [comment] 2020-05-03 06:06
BTW I was trying to change this schema to that
```
type User @model
@key(fields: ["email"])
{
    email: AWSEmail!
    title: String!
    posts: [Post] @connection(keyName: "postsByProfile", fields: ["email"])
}


type Post @model
@key(name: "postsByProfile", fields: ["userEmail"]) {
    id: ID!
    userEmail: AWSEmail!
    user: User @connection(fields: ["userEmail"])
    title: String!
    comments: [Comment] @connection(keyName: "commentsByPost", fields: ["id"])
    pictures: [Picture] @connection(keyName: "picturesByPost", fields: ["id"])
}

type Comment @model
@key(name: "commentsByPost", fields: ["postID", "content"]) {
    id: ID!
    postID: ID!
    content: String!
    post: Post @connection(fields: ["postID"])
}

type Picture @model
@key(name: "picturesByPost", fields: ["postID"]) {
    id: ID!
    postID: ID!
    post: Post @connection(fields: ["postID"])
}
```
This works :( :( I feel so stupid - not sure if I am missing some minute detail or if there is a bug?

**Comment by yuth** [comment] 2020-05-04 19:45
@gautamkshitij Mock does 

> if you change `Task` to `Comment` like this - things work :| am I missing something? is there some black magic in keynames? (BTW I did try to change key names too - and I am stuck)

Amplify mock creates table and indexes initially and can't change the indexes once they get created. This might be because of that. One solution to this problem is to nuke the `amplify/mock-data` folder which has the local dynamodb tables.

**Comment by gautamkshitij** [comment] 2020-05-04 20:02
@yuth i always nuke my mock-data (always) i combined it with an alias (mock api + rm -r /mock-data). 

And this is a weird thing. Lol naming my variable singular works but plural throws the error. 

Happy to get on a zoom link to show this :|

**Comment by gautamkshitij** [comment] 2020-05-04 21:15
I am confirming again and again - plural variable names for arrays didn't work for me lol - singular variable names don't throw any error. Fixing all my problems by that.

**Comment by yuth** [comment] 2020-05-05 19:58
Closing as duplicate of #4157

**Closed by yuth** 2020-05-05 19:58 UTC
Labels: mock, question
