### ISSUE TITLE
CLI 5.0.1 layers issue

### ISSUE THREAD

**Issue by tomhirschfeld** [aws-amplify/amplify-cli#7602] opened 2021-06-24 18:22 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

5.0.1

### What operating system are you using?

mac

### Amplify Categories

function

### Amplify Commands

push

### Describe the bug

Strange behavior observed on amplify push:

We have a layer (sharedv3) in which on ever push, amplify believes there are changes and attempts to create a new layer version. I believe the root cause of this issue is that we have a /opt/lib directory in this lambda that causes a conflict with the /lib directory and always triggers a new version on push. In order to test this theory, I created a new lambda (wesponsoredwebsharedv5) and migrated the /opt/lib directory to /opt/util in wesponsoredwebsharedv5. Now when I run amplify push, I experienced the following dialogue

```
➜  wesponsored-web git:(at) ✗ amplify push
✔ Successfully pulled backend environment tmhc from the cloud.

Current Environment: tmhc

| Category     | Resource name                              | Operation | Provider plugin   |
| ------------ | ------------------------------------------ | --------- | ----------------- |
| Function     | wesponsoredwebsharedv5                     | Update    | awscloudformation |
| Auth         | wesponsoredweb1966eb90                     | No Change | awscloudformation |
| Auth         | userPoolGroups                             | No Change | awscloudformation |
| Function     | userApprovalNotification                   | No Change | awscloudformation |
...
? Are you sure you want to continue? Yes

Content changes in Lambda layers detected.
Suggested configuration for new layer versions:

sharedv3
  - Description: Updated layer version  2021-06-24T18:16:28.678Z

? Accept the suggested layer version configurations? Yes
Content changes in Lambda layer sharedv3 detected.
```
Which shows no changes detected in sharedv3, but then after I enter y to continue, it shows the version update is for sharedv3, not for wesponsoredwebsharedv5. 

This is definitely unexpected behavior. 

### Expected behavior

see above

### Reproduction steps

see above

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by attilah** [comment] 2021-06-24 19:32
Hi Tom, this is a duplicate of #7569 and was fixed in 5.0.2 that we just released this morning. The fixing PR was: #7581

**Closed by attilah** 2021-06-24 19:32 UTC
Labels: bug, duplicate, lambda-layers
