### ISSUE TITLE
graphqconfig should reflect removed api

### ISSUE THREAD

**Issue by kjetilge** [aws-amplify/amplify-cli#3546] opened 2020-03-02 12:37 UTC
When I remove an API end then later create a new one with a different name, the schemaPath still has the former name.

If I have an initial config that looks like this:
```
projects:
  fftest9:
    schemaPath: amplify/backend/api/fftest9/build/schema.graphql
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
```

- And then delete the API, then add a new API named ```fftest11``` and then try to run ```amplify codegen``` the results in this:

```
ENOENT: no such file or directory, open '/Users/kjetilge/Documents/GitHub/FAGFILM_AMPLIFY_APPS/fagfilm-backend/amplify/backend/api/fftest9/build/schema.graphql'
```
**The solution I'd like**
The schemaPath should be updated when I remove or add a new API.

For now I can change the schemaPath manually. It works fine, but it took some time to figure out what was happening.

I'm using the mock backend when writing this, but I believe I have encountered the same problem when running proper backend.

**Comment by kjetilge** [comment] 2020-03-02 16:52
Update:
So, I started from scratch and added all needed categories and pushed most of them EXCEPT the api. So when i try to "amplify mock" or "amplify codegen" i still get ```Codegen support only one GraphQL API per project```.

The reason is that, event after running ```Amplify delete``` the ```.graphqlconfig.yml``` from the previos backend is still there. It is not replaced before the api is pushed.

The manual states that one can start using the mocking server without having to push the category. That is only true the first time the api category is added to the backend.

Running either ```amplify delete``` or ```amplify init``` - probably the latter, should delete/replace ```.graphqlconfig.yml```

**Comment by SwaySway** [comment] 2020-03-02 22:30
Hello @kjetilge
Closing as duplicate of #3239

**Closed by SwaySway** 2020-03-02 22:30 UTC
Labels: code-gen, enhancement, graphql-transformer
