### ISSUE TITLE
lambda layer versions unsynced in console and local in multi env team

### ISSUE THREAD

**Issue by tomhirschfeld** [aws-amplify/amplify-cli#6395] opened 2021-01-15 02:20 UTC
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
The Lambda layer versions are continuously getting out of sync between deployments and rebasing from master in our team env. We use the provided lambda versions and they are constantly getting out of sync requiring us to manually update the team-provider-info.json file
**Amplify CLI Version**
4.40.1

**To Reproduce**
use lambda layers in a team with deployments to master and production envs  using the push simple script and individual team member envs using the normal amplify cli

**Expected behavior**
the layers in the console and in local should be sync'ed so that the code that attaching a lambda to a lambda layer with a version give predictable results and rebasing from master and running "amplify env checkout $env" then pushing does not result in CLI failures related to layer versions

**Additional context**

**Comment by attilah** [comment] 2021-01-15 19:27
@tomhirschfeld thanks for reporting, we are aware of the issue and actively working on it to come up with a solution.

Closing as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/5072

**Closed by attilah** 2021-01-15 19:27 UTC
Labels: bug, lambda-layers
