### ISSUE TITLE
Amplify pull fails with Cannot find module 'semver/ranges/subset'

### ISSUE THREAD

**Issue by jayKayEss** [aws-amplify/amplify-cli#9932] opened 2022-03-07 20:49 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

16.13.0

### Amplify CLI Version

7.6.23

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

auth, storage, function, api

### Amplify Commands

pull

### Describe the bug

Attempting to upgrade our app to 7.6.23, I received the following error after "amplify pull"

```
Failed to pull the backend.
Cannot find module 'semver/ranges/subset'
Require stack:
- /Users/jks/.config/yarn/global/node_modules/@aws-amplify/amplify-util-uibuilder/lib/commands/utils/notifyMissingPackages.js
- /Users/jks/.config/yarn/global/node_modules/@aws-amplify/amplify-util-uibuilder/lib/commands/generateComponents.js
- /Users/jks/.config/yarn/global/node_modules/@aws-amplify/amplify-util-uibuilder/lib/index.js
- /Users/jks/.config/yarn/global/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/invoke-plugin-method.js
- /Users/jks/.config/yarn/global/node_modules/@aws-amplify/cli/lib/domain/amplify-toolkit.js
- /Users/jks/.config/yarn/global/node_modules/@aws-amplify/cli/lib/domain/context.js
- /Users/jks/.config/yarn/global/node_modules/@aws-amplify/cli/lib/context-manager.js
- /Users/jks/.config/yarn/global/node_modules/@aws-amplify/cli/lib/index.js
- /Users/jks/.config/yarn/global/node_modules/@aws-amplify/cli/bin/amplify
Error: Cannot find module 'semver/ranges/subset'
Require stack:
- /Users/jks/.config/yarn/global/node_modules/@aws-amplify/amplify-util-uibuilder/lib/commands/utils/notifyMissingPackages.js
- /Users/jks/.config/yarn/global/node_modules/@aws-amplify/amplify-util-uibuilder/lib/commands/generateComponents.js
- /Users/jks/.config/yarn/global/node_modules/@aws-amplify/amplify-util-uibuilder/lib/index.js
- /Users/jks/.config/yarn/global/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/invoke-plugin-method.js
- /Users/jks/.config/yarn/global/node_modules/@aws-amplify/cli/lib/domain/amplify-toolkit.js
- /Users/jks/.config/yarn/global/node_modules/@aws-amplify/cli/lib/domain/context.js
- /Users/jks/.config/yarn/global/node_modules/@aws-amplify/cli/lib/context-manager.js
- /Users/jks/.config/yarn/global/node_modules/@aws-amplify/cli/lib/index.js
- /Users/jks/.config/yarn/global/node_modules/@aws-amplify/cli/bin/amplify
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/jks/.config/yarn/global/node_modules/@aws-amplify/amplify-util-uibuilder/src/commands/utils/notifyMissingPackages.ts:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/jks/.config/yarn/global/node_modules/@aws-amplify/amplify-util-uibuilder/src/commands/generateComponents.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at executeAmplifyCommand (/Users/jks/.config/yarn/global/node_modules/@aws-amplify/amplify-util-uibuilder/src/index.ts:7:25)
    at AmplifyToolkit.invokePluginMethod [as _invokePluginMethod] (/Users/jks/.config/yarn/global/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/invoke-plugin-method.ts:29:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at postPullCodegen (/Users/jks/.config/yarn/global/node_modules/@aws-amplify/cli/src/amplify-service-helper.ts:34:3)
    at onSuccess (/Users/jks/.config/yarn/global/node_modules/@aws-amplify/cli/src/attach-backend.ts:59:3)
    at attachBackend (/Users/jks/.config/yarn/global/node_modules/@aws-amplify/cli/src/attach-backend.ts:31:5)
    at Object.run (/Users/jks/.config/yarn/global/node_modules/@aws-amplify/cli/src/commands/pull.ts:57:9)
    at Object.executeAmplifyCommand (/Users/jks/.config/yarn/global/node_modules/@aws-amplify/cli/src/index.ts:373:5)
    at executePluginModuleCommand (/Users/jks/.config/yarn/global/node_modules/@aws-amplify/cli/src/execution-manager.ts:178:3)
    at executeCommand (/Users/jks/.config/yarn/global/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/Users/jks/.config/yarn/global/node_modules/@aws-amplify/cli/src/index.ts:205:5)
```

### Expected behavior

I should be able to pull an environment

### Reproduction steps

```
yarn global add @aws-amplify/cli@7.6.23
amplify pull --appId ddzxwz9kd3xor --envName danyette
```

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by johnpc** [comment] 2022-03-08 18:22
I am unable to reproduce this. Maybe there's something stale in your yarn cache. Does `yarn cache clean` fix the problem?

**Comment by jayKayEss** [comment] 2022-03-08 21:15
Hi there,

I tried `yarn cache clear --all` and reinstalled, but still got the same error.

Uninstalling via `yarn` and re-installing via `npm` seems to work OK, although I'm getting the following warning:

```
(node:20259) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/jks/.nvm/versions/node/v16.13.0/lib/node_modules/@aws-amplify/cli/node_modules/cloudform/package.json' of 'packages/cloudform/index.js'. Please either fix that or report it to the module author
```

This doesn't seem to prevent the CLI from functioning though.

**Comment by akshbhu** [comment] 2022-03-09 14:30
Glad to know that you are unblocked. 

Is the warning displayed during npm install or when running amplify commands ?

**Comment by akshbhu** [comment] 2022-03-09 14:52
Hey I have reproduced this . I guess this is happening with ```node - v : 16.14.0```  and  ```npm -v :  8.3.1``` and ```amplify -v : 7.6.23```.

happening with any amplify commands.

![image](https://user-images.githubusercontent.com/39866697/157466124-94cb01f0-169d-48cb-bd8a-e9d289c6614e.png)

**Comment by akshbhu** [comment] 2022-03-09 16:07
Closing in favour of : https://github.com/aws-amplify/amplify-cli/issues/9939

**Closed by akshbhu** 2022-03-09 16:07 UTC
Labels: bug, platform, p3

**Comment by WaynahArchitectureAgency** [comment] 2022-03-21 11:24
i have the same problem than you, i don't understand how resolve this, you can pls explain ?
