### ISSUE TITLE
Amplify creates duplicated files

### ISSUE THREAD

**Issue by menottiRicardo** [aws-amplify/amplify-cli#8065] opened 2021-08-30 22:47 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

us-east-1

### Amplify Console feature

Build settings

### Describe the bug

Adding a lambda trigger for the auth, creates two additional **package.json** files which create an error.
Im using AWS Amplify for react native.

### Expected behavior

Amplify cli shouldnt create two new **package.json**

### Reproduction steps

1. I add the post confirmation trigger to cognito
2. as soon as I push it, I creates the two new files

### Additional information

I deleted the app, change the lambda function and even use another computer and I doesn't solve the issue.
Im trying to add the user who sign up to a Dynamodb table through lambda

**Comment by cjihrig** [comment] 2021-08-31 16:12
@menottiRicardo in addition to @siegerts asked for, can you also provide a few more details since this issue was transferred from the amplify-console repo:

1. More detailed steps to reproduce the issue - I was able to run `amplify add auth`, add a post confirmation trigger, and run `amplify push` without errors. However, I realize that the auth flow has many steps, so it would be useful to know exactly what you're doing.
2. The relative paths in the project to the multiple `package.json` files that are causing the issue.

**Comment by kaustavghosh06** [comment] 2021-09-10 16:12
Closing based on last response and no further communication or related issues tied to this. Please let us know if you're still stuck on this issue.

**Closed by kaustavghosh06** 2021-09-10 16:12 UTC
Labels: auth, pending-close-response-required, transferred
