### ISSUE TITLE
Fresh amplify pull fails with 🛑 Command failed with ENOENT

### ISSUE THREAD

**Issue by sebsto** [aws-amplify/amplify-cli#13202] opened 2023-09-08 21:55 UTC
### How did you install the Amplify CLI?

brew install aws-amplify

### If applicable, what version of Node.js are you using?

v20.6.0

### Amplify CLI Version

12.4.0

### What operating system are you using?

macOS 12.5.1 (21G83)

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Describe the bug

When pulling a fresh project on a fresh machine, `amplify pull` fails with 

```
Updating Xcode project:
🛑 Command failed with ENOENT: /Users/ec2-user/.amplify/lib/aws-amplify-amplify-frontend-ios/resources/amplify-xcode import-config --path=/Users/ec2-user/amplify-ios-getting-started/code
spawn /Users/ec2-user/.amplify/lib/aws-amplify-amplify-frontend-ios/resources/amplify-xcode ENOENT
```

This step used to work with previous version of the Amplify CLI 

### Expected behavior

A fresh `amplify pull` should succeed

### Reproduction steps

1. `rm -rf ~/.amplify`
2. `git clone https://github.com/sebsto/amplify-ios-getting-started.git`
3. `cd amplify-ios-getting-started`
4. `./code/ci_actions/02_amplify.sh`

```
Default region: us-east-1
AWS CLI       : /opt/homebrew/bin/aws
Code directory: /Users/ec2-user/amplify-ios-getting-started/code
Home directory: /Users/ec2-user
Using amplify at /opt/homebrew/bin/amplify
Changing to code directory at /Users/ec2-user/amplify-ios-getting-started/code
~/amplify-ios-getting-started/code ~/amplify-ios-getting-started
Pulling amplify environment
Amplify AppID found: d1lld0ga9eqxz2. Amplify App name is: iOSGettingStarted
Backend environment dev found in Amplify Console app: iOSGettingStarted
✔ Successfully pulled backend environment dev from the cloud.
✅ 
Updating Xcode project:
🛑 Command failed with ENOENT: /Users/ec2-user/.amplify/lib/aws-amplify-amplify-frontend-ios/resources/amplify-xcode import-config --path=/Users/ec2-user/amplify-ios-getting-started/code
spawn /Users/ec2-user/.amplify/lib/aws-amplify-amplify-frontend-ios/resources/amplify-xcode ENOENT

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
```

### Project Identifier

3781fad98a5f311089fdb50c344822c2

### Log output

<details>

```
# Put your logs below this line
2023-09-08T21:50:54.211Z|info : amplify pull core  [***]{"amplify":"{\"projectName\":\"[***]Started\",\"appId\":\"[***]9eqxz2\",\"envName\":\"[***]ev\",\"[***]ultEditor\":\"code\"}","frontend":"{\"frontend\":\"ios\"","}":true,"providers":"{\"awscloudformation\":{\"configLevel\":\"general\",\"useProfile\":true,\"profileName\":\"default\"}}","yes":true,"region":"eu-central-1"}
2023-09-08T21:50:54.241Z|info : @aws-amplify/amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2023-09-08T21:50:54.681Z|info : amplify-provider-awscloudformation.amplify-service-permission-check.checkAmplifyServiceIAMPermission.amplifyClient.listApps([])
2023-09-08T21:50:55.083Z|info : amplify-provider-awscloudformation.attach-backend.getAmplifyApp.amplifyClient.getApp([{"appId":"[***]9eqxz2"}])
2023-09-08T21:50:55.444Z|info : amplify-provider-awscloudformation.attach-backend.getBackendEnv.amplifyClient.getBackendEnvironment([{"appId":"[***]9eqxz2","environmentName":"[***]ev"}])
2023-09-08T21:50:55.604Z|info : amplify-provider-awscloudformation.attach-backend.downloadBackend.s3.getObject([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]ify-[***]started-[***]ev-[***]022-[***]ment"}])
2023-09-08T21:50:56.355Z|info : amplify-provider-awscloudformation.zip-util.downloadZip.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip"},null])
2023-09-08T21:50:56.356Z|info : amplify-provider-awscloudformation.aws-s3.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]ify-[***]started-[***]ev-[***]022-[***]ment"}])
2023-09-08T21:50:56.931Z|info : amplify-provider-awscloudformation.initialize-env.run.cfn.updateamplifyMetaFileWithStackOutputs([{"StackName":"[***]ify-[***]started-[***]ev-[***]022"}])
2023-09-08T21:50:56.935Z|info : amplify-provider-awscloudformation.aws-cfn.updateamplifyMetaFileWithStackOutputs.cfn.listStackResources([{"StackName":"[***]ify-[***]started-[***]ev-[***]022"}])
2023-09-08T21:50:57.486Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]ify-[***]started-[***]ev-[***]022"}])
2023-09-08T21:50:57.973Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:eu-[***]ral-[***]93:stack/[***]ify-[***]started-[***]ev-[***]022-[***]gstarted-[***]JJYGM/[***]bf20-[***]ab-[***]ec-[***]d1-[***]8e8c8"}])
2023-09-08T21:50:57.974Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:eu-[***]ral-[***]93:stack/[***]ify-[***]started-[***]ev-[***]022-[***]rted2ee74a53-[***]CQGAC/[***]5850-[***]37-[***]ec-[***]80-[***]3ac92"}])
2023-09-08T21:50:57.975Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:eu-[***]ral-[***]93:stack/[***]ify-[***]started-[***]ev-[***]022-[***]image-[***]B8EQ2/[***]d960-[***]41-[***]ec-[***]34-[***]19420"}])
2023-09-08T21:50:58.415Z|info : amplify-provider-awscloudformation.aws-s3.s3.getFile([{"Key":"[***]ify-[***]json","Bucket":"[***]ify-[***]started-[***]ev-[***]022-[***]ment"}])
2023-09-08T21:50:58.985Z|info : amplify-provider-awscloudformation.CognitoUserPoolService.listUserPool.cognito.listUserPools([{"params":{"MaxResults":60}}])
2023-09-08T21:50:59.409Z|info : amplify-provider-awscloudformation.CognitoUserPoolService.listUserPoolIdentityProviders.cognito.listIdentityProviders([{"UserPoolId":"[***]u-[***]ral-[***]yKqf2","MaxResults":60}])
2023-09-08T21:50:59.730Z|info : amplify-provider-awscloudformation.CognitoUserPoolService.listUserPoolIdentityProviders.cognito.describeIdentityProviderPromises([{"UserPoolId":"[***]u-[***]ral-[***]yKqf2","ProviderName":"[***]hApple"}])
2023-09-08T21:54:19.472Z|info : amplify diagnose core  {"send-report":true,"yes":false}
2023-09-08T21:54:19.502Z|info : @aws-amplify/amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2023-09-08T21:54:22.820Z|info : amplify diagnose core  {"send-report":true,"yes":false}
2023-09-08T21:54:22.854Z|info : @aws-amplify/amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}

```

</details>

### Additional information

I also filed https://github.com/aws-amplify/amplify-cli/issues because I observe the two different behaviors on two different machines.

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by sebsto** [comment] 2023-09-08 22:40
I received the same error when initializing a project from scratch 

```
➜  test amplify init 
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project test
The following configuration will be applied:

Project information
| Name: test
| Environment: dev
| Default editor: Visual Studio Code
| App type: ios

? Initialize the project with the above configuration? Yes
Using default provider  awscloudformation
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use default
Adding backend environment dev to AWS Amplify app: d2hqyq7e33dbbr

Deployment completed.
Deploying root stack test [ ====================-------------------- ] 2/4
	amplify-test-dev-173633        AWS::CloudFormation::Stack     CREATE_IN_PROGRESS             Fri Sep 08 2023 17:36:38…     
	DeploymentBucket               AWS::S3::Bucket                CREATE_IN_PROGRESS             Fri Sep 08 2023 17:36:40…     
	UnauthRole                     AWS::IAM::Role                 CREATE_COMPLETE                Fri Sep 08 2023 17:36:56…     
	AuthRole                       AWS::IAM::Role                 CREATE_COMPLETE                Fri Sep 08 2023 17:36:56…     

✔ Help improve Amplify CLI by sharing non-sensitive project configurations on failures (y/N) · yes

    Thank you for helping us improve Amplify CLI!
Deployment state saved successfully.
✔ Initialized provider successfully.
✅ Initialized your environment successfully.
✅ Your project has been successfully initialized and connected to the cloud!
Some next steps:

"amplify status" will show you what you've added already and if it's locally configured or deployed
"amplify add <category>" will allow you to add features like user login or a backend API
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify console" to open the Amplify Console and view your project status
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud


Pro tip:
Try "amplify add api" to create a backend API and then "amplify push" to deploy everything

Updating Xcode project:
🛑 Command failed with ENOENT: /Users/stormacq/.amplify/lib/aws-amplify-amplify-frontend-ios/resources/amplify-xcode import-config --path=/Users/stormacq/Documents/amazon/code/amplify/test
spawn /Users/stormacq/.amplify/lib/aws-amplify-amplify-frontend-ios/resources/amplify-xcode ENOENT

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

```

**Comment by josefaidt** [comment] 2023-09-08 22:47
Hey @sebsto :wave: thanks for raising this! I was able to successfully reproduce this by initializing a new Swift/iOS project with CLI 12.4.0, marking as a bug

**Comment by sebsto** [comment] 2023-09-08 22:49
Workaround :

- uninstall amplify cli from brew 
- reinstall with curl : `curl -sL https://aws-amplify.github.io/amplify-cli/install | bash && $SHELL`

after that, `amplify init` and `amplify pull` works as expected.

**Comment by sebsto** [comment] 2023-09-08 22:56
one caveat for `amplify pull`, it does not create the `generated/src` directory, It must be created manually before the pull.
Then the first `amplify pull` fails and the second succeeds.
 See https://github.com/aws-amplify/amplify-cli/issues/13201 to track this other problem

**Comment by ykethan** [comment] 2023-09-08 23:14
@josefaidt The error `🚫 xcodeProject: -- Caused by: notFound` will occur if you do not have xcode installed locally 
issue filed here: https://github.com/aws-amplify/amplify-swift/issues/3139

**Comment by sebsto** [comment] 2023-09-08 23:16
@josefaidt @ykethan  the error you reproduced is the not the same I reported.

Also, look at https://github.com/aws-amplify/amplify-cli/issues/13202#issuecomment-1712310065 for a workaround.

Seems this issue is specific to a `brew` installation.  When doing a `curl` installation, it works.

**Comment by josefaidt** [comment] 2023-09-09 00:00
After further review the issue in the original post (`ENOENT...`) is due to the removal of `~/.amplify` where this bin is located

**Comment by sebsto** [comment] 2023-09-09 00:08
I disagree, unless I am wrong, the binary is in `/opt/homebrew/bin/` when installing with `brew`.

**Comment by josefaidt** [comment] 2023-09-09 00:08
apologies @sebsto, updated my comment with the callout for the `amplify-xcode` supplemental bin

**Comment by sebsto** [comment] 2023-09-09 01:42
@josefaidt, I triple check. When installing using `brew install aws-amplify`, there is no directory `~/.amplify` after installation.

The directory is created during `amplify pull`.  In the `aws-amplify-amplify-frontend-ios/resources` directory, there is no executable binary. Just a `json` file.

Look at this sequence of commands :

```
# no left over from previous curl based installation
➜  ~ rm -rf ~/.amplify         

# install from scratch using brew 
➜  ~ brew install aws-amplify  
==> Downloading https://ghcr.io/v2/homebrew/core/aws-amplify/manifests/12.4.0
Already downloaded: /Users/ec2-user/Library/Caches/Homebrew/downloads/2ae5fe76b1bc7bd51697b70168b8bed9266fdc019db6c07a1ee2cfc7ce44d1a7--aws-amplify-12.4.0.bottle_manifest.json
==> Fetching aws-amplify
==> Downloading https://ghcr.io/v2/homebrew/core/aws-amplify/blobs/sha256:08c0fb9cb26db8d867406614a10e8d95e9af7f6c85be7116fad540cafdd1c389
Already downloaded: /Users/ec2-user/Library/Caches/Homebrew/downloads/9dbc93078c5b4e69e51aa22affcc4a6efaa7a98dc876c757a10b460708987fe6--aws-amplify--12.4.0.arm64_monterey.bottle.tar.gz
==> Pouring aws-amplify--12.4.0.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/aws-amplify/12.4.0: 67,181 files, 658.5MB
==> Running `brew cleanup aws-amplify`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

# download a fresh copy of my project 
➜  ~ rm -rf amplify-ios-getting-started && git clone https://github.com/sebsto/amplify-ios-getting-started.git && cd amplify-ios-getting-started

Cloning into 'amplify-ios-getting-started'...
remote: Enumerating objects: 2331, done.
remote: Counting objects: 100% (553/553), done.
remote: Compressing objects: 100% (198/198), done.
remote: Total 2331 (delta 358), reused 531 (delta 340), pack-reused 1778
Receiving objects: 100% (2331/2331), 26.38 MiB | 56.99 MiB/s, done.
Resolving deltas: 100% (1471/1471), done.

# launch the script that does the amplify pull
➜  amplify-ios-getting-started git:(main) ./code/ci_actions/02_amplify.sh
Default region: us-east-1
AWS CLI       : /opt/homebrew/bin/aws
Code directory: /Users/ec2-user/amplify-ios-getting-started/code
Home directory: /Users/ec2-user
Using amplify at /opt/homebrew/bin/amplify
Changing to code directory at /Users/ec2-user/amplify-ios-getting-started/code
~/amplify-ios-getting-started/code ~/amplify-ios-getting-started
Pulling amplify environment
Amplify AppID found: d1lld0ga9eqxz2. Amplify App name is: iOSGettingStarted
Backend environment dev found in Amplify Console app: iOSGettingStarted
✔ Successfully pulled backend environment dev from the cloud.
✅ 
Updating Xcode project:
🛑 Command failed with ENOENT: /Users/ec2-user/.amplify/lib/aws-amplify-amplify-frontend-ios/resources/amplify-xcode import-config --path=/Users/ec2-user/amplify-ios-getting-started/code
spawn /Users/ec2-user/.amplify/lib/aws-amplify-amplify-frontend-ios/resources/amplify-xcode ENOENT

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

# FAILED 

# some files have been created in ~/.amplify but not the executable 
➜  amplify-ios-getting-started git:(main) ✗ ls -al ~/.amplify/lib/aws-amplify-amplify-frontend-ios/resources 
total 8
drwxr-xr-x  3 ec2-user  staff   96 Sep  9 01:37 .
drwxr-xr-x  3 ec2-user  staff   96 Sep  9 01:37 ..
-rw-r--r--  1 ec2-user  staff  955 Sep  9 01:37 amplify-xcode.json
```

**Comment by sebsto** [comment] 2023-09-09 01:47
When using the curl-based installation, it works. (modulo the generated directory problem that I reported separately)

Notice in the last step that the `amplify-xcode` binary is present.

```
# no left over from previous curl based installation
➜  ~ rm -rf ~/.amplify                                                

 # install from scratch using curl                                                                         
➜  ~ curl -sL https://aws-amplify.github.io/amplify-cli/install | bash && $SHELL


 Installing the AWS Amplify CLI...

 Downloading binary...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  281M  100  281M    0     0   131M      0  0:00:02  0:00:02 --:--:--  138M
 Download complete!
 Extracting binary...
 Extraction complete!

Successfully installed the Amplify CLI.
Run 'amplify help' to get started!

# download a fresh copy of my project 
➜  ~ rm -rf amplify-ios-getting-started && git clone https://github.com/sebsto/amplify-ios-getting-started.git && cd amplify-ios-getting-started

Cloning into 'amplify-ios-getting-started'...
remote: Enumerating objects: 2331, done.
remote: Counting objects: 100% (553/553), done.
remote: Compressing objects: 100% (198/198), done.
remote: Total 2331 (delta 358), reused 531 (delta 340), pack-reused 1778
Receiving objects: 100% (2331/2331), 26.38 MiB | 59.24 MiB/s, done.
Resolving deltas: 100% (1471/1471), done.

# launch the script that does the amplify pull
➜  amplify-ios-getting-started git:(main) ./code/ci_actions/02_amplify.sh

Default region: us-east-1
AWS CLI       : /opt/homebrew/bin/aws
Code directory: /Users/ec2-user/amplify-ios-getting-started/code
Home directory: /Users/ec2-user
Using amplify at /Users/ec2-user/.amplify/bin/amplify
Changing to code directory at /Users/ec2-user/amplify-ios-getting-started/code
~/amplify-ios-getting-started/code ~/amplify-ios-getting-started
Pulling amplify environment
Amplify AppID found: d1lld0ga9eqxz2. Amplify App name is: iOSGettingStarted
Backend environment dev found in Amplify Console app: iOSGettingStarted
✔ Successfully pulled backend environment dev from the cloud.
✅ 
Updating Xcode project:
-- Amplify project found.
-- Amplify config files found.
-- Successfully updated project /Users/ec2-user/amplify-ios-getting-started/code.
🚫 folderNotFound: Amplify generated models not found at /Users/ec2-user/amplify-ios-getting-started/code/amplify/generated/models
-- Recovery suggestion: Run amplify codegen models.
🛑 Command failed with exit code 1: /Users/ec2-user/.amplify/lib/aws-amplify-amplify-frontend-ios/resources/amplify-xcode import-models --path=/Users/ec2-user/amplify-ios-getting-started/code

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: dabfa92c-1b62-4fb3-9e55-7a78a3f0a4db
First amplify pull failed, applying workaround for Amplify CLI Issue # 13201

Pre-pull status:

    Current Environment: dev
    
┌──────────┬───────────────────────────┬───────────┬───────────────────┐
│ Category │ Resource name             │ Operation │ Provider plugin   │
├──────────┼───────────────────────────┼───────────┼───────────────────┤
│ Auth     │ iosgettingstarted2ee74a53 │ No Change │ awscloudformation │
├──────────┼───────────────────────────┼───────────┼───────────────────┤
│ Api      │ iosgettingstarted         │ No Change │ awscloudformation │
├──────────┼───────────────────────────┼───────────┼───────────────────┤
│ Storage  │ image                     │ No Change │ awscloudformation │
└──────────┴───────────────────────────┴───────────┴───────────────────┘

✔ Successfully pulled backend environment dev from the cloud.
✅ 
Post-pull status:

    Current Environment: dev
    
┌──────────┬───────────────────────────┬───────────┬───────────────────┐
│ Category │ Resource name             │ Operation │ Provider plugin   │
├──────────┼───────────────────────────┼───────────┼───────────────────┤
│ Auth     │ iosgettingstarted2ee74a53 │ No Change │ awscloudformation │
├──────────┼───────────────────────────┼───────────┼───────────────────┤
│ Api      │ iosgettingstarted         │ No Change │ awscloudformation │
├──────────┼───────────────────────────┼───────────┼───────────────────┤
│ Storage  │ image                     │ No Change │ awscloudformation │
└──────────┴───────────────────────────┴───────────┴───────────────────┘

Updating Xcode project:
-- Amplify project found.
-- Amplify config files found.
-- Successfully updated project /Users/ec2-user/amplify-ios-getting-started/code.
-- Amplify models folder found at /Users/ec2-user/amplify-ios-getting-started/code/amplify/generated/models
-- Successfully added models [] to 'AmplifyModels' group.
Amplify setup completed successfully.
Generate code for application models
GraphQL schema compiled successfully.

Edit your schema at /Users/ec2-user/amplify-ios-getting-started/code/amplify/backend/api/iosgettingstarted/schema.graphql or place .graphql files in a directory at /Users/ec2-user/amplify-ios-getting-started/code/amplify/backend/api/iosgettingstarted/schema
Successfully generated models. Generated models can be found in /Users/ec2-user/amplify-ios-getting-started/code/amplify/generated/models
Updating Xcode project:
-- Amplify models folder found at /Users/ec2-user/amplify-ios-getting-started/code/amplify/generated/models
-- Successfully added models ["AmplifyModels.swift", "NoteData+Schema.swift", "NoteData.swift"] to 'AmplifyModels' group.
Amplify setup completed successfully.
~/amplify-ios-getting-started

# SUCCESS ! 

# the amplify-xcode binary has been installed
➜  amplify-ios-getting-started git:(main) ✗ ls -al ~/.amplify/lib/aws-amplify-amplify-frontend-ios/resources

total 20208
drwxr-xr-x  4 ec2-user  staff       128 Sep  9 01:43 .
drwxr-xr-x  3 ec2-user  staff        96 Sep  9 01:43 ..
-rwxr-xr-x  1 ec2-user  staff  10339016 Sep  9 01:43 amplify-xcode
-rw-r--r--  1 ec2-user  staff       955 Sep  9 01:43 amplify-xcode.json
```

**Comment by josefaidt** [comment] 2023-09-11 18:22
Hey @sebsto thanks for the clarification! We do not officially vend the Amplify CLI via Homebrew, and the curl/npm instructions are the official Amplify CLI. Despite this, I was able to reproduce the issue where the CLI previously printed a warning and is now printing an error.

**Comment by klsetzer** [comment] 2023-09-14 16:30
I am seeing the same behavior with both the npm-installed amplify cli (12.4.0 and 12.2.3) and the script-installed amplify cli from https://github.com/aws-amplify/amplify-cli/issues/13104#issuecomment-1675137697.

I am attempting to init a new xcode/ios project. Xcode is installed.

```sh
$ amplify pull --appId <app id> --envName staging
Opening link: https://us-east-1.admin.amplifyapp.com/admin/<app id>/staging/verify/?loginVersion=1
⠏ Confirm login in the browser or manually paste in your CLI login key:
Successfully received Amplify Studio tokens.
Amplify AppID found: <app id>. Amplify App name is: Hush
Backend environment staging found in Amplify Console app: Hush
? Choose your default editor: Xcode (macOS only)
✔ Choose the type of app that you're building · ios
? Do you plan on modifying this backend? Yes
✔ Successfully pulled backend environment staging from the cloud.
✅

✅ Successfully pulled backend environment staging from the cloud.
Run 'amplify pull' to sync future upstream changes.

Updating Xcode project:
🚫 xcodeProject:
-- Caused by: notFound(path: "/Users/<user>")
🛑 Command failed with exit code 1: /Users/<user>/.amplify/lib/aws-amplify-amplify-frontend-ios/resources/amplify-xcode import-config --path=/Users/<user>

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: fd397e50-186d-4cd3-8af1-efe79881f986
✔ An unexpected error has occurred, opt in to send an error report to AWS Amplify with non-sensitive project configuration files. Confirm  (y/N) · no

```

**Comment by josefaidt** [comment] 2023-09-19 20:35
Closing in favor of tracking https://github.com/aws-amplify/amplify-swift/issues/3139

**Closed by josefaidt** 2023-09-19 20:35 UTC
Labels: bug, investigating, platform
