### ISSUE TITLE
Amplify env checkout falls out of sync when a resource is updated in another environment

### ISSUE THREAD

**Issue by phani-srikar** [aws-amplify/amplify-cli#8351] opened 2021-10-04 01:09 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14

### Amplify CLI Version

6.1.1

### What operating system are you using?

MacOS

### Amplify Categories

auth

### Amplify Commands

env

### Describe the bug

**Although `auth` category resource is used as an example, the following issue is applicable to any category resource that stores updatable configuration in `amplify-meta.json`.** 
I have 2 environments in my Amplify JS App (say `dev` and `test`). I add and push an Auth resource in my `dev` env with default configuration. Now, I checkout the `test` environment using `amplify env checkout test`, update the Auth resource's MFA configuration (for example) and push the modified resource in `test` environment. 
Now when I switch back to the `dev` environment using `amplify env checkout dev`, `amplify status` shows that the Auth resource has updates to push (I confirm this is correct as the `parameters.json` file for that resource has updated configuration inputs to the stack). However, the `amplify-meta` file does not have the updated resource configuration. Hence, after I run `amplify push` in `dev`, the Auth resource stack provisions the updated stack but neither `aws-exports` nor `amplify-meta` show the correct updated configuration. 

Digging a little into why `env checkout` does not fetch the resource configuration updates into `amplify-meta`, I see that there is a file called `backend-config` which is not updated during `amplify update <category>` commands. `amplify env checkout` might be using that file to initialize the `amplify-meta` during env switching, hence making it fall out of sync. 

### Expected behavior

Both `amplify-meta` and `aws-exports` should reflect the changes in resource configuration made in another environment after running `amplify push`. 

### Reproduction steps

1. `amplify init` in a JS app - choose env name as `dev`. Run `amplify push`.
2. `amplify env add test`, `amplify env checkout test` followed by `amplify push` in `test` environment. 
3. Switch back to dev environment using `amplify env checkout dev`.
4. Add Auth resource in dev using `amplify add auth` - choose all defaults. Run `amplify push` and verify the following Auth configuration settings in `amplify-meta` and `aws-exports`:
```
"mfaConfiguration": "OFF",
"mfaTypes": [
  "SMS"
],
"verificationMechanisms": [
  "EMAIL"
]
```
5. Checkout the `test` environment using `amplify env checkout test`. Run `amplify update auth` and set the following configuration:
```
What do you want to do? Walkthrough all the auth configurations
Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AWS IAM controls (Enables per-user Storage features for images or other content, Analytics, and more)
Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) Yes
Do you want to enable 3rd party authentication providers in your identity pool? No
Do you want to add User Pool Groups? No
Do you want to add an admin queries API? No
Multifactor authentication (MFA) user login options: OPTIONAL (Individual users can use MFA)
For user login, select the MFA types: SMS Text Message, Time-Based One-Time Password (TOTP)
Please specify an SMS authentication message: Your authentication code is {####}
Email based user registration/forgot password: Disabled (Uses SMS/TOTP as an alternative)
Please specify an SMS verification message: Your verification code is {####}
Do you want to override the default password policy for this User Pool? No
 Specify the app's refresh token expiration period (in days): 30
Do you want to specify the user attributes this app can read and write? No
Do you want to enable any of the following capabilities? 
Do you want to use an OAuth flow? No
Do you want to configure Lambda Triggers for Cognito? No
```
6. Run `amplify push` and verify that the Auth configuration in `amplify-meta` and `aws-exports` are updated with following options:
```
"mfaConfiguration": "OPTIONAL",
"mfaTypes": [
  "SMS",
  "TOTP"
],
"verificationMechanisms": [
  "PHONE_NUMBER"
]
```
Note that the `backend-config` is not updated with the above options and still has the older config. 
7. Run `amplify env checkout dev` and verify that `amplify status` shows the Auth resource as updated which can be confirmed with the following options in `parameters.json` file for Auth resource:
```
"autoVerifiedAttributes": [
  "phone_number"
],
"mfaConfiguration": "OPTIONAL",
"mfaTypes": [
  "SMS Text Message",
  "TOTP"
]
```
8. However, check that the `amplify-meta` and `backend-config` files still have the old configuration:
```
"mfaConfiguration": "OFF",
"mfaTypes": [
  "SMS"
],
"verificationMechanisms": [
  "EMAIL"
]
```
9. Run `amplify push`. You see that the stack is updated with the new MFA configuration but the `aws-exports` file still has the older configuration. 
```
"aws_cognito_mfa_configuration": "OFF",
"aws_cognito_mfa_types": [
    "SMS"
],
"aws_cognito_verification_mechanisms": [
    "EMAIL"
]
```

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment] 2021-10-04 14:50
Hey @phani-srikar :wave: thanks for raising this! To clarify, are each of these two environments tied to a corresponding git branch?

**Comment by phani-srikar** [comment] 2021-10-04 16:21
Hi. No they are on the same branch. I am not using hosting.

**Comment by josefaidt** [comment] 2021-10-04 18:03
Hey @phani-srikar thanks for clarifying! The [multi-environment workflow](https://docs.amplify.aws/cli/teams/sandbox/) relies heavily on git to prevent unwanted/unintentional changes to your project's backend resources. Despite this, it is interesting that you are not seeing an update to your exports file after an env checkout and resource update. 

> Run amplify push. You see that the stack is updated with the new MFA configuration but the aws-exports file still has the older configuration.

Ideally the exports file is updated after a successful push, however in this case we can mitigate by checking out the current environment (similar to the Custom Resources workflow to enable a new custom resource) with `amplify env checkout <current-environment-name>`.

Marking as a bug 🙂

**Comment by lazpavel** [comment] 2022-02-15 22:14
Hi @phani-srikar, 

I was able to reproduce the issue related to the `backend-config.json` not being updated which I fix as part of 
[8566](https://github.com/aws-amplify/amplify-cli/issues/8566). But I am not able to reproduce `step 8` incorrect `amplify-meta.json` and step 9 incorrect `aws-exports.js`

closing this ticket, please reopen if you still have this issue with latest CLI

**Closed by lazpavel** 2022-02-15 22:14 UTC
Labels: bug, multienv
