### ISSUE TITLE
AccessDenied When uploading image using S3 trigger

### ISSUE THREAD

**Issue by MontoyaAndres** [aws-amplify/amplify-cli#6375] opened 2021-01-13 04:26 UTC
**Describe the bug**
I have updated my Bucket to add a trigger, like this:

```
andres@andres:~/Entrepreneurship/TeVi$ amplify update storage
? Please select from one of the below mentioned services: Content (Images, audio, video, etc.)
? Who should have access: Auth and guest users
? What kind of access do you want for Authenticated users? create/update, read
? What kind of access do you want for Guest users? read
? Do you want to add a Lambda Trigger for your S3 Bucket? Yes
? Select from the following options Create a new function
Successfully added resource S3Triggerde8bc6ca locally
? Do you want to edit the local S3Triggerde8bc6ca lambda function now? No
Successfully updated resource
```

So, I tried to upload an image, logged in as a user, but the lambda throws me this error:

```
2021-01-13T03:38:01.328Z	453e3118-2293-4632-be5e-aed92f7f2a6f	ERROR	{ AccessDenied: Access Denied
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/services/s3.js:700:35)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message: 'Access Denied',
  code: 'AccessDenied',
  region: null,
  time: 2021-01-13T03:38:01.267Z,
  requestId: '223B11A29A616F64',
  extendedRequestId:
   'B+OEiQmGOdHQTCSIqERtk7Dvto+Ohqysz+9tkB6np0u+2vfLLU/pXvGW01r3+J3gvPpjVhO3iGc=',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 45.67291209389794 }
```

So, the lambda is not able to just do a getObject operation :(.

Note: I have configured the project to use Cognito as the main auth method, and IAM, to allow unauthorized access.

**Amplify CLI Version**
4.40.1

**Expected behavior**
Allow executing s3 operations in the lambda created without problems.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Node Version. v14.15.1

**Additional context**
The user uses the application, he signed in using Cognito, like this: `await Auth.signIn(values.email, values.password);`. When he tries to upload the image, like this: `await Storage.put('my_image.png', values.picture[0]);`. The image is uploaded successfully, but when the lambda is executed, I get the access denied error... This is the code I want to execute:

index.js:
```
const S3 = require('aws-sdk/clients/s3');
const sharp = require('sharp');

const s3 = new S3();

const regexUserPictureRoute = /public\/\b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b\/picture\/.*/gy;
const SIZE = 130;

exports.handler = async event => {
  if (event.Records[0].eventName === 'ObjectRemoved:Delete') return;

  const Bucket = event.Records[0].s3.bucket.name;
  const Key = event.Records[0].s3.object.key;

  if (!regexUserPictureRoute.test(Key)) return;

  try {
    let image = await s3.getObject({ Bucket, Key }).promise();
    image = await sharp(image.Body);

    const metadata = await image.metadata();

    if (metadata.width > SIZE || metadata.height > SIZE) {
      const resizedImage = await image
        .resize({ width: SIZE, height: SIZE })
        .toBuffer();
      await s3
        .putObject({
          Bucket,
          Body: resizedImage,
          Key,
        })
        .promise();
    }

    return;
  } catch (err) {
    console.error(err);
  }
};
```

package.json:
```
{
  "name": "S3Triggerde8bc6ca",
  "version": "2.0.0",
  "description": "Lambda function generated by Amplify",
  "main": "index.js",
  "license": "Apache-2.0",
  "scripts": {
    "install": "npm install --arch=x64 --platform=linux sharp"
  },
  "dependencies": {
    "sharp": "^0.27.0"
  }
}
```

This is what I'm doing... If you need more information, let me know 🙏

**Comment by MontoyaAndres** [comment] 2021-01-13 21:45
I also tried to add the permissions to the lambda, but I got this error:

```
andres@andres:~/Entrepreneurship/TeVi$ amplify update function
? Select which capability you want to update: Lambda function (serverless function)
? Select the Lambda function you want to update S3Triggerde8bc6ca
General information
| Name: S3Triggerde8bc6ca
| Runtime: nodejs

Resource access permission
- Not configured

Scheduled recurring invocation
| Not configured

Lambda layers
- Not configured

? Which setting do you want to update? Resource access permissions
? Select the category storage
? Storage has 4 resources in this project. Select the one you would like your Lambda to access s365879b5a
? Select the operations you want to permit for s365879b5a read, update

You can access the following resource attributes as environment variables from your Lambda function
        STORAGE_S365879B5A_BUCKETNAME
Error: Cannot add S3Triggerde8bc6ca due to a cyclic dependency
    at checkForCyclicDependencies (/home/andres/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/update-amplify-meta.js:199:15)
    at AmplifyToolkit.updateamplifyMetaAfterResourceUpdate [as _updateamplifyMetaAfterResourceUpdate] (/home/andres/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/update-amplify-meta.js:116:9)
    at updateFunctionResource (/home/andres/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/index.js:144:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.executeAmplifyCommand (/home/andres/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/index.js:195:5)
    at async executePluginModuleCommand (/home/andres/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:166:5)
    at async Object.executeCommand (/home/andres/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/home/andres/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/lib/index.js:92:9)
There was an error adding the function resource
```

**Comment by attilah** [comment] 2021-01-13 22:04
@MontoyaAndres I tried to reproduce the problem and it was working for me with your steps.

I removed the regex part from the code to simplify the testing as it is unrelated and when I uploaded a JPG from theS3 console it was overwritten with a small version of it as it should.

When you create a trigger we create the appropriate IAM policy in the `s3-cloudformation-template.json` file which grants wildcard permissions to the bucket. Could you check and confirm that you have a snippet like this there?

```json
          "S3TriggerBucketPolicy": {
            "DependsOn": [
                "S3Bucket"
            ],
            "Type": "AWS::IAM::Policy",
            "Properties": {
                "PolicyName": "amplify-lambda-execution-policy",
                "Roles": [
                    {
                        "Ref": "functionS3Trigger90268e89LambdaExecutionRole"
                    }
                ],
                "PolicyDocument": {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Action": [
                                "s3:PutObject",
                                "s3:GetObject",
                                "s3:ListBucket",
                                "s3:DeleteObject"
                            ],
                            "Resource": [
                                {
                                    "Fn::Join": [
                                        "",
                                        [
                                            "arn:aws:s3:::",
                                            {
                                                "Ref": "S3Bucket"
                                            },
                                            "/*"
                                        ]
                                    ]
                                }
                            ]
                        }
                    ]
                }
            }
        },
```

Also try to upload from the S3 console and check the cloudwatch log for the lambda if there is anything that could help troubleshooting it? from CLI side it works as expected so far.

**Comment by MontoyaAndres** [comment] 2021-01-13 22:44
I have the same...

```
       "S3TriggerBucketPolicy": {
            "Type": "AWS::IAM::Policy",
            "DependsOn": [
                "S3Bucket"
            ],
            "Properties": {
                "PolicyName": "s3-trigger-lambda-execution-policy",
                "Roles": [
                    {
                        "Ref": "functionS3Triggerde8bc6caLambdaExecutionRole"
                    }
                ],
                "PolicyDocument": {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Action": [
                                "s3:PutObject",
                                "s3:GetObject",
                                "s3:ListBucket",
                                "s3:DeleteObject"
                            ],
                            "Resource": [
                                {
                                    "Fn::Join": [
                                        "",
                                        [
                                            "arn:aws:s3:::",
                                            {
                                                "Ref": "S3Bucket"
                                            },
                                            "/*"
                                        ]
                                    ]
                                }
                            ]
                        }
                    ]
                }
            }
        },
```

I'm still getting the same error :/

**Comment by MontoyaAndres** [comment] 2021-01-13 22:57
I tried also removing the trigger and the lambda, and create it again, and did not work :(, I have the same access denied in the lambda log. Maybe I can send you the amplify folder?

**Comment by attilah** [comment] 2021-01-13 23:20
I noticed that you were using a 4.40.1 not 4.41.1 which is the latest and I was tested with.

After `amplify init`, here is my full flow:

```

❯ amplify add storage
? Please select from one of the below mentioned services: Content (Images, audio, video, etc.)
? You need to add auth (Amazon Cognito) to your project in order to add storage for user files. Do you want to add auth now? Yes
Using service: Cognito, provided by: awscloudformation

 The current configured provider is Amazon Cognito.

 Do you want to use the default authentication and security configuration? Default configuration
 Warning: you will not be able to edit these selections.
 How do you want users to be able to sign in? Username
 Do you want to configure advanced settings? No, I am done.
Successfully added auth resource s3t22b31ea8b locally

Some next steps:
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud

? Please provide a friendly name for your resource that will be used to label this category in the project: s3t2
? Please provide bucket name: s3t2
? Who should have access: Auth and guest users
? What kind of access do you want for Authenticated users? create/update, read
? What kind of access do you want for Guest users? read
? Do you want to add a Lambda Trigger for your S3 Bucket? Yes
? Select from the following options Create a new function
Successfully added resource S3Trigger467d953c locally
? Do you want to edit the local S3Trigger467d953c lambda function now? No
Auth configuration is required to allow unauthenticated users, but it is not configured properly.
Successfully updated auth resource locally.
Successfully added resource s3t2 locally

If a user is part of a user pool group, run "amplify update storage" to enable IAM group policies for CRUD operations
Some next steps:
"amplify push" builds all of your local backend resources and provisions them in the cloud
"amplify publish" builds all of your local backend and front-end resources (if you added hosting category) and provisions them in the cloud
```
After this overwrite `index.js` and `package.json` and do `amplify push --yes`

Go to S3 console and upload an image. (Note I removed the regex matching part in your code). I like to close out any other code then the Lambda and the Bucket itself, since that is what the CLI manages.

And everything worked like a charm. Would you give a try with the latest CLI and the exact steps above? You can send the amplify folder to amplify-cli@amazon.com I would compare to see if I see anything.

**Comment by MontoyaAndres** [comment] 2021-01-13 23:34
I have sent you the email with the folder, I'm going to try the new version and comment on how it was :)

**Comment by MontoyaAndres** [comment] 2021-01-13 23:48
Tried with the latest, same error... Please help me check the folder if there's something wrong :(

![image](https://user-images.githubusercontent.com/15065852/104526181-cfedee00-55cf-11eb-9839-0ff9cb2f2b17.png)

**Comment by attilah** [comment] 2021-01-14 00:03
I compared the folders and cannot see any difference that would cause this problem. CF templates, policy all looks good.

**Comment by MontoyaAndres** [comment] 2021-01-14 00:24
Maybe is possible for you to take the cloud formation templates and test them? I really don't know why it's happening that just to me 😪😢

**Comment by attilah** [comment] 2021-01-14 00:32
I took your sources, did an `amplify env add`, then `amplify push` and after uploading a file I saw this in the CloudWatch logs:
![image](https://user-images.githubusercontent.com/230432/104528618-a11a4c80-55bc-11eb-9e4c-9970e670b5b9.png)

So the trigger was invoked and was able to read the resource from S3. The CLI generated and provisions the right resources, I can think of some account level problem on your side, as it is working here with multiple methods.

**Comment by MontoyaAndres** [comment] 2021-01-14 00:53
@attilah thank you for all the effort you did to helping me! I really appreciate it! Thank you so much. Maybe is because of that account level problem. The account has administrator access in IAM. If it's not that, where I can see them?

**Comment by attilah** [comment] 2021-01-14 17:38
@MontoyaAndres admin access should be fine.

**Comment by attilah** [comment] 2021-01-14 20:23
Closing the issue as it is answered, if @MontoyaAndres something new comes up feel free to comment on here or open a new issue.

**Closed by attilah** 2021-01-14 20:23 UTC
Labels: not-reproducable, pending-response, pending-triage, storage

**Comment by MontoyaAndres** [comment] 2021-01-14 23:12
Thank you so much for the help!

**Comment by MontoyaAndres** [comment] 2021-01-16 03:19
Hey @attilah I could found the problem, it's not about permissions, it's about aws s3 and developers :).

aws-sdk s3 returns Access denied when the file is not found or the file has the name with spaces (in my case), it's not descriptive... I lost 5 days finding the error on the permissions and was this. My dear f*cking s3 throws "Access Denied" when the file is not found... They couldn't put "File not found" or something better... Just Access denied :).

**Comment by undefobj** [comment] 2021-01-16 05:50
> Hey @attilah I could found the problem, it's not about permissions, it's about aws s3 and developers :).
> 
> aws-sdk s3 returns Access denied when the file is not found or the file has the name with spaces (in my case), it's not descriptive... I lost days finding the error on the permissions and was this. My dear f*cking s3 throws "Access Denied" when the file is not found... They couldn't put "File not found" or something better... Just Access denied :).
> 
> Maybe you might send this to any s3 developer and say to them that, please, improve the warning/error messages, maybe they can save other people from stress thanks to just a message :)

Sorry you lost days to this, but there's a valid reason for this behavior: information disclosure. If you throw something like "file not found" an attacker could fingerprint your system and discover information.

**Comment by MontoyaAndres** [comment] 2021-01-16 13:35
@undefobj  Oh, makes a lot of sense, I didn't consider it in that way... Maybe I need to read more the docs and avoid this kind of things 😅

**Comment by MontoyaAndres** [comment] 2021-01-19 02:27
Thanks for helping me @attilah @undefobj :)
