### ISSUE TITLE
Repeated merge conflicts due to multi-env workflow

### ISSUE THREAD

**Issue by lon9man** [aws-amplify/amplify-cli#7397] opened 2021-05-25 12:26 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

latest

### What operating system are you using?

Ubuntu

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

issue [1850](https://github.com/aws-amplify/amplify-cli/issues/1850) was closed after 2 years, but WITHOUT any applicable solution.
AWS Team, maybe it is time for some comments?

### Expected behavior

the same as [1850](https://github.com/aws-amplify/amplify-cli/issues/1850)

### Reproduction steps

the same as [1850](https://github.com/aws-amplify/amplify-cli/issues/1850)

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment] 2021-06-04 16:28
Hey @lon9man :wave: thanks for raising this. For more context, what kind of changes were made on the other branch that was merged in (adding/removing specific resources, altering resources, etc.)?

**Comment by lon9man** [comment] 2021-06-07 10:11
@josefaidt i don't remember concrete start point, after which it has started. 
but general steps were:
1. create several environments (`master/dev/local`)
2. develop new functionality (adding/removing specific resources, altering resources, etc.) saying on `local`-env
3. merge changes into `dev`-env 
and so on

**Comment by josefaidt** [comment] 2021-06-07 14:42
@lon9man thanks for the information. I was not able to reproduce it after doing a few changes but I will try again with more adjustments and a third environment.

**Comment by josefaidt** [comment] 2021-06-09 20:46
Hey @lon9man I'm still looking into this given there are others that have similar issues, but in the mean time what files are you seeing conflicts in? Is this affecting any files in particular or sort of scattered throughout the amplify folder?

**Comment by lon9man** [comment] 2021-06-11 10:07
@josefaidt my problem is the same as described in the first post on https://github.com/aws-amplify/amplify-cli/issues/1850

![image](https://user-images.githubusercontent.com/10497794/121669825-6bb75380-cab5-11eb-8454-d3efe136a6e3.png)

> but in the mean time what files are you seeing conflicts in? Is this affecting any files in particular or sort of scattered throughout the amplify folder?

only amplify-folder and only on lambda's related cloudformation-templates (maybe it is also related to other parts not only lambda, but i didn't use it)

**Comment by josefaidt** [comment] 2021-06-11 15:45
Thank you for the information @lon9man to clarify, what version of the CLI are you using? This key was moved out of the function's cloudformation template and I am currently seeing it populate in `amplify/team-provider-info.json` to mitigate this issue. In your function's cloudformation template do you see the following?

```json
"Resources": {
    "LambdaFunction": {
      "Type": "AWS::Lambda::Function",
      "Metadata": {
        "aws:asset:path": "./src",
        "aws:asset:property": "Code"
      },
      "Properties": {
        "Code": {
          "S3Bucket": {
            "Ref": "deploymentBucketName"
          },
          "S3Key": {
            "Ref": "s3Key"
          }
        },
```

This `deploymentBucketName` can be found in the team provider info file at `<env-name>.categories.function.<function-name>.deploymentBucketName`

**Comment by josefaidt** [comment] 2021-06-28 16:36
Closing issue, @lon9man if you are still experiencing this issue please reply back/comment and we can re-open for further investigation

**Closed by josefaidt** 2021-06-28 16:36 UTC
Labels: pending-response, pending-triage, platform
