### ISSUE TITLE
amplify mock 'failed to fetch' query 

### ISSUE THREAD

**Issue by mdegrees** [aws-amplify/amplify-cli#4240] opened 2020-05-12 19:30 UTC
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Running a query that returns a ~12kb object takes more than 2 minutes to resolve and terminated with 'failed to fetch`. The query is run locally with amplify mock and the resolver is a lambda function. 
When pushing the api and running the query via AppSync console the problem disappears. 

**Amplify CLI Version**
4.19.0

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
MacOs Mojave
 - Node Version. You can use `node -v` to check the node version on your system
v12.10.0

**Additional context**

**Comment by SwaySway** [comment] 2020-05-15 17:16
@mdegrees
A few questions here
- Are you seeing this error on the browser?
- Is this a full mock? (Mocking the API and the lambda function)
- Could you provide a minimal schema and function so that we can try reproduce this issue?

**Comment by kaustavghosh06** [comment] 2020-08-14 02:00
The issue is fixed with CLI version > 4.26.0. Reference issue #4625

**Closed by kaustavghosh06** 2020-08-14 02:00 UTC
Labels: mock, pending-response, pending-triage
