### ISSUE TITLE
No Google Provider added to Identity pool

### ISSUE THREAD

**Issue by hysuki** [aws-amplify/amplify-cli#6844] opened 2021-03-09 20:49 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v15.11.0

### Amplify CLI Version

4.45.0

### What operating system are you using?

Mac

### Amplify Categories

auth

### Amplify Commands

add

### Describe the bug

To create a new project and add authentication, 'amplify add auth' -> 'Manual configuration' -> 'User Sign-Up, Sign-In, connected with AWS IAM controls' entered '3rd party authentication providers', but only Facebook was added to the provider and Google was not created.

![스크린샷 2021-03-10 오전 5 40 12](https://user-images.githubusercontent.com/35303552/110535236-5d2e6880-8163-11eb-99bb-d31a29f8c689.png)

### Expected behavior

add Google client id  to Authentication providers

![스크린샷 2021-03-10 오전 5 41 09](https://user-images.githubusercontent.com/35303552/110535280-68819400-8163-11eb-8075-47b13c381244.png)

### Reproduction steps

1. amplify init
2. amplify add auth
```
Using service: Cognito, provided by: awscloudformation
 
 The current configured provider is Amazon Cognito. 
 
 Do you want to use the default authentication and security configuration? Manual configuration
 Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AWS IAM controls (Enables per-user Storage features for ima
ges or other content, Analytics, and more)
 Please provide a friendly name for your resource that will be used to label this category in the project: airwith
 Please enter a name for your identity pool. airwith_identity_pool
 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) No
 Do you want to enable 3rd party authentication providers in your identity pool? Yes
 Select the third party identity providers you want to configure for your identity pool: Facebook, Google
  
 You've opted to allow users to authenticate via Facebook.  If you haven't already, you'll need to go to https://developers.facebook.com and create an App ID. 
 
 Enter your Facebook App ID for your identity pool:  xxxxxxxxxxxxxxxxxxxxx
  
 You've opted to allow users to authenticate via Google.  If you haven't already, you'll need to go to https://developers.google.com/identity and create an App ID. 
 
 Enter your Google Web Client ID for your identity pool:  xxxxxxxxxxxxxxxxxxxxx
 Please provide a name for your user pool: airwith_user_pool
 Warning: you will not be able to edit these selections. 
 How do you want users to be able to sign in? Email or Phone Number
 Do you want to add User Pool Groups? Yes
? Provide a name for your user pool group: traveler
? Do you want to add another User Pool Group Yes
? Provide a name for your user pool group: partner
? Do you want to add another User Pool Group Yes
? Provide a name for your user pool group: company
? Do you want to add another User Pool Group Yes
? Provide a name for your user pool group: manager
? Do you want to add another User Pool Group No
✔ Sort the user pool groups in order of preference · traveler, partner, company, manager
 Do you want to add an admin queries API? No
 Multifactor authentication (MFA) user login options: OPTIONAL (Individual users can use MFA)
 For user login, select the MFA types: SMS Text Message
 Please specify an SMS authentication message: Your authentication code is {####}
 Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
 Please specify an email verification subject: Your verification code
 Please specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? No
 Warning: you will not be able to edit these selections. 
 What attributes are required for signing up? Email
 Specify the app's refresh token expiration period (in days): 365
 Do you want to specify the user attributes this app can read and write? Yes
 Specify read attributes: Address, Birthdate, Email, Family Name, Gender, Locale, Given Name, Picture
 Specify write attributes: Address, Birthdate, Family Name, Gender, Locale, Given Name, Picture
 Do you want to enable any of the following capabilities? Email Verification Link with Redirect, Add User to Group
 Do you want to use an OAuth flow? Yes
 What domain name prefix do you want to use? airwith
 Enter your redirect signin URI: airwith://callback/
? Do you want to add another redirect signin URI No
 Enter your redirect signout URI: airwith://signout/
? Do you want to add another redirect signout URI No
 Select the OAuth scopes enabled for this project. Phone, Email, OpenID, Profile, aws.cognito.signin.user.admin
 Select the social providers you want to configure for your user pool: Facebook, Google
  
 You've opted to allow users to authenticate via Facebook.  If you haven't already, you'll need to go to https://developers.facebook.com and create an App ID. 
 
 Enter your Facebook App ID for your OAuth flow:  xxxxxxxxxxxxxxxxxxxxx
 Enter your Facebook App Secret for your OAuth flow:  xxxxxxxxxxxxxxxxxxxxx
  
 You've opted to allow users to authenticate via Google.  If you haven't already, you'll need to go to https://developers.google.com/identity and create an App ID. 
 
 Enter your Google Web Client ID for your OAuth flow:  xxxxxxxxxxxxxxxxxxxxx
 Enter your Google Web Client Secret for your OAuth flow:  xxxxxxxxxxxxxxxxxxxxx
? Do you want to configure Lambda Triggers for Cognito? Yes
? Which triggers do you want to enable for Cognito Custom Message, Post Authentication, Post Confirmation, Pre Sign-up
? What functionality do you want to use for Custom Message Send Account Confirmation Link w/ Redirect
? What functionality do you want to use for Post Authentication Create your own module
? What functionality do you want to use for Post Confirmation Add User To Group, Create your own module
? What functionality do you want to use for Pre Sign-up Create your own module
? Enter the URL that your users will be redirected to upon account confirmation: https://airwith.me/
? Enter the subject for your custom account confirmation email: verify email
? Enter the body text for your custom account confirmation email (this will appear before the link URL): verify link
Successfully added resource airwithCustomMessage locally.

Next steps:
Check out sample function code generated in <project-dir>/amplify/backend/function/airwithCustomMessage/src
"amplify function build" builds all of your functions currently in the project
"amplify mock function <functionName>" runs your function locally
"amplify push" builds all of your local backend resources and provisions them in the cloud
"amplify publish" builds all of your local backend and front-end resources (if you added hosting category) and provisions them in the cloud
Successfully added the Lambda function locally
? Do you want to edit your verification-link function now? No
Successfully added resource airwithPostAuthentication locally.

Next steps:
Check out sample function code generated in <project-dir>/amplify/backend/function/airwithPostAuthentication/src
"amplify function build" builds all of your functions currently in the project
"amplify mock function <functionName>" runs your function locally
"amplify push" builds all of your local backend resources and provisions them in the cloud
"amplify publish" builds all of your local backend and front-end resources (if you added hosting category) and provisions them in the cloud
Successfully added the Lambda function locally
? Do you want to edit your custom function now? No
? Enter the name of the group to which users will be added. traveler
Successfully added resource airwithPostConfirmation locally.

Next steps:
Check out sample function code generated in <project-dir>/amplify/backend/function/airwithPostConfirmation/src
"amplify function build" builds all of your functions currently in the project
"amplify mock function <functionName>" runs your function locally
"amplify push" builds all of your local backend resources and provisions them in the cloud
"amplify publish" builds all of your local backend and front-end resources (if you added hosting category) and provisions them in the cloud
Successfully added the Lambda function locally
? Do you want to edit your add-to-group function now? No
? Do you want to edit your custom function now? No
Successfully added resource airwithPreSignup locally.

Next steps:
Check out sample function code generated in <project-dir>/amplify/backend/function/airwithPreSignup/src
"amplify function build" builds all of your functions currently in the project
"amplify mock function <functionName>" runs your function locally
"amplify push" builds all of your local backend resources and provisions them in the cloud
"amplify publish" builds all of your local backend and front-end resources (if you added hosting category) and provisions them in the cloud
Successfully added the Lambda function locally
? Do you want to edit your custom function now? No
Successfully added auth resource airwith locally

Some next steps:
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud
```

### Log output

```
2021-03-09T20:09:17.531Z|info : amplify add auth  
2021-03-09T20:15:48.812Z|info : amplify push core  {"yes":true}
2021-03-09T20:15:56.692Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-03-09T20:15:56.693Z|info : amplify-provider-awscloudformation.system-config-manager.makeFileOwnerReadWrite(["/Users/code/.aws/config"])
2021-03-09T20:15:56.694Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1","output":"json"}])
2021-03-09T20:15:56.694Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-03-09T20:15:56.694Z|info : amplify-provider-awscloudformation.system-config-manager.makeFileOwnerReadWrite(["/Users/code/.aws/credentials"])
2021-03-09T20:15:56.702Z|info : amplify-provider-awscloudformation.zip-util.downloadZip.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip"},null])
2021-03-09T20:15:56.704Z|info : amplify-provider-awscloudformation.aws-s3.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]ify-[***]ith-[***]od-[***]42-[***]ment"}])
2021-03-09T20:15:57.597Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-03-09T20:15:57.597Z|info : amplify-provider-awscloudformation.system-config-manager.makeFileOwnerReadWrite(["/Users/code/.aws/config"])
2021-03-09T20:15:57.597Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1","output":"json"}])
2021-03-09T20:15:57.597Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-03-09T20:15:57.597Z|info : amplify-provider-awscloudformation.system-config-manager.makeFileOwnerReadWrite(["/Users/code/.aws/credentials"])
2021-03-09T20:15:57.602Z|info : amplify-provider-awscloudformation.initialize-env.run.cfn.updateamplifyMetaFileWithStackOutputs([{"StackName":"[***]ify-[***]ith-[***]od-[***]42"}])
2021-03-09T20:15:58.562Z|info : amplify-provider-awscloudformation.aws-s3.s3.getFile([{"Key":"[***]ify-[***]json","Bucket":"[***]ify-[***]ith-[***]od-[***]42-[***]ment"}])
2021-03-09T20:16:03.069Z|info : amplify-provider-awscloudformation.push-resources.packageResources.s3.uploadFile([{"Key":"[***]ify-[***]lds/[***]mMessage-[***]48346946-[***].zip"}])
2021-03-09T20:16:03.075Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ify-[***]lds/[***]mMessage-[***]48346946-[***].zip","Bucket":"[***]ify-[***]ith-[***]od-[***]42-[***]ment"}])
2021-03-09T20:16:03.086Z|info : amplify-provider-awscloudformation.push-resources.packageResources.s3.uploadFile([{"Key":"[***]ify-[***]lds/[***]eSignup-[***]65476261-[***].zip"}])
2021-03-09T20:16:03.087Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ify-[***]lds/[***]eSignup-[***]65476261-[***].zip","Bucket":"[***]ify-[***]ith-[***]od-[***]42-[***]ment"}])
2021-03-09T20:16:03.098Z|info : amplify-provider-awscloudformation.push-resources.packageResources.s3.uploadFile([{"Key":"[***]ify-[***]lds/[***]entication-[***]6f5a2b4f-[***].zip"}])
2021-03-09T20:16:03.098Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ify-[***]lds/[***]entication-[***]6f5a2b4f-[***].zip","Bucket":"[***]ify-[***]ith-[***]od-[***]42-[***]ment"}])
2021-03-09T20:16:03.227Z|info : amplify-provider-awscloudformation.push-resources.packageResources.s3.uploadFile([{"Key":"[***]ify-[***]lds/[***]nfirmation-[***]4c2f6f47-[***].zip"}])
2021-03-09T20:16:03.228Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ify-[***]lds/[***]nfirmation-[***]4c2f6f47-[***].zip","Bucket":"[***]ify-[***]ith-[***]od-[***]42-[***]ment"}])
2021-03-09T20:16:06.870Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ify-[***]fn-[***]ates/[***]tion/[***]mMessage-[***]mation-[***]e.json","Bucket":"[***]ify-[***]ith-[***]od-[***]42-[***]ment"}])
2021-03-09T20:16:06.872Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ify-[***]fn-[***]ates/[***]tion/[***]entication-[***]mation-[***]e.json","Bucket":"[***]ify-[***]ith-[***]od-[***]42-[***]ment"}])
2021-03-09T20:16:06.874Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ify-[***]fn-[***]ates/[***]tion/[***]nfirmation-[***]mation-[***]e.json","Bucket":"[***]ify-[***]ith-[***]od-[***]42-[***]ment"}])
2021-03-09T20:16:06.875Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ify-[***]fn-[***]ates/[***]tion/[***]eSignup-[***]mation-[***]e.json","Bucket":"[***]ify-[***]ith-[***]od-[***]42-[***]ment"}])
2021-03-09T20:16:06.877Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ify-[***]fn-[***]ates/[***]th/[***]e.json","Bucket":"[***]ify-[***]ith-[***]od-[***]42-[***]ment"}])
2021-03-09T20:16:06.879Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ify-[***]fn-[***]ates/[***]th/[***]ith-[***]mation-[***]e.yml","Bucket":"[***]ify-[***]ith-[***]od-[***]42-[***]ment"}])
2021-03-09T20:16:10.132Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-03-09T20:16:10.132Z|info : amplify-provider-awscloudformation.system-config-manager.makeFileOwnerReadWrite(["/Users/code/.aws/config"])
2021-03-09T20:16:10.133Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1","output":"json"}])
2021-03-09T20:16:10.133Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-03-09T20:16:10.133Z|info : amplify-provider-awscloudformation.system-config-manager.makeFileOwnerReadWrite(["/Users/code/.aws/credentials"])
2021-03-09T20:16:10.134Z|info : amplify-provider-awscloudformation.push-resources.updateCloudFormationNestedStack(["/Users/code/Workspace/airwith/amplify/amplify/backend/awscloudformation","/Users/code/Workspace/airwith/amplify/amplify/backend/awscloudformation/nested-cloudformation-stack.yml"])
2021-03-09T20:16:10.138Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ted-[***]mation-[***].yml","Bucket":"[***]ify-[***]ith-[***]od-[***]42-[***]ment"}])
2021-03-09T20:21:56.537Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-03-09T20:21:56.539Z|info : amplify-provider-awscloudformation.system-config-manager.makeFileOwnerReadWrite(["/Users/code/.aws/config"])
2021-03-09T20:21:56.541Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1","output":"json"}])
2021-03-09T20:21:56.541Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-03-09T20:21:56.541Z|info : amplify-provider-awscloudformation.system-config-manager.makeFileOwnerReadWrite(["/Users/code/.aws/credentials"])
2021-03-09T20:22:00.432Z|info : amplify-provider-awscloudformation.push-resources.storeCurrentcoudBackend.s3.uploadFile([{"Key":"[***]rent-[***]ud-[***]d.zip"}])
2021-03-09T20:22:00.433Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]ify-[***]ith-[***]od-[***]42-[***]ment"}])
2021-03-09T20:22:02.738Z|info : amplify-provider-awscloudformation.amplify-service-manager.s3.uploadFile([{"Key":"[***]ify-[***]json"}])
2021-03-09T20:22:02.739Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ify-[***]json","Bucket":"[***]ify-[***]ith-[***]od-[***]42-[***]ment"}])
2021-03-09T20:22:04.251Z|info : amplify-provider-awscloudformation.amplify-service-manager.s3.uploadFile([{"Key":"[***]end-[***].json"}])
2021-03-09T20:22:04.252Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]end-[***].json","Bucket":"[***]ify-[***]ith-[***]od-[***]42-[***]ment"}])
```

**Comment by attilah** [comment] 2021-03-09 23:34
@hysuki I was not able to reproduce this issue scenarios like this are covered in our e2e tests as well, so at this point it is possible that something was different in your user inputs. Going through the same flow that you pasted everything was working correctly here. As you picked OAuth and Federated login as well, you have 3 checkpoints you can check, one is what you also sent in. For federated logins Identity Pool configuration can be checked:

![image](https://user-images.githubusercontent.com/230432/110552617-87910f00-80ec-11eb-8d1b-3b8f4aea2d1f.png)

Also in the configuration of the IDP you can see the Facebook and Google+ Application Ids you supplied:

![image](https://user-images.githubusercontent.com/230432/110552576-7811c600-80ec-11eb-991f-18580a99f797.png)

For OAuth login, the User Pool can be checked, notice the checkmarks in the picture:

![image](https://user-images.githubusercontent.com/230432/110552653-92e43a80-80ec-11eb-93b1-b24ee414c5f0.png)

I'm closing the issue as it is a no repro on my end if you think this is closed in an error provide the exact repro steps that is different from the ones above to be able to resolve the issue.

**Closed by attilah** 2021-03-09 23:34 UTC
Labels: auth, not-reproducable
