### ISSUE TITLE
No option of ap-east-1 when specifying the AWS Region in amplify configure

### ISSUE THREAD

**Issue by williamkhshea** [aws-amplify/amplify-cli#10835] opened 2022-08-02 19:49 UTC
> **Note**: If your question is regarding the AWS Amplify Console service, please log it in the
> [AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
Usage

**Amplify CLI Version**
9.2.0

You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**
Amplify CLI

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**
I was prompted to select the AWS Region in amplify configure
<img width="304" alt="Screenshot 2022-08-03 at 3 47 54 AM" src="https://user-images.githubusercontent.com/4775489/182460706-a5ee4248-9373-4da3-8e47-2b3f9eaa3838.png">

I want to select ap-east-1 but the option is not in the list.

**Comment by josefaidt** [comment] 2022-08-02 21:26
Hey @williamkhshea :wave: thanks for raising this! Marking as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/6727, please subscribe to the linked issue for further updates in regards to supporting this region

**Closed by josefaidt** 2022-08-02 21:26 UTC
Labels: question
