### ISSUE TITLE
Cannot build project on remote: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by OlgaMaslova** [aws-amplify/amplify-cli#11724] opened 2023-01-06 07:48 UTC
### Amplify CLI Version

10.6.0

### Question

Hello!
My project is no longer built in amplify console (without any modifications of the backend). In local I can perform 'amplify push' without problem.
I have the following error without any further precisions:
`2023-01-06T07:28:02.285Z [WARNING]: ✖ There was an error initializing your environment.
2023-01-06T07:28:02.286Z [INFO]: 🛑 The "path" argument must be of type string. Received undefined
2023-01-06T07:28:02.286Z [INFO]: Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/`

Any suggestions?
Thanks!

**Comment by josefaidt** [comment] 2023-01-06 16:52
Hey @OlgaMaslova :wave: thanks for raising this! As we begin to look at this in more depth would you mind posting the project ID output from `amplify diagnose --send-report`? Did this issue occur after upgrading the CLI?

**Comment by OlgaMaslova** [comment] 2023-01-06 18:33
Hi @josefaidt 
Here is the report.
[report-1673029833590.zip](https://github.com/aws-amplify/amplify-cli/files/10362279/report-1673029833590.zip)

I think I perfromed `amplify upgrade `in local. I tried to `amplify pull `and then push on gitlab to trigger th build in remote. And it fails with the same error. As I said no errors if I perform `amplify push`.

**Comment by josefaidt** [comment] 2023-01-09 18:55
Hey @OlgaMaslova thanks for clarifying! To clarify further would you mind posting the following information:

- project ID output from `amplify diagnose --send-report`
- Amplify App ID
- region in which the project is deployed

**Comment by OlgaMaslova** [comment] 2023-01-10 07:21
Hi @josefaidt ,
here it is:
Project Identifier: 093af84b3c7dec95a47086576335b703
App ID: do5lfh5kuwuas
Region: eu-west-1

Thanks!

**Comment by OlgaMaslova** [comment] 2023-01-11 09:38
Hi @josefaidt 
Some new observations from my part. I upgraded amplify to 10.6.1. Once I do `amplify push` locally and immediatly push to git => then I have no error.
However without local  `amplify push` even if I change only one file (css, example) and commit/push => I have the same error.

I a m looking forward your advice because our deploiement is strongly affected by this problem. Many thanks!

**Comment by josefaidt** [comment] 2023-01-11 18:19
Hey @OlgaMaslova I was doing a bit of digging on this issue and I appreciate the follow-up with those details! Can you confirm `amplify/.config/project-config.json` contains a `providers` array with `awscloudformation` in it? 

```json
{
  "projectName": "11723",
  "version": "3.1",
  "frontend": "javascript",
  "javascript": {
    "framework": "none",
    "config": {
      "SourceDir": "src",
      "DistributionDir": "dist",
      "BuildCommand": "npm run-script build",
      "StartCommand": "npm run-script start"
    }
  },
  "providers": [
    "awscloudformation"
  ]
}
```

**Comment by josefaidt** [comment] 2023-01-11 19:33
Hey @OlgaMaslova thank you for confirming! Would you be open to sending a zip archive of your project's `amplify/` to amplify-cli@amazon.com? If so, please be sure to omit any sensitive information. Additionally, are you able to reproduce this issue locally be executing `amplify init --envName <current-env-name> --yes`?

**Comment by OlgaMaslova** [comment] 2023-01-12 08:22
Hey @josefaidt 
I tried reproducing with `amplify init`, all the same.
Here is the archive. Thanks for looking!
[amplify.zip](https://github.com/aws-amplify/amplify-cli/files/10399524/amplify.zip)

**Comment by OlgaMaslova** [comment] 2023-01-12 15:50
Hey @josefaidt, 
Another observation. I created new git branch and  I created a new backend environment with `amplify add env` reusing existing amplify folder.
Still same problem with the new environment and another git branch.

**Comment by josefaidt** [comment] 2023-01-12 21:34
Hey @OlgaMaslova thanks for sending that over! Unfortunately I was not able to readily reproduce this issue using the same project files. Would you mind adding the  `AMPLIFY_ENABLE_DEBUG_OUTPUT` environment variable to Amplify Hosting and re-attempt the build?

**Comment by OlgaMaslova** [comment] 2023-01-13 07:35
Hey @josefaidt ,

Here is the output:
`✖ There was an error initializing your environment.
2023-01-13T07:26:11.520Z [INFO]: 🛑 The "path" argument must be of type string. Received undefined
2023-01-13T07:26:11.520Z [INFO]: Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
                                 DeploymentFault: The "path" argument must be of type string. Received undefined
                                 at Object.run (/snapshot/repo/build/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:447:11)
                                 at runMicrotasks (<anonymous>)
                                 at processTicksAndRejections (internal/process/task_queues.js:95:5)
                                 The "path" argument must be of type string. Received undefined
                                 TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
                                 at new NodeError (internal/errors.js:322:7)
                                 at validateString (internal/validators.js:124:11)
                                 at Object.join (path.js:1148:7)
                                 at generateTransformerOptions (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-api/lib/graphql-transformer/transformer-options-v2.js:69:47)
                                 at runMicrotasks (<anonymous>)
                                 at processTicksAndRejections (internal/process/task_queues.js:95:5)
                                 at async transformGraphQLSchemaV2 (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-api/lib/graphql-transformer/transform-graphql-schema-v2.js:105:25)
                                 at async Object.run (/snapshot/repo/build/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:217:5)`.

Hope, it helps!

**Comment by josefaidt** [comment] 2023-01-14 00:33
Hey @OlgaMaslova yes thank you this is incredibly helpful!! While I investigate this a bit further can you verify whether running `amplify pull` locally changes any of the files in the `amplify/` directory? Since this is failing in the `init` phase I am curious if it is pulling contents from your project's deployment bucket that are causing the issue

**Comment by OlgaMaslova** [comment] 2023-01-16 07:46
Hey @josefaidt 
I thought `amplify pull `would fix the problem just when I had just found this bug. But apart of `team-provider-info.json` no changes.

**Comment by josefaidt** [comment] 2023-01-17 23:57
Hey @OlgaMaslova what sort of changes were applied to the `team-provider-info.json`? For what it's worth it appears to be failing on one of the few `.join()` calls here https://github.com/aws-amplify/amplify-category-api/blob/main/packages/amplify-category-api/src/graphql-transformer/transformer-options-v2.ts#L91

**Comment by josefaidt** [comment] 2023-01-17 23:58
Can you download the `#current-cloud-backend.zip` from your project's deployment bucket and verify the integrity of the `team-provider-info.json` file if you are unable to reproduce after pulling?

**Comment by OlgaMaslova** [comment] 2023-01-18 08:33
Hey @josefaidt 
When I perform `amplify pull` 3 lambda functions change their s3Key in `team-provider-info.json`. 

Concerning the `#current-cloud-backend.zip`, how can I verify the integrity of `team-provider-info.json` (local or pulled)?

Thanks!

**Comment by josefaidt** [comment] 2023-01-18 23:28
Hey @OlgaMaslova I would be interested in seeing whether there are any significant changes to the resources' structure in the `team-provider-info.json` comparing the copy from the zip archive to the copy you currently have locally

**Comment by OlgaMaslova** [comment] 2023-01-19 07:57
Hey @josefaidt , everything seems in order when comparing.
For unblock the situation I had to rollback the whole application to transformer v1 (to the state of 2 weeks before) and now it works back. (I still have the not working copy of the environment, so we can continue tests...)
Seems that the problem appeared with the migration which I had to perform manually.

**Comment by josefaidt** [comment] 2023-01-19 22:58
Hey @OlgaMaslova :wave: thanks for clarifying again! I was able to reproduce this after noticing `amplify/backend/api/<api-name>/cli-inputs.json` was missing. Here are the steps I followed to reproduce:

1. `amplify init -y`
2. `amplify add api` > doesn't matter, just take defaults
3. `amplify push -y` (send all this up to current-cloud-backend)
4. create a git repo, push `git init; gh repo create --source . --private`
5. add hosting with `amplify add hosting` > connect your git repo
6. (let hosting build)
7. locally, delete `cli-inputs.json` from the api directory
8. `amplify push -y` (send this up to current-cloud-backend)
9. `git push` to trigger hosting build
10. observe error

To mitigate, can you try running `amplify migrate api` again to regenerate this file and manually push with `amplify push -y`? Afterwards, subsequent pushes to git should be successful 🙂

**Comment by OlgaMaslova** [comment] 2023-01-20 10:25
Hey @josefaidt ,
That was it! It works now. Thanks a lot!

**Comment by josefaidt** [comment] 2023-01-20 16:52
Glad to hear it @OlgaMaslova ! I'll close this out for now but if something comes up again please don't hesitate to reach out!

**Closed by josefaidt** 2023-01-20 16:52 UTC
Labels: question, investigating, pending-triage
