### ISSUE TITLE
API_xxx_GRAPHQLAPIENDPOINTOUTPUT is returning apixxxGraphQLAPIEndpointOutput

### ISSUE THREAD

**Issue by GeorgeBellTMH** [aws-amplify/amplify-cli#6489] opened 2021-01-27 09:13 UTC
Please re-open #3941 as it is still occurring in 4.41.2.

**Comment by avlonder** [comment] 2021-01-27 14:16
Duplicate of #6484

**Comment by ammarkarachi** [comment] 2021-01-27 16:54
@GeorgeBellTMH Opened it and looking into it

**Closed by ammarkarachi** 2021-01-27 16:54 UTC
