### ISSUE TITLE
sortField update does not push to the cloud

### ISSUE THREAD

**Issue by stanleycyang** [aws-amplify/amplify-cli#902] opened 2019-02-20 05:55 UTC
**Describe the bug**

I have a simple User and Notification model:

```
type Notification
  @model
{
  id: ID!
  recipient: User! @connection(name: "UserNotifications")
  sender: User! @connection
  message: String!
  createdAt: AWSDateTime
}

type User
  @model
{
  id: ID!
  givenName: String
  familyName: String
  email: AWSEmail
  notifications: [Notification] @connection(name: "UserNotifications", sortField: "createdAt")
  createdAt: AWSDateTime
}
```

When I added the sortField, it threw an error and refused to update:

```
UPDATE_FAILED   Notification AWS::CloudFormation::Stack Tue Feb 19 2019 16:43:20 GMT-0800 (PST) Embedded stack arn:aws:cloudformation:us-west-2:281461261113:stack/topsheet-20190213165923-apitopsheet-8KPKP6ACAH6H-Notification-BV4PI3P1RRGT/6c407f50-2ff5-11e9-b90a-02c3ece5f9fa was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to update: [NotificationTable, GetNotificationResolver, UpdateNotificationResolver, CreateNotificationResolver, ListNotificationResolver, DeleteNotificationResolver].
```

**To Reproduce**
1. Create the same models
2. Push to the cloud
3. See error message

**Expected behavior**
The sortField should be easily updated

**Desktop (please complete the following information):**
 - Mac

**Comment by chris-merapar** [comment] 2019-02-20 11:48
I have the same issue using CLI 1.1.2. Changing any property of the Connection annotation has the same effect. The root cause is that you cannot update a GSI on a DynamoDB table after creation, you have to make a new one with a unique name. Another complication is that you cannot create a GSI on a DynamoDB table whilst an existing one is deleting.

**Comment by stanleycyang** [comment] 2019-02-20 19:29
@chris-merapar I thought you are able to update the GSI on the DynamoDB tables now?

**Comment by mikeparisstuff** [comment] 2019-02-21 21:45
When starting from a brand new project, I was able to create the schema above without a problem. If you are having problems because you previously pushed a version that had @connection but no *sortField*, I would suggest trying to remove the @connection entirely (thus removing the GSI), pushing, and then re-adding the updated @connection with the *sortField* and push again.

E.G. Push with

```graphql
type Notification
  @model
{
  id: ID!
  recipient: User!
  sender: User! @connection
  message: String!
  createdAt: AWSDateTime
}

type User
  @model
{
  id: ID!
  givenName: String
  familyName: String
  email: AWSEmail
  notifications: [Notification]
  createdAt: AWSDateTime
}
```

and then again with

```graphql
type Notification
  @model
{
  id: ID!
  recipient: User! @connection(name: "UserNotifications")
  sender: User! @connection
  message: String!
  createdAt: AWSDateTime
}

type User
  @model
{
  id: ID!
  givenName: String
  familyName: String
  email: AWSEmail
  notifications: [Notification] @connection(name: "UserNotifications", sortField: "createdAt")
  createdAt: AWSDateTime
}
```

Any existing data included in the table will be re-indexed into the GSI so you should be able to query it as usual after the second push.

**Comment by chris-merapar** [comment] 2019-02-22 16:33
This workaround could be ok for a dev sandbox env but won't work in a production env. I would have to remove the connection, then propagate a release through all envs (dev, test, UAT, prod etc), then make a new release with the new connection, which is is a lot of downtime.

**Comment by mikeparisstuff** [comment] 2019-03-08 21:42
@chris-merapar This is an unfortunate side effect of DynamoDB. We are working on an RFC that will be released to GitHub soon that provides users more control over the index structures that are placed on a table. With the new directives in place, you will be able to make these changes in a purely additive fashion such that you do not experience downtime. In this case, you would be able to add a new index with the new structure that you want and then configure the connection to use that new index. Once you have deployed the new index and connection, you could later remove the old index once it is no longer necessary.

**Comment by kaustavghosh06** [comment] 2019-05-30 05:32
We launched support for custom indexes today. You can find docs for the same out here - https://aws-amplify.github.io/docs/cli/graphql#key
Please let us know if you're still not able to solve your problem through this solution and we'll re-open this issue for you.

**Closed by kaustavghosh06** 2019-05-30 05:32 UTC
Labels: enhancement, graphql-transformer
