### ISSUE TITLE
Invalid instance type: c6g.xlarge.elasticsearch

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-cli#8572] opened 2021-10-27 01:27 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

https://docs.amplify.aws/cli/start/install/

### If applicable, what version of Node.js are you using?

N/A

### Amplify CLI Version

6.3.1

### What operating system are you using?

N/A

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

I just created a new environment and pushed to it for the first time and got:

```
Invalid instance type: c6g.xlarge.elasticsearch
```

THis is probably because of the change in elasticsearch, https://aws.amazon.com/opensearch-service/pricing/ if I use `c6g.xlarge.search` it will throw an error because of the allowed values, `amplify update api` does not seem to update the allowed values.

### Expected behavior

This should not happen.

### Reproduction steps

Read above.

### GraphQL schema(s)

N/A

### Log output

N/A

**Comment by aprilmintacpineda** [comment] 2021-11-09 23:11
So no fix for this yet?

**Comment by cjihrig** [comment] 2021-11-15 15:45
Sorry for the delay. We have received an update on this issue. The c6g instance type is only supported in [Elasticsearch 7.9 or later or any version of OpenSearch](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/supported-instance-types.html). Amplify will likely need to stop offering this instance type until we upgrade to a newer version of the search service.

**Comment by aprilmintacpineda** [comment] 2021-11-15 22:13
> Sorry for the delay. We have received an update on this issue. The c6g instance type is only supported in [Elasticsearch 7.9 or later or any version of OpenSearch](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/supported-instance-types.html). Amplify will likely need to stop offering this instance type until we upgrade to a newer version of the search service.

How do I handle this then? What do I put into the template? Because I'm going to create the production environment tomorrow for one of our clients

**Comment by aprilmintacpineda** [comment] 2021-11-16 08:49
@cjihrig hoping to get actionable items tomorrow as we need to have a production environment by Thursday. Thanks so much 🙏🏻

**Comment by johnpc** [comment] 2022-03-25 18:37
closing this as duplicate of https://github.com/aws-amplify/amplify-cli/issues/9956. track resolution of that ticket for a more thorough fix

**Closed by johnpc** 2022-03-25 18:37 UTC
Labels: bug, @searchable, p1
