### ISSUE TITLE
Cannot finish the build after amplify-cli version update

### ISSUE THREAD

**Issue by ssyuzev** [aws-amplify/amplify-cli#7198] opened 2021-04-28 09:08 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.15.3

### Amplify CLI Version

4.50.0

### What operating system are you using?

Mac

### Amplify Categories

auth, storage, function, api, analytics

### Amplify Commands

push

### Describe the bug

2021-04-28T08:12:36.659Z [INFO]: [0mTypeError: Cannot read property 'length' of undefined[0m
                                 [0m    at /usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/utils/consolidate-apigw-policies.ts:121:99[0m
                                 [0m    at Array.forEach (<anonymous>)[0m
                                 [0m    at ApiGatewayAuthStack.createPoliciesFromResources (/usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/utils/consolidate-apigw-policies.ts:120:13)[0m
                                 [0m    at /usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/utils/consolidate-apigw-policies.ts:94:16[0m
                                 [0m    at Array.forEach (<anonymous>)[0m
                                 [0m    at /usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/utils/consolidate-apigw-policies.ts:84:31[0m
                                 [0m    at Array.forEach (<anonymous>)[0m
                                 [0m    at new ApiGatewayAuthStack (/usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/utils/consolidate-apigw-policies.ts:62:23)[0m
                                 [0m    at createApiGatewayAuthResources (/usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/utils/consolidate-apigw-policies.ts:205:17)[0m
                                 [0m    at Object.consolidateApiGatewayPolicies (/usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/utils/consolidate-apigw-policies.ts:201:10)[0m
                                 [0m    at Object.createEnvLevelConstructs (/usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/utils/env-level-constructs.ts:22:5)[0m
                                 [0m    at runMicrotasks (<anonymous>)[0m
                                 [0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m
                                 [0m    at Object.run (/usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:97:5)[0m
2021-04-28T08:12:36.703Z [ERROR]: !!! Build failed
2021-04-28T08:12:36.704Z [ERROR]: !!! Non-Zero Exit Code detected
2021-04-28T08:12:36.704Z [INFO]: # Starting environment caching...
2021-04-28T08:12:36.704Z [INFO]: # Environment caching completed
Terminating logging...

### Expected behavior

Should finish the build without errors

### Reproduction steps

1. amplify push

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by cjihrig** [comment] 2021-04-28 11:34
Closing this as a duplicate of #7190. Please feel free to engage in that issue.

**Closed by cjihrig** 2021-04-28 11:34 UTC
