### ISSUE TITLE
Mock REST APIs locally

### ISSUE THREAD

**Issue by tobiasfeil** [aws-amplify/amplify-cli#4943] opened 2020-07-27 15:04 UTC
**Describe the solution you'd like**
I would like to mock REST APIs, not just GraphQL, locally.

**Describe alternatives you've considered**
Only mock the function locally and test the API only when it's pushed

**Comment by ammarkarachi** [comment] 2020-07-27 17:26
Hi @tobiasfeil, Is you Rest API backed by a Lambda function? You could always mock the Lambda function by using `amplify mock function <functionName>`

**Comment by tobiasfeil** [comment] 2020-07-28 06:49
Yes there's a Lambda behind it, that's true. I would just like to run the actual API to see the full scope of what it would look like in production and how it would handle different requests. But I understand if this is out of scope right now.

**Comment by ammarkarachi** [comment] 2020-07-29 18:07
@tobiasfeil we will look into the viability of mocking for rest api I will mark this as an enhancement.

**Comment by tobiasfeil** [comment] 2020-07-30 07:25
Thank you! This (and being able to secure REST APIs via access token) would be viable, since for now, for these two reasons, I've just decided to develop a REST API with SAM instead. It would be awesome to do all of this with Amplify.

**Comment by cjihrig** [comment] 2021-03-13 05:47
Closing as a duplicate of #3399

**Closed by cjihrig** 2021-03-13 05:47 UTC
Labels: enhancement, mock
