### ISSUE TITLE
`Error: xxxCustomMessage is present in amplify-meta.json` when `amplify auth update`

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#5674] opened 2020-10-23 04:32 UTC
**Describe the bug**
I ran `amplify auth update` twice, the second time I got an error:

```
Error: xxxCustomMessage is present in amplify-meta.json` when `amplify auth update
```

**Amplify CLI Version**
4.29.2

**To Reproduce**
```bash
# amplify add auth
# amplify push
amplify auth update
git reset --hard
amplify auth update
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Node Version: v14.11.0

**Comment by UnleashedMind** [comment] 2020-10-23 23:10
I'm not able to reproduce after I tested some simple cases. 
If you run `git status` before the first `amplify auth update`, what are the changed files not added yet? what are the staged changes not committed yet?
If you run `git add .` and then `git commit` before the first `amplify auth update`, do you still get the error? 

Amplify CLI is not directly integrated with the git CLI, so it's possible that `git reset --hard` put the project in a corrupt state, so be very careful when you running the CLIs together.

**Comment by yaquawa** [comment] 2020-10-25 10:08
@UnleashedMind Oh, I ran `amplify auth update` before the second `amplify auth update`, so files like `amplify-meta.json` has been generated already. Should I clear all the generated files(which listed in the `.gitignore`)?

**Comment by UnleashedMind** [comment] 2020-10-26 16:22
You don't need to remove any locally generated files, you just continue your development, the generated files are needed for the CLI to continue to function. 
For now in order to put your project back to a workable state, run `amplify pull --restore` first, and then continue your development,

**Comment by yaquawa** [comment] 2020-10-27 12:57
```
amplify pull --restore
```

@UnleashedMind Thanks for that tips, maybe this should on the docs too 🥳

**Comment by UnleashedMind** [comment] 2020-10-27 16:35
Here's the doc for the --restore flag: https://docs.amplify.aws/cli/teams/commands#pull-the-environment-from-the-cloud

I'm closing this issue now, feel free to open new ones if needed.

**Closed by UnleashedMind** 2020-10-27 16:35 UTC
Labels: auth, pending-response, question
