### ISSUE TITLE
[API] GraphQL update mutation doesn't work

### ISSUE THREAD

**Issue by Northshoot** [aws-amplify/amplify-cli#4765] opened 2020-07-07 21:26 UTC
**Describe the bug**
After creating an item, update mutation doesn't work and does not give any error.

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
 amplify -v
4.22.0

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

1. Create model
```gql
type Survey @model {
  id: ID!
  version: String!
  creator: String!
}
```
2. Inser data
```gql
mutation addSurvey{
  createSurvey(input:{
    creator: "Tom"
    version: "0.1"
  }){
    id
    creator
    version
  }
}
```
3. try to update data 

```gql
mutation us{
  updateSurvey(input:{
    id: "xxxxx"
    creator: "Updator"
    version:"0.2"
  }){
    id
    creator
    version
  }
}
```

**Expected behavior**
survey with id "xxxxx" will have creator "Updator" and version "0.2"
but the item is not updated

**Screenshots**
![2020-07-07_14-02-52](https://user-images.githubusercontent.com/7857361/86844970-ab7fea80-c05d-11ea-9c31-591b07531f36.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

Same behavior in console or JS

**Additional context**

**Comment by jhockett** [comment] 2020-07-07 22:29
Hi @Northshoot, I was not able to reproduce this issue on 4.23.0 or 4.22.0. The `us` mutation worked correctly for me.

What OS are you using? Which version of Node are you on?

**Comment by Northshoot** [comment] 2020-07-07 22:49
hum, I have deployed that on AWS. 
Upgraded to 4.23.0 and using node v10.16.0. Same issue. 
Have multiple models that do not update. Neither going to console or from JS. 

Is there a way to regenerate resolvers?

**Comment by jhockett** [comment] 2020-07-08 00:11
> Is there a way to regenerate resolvers?

`amplify api gql-compile` - See [docs](https://docs.amplify.aws/cli/graphql-transformer/resolvers#overwriting-resolvers).

Do you have custom resolvers for your api?

**Comment by Northshoot** [comment] 2020-07-08 00:18
I don't have custom resolvers and running the command made no changes. Still unclear whats going on.

**Comment by Northshoot** [comment] 2020-07-08 00:48
I enabled x-ray, and as you can see the resolvers are executed but do not change values.

![2020-07-07_17-47-29](https://user-images.githubusercontent.com/7857361/86860622-0cb5b700-c07a-11ea-9174-adf7e0f95471.png)

![2020-07-07_17-42-01](https://user-images.githubusercontent.com/7857361/86860634-117a6b00-c07a-11ea-8947-29d80efee3d0.png)

**Comment by Northshoot** [comment] 2020-07-08 01:06
I created new project and can confirm your experience that update works. Something went wrong during one of the updates. I noticed that NONE of the object can be updated. 

Is there a way to recover from this slip?

**Comment by jhockett** [comment] 2020-07-08 01:10
Are you able to remove the api and create a new one with your existing schema?

If so, make sure to backup your schema beforehand.

**Comment by Northshoot** [comment] 2020-07-08 01:12
that will delete database and I lose all the data?

**Comment by jhockett** [comment] 2020-07-08 01:14
Yes.

**Comment by Northshoot** [comment] 2020-07-08 01:19
Any other suggestions to debug what went wrong and fix it? Rather not have happen it again :)

**Comment by jhockett** [comment] 2020-07-08 01:26
Do you know what version of the CLI you used to create the api?

**Comment by Northshoot** [comment] 2020-07-08 01:33
I used 4.22.0.

**Comment by Northshoot** [comment] 2020-07-08 17:07
I had to delete the amplify and restart all. Would be great to have some disaster recovery documentation for backup and restore. 

Seems that this person had similar issue:
https://stackoverflow.com/questions/60232048/update-mutations-in-graphql-with-appsync

Feel free to close if needed. Thank you for your help @jhockett <3

**Comment by jhockett** [comment] 2020-07-08 21:48
Sorry to hear you had to do all that just to get to a clean state @Northshoot.

I'll bring your feedback to the team to see how we can best improve the docs for recovery scenarios. Closing for now, but please comment below if you experience this again and we will reopen the issue.

**Closed by jhockett** 2020-07-08 21:48 UTC
Labels: graphql-transformer

**Comment by Kozek** [comment] 2020-10-21 17:40
I'm facing the same issue with update mutations.

**Backend:**
- Api
- Auth
- Auth User Pools Groups

**Amplify CLI Version**
4.30.0

**Desktop:**
OS: MacOS Big Sur (Tested on Catalina before)
Node Version: v10.16.3

**Additional context**
I tried it with example schemas created by the amplify cli and even with more complex or other types of attributes.
The confusing thing is that the _version tag of the object increments in DynamoDB, what makes sense because the query is successful (Web console and Amplify API for iOS return no error) but the attributes don't change.

Between every new scheme I ran amplify remove api.  

I recognised that conflict detection with auto merge was enabled which may break something. (guess this is just blind hope) 
Trying this one until I have to completely delete amplify..

**Comment by Kozek** [comment] 2020-10-21 17:58
Well I'm happy that my blind hope worked (at least for a simple todo object) but that should be written somewhere in the docs.
After disabling conflict detection the DataStore DynamoDB table got removed, what I expected but that doesn't explain why the API is not merging the changes correctly or is that wanted for auto merge?
