### ISSUE TITLE
Pushing a new custom resolver returns "The specified key does not exist" and fails

### ISSUE THREAD

**Issue by biztems** [aws-amplify/amplify-cli#8323] opened 2021-09-30 16:45 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

16.2.0

### Amplify CLI Version

6.1.0

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

When pushing changes to CustomResources.json, I receive the following error:

CREATE_FAILED      QueryCustomQueryResolver AWS::AppSync::Resolver Thu Sep 30 2021 18:39:06 GMT+0200 (Central European Summer Time) The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: [cut]; S3 Extended Request ID: [cut]; Proxy: null)

UPDATE_FAILED               CustomResourcesjson                                               AWS::CloudFormation::Stack Thu Sep 30 2021 18:39:09 GMT+0200 (Central European Summer Time) Embedded stack arn:aws:cloudformation:eu-west-1:[cut]CustomResourcesjson[cut] was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to create: [QueryCustomQueryResolver].

UPDATE_FAILED               apiName                                    AWS::CloudFormation::Stack Thu Sep 30 2021 18:39:13 GMT+0200 (Central European Summer Time) Embedded stack arn:aws:cloudformation:eu-west-1:[cut]CustomResourcesjson[cut] was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to update: [CustomResourcesjson].

Removing the custom resolver lets the push work, but then the resolver does not work - at least from what I can gather from the guides, since I only get nulls from it.

I can see the vtl files correctly, in the correct path in S3.

### Expected behavior

The push should just work.

### Reproduction steps

Just added this under 

    "EmptyResource": {
      "Type": "Custom::EmptyResource",
      "Condition": "AlwaysFalse"
    },

in Resources.

    "QueryCustomQuerResolver": {
      "Type": "AWS::AppSync::Resolver",
      "Properties": {
        "ApiId": {
              "Ref": "AppSyncApiId"
        },
        "DataSourceName": "DataTable",
        "TypeName": "Query",
        "FieldName": "customQuery",
        "RequestMappingTemplateS3Location": {
          "Fn::Sub": [
              "s3://${S3DeploymentBucket}/${S3DeploymentRootKey}/resolvers/Query.customQuery.req.vtl",
            {
              "S3DeploymentBucket": {
                "Ref": "S3DeploymentBucket"
              },
              "S3DeploymentRootKey": {
                "Ref": "S3DeploymentRootKey"
              }
            }
          ]
        },
        "ResponseMappingTemplateS3Location": {
              "Fn::Sub": [
                  "s3://${S3DeploymentBucket}/${S3DeploymentRootKey}/resolvers/Query.customQuery.res.vtl",
                  {
                      "S3DeploymentBucket": {
                          "Ref": "S3DeploymentBucket"
                      },
                      "S3DeploymentRootKey": {
                          "Ref": "S3DeploymentRootKey"
                      }
                  }
              ]
        }
      }
    }

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Query {
  customQuery(value: String!): DataTable @aws_api_key @aws_iam
}

```

```graphql
# Put vtls below this line

--- Query.customQuery.res.vtl ---
{
  "version": "2018-05-29",
  "operation": "Query",
  "query" : {
    "expression": "value = :value",
      "expressionValues" : {
        ":value" : $util.dynamodb.toDynamoDBJson($context.arguments.value)
      }
  }
}

--- Query.customQuery.res.vtl ---
#if( $ctx.error )
$util.error($ctx.error.message, $ctx.error.type, $ctx.result)
#else
$util.toJson($ctx.result)
#end

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by biztems** [comment] 2021-10-01 11:38
Thanks to @renegoretzka we have found out that the issue was in the auth directives in the Query type in graphql.schema. Removing them and then pushing worked - I then re-added back in the auth directives and that push went okay as well.

Definitely a bug. The error, that only references S3, is also extremely confusing.

**Comment by josefaidt** [comment] 2021-10-05 17:35
Hey @biztems :wave: thanks for raising this! And I'm glad to hear you're back up and running despite the experience. I was not able to reproduce after mimicking the setup and took the following notes:

- tried using the `@auth` rules ran into this issue https://github.com/aws-amplify/amplify-cli/issues/5892
- removed auth rules and pushed with no auth successfully, then added the AppSync `@aws_api_key @aws_iam` and was able to push successfully
- created a new env and pushed with the following schema and was able to push successfully
   ```graphql
    type Todo @model {
      id: ID!
      name: String!
      description: String
    }

    type Query {
      myCustomQuery: [Todo] @aws_api_key @aws_iam
    }
   ```
- started second project and was able to successfully push the custom resolver

Do you also encounter this issue in a new environment?

**Comment by josefaidt** [comment] 2021-10-12 19:16
Hey @biztems just wanted to follow up to my previous message and see whether you were also experiencing this issue in new environments?

**Comment by biztems** [comment] 2021-10-13 14:15
Hi @josefaidt - sorry for the lack of reply. I haven't been able to find enough time yet to test with a new environment. Will try to do ASAP but from what I have seen with Amplify, most of the errors happen with a _very_ specific combination of things which is extremely difficult to reproduce at a later time.

**Comment by josefaidt** [comment] 2021-11-30 21:23
Hey @biztems wanted to follow up and see if you're still experiencing this issue?

**Comment by biztems** [comment] 2021-12-01 10:11
Hi @josefaidt , 

we couldn't reproduce it, even in subsequent projects. Nor it did reappear In the original project where we first saw this bug. It looks like it had to be a (rare?) combination of factors coming into play.

**Comment by josefaidt** [comment] 2021-12-01 15:21
Hey @biztems thanks for the reply. Interesting to hear it hasn't resurfaced past the initial occurrence. I'll close this issue for now as I was not able to reproduce, however if this issue resurfaces please reply back to this thread and we can re-open to investigate further 🙂

**Closed by josefaidt** 2021-12-01 15:21 UTC
Labels: pending-response, pending-triage, not-reproducible, @auth
