### ISSUE TITLE
auth headless is missing the following inputParameters googleAppIdUserPool, googleAppSecretUserPool

### ISSUE THREAD

**Issue by redjonzaci** [aws-amplify/amplify-cli#13499] opened 2023-12-21 17:15 UTC
### Amplify CLI Version

12.3.0

### Question

I went through the following issue: https://github.com/aws-amplify/amplify-cli/issues/9176 and the following docs: https://docs.amplify.aws/javascript/tools/cli/usage/headless/#headless-category-payloads,
but I don't understand how to utilize `amplify update auth --headless` in the CI/CD pipeline.
Currently, we just do `amplifyPush --simple` to build the backend. Where does that fit in?

**Comment by ykethan** [comment] 2023-12-21 18:13
Hey @redjonzaci, thank you for reaching out. Could you try adding the OAuth parameters as environment variables and rebuild on Amplify hosting , `AMPLIFY_GOOGLE_CLIENT_ID`, `AMPLIFY_GOOGLE_CLIENT_SECRET` environment variables are accessible by default within the Amplify console.
Please refer to the [documentation](https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html#amplify-console-environment-variables)
similar issue: https://github.com/aws-amplify/amplify-hosting/issues/2039#issuecomment-1132790185

**Comment by redjonzaci** [comment] 2023-12-21 18:16
Trying it now, but it seems like the repeated issue needs a documentation / error message update?

**Comment by redjonzaci** [comment] 2023-12-21 20:01
@ykethan it worked, thank you!

**Comment by ykethan** [comment] 2023-12-21 20:40
@redjonzaci glad to hear that, i am working on a reproduction for this behavior.


Note: https://github.com/aws-amplify/amplify-cli/issues/11010: Tried reproducing using the steps on this issue but was not able to reproduce the issue.

**Comment by redjonzaci** [comment] 2023-12-21 20:51
We had an existing app and then did `amplify update auth`. On next PR, we got the error.

**Comment by ykethan** [comment] 2023-12-22 18:27
On diving deeper it appears the `amplifyPush --simple` runs a headless pull and init push without the auth config. adding the client config as environment variables should add the auth config on the push. 

Closing the issue.

**Closed by ykethan** 2023-12-22 18:27 UTC
Labels: question, investigating, pending-triage

**Comment by danny33118** [comment] 2024-01-12 04:55
Problem :
auth headless is missing the following inputParameters googleAppIdUserPool, googleAppSecretUserPool...

Solution:
amplify pull --appId d2w68xxxxxxxxx --envName dev
(get the appid from your amplify backend)
