### ISSUE TITLE
mock api EPERM: operation not permitted, lstat

### ISSUE THREAD

**Issue by joekiller** [aws-amplify/amplify-cli#11657] opened 2022-12-25 00:03 UTC
### How did you install the Amplify CLI?

curl -sL https://aws-amplify.github.io/amplify-cli/install-win -o install.cmd && install.cmd

### If applicable, what version of Node.js are you using?

v16.13.2

### Amplify CLI Version

10.5.2

### What operating system are you using?

Windows 11

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

While running `amplify mock api` and rapidly ingesting data, the amplify-cli will encounter an error: `EPERM: operation not permitted, lstat`

### Expected behavior

Rapid ingest shouldn't be a problem with the mock api.

### Reproduction steps

1. Create a mock api.
2. Submit 1000's of transactions into the database.
3. CLI encounters error.

### Project Identifier

Session Identifier: dc189b9e-1161-417d-a293-14ef4e786d81

### Log output

<details>

```
2022-12-24T23:55:11.660Z|error : EPERM: operation not permitted, lstat 'C:\Users\test\trading\src\test\amplify\mock-data\dynamodb\fake_us-fake-1.db-journal'
UnknownNodeJSFault: EPERM: operation not permitted, lstat 'C:\Users\test\trading\src\test\amplify\mock-data\dynamodb\fake_us-fake-1.db-journal'

```

</details>

### Additional information

The watch on the mockDataDirectory throws the error when the `.db-journal` flashes into existence and then is removed.

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment] 2023-01-03 15:58
Hey @joekiller :wave: thanks for raising this and for submitting a PR! Do you have a script you're using to shove data to the mocked api?

**Comment by joekiller** [comment] 2023-01-03 21:56
@josefaidt I created https://github.com/joekiller/next-amplified-11657 to help demonstrate the issue.

The project created `Session Identifier: af98177b-63f8-4615-ab94-24a3f1782c51`

**Comment by josefaidt** [comment] 2023-01-06 00:52
Hey @joekiller I will take a look at the session details as I was unable to reproduce using the provided sample repo, but in the end I think this is a reasonable adjustment

**Comment by joekiller** [comment] 2023-01-11 01:01
I think this only happens on windows. I ran it a few times if needed. Thanks for investigating. it'll be nice not to have to use amplify-dev.

**Comment by TommyDong1998** [comment] 2023-02-19 03:42
I have the same error "Error: EPERM: operation not permitted, open 'C:\Users\tommy\.amplify\bin\amplify.exe'" using

Node v16.19.1
Amplify 10.7.3

When running amplify pull --appId <appid> --envName staging

**Comment by TommyDong1998** [comment] 2023-02-19 06:02
Update: eventually just changed the directory of global and that fixed it for me.
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Closed** 2023-03-08 01:04 UTC
Labels: investigating, windows, pending-triage, mock, api-graphql

**Comment by brettlyman** [comment] 2023-08-16 02:04
Commenting for others: I had the exact same error as @TommyDong1998 but in my case my antivirus was the culprit, it kept removing the amplify executables. Adding an exception made it work.
