### ISSUE TITLE
Unable to set Pre Sign-up lambda trigger

### ISSUE THREAD

**Issue by jk171505** [aws-amplify/amplify-cli#9351] opened 2021-12-20 17:00 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### Amplify CLI Version

7.6.4

### What operating system are you using?

mac

### Amplify Categories

auth, storage, function, api

### Amplify Commands

update

### Describe the bug

The trigger generated by amplify-cli contains typo. Instead of `PreSignup` name the `PreSignUp` is being generated which causes the trigger not being recognised in Cognito console. When I try manually set that function as Pre Sign-up trigger there is an error (404), ResourceNotFound. It turns out that the required policy for this lambda isn't generated.
This doesn't happen for `PostConfirmation` trigger. I'm guessing that the name `Pre Sign-up` is affected by some cam-case logic.

The problem is visible in `backend/api/auth/<name>/cli-inputs.json` and `backend/api/auth/<name>/build/parameters.json` 

```
    "triggers": {
      "PostConfirmation": [
        "add-to-group"
      ],
      "PreSignup": [
        "custom"
      ]
    },
    "authRoleArn": {
      "Fn::GetAtt": [
        "AuthRole",
        "Arn"
      ]
    },
    "unauthRoleArn": {
      "Fn::GetAtt": [
        "UnauthRole",
        "Arn"
      ]
    },
    "breakCircularDependency": false,
    "useEnabledMfas": false,
    "dependsOn": [
      {
        "category": "function",
        "resourceName": "**********PostConfirmation",
        "triggerProvider": "Cognito",
        "attributes": [
          "Arn",
          "Name"
        ]
      },
      {
        "category": "function",
        "resourceName": "*******PreSignup",
        "triggerProvider": "Cognito",
        "attributes": [
          "Arn",
          "Name"
        ]
      }
    ],
    "permissions": [
      "{\n  \"policyName\": \"AddToGroupCognito\",\n  \"trigger\": \"PostConfirmation\",\n  \"effect\": \"Allow\",\n  \"actions\": [\n    \"cognito-idp:AdminAddUserToGroup\",\n    \"cognito-idp:GetGroup\",\n    \"cognito-idp:CreateGroup\"\n  ],\n  \"resource\": {\n    \"paramType\": \"!GetAtt\",\n    \"keys\": [\n      \"UserPool\",\n      \"Arn\"\n    ]\n  }\n}"
    ],
    "authTriggerConnections": [
      "{\"triggerType\":\"PostConfirmation\",\"lambdaFunctionName\":\"*******PostConfirmation\"}",
      "{\"triggerType\":\"PreSignUp\",\"lambdaFunctionName\":\"********PreSignup\"}"
    ],
    "parentStack": {
      "Ref": "AWS::StackId"
    }

```

I believe similar policy to `PostConfirmation` should be generated in `/amplify/backend/auth/<name>/build/******-cloudformation-template.json`:
```
...
"UserPoolPostConfirmationLambdaInvokePermission": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "Action": "lambda:invokeFunction",
        "FunctionName": {
          "Ref": "function******PostConfirmationName"
        },
        "Principal": "cognito-idp.amazonaws.com",
        "SourceArn": {
          "Fn::GetAtt": [
            "UserPool",
            "Arn"
          ]
        }
      }
    }
...
```
- but it's missing

Also, the reference to `Pre Sign-up` trigger is missing in `LambdaConfig` but it is generated for `PostConfirmation`:
```
...
"LambdaConfig": {
          "PostConfirmation": {
            "Ref": "function*******PostConfirmationArn"
          }
        },
...
```

### Expected behavior

The Pre sign-up naming consistent and the trigger is visible in console, as well as proper policy ic generated for the trigger.

### Reproduction steps

update cognito auth and add pre sign-up trigger:
```
% amplify update auth
Please note that certain attributes may not be overwritten if you choose to use defaults settings.

You have configured resources that might depend on this Cognito resource.  Updating this Cognito resource could have unintended side effects.

Using service: Cognito, provided by: awscloudformation
 What do you want to do? Walkthrough all the auth configurations
 Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AWS IAM controls (Enables per-user Storage features for images or other content, Analytics, and more)
 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) No
 Do you want to enable 3rd party authentication providers in your identity pool? No
 Do you want to add User Pool Groups? No
 Do you want to add an admin queries API? No
 Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
 Specify an email verification subject: Your verification code
 Specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? No
 Specify the app's refresh token expiration period (in days): 30
 Do you want to specify the user attributes this app can read and write? No
 Do you want to enable any of the following capabilities? Add User to Group
 Do you want to use an OAuth flow? No
? Do you want to configure Lambda Triggers for Cognito? Yes
? Which triggers do you want to enable for Cognito Post Confirmation, Pre Sign-up
? What functionality do you want to use for Post Confirmation Add User To Group
? What functionality do you want to use for Pre Sign-up Create your own module
✅ Successfully updated AdminQueriese**** function locally
✅ Successfully updated AdminQueries API locally
Successfully updated the Cognito trigger locally
Successfully added resource *****PreSignup locally.
```

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by paulnolan7** [comment] 2022-01-07 00:15
I have the same issue. Pre signup lambda are not producing the correct cloud-formation file in the build folder. 
Not sure if there is a workaround?

**Comment by cespin** [comment] 2022-01-13 00:04
I'm also having this issue, I fixed it (it's a hack) by adding the function again in the Auth's _override.ts_. I posted my fix in #8997

**Comment by johnpc** [comment] 2022-01-14 21:55
Was this fixed in v7.6.5? #8997 was resolved with that release.

**Comment by Leandros** [comment] 2022-01-21 13:03
I still seem to have issues setting lambda triggers, with the latest release.

**Comment by clintfoster** [comment] 2022-01-21 18:44
I'm having the same problem in the current release: `7.6.11`. It also reproduced in the last few releases. 

Only the `PreSignup` trigger is affected. Other triggers like `PostAuthentication`& `PostConfirmation` get configured on the pool, as expected. In other words, if I run `add auth` and specify triggers, when I finish & push I see all the trigger names are set in the Cognito User Pool console _except_ the `PreSignup` trigger, which is set to `None`. 

Interestingly, I can see the `PreSignup` trigger in the dropdown, and I can even select it & save without getting an error. However, I'm not sure that's a good workaround since everything should be hooked up properly by CloudFormation. (Any manual changes might be reverted by a future deployment.)

## backend-config.json (abridged)
After `amplify auth` completes I see two related entries in `amplify/backend/backend-config.json`:

```json
    "MyUserPool": {
      "service": "Cognito",
      "providerPlugin": "awscloudformation",
      "dependsOn": [
        {
          "category": "function",
          "resourceName": "MyUserPoolPreSignup",
          "triggerProvider": "Cognito",
          "attributes": [
            "Arn",
            "Name"
          ]
        }
      ],

  "function": {
    "MyUserPoolPreSignup": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda"
    },
```

## team-provider-info.json (abridged)
The S3 key for the built function is defined in `amplify/backend/team-provider-info.json`:
```
      "function": {
        "MyUserPoolPreSignup": {
          "deploymentBucketName": "xxx-deployment",
          "s3Key": "amplify-builds/xxx-build.zip"
        },
```

## Lambda function directory
There is a directory under `amplify/backend/function` for each trigger, e.g. `MyUserPoolPreSignup` containing a `src` subdir with a boilerplate `custom.js` for the Lambda code and a CloudFormation template with the Lambda def & execution role (abridged):

```json
  "Resources": {
    "LambdaFunction": {
      "Type": "AWS::Lambda::Function",
      "Metadata": {
        "aws:asset:path": "./src",
        "aws:asset:property": "Code"
      },
      "Properties": {
        "Handler": "index.handler",
        "FunctionName": {
          "Fn::If": [
            "ShouldNotCreateEnvResources",
            "MyUserPoolPreSignup",


    "LambdaExecutionRole": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "RoleName": {
          "Fn::If": [
            "ShouldNotCreateEnvResources",
            "MyUserPoolPreSignup",
```

## No case mismatch?
I searched my project directory for `PreSignUp` (capital `U`) but didn't find it. I only get hits when I search for `PreSignup` (14 results in 8 files). So perhaps the root cause for me is other than the case discrepancy mentioned above. Could this be a different problem with the same symptom?

**Comment by sachscode** [comment] 2022-01-21 19:22
The root issue has been confirmed to be fixed. This particular issue  PreSignUp vs PreSignup seems like a a different problem. we are moving this to pending-triage. 
Have you previously migrated this project from an older version ( < 6.4 )of the CLI ? Did you have these resources created with the older version of the CLI?

**Comment by josefaidt** [comment] 2022-01-21 19:41
Hey @clintfoster :wave: to add on to @sachscode 's response above, I am also seeing the casing you are noticing `PreSignup`, however it does appear the pre-signup trigger is getting attached to the user pool as expected. I've tried switching from the email filter allowlist to a custom pre-signup module and that was also attaching as expected. 
![image](https://user-images.githubusercontent.com/5033303/150589591-d7283be7-4916-4e5c-afaf-c81e3780f28a.png)

Can you verify in the auth resource's `cli-inputs.json` also includes the following `triggers` block and a `dependsOn` block similar to what is shown in the `backend-config.json`?

```json
"triggers": {
      "PostConfirmation": [
        "add-to-group"
      ],
      "PreSignup": [
        "custom"
      ]
    },
"dependsOn": [
      {
        "category": "function",
        "resourceName": "myproject9e6df361PreSignup",
        "triggerProvider": "Cognito",
        "attributes": [
          "Arn",
          "Name"
        ]
      },
      {
        "category": "function",
        "resourceName": "myproject9e6df361PostConfirmation",
        "triggerProvider": "Cognito",
        "attributes": [
          "Arn",
          "Name"
        ]
      }
    ],
```

**Comment by clintfoster** [comment] 2022-01-21 20:04
@sachscode It's interesting you ask that question. We're still in development, and we decided to delete the Amplify project and start over for various reasons. Prior to that, the PreSignup trigger was working. It was created with a version of the Amplify CLI from perhaps 3 or 4 weeks ago.

As far as I can tell the project was deleted completely by `amplify delete`. I verified that everything in the Amplify, Cognito, Lambda, Dynamo, CloudFormation and S3 consoles was gone. I also verified the `amplify` directory was gone in my local workspace. Only then did I run `amplify init` and `amplify auth` again. I've actually done a `delete/init/auth` cycle several times now using many different permutations of responses to the `amplify auth` CLI. I always end up in the same situation where the PreSignup trigger seems to be created & deployed, but it doesn't show up in the User Pool console (yet any other triggers are there).

Is it possible running `amplify delete` is leaving something behind that could cause this problem when `amplify init` and `amplify auth` are run again?

@josefaidt I'll gather the answer to your question next...

**Comment by clintfoster** [comment] 2022-01-21 20:26
@josefaidt Here is an only slightly abridged `amplify/backend/auth/MyUserPool/cli-inputs.json`. The `triggers` section is present, but there is no `dependsOn`.

I apologize for polluting this issue with an apparently unrelated problem. Since the symptoms were the same and both were recent I thought they might be related. Let me know if you'd like me to open a separate issue.

```json
{
  "version": "1",
  "cognitoConfig": {
    "identityPoolName": "MyIdentityPool",
    "allowUnauthenticatedIdentities": true,
    "resourceNameTruncated": "xxx5c9cb518",
    "userPoolName": "MyUserPool",
    "autoVerifiedAttributes": [
      "email"
    ],
    "requiredAttributes": [],
    "aliasAttributes": [],
    "userpoolClientGenerateSecret": false,
    "userpoolClientLambdaRole": "xxx_userpoolclient_lambda_role",
    "userpoolClientSetAttributes": false,
    "resourceName": "MyUserPool",
    "authSelections": "identityPoolAndUserPool",
    "useDefault": "manual",
    "thirdPartyAuth": false,
    "usernameAttributes": [
      "email, phone_number"
    ],
    "userPoolGroups": true,
    "adminQueries": true,
    "triggers": {
      "PreSignup": [
        "custom"
      ]
    },
    "hostedUI": true,
    "hostedUIDomainName": "xxx",
    "authProvidersUserPool": [],
    "hostedUIProviderMeta": "[]",
    "oAuthMetadata": "{\"AllowedOAuthFlows\":[\"code\"],\"AllowedOAuthScopes\":[\"phone\",\"email\",\"openid\",\"profile\",\"aws.cognito.signin.user.admin\"],\"CallbackURLs\":[\"https://xxx/\"],\"LogoutURLs\":[\"https://xxx/\"]}",
    "userPoolGroupList": [
      "Admin"
    ],
    "adminQueryGroup": "Admin",
    "useEnabledMfas": false
  }
}
```

**Comment by clintfoster** [comment] 2022-01-21 21:52
@josefaidt If I start in a completely empty directory (no frontend or other files) and answer the `amplify auth` prompts the same way, the PreSignup trigger is correctly set up (same as you reported). So, something must be different about the project directory in which I am running `amplify delete` and then `amplify init/auth`. I can think of two things:

1. It has a Vue frontend in it (rather than an empty directory)
2. It is a subdirectory of an Amplify monorepo, e.g. `my-app1` below:

```
my-monorepo/
    amplify/
        backend
        cli.json
    amplify.yml
    amplify-apps/
        my-app1/
        my-app2/
```

The `amplify-apps` directory is where all the monorepo subprojects live like `my-app1`. I don't remember how the top-level `amplify` directory got into the monorepo. I guess I could have accidentally run `amplify init` in that directory at some point. It contains an empty `backend` directory and a `cli.json` that seems to only contain defaults:

## top-level monorepo amplify/cli.json (defaults?)
```json
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "improvepluralization": false,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": true,
      "enableiterativegsiupdates": true,
      "secondarykeyasgsi": true,
      "skipoverridemutationinputtypes": true,
      "transformerversion": 2,
      "suppressschemamigrationprompt": true
    },
    "frontend-ios": {
      "enablexcodeintegration": true
    },
    "auth": {
      "enablecaseinsensitivity": true,
      "useinclusiveterminology": true,
      "breakcirculardependency": true,
      "forcealiasattributes": false,
      "useenabledmfas": true
    },
    "codegen": {
      "useappsyncmodelgenplugin": true,
      "usedocsgeneratorplugin": true,
      "usetypesgeneratorplugin": true,
      "cleangeneratedmodelsdirectory": true,
      "retaincasestyle": true,
      "addtimestampfields": true,
      "handlelistnullabilitytransparently": true,
      "emitauthprovider": true,
      "generateindexrules": true,
      "enabledartnullsafety": true
    },
    "appsync": {
      "generategraphqlpermissions": true
    },
    "latestregionsupport": {
      "pinpoint": 1,
      "translate": 1,
      "transcribe": 1,
      "rekognition": 1,
      "textract": 1,
      "comprehend": 1
    },
    "project": {
      "overrides": true
    }
  }
}
```

Maybe this is a red herring, but I will delete these local files from the parent monorepo directory structure. There is nothing in the cloud that knows about the monorepo any more since I only ever did `amplify init/push` on the `my-app1` subproject. The first time I ran `amplify delete` in `my-app1` the cloud Amplify console was completely empty, and I did not re-enable Amplify CI/CD & monorepo for the trigger experiments I've been doing. Still, it's an interesting coincidence that if I run `amplify auth` in an empty directory outside the monorepo structure, the trigger is set up correctly.

**Comment by clintfoster** [comment] 2022-01-21 22:19
This doesn't make any sense, but getting rid of the `amplify` directory & `amplify.yml` file at the top of the monorepo file structure fixed the problem. I ran `amplify delete/init/auth` in the the `my-app1` subproject again, answering all the CLI questions the same way, and this time the PreSignup trigger was correctly hooked up in the User Pool console

<img width="312" alt="image" src="https://user-images.githubusercontent.com/1449737/150607409-45e993c7-1285-4d6c-bc47-9e0df254c446.png">

Previously only the other two triggers were getting hooked up.

**Comment by josefaidt** [comment] 2022-01-24 14:38
Ah hey @clintfoster glad to hear that you're back up and running despite the oddities. In my experience running amplify commands like initializing a new project from a child directory of another amplify project can cause unexpected issues. Around the time this issue was originally opened there were issues with triggers not getting set or all triggers disconnected when switching envs, however this has since been fixed.

**Comment by clintfoster** [comment] 2022-01-24 16:00
If I had not run the same `delete/init/add auth` sequence many times I would not believe it myself. The only thing I changed was removing the `amplify` directory & `amplify.yml` at the root of the monorepo. Then, voila, the PreSignup trigger was set in the User Pool console after I pushed. I would not have tried it had I not performed so many permutations in separate test directories that failed to reproduce the problem. I was trying to create the simplest possible example for a bug report. But none of my test projects reproduced the problem, even as I ramped up the complexity until they were identical to the original project. Finally I realized the only thing left that was special about the original project was the monorepo.

Why this problem would only affect the PreSignup trigger, and not PostAuthentication & PostConfirmation I don't know. Those triggers were consistently set even in the monorepo subproject. The results were the same with CLI `7.6.9` and `10`.

I thought the [monorepo approach](https://aws.amazon.com/blogs/mobile/set-up-continuous-deployment-and-hosting-for-a-monorepo-with-aws-amplify-console/) might make it easier to share a backend in one project with multiple frontends in other projects. But doing a "read-only" `amplify pull` from the other projects should be fine for that (per [docs](https://docs.amplify.aws/cli/teams/multi-frontend/)).

To clarify for anyone reading, this issue does _not_ appear to be related to the `PreSignUp` / `PreSignup` bug. That had apparently already been fixed in `7.6.9/10`.

**Comment by josefaidt** [comment] 2022-01-27 21:04
Hey @clintfoster to your note regarding the monorepo approach, yes I believe we should be okay as long as the projects live in sibling directories rather than nested.

@jk171505 are you still experiencing this?

**Comment by jk171505** [comment] 2022-01-27 21:10
@josefaidt I don't - I gave up this trigger :)

**Comment by josefaidt** [comment] 2022-01-27 21:15
Ah understandable @jk171505. I'll close this issue for now, but if you run into this again when adding a trigger please feel free to reply back to this thread and we can re-open to investigate further 🙂

**Closed by josefaidt** 2022-01-27 21:15 UTC
Labels: bug, pending-close-response-required, duplicate

**Comment by biller-aivy** [comment] 2022-02-14 15:06
<img width="1081" alt="Bildschirmfoto 2022-02-14 um 16 04 48" src="https://user-images.githubusercontent.com/88539760/153889253-fa81e1a1-0523-42a4-9b31-fd34b5c9c59e.png">

`{
  "version": "1",
  "cognitoConfig": {
    "identityPoolName": "aivyusers_identitypool_f0efee42",
    "allowUnauthenticatedIdentities": true,
    "resourceNameTruncated": "aivyusf0efee42",
    "userPoolName": "aivyusers",
    "autoVerifiedAttributes": ["email"],
    "mfaConfiguration": "OPTIONAL",
    "mfaTypes": ["SMS Text Message", "TOTP"],
    "smsAuthenticationMessage": "Your authentication code is {####}",
    "smsVerificationMessage": "Your verification code is {####}",
    "emailVerificationSubject": "Code",
    "emailVerificationMessage": "<head> <meta charset=\"utf-8\"/> <title>Willkommen</title> <meta content=\"mail-template\" property=\"og:title\"/> <meta content=\"mail-template\" property=\"twitter:title\"/> <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\"/> <link href=\"https://uploads-ssl.webflow.com/5d3c10823dfa66198f3d1166/css/aivy-app.webflow.614f2b6cd.css\" rel=\"stylesheet\" type=\"text/css\"/> <script src=\"https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js\" type=\"text/javascript\" ></script> <script type=\"text/javascript\">WebFont.load({google:{families: [ \"Open Sans:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic\", \"Fira Sans:regular,500,600,800,900\", \"Fira Sans:200,300,regular\",],},}); </script> <script type=\"text/javascript\">!(function (o, c){var n=c.documentElement, t=\" w-mod-\"; (n.className +=t + \"js\"), (\"ontouchstart\" in o || (o.DocumentTouch && c instanceof DocumentTouch)) && (n.className +=t + \"touch\");})(window, document); </script> <link href=\"https://uploads-ssl.webflow.com/5d3c10823dfa66198f3d1166/5d4d808ae11fbe9c7f6a2cc5_favicon.png\" rel=\"shortcut icon\" type=\"image/x-icon\"/> <link href=\"https://uploads-ssl.webflow.com/5d3c10823dfa66198f3d1166/5d4d80c5574a789cbcd8d7ab_256.png\" rel=\"apple-touch-icon\"/> </head> <body class=\"body-2\"> <img src=\"https://uploads-ssl.webflow.com/5d3c10823dfa66198f3d1166/5d52ea4bd4a630e67d3d2e08_Aivy_Logo.jpg\" alt=\"\" class=\"image-75\"/> <div class=\"div-block-166\"> <div class=\"div-block-167\"> <h3 class=\"heading-19\">Herzlich Willkommen</h3> <p class=\"paragraph-14\"> Ich freue mich gemeinsam mit dir deine Stärken und Potenziale zu entdecken! </p><p class=\"paragraph-15\"> Bestätige deine E-Mail mit <strong>folgenden Code:</strong> </p><div class=\"text-block-71\">{####}</div><p class=\"paragraph-14\"> Solltest du Probleme mit der Aktivierung haben, antworte mir einfach auf diese E-Mail. </p></div><div class=\"div-block-169\"> <div class=\"div-block-28\"> <a href=\"https://www.facebook.com/aivyapp\" target=\"_blank\" class=\"link-block w-inline-block\" ><img src=\"https://uploads-ssl.webflow.com/5d3c10823dfa66198f3d1166/5d50483e3691c9cfc2e2dd44_Social-Media-Facebook.png\" width=\"40\" alt=\"\"/></a ><a href=\"https://www.instagram.com/aivy.app/\" target=\"_blank\" class=\"w-inline-block\" ><img src=\"https://uploads-ssl.webflow.com/5d3c10823dfa66198f3d1166/5d5048413691c9a041e2dd47_Social-Media-Instagram.png\" width=\"40\" alt=\"\"/></a ><a href=\"https://twitter.com/aivyapp\" target=\"_blank\" class=\"w-inline-block\" ><img src=\"https://uploads-ssl.webflow.com/5d3c10823dfa66198f3d1166/5d504843493b05298b316160_Social-Media-Twitter.png\" width=\"40\" alt=\"\"/></a ><a href=\"https://www.youtube.com/channel/UCraNBOrc6VH2z8sS-nEir8Q\" target=\"_blank\" class=\"w-inline-block\" ><img src=\"https://uploads-ssl.webflow.com/5d3c10823dfa66198f3d1166/5d504844493b05bd5331616b_Social-Media-YouTube.png\" width=\"40\" alt=\"\"/></a ><a href=\"https://www.xing.com/companies/aivy\" target=\"_blank\" class=\"w-inline-block\" ><img src=\"https://uploads-ssl.webflow.com/5d3c10823dfa66198f3d1166/5d504844493b05e731316162_Social-Media-Xing.png\" width=\"40\" alt=\"\"/></a ><a href=\"https://www.linkedin.com/company/14034150\" target=\"_blank\" class=\"w-inline-block\" ><img src=\"https://uploads-ssl.webflow.com/5d3c10823dfa66198f3d1166/5d5048423691c90c41e2dd48_Social-Media-LinkedIn.png\" width=\"40\" alt=\"\"/></a> </div><div class=\"div-block-168\"> <a href=\"https://www.aivy.app/agb\" class=\"link-10\">AGB</a> <div class=\"text-block-72\">|</div><a href=\"https://www.aivy.app/datenschutz\" class=\"link-10\" >Datenschutz</a > <div class=\"text-block-72\">|</div><a href=\"https://www.aivy.app/impressum\" class=\"link-10\">Impressum</a> </div></div></div></body>",
    "defaultPasswordPolicy": false,
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": [],
    "requiredAttributes": ["email"],
    "aliasAttributes": [],
    "userpoolClientGenerateSecret": true,
    "userpoolClientRefreshTokenValidity": "90",
    "userpoolClientWriteAttributes": ["birthdate", "name", "email"],
    "userpoolClientReadAttributes": ["birthdate", "email", "name"],
    "userpoolClientLambdaRole": "aivyusers_userpoolclient_lambda_role",
    "userpoolClientSetAttributes": false,
    "authSelections": "identityPoolAndUserPool",
    "resourceName": "aivyusers",
    "serviceName": "Cognito",
    "useDefault": "manual",
    "userPoolGroupList": ["Admin"],
    "userPoolGroups": true,
    "usernameAttributes": ["email"],
    "verificationBucketName": "aivyusersverificationbucket",
    "adminQueries": true,
    "adminQueryGroup": "Admin",
    "hostedUI": false,
    "thirdPartyAuth": false,
    "authProviders": [],
    "triggers": {
      "CreateAuthChallenge": ["boilerplate-create-challenge"],
      "CustomMessage": ["custom"],
      "DefineAuthChallenge": ["boilerplate-define-challenge"],
      "PreSignup": ["custom"],
      "VerifyAuthChallengeResponse": ["boilerplate-verify"]
    },
    "authRoleArn": {
      "Fn::GetAtt": ["AuthRole", "Arn"]
    },
    "unauthRoleArn": {
      "Fn::GetAtt": ["UnauthRole", "Arn"]
    },
    "breakCircularDependency": false,
    "useEnabledMfas": false,
    "dependsOn": [
      {
        "category": "function",
        "resourceName": "aivyusersCreateAuthChallenge",
        "triggerProvider": "Cognito",
        "attributes": ["Arn", "Name"]
      },
      {
        "category": "function",
        "resourceName": "aivyusersCustomMessage",
        "triggerProvider": "Cognito",
        "attributes": ["Arn", "Name"]
      },
      {
        "category": "function",
        "resourceName": "aivyusersDefineAuthChallenge",
        "triggerProvider": "Cognito",
        "attributes": ["Arn", "Name"]
      },
      {
        "category": "function",
        "resourceName": "aivyusersPreSignup",
        "triggerProvider": "Cognito",
        "attributes": ["Arn", "Name"]
      },
      {
        "category": "function",
        "resourceName": "aivyusersVerifyAuthChallengeResponse",
        "triggerProvider": "Cognito",
        "attributes": ["Arn", "Name"]
      }
    ],
    "permissions": [],
    "authTriggerConnections": [
      "{\"triggerType\":\"CreateAuthChallenge\",\"lambdaFunctionName\":\"aivyusersCreateAuthChallenge\"}",
      "{\"triggerType\":\"CustomMessage\",\"lambdaFunctionName\":\"aivyusersCustomMessage\"}",
      "{\"triggerType\":\"DefineAuthChallenge\",\"lambdaFunctionName\":\"aivyusersDefineAuthChallenge\"}",
      "{\"triggerType\":\"PreSignUp\",\"lambdaFunctionName\":\"aivyusersPreSignup\"}",
      "{\"triggerType\":\"VerifyAuthChallengeResponse\",\"lambdaFunctionName\":\"aivyusersVerifyAuthChallengeResponse\"}"
    ],
    "parentStack": {
      "Ref": "AWS::StackId"
    }
  }
}
`

CLI -   7.6.19

Tried to redeploy with --force
