### ISSUE TITLE
default amplify function runtime versions should be the same as aws lambda latest runtime versions

### ISSUE THREAD

**Issue by renschler** [aws-amplify/amplify-cli#11160] opened 2022-10-11 20:23 UTC
### Is this feature request related to a new or existing Amplify category?

function

### Is this related to another service?

Lambda

### Describe the feature you'd like to request

Amplify CLI currently has these default runtimes:
https://docs.amplify.aws/cli/function/#supported-lambda-runtimes

They are not the same as the AWS lambda latest supported runtimes.

For example, the Amplify CLI defaults to NodeJS version 14.x but AWS Lambda defaults to NodeJS version 16.x.

### Describe the solution you'd like

Amplify CLI should stay up-to-date with the AWS Lambda defaults.

### Describe alternatives you've considered

Manually altering the cloud-formation-template of the Amplify CLI output.

Manually changing the runtime from the AWS Lambda console.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment] 2022-10-12 13:41
Hey @renschler :wave: thanks for raising this, and you make a valid point! I'll mark this as a functions feature request for the team to evaluate further 🙂

**Comment by ykethan** [comment] 2022-10-31 19:32
duplicate of https://github.com/aws-amplify/amplify-cli/issues/11252
closing the issue to prevent any miscommunications and better track this.

**Closed by ykethan** 2022-10-31 19:32 UTC
Labels: functions, feature-request, ops-functions
