### ISSUE TITLE
The Amplify CLI can NOT find command:  serve

### ISSUE THREAD

**Issue by aluminick** [aws-amplify/amplify-cli#2464] opened 2019-10-01 07:00 UTC
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I created an app using `npx create-react-app`

**To Reproduce**
1. amplify serve

**Expected behavior**
to not get `The Amplify CLI can NOT find command:  serve`

**Desktop (please complete the following information):**
 - Ubuntu 16.04

**Comment by bc-ppuente** [comment] 2019-10-01 15:27
Looks like this is patched in https://github.com/aws-amplify/amplify-cli/pull/2394, hoping for a quick resolution!

**Comment by hatertron3000** [comment] 2019-10-01 15:28
Looks like this is patched in https://github.com/aws-amplify/amplify-cli/pull/2394, hoping for a quick resolution!

**Comment by aluminick** [comment] 2019-10-01 15:44
@hatertron3000 what version were you using before you get the error?

**Comment by hatertron3000** [comment] 2019-10-01 15:55
@aluminick honestly, I don't remember and I'm too ignorant to figure it out. But, after thinking about it, rolling back to a previous version many be a bit drastic since the issue is just the command alias. Running `amplify run` instead of `amplify serve` seems to do the trick for me on the current version.

**Comment by SwaySway** [comment] 2019-10-03 19:45
Closing this issue as the fix for this has been merged.

**Closed by SwaySway** 2019-10-03 19:45 UTC
Labels: bug, platform, review
