### ISSUE TITLE
Not possible to do init headless

### ISSUE THREAD

**Issue by SebSchwartz** [aws-amplify/amplify-cli#2880] opened 2019-11-29 09:28 UTC
**Describe the bug**
In my CodeBuild, i'm installing amplify then initializing it with headless mode but it crash with this error:
```
Scanning for plugins... 
Plugin scan successful 
Note: It is recommended to run this command from the root of your app directory 
Using default provider  undefined 
init failed 
TypeError [ERR_INVALID_ARG_TYPE]: The 'request' argument must be string. Received type undefined 
    at providers.forEach.provider (/usr/local/share/.config/yarn/global/node_modules/@aws-amplify/cli/lib/lib/init-steps/s2-initProviders.js:22:36) 
    at Array.forEach (<anonymous>) 
    at /usr/local/share/.config/yarn/global/node_modules/@aws-amplify/cli/lib/lib/init-steps/s2-initProviders.js:21:19 
    at Generator.next (<anonymous>) 
    at fulfilled (/usr/local/share/.config/yarn/global/node_modules/@aws-amplify/cli/lib/lib/init-steps/s2-initProviders.js:5:58) 
```

**Amplify CLI Version**
4.2.0

**To Reproduce**
Here is my config for headless init (i copied it from the doc):
```bash
#!/bin/bash 
set -e
IFS='|'

export REACTCONFIG="{\
\"SourceDir\":\"src\",\
\"DistributionDir\":\"build\",\
\"BuildCommand\":\"npm run-script build\",\
\"StartCommand\":\"npm run-script start\"\
}"

export AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":false,\
\"profileName\":\"default\",\
\"accessKeyId\":\"$AWS_ACCESS_KEY_ID\",\
\"secretAccessKey\":\"$AWS_SECRET_ACCESS_KEY\",\
\"region\":\"ap-southeast-1\"\
}"

export FRONTEND="{\
\"frontend\":\"javascript\",\
\"framework\":\"react\",\
\"config\":$REACTCONFIG\
}"

export AMPLIFY="{\
\"projectName\":\"myproject\",\
\"envName\":\"$DEPLOY_ENV\",\
\"defaultEditor\":\"code\"\
}"


export PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"

amplify init \
--amplify $AMPLIFY \
--frontend $FRONTEND \
--providers $PROVIDERS \
--yes
```
I've printed all env and printed the result and all are normal and rightly formated json.

**Expected behavior**
It should work :)

**Desktop (please complete the following information):**
- Node 10
- Linux Amazon

**Comment by UnleashedMind** [comment] 2019-12-05 19:29
Please get the latest CLI, run `amplify plugin scan` and try again. Let us know if the issue is still there.

**Comment by SebSchwartz** [comment] 2019-12-06 08:13
Issue is still here :(

```
Scanning for plugins... 
Plugin scan successful 
Scanning for plugins... 
Plugin scan successful 
Note: It is recommended to run this command from the root of your app directory 
Using default provider  undefined 
init failed 
TypeError [ERR_INVALID_ARG_TYPE]: The 'request' argument must be string. Received type undefined 
    at providers.forEach.provider (/usr/local/share/.config/yarn/global/node_modules/@aws-amplify/cli/lib/lib/init-steps/s2-initProviders.js:22:36) 
    at Array.forEach (<anonymous>) 
    at /usr/local/share/.config/yarn/global/node_modules/@aws-amplify/cli/lib/lib/init-steps/s2-initProviders.js:21:19 
    at Generator.next (<anonymous>) 
    at fulfilled (/usr/local/share/.config/yarn/global/node_modules/@aws-amplify/cli/lib/lib/init-steps/s2-initProviders.js:5:58) 
    at process._tickCallback (internal/process/next_tick.js:68:7) 
```


I ran `amplify plugin scan` before the init.

**Comment by SebSchwartz** [comment] 2019-12-09 16:13
Any news on this error?
This is blocking our CI/CD process...

Thanks,
Sebastien

**Comment by kaustavghosh06** [comment] 2019-12-10 00:16
@UnleashedMind Did you get a chance to take a look at this? ^

**Comment by UnleashedMind** [comment] 2019-12-10 00:26
We have a PR out for it already, but it's not merged yet. 
https://github.com/aws-amplify/amplify-cli/pull/2907
But the PR only prevents the incorrect prompt for selection or require the non-existing provider plugin. 
@SebSchwartz let me gather some more info: 
- what is the CLI version? (run `amplify -v` to find out)
- run `amplify plugin scan` and then `amplify plugin list`, select `active plugins` , tell us what are there, and if `awscloudformation` is in the list.

**Comment by SebSchwartz** [comment] 2019-12-10 09:28
Hi,

Here is the results of the commands:

```terminal
v10.17.0 - Node version
6.11.3  - NPM Version
Scanning for plugins... 
Plugin scan successful 
4.6.0 - Amplify version
Scanning for plugins... 
Plugin scan successful 
? Select the section to list (Use arrow keys) 
❯ active plugins  
  excluded plugins  
  general information ·[22D·[22C·[2K·[1A·[2K·[1A·[2K·[1A·[2K·[G? Select the section to list active plugins·[43D·[43C 
 all 
core 
  analytics 
 api 
  auth 
  function 
  hosting
interactions 
  notifications 
  predictions 
 storage 
  xr 
  codegen 
  android
ios 
  javascript 
  awscloudformation 
 mock 


```

**Comment by UnleashedMind** [comment] 2019-12-10 19:34
then you should be fine now, are you still having the issue?

**Comment by SebSchwartz** [comment] 2019-12-12 22:31
Yes still the same issue :(

**Comment by SebSchwartz** [comment] 2019-12-17 08:12
@UnleashedMind Still the issue in 4.6.0. Our CI/CD is still not building and our customer is not very happy with that :(

**Comment by chadkouse** [comment] 2019-12-18 01:25
Same here

**Comment by chadkouse** [comment] 2019-12-18 02:04
@SebSchwartz fwiw I got this working by installing `aws-amplify/cli` globally and running it that way.  But I also did not have the plugins you have listed when I checked.

**Comment by SebSchwartz** [comment] 2019-12-18 21:47
@chadkouse What do you mean by "running it that way"?

@kaustavghosh06 any news on that? I just copied what is on the online doc and ran it on AWS CodeBuild, no reason this should not work...

**Comment by SebSchwartz** [comment] 2019-12-19 09:13
I just sent the email with the script @UnleashedMind , thanks for help ;)

**Comment by chadkouse** [comment] 2019-12-21 17:45
@SebSchwartz running it as a globally installed package instead of just a binary in your project's `node_modules`

**Comment by SebSchwartz** [comment] 2020-01-06 09:17
Any news on that @UnleashedMind @kaustavghosh06 ?
It's been more than one month that this issue is there and as I already said I'm not doing anything fancy, just copy/paste the doc init headless and run them inside an AWS CodeBuild...

**Comment by SebSchwartz** [comment] 2020-01-06 09:29
If that helps, with new amplify version I got this at init:
```
aws-cli/1.16.284 Python/3.8.0 Linux/4.14.152-98.182.amzn1.x86_64 exec-env/AWS_ECS_EC2 botocore/1.13.20 
Scanning for plugins... 
The following official plugins are missing or inactive: 
    awscloudformation: provider | amplify-provider-awscloudformation@4.11.0 
    analytics: category | amplify-category-analytics@2.11.0 
    api: category | amplify-category-api@2.11.0 
    auth: category | amplify-category-auth@2.11.0 
    function: category | amplify-category-function@2.11.0 
    hosting: category | amplify-category-hosting@2.1.6 
    interactions: category | amplify-category-interactions@2.1.6 
    notifications: category | amplify-category-notifications@2.11.0 
    predictions: category | amplify-category-predictions@2.1.6 
    storage: category | amplify-category-storage@2.1.6 
    xr: category | amplify-category-xr@2.1.6 
    codegen: util | amplify-codegen@2.11.0 
    android: frontend | amplify-frontend-android@2.11.0 
    ios: frontend | amplify-frontend-ios@2.11.0 
    javascript: frontend | amplify-frontend-javascript@2.11.0 
    mock: util | amplify-util-mock@3.11.0 
Plugin scan successful 
```

**Comment by SebSchwartz** [comment] 2020-01-06 16:14
I found the "problem". It seems that installing amplify-cli with yarn globally is not ok...

I just changed to ```npm install -g @aws-amplify/cli --unsafe-perm=true``` and it worked...

**Comment by nelsona** [comment] 2020-01-08 09:19
I am trying to run headless on a Mac trying to build react-native and I am hitting the same issue as @SebSchwartz in that I am getting the `The following official plugins are missing or inactive: ` error.

I have run the `npm install -g @aws-amplify/cli --unsafe-perm=true` command and it is still failing for me.

Is there anything else I can try that might get this working?

**Comment by kaustavghosh06** [comment] 2020-02-10 06:18
@nelsona Could you please try using `npm install -g @aws-amplify/cli` and see if you're still facing this issue?

**Closed** 2020-02-10 06:18 UTC
Labels: pending-response, pending-triage, platform

**Comment by nelsona** [comment] 2020-03-12 12:20
@kaustavghosh06 Just tried this and I now get an issue with the `.aws/credentials` file not existing even though I have `useProfile: false` set in the config...

**Comment by hardchor** [comment] 2020-03-29 19:12
Can confirm that this is only happening when installing through yarn.
Even when manually installing the missing plugins, e.g. `amplify-provider-awscloudformation`, it still won't recognise them as a provider plugin.

**Comment by sarahsga** [comment] 2020-04-03 13:05
> @kaustavghosh06 Just tried this and I now get an issue with the `.aws/credentials` file not existing even though I have `useProfile: false` set in the config...

I have the same issue. Were you able to figure this out?

**Comment by sceptyk** [comment] 2020-04-06 18:52
@sarahsga easy workaround to create those files manually:
`mkdir -p ~/.aws; touch ~/.aws/credentials; touch ~/.aws/config`

**Comment by toddsampson** [comment] 2020-04-25 20:07
I received this error as well. I was able to fix the issue as suggested above by uninstalling the global yarn version, manually deleting /usr/local/bin/amplify and reinstalling using npm fixed the issue for me. Any idea when this is going to be fixed for yarn? Thanks
