### ISSUE TITLE
REST API authorization type

### ISSUE THREAD

**Issue by kqumsieh** [aws-amplify/amplify-cli#2527] opened 2019-10-08 19:26 UTC
When I create a REST Api I do not get a choice for authorization type.  I want to add a Cognito User Pool authorization type for my REST Api.  This option is available for GraphQL but not REST.  The only authorization type available for REST Api is AWS_IAM.  

<img width="386" alt="image" src="https://user-images.githubusercontent.com/37556705/66426273-7582dc80-e9df-11e9-844c-a51aa5276ab8.png">

Am I missing something?  How do I authenticate my REST Api with Cognito user pool.

Thanks!

**Comment by yuth** [comment] 2019-10-10 00:00
Thanks for reporting this. Amplify CLI currently does not have support for adding additional authorization support. I am marking this as a feature request and adding this to our backlog.

**Comment by kaustavghosh06** [comment] 2019-10-11 04:24
This request is a duplicate of #1016

**Closed by kaustavghosh06** 2019-10-11 04:24 UTC
Labels: REST API, feature-request, functions, pending-review

**Comment by kqumsieh** [comment] 2019-10-11 15:20
@kaustavghosh06 this is not a duplicate of #1016 .  That ticket asks specifically for API Key authentication.  Here I m asking for more like Cognito User Pool.

**Comment by kaustavghosh06** [comment] 2019-10-11 15:22
This feature (in both the issues) is asking for adding additional authorization types for API gateway. 
Right now the CLI only supports IAM.
