### ISSUE TITLE
Cannot read property 'Id' of undefined on notifications update/add

### ISSUE THREAD

**Issue by GeorgeBellTMH** [aws-amplify/amplify-cli#11844] opened 2023-01-25 00:56 UTC
### How did you install the Amplify CLI?

npm

### Amplify CLI Version

10.6.2

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

This is a new environment...

### Describe the bug

When running amplify notifications update/add I get:

Cannot read property 'Id' of undefined

When I publish/push I get storage+notifications and notifications both in create mode. Push is successful, but next push also has both still in create mode.

### Expected behavior

Push should be successful, second push should result in no additional updates/creates, add likely shouldn't work, update should work

### Reproduction steps

I created this environment using 10.6.1, and it was a duplicate of a functional environment.

### Project Identifier

87a0715a84d88aea78b93beedf132706

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by GeorgeBellTMH** [comment] 2023-01-25 02:23
I did a bit more digging...it looks like at some point a bunch of pinpoint environments were created in AWS...all with different id's...I would chalk this up to aborted push's during environment setup...

Anyways...I took the most recent one, and added: 

 "notifications": {
        "Pinpoint": {
          "Name": "themeetinghouse-prodnew",
          "Id": "0a2b4c0b6e7448249fac4bf70c54b478",
          "Region": "us-east-1"
        }
      },

to team-provider...

Pushed again, and same thing, also the notifications update/add still gives the same error...so I suspect I am missing some information in my amplify-meta...but not sure what or how to resolve...

**Comment by GeorgeBellTMH** [comment] 2023-01-25 02:47
Added "Name": "xxxxx",
"Id": "xxxxx",
"Region": "us-east-1" to the amplify-meta notifications section and things are starting to work...

**Comment by josefaidt** [comment] 2023-01-25 19:29
Hey @GeorgeBellTMH :wave: thanks for raising this! This appears similar to a few other active bugs, and as such I will mark this as a duplicate and close in favor of tracking the existing items

- https://github.com/aws-amplify/amplify-cli/issues/11768
- https://github.com/aws-amplify/amplify-cli/issues/11819
- https://github.com/aws-amplify/amplify-cli/issues/11432

Primarily a duplicate of #11432

**Closed by josefaidt** 2023-01-25 19:29 UTC
Labels: bug, notifications

**Comment by osehmathias** [comment] 2023-09-23 03:42
Just encountered this today.  None of these things worked. 

Removed notifications from my team-provider.json, removed aws-config and amplifyconfiguration.json, then pulled down from the env. 

Seems to have solved it.
