### ISSUE TITLE
AWS-Amplify/CLI not allowing sign-in

### ISSUE THREAD

**Issue by awsirkis** [aws-amplify/amplify-cli#3444] opened 2020-02-17 01:43 UTC
**Describe the bug**
When attempting to configure an AWS Amplify project using `amplify configure`, user is met with exception before being able to sign in.

Error text:
`2020-02-16T04:13:06.005Z - error: uncaughtException: spawn cmd ENOENT date=Sat Feb 15 2020 20:13:05 GMT-0800 (Pacific Standard Time), pid=24080, uid=null, gid=null, cwd=C:\Users\awsir\CMAA, execPath=C:\Program Files\nodejs\node.exe, version=v12.16.0, argv=[C:\Program Files\nodejs\node.exe, C:\Users\awsir\AppData\Roaming\npm\node_modules\@aws-amplify\cli\bin\amplify, configure], rss=251940864, heapTotal=210722816, heapUsed=182127848, external=13769947, loadavg=[0, 0, 0], uptime=240206, trace=[column=19, file=internal/child_process.js, function=Process.ChildProcess._handle.onexit, line=267, method=onexit, native=false, column=16, file=internal/child_process.js, function=onErrorNT, line=469, method=null, native=false, column=21, file=internal/process/task_queues.js, function=processTicksAndRejections, line=84, method=null, native=false], stack=[Error: spawn cmd ENOENT,     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19),     at onErrorNT (internal/child_process.js:469:16),     at processTicksAndRejections (internal/process/task_queues.js:84:21)]`

**Amplify CLI Version**
4.13.3

**To Reproduce**
After configuring the regular AWS CLI in another CLI, use the Node.js CLI to navigate to a server-less project. 

**Expected behavior**
I expect to be directed to sign-in to the AWS console and continue to be able to make changes to the back-end environment.

**Screenshots**
![image](https://user-images.githubusercontent.com/44416148/74617778-ba342800-50e3-11ea-9e14-ec022a7f17bf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version: 12.16.0

**Additional context**

**Comment by ammarkarachi** [comment] 2020-02-17 18:40
@awsirkis Can you run the node.js cli as Administrator and rerun the command?

**Comment by awsirkis** [comment] 2020-02-17 19:03
@ammarkarachi same error response
![image](https://user-images.githubusercontent.com/44416148/74680320-1004e080-5175-11ea-8281-cc761ecdd9dd.png)

**Comment by ammarkarachi** [comment] 2020-02-17 19:27
@awsirkis Is the $PATH variable populated?

**Comment by awsirkis** [comment] 2020-02-17 19:34
$PATH contains "C:\Users\awsir\AppData\Roaming\npm" and C:\Program Files\nodejs"

**Comment by ammarkarachi** [comment] 2020-02-18 00:38
@awsirkis I tried it on a windows machine and I wasn't successful in reproducing this issue, but I do have System32 in my path variable other than npm and nodejs paths

**Comment by attilah** [comment] 2020-02-27 19:40
@awsirkis could you please elaborate on this: "After configuring the regular AWS CLI in another CLI"?

Based on the screenshot the next step is the CLI is spawning your default browser with the `https://console.aws.amazon.com` URL and that's where it fails.

Could you please tell me what is your default browser? Would you change that setting in Windows and retry the same command? unfortunately I was not able to reproduce it in either way, but it seems to be some local issue launching URLs. It was working from cmd, node.js cmd, non-elevated account.

**Comment by awsirkis** [comment] 2020-02-27 20:15
@attilah My previous default browser was Chromium Edge. I tried the same command on Microsoft Edge, IE11, and Google Chrome to the same result. 

I tried completely reinstalling Node.js to see if that was the problem, but that didn't give a different result

**Comment by attilah** [comment] 2020-02-27 20:38
@imonzalvo since my suspicion is around the `open` failing, would you do these steps:

- create a directory
- npm init -y
- npm i open
- touch index.js
- add this code piece to index.js:
```js
const open = require('open');

try {
    open('https://console.aws.amazon.com', { wait: false });
} catch (e) {
    console.log(e);
}
```
- node index.js

And tell me what happened.

**Comment by awsirkis** [comment] 2020-02-28 22:59
It seems you suspicion was correct @attilah 

`C:\Users\user\test>node index.js
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs: [
    '/s',
    '/c',
    'start',
    '""',
    '/b',
    '"https://console.aws.amazon.com"'
  ]
}`

**Comment by attilah** [comment] 2020-03-05 16:45
@awsirkis from that it seems that launching 'cmd' fails. This is some user/OS level issue you've. Just out of curiosity What happens when you open a cmd and execute this command: `start cmd /s /c start "" /b "https://console.aws.amazon.com"`?

Your OS cannot find `cmd.exe` which is in `C:\Windows\System32`.

Execute `echo %path%` from a `cmd` prompt to see if that directory is in the path or not.

I'm closing the issue as it is a local non CLI related one and the workaround/solution provided above.

**Closed by attilah** 2020-03-05 16:45 UTC
Labels: configure, not-reproducable, pending-triage
