### ISSUE TITLE
Amplify add analytics command doesn't properly set up permissions

### ISSUE THREAD

**Issue by dayhaysoos** [aws-amplify/amplify-cli#10376] opened 2022-05-06 20:20 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.13.1

### Amplify CLI Version

8.1.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No Manual Changes made

### Amplify Categories

auth, analytics

### Amplify Commands

add

### Describe the bug

Running `amplify add analytics` results in Pinpoint being set up incorrectly. It appears that permissions for the cognitoGroups are not handled as expected.

This is the error I get:

`candidatesGroupRole/CognitoIdentityCredentials is not authorized to perform: mobiletargeting:PutEvents on resource: arn:aws:mobiletargeting:us-east-1:`

### Expected behavior

I expect that I should be able to track events and other analytical data from Amplify

### Reproduction steps

`amplify add analytics`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line

candidatesGroupRole/CognitoIdentityCredentials is not authorized to perform: mobiletargeting:PutEvents on resource: arn:aws:mobiletargeting:us-east-1:

```

</details>

**Comment by Straubulous** [comment] 2022-05-06 20:47
This issue is being tracked with https://github.com/aws-amplify/amplify-cli/issues/10086
Work is in progress to address.

**Comment by Straubulous** [comment] 2022-05-06 20:54
This issue is a duplicate of these issues, which are both being actively worked on:
https://github.com/aws-amplify/amplify-cli/issues/4772
https://github.com/aws-amplify/amplify-cli/issues/10086

**Comment by josefaidt** [comment] 2022-05-19 20:31
Closing in favor of tracking existing issue #4772

**Closed by josefaidt** 2022-05-19 20:31 UTC
Labels: bug, analytics, duplicate
