### ISSUE TITLE
Not able to push new lambda function changes via amplify push. Error: Could not find a pipenv site-packages directory 

### ISSUE THREAD

**Issue by heng2j** [aws-amplify/amplify-cli#6159] opened 2020-12-11 22:03 UTC
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

I am not able to do amplify push after making any changes to one of my lambda function. For example simply remove a single space.

I am receiving this error:

```
nstalling dependencies from Pipfile.lock (a65489)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
(node:52398) UnhandledPromiseRejectionWarning: Error: Could not find a pipenv site-packages directory at /Users/heng2j/.virtualenvs/collectorVideosProcessor-r9qVMPot/lib/python3.8/site-packages
    at Object.getPipenvDir (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-python-function-runtime-provider/src/util/pyUtils.ts:24:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-python-function-runtime-provider/src/util/packageUtils.ts:27:21
(node:52398) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:52398) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system

**4.39.0**

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

I am putting my python dependencies in another lambda layer for that lambda function at **opt/python**

And I am using runtime Python 3.7 instead. But I have tried to run Python 3.8

**Expected behavior**

Successful push changes to the lambda function.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. You can use `node -v` to check the node version on your system
   v12.13.0

**Additional context**

**Comment by half2me** [comment] 2020-12-15 16:37
@heng2j I'm having the exact same issue. Have you found a workaround yet?

**Comment by akshbhu** [comment] 2020-12-15 21:21
Hi @half2me , @heng2j 

It looks like pipenv is missing. I have a following questions:

1) Are you able to push functions before this error(selecting python as runtime)?

2) Can you make sure you have pipenv installed and included in your PATH variable(make sure python verison > 3.8)?

**Comment by half2me** [comment] 2020-12-15 21:25
@akshbhu 
1. I got this error the very first time I tried to push my python function.
2. I have it installed:
```bash
➜  ~ python3 --version
Python 3.9.1
➜  ~ pipenv --version
pipenv, version 2020.11.15
```

**Comment by akshbhu** [comment] 2020-12-15 21:40
Can you try this:

1. Install pipenv using ```pip install --user pipenv```.This does a user installation to prevent breaking any system-wide packages.
2. Run ```python -m site --user-base``` to get your  user base binary directory, append bin to the path and add this path to your $PATH variable. You can ```echo $PATH``` if its added or not. 
3. Try ```amplify push``` again.

Let me know if this works for you?

**Comment by heng2j** [comment] 2020-12-17 00:10
For me, I checked that I only have python3.7 in my lambda function's virtualenv. So I have to renamed it manually to 3.8 to fix this issue.

/Users/heng2j/.virtualenvs/collectorVideosProcessor-r9qVMPot/lib/python3.**8**/site-packages

**Comment by kaustavghosh06** [comment] 2020-12-24 20:46
@heng2j @half2me Are you'll unblocked on this issue?

**Comment by jhockett** [comment] 2021-01-05 21:02
Closing due to lack of response.

**Comment by rt-demetri** [comment] 2021-01-06 02:05
`amplify pull` did the trick for me. It must have recreated what was missing (obviously I already had python and pipenv). Think of it this way ... if you were to pick up on a brand new machine, you wouldn't have any of those files under ~/.local/share/virtualenvs or ~/.virtualenvs. That's technically what happened to me (migrated Amplify project to M1 Mac).

**Comment by bjm88** [comment] 2021-01-15 02:09
thanks @rt-demetri  this worked for me

pipenv run amplify push

**Comment by vincent38wargnier** [comment] 2021-01-17 14:58
I had the same problem. 
The solution to solve it was to call python -m site --user-base as @akshbhu said. And then go inside the folder created, and copy the site-package folder into the path given by the pipenv error.

**Comment by bfleming-ciena** [comment] 2021-02-01 19:01
I'm having a similar problem.  When I add a new lambda function I have to cd into the folder and run pipenv shell, then amplify push works.

So I have to have a separate pipenv virtual environment for EVERY lambda function?  Where are the docs on how to properly use pipenv and add a python lambda function with amplify. I should just be able to follow a doc and it should work.

**Comment by michaelbrewer** [comment] 2021-02-13 12:13
But default i still get this issue and i can't do a `amplify function build`. Amplify CLI should fix this out of the box.

**Comment by michaelbrewer** [comment] 2021-02-13 12:15
@bfleming-ciena i agree this is not resolved
@jhockett can you reopen this

**Comment by esotericzhang** [comment] 2021-02-26 05:00
Also seeing this issue. Anyone find a workaround yet? Neither @rt-demetri or @bfleming-ciena solutions worked for me.

**Comment by ousjaguraga** [comment] 2021-03-09 17:34
> I had the same problem.
> For me, the solution to solve it was to call "python3 -m site --user-base" as @akshbhu said. And then go inside the folder created, and copy the site-package folder into the path given by the pipenv error.
> 
> I needed this for an amplify lambda, the default path is not the path used by my lambda.

This worked for me, I don't normally reply lol. Thank you and @akshbhu.

**Comment by michaelbrewer** [comment] 2021-03-09 17:40
Maybe @heitorlessa can help with a suggestion on how to fix this in the Amplify cli?

**Comment by viaSSH** [comment] 2021-03-12 14:07
> For me, I checked that I only have python3.7 in my lambda function's virtualenv. So I have to renamed it manually to 3.8 to fix this issue.
> 
> /Users/heng2j/.virtualenvs/collectorVideosProcessor-r9qVMPot/lib/python3.**8**/site-packages

I have also encountered this problem. 
In my case, pipenv   command makes ~/.local/share/virtualenvs/myPythonAmplify/lib/python3.8
But, I'm using python3.9
So,   I change directory name from python3.8 to python3.9

I don't know why this works, but the problem is solved.
Now I can `amplify push` !!!

**Comment by dcchristopher** [comment] 2021-03-12 14:14
> > For me, I checked that I only have python3.7 in my lambda function's virtualenv. So I have to renamed it manually to 3.8 to fix this issue.
> > /Users/heng2j/.virtualenvs/collectorVideosProcessor-r9qVMPot/lib/python3.**8**/site-packages
> 
> I have also encountered this problem.
> In my case, pipenv command makes ~/.local/share/virtualenvs/myPythonAmplify/lib/python3.8
> But, I'm using python3.9
> So, I change directory name from python3.8 to python3.9
> 
> I don't know why this works, but the problem is solved.
> Now I can `amplify push` !!!

Funny thing you should mention that. I think each first time you run Python in an amplify project, it leaves behind version information in a pipfile or something like that. Subsequent runs with a different version of Python will see the different version listed and you run into situations such as this issue. Another coworker unknowingly updated the pipfile (by means of running a multitude of different pip/pipenv commands) and suddenly I’m not getting the error anymore. Next time I’m in that code, I’ll take a look at the commit.

**Comment by viaSSH** [comment] 2021-03-12 14:57
That's right. Changing "python3.8 to python3.9 version" Methods was only possible **once**....
After that, I use `pipenv run amplify push`   It's Works!!

Maybe my Python version and pipfile have compatibility confilcts.

**Comment by magicalne** [comment] 2021-03-16 03:05
Same problem just resolved.

There is a mistake in the project in my case. My college setup python 3.8 in the functions, but use 3.9 in the Pipefile under the root of project. 

So pipenv kept looking for site-packages under **python-3.9** instead of **python-3.8**.

After set python 3.8 in the pipefile, I followed what akshbhu  said:
- pip install --user pipenv
- export PATH="$HOME/.cargo/bin:$HOME/.local/bin:$PATH" 
- amplify push

It works now.

**Comment by kaustavghosh06** [comment] 2021-03-19 19:28
Closing this issue.
Looks like moving from python3.8 to python3.9 version fixes this issue.

**Closed by kaustavghosh06** 2021-03-19 19:28 UTC
Labels: functions, pending-triage

**Comment by michaelbrewer** [comment] 2021-03-25 14:27
Maybe we can clarify how this should work in the AWS Amplify docs?
