### ISSUE TITLE
Running `amplify api add-graphql-datasource` yields strange error

### ISSUE THREAD

**Issue by NoahGaeta** [aws-amplify/amplify-cli#9228] opened 2021-12-06 15:19 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

12.22.1

### Amplify CLI Version

7.6.2

### What operating system are you using?

mac

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

Following this instruction set https://docs.amplify.aws/cli-legacy/graphql-transformer/relational/, I follow the instructions to exactness. At the point of running `amplify api add-graphql-datasource`, I get a strange error. The documentation seems to be legacy(if you look to where the documentation exists), but I failed to find any updated version.  

### Expected behavior

The amplify command line interface should allow you to run `amplify api add-graphql-datasource` without error. If that command is deprecated it should state as such. 

### Reproduction steps

1. Follow the steps in https://docs.amplify.aws/cli-legacy/graphql-transformer/relational/

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```🛑 There was an error adding the datasource
🛑 Cannot destructure property 'serviceWalkthroughFilename' of 'serviceMetadata' as it is undefined.
TypeError: Cannot destructure property 'serviceWalkthroughFilename' of 'serviceMetadata' as it is undefined.
    at Object.addDatasource (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/src/provider-utils/awscloudformation/index.ts:300:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/src/commands/api/add-graphql-datasource.ts:37:21)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/src/index.ts:222:5)
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:204:3)
    at executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)
```

</details>

**Comment by marcvberg** [comment] 2021-12-06 18:04
Hi @NoahGaeta, could you provide the contents of your config file `./amplify/cli.json`? Want to verify which version of the transformer is enabled

**Comment by NoahGaeta** [comment] 2021-12-06 19:37
@marcvberg After investigating more, I found that graphql-transformer-v2 does not support RDS. I went back to older version of the command line interface and I am able run the command fine(other than postgres not working). I can give you the json if you find my report still relevant, if not I will close the issue.

**Comment by marcvberg** [comment] 2021-12-06 19:40
We would expect that you are still able to add a graphql datasource on the latest version so long as the `transformerVersion` feature flag is set to 1, there are plans to make this available in V2 in the future but you are correct the functionality is currently not supported. If this is broken for V1 on the latest version that's still a concern as we don't want to break existing functionality

**Comment by NoahGaeta** [comment] 2021-12-06 19:49
It was a test project to see what the system feels like, I can no longer recover it but I did not modify the `cli.json` file. So whatever behavior exists for generating that file on the latest cli version should've been mirrored in my environment. Is there any documentation that discusses `transformerVersion`? I totally missed that.

**Comment by marcvberg** [comment] 2021-12-06 19:53
`transformerVersion` determines whether to use the graphQL V1 vs V2 transformer, so if you create a new project but want to use the V1 transformer you'll need to switch it to 1 instead of 2 to use V1. We like to abstract the feature flag details away when possible, it's something that's automatic in the `amplify migrate api` workflow

**Comment by NoahGaeta** [comment] 2021-12-06 19:55
@marcvberg I am not really wondering about that specific flag, I am actually wondering about where other flags/parameters are documented so I know where to look.

**Comment by marcvberg** [comment] 2021-12-06 19:57
It looks like the docs aren't fully up to date with every feature flag released, but generally speaking this is where you would find feature flag information: https://docs.amplify.aws/cli/reference/feature-flags/

**Comment by NoahGaeta** [comment] 2021-12-06 19:58
Got it, I appreciate the help.

**Comment by marco-viewpoint** [comment] 2021-12-08 19:59
I'm getting the exact same crash even with version 1.

I initialized a new project with these flags:
AMPLIFYCLI_GRAPHQLTRANSFORMER__TRANSFORMERVERSION=1
AMPLIFYCLI_GRAPHQLTRANSFORMER__useExperimentalPipelinedTransformer=false
(by default Amplify generates a cli.json with useExperimentalPipelinedTransformer=true, which overwrites the transformer version, so you need that flag as well)

I then added an api and tried add-graphql-datasource.

<details>
<summary>cli.json</summary>

```
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "improvepluralization": false,
      "validatetypenamereservedwords": true,
      "enableiterativegsiupdates": true,
      "secondarykeyasgsi": true,
      "skipoverridemutationinputtypes": true,
      "transformerversion": 1,
      "suppressschemamigrationprompt": true
    },
    "frontend-ios": {
      "enablexcodeintegration": true
    },
    "auth": {
      "enablecaseinsensitivity": true,
      "useinclusiveterminology": true,
      "breakcirculardependency": true,
      "forcealiasattributes": false,
      "useenabledmfas": true
    },
    "codegen": {
      "useappsyncmodelgenplugin": true,
      "usedocsgeneratorplugin": true,
      "usetypesgeneratorplugin": true,
      "cleangeneratedmodelsdirectory": true,
      "retaincasestyle": true,
      "addtimestampfields": true,
      "handlelistnullabilitytransparently": true,
      "emitauthprovider": true,
      "generateindexrules": true,
      "enabledartnullsafety": true
    },
    "appsync": {
      "generategraphqlpermissions": true
    },
    "latestregionsupport": {
      "pinpoint": 1,
      "translate": 1,
      "transcribe": 1,
      "rekognition": 1,
      "textract": 1,
      "comprehend": 1
    },
    "project": {
      "overrides": true
    }
  }
}
```
</details>
<details>
<summary>Crash log</summary>

```
? Please select from one of the below mentioned datasources GraphQL
� There was an error adding the datasource
� Cannot destructure property 'serviceWalkthroughFilename' of 'serviceMetadata' as it is undefined.
TypeError: Cannot destructure property 'serviceWalkthroughFilename' of 'serviceMetadata' as it is undefined.
    at Object.addDatasource (/home/marco/.nvm/versions/node/v17.2.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/src/provider-utils/awscloudformation/index.ts:300:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.run (/home/marco/.nvm/versions/node/v17.2.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/src/commands/api/add-graphql-datasource.ts:37:21)
    at Object.executeAmplifyCommand (/home/marco/.nvm/versions/node/v17.2.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/src/index.ts:222:5)
    at executePluginModuleCommand (/home/marco/.nvm/versions/node/v17.2.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:204:3)
    at executeCommand (/home/marco/.nvm/versions/node/v17.2.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/home/marco/.nvm/versions/node/v17.2.0/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)
```
</details>

**Comment by NoahGaeta** [comment] 2021-12-09 19:14
Reopening for @marco-viewpoint

**Comment by ryanchuleff** [comment] 2021-12-09 22:00
I'm seeing the same error as @marco-viewpoint and my cli.json is identical in terms of flag values.

**Comment by Dennis-Dekker** [comment] 2021-12-18 10:52
Hi, is it possible to use the `add-graphql-datasource` command if you install an old version of the cli? If so, do you know which version allows this? If not, is there any other way to add a datasource (I'm trying to connect Amazon Aurora) to the graphql api?

**Comment by ryanchuleff** [comment] 2021-12-20 16:24
@Dennis-Dekker I was told that the breaking change was introduced in 7.5.0 so in theory if you reverted your CLI to an earlier version than that, you should be able to do it.  I had an earlier version that I was using it with, so I can confirm it does work.

**Comment by Dennis-Dekker** [comment] 2021-12-21 14:50
@ryanchuleff Thanks for your answer, I just noticed that the issue is resolved in the new version of the CLI. After the update, the `add-graphql-datasource` command works again.

**Comment by ryanchuleff** [comment] 2021-12-21 15:39
@Dennis-Dekker thanks for the heads up, I'll grab the latest update.

**Comment by marcvberg** [comment] 2021-12-27 17:25
[9288](https://github.com/aws-amplify/amplify-cli/pull/9288)

**Closed by marcvberg** 2021-12-27 17:25 UTC
Labels: graphql-transformer
