### ISSUE TITLE
Missing/broken resolvers for createdAt and updatedAt

### ISSUE THREAD

**Issue by FizzBuzz791** [aws-amplify/amplify-cli#4613] opened 2020-06-19 08:36 UTC
**Describe the bug**
The CLI automatically generates a subscription, including the createdAt and updatedAt fields, but when triggered, GraphQL returns errors "Cannot return null for non-nullable type 'AWSDateTime!'..."

Given this type isn't in my schema, I can't even control it.

**Amplify CLI Version**
4.21.1

**To Reproduce**
Follow this [workshop](https://aws-fullstack-workshop.dcolcott.com/70_generating_thumbnails/10_processing_photos_with_the_s3_trigger_lambda_function.html) up until this step, but make sure to use the latest Amplify version.

It should fail at the last instruction on the linked page; "Try uploading another photo"

**Expected behavior**
`createdAt` and `updatedAt` are resolved correctly.

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version: 12.16.3

**Comment by attilah** [comment] 2020-06-19 23:53
@FizzBuzz791 thanks for reporting this issue, we'll look into it.

**Comment by FOMSON** [comment] 2020-07-14 16:30
Same issue...

Unpredictable behaviour too - seems to work well in dev environment (on localhost) and breaks on prod.

**Comment by FOMSON** [comment] 2020-07-15 00:15
It seems that AppSync GraphQL schema does somehow include `createdAt` and `updatedAt` fields [even though I do not mention them in my schema]...

![Screen Shot 2020-07-15 at 12 48 39 am](https://user-images.githubusercontent.com/42376164/87487318-4156df00-c635-11ea-990d-df8947801637.png)

It seems to solve itself time-to-time, i.e. `createdAt` and `updatedAt` just disappear from the scheme... maybe with push it with a little tweak to the schema [I juts added empty line breaks to my schema and pushed with Amplify CLI]

HOWEVER!!! THIS SEEMS TO BE A PERSISTENT ISSUE THAT BREAKS FRONTEND with unexpected errors.

**Comment by chantlong** [comment] 2020-07-16 05:55
Can confirm this happened to me. APIs that used to work suddenly don't work because of non-nullable `updatedAt` error.
Added `updatedAt` into the schema as @FOMSON said to fix it. Kind of scary if this happens in `prod` suddenly.

**Comment by SwaySway** [comment] 2020-07-31 01:42
@FizzBuzz791 A few questions here to better understand the issue
I was not able to get this error as I'm able to queries just fine. Did you start using the tutorial with one version and the continue with an updated version?
Before auto population of date fields the CLI would still add createdAt and updatedAt, records should still have the timestamps added. Was the schema setup such that createdAt and updatedAt were not included?

**Comment by FizzBuzz791** [comment] 2020-07-31 01:59
I don't think I changed versions, but I do remember using the latest version rather than the version specified in the tutorial.

My "workaround"/"fix" is as per the other responses; explicitly add the fields to the schema. I think I also tried adding the field to the generated queries, but that's a bad hack as it'll get removed/overwritten next time I change the schema and regenerate the queries.

**Comment by SwaySway** [comment] 2020-07-31 17:44
@FizzBuzz791 
Are there null values for `createdAt` and `updatedAt` in the created dynamodb table?

**Comment by henninghoyer** [comment] 2020-08-02 20:01
I can confirm the issue. I have a subscription for an onCreate Event that looks like this:
```
subscription OnCreateProject {
    onCreateProject {
      id
      number
      name
      description
      createdAt
      updatedAt
    }
  }
```
In the DynamoDB Table the fields createdAt and updatedAt get correctly populated by the resolvers but in my frontend I get the "Cannot return null [...]" error mentioned by @FizzBuzz791. Everything works fine if I remove createdAt and updatedAt from the subscription.

**Amplify Version**
4.26.0

**Comment by FizzBuzz791** [comment] 2020-08-03 01:05
@SwaySway - same as @henninghoyer above, all the fields seem to be fine in the table. I _thought_ that the subscription was missing those fields and I had to add them to get rid of the issue, but @henninghoyer has reproduced the issue more recently than I have, so maybe my memory is wonky.

**Comment by SwaySway** [comment] 2020-08-03 18:49
@henninghoyer @FizzBuzz791 If the resolvers are adding those fields it's possible the mutation's selection set does not include those fields. 

Does `createProject` include `createdAt` and `updatedAt`?

**Comment by chantlong** [comment] 2020-08-03 20:52
Just to reinforce how big of an issue this is, my schema.graphql had 4-5 tables and none of the tables had `updatedAt` explicitly defined.
`updatedAt` does get autopopulated whenever an item is created, which is fine.
All I did was remove 1 attribute which is not a timestamp from one of the tables and after amplify push it broke all my APIs to all 4-5 tables with the "Cannot return null for non-nullable type 'AWSDateTime!' within parent 'Table Name'" error. I had to fix it by adding  the `updatedAt` attribute into the schema.graphql to revive the APIs.
Before I did `amplify push` I did update my CLI to `4.2X...` don't remember. So I'm assuming the push made the resolvers mandatory to have `updatedAt`

**Comment by teezeit** [comment] 2020-08-05 08:27
having the same experience. The createdAt & updatedAt fields are autogenerated in queries.js, but when null in dynamo, it creates an error: "Cannot return null for non-nullable type: 'AWSDateTime'.

**Comment by henninghoyer** [comment] 2020-08-05 13:51
@SwaySway Yes, the mutation does include both `createdAt` and `updatedAt`

```
export const createProject = /* GraphQL */ `
  mutation CreateProject(
    $input: CreateProjectInput!
    $condition: ModelProjectConditionInput
  ) {
    createProject(input: $input, condition: $condition) {
      id
      number
      name
      description
      status
      entries {
        items {
          id
          owner
          duration
          date
          description
          projectID
          createdAt
          updatedAt
        }
        nextToken
      }
      createdAt
      updatedAt
    }
  }
`;
```

**Comment by SwaySway** [comment] 2020-08-05 17:27
@henninghoyer
On running the mutation are there values returned from createdAt and updatedAt? Is it only in a subscription when you see that error?

**Comment by henninghoyer** [comment] 2020-08-06 14:41
@SwaySway I just checked, the mutation does indeed return both values, it is only the subscription.

**Comment by SwaySway** [comment] 2020-08-10 17:45
@henninghoyer The result of the subscription should be the same as the mutation. This sounds like a potential issue with the service. I would recommend their forum. https://forums.aws.amazon.com/forum.jspa?forumID=280

Closing this as a dependency issue with Appsync.

**Closed by SwaySway** 2020-08-10 17:45 UTC
Labels: graphql-transformer, pending-triage

**Comment by duncangroenewald** [comment] 2020-10-08 23:50
So is there a solution for this problem ?

**Comment by FOMSON** [comment] 2020-10-08 23:55
> So is there a solution for this problem ?

https://github.com/aws-amplify/amplify-cli/issues/4613#issuecomment-658474460

Plus the rest of the threat may be useful...

**Comment by duncangroenewald** [comment] 2020-10-09 00:43
> > So is there a solution for this problem ?
> 
> [#4613 (comment)](https://github.com/aws-amplify/amplify-cli/issues/4613#issuecomment-658474460)
> 
> Plus the rest of the threat may be useful...

Huh !  this is #4613

**Comment by cybercussion** [comment] 2021-01-10 16:21
I read this a few times .. some adding:

```
createdAt: AWSDateTime
updatedAt: AWSDateTime
```
to their schema or removing it?
