### ISSUE TITLE
Invalid AttributeDataType input, consider using the provided AttributeDataType enum

### ISSUE THREAD

**Issue by alberto115** [aws-amplify/amplify-cli#9532] opened 2022-01-14 10:37 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

17.3.1

### Amplify CLI Version

7.6.9

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made since the issue start to appear. A custom attribute had been added to the user pool.

### Amplify Categories

auth

### Amplify Commands

push

### Describe the bug

When upgrading to version 7.6.9 from an older version and attempt to push the code to the cloud the UserPool (which has no changes according to the summary) fails to update with the message "Invalid AttributeDataType input, consider using the provided AttributeDataType enum".

This happens using the command line from local with version 7.6.9, and also during the automated deployment in Amplify AWS console.

```
UPDATE_FAILED      UserPool AWS::Cognito::UserPool Fri Jan 14 2022 10:22:22 GMT+0000 (Coordinated Universal Time) Invalid AttributeDataType input, consider using the provided AttributeDataType enum. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: 4ea3a100-a0dd-4a31-a06d-800266fc9e76; Proxy: null)
```

### Expected behavior

The code gets deployed and doesn't try to update attributes.

### Reproduction steps

I need to find which two version cause the issue, as new project won't have the same error.

Basic steps:
1. Create project with old version of CLI or reuse an older project version.
2. run `amplify push`
3. Above error returned when updated UserPool (even if no changes on summary page)

I will try to figure out which version I used at the start of the project (back in July 2021) and try to reproduce the issue with more details.

### Additional information

**Workaround**

Set version of amplify to 7.6.8 locally and in the environment variables in Amplify AWS console.

**Comment by cculler-bioskryb** [comment] 2022-01-14 15:49
I am also receiving this error. Rolling back to 7.6.8 fixed it.

**Comment by johnpc** [comment] 2022-01-14 20:26
Can you please share your user pool configuration?

**Comment by johnpc** [comment] 2022-01-14 20:56
Closing as duplicate of https://github.com/aws-amplify/amplify-cli/issues/9525

**Comment by johnpc** [comment] 2022-01-14 20:59
Please still share your user pool configuration? Also your cli-inputs.json contents on #9525

**Comment by pratikdhody** [comment] 2022-01-15 22:32
Hi,

I'm having the same issue even after being on amplify version 7.6.8.
This seemed to happen to me after adding a new api

Error when running amplify push
```
Resource Name: ap-southeast-2_53aQwmrr9 (AWS::Cognito::UserPool)
Event Type: update
Reason: Invalid AttributeDataType input, consider using the provided AttributeDataType enum. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: 69f5a5c3-19fa-4d9f-aad4-ea98766820dc; Proxy: null)
URL: https://console.aws.amazon.com/cloudformation/home?region=ap-southeast-2#/stacks/arn%3Aaws%3Acloudformation%3Aap-southeast-2%3A158495622644%3Astack%2Famplify-vewwebapp-dev-134339-authvewwebapp5d8cc702-CIHHXDGWYD27%2F871233c0-65f6-11ec-a198-0abe9ed47e04/events
```

my cli-inputs.json for the new api is
```
{
  "version": 1,
  "paths": {
    "/payment": {
      "permissions": {
        "setting": "open"
      },
      "lambdaFunction": "createPayment"
    }
  }
}
```

my cli-inputs.json for auth is
```
{
  "version": "1",
  "cognitoConfig": {
    "identityPoolName": "vewwebapp5d8cc702_identitypool_5d8cc702",
    "allowUnauthenticatedIdentities": false,
    "resourceNameTruncated": "vewweb5d8cc702",
    "userPoolName": "vewwebapp5d8cc702_userpool_5d8cc702",
    "autoVerifiedAttributes": [
      "email"
    ],
    "mfaConfiguration": "OFF",
    "mfaTypes": [
      "SMS Text Message"
    ],
    "smsAuthenticationMessage": "Your authentication code is {####}",
    "smsVerificationMessage": "Your verification code is {####}",
    "emailVerificationSubject": "Your verification code",
    "emailVerificationMessage": "Your verification code is {####}",
    "defaultPasswordPolicy": false,
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": [],
    "requiredAttributes": [
      "email",
      "family_name",
      "given_name"
    ],
    "aliasAttributes": [],
    "userpoolClientGenerateSecret": false,
    "userpoolClientRefreshTokenValidity": 30,
    "userpoolClientWriteAttributes": [
      "email"
    ],
    "userpoolClientReadAttributes": [
      "email"
    ],
    "userpoolClientLambdaRole": "vewweb5d8cc702_userpoolclient_lambda_role",
    "userpoolClientSetAttributes": false,
    "authSelections": "identityPoolAndUserPool",
    "resourceName": "vewwebapp5d8cc702",
    "serviceName": "Cognito",
    "useDefault": "defaultSocial",
    "sharedId": "5d8cc702",
    "userPoolGroupList": [],
    "usernameAttributes": [
      "email"
    ],
    "usernameCaseSensitive": false,
    "hostedUI": true,
    "triggers": {},
    "authRoleArn": {
      "Fn::GetAtt": [
        "AuthRole",
        "Arn"
      ]
    },
    "unauthRoleArn": {
      "Fn::GetAtt": [
        "UnauthRole",
        "Arn"
      ]
    },
    "breakCircularDependency": true,
    "useEnabledMfas": true,
    "dependsOn": [],
    "parentStack": {
      "Ref": "AWS::StackId"
    },
    "permissions": [],
    "hostedUIDomainName": "vewwebappa599d801-a599d801",
    "authProvidersUserPool": [
      "Facebook",
      "Google"
    ],
    "hostedUIProviderMeta": "[{\"ProviderName\":\"Facebook\",\"authorize_scopes\":\"email,public_profile\",\"AttributeMapping\":{\"email\":\"email\",\"family_name\":\"last_name\",\"given_name\":\"first_name\",\"username\":\"id\"}},{\"ProviderName\":\"Google\",\"authorize_scopes\":\"openid email profile\",\"AttributeMapping\":{\"email\":\"email\",\"family_name\":\"family_name\",\"given_name\":\"given_name\",\"username\":\"sub\"}}]",
    "oAuthMetadata": "{\"AllowedOAuthFlows\":[\"code\"],\"AllowedOAuthScopes\":[\"phone\",\"email\",\"openid\",\"profile\",\"aws.cognito.signin.user.admin\"],\"CallbackURLs\":[\"http://localhost:3000/\"],\"LogoutURLs\":[\"https://localhost:3000/signout/\"]}",
    "authProviders": []
  }
}
```

**Comment by johnpc** [comment] 2022-01-19 16:57
Closing as duplicate of #9525

**Closed by johnpc** 2022-01-19 16:57 UTC
Labels: bug, auth, pending-response

**Comment by jk171505** [comment] 2022-01-23 12:48
I have the same problem in v7.6.11

**Comment by vifox001** [comment] 2022-02-02 09:02
I have the same issue in v7.6.5.

**Comment by mandeepsingh-private** [comment] 2022-03-03 18:46
I was able to fix it by rolling back the cli locally to my original version locally

sudo npm install -g @aws-amplify/cli@7.4.0

and then deleting these 2 lines from file amplify/cli.json

These feature flags are defined in the "amplify/cli.json" configuration file and are unknown to the currently running Amplify CLI:

graphqltransformer.securityenhancementnotification
graphqltransformer.showfieldauthnotification
