### ISSUE TITLE
Amplify push randomly restored cloud environment to previous version of it

### ISSUE THREAD

**Issue by alessandromoscato** [aws-amplify/amplify-cli#7476] opened 2021-06-08 00:11 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v12.12.0

### Amplify CLI Version

4.51.3

### What operating system are you using?

Ubuntu 20.04

### Amplify Categories

Not applicable

### Amplify Commands

pull, push

### Describe the bug

I created a new Lambda function in the project and made some changes, then I tried to push it. When I do, I notice in the changes log that one of the functions is marked as Deleted, but obviously I did not delete it. Since this has happened to me before, I already have a "procedure" for such scenario. I do `amplify env pull --restore` to restore the local to the previous cloud version, then I recreate the function and try to push again. Everything seems correct in the changes log, the new function is marked as Created, and the other functions as No change. But when I check on the AWS Console, all the cloud environment has been downgraded to a very old version of it. Now I don't have a way to restore the previous version in the cloud. The local and the remote version are different (since the local is still the up-to-date version) but if I try to push again, the push really behaves as a pull. The change log shows the new functions as Deleted and No change to the already-existing ones.

### Expected behavior

The function that I did not delete should not have been marked as Deleted. The push to the cloud environment should not have randomly restored to a previous  version of it. I should now have a way to at least push again my local version (which is currently the correct one).

As requested by several others users, there should be a clear and simple way to restore to previous cloud versions to avoid such disasters.

### Reproduction steps

I don't know how to reproduce this bug. It has happened to me before that some function are marked as Deleted even though I never deleted them, but this is the first time that the push breaks everything in the cloud environment.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment] 2021-06-09 20:40
Hey @alessandromoscato thanks for raising this! How were the changes made to the project? Were these changes done via the console, cli, mix of both, etc.?

**Comment by alessandromoscato** [comment] 2021-06-09 21:25
Hi @josefaidt, everything was done via cli. The sequence of commands was:

1. `amplify add function`, to create the Lambda function
2. `amplify update api`, to attach the Lambda function to a REST API
3. Made some changes to the source of the function
4. Attempt to `amplify push`, but realized that another function results as Delete even though I hadn't deleted it, therefore I do not proceed with the push
5. `amplify env pull --restore`, to fetch the cloud environment locally. The function created at 1. is correctly deleted from local environment
6. Repeat steps from 1. to 3.
7. `amplify push`, this time everything seems correct. The function (re)created at 6. is marked as Update and no other function is marked as Delete, therefore I proceed with the push.
8. Check in the console and realize that all functions in the project have been "rolled back" to a very old version of the project
9. There is an obvious difference in the local environment (which is still up-to-date) and the cloud environment, therefore I try `amplify push` again. No changes are detected

Hope this more detailed explanation helps reproduce the bug. Obviously, the issue already occurs at 4., but I have perfomed steps 1. to 3. several other times before and everything worked fine.

**Comment by alessandromoscato** [comment] 2021-06-11 13:06
Some of the functions have Lambda layers, but I do not create them (the layers) within the Amplify project. At the moment, I only have one environment.

**Comment by josefaidt** [comment] 2021-06-11 20:34
For the functions that were rolled back, are they all a part of the same lambda layer? Is it just a specific layer?

**Comment by alessandromoscato** [comment] 2021-06-15 19:03
Yes, they were all part of the same layer. By that, I mean that I have several functions that have the same layer attached.

**Comment by josefaidt** [comment] 2021-06-16 19:29
@alessandromoscato were any changes done outside of Amplify in between local changes? I'm not able to reproduce, but I'm thinking there's some drift between what is available locally and what is available in the cloud. There has been significant work done to Lambda Layers in our [most recent release](https://github.com/aws-amplify/amplify-cli/releases/tag/v5.0.0). Can you try upgrading to the latest version of the CLI and see if the issue persists?

**Comment by josefaidt** [comment] 2021-06-29 19:51
Hey @alessandromoscato just wanted to follow up on this issue and see if you are still experiencing it on the [latest version of the CLI](https://github.com/aws-amplify/amplify-cli/releases/tag/v5.0.2)?

**Comment by alessandromoscato** [comment] 2021-06-29 21:56
Hi @josefaidt, sorry for the late response. I have upgraded to the new CLI about a couple of weeks ago and the issue didn't happen for a while. Unfortunately, yesterday it occurred again.

To answer your question above, no changes were done outside Amplify in between local changes. Let me add two more info though: 

1. Not sure if this is relevant but all my Lambda functions are inside a VPC. To allow this, I perform two "manual" steps each time I create a new function. After the first time I push the function to the cloud, in the Management Console I attach a specific policy to the function to allow it to be inside a VPC. Then I modify the (local) cloud formation template to include the VPC and push the function again.
2. I use an EC2 instance as a dev machine. Therefore, I have an AMI that "represents" my dev environment. Each time I work, I create a brand new EC2 instance from the AMI and pull my repo from GitHub. To make sure that the cloud environment and my local environment are aligned, I also run `amplify env pull` before I start working.

Once again, this is my standard set up and usually everything goes smoothly. I have not been able to figure out myself the set of steps that lead to the bug.

**Comment by josefaidt** [comment] 2021-06-30 20:11
Hey @alessandromoscato thank you for the details!

> Then I modify the (local) cloud formation template to include the VPC and push the function again.

I believe this _may_ be causing the drift but I have not been able to reproduce. A couple of follow-up questions:

- are there multiple Lambda Layers in the project where a Lambda may be connected to both layers?
- are the changes made to the Lambda's cloudformation template mimicking what has been performed in the console?
- have you noticed any unwanted changes to the cloudformation templates upon running an Amplify command that are reversing/removing your changes?
- are the associated Lambda Layers also getting rolled back?

**Comment by alessandromoscato** [comment] 2021-07-22 20:59
Hi @josefaidt, the issue has not been happening for a while now. Please find below my answers:

- no, there is just one layer, to which all Lambda functions are connected
- could you please clarify this question?
- no, I check the templates and they seem correct and consistent with what I have done. My understanding is that there is a local copy of the template in a hidden folder, which is used to make the comparison between local and cloud templates. I believe that is the template that gets unwanted changes or rollbacks
- It depends, my impression is that since the aforementioned templates in the hidden folder do not get updated or get rolled back, the status of the project (including the Lambda layers) will be restored to the "version" of those hidden templates

**Comment by josefaidt** [comment] 2021-07-23 15:03
Hey @alessandromoscato thank you for the information and glad to hear you are not experiencing the issue anymore! I have not been able to successfully reproduce with the steps provided, however I do want to continue to keep an eye on this issue. If/when you experience this issue again please provide the steps necessary to reproduce, which will help us better identify what went awry.

I'll close this issue for now, but please respond with the reproduction steps if/when you experience it again and we can re-open and investigate further.

**Closed by josefaidt** 2021-07-23 15:03 UTC
Labels: lambda-layers, not-reproducible, pending-close-response-required, pending-response, pending-triage
