### ISSUE TITLE
User email only sign in

### ISSUE THREAD

**Issue by enier290188** [aws-amplify/amplify-cli#7966] opened 2021-08-16 00:24 UTC
**Please describe which feature you have a question about?**
User Pool atributes.

**Provide additional details**
I want my users to login using only their email, I have been doing the following. See image bellow:
<img width="1927" alt="image-001" src="https://user-images.githubusercontent.com/24461835/129497033-50b2d997-be55-4009-a643-16dc90a189e7.png">

When I use the command "amplify push" and go check I got the following. See image bellow:
<img width="1911" alt="image-002" src="https://user-images.githubusercontent.com/24461835/129497134-cbc7e2c9-4f95-4cb5-a1b1-8960b9aa36d4.png">

I need to know what is the path to follow to get the second option in the second screen shoot.

I have been following the documentation and no result so far

**What AWS Services are you utilizing?**
Amplify and Cognito
@aws-amplify/cli@5.3.0
"aws-amplify": "4.2.3"

**Provide additional details e.g. code snippets**
See images

**Comment by enier290188** [comment] 2021-08-16 17:27
Thank you, I want to add that when I used the amplify admin it works like it should. But not if I do it with CLI. 
I have created a few app in amplify using the CLI to test it, and it never works.

**Comment by josefaidt** [comment] 2021-08-16 17:28
Hey @enier290188 :wave: this seems like a duplicate of https://github.com/aws-amplify/amplify-cli/issues/7833, closing in favor of tracking the existing issue

**Closed by josefaidt** 2021-08-16 17:28 UTC
Labels: transferred

**Comment by enier290188** [comment] 2021-08-16 17:33
Thank you, I will follow it!
