### ISSUE TITLE
IAM provider unauthorized

### ISSUE THREAD

**Issue by ataravati** [aws-amplify/amplify-cli#9204] opened 2021-12-03 17:31 UTC
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**

AppSync

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
7.5.2

**What AWS Services are you utilizing?**
Auth, API, Function, Storage

**Provide additional details e.g. code snippets**

I have two models like this. 

```
type Class 
  @model 
  @auth(rules: [{ 
    allow: owner, 
    identityClaim: "sub" 
  }      
  {
    allow: owner
    identityClaim: "sub" 
    ownerField: "studentUserIds"
    operations: [read]
  }
  { 
    allow: private, 
    provider: iam 
    operations: [read]
  }
]) {
  id: ID!
  name: String!
  students: [Student!] @connection(keyName: "ClassStudent", fields: ["id"])
}


type Student
  @model(queries: null)
  @auth(
    rules: [
      { allow: owner, identityClaim: "sub", operations: [create, update, delete, read] }
      { allow: private, provider: iam, operations: [create, update, delete, read] }
      { allow: owner, ownerField: "studentUserId", operations: [update, delete] }
      { allow: private, operations: [read] }
    ]
  )
  @key(name: "ClassStudent", fields: ["classId", "id"]) 
  @key(name: "ClassesByStudent", fields: ["studentUserId"], queryField: "classesByStudent") {
  id: ID!
  classId: ID!
  class: Class @connection(fields: ["classId"])
  studentUserId: ID!
  user: User! @connection(fields: ["studentUserId"])
  owner: String
}
```

When I run the `classesByStudent` using an IAM account, I get an Unauthorized response, even though the IAM provider has read access to the both the Student and Class tables. What am I doing wrong?

**Comment by danielleadams** [comment] 2021-12-13 22:03
@ataravati can provide your `cli.json` file? Your project configuration will affect how `@auth` works. I am particularly interested in the `features.graphqltransformer.useexperimentalpipelinedtransformer` and `features.graphqltransformer.transformerversion` keys. Thank you.

**Comment by benjamindoe** [comment] 2021-12-17 14:47
I think I'm running into something similar. `features.graphqltransformer.useexperimentalpipelinedtransformer: true` and `features.graphqltransformer.transformerversion: 2`. This only breaks for the v2 transformer as this used to work when I was on v1. Migrating from 6.4.0 to 7.6.3 broke things for me. This is my `@auth` directive I'm using

```
@auth(
    rules: [
      { allow: public, provider: iam, operations: [read, create] }
      { allow: private, operations: [read] }
      { allow: owner }
    ]
)
```

**Comment by ataravati** [comment] 2021-12-17 14:52
@danielleadams Here's my `cli.json` file:

```
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "improvepluralization": true,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": false,
      "enableiterativegsiupdates": true,
      "secondarykeyasgsi": true,
      "skipoverridemutationinputtypes": true
    },
    "frontend-ios": {
      "enablexcodeintegration": true
    },
    "auth": {
      "enablecaseinsensitivity": true,
      "useinclusiveterminology": true,
      "breakcirculardependency": true
    },
    "codegen": {
      "useappsyncmodelgenplugin": true,
      "usedocsgeneratorplugin": true,
      "usetypesgeneratorplugin": true,
      "cleangeneratedmodelsdirectory": true,
      "retaincasestyle": true,
      "addtimestampfields": true,
      "handlelistnullabilitytransparently": true,
      "emitauthprovider": true,
      "generateindexrules": true,
      "enabledartnullsafety": true
    },
    "appsync": {
      "generategraphqlpermissions": true
    },
    "project": {
      "overrides": true
    }
  }
}
```

By the way, if I remove `queries: null` on type Student, everything works as expected.

**Comment by danielleadams** [comment] 2021-12-17 20:04
@benjamindoe You are running on a different version of transformers than the issue author - if you are seeing issues, do you mind opening another issue? Thanks!

**Comment by danielleadams** [comment] 2021-12-21 23:01
@ataravati Looking at this, I think that the issue is that `{ allow: owner, identityClaim: "sub", operations: [create, update, delete, read] }` rule on `Student` is preventing IAM access. The rule will protect all the operations from other user access. When I removed the operations from the rule, I got another error message (`Expression block '$[query]' requires an expression`) which I think just needs to be fixed in your schema.

**Comment by ataravati** [comment] 2021-12-21 23:28
@danielleadams This seems to be a bug. As I mentioned, if I remove `queries: null` everything works as expected.

**Comment by danielleadams** [comment] 2021-12-22 00:33
@ataravati We just released transformers V2 a few weeks ago. Would you be able to migrate your schema to use the new version? https://docs.amplify.aws/cli/migration/transformer-migration/

**Comment by ataravati** [comment] 2021-12-22 00:35
@danielleadams Well, I don't need to. As I said, I managed to resolve the issue by removing `queries: null`. Thank you!

**Comment by danielleadams** [comment] 2021-12-22 15:04
Okay. Glad you've solved it - I'll go ahead and close the issue then.

**Closed by danielleadams** 2021-12-22 15:04 UTC
Labels: question, graphql-transformer, pending-response
