### ISSUE TITLE
Can't use the amplify cli anymore... validatetypenamereservedwords, useexperimentalpipelinedtransformer in the cli.json file blocking it. with issue.

### ISSUE THREAD

**Issue by iuyt9003** [aws-amplify/amplify-cli#5949] opened 2020-11-24 14:37 UTC
**Describe the bug**
After I added the API, the local cli.json file blocking me from working with Amplify.
it has an object with 3 keys which 2 of which causing the amplify to crush.

![image](https://user-images.githubusercontent.com/23431551/100107549-6f192380-2e72-11eb-82e8-237654ce65a4.png)
![image](https://user-images.githubusercontent.com/23431551/100107603-7b9d7c00-2e72-11eb-9ff3-0d51c9862bcb.png)

it's blocking me from using the CLI. and I can't take any actions and work with Amplify like that.
I commented them out, but I can't use some features and delete environments because of them.

**To Reproduce**
I have just added an API to my project with Graphql. 
I am using windows 10. my teammates using a mac (on mac it's work good.)

**Expected behavior**
Not to crush...

**Screenshots**
![image](https://user-images.githubusercontent.com/23431551/100107549-6f192380-2e72-11eb-82e8-237654ce65a4.png)
![image](https://user-images.githubusercontent.com/23431551/100107603-7b9d7c00-2e72-11eb-9ff3-0d51c9862bcb.png)

**Comment by sammartinez** [comment] 2020-11-24 17:57
Transferring this issue to Amplify CLI as this seems to be related to CLI vs JavaScript. cc @renebrandel for visibility

**Comment by ammarkarachi** [comment] 2020-11-24 18:31
@iuyt9003 Which amplify version are you using?

**Comment by iuyt9003** [comment] 2020-11-24 22:57
V4.34.0 and V4.30.0 I tried on both @ammarkarachi

**Comment by iuyt9003** [comment] 2020-11-25 17:41
any update maybe? I can't work now. this is really an issue. CLI is blocked for any command.

**Comment by akshbhu** [comment] 2020-11-25 19:42
Hi @iuyt9003 

Maybe I am wrong here but as posted in image above, Can you put a comma after ```addmissingownerfields``` flag.
Let me know if that works?

**Comment by iuyt9003** [comment] 2020-11-26 10:18
Hey @akshbhu it's working when I put a comment on the 2 others.
validatetypenamereservedwords, useexperimentalpipelinedtransformer

the addmissingownerfields does not intrrupt. but I can't use some of the features of the CLI (kind of blocked).

**Comment by idanlo** [comment] 2020-11-26 11:28
I'm having the same issue. Works on my machine (MacOS), but build fails on Amplify Console, we cannot deploy our web app

**Comment by ammarkarachi** [comment] 2020-11-29 22:07
@iuyt9003 What do you mean by you can't use some features? you would have more luck explaining clearly what is it that was desired and what was the outcome to get your issue resolved.

**Comment by iuyt9003** [comment] 2020-11-30 01:40
Hey @ammarkarachi , yes of course.
I am only able to use the CLI when I put a comment out these flags.
but some of the features I use with the CLI even if I comment them out still getting the error.
example deleting env.

**Comment by ammarkarachi** [comment] 2020-11-30 02:20
@iuyt9003 What's the delete error?

**Comment by ammarkarachi** [comment] 2020-11-30 22:49
@iuyt9003 

 >Maybe I am wrong here but as posted in image above, Can you put a comma after addmissingownerfields flag. Let me know if that works?

Just to be sure we meant the word 'comma' not 'comment'

Can you use the following json in your `cli.json` file and try it out? 
```json
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": false
    }
  }
}
```

**Comment by iuyt9003** [comment] 2020-12-01 13:25
@ammarkarachi this is not working : P,
I meant comment out, this it's working but I have still limits on the CLI actions I can do.
![image](https://user-images.githubusercontent.com/23431551/100746439-603dee00-33e9-11eb-9dd9-187dbccabb66.png)
Added a picture of how I configure it for now to use some of the CLI features.

**Comment by iuyt9003** [comment] 2020-12-01 13:27
![image](https://user-images.githubusercontent.com/23431551/100746671-b317a580-33e9-11eb-8c87-62e0099f73cf.png)
Full image display

**Comment by iuyt9003** [comment] 2020-12-07 11:50
any news? I am almost fully blocked from working

**Comment by vikrantRajan** [comment] 2020-12-08 01:13
I have nearly the same error, but I face this issue when I am trying to deploy the app on amplify. 

Everytime the command "amplifyPush --simple" runs I get this JSONValidator error (see image attached)

Because of this I can't push my project and deploy it all. I am not sure why this is happening, but im certain that "graphqltransformer" is coming from the cli.json file, it keeps having an issue with what is written on that file.

I tried to delete the entire block (the object  "graphqltransformer", see 2nd image attached ), and the CLI made some more progress in the build but then failed to say "No updates are to be performed.". (thats because i cleared the file and there was nothing there). So I think it had something to do with the way things are setup. Any help on how to resolve this issue would be fantastic!  

<img width="1278" alt="Screen Shot 2020-12-07 at 5 08 28 PM" src="https://user-images.githubusercontent.com/48606890/101423872-d55c6800-38ae-11eb-9f19-0dee5957038c.png">



<img width="1280" alt="Screen Shot 2020-12-07 at 5 12 15 PM" src="https://user-images.githubusercontent.com/48606890/101424161-67fd0700-38af-11eb-8979-50596386174f.png">

**Comment by kaustavghosh06** [comment] 2020-12-08 01:34
@vikrantRajan do you have an Amplify CLI version pinned for your backend build CI/CD?

**Comment by kaustavghosh06** [comment] 2020-12-08 01:36
@iuyt9003 Can you install the latest version of the CLI > 4.37.0 and see if you're getting the same error?
Saw a similar error out here - https://github.com/aws-amplify/amplify-adminui/issues/25 which got resolved by installing the latest version of the CLI locally.

**Comment by iuyt9003** [comment] 2020-12-08 11:11
Hey @kaustavghosh06 yes I will try! Thanks!

**Comment by attilah** [comment] 2020-12-08 15:35
@iuyt9003 the error you see is coming from the fact the CI/CD and the local CLI version is different and between the two versions we added a new feature flag that cannot be interpreted by the old CLI. Removing the feature flags can have unintended side effects and you can end up with different outputs in your local and CI/CD deployed environments. I would suggest to either stay on the latest or on the same version in all your CI/CD pipelines and developer machines. I'm closing the issue as the root cause has been identified if something new comes up feel free to re-open.

**Closed by attilah** 2020-12-08 15:35 UTC
Labels: platform, question

**Comment by murvinlai** [comment] 2020-12-08 21:04
How to check and change the CI/CD version?  I'm using the amplify CLI version 4.38.0. the latest.   And I have no clue how to update the Ci/CD pipeline. it is just the amplify console connecting to my bitbucket.  That's all.   I have been stuck on that for days.

**Comment by vikrantRajan** [comment] 2020-12-08 23:45
@kaustavghosh06 I am not sure how to get the version for the backend build CI/CD. Amplify CLI is 4.38.0. 
I ran these commands
`npm install -g @aws-amplify/cli@latest`
`amplify configure`
`amplify init`
`npm i @aws-amplify/ui-vue`

added the following the main.js file (I am using Vue.js for frontend)
`import Amplify, { Auth } from 'aws-amplify';`
`import awsconfig from './aws-exports';`
`Amplify.configure(awsconfig);`

added the following UI components from the auth
`<template>

  <amplify-authenticator>

    <div>

      My App

      <amplify-sign-out></amplify-sign-out>

    </div>

  </amplify-authenticator>

</template>
`

checked out to my dev env
`amplify env checkout dev [--restore]`

removed my previous auth in dev with 
`amplify remove auth`

then added a fresh auth with default settings for dev
`amplify add auth`

pushed this with
`amplify push`

I have a prod env as well and did the same steps for that, but for now I am testing just the dev branch.
Then I pushed my code to bitbucket. But as you can see in this image from the AWS Amplify Console, any command associated with amplify is failing. I am not sure if I am missing some kind of configuration 

<img width="1041" alt="Screen Shot 2020-12-08 at 3 34 03 PM" src="https://user-images.githubusercontent.com/48606890/101554082-cfc45800-396a-11eb-9042-b21cbbef1b3b.png">

**Comment by idanlo** [comment] 2020-12-13 09:19
> @iuyt9003 the error you see is coming from the fact the CI/CD and the local CLI version is different and between the two versions we added a new feature flag that cannot be interpreted by the old CLI. Removing the feature flags can have unintended side effects and you can end up with different outputs in your local and CI/CD deployed environments. I would suggest to either stay on the latest or on the same version in all your CI/CD pipelines and developer machines. I'm closing the issue as the root cause has been identified if something new comes up feel free to re-open.
> 
> `validateTypeNameReservedWords` was added in 4.32.1 and you can always check feature flags in the [docs](https://docs.amplify.aws/cli/reference/feature-flags#environment-variables).

But the error that most of us are getting comes from the Amplify Console that builds the application, it somehow uses a certain version of the Amplify CLI that doesn't support these features, and I hope you see how absurd this is that we cannot *easily* control or see the CLI version in the console, when both products are coming from the Amplify team.

**Comment by iuyt9003** [comment] 2020-12-13 09:37
Hey, Thanks guys! I understand what happened
Hard to understand it by myself. 

Thanks for the explanation.

**Comment by kahdojay** [comment] 2021-08-20 20:41
Leaving a note here for posterity - if the issue is one of what version the Amplify CLI is being used during CI/CD in Amplify Console, customers can check their Build Settings and leverage the [Live Package Updates](https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html#setup-live-updates) feature to ensure they're using the latest or a specific version of the Amplify CLI.
