### ISSUE TITLE
Pinpoint has a default region

### ISSUE THREAD

**Issue by housekorea** [aws-amplify/amplify-cli#7390] opened 2021-05-24 09:22 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

ap-northeast-2

### Amplify Console feature

Backend builds

### Describe the bug

When I add analytics using "amplify add analytics" make pinpoint in use-west-2 region.

I checked "amplify/backend/anlaytics/{project_name}/pinpoint-cloudformation-template.json"

In json file,  "Mppings" key below "ap-northeast-2" has a "pinpointRegion" : "us-west-2". 

I don't know why cloudformation mapped ap-northeast-2 to us-west-2. 

My ampliyf project based in "ap-northeast-2", but pinpoint project created in "us-west-2", how can I change pinpoint region?

### Expected behavior

Create pinpoint in ap-northeast-2 region.

### Reproduction steps

1. amplify add analytics

**Comment by cjihrig** [comment] 2021-05-24 15:02
I'm going to close this as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/5287. We are planning to add native support for more regions over time, and will provide updates once we have something concrete to share.

**Closed by cjihrig** 2021-05-24 15:02 UTC
Labels: region support

**Comment by housekorea** [comment] 2021-05-24 23:13
My aws cli version 4.51.0. I can't believe old issue not fixed(#5287) until now. I hope that next minor version fix this problems. 

Thanks.
