### ISSUE TITLE
Many to many relationship - nested data doesnt work

### ISSUE THREAD

**Issue by valceaalexandra** [aws-amplify/amplify-cli#5522] opened 2020-10-08 08:56 UTC
**Describe the bug**
I am using Amplify and everything worked fine until now. I built a schema where I have a many-to-many relationship and when I get the data with Datastore the result is not what I expected.

Those are my dependencies
![image](https://user-images.githubusercontent.com/72545568/95430844-0672f780-0955-11eb-8c3b-ae059db7e5ce.png)

My schema looks like this:

```gql
type Question @model {
  id: ID!
  name: String!
  answers: [QuestionAnswer] @connection(keyName: "byQuestion", fields: ["id"])
}

type QuestionAnswer
  @model(queries: null)
  @key(name: "byQuestion", fields: ["questionID", "answerID"])
  @key(name: "byAnswer", fields: ["answerID", "questionID"]) {
  id: ID!
  questionID: ID!
  answerID: ID!
  question: Question! @connection(fields: ["questionID"])
  answer: Answer! @connection(fields: ["answerID"])
}

type Answer @model {
  id: ID!
  name: String!
  questions: [QuestionAnswer] @connection(keyName: "byAnswer", fields: ["id"])
}
```

**The depth is currently 5 but I've tried with 10 and I have the same problem.**

If I try to query from AppSync like this :
![image](https://user-images.githubusercontent.com/72545568/95436164-32de4200-095c-11eb-8d5d-a421427c159f.png)

I get this: 

           "data": {
             "syncQuestionAnswers": {
                "items": [
                  {
                    "question": {
                    "name": "How are you?",
                    "answers": {
                        "items": [
                          {
                            "answer": {
                              "name": "Good"
                            }
                        },
                        {
                            "answer": {
                              "name": "Bad"
                            }
                        }
                      ]
                    }
                  }
                },
                {
                  "question": {
                     "name": "How are you?",
                     "answers": {
                       "items": [
                          {
                            "answer": {
                              "name": "Good"
                            }
                          },
                          {
                            "answer": {
                              "name": "Bad"
                            }
                          }
                        ]
                      }
                    }
                  }
                ]
              }
            }

The question will appear 2 times, because I have 2 answers assigned to it.

However when I use Datastore on the QuestionAnswer model:

async getQuestions() {
      this.questions = await DataStore.query(QuestionAnswer);
      console.log(this.questions);
}

I get this:
![image](https://user-images.githubusercontent.com/72545568/95433601-d4fc2b00-0958-11eb-9245-8a33a90ae1ad.png)

What I would like to happen when I query the data it would be this:

          "question": {
            "name": "How are you?",
            "answers": {
              "items": [
                {
                  "answer": {
                    "name": "Good"
                  }
                },
                {
                  "answer": {
                    "name": "Bad"
                  }
                }
              ]
            }
          }
 
If I'm doing something wrong please tell me what because I'm going crazy :)

**Comment by pascut** [comment] 2020-10-21 18:13
I have the same problem.

I need the nested data for the many to many relationship. There should be a function like: **withAll()** or **with(['first-relation-name', 'second-relation-name',..])** . Some functions like these will help a lot. Or you can just returned the nested data by default.

Is there a workaround? Has someone found a way to make this work?

Thanks.

**Comment by akshbhu** [comment] 2020-10-24 23:53
Hi @valceaalexandra 

Since the ```QuestionAnswer ```table contains two objects ( how are you ? , Good!) and (how are you? , bad!) as you can see in the image you posted above , this is why the syncQuestionAnswers Query is returning both data.

You can try ```SyncQuestions``` Query with same model as you suggested and as your relation is M:N it will find the connected answer. 
For ex this is my syncQuery similar as yours

```graphql
query MyQuery {
  syncQuestions {
    items {
      name
      answers {
        items {
          answer {
            name
          }
        }
      }
    }
  }
}
```
This is the returned output 
```json
    "syncQuestions": {
      "items": [
        {
          "name": "how are you?",
          "answers": {
            "items": [
              {
                "answer": {
                  "name": "bad!"
                }
              },
              {
                "answer": {
                  "name": "good!"
                }
              }
            ]
          }
        }
      ]
    }
  }
```

**Comment by valceaalexandra** [comment] 2020-10-25 12:31
> Hi @valceaalexandra
> 
> Since the `QuestionAnswer `table contains two objects ( how are you ? , Good!) and (how are you? , bad!) as you can see in the image you posted above , this is why the syncQuestionAnswers Query is returning both data.
> 
> You can try `SyncQuestions` Query with same model as you suggested and as your relation is M:N it will find the connected answer.
> For ex this is my syncQuery similar as yours
> 
> ```graphql
> query MyQuery {
>   syncQuestions {
>     items {
>       name
>       answers {
>         items {
>           answer {
>             name
>           }
>         }
>       }
>     }
>   }
> }
> ```
> 
> This is the returned output
> 
> ```json
>     "syncQuestions": {
>       "items": [
>         {
>           "name": "how are you?",
>           "answers": {
>             "items": [
>               {
>                 "answer": {
>                   "name": "bad!"
>                 }
>               },
>               {
>                 "answer": {
>                   "name": "good!"
>                 }
>               }
>             ]
>           }
>         }
>       ]
>     }
>   }
> ```

Thats the problem. When I query from AppSync, I get that output and everything looks fine.

**But when I use DataStore I don't get the nested data:**

![image](https://user-images.githubusercontent.com/72545568/97107146-a0190380-16ce-11eb-8517-b5b5f7b37e03.png)

No answers, only the question.

**Comment by akshbhu** [comment] 2020-10-26 15:49
Hi @valceaalexandra 

Yes , Currently in Datastore doesn't has the feature to fetch related data in the single query to a model. You can track feature request and can comment on it describing your case : https://github.com/aws-amplify/amplify-js/issues/5054

As a workaround you can query the models separately to fetch the connected data. You can find a documentation here: https://docs.amplify.aws/lib/datastore/relational/q/platform/js#querying-relations

I am closing this issue as duplicate of : https://github.com/aws-amplify/amplify-js/issues/5054. If you feel like your case is different , feel free to comment and i will reopen this again.

**Closed by akshbhu** 2020-10-26 15:49 UTC
Labels: DataStore, pending-triage
