### ISSUE TITLE
Support for `AWS_LAMBDA` Authorizer for AppSync

### ISSUE THREAD

**Issue by MontoyaAndres** [aws-amplify/amplify-cli#8194] opened 2021-09-16 14:51 UTC
### Is this related to a new or existing Amplify category?

auth, function, api

### Is this related to another service?

Lambda, AppSync

### Describe the feature you'd like to request

Is there any possibility to support the `AWS_LAMBDA` authorizer for the AppSync API?

What I'm doing right now is to create the Lambda Authorizer through the console:

![image](https://user-images.githubusercontent.com/15065852/133633959-fab015ea-80a4-4d39-881f-fb0949389b74.png)

It works well, but the CLI does not allow me to update the Queries/Mutations/Subscriptions generated to add @aws_lambda as a new authentication method...

### Describe the solution you'd like

Being able to use the `AWS_LAMBDA` Authorization method for custom authentications.

### Describe alternatives you've considered

I don't know any alternative.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment] 2021-09-16 17:13
Hey @MontoyaAndres thanks for raising this! This appears to be a duplicate of https://github.com/aws-amplify/amplify-cli/issues/7963. Closing in favor of tracking existing request, please subscribe to #7963 for further updates 🙂

**Closed by josefaidt** 2021-09-16 17:13 UTC
Labels: feature-request, api-graphql, duplicate
