### ISSUE TITLE
aws-exports file contains values for removed resource

### ISSUE THREAD

**Issue by haverchuck** [aws-amplify/amplify-cli#1691] opened 2019-06-20 16:38 UTC
**Describe the bug**
After running the 'delete' or '<x> remove' commands, the aws-exports file persists old values.

**To Reproduce**
1. Init a JS project with Vue and VS Code.
2. Add and push an auth resource.
3. Run amplify delete or remove the resource.

**Expected behavior**
aws-exports file should not persist values for resources that have been removed.

**Desktop (please complete the following information):**
 - OS: macOS High Sierra

**Comment by kaustavghosh06** [comment] 2019-06-20 17:15
@haverchuck Can you provide specifics? Which resources got removed?
Is it on amplify delete or ampify remove <resource> -> amplify push?

**Comment by haverchuck** [comment] 2019-06-27 16:49
@kaustavghosh06  - Let's say I have an aws-exports file with a value for user pool id  of 'abc'. When I run auth remove and then auth add (which creates a new user pool with id of 'xyz'), I'd expect the exports file to contain 'xyz', but it still contains 'abc'.  I've experienced similar behavior with amplify delete.

**Comment by kaustavghosh06** [comment] 2019-06-27 16:51
@haverchuck I understand with delete we do not delete/remove the exports file but with add abc -> remove xyz and the push the exports file would have the userpoolID of xyz.

**Comment by kaustavghosh06** [comment] 2019-07-03 05:40
@haverchuck  Closing this issue since this was not-reproducible.

**Closed by kaustavghosh06** 2019-07-03 05:40 UTC
Labels: pending-response, pending-triage, platform
