### ISSUE TITLE
Trigger changed to initial default after every deployment

### ISSUE THREAD

**Issue by kevinRR** [aws-amplify/amplify-cli#9229] opened 2021-11-17 16:58 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Not applicable

### Amplify Categories

hosting

### Environment information

<details>

```
suppose I have two triggers CustomMessage and PostConfirmation if I deployed my any branch its changes to none


```

</details>

### Describe the bug

If I set the Lamda function trigger its change to none after every deployment 

### Expected behavior

should not change the Lamda function to none by default

### Reproduction steps

1. let say I set the Lamda function to suppose 'PostConfirmationDev"
2. Then I make deployment to dev server 
3.  My lambda function changed to none from the dropdwon
![Screen Shot 2021-11-17 at 17 55 57](https://user-images.githubusercontent.com/16461178/142245961-110a8015-e4af-4e66-8cd3-af98bd119e8c.png)
![Screen Shot 2021-11-17 at 17 56 10](https://user-images.githubusercontent.com/16461178/142245970-2d90fedf-3727-4eb5-a74a-e5b585d39aa2.png)

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by josefaidt** [comment] 2021-12-06 16:29
Hey @kevinRR and @cespin :wave: thanks for raising this! As @chrisbonifacio mentioned this is a duplicate of #8997 and we'll close in favor of tracking the existing item. Please subscribe to the existing issue for further updates. 🙂 

As a side note, love to see how the overrides were used as a workaround!

**Closed by josefaidt** 2021-12-06 16:29 UTC
Labels: transferred, duplicate

**Comment by hackrx** [comment] 2021-12-06 21:27
Hey @cespin, I tried your solution, but it is not working for me. 
Error: 
```
UPDATE_FAILED      authBlog8xxx3239                     AWS::CloudFormation::Stack Tue Dec 07 2021 02:45:34 GMT+0530 (India Standard Time) Template format error: Unresolved resource dependencies [Blog8xxx3239PreSignup-testapis, Blog8xxx3239PostConfirmation-testapis] in the Resources block of the template

```
And my `override.ts` file: 
```
import { AmplifyAuthCognitoStackTemplate } from '@aws-amplify/cli-extensibility-helper';

export function override(resources: AmplifyAuthCognitoStackTemplate) {
  const newLambdaConfig = {
    ...resources.userPool.lambdaConfig,
};

if (!newLambdaConfig["preSignUp"]) {
    newLambdaConfig["preSignUp"] = {
        "Ref": "Blog8xxx3239PreSignup-testapis"
    };
    newLambdaConfig["postConfirmation"] = {
      "Ref": "Blog8xxx3239PostConfirmation-testapis"
    };
}

resources.userPool.lambdaConfig = newLambdaConfig;
}

```
What I have also tried: 
1. in Ref: Value ->  Blog8xxx3239PreSignup , but didn't worked.
2. in Ref: Value ->  Blog8xxx3239PreSignup-testapisArn , but didn't worked.
3. in Ref: Value ->  arn:aws:iam::6yyy81cc1465:role/Blog8xxx3239PreSignup-testapis, but didn't worked. [Copied arn from IAM console.]
4. n Ref: Value ->  Blog8xxx3239PreSignup-testapis , but it also didn't worked.
Getting the same error in all cases.
Please correct me, if I am missing something.

**Comment by cespin** [comment] 2021-12-09 02:43
Hi @hackrx ,

Are those stack params ? Check the effective CloudFormation file that's being generated by Amplify and the available stack parameters. If the parameter is available you should then be able to Ref it.

In my case all the lambda triggers were already there as params so I didn't have to add them. 

If you need to add params you can leverage Amplify env vars option or you can declare a stack dependency. I declare stack dependencies by manually modifying the team-provider-info.json file and then doing a _amplify env checkout NAME_ command. All dependencies will be available as stack parameters.
