### ISSUE TITLE
Inconsistency w/ allowed Lambda name and @function directive name

### ISSUE THREAD

**Issue by ChrisFieldsII** [aws-amplify/amplify-cli#1591] opened 2019-05-31 01:46 UTC
**Describe the bug**
I made a lambda function which contained an underscore. When using that name within my GraphQL schema @function directive, I received an error that the name is not alphanumeric.
**To Reproduce**
1. Create Lambda with underscore in name which is allowed
2. Create AWS AppSync GraphQL API
3. use @function directive with the created Lambda's name

**Expected behavior**
There is no error when using the Lambda name in @function directive

**Screenshots**
![Screen Shot 2019-05-30 at 8 39 39 PM](https://user-images.githubusercontent.com/38661015/58675864-c55be380-831b-11e9-9bc0-429829c13bed.png)

**Comment by kaustavghosh06** [comment] 2019-06-06 01:21
Closing as this is a duplicate of #1574

**Closed by kaustavghosh06** 2019-06-06 01:21 UTC
