### ISSUE TITLE
Calling `amplify delete` has a `flatMap` error 

### ISSUE THREAD

**Issue by mbalex99** [aws-amplify/amplify-cli#506] opened 2018-11-25 20:03 UTC
**Describe the bug**

I am trying to run `amplify delete` and I get 

**To Reproduce**
1. run `amplify delete` on the cli with version __0.1.35__
2. See error

**Expected behavior**
Amplify deletes resources.

**Screenshots**

```
Maximilians-MacBook-Pro:test-proj maximilianalexander$ amplify delete
? Are you sure you want to continue?(This would delete all the project from the cloud and wipe out all the local amplify resource files) true
✖ An error occurred when deleting the resources
TypeError: Cannot redefine property: flatMap
    at Function.defineProperty (<anonymous>)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/src/utilities/array.ts:9:8)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/src/compiler/legacyIR.ts:10:1)

Cannot redefine property: flatMap
```

**Desktop (please complete the following information):**
 - OS: MacOSX
 - Version: CLI version  __0.1.35__
 - Node Version: __v10.2.1__

**Comment by yuth** [comment] 2018-11-26 18:40
What is the version of node are you using? You can get the version by running `node -v`

**Comment by mbalex99** [comment] 2018-11-26 22:50
@yuth I am runnning__v10.2.1__. Sorry forgot to put that in, I've also added it to the original post.

**Comment by kaustavghosh06** [comment] 2018-11-26 22:52
@mbalex99  Can you run `amplify configure project` from the root of your project and try the command again?

**Comment by yuth** [comment] 2018-11-28 19:29
@mbalex99 could you first uninstall amplify cli and reinstall it back and try the command
```bash
$ npm uninstall -g @aws-amplify/cli
$ npm install -g @aws-amplify/cli
```

**Comment by mbalex99** [comment] 2018-11-29 06:39
:-( Same thing

**Comment by kaustavghosh06** [comment] 2018-12-27 21:43
Closing this issue due to lack of requestor response. Also, the team wasn't able to reproduce this error with the latest version of the CLI. Please feel free to re-open this issue or comment on it if the issue still persists.

**Closed by kaustavghosh06** 2018-12-27 21:43 UTC
Labels: investigating
