### ISSUE TITLE
Feature request: Allow setting default appsync limit for codegen for nested items

### ISSUE THREAD

**Issue by CaptainChemist** [aws-amplify/amplify-cli#3171] opened 2020-01-12 20:23 UTC
**Is your feature request related to a problem? Please describe.**

I know that there is a way to set the default depth limit for codegenning appsync. Along that same line, I'd instead like for there to be a way to set the default limit for returned lists, including those that are nested. Appsync has a conservative limit of 10 and that applies to all the nested items if you don't provide a limit quantity and this is insufficient for many applications.

**Describe the solution you'd like**

I'd like a way to set the default list limit for the output of the codgen in amplify for *nested items*. Let's say that I want my depth limit to be 60- the resulting graphql query would look something like this for a list of courses that have lectures:

```
{
  listCourses(limit:60){
    items{
      id
      lectures(limit:60){
        items{
          id
          title
          order
        }
      }
    }
  }
}
```

Although I can go into my queries.ts file that is created by the amplify codegen and add these limits manually, they will get overwritten the next time I run the codegen.

Ideally, it would be *even* better if we could set the limits based on the type. So I could set a lecture limit and a separate courses list.

**Comment by ammarkarachi** [comment] 2020-01-13 01:36
@CaptainChemist Hey thanks for the request

**Comment by jkeys-ecg-nmsu** [comment] 2020-01-19 05:04
@CaptainChemist I think there may already be a request for this (or at least a closed issue asking how to achieve this). Rather than overwrite the queries, you can [overwrite the request resolver](https://aws-amplify.github.io/docs/cli-toolchain/graphql#custom-resolvers) to have a default limit of 60 rather than 10.  

You can copy the original from `/amplify/backend/api/yourApiName/resolvers/defaultResolver.req.vtl`, then modify the first line the to sixty, like so:


```
#set( $limit = $util.defaultIfNull($context.args.limit, 60) )
```

Note that you won't get "automatic" updates to your one-to-many resolvers that you overwrite, of course. You'll have to merge any changes in yourself until this feature request is implemented.

https://github.com/aws-amplify/amplify-cli/issues/1703#issuecomment-505135290

**Comment by SwaySway** [comment] 2020-02-03 17:42
Closing this as a duplicate of #1703.

**Closed by SwaySway** 2020-02-03 17:42 UTC
Labels: enhancement, graphql-transformer
