### ISSUE TITLE
Cloudformation apply of API stack after CLI multienv to 1.1.2 fails

### ISSUE THREAD

**Issue by chris-merapar** [aws-amplify/amplify-cli#906] opened 2019-02-20 12:07 UTC
**Describe the bug**
Cloudformation apply of API stack after CLI multienv to 1.1.2 fails to move DynamoDB tables from the API stack to the new child stacks, as resources already exist

**To Reproduce**
1. Create API using amplify cli multienv (0.2.1-multienv.40)
2. Upgrade to amplify CLI 1.1.2
3. Execute "amplify init" followed by "amplify push". Note, amplify does not give the warning about migration at this point.
4. Make a small change in the API, e.g. add a field to trigger update
5. Execute "amplify push"
6. Accept warning about migration
7. Push fails and rolls back
8. Inspection of the stacks nested under the API stack in the Cloudformation console reveals the error is causes when creating DynamoDB tables, because the resource already exists in the API stack 

We have a number of envs and saw the same issue in all cases. I also tried making a totally fresh environment with the 1.1.2 CLI and had the same issue.

**Workaround**
The only solution I found was the delete and recreate the API, like this:
1. amplify remove api
2. amplify push
3. restore the API config from git e.g. git reset --hard (assuming at step 1 you had no uncommitted changes)
4. amplify init (to recognise the new API config)
5. amplify push

This does mean you lose all the data in DynamoDB, so it's not a great solution.

**Expected behavior**
Upgrade from multienv to 1.1.2 should work with no data loss

**Desktop (please complete the following information):**
 - OS: Mac 
 - Version 10.12.6

**Additional context**
I noticed the templates in S3 had been updated and the API stack template no longer has DDB tables in. These seem to have moved into child API stacks in the new CLI, one stack per model. In the CF console the template shown for the API stack shows the DDB tables inside it and the DDB tables are listed as resources for the stack (i.e. the way the multienv CLI did it). So the new template from S3 is correct but has not been applied (makes sense, it was rolled back). I then tried to update the CF stack manually in the console, specifying the S3 location for the template. This operation failed with the same error I saw when amplify did this. Given that it looks like CF first tries to update the API child stacks before moving to update the API stack itself, I'm struggling to see how this could ever work. However since I seem to be the only person with this error there must be more to it than this...!

**Comment by mikeparisstuff** [comment] 2019-02-21 18:58
Do you see a 'transform.conf.json' file added to your project. This file should be added when you run migration and contains a set of logical ids that will remain in the root template (e.g. DynamoDB tables & Elasticsearch Domains). When you run migrate, the CLI first deploys an update to the project that removes all the resources that don't contain data (resolvers, data sources, roles, etc) but that retains the resources that contain data. Once this update finishes, it deploys the new nested stack structure but slightly modified such that the resources that contain data remain in the root stack thus preventing the removal of the resources.

**Comment by chris-merapar** [comment] 2019-02-26 11:01
I think I see what is happening now. On an old sandbox env, a transform.json was created for the old resources. We then add some new resources in this sandbox, which are created using the new way (tables in nested stacks). Then the transform.json is checked into a feature branch. If anyone tries to deploy that branch on an env that is created from scratch (including our test and prod envs after the merge to master), then there is an issue because the transform.json is for the sandbox env.

**Comment by mikeparisstuff** [comment] 2019-03-08 21:44
@chris-merapar Thanks for investingating this. Let me try to reproduce this and verify the cause. Do you see that the CLI is removing the transform.conf file when you change environments?

**Comment by kaustavghosh06** [comment] 2019-04-26 19:15
Closing this issue for now and if you're still facing this issue please comment on this thread.

**Closed by kaustavghosh06** 2019-04-26 19:15 UTC
Labels: graphql-transformer, migration, pending-response, question
