### ISSUE TITLE
amplifyxc.config not created when following docs exactly

### ISSUE THREAD

**Issue by hatunike** [aws-amplify/amplify-cli#3580] opened 2020-03-01 07:28 UTC
**Describe the bug**
If you follow the guide [here](https://aws-amplify.github.io/docs/ios/api)exactly you end up with no `amplifyxc.config` file generated, and a project that doesn't build.

**To Reproduce**
1. Go to 'https://aws-amplify.github.io/docs/ios/api'
2. Follow every step of the documentation
3. Open the .xcworkspace file created by CocoaPods
4. "Build your project and you should see the amplify folder, amplifyxc.config"
5. Notice the project fails to build

```
✅ Found Amplify CLI version 4.13.4
An Amplify project is already initialized in your current working directory 😃. Not generating base project.

💥 Amplify setup completed successfully.

Some next steps:
Running the "modelgen" task provided in the amplifytools plugin will allow you to generate models/entities for your GraphQL models
Running the "amplifyPush" task provided in the amplifytools plugin will build all your local backend resources and provision them in the cloud

/Users/USER/Library/Developer/Xcode/DerivedData/SampleAmplify-hhzfcdrcdlvhloejjviixrfxcchs/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/amplify-tools.build/Script-A25A17163ECF22B928D19C9FEBC62DAB.sh: line 18: amplifyxc.config: No such file or directory
```
(looks like it succeeds, but no amplifyxc.config file - and Xcode shows it as failed)
**Expected behavior**
1. The build should succeed
2. I should have a `amplifyxc.config` file in my project folder

**Desktop (please complete the following information):**
- macOS Catalina 10.15.3
- Xcode 11.3.1

**Additional context**
Investigating this bug will ultimately lead to 2 links that are relevant and possibly related. 

[The First One](https://github.com/aws-amplify/amplify-ios/issues/247) will make you think the issue has since been fixed.

[The Second One](https://github.com/aws-amplify/amplify-cli/pull/3312) is the pull request with the supposed fix. 

Both of these indicate the issue should be fixed, but something is still wrong because IF you follow the guide exactly, things won't work.

**Comment by nikhname** [comment] 2020-03-04 21:45
@hatunike @lawmicha  This is not the expected behavior - the amplifyxc.config file should be created even if there is an existing amplify project. Could you try running npm uninstall -g amplify-app and building again? I was not able to reproduce this locally

**Comment by hatunike** [comment] 2020-03-04 21:49
Yeah, the file isn't showing up in Xcode as well as the directory. Yes, I will uninstall and run through again as a fresh run through of the documented steps.

**Comment by prmacias** [comment] 2020-03-06 16:46
I'm having this issue as well -

@hatunike I tried generating the model files but not working for me 

line 18: amplifyxc.config: No such file or directory

I need to reread the steps - I don't plan to use graphql so need to figure out how to remove the model stuff

**Comment by lawmicha** [comment] 2020-03-06 17:19
related https://github.com/aws-amplify/amplify-ios/issues/345

**Comment by nikhname** [comment] 2020-03-09 14:47
@prmacias @hatunike are you using nvm to manage node versions?

**Comment by prmacias** [comment] 2020-03-09 14:51
@nikhname 

yes -

the node version is v12.4.0

**Comment by nikhname** [comment] 2020-03-09 16:33
@prmacias Xcode does not load your shell profile so amplify-app would be installed outside of the nvm directory. ```which amplify-app``` should show you that this is the case. It is likely that you have a broken version of amplify-app installed and ```npm uninstall -g amplify-app``` is not removing it because you are using nvm in your shell. You can try loading a terminal without nvm and uninstalling amplify-app there to ensure that the latest version of amplify-app is installed by the script. We are looking into improving this experience so that this flow is not dependent on your shell profile

**Comment by prmacias** [comment] 2020-03-10 15:08
I checked on it - I couldn't find/google to open the terminal wtihout nvm to install amplify.  So I checked it seems amplify is in nvm. Do I need to uninstall nvm in order to use amplify?

```
(base) user:~ user$ which amplify-app
/Users/user/.nvm/versions/node/v12.4.0/bin/amplify-app
```

```
amplify -version
Scanning for plugins...
Plugin scan successful
4.16.0
```

**Comment by nikhname** [comment] 2020-03-10 16:40
Hello @prmacias. ```/Users/user/.nvm/versions/node/v12.4.0/bin/amplify-app``` is appearing because you installed amplify-app using nvm in the terminal. 

To open a terminal without nvm, in your .bash_profile/.bashrc/.zshrc (whichever shell configuration you used to install nvm) comment out the lines loading nvm: 
```
# export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
```
Then open a new terminal. When you run nvm you should see that the command is not found. 
Then run ```npm install -g amplify-app``` so that the latest version of amplify-app is installed outside of nvm.

**Comment by prmacias** [comment] 2020-03-19 14:39
@nikhname 

Sorry about the delay. That terminal without nvm worked somehow - I had anaconda installed and nvm so I had to comment everything and got the terminal with no nvm commands. I'll be going to work on amplify installation. 

```
user:~ user$ nvm
-bash: nvm: command not found
user:~ user$ amplify --version
Scanning for plugins...
4.13.1
```

**Comment by kaustavghosh06** [comment] 2020-04-24 23:55
@prmacias Closing this issue, let us know if you're still stuck on this.

**Closed by kaustavghosh06** 2020-04-24 23:55 UTC
Labels: amplify-app, enhancement, pending-response
