### ISSUE TITLE
Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: No export named BUT CloudFormation status is: UPDATE_ROLLBACK_COMPLETE

### ISSUE THREAD

**Issue by davidbiller** [aws-amplify/amplify-cli#4877] opened 2020-07-20 09:16 UTC
i tried to get access to storage category in my preSignup. Its not possible because the good old circular error. Than i removed my changes, now i get this error:

Amplify --v -> 4.24.3

UPDATE_FAILED functionaivyusersPreSignup AWS::CloudFormation::Stack Mon Jul 20 2020 10:57:53 GMT+0200 (GMT+02:00) Embedded stack arn:aws:cloudformation:eu-central-1:xxxx:stack/aivy-rn-app-develop-20190803185319-functionaivyusersPreSignup-1Q6DFG41IA5O/a6158660-46a8-11ea-bd52-0a233b5d9d4c was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: No export named apiaivyGraphQLAPIIdOutput:GetAtt:SpaceTable:Name found

i cant push anymore new updates now.
I checked the CloudFormation in WebConsole.

![Bildschirmfoto 2020-07-20 um 11 02 46](https://user-images.githubusercontent.com/7137361/87921157-7bcbdc00-ca7a-11ea-8ded-4ebfceb16edf.png)

**Comment by wongpiwat** [comment] 2020-07-20 11:30
Me too, I have the same problem.

**Comment by davidbiller** [comment] 2020-07-21 14:30
Any news here? i cant push anymore :(

**Comment by davidbiller** [comment] 2020-07-22 09:56
@wongpiwat this is not a storage problem. i tried to update the stack without the cli. tried to update in cloudFormation console. get the same error. 

We cant push anymore, because the cloudformation stack is broken now.

**Comment by davidbiller** [comment] 2020-07-22 10:23
@wongpiwat 

i deleted in amplify/backend/function/aivyusersPreSignup/aivyusersPreSignup-cloudformation-template.json

this:


```
"API_AIVY_SPACETABLE_NAME": {
							"Fn::ImportValue": {
								"Fn::Sub": "${apiaivyGraphQLAPIIdOutput}:GetAtt:SpaceTable:Name"
							}
						},
						"API_AIVY_SPACETABLE_ARN": {
							"Fn::Join": [
								"",
								[
									"arn:aws:dynamodb:",
									{
										"Ref": "AWS::Region"
									},
									":",
									{
										"Ref": "AWS::AccountId"
									},
									":table/",
									{
										"Fn::ImportValue": {
											"Fn::Sub": "${apiaivyGraphQLAPIIdOutput}:GetAtt:SpaceTable:Name"
										}
									}
								]
							]
						},
						"API_AIVY_GRAPHQLAPIIDOUTPUT": {
							"Ref": "apiaivyGraphQLAPIIdOutput"
						},
						"API_AIVY_GRAPHQLAPIENDPOINTOUTPUT": {
							"Ref": "apiaivyGraphQLAPIEndpointOutput"
						}
```

now it works again. 
Seems that the cli is not cleaning the files when 
- amplify function update 
is changing the permissions to access other resources.

**Comment by ammarkarachi** [comment] 2020-07-22 16:22
@davidbiller Did you add the table created by the GraphQL API as the resource?

**Comment by davidbiller** [comment] 2020-07-22 16:25
@ammarkarachi right! After that I got the known circular error. When I do this backwards in the cli, than I have this state above.

**Comment by ammarkarachi** [comment] 2020-07-22 19:56
I was able to reproduce this, it looks like CLI does not remove the Environment Variables from the CFN after a resource access  is removed.

**Comment by davidbiller** [comment] 2020-07-22 19:58
@ammarkarachi right.

This is what i meant when I wrote:

Seems that the cli is not cleaning the files when

amplify function update
is changing the permissions to access other resources.

**Comment by wongpiwat** [comment] 2020-07-23 09:58
> @wongpiwat
> 
> i deleted in amplify/backend/function/aivyusersPreSignup/aivyusersPreSignup-cloudformation-template.json
> 
> this:
> 
> ```json
>    "API_AIVY_SPACETABLE_NAME":{
>       "Fn::ImportValue":{
>          "Fn::Sub":"${apiaivyGraphQLAPIIdOutput}:GetAtt:SpaceTable:Name"
>       },
>       "API_AIVY_SPACETABLE_ARN":{
>          "Fn::Join":[
>             "",
>             [
>                "arn:aws:dynamodb:",
>                {
>                   "Ref":"AWS::Region"
>                },
>                ":",
>                {
>                   "Ref":"AWS::AccountId"
>                },
>                ":table/",
>                {
>                   "Fn::ImportValue":{
>                      "Fn::Sub":"${apiaivyGraphQLAPIIdOutput}:GetAtt:SpaceTable:Name"
>                   }
>                }
>             ]
>          ]
>       },
>       "API_AIVY_GRAPHQLAPIIDOUTPUT":{
>          "Ref":"apiaivyGraphQLAPIIdOutput"
>       },
>       "API_AIVY_GRAPHQLAPIENDPOINTOUTPUT":{
>          "Ref":"apiaivyGraphQLAPIEndpointOutput"
>       }
>    }
> ```
> 
> now it works again.
> Seems that the cli is not cleaning the files when
> 
> * amplify function update
>   is changing the permissions to access other resources.

I confirm this way can solve this problem. Thanks @davidbiller

**Comment by Tguntenaar** [comment] 2020-08-06 08:27
I ran into the same issue. Only after I deleted the cloudformation template file I got this: 
```Following resources failed
✖ An error occurred when pushing the resources to the cloud
Resource is not in the state stackUpdateComplete
ResourceNotReady: Resource is not in the state stackUpdateComplete
    at constructor.setError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/resource_waiter.js:182:47)
    at Request.CHECK_ACCEPTORS (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/resource_waiter.js:44:12)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12)
An error occurred when pushing the function resource```

**Comment by ammarkarachi** [comment] 2020-09-14 21:47
The issue should be resolved in the next release.

**Closed by ammarkarachi** 2020-09-14 21:47 UTC
Labels: bug, functions, pending-release

**Comment by kldeb** [comment] 2021-02-24 19:17
I leave this hear in case anyone else stumbles upon this issue.

In our case, we dropped a table that we granted access to in a lambda then deployed to a new env and got the error message. The missing resource part of the error was in the CF output but buried later down the file.
