### ISSUE TITLE
GraphQLSchema "The specified key does not exist."

### ISSUE THREAD

**Issue by ehalca** [aws-amplify/amplify-cli#4627] opened 2020-06-21 15:36 UTC
**Describe the bug**
`amplify push` fails with:

> **Following resources failed** 
> **Resource Name:** qexdsgmbbrc4ddsothvfik7oauGraphQLSchema (AWS::AppSync::GraphQLSchema)
> **Event Type:** update
> **Reason:** The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 0F36192E4BFA9CC0; S3 Extended Request ID: 2Rf0PcdJSrHP9SFRQLhwKyDovNA76tncyiCAQVA5Z71GOMCXanaqCAUKj/dn1zcMzdLgFrfaQWo=)

**Amplify CLI Version**
4.21.4

**To Reproduce**

- Modify lambda resource
- `amplify push`

**Expected behavior**
Stack deploys successfully.

**Desktop (please complete the following information):**
 - Ubuntu 18.04.4 LTS
 - Node Version: v10.16.3

**Additional context**
I've created a GraphQL resource and some Lambdas. Gave Lambdas access to "GraphQL API" resource.
Modifying lambdas and pushing them worked perfectly until some changes in GraphQL Schema. (added some fields and connections), after which, pushing only lambda resources fails.
But if I modify GraphQL schema along with Lambda, everything works again.
  
![amp succes](https://user-images.githubusercontent.com/6044231/85228692-9cf2cb80-b3ed-11ea-8762-05f03eb7f687.png)
![amp fails](https://user-images.githubusercontent.com/6044231/85228726-c9a6e300-b3ed-11ea-989d-5ff5531f8596.png)

**Comment by tomhirschfeld** [comment] 2020-06-22 05:51
there is a workaround, revert to CLI version 4.21.3 and then force push

**Comment by ehalca** [comment] 2020-06-22 07:35
> there is a workaround, revert to CLI version 4.21.3 and then force push

this works. thank you.

**Comment by attilah** [comment] 2020-06-22 15:37
Closing as duplicate of #4612.

**Closed by attilah** 2020-06-22 15:37 UTC
