### ISSUE TITLE
Updating amplify cli issues

### ISSUE THREAD

**Issue by OukhouyaAyoub** [aws-amplify/amplify-cli#1859] opened 2019-07-18 08:46 UTC
Hello I am facing a very strange issue, I am trying to push changes within my amplify env, but it does not work, I'm getting a CloudFormation error (that I never got before when pushing changes) : 

`CREATE_FAILED xxxxxx-dev-20190xxxxxx327-apixxxxx-xxxx-SpacePost-1MOMW1Cxxxxx AWS::CloudFormation::Stack Mon Jul 15 2019 14:57:12 GMT+0200 (CEST) Export with name yguwd54vxjbkvomojapxxxxx:GetAtt:SpacePostTable:StreamArn is already exported by stack xxxxxxx-dev-2019xxxxxx327-apixxxxxxx-LQxxxxxxISG-Post-10xxxxxxxFL`

I believe that the reason of this : is that my last amplify push was with an amplify CLI version 1.7.6, and that I now updated it and have the 1.7.8 version: what corroborate my thoughts is that we tried to push the same changes in the laptop of a colleague that has amplify CLI version 1.7.6 and it succeeded!

What pisses me off is that the solution for me is to delete everything and redeploy from scratch.

My question is: is there a bug that makes amplify not able to "communicate" with anything deployed with older versions? So when starting a project we don't have to update amplify cli? 

Is there another solution than deleting everything?

**Comment by UnleashedMind** [comment] 2019-07-18 16:41
@OukhouyaAyoub 
@OukhouyaAyoub 
Sorry to hear your frustration, "deleting everything" is definitely not the intended solution.
We've had a couple of bug fixes since version 1.7.8 . 
Could you try to use the latest version 1.8.2 and see if you still have the same issue?

**Comment by kaustavghosh06** [comment] 2019-07-18 18:05
@OukhouyaAyoub Could you please provide your schema? Do you have custom resolvers as well?

**Comment by kaustavghosh06** [comment] 2019-07-18 18:49
This issue seems similar to #1581 and the fix for this is in a PR which we'll merge soon - #1815 
Closing this as a duplicate of #1581

**Closed by kaustavghosh06** 2019-07-18 18:49 UTC
Labels: pending-response, pending-triage, platform
