### ISSUE TITLE
Keep getting auth errors on console build

### ISSUE THREAD

**Issue by incr3m** [aws-amplify/amplify-cli#3422] opened 2020-02-13 00:55 UTC
My current builds are failing right now due to auth errors. It happened after I upgrade amplify-cli version on build settings from 3.15 to 4.13.

![image](https://user-images.githubusercontent.com/3125784/74391045-f9d9e600-4e3d-11ea-905a-35d102eec95f.png)

Already tried click that "Re-authenticate app" button on General Settings and rebuld but it still throwing the same issue

**Comment by attilah** [comment] 2020-02-13 21:21
Closing the issue as the root cause was multiple auth directives which is invalid and validation works  correctly.

**Closed by attilah** 2020-02-13 21:21 UTC
Labels: @auth, graphql-transformer, question
