### ISSUE TITLE
Please provide an update or at least guidance on the bug where AppSync transform violates DynamoDB rules for sparse index for GSI

### ISSUE THREAD

**Issue by arkllc** [aws-amplify/amplify-cli#6278] opened 2020-12-30 03:03 UTC
**Describe the bug**
Creating this issue because I am stuck with this issue and I am not getting any guidance from the AWS Amplify team on how to proceed here. Here is the bug - https://github.com/aws-amplify/amplify-cli/issues/5468

**Amplify CLI Version**
See https://github.com/aws-amplify/amplify-cli/issues/5468

**To Reproduce**
See https://github.com/aws-amplify/amplify-cli/issues/5468

**Expected behavior**
See https://github.com/aws-amplify/amplify-cli/issues/5468

**Desktop (please complete the following information):**
See https://github.com/aws-amplify/amplify-cli/issues/5468

**Additional context**
I first raised this issue in May. Since then many others have faced the issue. Please provide attention to this issue.

Ask - Is there a timeline when the issue will be fixed? Also, please provide your guidance on the design in the interim.

Appreciate your attention.

**Comment by jhockett** [comment] 2020-12-30 18:22
Hi @arkllc. I understand the frustration, but please do not open new issues for existing ones. We do not provide timelines as a general rule of thumb. Closing as a duplicate of #5468.

**Closed by jhockett** 2020-12-30 18:22 UTC

**Comment by arkllc** [comment] 2020-12-31 05:07
ok. Then at least provide an interim solution. You are correct it is extremely frustrating...
