### ISSUE TITLE
Publish entry points last

### ISSUE THREAD

**Issue by GeorgeBellTMH** [aws-amplify/amplify-cli#4210] opened 2020-05-10 01:43 UTC
When running amplify publish -c frequently (ie before cloud front has had a chance to fully cache to all edgepoints) there is a chance that entry points will be pointing to files that haven't been published yet. 

In large SPA this causes chunk 404 errors etc. 

It would be nice if we could set entry points (ie index.html file, and other html files) to publish last, after the entire package has been uploaded to S3. Thus ensuring the chunks are available.

**Comment by josefaidt** [comment] 2022-12-06 21:46
Marking and closing as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/2087

**Closed by josefaidt** 2022-12-06 21:46 UTC
Labels: feature-request, hosting, p4
