### ISSUE TITLE
amplify push throws "An error occurred during the push operation: FeatureFlags is not initialized"

### ISSUE THREAD

**Issue by sanjaykataria10** [aws-amplify/amplify-cli#7068] opened 2021-04-12 18:13 UTC
### Before opening, please confirm:

I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

10.15.3

### Amplify CLI Version

4.47.1

### What operating system are you using?

Windows

### Amplify Categories

auth

### Amplify Commands

push

### Describe the bug

I get the following error when running amplify push

FeatureFlags is not initialized
An error occurred during the push operation: FeatureFlags is not initialized

I am running amplify push after removing current auth, add new auth and enable case insensitivity in cloud formation template for auth.
      UsernameConfiguration:
        CaseSensitive: false

Thanks.

### Expected behavior

amplify push should delete and add new auth.

### Reproduction steps

amplify auth remove
amplify auth add (follow prompts)
change cloud formation template to include 
      UsernameConfiguration:
        CaseSensitive: false

amplify push

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line
2021-04-12T18:12:48.554Z|error : amplify-provider-awscloudformation.push-resources.run([{"resourcesToBeCreated":[{"service":"Cognito","providerPlugin":"[***]rmation","dependsOn":[],"customAuth":false,"resourceName":"[***]pp34e348ed","category":"auth"}],"resourcesToBeUpdated":[],"resourcesToBeSynced":[],"resourcesToBeDeleted":[{"service":"Cognito","providerPlugin":"[***]rmation","dependsOn":[],"providerMetadata":{"s3TemplateURL":"https://s3.amazonaws.com/amplify-amplify-profile-app-prodprof-170611-deployment/amplify-cfn-templates/auth/[***]pp7d1099c3-cloudformation-template.yml","logicalId":"[***]eapp"},"lastPushTimeStamp":"2020-09-09T21:25:20.651Z",""IdentityPoolId":"[***]s-[***]st-[***]3a3a-[***]02-[***]07-[***]99-[***]3e711","IdentityPoolName":"[***]pool_7d1099c3__prodprof","UserPoolName":"[***]_userpool_7d1099c3"},"lastPushDirHash":"sLEZHQZaUlr9VmimfcyuOrdAftE=","resourceName":"amplifyprofileapp","category":"auth"}],"tagsUpdated":false,"allResources":[{"service":"Cognito","providerPlugin":"[***]rmation","dependsOn":[],"customAuth":false,"resourceName":"[***]pp","category":"auth"}]}])
Error: FeatureFlags is not initialized

```

</details>

**Comment by jhockett** [comment] 2021-04-12 18:23
Hi @sanjaykataria10, can you please share the `cli.json` file from your project? It's located at `<project-root>/cli.json` or `<project-root>cli.<environment name>.json`.

**Comment by sanjaykataria10** [comment] 2021-04-13 01:29
Thanks for the response. I will try amplify push as an intermediate step after removing and before adding auth. 

I did try by adding the following cli.json as my init was before the feature flags but this results in the same error.
{
  "features": {
    "auth": {
      "enableCaseInsensitivity": true
    }
  }
}

**Comment by sanjaykataria10** [comment] 2021-04-13 01:31
so just amplify auth remove followed by amplify push gives the same error.

"FeatureFlags is not initialized
An error occurred during the push operation: FeatureFlags is not initialized"

**Comment by sanjaykataria10** [comment] 2021-04-16 16:39
It appears some issue with amplify push. I tried doing an amplify init, add auth and push and I get the same error 

FeatureFlags is not initialized
An error occurred during the push operation: FeatureFlags is not initialized"

Any inputs here will be appreciated.

Thanks.

**Comment by jhockett** [comment] 2021-04-16 17:57
> Thanks for the response. I will try amplify push as an intermediate step after removing and before adding auth.
> 
> I did try by adding the following cli.json as my init was before the feature flags but this results in the same error.
> {
> "features": {
> "auth": {
> "enableCaseInsensitivity": true
> }
> }
> }

@sanjaykataria10 apologies for the late reply. Is this snippet your entire `cli.json` file? If so, that's why nothing is working. The CLI will prevent you from using a new version that your project does not support.

https://docs.amplify.aws/cli/reference/feature-flags#feature-flags

**Comment by sanjaykataria10** [comment] 2021-04-16 18:06
in the last set up, I did amplify init (blank dir), amplify add auth and amplify push. The default cli file is below and I still get the same error on amplify push i.e. Featureflags not initialized.

{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": false,
      "enableiterativegsiupdates": false,
      "secondarykeyasgsi": true,
      "skipoverridemutationinputtypes": true
    },
    "frontend-ios": {
      "enablexcodeintegration": true
    },
    "auth": {
      "enablecaseinsensitivity": true,
      "useinclusiveterminology": true
    },
    "codegen": {
      "useappsyncmodelgenplugin": true,
      "usedocsgeneratorplugin": true,
      "usetypesgeneratorplugin": true,
      "cleangeneratedmodelsdirectory": true,
      "retaincasestyle": true
    },
    "appsync": {
      "generategraphqlpermissions": true
    }
  }
}

**Comment by jhockett** [comment] 2021-04-19 22:46
Hi @sanjaykataria10, can you see if the latest version fixes the issue?

If not, can you share your amplify project folder with us? Please email amplify-cli@amazon.com with the issue number in the subject.

**Comment by sanjaykataria10** [comment] 2021-04-20 02:05
Thanks John. I will try with latest version but this appears to be a problem with my set up. I tried the set up on a different machine (mac) and was able to remove, add new auth and push.

**Comment by jhockett** [comment] 2021-04-20 04:29
Glad to hear you're no longer blocked on this @sanjaykataria10. I'm going to close this issue because we haven't been able to reproduce this, but if you run into this again, comment below and we can re-open to take another look.

**Closed by jhockett** 2021-04-20 04:29 UTC
Labels: pending-triage, platform, windows
