### ISSUE TITLE
@searchable - wrong data type in ElasticSearch

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-cli#4436] opened 2020-06-02 02:51 UTC
**Describe the bug**

My schema.graphql has defined a fields as a String

```
userField01: String
userField02: String
userField03: String
```
But when the data is sent to ElasticSearch the TYPE is not sent to ElasticSearch - seems that whatever the data looks like means the type is inferred. This then means records that don't have this format won't sync. For example, if I have a field as type String and my first record is 45.37 it creates a float type in ElasticSearch, so if the next record is 27 ABC then it fails.
```
userField01  text
userField02  date
userField03  text
```

**Amplify CLI Version**
4.21.0

**To Reproduce**
I believe that if you create a field with type string, then add data in the form of a Float to that string field it will create a field of type Float in ElasticSearch which means string data will fail.

**Expected behavior**
I expect the schema that we have defined in schema.graphql will be honoured in ElasticSearch so that data can stream.

**Additional context**
If the schema from AppSycn is not reflected in ElasticSearch then data will fail to stream.

**Comment by nikhname** [comment] 2020-06-02 18:15
@sacrampton just trying to make sure I understand - in your example the record "45.37" is of String type in your schema?

**Comment by sacrampton** [comment] 2020-06-02 21:40
Hi @nikhname 

In my example above I didn't use specific data examples. However, here I will. I have a field called userField10 in AppSync which is of type String. However, in ElasticSearch it is of type date.

So if I do a query of ElasticSearch as follows to see some of the data it shows they are indeed all in date format. The simple query is as follows

```
query searchAssets{
  searchAssets(
    filter:{  userField10: {exists:true}  }
    limit: 5
  )
  {items{userField10}}
}
```

The data generated from the query is as follows:

```
{ "data": {
    "searchAssets": {
      "items": [
        {  "userField10": "2017-02-14" },
        {  "userField10": "2016-07-10" },
        {  "userField10": "2016-02-12" },
        {  "userField10": "2016-07-10" },
        {  "userField10": "2016-08-30" }
      ]
} } }
```

**Comment by SwaySway** [comment] 2020-06-05 17:46
Hello @sacrampton 
The reason this is happening is because the lambda trigger will push the record from the dynamodb stream into elasticsearch. During this time the types being used in the record are inferred. This is something we are looking into to addressing.

A potential workaround would be to re-index the ES Cluster this way you can ensure the types in your Cluster are in parity with the your types defined in AppSync.
Re-Index Docs: https://www.elastic.co/guide/en/elasticsearch/reference/6.2/docs-reindex.html
Re-Index Sample Python Script: https://gist.github.com/SwaySway/41548b31f48b00dc18080c08d1583601

Closing as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/3340.
Please follow that thread for updates.

**Closed by SwaySway** 2020-06-05 17:46 UTC
Labels: @searchable, graphql-transformer, pending-triage

**Comment by sacrampton** [comment] 2020-06-07 23:58
Hi @SwaySway - thanks for this. When AppSync's function sets up the sync to ElasticSearch it is creating keyword fields (ie. name and name.keyword). My application uses these keyword fields. The reindex seems to be only copying the name and not the name.keyword. Appreciate any insight that you might have here.

**Comment by sacrampton** [comment] 2020-06-08 06:35
Got this working so thought I'd document the process that worked for me in case its helpful for anyone else. I was seeking to reindex an index called asset. So I opened up the console in Kibana and executed the following. Firstly I needed to create a new index which I called new index.

```
PUT /new_asset
```
Then I needed to define the "schema" for the new index so there would be no inferring. Some example fields are shown. To generate this I cut/paste from the schema.graphql for this particular type/index then map the fields as shown.
```
PUT /new_asset/_mapping/doc
{
    "properties": {
        "id": {"type": "text", "fields": {"keyword": {"type": "keyword", "ignore_above": 256}}},
        "acquisitionDate": {"type": "date"},
        "acquisitionValue": {"type": "float"},
        "assetVisitQueue": {"type": "integer"},
        "auditCompleted": {"type": "boolean"},
        "geolocation": {"type": "geo_point"}
    }
}
```
For text, originally I just used "type" : "text" and it didn't create the keyword field (ie. id.keyword) which allows you to search exactly on an ID. However, if I specify it as shown above that works.

Then I reindex from asset to new_asset as shown.
```
POST _reindex
{
  "source": {
    "index": "asset"
  },
  "dest": {
    "index": "new_asset"
  }
}
```

So then I delete the original index as shown and create it again and define mappings.

```
DELETE /asset
PUT /asset
PUT /asset/_mapping/doc
{
    "properties": {
        "id": {"type": "text", "fields": {"keyword": {"type": "keyword", "ignore_above": 256}}},
        "acquisitionDate": {"type": "date"},
        "acquisitionValue": {"type": "float"},
        "assetVisitQueue": {"type": "integer"},
        "auditCompleted": {"type": "boolean"},
        "geolocation": {"type": "geo_point"}
    }
}
```

Then from there I reindex back from new_asset to asset.

```
POST _reindex
{
  "source": {
    "index": "new_asset"
  },
  "dest": {
    "index": "asset"
  }
}
```

After I do that then my app is working exactly as before, except now the types in ElasticSearch match the types as defined in AppSync.

If anyone has a better way than what I've shown here then I'd love to hear it.
