### ISSUE TITLE
Empty backend amplify project keeps failing irregularly

### ISSUE THREAD

**Issue by jfdesgagne** [aws-amplify/amplify-cli#9161] opened 2021-12-01 06:16 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

17.0.1

### Amplify CLI Version

7.5.4

### What operating system are you using?

Mac

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

When I push new commit to github, during the amplify build process, it sometimes fails during the backend phase. The only thing in my amplify project is out of the box hosting and auth.                                

### Expected behavior

Backend build should succeed

### Reproduction steps

1. Commit new code to github
2. Wait until amplify capture the changes and kick off a new build
3. From time to time, the backend part would fail.
4. Usually, restarting the build from the console would work, sometime it takes 2-3 tries without changing anything.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
 ## Checking for associated backend environment...
                                 ## Backend environment association found
2021-12-01T06:03:12.679Z [INFO]: [0mAmplify AppID found: d21d5zdo7fygu8. Amplify App name is: ledticker[0m
2021-12-01T06:03:12.759Z [INFO]: [0mBackend environment dev found in Amplify Console app: ledticker[0m
2021-12-01T06:03:13.973Z [WARNING]: - Fetching updates to backend environment: dev from the cloud.
2021-12-01T06:03:15.012Z [WARNING]: - Building resource auth/ledticker88d61bd7
2021-12-01T06:03:15.222Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
2021-12-01T06:03:15.248Z [WARNING]: ✖ There was an error initializing your environment.
2021-12-01T06:03:15.254Z [INFO]: [31mFailed to pull the backend.[39m
2021-12-01T06:03:15.255Z [INFO]: [31mauth headless is missing the following inputParams facebookAppIdUserPool, facebookAppSecretUserPool, googleAppIdUserPool, googleAppSecretUserPool, loginwithamazonAppIdUserPool, loginwithamazonAppSecretUserPool[39m
2021-12-01T06:03:15.260Z [INFO]: [0mError: auth headless is missing the following inputParams facebookAppIdUserPool, facebookAppSecretUserPool, googleAppIdUserPool, googleAppSecretUserPool, loginwithamazonAppIdUserPool, loginwithamazonAppSecretUserPool[0m
                                 [0m    at updateConfigOnEnvInit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/index.js:136:15)[0m
                                 [0m    at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/index.js:349:28[0m
                                 [0m    at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18[0m
                                 [0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m
2021-12-01T06:03:15.286Z [ERROR]: !!! Build failed
2021-12-01T06:03:15.286Z [ERROR]: !!! Non-Zero Exit Code detected
2021-12-01T06:03:15.286Z [INFO]: # Starting environment caching...
2021-12-01T06:03:15.287Z [INFO]: # Uploading environment cache artifact...
2021-12-01T06:03:15.389Z [INFO]: # Environment caching completed
Terminating logging...
```

</details>

**Comment by danielleadams** [comment] 2021-12-21 23:04
@jfdesgagne can you give details of your auth configuration? Or the steps you took to set it up?

**Comment by jfdesgagne** [comment] 2021-12-21 23:10
@danielleadams Thank you for looking into this. I've setup the auth module using the CLI tool, and I'm using the `Default configuration with Social Provider (Federation)` option with every social provider configured.

**Comment by GanymedeIndustries** [comment] 2021-12-22 01:32
Hi @danielleadams, not too sure if its related or not but my builds also fail in the backend phase with an empty log in the amplify console (https://github.com/aws-amplify/amplify-cli/issues/9367).

Please let me know if this is a direct duplicate and I'll close it. Cheers.

**Comment by josefaidt** [comment] 2022-06-22 18:49
Closing due to inactivity. @jfdesgagne if you are still experiencing this issue please open a new [bug report](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml) with minimal reproduction steps to investigate further

**Closed by josefaidt** 2022-06-22 18:49 UTC
Labels: hosting, headless
