### ISSUE TITLE
AWS Amplify eu-west-3 Paris

### ISSUE THREAD

**Issue by rudyhadoux** [aws-amplify/amplify-cli#7794] opened 2021-07-24 09:13 UTC
Hi,
It seems impossible to configure the eu-west-3 region for Amplify-cli.
Why ?

**Comment by johnpc** [comment] 2021-07-30 19:30
eu-west-3 is a newer region and it's taken a while for all the services amplify depends on to add support for it.

Based on [the regional product services page](https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/) it looks like most of them have now. We would need to dig in a bit more in depth to verify, but at a glance the big ones are supported.

It may be possible for us to add this to the CLI. I'll mark this as a feature request and share with the team.

**Comment by rudyhadoux** [comment] 2021-07-30 19:36
Yes BUT, it seems that CLI is the only way to set the region.
So now it is impossible to use eu-west-3 Amplify services.

**Comment by sebsto** [comment] 2021-09-01 08:45
duplicate of https://github.com/aws-amplify/amplify-cli/issues/5832

**Comment by magrinj** [comment] 2021-09-01 12:10
@johnpc It's been almost a year now, I can understand `amplify` depends on multiple packages, but a year for a region it's quite a lot...
I've tried to make a PR here: #8056 
Not sure if it's the right way to implement it, but seems to works locally.

**Comment by rudyhadoux** [comment] 2021-09-01 12:15
Hi @magrinj, 
Does your solution work only by changing those config files in the Amplify folder ?
If so, it's good to know.

**Closed** 2021-09-01 19:28 UTC
Labels: feature-request, platform, region support
