### ISSUE TITLE
Auth Trigger Function environment variables not configured correctly

### ISSUE THREAD

**Issue by wderezin** [aws-amplify/amplify-cli#6361] opened 2021-01-11 03:14 UTC
**Describe the bug**

When creating an Auth PostConfirmation function for a coginito the following environment variables are not correctly:  `API_<APPID>_GRAPHQLAPIENDPOINTOUTPUT`   and   `API_<APPID>_GRAPHQLAPIIDOUTPUT`

The values are 
```
API_<APPID>_GRAPHQLAPIENDPOINTOUTPUT   = api<APPID>GraphQLAPIEndpointOutput
API_<APPID>_GRAPHQLAPIIDOUTPUT = api<APPID>GraphQLAPIIdOutput
```

**Amplify CLI Version**

```
# amplify -v
4.41.1
```

**To Reproduce**

My steps using `amplify update auth` to the Post Confirmation lambda function.

```
# amplify update auth
Please note that certain attributes may not be overwritten if you choose to use defaults settings.

You have configured resources that might depend on this Cognito resource.  Updating this Cognito resource could have unintended side effects.

Using service: Cognito, provided by: awscloudformation
 What do you want to do? Walkthrough all the auth configurations
 Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AWS IAM controls (Enables per-user Storage features for images o
r other content, Analytics, and more)
 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) No
 Do you want to enable 3rd party authentication providers in your identity pool? No
 Do you want to add User Pool Groups? No
 Do you want to add an admin queries API? No
 Multifactor authentication (MFA) user login options: OFF
 Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
 Please specify an email verification subject: Your verification code
 Please specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? No
 Specify the app's refresh token expiration period (in days): 30
 Do you want to specify the user attributes this app can read and write? No
 Do you want to enable any of the following capabilities? 
 Do you want to use an OAuth flow? No
? Do you want to configure Lambda Triggers for Cognito? Yes
? Which triggers do you want to enable for Cognito (Press <space> to select, <a> to toggle all, <i> to invert selection)
❯◯ Learn More
 ──────────────
 ◯ Create Auth Challenge
 ◯ Custom Message
 ◯ Define Auth Challenge
 ◯ Post Authentication
 ◉ Post Confirmation

```

Also, run `amplify update function` and add permission to access the API. 

Once the above is configured, then 
```
# amplify push
```

Then from the console check your environment variables on the lambda configuration screen.

...

**Expected behavior**

The environment variable values for the lambda
```
API_<APPID>_GRAPHQLAPIENDPOINTOUTPUT   =  https://<GRAPH_HOSTBNAME/graphql
API_<APPID>_GRAPHQLAPIIDOUTPUT = <RANDOM_ALPHANUMERIC>
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

```
Mac os 11.1 
# node -v
v10.23.0
```

**Additional context**

Screen shot of lambda environment configuration

<img width="1041" alt="Screen Shot 2021-01-10 at 21 59 22" src="https://user-images.githubusercontent.com/10068775/104143962-831bd480-538f-11eb-948d-671b28dc96e3.png">

**Comment by attilah** [comment] 2021-01-11 23:29
@wderezin I was not able to reproduce it on my end since doing the same steps I had correct env vars:

![image](https://user-images.githubusercontent.com/230432/104249971-64661e00-5421-11eb-8085-025cea2d2b95.png)

When you see the strings you see they are coming from the "DefaultValue" specification inside of the Function's CFN template:

```json
    "apifffffffGraphQLAPIIdOutput": {
      "Type": "String",
      "Default": "apifffffffGraphQLAPIIdOutput"
    },
    "apifffffffGraphQLAPIEndpointOutput": {
      "Type": "String",
      "Default": "apifffffffGraphQLAPIEndpointOutput"
    },
    "apifffffffGraphQLAPIKeyOutput": {
      "Type": "String",
      "Default": "apifffffffGraphQLAPIKeyOutput"
    }
```

And the value for these are being supplied from the root stack template in `amplify/backend/awscloudformation/nested-cloudformation-template.yml`:

```
          "apifffffffGraphQLAPIIdOutput": {
            "Fn::GetAtt": [
              "apifffffff",
              "Outputs.GraphQLAPIIdOutput"
            ]
          },
          "apifffffffGraphQLAPIEndpointOutput": {
            "Fn::GetAtt": [
              "apifffffff",
              "Outputs.GraphQLAPIEndpointOutput"
            ]
          },
          "apifffffffGraphQLAPIKeyOutput": {
            "Fn::GetAtt": [
              "apifffffff",
              "Outputs.GraphQLAPIKeyOutput"
            ]
          },
```

And these are dynamic values being replaced with the actual values from the GraphQL APIs stack.

Could you please double check if you have the same pieces in your project?

**Comment by wderezin** [comment] 2021-01-12 01:53
I was able to track the issue down in the cloud formation templates. 

Below is the configuration for my PostConfirmation function.  Here is the configuration for the function missing the parameters.

```
    "functionXXXXXXXXX5221197dPostConfirmation": {
      "Type": "AWS::CloudFormation::Stack",
      "Properties": {
        "TemplateURL": "https://s3.amazonaws.com/amplify-XXXXXXXXX-walter-113614-deployment/amplify-cfn-templates/function/XXXXXXXXX5221197dPostConfirmation-cloudformation-template.json",
        "Parameters": {
          "modules": "add-to-group,custom",
          "resourceName": "XXXXXXXXX5221197dPostConfirmation",
          "env": "walter"
        }
      }
    },
```

It is missing the following Parameters like the other functions configured for API access
```
          "apiXXXXXXXXXGraphQLAPIIdOutput": {
            "Fn::GetAtt": [
              "apiXXXXXXXXX",
              "Outputs.GraphQLAPIIdOutput"
            ]
          },
          "apiXXXXXXXXXGraphQLAPIEndpointOutput": {
            "Fn::GetAtt": [
              "apiXXXXXXXXX",
              "Outputs.GraphQLAPIEndpointOutput"
            ]
          },
```

**Comment by wderezin** [comment] 2021-01-12 02:01
I checked the PostConfirmation permissions to access the API and enabled read/update/create/delete and now get the following cloud formation circular error:
```

⠴ Updating resources in the cloud. This may take a few minutes...Error updating cloudformation stack
✖ An error occurred when pushing the resources to the cloud

Circular dependency between resources: [UpdateRolesWithIDPFunctionOutputs, apiXXXXXXXXX, functionXXXXXXXXX5221197dPostConfirmation, functionXXXXXXXXXAnswerUpdate, functionXXXXXXXXXMoreAnswers, authXXXXXXXXX5221197d, UpdateRolesWithIDPFunction]
An error occurred during the push operation: Circular dependency between resources: [UpdateRolesWithIDPFunctionOutputs, apiXXXXXXXXX, functionXXXXXXXXX5221197dPostConfirmation, functionXXXXXXXXXAnswerUpdate, functionXXXXXXXXXMoreAnswers, authXXXXXXXXX5221197d, UpdateRolesWithIDPFunction]

```

**Comment by wderezin** [comment] 2021-01-12 11:57
I think issue is really "When in enabling a Auth function for API access a cloudformation circular reference is generated'

So I did another test with adding a `PostAuthentication` function and I caused the same results/error as above with the circular reference.

**Comment by attilah** [comment] 2021-01-12 17:13
Circular dependency is a side effect since you create a circular reference between auth, api, function resource. Unfortunately it cannot be solved in an automated way with single CF deployment and Amplify created resource references, what you can do as a workaround is to extract out the generated access policy as a custom resource and use amplify to deploy it. Also the env vars has to be set manually for the function.

I'm closing the issue as the original problem was probably because of a misconfiguration of the cross category resource access.

Related issues:
https://github.com/aws-amplify/amplify-cli/issues/1874
https://github.com/aws-amplify/amplify-cli/issues/2303
https://github.com/aws-amplify/amplify-cli/issues/4568

**Closed by attilah** 2021-01-12 17:13 UTC
Labels: duplicate, functions, not-reproducable
