### ISSUE TITLE
Is there any possibility of flutter support?

### ISSUE THREAD

**Issue by yukitaka13-1110** [aws-amplify/amplify-cli#2486] opened 2019-10-03 04:29 UTC
Feature request.
We long for flutter support.

Is there a possibility to support it ?

**Comment by kaustavghosh06** [comment] 2019-10-03 05:56
@yukitaka13-1110 We don't have a plans for Flutter support in the immediate future but we're actively  looking into it.

Closing, as this is a duplicate of #251

**Closed by kaustavghosh06** 2019-10-03 05:56 UTC
