### ISSUE TITLE
Error in Amplify CLI's latest(4.24.0) version in Build Image: auth headless is missing the following inputParams facebookAppIdUserPool, facebookAppSecretUserPool, googleAppIdUserPool, googleAppSecretUserPool

### ISSUE THREAD

**Issue by geoseong** [aws-amplify/amplify-cli#4806] opened 2020-07-11 13:43 UTC
**Is your feature request related to a problem? Please describe.**

I'm configuring `Continuous-Deployment` with [this repository](https://github.com/awskrug/kendra-button)'s temporary feature branch and I was working react frontend UI.
I pushed some commits that are not related to amplify's backend environment. 
after checking in Amplify console, it fails in the build step!
It just passed several days ago.

The detailed error message was...
```
[INFO]: auth headless is missing the following inputParams facebookAppIdUserPool, facebookAppSecretUserPool, googleAppIdUserPool, googleAppSecretUserPool
[INFO]: Error: auth headless is missing the following inputParams facebookAppIdUserPool, facebookAppSecretUserPool, googleAppIdUserPool, googleAppSecretUserPool
                                 at updateConfigOnEnvInit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/provider-utils/awscloudformation/index.js:370:15)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/index.js:240:28
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
                                 at process._tickCallback (internal/process/next_tick.js:68:7)
[ERROR]: !!! Build failed
```

I tried to change the shell script to execute `headless cli` refer to #2877.
- but no luck! and How can I find the documentation of the headless cli's `categories` parameter? I can't find in any documentation

**Describe the solution you'd like**

I was set up the amplify cli version in build image to `latest`.
The version I failed is `4.24.0`.

so changing cli version from `latest` to `4.20`, error disappeared and passed the all steps!
(version `4.20` is the version in my local environment)

**Additional context**

so Here are the questions:
- How can I use the headless cli with handling the following inputParams to pull backend environment in latest cli version(4.24.0)?
  - inputParam like `facebookAppIdUserPool`, `facebookAppSecretUserPool`, `googleAppIdUserPool`, `googleAppSecretUserPool`
  - is there any documentation or change log?
- please let me know. that kind of undocumented issues make me exhausted...

**Comment by SwaySway** [comment] 2020-07-11 16:31
Hello @geoseong 
How did you change the shell script? If you are using Amplify Console for your builds you would need to include those input params as environment variables.  An example of this is noted in this comment: https://github.com/aws-amplify/amplify-cli/issues/4790#issuecomment-656422252
Reference from Amplify Console Repo: https://github.com/aws-amplify/amplify-console/issues/206#issuecomment-657013051

Closing this as a duplicate of #4790.

**Closed by SwaySway** 2020-07-11 16:31 UTC
