### ISSUE TITLE
Amplify push fails, then rollback fails

### ISSUE THREAD

**Issue by ceich** [aws-amplify/amplify-cli#1206] opened 2019-04-04 00:19 UTC
**Describe the bug**
```
amplify init
amplify add auth
amplify push # FAILS, then rollback FAILS
```

**To Reproduce**
1. Create new app, per [yesterday's blog post](https://aws.amazon.com/blogs/mobile/amplify-framework-simplifies-configuration-for-oauth-flows-the-hosted-ui-and-ar-vr-scenes-for-mobile-and-web-developers/).
2. Follow `amplify add auth` from  this [gist](https://gist.github.com/ceich/65a53682fbf5d88e3b77359c3001fb31); no errors.
3. Run `amplify push`; the UserPool create fails, and then the rollback fails; see above gist.

**Expected behavior**
I expected amplify push to succeed.

**Screenshots**
I now see the following in CloudFormation console:
![Screen Shot 2019-04-03 at 5 07 10 PM](https://user-images.githubusercontent.com/38611/55521048-e2ce4300-5633-11e9-95db-7b7d28855b48.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.3
 - Browser: n/a
 - Version: Amplify 1.5.1

**Additional context**
I re-used the Facebook App ID & secret of an existing FB app which works fine.

**Comment by kaustavghosh06** [comment] 2019-04-04 00:36
@ceich We would need more information to root-cause/reproduce this issue.

1) Could you provide with terminal logs for your `amplify add auth` command?
2) Could you provide with  terminal logs for the CLI push failure?

**Comment by ceich** [comment] 2019-04-04 00:37
Did you click through to the gist linked in step 2? What more do you want?

**Comment by kaustavghosh06** [comment] 2019-04-04 00:38
@ceich Sorry, I missed the gist.

**Comment by haverchuck** [comment] 2019-04-04 00:45
@ceich Would you be willing to share your parameters.json?

**Comment by ceich** [comment] 2019-04-04 05:29
@haverchuck I added parameters.json to the gist.

**Comment by haverchuck** [comment] 2019-04-04 19:21
@ceich I replicated your configuration based on your parameters.json and successfully pushed.  Have you reproduced this issue multiple times?

**Comment by ceich** [comment] 2019-04-04 21:10
No, first I'd like to recover. Just manually delete the stacks?

**Comment by ceich** [comment] 2019-04-04 21:52
I deleted the parent stack fine but the nested stack goes back to DELETE_FAILED status. WDIDN?

**Comment by kaustavghosh06** [comment] 2019-04-05 17:16
@ceich Did you manually delete the stacks from the cloudformation console?

**Comment by ceich** [comment] 2019-04-05 18:47
Yes, as described in my previous comment. The original create failure was:
```
Internal server error. (Service: AWSCognitoIdentityProviderService; Status Code: 500; Error Code: InternalErrorException; Request ID: 1ace06f3-566b-11e9-8365-6df8928fe62d)
```
and the delete failure ever after has been a validation error:
```
1 validation error detected: Value '8344ee37-8429-4e87-9566-ed11dbc3cea9' at 'userPoolId' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w-]+_[0-9a-zA-Z]+ (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: 2c01b743-566b-11e9-b27b-5d4d959187a9)
```
I can't see the User Pool in the console, but CF is convinced it's still there.

**Comment by thomers** [comment] 2019-04-08 09:37
I'm having the same problem. 

Note that we both seemed to have chosen "Email" as sign-in!

```
Do you want to use the default authentication and security configuration? Default configuration
 Warning: you will not be able to edit these selections.
 How do you want users to be able to sign in when using your Cognito User Pool? Email
 Warning: you will not be able to edit these selections.
 What attributes are required for signing up? Email
Successfully added resource cognitocda08971 locally


...

amplify push

Current Environment: envdefault

| Category | Resource name   | Operation | Provider plugin   |
| -------- | --------------- | --------- | ----------------- |
| Auth     | cognitocda08971 | Create    | awscloudformation |
? Are you sure you want to continue? Yes
⠇ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS awsamplifytest-20190408111139 AWS::CloudFormation::Stack Mon Apr 08 2019 11:20:45 GMT+0200 (CEST) User Initiated
⠙ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS authcognitocda08971 AWS::CloudFormation::Stack Mon Apr 08 2019 11:20:51 GMT+0200 (CEST)
⠙ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS authcognitocda08971 AWS::CloudFormation::Stack Mon Apr 08 2019 11:20:52 GMT+0200 (CEST) Resource creation Initiated
⠋ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS awsamplifytest-20190408111139-authcognitocda08971-1UFOJ543TW0SR AWS::CloudFormation::Stack Mon Apr 08 2019 11:20:52 GMT+0200 (CEST) User Initiated
⠇ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS SNSRole AWS::IAM::Role Mon Apr 08 2019 11:20:59 GMT+0200 (CEST)
CREATE_IN_PROGRESS SNSRole AWS::IAM::Role Mon Apr 08 2019 11:21:00 GMT+0200 (CEST) Resource creation Initiated
⠙ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE SNSRole AWS::IAM::Role Mon Apr 08 2019 11:21:20 GMT+0200 (CEST)
⠹ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS UserPool AWS::Cognito::UserPool Mon Apr 08 2019 11:21:25 GMT+0200 (CEST)
⠼ Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED UserPool                                                        AWS::Cognito::UserPool     Mon Apr 08 2019 11:22:10 GMT+0200 (CEST) Internal server error. (Service: AWSCognitoIdentityProviderService; Status Code: 500; Error Code: InternalErrorException; Request ID: c9308599-59df-11e9-a7a9-3d63897ecff8)
CREATE_FAILED awsamplifytest-20190408111139-authcognitocda08971-1UFOJ543TW0SR AWS::CloudFormation::Stack Mon Apr 08 2019 11:22:11 GMT+0200 (CEST) The following resource(s) failed to create: [UserPool].

```

**Comment by thomers** [comment] 2019-04-08 15:31
Just FYI, I started from scratch again, `amplify auth add` with the same settings, just "username" instead of "email" - worked now.

**Comment by haverchuck** [comment] 2019-04-08 15:51
@thomers Are you getting the error that @ceich  posted above?  i.e.: 
```
1 validation error detected: Value '8344ee37-8429-4e87-9566-ed11dbc3cea9' at 'userPoolId' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w-]+_[0-9a-zA-Z]+ (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: 2c01b743-566b-11e9-b27b-5d4d959187a9)
```

**Comment by ceich** [comment] 2019-04-08 18:31
@haverchuck He hasn't tried to delete it yet, AFAICT.

He **is** getting the same _first_ failure, the 500 ("Internal server error") from Cognito. That seems to be what leads to the subsequent delete failure.

I still haven't heard any suggestions for how to clean up CF.

**Comment by ceich** [comment] 2019-04-08 21:23
@kaustavghosh06 What is the dependency issue here? If @thomers sees it too, how is it not reproducible?

**Comment by kaustavghosh06** [comment] 2019-04-08 21:40
@ceich We added  `auth` with the same parameters (with the same flow that you have) to an amplify project and we were able to push successfully (this was tried by two other members of the team as well). You can maybe try creating another project and adding auth with the same parameters and try pushing it and let us know if you're getting the same error. To delete the resources generated, you can use the `amplify delete` command and not manually delete the Cloudformation stacks from the console which may lead to the CLI being in an inconsistent state. 

This 500 error code is returned by the Cognito service via Cloudformation and we've contacted Cognito (which is a dependency) with your request ID to investigte further as to what exactly went wrong with your request since the error logs aren't helpful.

**Comment by ceich** [comment] 2019-04-08 21:46
Thanks @kaustavghosh06, I will `amplify delete auth` and re-try.

**Comment by kaustavghosh06** [comment] 2019-04-08 22:14
@ceich As I'd mentioned in my previous comment, if you manually delete the stack in the Cloudformation console, that would lead the CLI to be in an inconsistent state and would lead to errors like the one above. You might want to just delete the nested stack manually (a force delete from the console itself now that the parent stack is deleted manually).

Also, would it be possible for you to provide your Account ID and region you were trying to deploy to so that the Cognito service team can further investigate on the reason for the 500 internal error?
You can send it to me via email - kaustavg@amazon.com if you don't want to share this information publicly.

**Comment by ceich** [comment] 2019-04-08 22:23
The "force delete" on the console fails with the same (second) error that `amplify push` got, the validation error.

I have sent you the requested info via email.

**Comment by ceich** [comment] 2019-04-08 22:41
I just reproduced the same first and second errors:
```
Internal server error. (Service: AWSCognitoIdentityProviderService; Status Code: 500; Error Code: InternalErrorException; Request ID: 4bbed54f-5a4d-11e9-99b3-0161cebb176a)
Reason: Internal server error. (Service: AWSCognitoIdentityProviderService; Status Code: 500; Error Code: InternalErrorException; Request ID: 4bbed54f-5a4d-11e9-99b3-0161cebb176a)
```

**Comment by ceich** [comment] 2019-04-08 23:38
And in case it wasn't obvious: there is no user pool. So I'm wondering if the second problem is a bug in CF, which is not in sync with Cognito after the first failure.

**Comment by konstankinollc** [comment] 2019-04-13 20:22
The same issue here.

**Comment by kaustavghosh06** [comment] 2019-04-26 19:43
Hey guys, Cognito service rolled out a fix for this issue earlier this week. Please `amplify remove auth` and `amplify add auth` with your desired flow to make this work. Thank you!

**Closed by kaustavghosh06** 2019-04-26 19:43 UTC
Labels: auth, bug, dependency-issue, investigating, not-reproducable
