### ISSUE TITLE
Amplify push keeps failing with "This service may not be available in the 'us-east-1' region."

### ISSUE THREAD

**Issue by TheDutchCoder** [aws-amplify/amplify-cli#7492] opened 2021-06-09 21:46 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm (globally)

### If applicable, what version of Node.js are you using?

16.0.0

### Amplify CLI Version

4.52.0

### What operating system are you using?

MacOS 11.4

### Amplify Categories

function, api

### Amplify Commands

push

### Describe the bug

Pretty much every single `amplify push` results in a "Inaccessible host: 'hostname'. This service may not be available in the 'us-east-1' region." error.

The pushes take ~30 minutes and then they fail.

### Expected behavior

The push to succeed.

### Reproduction steps

1. `amplify push -y`
2. Wait
3. Get the error

### GraphQL schema(s)

N/A (it's too big to share)

### Log output

The logs are way too large to be useful, but there's **a lot** of these messages
<details>

```
2021-06-09T14:45:51.943Z|error : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]rmation:us-[***]st-[***]12:stack/[***]ify-[***]ayeroms-[***]ier-[***]552-[***]pifywebhooks-[***]8MSHNF/[***]4960-[***]22-[***]eb-[***]e9-[***]9da6d"}])
Throttling: Rate exceeded
2021-06-09T14:45:51.946Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]rmation:us-[***]st-[***]12:stack/[***]ify-[***]ayeroms-[***]ier-[***]552-[***]seLineitem-[***]UEH1NN/[***]4d90-[***]22-[***]eb-[***]d2-[***]064a3"}])
2021-06-09T14:45:52.130Z|error : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]ify-[***]ayeroms-[***]ier-[***]552"}])
Throttling: Rate exceeded
2021-06-09T14:45:52.137Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]rmation:us-[***]st-[***]12:stack/[***]ify-[***]ayeroms-[***]ier-[***]552-[***]oAuthToken-[***]2KQNVT/[***]bf30-[***]22-[***]eb-[***]11-[***]3308d"}])
2021-06-09T14:45:52.658Z|error : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]rmation:us-[***]st-[***]12:stack/[***]ify-[***]ayeroms-[***]ier-[***]552-[***]InstallLink-[***]S2RFO8/[***]4d70-[***]22-[***]eb-[***]d6-[***]c8b8d"}])
Throttling: Rate exceeded
2021-06-09T14:45:52.661Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]rmation:us-[***]st-[***]12:stack/[***]ify-[***]ayeroms-[***]ier-[***]552-[***]voiceReport-[***]6SKZ6I/[***]c850-[***]22-[***]eb-[***]34-[***]5a299"}])
2021-06-09T14:45:52.794Z|error : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]rmation:us-[***]st-[***]12:stack/[***]ify-[***]ayeroms-[***]ier-[***]552-[***]ateStats-[***]WY6N0/[***]e2d0-[***]22-[***]eb-[***]49-[***]81873"}])
Throttling: Rate exceeded
2021-06-09T14:45:52.797Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]rmation:us-[***]st-[***]12:stack/[***]ify-[***]ayeroms-[***]ier-[***]552-[***]nessProducts-[***]MYZUT/[***]ee00-[***]22-[***]eb-[***]6a-[***]c8c9d"}])
2021-06-09T14:45:53.282Z|error : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]rmation:us-[***]st-[***]12:stack/[***]ify-[***]ayeroms-[***]ier-[***]552-[***]celOrder-[***]LR94H/[***]3e40-[***]22-[***]eb-[***]cd-[***]17b41"}])
Throttling: Rate exceeded


```

</details>

### Additional information

N/A

**Comment by TheDutchCoder** [comment] 2021-06-10 14:37
Well... I had to delete and recreate my entire stack.
I don't know what the cause of all this is, but this is not a good thing...

**Comment by jhockett** [comment] 2021-06-11 22:41
@TheDutchCoder, sorry to hear you ran into this. I am not able to reproduce the issue. Are you still seeing this after recreating your stack?

**Comment by TheDutchCoder** [comment] 2021-06-11 22:46
> @TheDutchCoder, sorry to hear you ran into this. I am not able to reproduce the issue. Are you still seeing this after recreating your stack?

No, everything works fine with a fresh stack.

The only thing to go on is that we had to do a lot of consecutive pushes. The logs clearly show I was getting throttled, which could be related to that.

**Comment by jhockett** [comment] 2021-06-11 23:40
@TheDutchCoder by any chance, do you still have the Amplify appId from your old stack? That would help us investigate what happened.

**Comment by TheDutchCoder** [comment] 2021-06-12 00:30
> @TheDutchCoder by any chance, do you still have the Amplify appId from your old stack? That would help us investigate what happened.

Unfortunately I don't.
I deleted all the old parts of the stack in the process of making a new one :(

**Comment by jhockett** [comment] 2021-06-12 01:14
@TheDutchCoder since the issue isn't reproducible and you're unblocked I'm going to mark this issue as pending-close-response-required. If you run into this issue again, even if the issue is closed, please comment below with your current appId and we can deep dive into what's happening.

**Comment by TheDutchCoder** [comment] 2021-06-12 01:45
@jhockett Sounds good to me, I'll keep you posted if one of us walks into this again!

**Comment by akshbhu** [comment] 2021-06-14 21:53
Closing this issue as it seems to be solved

**Closed by akshbhu** 2021-06-14 21:53 UTC
Labels: not-reproducible, pending-close-response-required, platform
