### ISSUE TITLE
AWS Amplify Pull not updating appsync changes 

### ISSUE THREAD

**Issue by ncohen17** [aws-amplify/amplify-cli#4275] opened 2020-05-14 21:06 UTC
#1. I changed the schema of Appsync in the cloud(not local) which is connected to Amplify. and I want to pull the resolvers and schema of Appsync into my local but it says cloud has no change. 

#2. I want to remove Authentication in Amplify and want to add a new one or change Cognito but cant'. The others are saying that the solution of this case, try to change cognito values in aws-exports.js (which is auto-generated). I think this works but if I pull amplify again, I need to change manually again and again.
In the second problem, I can remove by command "amplify auth remove" but I need to pull the latest environment from cloud, but it says no change and I remove auth and push to the cloud. then everything I work on the cloud are gone.

**Comment by SwaySway** [comment] 2020-05-14 21:14
Hello @ncohen17 
`amplify pull` pulls down backend environment changes from the cloud and updates the local environment. Changes made outside of the amplify project are not pulled in.
Docs here: https://docs.amplify.aws/cli/start#amplify-pull

Closing as duplicate of #4260

**Comment by ncohen17** [comment] 2020-05-14 21:16
Hello @SwaySway , 
What about the second problem ?

**Comment by ncohen17** [comment] 2020-05-14 21:17
@SwaySway 
are you available to discuss this privately ?

**Comment by SwaySway** [comment] 2020-05-14 21:34
In the second problem, I can remove by command "amplify auth remove" but I need to pull the latest environment from cloud, but it says no change and I remove auth and push to the cloud. then everything I work on the cloud are gone.

**Comment by SwaySway** [comment] 2020-05-14 21:38
> In the second problem, I can remove by command "amplify auth remove" but I need to pull the latest environment from cloud, but it says no change and I remove auth and push to the cloud. then everything I work on the cloud are gone.

The changes made in the cloud would not be pulled since Amplify is keep a tracking of the changes made in the backend environment. Could you elaborate on the usecase you are looking for when running `amplify auth update`? Are you looking at importing a different cognito userpool?

**Comment by danielfranca** [comment] 2020-05-14 22:01
How to force the backend to be updated with changes on the cloud then?
I have opened an issue days ago that is blocking my deployment, but I barely got any response, so I'm commenting here because the response here might help me.

My backend is pulling some userPoolClientId that doesn't exist anymore, and then it is making any push to fail.

This is the issue https://github.com/aws-amplify/amplify-cli/issues/4233

So I think it should have a way to update the backend with up-to-date information from your cloud, even if it is a "hack" way to do it.

**Closed** 2020-05-22 18:11 UTC
Labels: pending-response, platform, question
