### ISSUE TITLE
Analytics does not work for logged in user groups

### ISSUE THREAD

**Issue by ahansson89** [aws-amplify/amplify-cli#4772] opened 2020-07-08 18:30 UTC
**Describe the bug**
Analytics does not work for Logged In User Groups

**Amplify CLI Version**
4.23.0

**To Reproduce**
Set up auth with user groups and analytics and record events

**Expected behavior**
Events should show up in the Pinpoint dashboard

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v12.18.2

**Additional context**
There are no user group roles defined in the CloudFormation template and the template only have an auth and unauth role, which is not assumed by the logged in user when user groups are enabled.

**Comment by ahansson89** [comment] 2020-07-08 21:06
In order to get around this I added... 
```"UsersGroupPolicy": {
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyName": "Users-group-analytics-policy",
        "Roles": [
          {
            "Fn::Join": [
              "",
              [
                {
                  "Ref": "authbabynotebookAuthUserPoolId"
                },
                "-UsersGroupRole"
              ]
            ]
          }
        ],
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "mobiletargeting:PutEvents",
                "mobiletargeting:UpdateEndpoint",
                "mobiletargeting:GetUserEndpoints"
              ],
              "Resource": [
                {
                  "Fn::Join": [
                    "",
                    [
                      "arn:aws:mobiletargeting:*:",
                      {
                        "Fn::Select": [
                          "4",
                          {
                            "Fn::Split": [
                              ":",
                              {
                                "Ref": "authRoleArn"
                              }
                            ]
                          }
                        ]
                      },
                      ":apps/",
                      {
                        "Fn::GetAtt": ["PinpointFunctionOutputs", "Id"]
                      },
                      "*"
                    ]
                  ]
                }
              ]
            }
          ]
        }
      }
    },
    "AdminsGroupPolicy": {
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyName": "Admins-group-analytics-policy",
        "Roles": [
          {
            "Fn::Join": [
              "",
              [
                {
                  "Ref": "authbabynotebookAuthUserPoolId"
                },
                "-AdminsGroupRole"
              ]
            ]
          }
        ],
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "mobiletargeting:PutEvents",
                "mobiletargeting:UpdateEndpoint",
                "mobiletargeting:GetUserEndpoints"
              ],
              "Resource": [
                {
                  "Fn::Join": [
                    "",
                    [
                      "arn:aws:mobiletargeting:*:",
                      {
                        "Fn::Select": [
                          "4",
                          {
                            "Fn::Split": [
                              ":",
                              {
                                "Ref": "authRoleArn"
                              }
                            ]
                          }
                        ]
                      },
                      ":apps/",
                      {
                        "Fn::GetAtt": ["PinpointFunctionOutputs", "Id"]
                      },
                      "*"
                    ]
                  ]
                }
              ]
            }
          ]
        }
      }
    }```
and 
```
"authbabynotebookAuthUserPoolId": {
      "Type": "String",
      "Default": "authbabynotebookAuthUserPoolId"
    },
    "authuserPoolGroupsUsersGroupRole": {
      "Type": "String",
      "Default": "authuserPoolGroupsUsersGroupRole"
    },
    "authuserPoolGroupsAdminsGroupRole": {
      "Type": "String",
      "Default": "authuserPoolGroupsAdminsGroupRole"
    }
```
... to the analytics cloudformation template.
added the "dependsOn" to the backend-config.json
```"analytics": {
    "babynotebook": {
      "service": "Pinpoint",
      "providerPlugin": "awscloudformation",
      "dependsOn": [
        {
          "category": "auth",
          "resourceName": "babynotebookAuth",
          "attributes": ["UserPoolId"]
        },
        {
          "category": "auth",
          "resourceName": "userPoolGroups",
          "attributes": ["AdminsGroupRole"]
        },
        {
          "category": "auth",
          "resourceName": "userPoolGroups",
          "attributes": ["UsersGroupRole"]
        }
      ]
    }
  }```

... Have to say I am still amazed by the amount of bugs like this I have to fix in my cloudformation manually and seems like the QA testing is no adequate for a product that has the AWS name on it.

**Comment by lenarmazitov** [comment] 2020-07-11 13:38
Confirm that behavior

**Comment by eripoll** [comment] 2020-08-02 19:49
@jhockett Any news on this? I see the same issue on Users in Groups

**Comment by christodupreez** [comment] 2020-09-10 12:35
Has this bug been resolved yet?

**Comment by jcbdev** [comment] 2020-11-16 12:22
The amount of bugs this platform has is incredible.  It's almost like they don't test anything 🤔 ... I'm on the issue pages almost daily.

I can confirm this bug and it is super annoying.

**Comment by renebrandel** [comment] 2020-11-16 18:21
Hi folks - we've reproduced the issue and are going to tackle it as part of our bug bash over the next upcoming weeks.

**Comment by dylan-westbury** [comment] 2020-11-29 01:39
Yes would be awesome if groups roles to apply auth role permissions, as when updating endpoint we get this error for the group all users are added to in post confirmation:

could not update endpoint AccessDeniedException: User: arn:aws:sts::XXXXXXXXXXXXXX:assumed-role/xxxxxxxxx-CustomersGroupRole/CognitoIdentityCredentials is not authorized to perform: mobiletargeting:UpdateEndpoint on resource: arn:aws:mobiletargeting:xxxxxx:XXXXXXXXX:apps/XXXXXXXXXXXXXXXXXX/endpoints/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

**Comment by ahansson89** [comment] 2020-12-22 18:18
@jcbdev what is the ETA on this issue?

**Comment by ahansson89** [comment] 2020-12-22 18:21
My above solution seems to no longer work and I get:

Invalid CloudFormation template: pinpoint-cloudformation-template.json
✖ An error occurred when pushing the resources to the cloud
Invalid parameterized type: 
An error occurred during the push operation: Invalid parameterized type: 

Not really helpful to debug what is going on and the above is blocking a release.

**Comment by ahansson89** [comment] 2020-12-22 19:31
That seems to be an unrelated issue to this one with the latest Amplify CLI version. Was able to downgrade to @aws-amplify/cli@4.36.2 in order to get past the error message.

**Comment by lexlemmens** [comment] 2021-01-26 08:32
@ahansson89 I have same issue reverted to 4.36.2, what file do I need to change to get this to work with what content?

**Comment by lexlemmens** [comment] 2021-01-26 13:57
For anyone still dealing with the issue. In my situation we have one group called admin, no user group like @ahansson89 has.

To make this work you have to add this to your `pinpoint-cloudformation-template.json`:

In Resources section:

```
"AdminsGroupPolicy": {
      "Type": "AWS::IAM::Policy",
      "Condition": "ShouldCreatePinpointApp",
      "Properties": {
        "PolicyName": "Admins-group-analytics-policy",
        "Roles": [
          {
            "Fn::Join": [
              "",
              [
                {
                  "Ref": "AuthUserPoolId" // References to parameters
                },
                "-adminGroupRole"
              ]
            ]
          }
        ],
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "mobiletargeting:PutEvents",
                "mobiletargeting:UpdateEndpoint",
                "mobiletargeting:GetUserEndpoints"
              ],
              "Resource": [
                {
                  "Fn::If": [
                    "ShouldCreatePinpointApp",
                    {
                      "Fn::Join": [
                        "",
                        [
                          "arn:aws:mobiletargeting:*:",
                          {
                            "Fn::Select": [
                              "4",
                              {
                                "Fn::Split": [
                                  ":",
                                  {
                                    "Ref": "authRoleArn"
                                  }
                                ]
                              }
                            ]
                          },
                          ":apps/",
                          {
                            "Fn::GetAtt": [
                              "PinpointFunctionOutputs",
                              "Id"
                            ]
                          },
                          "*"
                        ]
                      ]
                    },
                    {
                      "Fn::Join": [
                        "",
                        [
                          "arn:aws:mobiletargeting:*:",
                          {
                            "Fn::Select": [
                              "4",
                              {
                                "Fn::Split": [
                                  ":",
                                  {
                                    "Ref": "authRoleArn"
                                  }
                                ]
                              }
                            ]
                          },
                          ":apps/",
                          {
                            "Ref": "appId"
                          },
                          "*"
                        ]
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      }
    },
    ```
    
In Parameters:

```
"AuthUserPoolId": {
      "Type": "String",
      "Default": "YourCognitoPoolId"
    },
    ```

**Comment by mgarabedian** [comment] 2021-03-22 13:28
Hello - this is an important bug to solve - I cannot use Analytics with any user in a user group.  I am manually messing with IAM in AWS which is incorrect. Will this be addressed?

**Comment by lseemann** [comment] 2021-03-24 19:06
This is bananas.

**Comment by lseemann** [comment] 2021-03-24 21:53
I was able to get @lexlemmens’ [solution](https://github.com/aws-amplify/amplify-cli/issues/4772#issuecomment-767557359) to work, but having to hard-code the pool ID was a deal-breaker, as we have multiple environments and multiple user pools.

To get around this, I made the following change to `backend-config.json`, where `mhPinpoint` is the name of my analaytics resource and `mhAuth` is the name of my auth resource.:
```
  "analytics": {
    "mhPinpoint": {
      "service": "Pinpoint",
      "providerPlugin": "awscloudformation",
      "dependsOn": [ // ADDED THIS
        {
          "category": "auth",
          "resourceName": "mhAuth",
          "attributes": [
            "UserPoolId"
          ]
        }
      ]
    }
  }
  ```
  
  That rigs it so that auth will export its userpool ID to the pinpoint resource.

Now I add the following the Parameters section of `pinpoint-cloudformation-template.json`:
```
   "authmhAuthUserPoolId": {
      "Type": "String",
      "Default": "authmhAuthUserPoolId"
    }
```

And then for each usergroup policy in Resources, this the value for `Properties.Roles`, where `Admins` is the name of my this particular usergroup
```
        "Roles": [
          {
            "Fn::Join": [
              "",
              [
                {
                  "Ref": "authmhAuthUserPoolId"
                },
                "-AdminsGroupRole"
              ]
            ]
          }
        ],
```

I'm new to Amplify and this is way more config than I feel comfortable having to do manually. I'm also left feeling nervous it’s all going to break with the next CLI update. (I'm on 4.45.0.)

**Comment by kylekirkby** [comment] 2021-04-13 09:10
Any update on this folks? This has been an issue for almost a year! I'm pretty sure this is a very common use case. Most apps have some degree of tiering added to users via Cognito groups and most apps are going to be using some form of analytics. This being broken is going to pushing people away from using another AWS service - Pinpoint. Can we get this expedited within the amplify team please?  @SwaySway @akshbhu

**Comment by kaustavghosh06** [comment] 2021-04-14 18:35
Firstly, apologize for the delayed response on this issue for a workaround.  Right now the CLI allows you to add user-pool groups and then natively supports adding group permissions for categories like Storage and API Gateway. While we work on supporting more categories like analytics to work with user-pool groups permissions out of the box, we provide an escape hatch to workaround in the meanwhile.  For example, since analytics is not natively supported with the cognito groups permissions model, as an escape hatch, you can modify the file `amplify/backend/auth/userPoolGroups/user-pool-group-precedence` and add customPolicies key to the user-pool groups and these IAM policies would be applied to an individual group. An example for this would look like the following


```json
[
  {
    "groupName": "admin",
    "precedence": 1,
    "customPolicies": [{
      "PolicyName": "analytics-pinpoint-policy",
      "PolicyDocument": {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "mobiletargeting:PutEvents",
              "mobiletargeting:UpdateEndpoint"
            ],
            "Resource": ["arn:aws:mobiletargeting:*:<account-id>:apps/<pinpoint-app-id>"]
          }
        ]
      }
    }]
  },
  {
    "groupName": "nonadmin",
    "precedence": 2,
    "customPolicies": [{
      "PolicyName": "analytics-pinpoint-policy",
      "PolicyDocument": {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "mobiletargeting:PutEvents",
              "mobiletargeting:UpdateEndpoint"
            ],
            "Resource": ["arn:aws:mobiletargeting:*:<account-id>:apps/<pinpoint-app-id>"]
          }
        ]
      }
    }]
  }
]


```

**Comment by kylekirkby** [comment] 2021-04-15 12:56
@kaustavghosh06 Thank you for the update! Any suggestions on the best way to add `<account-id>:apps/<pinpoint-app-id>` ?

**Comment by IcedNet** [comment] 2021-06-09 14:12
> ```json
> ,
>     "customPolicies": [{
>       "PolicyName": "analytics-pinpoint-policy",
>       "PolicyDocument": {
>         "Version": "2012-10-17",
>         "Statement": [
>           {
>             "Effect": "Allow",
>             "Action": [
>               "mobiletargeting:PutEvents",
>               "mobiletargeting:UpdateEndpoint"
>             ],
>             "Resource": ["arn:aws:mobiletargeting:*:<account-id>:apps/<pinpoint-app-id>"]
>           }
>         ]
>       }
>     }]
> ```

UPDATE_FAILED <apiname> AWS::CloudFormation::Stack Wed Jun 09 2021 09:59:48 GMT-0400 (Eastern Daylight Time) Parameters: [authRoleName] must have values

here we go...
Perhaps you can make this issue I've encountered with your workaround less opaque - I'm "assuming" it needs the authRoleName provided, but I've seen similar issues before that were referring to an entirely different file
That being said, updating  "Update available 4.51.1 → 4.52.0" now...
I'm sure I'll be back. :(

**Comment by arturocanalda** [comment] 2021-07-01 14:29
+1

**Comment by semap** [comment] 2021-11-05 04:33
> @kaustavghosh06 Thank you for the update! Any suggestions on the best way to add `<account-id>:apps/<pinpoint-app-id>` ?

***** works for me, but not ideal.

**Comment by ngnathan** [comment] 2021-11-15 06:31
https://github.com/aws-amplify/amplify-cli/issues/4772#issuecomment-819743759

I was @kaustavghosh06 's post above with customPolicies in my `user-pool-group-precendence.json` file for the last few months, but as of Amplify CLI v7.3.0 (and I think 6.4.0), it erases the customPolicies object in the file and I'm back to square one.

**Comment by IcedNet** [comment] 2021-12-05 20:30
Still hoping for a solution.
I have great hope for the platform, but this made us use Google Analytics with an app that should have 100% AWS content...

**Comment by WinterYukky** [comment] 2022-01-20 07:57
This is using wild card in ARN so no good solution, but at least it is alternative to @kaustavghosh06 's solution in current Amplify CLI (v7.6.10).


1. run command `amplify override auth`, and choose user group.
1. write this code to `amplify/backend/auth/<group>/override.ts`.


```typescript
import { AmplifyUserPoolGroupStackTemplate } from '@aws-amplify/cli-extensibility-helper'

export function override(resources: AmplifyUserPoolGroupStackTemplate) {
  for (const userGroupRoleName in resources.userPoolGroupRole) {
    const userGroupRole = resources.userPoolGroupRole[userGroupRoleName]
    const basePolicies = Array.isArray(userGroupRole.policies)
      ? userGroupRole.policies
      : [userGroupRole.policies]
    userGroupRole.policies = [
      ...basePolicies,
      {
        policyName: 'analytics-pinpoint-policy',
        policyDocument: {
          Version: '2012-10-17',
          Statement: [
            {
              Effect: 'Allow',
              Action: [
                'mobiletargeting:PutEvents',
                'mobiletargeting:UpdateEndpoint',
              ],
              Resource: ['arn:aws:mobiletargeting:*:*'],
            },
          ],
        },
      },
    ]
  }
}

```

ref: https://docs.amplify.aws/cli/auth/override/#customize-amplify-generated-cognito-user-group-resources

**Comment by WinterYukky** [comment] 2022-01-20 08:09
Currently, `override.ts` can't import nothing except `@aws-amplify/cli-extensibility-helper`.
So it can't use CloudFormation functions (ex: Ref, Fn:GetAtt), but maybe we can get the solution in this issue https://github.com/aws-amplify/amplify-cli/issues/9383.

**Comment by akshbhu** [comment] 2022-06-27 18:01
closing in favour of #10455

**Closed by akshbhu** 2022-06-27 18:01 UTC
Labels: bug, analytics, p1
