### ISSUE TITLE
HostedUiProvider credentials and cloudformation config (CaseSensitive) gone after amplify pull

### ISSUE THREAD

**Issue by AlessandroVol23** [aws-amplify/amplify-cli#7685] opened 2021-07-08 09:51 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v12.18.3

### Amplify CLI Version

5.1.0

### What operating system are you using?

Mac

### Amplify Categories

auth

### Amplify Commands

pull, push

### Describe the bug

If I pull my current backend my HostedUi Provider credentials for the social provider are gone. If I starte the next push I'll get the following error message:
```
UPDATE_FAILED               HostedUIProvidersCustomResourceInputs                             Custom::LambdaCallout      Thu Jul 08 2021 11:37:57 GMT+0200 (Central European Summer Time) Received response status [FAILED] from custom resource. Message returned: See the details in CloudWatch Log Stream: 2021/07/08/[$LATEST]d16ab26ffb234b63950ccdb8de4beb99 (RequestId: f76cb5c7-43c3-402a-b8a6-1df952111b8e)
```

I have to go to `amplify update auth` -> `Update OAuth social providers` and enter the secrets again. 

After that I have to add my default cloudformation config again (`CaseSensitive: false`)

After that everything works again. This just leads to the fact that I won't pull the backend anymore.

### Expected behavior

I pull the backend and my secrets and auth config is still saved.

### Reproduction steps

Assumption: Social providers **and** caseSensitive flag false is present:

1. `amplify pull`
2. Change something in e.g. lamdba
3. `amplify push`
4. Error

**Fix**

1. `amplify update auth`
2. `Update OAuth social providers`
3. Enter credentials for Facebook and Google
4. Add old CloudFormation config
5. `amplify push`

**Comment by wcomicho** [comment] 2021-07-09 10:01
Also encountering the same.  

Reproduction steps on my side:
1 Switch environment (dev or test)
2 amplify pull
3 Change something in e.g. lamdba / graphql
4 amplify push
5 Error

Fix
1 amplify update auth
2 update OAuth social providers
3 enter credentials for FB and Google
4 amplify push

**Comment by ammarkarachi** [comment] 2021-07-13 00:41
@AlessandroVol23 Can you send me your amplify/auth folder to amplify-cli@amazon.com?

**Comment by AlessandroVol23** [comment] 2021-07-14 05:17
Yes sure I'll send it

**Comment by AlessandroVol23** [comment] 2021-07-14 10:33
fyi: I think it is overwriting the Sign in with Apple config as well and unfortunately it broke my prod login. Maybe that helps 🙂

**Comment by ammarkarachi** [comment] 2021-07-14 17:52
@AlessandroVol23 Thanks I got it

**Comment by ammarkarachi** [comment] 2021-07-14 17:53
Actually I take that back, Can you send it again?
![image](https://user-images.githubusercontent.com/56042290/125669351-b753156b-eb67-4273-8c9c-3f3acc0eec5b.png)

**Comment by AlessandroVol23** [comment] 2021-07-14 19:01
My mistake I sent the email again, sorry!

**Comment by AlessandroVol23** [comment] 2021-07-24 08:41
Just one update. I still experience the issue. And one of the worst parts is that **Sign in with Apple** gets overriden which results in a downtime on **any** deployment on prod.

**Comment by AlessandroVol23** [comment] 2021-08-02 07:45
Hi @ammarkarachi, 
do you have any updates for that. It still happens so often and the development workflow really suffers a lot with this issue.

Thanks! :)

**Comment by AlessandroVol23** [comment] 2021-08-12 08:10
I have no updates on this just that I am still facing the issue and it is really annoying, to be honest. 
For a simple deploy I have always to:
- Update OAuth providers
- Change ENVs for custom message
- Add case sensitive flag in cloudformation template again
- Have a sign in with apple downtime and add information in Cognito again

It is a bit frustrating 😉

**Comment by josefaidt** [comment] 2021-08-12 18:05
Hey y'all :wave: apologies for the delay! We'll be addressing this issue as a part of our weekly bug bash tomorrow 🙂

**Comment by yannikw23** [comment] 2021-09-14 15:30
I don't know if that adds a layer of confusion or helps in any way: Interestingly, when I try to add `Sign in with Apple` through the Amplify Admin panel, I see this error on deployment: 

```
2 validation errors detected: Value '[]' at 'writeAttributes' failed to satisfy constraint: Member must satisfy constraint: [Member must have length less than or equal to 2048, Member must have length greater than or equal to 1]; Value '[]' at 'readAttributes' failed to satisfy constraint: Member must satisfy constraint: [Member must have length less than or equal to 2048, Member must have length greater than or equal to 1]. 
```

That's also a mystery to me but it doesn't seem to be connected to the IAM issue...

**Comment by ammarkarachi** [comment] 2022-02-11 19:07
This should be fixed in the latest release sorry for the delay

**Closed by ammarkarachi** 2022-02-11 19:07 UTC
Labels: bug, auth

**Comment by ENT108** [comment] 2022-03-07 15:11
I think it's not...

**Comment by jk171505** [comment] 2022-04-29 12:32
I'm also facing this issue. It happens when I apply default configuration with social provider (federation) to cognito user pool that with no required attributes required for signing up. The problem is that cloudwatch log is useless:
```
2022-04-29T07:04:59.963Z	xxxxx	INFO	{ Providers: [] }
2022-04-29T07:05:00.758Z	xxxxx	INFO	InternalErrorException: Internal server error.
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
2022-04-29T07:05:00.758Z	xxxxx	INFO	Response body:
 {
    "Status": "FAILED",
    "Reason": "See the details in CloudWatch Log Stream: 2022/04/29/[$LATEST]a43...",
    "PhysicalResourceId": "2022/04/29/[$LATEST]a43...",
    "StackId": "arn:aws:cloudformation:eu-west-1:......:stack/amplify-testapp5-dev-xxx-authtestapp5xxxxx/xxxxx",
    "RequestId": "fexxxx",
    "LogicalResourceId": "HostedUIProvidersCustomResourceInputs",
    "NoEcho": false,
    "Data": {
        "err": {
            "message": "Internal server error.",
            "code": "InternalErrorException",
            "time": "2022-04-29T07:05:00.757Z",
            "requestId": "ddeededeededdeedde",
            "statusCode": 500,
            "retryable": true
        }
    }
}
```

It works if I apply Default configuration with Social Provider (Federation), but then after authorisation on Apple's side, I am redirected to url with missing required param error (email)
`/?error_descripticcon=Invalid+user+attributes%3A+email%3A+The+attribute+is+required%0A+&error=invalid_request`

**Comment by losdwind** [comment] 2022-08-05 08:30
Luckily I got it fixed by setting the default login method to "username" instead of "email". Then, the "sign in with apple" can be deployed successfully. I guess Apple need the "username" as its "sub"  field during authentication.
