### ISSUE TITLE
Cannot push stack after removing @searchable from model

### ISSUE THREAD

**Issue by mdw2000** [aws-amplify/amplify-cli#1478] opened 2019-05-17 10:40 UTC
Hi there,

I'm getting the same errors as reported in #982 when removing the @searchable directive from a model:

```
UPDATE_FAILED User AWS::CloudFormation::Stack Fri May 17 2019 11:40:59 GMT+0200 (South Africa Standard Time) Embedded stack <User stack> was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: Export biblhxdnkzbmlizdt6nvrrnfjm:GetAtt:UserTable:StreamArn cannot be deleted as it is in use by <SearchableStack stack>
```

Adding back the @searchable directive and pushing produces the following error: 
```
No resolver found. Service: AWSAppSync; Status Code: 404; Error Code: NotFoundException
```

Is there any way to recover from this error without recreating the stack?

**To Reproduce**

1. Add a model with @searchable directive
```
type User @model @searchable{
  id: ID!
  Role: String
  Email: String
  Name: String
  PhoneNumber: String
}
```
2. `amplify push` - completes successfully

3. Edit the model & remove @searchable directive
```
type User @model {
  id: ID!
  Role: String
  Email: String
  Name: String
  PhoneNumber: String
}
```
4. `amplify push` - this one errors and there is no

node @ v10.15.3
npm @ 6.4.1
amplify @ 1.6.8

Thanks!

**Comment by kstro21** [comment] 2019-05-17 15:32
About removing the **@searchable** directive, this is a duplicate of #980 and exist a PR open that solve it, see #1140 

About the `No resolver found` after removing the **@searchable** directive, I've seen it reported in other issues, but I think it is more a bug in the CloudFormation service that not restore the **resolver** a in the update rollback process.

You will need to create the resolver manually using the AppSync Console, until then, you won't be able to update your stack.

**Comment by kaustavghosh06** [comment] 2019-05-20 17:41
We've merged the PR for this fix. This would be released as a part of our next CLI npm release - 1.6.10.

**Closed by kaustavghosh06** 2019-05-20 17:41 UTC
Labels: bug, graphql-transformer
