### ISSUE TITLE
Adding permission to read api from pre-signup lambda function results in Circular dependency error

### ISSUE THREAD

**Issue by kjetilge** [aws-amplify/amplify-cli#4696] opened 2020-06-28 16:14 UTC
**Describe the bug**
Adding permission to read api from pre-signup function results in Circular dependency error when cognito user pool auth is enabled.

```amplify --version 4.22.0```

**To Reproduce**
1. Create an iam based auth with a pre-signup function.
2. Create an api with iam as default auth and cognito user pool as secondary auth.
3. Update the pre-signup function to be able to access the api read.
4. amplify push -> circular depenency problem.

The error:

```An error occurred when pushing the resources to the cloud
Circular dependency between resources: [authuserPoolGroups, apiffb9, UpdateRolesWithIDPFunctionOutputs, authFFB9auth, UpdateRolesWithIDPFunction, functionFFB9authPreSignup]
An error occurred during the push operation: Circular dependency between resources: [authuserPoolGroups, apiffb9, UpdateRolesWithIDPFunctionOutputs, authFFB9auth, UpdateRolesWithIDPFunction, functionFFB9authPreSignup]
```

**Expected behavior**
amplify push should succeed.

The goal is to be able to acces the API using iam and user pool combo as described [here](https://docs.amplify.aws/cli/graphql-transformer/directives#combining-multiple-authorization-types)

I have instead enabled api auth combo iam + api key. It seems to work when i use [Signed request from Lambda](https://docs.amplify.aws/lib/graphqlapi/graphql-from-nodejs/q/platform/js#signing-a-request-from-lambdal)

I'm using a rule like this: ```@auth(rules: [{allow: public, provider: iam, operations: [read]}])``` - it works (from the pre-signup function)

In the docs we have an example:
```
type Post @model
  @auth (
    rules: [
      { allow: owner },
      { allow: private, provider: iam, operations: [read] }
    ]
  ) {
  id: ID!
  title: String
  owner: String
}
````

With an explanation: "The above schema assumes a combination of Amazon Cognito User Pools and IAM authentication types."

This seems not to be possible with the problems I'm experiencing now.

**Desktop (please complete the following information):**
 - OS:Mac
 - Node Version: v10.17.0

**Additional context**

**Comment by kjetilge** [comment] 2020-06-29 11:47
Update: When starting from scratch, it is possible to do the steps above! It's when I try to update from a previos state that I can not seem to combine  iam and cognito user pool with pre-signup.

It would be nice if it was possible to to a command like ```amplify status --details``` that could output all the choices made for a deployed service - it would make it easier to debug whats going on. Maybe even ```amplify push --diff``` that highlights changes about to be made.

**Comment by yuth** [comment] 2020-06-30 01:19
duplicate of https://github.com/aws-amplify/amplify-cli/issues/1874

**Comment by yuth** [comment] 2020-06-30 01:25
We hav

**Closed by yuth** 2020-06-30 01:25 UTC
Labels: bug, platform
