### ISSUE TITLE
Handling auth access to nested simple types in multi-auth model (Cognito and IAM)

### ISSUE THREAD

**Issue by zetsnotdead** [aws-amplify/amplify-cli#4090] opened 2020-04-27 20:23 UTC
**Describe the bug**
I cannot query simple types nested more than 1 level deep, when using `@model` with IAM and Cognito `@auth`.

I am using  
- Cognito User Pools for default auth for my client application.
- IAM auth for my backend functions

The #3289 was closed, but it only fixes the issue for queries nested one level deep. Any more than than, and it still doesn't work.

**Amplify CLI Version**
4.18.0

**To Reproduce**
Assuming the following schema

```graphql
type Address {
  streetName: String!
}

type Organisation {
  address: Address!
}

type Person @model @auth(rules: [
  { allow: private }
  { allow: private, provider: iam }
]) {
  organisation: Organisation!
}
```

If my backend function, using IAM auth, runs the following query
```graphql

getPerson(id: "123") {
  organisation {
    address {
      streetName
    }
  }
}
```
I get unauthorized error for accessing the streetName field.

**Comment by attilah** [comment] 2020-04-27 21:55
Duplicate of #3910

**Closed by attilah** 2020-04-27 21:55 UTC

**Comment by zetsnotdead** [comment] 2020-04-28 16:29
I appreciate you looking into this. Could you please provide me with a rough estimate of when this is going to be addressed? I need to know if i need to come up with a workaround right now, or just wait for the fix.

Anyway, love using the framework, and you guys are doing an awesome job :+1:
