### ISSUE TITLE
aws-exports.js is not generated

### ISSUE THREAD

**Issue by baharev** [aws-amplify/amplify-cli#186] opened 2018-09-21 13:22 UTC
I created a new hello world app with create-react-app. Followed the instructions on https://github.com/aws-amplify/amplify-cli and added auth and hosting to my hello world react app. The amplify cli did not report any errors, but reported OK. As far as I can tell all the necessary files were created by the amplify cli in the amplify subdirectory of the project. `amplify status` does show Auth. Everything looks OK except that the aws-exports.js is nowhere to find in the entire project folder.

Repeated the whole thing again, with the same result.

Everything is at the latest version as of Sep 21, 2018.

**Comment by mwarger** [comment] 2018-09-21 15:04
You will need to run `amplify push` to generate the `aws-exports.js` file, as this is done after the resources are created on AWS.

**Comment by baharev** [comment] 2018-09-21 16:15
OK, thanks. Please improve the documentation. It is counterintuitive and I don't see this piece of information in the README.md either.

**Comment by UnleashedMind** [comment] 2018-09-21 18:16
Hi 

Please visit the following link for more details documentation: 

https://aws-amplify.github.io/amplify-js/media/quick_start?platform=purejs

**Comment by baharev** [comment] 2018-09-21 19:11
Even after the third read I find it utterly confusing, and I have usability issues too.

Why should I push something that I could not have run locally? It is untested and most likely buggy but I cannot run `npm start` to test it without the `aws-exports.js`. 

In other words, on the first push, I would have to push something that is most likely broken because it has never been run (but I cannot run it).

I also find the https://aws-amplify.github.io/amplify-js/media/quick_start?platform=purejs page utterly confusing. `aws-exports.js` is only mentioned at `amplify push`, right above it I read: *"Create the AWS backend resources and update the aws-exports.js file."* This sentence tells me that this file already exists, since it is being updated. And that would be my expectation too. I would expect this file to be complete after `amplify init` (or maybe after the first `add`) has finished.

Generating `aws-exports.js` on the first push is confusing, and forces the users to push broken things the first time.

**Comment by UnleashedMind** [comment] 2018-09-21 21:12
Thanks for the feedbacks.

**Comment by kaustavghosh06** [comment] 2018-11-05 20:31
@caffodian I couldn't reproduce the issue with the latest version of the CLI. Many a times VS code bugs out and doesn't sync with my local filesystem to display the newly created files. Closing this issue for now. Please let me know if you're able to re-produce this with he latest version of the CLI.

**Comment by baharev** [comment] 2018-11-05 21:07
@kaustavghosh06 I don't see how [my objections](https://github.com/aws-amplify/amplify-cli/issues/186#issuecomment-423642385) were resolved.

**Comment by kaustavghosh06** [comment] 2018-11-05 21:10
@baharev  There is no way to locally test your AWS resources without pushing it. So I'm not sure what would you test with an empty aws_exports.js file without pushing your resources.

**Comment by jmanek** [comment] 2018-11-20 17:32
@kaustavghosh06 I found this issue for the same reasons @baharev had.  
If new resources need to be provisioned then obviously `init` is not enough and `push` is just not a clear name.  However I am working with existing AWS resources. So for example I want the "template" for Cognito authentication so I can replace the values with my own and not rely on magic.  It seems like I am actually expected to allocate an entirely new pool just to get this single config file that contains no config I actually need.  I just want the key names.  If there is a way to more simply integrate Amplify into an existing production environment it would go a long way for someone like me.

**Comment by kaustavghosh06** [comment] 2018-11-20 23:49
@jmanek If you look into our AWS Amplify documentation - https://aws-amplify.github.io/docs/cli/init you would observe that there isn't a lot of magic happening with the Amplify CLI. You can notice in the documentation that the CLI uses AWS Cloudformation underneath to create and manage your AWS resources. These Cloudformation files are created for you in your `amplify/<category>` directory as a response to you `amplify add <category>` command, which in turn gets deployed to the cloud on an `amplify push`. If you already have a resource provisioned, and are using the AWS Amplify JS lib, you could manually pass in your resource metadata information to the lib using the `Amplify.configure()` method and your frontend could then use an already existing userpool. The Amplify CLI is useful to use for provisioning resources and managing new userpools/identity pools.

**Comment by minheq** [comment] 2018-12-03 15:18
I am facing the same issue, but even after `amplify push` I do not have `aws-export.js` generated

**Comment by rkuzsma** [comment] 2018-12-04 11:43
I faced the same issue. In my case, when prompted during `amplify init` with the following choice:
```
Choose the type of app that you're building (Use arrow keys)
  android
  ios
❯ javascript
```
Make sure to choose `javascript`. If you choose the `android` option, then later on when you `amplify add auth` and `amplify push`, the CLI will not generate an `aws-exports.js` file.

Here is what my generated `aws-exports.js` file contains:
```
const awsmobile =  {
    "aws_project_region": "us-east-1"
};
export default awsmobile;
```

**Comment by JrSagas** [comment] 2018-12-17 21:14
> I faced the same issue. In my case, when prompted during `amplify init` with the following choice:
> 
> ```
> Choose the type of app that you're building (Use arrow keys)
>   android
>   ios
> ❯ javascript
> ```
> Make sure to choose `javascript`. If you choose the `android` option, then later on when you `amplify add auth` and `amplify push`, the CLI will not generate an `aws-exports.js` file.
> 
> Here is what my generated `aws-exports.js` file contains (actual ID's redacted by me):
> 
> ```
> const awsmobile =  {
>     "aws_project_region": "us-east-1",
>     "aws_cognito_identity_pool_id": "us-east-1:REDACTED",
>     "aws_cognito_region": "us-east-1",
>     "aws_user_pools_id": "us-east-1_REDACTED",
>     "aws_user_pools_web_client_id": "REDACTED"
> };
> export default awsmobile;
> ```

Everything works fine. 
In my case, I did it wrong! (Be careful to specify the source folder)

Whe I have to specify the source folder I put "www" instead of "src".
Because of that I never find the aws-exports.js in the "src" folder.

**Comment by kaustavghosh06** [comment] 2018-12-26 19:08
@rkuzsma For android projects, the CLI generates an `awsconfiguration.json` file (in the app directory) and not an `aws_exports.js` file ( which is generated only for javascript projects).

**Comment by kaustavghosh06** [comment] 2018-12-26 21:01
Closing this issue for now. Please feel free to re-open this if you have further questions.

**Comment by baharev** [comment] 2018-12-26 21:47
@kaustavghosh06 Once again, I don't see how [my objections](https://github.com/aws-amplify/amplify-cli/issues/186#issuecomment-423642385) were resolved. In reply to your earlier comment: Who said that I want to test my AWS resources? And why would I want to test AWS?

**Comment by kaustavghosh06** [comment] 2018-12-26 21:55
@baharev I'm not clear as to what you're advocating here.
If you do not want to test AWS, why would you want the aws_exports.js file in the first place?

**Comment by baharev** [comment] 2018-12-27 05:58
@kaustavghosh06 I would like to test my own client-side code, which imports aws_exports.js. Note that the code would run just fine without any AWS resource being available but it needs the aws_exports.js just to call `npm start`. Without the aws_exports.js, I have to push a most likely broken code on the first push to get the aws_exports.js. This is just wrong.

**Comment by kaustavghosh06** [comment] 2019-02-19 21:56
@baharev Please use the new install of the CLI. We genarate an aws_exports file on the first `amplify init` operation.

**Comment by baharev** [comment] 2019-02-20 19:14
@kaustavghosh06 OK, thanks.

**Comment by richardzyx** [comment] 2019-02-25 03:41
@kaustavghosh06 Just tried with the lastest 1.1.5 CLI, did a fresh clone of the repo, `amplify init` the master environment, but aws-exports file still not generated. Am I missing any step?

**Comment by kaustavghosh06** [comment] 2019-02-25 03:46
Please take a look at my screenshot below. 

<img width="1280" alt="screen shot 2019-02-24 at 7 44 00 pm" src="https://user-images.githubusercontent.com/7247658/53313117-b6711b00-386c-11e9-820f-4c868b15db34.png">

The aws_exports.js file would be in the directory which you specified as your "Source Directory Path" when you ran an `amplify init`.

**Comment by richardzyx** [comment] 2019-02-25 03:53
@kaustavghosh06 Thanks for the prompt reply!

I believe the screenshot shows the use case of creating a new environment through Amplify init which does work properly. My use case was cloning an amplify project on a fresh machine and trying to regenerate the aws-exports file after a new amplify profile is setup. In this case, only amplify push will regenerate the aws-exports file =]

**Comment by kaustavghosh06** [comment] 2019-02-25 03:55
I tried that as well..see the screenshot below. Is there something different that I shoud try out to reproduce this?

<img width="883" alt="screen shot 2019-02-24 at 7 54 35 pm" src="https://user-images.githubusercontent.com/7247658/53313405-11efd880-386e-11e9-94ae-c840710a508d.png">

**Comment by richardzyx** [comment] 2019-02-25 04:14
@kaustavghosh06 Hmm interesting, I don't see any difference except here's my output:

![image](https://user-images.githubusercontent.com/7928839/53313914-399c6c00-3881-11e9-825a-feb695525871.png)

As you can see, only amplify push generates the aws-exports.js... let me know if there's anything else you would like me try! I should note that I do have amplify profiles from two different organizations on my laptop, just in case it might be related to this issue.

**Comment by richardzyx** [comment] 2019-02-28 17:00
@kaustavghosh06 any update on this issue?

**Comment by appsols-dev** [comment] 2019-03-02 14:59
I had the same issue. What I was doing wrong was when I was setting my source destination during "amplify init", I was giving this "/src". So this is not the correct path as this means the initial destination of your partition, ed: D:/ or C:/.
I update the source destination to "src" only and it works, and now I have aws-export.js file in it.

**Comment by daniyal-intellicel** [comment] 2019-03-02 15:01
I had the same issue. What I was doing wrong was when I was setting my source destination during "amplify init", I was giving this "/src". So this is not the correct path as this means the initial destination of your partition, ed: D:/ or C:/.
I update the source destination to "src" only and it works, and now I have aws-export.js file in it.

**Comment by daniyal-intellicel** [comment] 2019-03-02 15:03
> I had the same issue. What I was doing wrong was when I was setting my source destination during "amplify init", I was giving this "/src". So this is not the correct path as this means the initial destination of your partition, eg: D:/ or C:/.
> I update the source destination to "src" only and it works, and now I have aws-export.js file in it.

You can update it using "amplify update project"

**Comment by roychoo** [comment] 2019-03-11 16:04
@richardzyx did you find your answer? i am also having this issue except the fact is that, aws-exports is not generated on my CI server but on local, it does.

**Comment by roychoo** [comment] 2019-03-12 15:35
@richardzyx it seems that the promise is not resolved correctly but i could not understand why it work on my mac and not on my CI server.
Would appreciate if you could at the same time test my PR https://github.com/aws-amplify/amplify-cli/pull/1028

**Comment by chris-merapar** [comment] 2019-03-19 10:37
On my mac and in CodeBuild the aws-exports.js is not generated:

1. Delete src/aws-exports.js (thereby simulating the CI env, as this is in the gitignore)
2. amplify init
3. amplify push (reports no changes, so does not do anything)
4. amplify publish

No src/aws-exports is generated. I am on amplify CLI v1.1.7. 

Does anyone have a workaround? Right now all our environments are broken as the aws-exports is not generated. Adding it to git won't help as it will be wrong for all our cloud envs.

**Comment by roychoo** [comment] 2019-03-19 10:55
I think it will work on node lts/carbon node 8.15.1. Are you using node 10?

**Comment by chris-merapar** [comment] 2019-03-19 12:01
Confirmed it works ok with CodeBuild image aws/codebuild/nodejs:8.11.0

Thanks for the tip!

**Comment by roychoo** [comment] 2019-03-19 12:30
@chris-merapar no prob

**Comment by ajhool** [comment] 2019-07-17 22:19
aws-exports isn't being generated for me in amplify-cli 1.8.2 (or 1.7.5). Have tried:

`amplify env checkout someenv`

`amplify env pull --restore`

`amplify push`

`amplify codegen`

`amplify status` (NO CHANGES) across the board.

There are no warnings or errors as far as I can tell.

**Comment by isubasinghe** [comment] 2019-08-06 10:36
It would be good if we can regenerate aws-exports as well, is this possible with the cli?

**Comment by jamesw6811** [comment] 2019-08-12 22:35
> It would be good if we can regenerate aws-exports as well, is this possible with the cli?

Agree. I have found my aws-exports does not always update, especially if I delete resources then init a new project. It will be stuck without updating to the new resources. It would be good to be able to do a complete project update/overwrite.

**Comment by Elifaz** [comment] 2019-08-31 07:45
> > It would be good if we can regenerate aws-exports as well, is this possible with the cli?
> 
> Agree. I have found my aws-exports does not always update, especially if I delete resources then init a new project. It will be stuck without updating to the new resources. It would be good to be able to do a complete project update/overwrite.

any updates on this?

**Comment by aldrinc** [comment] 2019-10-04 22:43
What is the recommended approach for handling this issue in a CI env? 

I'm using MS Appcenter for my builds and its failing because aws-exports.js is missing. I am unable to generate the aws-exports.js file via amplify push as it says no change. I'm on node v12.4.0.

**Comment by collindutter** [comment] 2020-02-27 21:25
@isubasinghe `amplify pull` regenerates aws-exports.

**Comment by ivenxu** [comment] 2020-03-10 20:03
The aws-exports.js is in .gitignore file and the only ways to generate are so heavy. It's a must-have that lightweight cli option to just generate the aws-exports.js.

**Comment by devbanhustly** [comment] 2020-03-16 21:29
Guys what really is the solution here? I was up all night trying to fix this. This is not a production ready product. WTF. What are the options to use cognito without amplify, if amplify is basically in beta?

**Comment by devbanhustly** [comment] 2020-03-16 21:33
I had to remove it from gitignore. If 100% of users are going to face such issues, please add a "in beta" ribbon to product label. Poor documentation.

**Comment by agentlewis** [comment] 2020-04-13 10:59
While I think it logically makes sense to be able to download the exports file again - it doesn't seem like a high priority to fix.

The documented bullet proof solution should be: `push up your code to a working branch`,`rm your repo`, `re-clone the repo`, `cd in` & `amplify init`

As you are already logged in on your computer it will ask something like this:

```bash
Do you want to use an existing environment? Yes
Choose the environment you would like to use: develop
Choose your default editor: Visual Studio Code
Do you want to use an AWS profile? Yes
Please choose the profile you want to use SELECT PREVIOUS PROFILE
etc...
```

Having done this you will then need to run `amplify pull` again. After that you should be good to go

**Comment by germanamz** [comment] 2021-03-12 09:54
So...
The problem with removing the `aws-exports.js` from the `.gitignore` is that you'll need to generate configurations each time you want to deploy to different envs... so my suggestion is to use a custom build image that should do the `amplify pull` to generate the file.

I think this should be included somehow on the default build image as Amplify is supposed to support different environments and we aren't able to build the apps properly because of this missing file.

NOTE: I think this is a major issue that's making me reconsider using Amplify...

**Comment by MaxmaxmaximusAWS** [comment] 2021-04-15 16:33
amplify is not capable of doing basic things like creating a config file. we have abandoned its use in favor of Microsoft Azure

**Comment by swaminator** [comment] 2021-07-06 16:40
The Amplify console just released a way so that you can autogenerate the aws-exports file at build time without checking it into your git repo: https://docs.aws.amazon.com/amplify/latest/userguide/amplify-config-autogeneration.html

**Closed by swaminator** 2021-07-06 16:40 UTC
Labels: documentation, enhancement
