### ISSUE TITLE
Parameters: [authRoleName, unauthRoleName] do not exist in the template

### ISSUE THREAD

**Issue by AlessandroVol23** [aws-amplify/amplify-cli#9166] opened 2021-12-01 13:27 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.18.1

### Amplify CLI Version

7.5.5

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

I try to add new code to my lambda function and push it locally (or in the console).

I get an error that my websocket API `apiPaymentWebhooks` has missing parameters.

```
UPDATE_FAILED      apiPaymentWebhooks AWS::CloudFormation::Stack Wed Dec 01 2021 14:22:36 GMT+0100 (Central European Standard Time) Parameters: [authRoleName, unauthRoleName] do not exist in the template
```

The parameters.json of this API looks like that:

```json
{
    "authRoleName": {
        "Ref": "AuthRoleName"
    },
    "unauthRoleName": {
        "Ref": "UnauthRoleName"
    }
}
```

I haven't changed anything in the API. 

The status shows only an update for the lambda function. 

It happens with this version and the version before as well. 

See discord [thread](https://discord.com/channels/705853757799399426/708077731711156284/915589050482696213) 

The deployment fails in **all** environments (dev, staging, prod)

### Expected behavior

The lambda function is updated and no deployment fails.

### Reproduction steps

1. Change lambda function
2. `amplify push`
3. Error

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by jhockett** [comment] 2021-12-01 18:38
Hi @AlessandroVol23, you should be able to change the content of `parameters.json` to be an empty object `{}`.

`authRoleName` and `unauthRoleName` are now passed in from the root stack, so the REST API CloudFormation template doesn't have those parameters anymore. Let me know if that fixes the issue for you.

@parvusville I think this is a separate issue, but thank you for reporting it. Hopefully will be fixed by https://github.com/aws-amplify/amplify-cli/pull/9144

**Comment by AlessandroVol23** [comment] 2021-12-02 08:03
So I tried executing the migration workflow and now I get another error.
The `parameters.json` is an empty object now. 

```
✔ A migration is needed to support latest updates on api resources.
Recommended to try in a non-production environment first. Run "amplify env add" to create or clone an environment.
Learn more about this migration: https://docs.amplify.aws/cli/migration/override
Do you want to migrate api resource "PaymentWebhooks"? (Y/n) · yes
```
**New Error**

```
✖ An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: Cannot read property 'deploymentBucketName' of undefined
```

**Comment by AlessandroVol23** [comment] 2021-12-02 08:25
Update: I've downgraded on `7.4.5` because I thought there was some issue that I need to downgrade

Next error:
```
UPDATE_FAILED LambdaFunction AWS::Lambda::Function Thu Dec 02 2021 09:21:28 GMT+0100 (Central European Standard Time) Resource handler returned message: "Layers consume more than the available size of 262144000 bytes (Service: Lambda, Status Code: 400, Request ID: c77bbfa3-04ee-4238-9375-56e6b07a4685, Extended Request ID: null)" (RequestToken: f6a9272b-edd6-a886-f6d6-0de9ee933457, HandlerErrorCode: InvalidRequest)
```

Not sure why anything happens with the layer now but try to figure that out now

**Comment by AlessandroVol23** [comment] 2021-12-02 09:26
I document the journey a bit that you get some insights on how it is sometimes with amplify :D 

I wanted to change the layer to the [public](https://awslabs.github.io/aws-lambda-powertools-python/latest/#lambda-layer) available of powertools anyway so I do that right now.

- Updated function to not use local layer but public available

**Delete local layer**

```
❯ amplify remove function
? Choose the resource you would want to remove stockifyawspowertoolspython (layer)
When you delete a layer version, you can no longer configure functions to use it.
However, any function that already uses the layer version continues to have access to it.
? Choose the Layer versions you want to remove. 44, 50
Layer versions marked for deletion:
- 44 | Description: Updated layer version 2021-11-06T17:48:47.526Z
- 50 | Description: Updated layer version 2021-11-16T10:06:42.032Z
Warning: By continuing, these layer versions [44] will be immediately deleted. All other layer versions will be deleted on amplify push.
All new layer versions created with the Amplify CLI will only be deleted on amplify push.

✔ Layers deleted

? Are you sure you want to delete the resource? This action deletes all files related to this resource from the backend directory. Yes
Error: ENOTEMPTY: directory not empty, rmdir '/Users/alessandrovolpicella/repo/stockify/amplify/backend/function/stockifyawspowertoolspython/lib/python/lib/python3.8/site-packages/boto3'
    at Object.rmdirSync (fs.js:916:10)
    at rmkidsSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:308:25)
    at rmdirSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:281:7)
    at rimrafSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:252:7)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:291:39
    at Array.forEach (<anonymous>)
    at rmkidsSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:291:26)
    at rmdirSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:281:7)
    at rimrafSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:252:7)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:291:39
    at Array.forEach (<anonymous>)
    at rmkidsSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:291:26)
    at rmdirSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:281:7)
    at rimrafSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:252:7)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:291:39
    at Array.forEach (<anonymous>)
    at rmkidsSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:291:26)
    at rmdirSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:281:7)
    at rimrafSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:252:7)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:291:39
    at Array.forEach (<anonymous>)
    at rmkidsSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:291:26)
    at rmdirSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:281:7)
    at rimrafSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:252:7)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:291:39
    at Array.forEach (<anonymous>)
    at rmkidsSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:291:26)
    at rmdirSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:281:7)
    at rimrafSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:252:7)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:291:39
    at Array.forEach (<anonymous>)
    at rmkidsSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:291:26)
    at rmdirSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:281:7)
    at Object.rimrafSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:252:7)
    at Object.remove (/usr/local/lib/node_modules/@aws-amplify/cli/src/context-extensions.ts:141:8)
    at deleteResourceFiles (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/remove-resource.ts:149:22)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at AmplifyToolkit.removeResource [as _removeResource] (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/remove-resource.ts:109:12)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/index.ts:252:3)
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:204:3)
    at Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)
🛑 An error occurred when removing the resources from the local directory
```

Error because some directory is not empty.

I delete all site-packages but cannot trigger it from the CLI now because the layer is already deleted in the configs.


This push seems to work. Not sure if I now just remove the local layer files or keep them?

**Comment by ludwigward** [comment] 2021-12-02 10:11
FYI there are some related content in a similar issue I had a while back. Although some others were not able to reproduce my solution was to add the two parameters back manually. https://github.com/aws-amplify/amplify-cli/issues/2519#issuecomment-834448537

**Comment by AlessandroVol23** [comment] 2021-12-02 10:12
Hopefully, you want to see the journey of a customer so I continue a bit. The original issue is solved I think.

Next issue: Layer was not deleted properly. It was removed somewhere that it doesn't appear in the CLI anymore but is still in `team-provider` and `backend-config.json`. Now the build fails in the console

```
Lambda layer stockifyawspowertoolspython is missing a state file. Try running "amplify pull --restore". If the issue persists, recreating the layer is the best option. Ensure your layer content is backed up!
```

So I try to restore it with `amplify pull --restore`

-> Nothing changed

`amplify remove function` doesn't show the layer anymore but it is in every file still existing just not in the file `amplify/backend/types/amplify-dependent-resources-ref.d.ts`. 

Added it back there, no change. 

So I try to recreate it like suggested in the error message.

- Recreated layer with the same name
- Did **not** push
- Deleted layer again
- Push
- Push did work
- Develop push -> Trigger console
- Console worked
Everything looks good now!

I know it is not best practice to mix 5 different problems into one issue but I hope I could give you a bit of a glance how it (sometimes) is developing some things with Amplify 😃 

Took now about ~3 hrs for adding two LOC in lambda with some really bad luck. 

Still thanks for your support! :) 
We can close this one now.

**Comment by christianguevara** [comment] 2021-12-02 19:48
Same error with amplify v7.6.1

```
UPDATE_FAILED      apiYYYYYY                  AWS::CloudFormation::Stack Thu Dec 02 2021 14:25:48 GMT-0500 (Ecuador Time) Parameters: [authRoleName, unauthRoleName] must have values
UPDATE_FAILED      apiaXXXXX                   AWS::CloudFormation::Stack Thu Dec 02 2021 14:25:48 GMT-0500 (Ecuador Time) Parameters: [authRoleName, unauthRoleName] must have values
UPDATE_FAILED      apiZZZZZZ                 AWS::CloudFormation::Stack Thu Dec 02 2021 14:25:48 GMT-0500 (Ecuador Time) Parameters: [authRoleName, unauthRoleName] must have values
```
Changes after I was FORCED to migrate after an auth override.

<img width="627" alt="Screen Shot 2021-12-02 at 14 45 02" src="https://user-images.githubusercontent.com/10765364/144492185-266a6f67-2f0c-4aa2-8a27-6cceee8a158f.png">

At this point I'm way too afraid to update minor/patch versions :/

**Closed** 2021-12-02 21:07 UTC
Labels: bug, api-rest
