### ISSUE TITLE
Exception when running default generated Lambda triggers for Cognito

### ISSUE THREAD

**Issue by skryshi** [aws-amplify/amplify-cli#8102] opened 2021-09-05 07:00 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.6.1

### Amplify CLI Version

5.4.0

### What operating system are you using?

OSX 11.5.2

### Amplify Categories

auth

### Amplify Commands

update

### Describe the bug

1. Generate Lambda Triggers for Cognito. I tried "pre-sign up" and "post confirmation" ones. Select "Create your own module".

```
 What do you want to do? Walkthrough all the auth configurations
 Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AWS IAM controls (Enables per-user Storage features for images
 or other content, Analytics, and more)
 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) No
 Do you want to enable 3rd party authentication providers in your identity pool? No
 Do you want to add User Pool Groups? No
 Do you want to add an admin queries API? No
 Multifactor authentication (MFA) user login options: OFF
 Email based user registration/forgot password: Disabled (Uses SMS/TOTP as an alternative)
 Please specify an SMS verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? No
 Specify the app's refresh token expiration period (in days): 30
 Do you want to specify the user attributes this app can read and write? Yes
 Specify read attributes: Phone Number
 Specify write attributes: Phone Number
 Do you want to enable any of the following capabilities? 
 Do you want to use an OAuth flow? No
 Do you want to configure Lambda Triggers for Cognito? Yes
 Which triggers do you want to enable for Cognito Post Confirmation, Pre Sign-up
 What functionality do you want to use for Post Confirmation Create your own module
 What functionality do you want to use for Pre Sign-up Create your own module

```

2. Without changing the generated NodeJS code, mock the function: "amplify mock function"
3. Fails with this exception: `"TypeError: callback is not a function"`

If instead of (2), I upload the code to the cloud and run it, I also get the same exception (3).

This is the function that's generated (`src/custom.js`) that throws the exception:

```
exports.handler = (event, context, callback) => {
  // insert code to be executed by your lambda trigger
  callback(null, event);
};
```

### Expected behavior

Generated default function code does not throw exception.

### Reproduction steps

See above.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by lazpavel** [comment] 2021-09-08 13:00
Hello @skryshi,

Thank you for reporting this issue, I was able to reproduce it and marked as a bug for the team to pick up.

**Comment by josefaidt** [comment] 2021-09-08 14:31
Hey @skryshi :wave: as @lazpavel noted this is indeed a bug where the `custom.js` template requires an update. If we look at the entrypoint file `index.js` we see only `event` is being passed in to our `custom.js` module. As a workaround, please update your `custom.js` module to return the event:

```js
// custom.js
exports.handler = event => {
  // insert code to be executed by your lambda trigger
  return event
}
```

and with the entrypoint anticipating a Promise, we can also make this custom module async!

```js
// custom.js
exports.handler = async event => {
  // insert code to be executed by your lambda trigger
  return event
}
```

**Comment by skryshi** [comment] 2021-11-21 10:25
@josefaidt Yes, thank you, that's what I've been doing, replacing the generated code with your snippet.

**Comment by clintfoster** [comment] 2021-12-04 18:04
This problem is present in the `index.js` originally created by `amplify add auth`. (In other words, it repros without having to do `auth update`.)

As discussed above, the generated `index.js` is passing only the `event` parameter, not `context` & `callback`. I went down a rat hole trying to figure out why the service isn't passing these parameters until I noticed the problem is in the generated `index.js` that invokes all the callbacks in parallel. 

I guess it goes without saying a simple fix to `index.js` is as follows. This assumes all the trigger handlers take the same parameters. But I don't know if that's the case.

```javascript
// exports.handler = async event => {  // bad code generated by "add auth"
exports.handler = async (event, context, callback) => {
  /**
   * Instead of naively iterating over all handlers, run them concurrently with
   * `await Promise.all(...)`. This would otherwise just be determined by the
   * order of names in the `MODULES` var.
   */
  // await Promise.all(modules.map(module => module.handler(event)));  // bad
  await Promise.all(modules.map(module => module.handler(event, context, callback)));
  return event;
};
```

**Comment by josefaidt** [comment] 2022-02-14 22:56
Hey @skryshi this has now been fixed with https://github.com/aws-amplify/amplify-cli/pull/9649, where newly created custom modules will have the following `custom.js` contents

```js
/**
 * @type {import('@types/aws-lambda').APIGatewayProxyHandler}
 */
exports.handler = async (event, context) => {
  // insert code to be executed by your lambda trigger
  return event
};
```

Closing issue 🙂

**Closed by josefaidt** 2022-02-14 22:56 UTC
Labels: bug, functions, p2
