### ISSUE TITLE
Function delete permissions misses "dynamodb:BatchWriteItem" policy

### ISSUE THREAD

**Issue by ignaciolarranaga** [aws-amplify/amplify-cli#5156] opened 2020-08-23 11:03 UTC
**Describe the bug**
When you grant permissions to a function to delete in a table the associated cloudformation template misses to grant "dynamodb:BatchWriteItem" permissions which are required for a batch deletion.

**Amplify CLI Version**
4.27.3

**To Reproduce**
Over the todo example:
1) create a function to resolve a custom delete.
Example:
```
type Mutation {
  deleteAllTodos(input: DeleteAllTodosInput!): [Todo] @function(name: "todoDeleteResolvers-${env}")
}
```
2) Grant delete permissions to `todoDeleteResolver` function

You will see the granted permissions are `"dynamodb:Delete*"`

**Expected behavior**
`"dynamodb:BatchWriteItem"` should be also added as it is required to perform batch delete operations

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: 12.16.1

**Additional context**
N/A

**Comment by UnleashedMind** [comment] 2020-08-24 17:51
When granting permissions to a function, we follow the Principle of Least Privilege.  "dynamodb:BatchWriteItem" would allow not only batch delete, but also batch put, of multiple items, which goes beyond the least privilege of the specified delete permission.

There are simple ways to explicitly ask the Amplify CLI to grant batch operation permissions though, marked this as enhancement.

**Comment by UnleashedMind** [comment] 2020-08-24 18:15
I can't reproduce, "dynamodb:BatchWriteItem" is actually in the policy statement of the function.

**Comment by ignaciolarranaga** [comment] 2020-08-29 14:47
mmm, not sure what can be different, I just tried again and only "Delete" permission is added, check this out:
<img width="1060" alt="Sample" src="https://user-images.githubusercontent.com/15932965/91639468-32619b80-e9ed-11ea-94a4-e34c51494c8f.png">

**Closed** 2020-10-10 12:41 UTC
Labels: functions, not-reproducable, pending-close-response-required
