### ISSUE TITLE
UPDATE_FAILED      functionstorageTrigger         AWS::CloudFormation::Stack Mon Sep 20 2021 06:16:51 GMT-0700 (Pacific Daylight Time) Parameters: [functionsharedResourcesArn] do not exist in the template

### ISSUE THREAD

**Issue by babaralishah** [aws-amplify/amplify-cli#8217] opened 2021-09-20 14:48 UTC
I am been facing this error, if someone else encountered such, then please help me out

**Comment by siegerts** [comment] 2021-09-20 14:58
Closing as duplicate of https://github.com/aws-amplify/amplify-cli/issues/8218. @babaralishah, please reformat with more context ([issue form](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml)) to help the team troubleshoot.

**Closed by siegerts** 2021-09-20 14:58 UTC
Labels: question
