### ISSUE TITLE
Current environment cannot be determined

### ISSUE THREAD

**Issue by libeanim** [aws-amplify/amplify-cli#3161] opened 2020-01-10 17:29 UTC
I recently updated the amplify cli and now when running `amplify push` in my project I receive following error:

```
$ amplify push
An error occured during the push operation: Current environment cannot be determined
Use 'amplify init' in the root of your app directory to initialize your project with Amplify
```

Running `amplify init` again returns following:

```
$ amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the environment dev
? Choose your default editor: Visual Studio Code
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use PeskyAWS
Adding backend environment dev to AWS Amplify Console app: d3i74i7p2o0hzv
⠏ Initializing project in the cloud...

CREATE_IN_PROGRESS amplify-amplify-dev-162400 AWS::CloudFormation::Stack Fri Jan 10 2020 16:24:02 GMT+0000 (Greenwich Mean Time) User Initiated             
CREATE_IN_PROGRESS DeploymentBucket           AWS::S3::Bucket            Fri Jan 10 2020 16:24:05 GMT+0000 (Greenwich Mean Time)                            
CREATE_IN_PROGRESS UnauthRole                 AWS::IAM::Role             Fri Jan 10 2020 16:24:05 GMT+0000 (Greenwich Mean Time)                            
CREATE_IN_PROGRESS AuthRole                   AWS::IAM::Role             Fri Jan 10 2020 16:24:05 GMT+0000 (Greenwich Mean Time)                            
CREATE_IN_PROGRESS UnauthRole                 AWS::IAM::Role             Fri Jan 10 2020 16:24:06 GMT+0000 (Greenwich Mean Time) Resource creation Initiated
CREATE_IN_PROGRESS AuthRole                   AWS::IAM::Role             Fri Jan 10 2020 16:24:06 GMT+0000 (Greenwich Mean Time) Resource creation Initiated
CREATE_IN_PROGRESS DeploymentBucket           AWS::S3::Bucket            Fri Jan 10 2020 16:24:06 GMT+0000 (Greenwich Mean Time) Resource creation Initiated
⠴ Initializing project in the cloud...

CREATE_COMPLETE AuthRole   AWS::IAM::Role Fri Jan 10 2020 16:24:21 GMT+0000 (Greenwich Mean Time) 
CREATE_COMPLETE UnauthRole AWS::IAM::Role Fri Jan 10 2020 16:24:21 GMT+0000 (Greenwich Mean Time) 
⠧ Initializing project in the cloud...

CREATE_COMPLETE DeploymentBucket AWS::S3::Bucket Fri Jan 10 2020 16:24:27 GMT+0000 (Greenwich Mean Time) 
⠏ Initializing project in the cloud...

CREATE_COMPLETE amplify-amplify-dev-162400 AWS::CloudFormation::Stack Fri Jan 10 2020 16:24:29 GMT+0000 (Greenwich Mean Time) 
✔ Successfully created initial AWS cloud resources for deployments.
init failed
TypeError [ERR_INVALID_ARG_TYPE]: The 'request' argument must be string. Received type undefined
    at /usr/lib/node_modules/@aws-amplify/cli/lib/lib/init-steps/s9-onSuccess.js:39:32
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/@aws-amplify/cli/lib/lib/init-steps/s9-onSuccess.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/@aws-amplify/cli/lib/lib/init-steps/s9-onSuccess.js:4:12)
    at run (/usr/lib/node_modules/@aws-amplify/cli/lib/lib/init-steps/s9-onSuccess.js:19:12)
```

After that I still cannot run `amplify push`. Unfortunately I also can't remember what the previous version of amplify cli was I used. Otherwise I would have gone back to that version.

**Whats the best way to fix that?**
The only option I see at the moment is to create a new amplify project, then run `amplify add api`, copy the `schema.graphl` to the new amplify project and then link the AppSync Data Sources to the old dynamo db tables.

**Amplify CLI Version** 

4.12.0

**What AWS Services are you utilizing?**

Cognito, AppSync (DynamoDB)

**Provide additional details e.g. code snippets**

**Comment by libeanim** [comment] 2020-01-10 17:32
I also tried the workaround suggested in #3094

```
echo "{ \"projectPath\": \"$(pwd)\", \"envName\": \"${AWS_BRANCH}\"}" > amplify/.config/local-env-info.json
```

Which then causes this:

```
$ amplify push
✖ There was an error pulling the backend environment .
An error occured during the push operation: ENOENT: no such file or directory, open 'amplify/team-provider-info.json'
```


Let me know if you need any additional info.

**Comment by UnleashedMind** [comment] 2020-01-10 22:29
@libeanim 
It seems like your project is in a corrupt state, it does not have the team-provider-info.json file and the local-env-info.json file. 
is the project originally been setup on the computer you are working on now? or you pull the codebase from somewhere? 
Could you zip the `amplify` folder and send it over to us so we can investigate future? 
amplify-cli@amazon.com

**Comment by malbrecht0792** [comment] 2020-01-11 22:08
I'm also having this issue when I try to run `aws amplify start-job --app-id <appid> --branch-name <branchname> --job-type RELEASE` for a specific branch.

I've run `amplify init` again and selected my existing `dev` environment but every time I try to run the release command for my branch I'm getting this error

Any help would be much appreciated

**Comment by libeanim** [comment] 2020-01-12 21:01
@UnleashedMind Thanks for your help, I sent an email with the zipped amplify folder.

The project was originally created on this computer and was also under version control since. However it was created a year ago with an older amplify-cli version. (I just recently upgraded the amplify-cli to the newest version).

Is it possible that the team-provider-info.json file and the local-env-info.json file did not exist back then?

**Comment by heitorlessa** [comment] 2020-01-15 00:23
I had something similar when I upgraded from 1.x to 4.x and the command `amplify configure project` created/updated the correct files for me - have tried that?

**Comment by olivoil** [comment] 2020-01-15 06:49
I'm facing the same issue for a project created with version 4.5 after upgrading to 4.12

I do have a team-provider-info.json file locally, and PR builds were working before upgrading the CLI version.

I believe this is a bug in recent versions of the CLI, and I can't downgrade to older versions because they create lambda functions with the node8 runtime which does not work anymore.

**Comment by heitorlessa** [comment] 2020-01-15 23:16
@olivoil I've just pinned mine to 4.11.0 and that includes nodejs10.x runtime. My project is now fully working both locally and within Amplify Console:

**excerpt amplify.yml**

```yaml
version: 0.1
backend:
  phases:
    preBuild:
      commands:
        - npm install -g @aws-amplify/cli@4.11.0 # pinned known working version
```

**Comment by UnleashedMind** [comment] 2020-01-16 19:25
@olivoil 
Your issue is probably different from @libeanim 's , although the error message is the same. There's a [PR](https://github.com/aws-amplify/amplify-cli/pull/3196) out already for the issue you had.

**Comment by olivoil** [comment] 2020-01-17 05:29
Thank you @heitorlessa, pinning down the version to 4.11.0 worked!

**Comment by olivoil** [comment] 2020-01-17 05:34
Thanks @UnleashedMind, good to know. I'll test when the PR is merged to confirm

**Comment by rahulvyas1** [comment] 2020-01-17 05:51
> `amplify configure project` created/updated the correct file

This worked for me. Thanks

**Comment by Elmegaard** [comment] 2020-01-19 14:43
I am getting this same error:
```
2020-01-19T14:36:25.870Z [INFO]: # Initializing existing Amplify environment: master (amplify init)
2020-01-19T14:36:26.345Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2020-01-19T14:36:28.826Z [INFO]: init failed
2020-01-19T14:36:28.829Z [INFO]: UndeterminedEnvironmentError: Current environment cannot be determined
                                 Use 'amplify init' in the root of your app directory to initialize your project with Amplify
                                 at getEnvInfo (/root/.nvm/versions/node/v12.8.1/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/get-env-info.js:19:15)
                                 at AmplifyToolkit.getProjectDetails [as _getProjectDetails] (/root/.nvm/versions/node/v12.8.1/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/get-project-details.js:14:26)
                                 at Object.run (/root/.nvm/versions/node/v12.8.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/amplify-service-migrate.js:9:42)
                                 at Object.run (/root/.nvm/versions/node/v12.8.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initializer.js:80:33) {
                                 name: 'UndeterminedEnvironmentError'
                                 }
```
This works perfectly fine locally though and I can push just fine and everything is working exactly as intended. But as soon as I start a build the backend fails to build.

I tried everything mentioned here and no dice. This is my build file:
```
version: 0.1
backend:
  phases:
    preBuild:
      commands:
        - npm install -g @aws-amplify/cli@4.12.0 # pinned known working version  
    build:
      commands:
        - '# Get Amplify CLI Cloud-Formation stack info from environment cache'
        - export STACKINFO="$(envCache --get stackInfo)"
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --environment $AWS_BRANCH
        - '# Store Amplify CLI Cloud-Formation stack info in environment cache'
        - envCache --set stackInfo "$(amplify env get --json --name $AWS_BRANCH)"
frontend:
  phases:
    preBuild:
      commands:
        - npm install
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by heitorlessa** [comment] 2020-01-19 16:48
Peter - Change to 4.11.0 under your preBuild section and it should work

**Comment by Elmegaard** [comment] 2020-01-19 17:01
I am getting the same issue with 4.11.0. I use 4.12.0 locally and that seemed to work so I tried that.

**Comment by heitorlessa** [comment] 2020-01-19 17:03
I had the same issue with 4.12 - works locally but not in Amplify Console.
Changed to 4.11 in the build settings and it’s working since last week
 with multiple builds and envs

**Comment by Elmegaard** [comment] 2020-01-19 17:16
Doesn't seem to work for me, could the version be cached or something?

**Comment by heitorlessa** [comment] 2020-01-19 17:19
Possibly. To rule that out, comment that line in preBuild and use the Live
Packages features that is handled at the container build lifecycle:

https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html

Here’s my custom build setup just in case

https://github.com/aws-samples/aws-serverless-airline-booking/blob/develop/amplify.yml

**Comment by Elmegaard** [comment] 2020-01-19 18:18
I have overridden the amplify cli version in build settings and that fixed the issue. Thank you very much.

**Comment by davekiss** [comment] 2020-01-27 16:14
Followed the same steps above to pin to 4.11 and it worked, 4.12 is currently broken

**Comment by kaustavghosh06** [comment] 2020-01-27 16:33
@davekiss 4.13.1 should have the fix for this.

**Closed** 2020-01-27 16:34 UTC
Labels: pending-triage, platform

**Comment by Jordan-Eckowitz** [comment] 2020-03-10 20:45
@kaustavghosh06 I'm currently getting this error with `v4.16.1`

**Comment by chai86** [comment] 2020-03-31 16:04
@UnleashedMind I have just moved to a new machine and my project was running beautifully (with Api, Auth, Storage services via Amplify). I then installed `npm install -g @aws-amplify/cli`. I ran amplify status: 

```
| Category | Resource name | Operation | Provider plugin   |
| -------- | ------------- | --------- | ----------------- |
| Api      | project     | Update    | awscloudformation | <-strangely updated?
| Auth     | project837477  | No Change | awscloudformation |
| Storage  | projectStorage | No Change | awscloudformation |
```

Strangely Api updated even though i've made no changes. Anyway, when i ran `amplify push`, i got the following error. 
`An error occurred during the push operation: ENOENT: no such file or directory, team-provider-info.json'`

Then i tried `npm install -g @aws-amplify/cli@4.11.0` but still no luck to push. What on earth is going on? I'm paralyzed in my tracks right now and i have to kick on and complete this project. Please help!!

**Comment by bilal-korir** [comment] 2020-05-04 15:40
Running `amplify init` from the root project's directory has solved the issue for me.

My issue started when I tried to work on an old project that was initialized by an old version of Amplify CLI.
