### ISSUE TITLE
Duplicated files generated from amplify env pull --restore

### ISSUE THREAD

**Issue by 112Cracker** [aws-amplify/amplify-cli#3577] opened 2020-03-04 19:18 UTC
**Issue/question**
I am setting up an amplify project. I cloned a existing git repo first.
And I ran `amplify configure` within my project folder and created a new IAM user on aws.
After that, I ran `amplify init` and select a existing environment that have been created by my colleagues to initialize my amplify project.

The problem is when I ran `amplify env pull --restore`, there will be duplicated files generated in several minutes. For a file named "file.json', the file with duplicated content will be "files 2.json". Always have a number like 2 or 3 appending at the end of the previous filename.

**Additional information**
OS: macOS Mojave
node version: 12.16.1
aws-amplify: ^1.1.36

I found a similar issues here but is not exactly same to my situation:
https://github.com/aws-amplify/amplify-cli/issues/3153

**Comment by nikhname** [comment] 2020-03-04 22:18
@112Cracker Could you specify which files are duplicated?

**Comment by 112Cracker** [comment] 2020-03-04 22:53
Yes. This situation is that after I ran `amplify init`, every file within my amplify directory is duplicated.

**Comment by jhockett** [comment] 2020-03-06 19:47
@112Cracker I haven't been able to reproduce the issue so far. What version of the CLI are you using? You can find it by typing `amplify -v` in terminal.

Have you tried running init as root? Does `sudo amplify init` result in the same issue for you?

**Comment by eliasdefaria** [comment] 2020-03-06 21:07
We've recently experienced the same behavior on a project. We were using amplify version 4.13.4 and running it as root did not change the outcome. We recently had a new Iam user initialize amplify using 4.13.4 while we were still on 4.13.1. Could that discrepancy be the issue?

**Comment by 112Cracker** [comment] 2020-03-06 21:07
I have given my terminal admin access before running `amplify env pull --restore` and it still had duplicated files.

**Comment by jhockett** [comment] 2020-03-06 21:58
> We've recently experienced the same behavior on a project. We were using amplify version 4.13.4 and running it as root did not change the outcome. We recently had a new Iam user initialize amplify using 4.13.4 while we were still on 4.13.1. Could that discrepancy be the issue?

Hello @eliasdefaria. Which OS was being used when the CLI duplicated the files? Was it also the files in the amplify/ folder? Were there any others?

**Comment by eliasdefaria** [comment] 2020-03-06 22:05
@jhockett I was using MacOS 10.14.6. It was only files in the amplify/ folder and sub-folders. It would start by duplicating the backend-config.json and amplify-meta.json in backend/, then it would duplicate the files in our service sub-folders.

**Comment by jhockett** [comment] 2020-03-06 23:58
Hello @112Cracker, we're still looking for the cause of the duplication. Can you help me eliminate some possible causes?

Do you remember having the amplify project open in a text editor/IDE while you were running `amplify env pull --restore`? If so, which one?

Which version of the CLI are you using presently? `amplify -v`

If you're not already on 4.14.1, can you see if you still get the duplication after updating to the newest CLI version?

**Comment by 112Cracker** [comment] 2020-03-07 01:01
Yes. I am opening VS-Code when running `amplify env pull --restore`.
My amplify version 4.13.4
The latest duplicate file situation is when I run `git pull origin master` from my feature branch. After several minutes, the duplicated files came back, and this time my original files are deleted.
For example, if there is a index.js, this file is deleted and a index 3.js is created with the same content.

**Comment by attilah** [comment] 2020-03-07 03:56
@112Cracker do you have a share-able git repo where we could reproduce this behavior? also exact repro steps.

- You are in a git branch?
- You execute git pull origin master when VS code is opened and from within vs code terminal?
- What is the amplify env when you do a pull --restore?
- Is the amplify init command the exact one that creates these numbered dupliacates?

If you do all these commands outside of vs code with vs code closed is the duplication happens in that case as well?

((I'm trying to eliminate the influence of vs code in this whole file numbering problem))

**Comment by attilah** [comment] 2020-03-09 19:20
@112Cracker this issue relates to #3576 and the same [workaround steps](https://github.com/aws-amplify/amplify-cli/issues/3576#issuecomment-596732233) would resolve your problem as well.

Try them and get back to us if this helped.

**Comment by 112Cracker** [comment] 2020-03-10 23:36
Hi @attilah ,

From my most-recent observations, I carried out the following steps:
(1) Git clone the project repo.
(2) Run `amplify init` inside project root directory.
(3) Run `amplify status` and find there are multiple resource updates after step (2) and no one is actually doing `amplify push` at the same time to push any changes.
(4) By the time when I run `amplify env pull --restore`, there are some old changes pouring in and update several local files in amplify folder. Several minutes later, duplicated files are generated which are not the identical content to the current files but are identical to the previous files before running `amplify env pull --restore`.

**Comment by 112Cracker** [comment] 2020-03-10 23:38
Hi @jhockett, thanks for the follow-up! I think the current problem is that after running `amplify init`, I could not get the latest environment resources. After doing `amplify env pull --restore`, it's actually pulling something outdated which later led to the duplicated files.

**Comment by jhockett** [comment] 2020-03-12 04:57
@112Cracker Could you please try the steps you've mentioned with VS-Code closed? We had another customer with a similar duplicate files issue and it was because VS-Code was open. I'm not seeing any code in the Amplify CLI that appends numbers to file names when saving files.

**Comment by kaustavghosh06** [comment] 2020-03-19 22:01
@112Cracker Closing this issue due to lack of requested information above and based on the conversation above it looks like a VSCode issue and not amplify-cli related. Please comment on this thread if you have more thoughts around this.

**Closed by kaustavghosh06** 2020-03-19 22:01 UTC
Labels: multienv, not-reproducable, pending-response

**Comment by brandonking7** [comment] 2020-10-31 10:40
This is still an issue.

**Comment by jhockett** [comment] 2020-10-31 19:02
@brandonking7 the team hasn't been able to reproduce this issue so far. Can you tell me more about your setup? Any ideas on steps to repro?

OS, amplify version, node version, code editor

**Comment by 112Cracker** [comment] 2020-10-31 19:19
The reason for this issue is not because of Amplify CLI I think. It is because I iCloud sync was enabled on my laptop. details see [incloud sync creating duplicate files when saving](https://technology.siprep.org/icloud-sync-creating-duplicate-files-when-saving/). 
After I disabled it, this issue is gone @brandonking7 @jhockett
