### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-cli#2454] opened 2019-09-29 17:49 UTC
Just updated amplify cli, and when i run 'amplify push' it starts and then gives this error:

> Cannot read property 'length' of undefined
> An error occured during the push operation: Cannot read property 'length' of undefined

I have simply added a string field to one of my models.

**Comment by YikSanChan** [comment] 2019-09-30 00:12
If you do not paste your code change people are unable to help

**Comment by oliverandersencox** [comment] 2019-09-30 03:27
@YikSanChan I changed this model:

```
type City @model 
@key(name: "cityByName", fields: ["title"], queryField: "findCityByName")
  @auth(rules: [
    { allow: groups, groups: ["admin"], operations: [update, delete, create] }
  ])
@searchable {
  id: ID!
  title: String!
  description: String
  country: String
  continent: String
  location: Location
  timezoneOffset: Float
  currency: String <-- NEW
  images: [String]
  createdAt: Float!
  updatedAt: Float!
}
```
Nothing I can see there should be causing an issue. Everything worked find before the update

**Comment by YikSanChan** [comment] 2019-09-30 03:54
if you run `amplify mock api` do you get error? this is an easier way to see how things go without pushing it

**Comment by oliverandersencox** [comment] 2019-09-30 03:56
@YikSanChan jus did that, and get the same error:

> Failed to start API Mock endpoint TypeError: Cannot read property 'length' of undefined

Its seems I cannot just update amplify cli as each time a brand new issue appears with errors that provide no idea of whats causing it

**Comment by kaustavghosh06** [comment] 2019-10-03 06:51
@oliverandersencox Does the CLI any error stack trace for this?

**Comment by GeorgeBellTMH** [comment] 2019-10-08 07:34
I am getting this as well...mock and push not working...

The following types do not have '@auth' enabled. Consider using @auth with @model
	 - TNSeries
	 - TNSermon
	 - Blog
	 - News
	 - Event
	 - Group
	 - Organization
	 - Staff
	 - Region
Learn more about @auth here: https://aws-amplify.github.io/docs/cli-toolchain/graphql#auth 

Failed to start API Mock endpoint TypeError: Cannot read property 'length' of undefined

**Comment by GeorgeBellTMH** [comment] 2019-10-08 07:35
Using 3.11.0, update was from 3.2.0

**Comment by GeorgeBellTMH** [comment] 2019-10-08 08:02
I did update on functions, api, hosting...I have one graph and one rest api....

**Comment by divait** [comment] 2019-10-08 17:47
Same issue, any solution?

**Comment by SwaySway** [comment] 2019-10-08 20:09
@GeorgeBellTMH @divait What are the steps done that led up to this issue?
I'm not able to reproduce this issue below are the steps taken to reproduce this.
Using @oliverandersencox's schema with Location type defined.
### Schema
```gql
type City @model
	@key(name: "cityByName", fields: ["title"], queryField: "findCityByName")
	@auth(rules: [
		{ allow: groups, groups: ["admin"], operations: [update, delete, create] }
	])
{
	id: ID!
	title: String!
	description: String
	country: String
	continent: String
	location: Location # used a some Location type
	timezoneOffset: Float
	currency: String # did not add this with the first push using ver 3.2.0
	images: [String]
	createdAt: Float!
	updatedAt: Float!
}

type Location {
	name: String!
	address: String!
}
```
### Steps Taken
1. Did the push with the following schema above using amplify 3.2.0.
1. Installed amplify version 3.11.0 and added `currency: String` and ran mock

**Comment by philipmclifton** [comment] 2019-10-08 20:20
I get the same error:

1. Upgrade
2. Run push successfully
3. Run mock (length error shows)
4. Run push (length error shows)

**Comment by philipmclifton** [comment] 2019-10-08 21:02
Went through older versions.

Issue disappears in : `npm i -g @aws-amplify/cli@3.4.0`

Ran into this error in 3.4.0:

```Must provide at least one transformer.
An error occured during the push operation: Must provide at least one transformer.```

Downgraded to 2.0.0:

Ran into this issue: https://github.com/aws-amplify/amplify-cli/issues/2287

Renamed my keys. 

Won't be upgrading again in a hurry.

**Comment by GeorgeBellTMH** [comment] 2019-10-09 05:47
In sanity-check.js line 226         
var innerDiffs = deep_diff_1.diff(oldIndexesDiffable, newIndexesDiffable);
is returning null...error is happening at line 229
        for (var _i = 0, innerDiffs_2 = innerDiffs; _i < **innerDiffs_2.length**; _i++) {


old/new index are:
OLD:
{
  'gsi-SeriesSermons': {
    IndexName: 'gsi-SeriesSermons',
    KeySchema: [ [Object] ],
    Projection: { ProjectionType: 'ALL' },
    ProvisionedThroughput: { 'Fn::If': [Array] }
  },
  BySermonIdent: {
    IndexName: 'BySermonIdent',
    KeySchema: [ [Object] ],
    Projection: { ProjectionType: 'ALL' },
    ProvisionedThroughput: { 'Fn::If': [Array] }
  }
}

NEW:
{
  BySermonIdent: {
    IndexName: 'BySermonIdent',
    KeySchema: [ [Object] ],
    Projection: { ProjectionType: 'ALL' },
    ProvisionedThroughput: { 'Fn::If': [Array] }
  },
  'gsi-SeriesSermons': {
    IndexName: 'gsi-SeriesSermons',
    KeySchema: [ [Object] ],
    Projection: { ProjectionType: 'ALL' },
    ProvisionedThroughput: { 'Fn::If': [Array] }
  }
}

**Comment by GeorgeBellTMH** [comment] 2019-10-09 06:02
I believe that after the keyBy we need to sortBy indexName for a more accurate diff...

**Comment by GeorgeBellTMH** [comment] 2019-10-10 05:59
This was resolved by deleting my global node_modules and project node_modules and reinstalling everything.

**Comment by divait** [comment] 2019-10-11 17:50
To generate the error I create my schema using version 3.2:
```graphql
scalar AWSDateTime

enum DownloadType
{
  all
  reviewed
}

type Image
  @model
  @key(name: "ByDataset", fields: ["imageDatasetId", "createdAt"], queryField: "imagesByDataset")
{
  id: ID!
  key: String!
  url: String!
  status: Status!
  createdAt: AWSDateTime
  imageDatasetId: String
  width: Int!
  height: Int! 
  type: DownloadType
}
```
Then `amplify push` this works correctly.

Then I run `npm install -g @aws-amplify/cli` to get last version of the Amplify CLI and modify the enum:

```graphql
enum DownloadType
{
  all
  labeled
  reviewed
}
```

And now again `amplify push` and get the error:
```
Cannot read property 'length' of undefined
An error occured during the push operation: Cannot read property 'length' of undefined
```

**Comment by theslyone** [comment] 2019-10-14 15:11
Encountered this earlier today, had an amplify project, Then I ran ```npm install -g @aws-amplify/cli``` only to find that i could no longer ```amplify push```.

I was too impatient to debug, but one thing is sure, the problem lies in the templates generated with the previous amplify cli version used. I backed up my project folder, removed the api category and push works. Adding the api category back makes it work just fine also.

Note: this isn't a solution, just a quick fix

**Comment by bob-lee** [comment] 2019-10-17 19:44
Had this issue on `3.15.0`, downgraded to `3.2.0` then back to normal. I wanted to use multi auth feature but would wait until it is settled..

**Comment by SwaySway** [comment] 2019-10-18 00:22
@divait I tried doing the same with this schema and I'm not able to reproduce it. Could you email us your project?
amplify-cli@amazon.com

**Comment by rarira** [comment] 2019-10-18 14:45
> @divait I tried doing the same with this schema and I'm not able to reproduce it. Could you email us your project?
> [amplify-cli@amazon.com](mailto:amplify-cli@amazon.com)

I think it might not be reproducible.

I'd used version 1.12 and when I tried to update 3.15, I had same error.

So I tried to upgrade version one by one, and until version 3.2.0 there was no problem, but multi-auth was not working as expected.

3.2.0 to version 3.3.0 : there happened to be another error,
3.3.0 to version 3.4.0 : 'length' of undefined...

so I decided to go back to version 3.2.0 and delete all @key annotations with queryField and upgraded directly to version 3.15.0, and there was no 'amplify push' problem except some @connection error which could be resolved easily.

and at version 3.15.0
I re-added one @key annotation which I'd deleted before  and 'amplify push' , added another @key annotation and 'amplify push'... and so on..
finally there is no "'length' of undefined" error when trying to push api, but schema.graphql is totally as same as before.

**Comment by divait** [comment] 2019-10-23 15:26
> > @divait I tried doing the same with this schema and I'm not able to reproduce it. Could you email us your project?
> > [amplify-cli@amazon.com](mailto:amplify-cli@amazon.com)
> 
> I think it might not be reproducible.
> 
> I'd used version 1.12 and when I tried to update 3.15, I had same error.
> 
> So I tried to upgrade version one by one, and until version 3.2.0 there was no problem, but multi-auth was not working as expected.
> 
> 3.2.0 to version 3.3.0 : there happened to be another error,
> 3.3.0 to version 3.4.0 : 'length' of undefined...
> 
> so I decided to go back to version 3.2.0 and delete all @key annotations with queryField and upgraded directly to version 3.15.0, and there was no 'amplify push' problem except some @connection error which could be resolved easily.
> 
> and at version 3.15.0
> I re-added one @key annotation which I'd deleted before and 'amplify push' , added another @key annotation and 'amplify push'... and so on..
> finally there is no "'length' of undefined" error when trying to push api, but schema.graphql is totally as same as before.

This work around was the way to make it work!

**Closed** 2019-10-31 18:00 UTC
Labels: graphql-transformer, pending-response, pending-triage
