### ISSUE TITLE
Storage category always shows "Create" after env checkout

### ISSUE THREAD

**Issue by HarborneD** [aws-amplify/amplify-cli#8089] opened 2021-09-03 06:43 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.16.1

### Amplify CLI Version

5.4.0

### What operating system are you using?

windows 10

### Amplify Categories

storage

### Amplify Commands

env

### Describe the bug

After checking out an amplify environment, the Operation of Storage is always Create.

Steps: 
Two env exists : `dev` and `master`

- starting with `dev` checked out
-  `Amplify Status` shows Storage's Operation as Create
- `Amplify Push`
- `Amplify Status` shows Storage's Operation as No Change
- `Amplify env checkout master`
- `Amplify env checkout dev`
-  `Amplify Status` shows Storage's Operation as Create

This process can be repeated with the same result every time. No changes seem to occur in the deployed infrastructure.

### Expected behavior

Checking out a env that previously had no changes , and that has not been modified should arrive at the env still with no changes made. 

### Reproduction steps

Steps: 
Two env exists : `dev` and `master`

- starting with `dev` checked out
-  `Amplify Status` shows Storage's Operation as Create
- `Amplify Push`
- `Amplify Status` shows Storage's Operation as No Change
- `Amplify env checkout master`
- `Amplify env checkout dev`
-  `Amplify Status` shows Storage's Operation as Create

This process can be repeated with the same result every time.

**Comment by josefaidt** [comment] 2021-09-08 21:08
Hey @HarborneD :wave: thanks for raising this! I was not able to reproduce this issue on Mac and Windows with the steps provided using v5.4.0 of the CLI and Node 14. I have a few follow-up questions:

- what type of storage was added?
- was the resource pushed to the new env in-between checkouts?

**Comment by josefaidt** [comment] 2021-09-21 14:10
Closing issue. @HarborneD if you are still experiencing this issue please reply back to this thread and we can re-open to investigate further 🙂

**Closed by josefaidt** 2021-09-21 14:10 UTC
Labels: storage, pending-close-response-required, pending-response, pending-triage
