### ISSUE TITLE
Function Auth Role - "Read" Permission does not give "appsync:GraphQL" access in IAM Role.

### ISSUE THREAD

**Issue by blazinaj** [aws-amplify/amplify-cli#6093] opened 2020-12-07 19:52 UTC
When creating an Amplify CLI Function, I am assuming that choosing the 'read' option will allow us to perform queries. When using this option, `"appsync:GraphQL"` does not get added to the IAM Role Policy for this Lambda, thus initializing an AppSync Client in the Lambda fails.

Adding 'Create', 'Update', or 'Delete' then adds the necessary `"appsync:GraphQL"` action to the Lambda role. This may be by design, but took us a bit to figure out. May not be a Bug per se.

**Comment by half2me** [comment] 2020-12-07 22:32
I literally ran into this just today. I also found it strange how `read` access doesn't grant `appsync::GraphQL`

**Comment by attilah** [comment] 2020-12-07 23:55
Duplicate of #4306, #5342 fixes it

**Closed by attilah** 2020-12-07 23:55 UTC
Labels: api-graphql, bug, duplicate
