### ISSUE TITLE
Cannot create new @key LSI

### ISSUE THREAD

**Issue by acoulson2000** [aws-amplify/amplify-cli#6694] opened 2021-02-20 20:47 UTC
**Which Category is your question related to?**
amplify push

**Amplify CLI Version** 
4.41.2

**What AWS Services are you utilizing?**
Amplify with Appsync

**Provide additional details e.g. code snippets**
I want to be able to get a list of my Site records ordered by siteName. I already have data in the table that I need to retain. I am trying to add a sort index to my model entity, but when I `amplify push` i get:
``
Attempting to add a local secondary index to the SiteTable table in the Site stack. Local secondary indexes must be created when the table is created.
An error occurred during the push operation: Attempting to add a local secondary index to the SiteTable table in the Site stack. Local secondary indexes must be created when the table is created.
`` 

Before:
```
type Site
  @model
  @auth(
    rules: [
      { allow: public, provider: apiKey }
      { allow: private }
    ]
  ) {
  id: ID!
  siteName: String!
  url: String!
  website: String!
  opType: String
  opContent: String
  header1: String
  header2: String
  testString1: String!
  testString2: String
  comments: String
  compressed: Boolean
  message: String
  wordCount: Int!
  condition: String
  test: String
  regex: String
  diabled: Boolean!
  fetch: String
  Subscribers: [SiteSubscriber] @connection(name: "SiteSubscriber")
}
```
After:
```
type Site
  @model
  @key(name: "SitesByName", fields: ["id", "siteName"],  queryField: "listSitesByName")
  @auth(
    rules: [
      { allow: public, provider: apiKey }
      { allow: private }
    ]
  ) {
  id: ID!
  siteName: String!
  url: String!
  website: String!
  opType: String
  opContent: String
  header1: String
  header2: String
  testString1: String!
  testString2: String
  comments: String
  compressed: Boolean
  message: String
  wordCount: Int!
  condition: String
  test: String
  regex: String
  diabled: Boolean!
  fetch: String
  Subscribers: [SiteSubscriber] @connection(name: "SiteSubscriber")
}
```

**Comment by acoulson2000** [comment] 2021-02-20 23:24
I will add that the following does create a GSI, but of course, the resulting index does not include a sort key.

`@key(name: "SitesByName", fields: ["siteName"],  queryField: "listSitesByName")`

**Comment by edwardfoyle** [comment] 2021-02-22 19:45
@acoulson2000 I think you may be able to solve this by using a recently implemented feature to use GSIs instead of LSIs for all secondary @key directives. You can enable it by setting `"secondaryKeyAsGSI": true` in your `cli.json` file. See https://github.com/aws-amplify/amplify-cli/pull/5648 and https://docs.amplify.aws/cli/reference/feature-flags#configuration for more details.

**Comment by SwaySway** [comment] 2021-02-24 01:22
Closing as a duplicate of this issue: https://github.com/aws-amplify/amplify-cli/issues/6650

**Closed by SwaySway** 2021-02-24 01:22 UTC
Labels: @key, pending-close-response-required, question
