### ISSUE TITLE
Use sortField (& limit) with new @connection syntax

### ISSUE THREAD

**Issue by FemkeBuijs** [aws-amplify/amplify-cli#3258] opened 2020-01-24 09:54 UTC
**Which Category is your question related to?**

GraphQL @connection

**Amplify CLI Version** 

4.13.0

**What AWS Services are you utilizing?**

DynamoDB, Amplify Console, AppSync, Cognito, SES

**Question**

In the docs, using the 'old, alternative' way, you can add a sortField to a GraphQL connection, like so:

```directive @connection(name: String, keyField: String, sortField: String, limit: Int) on FIELD_DEFINITION```

However, I cannot find a way to do that with the new syntax:

```directive @connection(keyName: String, fields: [String!]) on FIELD_DEFINITION```

And what about the limit?

Thank you for any help!

**Comment by dantasfiles** [comment] 2020-01-24 17:16
`fields` is an array that combines the old `keyField` and the `sortField`.

From the docs:
> If two fields are provided the second field will be the SORT key. If more than two fields are provided, a single composite SORT key will be created from a combination of fields[1...n]. 

What helped me reason about all of this was skipping past the @key and @field docs and [walking through the example](https://aws-amplify.github.io/docs/cli-toolchain/graphql#data-access-patterns).

I think they removed the limit, because you can just specify it in your GraphQL operation
```
getWarehouse(id: "0123") {
  id
  employees(limit: 10)
}
```

**Comment by SwaySway** [comment] 2020-02-03 17:43
Closing this is as a duplicate of #1703.
Please follow that thread for updates.

**Closed by SwaySway** 2020-02-03 17:43 UTC
Labels: enhancement, graphql-transformer

**Comment by FemkeBuijs** [comment] 2020-02-04 08:58
@SwaySway thanks i will follow that issue regarding the limit. However, issue #1703 does not address the sortField.

**Comment by thomasklein-winemaker** [comment] 2020-08-07 12:41
@SwaySway - please re-open. As @FemkeBuijs states, the issue is not addressed in the linked issue.

**Comment by RossWilliams** [comment] 2020-08-07 21:24
@thomasklein-winemaker sortField is controlled by the @key directive with the new syntax. The first field is the partition key, and the other fields are concatenated to make up the sort key. By default the @connection will scan forward based on the sort field.
