### ISSUE TITLE
amplify console --> Just blank screen, with error message: "ERR_SSL_PROTOCOL_ERROR"

### ISSUE THREAD

**Issue by burakkbilginn** [aws-amplify/amplify-cli#10113] opened 2022-04-01 16:00 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v14.17.3

### Amplify CLI Version

7.6.26

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I didn't make any manual change. I am developing the same app in different laptops, maybe this can also be cause? 

### Amplify Categories

auth, api

### Amplify Commands

Not applicable

### Describe the bug

When I enter `amplify console` inside react native terminal by typing `amplify console`, just blank page appears. I don't see the overview page of the appsync. When I look at console, `ERR_SSL_PROTOCOL_ERROR` lines with no description in google chrome browser. 

### Expected behavior

Opening Appsync, but blank page

### Reproduction steps

"amazon-cognito-identity-js": "^5.2.8",
"aws-amplify": "^4.3.18",
"aws-amplify-react-native": "^6.0.4",

### GraphQL schema(s)

<details>

```graphql

type User @model @auth(rules: [ { allow: private } ])
{
  id: ID!
  username: String!
  email: String!
  rating: Float
  comments: [Comment] @hasMany  
}

type Comment @model @auth(rules: [{ allow: private } ]) 
{
  id: ID!
  createdAt: String!
  text: String!
  user: User 
}


```

</details>

### Log output

<details>

```
# Put your logs below this line
Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR
a.b.cdn.console.awss…/vendors~main.css:1 
 Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR
main.js:1 
 Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR
vendors~main.js:1 
 Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR

```

</details>

**Comment by josefaidt** [comment] 2022-04-01 19:31
Hey @burakkbilginn :wave: can you include minimal reproduction steps to reproduce this error? Where are you executing this command?

**Comment by burakkbilginn** [comment] 2022-04-01 19:50
> Hey @burakkbilginn 👋 can you include minimal reproduction steps to reproduce this error? Where are you executing this command?

Hi Josef👋 In vscode inside powershell terminal I execute this command. Minimal reproduction steps are: 
amplify init (works)
amplify push (works)
amplify console (problem-blank screen)

**Comment by josefaidt** [comment] 2022-04-01 20:23
Hey @burakkbilginn unfortunately I was not able to reproduce this issue using the provided steps. Out of curiosity, how many Amplify apps do you currently have in this region? For transparency, I'm curious if we currently have 25 apps in this region and this is impacting the functionality of `amplify console`

**Comment by burakkbilginn** [comment] 2022-04-01 20:51
> Hey @burakkbilginn unfortunately I was not able to reproduce this issue using the provided steps. Out of curiosity, how many Amplify apps do you currently have in this region? For transparency, I'm curious if we currently have 25 apps in this region and this is impacting the functionality of `amplify console`

I have just 1 app, no more. This problem occurs very frequently, and persists for example for 1 week, and then disappears automatically. I couldn't find any rigid solution for that. Is this a bug? Shall I send the link of aws console?

**Comment by josefaidt** [comment] 2022-04-04 15:23
Hey @burakkbilginn thank you for clarifying. I have a few follow-up questions:

- are you able to manually navigate to the console's web page?
- do you also experience this issue in other browsers?
- are you behind a vpn or proxy?

**Comment by burakkbilginn** [comment] 2022-04-04 17:13
> Hey @burakkbilginn thank you for clarifying. I have a few follow-up questions:
> 
> * are you able to manually navigate to the console's web page?
> * do you also experience this issue in other browsers?
> * are you behind a vpn or proxy?

Hi again Joseph. 
1-) Yes I can, but again empty page
2-) Yes other browsers also same result
3-) No.

But I think I found a solution for that. When I connected to another wifi network, and then back to the first wifi network, it surprisingly opened. Maybe that makes connection reset and solves the problem. Thanks for your kind care. Hope not to see it again.

**Comment by josefaidt** [comment] 2022-04-08 14:09
Hey @burakkbilginn glad to hear you were able to find a resolution! I'll close this issue for now, but if this creeps up again please don't hesitate to reply back to this thread or create a new issue 🙂

**Closed by josefaidt** 2022-04-08 14:09 UTC
Labels: pending-close-response-required, pending-triage
