### ISSUE TITLE
Assign dynamically named resources to a `modelIamRoleDefaultPolicy` policy document

### ISSUE THREAD

**Issue by gxxcastillo** [aws-amplify/amplify-cli#11734] opened 2023-01-09 19:10 UTC
### Is this feature request related to a new or existing Amplify category?

api

### Describe the feature you'd like to request

I have an Amplify auto generated role relative to a specific model, `MyModelAutoGeneratedRole` and by default, it's policy document has permission to various DynamoDB actions as well on `MyModelTable`.  However, I'd like for it to have access to more resources in order to support `TransactWriteItems`

My understanding is that the way to add resources to the policy document is by updating the Resource array for the given policyDocument in the override.ts file created by running `amplify override api`:

```
  return models['MyModel'].modelIamRoleDefaultPolicy.policyDocument = {
    Version: '2012-10-17',
    Statement: [
      {
        Action: [
          'dynamodb:BatchGetItem',
          'dynamodb:GetRecords',
          'dynamodb:GetShardIterator',
          'dynamodb:Query',
          'dynamodb:GetItem',
          'dynamodb:Scan',
          'dynamodb:ConditionCheckItem',
          'dynamodb:BatchWriteItem',
          'dynamodb:PutItem',
          'dynamodb:UpdateItem',
          'dynamodb:DeleteItem',
          'dynamodb:DescribeTable'
        ],
        Effect: 'Allow',
        Resource: [
          "arn:aws:dynamodb:us-west-1:11111111111:table/MyModel-1212121212-myenvironment",
          "arn:aws:dynamodb:us-west-1:11111111111:table/MyModel1-1212121212-myenvironment",
          "arn:aws:dynamodb:us-west-1:11111111111:table/MyModel2-1212121212-myenvironment",
          "arn:aws:dynamodb:us-west-1:11111111111:table/MyModel3-1212121212-myenvironment",
          "arn:aws:dynamodb:us-west-1:11111111111:table/MyModel4-1212121212-myenvironment"
        ]
      }
    ]
  };
```

However, this requires hardcoding values such as the environment name and the appID.  With the help of customer support, we thought this might work but it failed in some cases saying the table didn't exist:
```
              {
                "Fn::GetAtt": [
                  "MyModelTable",
                  "Arn"
                ]
              }
```

Another option was to create a custom resource via `amplify add custom` but we ran into similar issues in that we weren't able to dynamically reference the tables.

My request is to have a way of assigning dynamically assigning resources to a role.

### Describe the solution you'd like

I'd like to be able to dynamically reference table names when assigning them as resources to a policy document.

Additionally, it would be great to be able to do something like `models['MyModel'].modelIamRoleDefaultPolicy.policyDocument.addResource(dynamicResourceReference)`

as apposed to having to manually override the entire `policyDocument` object.

### Describe alternatives you've considered

1) 
```
                "Fn::GetAtt": [
                  "MyModelTable",
                  "Arn"
                ]
```

2) `amplify add custom`

For now I am just hardcoding the values into my override.ts file.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment] 2023-01-09 22:10
Hey @gxxcastillo :wave: thanks for raising this! It appears you are encountering an issue that is documented as a feature request to improve the use of overrides, expanding to be able to reference env-specific information such as the current environment name, app id, region, etc. 

> Another option was to create a custom resource via amplify add custom but we ran into similar issues in that we weren't able to dynamically reference the tables.

What is the issue you were encountering with custom resources? Do you have an example of the cdk code used with your custom resource?

**Comment by gxxcastillo** [comment] 2023-01-09 22:39
Hi @josefaidt , I deleted the custom resource so I don't have an example atm.  I think the issue I ran into was that I didn't know how to reference the role I wan't to update from within the cdk-stack.ts file without hardcoding it.

**Comment by josefaidt** [comment] 2023-01-10 18:18
Hey @gxxcastillo thanks for clarifying! Unfortunately without hardcoding some value or using Amplify CLI command hooks to inject some values, we are unable to reference information such as App ID and environment name. While it may be possible to iterate over the available values I agree in that this flow could be improved, and for that I will mark this as a feature request.

For what it's worth there are a few approaches noted in the feature request here that leverage dynamic requires to read information from JSON files such as `amplify-meta.json` https://github.com/aws-amplify/amplify-cli/issues/9063

**Comment by josefaidt** [comment] 2023-01-10 21:36
After taking a further look at this one, I'm going to close this as a duplicate of #9063 in favor of tracking the existing item. Please subscribe to #9063 for further updates

**Closed by josefaidt** 2023-01-10 21:36 UTC
Labels: feature-request, extensibility, duplicate, p3
