### ISSUE TITLE
What is the intended behavior for authorized fields?

### ISSUE THREAD

**Issue by tobiastimm** [aws-amplify/amplify-cli#7089] opened 2021-04-14 08:22 UTC
**Which Category is your question related to?**
I'm trying to build a GraphQL API with amplify and wanted to restrict the access to certain fields for users with a specific Cognito user group.

I've mocked the API with `amplify mock api` and tried to list the courses with the auto-generated queries. Every time I try to access the `status` field, I get the error that I'm not authorized for that (this is correct), BUT the returned items are `null`. Is this the intended behavior?

I would have assumed that I just receive the items and the restricted field is excluded if my authorization is not valid.

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

`4.46.1`

**What AWS Services are you utilizing?**

- AppSync
- Cognito

**Provide additional details e.g. code snippets**
Here is my schema
```gql
type Course
  @model
  @auth(
    rules: [
      { allow: owner }
      { allow: owner, ownerField: "organizers", operations: [update, read] }
    ]
  ) {
  id: ID!
  title: String!
  description: String!
  duration: Int!
  image: String
  status: CourseStatus! @aws_auth(cognito_groups: ["organizer", "admin"]) #This is the important part!
}
  
enum CourseStatus {
  Accepted
  Draft
  Rejected
  Review
}
  
```

**Comment by houmark** [comment] 2021-04-14 22:02
Unfortunately, as I understand it, failing is intended behavior.

A much nicer solution would be to just get null back from the field, but I think the reason is that even a null value would reveal information because the field name is a part of response. In our case that would be okay, so it should at least be configurable, so we can decide instead of Amplify forcing it.

The only solution is to only include the fields you know the user has access to, which complicates preparation of any query heavily.

Someone created a package that may be able to handle some of it, not sure, I never really digged into it in full, but maybe take a look (I doubt Amplify will solve this in the core anytime soon):
https://www.npmjs.com/package/graphql-auto-transformer

**Comment by tobiastimm** [comment] 2021-04-15 08:10
@houmark thanks for your answer. The need to write all queries again to exclude the authorization fields fails for me the reason to use the auto-generated queries at all. If the fields, I don't have access to, are just undefined or not returned at all, would be the intended and better behavior for me.

**Comment by houmark** [comment] 2021-04-15 08:18
I agree 100% — Amplify should handle this automatically. It's a showstopper and we have avoided using auth on fields for the same reason, but we have multiple places where it would be really useful.

**Comment by tobiastimm** [comment] 2021-04-15 08:35
Okay if I declare `CourseStatus` as nullable it works as intended

**Comment by houmark** [comment] 2021-04-15 08:42
It's been a long time since we hit this, and it may have changed since. It may also be it was on a connection or something like that. Unfortunately making some of the fields we would want to be auth'ed cannot be non-mandatory.

**Comment by jhockett** [comment] 2021-04-19 19:40
Hi @tobiastimm, apologies for the delayed reply. We don't support `@aws-auth`. The recommended path is to use a field level `@auth` directive, but it would require you to change the field to be nullable.

**Comment by jhockett** [comment] 2021-08-06 18:40
Closing this issue since there were no further questions.

**Closed by jhockett** 2021-08-06 18:40 UTC
Labels: question, graphql-transformer
