### ISSUE TITLE
[Urgent] Cannot push at all: `An error occurred during the push operation: write EPIPE`

### ISSUE THREAD

**Issue by ataibarkai** [aws-amplify/amplify-cli#7632] opened 2021-06-29 11:35 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.1

### Amplify CLI Version

5.0.2

### What operating system are you using?

macOS Big Sur

### Amplify Categories

Not applicable

### Amplify Commands

push

### Describe the bug

When running `amplify push`, I consistently get an error during the 'uploading files' step.
This is completely blocking my development so I would appreciate any and all help resolving this issue.

The errors doesn't seem to be emitted at a consistent point in the 'uploading files'  step. It can be emitted after ~30% of uploading is done, ~50%, 80%, etc.

On almost all occasions, the error emitted is as follows:
```
✖ An error occurred when pushing the resources to the cloud

write EPIPE
An error occurred during the push operation: write EPIPE
```

On 2 occasions, there was a different error emitted:
```
✖ An error occurred when pushing the resources to the cloud

Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.
An error occurred during the push operation: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.
```

### Expected behavior

pushing should resolve successfully.

### Reproduction steps

1. run `amplify push --yes`
2. observe errors

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line

[***].zip","Bucket":"[***]ify-[***]e02-[***]expd-[***]222-[***]ment"}])
2021-06-29T09:54:53.260Z|info : amplify-provider-awscloudformation.push-resources.packageResources.s3.uploadFile([{"Key":"[***]ify-[***]lds/[***]copyOriginalAsset-[***]502b4939-[***].zip"}])
2021-06-29T09:54:53.260Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.upload([{"Key":"[***]ify-[***]lds/[***]copyOriginalAsset-[***]502b4939-[***].zip","Bucket":"[***]ify-[***]e02-[***]expd-[***]222-[***]ment"}])
2021-06-29T09:54:53.997Z|info : amplify-provider-awscloudformation.push-resources.packageResources.s3.uploadFile([{"Key":"[***]ify-[***]lds/[***]derXxxPost-[***]70637435-[***].zip"}])
2021-06-29T09:54:53.998Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.upload([{"Key":"[***]ify-[***]lds/[***]derXxxPost-[***]70637435-[***].zip","Bucket":"[***]ify-[***]e02-[***]expd-[***]222-[***]ment"}])
2021-06-29T09:55:51.199Z|error : amplify-provider-awscloudformation.aws-s3.uploadFile.s3([{"Key":"[***]ify-[***]lds/[***]rXxxPostLike-[***]6465376c-[***].zip","Bucket":"[***]ify-[***]e02-[***]expd-[***]222-[***]ment"}])
TimeoutError: write EPIPE
2021-06-29T09:55:51.202Z|error : amplify-provider-awscloudformation.push-resources.packageResources.s3.uploadFile([{"Key":"[***]ify-[***]lds/[***]rXxxPostLike-[***]6465376c-[***].zip"}])
TimeoutError: write EPIPE
2021-06-29T09:55:51.207Z|error : amplify-provider-awscloudformation.push-resources.run([{"resourcesToBeCreated":[{"service":"[***]ito","providerPlugin":"[***]rmation","dependsOn":[{"category":"function","resourceName":"[***]onfirmation","triggerProvider":"[***]ito","attributes":["Arn","Name"]}],"customAuth":false,"resourceName":"[***]auth","category":"auth"},{"service":"AppSync","providerPlugin":"[***]rmation","output":{"authConfig":{"defaultAuthentication":{"authenticationType":"AMAZON_COGNITO_USER_POOLS","userPoolConfig":{"userPoolId":"[***]itauth"}},"additionalAuthenticationProviders":[{"authenticationType":"API_KEY","apiKeyConfig":{"apiKeyExpirationDays":365,"description":""}},{"authenticationType":"AWS_IAM"}]}},"resourceName":"[***]e02","category":"api"},{"service":"API Gateway","providerPlugin":"[***]rmation","dependsOn":[{"category":"function","resourceName":"[***]Identify","attributes":["Name","Arn"]}],"resourceName":"[***]Api","category":"api"},{"build":true,"providerPlugin":"[***]rmation","service":"Lambda","lastBuildTimeStamp":"2021-06-29T09:54:14.167Z","lastPackageTimeStamp":"2021-06-29T09:42:05.744Z","distZipFilename":"[***]Confirmation-[***]53583576-[***].zip","s3Bucket":{"deploymentBucketName":"[***]ify-[***]e02-[***]expd-[***]222-[***]ment","s3Key":"[***]ify-[***]lds/[***]Confirmation-[***]53583576-[***].zip"},"resourceName":"[***]Confirmation","category":"function"},{"build":true,"providerPlugin":"[***]rmation","service":"Lambda","dependsOn":[{"category":"api","resourceName":"[***]e02","attributes":["GraphQLAPIIdOutput"]}],"lastBuildTimeStamp":"2021-06-29T09:54:14.169Z","lastPackageTimeStamp":"2021-06-29T09:42:04.883Z","distZipFilename":"[***]rObject-[***]51696668-[***].zip","s3Bucket":{"deploymentBucketName":"[***]ify-[***]e02-[***]expd-[***]222-[***]ment","s3Key":"[***]ify-[***]lds/[***]rObject-[***]51696668-[***].zip"},"resourceName":"[***]rObject","category":"function"},{"build":true,"providerPlugin":"[***]rmation","service":"Lambda","dependsOn":[{"category":"api","resourceName":"[***]e02","attributes":["GraphQLAPIIdOutput","GraphQLAPIEndpointOutput","GraphQLAPIKeyOutput"]}],"lastBuildTimeStamp":"2021-06-29T09:54:22.499Z","lastPackageTimeStamp":"2021-06-29T09:42:47.128Z","distZipFilename":"[***]Identify-[***]52507073-[***].zip","resourceName":"[***]Identify","category":"function"},{"build":true,"providerPlugin":"[***]rmation","service":"Lambda","dependsOn":[{"category":"tawkitstepfunctioncategory","resourceName":"[***]StepFunction","attributes":["Name","Arn"]}],"lastBuildTimeStamp":"2021-06-29T09:54:22.262Z","lastPackageTimeStamp":"2021-06-29T09:42:43.158Z","distZipFilename":"[***]solver-[***]2f2f4c55-[***].zip","resourceName":"[***]solver","category":"function"},{"build":true,"providerPlugin":"[***]rmation","service":"Lambda","dependsOn":[{"category":"api","resourceName":"[***]e02","attributes":["GraphQLAPIIdOutput","GraphQLAPIEndpointOutput","GraphQLAPIKeyOutput"]},{"category":"storage","resourceName":"[***]adedAssets","attributes":["BucketName"]}],"lastBuildTimeStamp":"2021-06-29T09:54:22.083Z","lastPackageTimeStamp":"2021-06-29T09:42:47.975Z","distZipFilename":"[***]copyOriginalAsset-[***]502b4939-[***].zip","resourceName":"[***]copyOriginalAsset","category":"function"},{"build":true,"providerPlugin":"[***]rmation","service":"Lambda","dependsOn":[{"category":"storage","resourceName":"[***]adedAssets","attributes":["BucketName"]}],"lastBuildTimeStamp":"2021-06-29T09:54:22.023Z","lastPackageTimeStamp":"2021-06-29T09:42:39.132Z","distZipFilename":"[***]lbyAudioProcessing-[***]622f2b49-[***].zip","resourceName":"[***]lbyAudioProcessing","category":"function"},{"build":true,"providerPlugin":"[***]rmation","service":"Lambda","dependsOn":[{"category":"storage","resourceName":"[***]adedAssets","attributes":["BucketName"]}],"lastBuildTimeStamp":"2021-06-29T09:54:22.169Z","lastPackageTimeStamp":"2021-06-29T09:42:40.558Z","distZipFilename":"[***]nerateTranscription-[***]33647541-[***].zip","resourceName":"[***]nerateTranscription","category":"function"},{"build":true,"providerPlugin":"[***]rmation","service":"Lambda","dependsOn":[{"category":"api","resourceName":"[***]e02","attributes":["GraphQLAPIIdOutput","GraphQLAPIEndpointOutput","GraphQLAPIKeyOutput"]},{"category":"storage","resourceName":"[***]adedAssets","attributes":["BucketName"]}],"lastBuildTimeStamp":"2021-06-29T09:54:22.694Z","lastPackageTimeStamp":"2021-06-29T09:42:45.739Z","distZipFilename":"[***]XXGenerateVideos-[***]5671534b-[***].zip","resourceName":"[***]XXGenerateVideos","category":"function"},{"build":true,"providerPlugin":"[***]rmation","service":"Lambda","dependsOn":[{"category":"api","resourceName":"[***]e02","attributes":["GraphQLAPIIdOutput","GraphQLAPIEndpointOutput","GraphQLAPIKeyOutput"]},{"category":"storage","resourceName":"[***]adedAssets","attributes":["BucketName"]}],"lastBuildTimeStamp":"2021-06-29T09:54:22.424Z","lastPackageTimeStamp":"2021-06-29T09:42:44.187Z","distZipFilename":"[***]ploadToCdnAndDBize-[***]5a426364-[***].zip","resourceName":"[***]ploadToCdnAndDBize","category":"function"},{"build":true,"providerPlugin":"[***]rmation","service":"Lambda","dependsOn":[],"lastBuildTimeStamp":"2021-06-29T09:54:14.170Z","lastPackageTimeStamp":"2021-06-29T09:42:05.851Z","distZipFilename":"[***]onfirmation-[***]62717061-[***].zip","s3Bucket":{"deploymentBucketName":"[***]ify-[***]e02-[***]expd-[***]222-[***]ment","s3Key":"[***]ify-[***]lds/[***]onfirmation-[***]62717061-[***].zip"},"resourceName":"[***]onfirmation","category":"function"},{"build":true,"providerPlugin":"[***]rmation","service":"Lambda","dependsOn":[{"category":"api","resourceName":"[***]e02","attributes":["GraphQLAPIIdOutput","GraphQLAPIEndpointOutput","GraphQLAPIKeyOutput"]},{"category":"storage","resourceName":"[***]adedAssets","attributes":["BucketName"]}],"lastBuildTimeStamp":"2021-06-29T09:54:22.533Z","lastPackageTimeStamp":"2021-06-29T09:42:42.400Z","distZipFilename":"[***]tializePublishedTawk-[***]45796568-[***].zip","resourceName":"[***]tializePublishedTawk","category":"function"},{"build":true,"providerPlugin":"[***]rmation","service":"Lambda","dependsOn":[{"category":"api","resourceName":"[***]e02","attributes":["GraphQLAPIIdOutput"]}],"lastBuildTimeStamp":"2021-06-29T09:54:22.544Z","lastPackageTimeStamp":"2021-06-29T09:42:39.817Z","distZipFilename":"[***]rXxxPostLike-[***]6465376c-[***].zip","resourceName":"[***]rXxxPostLike","category":"function"},{"build":true,"providerPlugin":"[***]rmation","service":"Lambda","dependsOn":[{"category":"api","resourceName":"[***]e02","attributes":["GraphQLAPIIdOutput"]}],"lastBuildTimeStamp":"2021-06-29T09:54:37.391Z","lastPackageTimeStamp":"2021-06-29T09:42:48.813Z","distZipFilename":"[***]derXxxPost-[***]70637435-[***].zip","resourceName":"[***]derXxxPost","category":"function"},{"service":"S3","providerPlugin":"[***]rmation","dependsOn":[{"category":"function","resourceName":"[***]solver","attributes":["Name","Arn","LambdaExecutionRole"]}],"resourceName":"[***]adedAssets","category":"storage"},{"service":"Step Function","providerPlugin":"[***]rmation","dependsOn":[],"resourceName":"[***]StepFunction","category":"tawkitstepfunctioncategory"}],"resourcesToBeUpdated":[],"resourcesToBeSynced":[],"resourcesToBeDeleted":[],"tagsUpdated":false,"allResources":[{"service":"Cognito","providerPlugin":"[***]rmation","dependsOn":[{"category":"function","resourceName":"[***]onfirmation","triggerProvider":"Cognito","attributes":["Arn","Name"]}],"customAuth":false,"resourceName":"[***]auth","category":"auth"},{"service":"AppSync","providerPlugin":"[***]rmation","output":{"authConfig":{"defaultAuthentication":{"authenticationType":"AMAZON_COGNITO_USER_POOLS","userPoolConfig":{"userPoolId":"[***]itauth"}},"additionalAuthenticationProviders":[{"authenticationType":"API_KEY","apiKeyConfig":{"apiKeyExpirationDays":365,"description":""}},{"authenticationType":"AWS_IAM"}]}},"resourceName":"[***]e02","category":"api"},{"service":"API Gateway","providerPlugin":"[***]rmation","dependsOn":[{"category":"function","resourceName":"[***]Identify","attributes":["Name","Arn"]}],"resourceName":"[***]Api","category":"api"},{"build":true,"providerPlugin":"[***]rmation","service":"Lambda","lastBuildTimeStamp":"2021-06-29T09:54:14.167Z","lastPackageTimeStamp":"2021-06-29T09:42:05.744Z","distZipFilename":"[***]Confirmation-[***]53583576-[***].zip","s3Bucket":{"deploymentBucketName":"[***]ify-[***]e02-[***]expd-[***]222-[***]ment","s3Key":"[***]ify-[***]lds/[***]Confirmation-[***]53583576-[***].zip"},"resourceName":"[***]Confirmation","category":"function"},{"build":true,"providerPlugin":"[***]rmation","service":"Lambda","dependsOn":[{"category":"api","resourceName":"[***]e02","attributes":["GraphQLAPIIdOutput"]}],"lastBuildTimeStamp":"2021-06-29T09:54:14.169Z","lastPackageTimeStamp":"2021-06-29T09:42:04.883Z","distZipFilename":"[***]rObject-[***]51696668-[***].zip","s3Bucket":{"deploymentBucketName":"[***]ify-[***]e02-[***]expd-[***]222-[***]ment","s3Key":"[***]ify-[***]lds/[***]rObject-[***]51696668-[***].zip"},"resourceName":"[***]rObject","category":"function"},{"build":true,"providerPlugin":"[***]rmation","service":"Lambda","dependsOn":[{"category":"api","resourceName":"[***]e02","attributes":["GraphQLAPIIdOutput","GraphQLAPIEndpointOutput","GraphQLAPIKeyOutput"]}],"lastBuildTimeStamp":"2021-06-29T09:54:22.499Z","lastPackageTimeStamp":"2021-06-29T09:42:47.128Z","distZipFilename":"[***]Identify-[***]52507073-[***].zip","resourceName":"[***]Identify","category":"function"},{"build":true,"providerPlugin":"[***]rmation","service":"Lambda","dependsOn":[{"category":"tawkitstepfunctioncategory","resourceName":"[***]StepFunction","attributes":["Name","Arn"]}],"lastBuildTimeStamp":"2021-06-29T09:54:22.262Z","lastPackageTimeStamp":"2021-06-29T09:42:43.158Z","distZipFilename":"[***]solver-[***]2f2f4c55-[***].zip","resourceName":"[***]solver","category":"function"},{"build":true,"providerPlugin":"[***]rmation","service":"Lambda","dependsOn":[{"category":"api","resourceName":"[***]e02","attributes":["GraphQLAPIIdOutput","GraphQLAPIEndpointOutput","GraphQLAPIKeyOutput"]},{"category":"storage","resourceName":"[***]adedAssets","attributes":["BucketName"]}],"lastBuildTimeStamp":"2021-06-29T09:54:22.083Z","lastPackageTimeStamp":"2021-06-29T09:42:47.975Z","distZipFilename":"[***]copyOriginalAsset-[***]502b4939-[***].zip","resourceName":"[***]copyOriginalAsset","category":"function"},{"build":true,"providerPlugin":"[***]rmation","service":"Lambda","dependsOn":[{"category":"storage","resourceName":"[***]adedAssets","attributes":["BucketName"]}],"lastBuildTimeStamp":"2021-06-29T09:54:22.023Z","lastPackageTimeStamp":"2021-06-29T09:42:39.132Z","distZipFilename":"[***]lbyAudioProcessing-[***]622f2b49-[***].zip","resourceName":"[***]lbyAudioProcessing","category":"function"},{"build":true,"providerPlugin":"[***]rmation","service":"Lambda","dependsOn":[{"category":"storage","resourceName":"[***]adedAssets","attributes":["BucketName"]}],"lastBuildTimeStamp":"2021-06-29T09:54:22.169Z","lastPackageTimeStamp":"2021-06-29T09:42:40.558Z","distZipFilename":"[***]nerateTranscription-[***]33647541-[***].zip","resourceName":"[***]nerateTranscription","category":"function"},{"build":true,"providerPlugin":"[***]rmation","service":"Lambda","dependsOn":[{"category":"api","resourceName":"[***]e02","attributes":["GraphQLAPIIdOutput","GraphQLAPIEndpointOutput","GraphQLAPIKeyOutput"]},{"category":"storage","resourceName":"[***]adedAssets","attributes":["BucketName"]}],"lastBuildTimeStamp":"2021-06-29T09:54:22.694Z","lastPackageTimeStamp":"2021-06-29T09:42:45.739Z","distZipFilename":"[***]XXGenerateVideos-[***]5671534b-[***].zip","resourceName":"[***]XXGenerateVideos","category":"function"},{"build":true,"providerPlugin":"[***]rmation","service":"Lambda","dependsOn":[{"category":"api","resourceName":"[***]e02","attributes":["GraphQLAPIIdOutput","GraphQLAPIEndpointOutput","GraphQLAPIKeyOutput"]},{"category":"storage","resourceName":"[***]adedAssets","attributes":["BucketName"]}],"lastBuildTimeStamp":"2021-06-29T09:54:22.424Z","lastPackageTimeStamp":"2021-06-29T09:42:44.187Z","distZipFilename":"[***]ploadToCdnAndDBize-[***]5a426364-[***].zip","resourceName":"[***]ploadToCdnAndDBize","category":"function"},{"build":true,"providerPlugin":"[***]rmation","service":"Lambda","dependsOn":[],"lastBuildTimeStamp":"2021-06-29T09:54:14.170Z","lastPackageTimeStamp":"2021-06-29T09:42:05.851Z","distZipFilename":"[***]onfirmation-[***]62717061-[***].zip","s3Bucket":{"deploymentBucketName":"[***]ify-[***]e02-[***]expd-[***]222-[***]ment","s3Key":"[***]ify-[***]lds/[***]onfirmation-[***]62717061-[***].zip"},"resourceName":"[***]onfirmation","category":"function"},{"build":true,"providerPlugin":"[***]rmation","service":"Lambda","dependsOn":[{"category":"api","resourceName":"[***]e02","attributes":["GraphQLAPIIdOutput","GraphQLAPIEndpointOutput","GraphQLAPIKeyOutput"]},{"category":"storage","resourceName":"[***]adedAssets","attributes":["BucketName"]}],"lastBuildTimeStamp":"2021-06-29T09:54:22.533Z","lastPackageTimeStamp":"2021-06-29T09:42:42.400Z","distZipFilename":"[***]tializePublishedTawk-[***]45796568-[***].zip","resourceName":"[***]tializePublishedTawk","category":"function"},{"build":true,"providerPlugin":"[***]rmation","service":"Lambda","dependsOn":[{"category":"api","resourceName":"[***]e02","attributes":["GraphQLAPIIdOutput"]}],"lastBuildTimeStamp":"2021-06-29T09:54:22.544Z","lastPackageTimeStamp":"2021-06-29T09:42:39.817Z","distZipFilename":"[***]rXxxPostLike-[***]6465376c-[***].zip","resourceName":"[***]rXxxPostLike","category":"function"},{"build":true,"providerPlugin":"[***]rmation","service":"Lambda","dependsOn":[{"category":"api","resourceName":"[***]e02","attributes":["GraphQLAPIIdOutput"]}],"lastBuildTimeStamp":"2021-06-29T09:54:37.391Z","lastPackageTimeStamp":"2021-06-29T09:42:48.813Z","distZipFilename":"[***]derXxxPost-[***]70637435-[***].zip","resourceName":"[***]derXxxPost","category":"function"},{"service":"S3","providerPlugin":"[***]rmation","dependsOn":[{"category":"function","resourceName":"[***]solver","attributes":["Name","Arn","LambdaExecutionRole"]}],"resourceName":"[***]adedAssets","category":"storage"},{"service":"Step Function","providerPlugin":"[***]rmation","dependsOn":[],"resourceName":"[***]StepFunction","category":"tawkitstepfunctioncategory"}]}])
TimeoutError: write EPIPE
2021-06-29T09:55:51.216Z|error : amplify-provider-awscloudformation.aws-s3.uploadFile.s3([{"Key":"[***]ify-[***]lds/[***]solver-[***]2f2f4c55-[***].zip","Bucket":"[***]ify-[***]e02-[***]expd-[***]222-[***]ment"}])
TimeoutError: write EPIPE
2021-06-29T09:55:51.216Z|error : amplify-provider-awscloudformation.push-resources.packageResources.s3.uploadFile([{"Key":"[***]ify-[***]lds/[***]solver-[***]2f2f4c55-[***].zip"}])
TimeoutError: write EPIPE
2021-06-29T10:02:32.237Z|info : amplify version core  


```

</details>

### Additional information

I've tried restarting my computer, upgrading node + the amplify CLI, creating fresh amplify environments, and a half dozen other things, to no avail.

Possibly of note:
1. I am attempting a push onto a new environment after accidentally getting my previous development environment into a bad state (that breakage seems unrelated to the current problem: I had pushed a symlink into my previous environment, which then triggered local errors due to the symlink breaking under `#current-cloud-backend`)
2. Since the errors reference timeouts, it may be of note that I am currently outside of the USA, oversees. speedtest.net measures my speed @ 87Mbps down, 1.5Mbps up.

**Comment by edwardfoyle** [comment] 2021-06-29 20:11
Hi @ataibarkai, when the push was succeeding before, were you in the US / geographically closer to the AWS region you were pushing to? It could be that low upload speeds coupled with being further from the deployment region is causing timeouts

**Comment by ataibarkai** [comment] 2021-06-30 00:29
@edwardfoyle thanks for the reply.

I can't remember if I tried and succeeded to push from outside the US this time around.

But even if this is indeed the root cause, surely there is something that can be done? My upload speeds aren't blazing fast -- but they are not exceptionally slow either.
Perhaps increasing the upload timeout window?

This issue is throwing *significant* wrenches at me as it is (effectively paralyzing backend development), but with production loads this sort of issue could simply be a startup-killer.

**Comment by ataibarkai** [comment] 2021-06-30 01:54
@edwardfoyle I think we can rule out the 'outside the US/ slow connection' theory.

I've tried pushing again, this time using a US-based VPN. Speedtest.net measures 20.6Mbps down, and 3.8Mbps up to the East Coast. I'm getting the same EPIPE failure.

What else could be causing this? Is there a way to explicitly debug the issue and trace its origin?

Another potentially relevant datapoint is that the amplify project has ~180MB worth of data, mostly due to ~15MB lambda functions x 12 lambda functions.

**Comment by ataibarkai** [comment] 2021-06-30 02:02
Thinking out loud:
The amplify logs show the following error:
```
RequestTimeout: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.
```

A google search brings up [this S3 help page](https://aws.amazon.com/premiumsupport/knowledge-center/s3-socket-connection-timeout-error/), which suggests "The number of bytes set in the "Content-Length" header is less than the actual file size" as a possible cause.

Is it possible the amplify cli indeed sets the wrong content length on upload?

My project is on the larger side (~180MB, mostly due to ~15MB python lambda functions x 12 lambda functions), so it's possible it's running into this sort of edge case while other projects can get away with the default timeout without the presumably increased timeout based on "Content-Length" header.

**Comment by edwardfoyle** [comment] 2021-06-30 20:14
Hi @ataibarkai I was able to reproduce the error by simulating a slow network (Down:280kbit/s Up:256kbit/s RTT:400ms). I agree a slow ping or slow upload speed should not cause the push to fail (but it might take a while). We will investigate what we can do in this case

**Comment by edwardfoyle** [comment] 2021-06-30 22:49
After further investigation, I still have not been able to get the upload to succeed. I have tried:
1. increasing the idle timeout
2. Increasing the number of retries
3. decreasing the multipart queue size to 1 (effectively serializing the upload rather than uploading chunks in parallel)

All of these tweaks still resulted in the timeout error. There may still be some magical client configuration that will lead to a successful upload but it will likely be specific to a given network bandwidth, congestion, packet loss, throughput, etc. Since we have no way of knowing these parameters in advance, we likely won't be able to come up with a general solution.

If you have the ability to ssh to a host with better network performance, that may be a potential workaround.

**Comment by SwaySway** [comment] 2021-07-26 21:36
Marking as documentation to note minimum requirement of internet speed.

**Comment by renebrandel** [comment] 2021-08-13 03:36
Given Ed's comment, we won't be able to provide a fix for this issue.

**Closed by renebrandel** 2021-08-13 03:36 UTC
Labels: documentation, platform

**Comment by GeorgeBellTMH** [comment] 2021-09-17 20:01
What is the minimum speed? I am getting this error with 10Mbps up/2.5Mpbs down....

**Comment by GeorgeBellTMH** [comment] 2021-09-17 20:03
georgebell@Georges-MacBook-Pro web % amplify --version
5.3.1
georgebell@Georges-MacBook-Pro web % npm --version
7.23.0
georgebell@Georges-MacBook-Pro web % node --version
v14.17.6

**Comment by GeorgeBellTMH** [comment] 2021-09-17 20:04
Content changes in Lambda layers detected.
Suggested configuration for new layer versions:

themeetinghousetmhShared
  - Description: Updated layer version  2021-09-17T19:38:14.424Z

Content changes in Lambda layer themeetinghousetmhShared detected.
✖ An error occurred when pushing the resources to the cloud

write EPIPE
An error occurred during the push operation: write EPIPE
