### ISSUE TITLE
Connection always returns null when adding @auth

### ISSUE THREAD

**Issue by rafaelsorto** [aws-amplify/amplify-cli#4760] opened 2020-06-10 19:49 UTC
**Describe the bug**
Hi. I am having an issue where if I try to add @auth to a connection as documented in the amplify docs in the section "Protect access to a @connection resolver based on some attribute in the source object". The connection always returns null. If I remove the auth it works without any problems. In this example the @auth is added to the StoreLocations carts connection.

**To Reproduce**
I created a completely new React App project, then added amplify. Added auth with cognito groups, API_KEY and IAM access, and also added the GraphQL API. Then created the following Schema.
```graphql
type Store
  @model
  @auth(
    rules: [
      { allow: groups, groups: ["admins"] }
      { allow: owner, ownerField: "merchant" }
      { allow: owner, ownerField: "staff" }
    ]
  ) {
  id: ID!
  name: String!
  locations: [StoreLocation] @connection(keyName: "byStore", fields: ["id"])
  merchant: String
  staff: [String]
}

type StoreLocation
  @model
  @key(name: "byStore", fields: ["storeID"])
  @auth(
    rules: [
      { allow: groups, groups: ["admins"] }
      { allow: owner, ownerField: "merchant" }
      { allow: owner, ownerField: "staff" }
    ]
  ) {
  id: ID!
  name: String!
  storeID: ID!
  store: Store @connection(fields: ["storeID"])
  carts: [Cart]
    @connection(keyName: "byStoreLocation", fields: ["id"])
    @auth(
      rules: [
        { allow: groups, groups: ["admins"] }
        { allow: owner, ownerField: "merchant" }
        { allow: owner, ownerField: "staff" }
      ]
    )
  merchant: String
  staff: [String]
}

type Cart
  @model
  @key(name: "byStoreLocation", fields: ["storeLocationID"])
  @auth(
    rules: [
      { allow: groups, groups: ["admins"] }
      { allow: private, provider: iam, operations: [create, update, read] }
    ]
  ) {
  id: ID!
  storeLocationID: ID!
  storeLocation: StoreLocation @connection(fields: ["storeLocationID"])
  items: [CartItem]
  currency: String!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}

type CartItem {
  id: ID!
  title: String!
  quantity: Int!
  weight: Int!
  tags: String!
  total: Int!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}
```

```graphql
mutation store {
  createStore (input: {
    name: "First Store"
  }) {
    id
    merchant
    staff
  }
}

mutation storeLocation {
  createStoreLocation (input: {
    name: "USA"
    storeID: "34cec90d-0e8a-4438-84e5-07ee3a7a4337"
  }) {
    id
    merchant
    staff
  }
}

mutation cart {
  createCart (input: {
    storeLocationID: "a335d798-ae41-4249-81d3-b795711653ff"
    items: [
      {
        id: "12345"
				title: "Water"
        quantity: 1
        weight: 200
        tags: ""
        total: 200
        createdAt: "2020-06-10T16:26:15.449Z"
    updatedAt: "2020-06-10T16:26:15.449Z"
      }
    ]
    currency: "$"
    createdAt: "2020-06-10T16:26:15.449Z"
    updatedAt: "2020-06-10T16:26:15.449Z"
  }) {
    id
  }
}

query cartsByStoreLocation {
  listStoreLocations {
    items {
      id
      carts {
        items {
          id
        }
      }
    }
  }
}

```

So the idea is that A Store has many StoreLocations. And a StoreLocation has many Carts. The thing is that the Cart records are going to be created via a lambda. That is why the Cart is only limited to admins group and IAM access. But I want to provide the Merchants and Staff with access to the Stores Info and also to see the Carts, but the Carts are going to be accessed via a Store Location. Thus I am using the connection with auth but it always returns null. If I remove 
the auth it works without problems.

This is the output of the cartsByStoreLocation query shown above:

```js
{
  "data": {
    "listStoreLocations": {
      "items": [
        {
          "id": "a335d798-ae41-4249-81d3-b795711653ff",
          "carts": null
        }
      ]
    }
  }
}
```

**Expected behavior**
If I remove the @auth on the connection it shows the carts without issues

**What is Configured?**
```js
$ cat src/aws-exports.js 
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ff623ba3-53ea-4984-b45f-a0f2ad11a17e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_9voxI0t0z",
    "aws_user_pools_web_client_id": "XXX",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://XXX.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "XXX"
};


export default awsmobile;
```

<details>
  <summary><strong>Environment</strong></summary>

Full set of options selected https://gist.github.com/rafaelsorto/6fb038e9933a23456ee0e78dfa403bd6

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```
```
npx: installed 1 in 1.382s

  System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 AMD Ryzen 5 2400G with Radeon Vega Graphics
    Memory: 2.75 GB / 11.40 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.3/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: 77.0.1
  npmPackages:
    @testing-library/jest-dom: ^4.2.4 => 4.2.4 
    @testing-library/react: ^9.3.2 => 9.5.0 
    @testing-library/user-event: ^7.1.2 => 7.2.1 
    react: ^16.13.1 => 16.13.1 
    react-dom: ^16.13.1 => 16.13.1 
    react-scripts: 3.4.1 => 3.4.1 
  npmGlobalPackages:
    @aws-amplify/cli: 4.21.1
    @storybook/cli: 5.3.19
    lerna: 3.20.2
    npm: 6.14.4
    serverless: 1.72.0
    yarn: 1.22.4

```
</details>

**Smartphone (please complete the following information):**

rafael@rafael-vm:~/Documents/Learning/blog-amplify$ uname -a
Linux rafael-vm 5.3.0-53-generic aws-amplify/amplify-js#47~18.04.1-Ubuntu SMP Thu May 7 13:10:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
rafael@rafael-vm:~/Documents/Learning/blog-amplify$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"

I created a repo with my example but I notice that most of the things are in gitignore so maybe it wont provide any help https://github.com/rafaelsorto/amplify-connection-issues

Thanks in advance for your help!

**Comment by sammartinez** [comment] 2020-07-07 14:37
Reassigning to Amplify CLI cc @brene for visibility

**Comment by rafaelsorto** [comment] 2020-07-07 15:37
Thank you @sammartinez

**Comment by ignaciolarranaga** [comment] 2020-11-28 10:00
I think is related to this https://github.com/aws-amplify/amplify-cli/issues/5637

**Comment by jmcruzmanalo** [comment] 2020-12-22 09:31
We were able to figure out it was returning null for us because the resolver `<YourModel>.<PropertyWithConnection>.res.vtl` was calling `$context.source.<PropertyWithConnection>` instead of `$context.result`

How we tested:
- Remove the `@auth` rule on the property with the `@connection` directive
- Run `amplify mock` to see the auto generated resolvers
- Open `amplify/backend/api/<project-name>/resolvers` and look for a the generated file `<YourModel>.<PropertyWithConnection>.res.vtl`.
- In the below screen shot notice `$context.result` (This works! but we need authentication)
![image](https://user-images.githubusercontent.com/41225365/102872132-49d00300-447a-11eb-8253-630c46556bc7.png)
- If we then re-add `@auth` to the property and restart `amplify mock` (This doesn't throw any authentication errors but returns null)
![image](https://user-images.githubusercontent.com/41225365/102872353-8996ea80-447a-11eb-9cce-f4d9495a06bd.png)
- Changing the highlighted line fixed the issue and authentication also worked. Note that making changes to this file you'll notice that `amplify mock` will no longer delete and modify it, and is considered an overwrite to the resolver - [docs](https://docs.amplify.aws/cli/graphql-transformer/resolvers#overwriting-resolvers)

Hope this helps someone, it took us days to figure out. If anybody has a better solution we would love to hear it!

**Comment by SwaySway** [comment] 2020-12-23 00:04
@rafaelsorto I was able to reproduce this. The scenario here is adding field auth on a connection. It's adding the default value which is `$ctx.source`. Marking this is a bug. 

Potential Workarounds
- Override the resolver `StoreLocation.carts.res.vtl` and change the value to `$ctx.result` as mentioned by @jmcruzmanalo 
-  Another option is the rules look to be the same as the ones on the object. Those rules are already applied on the field as well so you could also remove them from the field.

**Closed** 2021-01-07 20:33 UTC
Labels: @auth, bug, graphql-transformer
