### ISSUE TITLE
Backend cannot be pushed after adding a Function resource

### ISSUE THREAD

**Issue by im-btownsend** [aws-amplify/amplify-cli#3213] opened 2020-01-19 14:15 UTC
**Describe the bug**
After adding a Function resource locally I cannot push the backend to the cloud and receive the error:
```
✖ An error occurred when pushing the resources to the cloud

null
An error occured during the push operation: null
```

**Amplify CLI Version**
4.12.0

**To Reproduce**
Add a Function resource e.g. by enabling reCAPTCHA or email verification to an Auth resource or adding an admin queries API.
In this case, I tried adding:
- Add Google reCaptcha Challenge
- Email Verification Link with Redirect
- Add User to Group
- Email Domain Filtering (blacklist)

The same result is given if only adding a single Function resource e.g. "Add User to Group"

**Expected behaviour**
The backend is pushed and the functions are updated/created

**Desktop (please complete the following information):**
 - OS: macOS 10.15
 - Node Version: 10.16.3

**Comment by montycheese** [comment] 2020-02-22 00:03
One member of our team is also experiencing this issue when pushing the stack for the first time, after initing the project. Any update?

**Comment by Maauritz** [comment] 2020-04-14 12:19
Any updates on this? Cant figure it out.. even just adding a function with` amplify add function` gives `An error occured during the push operation: null`

**Comment by ammarkarachi** [comment] 2020-04-20 17:21
@Maauritz What version of Amplify are you using?
@im-btownsend Have you added the function resource using Auth?

**Comment by Maauritz** [comment] 2020-04-20 18:20
@ammarkarachi tested on `4.13 `and `4.18`
`4.13` gives the error: `An error occured during the push operation: null` 
`4.18` gives the error: `An error occured during the push operation: Cannot read property 'join' of null`
OS: `MacOs Mojave 10.14.6`
Note: This occurs even if i initiate an empty project, followed by adding a single empty function.

**Comment by ammarkarachi** [comment] 2020-04-20 21:07
@Maauritz What's the function template you are using?

**Comment by Maauritz** [comment] 2020-04-20 22:44
@ammarkarachi Have been using the Hello-World template, but the error also occurs when adding premade/custom lamda triggers as part of the auth setup.

**Comment by Maauritz** [comment] 2020-04-22 09:13
@ammarkarachi The error appears to be thrown in `lib/extentions/amplify-helpers/push-resources.js` in function `providersPush()` at `yield Promise.all(providerPromises);`. `providerPromises` seems to be logged as `[{}]`.

**Comment by seankovacs** [comment] 2020-04-28 12:51
Same error - in my case, I added MemorySize to all my functions CF json - I could push successfully doing this for most of my functions, but 2 will consistently throw this error. Now I believe it has nothing to do with MemorySize (no syntax errors), but perhaps something else specific to these functions. Tried different node versions from 10-14. I did just reinstall OSX - might be dependency related.

**Comment by seankovacs** [comment] 2020-04-28 14:20
Okay - down the rabbit hole. The error, for me at-least, is coming from runPackageManager in legacyBuild.js. It's trying to throw an error, but actually is raising a secondary error whilst trying to throw a proper error. 
> throw new Error(childProcessResult.output.join());

childProcessResult.output is null - hence the"Cannot read property 'join' of null" error in console.

So the real problem is it's trying to use yarn which isn't installed (currently). I decided to switch back to npm even though I previously used Yarn. Some of my functions have a yarn lock file which is tripping up the runPackageManager inside legacyBuild. If you install Yarn or remove the lock file from your lambda function folder, it should work.

**Comment by Maauritz** [comment] 2020-04-28 17:23
@seankovacs I am using yarn for my project, and my functions does not contain any lock-files so my error still persists :(

**Comment by KandarpAjvalia** [comment] 2020-05-29 03:49
The way I fixed this was by
1. deleting node_modules and yarn.lock
2. npm install (not using yarn now)
3. amplify push

**Comment by SwaySway** [comment] 2020-08-04 20:34
@im-btownsend are you experiencing these issues in the last version?

> - Add Google reCaptcha Challenge
> - Email Verification Link with Redirect
> - Add User to Group
> - Email Domain Filtering (blacklist)

I tried reproing the above in version 4.24.3 and I'm able to receive this error. I also tried to pull down changes and make a change though I am not running into with that workflow either.

**Comment by kaustavghosh06** [comment] 2020-08-14 01:45
Closing this issue due to lack of reproducibility. Please comment on this thread if you're still stuck.

**Closed by kaustavghosh06** 2020-08-14 01:45 UTC
Labels: auth, pending-close-response-required, pending-triage

**Comment by 9514Edward** [comment] 2020-12-07 02:45
The way I fixed this was.  
check if yarn is installed with
yarn version
yarn wasn't installed so I installed it with
npm install -g yarn
Then I started my project over from scratch  (I was coding from a tutorial) and I did amplify push after adding each new set of resources to make sure things were going OK.  They did go ok and I got past the point where I was stuck.
