### ISSUE TITLE
Incorrect resource in generated lambda policy

### ISSUE THREAD

**Issue by khacminh** [aws-amplify/amplify-cli#7828] opened 2021-07-29 09:28 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.15.1

### Amplify CLI Version

5.1.2

### What operating system are you using?

macOS

### Amplify Categories

function

### Amplify Commands

update

### Describe the bug

I would like to allow the lambda function  to update users in the cognito user pool. I ran `amplify update function` to update my function policy for **Resource access permissions**, category **auth**. Then I selected my auth resource name, for example: **demoamplifyad0ec789**. Then, select **create**, **update**, and **read**. The policy created by AWS is not correct:

- The Resources arn was: `arn:aws:cognito-idp:<region>:<account ID>:userpool/authdemoamplifyad0ec789UserPoolId`.
- The **create** permission is selected, but in the **Actions** created, I cannot find the cognito-idp create permissions such as `AdminCreateUser`
- The **update** permission is selected, but in the **Actions** created, I cannot find the cognito-idp update permissions such as `AdminSetUserPassword`, `AdminUpdateUserAttributes`
- The Environment Variable of the user pool ID that was configured for the lambda function is not correct. which was `authdemoamplifyad0ec789UserPoolId`
- After pushing the update to AWS, the configuration in the local has gone also.

Here are the policy created

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "cognito-identity:Describe*",
                "cognito-identity:Get*",
                "cognito-identity:List*",
                "cognito-idp:Describe*",
                "cognito-idp:AdminGetDevice",
                "cognito-idp:AdminGetUser",
                "cognito-idp:AdminList*",
                "cognito-idp:List*",
                "cognito-sync:Describe*",
                "cognito-sync:Get*",
                "cognito-sync:List*",
                "iam:ListOpenIdConnectProviders",
                "iam:ListRoles",
                "sns:ListPlatformApplications"
            ],
            "Resource": [
                "arn:aws:cognito-idp:<region>:<account ID>:userpool/authdemoamplifyad0ec789UserPoolId"
            ],
            "Effect": "Allow"
        }
    ]
}
```

### Expected behavior

- Expected resource: `arn:aws:cognito-idp:<region>:<account ID>:userpool/**<The user pool ID>**`
- The environment variable of the user pool ID for lambda must be set to the correct user pool ID
- The `cognito-idp:Admin*` actions should be included in the policy

### Reproduction steps

1. run`amplify update function` 
2. Lambda function (serverless function)
3. Select the function
4. Select Resource access permissions
5. Select auth, then next
6. Select auth Resource name, for example: **demoamplifyad0ec789**. Then next
7. Select **create**, **update**, and **read**, then next
8. run `amplify push`

**Comment by johnpc** [comment] 2021-07-30 19:54
Have you looked at the [admin queries api](https://docs.amplify.aws/cli/auth/admin#admin-queries-api)? It may offer the functionality you need. 

If not, for now you can manually add the action to the policy. However, it will go away next time you call `amplify update function`.

**Comment by khacminh** [comment] 2021-07-31 10:36
Hi @johnpc,

My use case is a Lambda function can access to the cognito user pool. I can update the policy myself. And I

**Comment by josefaidt** [comment] 2023-01-09 22:39
Closing as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/7828

**Closed by josefaidt** 2023-01-09 22:39 UTC
Labels: pending-triage, extensibility
