### ISSUE TITLE
Add permissions to a DataSource and use it in resolver

### ISSUE THREAD

**Issue by tafelito** [aws-amplify/amplify-cli#1255] opened 2019-04-11 18:26 UTC
I'm adding a custom resolver to do a batch create. I defined the resolver in `CustomerResources.json`
The resolver uses a DynamoDB Table that was automatically generated by the cli from my schema. The resolver needs to update 2 different tables so the IAM Role needs access to both tables as well. I had to manually go to IAM and assign the permissions there but I was wondering if this can be done from the cli

Also the batch update resolver vtl needs to know the Tables name to do the batch update, but I couldn't find any way to pass the name that the cli generates (Table Name + GraphQLAPIIdOutput + env)  to the resolver. How can I do this? As a reference, this was asked here
https://stackoverflow.com/questions/51532658/how-get-enviroment-varible-or-cloudformation-info-in-resolver-mapping-template
https://stackoverflow.com/questions/52449215/is-it-possible-to-reference-a-cloudformation-resource-name-in-an-appsync-resolve

**Comment by mikeparisstuff** [comment] 2019-04-12 19:24
Hey @tafelito, this is certainly possible and it would be great to have better support for batch operations. I think a great first step towards enabling this is to allow you to write your own transformers to encapsulate your own reproducible behavior like this. There is a discussion going on here #1060.

**Comment by mikeparisstuff** [comment] 2019-04-12 19:35
Duplicate of #704.

**Closed by mikeparisstuff** 2019-04-12 19:35 UTC
Labels: duplicate, feature-request, graphql-transformer
