### ISSUE TITLE
`amplify import auth` has two broken multi-environment scenarios

### ISSUE THREAD

**Issue by renebrandel** [aws-amplify/amplify-cli#5677] opened 2020-10-23 15:51 UTC
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
When I import an auth resource and then switch environments without pushing, it results in an error.

**Scenario 1**
```
* amplify init (dev environment)
* amplify auth import (auth #1 - dev)
* amplify env add test (do not use the same auth when offered, instead select a new one)
* amplify env checkout dev
* amplify env checkout test (error listed below)
⚡ amplify env checkout test
✔ Initialized provider successfully.
The following OAuth properties are not matching:
Callback URLs:
| o4ay0b8c1d56_app_clientWeb | o4ay0b8c1d56_app_client |
| -------------------------- | ----------------------- |
| localhost:3000             |                         |
✖ There was an error initializing your environment.
There was an error importing the previously configured auth configuration to the new environment.
Error: There was an error importing the previously configured auth configuration to the new environment.
    at updateConfigOnEnvInit (/Users/asmajlovic/.nvm/versions/node/v14.7.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/index.js:85:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /Users/asmajlovic/.nvm/versions/node/v14.7.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/index.js:300:22
~/code/amp-import-test
```

**Scenario 2**
```
* import AUTH into dev
* import different AUTH into test (as per the same scenario as #1)
* both envs have the same resource name:
| Category | Resource name         | Operation | Provider plugin   |
| -------- | --------------------- | --------- | ----------------- |
| Auth     | ampimporttestedfed212 | Import    | awscloudformation |
* amplify remove auth (removes auth in both environments - should it?)
```
Expected: it only removes the auth resource from the latest env.

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
4.30.0

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

**Additional context**

**Comment by renebrandel** [comment] 2020-10-23 16:45
cc @ asmajlovicmars

**Comment by renebrandel** [comment] 2020-10-23 17:16
@asmajlovicmars - we're having trouble reproducing this issue. Can you try again with the latest version or provide more detailed intsructions?

**Comment by attilah** [comment] 2020-10-23 17:19
@asmajlovicmars I tried to reproduce both scenarios but I was unable to do so, it worked for me as expected.

The first scenario is clear that during import 2 properties were different between the two app clients, it would be good to know how that happened if those were provisioned with the CLI.

About the 2nd one, no it should be only removed from the currently checked out environment, so if you have git tracking you should see that it removed only from the `test` env's object within `team-provider-info.json`, but not from `dev`.

**Comment by asmajlovicmars** [comment] 2020-10-23 17:57
@attilah I re-run the whole scenario, and true, I didn't get the same error, but I'm sure I run more commands on my first run, so if I figure out what caused the error, I'll report it. 

To summarize: 
Switching between the dev and test environments was fine. 
Case #2: When I removed the User Pool from the second environment (test), and checked-out the dev environment again, visually the auth wasn't there (amplify status), but you're right, it was still in team-provider-info.json! 

I think amplify status should still show it, or should I do something else to be able to still see the auth in the dev environment?  

Below are the steps I followed:

`
⚡ amplify init
⚡ amplify auth import
? What type of auth resource do you want to import? …
❯ Cognito User Pool and Identity Pool
⚡ amplify status
Current Environment: dev

| Category | Resource name         | Operation | Provider plugin   |
| -------- | --------------------- | --------- | ----------------- |
| Auth     | ampimporttest6aed1948 | Import    | awscloudformation |
⚡ amplify env add
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? No
? Enter a name for the environment test
Using default provider  awscloudformation
✔ Successfully created initial AWS cloud resources for deployments.
✔ Initialized provider successfully.
? The resource: 'ampimporttest6aed1948' (Cognito User Pool: 'us-east-1_f1Ed74Hzs') already imported to 'dev' environment, do you want to import it to the new environment? (y/N) › false
If you choose No, then an import walkthrough will run to import a different resource into the new environment.
(specify a different C. User Pool)
⚡ amplify status

Current Environment: test

| Category | Resource name         | Operation | Provider plugin   |
| -------- | --------------------- | --------- | ----------------- |
| Auth     | ampimporttest6aed1948 | Import    | awscloudformation |
⚡ amplify env checkout dev
✔ Initialized provider successfully.
Initialized your environment successfully.
~/code/amp-import-test
⚡
⚡ amplify env checkout test
✔ Initialized provider successfully.
Initialized your environment successfully.
~/code/amp-import-test
⚡ amplify status

Current Environment: test

| Category | Resource name         | Operation | Provider plugin   |
| -------- | --------------------- | --------- | ----------------- |
| Auth     | ampimporttest6aed1948 | Import    | awscloudformation |
⚡ amplify remove auth
? Choose the resource you would want to remove (Use arrow keys)
❯ ampimporttest6aed1948
? Are you sure you want to unlink this imported resource from this Amplify backe
nd environment? The imported resource itself will not be deleted. (Y/n) y

⚡ amplify remove auth
? Choose the resource you would want to remove ampimporttest6aed1948

? Are you sure you want to unlink this imported resource from this Amplify backe
nd environment? The imported resource itself will not be deleted. Yes
Successfully removed resource
~/code/amp-import-test
⚡ amplify env checkout dev
✔ Initialized provider successfully.
Initialized your environment successfully.
~/code/amp-import-test
⚡ amplify status

Current Environment: dev

| Category | Resource name | Operation | Provider plugin |
| -------- | ------------- | --------- | --------------- |


`

**Comment by attilah** [comment] 2020-10-23 20:48
@asmajlovicmars based on our conversation I was able to get to the same situation what you described, but it is by design and works the same way for other resources when auth is added and not imported. The main reason is that env switching does not involve cloud uploads, so when you add a resource locally to an env, then switching to another one, all those settings are gone, since the CLI had no way of storing those as no push operations were done. I will talk with @renebrandel about the DX here, but closing the issue as it is by design.

**Closed by attilah** 2020-10-23 20:48 UTC
Labels: auth, import
