### ISSUE TITLE
Parameters: [bucketName] must have values

### ISSUE THREAD

**Issue by brylie** [aws-amplify/amplify-cli#955] opened 2019-02-27 10:19 UTC
**Describe the bug**
When adding hosting to a project and running the `amplify publish`, the command fails with the following:

> CREATE_FAILED hostingS3AndCloudFront AWS::CloudFormation::Stack ... Parameters: [bucketName] must have values

My *parameters.json* looks like this:

```js
{
    "bucketName": "suggested-bucket-name-20190227121241-hostingbucket"
}
```

**To Reproduce**
1. issue `amplify add hosting`
2. use default values offered
3. run `amplify publish`

**Expected behavior**
I expected the app to be published successfully.

**Comment by yuth** [comment] 2019-02-28 00:46
@brylie what version of Amplify CLI do you have installed? You can determine the version number by running `amplify -v`

**Comment by brylie** [comment] 2019-02-28 10:30
amplify -v > 1.1.6

I ran the upgrade process when Amplify detected that I had initialized the project with an older version.

I added hosting *after* initializing and upgrading the project.

**Comment by brylie** [comment] 2019-02-28 10:36
I tried again today, removing *all* Amplify resources from the project, and then re-adding hosting. However, the process fails again, with a different error:

```
$ amplify status

Current Environment: NONE

| Category | Resource name | Operation | Provider plugin |
| -------- | ------------- | --------- | --------------- |


brylie@brylie-kubuntu:~/code/MaaS_Global/abuse-platform/frontend$ amplify add hosting
? Select the environment setup: DEV (S3 only with HTTP)
? hosting bucket name frontendpoc-20190228123211-hostingbucket
? index doc for the website index.html
? error doc for the website index.html

You can now publish your app using the following command:
Command: amplify publish

$ amplify publish

Current Environment: NONE

| Category | Resource name   | Operation | Provider plugin   |
| -------- | --------------- | --------- | ----------------- |
| Hosting  | S3AndCloudFront | Create    | awscloudformation |
? Are you sure you want to continue? Yes
⠏ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS hostingS3AndCloudFront     AWS::CloudFormation::Stack Thu Feb 28 2019 12:33:20 GMT+0200 (Eastern European Standard Time)               
UPDATE_IN_PROGRESS frontendpoc-20190208162455 AWS::CloudFormation::Stack Thu Feb 28 2019 12:33:15 GMT+0200 (Eastern European Standard Time) User Initiated
⠋ Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS frontendpoc-20190208162455 AWS::CloudFormation::Stack Thu Feb 28 2019 12:33:24 GMT+0200 (Eastern European Standard Time)                                                                      
UPDATE_ROLLBACK_IN_PROGRESS                  frontendpoc-20190208162455 AWS::CloudFormation::Stack Thu Feb 28 2019 12:33:22 GMT+0200 (Eastern European Standard Time) The following resource(s) failed to create: [hostingS3AndCloudFront].
CREATE_FAILED                                hostingS3AndCloudFront     AWS::CloudFormation::Stack Thu Feb 28 2019 12:33:21 GMT+0200 (Eastern European Standard Time) Parameters: [bucketName] must have values                            
⠇ Updating resources in the cloud. This may take a few minutes...

DELETE_COMPLETE hostingS3AndCloudFront AWS::CloudFormation::Stack Thu Feb 28 2019 12:33:26 GMT+0200 (Eastern European Standard Time) 
⠹ Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_COMPLETE frontendpoc-20190208162455 AWS::CloudFormation::Stack Thu Feb 28 2019 12:33:26 GMT+0200 (Eastern European Standard Time) 
⠧ Updating resources in the cloud. This may take a few minutes...Error updating cloudformation stack
⠇ Updating resources in the cloud. This may take a few minutes...

Following resources failed

✖ An error occurred when pushing the resources to the cloud
```

**Comment by brylie** [comment] 2019-02-28 10:39
I tried again today, removing *all* Amplify resources from the project, and then re-adding hosting. However, the process fails again, with a different error:

```
$ amplify status

Current Environment: NONE

| Category | Resource name | Operation | Provider plugin |
| -------- | ------------- | --------- | --------------- |


$ amplify add hosting
? Select the environment setup: DEV (S3 only with HTTP)
? hosting bucket name project-20190228123211-hostingbucket
? index doc for the website index.html
? error doc for the website index.html

You can now publish your app using the following command:
Command: amplify publish

$ amplify publish

Current Environment: NONE

| Category | Resource name   | Operation | Provider plugin   |
| -------- | --------------- | --------- | ----------------- |
| Hosting  | S3AndCloudFront | Create    | awscloudformation |
? Are you sure you want to continue? Yes
⠏ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS hostingS3AndCloudFront     AWS::CloudFormation::Stack Thu Feb 28 2019 12:33:20 GMT+0200 (Eastern European Standard Time)               
UPDATE_IN_PROGRESS project-20190208162455 AWS::CloudFormation::Stack Thu Feb 28 2019 12:33:15 GMT+0200 (Eastern European Standard Time) User Initiated
⠋ Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS project-20190208162455 AWS::CloudFormation::Stack Thu Feb 28 2019 12:33:24 GMT+0200 (Eastern European Standard Time)                                                                      
UPDATE_ROLLBACK_IN_PROGRESS                  project-20190208162455 AWS::CloudFormation::Stack Thu Feb 28 2019 12:33:22 GMT+0200 (Eastern European Standard Time) The following resource(s) failed to create: [hostingS3AndCloudFront].
CREATE_FAILED                                hostingS3AndCloudFront     AWS::CloudFormation::Stack Thu Feb 28 2019 12:33:21 GMT+0200 (Eastern European Standard Time) Parameters: [bucketName] must have values                            
⠇ Updating resources in the cloud. This may take a few minutes...

DELETE_COMPLETE hostingS3AndCloudFront AWS::CloudFormation::Stack Thu Feb 28 2019 12:33:26 GMT+0200 (Eastern European Standard Time) 
⠹ Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_COMPLETE project-20190208162455 AWS::CloudFormation::Stack Thu Feb 28 2019 12:33:26 GMT+0200 (Eastern European Standard Time) 
⠧ Updating resources in the cloud. This may take a few minutes...Error updating cloudformation stack
⠇ Updating resources in the cloud. This may take a few minutes...

Following resources failed

✖ An error occurred when pushing the resources to the cloud
```

**Comment by bitIO** [comment] 2019-02-28 14:33
This also happens to me when using different cli versions. In one computer, amplify-cli works for the project I'm building with version 1.1.3 but, in the laptop, after cloning the repo, install packges, etc when adding a function I got the message for all the parameter of every resource that has been created before. Just my 2 cents

**Comment by UnleashedMind** [comment] 2019-02-28 21:30
@brylie 
It might be because your amplify cli is not properly updated, could you go through these steps to update it again? 
- npm remove -g @aws-amplify/cli
- npm cache clean
- npm install -g @aws-amplify/cli@latest

If you are just practicing, try to run `amplify init` on a new project and then add the hosting category. 
The CLI does have to capability to migrate project setup from its older versions though, so that shouldn't be a big concern.

**Comment by bitIO** [comment] 2019-03-01 08:50
@UnleashedMind so, if the project we are working on is not just a toy, we should not be using updated versions from the one we used to create it? I mean, right now, I can't use it having versions 1.1.3 and 1.1.6 😕

**Comment by UnleashedMind** [comment] 2019-03-04 18:42
@bitIO that's not what I meant, you should go ahead and update the CLI version, but make sure your update is complete. 
We couldn't reproduce the issue, so we suspect that there might be some problem with your cli installation. Please try to follow the steps to re-install it.

**Comment by UnleashedMind** [comment] 2019-03-05 18:49
@brylie 
Do you still have this issue? 
If you don't see this issue anymore, please close it.

**Comment by brylie** [comment] 2019-03-06 07:16
Well, I will try to deploy again today. Otherwise, we are considering just deploying with Jenkins.

**Comment by brylie** [comment] 2019-03-06 08:06
I tried again with CLI 1.1.7, updating the project when prompted:

![peek 2019-03-06 09-58](https://user-images.githubusercontent.com/17307/53865258-56f6d600-3ff7-11e9-8f2d-0604a39fd131.gif)

For whatever reason, it is not creating or finding the S3 bucket when running `amplify publish` after adding hosting.

**Comment by UnleashedMind** [comment] 2019-03-06 18:36
I see the cli has successfully migrated your project to be used with the latest CLI version. 
There's only an auth category after the migration. 
Could you run `amplify hosting add` after the migration? and then do a `amplify push`?

**Comment by kaustavghosh06** [comment] 2019-04-12 19:35
Closing this issue due to lack of requester comments and abiity to not reproduce this behavior with the latest version of the CLI. Please feel free to re-open this if you're still sseeing the issue.

**Closed by kaustavghosh06** 2019-04-12 19:35 UTC
Labels: hosting, pending-response, pending-triage

**Comment by brylie** [comment] 2019-04-13 07:15
> Could you run `amplify hosting add` after the migration? and then do a amplify push?

If you notice, `amplify add hosting` is the first command issued in the animated GIF. It then proceeds to upgrade the project.

**Comment by dysc** [comment] 2019-05-08 23:30
I am still getting this issue with v1.6.4-v1.6.8

**Comment by dperconti** [comment] 2019-05-19 06:15
I am getting this error as well with `v1.6.9`

```UPDATE_FAILED               authcognito348bef3a    AWS::CloudFormation::Stack Sat May 18 2019 23:13:31 GMT-0700 (Pacific Daylight Time) Parameters: [authRoleArn, usernameAttributes, autoVerifiedAttributes, unauthRoleName, allowUnauthenticatedIdentities, smsVerificationMessage, userpoolClientReadAttributes, mfaTypes, emailVerificationSubject, useDefault, openIdLambdaIAMPolicy, userpoolClientGenerateSecret, mfaConfiguration, userpoolClientLogPolicy, openIdRolePolicy, identityPoolName, openIdLogPolicy, authSelections, smsAuthenticationMessage, roleExternalId, mfaLambdaLogPolicy, passwordPolicyMinLength, userPoolName, openIdLambdaRoleName, userpoolClientWriteAttributes, policyName, userpoolClientName, userpoolClientLambdaPolicy, resourceName, mfaLambdaIAMPolicy, mfaPassRolePolicy, emailVerificationMessage, userpoolClientRefreshTokenValidity, userpoolClientSetAttributes, unauthRoleArn, authRoleName, requiredAttributes, roleName, passwordPolicyCharacters, lambdaLogPolicy, userpoolClientLambdaRole, defaultPasswordPolicy, mfaLambdaRole] must have values
CREATE_FAILED               myApi             AWS::CloudFormation::Stack Sat May 18 2019 23:13:31 GMT-0700 (Pacific Daylight Time) Parameters: [S3DeploymentBucket, S3DeploymentRootKey] must have values```

**Comment by LoganArnett** [comment] 2019-06-05 16:19
Still getting this in v1.7.0 as well, I can see in my nested config that the values I need are there before running `amplify push` or `amplify publish` but then are removed as the process is running which causes the error

**Comment by brylie** [comment] 2019-06-05 16:23
I believe this issue should be re-opened, although not on my behalf. Rather, for other people who are experiencing the issue.

**Comment by Lasim** [comment] 2019-08-18 12:51
unfortunately I have the same problem.
I have created a new VueJS project with GraphQL APi.

Amplify Version: `1.12.0`

```
$ amplify push

UPDATE_ROLLBACK_IN_PROGRESS test-graphql-multi-prod-20190818144634 AWS::CloudFormation::Stack Sun Aug 18 2019 14:48:00 GMT+0200 (Mitteleuropäische Sommerzeit) The following resource(s) failed to create: [apitestGraphQLMulti].    
CREATE_FAILED               apitestGraphQLMulti                    AWS::CloudFormation::Stack Sun Aug 18 2019 14:47:59 GMT+0200 (Mitteleuropäische Sommerzeit) Parameters: [S3DeploymentBucket, S3DeploymentRootKey] must have values

```

**Comment by dabit3** [comment] 2019-09-04 11:08
For anyone running into this issue after attempting to update an API, check `amplify/.config/local-env-info.json` to make sure the path is correct. I had moved my project and the path no longer was the right path.

**Comment by andyhmi** [comment] 2019-09-05 15:43
Still having troubles. Once again, I did not look into this too deep. Just wondering if you can see something wrong again, otherwise I'll spend some time debugging. Getting the following error messages now. Also attached full output. Thank you!

```
UPDATE_FAILED               quicksightapiquicksightapi          AWS::CloudFormation::Stack Thu Sep 05 2019 10:31:51 GMT-0500 (Central Daylight Time) Parameters: [S3DeploymentBucket, S3DeploymentRootKey] must have values 

DELETE_FAILED      UpdateRolesWithIDPFunctionOutputs AWS::CloudFormation::CustomResource Thu Sep 05 2019 10:32:41 GMT-0500 (Central Daylight Time) Invalid Response object: Value of property Data must be an object

Following resources failed

Resource Name: 2019/09/05/[$LATEST]d9226b1e004c4afba53c1df78a0a0da3 (AWS::CloudFormation::CustomResource)
Event Type: delete
Reason: Invalid Response object: Value of property Data must be an object
URL: https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/arn%3Aaws%3Acloudformation%3Aus-east-1%3A153753875240%3Astack%2Fquicksight-embed-dev-20190730193111%2F1d9f9b50-b322-11e9-ba19-0a325fb8c980/events


✖ An error occurred when pushing the resources to the cloud
```


[output.txt](https://github.com/aws-amplify/amplify-cli/files/3580058/output.txt)

**Comment by philohelp** [comment] 2019-09-08 23:10
Thanks a lot @dabit3 ! I had indeed renamed the directory of my project. Such a tiny little change...

**Comment by PeteLatham-CothamTechnologies** [comment] 2019-12-11 11:48
Thank you @dabit3 !

**Comment by vlac666** [comment] 2020-04-14 12:43
Thank you @dabit3 !

**Comment by hoomand** [comment] 2020-05-04 22:13
Thanks @dabit3 , very true!

I was getting exactly the same error and re-configuring amplify fixed the problem:

`amplify configure project`

What I noticed was that I had renamed my main project directory (git root) from amplifyagora to amplify-marketplace, however this hadn't changed the directory name in amplify/.config/local-env-info.json, so, the right parameters were not being sent to Cloudformation. Re-configuring amplify (which is harmless and asks only bunch of questions) solved it for me and my next amplify push created the S3 bucket successfully.
