### ISSUE TITLE
Trigger functions are created separately from  index.js

### ISSUE THREAD

**Issue by kimfucious** [aws-amplify/amplify-cli#4151] opened 2020-05-02 13:10 UTC
**Describe the bug**

This is potentially more of an annoyance than a bug.

When creating a trigger function using `amplify function add`, the `trigger-xxx.js` file is created in the `src` directory alongside the `index.js` function.

The `index.js` function is a generic placeholder.  This is the file that gets triggered, not the trigger function that the CLI prompts you to edit.

This is solved by replacing the contents of `index.js` with what's in `trigger-xxx.js`.

My assumption is that the `index.js` is there to `prove it works` before implementing what has been edited into `trigger-xxx.js`; not sure.

**Amplify CLI Version**
4.18.0

**To Reproduce**
```console
$ amplify function add
Using service: Lambda, provided by: awscloudformation
? Provide a friendly name for your resource to be used as a label for this category in the project: myTriggerFn
? Provide the AWS Lambda function name: myTriggerFn
? Choose the function runtime that you want to use: NodeJS
? Choose the function template that you want to use: Lambda trigger
? What event source do you want to associate with Lambda trigger? Amazon DynamoDB Stream
? Choose a DynamoDB event source option Use API category graphql @model backed DynamoDB table(s) in the current Amplify project
Selected resource myApp
Selected @model MyModel
? Do you want to access other resources created in this project from your Lambda function? Yes
? Select the category 

You can access the following resource attributes as environment variables from your Lambda function
var environment = process.env.ENV
var region = process.env.REGION

? Do you want to invoke this function on a recurring schedule? No
? Do you want to edit the local lambda function now? Yes
Please edit the file in your editor: /home/kim/myapp/amplify/backend/function/myTriggerFn/src/trigger-dynamodb.js
? Press enter to continue 
Successfully added resource myTriggerFn locally.
```

**Expected behavior**
When the CLI prompts with `Do you want to edit the local lambda function now?`, The file that gets edited should be the file one that gets triggered (i.e. index.js).

**Comment by edwardfoyle** [comment] 2020-05-05 21:40
I believe this was a bug that is fixed in the latest release (4.18.1). Can you try updating to that version and see if the issue is fixed?

**Comment by kimfucious** [comment] 2020-05-07 14:30
Hi @edwardfoyle,

Thanks for the response.

I will check on this and report asap.

**Closed** 2020-05-08 17:38 UTC
Labels: functions, pending-response, question

**Comment by kimfucious** [comment] 2020-05-08 18:22
I was gonna test this, but now, I guess I won't.
