### ISSUE TITLE
amplify init "type of app" doesn't actually allow selection Windows 10

### ISSUE THREAD

**Issue by bradthurber** [aws-amplify/amplify-cli#34] opened 2018-08-27 12:08 UTC
Do you want to request a feature or report a bug? Bug

What is the current behavior?
When I do amplify init, it asks the first question about editor and I am able to select an editor. The next question about type of app I don't have a chance to answer. Note below that it looks like I picked javascript, but actually I just got my os prompt back

```
PS C:\Users\bradt\Documents\cs\react\my-amplify-app> amplify init
Note: It is recommended to run this command from the root of your app directory
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building (Use arrow keys)
  android
  ios
> javascript
PS C:\Users\bradt\Documents\cs\react\my-amplify-app>
```

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
1. Run amplify init
2. Select editor
3. Notice no change to select type of app

What is the expected behavior?
Should be able to select app type

Which versions of Amplify CLI, and which  OS are affected by this issue? Did this work in previous versions?

Windows 10, latest version of Amplify CLI that gets installed (0.1.14)

**Comment by mwarger** [comment] 2018-08-27 13:09
Can confirm that this isn't just on init.  Any time there is a prompt, the choice fails out and kicks you back to the shell without letting you continue selecting choices.  I believe something is silently failing.

**Comment by kaustavghosh06** [comment] 2018-08-27 23:29
Hey guys, so I tried using the CLI with the Windows Linux subsystem(WSL) on windows and it works great. We have updated our main README as well with the following. Highly encourage using the WSL for your Amplify development. 
 
```

If you're using Windows, the CLI currently supports [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10).

```

In the meanwhile, we're trying to figure out the root cause of the erroneous behavior of the CLI with the windows filesystem.

**Comment by ericathegreat** [comment] 2018-08-28 01:56
For reference, the option selection works for me in Powershell. Might be worth a try as an alternative to CMD?

**Comment by ericathegreat** [comment] 2018-08-28 22:48
@mwarger No, I haven't had any issues with the actual interactions. What key are you pressing for selection? Spacebar?

**Comment by kaustavghosh06** [comment] 2018-08-29 01:33
@wstidolph  checkout @mwarger  post on using Windows Linux Subsystem(WSL) on native windows power shell out here - https://github.com/aws-amplify/amplify-cli/issues/13. I think it’s a great workaround and would highly recommend using WSL for the Amplify CLI.

**Comment by mwarger** [comment] 2018-09-20 13:41
@kaustavghosh06  - I believe this has been resolved with a recent release.

**Comment by kavengagne** [comment] 2018-09-22 18:28
@mwarger @kaustavghosh06 @wstidolph This is possible that my recent changes to gluegun fixed it on Windows. I would be interested to know if that's not the case. I'm pretty sure I can fix that issue.

**Comment by mwarger** [comment] 2018-09-22 18:40
I think it did. I was able to install on a new machine a couple days ago and was able to make selections without any issues.

**Comment by attilah** [comment] 2018-10-08 20:56
I just tried with latest amplify-cli and init exits at frontend plugin selection.

I patched the sources to remove the frontend step and the issue is the same, it sliently exits.

So the issue is that the 2nd option is always exits. I tried to put the latest gluegun into the cli's node_modules dir, that did not help either.

**Comment by kaustavghosh06** [comment] 2018-10-15 17:31
@stevegula  @attilah Are you using windows without WSL?

**Comment by attilah** [comment] 2018-10-15 17:35
@kaustavghosh06 yes, I tried in "windows windows", in WSL on the same machine, everything works...WSL is "not windows".

**Comment by kaustavghosh06** [comment] 2018-10-15 17:37
@attilah We have an issue open with our dependent CLI framework for making it work on windows natively and are actively working with them to get the fix out. Until then we recommend using WSL.

**Comment by attilah** [comment] 2018-10-15 17:40
@kaustavghosh06 I tried the @next from that cli library where the "path fix" was included and still had the same problem, but ok, let's wait. The problem is that working with WSL and Windows is not going back and forth, since some generated files are including the absolute path on the host machine /home/xyz/....... which does not map to the same location under Windows...

But sure working purely in WSL could do the trick.

**Comment by baldo12** [comment] 2018-10-19 00:39
Same!

amplify -v
0.1.28
node -v
v10.10.0

PS C:\Projetos\> amplify init
Note: It is recommended to run this command from the root of your app directory
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building (Use arrow keys)
  android
  ios
> javascript
PS C:\Projetos\>

**Comment by stevegula** [comment] 2018-10-24 14:39
> @stevegula @attilah Are you using windows without WSL?

Correct, I'm not using the Linux subsystem.

**Comment by kaustavghosh06** [comment] 2018-11-05 20:21
We published a new version of the CLI to npm, version -> 0.1.32 with fixes for windows. Feel free to re-open the issue if the problem still persists.

**Closed by kaustavghosh06** 2018-11-05 20:21 UTC
Labels: windows

**Comment by bghtrbb** [comment] 2018-11-09 03:07
@kaustavghosh06 This has not fixed the issue. I have clean installed these and am still not able to run the commands.

![Amplify Config](https://s3.amazonaws.com/otherrandomfiles/amplify+config.PNG)
![Amplify Init](https://s3.amazonaws.com/otherrandomfiles/amplify+init.PNG)

**Comment by kaustavghosh06** [comment] 2018-11-09 03:08
@bghtbb can do run ‘amplify -v’ and check which version of the CLI you’re using?

**Comment by bghtrbb** [comment] 2018-11-09 03:14
@kaustavghosh06 0.1.32

![Amplify Version](https://s3.amazonaws.com/otherrandomfiles/amplify+version.PNG)

**Comment by pdeak** [comment] 2019-01-03 15:09
I still get this exact same issue on Node v11.6.0, Amplify 0.1.38 and Widows 10. It doesn't make a difference if amplify is used from the local node_modules or global installation.

**Comment by dmhalejr** [comment] 2019-01-03 16:01
I don't think this problem is something in regards to Amplify CLI itself but maybe to do with `inquirer` dependency which leverages the prompt.

https://github.com/aws-amplify/amplify-cli/blob/b12d20b9d85f7fc6abf7e2f7fbe11e1a108911b9/packages/amplify-cli/src/lib/init-steps/s1-initFrontendHandler.js#L35

Just as a friendly road sign, I'd recommend if you can on Windows 10 to [leverage the Ubuntu subsystem](https://docs.microsoft.com/en-us/windows/wsl/install-win10) as a workaround for now. I'm still running into the issue in PowerShell but had success utilizing the subsystem without any issue.

Going to be digging into that dependency package and see if I can figure out the `why?` to the `uh?`

Best wishes everyone!

**Comment by pdeak** [comment] 2019-01-04 09:35
I finally got it working, just leaving this here in case it helps anyone else.

Using WSL did not make a difference. I also tried using several different command windows and shells (Powershell, cmd, cmder, Consolez, bash) and none if it made a difference. I also tried running a linux terminal using docker (docker -it) and running amplify init in there, and still I would have the exact same issue.

How I eventually got it working is that I switched from using yarn to npm. Using npm with a global install of @aws-amplify/cli works now, and I can choose the app type on the second step of amplify init.
