### ISSUE TITLE
GraphQL mutation update, delete doesn't working

### ISSUE THREAD

**Issue by pptavozl** [aws-amplify/amplify-cli#9330] opened 2021-12-16 18:27 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.18.1

### Amplify CLI Version

7.63

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

I can't do graphql mutations: update, delete.
Actually I can do: get, list, create

### Expected behavior

Update the document

### Reproduction steps

1.- Run my mutation with graphql client:
```
mutation MyMutation {
	updatePost(input: {
		id: "c18c389d-f2be-4229-a38e-8de97cf8d601",
    titulo: "Sisisisisisi" 
  }) {
    id
    titulo 
  }
}
```

Resulting:
```
{
  "data": {
    "updatePost": null
  },
  "errors": [
    {
      "path": [
        "updatePost"
      ],
      "data": null,
      "errorType": "MappingTemplate",
      "errorInfo": null,
      "locations": [
        {
          "line": 9,
          "column": 2,
          "sourceName": null
        }
      ],
      "message": "Unsupported element '$[operation]'."
    }
  ]
}
```

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by Straubulous** [comment] 2021-12-17 18:10
@pptavozl please provide schema, cli.json. Also, do you have any custom resolvers?

**Comment by pptavozl** [comment] 2021-12-17 19:34
> @pptavozl please provide schema, cli.json. Also, do you have any custom resolvers?

Thanks for answering

I have schema and rsolvers created by "amplify push"


schema.graphql
```

type Categoria @aws_iam @aws_api_key {
  id: ID!
  nombre: String
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  _version: Int!
  _deleted: Boolean
  _lastChangedAt: AWSTimestamp!
}

type Post @aws_iam @aws_api_key {
  id: ID!
  titulo: String
  contenido: String
  date: AWSDateTime
  timestamp: AWSTimestamp
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  _version: Int!
  _deleted: Boolean
  _lastChangedAt: AWSTimestamp!
}

input ModelStringInput {
  ne: String
  eq: String
  le: String
  lt: String
  ge: String
  gt: String
  contains: String
  notContains: String
  between: [String]
  beginsWith: String
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
  size: ModelSizeInput
}

input ModelIntInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelFloatInput {
  ne: Float
  eq: Float
  le: Float
  lt: Float
  ge: Float
  gt: Float
  between: [Float]
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelBooleanInput {
  ne: Boolean
  eq: Boolean
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelIDInput {
  ne: ID
  eq: ID
  le: ID
  lt: ID
  ge: ID
  gt: ID
  contains: ID
  notContains: ID
  between: [ID]
  beginsWith: ID
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
  size: ModelSizeInput
}

enum ModelAttributeTypes {
  binary
  binarySet
  bool
  list
  map
  number
  numberSet
  string
  stringSet
  _null
}

input ModelSizeInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
}

enum ModelSortDirection {
  ASC
  DESC
}

type ModelCategoriaConnection @aws_api_key @aws_iam {
  items: [Categoria!]!
  nextToken: String
  startedAt: AWSTimestamp
}

input ModelCategoriaFilterInput {
  id: ModelIDInput
  nombre: ModelStringInput
  and: [ModelCategoriaFilterInput]
  or: [ModelCategoriaFilterInput]
  not: ModelCategoriaFilterInput
}

type Query {
  getCategoria(id: ID!): Categoria @aws_api_key @aws_iam
  listCategorias(filter: ModelCategoriaFilterInput, limit: Int, nextToken: String): ModelCategoriaConnection @aws_api_key @aws_iam
  syncCategorias(filter: ModelCategoriaFilterInput, limit: Int, nextToken: String, lastSync: AWSTimestamp): ModelCategoriaConnection @aws_api_key @aws_iam
  getPost(id: ID!): Post @aws_api_key @aws_iam
  listPosts(filter: ModelPostFilterInput, limit: Int, nextToken: String): ModelPostConnection @aws_api_key @aws_iam
  syncPosts(filter: ModelPostFilterInput, limit: Int, nextToken: String, lastSync: AWSTimestamp): ModelPostConnection @aws_api_key @aws_iam
}

input ModelCategoriaConditionInput {
  nombre: ModelStringInput
  and: [ModelCategoriaConditionInput]
  or: [ModelCategoriaConditionInput]
  not: ModelCategoriaConditionInput
}

input CreateCategoriaInput {
  id: ID
  nombre: String
  _version: Int
}

input UpdateCategoriaInput {
  id: ID!
  nombre: String
  _version: Int
}

input DeleteCategoriaInput {
  id: ID!
  _version: Int
}

type Mutation {
  createCategoria(input: CreateCategoriaInput!, condition: ModelCategoriaConditionInput): Categoria @aws_api_key @aws_iam
  updateCategoria(input: UpdateCategoriaInput!, condition: ModelCategoriaConditionInput): Categoria @aws_api_key @aws_iam
  deleteCategoria(input: DeleteCategoriaInput!, condition: ModelCategoriaConditionInput): Categoria @aws_api_key @aws_iam
  createPost(input: CreatePostInput!, condition: ModelPostConditionInput): Post @aws_api_key @aws_iam
  updatePost(input: UpdatePostInput!, condition: ModelPostConditionInput): Post @aws_api_key @aws_iam
  deletePost(input: DeletePostInput!, condition: ModelPostConditionInput): Post @aws_api_key @aws_iam
}

type Subscription {
  onCreateCategoria: Categoria @aws_subscribe(mutations: ["createCategoria"]) @aws_api_key @aws_iam
  onUpdateCategoria: Categoria @aws_subscribe(mutations: ["updateCategoria"]) @aws_api_key @aws_iam
  onDeleteCategoria: Categoria @aws_subscribe(mutations: ["deleteCategoria"]) @aws_api_key @aws_iam
  onCreatePost: Post @aws_subscribe(mutations: ["createPost"]) @aws_api_key @aws_iam
  onUpdatePost: Post @aws_subscribe(mutations: ["updatePost"]) @aws_api_key @aws_iam
  onDeletePost: Post @aws_subscribe(mutations: ["deletePost"]) @aws_api_key @aws_iam
}

type ModelPostConnection @aws_api_key @aws_iam {
  items: [Post!]!
  nextToken: String
  startedAt: AWSTimestamp
}

input ModelPostFilterInput {
  id: ModelIDInput
  titulo: ModelStringInput
  contenido: ModelStringInput
  date: ModelStringInput
  timestamp: ModelIntInput
  and: [ModelPostFilterInput]
  or: [ModelPostFilterInput]
  not: ModelPostFilterInput
}

input ModelPostConditionInput {
  titulo: ModelStringInput
  contenido: ModelStringInput
  date: ModelStringInput
  timestamp: ModelIntInput
  and: [ModelPostConditionInput]
  or: [ModelPostConditionInput]
  not: ModelPostConditionInput
}

input CreatePostInput {
  id: ID
  titulo: String
  contenido: String
  date: AWSDateTime
  timestamp: AWSTimestamp
  _version: Int
}

input UpdatePostInput {
  id: ID!
  titulo: String
  contenido: String
  date: AWSDateTime
  timestamp: AWSTimestamp
  _version: Int
}

input DeletePostInput {
  id: ID!
  _version: Int
}

```
cli-input.json
```
{
  "version": 1,
  "serviceConfiguration": {
    "apiName": "svelteaws",
    "serviceName": "AppSync",
    "gqlSchemaPath": "/Users/zimbronapps/development/tests/svelteaws/amplify/backend/api/svelteaws/schema.graphql",
    "defaultAuthType": {
      "mode": "API_KEY",
      "keyDescription": "api key description",
      "expirationTime": 30
    },
    "additionalAuthTypes": [
      {
        "mode": "AWS_IAM"
      },
      {
        "mode": "AMAZON_COGNITO_USER_POOLS",
        "cognitoUserPoolId": "authsvelteaws"
      }
    ],
    "conflictResolution": {
      "defaultResolutionStrategy": {
        "type": "AUTOMERGE"
      }
    }
  }
}
```

**Comment by AndyW22** [comment] 2021-12-17 23:27
Im also having this issue, with schema: 

```type UserVote
  @model
  @auth(rules: [{ allow: owner }, { allow: private, provider: iam }]) {
  id: String!
  owner: String! 
  createdAt: AWSDateTime!
  slug: String!
  vote: Vote!
}``` 

Running locally, I can't update or delete a `UserVote` using cognito pool authentication, giving `Unauthorized`. Locally I can update/delete them with IAM with an AuthRole. 

Once pushed, cognito still gives same error, and trying to update/delete with IAM with AuthRole gives: 

```{
    "errorType": "Error",
    "errorMessage": "GraphQL error: Unsupported element '$[operation]'.\nGraphQL error: Unsupported element '$[operation]'.",
    "graphQLErrors": [
        {
            "path": [
                "updateGameVote"
            ],
            "data": null,
            "errorType": "MappingTemplate",
            "errorInfo": null,
            "locations": [
                {
                    "line": 2,
                    "column": 3,
                    "sourceName": null
                }
            ],
            "message": "Unsupported element '$[operation]'."
        },
        {
            "path": [
                "updateOptimization"
            ],
            "data": null,
            "errorType": "MappingTemplate",
            "errorInfo": null,
            "locations": [
                {
                    "line": 11,
                    "column": 3,
                    "sourceName": null
                }
            ],
            "message": "Unsupported element '$[operation]'."
        }
    ],
    "networkError": null,
    "message": "GraphQL error: Unsupported element '$[operation]'.\nGraphQL error: Unsupported element '$[operation]'.",
    "stack": [
        "Error: GraphQL error: Unsupported element '$[operation]'.",
        "GraphQL error: Unsupported element '$[operation]'.",
        "    at new ApolloError (/var/task/node_modules/apollo-client/bundle.umd.js:85:32)",
        "    at Object.next (/var/task/node_modules/apollo-client/bundle.umd.js:890:37)",
        "    at notifySubscription (/var/task/node_modules/zen-observable/lib/Observable.js:135:18)",
        "    at onNotify (/var/task/node_modules/zen-observable/lib/Observable.js:179:3)",
        "    at SubscriptionObserver.next (/var/task/node_modules/zen-observable/lib/Observable.js:235:7)",
        "    at notifySubscription (/var/task/node_modules/zen-observable/lib/Observable.js:135:18)",
        "    at onNotify (/var/task/node_modules/zen-observable/lib/Observable.js:179:3)",
        "    at SubscriptionObserver.next (/var/task/node_modules/zen-observable/lib/Observable.js:235:7)",
        "    at notifySubscription (/var/task/node_modules/zen-observable/lib/Observable.js:135:18)",
        "    at onNotify (/var/task/node_modules/zen-observable/lib/Observable.js:179:3)"
    ]
}``` where the mutation is: 

```const { data } = (await client.mutate({
    mutation: gql(updateUserVote),
    variables: {
      id: "example",
     vote: Vote.Good
     },
  })) as ApolloQueryResult<UpdateUserVoteMutation>;``` which is from a lambda function using the Appsync client.

This issue started with transformer v2. and my cli.json:

```{
  "version": 1,
  "serviceConfiguration": {
    "serviceName": "AppSync",
    "defaultAuthType": {
      "mode": "AWS_IAM"
    },
    "additionalAuthTypes": [
      {
        "mode": "AMAZON_COGNITO_USER_POOLS",
        "cognitoUserPoolId": "authdefc1b0c"
      }
    ],
    "conflictResolution": {},
    "apiName": "ciri",
    "gqlSchemaPath": "/Users/andy/Coding/web/projects/amplifyapp/amplify/backend/api/votegql/schema.graphql"
  }
}```

**Comment by rafaelfaria** [comment] 2021-12-19 10:49
I'm having the same problem. Out of a sudden, my mutations does not work anymore with Cognito. 
please. I wonder if there is anything to do with the cli.

**Comment by AndyW22** [comment] 2021-12-19 11:06
I think I was able to fix my issue,  this is what I did:

-  upgrade amplify CLI to 7.6.4
- `amplify remove auth`
- `amplify add auth` (with a different name)
- `amplify update api`, select same options which will update the cognito pool it uses.
- `amplify push`

I think the issue is related to using authentication made before 7.x with the new transformer.

**Comment by marcvberg** [comment] 2021-12-20 21:50
Hi @AndyW22,

Could you provide your GraphQL schema from before it's compiled by the CLI?

Specifically I'm looking for usage of `@auth` and other directives in our transformer

If you could also provide the `amplify/cli.json` file (not `cli-input.json`) just so we can see which feature flags you have enabled/disabled

Thank you

**Comment by rafaelfaria** [comment] 2021-12-21 21:34
@marcvberg 

While we wait for Andy, I am having the same problems.

I tried to downgrade to version 7.5.0 which worked initially, but now, it just started to failed again, same error. Not sure what could be happening.

Here is my schema.

```
enum TransactionState {
  SUCCESS
  FAILED
}

type Transactions @model
  @auth(
    rules: [
      { allow: owner }
    ]
  )
{
  id: ID!
  fromTokenName: String!
  fromTokenAmount: Float!
  toTokenName: String!
  toTokenAmount: Float
  toTokenPriceUSD: Float
  date: String!
  fee: Float
  feePercentage: Float
  tx: String
  totalUSD: Float
  state: TransactionState!
}

enum UserStatus {
  ACTIVE
  INACTIVE
  BANNED
}


type UserSettings @model (subscriptions:null)
  @auth(
    rules: [
      { allow: owner }
    ]
  )
{
  username: String! @primaryKey
  walletAddress: String!
  maxPricePerToken: Float!
  currencyToken: String!,
  currencyAmount: Float!
  slippage: Float!
  gasPrice: Float!
  gasLimit: Int!
  liquidityMinAdded: Float!
  skipLiquidityCheck: Boolean
  referredBy: String
  status: UserStatus!
  privateKey: String # Bit of a hack adding this here so we don't need to mess around with the type in the rest of the code. However, the private key is not really stored here. :)
}


########################################################################################################################
# CUSTOM OPERATIONS
########################################################################################################################
input UpgradeUserTierInput {
  groupName: String!
}

type UpgradeUserTierResult {
  success: Boolean
}

input SavePrivateKeyInput {
  privateKey: String!
}

type Query {
  getPrivateKey: String
    @function(name: "getPrivateKey-${env}")
}

type Mutation {
  upgradeUserTier(input: UpgradeUserTierInput!): UpgradeUserTierResult!
    @function(name: "upgradeUserTier-${env}")
  savePrivateKey(input: SavePrivateKeyInput!): String
    @function(name: "savePrivateKey-${env}")
}
```

`UserSettings` and `Transactions` are failing.


I noticed the resolvers doesn't check for owners anymore, and weird resolvers that i haven't seen before started to appear `Query.getUserSettings.postAuth.1.req.vtl`, `Query.getUserSettings.preAuth.1.req.vtl` which I am assuming it's from the new resolvers? 

and here is my cli.json

```
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "improvepluralization": false,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": true,
      "enableiterativegsiupdates": true,
      "secondarykeyasgsi": true,
      "skipoverridemutationinputtypes": true,
      "transformerversion": 2,
      "suppressschemamigrationprompt": true
    },
    "frontend-ios": {
      "enablexcodeintegration": true
    },
    "auth": {
      "enablecaseinsensitivity": true,
      "useinclusiveterminology": true,
      "breakcirculardependency": true,
      "forcealiasattributes": false,
      "useenabledmfas": true
    },
    "codegen": {
      "useappsyncmodelgenplugin": true,
      "usedocsgeneratorplugin": true,
      "usetypesgeneratorplugin": true,
      "cleangeneratedmodelsdirectory": true,
      "retaincasestyle": true,
      "addtimestampfields": true,
      "handlelistnullabilitytransparently": true,
      "emitauthprovider": true,
      "generateindexrules": true,
      "enabledartnullsafety": true
    },
    "appsync": {
      "generategraphqlpermissions": true
    },
    "latestregionsupport": {
      "pinpoint": 1,
      "translate": 1,
      "transcribe": 1,
      "rekognition": 1,
      "textract": 1,
      "comprehend": 1
    },
    "project": {
      "overrides": true
    }
  }
}
```

Also, What is the cli version before the updates for the new transformer?

**Comment by AndyW22** [comment] 2021-12-21 22:26
> Hi @AndyW22,
> 
> Could you provide your GraphQL schema from before it's compiled by the CLI?
> 
> Specifically I'm looking for usage of `@auth` and other directives in our transformer
> 
> If you could also provide the `amplify/cli.json` file (not `cli-input.json`) just so we can see which feature flags you have enabled/disabled
> 
> Thank you

did you mean to tag @pptavozl ? The schema i posted was made before compiled by the CLI. 

my amplify/cli.json:
```
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": true,
      "enableiterativegsiupdates": true,
      "secondarykeyasgsi": true,
      "skipoverridemutationinputtypes": true,
      "transformerversion": 2,
      "suppressschemamigrationprompt": true
    },
    "frontend-ios": {
      "enablexcodeintegration": true
    },
    "auth": {
      "enablecaseinsensitivity": true
    },
    "codegen": {
      "useappsyncmodelgenplugin": true,
      "usedocsgeneratorplugin": true,
      "usetypesgeneratorplugin": true,
      "cleangeneratedmodelsdirectory": true,
      "retaincasestyle": true
    },
    "appsync": {
      "generategraphqlpermissions": true
    },
    "project": {
      "overrides": true
    }
  }
}
```

**Comment by sachscode** [comment] 2022-01-21 19:58
@pptavozl 
Could you please provide your GraphQL Schema, we would like to inspect the auth specific directives

**Comment by cjihrig** [comment] 2022-02-01 19:10
Closing due to a lack of followup, but we can revisit this issue if needed.

**Closed by cjihrig** 2022-02-01 19:10 UTC
Labels: graphql-transformer, pending-response

**Comment by Rhys-Yakkr** [comment] 2022-02-02 14:33
Also having the same issue as above.
Removing field level authorisation stopped an auth denied error, even when that was not the field being mutated, but instead failed with this error.
