### ISSUE TITLE
Multi auth for single api not working with Datastore

### ISSUE THREAD

**Issue by apoorvmote** [aws-amplify/amplify-cli#3683] opened 2020-03-17 05:50 UTC
**Describe the bug**
If I add auth `{allow: private, provider: iam}` then I get following error 

`[WARN] 50:18.733 DataStore - Sync error subscription failed Connection failed: {"errors":[{"message":"Validation error of type MissingFieldArgument: Missing field argument owner @ 'onCreateProduct'"}]}`

**To Reproduce**

1. `npx create-react-app store --use-npm --template typescript`
1. `amplify init`
1. `amplify add auth` default configuration
1. `amplify add api`
add following schema
```
type Product @model
  @auth(rules: [
    {allow: owner},
    {allow: private, provider: iam}
  ]) {
  id: ID!
  owner: String!
  name: String!
}
```
After this I cannot save new product to cloud I cannot list products from the cloud.

if I remove `{allow: private, provider:iam}` and push to cloud then I get following error

`[WARN] 08:40.931 DataStore - Sync error subscription failed Connection failed: {"errors":[{"errorType":"UnauthorizedException","message":"Permission denied"}]}`

If I create fresh project with following schema then it works
```
type Product @model
  @auth(rules: [  {allow: owner}  ]) {
  id: ID!
  owner: String!
  name: String!
}
```
Above schema works if created fresh. 

Alternatively I tried adding api key with congnito auth as default api auth. I get similar error.
`amplify update api` add additional auth and select api key.

If I remove auth entirely then it works perfectly.
```
type Product @model
  @auth(rules: [
    {allow: public},
    {allow: public, provider: iam}
  ]) {
  id: ID!
  name: String!
}
```
I get API key and I can update using lambda with API key or AWS_IAM and locally on browser with api key.

**Expected behavior**
Multi auth should work with datastore. So I can update records using browser or using dynamodb streams.

OS Ubuntu 18.04
Node v12.16.1
Amplify cli v4.16.1

**Comment by kaustavghosh06** [comment] 2020-03-17 16:23
@apoorvmote What was your flow for `amplify add api`? Did go into the "Additional settings" flow and choose to enable "Sync" settings?

**Comment by apoorvmote** [comment] 2020-03-18 02:22
@kaustavghosh06 yes I did. I changed 2 things. 
1. Added addtional auth and selected IAM for api
1. And changed the conflict resolution to optimized concurrency.

My guess is graphql transform is not working properly. 

It's working without multi auth as mentioned earlier
>If I create fresh project with following schema then it works
>
> `type Product @model
>  @auth(rules: [  {allow: owner}  ]) {
>  id: ID!
>  owner: String!
>  name: String!
> }`
>
> Above schema works if created fresh.

Current workaround is to leave schema like above and update schema in appsync console and adding @aws_iam @aws_cognito_user_pools to required query, mutation and types. Then everything works. 

So its the graphql transform that is not working correctly.

**Comment by kaustavghosh06** [comment] 2020-04-24 22:54
@apoorvmote Were you able to get your API to work?

**Comment by apoorvmote** [comment] 2020-04-25 01:35
@kaustavghosh06 Like I said earlier
> Current workaround is to leave schema like above and update schema in appsync console and adding @aws_iam @aws_cognito_user_pools to required query, mutation and types. Then everything works.

The drawback is everytime I make changes to schema and push then I needed to manually go to appsync console and manually add auth rules.

Luckily my app requirements were changed. I no longer require `dynamodb streams`. Hence I no longer require to authenticate API with lambda function. So this is no longer need of mine.

**Comment by UnleashedMind** [comment] 2020-05-05 20:09
Closing the issue since you are not blocked anymore. 
Feel free to open a new issue or comment on this one if needed.

**Closed by UnleashedMind** 2020-05-05 20:09 UTC
Labels: DataStore, pending-triage

**Comment by meducati** [comment] 2020-08-10 08:33
I believe I have the same issue, but maybe the root cause is different?

When I compare a previous build (working) and my latest (permission issue), looking at the schema.js file generated by "amplify codegen models", I notice that the difference in these two files are blocks of:

` {
                                "allow": "private",
                                "provider": "iam",
                                "operations": [
                                    "create",
                                    "update",
                                    "delete",
                                    "read"
                                ]
                            }`

in the newer/not working one...

If I manually delete these "iam-blocks", the sync error disappears.

I have but way too much time into error-debugging this, so would be great if these things could be looked into. I am currently not blocked either, since I only use iam for my lambda-functions in the backend.
