### ISSUE TITLE
Github Actions support for CLI

### ISSUE THREAD

**Issue by ambientlight** [aws-amplify/amplify-cli#2828] opened 2019-11-25 11:36 UTC
minor plug here.

I had positive experience in deploying amplify with github actions so I decided to formalize it into step: [amplify-cli-action](https://github.com/marketplace/actions/amplify-cli-action).

Will be really happy if any feedback or suggestions

**Comment by attilah** [comment] 2019-11-27 16:26
@ambientlight nice!

Just to clarify, the issue is to seek feedback on the github action?

**Comment by ambientlight** [comment] 2019-11-27 16:53
@attilah: to get the word out, my assumption (was) that folks subscribed here might be the ones to find the integration useful, given the headless amplify is not so much out-of-the-box. will be extremely happy for any feedback

**Comment by RossWilliams** [comment] 2019-12-03 00:36
@ambientlight how have you found the deployment speed vs using Amplify's service?

**Comment by ambientlight** [comment] 2019-12-03 01:37
@RossWilliams: I haven’t used Amplify’s service, used bitrise before GitHub actions landed, Deployments are slow when CloudFormation populates/descales CloudFront, other then that it is reasonable

**Comment by yuth** [comment] 2020-01-30 18:20
Closing this as no action is needed from Amplify team.

**Closed by yuth** 2020-01-30 18:20 UTC
