### ISSUE TITLE
Switching ENVs does not clear #current-cloud-backend

### ISSUE THREAD

**Issue by tobinbc** [aws-amplify/amplify-cli#5305] opened 2020-09-10 21:05 UTC
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

When a table with a `@connection` exists with this key already deployed:

```gql
type A @key(name: "ByBIdCId", fields: ["BId", "CId"], queryField: "AByBIdCId") {
   B: String @connection
   BId: String
   C: String @connection
   CId: String
}
```

And I try to deploy this 

```gql
type A @key(name: "ByBIdCId", fields: ["BId", "CId"], queryField: "AByBIdCId")
            @key(name: "ByBId", fields: ["BId"], queryField: "AByBId") 
```
The CLI errors with `Attempting to mutate more than 1 global secondary index at the same time`

I can see in the `/build/stacks/<table>.json` that the GSIs have generated correctly in the Cloudformation.

**Amplify CLI Version**
4.28.2

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

**Expected behavior**
The key/index would deploy; using the console I can create the index OK.

**Screenshots**
CF Stack (truncated):
```json
"GlobalSecondaryIndexes": [
                    {
                        "IndexName": "ByB",
                        "KeySchema": [
                            {
                                "AttributeName": "BiD",
                                "KeyType": "HASH"
                            }
                        ],
                        "Projection": {
                            "ProjectionType": "ALL"
                        },
                        "ProvisionedThroughput": {
                          
                        }
                    },
                    {
                        "IndexName": "ByBC",
                        "KeySchema": [
                            {
                                "AttributeName": "BiD",
                                "KeyType": "HASH"
                            },
                            {
                                "AttributeName": "CiD",
                                "KeyType": "RANGE"
                            }
                        ],
                        "Projection": {
                            "ProjectionType": "ALL"
                        },
                        "ProvisionedThroughput": {
                           
                        }
                    },
                    {
                        "IndexName": "gsi-B",
                        "KeySchema": [
                            {
                                "AttributeName": "",
                                "KeyType": "HASH"
                            }
                        ],
                        "Projection": {
                            "ProjectionType": "ALL"
                        },
                        "ProvisionedThroughput": {
                            
                        }
                    },
                    {
                        "IndexName": "gsi-C",
                        "KeySchema": [
                            {
                                "AttributeName": "",
                                "KeyType": "HASH"
                            }
                        ],
                        "Projection": {
                            "ProjectionType": "ALL"
                        },
                        "ProvisionedThroughput": {
                           
                        }
                    },
                    {
                        "IndexName": "gsi-D",
                        "KeySchema": [
                            {
                                "AttributeName": "",
                                "KeyType": "HASH"
                            }
                        ],
                        "Projection": {
                            "ProjectionType": "ALL"
                        },
                        "ProvisionedThroughput": {
                            
                        }
                    }
                ]
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version. 12.13.1

I tried with 2 different tables and both yielded the same result, whether adding the Primary/Sort index key before or after the Primary index key.

**Comment by akshbhu** [comment] 2020-09-10 22:59
Hi @tobinbc 

While updating , you can only update or create or delete  1 GSI and its a dynamoDB limitation. https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html#limits-secondary-indexes
Based on your schema you are deleting 1 GSI and adding 2 new GSIs. Try deleting first and add one at a time.

**Comment by tobinbc** [comment] 2020-09-11 06:32
Hi @akshbhu 

Apologies I made a typo in the post (have updated).

I have 4 GSIs currently deployed on the table. When I `amplify push` with the added index I can see the template `<table>.json` generates with 5 GSIs - 4 of those identical to the current deployment (what the template has when I `amplify push` without the 5th GSI). By that count, I am only creating 1 GSI.

If I push a brand new environment with the 5 GSIs, it has a different error :
```
Attempting to edit the global secondary index ByBId on the ATable table in the A stack.
```
Many thanks,
Tobin

**Comment by dsypniewski** [comment] 2020-10-01 08:53
If you are creating the new @key between other existing @keys this could be related to #5380 
If that's the case just add the key as the last one for given model instead of between and it should work.

**Comment by SwaySway** [comment] 2020-10-22 23:49
I tried to reproduce this and I noticed when adding a new env that the current-cloud-backend is still set to the previous env. In any case one fix here would be to clear the directory when switching env. This is something I can discuss with the team.

Marking as an enhancement.

**Comment by tobinbc** [comment] 2020-10-23 08:38
@SwaySway exactly this yes. I noticed that even when I had:
- Created a new env + checkout
- deleted the current-cloud-backend directory, 
- deleted the cloudformation stack, 
- deleted the deployment bucket,

 Amplify would still some how populate the #current-cloud-backend with that previous deployment (and then error as applicable).

**Comment by josefaidt** [comment] 2022-12-21 21:18
Closing as this issue has since been resolved. Upon checking out or creating an environment the files in `#current-cloud-backend` are updated to reflect the target environment.

**Closed by josefaidt** 2022-12-21 21:18 UTC
Labels: feature-request, platform
