### ISSUE TITLE
If both allow: group and allow: owner are set, Null is an error in real-time communication.

### ISSUE THREAD

**Issue by shichi18** [aws-amplify/amplify-cli#10245] opened 2022-04-19 15:51 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.3

### Amplify CLI Version

7.6.26

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth, api

### Amplify Commands

push

### Describe the bug

We are currently using group and owner authentication at the same time.

An account belongs to one or more groups.

If both `allow: owner` and `allow: group` are used, the subscription will be the following code.

``` js
this.apiService.OnUpdateRoomsListener(room.id).subscribe( 
        (res) => {
        console.log(res);
        },
        (e) => {
          console.log(e);
        },
        () => console.log('Room Done')
      );
    });
```
If you put null in the room id, you will get an error.
`"Connection failed: {"errors":[{"message":"Validation error of type UndefinedVariable: variable not found"}]}"`

I understand that this error occurs when using `allow: owner`.

However, I believe you can put null when using `allow: group`.
Is this a bug?

### Expected behavior

The following code does not cause an error when "allow: group" is present.
`"Connection failed: {"errors":[{"message":"Validation error of type UndefinedVariable: variable not found"}]}"`

``` js
this.apiService.OnUpdateRoomsListener().subscribe( 
        (res) => {
        console.log(res);
        },
        (e) => {
          console.log(e);
        },
        () => console.log('Room Done')
      );
    });
```

I think null should be allowed if accounts belong to  groups.

### Reproduction steps

set allow: owner and allow: group in GraphQL 

↓
this.apiService.OnUpdateListener();
this.apiService.OnCreateListener();
this.apiService.OnDeleteListener();

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Rooms @model
@auth(rules: [
  { allow: owner, ownerField: "id", operations: [create, update, read] }
  { allow: groups, groups: ["employee"] }
  { allow: public, provider: iam, operations: [create, update, read] }
]) {
  id: ID!
 data1: string
 data2:string
...
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ykethan** [comment] 2022-04-20 20:00
Hello @shichi18, Thank you for reaching. could you please provide us the implementation for the `OnUpdateRoomsListener`.
As normally when using the graphql API we normally pass in the query and variables attributes to the subscription call, having insight into the implementation can help us dive deeper into the issue.

**Comment by shichi18** [comment] 2022-04-28 06:59
@ykethan 
Thank you!
Sorry for being late to confirm.

I'm using Angular and I'm using the raw code that is automatically generated from the GraphQL schema.
(add only `@model`)
```js

  constructor(
    private apiService: APIService,
  ) {}

ngOnInit() {
const id = null;  // or room's id
this.apiService.OnUpdateRoomsListener(id).subscribe((res) => {});
// 1. id = null 
// "Connection failed: {"errors":[{"message":"Validation error of type UndefinedVariable: variable not found"}]}"

// 2. id = guest (Rooms id, not null)
// Success!
}

```
Is it a bug that "allow: owner" is prioritized even if null is entered when both "allow: owner" and "allow: groups" exist?

For the time being,
This solution could be solved using a custom subscription, but I was curious, so I opened Issue.
```
type Subscription {
  onUpdateCustomRooms: Rooms
    @aws_subscribe(mutations: ["updateRooms"])
    @auth(rules: [{ allow: groups, groups: ["employee"] }])
}
```

**Comment by ykethan** [comment] 2022-04-29 16:54
Hey @shichi18, thank you the information. From the use case provided I wanted to inform you on the hierarchy of authorization.
if the user is authorized by the group first, then they will not be authorized as an "owner". If you want to add the user to the record though as the owner when they are in the group, you'll have to manually add it to the input params.

Hope this helps.

**Comment by shichi18** [comment] 2022-05-03 14:14
@ykethan 
Thank you! Understood!
If it's not a bug or something, you can Close it.

**Comment by ykethan** [comment] 2022-05-03 18:50
For better tracking purposes into the behaviour, closing the issue here but the issue is currently being tracked at https://github.com/aws-amplify/amplify-cli/issues/10361.

**Closed by ykethan** 2022-05-03 18:50 UTC
Labels: pending-close-response-required, pending-triage, @auth
