### ISSUE TITLE
Timeout is unreasonable. I want to override

### ISSUE THREAD

**Issue by 24jr** [aws-amplify/amplify-cli#9815] opened 2022-02-20 19:22 UTC
### Describe the feature you'd like to request

Every schema change I do I have to hit are you sure you want to continue, which I do, however then after it starts I am revealed the big question of how long. So when says 1 of 15 you and I both know it will timeout at the hour mark. I am also fully happy with waiting say 5 hours for it to complete if thats what it takes. Now when it gets to 12 of 15 and times out that solves no issues for anyone...Now I have an 11 step rollback and then redo it again incrementally instead of 20 more mins of 3 more steps now its 5 hours of tinkering and waiting and probably causing. some other screwed up backend resources from all the half done things

### Describe the solution you'd like

Custom timeout setting and prob default at least 2 hours

### Describe alternatives you've considered

Incremental pushes to the best I can. When adding several types with their own connections its still a unsmooth process

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment] 2022-02-21 20:49
Hey @24jr :wave: what version of the CLI are you currently using and how large is your schema?

**Comment by 24jr** [comment] 2022-02-22 15:58
@josefaidt Newest version and 14 types and several index on those

**Comment by josefaidt** [comment] 2022-02-24 22:18
Hey @24jr would you mind sharing the logs of the failures from your terminal output and the log files (`~/.amplify/logs`) at the time it occurred? Also can you clarify what you're experiencing when saving a schema during a push? Earlier today I did notice if I saved a change while pushing, the API resource was not showing "UPDATE" on a subsequent `amplify status`

**Comment by josefaidt** [comment] 2022-04-07 18:32
Hey @24jr :wave: I wanted to follow-up on this and see if you were still experiencing the issue? If so, can you confirm the maximum amount of changed indexes on a single table? I'm curious about the 15 steps

> Now when it gets to 12 of 15

**Comment by undefobj** [comment] 2022-04-12 18:52
@24jr can you give us your schema for a reproduction (or a sample schema that demonstrates the issue) potentially with some index changes caused by schema updates? For example:
- schema with `@model` details of XYZ
- `time push`
- note how long deployment takes
- Make changes to the schema adding/removing things (which might cause index updates or something else)
- `time push`
- note how long deployment takes

**Comment by 24jr** [comment] 2022-04-12 20:42
@josefaidt  @undefobj  I have been side tracked from this for a while with other projects and now giving supabase a shot because I like simple but I know amplify pretty well and will likely stick with it. So I cant remember exacty what the full schema was but I wanted to abtsract data as best i could into klines and have indexes on many fields to query for what I desired and used keys as id combined with underline to allow for joint keys to be queried.

like btc_1h_5m_liquidations or something that i would just assemble on front end to use as query key. Again this has been out of my brain space for a little but I may have more insight if my supabase wave passes and jump back in again

```
type PeriodSubPeriodField
  @model(subscriptions: { level: off })
  @auth(
    rules: [
      { allow: public, operations: [read] }
      { allow: private, operations: [read] }
      { allow: groups, groups: ["admin"], operations: [read, create, update, delete] }
    ]
  ) {
  id: ID! 
  field_id: ID! @index(name: "byField", queryField: "listPeriodSubPeriodFieldsByField")
  period_id: ID! @index(name: "byPeriod", queryField: "listPeriodSubPeriodFieldsByPeriod")
  is_active: Int! @index(name: "byIsActive", queryField: "listPeriodSubPeriodFieldsByIsActive")
  sub_period_id: ID! @index(name: "bySubPeriod", sortKeyFields: ["is_active"], queryField: "listPeriodSubPeriodFieldsBySubPeriod")
  period_id_field_id: ID! @index(name: "byPeriodField", sortKeyFields: ["is_active"],  queryField: "listPeriodSubPeriodFieldsByPeriodField")
  period_sub_period_id: ID! @index(name: "byPeriodSubPeriod", sortKeyFields: ["is_active"],  queryField: "listPeriodSubPeriodFieldsByPeriodSubPeriod")
  field: Field @belongsTo(fields: ["field_id"])
  period_sub_period: PeriodSubPeriod @belongsTo(fields: ["period_sub_period_id"])
}
```

**Comment by undefobj** [comment] 2022-04-13 06:09
Thank you @24jr we're going to look into this more, however from a cursory glance at your schema my guess is due to the amount of indexes you are putting on all attributes you'll have some latency in your deployments due to the nature of the deployment process which must serialize each underlying GSI in DynamoDB. This is a constraint that is necessary for consistency of data on the backend. Do you need indexes to do this type of arbitrary queries on every attribute? This feels like it might be more of an analytics workload from your schema definition.

**Comment by 24jr** [comment] 2022-04-13 14:53
@undefobj Idk what all the implications are for optimization and longevity of the database with all the indexes. It seemed to me that combining all my data into one table since its mostly the same shape would be the simplest and best solution. So everything does get added into the same table rather than a ton of tables with diff coin or source names. And adding my own fields used as indexes with whatever combination of attributes seems like the best way to query the data fast for what I want without risk or having to call several times with filter and what not.

This is partly why I want to see what supabase is like. It seems more to the fundamentals. I personally dont care about datastore and pinpoint stuff like analytics, notifications, etc. I just want the fundamentals auth, data, storage, functions, hosting,emails, payments is probably all and I'm worried one day Ill run amplify push for a small change and an error will cause my entire backend to break beyond my knowledge of how to fix. 

I'm still learning about postgresql for supabase and all its pros and cons. I'm not some database engineer so I don't know if that one has weird table size limits or the "doesnt scale well" would affect me or its slow or has other qualms to be discovered. And i have to learn plpgsql to use well. 

I like sveltekit which I have working with amplify but required some figuring out as there arent docs or anything for that so it feels a bit like last thought with amplify and Idk how ssr is with all that and so forth whereas sveltekit feels very welcomed with supabase. Bottom line I like the fundamentals of Amplify but worry that with 8 million services being stitched together  something beyond my control will break and it just worries me wheres supabase/postgres feels like one unified, proven, secure, reliable service (but its incomplete thus far on some things also).

Also shoutout that focus otter guy that works with amplify he makes me want to stick with it with his youtube that enlightened me to sending emails with triggers on amplify. and I got templates working and now going to watch and figure out stripe. So both are appealing but I'm trying to make a smart future-proof choice. What was the question again? jk, I got a little sidetracked

**Comment by undefobj** [comment] 2022-04-13 23:10
Thanks good feedback. To refocus this on your schema above, putting indexes on every attribute is more in line with an analytical workload using a relational database or using the `@searchable` directive with Amplify. The underlying database in Amplify that you're using above is DynamoDB which is NoSQL and while it will function, that's not the optimal pattern which is where you're running into some of the tradeoffs such as friction in data modeling and deployment times. While we're looking at ways to improve this in the future, right now I would offer you the following guidance if you're looking to stay in the Amplify/DynamoDB-architecture:
1. Match up your use cases to the ones outlined in our [Data Modeling Guide](https://docs.amplify.aws/cli/graphql/data-modeling/). See if you can leverage other directives such as `@primaryKey(sortKeyFields: ["XYZ"])`

**Comment by 24jr** [comment] 2022-04-14 04:00
@undefobj I used searchable probably 4 years and recall it causing $30 a month bill to my aws account and at the time had no money so since then structured my schema to never use searchable. But perhaps my use case has elevated to the point where I should look into using it again and idk what it costs but if its $30ish a month I can manage. And then well I'll have to give the docs a good look over and test it out but I think this could be a good option. Thanks for suggesting this alternative

**Comment by josefaidt** [comment] 2022-04-14 18:11
Hey @24jr with the guidance above we are working with the appropriate teams to improve this experience, however if you feel the guidance is sufficient we can close this issue out for the time being 🙂

**Comment by 24jr** [comment] 2022-04-14 21:45
@josefaidt Ya that's fine. So in conclusion are you suggesting limiting the number of indexes for the entire schema or for one type. Is there a back of the hand ballpark as to what may be too many. I feel like I might not dive into searchable on account of cost although it may be feasible I'm not sure yet. And I missed todays office hours! oh well.  

And thanks for listening and communicating to help solve problem

**Closed** 2022-04-19 20:01 UTC
Labels: pending-close-response-required, pending-triage, api-graphql, platform-push
