### ISSUE TITLE
mock function does not work with nodejs optional chaining (?.) (new syntax from nodejs 14)

### ISSUE THREAD

**Issue by ktoyoda39** [aws-amplify/amplify-cli#7056] opened 2021-04-10 22:51 UTC
### Before opening, please confirm:

I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

curl -sL https://aws-amplify.github.io/amplify-cli/install | bash && $SHELL

### If applicable, what version of Node.js are you using?

v14.15.5

### Amplify CLI Version

4.47.1

### What operating system are you using?

Mac (intel)

### Amplify Categories

function

### Amplify Commands

Not applicable

### Describe the bug

in mock function(testing locally), if my code contains "optional chaining (?.)" which is a new syntax from nodejs version14, it raises a following error.
```
{
  stack: "Error: Could not load lambda handler function due to SyntaxError: Unexpected token '.'\n" +
    '    at loadHandler (/snapshot/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/execute.js:106:15)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)',
  message: "Could not load lambda handler function due to SyntaxError: Unexpected token '.'"
}
```

### Expected behavior

It should simply work without any errors.

### Reproduction steps

1. amplify function add   # nodejs
2. add "optional chaining (?.)" in index.js like : 
```
exports.handler = async (event) => {
    console.log(event?.data?.text);   // this should log "undefined"
```
3. amplify mock function $functionName

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

The same code can work after "amplify push", and execute it from Lambda's web console.

PS. I confirmed that "$FUNCTIONNAME-cloudformation-template.json" file contains "Resources.LambdaFunction.Runtime = nodejs14.x"

**Comment by cjihrig** [comment] 2021-04-10 23:09
I cannot reproduce this locally on Node 14, but can on earlier versions. I believe mock is just using whatever version of Node you're running locally. You can verify by logging `process.version` in your function.

**Comment by ktoyoda39** [comment] 2021-04-10 23:18
@cjihrig
Thanks a lot for your advice. 
As you mentioned, my `process.version` returns `v12.18.1` .
This should be the reason...
My simply `node -v` returns `v14.15.5`.    May I know how to switch Node version for my `amplify mock function` ?

**Comment by ktoyoda39** [comment] 2021-04-10 23:23
I did 
- "amplify uninstall"
- curl -sL https://aws-amplify.github.io/amplify-cli/install | bash && $SHELL

But my `process.version` still returns the old one `v12.18.1` .  (`node -v` returns `v14.15.5` though.)

**Comment by cjihrig** [comment] 2021-04-10 23:54
It sounds like a possible`$PATH` issue on your machine. I would try looking at `process.execPath` and `process.env.PATH` and see how they compare between your system Node and the Node executable being used in mock.

**Comment by ktoyoda39** [comment] 2021-04-11 00:19
The strange thing is that I don't have `v12.18.1` on my local machine.
I am using `nodebrew` locally.  my machine should have only v12.20.1 and v14.15.5 ...
```
> nodebrew ls
v12.20.1
v14.15.5
current: v14.15.5
```

`process.execPath` returns `/Users/myname/.amplify/bin/amplify`
`process.env.PATH` returns `undefined`

I checked `Users/myname/.amplify/bin/amplify`. It is `Mach-O 64-bit executable x86_64` and the size is 395MB. I guess this binary file contains not only amplify-cli but also `node v.12.18.1` ???

**Comment by cjihrig** [comment] 2021-04-11 00:57
Oh, you installed the packaged version of the CLI. That is bundled with a version of Node - in this case v12.18.1. AFAIK, there isn't a way to change the bundled Node version. As a workaround, if you install the CLI from npm (`npm install -g @aws-amplify/cli`), you should be able to use your local version of Node.

**Comment by ktoyoda39** [comment] 2021-04-11 00:57
I did this following workaround.
- amplify uninstall  # remove amplify-cli installed by `curl...` .
- npm install -g @aws-amplify/cli

Now, my `amplify mock function` can work as I expected.

I'm happy with this solution for now.

**Comment by cjihrig** [comment] 2021-04-11 01:01
Glad you're unblocked. I'll close this issue out.

**Closed by cjihrig** 2021-04-11 01:01 UTC

**Comment by ktoyoda39** [comment] 2021-04-11 01:02
@cjihrig 
Thanks a lot for your comment.
Somehow I reached the same solution you suggested.  
I hope the packaged version will have v14 instead of v12 someday. 
Anyway, Thank you very much.
