### ISSUE TITLE
There's an error initializing your environment

### ISSUE THREAD

**Issue by atef-abdellatif** [aws-amplify/amplify-cli#12809] opened 2023-06-15 18:53 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d365ce6y79hx7o

### AWS Region

us-east-1

### Amplify Hosting feature

Backend builds, Build settings

### Describe the bug

Build fails with error: There was an error initializing your environment. I'm fetching the repo from GitHub.
Project Identifier: fa62b31536a55f4721b023a1da51ce62
aws version: aws-cli/2.11.0 Python/3.11.2 Darwin/22.5.0 exe/x86_64 prompt/off

### Expected behavior

Successfully build and deployment.

### Reproduction steps

1- push code to repo on GitHub
2- Amplify automatically build the app 

### Log output

<details>

```
# Put your logs below this line


```

</details>
error: There was an error initializing your environment.
Project Identifier: fa62b31536a55f4721b023a1da51ce62

**Comment by ykethan** [comment] 2023-06-16 16:03
Hey @atef-abdellatif, 👋 thank you for reaching out. From the AppID and project Identifier provided, we were able to identify that this issue is currently caused by utilizing split GraphQL schemas under the schema folder. This behaviour is currently being tracked here: https://github.com/aws-amplify/amplify-category-api/issues/1074
Observed a PR to fix this here: https://github.com/aws-amplify/amplify-cli/pull/12701, the team should provide an update as soon as the fix gets released. 

Closing this issue to prevent any miscommunication between issues.

**Closed by ykethan** 2023-06-16 16:03 UTC
Labels: pending-triage, platform-push
