### ISSUE TITLE
Amplify 8+ deployments fail with circular dependency error

### ISSUE THREAD

**Issue by eettaa** [aws-amplify/amplify-cli#10943] opened 2022-08-26 20:02 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.18.1

### Amplify CLI Version

7.6.21 (that's the problem!)

### What operating system are you using?

Ubuntu locally, but also repro's in Amplify's hosting environment

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Lambdas are deployed into a VPC via "vpc config" updates in *-cloudformation-template.json. However, this is longstanding/has not previously had a bad interaction with amplify mock api or amplify push

### Amplify Categories

hosting

### Amplify Commands

push

### Describe the bug

Hi!
My prod app, deployed via amplify Hosting + CI/CD, has been fully blocked from updating to amplify >7.6.21 for over two months at this point.  This is starting to become an acute problem (for example, Node 12 deprecation will impact us unless I can update the CLI/redploy auth lambdas with newer node versions).

When I update the CLI to 8+ and run `amplify push`, I get circular dependency errors like:
```
2022-06-15T23:16:37.022Z [INFO]: UPDATE_FAILED               api<name>                  AWS::CloudFormation::Stack Wed Jun 15 2022 23:16:32 GMT+0000 (Coordinated Universal Time) Circular dependency between resources: [Table1, Table2, ..., ConnectionStack ]
```

... where "Table1, Table2, ..." is a list of every @model I have in my schema.

`amplify mock` also fails.

I immediately filed https://github.com/aws-amplify/amplify-category-api/issues/560 but cannot seem to attract any attention to it.  I am filing this bug just in case that one was miscategorized/somehow lost.

During the past two months I've consistently been searching these issue pages for related issues and have attempted some of my own debugging, all of which I have shared on https://github.com/aws-amplify/amplify-category-api/issues/560.

I do understand the amplify team is quite busy; if that bug is properly categorized and just waiting in line, I understand.  But in the off-chance something went wrong, maybe opening this ticket will help :)

I'm happy to contribute resources to resolving this in what ways I can, although I am not an expert in the CLI's implementation or AWS architecture as a whole.  If there are further diagnostics/tests I can run, or anything else I can do to facilitate resolution, I'm happy to do so.

Thank you!!

### Expected behavior

Updating to new versions of the CLI and deploying the project just works.

### Reproduction steps

Full notes in https://github.com/aws-amplify/amplify-category-api/issues/560

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment] 2022-09-08 18:48
Hey @eettaa :wave: thanks for raising this and apologies for the delay! It appears @AaronZyLee was able to find a temporary workaround to this issue. As such, closing as a duplicate of https://github.com/aws-amplify/amplify-category-api/issues/560, please see [this comment](https://github.com/aws-amplify/amplify-category-api/issues/560#issuecomment-1239913182) for a temporary workaround as the team continues to address these issues.

**Closed by josefaidt** 2022-09-08 18:48 UTC
Labels: pending-triage
