### ISSUE TITLE
"undefined is not iterable" error when doing amplify publish

### ISSUE THREAD

**Issue by Coteh** [aws-amplify/amplify-cli#6660] opened 2021-02-17 23:33 UTC
**Describe the bug**
Hi, I ran into the following error message that stopped our Amplify deployment via Jenkins.

**Amplify CLI Version**
4.37.1

**To Reproduce**
Run `amplify publish -y` with an existing stack.

**Expected behavior**
It publishes successfully

**Actual Behaviour**
```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

    at getUniqueStacksEvents (/Users/jenkins/.asdf/installs/nodejs/12.16.1/.npm/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:477:24)

    at /Users/jenkins/.asdf/installs/nodejs/12.16.1/.npm/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:129:30

    at runMicrotasks (<anonymous>)

    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Appears to be the same class of error as #5841.

**Desktop (please complete the following information):**

- OS: macOS 10.15.7
- Node Version: 12.16.1

**Other Notes**

I'm currently on 4.37.1 due to #6110. If you believe the latest version resolves this issue, I will update and try again.

**Comment by yuth** [comment] 2021-02-19 02:01
@Coteh does this happen consistently?

**Comment by Coteh** [comment] 2021-02-19 18:35
So far it's happened just once but I will report back next time our CI runs.

**Comment by yuth** [comment] 2021-02-22 19:52
I suspect this to be an intermittent error where the Cloudformation events were returned nothing. I am marking this as a enhancement to make the [code more robust](https://github.com/aws-amplify/amplify-cli/blob/a2c15774762c0f07b44ca9c91c57ef4eb3752f2b/packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js#L491-L494) to handle the case where the event are not passed.

**Comment by cjihrig** [comment] 2021-07-07 17:08
This should be fixed. Closing as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/7004.

**Closed by cjihrig** 2021-07-07 17:08 UTC
Labels: cloudformation, enhancement
