### ISSUE TITLE
Template error: instance of Fn::GetAtt references undefined resource $authname

### ISSUE THREAD

**Issue by hackrx** [aws-amplify/amplify-cli#9345] opened 2021-12-19 13:45 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

7.6.3

### What operating system are you using?

Mac

### Amplify Categories

auth

### Amplify Commands

push

### Describe the bug

`amplify remove auth` then `amplify add auth` results in : 

```
✖ An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: Template error: instance of Fn::GetAtt references undefined resource $authname
```
I request amplify team to fix this issue, I already faced this two times, and 3rd time, I decided to create an issue, this is really very frustrating 😞 .

Though the workaround of this issue is, first `remove auth`, then `amplify push `and then `amplify add auth`, but amplify push takes more than 20 minutes for me, I can't wait for 40 mins to update my auth 😢 .
🙏🏼  please fix it.

### Expected behavior

`amplify remove auth` then `amplify add auth` and `amplify push` should work and it should also delete the old auth, which was removed. 

### Reproduction steps

I already explained.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hackrx** [comment] 2021-12-19 14:02
now amplify pull is also not working: 
```
✔ Successfully pulled backend environment rtestapis from the cloud.
✖ There was an error initializing your environment.
auth headless is missing the following inputParams googleAppIdUserPool, googleAppSecretUserPool
Error: auth headless is missing the following inputParams googleAppIdUserPool, googleAppSecretUserPool
    at updateConfigOnEnvInit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/index.js:136:15)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/index.js:349:28
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by johnpc** [comment] 2022-01-14 21:53
Testing on 7.6.9, I am unable to reproduce your issue. Have you tried on the latest cli version? Is it still reproducible for you?

I am happy to see you at least have some workaround:

> the workaround of this issue is, first remove auth, then amplify push and then amplify add auth

though I realize that is time consuming and inconvenient. Does that also work around the second issue where `amplify pull` breaks?

Can you please share your auth configuration as well? In my attempt to reproduce, I used only the default Cognito configuration.

**Comment by cjihrig** [comment] 2022-02-01 19:11
Closing due to a lack of followup, but we can revisit this issue if needed.

**Closed by cjihrig** 2022-02-01 19:11 UTC
Labels: auth, pending-response

**Comment by kgoyal98** [comment] 2022-03-24 18:18
I am on version 7.6.26. Even the workaround is not working for me.

**Comment by kgoyal98** [comment] 2022-03-24 18:20
✖ An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: Template error: instance of Fn::GetAtt references undefined resource authtelebuff9420622e
⚠️ Review the Amplify CLI troubleshooting guide for potential next steps: https://docs.amplify.aws/cli/project/troubleshooting/

**Comment by jk171505** [comment] 2022-04-26 18:12
I have the same issue:
```
🛑 auth headless is missing the following inputParams facebookAppIdUserPool, facebookAppSecretUserPool, googleAppIdUserPool, googleAppSecretUserPool
Error: auth headless is missing the following inputParams facebookAppIdUserPool, facebookAppSecretUserPool, googleAppIdUserPool, googleAppSecretUserPool
                                 at updateConfigOnEnvInit (/snapshot/node_modules/@aws-amplify/amplify-category-auth/lib/provider-utils/awscloudformation/index.js:93:23)
                                 at /snapshot/node_modules/@aws-amplify/amplify-category-auth/lib/index.js:272:34
                                 at /snapshot/node_modules/promise-sequential/index.js:16:18
                                 at runMicrotasks (<anonymous>)
                                 at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
