### ISSUE TITLE
Storage parameters.json does not exist (issue from the backend build)

### ISSUE THREAD

**Issue by julienlaurent-migso** [aws-amplify/amplify-cli#10931] opened 2022-08-24 07:19 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.15.1

### Amplify CLI Version

v9.2.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual update

### Amplify Categories

storage

### Amplify Commands

add

### Describe the bug

In my amplify project i run 
**Amplify add storage**
![image](https://user-images.githubusercontent.com/79509459/186354953-5fcfb430-3ba1-4479-a81a-af4022ec7c89.png)

Once the storage in added localy i push my backend using **Amplify push**

One the backend is pushed i build/deploy my application from Amplify but i get this issue during the build backend :
![image](https://user-images.githubusercontent.com/79509459/186355430-d7c12f78-c1ff-419b-939f-95793877297d.png)

### Expected behavior

Want tobuild / deploy my application including storage resource created from amplify cli

### Reproduction steps

amplify add storage
amplify push
build app 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Project Identifier

Project Identifier: e729fe38a8479db15c640454220f0835

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

The Storage folder and the parameters.json file are in the amplify folder in my local :
![image](https://user-images.githubusercontent.com/79509459/186356173-2e75a550-14b3-4577-b7ba-138c9fc21c9b.png)

**Comment by josefaidt** [comment] 2022-08-24 14:43
Hey @julienlaurent-migso :wave: thanks for raising this! From the path in the stack trace, it appears the CLI is looking for `parameters.json` in the storage category's directory rather than the `build/` directory nested within. Can you confirm the CLI version used in Amplify Hosting matches the version used locally? I'm curious if the CLI version is pinned to an older version of the CLI that is not recognizing `cli-inputs.json` (instead of `parameters.json`, this changed a few major versions back)

**Comment by julienlaurent-migso** [comment] 2022-08-25 07:15
Hi  @josefaidt, Thank you for your answer.

Concerning the Amplify Hosting version : 
![image](https://user-images.githubusercontent.com/79509459/186599042-608090d6-63fe-497f-94b9-0d5c247ad7dd.png)

And locally:
![image](https://user-images.githubusercontent.com/79509459/186599124-f04f1d59-b904-4e20-b565-b1963a4efdbb.png)

How can i fix this issue ? Do i need to move the `parameters.json` to the storage folder (same position than `cli-inputs.json`)  inside S3 ? I tried to move it from my local and amplify push it again but it's not working.

**Comment by julienlaurent-migso** [comment] 2022-08-25 15:56
Hi @josefaidt,
I don't know why but i have launched again a build from another computer with the last Amplify/cli and now it's working..
![image](https://user-images.githubusercontent.com/79509459/186712870-3f8b6b8d-6790-4472-9350-168bb9208371.png)

**Comment by bentonmize** [comment] 2022-08-30 14:56
Hi @julienlaurent-migso, I'm having the same issue on 9.2.1 and was wondering what version you used to get the build working?  (In other words...what was the "last" amplify/cli version that worked for you)
Thanks!

**Comment by julienlaurent-migso** [comment] 2022-08-31 14:04
hi @bentonmize, the last version for me is related to 9.2.1
I can't explained how i have fixed this issue .. try to push again your backend (updating something). 
On my side i remember that i have worked from another computer / pulled my amplify backend / updated the graphql schema / pushed the new version of the backend and my amplify app was able to build again ..

**Comment by josefaidt** [comment] 2022-08-31 19:07
Hey @julienlaurent-migso apologies for the delay,

> I don't know why but i have launched an amplify push from another computer with the last Amplify/cli version and now the build is working..

Interesting! It appears an older version of the CLI was being used when the error originally occurred, however can you confirm whether your successful mitigation was from running `amplify push` manually or `git push` with the automated workflow?

**Comment by julienlaurent-migso** [comment] 2022-09-02 09:41
Hi @josefaidt, 
Yes i confirm it, see below my steps: 
- amplify upgrade (global)
- clone gitlab folder
- npm install
- amplify pull
- update graphql schema
- amplify push
- gitlab commit 
- Amplify build automatically with the CI/CD activated 
- Result: everything is working well

**Comment by josefaidt** [comment] 2022-09-09 17:04
Hey @julienlaurent-migso does the Amplify build with Amplify Hosting's CI/CD also build the backend (typically with `amplifyPush --simple`)? If so it appears the manual `amplify push` may have resolved something

**Comment by julienlaurent-migso** [comment] 2022-09-16 09:57
Hey @josefaidt, yes i am using this command
![image](https://user-images.githubusercontent.com/79509459/190613183-842012c4-cc50-4e32-a92d-99218c8b1c62.png)

**Comment by josefaidt** [comment] 2022-09-28 19:10
Hey @julienlaurent-migso apologies for the delay but I am glad to hear that you were able to resolve this with a manual `amplify push` execution. I'm tracking this issue along with a few others for CLI+Hosting-related issues and inconsistencies. Continuing to work on a reproduction to confirm whether the CLI is impacting the workflow here

**Comment by josefaidt** [comment] 2022-11-11 18:00
Hey @julienlaurent-migso I've added the `ops-deploy` label to help us track issues related to deployment safety, and given the issue is no longer being experienced and was not reproducible I will close this for the time being.

**Closed by josefaidt** 2022-11-11 18:00 UTC
Labels: storage, not-reproducible, ops-deploy

**Comment by projectforeveryoung** [comment] 2022-11-14 18:35
I am experiencing the same issue. Attempted mitigation steps above which didn't resolve the issue. 
I had working version deployed via CI/CD. Completed the following steps and can no longer build:

1. Updated to latest CLI ("amplify upgrade")
2. Removed previous auth ("amplify auth remove") 
3. Added new auth in order to change configs to use SSO ("amplify auth add")
4. Tested locally successfully
5. amplify push
6. git push
7. CI/CD triggered with build fail
`2022-11-14T06:16:50.802Z [WARNING]: ✖ There was an error initializing your environment.
2022-11-14T06:16:50.816Z [INFO]: 🛑 Failed to pull the backend.
2022-11-14T06:16:50.816Z [INFO]: File at path: '/codebuild/output/src159328036/src/xxxxxxxx-xxxxxxxxxxxx/amplify/backend/auth/xxxxxxxxxxxxxxxxxxxxcf7697d7/parameters.json' does not exist`

Add'l info:
amplify CLI version: 10.4.1
Local node version: v18.6.0
Amplify node version: v16.18.1

**Comment by nathankopp** [comment] 2023-01-10 16:58
I'm facing the same issue.  These kinds of unresolvable failures are making Amplify completely unusable.  I may have to move to another platform. :-(

**Comment by nathankopp** [comment] 2023-01-10 22:50
Update: This was resolved by adding the file "cli-inputs.json" into the commit.  The error message indicated it was missing "parameters.json", so it was not clear that the real missing file was "cli-inputs.json".  I think the error message needs to be improved.

But for anyone facing this issue, check to see if you need to commit a file named "cli-inputs.json".
