### ISSUE TITLE
Amplify CLI 5.3 creates cognito pool with username plus email alias, *not* email as user name

### ISSUE THREAD

**Issue by BruceWheaton** [aws-amplify/amplify-cli#8016] opened 2021-08-24 01:53 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### Amplify CLI Version

5.3.0

### What operating system are you using?

Windows

### Amplify Categories

auth

### Amplify Commands

add

### Describe the bug

When creating auth with amplify add auth, manual configuration, and picking email as user name, the cognito pool created has username and email as alias, therefore a username that is an email is not accepted

### Expected behavior

Selecting email as username should create a pool with email as the sign-in. cli 5.2.1 works this way

### Reproduction steps

amplify init
amplify add auth
follow manual steps (I added four user groups too)

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by attilah** [comment] 2021-08-24 20:11
Duplicate of #7666

**Closed by attilah** 2021-08-24 20:11 UTC
Labels: auth, duplicate
