### ISSUE TITLE
EACCES: permission denied

### ISSUE THREAD

**Issue by georgehuardtechserv** [aws-amplify/amplify-cli#11430] opened 2022-11-17 19:44 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v19.1.0

### Amplify CLI Version

10.5.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

None

### Amplify Categories

api

### Amplify Commands

add, status, update

### Describe the bug

Any command that I run using amplify gets me that error.

### Expected behavior

Add API

### Reproduction steps

I followed all the instructions stated in the [project setup](https://docs.amplify.aws/lib/project-setup/prereq/q/platform/ios/#option-2-follow-the-instructions).

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Project Identifier

f6bf5187c42df44ef6d33bde62aa7b26

### Log output

<details>

```
# Put your logs below this line
2022-11-17T18:44:23.484Z|info : amplify version core  
2022-11-17T19:19:50.348Z|info : amplify version core 

```

</details>

**Comment by josefaidt** [comment] 2022-11-17 20:52
Hey @georgehuardtechserv :wave: can you provide additional details on this issue to help us reproduce on our end? How was the Amplify CLI installed? Did a previous version of the CLI work for you?

**Comment by georgehuardtechserv** [comment] 2022-11-17 21:39
Hey @josefaidt thanks for the response. The CLI was installed with sudo npm install -g @aws-amplify/cli --unsafe-perm=true. This is the very first version of CLI I've ever installed.

**Comment by josefaidt** [comment] 2022-11-18 18:36
Hey @georgehuardtechserv :wave: can you try reinstalling without sudo? If you are running into issues installing global node packages please refer to this doc https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by josefaidt** [comment] 2022-11-29 17:51
Closing due to inactivity.

**Closed by josefaidt** 2022-11-29 17:51 UTC
Labels: installation, pending-response, pending-triage
