### ISSUE TITLE
Error updating auth to migrate resources to the latest amplify version

### ISSUE THREAD

**Issue by ZalgirisKaunas** [aws-amplify/amplify-cli#12784] opened 2023-06-13 15:02 UTC
### Amplify CLI Version

12.0.3

### Question

Couldn't push new API endpoint via cli because error:  "Auth triggers have been configured using an older version of the CLI and must be migrated before they can be deployed." 

I then tried to do auth update but after that I still couldn't push the code and was getting Error updating the Cognito trigger: The "path" argument must be of type string. Received undefined.

not sure what should I do next

**Comment by ykethan** [comment] 2023-06-13 15:42
Hey @ZalgirisKaunas, thank you for reaching out.The issue appears to have a similar message as https://github.com/aws-amplify/amplify-cli/issues/12433. 
Could you provide us some additional information on the version of Amplify CLI that was utilized before? 
Could you provide us some minimal steps that would assist us in reproducing this behaviour. Additionally, could you let us know the current `amplify status` output.

**Comment by ZalgirisKaunas** [comment] 2023-06-14 06:41
I pulled the restored environment so I continue where I left it without that new endpoint. but I still get � Auth triggers have been configured using an older version of the CLI and must be migrated before they can be deployed.  
Even when I do changes to resources that worked fine just a few days ago.

**Comment by ykethan** [comment] 2023-06-14 15:33
Hey @ZalgirisKaunas, It is currently not recommended to modify Amplify managed resources in the AWS console as this may cause a drift between the resource. Expected if the auth resource was imported into the project.

Could you try running `amplify update auth`, select `Walkthrough all the auth configurations` and run through the flow while keeping the previous changes such as the auth triggers previously added. Could you then run `amplify push --debug`  and let us know if the auth resource throws an error.

**Comment by thathypeapp** [comment] 2023-07-03 01:38
Hi having trouble with this also but don't quite understand the issue. Its been a while since I've touched my amplify app (2022). I tried to make some changes today but I'm running into an issue where the CLI says I have to upgrade the auth. When I try to update it, it removes a bunch of files and then on amplify push, I get this error in my stack. `Existing schema attributes cannot be modified or deleted. (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: InvalidParameterException; Request ID: null; Proxy: null)`

**Comment by MohamedDarwiche-DaherSoftware** [comment] 2023-07-26 15:12
hello
I have the same issue, I had Amplify CLI version 7.6.15 with node version of 12

I upgraded to node 16, but I had errors while pushing regarding the function UpdateRolesWithIDPFunction because the node version was persistent on 12.

so I read in on the related issues that I need to upgrade my amplify cli (to have a higher node version of UpdateRolesWithIDPFunction), therefore I updated amplify cli to 12.2.1
then, when running `amplify push`, I got the following error "Auth triggers have been configured using an older version of the CLI and must be migrated before they can be deployed" 

I ran `amplify auth update`, and went through "Walkthrough all the auth configurations" and "Apply default configuration with Social Provider (Federation)" options, and for both them, after finishing the steps I'm getting the following error "Error updating the Cognito trigger: The "path" argument must be of type string. Received undefined"

**Comment by MohamedDarwiche-DaherSoftware** [comment] 2023-07-28 10:37
And when pushing to the cloud I get this error as well `Existing schema attributes cannot be modified or deleted. (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: InvalidParameterException;`

**Comment by josefaidt** [comment] 2023-09-11 22:46
Hey @g33kracc00n @thathypeapp please be sure to port modifications to user attributes (i.e. custom attributes) by using [`auth overrides`](https://docs.amplify.aws/cli/auth/override/#customize-amplify-generated-cognito-auth-resources) after migrating the resource with `amplify update auth`

**Comment by josefaidt** [comment] 2023-10-02 17:36
Hey @g33kracc00n @thathypeapp just wanted to follow-up here and see if you're still experiencing this?

**Comment by g33kracc00n** [comment] 2023-10-19 10:38
@josefaidt Hey, I tried the `auth overrides` but it didn't work I had to create new environment and migrate everything manually

**Comment by ykethan** [comment] 2023-11-07 17:31
thank you for the confirmation, glad to hear that you were able to mitigate the issue.  
Closing the GitHub issue. Please feel free in reaching out to us again.

**Closed by ykethan** 2023-11-07 17:31 UTC
Labels: question, auth, migration-issue, pending-triage
