### ISSUE TITLE
Typescript Build Options not being invoked

### ISSUE THREAD

**Issue by bruceharrison1984** [aws-amplify/amplify-cli#12128] opened 2023-02-28 15:32 UTC
### How did you install the Amplify CLI?

nap

### If applicable, what version of Node.js are you using?

16

### Amplify CLI Version

10.8.0

### What operating system are you using?

Windows 11

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Switched the boilerplate JS functions to TS, and added an tsconfig.json

### Describe the bug

I added a [build option](https://docs.amplify.aws/cli/function/build-options/) entry to main root package.json, but it is not invoked prior to `amplify push` actually deploying the changes. Since I am using TS, this means the deployed package doesn't contain any JS, thus it doesn't work.

```js
//root package.json (exerpt)

  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview",
    "amplify:graphqllambdaauthorizerab789ab7": "cd amplify/backend/function/graphQlLambdaAuthorizerab789ab7/src && npm i && swc ./index.ts -o index.js",
    "amplify:createawsaccount": "echo 'TEST' && cd amplify/backend/function/CreateAwsAccount/src && npm i && swc ./index.ts -o index.js"
  },
```

```js
//tsconfig in amplify/backend/function
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "lib": ["dom", "esnext"],
    "module": "commonjs",
    "moduleResolution": "node",
    "skipLibCheck": true,
    "resolveJsonModule": true
  },
  "include": ["**/*"]
}
```

The lambdas reside in the typical `function` directory, and they are the standard ones created via the CLI, transposed into TS. I don't get any messages regarding  the build options executing. In the `amplify:createawsaccount` script, I added an echo but it never fires AFAIK. 

It also seems that `npm install` is not run prior to deployment either. `node_modules` is emptied upon first running `amplify push` but `node_modules` remains empty unless I manually run `npm i` in the function directory. So the first paragraph from the Build Options docs doesn't make sense to me based on that.

> In some cases, it might be necessary to execute a script before a function is deployed, e.g. to transpile Typescript or ES6 with Babel or with tsc into a format that is supported by the AWS Lambda's node runtime. amplify push will look for a script definition in the project root's package.json with the name amplify:<resource_name> and run it right after npm install is canned in the function resource's src directory.

Just looking for guidance, since it looks like this feature does work.

### Expected behavior

I expect the Build Option command to be invoked before the lambda is deployed.

### Reproduction steps

- Create a new function via `amplify add function`
- Add tsconfig.json
- add build option to root `package.json`
- Convert boilerplate JS index.js to TS
- run `amplify push`

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment] 2023-02-28 16:47
Hey @bruceharrison1984 :wave: thanks for raising this! I was not able to reproduce this using the provided steps. Using the following root `package.json` I'm able to see a text file get created when I run `amplify push`

```json
{
  "scripts": {
    "amplify:myfunction": "echo 'hello my function build' > amplify/backend/function/myfunction/src/hello.txt"
  }
}
```

```
➜  tree -a amplify/backend/function/myfunction/src
amplify/backend/function/myfunction/src
├── event.json
├── hello.txt
├── index.js
├── node_modules
│   └── .yarn-integrity
├── package.json
└── yarn.lock

1 directory, 6 files
```

Moving this over to TypeScript I am also seeing this executed:

root package.json
```json
{
  "scripts": {
    "amplify:myfunction": "cd ./amplify/backend/function/myfunction/src && npm install && npm run build && cd -"
  }
}
```

function package.json
```json
{
  "name": "myfunction",
  "version": "2.0.0",
  "description": "Lambda function generated by Amplify",
  "main": "index.js",
  "license": "Apache-2.0",
  "scripts": {
    "build": "tsc"
  },
  "devDependencies": {
    "@types/aws-lambda": "^8.10.92",
    "typescript": "^4.9.5"
  }
}
```

function tsconfig.json
```json
//tsconfig in amplify/backend/function
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "lib": ["dom", "esnext"],
    "module": "commonjs",
    "moduleResolution": "node",
    "skipLibCheck": true,
    "resolveJsonModule": true
  },
  "include": ["./**/*.ts"]
}
```

Can you try changing your build script to execute `swc` with npx? This way it will execute `swc` under the context of your function rather than the project root

```json
"amplify:graphqllambdaauthorizerab789ab7": "cd amplify/backend/function/graphQlLambdaAuthorizerab789ab7/src && npm i && npx swc ./index.ts -o index.js"
```

Or move the build script to the `build` of your function's `package.json`?

```
"amplify:graphqllambdaauthorizerab789ab7": "cd amplify/backend/function/graphQlLambdaAuthorizerab789ab7/src && npm i && npm run build"
```

```json
{
	"scripts": {
		"build": "swc ./index.ts -o index.js"
	}
}
```

**Comment by bruceharrison1984** [comment] 2023-02-28 16:51
@josefaidt Thanks for the fast response! I played with this a bit more, and I think the cause of my woes was the casing of the `amplify:<function>` command. I was unsure if the `function` name was the one in package.json, or the one contained in `backend-config.json`.

It worked after I changed the command as follows:
```
"amplify:createawsaccount": "cd amplify/backend/function/CreateAwsAccount/src && tsc",
to
"amplify:CreateAwsAccount": "cd amplify/backend/function/CreateAwsAccount/src && tsc",
```

So user error. It might be helpful to expand the docs on Build Options a bit to capture implicit rules like this that aren't immediately obvious.

Again, thanks for the fast reply!

**Comment by josefaidt** [comment] 2023-02-28 19:25
Hey @bruceharrison1984 glad to hear you got it resolved, and yes that npm script will rely on the function name from the backend-config.json/function directory name. I agree with you in that this build process could be improved to surface any errors and output the build execution. 

I'll use this issue as a point of reference as we look to improve this experience, but for now I will close this issue.

**Closed by josefaidt** 2023-02-28 19:25 UTC
Labels: functions, pending-triage, not-reproducible
