### ISSUE TITLE
"`.config\local-env-info.json` does not exist" after exiting `amplify pull` flow early in subsequent pull attempts

### ISSUE THREAD

**Issue by kkbava** [aws-amplify/amplify-cli#11245] opened 2022-10-23 01:54 UTC
when I issued the command 
amplify pull --appId d2zn7182wew3qb --envName staging
I received the error 

🛑 File at path: 'C:\KK\code\amplify\Oct22\amplify\.config\local-env-info.json' does not exist

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

-----------------

Windows 11
Visual Studio Code (Sep22 update)
Was trying to follow instructions from a recent AWS Innovate video at https://innovate-modernapps-apj.virtual.awsevents.com/media/Build%20full-stack%20web%20applications%20using%20AWS%20Amplify%20Studio/1_bwol1fdj 

amplify --version says 10.3.1 (Noticed that this issue was first reported in 2020, but closed in May 2021. If it is resurfacing, it could probably be my environment?)

**Comment by ykethan** [comment] 2022-11-08 17:33
Hey @kkbava, following up on this issue. Do let us know if the issue is mitigated.

**Comment by kkbava** [comment] 2022-11-09 01:23
I didnt try after the day of failures!
Thanks for the suggestions - can only try on friday evening / saturday
morning IST and will sure let you know if any of these help
Plan to start the entire exercise from a clean folder - will sure verify
that all components/ libraries are updated

If it fails again, will send screenshot of the error

regards,
kk

**Comment by josefaidt** [comment] 2022-11-14 21:53
Hey @kkbava thanks for the clarification. We are going to close this issue for now however if the issue persists please reply back to this thread and we can re-open to investigate further

**Comment by kkbava** [comment] 2022-11-15 01:29
Thanks Josef!
I'm sure it is an environment issue on my side - hope I can crack it

**Comment by sarv-fuse** [comment] 2022-11-23 10:25
Facing same issue,
![Screenshot 2022-11-23 at 10 18 07](https://user-images.githubusercontent.com/69785042/203523344-376dd29d-37e7-4e8a-a593-5bfd21cc1950.png)

**Comment by cwoolum** [comment] 2022-12-21 21:51
@josefaidt , I just ran into this issue and am able to reproduce it. If you create a new Amplify App and then run pull, cancel after selecting the language. Now I repeatedly get the error, `File at path: 'C:\{some path}\amplify\.config\local-env-info.json' does not exist` when I try to pull.

Diagnose seems to be broken as well. When I try to run `amplify diagnose --send-report`, I get the error 

```
File at path: 'C:\{some path}\amplify\backend\backend-config.json' does not exist
× Creating Zip
```

One last thing, on the language selector, it won't let me select JavaScript until I switch to one of the other menu options and then go back.

**Comment by josefaidt** [comment] 2022-12-22 00:40
Hey @cwoolum thanks for bringing this to my attention! I was able to reproduce this by exiting the `amplify pull` flow after selecting the language. It appears that although the CLI pulled to relevant project's backend resources and metadata, `amplify/.config` remained empty. Here it would be helpful if the CLI were to recognize the incomplete project state and prompt to fix/continue:

```
➜  amplify pull
🛑 File at path: '/Users/josef/Documents/projects/aws-amplify/reproductions/pulltest/amplify/.config/local-env-info.json' does not exist

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: 5c2f448f-8fb2-44ea-af42-892cfa575f25
✖ An unexpected error has occurred, opt in to send an error report to AWS Amplify with non-sensitive project configuration files. Confirm  (y/N) ·
```

suggestion:

```
➜  amplify pull
An Amplify project exists in this directory but is not initialized. Would you like to initialize it? (Y/n)
```

To workaround this issue, simply delete the `amplify/` directory and reattempt `amplify pull`

**Comment by josefaidt** [comment] 2022-12-22 20:39
related https://github.com/aws-amplify/amplify-cli/issues/2545

**Comment by salman-plateron** [comment] 2023-04-06 09:19
TakeAway_web/amplify/.config/project-config.json' does not exist

**Closed** 2023-05-12 17:36 UTC
Labels: bug, platform-pull, p2
