### ISSUE TITLE
Graphql transformer to generate SEARCH filters for nested type objects

### ISSUE THREAD

**Issue by tgjorgoski** [aws-amplify/amplify-cli#3539] opened 2020-02-29 08:53 UTC
If you have schema like this, the autogenerated elasticsearch filters don't include possibility to search on base of the nested data: 
```
type Todo @searchable {
 id: ID!
 description: RichText
}

type RichText {
  content: String
  plaintext: String
}
```
The use case here is that I'm populating a plaintext field with the text-only data of the rich text, as the rich text content data is not quite appropriate for indexing and searching.
Of course you can currently store the content and plaintext fields both at the Todo level, however it would be much more elegant if they can be isolated in their own type.

Note: Issue https://github.com/aws-amplify/amplify-cli/issues/2055  is similar but it is for DynamoDB queries which based on the comments are impossible. The comments there hint that it could be possible to implement in Elasticsearch.

**Comment by vkumarvs** [comment] 2020-04-10 10:56
@SwaySway  I am also looking for the similar solution.

My previous post was this: 
https://github.com/aws-amplify/amplify-cli/issues/2055

**Comment by ashish369in** [comment] 2020-06-11 04:17
it would be great to have @searchable working with nested fields

**Comment by SwaySway** [comment] 2020-06-11 17:17
Closing as a duplicate of #2055

**Closed by SwaySway** 2020-06-11 17:17 UTC
Labels: enhancement, graphql-transformer
