### ISSUE TITLE
Local Front end changes are not detected by publish

### ISSUE THREAD

**Issue by sravimohan** [aws-amplify/amplify-cli#416] opened 2018-11-08 19:47 UTC
**Describe the bug**
I have a react project deployed and is working as expected.  Now I make some front end changes and issue "amplify publish".  But the Hosting operations is showing "No Change" and my s3 bucktet is not being updated with my changes. Am I missing any steps to republish my updates to the frontend?

**To Reproduce**
1. Create and publish a react project.
2. Make some front end changes and publish again.
3. Check you website to see if the changes have been pushed.
4. The s3 bucket is not updated.

**Expected behavior**
The front end s3 bucket will be updated with all my local changes when the publish is issued again.

**Desktop (please complete the following information):**
 - OS: OSX

**Comment by kaustavghosh06** [comment] 2018-11-08 19:54
@sravimohan  Can you paste your terminal output here? 
The no change is for the S3/Cloudfornt configuration changes. When you do an `amplify publish` it should build your frontend and upload it to your S3 bucket. Are you sure you're running `amplify publish` and not `amplify push`?

**Comment by sravimohan** [comment] 2018-11-08 20:52
Hi @kaustavghosh06.  I tried both and they both say no change.
When I make make a react JS file change and issue amplify status, What should it say?  When I do that it's saying no change.

amplify --version
0.1.32

**Comment by kaustavghosh06** [comment] 2018-11-08 20:53
@sravimohan Since you're not making any changes to the S3 configurations or Cloudfront configurations, it will say "No change", but all your frontend-related files - static assets would still be uploaded to your S3 bucket.

**Comment by sravimohan** [comment] 2018-11-08 21:08
ok.  It's definitely not updating the bucket.  I also confirmed the local build folder does have the updates.

 amplify publish
| Category | Resource name   | Operation | Provider plugin   |
| -------- | --------------- | --------- | ----------------- |
| Hosting  | S3AndCloudFront | No Change | awscloudformation |
| Auth     | cognito17c58765 | No Change | awscloudformation |
| Api      | 3pt             | No Change | awscloudformation |
? Are you sure you want to continue? true
✔ All resources are updated in the cloud

> 3pt@0.1.0 build /Users/xxx
> react-scripts build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  386.41 KB (+101 B)  build/static/js/1.a85e644f.chunk.js
  6.2 KB (+77 B)      build/static/js/main.8b4bb82e.chunk.js
  2.94 KB             build/static/css/1.7d002bd3.chunk.css
  763 B               build/static/js/runtime~main.229c360f.js
  276 B               build/static/css/main.20ae146b.chunk.css

The project was built assuming it is hosted at the server root.
You can control this with the homepage field in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  http://bit.ly/CRA-deploy

frontend build command exited with code 0
✔ Uploading files successful.
Your app is published successfully.
http://xxxx--hostingbucket.s3-website-ap-southeast-2.amazonaws.com

**Comment by gmarab** [comment] 2018-11-12 12:05
I have the same problem in Windows with a project in Angular 7.
The problem is with the version @aws-amplify/cli@0.1.33.
With the version @aws-amplify/cli@0.1.32 everything works correctly.

**Comment by UnleashedMind** [comment] 2018-11-15 01:05
@gmarab 
for Angular version 6 and above, follow this steps: 
- Please check the angular.json file, and get the value at `project.<your-project-package-name>.architect.build.options.outputPath`
- run `amplify configure project`, and set the above value when prompted "Distribution Directory Path"

**Comment by UnleashedMind** [comment] 2018-11-15 01:12
@sravimohan 
 run `amplify configure project`, make sure the build command and the distribution folder are correctly set. 
Seems like the build command is correctly set, and it's carried out successfully, so make sure the cli knows what folder to upload to the hosting S3 bucket by setting the `Distribution Directory Path` correctly.

**Comment by MiMo42** [comment] 2018-12-11 19:53
+1 
@aws-amplify/cli@0.1.33
react
macOS

**Comment by kaustavghosh06** [comment] 2018-12-26 21:21
@MiMo42  @gmarab The issue should be fixed with the latest version of the CLI. Please feel free to re-open if the issue still persists.

**Closed by kaustavghosh06** 2018-12-26 21:21 UTC
Labels: investigating

**Comment by jpknapp3** [comment] 2019-01-01 23:35
This is still an issue for me. I'm on macOS 10.13.6 and I followed the tutorial here https://aws-amplify.github.io/docs/js/start?ref=amplify-js-btn&platform=purejs. Everything worked perfectly until I ran the 'amplify publish' command in step 5. The command appears to upload the necessary files as shown by the output.

```
| Category  | Resource name   | Operation | Provider plugin   |
| --------- | --------------- | --------- | ----------------- |
| Hosting   | S3AndCloudFront | Create    | awscloudformation |
| Auth      | cognito61860c3a | No Change | awscloudformation |
| Analytics | amplifyjsapp    | No Change | awscloudformation |
? Are you sure you want to continue? Yes
⠴ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS amplifyjsapp-20190101155508 AWS::CloudFormation::Stack Tue Jan 01 2019 16:31:43 GMT-0500 (Eastern Standard Time) User Initiated             
CREATE_IN_PROGRESS hostingS3AndCloudFront      AWS::CloudFormation::Stack Tue Jan 01 2019 16:31:46 GMT-0500 (Eastern Standard Time)                            
UPDATE_IN_PROGRESS analyticsamplifyjsapp       AWS::CloudFormation::Stack Tue Jan 01 2019 16:31:47 GMT-0500 (Eastern Standard Time)                            
UPDATE_IN_PROGRESS authcognito61860c3a         AWS::CloudFormation::Stack Tue Jan 01 2019 16:31:47 GMT-0500 (Eastern Standard Time)                            
CREATE_IN_PROGRESS hostingS3AndCloudFront      AWS::CloudFormation::Stack Tue Jan 01 2019 16:31:47 GMT-0500 (Eastern Standard Time) Resource creation Initiated
UPDATE_COMPLETE    authcognito61860c3a         AWS::CloudFormation::Stack Tue Jan 01 2019 16:31:48 GMT-0500 (Eastern Standard Time)                            
UPDATE_COMPLETE    analyticsamplifyjsapp       AWS::CloudFormation::Stack Tue Jan 01 2019 16:31:48 GMT-0500 (Eastern Standard Time)                            
⠇ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS amplifyjsapp-20190101155508-hostingS3AndCloudFront-1Y0M9Y0DDHYVZ AWS::CloudFormation::Stack Tue Jan 01 2019 16:31:47 GMT-0500 (Eastern Standard Time) User Initiated             
CREATE_IN_PROGRESS S3Bucket                                                         AWS::S3::Bucket            Tue Jan 01 2019 16:31:50 GMT-0500 (Eastern Standard Time)                            
CREATE_IN_PROGRESS S3Bucket                                                         AWS::S3::Bucket            Tue Jan 01 2019 16:31:52 GMT-0500 (Eastern Standard Time) Resource creation Initiated
⠏ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE S3Bucket AWS::S3::Bucket Tue Jan 01 2019 16:32:12 GMT-0500 (Eastern Standard Time) 
⠙ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS                  BucketPolicy                                                     AWS::S3::BucketPolicy      Tue Jan 01 2019 16:32:14 GMT-0500 (Eastern Standard Time)                            
CREATE_IN_PROGRESS                  BucketPolicy                                                     AWS::S3::BucketPolicy      Tue Jan 01 2019 16:32:15 GMT-0500 (Eastern Standard Time) Resource creation Initiated
CREATE_COMPLETE                     BucketPolicy                                                     AWS::S3::BucketPolicy      Tue Jan 01 2019 16:32:15 GMT-0500 (Eastern Standard Time)                            
CREATE_COMPLETE                     amplifyjsapp-20190101155508-hostingS3AndCloudFront-1Y0M9Y0DDHYVZ AWS::CloudFormation::Stack Tue Jan 01 2019 16:32:16 GMT-0500 (Eastern Standard Time)                            
CREATE_COMPLETE                     hostingS3AndCloudFront                                           AWS::CloudFormation::Stack Tue Jan 01 2019 16:32:21 GMT-0500 (Eastern Standard Time)                            
UPDATE_COMPLETE_CLEANUP_IN_PROGRESS amplifyjsapp-20190101155508                                      AWS::CloudFormation::Stack Tue Jan 01 2019 16:32:23 GMT-0500 (Eastern Standard Time)                            
⠋ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS analyticsamplifyjsapp       AWS::CloudFormation::Stack Tue Jan 01 2019 16:32:24 GMT-0500 (Eastern Standard Time) 
UPDATE_IN_PROGRESS authcognito61860c3a         AWS::CloudFormation::Stack Tue Jan 01 2019 16:32:24 GMT-0500 (Eastern Standard Time) 
UPDATE_COMPLETE    analyticsamplifyjsapp       AWS::CloudFormation::Stack Tue Jan 01 2019 16:32:24 GMT-0500 (Eastern Standard Time) 
UPDATE_COMPLETE    authcognito61860c3a         AWS::CloudFormation::Stack Tue Jan 01 2019 16:32:25 GMT-0500 (Eastern Standard Time) 
UPDATE_COMPLETE    amplifyjsapp-20190101155508 AWS::CloudFormation::Stack Tue Jan 01 2019 16:32:25 GMT-0500 (Eastern Standard Time) 
✔ All resources are updated in the cloud

Hosting endpoint: http://amplifyjsapp-20190101162940-hostingbucket.s3-website.us-east-2.amazonaws.com


> amplify-js-app@1.0.0 build /Volumes/PORTABLE/share/dad/Git/amplify-js-app
> webpack

Hash: 4498af5e3788bd1ff49e
Version: webpack 4.28.3
Time: 1539ms
Built at: 01/01/2019 4:32:49 PM
         Asset      Size  Chunks             Chunk Names
    index.html  1.53 KiB          [emitted]  
main.bundle.js   1.3 MiB    main  [emitted]  main
Entrypoint main = main.bundle.js
[0] fs (ignored) 15 bytes {main} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {main} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {main} [built]
[./src/app.js] 1.06 KiB {main} [built]
[./src/aws-exports.js] 695 bytes {main} [built]
    + 197 hidden modules
frontend build command exited with code 0
✔ Uploading files successful.
Your app is published successfully.
http://amplifyjsapp-20190101162940-hostingbucket.s3-website.us-east-2.amazonaws.com
```

Attempts to access the resource give a 404 error which I assume is because the bucket is, in fact, empty.

I was using @aws-amplify/cli version 0.1.38. I tried downgrading to 0.1.32 but this produced a number of errors and ultimately did not produce a different result.

**Comment by ryanjones** [comment] 2019-01-06 02:19
@jpknapp3 what's your distribution folder? I had a similar issue here:
https://github.com/aws-amplify/docs/pull/332 - It could be that your distribution folder isn't setup correctly w/ amplify.

**Comment by jpknapp3** [comment] 2019-01-06 14:12
Thanks for looking into this further Ryan. The issue you reference describes the setup of a React project while I was setting up a pure JS project. The two may be similar but I couldn't locate the distribution folder in my project.

In any case, I tried to publish the project again and it worked! Not sure what changed between the 1st and today but the page is now being served from S3. This run of publish did setup a new bucket though. I can provide configuration information if that helps to nail down what caused the initial run to fail or to help people identify what may be wrong in the future. As far as I'm concerned though, this issue may be closed.

**Comment by Jordan-Eckowitz** [comment] 2019-01-07 04:35
+1
@aws-amplify/cli@0.1.38
react
macOS

**Comment by ChenLi0830** [comment] 2019-02-28 22:58
I has been using multiple Amplify environments, and experienced this issue today. It is solved by switching to another environment and switch back.
