### ISSUE TITLE
Unable to connect to an existing backend though CLI

### ISSUE THREAD

**Issue by ShehryarKh** [aws-amplify/amplify-cli#8022] opened 2021-08-24 15:50 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

5.3.0

### What operating system are you using?

mac

### Amplify Categories

Not applicable

### Amplify Commands

pull

### Describe the bug

No Amplify backend project files detected within this folder. Either initialize a new Amplify project or pull an existing project.
      - "amplify init" to initialize a new Amplify project
      - "amplify pull <app-id>" to pull your existing Amplify project. Find the <app-id> in the AWS Console or Amplify Admin UI.
      

### Expected behavior

It should display the status of the backend resources.

### Reproduction steps

      Created a new folder
      ran `amplify pull --appId XXX --envName XX`
      ran `amplify pull`
      ran `amplify status`
      got Error

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by attilah** [comment] 2021-08-24 23:00
@ShehryarKh the `status` command is fully reimplemented in 5.3.1 that was released Today, give it a try, that error message was not showing when I tried to reproduce the error.

During pull if you answer `No` to the `Do you plan on modifying this backend?` question your backend files will not be downloaded, but everything that is needed to regenerate your frontend configuration files will be there, in this case since there are no backend files downloaded, it is expected that normal CLI commands that requiring an initialized project will give you a friendly error message.

If you answer with 'Yes' to that question, `amplify status` and other commands will behave as expected.

Closing the issue as the question has been answered.

**Closed by attilah** 2021-08-24 23:00 UTC
Labels: question, multienv
