### ISSUE TITLE
Amplify push "nothing to update" after change in VTL and revert.

### ISSUE THREAD

**Issue by mattiLeBlanc** [aws-amplify/amplify-cli#1736] opened 2019-06-27 07:06 UTC
**Describe the bug**
When I make a change in a resolver (VTL file) and do an Amplify push, it will push the change to the cloud.
When I revert the change in my VTL file (undo) and push again, it says there is nothing to push.

**To Reproduce**
1. Open a resolver file, make a change
2. run `amplify push` and to finish
3. Undo your change
4. run `amplify push` and it tells you there is nothing to push.

**Expected behavior**
I expect it to push my change

**Screenshots**
![image](https://user-images.githubusercontent.com/5285035/60244387-aa21cb00-98fd-11e9-8efa-2c8f130ce2e3.png)

Online resolver (not updated) because it didn't push again:
![image](https://user-images.githubusercontent.com/5285035/60244417-ba39aa80-98fd-11e9-838f-746aa848c232.png)

Local resolver which is correct:
![image](https://user-images.githubusercontent.com/5285035/60244428-c0c82200-98fd-11e9-92d7-56d05e9fc336.png)

Possible reason: file checksum not updated so when you revert back it doesn't see a change?

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] osx mojave

Workaround:  make a change in another file or change the resolver online.

**Comment by attilah** [comment] 2019-06-27 12:52
@mattiLeBlanc could you please tell us which version of the CLI are you using?

With the latest version of the CLI I was not able to reproduce this behavior, it worked as expected.

Just to confirm you are modifying custom resolvers, not generated ones, right? 

One thing that came to my mind is frequent changes to files could cause various text editors to not to save to disk, because they're optimizing disk access, please make sure it is not the case to make us able to close this out as a cause.

**Comment by mattiLeBlanc** [comment] 2019-06-28 00:49
Running 1.7.5.

I am using VS Code, I definitely save the file.

![image](https://user-images.githubusercontent.com/5285035/60309340-aa1edb00-9990-11e9-8c63-84185d94b595.png)

I must concur that trying it now, It did see changes and allowed me to push. So not sure why it doesn't happen consistently.
I did the exact same steps lol.

**Closed** 2019-07-03 05:51 UTC
Labels: pending-response, pending-triage, platform
