### ISSUE TITLE
Amplify partial push does not work as expected

### ISSUE THREAD

**Issue by vparpoil** [aws-amplify/amplify-cli#1147] opened 2019-03-29 16:01 UTC
**Describe the bug**
When trying to push partial ressources the output given by the CLI states that more ressources are updated than what is needed

**To Reproduce**
1. In an amplify app, create a function (`amplify add function`)
2. push the function `amplify push function functionName`
3 . watch the output: 
```

| Category | Resource name          | Operation | Provider plugin   |
| -------- | ---------------------- | --------- | ----------------- |
| Function | functionName             | Create    | awscloudformation |
? Are you sure you want to continue? Yes

GraphQL schema compiled successfully. // <= this step doesn't seem necessary when pushing functions
Edit your schema at path or place .graphql files in a directory at path
UPDATE_IN_PROGRESS app AWS::CloudFormation::Stack Fri Mar 29 2019 12:47:05 GMT+0100 (CET) User Initiated
CREATE_IN_PROGRESS functionfunctionName          AWS::CloudFormation::Stack Fri Mar 29 2019 12:47:11 GMT+0100 (CET)               
⠙ Updating resources in the cloud. This may take a few minutes...  // <= this seems ok
[...]
UPDATE_IN_PROGRESS GraphQLSchema AWS::AppSync::GraphQLSchema Fri Mar 29 2019 12:47:27 GMT+0100 (CET) 
UPDATE_IN_PROGRESS GraphQLAPIKey AWS::AppSync::ApiKey        Fri Mar 29 2019 12:47:27 GMT+0100 (CET) 
⠼ Updating resources in the cloud. This may take a few minutes...
[...]
UPDATE_IN_PROGRESS Table    AWS::CloudFormation::Stack  Fri Mar 29 2019 12:47:49 GMT+0100 (CET)  // <= this step doesn't seem necessary when pushing functions
UPDATE_COMPLETE    Table       AWS::AppSync::ApiKey        Fri Mar 29 2019 12:47:30 GMT+0100 (CET)  // <= this step doesn't seem necessary when pushing functions
```
**Expected behavior**
I was expecting to see only output related to the function being pushed

**Additional context**
Amplify cli 1.1.7

**Comment by jkeys-ecg-nmsu** [comment] 2019-03-31 00:43
Duplicate of #836

**Comment by kaustavghosh06** [comment] 2019-04-03 05:02
This is a duplicate of #836 . Closing this and let's track it via one issue.

**Closed by kaustavghosh06** 2019-04-03 05:02 UTC
Labels: bug, pending-review, platform
