### ISSUE TITLE
GraphQL-list-query (wihtout filters) returns nextToken although last entry was already sent as last item before limit was reached

### ISSUE THREAD

**Issue by MartinPindel** [aws-amplify/amplify-cli#3160] opened 2020-01-10 12:32 UTC
**Which Category is your question related to?**
API (GraphQL)

**Amplify CLI Version** 
4.0.0

**What AWS Services are you utilizing?**
AppSync, DynamoDB, Cognito

**Provide additional details e.g. code snippets**
I have a DynamoDB with 10 entries and my query has a limit of 5.
On my second request (with nextToken from first request) I receive the expected entries 6-10, but also a new nextToken. So the next request with this nextToken responds with no data.
Can anyone explain, why this happens?

**Comment by attilah** [comment] 2020-01-17 16:42
@MartinPindel This is by design in AppSync, as when you get back a full page - 5 items in your case - AppSync doesn't "scan forward" if there are more items or not, it presents you a ```nextToken``` because you requested 5 items, it returns you 5 items and the token to make you able to query for next pages if there is more data to return. What you're hitting is an "edge case" for the current state of your data, because there are 2 possibilities here:
- No more data for the next paging query (your case)
- New data gets inserted until the next paging query - so that data will be returned with the next paging query

I found a related issue [here](https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/57) in the AmplifyJS repo.

I hope this clears things up, I'm closing the issue as the question is answered. If something new comes up, please don't hesitate to ask.

**Closed by attilah** 2020-01-17 16:42 UTC
Labels: graphql-transformer, question
