### ISSUE TITLE
Resource is not in the state stackUpdateComplete

### ISSUE THREAD

**Issue by tomschiffmann** [aws-amplify/amplify-cli#6714] opened 2021-02-23 09:45 UTC
> **Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the
> [Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I have tried to add another api to my current amplify project and eventually tried to push it. After the build has failed, I deleted the new api from amplify/cli again but my I am still not able to run amplify push when adding a new lambda function

**Amplify CLI Version**
4.44.0

**Expected behavior**
Being able to upload lambda function, provide through @amplify/cli

**Screenshots**
<img width="773" alt="Screenshot 2021-02-23 at 10 44 54" src="https://user-images.githubusercontent.com/45202935/108826111-351c0280-75c4-11eb-8cb2-45076987d2a7.png">
<img width="1538" alt="Screenshot 2021-02-23 at 10 44 46" src="https://user-images.githubusercontent.com/45202935/108826124-377e5c80-75c4-11eb-9e11-485764592075.png">
<img width="1444" alt="Screenshot 2021-02-23 at 10 44 23" src="https://user-images.githubusercontent.com/45202935/108826130-39482000-75c4-11eb-943f-b645cbfd29f0.png">

**Desktop (please complete the following information):**

- OS: Mac
- Node Version. v12.18.3

**Comment by akshbhu** [comment] 2021-02-23 20:07
Hi @tomschiffmann 

Are you using CI/CD to deploy your changes or you did using amplify push?

Can you also Include any relevant log output under `~/.amplify/logs/amplify-cli-<issue-date>.log`?

**Comment by akshbhu** [comment] 2021-02-23 20:24
Closing this issue as this is a duplicate of https://github.com/aws-amplify/amplify-cli/issues/6619.

You can comment or follow  this above link for further updates on this issue

**Closed by akshbhu** 2021-02-23 20:24 UTC
Labels: pending-response, pending-triage, platform
