### ISSUE TITLE
UserPool not being tagged properly from tags.json

### ISSUE THREAD

**Issue by nathanthorpe** [aws-amplify/amplify-cli#11069] opened 2022-09-26 21:42 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.17.0

### Amplify CLI Version

10.0.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth

### Amplify Commands

Not applicable

### Describe the bug

The user pool is not being tagged by the tags.json file.

Tags.json file:
```
[
  {
    "Key": "application",
    "Value": "{project-name}-infra"
  },
  {
    "Key": "environment",
    "Value": "{project-env}"
  },
  {
    "Key": "createdby",
    "Value": "Amplify"
  },
  {
    "Key": "owner",
    "Value": "Amplify"
  }
]
```

User pool:
![image](https://user-images.githubusercontent.com/889094/192385551-ec6f67cf-c7bd-4884-bedb-858559c25e4e.png)

### Expected behavior

It should be tagged like the other resources

### Reproduction steps

- Add auth
- Push
- Observe no tags being added to user pool

### GraphQL schema(s)

Not Applicable

### Log output

Not applicable

### Additional information

Currently to get around it, in the override.ts I've been adding the following:
```
 resources.userPool.tags.setTag(
    'application', `${config.applicationName}-infra`
  );
  resources.userPool.tags.setTag(
    'environment', config.env
  );
  resources.userPool.tags.setTag(
    'createdby', 'Amplify'
  );
```

**Comment by josefaidt** [comment] 2022-09-28 14:54
Hey @nathanthorpe :wave: thanks for raising this and for providing the workaround! It appears this is a duplicate of https://github.com/aws-amplify/amplify-cli/issues/10548 and more specifically, https://github.com/aws-amplify/amplify-cli/issues/6642. Closing in favor of tracking the existing items

**Closed by josefaidt** 2022-09-28 14:54 UTC

**Comment by nathanthorpe** [comment] 2022-09-28 14:58
Ah great thanks, my bad I searched User pool rather than cognito :slightly_smiling_face:
