### ISSUE TITLE
amplify push throw error when remove auth resource (had Triggers)

### ISSUE THREAD

**Issue by phanviet** [aws-amplify/amplify-cli#7575] opened 2021-06-22 07:08 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v12.21.0

### Amplify CLI Version

5.0.1

### What operating system are you using?

Mac

### Amplify Categories

auth

### Amplify Commands

push

### Describe the bug

1. I have 1 User pool + 3 Triggers. All resources created by Amplify CLI
2. I'd like to remove auth resource. So I do:

`amplify remove auth` with this User pool.
`amplify remove function` all Triggers
`amplify push`

throw error 
![Screen Shot 2021-06-22 at 14 02 14](https://user-images.githubusercontent.com/2238528/122879743-6f739180-d363-11eb-9b4a-2bcd77aa3d46.jpg)

### Expected behavior

auth resources: User pool + Lambda Triggers should be removed on Cloudformation and Amplify

### Reproduction steps

1. I have 1 User pool + 3 Triggers. All resources created by Amplify CLI
2. I'd like to remove auth resource. So I do:

`amplify remove auth` with this User pool.
`amplify remove function` all Triggers

throw error 
![Screen Shot 2021-06-22 at 14 02 14](https://user-images.githubusercontent.com/2238528/122879743-6f739180-d363-11eb-9b4a-2bcd77aa3d46.jpg)

**Comment by attilah** [comment] 2021-06-22 18:55
@phanviet thanks for reporting the issue, I put it into our bugbash project to tracking a fix for it.

**Comment by attilah** [comment] 2021-06-23 00:11
Closing in favor of #7561 as the root cause is the same.

**Closed by attilah** 2021-06-23 00:11 UTC
Labels: auth, bug
