### ISSUE TITLE
Update .gitignore

### ISSUE THREAD

**Issue by jarrettj** [aws-amplify/amplify-cli#104] opened 2018-09-04 08:29 UTC
**Do you want to request a feature or report a bug?**
Feature

**What is the current behavior?**
Files that should be ignored in git should be added to .gitignore during init.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**Steps to reproduce the issue:**

1. amplify init 
2. check .gitignore
3. no changes to the file

**What is the expected behavior?**

**Additional environment details**

* **OS version (ie Windows 10 build X, macOS Sierra 10.12.6, etc.)**
MacOS
* **Output of ``amplify --version``**:
0.1.14
* **Did this work in previous versions?**: Y/N
N

**Comment by rygo6** [comment] 2018-09-04 15:33
What files should be ignored?

**Comment by haverchuck** [comment] 2018-09-04 16:32
@jarrettj  Thanks for the issue - can you please clarify which files/directories you are referring to?

**Comment by kaustavghosh06** [comment] 2018-09-05 17:43
@jarrettj Yes, you would need to share the folder with other devs (using version control maybe) and the other devs would need to run the 'amplify configure project' command to setup the project for his/her system.

**Comment by jarrettj** [comment] 2018-09-05 19:37
Cool thanks. So it needs a configure call, for it. Thanks.

**Comment by shavyg2** [comment] 2018-09-24 16:21
ye because somethings reference path that are directly on your computer.

**Comment by blbradley** [comment] 2018-09-25 04:39
Here's where I'm at on this:

* ignore `amplify/.config`.
* Some CloudFormation bits save the last deployed timestamp. It would be nice to ignore those files (like `amplify-meta.json`) but at least some are needed to reproduce on another machine.

**Comment by kaustavghosh06** [comment] 2018-12-27 21:06
With the release of the multienv and team workflow feature set in the CLI, a .gitignore file gets autogenerated for you (if none present) after the init step and the corresponding amplify files (to be gitignored) gets appended to it. For more details checkout https://aws-amplify.github.io/docs/cli/multienv?sdk=js

Closing this issue for now. Let me know if you've further questions around this.

**Closed by kaustavghosh06** 2018-12-27 21:06 UTC
Labels: enhancement

**Comment by jarrettj** [comment] 2019-04-10 05:39
Works well, thanks!
