### ISSUE TITLE
Corrupted zip archive produced

### ISSUE THREAD

**Issue by n3b** [aws-amplify/amplify-cli#10234] opened 2022-04-18 05:26 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

16.14.2

### Amplify CLI Version

8.0.1

### What operating system are you using?

MacOS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

nope

### Amplify Categories

function, api

### Amplify Commands

push

### Describe the bug

After very fresh repository init and the `amplify pull` I have added a comment to function then tried to push by `amplify push`. I was forced to do a migration and after that I see this:

<img width="951" alt="Screenshot 2022-04-18 at 01 24 21" src="https://user-images.githubusercontent.com/716480/163759115-d13eeab2-a46d-4b72-9ebb-baec78dd9f50.png">

I found similar reports at https://github.com/aws/aws-cdk/issues/12536, however nothing of mentioned there helped to resolve my particular issue. If you could provide some info about what do I need to run amplify-cli from sources - that would be very useful.

### Expected behavior

proper `amplify push`

### Reproduction steps

1. amplify pull
2. change function
3. amplify push

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment] 2022-04-18 18:19
Hey @n3b :wave: thanks for raising this! To clarify, was a change made to a Lambda function that is attached to a Lambda Layer? I see from the screenshot it appears our layer version is erroring out. I also have a few follow-up questions:

- what resource were you prompted to migrate?
- were there any changes made to the Lambda or Layer outside of Amplify CLI (i.e. in the AWS Console)?
- does `amplify function push` mitigate the issue?

**Comment by n3b** [comment] 2022-04-18 19:52
Hey @josefaidt thanks for helping!
The function I changed is not attached to the layer. I did change that layer itself (I had to mention it, sorry) by removing the deprecated `layerVersion` from `parameters.json`. Additionally amplify-cli does some changes too - there is a prompt "Accept the suggested layer version configurations".

- The lambda layer itself. "Amplify has updated the way Lambda Layer versions are managed. In order to take advantage of the newest features and bug fixes, a one-way migration is required....."
- No, the layer contains node_modules only. The function wasn't modified via console too as far as I know. 
- it doesn't, same issue.

**Comment by josefaidt** [comment] 2022-04-18 20:20
Hey @n3b thanks for the clarification! 

> No, the layer contains node_modules only.

To further clarify, does the layer also contain the `package.json` and associated lockfile?

**Comment by n3b** [comment] 2022-04-18 20:28
@josefaidt yes, those are there. The modules are installed locally too, not sure whether they are ignored or not.
I've checked multiple Node versions from 12 to 16 - the issue is consistent and doesn't depend on that.

**Comment by josefaidt** [comment] 2022-04-19 16:08
Hey @n3b can you check to see whether the lambda layer distribution zip is empty? Are you able to `cd` into that directory and install dependencies without error?

**Comment by n3b** [comment] 2022-04-19 18:01
hey @josefaidt yes it is empty 22b zip file, and yes I can install dependencies:
```
"dependencies": {
    "axios": "^0.21.1",
    "cross-fetch": "^3.0.6",
    "graphql-tag": "^2.11.0",
    "mysql": "^2.18.1"
  }
```

**Comment by josefaidt** [comment] 2022-04-19 21:22
Hey @n3b thank you for clarifying! Unfortunately I am unable to reproduce this issue using a sample lambda layer with a few dependencies as I can see my distribution zip archive is around 40MB. Would you mind sending your `amplify/` directory as a zip archive to amplify-cli@amazon.com? I'd like to take a further look at the setup

**Comment by n3b** [comment] 2022-04-21 04:27
Hey @josefaidt unfortunately I can't do that due to privacy. We've found a quick workaround by getting rid of the layer completely.

**Comment by josefaidt** [comment] 2022-04-26 20:04
Hey @n3b I have revisited this issue with another layer and the only way I'm able to reproduce this issue is if I delete all files in the layer's `lib/nodejs/` directory and `opt/` and push. Since the layer has been removed entirely and I am unable to reproduce I will close this issue for now. In the event you choose to use a Lambda Layer and this issue arises, please reply back to this thread with minimal reproduction steps and we can re-open to investigate further 🙂

**Closed by josefaidt** 2022-04-26 20:04 UTC
Labels: functions, pending-triage
