### ISSUE TITLE
Generated connection resolvers not using custom keys specified by @key directive

### ISSUE THREAD

**Issue by mdw2000** [aws-amplify/amplify-cli#1584] opened 2019-06-05 10:00 UTC
When using as custom primary key with @key, the generated connection resolvers does not use the keys specified in @key directive, it defaults to "id"

E.g. the model below the BlogPosts connection between Blog and Post

```
type Company @model {
  id: ID!
  name: String
  blogs: [Blog] @connection(name: "CompanyBlogs")
}

type Blog @model @key(fields: ["company","id"]){
  company: ID!
  id: ID!
  Company: Company @connection(name: "CompanyBlogs", keyField: "company")
  name: String!
  posts: [Post] @connection(name: "BlogPosts")
}

type Post @model @key(fields: ["company","id"]) {
  company: ID!
  id: ID!
  Company: Company @connection(keyField: "company")
  title: String!
  blog: Blog @connection(name: "BlogPosts")
}
```
Looking at the ` blog: Blog @connection(name: "BlogPosts")` connection, the resolver should use the `company, id` composite key specified in `type Blog @model @key(fields: ["company","id"])`, instead the generated `Post.blog.req.vtl` resolver uses the old `id` as key

```
{
  "version": "2017-02-28",
  "operation": "GetItem",
  "key": {
      "id": $util.dynamodb.toDynamoDBJson($util.defaultIfNullOrBlank($ctx.source.postBlogId, "___xamznone____"))
  }
}
```

**Expected behavior**
The generated resolver should use the partition/sort keys as specified in the @key directive
```
{
  "version": "2017-02-28",
  "operation": "GetItem",
  "key": {
            "company": $util.dynamodb.toDynamoDBJson($util.defaultIfNullOrBlank($ctx.source.copmany, "___xamznone____")),
      "id": $util.dynamodb.toDynamoDBJson($util.defaultIfNullOrBlank($ctx.source.postBlogId, "___xamznone____"))
  }
}
```

amplify @ 1.7.0

**Comment by rarira** [comment] 2019-06-05 11:03
#1562

**Comment by rarira** [comment] 2019-06-05 11:03
Duplicate of #1562

**Comment by kaustavghosh06** [comment] 2019-06-06 01:16
Closing as this is a duplicate fo #1562

**Closed by kaustavghosh06** 2019-06-06 01:16 UTC
