### ISSUE TITLE
amplify push => The following resource(s) failed to create: [UserPoolClientLambda]

### ISSUE THREAD

**Issue by coconutstd** [aws-amplify/amplify-cli#5982] opened 2020-11-26 15:40 UTC
**Describe the bug**

I tried to push amplify to cloud, but i got these error

```
junui@ijun-uiui-MacBookPro aws-android-workshop % amplify push

✔ Successfully pulled backend environment dev from the cloud.

Current Environment: dev

| Category | Resource name              | Operation | Provider plugin   |
| -------- | -------------------------- | --------- | ----------------- |
| Auth     | awsandroidworkshopf01d4c22 | Create    | awscloudformation |
| Api      | awsandroidworkshop         | Create    | awscloudformation |
? Are you sure you want to continue? Yes

The following types do not have '@auth' enabled. Consider using @auth with @model
         - Todo
Learn more about @auth here: https://docs.amplify.aws/cli/graphql-transformer/directives#auth


GraphQL schema compiled successfully.

Edit your schema at /Users/junui/AndroidStudioProjects/aws-android-workshop/amplify/backend/api/awsandroidworkshop/schema.graphql or place .graphql files in a directory at /Users/junui/AndroidStudioProjects/aws-android-workshop/amplify/backend/api/awsandroidworkshop/schema
? Do you want to generate code for your newly created GraphQL API Yes
? Enter the file name pattern of graphql queries, mutations and subscriptions app/src/main/graphql/**/*.graphql
? Do you want to generate/update all possible GraphQL operations - queries, mutations and subscriptions Yes
? Enter maximum statement depth [increase from default if your schema is deeply nested] 2
⠹ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS AuthRole                             AWS::IAM::Role             Fri Nov 27 2020 00:29:12 GMT+0900 (Korean Standard Time)               
UPDATE_IN_PROGRESS DeploymentBucket                     AWS::S3::Bucket            Fri Nov 27 2020 00:29:12 GMT+0900 (Korean Standard Time)               
UPDATE_IN_PROGRESS UnauthRole                           AWS::IAM::Role             Fri Nov 27 2020 00:29:12 GMT+0900 (Korean Standard Time)               
UPDATE_IN_PROGRESS amplify-awsandroidworkshop-dev-00759 AWS::CloudFormation::Stack Fri Nov 27 2020 00:29:07 GMT+0900 (Korean Standard Time) User Initiated
⠇ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE DeploymentBucket AWS::S3::Bucket Fri Nov 27 2020 00:29:32 GMT+0900 (Korean Standard Time) 
UPDATE_COMPLETE AuthRole         AWS::IAM::Role  Fri Nov 27 2020 00:29:31 GMT+0900 (Korean Standard Time) 
UPDATE_COMPLETE UnauthRole       AWS::IAM::Role  Fri Nov 27 2020 00:29:30 GMT+0900 (Korean Standard Time) 
⠏ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS authawsandroidworkshopf01d4c22 AWS::CloudFormation::Stack Fri Nov 27 2020 00:29:35 GMT+0900 (Korean Standard Time) Resource creation Initiated
CREATE_IN_PROGRESS UpdateRolesWithIDPFunctionRole AWS::IAM::Role             Fri Nov 27 2020 00:29:34 GMT+0900 (Korean Standard Time) Resource creation Initiated
CREATE_IN_PROGRESS authawsandroidworkshopf01d4c22 AWS::CloudFormation::Stack Fri Nov 27 2020 00:29:34 GMT+0900 (Korean Standard Time)                            
CREATE_IN_PROGRESS UpdateRolesWithIDPFunctionRole AWS::IAM::Role             Fri Nov 27 2020 00:29:33 GMT+0900 (Korean Standard Time)                            
⠋ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS amplify-awsandroidworkshop-dev-00759-authawsandroidworkshopf01d4c22-JHKPS83KAWWF AWS::CloudFormation::Stack Fri Nov 27 2020 00:29:35 GMT+0900 (Korean Standard Time) User Initiated
⠏ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS SNSRole AWS::IAM::Role Fri Nov 27 2020 00:29:42 GMT+0900 (Korean Standard Time) Resource creation Initiated
CREATE_IN_PROGRESS SNSRole AWS::IAM::Role Fri Nov 27 2020 00:29:41 GMT+0900 (Korean Standard Time)                            
⠋ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE UpdateRolesWithIDPFunctionRole AWS::IAM::Role Fri Nov 27 2020 00:29:55 GMT+0900 (Korean Standard Time) 
⠸ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE SNSRole AWS::IAM::Role Fri Nov 27 2020 00:30:02 GMT+0900 (Korean Standard Time) 
⠙ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS UserPool AWS::Cognito::UserPool Fri Nov 27 2020 00:30:07 GMT+0900 (Korean Standard Time) 
⠹ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS UserPoolClientWeb AWS::Cognito::UserPoolClient Fri Nov 27 2020 00:30:12 GMT+0900 (Korean Standard Time)                            
CREATE_COMPLETE    UserPool          AWS::Cognito::UserPool       Fri Nov 27 2020 00:30:09 GMT+0900 (Korean Standard Time)                            
CREATE_IN_PROGRESS UserPool          AWS::Cognito::UserPool       Fri Nov 27 2020 00:30:09 GMT+0900 (Korean Standard Time) Resource creation Initiated
⠹ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE    UserPoolClient    AWS::Cognito::UserPoolClient Fri Nov 27 2020 00:30:15 GMT+0900 (Korean Standard Time)                            
CREATE_IN_PROGRESS UserPoolClient    AWS::Cognito::UserPoolClient Fri Nov 27 2020 00:30:14 GMT+0900 (Korean Standard Time) Resource creation Initiated
CREATE_COMPLETE    UserPoolClientWeb AWS::Cognito::UserPoolClient Fri Nov 27 2020 00:30:14 GMT+0900 (Korean Standard Time)                            
CREATE_IN_PROGRESS UserPoolClientWeb AWS::Cognito::UserPoolClient Fri Nov 27 2020 00:30:14 GMT+0900 (Korean Standard Time) Resource creation Initiated
CREATE_IN_PROGRESS UserPoolClient    AWS::Cognito::UserPoolClient Fri Nov 27 2020 00:30:13 GMT+0900 (Korean Standard Time)                            
⠴ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS UserPoolClientRole AWS::IAM::Role Fri Nov 27 2020 00:30:18 GMT+0900 (Korean Standard Time) 
⠸ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS UserPoolClientRole AWS::IAM::Role Fri Nov 27 2020 00:30:18 GMT+0900 (Korean Standard Time) Resource creation Initiated
⠸ Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED      UserPoolClientLambda AWS::Lambda::Function Fri Nov 27 2020 00:30:42 GMT+0900 (Korean Standard Time) AccessDeniedExceptionnull (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: c33ad635-9f33-4e02-9505-ba37160e2775; Proxy: null)
CREATE_IN_PROGRESS UserPoolClientLambda AWS::Lambda::Function Fri Nov 27 2020 00:30:42 GMT+0900 (Korean Standard Time)                                                                                                                                                                           
CREATE_COMPLETE    UserPoolClientRole   AWS::IAM::Role        Fri Nov 27 2020 00:30:38 GMT+0900 (Korean Standard Time)                                                                                                                                                                           
⠸ Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED amplify-awsandroidworkshop-dev-00759-authawsandroidworkshopf01d4c22-JHKPS83KAWWF AWS::CloudFormation::Stack Fri Nov 27 2020 00:30:43 GMT+0900 (Korean Standard Time) The following resource(s) failed to create: [UserPoolClientLambda]. 
⠴ Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED authawsandroidworkshopf01d4c22 AWS::CloudFormation::Stack Fri Nov 27 2020 00:30:53 GMT+0900 (Korean Standard Time) Embedded stack arn:aws:cloudformation:ap-northeast-2:447914318995:stack/amplify-awsandroidworkshop-dev-00759-authawsandroidworkshopf01d4c22-JHKPS83KAWWF/2fcb0370-2ffc-11eb-b487-0aa6c7749250 was not successfully created: The following resource(s) failed to create: [UserPoolClientLambda]. 
⠹ Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_IN_PROGRESS amplify-awsandroidworkshop-dev-00759 AWS::CloudFormation::Stack Fri Nov 27 2020 00:30:53 GMT+0900 (Korean Standard Time) The following resource(s) failed to create: [authawsandroidworkshopf01d4c22]. 
⠹ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS UnauthRole       AWS::IAM::Role  Fri Nov 27 2020 00:31:03 GMT+0900 (Korean Standard Time) 
UPDATE_IN_PROGRESS AuthRole         AWS::IAM::Role  Fri Nov 27 2020 00:31:03 GMT+0900 (Korean Standard Time) 
UPDATE_IN_PROGRESS DeploymentBucket AWS::S3::Bucket Fri Nov 27 2020 00:31:03 GMT+0900 (Korean Standard Time) 
⠼ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE AuthRole AWS::IAM::Role Fri Nov 27 2020 00:31:23 GMT+0900 (Korean Standard Time) 
⠼ Updating resources in the cloud. This may take a few minutes...

DELETE_IN_PROGRESS                           authawsandroidworkshopf01d4c22       AWS::CloudFormation::Stack Fri Nov 27 2020 00:31:25 GMT+0900 (Korean Standard Time) 
DELETE_IN_PROGRESS                           UpdateRolesWithIDPFunctionRole       AWS::IAM::Role             Fri Nov 27 2020 00:31:25 GMT+0900 (Korean Standard Time) 
UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS amplify-awsandroidworkshop-dev-00759 AWS::CloudFormation::Stack Fri Nov 27 2020 00:31:24 GMT+0900 (Korean Standard Time) 
UPDATE_COMPLETE                              DeploymentBucket                     AWS::S3::Bucket            Fri Nov 27 2020 00:31:23 GMT+0900 (Korean Standard Time) 
UPDATE_COMPLETE                              UnauthRole                           AWS::IAM::Role             Fri Nov 27 2020 00:31:23 GMT+0900 (Korean Standard Time) 
⠴ Updating resources in the cloud. This may take a few minutes...

DELETE_COMPLETE    UserPoolClientLambda                                                             AWS::Lambda::Function        Fri Nov 27 2020 00:31:28 GMT+0900 (Korean Standard Time)               
DELETE_IN_PROGRESS UserPoolClientWeb                                                                AWS::Cognito::UserPoolClient Fri Nov 27 2020 00:31:28 GMT+0900 (Korean Standard Time)               
DELETE_IN_PROGRESS amplify-awsandroidworkshop-dev-00759-authawsandroidworkshopf01d4c22-JHKPS83KAWWF AWS::CloudFormation::Stack   Fri Nov 27 2020 00:31:26 GMT+0900 (Korean Standard Time) User Initiated
⠼ Updating resources in the cloud. This may take a few minutes...

DELETE_COMPLETE UpdateRolesWithIDPFunctionRole AWS::IAM::Role Fri Nov 27 2020 00:31:28 GMT+0900 (Korean Standard Time) 
⠦ Updating resources in the cloud. This may take a few minutes...

DELETE_IN_PROGRESS UserPool           AWS::Cognito::UserPool       Fri Nov 27 2020 00:31:32 GMT+0900 (Korean Standard Time) 
DELETE_COMPLETE    UserPoolClient     AWS::Cognito::UserPoolClient Fri Nov 27 2020 00:31:32 GMT+0900 (Korean Standard Time) 
DELETE_IN_PROGRESS UserPoolClient     AWS::Cognito::UserPoolClient Fri Nov 27 2020 00:31:31 GMT+0900 (Korean Standard Time) 
DELETE_COMPLETE    UserPoolClientRole AWS::IAM::Role               Fri Nov 27 2020 00:31:30 GMT+0900 (Korean Standard Time) 
DELETE_COMPLETE    UserPoolClientWeb  AWS::Cognito::UserPoolClient Fri Nov 27 2020 00:31:29 GMT+0900 (Korean Standard Time) 
DELETE_IN_PROGRESS UserPoolClientRole AWS::IAM::Role               Fri Nov 27 2020 00:31:28 GMT+0900 (Korean Standard Time) 
⠧ Updating resources in the cloud. This may take a few minutes...

DELETE_COMPLETE    SNSRole  AWS::IAM::Role         Fri Nov 27 2020 00:31:37 GMT+0900 (Korean Standard Time) 
DELETE_IN_PROGRESS SNSRole  AWS::IAM::Role         Fri Nov 27 2020 00:31:34 GMT+0900 (Korean Standard Time) 
DELETE_COMPLETE    UserPool AWS::Cognito::UserPool Fri Nov 27 2020 00:31:34 GMT+0900 (Korean Standard Time) 
⠇ Updating resources in the cloud. This may take a few minutes...

DELETE_COMPLETE amplify-awsandroidworkshop-dev-00759-authawsandroidworkshopf01d4c22-JHKPS83KAWWF AWS::CloudFormation::Stack Fri Nov 27 2020 00:31:38 GMT+0900 (Korean Standard Time) 
⠋ Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_COMPLETE amplify-awsandroidworkshop-dev-00759 AWS::CloudFormation::Stack Fri Nov 27 2020 00:31:48 GMT+0900 (Korean Standard Time) 
DELETE_COMPLETE          authawsandroidworkshopf01d4c22       AWS::CloudFormation::Stack Fri Nov 27 2020 00:31:47 GMT+0900 (Korean Standard Time) 
⠹ Updating resources in the cloud. This may take a few minutes...Error updating cloudformation stack
⠹ Updating resources in the cloud. This may take a few minutes...

Following resources failed

Resource Name: UserPoolClientLambda (AWS::Lambda::Function)
Event Type: create
Reason: AccessDeniedExceptionnull (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: c33ad635-9f33-4e02-9505-ba37160e2775; Proxy: null)


✖ An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
An error occurred during the push operation: Resource is not in the state stackUpdateComplete
```

**To Reproduce**

amplify configure
amplify init
amplify add auth
amplify add api
amplify push 

**Additional context**
I checked 
- amplify configure
- IAM Role => Permission Policy => AdministratorAccess

and, my amplify cli version is 4.36.0

**Comment by ammarkarachi** [comment] 2020-11-27 21:51
@coconutstd Which region were you pushing to?

**Comment by FocusedObjective** [comment] 2020-11-28 00:14
I started to get these errors yesterday as well (in the Oregon region if it matters).

I can push, but then when I check-in and the AWS console triggers an Amplify build, it fails with these messages there. I also then seem to have "Updated" changes on the next amplify push even though NOTHING should have changed. 

I will try and get more details to repro, but I just wanted to make it known that at least "two" people started getting this type of error November 26th odd.

**Comment by coconutstd** [comment] 2020-11-28 00:54
@ammarkarachi  I attempted at two regions, Virginia(us-east-1) and Seoul(ap-northeast-2)

**Comment by ammarkarachi** [comment] 2020-11-28 01:00
@FocusedObjective I was wondering if this was remnant of us-east-1 downtime. I am not able to reproduce it for now but I will keep checking

**Comment by t-lm** [comment] 2021-01-15 19:01
Same problem here. The UserPoolClientRole has gone missing - preventing the build. No change from my end.

**Comment by konichar** [comment] 2021-01-27 11:59
I have this same problem, after adding auth with 
amplify add auth
amplify push
I get
```
Following resources failed

Resource Name: UserPoolClientLambda (AWS::Lambda::Function)
Event Type: create
Reason: AccessDeniedExceptionnull (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: 8434d2a2-4287-4b79-b22f-5d95094436a0; Proxy: null)


× An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
An error occurred during the push operation: Resource is not in the state stackUpdateComplete
```
How I resolve this ?

PS: amplify cli is version 4.41.2

**Comment by ammarkarachi** [comment] 2021-01-28 00:23
@konichar @t-lm Is this after modifying the Lambda function?

**Comment by konichar** [comment] 2021-01-28 00:49
@ammarkarachi 

I have done almost everything I could find online except that, can you direct me on how to modify the lambda in the UserPoolClient.

**Comment by ammarkarachi** [comment] 2021-01-28 01:02
@konichar I am not advising to modify the function. I am just wondering whether there was any modification that resulted in this

**Comment by ammarkarachi** [comment] 2021-01-28 01:04
Was the project initialized and setup using an earlier version?

**Comment by konichar** [comment] 2021-01-28 01:07
Okay, I did not modify any function. However I tried switching my project to a different region, I have upgraded and downgraded cli, even starting a new project from scratch still resulted in the same error. This was all working yesterday.

What's the source of this issue CLI or AWS ?

**Comment by t-lm** [comment] 2021-01-28 07:24
Hi,
It is indeed after testing and publishing another lambda function directly in the web console (and not in the app).
Thanks


Le 28 janv. 2021 à 01:24, Ammar <notifications@github.com<mailto:notifications@github.com>> a écrit :



@konichar<https://github.com/konichar> @t-lm<https://github.com/t-lm> Is this after modifying the Lambda function?

**Comment by ammarkarachi** [comment] 2021-02-03 23:27
@konichar What's your IAM policy? does it include`lambda:InvokeFunction` policy?

**Comment by jaggar28** [comment] 2021-02-06 15:00
Hi,
I was facing similar problem. Check the solution given by "Freddy Haug" in the following link:
https://stackoverflow.com/questions/60157632/amplify-fails-to-push-auth-nodejs8-10

Quote:
"What you need to do is go to your Backend/Auth/ directory and find your *.yaml file

From there search for the AWS::Lambda::Function service and change the runtime environment to nodejs12.x"

It solved my problem.

**Comment by fruit-ninja** [comment] 2021-02-09 06:24
@konichar were you able to resolve your issue?

**Comment by konichar** [comment] 2021-02-09 09:48
> @konichar were you able to resolve your issue?

Sadly no, after a couple of days of bug finding I had to quickly switch my backend to firebase which has way less features than amplify but fewer bugs. 

Would definitely give amplify a shot on my next project when all issues have been resolved.

**Comment by dave-martinez** [comment] 2021-02-25 15:40
Hi, I'm encountering the same issue. Reproduced with the same steps.
Encountering this when auth is added

CLI version: 4.44.1

**Comment by archanashokeeniitg** [comment] 2021-03-02 05:16
> Hi, I'm encountering the same issue. Reproduced with the same steps.
> Encountering this when auth is added.
> 
> Does anyone encounter this as well? I followed the [Amplify React Native docs](https://docs.amplify.aws/start/getting-started/auth/q/integration/react-native#authentication-with-amplify) but hit this block.
> 
> Things I've done:
> 
> * IAM user has an AdministratorAccess
> * I've tried tried modifying nodejs10.x to nodejs12.x.
> * us-east-1 and ap-southeast-1
> 
> CLI version: 4.44.1
> $ amplify add auth
> $ amplify push
> 
> ```
> Resource Name: UserPoolClientLambda (AWS::Lambda::Function)
> Event Type: create
> Reason: AccessDeniedExceptionnull (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: de2203e0-7c39-4749-b494-e0871ee5c2fe; Proxy: null)
> ```

Yeah! I'm stuck on same . Cant find solution. Did you get through??

**Comment by t-lm** [comment] 2021-03-02 05:49
I ended-up re-creating the ressource manually outside of Amplify to sort the issue.

I did not get why the ressource disappeared in the first place.

Good luck.

Le 2 mars 2021 à 06:16, archanashokeeniitg <notifications@github.com<mailto:notifications@github.com>> a écrit :



Hi, I'm encountering the same issue. Reproduced with the same steps.
Encountering this when auth is added.

Does anyone encounter this as well? I followed the Amplify React Native docs<https://docs.amplify.aws/start/getting-started/auth/q/integration/react-native#authentication-with-amplify> but hit this block.

Things I've done:

  *   IAM user has an AdministratorAccess
  *   I've tried tried modifying nodejs10.x to nodejs12.x.
  *   us-east-1 and ap-southeast-1

CLI version: 4.44.1
$ amplify add auth
$ amplify push

Resource Name: UserPoolClientLambda (AWS::Lambda::Function)
Event Type: create
Reason: AccessDeniedExceptionnull (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: de2203e0-7c39-4749-b494-e0871ee5c2fe; Proxy: null)


Yeah! I'm stuck on same . Cant find solution. Did you get through??

**Comment by dave-martinez** [comment] 2021-03-02 11:04
Hi @t-lm ,

Can you share what you meant by creating the resource manually outside of Amplify?

I'd like to try out what you did hoping it'll fix the same for me.

**Comment by t-lm** [comment] 2021-03-02 12:13
The UserPoolClientLamba ressources points to an IAM role that had disappeared in some way in my case.

I recreated the IAM role directly in IAM with the exact name (Physical ID) and policies of the role that had gone missing. You can find the details of these in AWS CloudFormation, looking at the right stack and the ressources attached.

The role creation went Ok and the stack deployed normally after that.

Best


Thomas Langlois-Meurinne
+33 6 44 69 27 35
aconserver@hotmail.com<mailto:aconserver@hotmail.com>

Le 2 mars 2021 à 12:04, Dave Martinez <notifications@github.com<mailto:notifications@github.com>> a écrit :



Hi @t-lm<https://github.com/t-lm> ,

Can you share what you meant by creating the resource manually outside of Amplify?

I'd like to try out what you did hoping it'll fix the same for me.

**Comment by dave-martinez** [comment] 2021-03-02 16:05
Hi again @t-lm,

Thank you for sharing. However, I can't seem to make it work.

Here's what I tried
- Applying lambda policy's to all my roles [authRole, unauthRole, authRoleIdp] (Nothing happened)
- Manually created this role but tags as existed and cancels amplify push
```
  UserPoolClientRole:
  # Created to execute Lambda which gets userpool app client config values
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !If [ShouldNotCreateEnvResources, !Ref userpoolClientLambdaRole, !Join ['',['upClientLambdaRole', 'd30c42ae', !Select [3, !Split ['-', !Ref 'AWS::StackName']], '-', !Ref env]]]
```

What IAM role resource should I manually create?

**Comment by archanashokeeniitg** [comment] 2021-03-07 22:49
> Hi again @t-lm,
> 
> Thank you for sharing. However, I can't seem to make it work.
> 
> Here's what I tried
> 
> * Applying lambda policy's to all my roles [authRole, unauthRole, authRoleIdp] (Nothing happened)
> * Manually created this role but tags as existed and cancels amplify push
> 
> ```
>   UserPoolClientRole:
>   # Created to execute Lambda which gets userpool app client config values
>     Type: 'AWS::IAM::Role'
>     Properties:
>       RoleName: !If [ShouldNotCreateEnvResources, !Ref userpoolClientLambdaRole, !Join ['',['upClientLambdaRole', 'd30c42ae', !Select [3, !Split ['-', !Ref 'AWS::StackName']], '-', !Ref env]]]
> ```
> 
> What IAM role resource should I manually create?
> 
> Here's the full error that I get during amplify push as reference.
> 
> ```
> CREATE_FAILED UserPoolClientLambda AWS::Lambda::Function Wed Mar 03 2021 00:03:21 GMT+0800 (Philippine Standard Time) AccessDeniedExceptionnull (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: 7cdd9dc2-1200-4462-9e3b-dc334c1b3e2e; Proxy: null)
> ⠏ Updating resources in the cloud. This may take a few minutes...
> 
> CREATE_FAILED amplify-banana-dev-53441-authbananad30c42ae-1WE1YWIUU0BGS AWS::CloudFormation::Stack Wed Mar 03 2021 00:03:21 GMT+0800 (Philippine Standard Time) The following resource(s) failed to create: [UserPoolClientLambda].
> ⠼ Updating resources in the cloud. This may take a few minutes...
> 
> UPDATE_ROLLBACK_IN_PROGRESS amplify-banana-dev-53441 AWS::CloudFormation::Stack Wed Mar 03 2021 00:03:29 GMT+0800 (Philippine Standard Time) The following resource(s) failed to create: [authbananad30c42ae].
> CREATE_FAILED               authbananad30c42ae       AWS::CloudFormation::Stack Wed Mar 03 2021 00:03:28 GMT+0800 (Philippine Standard Time) Embedded stack arn:aws:cloudformation:ap-southeast-1:269793443487:stack/amplify-banana-dev-53441-authbananad30c42ae-1WE1YWIUU0BGS/8f8035f0-7b70-11eb-b0bc-06f1487f6a64 was not successfully created: The following resource(s) failed to create: [UserPoolClientLambda].
> ```
> 
> As a test, I also did this on a **Windows 10 desktop on a fresh install of amplify-cli and fresh create-react-app project**. The errors are still the same. I'm speculating that is it just my account (which I assume not since it's not only me that's experiencing this) or it's coming from the cli configuration.
> 
> Additional info is that I first tried it on my Apple Macbook Air M1 base model (Big Sur 11.2.1) if that information would help.
> Node Version: v15.9.0
> NPM Version: v7.6.0

Hi, Dave! 
Did you get through this error? Any solutions found? Been stuck for almost a week, trying everything available on the internet.

**Comment by dave-martinez** [comment] 2021-03-10 17:35
> Hi, Dave!
Did you get through this error? Any solutions found? Been stuck for almost a week, trying everything available on the internet.

Finally able to figure it out. 
My issue has something to do with my exposed api key case with my users.

I had help from the AWS support. Initially, I was just going to fix my billing payment method, and they mentioned that they locked my account due to the exposed api key. They walked me through it to rotate my API key and I just waited around 3-5 hours to get my account unlocked.

I tried it after following the same steps and it worked

$ amplify add auth
$ amplify push

**Comment by archanashokeeniitg** [comment] 2021-03-15 18:47
> > Hi, Dave!
> > Did you get through this error? Any solutions found? Been stuck for almost a week, trying everything available on the internet.
> 
> Finally able to figure it out.
> My issue has something to do with my exposed api key case with my users.
> 
> I had help from the AWS support. Initially, I was just going to fix my billing payment method, and they mentioned that they locked my account due to the exposed api key. They walked me through it to rotate my API key and I just waited around 3-5 hours to get my account unlocked.
> 
> I tried it after following the same steps and it worked
> 
> $ amplify add auth
> $ amplify push

Yeah ! that is true, Even I had an exposed API, that's why they locked me out of few services, Although I had to make a  fresh account before, which worked smoothly. But now I know, What messed up with my first Account . Thanks @dave-martinez

**Comment by kaustavghosh06** [comment] 2021-03-19 19:26
Closing this issue. 
Looks like the issue was due to locking of AWS accounts from create Lambda functions.

**Closed by kaustavghosh06** 2021-03-19 19:26 UTC
Labels: functions, not-reproducable, pending-triage
