### ISSUE TITLE
New created Lambda is not recognized in the next Env

### ISSUE THREAD

**Issue by biller-aivy** [aws-amplify/amplify-cli#10592] opened 2022-06-14 07:37 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v17.8.0

### Amplify CLI Version

8.4.0

### What operating system are you using?

MacOS M1

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no changes

### Amplify Categories

function, Not applicable

### Amplify Commands

push, status

### Describe the bug

I have 3 Env + 3 Branches. 

Develop / Staging / Production. 

If I now add a Lambda to Develop I do the following: 

- [develop] amplify push
- [develop] git push
- git checkout staging
- amplify env checkout staging
- git merge develop
- some merge conflicts (Amplify files) 

Now I get some changes from amplify status, but they are random I feel. The new lambda is not there. 

I tried to do an amplify env checkout staging --restore before. Without success. 

The funny thing is, when I do the amplify checkout staging in the develop branch, the CLI recognizes the new lambda and wants to create it. This is currently my workaround. Under Develop Branch I then push amplify staging env and then check out to staging Branch, then pull there via amplify pull the staging env and push it to git.

### Expected behavior

Should possible to push the new lambda to next env. 

### Reproduction steps

@josefaidt is knowing this issue from Discord Chat. 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment] 2022-06-14 13:44
Hey @biller-aivy :wave: thanks for taking the time to file this! I've marked this as a bug and the workaround would be to run `amplify env checkout <current-env-name>` again after `git merge`

**Comment by Nxtra** [comment] 2022-07-11 12:40
FYI, I think this behavior is already in the cli since quite a time. I've never known it otherwise and we joined around Amplify v5

**Comment by Nxtra** [comment] 2022-07-11 12:45
> Hey @biller-aivy 👋 thanks for taking the time to file this! I've marked this as a bug and the workaround would be to run `amplify env checkout <current-env-name>` again after `git merge`

I can confirm this workaround is working. Ofc developers have to remember to do this, which makes it a source of potential problems. But at least it's nice to have a less tedious workaround for now. 👍

**Comment by josefaidt** [comment] 2022-07-27 19:17
marking as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/8090, closing in favor of tracking existing item

**Closed by josefaidt** 2022-07-27 19:17 UTC
Labels: bug, functions, multienv, p2, ops-multienv
