### ISSUE TITLE
push api don't deploy stage version

### ISSUE THREAD

**Issue by kouz75** [aws-amplify/amplify-cli#9181] opened 2021-12-02 08:50 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.x

### Amplify CLI Version

7.5.6

### What operating system are you using?

mac

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

Updating an api won't deploy  a new stage. 

### Expected behavior

Ressources should be deploy when API is updated.

### Reproduction steps

1. add a new route to an api.
2. push the change.
3. In aws console, the new route is available in the ressources tab  but not in the stage  tab.

Manually deploy the Ressources fix the bug.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by jhockett** [comment] 2021-12-02 16:56
Closing this as a duplicate of #9142

**Closed by jhockett** 2021-12-02 16:56 UTC
