### ISSUE TITLE
Ability to have uni-directional 1-many connections via primary key id, not GSI

### ISSUE THREAD

**Issue by danrivett** [aws-amplify/amplify-cli#6352] opened 2021-01-09 22:46 UTC
**Is your feature request related to a problem? Please describe.**
The [AWS docs](https://docs.amplify.aws/cli/graphql-transformer/connection#usage) on connections show how a 1-1 relationship can be uni-directional and reference the other entity simply via its `id`:

```graphql
type Project @model {
  id: ID!
  name: String
  team: Team @connection
}

type Team @model {
  id: ID!
  name: String!
}
```

The key thing here is `Team` does not have any reference to `Project` and so it's a uni-directional relationship.

I am looking to do the same but for a 1-many relationship, I still want it uni-directional, so it would be something like:

```graphql
type Project @model {
  id: ID!
  name: String
  teams: [Team!]! @connection
}

type Team @model {
  id: ID!
  name: String!
}
```

The only difference here is the cardinality, now we are saying a Project can have many teams - it is still unidirectional and `Team` has no knowledge about what `Project`s it's associated with.

We could argue about the merit of having this as a uni-directional relationship - e.g. why not just have `Team` have a `projectId` field [like the docs suggest](https://docs.amplify.aws/cli/graphql-transformer/connection#has-many) for this use case - but our GraphQL schema model is more complicated and requires that the 1-many relationship is uni-directional for reasons outside the scope of this.

For now we have to manually model this as such:

```graphql
type Project @model {
  id: ID!
  name: String
  teamIds: [ID!]!
}

type Team @model {
  id: ID!
  name: String!
}
```

This is not very helpful because we can no longer zoom into the related `Team` fields via a single GraphQL query.

**Describe the solution you'd like**
What we would like is the ability to define something like:

```graphql
type Project @model {
  id: ID!
  name: String
  teams: [Team!]! @connection
}

type Team @model {
  id: ID!
  name: String!
}
```

Where the team ids are implicitly persisted in DynamoDB under the `teams` field.

Alternatively it could be modelled more explicitly under a `teamIds` field like so (similar to the [Has One](https://docs.amplify.aws/cli/graphql-transformer/connection#has-one) example in the docs):

```graphql
type Project @model {
  id: ID!
  name: String
  teamIds: [ID!]!
  teams: [Team!]! @connection(fields: ["teamIds"])
}

type Team @model {
  id: ID!
  name: String!
}
```

**Describe alternatives you've considered**
As mentioned above we are currently modelling this something like as follows:

```graphql
type Project @model {
  id: ID!
  name: String
  teamIds: [ID!]!
}

type Team @model {
  id: ID!
  name: String!
}
```

But we that prevents nested GraphQL queries, and requires us to make multiple queries so is actually quite painful. Our frontend uses DataStore so less of a problem there (but still is more hoops to jump through), but our backend uses GraphQL queries and that requires multiple GraphQL queries.

**Comment by attilah** [comment] 2021-01-11 19:12
@danrivett thanks for the feedback/suggestion. I think I understand your use case, but a single field is not really practical to store connected entities in any system. While it can work for some systems - as the number of connected entities are guarded and constrained otherwise - but can run into limitations of the underlying datastore whatever it is: like max field sizes, supported native datatypes (how could you filter on teams for example if that is a string, since list field types are not allowed), max record size. Beside the size limitations, performance issues can arise quickly as well.

I'm sure that these things were taken into consideration when the `@connection` directive was designed and implemented and the required functionality can be achieved with a many to many connection and using a connecting type, so I'm closing the issue. If you have further questions don't hesitate to comment on the issue or open a new one.

**Closed** 2021-01-11 19:12 UTC
Labels: @connection, graphql-transformer, question

**Comment by danrivett** [comment] 2021-01-11 21:43
Thanks @attilah. I'm not sure if my use case is fully understood, so just want to check this as you may have closed this prematurely if not.

Amplify already supports this schema as [described in the docs](https://docs.amplify.aws/cli/graphql-transformer/connection#has-many):

```graphql
type Post @model {
  id: ID!
  title: String!
  comments: [Comment] @connection(keyName: "byPost", fields: ["id"])
}

type Comment @model
  @key(name: "byPost", fields: ["postID", "content"]) {
  id: ID!
  postID: ID!
  content: String!
}
```

What I'm suggesting is it should also be able to support a uni-directional equivalent where it's not reqired to have a link back from the other side (e.g. `postId` above) but instead the relationship is just on the`Post` side.

The `Post` would have an array of UUIDs and the size limitations or other constraints do not appear to be a realistic constraint given a UUID is typically 128 bytes in length and how many UUIDs could be stored in an array under the 400kb limit.

While theoretically possible, I would suggest for over 99.9% of cases it would never be an issue.

For the 0.1% of cases either a `limit` parameter (e.g. `@connection(limit: 10000)`) could be supplied to provide a max array size that can be proactively policed, or I would suggest it's simply documented, if indeed that is even required, since it is solving a largely theoretical problem that can be tackled through good data modelling, and I don't see it being unique problem for uni-directional 1 to many relationships.

Requiring the other end of the connection to manage the relationship and so also requiring a separate GSI unfortunately doesn't fit a common data modelling pattern and forces me to manage the ids manually which means we cannot nest GraphQL queries.

**Comment by danrivett** [comment] 2021-01-11 21:49
Doing the maths 400kb could store 25,000 UUIDs without any other data, so I guess it's more possible than I first thought, which is what I think you are referring to, but I would still think people using the data model pattern wouldn't use it if that sort of number of UUIDs is a possibility. Certainly in the scenarios I would use this pattern for, it's not a consideration - e.g. an individual Team just isn't going to be part of thousands of Projects.
