### ISSUE TITLE
Appsync Console Schema auto populates @aws_iam even though the default authentication is aws_cognito_user_pools

### ISSUE THREAD

**Issue by vineethbhargavan** [aws-amplify/amplify-cli#8877] opened 2021-09-30 08:40 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:ap-southeast-2:888850479540:apps/d2efvo468a8rac

### Region

ap-southeast-2

### Amplify Console feature

Backend builds

### Describe the bug

Of late (last few days) its been observed that any change in schema.graphql , which gets auto built by the amplify backend -adds the directive @aws_iam and @aws_cognito_userpool to the schema  in Appsync (viewed in the appsync console).

**What we see now:**
`
type Activity @aws_iam
@aws_cognito_user_pools {
	id: ID!
	action: String!
`

**What was displayed a few days back:**
`
type Activity {
	id: ID!
	action: String!
`

**Note:** The above two are from the same schema.graphql. But the representation in Appsync console is different!!!
Also, I would like to mention that , while 95% of the entities in schema.graphql use the auth mode - cognito user pool, we have  a few entities and mutations using the @aws_iam e.g :
`
echoMutation(
    clientID: ID!
    entity: String!
    queryToCall: String!
    id: ID!
  ): Echo! @aws_iam
`

As a result of this change the default  cognito user pool authentication doesn't work  as  aws_iam auth mode takes precedence!- and all API calls fail!!!

So looking at the cloudformation templates, in the amplify backend folder, there is nothing suspicious.
- they all have default authentication as Cognito User Pool , with additional authentication as AWS_IAM
 e.g:
`
      "output": {
        "authConfig": {
          "defaultAuthentication": {
            "authenticationType": "AMAZON_COGNITO_USER_POOLS",
            "userPoolConfig": {
              "userPoolId": "authapp36xxx"
            }
          },
          "additionalAuthenticationProviders": [
            {
              "authenticationType": "AWS_IAM"
            }
          ]
        }
`

### Expected behavior

The Schema details in AppSync console should reflect the true nature of  the authentication schema - as defined in schema.graphql . 

@aws_iam directive should only be mentioned for those having @aws_iam in the schema.graphql and not for all the other entities/mutations.

### Reproduction steps

1. Have a schema.graphql with a combination of cognito user pool authentication and iam.
2. Git push the changes to Code commit - wait for amplify backend to build .
3. Upon successful build go to Appsync console and check the Schema of your respective api.
4.  You will notice a @aws_iam being tagged to all the entities/connections, inspite of not having explictly mapped to aws_iam authentication.

### Build Settings

```yaml
version: 1
applications:
  - backend:
      phases:
        build:
          commands:
            - '# Execute Amplify CLI with the helper script'
            - amazon-linux-extras install python3.8
            - ln -fs /usr/bin/python3.8 /usr/bin/python3
            - pip3.8 install pipenv
            - amplifyPush --simple
    frontend:
      phases:
        preBuild:
          commands:
            - yarn install
        build:
          commands:
            - yarn install
      artifacts:
        baseDirectory: src
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    appRoot: app
```

### Additional information

What we are seeing now:
![image](https://user-images.githubusercontent.com/12675696/135418210-ca498e67-0351-49e5-bfcd-116e2cb85bfd.png)

What we saw a few days back:
![image](https://user-images.githubusercontent.com/12675696/135418403-c486405e-3969-410a-b5da-0fbe1f047e66.png)

**Comment by vineethbhargavan** [comment] 2021-12-12 21:37
Any update on this?

**Comment by josefaidt** [comment] 2021-12-14 16:17
Hey @vineethbhargavan :wave: I'm currently looking into this. To clarify, what version of the Amplify CLI is being used locally and in the console? By default the console uses the latest version of the CLI, for reference. May you also paste the contents of the `amplify/cli.json` file?

**Comment by josefaidt** [comment] 2021-12-14 16:28
May you also share your schema.graphql file? Just the Activity model snippet with auth rules should suffice.

**Comment by vineethbhargavan** [comment] 2021-12-14 22:44
Hi @josefaidt ..thanks for looking into it. Below are the details requested.
- the amplify build is using the latest - 7.5.5.
Cli.json.
`{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": false,
      "improvepluralization": false,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": false,
      "enableiterativegsiupdates": true,
      "secondarykeyasgsi": false,
      "skipoverridemutationinputtypes": false,
      "transformerversion": 1,
      "suppressschemamigrationprompt": true
    },
    "frontend-ios": {
      "enablexcodeintegration": false
    },
    "auth": {
      "enablecaseinsensitivity": false,
      "useinclusiveterminology": false,
      "breakcirculardependency": false,
      "forcealiasattributes": false,
      "useenabledmfas": false
    },
    "codegen": {
      "useappsyncmodelgenplugin": false,
      "usedocsgeneratorplugin": false,
      "usetypesgeneratorplugin": false,
      "cleangeneratedmodelsdirectory": false,
      "retaincasestyle": false,
      "addtimestampfields": false,
      "handlelistnullabilitytransparently": false,
      "emitauthprovider": false,
      "generateindexrules": false,
      "enabledartnullsafety": false
    },
    "appsync": {
      "generategraphqlpermissions": false
    },
    "latestregionsupport": {
      "pinpoint": 0,
      "translate": 0,
      "transcribe": 0,
      "rekognition": 0,
      "textract": 0,
      "comprehend": 0
    },
    "project": {
      "overrides": true
    }
  }
}`

Activity model:
`type Activity
  @model
  @key(
    name: "byEnquiry"
    fields: ["enquiryID", "id"]
    queryField: "fetchActivityForEnquiry"
  )
  @key(
    name: "byPerson"
    fields: ["personId", "id"]
    queryField: "fetchActivityByPerson"
  )
  @auth(
    rules: [
      {
        allow: groups
        groups: ["clientAdmin", "friAdmin", "agentAdmin", "agentManagement"]
        queries: [get, list]
        mutations: [create, update, delete]
      }
      {
        allow: groups
        groups: ["clientTeamLeader", "clientAssessor"]
        queries: [get, list]
        mutations: [create, update]
      }
      {
        allow: groups
        groups: ["candidates"]
        queries: [get]
        mutations: [create]
      }
    ]
  ) {
  id: ID!
  action: String!
  textToDisplay: String

  createdAt: AWSDateTime!

  authorID: ID!
  author: Person @connection(fields: ["authorID"])

  clientID: ID!
  agentID: ID!

  enquiryID: ID!
  enquiry: Enquiry @connection(fields: ["enquiryID"])

  personId: ID!
  person: Person @connection(fields: ["personId"])

  priorityID: ID!
  priority: Priority @connection(fields: ["priorityID"])

  enquiryStateID: ID!
  enquiryState: EnquiryState @connection(fields: ["enquiryStateID"])

  assignedUserObj: Person @connection(fields: ["assignedUserID"])
  assignedUserID: ID!

  applicationID: ID!
  application: Application @connection(fields: ["applicationID"])

  applicationState: ApplicationState @connection(fields: ["applicationStateID"])
  applicationStateID: ID!

  notesID: ID!
  notes: Notes @connection(fields: ["notesID"])
}
`

Hope this helps.

**Comment by vineethbhargavan** [comment] 2021-12-14 22:47
Hi @josefaidt 

The amplify version is the default - latest - which i think is 7.5.5

Am attaching the cli.json and the activity model.
`
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": false,
      "improvepluralization": false,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": false,
      "enableiterativegsiupdates": true,
      "secondarykeyasgsi": false,
      "skipoverridemutationinputtypes": false,
      "transformerversion": 1,
      "suppressschemamigrationprompt": true
    },
    "frontend-ios": {
      "enablexcodeintegration": false
    },
    "auth": {
      "enablecaseinsensitivity": false,
      "useinclusiveterminology": false,
      "breakcirculardependency": false,
      "forcealiasattributes": false,
      "useenabledmfas": false
    },
    "codegen": {
      "useappsyncmodelgenplugin": false,
      "usedocsgeneratorplugin": false,
      "usetypesgeneratorplugin": false,
      "cleangeneratedmodelsdirectory": false,
      "retaincasestyle": false,
      "addtimestampfields": false,
      "handlelistnullabilitytransparently": false,
      "emitauthprovider": false,
      "generateindexrules": false,
      "enabledartnullsafety": false
    },
    "appsync": {
      "generategraphqlpermissions": false
    },
    "latestregionsupport": {
      "pinpoint": 0,
      "translate": 0,
      "transcribe": 0,
      "rekognition": 0,
      "textract": 0,
      "comprehend": 0
    },
    "project": {
      "overrides": true
    }
  }
}
`
Activity model 
`
type Activity
  @model
  @key(
    name: "byEnquiry"
    fields: ["enquiryID", "id"]
    queryField: "fetchActivityForEnquiry"
  )
  @key(
    name: "byPerson"
    fields: ["personId", "id"]
    queryField: "fetchActivityByPerson"
  )
  @auth(
    rules: [
      {
        allow: groups
        groups: ["clientAdmin", "friAdmin", "agentAdmin", "agentManagement"]
        queries: [get, list]
        mutations: [create, update, delete]
      }
      {
        allow: groups
        groups: ["clientTeamLeader", "clientAssessor"]
        queries: [get, list]
        mutations: [create, update]
      }
      {
        allow: groups
        groups: ["candidates"]
        queries: [get]
        mutations: [create]
      }
    ]
  ) {
  id: ID!
  action: String!
  textToDisplay: String

  createdAt: AWSDateTime!

  authorID: ID!
  author: Person @connection(fields: ["authorID"])

  clientID: ID!
  agentID: ID!

  enquiryID: ID!
  enquiry: Enquiry @connection(fields: ["enquiryID"])

  personId: ID!
  person: Person @connection(fields: ["personId"])

  priorityID: ID!
  priority: Priority @connection(fields: ["priorityID"])

  enquiryStateID: ID!
  enquiryState: EnquiryState @connection(fields: ["enquiryStateID"])

  assignedUserObj: Person @connection(fields: ["assignedUserID"])
  assignedUserID: ID!

  applicationID: ID!
  application: Application @connection(fields: ["applicationID"])

  applicationState: ApplicationState @connection(fields: ["applicationStateID"])
  applicationStateID: ID!

  notesID: ID!
  notes: Notes @connection(fields: ["notesID"])
}
`

**Comment by josefaidt** [comment] 2021-12-15 19:07
Hey @vineethbhargavan thank you for providing that information! Seeing this line in your `cli.json`

```
"transformerversion": 1,
```

Tells me we're using the GraphQL Transformer v1, which is also confirmed when seeing the older directives `@key` and `@connection`. If we run `amplify api gql-compile`, we can see in the built schema located at `amplify/backend/api/<resource-name>/build/schema.graphql` it will include those `@aws_iam` and user pools directive which explains why we are now seeing those directives in the AppSync Console. 

What is interesting is that at one point it looks like you may have had the schema built using the GraphQL Transformer v2. Although I have not been able to reproduce this behavior we can use `amplify migrate api` to migrate the GraphQL API to use the new transformer. For more information on the migration please see this doc https://docs.amplify.aws/cli/migration/transformer-migration/

A few follow-up questions:

- If you intend to remain on the GraphQL Transformer v1:
	- are you able to capture the CLI version that was used when we initially saw the lack of `@aws_iam` and `@aws_cognito_user_pools` directives in the schema?
	- are you able to log in and make GraphQL calls using Cognito User Pools?
- to clarify, are you seeing `@aws_iam` get added to _every_ model after running `amplify api gql-compile`?

**Comment by josefaidt** [comment] 2022-01-18 21:03
Hey @vineethbhargavan just wanted to follow-up to see if you'd had a chance to review the follow-up questions above?

**Comment by cjihrig** [comment] 2022-02-01 19:05
Closing due to a lack of followup, but we can revisit this issue if needed.

**Closed by cjihrig** 2022-02-01 19:05 UTC
Labels: graphql-transformer, pending-response, pending-triage, transferred
