### ISSUE TITLE
Amplify cli not detecting lambda changes

### ISSUE THREAD

**Issue by scottmanny** [aws-amplify/amplify-cli#12196] opened 2023-03-08 17:25 UTC
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.18.0

### Amplify CLI Version

10.8.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I did not make any manual changes to the cloud resources.

### Describe the bug

I have two amplify environments, uat and prod.  I created a lambda function in the uat environment using the amplify cli `amplify add function`.  After running amplify status I see the new lambda function.  I commit the change, then switch to the master branch.  Then I checkout the amplify prod environment.  Then I merge in the git uat branch.  I expect to see the new lambda function waiting to be created/pushed to my amplify prod environment, but it is simply missing.

I uploaded a YouTube video that perfectly shows the issue here: https://youtu.be/ZN5gjIKdoCY

Sorry for the white box that jumps all around.  I was hiding my api key.

### Expected behavior

After merging in the amplify changes in git to my amplify prod environment, I expected `amplify status` to result in detecting the new lambda function, which would then allow me to push it to prod.

### Reproduction steps

1. In amplify uat environment, create a new lambda function
2. Git commit amplify changes.
3. Switch to prod branch/environment
4. Merge in amplify changes
5. Erroneously see that the new lambda function is not waiting to be created/pushed.

### Project Identifier

84ad6fe6bf78f11c3b7a2443d1da93b0

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by HKJChen** [comment] 2023-03-09 18:56
After you do the merge, you might try running the amplify env checkout prod command again.  I don't think that amplify cli recognizes the change to backend-config.json when the file is changed through the git merge, but usually (for me), running env checkout command remedies that.

**Comment by scottmanny** [comment] 2023-03-09 20:28
Wow, that seemed to work.  Thanks! 

The process that I followed (using git merge) was from the amplify documentation here: https://docs.amplify.aws/cli/teams/overview/.  See the 3rd image and the verbiage around it.  

So that leads me to two quick questions.

1.  Is there a better way?
2. Is this expected to work more consistent in version 11 of the amplify-cli?

**Comment by HKJChen** [comment] 2023-03-09 20:35
I don't know of a better way.  This issue has been around since we started using amplify cli (version 4 or so).

**Comment by josefaidt** [comment] 2023-03-21 20:31
Hey @scottmanny :wave: thanks for raising this and apologies for the delay! This appears to be a duplicate of https://github.com/aws-amplify/amplify-cli/issues/8090, where we are required to run `amplify env checkout <target-env` before _and_ after `git merge`. This will populate the backend-config with the new Function to the gitignored `amplify-meta.json` file and the function will then be recognized in the target environment (more in-depth instructions can be found here https://github.com/aws-amplify/amplify-cli/issues/9790#issuecomment-1045258462)

**Comment by josefaidt** [comment] 2023-04-12 20:41
closing due to inactivity and in favor of tracking #8090

**Closed by josefaidt** 2023-04-12 20:41 UTC
Labels: bug, functions, pending-response, duplicate

**Comment by Nxtra** [comment] 2023-04-15 19:34
> Hey @scottmanny 👋 thanks for raising this and apologies for the delay! This appears to be a duplicate of #8090, where we are required to run `amplify env checkout <target-env` before _and_ after `git merge`. This will populate the backend-config with the new Function to the gitignored `amplify-meta.json` file and the function will then be recognized in the target environment (more in-depth instructions can be found here [#9790 (comment)](https://github.com/aws-amplify/amplify-cli/issues/9790#issuecomment-1045258462))

Is this in the docs already. Can't directly found it and haven't seen it yet. But I might have overlooked it.
If not, we should add it.
