### ISSUE TITLE
Amplify have multiple new Resources from Category "Parameters"

### ISSUE THREAD

**Issue by StefanVolkmer-WW** [aws-amplify/amplify-cli#11693] opened 2023-01-03 19:36 UTC
### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

14.19.3

### Amplify CLI Version

10.5.2

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

i tried to remove a dependency from one custom resource to the other one.
But i rejected this change in the meantime.

### Describe the bug

Today i updated my Amplify CLI from 9.1.0 to 10.5.2

i also refactored some resources.
But when i try to push now, i get informed that there are multiple new resources.

![image](https://user-images.githubusercontent.com/104902165/210428243-dd2b8059-6f24-4496-9183-934726ff6457.png)

Is this related to the new amplify upgrade?
Can someone give me some informations about this new category??

i completly rejected my changes in git, but when i run amplify status, the new resources comes again.

I'm a little bit afraid that i corrupted my environment now.

Can someone help me?
Kind Regards
Stefan

### Expected behavior

No unecassary Resources should be shown in amplify status

### Reproduction steps

amplify status

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment] 2023-01-03 21:09
Hey @StefanVolkmer-WW :wave: thanks for raising this! Would you mind sending us a copy of the contents of `amplify/team-provider-info.json` to amplify-cli@amazon.com? This will help us get a better understanding of the context

**Comment by ermrg** [comment] 2023-01-05 16:10
I am having the same issue. I also have amplify CLI  `10.5.2`.

**Comment by josefaidt** [comment] 2023-01-06 17:02
Hey @ermrg :wave: thanks for chiming in here! Do you experience the same issue if you upgrade to Amplify CLI 10.6+?

**Comment by josefaidt** [comment] 2023-01-06 18:51
Hey folks :wave: I was able to reproduce this issue using a project that was last built by Amplify CLI version 10.6.0, and running an older Amplify CLI version locally (9.1.0). These `parameters` in `amplify/backend/backend-config.json` were introduced in a more recent version of the CLI, and will not appear in the status list in CLI versions 10.6+

It is possible Amplify Hosting automated builds last built the project using `latest`, and subsequent `amplify pull` executions locally pulled these parameters in where the locally installed copy of the CLI was not able to hide the parameters from `status`.

To mitigate this issue, please upgrade your CLI locally with `amplify upgrade`

**Comment by salsa2k** [comment] 2023-01-15 02:25
I have the same issue. I upgrade to the latest version:
```
amplify --version
10.6.1
```

But I still getting:
```
┌────────────┬──────────────────────────────────────────────────────────────────┬───────────┬───────────────────┐
│ Category   │ Resource name                                                    │ Operation │ Provider plugin   │
├────────────┼──────────────────────────────────────────────────────────────────┼───────────┼───────────────────┤
│ Parameters │ AMPLIFY_function_projectPostConfirmation_deploymentBucketName    │ Create    │                   │
├────────────┼──────────────────────────────────────────────────────────────────┼───────────┼───────────────────┤
│ Parameters │ AMPLIFY_function_projectPostConfirmation_s3Key                   │ Create    │                   │
├────────────┼──────────────────────────────────────────────────────────────────┼───────────┼───────────────────┤
│ Auth       │ project                                                          │ No Change │ awscloudformation │
├────────────┼──────────────────────────────────────────────────────────────────┼───────────┼───────────────────┤
│ Auth       │ userPoolGroups                                                   │ No Change │ awscloudformation │
├────────────┼──────────────────────────────────────────────────────────────────┼───────────┼───────────────────┤
│ Storage    │ appassets                                                        │ No Change │ awscloudformation │
└────────────┴──────────────────────────────────────────────────────────────────┴───────────┴───────────────────┘
```

And still getting the same message.

**Comment by dral3x** [comment] 2023-01-24 10:37
Same issue with CLI version 10.6.2

**Comment by joekiller** [comment] 2023-01-31 21:06
I have  this problem as well.

I removed the "parameters" key from amplify/backend/backend-config.json, and amplify/backend/amplify-meta.json but that wasn't enough. I then updated the #current-cloud-backend.zip and backend-config.json in the bucket of the project's DeploymentBucket and pushed but the keys remain.

**Comment by ammar-kunaico** [comment] 2023-02-03 04:18
Facing the same problem. Did a successful `amplify push` and `amplify push --force` and it still shows up if I run `amplify status`

**Comment by josefaidt** [comment] 2023-02-03 23:15
Hey @salsa2k and folks in the thread :wave: after upgrading can you try running `amplify env checkout <current-env-name>`? These parameters were introduced in later versions of the CLI and passed into resources

**Comment by joekiller** [comment] 2023-02-17 14:45
I'm running 10.7.3 and after `amplify env checkout <my-env>` the artifacts are still there.

**Comment by josefaidt** [comment] 2023-02-23 20:04
Hey @joekiller are you seeing `Parameters` in your `amplify/backend/amplify-meta.json` file?

**Comment by joekiller** [comment] 2023-02-23 22:47
@josef I checked a bucket that built with cli 10.7.3 and I'm only seeing it
now in the backend-config.json and not in the amplify-meta.json

Sent via mobile

**Comment by u93** [comment] 2023-02-27 17:07
Running into a similar issue here... Thought I managed to solve it following some steps indicated here:

- https://github.com/aws-amplify/amplify-cli/issues/12097

But after doing a CLI modification to one of my functions to remove some env vars, not only I started to get the parameters again, but also now I'm unable to deploy to different environments due to the stack wanting to get the parameters and not getting them :(

- https://github.com/aws-amplify/amplify-cli/issues/12114

**Comment by joekiller** [comment] 2023-03-02 16:55
we've just committed them and moved on. annoying though yes.

**Comment by giuliotiseo** [comment] 2023-03-06 10:32
> Hey @salsa2k and folks in the thread 👋 after upgrading can you try running `amplify env checkout <current-env-name>`? These parameters were introduced in later versions of the CLI and passed into resources

Thanks, this works for me

**Comment by josefaidt** [comment] 2023-03-24 18:05
Hey @joekiller and folks in the thread. Are you still experiencing this?

**Comment by RyanRussell00** [comment] 2023-04-08 22:41
@josefaidt I'm still experiencing this

**Comment by ericlo23** [comment] 2023-04-12 09:44
I am facing a similar issue with Amplify version 11.0.3. In the beginning there are many parameters appear with operation `Create`. After doing some `amplify checkout` and `amplify push`, the `Create` become `Delete` and won't disappear.
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/5072364/231420318-d41d16bf-b8b5-4b64-9a33-5187e0663c79.png">

**Comment by chriswaterbury** [comment] 2023-05-07 22:56
I just started seeing this with the same Create becoming Delete after trying amplify env checkout <env>. Recently updated from 10.5.8 to 11.1.1. I see the parameters in amplify/backend-config.json and amplify/#current-cloud-backend/amplify-meta.json

**Comment by maziarzamani** [comment] 2023-05-17 17:06
Got same problem when moving from 10.8 to 12.0. What to do?

**Comment by josefaidt** [comment] 2023-05-17 17:24
Hey @chriswaterbury and @maziarzamani the Parameters that are printed in the status output are largely cosmetic and should not have an effect the project whether they show DELETE/CREATE, however they are supposed to be hidden and I can empathize with the concerns.

I've attempted to reproduce this by upgrading my CLI from 9.x to 12.x to no avail. @maziarzamani would you mind sending the project ID output from `amplify diagnose --send-report` to get a better idea of how the project is structured?

To workaround this issue you will need to remove the `parameters` block from `amplify/backend/amplify-meta.json`, then download the `#current-cloud-backend.zip` from your project's S3 deployment bucket, unzip, remove from `amplify-meta.json`, re-zip and re-upload, then `amplify env checkout <current-env-name>` will sync that to your local machine. From there you should not see the parameters in the status output 🎉

**Comment by maziarzamani** [comment] 2023-05-17 17:27
> 

Hey @josefaidt. Thank you for looking into this so promptly. As an engineer I tend to get a small heart attack when I see "DELETE", but I am more confident when you tell me that it is intentional.

The project ID is: 18de85a88a3a044d1924f966edae6682

Thanks for the workaround. I need to get this push going, can I safely push it and apply the workaround later?

**Comment by maziarzamani** [comment] 2023-05-17 17:34
@josefaidt , i was in the wrong branch, not sure if that matters, but nevertheless: f63982f559d2f4085b7b0785eb45f851

**Comment by josefaidt** [comment] 2023-07-03 20:07
Hey @maziarzamani apologies for the delay!

> I need to get this push going, can I safely push it and apply the workaround later?

Yes, after removing the parameters from the files noted you will be able to push successfully. The parameters unintentionally displayed in the status output are largely safe to ignore.

**Comment by josefaidt** [comment] 2023-07-03 20:08
Since the original issue has since been resolved I will close this thread. If you experience this after upgrading to a newer version of the CLI please file a [new bug report](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=pending-triage&projects=&template=1.bug_report.yaml)

**Closed by josefaidt** 2023-07-03 20:08 UTC
Labels: pending-response, pending-triage, platform-state
