### ISSUE TITLE
Issue cloning Amplify backend environment

### ISSUE THREAD

**Issue by ollieut** [aws-amplify/amplify-cli#10647] opened 2022-06-24 13:01 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.19.1

### Amplify CLI Version

9.0.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

There was a CloudFormation stack that was getting stuck and ROLLBACK.

I deleted the stack, which in turn deleted my "staging" backend environment.

### Amplify Categories

hosting

### Amplify Commands

env, push

### Describe the bug

In the AWS Amplify Console, I cloned my current live "release" branch with the name "staging". This cloning process creates a new environment but with "no enabled categories". ie no Authentication, Storage etc.

I then deleted the newly created environment and created the environment using the Amplify CLI using the command `amplify add env staging`. This added the environment as before, but when I tried to `amplify push` it failed with the below code.

🛑 An error occurred during the push operation: /
Cannot read property 'logicalId' of undefined

### Expected behavior

I expected the Amplify project to push up successfully to the "staging" environment with the correct enabled categories.

### Reproduction steps

I am unable to reproduce this issue as it seems specific to my current Amplify Project.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line

🛑 An error occurred during the push operation: /
Cannot read property 'logicalId' of undefined

```

</details>

### Additional information

My Amplify Project includes, 3 APIs (2 Rest, 1 GQL), s3 storage, and many lambdas.

**Comment by josefaidt** [comment] 2022-06-24 13:21
Hey @ollieut :wave: thanks for raising this! To clarify, was the CLI still aware of the "staging" environment you deleted in the AWS Console?

**Comment by ollieut** [comment] 2022-06-24 13:24
Hey @josefaidt the CLI was never aware of the staging environment that I created and then deleted in AWS console.

**Comment by josefaidt** [comment] 2022-06-24 13:27
Thanks @ollieut , to further clarify this "release" environment was cloned to "staging" which failed to initially deploy? From there you deleted the environment by deleting the CloudFormation stack? 

> There was a CloudFormation stack that was getting stuck and ROLLBACK. 
I deleted the stack, which in turn deleted my "staging" backend environment.

**Comment by ollieut** [comment] 2022-06-24 14:07
@josefaidt Apologies for the confusion. I originally had two backend environments, staging and release. Both of these environments were working as expected until a Cloud Formation stack got stuck at ROLLBACK and I deleted the stack which deleted the whole "staging environment".

That's when I attempted the actions detailed in the **Describe the bug** section of the ticket.

**Comment by josefaidt** [comment] 2022-06-24 17:08
Hey @ollieut thanks for clarifying! If you run `amplify env list` does it show the "staging" env?

**Comment by josefaidt** [comment] 2022-07-13 18:31
Hey @ollieut :wave: apologies for the delay here but thank you for sending that over! I was taking a look through it and noticed the zip archive did not include the `team-provider-info.json` file. Was that file intentionally omitted or are you missing that file?

**Comment by ollieut** [comment] 2022-07-14 09:07
Hey @josefaidt I can see the `team-provider-info.json` file in the zip I sent. I will send it over separately again to the amplify-cli email!

**Comment by josefaidt** [comment] 2022-07-15 19:03
Hey @ollieut thank you for sending that over! I was able to run `amplify init` on your project and receive the same error. It appears the Admin API resource is not generating its provider metadata including this `logicalId`. I've also attempted to update this resource in an attempt to generate this missing parameter to no avail, ultimately receiving:

```
🛑 Cannot read property 'setting' of undefined
```

Which is odd considering the path I was attempting to "update" has this key set on its path in `cli-inputs.json`

```
"permissions": {
	"setting": "private",
	"auth": [
		"read"
	]
}
```

Upon further inspection it appears the affected API resource is not being built with `amplify build` despite getting picked up in backend-config.json and amplify-meta.json. While I continue to investigate this with the team are there any additional details you can share about the steps taken prior to receiving this? How old is this project?

**Comment by adesito** [comment] 2022-09-19 13:07
Same here. I was creating a prod environment from my dev backend environment from the amplify aws console, but I get an error... no logs or something loke that.

![image](https://user-images.githubusercontent.com/34693266/191023813-505107bc-6886-4aac-89dc-5efba50015b5.png)
to
![image](https://user-images.githubusercontent.com/34693266/191023922-e661bd95-2394-4bb5-94e3-4f10f840dc16.png)

anything else. I create my dev environment with API, Authentification (Cognito) and a Lambda Function. All created from amplify cli. Always using amplify push. dev env works perfect backend and frontend.

**Comment by josefaidt** [comment] 2022-09-20 17:35
Hey @ollieut :wave: apologies for the delay here, but I wanted to follow up on this as we continue investigating the issue with creating a new environment in Amplify Hosting's console. I suspect there is a nuance with creating an environment with the same name that is causing the few resources to not generate their metadata properly, thus leading us to this error `cannot read property 'logicalId' of undefined`.

**Comment by ollieut** [comment] 2022-09-21 09:19
@josefaidt @adesito I solved this issue with the help of AWS support. I believe we ran through deleting stacks that were stuck in AWS CloudFormation.

**Comment by adesito** [comment] 2022-09-22 12:42
I think that in my application, the problem is with one lambda resolver as I have to configure a VPC access to a private subnet to a microservice and that configuration was made by hand as I don't know how to create the VPC link access with amplify cli

**Comment by josefaidt** [comment] 2022-09-22 15:16
Hey @ollieut I'm glad to hear that you're up and running. I'm going to use this issue to track efforts around the environment cloning functionality

**Comment by 0afcode** [comment] 2022-09-22 19:58
> Same here. I was creating a prod environment from my dev backend environment from the amplify aws console, but I get an error... no logs or something loke that.
> 
> ![image](https://user-images.githubusercontent.com/34693266/191023813-505107bc-6886-4aac-89dc-5efba50015b5.png) to ![image](https://user-images.githubusercontent.com/34693266/191023922-e661bd95-2394-4bb5-94e3-4f10f840dc16.png)
> 
> anything else. I create my dev environment with API, Authentification (Cognito) and a Lambda Function. All created from amplify cli. Always using amplify push. dev env works perfect backend and frontend.

I am also running into this same problem. I am trying to clone the prod backend environment in one of our apps from the aws console and it fails.

**Comment by 0afcode** [comment] 2022-09-22 19:58
> Same here. I was creating a prod environment from my dev backend environment from the amplify aws console, but I get an error... no logs or something loke that.
> 
> ![image](https://user-images.githubusercontent.com/34693266/191023813-505107bc-6886-4aac-89dc-5efba50015b5.png) to ![image](https://user-images.githubusercontent.com/34693266/191023922-e661bd95-2394-4bb5-94e3-4f10f840dc16.png)
> 
> anything else. I create my dev environment with API, Authentification (Cognito) and a Lambda Function. All created from amplify cli. Always using amplify push. dev env works perfect backend and frontend.

I am also running into this same problem. I am trying to clone the prod backend environment in one of our apps from the aws console and it fails.

**Comment by adesito** [comment] 2022-09-27 07:41
Reviewing the Amplify deployment log I get this:
![image](https://user-images.githubusercontent.com/34693266/192464180-0c0352c7-fa43-47e3-ac6b-2090acd1ceee.png)
but I have value in that env-var
![image](https://user-images.githubusercontent.com/34693266/192464432-165b746c-8c0b-4034-bcdf-1c925125ecac.png)

**Comment by cgaege** [comment] 2022-09-27 15:28
Running into the same issue when cloning a backend environment:

> Same here. I was creating a prod environment from my dev backend environment from the amplify aws console, but I get an error... no logs or something loke that.
> 
> ![image](https://user-images.githubusercontent.com/34693266/191023813-505107bc-6886-4aac-89dc-5efba50015b5.png) to ![image](https://user-images.githubusercontent.com/34693266/191023922-e661bd95-2394-4bb5-94e3-4f10f840dc16.png)
> 
> anything else. I create my dev environment with API, Authentification (Cognito) and a Lambda Function. All created from amplify cli. Always using amplify push. dev env works perfect backend and frontend.

**Comment by medinatochiajro-metergram** [comment] 2022-09-28 14:45
> Running into the same issue when cloning a backend environment:
> 
> > Same here. I was creating a prod environment from my dev backend environment from the amplify aws console, but I get an error... no logs or something loke that.
> > ![image](https://user-images.githubusercontent.com/34693266/191023813-505107bc-6886-4aac-89dc-5efba50015b5.png) to ![image](https://user-images.githubusercontent.com/34693266/191023922-e661bd95-2394-4bb5-94e3-4f10f840dc16.png)
> > anything else. I create my dev environment with API, Authentification (Cognito) and a Lambda Function. All created from amplify cli. Always using amplify push. dev env works perfect backend and frontend.

I am running into the same issue as well.

**Comment by josefaidt** [comment] 2022-11-02 00:21
Hey @medinatochiajro-metergram @cgaege :wave: apologies for the delay. Would you mind opening an issue on [aws-amplify/amplify-hosting](https://github.com/aws-amplify/amplify-hosting)? I'll close this issue as the original problem is now resolved, and will continue to track this with the efforts to improve multi-environment workflows

**Closed by josefaidt** 2022-11-02 00:21 UTC
Labels: investigating, hosting, platform, pending-triage, ops-multienv

**Comment by alpha-adam** [comment] 2023-12-20 12:59
I had the same problem, and removing analytics and notifications fixed it for me (I'm not sure which one cause the issue). I could easily clone the env from the Amplify console.
