### ISSUE TITLE
get query returns null but search query returns the correct record.

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-cli#3959] opened 2020-04-14 22:23 UTC
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

Search query will return one record, which is the record I am looking for

```graphql
{
  searchModel(filter: {
    id: {
      eq: "8ff0cdf9-e2f1-4f5f-b5d6-e97f05cb993b"
    }
  }) {
    items {
      id
    }
  }
}
```

but get query will return null

```graphql
{
  getModel(id: "8ff0cdf9-e2f1-4f5f-b5d6-e97f05cb993b") {
    id
  }
}
```

**Amplify CLI Version**

4.18.0

**To Reproduce**

I am unsure how to reproduce this, it simply happened out of nowhere which is very weird...

**Expected behavior**

Get query should return correct record.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

This is not applicable as I used the AppSync console to run those queries

**Additional context**

I'm thinking this might be related to this https://github.com/aws-amplify/amplify-cli/issues/3705

**Comment by aprilmintacpineda** [comment] 2020-04-14 23:13
Look like the record is not in the DynamoDB because when I tried to find the ID, it did not return any records. I am unsure how that happened.

**Comment by edwardfoyle** [comment] 2020-04-14 23:46
@aprilmintacpineda Can you provide more detail about your project configuration or detailed repro steps if possible? Without more information, there's not much we can investigate.

**Comment by aprilmintacpineda** [comment] 2020-04-15 01:11
@edwardfoyle I am very sorry but I also don't have enough details to figure out what may have happened and how to replicate it. The record was created last April 13 and I experienced the said issue on April 14 when I tried to get the record, I tried to figure it out before opening this issue and tried to ask around but couldn't find anything useful so I decided to open a ticket in hope that someone out there may have experienced the same issue... Very sorry, but I'm trying to figure out how to replicate it, if I find anything, I will definitely update this...

**Comment by edwardfoyle** [comment] 2020-04-15 19:39
@aprilmintacpineda Yes please let us know if you find any more details. A few questions that may help us debug:
1. Did this only happen once or it happens every time with that id?
2. Has it happened with other records, or just that one?
3. Was there ever a duplicate of this record entered or a record that was deleted and then another added with the same id?

**Comment by edwardfoyle** [comment] 2020-04-24 19:44
Closing due to lack of response. Please follow up below if you have more debugging info.

**Closed by edwardfoyle** 2020-04-24 19:44 UTC
Labels: pending-response, pending-triage
