### ISSUE TITLE
CLI tool doesn't update API authenticationType

### ISSUE THREAD

**Issue by volkanunsal** [aws-amplify/amplify-cli#6847] opened 2021-03-10 00:56 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v15.4.0

### Amplify CLI Version

4.44.0

### What operating system are you using?

Mac

### Amplify Categories

auth

### Amplify Commands

push

### Describe the bug

When I updated the `authenticationType` of the API under `backend/backend-config.json` file from `AWS_IAM` to `AMAZON_COGNITO_USER_POOLS`, it did not change the "Default Authorization Mode" of my AppSync API, as I expected it to do.

### Expected behavior

I expected the authorization mode to be changed to Amazon Cognito User Pools.

### Reproduction steps

1. I typed `amplify update api`
2. Selected Graphql
3. Selected "Walkthrough all configurations"
4. For "Choose the default authorization type for the API," selected "Amazon Cognito User Pool"
5. Selected "No, I am done"
6. I noted that the `authenticationType` was changed in backend-config.json
7. I typed `amplify push api`
8 . When the push was over, I checked AppSync console and noted that the Default Authorization Mode was still IAM.

### Log output

```
# Put your logs below this line

```

**Comment by attilah** [comment] 2021-03-10 17:49
@volkanunsal thanks for reporting this is a known issue that we are addressing, in the meantime you have to make at least a  whitespace modification to your schema to trigger an update of the API resource during push. 

Closing as it is a duplicate of #4914

**Closed by attilah** 2021-03-10 17:49 UTC
Labels: api-graphql, bug
