### ISSUE TITLE
amplify function update failing to update dependsOn

### ISSUE THREAD

**Issue by r0zar** [aws-amplify/amplify-cli#6086] opened 2020-12-06 22:39 UTC
**Describe the bug**
When updating a function and removing a layer, `amplify-meta.json` fails to remove Layer from dependsOn.

**Amplify CLI Version**
`4.37.1`

**To Reproduce**
1) create lambda and layer, attach layer to lambda.
2) attempt to `amplify remove function`, targeting the layer

**Expected behavior**
It should remove without error

**Screenshots**
![image](https://user-images.githubusercontent.com/4655474/101295125-4cc3c600-37e1-11eb-890b-30bd3199ad15.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/**Ubuntu**]
 - Node Version. `12`

**Additional context**
:baby_chick:

**Comment by kaustavghosh06** [comment] 2020-12-06 22:44
@r0zar The error in "Red" mentions that this layer has a dependency on the Lambda:AppSyncAuthorizer function. If you remove the layer, it'll have unintended implications on your resource in the project.
 Not able to get what the error you're trying to point out here is about.

**Comment by r0zar** [comment] 2020-12-06 22:46
> You might want to remove your AppSyncAuthorizer function first and then remove the lambda layer resource.

I did this. That's why I've raised it as a bug.

**Comment by r0zar** [comment] 2020-12-06 22:48
I've verified by manually removing it from `amplify-meta.json`, it will successful remove.
![image](https://user-images.githubusercontent.com/4655474/101295363-d9bb4f00-37e2-11eb-963a-ca06d1b15112.png)

**Comment by akshbhu** [comment] 2020-12-07 02:14
Hi @r0zar 

We have a PR that will fix this issue soon #6040

**Comment by kaustavghosh06** [comment] 2020-12-07 02:17
Closing this as a duplicate of #5845

**Closed by kaustavghosh06** 2020-12-07 02:17 UTC
Labels: Lambda layers, bug
