### ISSUE TITLE
@model @auth directives not returning data of the current user

### ISSUE THREAD

**Issue by yepes** [aws-amplify/amplify-cli#4338] opened 2020-05-20 13:31 UTC
**Amplify CLI Version** 
4.20.0

**What AWS Services are you utilizing?**
Cognito, APi, DynamoDB

**Provide additional details e.g. code snippets**

schema.graphql
```
type Todo @model @auth(rules: [
  {
    allow: owner,
    operations: [create, read, update, delete],
    identityClaim: "sub"
  }
]) {
  id: ID!
  name: String!
  description: String
  owner: String
}
```

I wan't to fetch the current user's todo's. Something like:

```
const todoData = await API.graphql(graphqlOperation(listTodos));
```

returns all todos. I'm a bit confused, since I guessed that @auth with the read operation was exactly for that. If I try to query for another todo which is not mine, I got it back without any error (which I expected wouldn't be possible).

Anyone can point me to the right direction?

Thanks

**Comment by attilah** [comment] 2020-05-20 22:34
@yepes when you check the given todo in DynamoDB what is the value in the owner field? Is that matches the sub of the currently logged in user?

When you test in AppSync Console do you get the same result as in your application?

**Comment by yepes** [comment] 2020-05-21 10:24
@attilah thanks for the answer

I'm at appsync -> myapp-dev -> Queries and logged is as one of my users. I checked my user sub in cognito and it maches with the one stored on dynamodb.

This query:
```
{
  listTodos{
  	items{
      name
      owner
    }
  }
}
```

returns 
```
{
  "data": {
    "listTodos": {
      "items": [
        {
          "name": "first one ",
          "owner": "8b55e2a3-5530-4fe8-a377-8e2532ee1200"
        },
        {
          "name": "second todo",
          "owner": "9f3bfdfe-d5b6-4afa-aae3-ec89773aad2e"
        },
        {
          "name": "third todo",
          "owner": "9f3bfdfe-d5b6-4afa-aae3-ec89773aad2e"
        }
      ]
    }
  }
}
```

the current user logged in in the console is 9f3bfdfe-d5b6-4afa-aae3-ec89773aad2e, so i guessed the response woldn't have to include the first one, as it's from another user.

**Comment by yepes** [comment] 2020-05-21 13:06
for testing purposes, I have cloned https://github.com/aws-samples/aws-amplify-graphql and the auth works as expected. I don't know where to check why mine is not

**Comment by attilah** [comment] 2020-05-21 21:21
@yepes I used your schema and was not able to reproduce this issue, it is a very basic use case that we're covering in out e2e tests as well, I tested with the latest version of the CLI and I can't see any regression there. As far as I can see you did not do anything wrong, but perhaps during the experiments something got out of state. I'd suggest to create a new project with the above schema and try to reproduce this behavior.

I'm closing the issue for now, if something new comes up or you can reproduce it starting from a clean slate, feel free to reopen it.

**Closed by attilah** 2020-05-21 21:21 UTC
Labels: @auth, graphql-transformer, question

**Comment by yepes** [comment] 2020-05-22 12:15
@attilah thanks for the reply. Will try to create the project again.

Thanks for your time ;)
