### ISSUE TITLE
Accidently removed amplify's s3 deployment bucket + NoSuchKey error with new API Key

### ISSUE THREAD

**Issue by regenrek** [aws-amplify/amplify-cli#3204] opened 2020-01-16 19:10 UTC
** Which Category is your question related to? **
deployment

** What AWS Services are you utilizing? **
S3

** Provide additional details e.g. code snippets **
* I accidentally removed S3 deployment bucket which amplify uses to deploy resources.

Same as here: https://github.com/aws-amplify/amplify-cli/issues/1441

What I did:

* Open `amplify\backend\amplify-meta.json` and look for the value of "DeploymentBucketName"
* Create a bucket in S3 with the value of "DeploymentBucketName"
```
aws s3api create-bucket --bucket mycoolapp-xxxxx-deployment --region eu-central-1 --create-bucket-configuration LocationConstraint=eu-central-1
```

* My API Key was outdated then I created a new in AWS Appsync and added it to the `aws-export` file. Also added it to `amplify-meta.json`

* amplify-meta.json
```
"GraphQLAPIKeyOutput": "NEW API KEY"
```

* parameters.json
```
I set   `"APIKeyExpirationEpoch": "-1"` 
```

```
amplify update api
# -> GraphQL
# -> no im done
```

```
amplify push
```

## Error

```
Fetching updates to backend environment: prod from the cloud.(node:80295) UnhandledPromiseRejectionWarning: NoSuchKey: The specified key does not exist.
```

**Comment by yuth** [comment] 2020-02-14 19:57
@regenrek Amplify CLI expects presences of a file called `#current-cloud-backend.zip`, at the root of your bucket. This file is zipped version od your `<proj-root>/amplify/#current-cloud-backend` folder. If you do have this folder present in your project, please zip it and upload it to the bucket. Please make sure you have backed up the entire project before doing anything as it would be hard to recover changes made to current-cloud-backend as the content from that file is not checked into the git. 

Once you have uploaded the file see if the deployment works.

__PS__: Please be sure to backup your data before doing a push as there is a possibility of data loss if the push fails

**Comment by raygerrard** [comment] 2020-02-17 05:29
@yuth this didn't work for me. When pushing you let get another error that amplify-meta.json could not be found but the file does exist locally at the path it states.

**Comment by regenrek** [comment] 2020-02-18 11:26
I ended up to "solve" this issue with creating a complete new environment and migrated my database. Everything else didn't work out. But @yuth thanks for the tip maybe it will help sometime if this happens again.

**Comment by raygerrard** [comment] 2020-02-18 11:41
I also had to create a new environment to get this working again. Is this a bug? A deploy should be able to recreate the bucket if it doesn't exist without having to create a new environment, is there any reason it would not be possible to recover from this situation without re-creation of the env? I removed the s3 bucket without realising it was still required when spring cleaning as I think others have.

**Comment by yuth** [comment] 2020-02-18 17:48
>  Is this a bug? A deploy should be able to recreate the bucket if it doesn't exist without having to create a new environment, is there any reason it would not be possible to recover from this situation without re-creation of the env?

This not a bug. Amplify CLI uses different workflow for initializing an environment and updating an initialized environment. The content in the bucket is also used by Amplify console to support `pull`.

We will have to do bit more research to confirm if this is doable without breaking support for all the current workflows . I am marking this as an enhancement and put it our backlog.

**Comment by josefaidt** [comment] 2022-11-22 21:45
Closing in favor of https://github.com/aws-amplify/amplify-cli/issues/10781

**Closed by josefaidt** 2022-11-22 21:45 UTC
Labels: feature-request, platform, pending-review
