### ISSUE TITLE
Be able to provide a custom elasticsearch instance ARN to be used rather than creating a new one

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-cli#8571] opened 2021-10-26 23:42 UTC
### Is this feature request related to a new or existing Amplify category?

api

### Is this related to another service?

AWS APPSYNC

### Describe the feature you'd like to request

Currently, when you do `amplify publish` on a new env, amplify will create a new elasticsearch instance, this can be problematic and can lead to having 4 or 5 different elasticsearch instances when you only need 2 (1 for dev envs, and one for production). We should be able to provide an ARN instead.

### Describe the solution you'd like

on `teams-provider-info.json`, we should be able to provide a `[env].categories.api[api-name].ElasticSearchArn` which will be the arn of the elasticsearch instance that we want to be used by this env.

### Describe alternatives you've considered

Nothing so far.

### Additional context

ElasticSearch instances are expensive, we have `dev`, `uat`, and `production`, what I want to achieve is just have one `c6g.xlarge.elasticsearch` instance for `dev` and `uat` and then one more `c6g.xlarge.elasticsearch` for `production`.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cjihrig** [comment] 2021-10-29 18:45
I'm going to close this as a duplicate of the request in #4591. Feel free to comment there with any additional information.

**Closed by cjihrig** 2021-10-29 18:45 UTC
Labels: feature-request, @searchable, extensibility
