### ISSUE TITLE
How Do I get UserPoolId, GraphQLAPIIdOutput, GraphQLAPIEndpointOutput in PostConfirmation Function

### ISSUE THREAD

**Issue by mightiesthero** [aws-amplify/amplify-cli#2699] opened 2019-11-07 03:47 UTC
**Which Category is your question related to?**

Usage Question

**Amplify CLI Version** 

3.17.0

**What AWS Services are you utilizing?**

Function (Post Confirmation)

**Provide additional details e.g. code snippets**
my goal:
I need to create user profile in database after user sign up

my requirements:
1. add permission to cognito-idp:AdminGetUser, appsync:GraphQL, 
1. access to GRAPHQLAPIENDPOINTOUTPUT

when I try to add permission using amplify-cli or using Fn::GetAtt in parameters.json
it's gonna error because of circular dependencies
auth depend-on "PostConfirmation"

for now my solutions for UserPoolId
1. hardcoded these
1. change auth cloudformation template directly

for GraphQLAPIIdOutput and GraphQLAPIEndpointOutput, I can only think using hardcoded

references #678, #621, #1185, #1099

I think these solutions not ideal

**Comment by kaustavghosh06** [comment] 2019-11-07 19:07
@mightiesthero Are you using Cognito for auth in your GraphQL API?

**Comment by mightiesthero** [comment] 2019-11-08 07:09
using IAM,  but I also need to get User Attributes

**Comment by BabyDino** [comment] 2019-11-11 13:55
I am running into the same issue. I've updated the function with `amplify function update` and added permissions to perform other resources (in my case I need the `GraphQLAPIIdOutput`) to target a `@model` DynamoDB Table.

I get the following error following a push:

```
Circular dependency between resources: [api<projectname>, UpdateRolesWithIDPFunctionOutputs, apiAdminQueries, function<projectname>PostConfirmation, auth<projectname>, functionAdminQueriesbc21d6ff, authuserPoolGroups, UpdateRolesWithIDPFunction]
An error occured during the push operation: Circular dependency between resources: [api<projectname>, UpdateRolesWithIDPFunctionOutputs, apiAdminQueries, function<projectname>PostConfirmation, auth<projectname>, functionAdminQueriesbc21d6ff, authuserPoolGroups, UpdateRolesWithIDPFunction]
```

I am trying to figure out where the dependency issues occur.

**Comment by kaustavghosh06** [comment] 2019-12-19 01:28
This is a duplicate of #1874.
Tracking this in #1874

**Closed by kaustavghosh06** 2019-12-19 01:28 UTC
Labels: auth, question
