### ISSUE TITLE
HostedUICustomResourceInputs Fails Pushing a New env

### ISSUE THREAD

**Issue by morgnism** [aws-amplify/amplify-cli#9173] opened 2021-12-01 19:27 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

brew

### If applicable, what version of Node.js are you using?

16.13.0

### Amplify CLI Version

7.4.5

### What operating system are you using?

Mac

### Amplify Categories

hosting

### Amplify Commands

add, env, push

### Describe the bug

Amplify doesn't create a new environment successfully because it fails to create `HostedUICustomResourceInputs`. After it failed to create, it also fails to delete that resource.

Notes:
* This is part of a migration effort
* The first new environment was pushed successfully to the new AWS account.
* Subsequent pushes for new environments fail with the same error
* Additional errors and CloudWatch logs provided in "Additional Notes"

### Expected behavior

Amplify push should successfully create a new environment.

### Reproduction steps

1. `amplify checkout env` to check the right env is active
2. `amplify end add`
3. `amplify push`

### GraphQL schema(s)

The log was too long and erased everything submitted the first time. Can provide on request.
<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

`amplify-cli errors`:
```bash
CREATE_FAILED      amplify-xxx-develop-114422-authxxxa9b56b11-KM0N0S276BVD AWS::CloudFormation::Stack Wed Dec 01 2021 11:49:52 GMT-0700 (Mountain Standard Time) The following resource(s) failed to create: [HostedUICustomResourceInputs].
...
DELETE_FAILED HostedUICustomResourceInputs Custom::LambdaCallout Wed Dec 01 2021 11:50:58 GMT-0700 (Mountain Standard Time) Received response status [FAILED] from custom resource. Message returned: See the details in CloudWatch Log Stream: 2021/12/01/[$LATEST]44957c2858b249cca431973acf2648a6 (RequestId: 7994a934-d1a6-434c-97dd-e0fae501e63a)
```

Then in CloudWatch:
```bash
2021-12-01T17:29:54.461Z	df3beb99-d66e-4af1-b8d3-89c61fd0a34e	INFO	Error: Domain not available
    at /var/task/index.js:1:1698
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

2021-12-01T17:29:54.480Z	df3beb99-d66e-4af1-b8d3-89c61fd0a34e	INFO	Response body:
 {
    "Status": "FAILED",
    "Reason": "See the details in CloudWatch Log Stream: 2021/12/01/[$LATEST]bcbfe8077a9541609635a9a949dc413f",
    "PhysicalResourceId": "2021/12/01/[$LATEST]bcbfe8077a9541609635a9a949dc413f",
    "StackId": "arn:aws:cloudformation:us-east-1:835808917490:stack/amplify-confmatch-develop-102113-authconfmatcha9b56b11-INNXX7IDWVTJ/05974b10-52cc-11ec-b95f-0a15421568b5",
    "RequestId": "35e5d2e0-f913-4fe3-90bf-81763d942f62",
    "LogicalResourceId": "HostedUICustomResourceInputs",
    "NoEcho": false,
    "Data": {
        "err": {}
    }
}

```

**Comment by josefaidt** [comment] 2021-12-01 19:31
Hey @morgnism :wave: thanks for raising this! To clarify, was the env created from the CLI using `amplify env add` then we attempted to `push`?

As a workaround, can you try running through `amplify update auth` and ensure all previously entered values are pre-populated, and accept all existing values to see if that alleviates the issue?

Marking as a duplicate bug https://github.com/aws-amplify/amplify-cli/issues/8149

**Comment by morgnism** [comment] 2021-12-01 19:57
Thanks for the quick reply @josefaidt. That didn't resolve my problem, unfortunately.

**Comment by josefaidt** [comment] 2021-12-01 20:14
Hey @morgnism thanks for clarifying! Re-reading the error in your original post I see `Error: Domain not available`, can you share the `amplify/backend/auth/<resource-name>/parameters.json` file omitting any sensitive information? Also, was this environment created using the `amplify env add` CLI command?

**Comment by morgnism** [comment] 2021-12-03 18:53
@josefaidt  Just one.

**Comment by josefaidt** [comment] 2021-12-03 20:34
Hey @morgnism can you confirm whether you were prompted for the 3rd party auth credentials when creating a new env? 
![image](https://user-images.githubusercontent.com/5033303/144669280-651b96bf-8360-40f9-8a4e-57c87cb5add3.png)

**Comment by morgnism** [comment] 2021-12-03 20:43
I used Access Keys and was NOT given the option for OAuth.

**Comment by josefaidt** [comment] 2021-12-03 20:46
@morgnism thanks for clarifying! What social providers do you have enabled on your auth resource?

**Comment by morgnism** [comment] 2021-12-03 20:51
@josefaidt none at the moment. We're just using cognito for auth.

**Comment by josefaidt** [comment] 2021-12-03 20:58
Ahh interesting, would you mind sharing the contents of the `cli-inputs.json` file at `amplify/backend/auth/<resource-name>/cli-inputs.json`, omitting any sensitive information?

**Comment by morgnism** [comment] 2021-12-03 21:01
```json
{
  "version": "1",
  "cognitoConfig": {
    "identityPoolName": "xxxa9b56b11_identitypool_a9b56b11",
    "allowUnauthenticatedIdentities": false,
    "resourceNameTruncated": "xxxa9b56b11",
    "userPoolName": "xxxa9b56b11_userpool_a9b56b11",
    "autoVerifiedAttributes": [
      "email"
    ],
    "mfaConfiguration": "OFF",
    "mfaTypes": [
      "SMS Text Message"
    ],
    "smsAuthenticationMessage": "Your authentication code is {####}",
    "smsVerificationMessage": "<p>Your verification code is {####}</p></br><p>You can enter your code at https://develop.ddmp1s9w0j37k.amplifyapp.com/signup/verify </p>",
    "emailVerificationSubject": "Your verification code",
    "emailVerificationMessage": "<p>Your verification code is {####}</p></br><p>You can enter your code at <a href=\"https://develop.ddmp1s9w0j37k.amplifyapp.com/signup/verify\">Verify</a></p>",
    "defaultPasswordPolicy": false,
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": [],
    "requiredAttributes": [
      "email"
    ],
    "aliasAttributes": [],
    "userpoolClientGenerateSecret": true,
    "userpoolClientRefreshTokenValidity": 30,
    "userpoolClientWriteAttributes": [
      "email"
    ],
    "userpoolClientReadAttributes": [
      "email"
    ],
    "userpoolClientLambdaRole": "xxxa9b56b11_userpoolclient_lambda_role",
    "userpoolClientSetAttributes": false,
    "authSelections": "identityPoolAndUserPool",
    "resourceName": "xxxa9b56b11",
    "useDefault": "defaultSocial",
    "userPoolGroupList": [
      "confmatch"
    ],
    "usernameAttributes": [
      "email"
    ],
    "hostedUI": true,
    "hostedUIDomainName": "confmatch",
    "hostedUIProviderMeta": "[]",
    "authProvidersUserPool": [],
    "authRoleArn": {
      "Fn::GetAtt": [
        "AuthRole",
        "Arn"
      ]
    },
    "unauthRoleArn": {
      "Fn::GetAtt": [
        "UnauthRole",
        "Arn"
      ]
    },
    "breakCircularDependency": false,
    "useEnabledMfas": false,
    "dependsOn": [],
    "hostedUIProviderCreds": "[]",
    "oAuthMetadata": "{\"AllowedOAuthFlows\":[\"code\"],\"AllowedOAuthScopes\":[\"phone\",\"email\",\"openid\",\"profile\",\"aws.cognito.signin.user.admin\"],\"CallbackURLs\":[\"http://localhost:4200/\"],\"LogoutURLs\":[\"http://localhost:4200/\"]}",
    "serviceName": "Cognito"
  }
}
```

**Comment by josefaidt** [comment] 2021-12-03 21:24
Thanks @morgnism I also tried to use that domain listed and am unable to reproduce. I think it's worth noting I did run into this the very first time I attempted to reproduce, where we also noticed there was the wrong UserPool ID referenced in the CloudWatch logs for this failed Lambda Callout, however I have not since been able to reproduce. Are you seeing something similar where the wrong UserPool ID is referenced in the CloudWatch logs? Does it fail to push on subsequent attempts?

**Comment by morgnism** [comment] 2021-12-03 21:34
@josefaidt I wasn't aware you'd try to run the json. I had removed the name of the app and replaced the name. Here's the working version of the same json.
```json
{
  "version": "1",
  "cognitoConfig": {
    "identityPoolName": "confmatcha9b56b11_identitypool_a9b56b11",
    "allowUnauthenticatedIdentities": false,
    "resourceNameTruncated": "confmaa9b56b11",
    "userPoolName": "confmatcha9b56b11_userpool_a9b56b11",
    "autoVerifiedAttributes": [
      "email"
    ],
    "mfaConfiguration": "OFF",
    "mfaTypes": [
      "SMS Text Message"
    ],
    "smsAuthenticationMessage": "Your authentication code is {####}",
    "smsVerificationMessage": "<p>Your verification code is {####}</p></br><p>You can enter your code at https://develop.ddmp1s9w0j37k.amplifyapp.com/signup/verify </p>",
    "emailVerificationSubject": "Your verification code",
    "emailVerificationMessage": "<p>Your verification code is {####}</p></br><p>You can enter your code at <a href=\"https://develop.ddmp1s9w0j37k.amplifyapp.com/signup/verify\">Verify</a></p>",
    "defaultPasswordPolicy": false,
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": [],
    "requiredAttributes": [
      "email"
    ],
    "aliasAttributes": [],
    "userpoolClientGenerateSecret": true,
    "userpoolClientRefreshTokenValidity": 30,
    "userpoolClientWriteAttributes": [
      "email"
    ],
    "userpoolClientReadAttributes": [
      "email"
    ],
    "userpoolClientLambdaRole": "confmaa9b56b11_userpoolclient_lambda_role",
    "userpoolClientSetAttributes": false,
    "authSelections": "identityPoolAndUserPool",
    "resourceName": "confmatcha9b56b11",
    "useDefault": "defaultSocial",
    "userPoolGroupList": [
      "confmatch"
    ],
    "usernameAttributes": [
      "email"
    ],
    "hostedUI": true,
    "hostedUIDomainName": "confmatch",
    "hostedUIProviderMeta": "[]",
    "authProvidersUserPool": [],
    "authRoleArn": {
      "Fn::GetAtt": [
        "AuthRole",
        "Arn"
      ]
    },
    "unauthRoleArn": {
      "Fn::GetAtt": [
        "UnauthRole",
        "Arn"
      ]
    },
    "breakCircularDependency": false,
    "useEnabledMfas": false,
    "dependsOn": [],
    "hostedUIProviderCreds": "[]",
    "oAuthMetadata": "{\"AllowedOAuthFlows\":[\"code\"],\"AllowedOAuthScopes\":[\"phone\",\"email\",\"openid\",\"profile\",\"aws.cognito.signin.user.admin\"],\"CallbackURLs\":[\"http://localhost:4200/\"],\"LogoutURLs\":[\"http://localhost:4200/\"]}",
    "serviceName": "Cognito"
  }
}
```

**Comment by morgnism** [comment] 2021-12-03 22:49
@josefaidt I did see it fail Lambda Callout, but the only error I noticed was the domain error I pasted in the issue description (under "Additional Notes"). I think I sent you the wrong json tho. I was attempting another env and I sent you the wrong `cli-inputs.json` file. However, I already deleted the failing env so I don't have the json for that one just the CloudWatch errors. Since the failing env was a clone, here's the one that's working:
```json
{
  "version": "1",
  "cognitoConfig": {
    "identityPoolName": "confmatcha9b56b11_identitypool_a9b56b11",
    "allowUnauthenticatedIdentities": false,
    "resourceNameTruncated": "confmaa9b56b11",
    "userPoolName": "confmatcha9b56b11_userpool_a9b56b11",
    "autoVerifiedAttributes": [
      "email"
    ],
    "mfaConfiguration": "OFF",
    "mfaTypes": [
      "SMS Text Message"
    ],
    "smsAuthenticationMessage": "Your authentication code is {####}",
    "smsVerificationMessage": "<p>Your verification code is {####}</p></br><p>You can enter your code at https://develop.ddmp1s9w0j37k.amplifyapp.com/signup/verify </p>",
    "emailVerificationSubject": "Your verification code",
    "emailVerificationMessage": "<p>Your verification code is {####}</p></br><p>You can enter your code at <a href=\"https://develop.ddmp1s9w0j37k.amplifyapp.com/signup/verify\">Verify</a></p>",
    "defaultPasswordPolicy": false,
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": [],
    "requiredAttributes": [
      "email"
    ],
    "aliasAttributes": [],
    "userpoolClientGenerateSecret": true,
    "userpoolClientRefreshTokenValidity": 30,
    "userpoolClientWriteAttributes": [
      "email"
    ],
    "userpoolClientReadAttributes": [
      "email"
    ],
    "userpoolClientLambdaRole": "confmaa9b56b11_userpoolclient_lambda_role",
    "userpoolClientSetAttributes": false,
    "authSelections": "identityPoolAndUserPool",
    "resourceName": "confmatcha9b56b11",
    "useDefault": "defaultSocial",
    "userPoolGroupList": [
      "confmatch"
    ],
    "usernameAttributes": [
      "email"
    ],
    "hostedUI": true,
    "hostedUIDomainName": "confmatch",
    "hostedUIProviderMeta": "[]",
    "authProvidersUserPool": [],
    "authRoleArn": {
      "Fn::GetAtt": [
        "AuthRole",
        "Arn"
      ]
    },
    "unauthRoleArn": {
      "Fn::GetAtt": [
        "UnauthRole",
        "Arn"
      ]
    },
    "breakCircularDependency": false,
    "useEnabledMfas": false,
    "dependsOn": [],
    "hostedUIProviderCreds": "[]",
    "oAuthMetadata": "{\"AllowedOAuthFlows\":[\"code\"],\"AllowedOAuthScopes\":[\"phone\",\"email\",\"openid\",\"profile\",\"aws.cognito.signin.user.admin\"],\"CallbackURLs\":[\"http://localhost:4200/\"],\"LogoutURLs\":[\"http://localhost:4200/\"]}",
    "serviceName": "Cognito"
  }
}
```

**Comment by josefaidt** [comment] 2021-12-03 22:56
Hey @morgnism no worries! I was really using that file's contents as a reference to set up an auth resource on my end with the same settings. When I originally encountered the "Domain not available..." error, then a couple lines down I was seeing an error about missing User Pool by some ID that was not the User Pool attached to the project.

**Comment by morgnism** [comment] 2021-12-03 23:10
@josefaidt Oh I see that now looking at it again.
```bash
2021-12-01T17:31:39.461Z	c286f4c3-0b7b-4841-92af-1571fd7ef723	INFO	ResourceNotFoundException: User pool us-east-1_mi7CZPAT9 does not exist.
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ResourceNotFoundException',
  time: 2021-12-01T17:31:39.439Z,
  requestId: 'd16c62bf-780d-4557-b1e1-a8183f00ecfc',
  statusCode: 400,
  retryable: false,
  retryDelay: 84.08217583530282
}
```

**Comment by josefaidt** [comment] 2021-12-03 23:14
Ahh thank you for taking a look, that's very similar to what I was also experiencing! I'm guessing that user pool ID is in fact, not the user pool associated with this app, correct?

**Comment by josefaidt** [comment] 2022-01-04 17:01
Hey @morgnism have you continuously experienced this issue when attempting to push to a new environment? Despite being able to reproduce initially in `us-east-1` I have not been able to reproduce again, and am curious if this was related to the recent outage.

**Comment by josefaidt** [comment] 2022-01-21 19:55
Closing due to inactivity. @morgnism if you are still experiencing this issue please reply back to this thread and we can re-open to investigate further 🙂

**Closed by josefaidt** 2022-01-21 19:55 UTC
Labels: auth, pending-close-response-required, pending-triage
