### ISSUE TITLE
Different error behavior for Amplify mock vs real API: "Cannot return null for non-nullable field"

### ISSUE THREAD

**Issue by Nxtra** [aws-amplify/amplify-cli#6450] opened 2021-01-21 10:55 UTC
**Describe the bug**
Mock API throws error on non-nullable field of nested object when connection does not exist, real API works fine.

**Amplify CLI Version**
4.41.2

**To Reproduce**
* I use the following `schema.graphql`: 
```
type Writer @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  name: String!
  addressLine: String
  blogs: [Blog] @connection(keyName: "byWriter", fields: ["id"])
}

type Blog
  @model
  @auth(rules: [{ allow: owner }])
  @key(name: "byWriter", fields: ["blogWriterId"]) {
  id: ID!
  name: String
  posts: [Post] @connection(keyName: "byBlog", fields: ["id"])
  blogWriterId: ID
  writer: Writer @connection
}

type Post
  @model
  @auth(rules: [{ allow: owner }])
  @key(name: "byBlog", fields: ["blogID"]) {
  id: ID!
  title: String!
  blogID: ID!
  blog: Blog @connection(fields: ["blogID"])
}
```

*  I run `amplify push --y` to deploy the API
* I start a local mock of the API: `amplify mock`
* Try to execute the following query locally: 
```
mutation createBlog {
  createBlog(input: {name: "Nick's blog"}) {
    id
    name
    posts {
      items {
        blogID
        id
        title
        owner
      }
    }
    writer {
      addressLine
      name
      owner
      id
    }
    owner
  }
}
```
This results in an error:
```
{
  "data": {
    "createBlog": {
      "id": "e8dba61a-1049-4212-9396-ac4d4c5e4123",
      "name": "Nick's blog",
      "posts": {
        "items": []
      },
      "writer": null,
      "owner": "Nxtra"
    }
  },
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Writer.name.",
      "locations": [
        {
          "line": 30,
          "column": 7
        }
      ],
      "path": [
        "createBlog",
        "writer",
        "name"
      ]
    }
  ]
}
```
* Execute the same query in the AppSync console (cloud).
This gives me the following result (no error):
```
{
  "data": {
    "createBlog": {
      "id": "0fa3cb68-949b-499b-b308-7f54235fc469",
      "name": "Nick's blog",
      "posts": {
        "items": []
      },
      "writer": null,
      "owner": "nxtra"
    }
  }
}
```

**Expected behavior**
I expect the mock API to behave without errors as well.

**Screenshots**
On the left the response in the AppSync console, on the left the local Amplify mock API.
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/36597466/105341063-f539b800-5bde-11eb-9a86-2495804e494a.png">

**Desktop:**

- OS: Mac
- Node Version: v12.20.1

**Log output**
Include any relevant log output under `~/.amplify/logs/amplify-cli-<issue-date>.log`
I don't see anything relevant here:
```
2021-01-21T10:38:14.639Z|info : amplify version core  {"version":true,"yes":false}
2021-01-21T10:38:19.986Z|info : amplify mock mock
2021-01-21T10:39:49.026Z|info : amplify mock mock
```

**Related issue**
This seems to be related but no solution was provided yet: https://github.com/aws-amplify/amplify-cli/issues/2248

**Comment by Nxtra** [comment] 2021-01-21 13:31
I have not found the source of the problem but it is connected to the way you configure `auth`. 

If the schema would use `@auth(rules: [{ allow: private }])` then it would have worked. 

```
type Writer @model @auth(rules: [{ allow: private }]) {
  id: ID!
  name: String!
  addressLine: String
  blogs: [Blog] @connection(keyName: "byWriter", fields: ["id"])
}

type Blog
  @model
  @auth(rules: [{ allow: private }])
  @key(name: "byWriter", fields: ["blogWriterId"]) {
  id: ID!
  name: String
  posts: [Post] @connection(keyName: "byBlog", fields: ["id"])
  blogWriterId: ID
  writer: Writer @connection
}

type Post
  @model
  @auth(rules: [{ allow: private }])
  @key(name: "byBlog", fields: ["blogID"]) {
  id: ID!
  title: String!
  blogID: ID!
  blog: Blog @connection(fields: ["blogID"])
}
```

But I'd like it to work with `@auth(rules: [{ allow: private }])`

**Comment by ammarkarachi** [comment] 2021-01-26 21:45
@Nxtra I believe there is a second PR that addresses this issue, it's been merged should be available within the next release
https://github.com/aws-amplify/amplify-cli/pull/5153

**Comment by alexkates** [comment] 2021-02-10 16:09
It appears that https://github.com/aws-amplify/amplify-cli/releases/tag/v4.42.0 contains this, however I am still seeing this issue.

**Comment by lostcodingsomewhere** [comment] 2021-02-16 08:20
i am having this same issue on 4.43.0, any advise?

**Comment by lostcodingsomewhere** [comment] 2021-02-16 23:19
For anyone running into this issue (on v4.43.0), here's a workaround (pretty hackey but will suffice for now):

replace all of your `API.graphql` with the following helper:

```
const graphqlAPI = async (
   options,
   additionalHeaders?: {
      [key: string]: string;
   }
): Promise<any> => {
   try {
      return await API.graphql(options, additionalHeaders);
   } catch (err) {
      const realErrors = err.errors.filter(
         (e) => !e.message.startsWith('Cannot return null for non-nullable')
      );
      if (realErrors.length > 0) {
         console.log(`THROWING GRAPHQL ERROR`);
         throw err;
      } else {
         const realDataResult = { data: err.data };
         return realDataResult;
      }
   }
};
```

**Comment by cwinters8** [comment] 2021-02-21 23:46
I am having the opposite problem compared to the the OP's original issue - my local mocked API works fine, but subscriptions are failing on the deployed API due to the error "Cannot return null for non-nullable type: 'String' within parent 'Form' (/onCreateForm/name)". The 'Form' item is created successfully and can be subsequently queried - it is only the subscription throwing the error. Here is the full output from the subscription:
```json
{
  "data": {
    "onCreateForm": null
  },
  "errors": [
    {
      "message": "Cannot return null for non-nullable type: 'String' within parent 'Form' (/onCreateForm/name)",
      "path": [
        "onCreateForm",
        "name"
      ]
    }
  ]
}
```
Please let me know if there is any other information that might be helpful in debugging this issue. It seems to be fairly new - I wasn't having this issue with my deployed API as early as about a week ago.

**Comment by cwinters8** [comment] 2021-02-21 23:56
This comment fixed me: https://github.com/aws-amplify/amplify-cli/issues/5542#issuecomment-731758272

Adding the field in the return value from the mutation allows the subscription access to the field. I'm still not sure why it works fine in the locally mocked API and not the deployed one. But I'll take it!

**Comment by alexkates** [comment] 2021-02-22 00:41
I think this needs to be looked into. Amplify mock hasn't worked for us for weeks.

**Comment by patrickcze** [comment] 2021-02-22 16:04
Also having this same issue on incoming subscriptions: 

```
DataStore - Skipping incoming subscription. Messages: Cannot return null for non-nullable type: 'AWSTimestamp' within parent 'LocationV1' (/onCreateLocationV1/_lastChangedAt)
```

The comment mentioned by @cwinters8 does not seem to resolve anything in my case as my subscriptions and mutations already have identical values.

**Comment by dmost714** [comment] 2021-02-26 20:43
I'm running v4.44.1 and this issue is still alive and kicking.

The easiest way to reproduce it is to simply query a record that doesn't exist with a non-nullable in the expected results.

**Comment by alexkates** [comment] 2021-02-26 20:47
Yup same here. I upgrade the CLI every release and this is the first thing I check. 

Haven't been able to mock in weeks. Really frustrating.

**Comment by kaustavghosh06** [comment] 2021-03-19 20:12
Fix for this issue was merged and released in the latest version of the CLI.
@alexkates Could you please confirm?

**Closed** 2021-03-19 20:12 UTC
Labels: bug, mock, pending-release

**Comment by alexkates** [comment] 2021-03-19 21:55
Confirmed ty!
