### ISSUE TITLE
Deploy Spring Cloud Function with amplify to AWS Lambda 

### ISSUE THREAD

**Issue by marcelweigle** [aws-amplify/amplify-cli#7860] opened 2021-08-03 06:17 UTC
**Which Category is your question related to?**
amplify CLI, AWS Lambda, Spring Cloud Function

**What AWS Services are you utilizing?**
Amplify, lambda

**Provide additional details e.g. code snippets**

Hello, I have trouble deploying the Spring Cloud Function Demo App from their docs with AWS Amplify. I used amplify add function, choose java and then copy/paste the Spring Cloud Function Demo App from their docs into my amplify Project. Error is about ClassDefNotFound -> cant't find the generic Spring Cloud Function Handler (org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest). 

As I am not able to get it working I have the general question if Amplify supports deploying Spring Cloud Function to AWS Lambda. Also if this is the case, are there any examples?

Thank's in regards

**Comment by jhockett** [comment] 2021-08-03 17:11
Hi @marcelweigle, we support the Java runtime for Lambda functions, so if the Java code you copy in is valid, then it should work. However, we don't specifically have support for Spring Cloud Function.

Can you share the demo code that you tried to make work?

**Comment by marcelweigle** [comment] 2021-08-03 17:21
I have a working spring lambda build with Maven. Does amplify only support Gradle? Or can I somehow use Maven?

**Comment by marcelweigle** [comment] 2021-08-03 18:39
The Demo Code is from the Spring Cloud Function Documentation. GitHub link is here: https://github.com/spring-cloud/spring-cloud-function/tree/main/spring-cloud-function-samples/function-sample-aws

**Comment by marcelweigle** [comment] 2021-08-05 06:30
Hi @jhockett I successful deployed my spring cloud function with amplify. However I can't use amplify mock. I am getting the following error:

`    '  .   ____          _            __ _ _\n' +
    " /\\\\ / ___'_ __ _ _(_)_ __  __ _ \\ \\ \\ \\\n" +
    "( ( )\\___ | '_ | '_| | '_ \\/ _` | \\ \\ \\ \\\n" +
    ' \\\\/  ___)| |_)| | | | | || (_| |  ) ) ) )\n' +
    "  '  |____| .__|_| |_|_| |_\\__, | / / / /\n" +
    ' =========|_|==============|___/=/_/_/_/\n' +
    ' :: Spring Boot ::                        \n' +
    '\n' +
    '06:29:25.951 [main] INFO shim.Invoker - Starting Invoker using Java 11.0.11 on C02C820ZMD6R with PID 94530 (/Users/weigle/.amplify/lib/amplify-java-function-runtime-provider/resources/localinvoke/lib/localinvoke.jar started by weigle in /Users/weigle/Documents/Bitbucket/angelreporting/amplify/backend/function/dealStatus)\n' +
    '06:29:25.952 [main] DEBUG shim.Invoker - Running with Spring Boot, Spring\n' +
    '06:29:25.952 [main] INFO shim.Invoker - No active profile set, falling back to default profiles: default\n' +
    '06:29:25.952 [main] DEBUG org.springframework.boot.SpringApplication - Loading source class angeldesk.FunctionConfiguration\n' +
    '06:29:25.996 [main] DEBUG org.springframework.context.annotation.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@6440112d\n' +
    "06:29:26.001 [main] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'org.springframework.context.annotation.internalConfigurationAnnotationProcessor'\n" +
    '06:29:26.040 [main] ERROR org.springframework.boot.SpringApplication - Application run failed\n' +
    'java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.\n' +
    '\tat org.springframework.util.Assert.notEmpty(Assert.java:470)\n' +
    '\tat org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getCandidateConfigurations(AutoConfigurationImportSelector.java:180)\n' +
    '\tat org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getAutoConfigurationEntry(AutoConfigurationImportSelector.java:123)\n' +
    '\tat org.springframework.boot.autoconfigure.AutoConfigurationImportSelector$AutoConfigurationGroup.process(AutoConfigurationImportSelector.java:434)\n' +
    '\tat org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGrouping.getImports(ConfigurationClassParser.java:879)\n' +
    '\tat org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.processGroupImports(ConfigurationClassParser.java:809)\n' +
    '\tat org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorHandler.process(ConfigurationClassParser.java:780)\n' +
    '\tat org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:193)\n' +
    '\tat org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331)\n' +
    '\tat org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247)\n' +
    '\tat org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311)\n' +
    '\tat org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112)\n' +
    '\tat org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746)\n' +
    '\tat org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564)\n' +
    '\tat org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)\n' +
    '\tat org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)\n' +
    '\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:338)\n' +
    '\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)\n' +
    '\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)\n' +
    '\tat org.springframework.cloud.function.adapter.aws.FunctionInvoker.start(FunctionInvoker.java:120)\n' +
    '\tat org.springframework.cloud.function.adapter.aws.FunctionInvoker.<init>(FunctionInvoker.java:67)\n' +
    '\tat java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n' +
    '\tat java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)\n' +
    '\tat java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n' +
    '\tat java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)\n' +
    '\tat shim.Invoker.<init>(Invoker.java:41)\n' +
    '\tat shim.Invoker.main(Invoker.java:25)\n' +
    '06:29:26.045 [main] DEBUG org.springframework.context.annotation.AnnotationConfigApplicationContext - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@6440112d, started on Thu Aug 05 06:29:25 UTC 2021',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
`

This is my build.gradle file

`buildscript {
    ext {
        springBootVersion = '2.5.3'
        wrapperVersion = '1.0.17.RELEASE'
    }
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url "https://repo.spring.io/snapshot" }
        maven { url "https://repo.spring.io/milestone" }
        maven { url "https://plugins.gradle.org/m2/" }
    }
    dependencies {
        classpath "com.github.jengelman.gradle.plugins:shadow:6.1.0"
        classpath("org.springframework.boot.experimental:spring-boot-thin-gradle-plugin:${wrapperVersion}")
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        classpath("io.spring.gradle:dependency-management-plugin:1.0.8.RELEASE")
    }
}

apply plugin: 'java'
apply plugin: 'maven'
apply plugin: 'eclipse'
apply plugin: 'com.github.johnrengelman.shadow'
apply plugin: 'org.springframework.boot'
apply plugin: 'org.springframework.boot.experimental.thin-launcher'
apply plugin: 'io.spring.dependency-management'

group = 'angeldesk.dealStatus'
version = '0.0.1'
sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenLocal()
    mavenCentral()
    maven { url "https://repo.spring.io/snapshot" }
    maven { url "https://repo.spring.io/milestone" }
}

ext['reactor.version'] = "3.1.7.RELEASE"

assemble.dependsOn = [shadowJar, thinJar]

jar {
    manifest {
        attributes 'Main-Class': 'angeldesk.FunctionConfiguration'
    }
}

thinJar {
    manifest {
        attributes 'Main-Class': 'angeldesk.FunctionConfiguration'
    }
}

import com.github.jengelman.gradle.plugins.shadow.transformers.*

shadowJar {
    dependencies {
        exclude(dependency("org.springframework.cloud:spring-cloud-function-web:3.1.3"))
    }
    manifest {
        attributes 'Main-Class': 'angeldesk.FunctionConfiguration'
        attributes 'Start-Class': 'angeldesk.FunctionConfiguration'
    }
    getDestinationDirectory().set(new File(projectDir, "./build/libs"))
    getArchiveFileName().set("latest_build.jar")
    // Required for Spring
    mergeServiceFiles()
    append 'META-INF/spring.handlers'
    append 'META-INF/spring.schemas'
    append 'META-INF/spring.tooling'
    transform(PropertiesFileTransformer) {
        paths = ['META-INF/spring.factories']
        mergeStrategy = "append"
    }
}

configurations {
    testCompile.extendsFrom(compileOnly)
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-function-dependencies:3.1.3"
    }
}

dependencies {
    compile('org.springframework.cloud:spring-cloud-function-adapter-aws:3.1.3')
    implementation 'org.springframework.cloud:spring-cloud-starter-function-web:3.1.3'
    compile('org.springframework.boot:spring-boot-configuration-processor:2.5.3')
    compileOnly("com.amazonaws:aws-lambda-java-events:3.9.0")
    compileOnly("com.amazonaws:aws-lambda-java-core:1.2.1")
    testCompile('org.springframework.boot:spring-boot-starter-test:2.5.3')
}

task buildZip(type: Zip) {
    from compileJava
    from processResources
    into('lib') {
        from configurations.runtimeClasspath
    }
    archiveFileName = 'latest_build.zip'
    destinationDirectory = file("$buildDir/distributions")

    from "$buildDir/libs/latest_build.jar"
}
build.dependsOn buildZip`

**Comment by jhockett** [comment] 2021-08-05 22:30
Glad to hear you were able to deploy your Lambda function @marcelweigle! Since the original issue is addressed, I'm going to close this issue.

I'm not sure what's happening with mock, but I suggest looking into this line: `'java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.'`

If you continue having issues with mock, please open a new issue with a minimal reproduction.

**Closed by jhockett** 2021-08-05 22:30 UTC
Labels: question, functions
