### ISSUE TITLE
How to integrate a python lambda using aws-amplify

### ISSUE THREAD

**Issue by artista7** [aws-amplify/amplify-cli#1074] opened 2019-03-20 11:34 UTC
Im currently using cra with amplify-cli for aws backend services like cognito, appsync, lambda and storage.
I have a requirement to integrate a flask app (maybe using lambda) to my existing application.

Can you guide me on how to process using already existing cloudformation script initialized by amplify, so that it could be used in CI/CD using amplify service also.

Thanks
Shubham Gupta

**Comment by kaustavghosh06** [comment] 2019-03-22 20:43
@artista7 You could use the Amplify Console for your CI/CD needs. Please take a look at https://aws.amazon.com/amplify/console/

cc @swaminator

**Comment by artista7** [comment] 2019-03-28 09:47
I am using amplify console for CI/CD. My main issue is is it possible to configure lambda written in python using existing amplify project? As of now i am able write lambdas in js only

**Comment by kaustavghosh06** [comment] 2019-03-29 20:15
No, we do not support. But I'll add this as a feature request.

**Comment by artista7** [comment] 2019-04-05 20:57
Hey Kaustuv, that would be awesome if you do!

**Comment by artista7** [comment] 2019-04-15 11:41
Hi @kaustavghosh06, how soon can we expect this functionality?

**Comment by artista7** [comment] 2019-04-24 10:09
@kaustavghosh06, Any updates?

**Comment by ambientlight** [comment] 2019-04-24 10:27
@artista7: what you can do now is the following.

Enable `@http` directive which is not yet available in release version of amplify-cli.
https://github.com/aws-amplify/amplify-cli/issues/84#issuecomment-483737268

Then if you have an available flask endpoint you can hit it via a following declaration in you graphql schema:

```graphql
Type Query {
    myFlaskAPI(route: String!): [ExpectedResponse] @http(url:"https://jsonplaceholder.typicode.com/:route")
}
```

> My main issue is is it possible to configure lambda written in python using existing amplify project?

For flask app in lambda one reasonable option to go with https://github.com/Miserlou/Zappa for deployment, it can smoothly integrate with your CI as you can use a single command to update your deployment based on your configuration defined in `zappa_settings.json`. In you CI it can look just like:

```
zappa update prod 
./node_modules/.bin/amplify publish --yes
```

**Comment by artista7** [comment] 2019-04-29 17:16
@ambientlight I will have a look at Zappa. Thanks

**Comment by kaustavghosh06** [comment] 2019-10-11 04:15
Closing, since this is a duplicate of #156

**Closed by kaustavghosh06** 2019-10-11 04:15 UTC
Labels: enhancement, functions
