### ISSUE TITLE
Function lambda layer dependencies are not removed

### ISSUE THREAD

**Issue by half2me** [aws-amplify/amplify-cli#6249] opened 2020-12-24 00:56 UTC
**Describe the bug**
Once a function has a lambda layer configured, removing it does not remove it as a dependency. This means a lambda layer can never be deleted if it has ever been configured to be used in a function. Even if the function no longer uses the lambda layer, it still acts like it is a dependency.

**Amplify CLI Version**
4.40.1

**To Reproduce**
1. Create a new lambda layer with `amplify add function`
2. Create a new function with `amplify add function`
3. Configure the function to use the layer with `amplify update function`
4. Configure the function to not use any layers with: `amplify update function`
5. Even though the function now does not use the layer, it will still have dependencies to it.
6. Try to remove the lambda layer with `amplify remove function` It will not allow you to remove it: `Resource cannot be removed because it has a dependency on another resource`

**Expected behavior**
Removing a lambda layer from the function should remove all references to it.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. 12.20.0

**Additional context**
Files which still incorrectly list the layer as a dependency of the function:
- `backend-config.json`
- `amplify-meta.json`
- `function-cloudformation-template`
If I manually remove these references, `amplify remove function` deletes the layer without any issues.

**Comment by jhockett** [comment] 2020-12-24 03:28
Closing as duplicate of https://github.com/aws-amplify/amplify-cli/issues/5961.

**Closed by jhockett** 2020-12-24 03:28 UTC
