### ISSUE TITLE
Field level auth is incompatible with composite keys key1#key2 in V2 transformer

### ISSUE THREAD

**Issue by ThomasRooney** [aws-amplify/amplify-cli#9755] opened 2022-02-14 13:15 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

16.13.2

### Amplify CLI Version

7.6.14

### What operating system are you using?

Mac/Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

N/A

### Amplify Categories

auth

### Amplify Commands

push

### Describe the bug

Composite keys `key1#key2` cause models with field-level auth to fail Create/Update Mutation interactions with a graphql error `message: "Unauthorized on [vmId#startTime]"`. Found after migration from the V1 to V2 transformer.

In particular, through inspecting the generated resolvers, given the following example graphql schema [1]:

```graphql
type StrippedExample @model
@auth(rules: [
    {allow: owner, operations: [create, update, read, delete]},
    {allow: owner, identityClaim: "custom:teamId", ownerField: "groupOwner", operations: [create, update, read, delete]},
    {allow: private, provider: iam, operations: [create, update, read, delete]}
])
{
    id: ID! @primaryKey
    startTime: AWSDateTime! @index(name: "ByStartTime")
    status: Status! @index(name: "ByStatus", queryField: "ByStatus", sortKeyFields: ["vmId", "startTime"]) @index(name: "ByStatusUpdatedAt", queryField: "ByStatusUpdatedAt", sortKeyFields: ["updatedAt"])
    vmId: String!
    runnerId: ID @auth(rules: [
        {allow: owner, operations: [read]},
        {allow: owner, identityClaim: "custom:teamId", ownerField: "groupOwner", operations: [read]},
        {allow: private, provider: iam, operations: [create, update, read, delete]}
    ])
    updatedAt: AWSDateTime!
    owner: String @index(name: "ByOwner")
    groupOwner: String @index(name: "ByGroupOwner", queryField: "ByGroupOwner")
}
```

The composite field in `Mutation.createStrippedExample.preAuth.2.req.vtl` is configured

```vtl
...
#if( $hasSeenSomeKeyArg )
  $util.qr($ctx.args.input.put("vmId#startTime","${mergedValues.vmId}#${mergedValues.startTime}"))
#end
...
```

But this is not referenced in the allowedFields In `Mutation.createStrippedExample.auth.1.req.vtl`

```vtl
#set( $inputFields = $util.parseJson($util.toJson($ctx.args.input.keySet())) )
...
  #set( $ownerAllowedFields0 = ["id","startTime","status","vmId","updatedAt","owner","groupOwner","_version","_deleted","_lastChangedAt"] )
```

Which then causes the graphql interaction to fail:

```
message: "Unauthorized on [vmId#startTime]"
```

From the later bit of `Mutation.createStrippedExample.auth.1.req.vtl`

```
...
  #set( $deniedFields = $util.list.copyAndRemoveAll($inputFields, $allowedFields) )
  #if( $deniedFields.size() > 0 )
    $util.error("Unauthorized on ${deniedFields}", "Unauthorized")
  #end
...
```

### Expected behavior

Having a composite key in a model should not cause field-level auth to fail.

### Reproduction steps

1. Create a model with the schema segment [1] within.
2. Attempt to make any create/update mutations to that model in the appsync console.
3. Observe the error message `Unauthorized on [vmId#startTime]`

### Additional information

Workaround 1: Monkey patch such that compound keys are removed from field-level auth. E.g. in `@aws-amplify/graphql-auth-transformer/lib/resolvers/mutation.create`

```ts
  totalAuthExpressions.push(
    iff(and([not(ref(IS_AUTHORIZED_FLAG)), ref(`${ALLOWED_FIELDS}.isEmpty()`)]), ref('util.unauthorized()')),
    iff(
      not(ref(IS_AUTHORIZED_FLAG)),
      compoundExpression([
        set(ref('nonCompoundKeys'), raw('[]')),
        forEach(ref('item'), ref('inputFields'), [
          iff(
            not(methodCall(ref('item.contains'), str('#'))),
            methodCall(ref('util.qr'), methodCall(ref('nonCompoundKeys.add'), ref('item')))
          ),
        ]),
        set(
          ref(DENIED_FIELDS),
          methodCall(ref('util.list.copyAndRemoveAll'), ref('nonCompoundKeys'), ref(ALLOWED_FIELDS))
        ),
        iff(
          ref(`${DENIED_FIELDS}.size() > 0`),
          methodCall(ref('util.error'), str(`Unauthorized on \${${DENIED_FIELDS}}`), str('Unauthorized'))
        ),
      ])
    )
  );
```

Workaround 2: Find/Replace across VTL resolvers:

```ts
  const transformed = data
    .replace(
      '  #set( $deniedFields = $util.list.copyAndRemoveAll($inputFields, $allowedFields) )',
      `  #set( $nonCompoundKeys = [] )
  #foreach( $item in $inputFields )
    #if( !$item.contains("#") )
      $util.qr($nonCompoundKeys.add($item))
    #end
  #end
  #set( $deniedFields = $util.list.copyAndRemoveAll($nonCompoundKeys, $allowedFields) )
`
    )
    .replace(
      '  #foreach( $deniedField in $util.list.copyAndRemoveAll($inputFields, $allowedFields) )',
      `  #set( $nonCompoundKeys = [] )
  #foreach( $item in $inputFields )
    #if( !$item.contains("#") )
      $util.qr($nonCompoundKeys.add($item))
    #end
  #end
  #foreach( $deniedField in $util.list.copyAndRemoveAll($nonCompoundKeys, $allowedFields) )`
    );
```

**Comment by ThomasRooney** [comment] 2022-02-14 13:17
Potentially related: #9666

**Comment by josefaidt** [comment] 2022-04-19 21:08
Hey @ThomasRooney :wave: thanks for raising this and apologies for the delay!! I _really_ appreciate the details you have included here, however I was not able to reproduce using the provided example and steps. Are you still experiencing this issue? 

<img width="988" alt="image" src="https://user-images.githubusercontent.com/5033303/164101055-92aa8858-a22b-4413-ac4a-d2113f9f3bb7.png">

**Comment by josefaidt** [comment] 2022-04-29 21:48
Hey @ThomasRooney :wave: are you still experiencing this issue?

**Comment by ThomasRooney** [comment] 2022-04-30 15:28
Hi @josefaidt -- I can see this as fixed when I upgrade my amplify package versions to the latest: and I can now drop my workaround

**Comment by josefaidt** [comment] 2022-05-04 00:38
Hey @ThomasRooney glad to hear you are back up and running 🙌 with this information I will close this issue for now, however if you run into this again please do not hesitate to reply back to this thread! From there we can re-open to investigate further 🙂

**Closed by josefaidt** 2022-05-04 00:38 UTC
Labels: pending-close-response-required, pending-triage, graphql-transformer-v2
