### ISSUE TITLE
Searching enum fields with @searchable - type not generated but it works

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/amplify-cli#3541] opened 2020-03-01 16:46 UTC
**Describe the bug**
when using the @searchable directive on a model, the cli generates inputs for the `searchX` queries, but it does not generate types for enum fields, so for example the `id` field is ok to filter with, but a field which is enum cannot be filtered because the types for filtering are not generated. 

After adding manually my enum field to the `SearchXFilterInput` and giving it the same type as a regular string input, I tried to do my query and it worked, it filtered the results with the given enum.

**Amplify CLI Version**
4.13.3

**To Reproduce**
Create a model, with at least one field that is an enum.
Add the @searchable directive to that model.
Create some data.
Manually go to the schema page in the AppSync console, and add to your `SearchXFilterInput` your enum field and give it the type of a string filter.
Try to query your data and filter it with the enum field.
You will receive filtered data with your enum field taken into consideration in the filtering process.

**Expected behavior**
All fields that exist in ElasticSearch will exist on the search input in AppSync. 
AppSync should generate a filter type for each enum, or make it a string filter like I did.

**Comment by SwaySway** [comment] 2020-03-02 22:06
Closing as this is a duplicate of #3248

**Closed by SwaySway** 2020-03-02 22:06 UTC

**Comment by idanlo** [comment] 2020-03-03 05:43
@SwaySway that issue hasn’t had any comments since it has been created, more than one month ago

**Comment by nniirraavv** [comment] 2020-12-29 06:41
Getting the same issue,
```
type Note
  @model
  @searchable
{
  id: ID!
  userID: ID!
  textContent: String
  htmlContent: String
  imageFilename: String
  noteType: NoteTypeEnum!
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
}
enum NoteTypeEnum {
  text
  annotation
}
```
@idanlo Thank you for your quick solution, But Adding manual searchField into the schema from the Amplify console is a temporary solution. It should be generated automatically.
@amplify Team Please look at the issue.
@SwaySway
