### ISSUE TITLE
Mock Resolver CF doesn't interpret 'RequestMappingTemplate' or 'ResponseMappingTemplate' 

### ISSUE THREAD

**Issue by nateiler** [aws-amplify/amplify-cli#2402] opened 2019-09-25 05:11 UTC
When mocking the API, the resolver 'RequestMappingTemplate' and 'ResponseMappingTemplate' CloudFormation are not taken into consideration; it appears only the file base ("RequestMappingTemplateS3Location" and "ResponseMappingTemplateS3Location") approach is supported.  Did a little investigation which led me to:

https://github.com/aws-amplify/amplify-cli/blob/c9829e22aed7082798605f23aeff978ac1fa85f6/packages/amplify-util-mock/src/CFNParser/appsync-resource-processor.ts#L156

The CloudFormation Spec:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-resolver.html

My assumption is, this should also apply to Function Configurations:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-functionconfiguration.html

Here is an example of my Resolver CF:

```
"CreateEntityResolver": {
            "Type": "AWS::AppSync::Resolver",
            "Properties": {
                "ApiId": {
                    "Ref": "AppSyncApiId"
                },
                "FieldName": "createEntity",
                "TypeName": "Mutation",
                "Kind": "PIPELINE",
                "PipelineConfig": {
                    "Functions": [
                        {
                            "Fn::GetAtt": [
                                "CreateEntityFunction",
                                "FunctionId"
                            ]
                        },
                        {
                            "Fn::GetAtt": [
                                "UpsertEntityPropertiesFunction",
                                "FunctionId"
                            ]
                        }
                    ]
                },
                "RequestMappingTemplate": {
                    "Fn::Join": [
                        "\n",
                        [
                            {
                                "Fn::Sub": [
                                    "$util.qr($ctx.stash.put(\"tableName\", \"${tableName}\"))",
                                    {
                                        "tableName": {
                                            "Fn::Join": [
                                                "-",
                                                [
                                                    "EntityProperty",
                                                    {
                                                        "Ref": "AppSyncApiId"
                                                    },
                                                    {
                                                        "Ref": "env"
                                                    }
                                                ]
                                            ]
                                        }
                                    }
                                ]
                            },
                            "{}"
                        ]
                    ]
                },
                "ResponseMappingTemplate": "$util.toJson($ctx.result)"
            },
            "DependsOn": [
                "CreateEntityFunction",
                "UpsertEntityPropertiesFunction"
            ]
        }

```

**Comment by yuth** [comment] 2019-09-26 17:48
This was reported in #2306 and fixed in #2355 and the change was released in Amplify CLI 3.10.0. If you are still facing this issue after installing the latest version please feel free to re-open/comment on this issue

**Comment by nateiler** [comment] 2019-09-26 17:52
This one is a little different.

This one is referring to not being able to define the template inline when mocking (currently only file base is supported).

**Comment by jwoehrle** [comment] 2020-04-01 15:24
I'm running into a similar (the same?) issue when trying to run `amplify mock api` with a custom resolve and an inline request-/responsetemplate.

The mock fails to start up with the error message:
```
Failed to start API Mock endpoint SyntaxError: Unexpected token u in JSON at position 0
```

Obviously this error message is not very helpful. However I traced back the problem to:
https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-util-mock/src/CFNParser/resource-processors/appsync.ts#L181-L182

The problem is that I cannot change to S3Location as I have to inject a CF Ref into the inline template. I need the Ref to the env in order to be able to construct the tablename for a Transactional Dynamo Write (https://github.com/aws-amplify/amplify-cli/issues/1946#issuecomment-536469005)

```
amplify --version
4.17.2
```

**Comment by yuth** [comment] 2020-04-01 17:05
@jwoehrle could you open a new issue for this.

**Comment by jwoehrle** [comment] 2020-04-02 06:04
Hi @yuth 

sure thing. I created: https://github.com/aws-amplify/amplify-cli/issues/3834

**Comment by yuth** [comment] 2020-05-14 04:16
https://github.com/aws-amplify/amplify-cli/commit/56fdd0057a6ecfbd320f2a3f8b0858959bbe750e should fix this.

**Closed by yuth** 2020-05-14 04:16 UTC
Labels: enhancement, mock
