### ISSUE TITLE
Unable to Add Analytics

### ISSUE THREAD

**Issue by YuantongL** [aws-amplify/amplify-cli#11148] opened 2022-10-08 04:57 UTC
### Describe the bug

Unable to add Analytics, showing error 
```
Template format error: Unresolved resource dependencies [PinpointFunction, LambdaExecutionRole] in the Resources block of the template
```
when "push"

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. add analytics via "amplify add analytics"
2. "amplify push"
3. push failed and observe error in cloudformation
```

### Expected behavior

Successfully add analytics service to Amplify project

### Amplify Framework Version

1.28.0

### Amplify Categories

Analytics

### Dependency manager

Swift PM

### Swift version

5.7

### CLI version

10.0.0

### Xcode version

14.0.1

### Relevant log output

```shell
ResourceNotReady: Resource is not in the state stackUpdateComplete
2022-10-08T04:48:10.645Z|info : amplify-provider-awscloudformation.aws-cfn.getStackEvents.cfnModel.describeStackEvents([{"StackName":"[***]rmation:us-[***]st-[***]31:stack/[***]ify-[***]app-[***]lop-[***]658/[***]f8b0-[***]c3-[***]ec-[***]07-[***]2c8f1"}])
2022-10-08T04:54:50.851Z|info : amplify version core  {"version":true,"yes":false}
```

### Is this a regression?

No

### Device

simulator

### iOS Version

16.0

**Comment by ykethan** [comment] 2022-10-12 15:27
Hey @YuantongL , thank you for reaching. I was unable to reproduce the issue utilizing the following steps.

1. `amplify init` to create a new app
2. `amplify add analytics` to add the pinpoint resource
 ```
? Select an Analytics provider Amazon Pinpoint
? Provide your pinpoint resource name: pinpointapp
Adding analytics would add the Auth category to the project if not already added.
? Apps need authorization to send analytics events. Do you want to allow guests and unauthenticated users to send analytics events? (we recommend you allow this when getting star
ted) Yes
```
3. `amplify add function` to with advanced settings.
```
? Select the categories you want this function to have access to: analytics
? Select the operations you want to permit on pinpointapp: create, read, update
```
4. `amplify push` to push the application.
But did not observe any errors. 

Does the replication steps align with your use case? It would be great if you could provide us some additional information and reproduction steps (please feel free in adding screenshots).

**Comment by YuantongL** [comment] 2022-10-15 19:17
Hello @ykethan! My project is an existing project, not a brand new one so there could be difference there.
Here I have more info to help you understand the issue:
- This is a live screenshot on command line
<img width="1290" alt="Screen Shot 2022-10-15 at 3 11 31 PM" src="https://user-images.githubusercontent.com/10422762/196004081-0817403e-9b72-4625-81ae-1a2c6fe6b1fd.png">

- This is a copy of my `pinpoint-cloudformation-template.json` after I use `amplify add analytics`
```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "{\"createdOn\":\"Mac\",\"createdBy\":\"Amplify\",\"createdWith\":\"10.0.0\",\"stackType\":\"analytics-Pinpoint\",\"metadata\":{}}",
  "Parameters": {
    "appName": {
      "Type": "String"
    },
    "appId": {
      "Type": "String",
      "Default": "NONE"
    },
    "roleName": {
      "Type": "String"
    },
    "cloudformationPolicyName": {
      "Type": "String"
    },
    "cloudWatchPolicyName": {
      "Type": "String"
    },
    "pinpointPolicyName": {
      "Type": "String"
    },
    "authPolicyName": {
      "Type": "String"
    },
    "unauthPolicyName": {
      "Type": "String"
    },
    "authRoleName": {
      "Type": "String"
    },
    "unauthRoleName": {
      "Type": "String"
    },
    "authRoleArn": {
      "Type": "String"
    },
    "env": {
      "Type": "String"
    }
  },
  "Metadata": {
    "AWS::CloudFormation::Interface": {
      "ParameterGroups": [
        {
          "Label": {
            "default": "Creating pinpoint app"
          },
          "Parameters": [
            "appName"
          ]
        }
      ]
    }
  },
  "Conditions": {
    "ShouldCreatePinpointApp": {
      "Fn::Equals": [
        {
          "Ref": "appId"
        },
        "NONE"
      ]
    },
    "ShouldNotCreateEnvResources": {
      "Fn::Equals": [
        {
          "Ref": "env"
        },
        "NONE"
      ]
    }
  },
  "Resources": {
    "LambdaExecutionRole": {
      "Condition": "ShouldCreatePinpointApp",
      "Type": "AWS::IAM::Role",
      "Properties": {
        "RoleName": {
          "Fn::If": [
            "ShouldNotCreateEnvResources",
            {
              "Ref": "roleName"
            },
            {
              "Fn::Join": [
                "",
                [
                  {
                    "Ref": "roleName"
                  },
                  "-",
                  {
                    "Ref": "env"
                  }
                ]
              ]
            }
          ]
        },
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              },
              "Action": [
                "sts:AssumeRole"
              ]
            }
          ]
        },
        "Policies": [
          {
            "PolicyName": {
              "Ref": "pinpointPolicyName"
            },
            "PolicyDocument": {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "mobileanalytics:*",
                    "mobiletargeting:*"
                  ],
                  "Resource": "*"
                }
              ]
            }
          },
          {
            "PolicyName": {
              "Ref": "cloudformationPolicyName"
            },
            "PolicyDocument": {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "cloudformation:*"
                  ],
                  "Resource": "*"
                }
              ]
            }
          }
        ]
      }
    },
    "LambdaCloudWatchPolicy": {
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyName": {
          "Ref": "cloudWatchPolicyName"
        },
        "Roles": [
          {
            "Ref": "LambdaExecutionRole"
          }
        ],
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
              ],
              "Resource": {
                "Fn::Sub": [
                  "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${lambdaName}:log-stream:*",
                  {
                    "lambdaName": {
                      "Ref": "PinpointFunction"
                    }
                  }
                ]
              }
            }
          ]
        }
      }
    },
    "PinpointFunction": {
      "Type": "AWS::Lambda::Function",
      "Condition": "ShouldCreatePinpointApp",
      "Properties": {
        "Code": {
          "ZipFile": {
            "Fn::Join": [
              "\n",
              [
                "const response = require('cfn-response');",
                "const aws = require('aws-sdk');",
                "exports.handler = function(event, context) {",
                "    if (event.RequestType == 'Delete') {",
                "      const stackID = event.StackId;",
                "      const cloudFormationClient = new aws.CloudFormation({ apiVersion: '2016-12-01', region: event.ResourceProperties.region });",
                "      cloudFormationClient.describeStacks({ StackName: stackID }).promise()",
                "        .then(describeStacksOutput => {",
                "          let appId;",
                "          if (describeStacksOutput.Stacks && describeStacksOutput.Stacks.length > 0) {",
                "            const { Outputs } = describeStacksOutput.Stacks[0];",
                "            const appIdOutput = Outputs.find((output)=>{ return output.OutputKey === 'Id'});",
                "            appId = appIdOutput ? appIdOutput.OutputValue : undefined;  ",
                "          }",
                "          return appId;",
                "        })",
                "        .then(appId => {",
                "          if (appId) {",
                "            const pinpointClient = new aws.Pinpoint({ apiVersion: '2016-12-01', region: event.ResourceProperties.pingPointRegion });",
                "            const params = {",
                "              ApplicationId: appId,",
                "            };",
                "            pinpointClient.deleteApp(params).promise();",
                "          }",
                "        })",
                "        .then(()=>{",
                "          response.send(event, context, response.SUCCESS, {'message': `Successfully deleted pinpoint project`});",
                "        })",
                "        .catch(e=>{",
                "          if (e.code !== 'ParameterNotFound') {",
                "            response.send(event, context, response.FAILED, {'message': `Failed to deleted Pinpoint project`, 'exception': e});",
                "          } else {",
                "            response.send(event, context, response.SUCCESS, {'message': `Successfully deleted pinpoint project`});",
                "          }",
                "        }); ",
                "    }",
                "    if (event.RequestType == 'Update') {",
                "        response.send(event, context, response.SUCCESS);",
                "        return;",
                "    }",
                "    if (event.RequestType == 'Create') {",
                "       const appName = event.ResourceProperties.appName;",
                "       let responseData = {};",
                "       const params = {",
                "           CreateApplicationRequest: {",
                "               Name: appName",
                "           }",
                "       };",
                "       const pinpoint = new aws.Pinpoint({ apiVersion: '2016-12-01', region: event.ResourceProperties.pingPointRegion });",
                "       pinpoint.createApp(params).promise()",
                "           .then((res) => {",
                "               responseData = res.ApplicationResponse;",
                "               response.send(event, context, response.SUCCESS, responseData);",
                "           }).catch((err) => {",
                "               console.log(err.stack);",
                "               responseData = {Error: err};",
                "               response.send(event, context, response.FAILED, responseData);",
                "               throw err;",
                "           });",
                "    }",
                "};"
              ]
            ]
          }
        },
        "Handler": "index.handler",
        "Runtime": "nodejs14.x",
        "Timeout": 300,
        "Role": {
          "Fn::GetAtt": [
            "LambdaExecutionRole",
            "Arn"
          ]
        }
      }
    },
    "PinpointFunctionOutputs": {
      "Type": "Custom::LambdaCallout",
      "Condition": "ShouldCreatePinpointApp",
      "Properties": {
        "ServiceToken": {
          "Fn::GetAtt": [
            "PinpointFunction",
            "Arn"
          ]
        },
        "region": {
          "Ref": "AWS::Region"
        },
        "pingPointRegion": {
          "Fn::FindInMap": [
            "RegionMapping",
            {
              "Ref": "AWS::Region"
            },
            "pinpointRegion"
          ]
        },
        "appName": {
          "Fn::If": [
            "ShouldNotCreateEnvResources",
            {
              "Ref": "appName"
            },
            {
              "Fn::Join": [
                "",
                [
                  {
                    "Ref": "appName"
                  },
                  "-",
                  {
                    "Ref": "env"
                  }
                ]
              ]
            }
          ]
        }
      },
      "DependsOn": "PinpointFunction"
    },
    "CognitoUnauthPolicy": {
      "Type": "AWS::IAM::Policy",
      "Condition": "ShouldCreatePinpointApp",
      "Properties": {
        "PolicyName": {
          "Ref": "unauthPolicyName"
        },
        "Roles": [
          {
            "Ref": "unauthRoleName"
          }
        ],
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "mobiletargeting:PutEvents",
                "mobiletargeting:UpdateEndpoint"
              ],
              "Resource": [
                {
                  "Fn::If": [
                    "ShouldCreatePinpointApp",
                    {
                      "Fn::Join": [
                        "",
                        [
                          "arn:aws:mobiletargeting:*:",
                          {
                            "Fn::Select": [
                              "4",
                              {
                                "Fn::Split": [
                                  ":",
                                  {
                                    "Ref": "authRoleArn"
                                  }
                                ]
                              }
                            ]
                          },
                          ":apps/",
                          {
                            "Fn::GetAtt": [
                              "PinpointFunctionOutputs",
                              "Id"
                            ]
                          },
                          "*"
                        ]
                      ]
                    },
                    {
                      "Fn::Join": [
                        "",
                        [
                          "arn:aws:mobiletargeting:*:",
                          {
                            "Fn::Select": [
                              "4",
                              {
                                "Fn::Split": [
                                  ":",
                                  {
                                    "Ref": "authRoleArn"
                                  }
                                ]
                              }
                            ]
                          },
                          ":apps/",
                          {
                            "Ref": "appId"
                          },
                          "*"
                        ]
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      }
    },
    "CognitoAuthPolicy": {
      "Type": "AWS::IAM::Policy",
      "Condition": "ShouldCreatePinpointApp",
      "Properties": {
        "PolicyName": {
          "Ref": "authPolicyName"
        },
        "Roles": [
          {
            "Ref": "authRoleName"
          }
        ],
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "mobiletargeting:PutEvents",
                "mobiletargeting:UpdateEndpoint"
              ],
              "Resource": [
                {
                  "Fn::If": [
                    "ShouldCreatePinpointApp",
                    {
                      "Fn::Join": [
                        "",
                        [
                          "arn:aws:mobiletargeting:*:",
                          {
                            "Fn::Select": [
                              "4",
                              {
                                "Fn::Split": [
                                  ":",
                                  {
                                    "Ref": "authRoleArn"
                                  }
                                ]
                              }
                            ]
                          },
                          ":apps/",
                          {
                            "Fn::GetAtt": [
                              "PinpointFunctionOutputs",
                              "Id"
                            ]
                          },
                          "*"
                        ]
                      ]
                    },
                    {
                      "Fn::Join": [
                        "",
                        [
                          "arn:aws:mobiletargeting:*:",
                          {
                            "Fn::Select": [
                              "4",
                              {
                                "Fn::Split": [
                                  ":",
                                  {
                                    "Ref": "authRoleArn"
                                  }
                                ]
                              }
                            ]
                          },
                          ":apps/",
                          {
                            "Ref": "appId"
                          },
                          "*"
                        ]
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      }
    }
  },
  "Outputs": {
    "Region": {
      "Value": {
        "Fn::FindInMap": [
          "RegionMapping",
          {
            "Ref": "AWS::Region"
          },
          "pinpointRegion"
        ]
      }
    },
    "Id": {
      "Value": {
        "Fn::If": [
          "ShouldCreatePinpointApp",
          {
            "Fn::GetAtt": [
              "PinpointFunctionOutputs",
              "Id"
            ]
          },
          {
            "Ref": "appId"
          }
        ]
      }
    },
    "appName": {
      "Value": {
        "Fn::If": [
          "ShouldCreatePinpointApp",
          {
            "Fn::GetAtt": [
              "PinpointFunctionOutputs",
              "Name"
            ]
          },
          {
            "Ref": "appName"
          }
        ]
      }
    }
  },
  "Mappings": {
    "RegionMapping": {
      "us-east-1": {
        "pinpointRegion": "us-east-1"
      },
      "us-east-2": {
        "pinpointRegion": "us-east-1"
      },
      "sa-east-1": {
        "pinpointRegion": "us-east-1"
      },
      "ca-central-1": {
        "pinpointRegion": "us-east-1"
      },
      "us-west-1": {
        "pinpointRegion": "us-west-2"
      },
      "us-west-2": {
        "pinpointRegion": "us-west-2"
      },
      "cn-north-1": {
        "pinpointRegion": "us-west-2"
      },
      "cn-northwest-1": {
        "pinpointRegion": "us-west-2"
      },
      "ap-south-1": {
        "pinpointRegion": "us-west-2"
      },
      "ap-northeast-3": {
        "pinpointRegion": "us-west-2"
      },
      "ap-northeast-2": {
        "pinpointRegion": "us-west-2"
      },
      "ap-southeast-1": {
        "pinpointRegion": "us-west-2"
      },
      "ap-southeast-2": {
        "pinpointRegion": "us-west-2"
      },
      "ap-northeast-1": {
        "pinpointRegion": "us-west-2"
      },
      "eu-central-1": {
        "pinpointRegion": "eu-central-1"
      },
      "eu-north-1": {
        "pinpointRegion": "eu-central-1"
      },
      "eu-west-1": {
        "pinpointRegion": "eu-west-1"
      },
      "eu-west-2": {
        "pinpointRegion": "eu-west-1"
      },
      "eu-west-3": {
        "pinpointRegion": "eu-west-1"
      },
      "me-south-1": {
        "pinpointRegion": "ap-south-1"
      }
    }
  }
}
```

**Comment by ykethan** [comment] 2022-10-17 15:54
Hello @YuantongL, thank you for the information and including the screenshots. I was able to reproduce the issue with the following steps.

1. amplify init
2. amplify add notifications
selected `? Choose the push notification channel to enable. SMS`
3. amplify add analytics
selected `Select an Analytics provider Amazon Pinpoint`
4. amplify push
push failed and observed the following error in cloudformaation console.

`error: Unresolved resource dependencies [PinpointFunction,  LambdaExecutionRole] in the Resources block of the template`

Note issue appears when adding notifications and then a analytics resource.

**Comment by lazpavel** [comment] 2023-02-24 21:46
This issue should be fixed in the latest Amplify CLI, as adding notifications will add analytics as a dependency

**Closed by lazpavel** 2023-02-24 21:46 UTC
Labels: bug, notifications, analytics, p2
