### ISSUE TITLE
Mocking API with @searchable in schema fails

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#5981] opened 2020-11-26 13:43 UTC
**Describe the bug**

My GraphQL schema uses the @searchable directive. This can't currently be mocked locally (by running `amplify mock api`) and the CLI tells me this, however it also reports that it will set a NONE data source as a work around for that but it still fails to run. 

This prevents any mocking while @searchable is in the schema.

To around around this I've been commenting out @searchable from my schema and then runnning amplify mock api. I'm happy with not being able to test the elasticsearch part of my schema functionality local but it is stopping me testing any of it easily currently.

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system

v4.32.0

**To Reproduce**

Create a schema:

`type Todo
  @model
  @searchable
{
  id: ID!
  name: String!
}`

in the CLI run `amplify mock api` and watch it complain with something similar to the following:

![image](https://user-images.githubusercontent.com/1674590/100357682-eb377680-2fec-11eb-86d6-bc5a29ae2351.png)

**Expected behavior**

Couple of options I think:

- Have the existing fix actually work, provide a dummy data source or whatever its doing and run that. 
- Just ignore the @searchable directive when run locally, warn us that it won't work and then skip over it, effectively "commenting it out" when you run by just ignoring it when parsing it locally in a mock.

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version. v12.18.4

**Comment by kaustavghosh06** [comment] 2021-02-05 21:27
@PeteDuncanson Yes, unfortunately @searchable is not currently supported with mock. But as you recommended, we can potentially ignore @searchable and do the same mocking with local DDB as we do without @searchable - but then the queries (with searching and sorting from the client) won't potentially work causing a discrepancy between what you see locally and what you see in the cloud. Marking this as an enhancement.

**Comment by mgarabedian** [comment] 2021-03-22 15:03
Is it possible to just get a fix that ignores @searchable when you run mock?  It makes no sense that I would need to remove it from the schema.graphql to run 'amplify mock', and then accidentally deploy ( which I did, and deleted the elasticsearch domain ).  These types of things have killed so much time developing with Amplify.

**Comment by PeteDuncanson** [comment] 2021-05-21 10:34
I'm getting to the point of writing a script that automatically comments/uncomments the `@searchable` fields from my schema at this point. Any update on if this might get looked at 6 months on?

**Comment by flogy** [comment] 2021-06-03 09:17
Would be interested in such a script too @PeteDuncanson . Better would be an official solution from Amplify of course.

**Comment by flogy** [comment] 2021-06-03 09:26
Another solution could be to allow creating separate GraphQL schemas per environment. Like that one could not only remove the `@searchable` directive in the `dev` schema to allow mocking, but also save those $30/month for ElasticSearch in the pushed dev environment.

**Comment by PeteDuncanson** [comment] 2021-06-03 14:09
@flogy can't you do that anyway? The schema is commited into source control, if you branch for live/dev then you would get that benefit?

**Comment by mgarabedian** [comment] 2021-06-03 15:47
@PeteDuncanson That is what I tried to do. I have a custom npm/yarn function that first comments out @searchable, then runs amplify mock, and then puts back searchable when the process exits.  But then the GQL API becomes out of whack, and breaks typescript in my app. So not really a good workaround.

**Comment by AlessandroVol23** [comment] 2021-06-21 17:19
Aren't these two duplicates? #4333

**Comment by cjihrig** [comment] 2021-06-21 18:46
@AlessandroVol23 yes, I'm going to close this as a duplicate of #4333.

Also, we recently posted an RFC for `@searchable` improvements at https://github.com/aws-amplify/amplify-cli/issues/7546. Local mocking is one of the enhancements we are targeting.

**Closed by cjihrig** 2021-06-21 18:46 UTC
Labels: enhancement, mock
