### ISSUE TITLE
AppId hardcoded when adding secrets (ASM) to lambda functions

### ISSUE THREAD

**Issue by karldanninger** [aws-amplify/amplify-cli#8045] opened 2021-08-26 15:18 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

5.3.1

### What operating system are you using?

Mac

### Amplify Categories

function

### Amplify Commands

update

### Describe the bug

When adding secrets to functions through `amplify update function`, the appId is hardcoded which is cumbersome when working with a distributed team with apps initialized across AWS accounts.

Exhibit where `SAD_FACE_APP_ID_HERE` is:

```
"MY_SECRET_KEY": {
  "Fn::Join": [
    "",
    [
      {
        "Fn::Sub": [
          "/amplify/${appId}/${env}/AMPLIFY_${functionName}_",
          {
            "appId": "SAD_FACE_APP_ID_HERE",
            "env": {
              "Ref": "env"
            },
            "functionName": "sweetfunction"
          }
        ]
      },
      "MY_SECRET_KEY"
    ]
  ]
}
```

### Expected behavior

It would be pretty awesome if the generated output was more like:

```
"MY_SECRET_KEY": {
  "Fn::Join": [
    "",
    [
      {
        "Fn::Sub": [
          "/amplify/${appId}/${env}/AMPLIFY_${functionName}_",
          {
            "appId": "${appId}",
            "env": {
              "Ref": "env"
            },
            "functionName": "sweetfunction"
          }
        ]
      },
      "MY_SECRET_KEY"
    ]
  ]
}
```

### Reproduction steps

1. amplify update function
2. add secret to project
3. exhibit generated cloudformation template

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by attilah** [comment] 2021-08-30 20:43
Duplicate of https://github.com/aws-amplify/amplify-cli/issues/7825 and the fix for that is already merged, will be in the next release.

**Closed by attilah** 2021-08-30 20:43 UTC
Labels: bug, functions

**Comment by mariusbutuc** [comment] 2021-08-31 01:11
Thanks for the follow-up @attilah; looking forward to `@aws-amplify/cli@5.3.2` then! 👍🏼

**Comment by mariusbutuc** [comment] 2021-09-09 18:02
Hey @attilah and @edwardfoyle (pinging you as well, since you authored #7922),

Using version `5.5.0`, the secret was removed from environment variables and added to secret values. 

This went as expected on my machine, and in `team-provider-info.json`:
* it removed the "secret" (not so secret when stored in source control) value that was set as an environment variable
* it set the `secretsPathAmplifyAppId` under the specific lambda function's configuration. 

So far so good.

When my teammate wanted to `amplify push` to their own environment, there was an `UPDATE_FAILED` error stating that
```
Parameters: [secretsPathAmplifyAppId] must have values
```

___

I was able to reproduce by manually deleting the `secretsPathAmplifyAppId` from under my own environment in `team-provider-info.json`: running `amplify push` returned

```
# …

UPDATE_IN_PROGRESS functionfoo                 AWS::CloudFormation::Stack Thu Sep 09 2021 13:18:05 GMT-0400 (Eastern Daylight Time)
UPDATE_IN_PROGRESS functionbar                 AWS::CloudFormation::Stack Thu Sep 09 2021 13:18:06 GMT-0400 (Eastern Daylight Time)
UPDATE_FAILED      functionfoo                 AWS::CloudFormation::Stack Thu Sep 09 2021 13:18:06 GMT-0400 (Eastern Daylight Time) Parameters: [secretsPathAmplifyAppId] must have values
UPDATE_IN_PROGRESS functionbaz                 AWS::CloudFormation::Stack Thu Sep 09 2021 13:18:06 GMT-0400 (Eastern Daylight Time)
UPDATE_FAILED      functionbar                 AWS::CloudFormation::Stack Thu Sep 09 2021 13:18:06 GMT-0400 (Eastern Daylight Time) Parameters: [secretsPathAmplifyAppId] must have values

# …

Following resources failed

✖ An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
An error occurred during the push operation: Resource is not in the state stackUpdateComplete
```

___

What does this mean and how should we deal with this? 

Here are some alternatives that came to mind:

1. Manually edit the `team-provider-info.json` for the environments that do not have the `secretsPathAmplifyAppId` set under the specific functions and add it there.
2. Every team member needs to use the CLI to run `amplify function update`, select the specific function, and add the secret there, under _Secret values configuration_.
3. Or does this mean that this feature is still buggy, if the desired behaviour was to have less friction?

What do you suggest?
