### ISSUE TITLE
Amplify mock doesn't set environment variables on python lambda function

### ISSUE THREAD

**Issue by half2me** [aws-amplify/amplify-cli#6185] opened 2020-12-15 16:48 UTC
**Describe the bug**
When running `amplify mock` python based lambda functions do not have their AWS environment variables set.

**Amplify CLI Version**
4.39.0

**To Reproduce**
1. Create a Lambda function in amplify using `amplify add function` and choose a python runtime
2. `print(os.environ)`

**Expected behavior**
environment variables should be set, just like when using the NodeJS runtime.

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. v12.20.0

**Additional context**
There seem to be lots of issues with lambda functions that run on python. From not being able to import any modules, etc. This really needs to be addressed, as being able to mock locally is key to productive development.

**Comment by kaustavghosh06** [comment] 2020-12-15 17:06
Closing as a duplicate of #4234

**Closed by kaustavghosh06** 2020-12-15 17:06 UTC
