### ISSUE TITLE
Warning message "(node:2500) [DEP0128] DeprecationWarning: Invalid 'main' field in ....." after typing amplify configure or amplify console

### ISSUE THREAD

**Issue by burakkbilginn** [aws-amplify/amplify-cli#10034] opened 2022-03-21 19:02 UTC
When I write amplify console in react-app, this warning message is coming:

```
    >amplify console

    (node:2500) [DEP0128] DeprecationWarning: Invalid 'main' field in
'C:\Users\SAMSUNG\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\cloudform\package.json' of
'packages/cloudform/index.js'. Please either fix that or report it to the module author
    (Use `node --trace-deprecation ...` to show where the warning was created)
    ? Which site do you want to open? ...  (Use arrow keys or type to filter)
```
And then, amplify console is not opening, just blank screen with error in the console (ERR_SSL_PROTOCOL_ERROR). How to fix this?

Runtime env:

```
"aws-amplify": "^4.3.16",     //latest
"aws-amplify-react-native": "^6.0.3",    //latest
node: v16.14.0     //latest
npm: 8.3.1         //latest
```

When I write "node --trace-deprecation ..." as suggested, this message comes:

```
PS C:\Users\SAMSUNG> node --trace-deprecation ...
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\SAMSUNG\...'
←[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:778:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)←[39m
←[90m    at node:internal/main/run_main_module:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}
```

**Comment by josefaidt** [comment] 2022-03-21 21:01
Hey @burakkbilginn :wave: thanks for raising this! In the future please consider filing bug reports using the provided bug report template, as this will give us a better understanding of the overall context of the issue. However, this appears to be a duplicate of https://github.com/aws-amplify/amplify-cli/issues/9939, which can be mitigated by downgrading to Node 14 (`nvm use 14`). Closing in favor of tracking the existing item

**Closed by josefaidt** 2022-03-21 21:01 UTC
