### ISSUE TITLE
When pushing a newly pulled environment with function secrets the push fails with "Parameters: [secretsPathAmplifyAppId] must have values" 

### ISSUE THREAD

**Issue by maziarzamani** [aws-amplify/amplify-cli#9667] opened 2022-02-01 09:41 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

nem

### If applicable, what version of Node.js are you using?

15.5.1

### Amplify CLI Version

7.6.3

### What operating system are you using?

macOS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

function

### Amplify Commands

pull, push

### Describe the bug

I recently added secrets to a function, then asked my colleague to pull the environment, make some changes, then push it back again. Unfortunately this resulted in updates failing (see the screenshot)

I inspected the `team-provider-info.json` file and realized that `secretsPathAmplifyAppId` is missing in the function. The secrets are already in the SSM and fully populated.

![Skærmbillede 2022-02-01 kl  10 37 49](https://user-images.githubusercontent.com/1084199/151944807-152a6ace-3bc0-481e-b237-daa7d19405e2.png)

### Expected behavior

Expecting the push to function as the SSM parameters are already populated and there.

### Reproduction steps

User 1:
- Adds a secret to a function
- Push
-
User 2:
- Pulls an entirely new environment
- Makes some changes to the function
- Push
- Awaits UPDATE_FAILED error from cloud formation

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

⠦ Updating resources in the cloud. This may take a few minutes...

Following resources failed

✖ An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: Resource is not in the state stackUpdateComplete

</details>

**Comment by jkervine** [comment] 2022-02-02 14:03
I fixed this by adding the secretsPathAmplifyAppId:"my-app-id" to the team-provider-info.json, in the function->function-name section ... it was missing from there after I pulled my environment. 

Looking at the file history, the line went missing after commit where I migrated to the v2 transformer... (i.e. after running amplify migrate api)

**Comment by josefaidt** [comment] 2022-02-02 16:40
Hey @maziarzamani and @jkervine :wave: since this data is captured in the `team-provider-info.json` and that file is tracked by git it can be carried from one machine/directory to another via a git pull, although our [doc for sharing a single environment](https://docs.amplify.aws/cli/teams/shared/) are misleading where we suggest an `amplify pull` to "sync" the environment.

On the other hand I was able to successfully reproduce this issue by using the following steps:

1. in one directory `myapp`, create a new amplify project with `amplify init -y`
2. add a function with a single secret with `amplify add function`, add `mysecret` with some value
3. push the new resource with `amplify push -y`
4. in a separate sibling directory `myapp2` pull the existing application with the pull command described in the console `amplify pull --appId <amplify-app-id> --envName <existing-env-name>`
5. try adding a small change to the function and push
6. observe error, missing `secretsPathAmplifyAppId`
7. as a workaround, we can:
	1. leverage git to pull latest changes, which will update the team-provider-info.json
	2. or run `amplify update function` > `update secrets` > `"I'm done"` to update the team-provider-info.json without git

Marking as a bug 🙂

**Comment by josh-mata** [comment] 2022-02-23 01:55
I'm having exactly the same problem:
<img width="863" alt="image" src="https://user-images.githubusercontent.com/96929158/155249357-afab5877-240d-43a1-b37c-66490444d54d.png">
This is my json 
<img width="718" alt="image" src="https://user-images.githubusercontent.com/96929158/155249744-755058e5-0596-4491-957c-d5786f27c3c6.png">

**Comment by edwardfoyle** [comment] 2022-03-15 21:33
This should be fixed in v7.6.23. Let us know if you're still running into issues using the latest version of the CLI.

**Closed by edwardfoyle** 2022-03-15 21:33 UTC
Labels: bug, functions, p2
