### ISSUE TITLE
[v2-feedback] Console can't find App

### ISSUE THREAD

**Issue by kay-is** [aws-amplify/amplify-cli#3966] opened 2020-04-03 13:55 UTC
**Page**: [`https://docs.amplify.aws/lib/auth/getting-started?platform=js`](https://docs.amplify.aws/lib/auth/getting-started?platform=js)

**Feedback**:

The docs mention `amplify console` "To view the deployed services in your project at any time" after running `amplify push`.

I got a link that displayed an error about the App with a specific ID can't be found.

**Comment by brene** [comment] 2020-04-15 16:14
This seems to be a CLI issue. Transferring to track it there.

**Comment by kaustavghosh06** [comment] 2020-04-15 16:16
@kay-is Can you check if you're logged into the same AWS account and region as the one you're using to deploy your resources via the Amplify CLI?

**Comment by kay-is** [comment] 2020-04-15 17:04
I used the ~/.aws/credentials profile from Cloud9

**Comment by kaustavghosh06** [comment] 2020-04-15 17:20
In your `amplify/team-provider-info.json` for your env do you see a a key called `AmplifyAppId`?

**Comment by kaustavghosh06** [comment] 2020-04-25 00:06
Closing due to lack of requested information.

**Closed by kaustavghosh06** 2020-04-25 00:06 UTC
Labels: pending-response, pending-triage, platform

**Comment by michelem09** [comment] 2020-07-02 07:23
I have the same problem here, trying to add hosting to the app:

```
$ amplify add hosting
? Select the plugin module to execute Hosting with Amplify Console (Managed hosting with custom domains, Continuous deployment)
App <ID> not found.
NotFoundException: App <ID> not found.
    at Object.extractError (/Users/michele/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/Users/michele/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/Users/michele/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/michele/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/michele/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/michele/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/michele/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/michele/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/michele/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/michele/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12)
```

In the `amplify/team-provider-info.json` the `<ID>` is set as `AmplifyAppId`

**Comment by jhockett** [comment] 2020-07-06 20:25
Hi @michelem09 this looks like a separate issue. Could you create a new issue with your information (steps to reproduce, CLI version, OS... etc) so we can track the issue and investigate better?
