### ISSUE TITLE
Can't delete Lambda layer

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#7100] opened 2021-04-15 13:21 UTC
### Before opening, please confirm:

I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

4.48

### What operating system are you using?

Windows

### Amplify Categories

function

### Amplify Commands

delete

### Describe the bug

I added a Lambda layer, assigned an existing Lambda function to use it, then need to get rid of it. Removed it from the function. Then tried to delete the layer. At that point I get the error:

Resource cannot be removed because it has a dependency on another resource
Dependency: Lambda:xeroIntergration
Error: Resource cannot be removed because it has a dependency on another resource
    at C:\Users\pete\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\extensions\amplify-helpers\remove-resource.ts:130:19
    at Array.forEach (<anonymous>)
    at C:\Users\pete\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\extensions\amplify-helpers\remove-resource.ts:126:32
    at Array.forEach (<anonymous>)
    at deleteResourceFiles (C:\Users\pete\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\extensions\amplify-helpers\remove-resource.ts:124:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.executeAmplifyCommand (C:\Users\pete\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-category-function\src\index.ts:240:3)
    at executePluginModuleCommand (C:\Users\pete\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\execution-manager.ts:175:3)
    at Object.executeCommand (C:\Users\pete\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\execution-manager.ts:28:5)
    at Object.run (C:\Users\pete\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\index.ts:139:5)

### Expected behavior

The layer should be removed as according to the CLI there is no dependency there yet it still thinks there is.

### Reproduction steps

create a layer with `amplify add function`
assign the layer to an existing function via `amplify update function`
realise that you can't mock a function with a layer...swear a bit...then get down to removing it
run `amplify update function` and remove the layer from your existing function by unselecting it
run that command again just to be doubly sure that it no longer shows any layer being linked to this function
run `amplify remove function` and delete the layer

BOOM! Error about an existing dependency.....gurrrr (shakes fist)

**Comment by PeteDuncanson** [comment] 2021-04-15 13:23
I should add that I tried pushing after removing the layer from the function and then deleting it to see if that would clear it but nope, nothing.

**Comment by jhockett** [comment] 2021-04-15 15:40
Closing this as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/5961

**Closed by jhockett** 2021-04-15 15:40 UTC
