### ISSUE TITLE
cant choose user pool auth mode and local graphql ui showing no schema available in amplify mock api

### ISSUE THREAD

**Issue by naingaungphyo** [aws-amplify/amplify-cli#10488] opened 2022-05-27 07:55 UTC
> **Note**: If your question is regarding the AWS Amplify Console service, please log it in the
> [AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
Amplify Cli,  mocking api locally with `amplify mock api`

**Amplify CLI Version**
8.3.0
You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**

I can't see cognito user pool auth mode and local graphql ui showing no schema available in local mock api console. 
That was working last week btw. 
I can confirm that local graphql api are working correctly by invoking from app (using authMode of both `AMAZON_COGNITO_USER_POOLS` and `API_KEY`).

I found similar issue #4935 but there is no info.

I think there is an error in console but I don't know what does it mean.
<img width="1792" alt="Screen Shot 2022-05-27 at 16 30 25" src="https://user-images.githubusercontent.com/5661543/170653124-3e1dfeb7-b28d-4ccc-a578-2426f3a7b494.png">

(Additional Question)
Is it possible to use `provider: iam` schema in local mock api? i.e using authMode: `AWS_IAM` to fetch data locally.
`{ allow: public, provider: iam, operations: [read] }` in schema

Currently I'm not setting provider in schema yet.

**Comment by jhockett** [comment] 2022-05-27 20:53
Hi @naingaungphyo, can you see if upgrading @aws-amplify/cli@8.3.1 solves the issue? `amplify upgrade` should do the trick.

**Comment by naingaungphyo** [comment] 2022-05-28 01:22
Hi @jhockett, Thanks!
I updated amplify cli to 8.3.1 and the console error is gone. 
But the situation is the same that I can't choose user pool auth and still see no schema available.
I think something is wrong to read schema definition from graphql local playground.

**Comment by masoud-mahmoudi** [comment] 2022-06-02 23:12
Hi, 
I bumped into the same error. It doesn't show any other Auth types.

**Comment by cgnhmt** [comment] 2022-06-06 13:32
Hi, I have tried with the 8.4.0 but still the problem is there. The only way I found so far is downgrading the amplify-cli to 8.0.2. 
I hope it will be fixed soon.

**Comment by josefaidt** [comment] 2022-06-06 18:36
Hey folks :wave: thanks for raising this! Marking as a duplicate of https://github.com/aws-amplify/amplify-category-api/issues/46

**Closed as not planned** 2022-06-06 18:37 UTC
Labels: bug, mock, duplicate, p2

**Comment by giovani-milanez** [comment] 2023-02-17 11:42
It seems that this problem is back on versions 10.7.x
Downgrading to version 10.6.2 works:
npm install -g @aws-amplify/cli@10.6.2
