### ISSUE TITLE
deleted Lambda functions and layers are still present in #current-cloud-backend

### ISSUE THREAD

**Issue by meop** [aws-amplify/amplify-cli#5577] opened 2020-10-13 21:38 UTC
**Describe the bug**
`amplify status` shows the desired Functions, and matches what is inside amplify/backend/function folder.
However, cloning project to another machine, running `amplify init` and then `amplify pull` recreates old, deleted Functions. Checking inside amplify/#current-cloud-backend/function folder on either machine still shows old, deleted Functions.

**Amplify CLI Version**
4.29.7

**To Reproduce**
Not sure how the project is in this state, but I used `amplify function remove` to delete all the Functions I no longer wanted, and `amplify push` to deploy.

**Expected behavior**
All of the deleted Functions and layers should have been removed from the #current-cloud-backend folder.. and should not reappear on a freshly git cloned instance, followed by an `amplify init` and `amplify pull`.

**Screenshots**
I can add screenshots if the description is unclear.

**Desktop (please complete the following information):**
OS: Debian / Windows
Node Version: 12.19.0

**Additional context**
None

**Comment by yuth** [comment] 2020-10-14 00:13
@meop Could you clarify the following
1. When you said cloning the project in another machine, did you mean git clone
2. After deleting the functions and doing an `push` did you commit the change to git and do an push
3. With `amplify init` in the other mahcine did you select the same env as that in step2

**Comment by meop** [comment] 2020-10-14 05:17
@yuth 

1. Yes, git clone.
2. Yes, see below.
3. Yes, this is a small project, there is only one Amplify env.

In the git repo, I added the following to gitignore file, per a post I saw from Amplify team, suggesting this was the recommended set to ignore:

# amplify
amplify/\#current-cloud-backend
amplify/.config/local-*
amplify/backend/amplify-meta.json
amplify/backend/awscloudformation
build/
dist/
node_modules/
aws-exports.js
awsconfiguration.json

After developing a Lambda group (few functions, all sharing a couple of layers), I got an error pushing this to AWS from Amplify CLI locally.
So I decided to delete all of them, push this state of not having any functions to cloud (to erase what was there), and then add a NEW layer and some NEW functions.
Locally, on my main workstation, all of this is detected fine, and Amplify pushes to cloud fine. But the automatic Amplify console build tied to the CodeCommit git repo fails now, in some Amplify code related to checking for Lambda functions to deploy.
I assume this Amplify console build error is related to #current-cloud-backend still containing ALL the functions, including the first deleted set and the new active set.
When I git clone the repo on another workstation, then Amplify init, then Amplify pull the same env, ALL the functions still show up in the backend folder.
I did a text search through the project, and do not see any references to the old functions in generated Cloud Formation files anymore. Not sure how to clear out the old functions from #current-cloud-backend, or get the project out of this state.
Thank you.

**Comment by meop** [comment] 2020-10-16 18:14
Even if getting into this situation is not reproducible anymore, I would appreciate if anyone knows how to get Amplify out of this state.

I need the removed functions to no longer be present that #current-cloud-backend folder. I need to get that folder to reflect only the list of functions that `amplify status` shows.

I tried `amplify push --force` but that did not help.

**Comment by yuth** [comment] 2020-10-16 19:13
Amplify CLI should delete the function from `#current-cloud-backend` when a function gets deleted and should zip that and upload the file to the deployment bucket, so when an `amplify env pull` happens, the `#current-cloud-backend` reflects that state.

I am not sure how the function folder stayed in `#current-cloud-backend` even after successful deployment. Could you provide us the exact steps/commands (if you have them handy) that you ran when you deleted the functions, which could help us narrow down the problem and fix this issue from happening.

**Comment by meop** [comment] 2020-10-16 19:29
Sorry, I do not have an exact sequence of commands, because this effort spanned over a few days. Are there any logs or artifacts you would like?

Also, do you know how to get the project out of this state? Should I remove something from the AWS cloud to allow an `amplify push` to overwrite it? I do not see other references to the deleted functions to manually delete locally. Manually removing these folders from the primary machine and running `amplify push` has no effect.. they still end up back in the folder.

**Comment by meop** [comment] 2020-10-21 04:22
I was able to get past this situation by downloading the `#current-cloud-backend.zip` file from the S3 bucket Amplify was using, extract it, manually remove the old, deleted-according-to-amplify-cli functions.. then zip again and overwrite this file in the S3 bucket. That seems to have fixed the situation. However, not sure if this will have any further consequences.

**Comment by UnleashedMind** [comment] 2020-10-23 19:21
I tried but I couldn't reproduce.
If all the Amplify commands run to completion, then the removed Lambda function should be reflected in #current-cloud-backend.zip file in the deployment bucket. 
I'm going to close this issue now since you are not blocked anymore. Feel free to open a new issue if you got into this situation again.

**Closed by UnleashedMind** 2020-10-23 19:21 UTC
Labels: Lambda layers, functions, not-reproducable
