### ISSUE TITLE
@aws_iam api auth without @model

### ISSUE THREAD

**Issue by oste** [aws-amplify/amplify-cli#2285] opened 2019-09-13 20:30 UTC
This is a followup to https://github.com/aws-amplify/amplify-js/issues/3626. 

I am using API with RDS resolvers and I need to access it in a lambda function with iam credentials. The only way that I know of to make this work is to use `@aws_iam` schema authorization mode shown here https://docs.aws.amazon.com/appsync/latest/devguide/security.html.

However when I run `amplify api push` aftering adding `@aws_iam` to my schema.graphql file I get the following error:

`An error occured during the push operation: Cannot read property 'defaultAuthentication' of undefined`

Is there a way to use @aws_iam with the new auth changes? I didn't see a way but wanted to make sure I didn't miss anything.

I think my issues is that the `@auth` directive requires `@model` but in my case, I cannot use `@model`

**Comment by houmark** [comment] 2019-09-13 21:12
See #2283

**Comment by oste** [comment] 2019-09-13 22:15
@houmark I don't think it's related. As I mentioned, I am not using '@model'

**Comment by kaustavghosh06** [comment] 2019-09-14 00:27
@oste This is a duplicate of #2260. Please take a look at that issue for the workaround.
We've fixed this issue and is pending release.

**Closed by kaustavghosh06** 2019-09-14 00:27 UTC

**Comment by oste** [comment] 2019-09-14 01:19
@kaustavghosh06 amazing! Thanks for the quick reply. Wasn't sure exactly the scope of the new auth changes. Really excited to see we can use `@aws_iam` directive standalone now.

All the work the amplify team is doing is much appreciated. Keep it up, can only imagine where this is going.
