### ISSUE TITLE
Support custom configuration properties in `awsconfiguration.json` for Android/ iOS

### ISSUE THREAD

**Issue by rohandubal** [aws-amplify/amplify-cli#731] opened 2019-01-18 20:27 UTC
**Is your feature request related to a problem? Please describe.**
When add a custom configuration item in `awsconfiguration.json`, the CLI over-rides the `awsconfiguration.json` file when `amplify push` is run (even if there is no change in awsconfiguration.json)

**Describe the solution you'd like**
We would like to have a feature where the properties in `awsconfiguration.json` which are not managed by amplify cli should stay in their place even in case of an update in config.

**Describe alternatives you've considered**
One alternative is to have them added via code but it creates a different non-standard path as compared to the whole client experience.

**Comment by kaustavghosh06** [comment] 2019-01-18 20:32
Closing, since it's a duplicate of issue #419

**Closed by kaustavghosh06** 2019-01-18 20:32 UTC
