### ISSUE TITLE
CREATE_FAILED [HostedUICustomResourceInputs, HostedUIProvidersCustomResourceInputs]

### ISSUE THREAD

**Issue by phlinhng** [aws-amplify/amplify-cli#1540] opened 2019-05-29 11:18 UTC
These message keep happen every time when I try to `amplify push` after adding or updating `auth`.    
Version: @amplify/cli 1.6.11

**Comment by kaustavghosh06** [comment] 2019-05-29 18:44
@phlinhng We found out the root-cause for this issue in #1513 
Closing this, since it's a duplicate of #1513

**Closed by kaustavghosh06** 2019-05-29 18:44 UTC
