### ISSUE TITLE
Adding @key LSI to an already existing table

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-cli#4723] opened 2020-07-01 00:31 UTC
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

I needed to add a new @key to my @model, the purpose of the @key is purely for sorting and @connection, but when I add `@key(name: "modelSortedByField", fields: ["id", "sortField"])`, it produces:

```
Attempting to add a local secondary index to the StoreTable table in the Store stack. Local secondary indexes must be created when the table is created.
An error occurred during the push operation: Attempting to add a local secondary index to the StoreTable table in the Store stack. Local secondary indexes must be created when the table is created.
```

What I want to do is to be able to sort a result by @connection field, example:

```gql
type Post @model {
  id: ID!
  title: String
  body: String
  userId: String
  user: User @connection(keyField: "userId")
}

type User @model {
  id: ID!
  fullname: String
}
```

and I want to sort the result of posts by `user.fullname`, I found through [this discussion](https://github.com/aws-amplify/amplify-js/discussions/5704) that it's possible through using @key in the connection, so I was thinking of something like so:

```gql
type Post @model {
  id: ID!
  title: String
  body: String
  userId: String
  user: User @connection(keyName: "userConnectionSortedByFullname", fields: ["id"])
}

type User
  @model
  @key(name: "userConnectionSortedByFullname", fields: ["id", "fullname"]) {
  id: ID!
  fullname: String
}
```

but doing that resulted to the error I said above.

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system

4.22

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

Please see above details.

**Expected behavior**

I'm unsure...

**Screenshots**

**Desktop (please complete the following information):**
 - OS: N/A
 - Node Version: N/A

**Additional context**

**Comment by yuth** [comment] 2020-07-01 20:05
GraphQL transformer `@key` directive trys to create an Local Secondary Index (LSI) if a key has same has key as that of the primary index. LSI can be created only when the table is created, this is an know issue that we are working to fix with creating GSI instead of LSI.

For now the only solution for this is to delete the table and recreate it (if dont care about the data)

**Comment by aprilmintacpineda** [comment] 2020-07-01 22:38
Thanks for the clarification...

**Comment by SwaySway** [comment] 2020-07-21 23:39
We currently have a PR in the works for this. Closing as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/2702.

**Closed by SwaySway** 2020-07-21 23:39 UTC
Labels: @key, enhancement, graphql-transformer
