### ISSUE TITLE
amplify push fails when deploying/creating more than 25 @models at once

### ISSUE THREAD

**Issue by blairtaylor** [aws-amplify/amplify-cli#3734] opened 2020-03-21 18:47 UTC
We are attempting to create a prod backend environment. We already have 2 existing non-prod environments which have been up for a few months.

We have created the environment via amplify env add

We have 46 tables in our graphql schema and 93 existing tables in our DynamoDB region so we should not be running into the initial limit of 256 tables per AWS Region. 

When we run the amplify push command, it runs successfully for a while then we receive this error:

Embedded stack arn:aws:cloudformation:us-east-1:<accountnumber>:stack/amplify-marketbox-pankaj-94936-apimarketbox-<acct number>/f6610960-6b7d-11ea-b442-1217092af407 was not successfully created: The following resource(s) failed to create: [ClientPackage, Package, CompanyUnavailability, Skill, Audit, ScheduleAvailability, ScheduleTimeblock, BillingProgress, ServiceType, UserInvitation, ProviderRatings, Reminder, Country, RequestMessages, ProviderSkill, Envt, City, Client, CompanyLocation, ProviderPhotos, ProviderServiceType, Company, PageAudit, SystemErrorLog, User, State, ServiceTypeCategory, Booking, Region, BillingTransaction, RepeatApptCreation, PublicAccessToken, PhoneType, Promotion, Order, UserRemoteAddress].

Same error is in the CloudWatch logs. For some reason Amplify cannot create the DynamoDB tables.

The same schema has been used to create the tables in a staging environment so we are very confused as to why we are receiving the error.

Please assist - we have a client ready to go live and cannot create our production environment for them to use.

Thanks. Please let me know if you need any more info.

**Comment by kaustavghosh06** [comment] 2020-03-21 18:50
The entire Cloudformation error log would be helpful. The above log doesn't give the reason for the stack to fail.

**Comment by kaustavghosh06** [comment] 2020-03-21 18:53
Also, there's a limit on DynamoDB to create only 25 tables at a given time. Reference - https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html


API-Specific Limits
CreateTable/UpdateTable/DeleteTable
In general, you can have up to 50 CreateTable, UpdateTable, and DeleteTable requests running simultaneously (in any combination). In other words, the total number of tables in the CREATING, UPDATING, or DELETING state cannot exceed 50.

The only exception is when you are creating a table with one or more secondary indexes. You can have up to 25 such requests running at a time. However, if the table or index specifications are complex, DynamoDB might temporarily reduce the number of concurrent operations.

**Comment by blairtaylor** [comment] 2020-03-21 18:56
Thanks. Two points. 

1. We already have an existing environment with 43 tables. We likely created them incrementally.

2. How do we work around this limit? Surely Amplify supports creating a new environment with more than 25 tables?

**Comment by kaustavghosh06** [comment] 2020-03-21 19:01
@bl

> Thanks. Two points.
> 
> 1. We already have an existing environment with 43 tables. We likely created them incrementally.

Yes, that must have been the case.

> 2. How do we work around this limit? Surely Amplify supports creating a new environment with more than 25 tables?

Yes, it does but you'll have to do it incrementally( similar to what you must've done in your existing environments). This is due to DynamoDB API restrictions on CreateTables API mentioned above.

**Comment by blairtaylor** [comment] 2020-03-21 19:06
Ok. Thanks. We'll have to try to work around this. I am puzzled - how are very large clients handling this? 25 table limit is very small. I have worked on relational DBs with 1000's of tables. Creating a new environment in that case would not be practical.

**Comment by kaustavghosh06** [comment] 2020-03-21 19:16
@blairtaylor I've usually seen customers build their apps incrementally - with not more than 25 DynamoDB tables created at once in an environment. But yes, it's a service level limitation and the Amplify team has a plan this year to get around these limitations by queuing  our deployments - to abstract away service level limitations like the one you experienced.

**Comment by blairtaylor** [comment] 2020-03-21 20:06
We removed all but 19 core tables and attempted an amplify api push

The push seemed to create all the tables but still threw an exception

UPDATE_COMPLETE                     amplify-marketbox-proda-150826 AWS::CloudFormation::Stack Sat Mar 21 2020 15:48:25 GMT-0400 (Eastern Daylight Time)
UPDATE_COMPLETE_CLEANUP_IN_PROGRESS amplify-marketbox-proda-150826 AWS::CloudFormation::Stack Sat Mar 21 2020 15:48:24 GMT-0400 (Eastern Daylight Time)
√ Generated GraphQL operations successfully and saved at src\graphql
\ Updating resources in the cloud. This may take a few minutes...Error: Invalid config C:\Users\blair\.amplify\awscloudformation\4xk1ONsYyl
    at loadConfigFromPath (C:\Users\blair\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\lib\configuration-manager.js:507:9)
    at loadConfigurationForEnv (C:\Users\blair\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\lib\configuration-manager.js:518:19)
    at Object.loadConfiguration (C:\Users\blair\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\lib\configuration-manager.js:497:24)
    at Object.aws.configureWithCreds (C:\Users\blair\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\src\aws-utils\aws.js:18:45)
    at Object.getConfiguredAWSClient (C:\Users\blair\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\index.js:59:13)
    at getS3Client (C:\Users\blair\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-category-auth\provider-utils\awscloudformation\utils\trigger-file-uploader.js:13:30)
    at uploadFiles (C:\Users\blair\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-category-auth\provider-utils\awscloudformation\utils\trigger-file-uploader.js:19:28)
    at uploadAuthTriggerFiles (C:\Users\blair\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\lib\upload-auth-trigger-files.js:7:11)
    at Object.run (C:\Users\blair\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\lib\push-resources.js:67:11)
    at runMicrotasks (<anonymous>)
× An error occurred when pushing the resources to the cloud
Unable to upload trigger files to S3
There was an error pushing the API resource
Error: Unable to upload trigger files to S3

We don't believe we have any S3 triggers .

Also the process crashed, did not attempt a rollback.

Invalid config C:\Users\blair\.amplify\awscloudformation\4xk1ONsYyl

What is causing this issue?

Thanks.

**Comment by blairtaylor** [comment] 2020-03-21 21:21
We created a new environment.
We commented a number of tables in the schema leaving 19 left.
We did an amplify api push

We were able to create the tables in the new environment.

We then uncommented other tables (total 38, incremental 19) and did an amplify api push

We not get the following error:

UPDATE_COMPLETE functionesprovidersearch AWS::CloudFormation::Stack Sat Mar 21 2020 17:06:05 GMT-0400 (Eastern Daylight Time)
UPDATE_COMPLETE functionstripesavecard   AWS::CloudFormation::Stack Sat Mar 21 2020 17:06:05 GMT-0400 (Eastern Daylight Time)
UPDATE_COMPLETE functionmessaging        AWS::CloudFormation::Stack Sat Mar 21 2020 17:06:05 GMT-0400 (Eastern Daylight Time)
UPDATE_COMPLETE functionsendsesemail     AWS::CloudFormation::Stack Sat Mar 21 2020 17:06:05 GMT-0400 (Eastern Daylight Time)
UPDATE_COMPLETE functionchangeuserrole   AWS::CloudFormation::Stack Sat Mar 21 2020 17:06:05 GMT-0400 (Eastern Daylight Time)
UPDATE_COMPLETE functionmapdirection     AWS::CloudFormation::Stack Sat Mar 21 2020 17:06:05 GMT-0400 (Eastern Daylight Time)
UPDATE_COMPLETE functionstripechargecard AWS::CloudFormation::Stack Sat Mar 21 2020 17:06:05 GMT-0400 (Eastern Daylight Time)
UPDATE_COMPLETE apisearchapi             AWS::CloudFormation::Stack Sat Mar 21 2020 17:06:04 GMT-0400 (Eastern Daylight Time)
UPDATE_COMPLETE apistripesavecard        AWS::CloudFormation::Stack Sat Mar 21 2020 17:06:04 GMT-0400 (Eastern Daylight Time)
UPDATE_COMPLETE apimessaging             AWS::CloudFormation::Stack Sat Mar 21 2020 17:06:04 GMT-0400 (Eastern Daylight Time)
UPDATE_COMPLETE apisendsesemail          AWS::CloudFormation::Stack Sat Mar 21 2020 17:06:04 GMT-0400 (Eastern Daylight Time)
UPDATE_COMPLETE apimapdirection          AWS::CloudFormation::Stack Sat Mar 21 2020 17:06:04 GMT-0400 (Eastern Daylight Time)
UPDATE_COMPLETE apichangeuserrole        AWS::CloudFormation::Stack Sat Mar 21 2020 17:06:04 GMT-0400 (Eastern Daylight Time)
UPDATE_COMPLETE apistripechargecard      AWS::CloudFormation::Stack Sat Mar 21 2020 17:06:04 GMT-0400 (Eastern Daylight Time)
- Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_COMPLETE amplify-marketbox-prodone-161616 AWS::CloudFormation::Stack Sat Mar 21 2020 17:07:40 GMT-0400 (Eastern Daylight Time)
UPDATE_COMPLETE          authmarketbox50a3b28b            AWS::CloudFormation::Stack Sat Mar 21 2020 17:07:40 GMT-0400 (Eastern Daylight Time)
UPDATE_COMPLETE          apimarketbox                     AWS::CloudFormation::Stack Sat Mar 21 2020 17:07:39 GMT-0400 (Eastern Daylight Time)
/ Updating resources in the cloud. This may take a few minutes...Error updating cloudformation stack
\ Updating resources in the cloud. This may take a few minutes...

Following resources failed

× An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
There was an error pushing the API resource
ResourceNotReady: Resource is not in the state stackUpdateComplete

**Comment by RossWilliams** [comment] 2020-03-21 21:27
@blairtaylor can you look at CloudFormation in the console, find any error events in your stack, where possible drill into the nested resource where there is a failure, and look at those failed events?

**Comment by blairtaylor** [comment] 2020-03-21 21:32
I've come across this error before 

Resource is not in the state stackUpdateComplete
There was an error pushing the API resource
ResourceNotReady: Resource is not in the state stackUpdateComplete

when doing an api push and was advised to do an amplify push (which worked on a previous issue). So I'll try an amplify push now.

**Comment by RossWilliams** [comment] 2020-03-21 21:33
@blairtaylor do you see the stack you are trying to deploy at all? If it’s not in stack update complete, you should be able to find it in the console to track down the issue.

You can also generate this error by simply trying to push an update while a current update is still running

**Comment by blairtaylor** [comment] 2020-03-21 21:56
I just ran amplify push.

Getting lots of errors on creation of the resolvers.

CREATE_FAILED amplify-marketbox-prodone-161616-apimarketbox-TXAZBADFVQXQ-UserInvitation-6A87VQJZB33K AWS::CloudFormation::Stack Sat Mar 21 2020 17:54:51 GMT-0400 (Eastern Daylight Time) The following resource(s) failed to create: [GetUserInvitationResolver, CreateUserInvitationResolver, DeleteUserInvitationResolver].
CREATE_FAILED DeleteUserInvitationResolver                                                           AWS::AppSync::Resolver     Sat Mar 21 2020 17:54:50 GMT-0400 (Eastern Daylight Time) No field named deleteUserInvitation found on type Mutation (Service: AWSAppSync; Status Code: 404; Error Code: NotFoundException; Request ID: 187c7ab3-4b6b-47af-967e-9c57ca514f95)
CREATE_FAILED CreateUserInvitationResolver                                                           AWS::AppSync::Resolver     Sat Mar 21 2020 17:54:48 GMT-0400 (Eastern Daylight Time) No field named createUserInvitation found on type Mutation (Service: AWSAppSync; Status Code: 404; Error Code: NotFoundException; Request ID: a20e4141-bf74-4b15-a27b-9f923af50f04)
- Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED      amplify-marketbox-prodone-161616-apimarketbox-TXAZBADFVQXQ-RepeatApptCreation-1QB4Y6BIP2FW0 AWS::CloudFormation::Stack Sat Mar 21 2020 17:54:52 GMT-0400 (Eastern Daylight Time) The following resource(s) failed to create: [ListRepeatApptCreationResolver, SubscriptiononDeleteRepeatApptCreationResolver].
CREATE_FAILED      ListRepeatApptCreationResolver                                                              AWS::AppSync::Resolver     Sat Mar 21 2020 17:54:51 GMT-0400 (Eastern Daylight Time) Resource creation cancelled                                                                                         
CREATE_FAILED      SubscriptiononDeleteRepeatApptCreationResolver                                              AWS::AppSync::Resolver     Sat Mar 21 2020 17:54:51 GMT-0400 (Eastern Daylight Time) No field named onDeleteRepeatApptCreation found on type Subscription (Service: AWSAppSync; Status Code: 404; Error Code: NotFoundException; Request ID: a8f2c2f1-6fc3-46ea-9c42-58349fcbc5c9)

**Comment by RossWilliams** [comment] 2020-03-21 22:29
It’s very hard to diagnose without seeing the details and poking around. I’d be curious to see the error events in the console around the first push at 17:05. The errors on the subsequent push I’d ignore until the cause of the initial error is found. Those latter errors seem to be due to a schema - CloudFormation template mismatch. You may want to consider destroying and recreating the environment on your next push after finding the underlying issue

**Comment by blairtaylor** [comment] 2020-03-21 22:51
We've created several environments tying to get this to work. 
We are running out of prod related names to use.
We've also had issues with amplify env remove <envt> also crashing.

**Comment by blairtaylor** [comment] 2020-03-22 02:22
We seem to have gotten to the root of the issue. We are hitting the default limit - 200 CloudFormation Stack Count. We've requested an increase (Case ID 6892494531). Is there any way to expedite this request? We've now spent an entire day attempting to create a new Amplify environment.

**Comment by blairtaylor** [comment] 2020-03-22 18:23
After requesting/receiving an increase to the CloudFormation Stack Count service quota (initially 200), we are now able to successfully build our production environment. Thanks.

Taking a look at the service quotas for Amplify, the service quotes for Amplify are not adjustable. Will they be in the future? The quotas I am most concerned with are the limit of 5 domains per app and limit of 50 subdomains per domain.

**Comment by mdepascale** [comment] 2020-03-25 16:35
It seems like we are getting the same issue here

`UPDATE_COMPLETE amplify-corporatedocsbackend-prod-112623 AWS::CloudFormation::Stack Wed Mar 25 2020 16:21:05 GMT+0000 (Coordinated Universal Time)
--
406 | Error: Profile configuration is missing for: PROFILE_NAME
407 | at Object.getProfiledAwsConfig (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/system-config-manager.js:82:11)
408 | at loadConfigurationForEnv (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/configuration-manager.js:516:45)
409 | at Object.loadConfiguration (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/configuration-manager.js:497:24)
410 | at Object.aws.configureWithCreds (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws.js:18:45)
411 | at Object.getConfiguredAWSClient (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/index.js:59:13)
412 | at getS3Client (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/provider-utils/awscloudformation/utils/trigger-file-uploader.js:13:30)
413 | at uploadFiles (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/provider-utils/awscloudformation/utils/trigger-file-uploader.js:19:28)
414 | at uploadAuthTriggerFiles (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/upload-auth-trigger-files.js:7:11)
415 | at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:67:11)
416 | at process._tickCallback (internal/process/next_tick.js:68:7)
417 | ✖ An error occurred when pushing the resources to the cloud
418 | ✖ There was an error initializing your environment.
419 | init failed
420 | Error: Unable to upload trigger files to S3
421 | at uploadFiles (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/provider-utils/awscloudformation/utils/trigger-file-uploader.js:49:11)
422 | at process._tickCallback (internal/process/next_tick.js:68:7)
`

we have 2 environment, this is not working on production while on develoment it works file
I thinks it fails while uploading files to s3 or maybe right after uploading files to s3

**Comment by mdepascale** [comment] 2020-03-26 10:42
update, it works we just had and error inside the buildspec 
turns out `echo -e "..." > file` save -e too, so there was it

**Comment by ammarkarachi** [comment] 2020-03-26 21:30
@mdepascale Can you create a separate issue so we can help you in following up with this problem?

**Comment by kaustavghosh06** [comment] 2020-03-26 21:34
@blairtaylor I would recommend opening up an issue regarding Amplify console limits in this repo - https://github.com/aws-amplify/amplify-console

Closing this issue as the original problem seems to be solved.

**Closed by kaustavghosh06** 2020-03-26 21:34 UTC
Labels: cloudformation, graphql-transformer, pending-triage
