### ISSUE TITLE
Auth directives aren't applied recursively on models.

### ISSUE THREAD

**Issue by arlyon** [aws-amplify/amplify-cli#4358] opened 2020-05-23 10:21 UTC
**Describe the bug**

I have a model that looks like this:

```gql
type Page @model(subscriptions: null)
    @auth(rules: [
        {allow: public, provider: iam, operations: [read]}
        {allow: private, operations: [read]}
        {allow: groups, groups: ["admin"]}
    ]) {
    id: ID!
    text: [TextTranslations!]!
    updatedAt: AWSDateTime! @auto
    createdAt: AWSDateTime! @auto
}

type TextTranslations {
    id: ID!
    langID: ID!
    translations: [TextTranslation!]!
    outOfDate: Boolean!
}

type TextTranslation {
    translationIndex: Int!
    text: String!
}
```

When I build this, I get the following out:

```gql
type Page @aws_iam @aws_cognito_user_pools {
  id: ID!
  text: [TextTranslations!]!
  updatedAt: AWSDateTime!
  createdAt: AWSDateTime!
}

type TextTranslations @aws_iam @aws_cognito_user_pools {
  id: ID!
  langID: ID!
  translations: [TextTranslation!]!
  outOfDate: Boolean!
}

type TextTranslation {
  translationIndex: Int!
  text: String!
}
```

This means that requests to list `TextTranslation` fails with an auth error:

```json
{
  "data": {
    "listPages": {
      "items": [
        null
      ]
    }
  },
  "errors": [
    {
      "path": [
        "listPages",
        "items",
        0,
        "text",
        0,
        "translations",
        0,
        "translationIndex"
      ],
      "data": null,
      "errorType": "Unauthorized",
      "errorInfo": null,
      "locations": [
        {
          "line": 6,
          "column": 11,
          "sourceName": null
        }
      ],
      "message": "Not Authorized to access translationIndex on type TextTranslation"
    }
  ]
}
```

It seems like the auth directives are not transitive, ie. if type `B` is on `A` then `@aws_iam` and `@aws_cognito_user_pools` are applied to `B`. But if `C` is on `B`, the auth isn't propagated.
The solution for now is to add a dummy model that references C 'at the top level':

```
"""
This is a dummy model until transitive auth
directives are applied.

https://github.com/aws-amplify/amplify-cli/issues/4358
"""
type Dummy @model(queries: null, mutations: null, subscriptions: null) 
    @auth(rules:[
        {allow: public, provider: iam, operations: [read]}
        {allow: private, operations: [read]}
    ]) {
    dummy: TextTranslation
}
```

**Amplify CLI Version**

4.20.0

**To Reproduce**

Schema above.

**Expected behavior**

I expect the build schema to propagate the `@aws_iam @aws_cognito_user_pools` recursively such that if A and reach B, and B can reach C, then A can reach C.

**Happy to write a PR with some pointers to help me get started**

**Comment by ammarkarachi** [comment] 2020-06-01 21:52
Relate #3910

**Comment by attilah** [comment] 2020-06-05 18:50
Duplicate of #3910

**Closed by attilah** 2020-06-05 18:50 UTC
Labels: @auth, graphql-transformer
