### ISSUE TITLE
`Amplify configure` not working properly with Chrome set as default browser

### ISSUE THREAD

**Issue by Inukares** [aws-amplify/amplify-cli#557] opened 2018-12-06 23:04 UTC
**Describe the bug**
After answering to following `amplify configure` questions: 
`Sign in to administrator account`
`Specify the AWS region`
`Specify the username of the new IAM user`
This question appears: 
`Complete the user creation using AWS console`.
It is supposed to open the IAM Management Console in the Chrome browser. It goes to this url: (https://console.aws.amazon.com/iam/home?region=us-east-2#/users$new?step=details&accessKey&userNames=someusername&permissionType=policies&policies=arn:aws:iam::aws:policy%2FAdministratorAccess), but the page is blank (screenshot attached). Just out of curiosity I tried to open the url within another tab, but still page fails to load. 
It did succeed however on Safari.

**To Reproduce**
```sh
npm install -g @aws-amplify/cli
amplify configure
```

**Expected behavior**
Chrome tab opens and enables me to add the new IAM user.

[![Zrzut-ekranu-2018-12-06-o-23-55-31.png](https://i.postimg.cc/59FrBFsR/Zrzut-ekranu-2018-12-06-o-23-55-31.png)](https://postimg.cc/23rTm3RQ)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Macbook Pro
 - OS: macOS High Sierra 10.13.6
 -  browser: Chrome 
 - Version 70.0.3538.110

**Comment by yuth** [comment] 2018-12-06 23:40
Could you try opening the same url in an incognito window and see if it still is empty?

**Comment by Inukares** [comment] 2018-12-07 13:03
I've tried opening in incognito and the tab opens with proper content ( same as on safari ).
I've also tried to delete site data, so went to developer tools -> Application -> Clear storage -> Clear site data and then went to the same url in Chrome, but it still failed.

**Comment by yuth** [comment] 2018-12-07 18:10
Do you see any error in the console (in developer tools)? I couldn't reproduce this on chrome. What version of chrome do you have installed?

**Comment by Inukares** [comment] 2018-12-07 23:04
I have 70.0.3538.110 Chrome running.
No, no errors.

**Comment by Inukares** [comment] 2018-12-17 22:08
If it's impossible to reproduce by anyone else apart from me, I suppose it's a subject to close.

**Comment by UnleashedMind** [comment] 2018-12-18 01:34
Closing this issue for now, feel free to reopen it though.

**Closed by UnleashedMind** 2018-12-18 01:34 UTC
Labels: investigating
