### ISSUE TITLE
Building video resources...🛑 Cannot read properties of undefined (reading 'dev')

### ISSUE THREAD

**Issue by SalmonMode** [aws-amplify/amplify-cli#13514] opened 2024-01-03 21:45 UTC
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18.18.2

### Amplify CLI Version

12.10.0

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Only changes to generated cloud formation templates (mostly removing unnecessary env vars, or adjusting the dynamodb permissions to be shorter/include the exact permission I needed).

### Describe the bug

When I try to use the `amplify video add` command, the generated GraphQL schema changes look like this:

```graphql
type VodAsset @model (subscriptions: {level: public})
@auth(
  rules: [
    {allow: owner, ownerField: "owner", operations: [create, update, delete, read] },
    {allow: groups, groups:["Admin"], operations: [create, update, delete, read]},
    {allow: private, operations: [read]}
  ]
)
{
  id:ID!
  title:String!
  description:String!

  #DO NOT EDIT
  video:VideoObject @connection
}

#DO NOT EDIT
type VideoObject @model
@auth(
  rules: [
    {allow: owner, ownerField: "owner", operations: [create, update, delete, read] },
    {allow: groups, groups:["Admin"], operations: [create, update, delete, read]},
    {allow: private, operations: [read]}
  ]
)
{
  id:ID!
}
```

Which is already a problem, because `@connection` isn't supported anymore it seems, and so it complains about that. But if I fix that and switch it to `@hasOne`, it then gives this error:

```
Edit your schema at /home/chris/dev/NewSeat/document-dashboard/amplify/backend/api/documentdashboard/schema.graphql or place .graphql files in a directory at /home/chris/dev/NewSeat/document-dashboard/amplify/backend/api/documentdashboard/schema
⠋ Building video resources...🛑 Cannot read properties of undefined (reading 'dev')

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
```

### Expected behavior

I'm not entirely sure what to expect, since this was the first time running this command, but I would expect it to not throw an error.

### Reproduction steps

I'm not sure if I can provide exact recreation steps. But here's the options I chose while running the `amplify video add command`:

```bash
$ amplify video add
? Select from one of the below mentioned services: Video-On-Demand
? Provide a friendly name for your resource to be used as a label for this category in the project: videoService
? Select a system-provided encoding template, specify an already-created template name:  Default HLS+DASH Adaptive
Bitrate
? Do you want to get notifications on the video processing job? Yes
? Do you want a custom function executed for notifications? Yes
? Is this a production enviroment? Yes
? Do you want to protect your content with signed urls? No
? Do you want Amplify to create a new GraphQL API to manage your videos? (Beta) Yes
Using documentdashboard to manage API
? Define your permission schema Admins can only upload videos, Any authenticated user can upload videos
? Do you want to override your GraphQL schema? No
? Do you want to edit your newly created model? Yes
```

Many other options error out in various other ways.

### Project Identifier

539310869d8d79b77347095522f128be

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment] 2024-01-04 15:46
Hey @SalmonMode, thank you for reaching out. This appears to be a duplicate of https://github.com/aws-amplify/amplify-cli/issues/11112, and [amplify-video](https://github.com/awslabs/amplify-video) is a third party plugin which is currently deprecated as mentioned by @armenr. Please see https://github.com/aws-amplify/amplify-cli/issues/11112#issuecomment-1268804613 for a more detailed explanation. 
@armenr thank you for chiming into this.

**Closed by ykethan** 2024-01-04 15:46 UTC
Labels: pending-triage

**Comment by SalmonMode** [comment] 2024-01-05 17:11
@armenr @ykethan ah, thanks for letting me know. 


@armenr Gotcha. I was luckily able to find `@aws-solutions-constructs/aws-cloudfront-s3` so I was able to get something up and running by adding a custom resource. I'll still need to hook up some transcoding stuff and manage my upload flow, but I think I have what I need. I appreciate the offer to collaborate, though!

**Comment by 8105976-lang** [comment] 2026-05-06 14:24
I like amplify amplify you can paly
