### ISSUE TITLE
Node module in Lambda Layer not found in connected function

### ISSUE THREAD

**Issue by kldeb** [aws-amplify/amplify-cli#4846] opened 2020-07-15 20:42 UTC
**Describe the bug**
I added a lambda layer to an existing project so that we can keep the dependencies in one place. We're using stripe for payment integration
 
**Amplify CLI Version**
4.23.0

**To Reproduce**
1. Have an existing project with functions that reference node modules. 
2. add a layer to the project
3. add the same dependencies to lambda layer
4. remove the dependencies from the function
5. update the function to use the new layer
6. push changes (we're using amplify console)
7. get module not found error when running the function after deployment

**Expected behavior**
expect the module in the layer to be required as usual. 

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v12.10.0

**Comment by jhockett** [comment] 2020-07-15 23:12
Hi @kldeb is there anything else in the Lambda layer that you are importing besides node_modules?

Can you share the line of code in your Lambda function where the import is failing?

**Comment by kldeb** [comment] 2020-07-16 00:18
@jhockett I added a file as well with a function in it but i haven't required it yet in the project. I'm saving that for "phase 2" changes as we adopt layers in the projects. 

this line is the issue (first line in the file): 

```js
const stripe = require('stripe')();
```

Here's the error from cloudwatch: 

```log
2020-07-15T19:16:35.234Z	undefined	ERROR	Uncaught Exception	
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'stripe'",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'stripe'",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:45:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
        "    at Module.load (internal/modules/cjs/loader.js:653:32)",
        "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
        "    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)",
        "    at startup (internal/bootstrap/node.js:283:19)"
    ]
}```

**Comment by jhockett** [comment] 2020-07-16 00:48
@kldeb can you describe the steps you took when you added the modules to the layer?

I was able to import the stripe module without issue.

**Comment by kldeb** [comment] 2020-07-16 17:30
@jhockett thanks for trying it out. 

- i added the layer using `amplify add function`
- cd'ed into the `shared/lib/nodejs` directory
- `npm install`'ed stripe
- back to cli and ran `amplify function update` and added the layer to the function 
- cd'ed into function src directory and `npm uninstall`'ed stripe
- committed changes to repo triggering build on amplify console
-saw the layer on the function in the lambda console
- called the query from the react front end and received error

**Comment by kldeb** [comment] 2020-07-16 18:46
Not sure if this is related but the aws console shows 17 layer versions (3 in the description) but the cli only shows version 1.

**Comment by jhockett** [comment] 2020-07-16 19:03
Based on the above steps, you are not using `amplify push`, is that correct?

**Comment by kldeb** [comment] 2020-07-16 19:27
@jhockett that's correct.

**Comment by jhockett** [comment] 2020-07-16 19:37
@kldeb that's likely why the layer versions shown by the CLI is out of sync then. All of the logic for packaging the layer happens on `amplify push`. 

This leads me to believe that the layer might be empty. Can you download the zip of the Lambda layer and check if the content you expect is present or not?

**Comment by kldeb** [comment] 2020-07-16 19:50
@jhockett i see. i downloaded the file (needed to add zip extention btw). it has the package.json file but the node_modules directory is empty. should i start again from stratch using `amplify push`?

**Comment by jhockett** [comment] 2020-07-16 19:54
That's what I would recommend. Lambda layers depends on the push flow to function correctly (it even adds the zip extension for you 😄).

**Comment by jhockett** [comment] 2020-07-16 19:56
@kldeb Let me know if that worked for you! Closing this issue. If you hit any roadblocks, please comment below and the issue can be re-opened.

**Closed by jhockett** 2020-07-16 19:56 UTC
Labels: Lambda layers

**Comment by kldeb** [comment] 2020-07-16 21:02
@jhockett thanks it worked! So i used amplify push to deploy the layer then went back to using amplify console to update to add the layer to the function.

**Comment by kldeb** [comment] 2020-07-17 01:37
@jhockett the error is back - module not found. This is after i updated the layer with a file i wouldn't to move into the layer. i pushed via cli. i got a message that the function that depends on it needs to be updated so i did that after the push was done then pushed the lambda change via cli just to be sure and got the error. then i pushed via console and still same error.

**Comment by jhockett** [comment] 2020-07-17 02:13
@kldeb when you got it working before, did you create a new layer altogether or push the previous one?

**Comment by kldeb** [comment] 2020-07-17 02:20
@jhockett i deleted the old layer and created a new one (with a new name just in case).

**Comment by jhockett** [comment] 2020-07-17 02:23
What module is it failing to import? `stripe` again?

**Comment by kldeb** [comment] 2020-07-17 02:24
yes, same as before.

**Comment by jhockett** [comment] 2020-07-17 02:34
Can you share the contents of `layer-parameters.json`?  Path should be `/amplify/backend/function/<your-Lambda-layer-name>/layer-parameters.json`

Have you checked the content in the Lambda layer's zip folder since running `amplify push` to verify that `node_modules` isn't empty?

**Comment by kldeb** [comment] 2020-07-17 02:40
I checked and the content is there. 

```
{
  "runtimes": [
    {
      "value": "nodejs",
      "name": "NodeJS",
      "layerExecutablePath": "nodejs/node_modules",
      "cloudTemplateValue": "nodejs12.x"
    }
  ],
  "layerVersionMap": {
    "1": {
      "permissions": [
        {
          "type": "private"
        }
      ],
      "hash": "1VMw2XPsH2QEuFPnJmaaCJUU1FIzC606WbsXVy5d5Zw="
    },
    "2": {
      "permissions": [
        {
          "type": "private"
        }
      ],
      "hash": "697ZdStCHWLWif2wBZQWKJYGM1KvMzpei7GuG/Q9Zj0="
    }
  }
}
```

**Comment by tomaszczechowski** [comment] 2020-07-25 20:51
I think you can have the same problem as I did.
I initially created a layer without choosing a provider like NodeJS. I ended up having different folders structure that supposes to have for node modules. After several tries to get it fixed a ended up having 9 versions of layer.
Then I realized that sth is wrong with the layer therefore, I begun the process again.

1. I made a backup of node_modules and package.json + package-lock.json
2. I detached the layer using command amplify function update
3. I removed the layer using command amplify function remove
4. I pushed the changes -> amplify push -y
5. It turned out that even if I removed the layer and push the changes with the success, the layer in the console has not been cleared out at all. I thought, that maybe it works like this to keep providing the versions to attached resources... I removed all layer's versions manually.

afterward, using CLI:

1. I created a layer (WITH THE SAME NAME - that's the key thing here, keep reading)
2. I copied node_modules to finally have created nodejs folder 
3. I attached the layer to the function having information about available version "1"
4. I pushed the changes.
5. I opened the console and noticed that instead of having a new layer created with version "1" I got an update of the previously removed layer (counter stoped on 9th version) with version 10 ->> what's going on? :-D It shows that if you use the name of the already removed layer you will have the version increased by 1 from the last one. The funny thing is that if I open the layer in the console I can see only the last version 10 without having the previous 9th that I removed. For me, it looks like a bug.

You can either attach the layer by selecting an option "Provide existing Lambda layer ARNs" or creating the layer with a different name to have the layer counter started from 1.

Once I did that the issue with the missing module was resolved.

Hope it helps.

**Comment by dylan-westbury** [comment] 2020-08-31 08:42
I have this issue also, module can't be found, here are steps to reproduce: 

1. Create a nodejs lambda layer (for dependencies with stripe only)
2. Create function that uses the layer (works fine calling stripe methods)
3. Add new dependency (moment) and amplify push
`Cannot find module 'moment'`

5. Update function to use new version of lambda layer and amplify push
`Cannot find module 'moment'`

6. Remove layer from lambda function and amplify push
7. Re-add layer to lambda function 
`Cannot find module 'moment'`

```
{
  "runtimes": [
    {
      "value": "nodejs",
      "name": "NodeJS",
      "layerExecutablePath": "nodejs/node_modules",
      "cloudTemplateValue": "nodejs12.x"
    }
  ],
  "layerVersionMap": {
    "1": {
      "permissions": [
        {
          "type": "awsAccounts",
          "accounts": [
            "xxxxxxxxxx"
          ]
        },
        {
          "type": "private"
        }
      ],
      "hash": "xxxxxxxxxx"
    },
    "2": {
      "permissions": [
        {
          "type": "awsAccounts",
          "accounts": [
            "xxxxxxxxxx"
          ]
        },
        {
          "type": "private"
        }
      ],
      "hash": "xxxxxxxxxx"
    }
  }
}
```

**Comment by juniarz** [comment] 2020-09-16 05:11
Hi i think it could be due to the lambda runtimes.

The layer is configured for node v12 while your lambda functions are running on other node versions.

**Comment by lkowalski-smartbusiness** [comment] 2020-09-18 11:31
> I have this issue also, module can't be found, here are steps to reproduce:
> 
> 1. Create a nodejs lambda layer (for dependencies with stripe only)
> 2. Create function that uses the layer (works fine calling stripe methods)
> 3. Add new dependency (moment) and amplify push
>    `Cannot find module 'moment'`
> 4. Update function to use new version of lambda layer and amplify push
>    `Cannot find module 'moment'`
> 5. Remove layer from lambda function and amplify push
> 6. Re-add layer to lambda function
>    `Cannot find module 'moment'`
> 
> ```
> {
>   "runtimes": [
>     {
>       "value": "nodejs",
>       "name": "NodeJS",
>       "layerExecutablePath": "nodejs/node_modules",
>       "cloudTemplateValue": "nodejs12.x"
>     }
>   ],
>   "layerVersionMap": {
>     "1": {
>       "permissions": [
>         {
>           "type": "awsAccounts",
>           "accounts": [
>             "xxxxxxxxxx"
>           ]
>         },
>         {
>           "type": "private"
>         }
>       ],
>       "hash": "xxxxxxxxxx"
>     },
>     "2": {
>       "permissions": [
>         {
>           "type": "awsAccounts",
>           "accounts": [
>             "xxxxxxxxxx"
>           ]
>         },
>         {
>           "type": "private"
>         }
>       ],
>       "hash": "xxxxxxxxxx"
>     }
>   }
> }
> ```

@dylan-westbury did you update your function that is **using** the layer? The extra dependency will only show up in layer v2 so if you don't update that reference for the main function you're toast
`amplify function update` and look for layer settings

**Comment by akash87** [comment] 2020-12-06 16:30
I was able to resolve this by updating amplify.yml to build lambda layer before calling amplifyPush
Example of build script.

build:
      commands:
        - '# Execute module build for lambda layers'
        - cd ./amplify/backend/function/viewerlayer/lib/nodejs
        - yarn install
        - echo "# Back to root folder"
        - cd ../../../../../..
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple

**Comment by dylan-westbury** [comment] 2020-12-12 01:19
We are having issue again on another project. 

**Lambda function parameters.json**
```
  "lambdaLayers": [
    {
      "type": "ProjectLayer",
      "resourceName": "DependencyLayer",
      "version": 2
    }
  ]
```

**Lambda function code **
```
const moment = require('moment');
```

**Lambda layer**
```
{
  "layerVersion": 2
}
```

**Package.json**
```
{
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "libphonenumber-js": "^1.9.6",
    "lodash": "^4.17.20",
    "moment": "^2.29.1"
  },
  "devDependencies": {}
}
```

Error from cloudwatch
```
Error: Cannot find module 'moment'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js
```

I can see node_modules installed within layer.

**Comment by xenowits** [comment] 2021-04-24 13:48
Does anyone hv solution for this?
It's a really interesting bug though
