### ISSUE TITLE
Lambda layer versioning out of sync

### ISSUE THREAD

**Issue by danielblignaut** [aws-amplify/amplify-cli#4963] opened 2020-07-29 10:21 UTC
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

1. Add a lambda layer to your amplify project using amplify function add
2. push this project
3. remove the lambda layer using amplify function remove
4. add the layer again using amplify function add (use the same resource name)
5. push the stack again

You will notice that now your version mapping on lambda layers is incorrect as AWS lambda never truly deletes a lambda layer or the version of that layer.  

In AWS , you now have 1 lambda layer with 2 versions of that layer (the latest being your latest code)
On your local machine, you only have 1 lambda layer with 1 version of that layer. 
Your resources will always therefore be pointing to the old layer instead of the new layer.

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
(base) user:backend user$ amplify -v
4.25.0

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

1. Add a lambda layer to your amplify project using amplify function add
2. push this project
3. remove the lambda layer using amplify function remove
4. add the layer again using amplify function add (use the same resource name)
5. push the stack again

**Expected behavior**

Re-adding a lambda layer with the same name needs to pull the layer version from AWS somehow even if the layer or version no longer "exists" in AWS as it's still is really "there behind the scenes"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

Mac
v12.14.0

**Additional context**

**Comment by danielblignaut** [comment] 2020-07-29 10:30
A manual fix for this, if it can't be automated, perhaps is to document the below:

if AWS layer version = 2
and local layer version = 1

1. open layer-parameters.json:

here you should only have one entry under versionMap... change this entry value from "1" to "3"

2. open backend-config.json:

under your lamda layer entry, again here you should only have one entry under versionMap... change this entry value from "1" to "3"

3. remove all layer dependency references from your other lambda functions...

run amplify function update 
select the function dependant on the above layer
remove the layer from the function

4. re-add all layer dependency references from your other lambda functions...

run amplify function update 
select the function dependant on the above layer
add the layer to the function

5. run amplify env checkout (you changed the backend-config.json)

6. amplify push

**Comment by dtelaroli** [comment] 2020-07-29 13:13
I have problem with different version between environments.
If you push multiple new versions in one env, when you go to another env, it fails, because those versions does not exists.

```
CREATE_FAILED               functiondependencies              AWS::CloudFormation::Stack Wed Jul 29 2020 10:05:31 GMT-0300 (Brasilia Standard Time) Embedded stack arn:aws:cloudformation:us-east-1:<id>:stack/<stackId> was not successfully created: The following resource(s) failed to create: [LambdaLayerPermissionprivate8, LambdaLayerPermissionprivate5, LambdaLayerPermissionprivate9, LambdaLayerPermissionprivate4, LambdaLayerPermissionprivate2, LambdaLayer, LambdaLayerPermissionprivate3, LambdaLayerPermissionprivate6, LambdaLayerPermissionprivate7].
CREATE_FAILED LambdaLayerPermissionprivate4 AWS::Lambda::LayerVersionPermission Wed Jul 29 2020 10:05:17 GMT-0300 (Brasilia Standard Time) Layer version <stackId>:4 does not exist. (Service: AWSLambdaInternal; Status Code: 404; Error Code: ResourceNotFoundException; Request ID: 2a573f91-e1d6-46e8-83c7-242317825876)
```

**Comment by danielblignaut** [comment] 2020-07-29 13:16
@dtelaroli what's the latest lambda layer version on AWS for that layer?
As far as I can tell, lambda layers don't currently support multiple AWS amplify environment configs

**Comment by dtelaroli** [comment] 2020-07-29 13:25
I'm using two environments and two aws accounts. I can share the lambda layer between accounts using organization permission, but the cli try deploy the lambda layer in each environment. If you right that the amplify does not support multi-env with lambda layer, amplify does not support multi-env after to use lambda layer managed by it. I'm locked in this issue.
I will remove lambda layer, because I can't lose multi-env and I will manage it with SAM.

**Comment by hisham** [comment] 2020-07-30 01:53
This is a dupe of https://github.com/aws-amplify/amplify-cli/issues/4886.

**Comment by naldertown** [comment] 2020-08-03 14:09
+1

**Comment by jhockett** [comment] 2020-08-03 21:09
Closing this in favor of #4886

**Closed by jhockett** 2020-08-03 21:09 UTC
Labels: Lambda layers, pending-triage
