### ISSUE TITLE
Owner update permission not working

### ISSUE THREAD

**Issue by maxludovicohofer** [aws-amplify/amplify-cli#9870] opened 2022-02-28 08:40 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.17.3

### Amplify CLI Version

7.6.22

### What operating system are you using?

Windows 11

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Added auth permissions in auth override.ts to all user groups in order to access geo and pinpoint.

### Amplify Categories

auth, api

### Amplify Commands

Not applicable

### Describe the bug

When a model has an auth rule that specifies owner update and an owner executes an update, the operation is not synced to the backend. No warning/error is displayed in the console.

### Expected behavior

The owner should be able to update, as was the case before 7.6.22.

### Reproduction steps

1. Create a model with auth rule update
2. Try to update and check if the update is synced

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line

type Task implements Deletable
  @model
  @auth(
    rules: [
      {
        allow: owner
        ownerField: "assigner"
        operations: [create, read, update]
      }
      { allow: owner, ownerField: "assignee", operations: [update] }
      { allow: groups, groups: ["Admin"], operations: [update, delete] }
      { allow: groups, groups: ["Management"], operations: [update] }
      { allow: private, operations: [read] }
    ]
  ) {
  id: ID!
  deletedAt: AWSDateTime @index(name: "byDeleted")
  assigner: String
  assignee: String! @index(name: "byAssignee")
  startDateTime: AWSDateTime!
  endDateTime: AWSDateTime!
  moved: Int @default(value: "0")
  activityTasksId: ID!
  identityTasksId: ID!
  children: [Task!] @hasMany
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by sachscode** [comment] 2022-03-01 00:16
Question: "Try to update and check if the update is synced"
How did you check if the update has synced ?

**Comment by maxludovicohofer** [comment] 2022-03-01 08:30
I created a "Task" model with an Admin user.
I updated that "Task" with a user that has only owner permission on a separate client.
By querying on both clients, the owner gets the updated task, while the Admin still receives the old task.

By the way, I use datastore for this test.

**Comment by josefaidt** [comment] 2022-03-01 17:35
Hey @maxludovicohofer :wave: outside of the context of DataStore I was able to reproduce this following issue #9883 , copying my notes here

I was not able to reproduce using the following schema:

```graphql
type Todo
  @model
  @auth(
    rules: [
      { allow: owner }
      { allow: groups, groups: ["admins"] }
    ]
  ) {
  id: ID! @primaryKey
  owner: ID
  name: String!
  description: String
}
```

with two users, `admin` and `user`, of which `admin` is a member of the `admins` group. Both `admin` and `user` are able to update records as intended. However, when explicitly granting `update` access the update mutations no longer work:

```graphql
type Todo
  @model
  @auth(
    rules: [
      { allow: owner, operations: [create, update, read] }
      { allow: groups, groups: ["admins"], operations: [read] }
    ]
  ) {
  id: ID! @primaryKey
  owner: ID
  name: String!
  description: String
}
```

It is important to note `create` and `read` are working as expected.

![image](https://user-images.githubusercontent.com/5033303/156216011-6de715e4-9728-4575-b95a-7c705e773180.png)


Marking as a bug 🙂

**Closed** 2022-03-14 22:00 UTC
Labels: bug, @auth, p2
