### ISSUE TITLE
subscriptions not working with user in allowed group

### ISSUE THREAD

**Issue by pmadhav** [aws-amplify/amplify-cli#4936] opened 2020-07-25 22:10 UTC
**Describe the bug**
For an auth model using Cognito user pool where a given user is in an allowed group, the user does not get notified of newly created objects. This is the model that I am using to test (based on the default generated from the amplify CLI, just added auth rules & owner field to all types).
```graphql
type Blog
@model
@auth(rules: [
  {allow: owner},
  {allow: groups, groups:["admin"]}
  ])
{
  id: ID!
  owner: String
  name: String!
  posts: [Post] @connection(keyName: "byBlog", fields: ["id"])
}

type Post
@model
@auth(rules: [
  {allow: owner},
  {allow: groups, groups:["admin"]}
  ])
@key(name: "byBlog", fields: ["blogID"]) {
  id: ID!
  owner: String
  title: String!
  blogID: ID!
  blog: Blog @connection(fields: ["blogID"])
  comments: [Comment] @connection(keyName: "byPost", fields: ["id"])
}

type Comment
@model
@auth(rules: [
  {allow: owner},
  {allow: groups, groups:["admin"]}
  ])
@key(name: "byPost", fields: ["postID", "content"]) {
  id: ID!
  owner: String
  postID: ID!
  post: Post @connection(fields: ["postID"])
  content: String!
}
```

The Cognito user pool has the following users:

username | group
----------|-------
user1|user
user2|user
admin1|admin
admin2|admin

**Amplify CLI Version**
`4.25.0`

**Expected behavior**
Based on the documentation at this link, https://docs.amplify.aws/cli/graphql-transformer/directives#authorizing-subscriptions, it leads me to believe that user `admin1` should be able to subscribe for `onCreateBlog` and receive notifications for any `Blog` objects created by either `admin1` or `admin2`, but what is observed is that the user subscribing only ever receives the objects owned by that user and not by any other user.

If you scroll down a bit from the provided link (right at the end of the section), it says:

_Finally, if you use both owner and group authorization then the username argument becomes optional. This means the following:_

- _If you don’t pass the user in, but are a member of an allowed group, the subscription will notify you of records added._
- _If you don’t pass the user in, but are NOT a member of an allowed group, the subscription will fail to connect._
- _If you pass the user in who IS the owner but is NOT a member of a group, the subscription will notify you of records added of which you are the owner._
- _If you pass the user in who is NOT the owner and is NOT a member of a group, the subscription will not notify you of anything as there are no records for which you own_

Based on this, I've tested the following scenarios:

id|user subscribing|group|user passed in subscription|user in allowed group|subscription success|object owner|notification received
--|--|--|--|--|--|--|--
1|user1|user|no|no|no|N/A|N/A
2|user1|user|yes/user1|no|yes|user1|yes
3|user1|user|yes/user1|no|yes|user2|no
4|user1|user|yes/admin1|no|no|N/A|N/A
5|admin1|admin|no|yes|yes|user1|**NO**
6|admin1|admin|no|yes|yes|admin1|**NO**
7|admin1|admin|no|yes|yes|admin2|**NO**
8|admin1|admin|yes/admin1|yes|yes|user1|no
9|admin1|admin|yes/admin1|yes|yes|admin1|yes
10|admin1|admin|yes/admin1|yes|yes|admin2|no
11|admin1|admin|yes/user1|yes|yes|user1|yes

I expected `5,6 and 7` in the test list above to succeed and receive a notification, but did not get any notification. Note that the `admin1` user is able to read the objects (using `get` or `list` operations) created in `5,6 and 7` in the test list above.

**Desktop (please complete the following information):**
 - OS: `macOS Catalina 10.15.5`
 - Node Version: `v14.2.0`

**Comment by pmadhav** [comment] 2020-10-20 15:50
@edwardfoyle @ammarkarachi Is there any update on this issue? I still see it in `pending-triage` state for over a month.

**Comment by edwardfoyle** [comment] 2021-01-29 19:37
Hi @pmadhav based on the docs and the behavior you listed above this is a bug. Added it to our GraphQL Transformer V2 project to track

**Comment by pmadhav** [comment] 2021-01-29 22:19
Thanks for the update @edwardfoyle. Looking forward to the fix for this.

**Comment by matteocarpi** [comment] 2021-03-24 08:13
Hi @edwardfoyle! Is there any news on when the GraphQL Transformer V2 will be released with this fix? Or where can one track progress? 

Thanks!

**Comment by danielesalvatore** [comment] 2021-03-24 08:32
Hi there! Just got here because I'm experiencing the same kind of issue using Amplify CLI v 4.46

**Comment by lazpavel** [comment] 2022-02-16 18:35
Hi @pmadhav, @danielesalvatore, @matteocarpi 

This issue seems to be fixed in the latest CLI. Tested in GraphQL Transformer V1 and GraphQL Transformer V2. Please reopen if you still have this issue after upgrading.

**Closed by lazpavel** 2022-02-16 18:35 UTC
Labels: bug, graphql-transformer-v1, @auth

**Comment by albertopavesi** [comment] 2022-03-19 19:45
> Hi @pmadhav, @danielesalvatore, @matteocarpi
> 
> This issue seems to be fixed in the latest CLI. Tested in GraphQL Transformer V1 and GraphQL Transformer V2. Please reopen if you still have this issue after upgrading.

Hi, I am experiencing the same problema both with v1 and v2. The goal is to have a model that is editable by the owner and by the administrators of the system. Every works fine when create, update, read the data, but I can't get subscription to work when on the @auth of the model I include both owner and groups.
Reading that the issue seems to be fixed I upgraded the cli to the latest version that appears to be, as of today, 7.6.25.

Any additional information to help on this?

**Comment by lazpavel** [comment] 2022-03-21 14:59
Hi @albertopavesi, 

After upgrading, can you ensure that the schema is recompiled and pushed (you can add a blank space to `schema.graphql` in order to trigger a difference check).

If you test just by using the AppSync console, in one tab executing the create/update mutation while in another one executing the subscription query, do you get any errors, is the subscription getting notified? Or is the issue happening when using data store only?

If you still have the issue can you attach a schema for reproduction? Let me know and I will reopen the issue

**Comment by albertopavesi** [comment] 2022-03-21 18:36
> Hi @albertopavesi,
> 
> After upgrading, can you ensure that the schema is recompiled and pushed (you can add a blank space to `schema.graphql` in order to trigger a difference check).
> 
> If you test just by using the AppSync console, in one tab executing the create/update mutation while in another one executing the subscription query, do you get any errors, is the subscription getting notified? Or is the issue happening when using data store only?
> 
> If you still have the issue can you attach a schema for reproduction? Let me know and I will reopen the issue

Hi @lazpavel, thank you for your kind reply. Unfortunately I had to stop my investigation to focus on a workaround but I will be back to you with more details in few days.

**Comment by konishi18** [comment] 2022-04-09 12:11
@lazpavel 

If both owner and group exist.

You cannot get all subscriptions of Model (Table) in the account that belongs to group.

`this.OnUpdateListener(id).subscribe(() => {});`

Expected behavior
`this.OnUpdateListener().subscribe(() => {});`

I don't know if this is relevant.
I hope you will find it helpful.

**Comment by shichi18** [comment] 2022-04-09 12:12
@lazpavel

If both owner and group exist.

You cannot get all subscriptions of Model (Table) in the account that belongs to group.

this.OnUpdateListener(id).subscribe(() => {});

Expected behavior
this.OnUpdateListener().subscribe(() => {});

I don't know if this is relevant.
I hope you will find it helpful.
