### ISSUE TITLE
SNS role set when mfa is disabled

### ISSUE THREAD

**Issue by clementAC** [aws-amplify/amplify-cli#3039] opened 2019-12-18 23:44 UTC
**Describe the bug**
A sns role is created on the cognito user pool even when the mfa option is not set during ``` amplify add auth ``` 
It cause some problems when I want to modify some options in the cognito console concerning verification. I can't modify anything because there is a sns role set that i can't delete (the field is disabled and even if i delete the role the field is set).

Every time I try to modify a verification option I am getting an error message (MFA can't be deactivated if a SMS role is set)

**To Reproduce**

- Add auth to your application through amplify cli
- Go to cognito admin console and try to modify a verification option

**Expected behavior**
Be able to delete the sns role in order to change verification option

**Comment by ammarkarachi** [comment] 2019-12-23 23:47
Hey @clementAC, We are working on this issue, will update you on when the issue is resolved.

**Comment by clementAC** [comment] 2019-12-27 19:35
Thanks @ammarkarachi

**Comment by wildcard27** [comment] 2020-01-04 09:40
Hey @ammarkarachi any eta on this fix? It's holding up development here.

**Comment by richAtreides** [comment] 2020-02-03 11:36
Can I ask if this was fixed as its also caused a problem for me. I deleted the role and now its still showing in cognito and causing a blocker as I can't replace it.

**Comment by wildcard27** [comment] 2020-06-19 12:32
I hate to be that guy but since your bot is trying to close the issue I figured it should stay open as a point of communication. Is there an ETA on this?

**Comment by SwaySway** [comment] 2020-08-04 00:45
As of now if you add auth with MFA it will create the IAM SNS role though you are not able to change it or remove it. This is something we can't change as the implementation lies within Cognito. Should you have further questions on this we recommend their support forum: https://forums.aws.amazon.com/forum.jspa?forumID=173

Closing this in favor of https://github.com/aws-amplify/amplify-cli/issues/887 as a bug to fix on the CLI's side between enabling/disabling MFA.

**Closed by SwaySway** 2020-08-04 00:45 UTC
Labels: auth, pending-triage, work-in-progress
