### ISSUE TITLE
GraphQL AppSync Subscriptions not generated by AWS Amplify for custom mutations

### ISSUE THREAD

**Issue by GeeeCoin** [aws-amplify/amplify-cli#1810] opened 2019-07-11 01:55 UTC
I tried creating a custom Subscription without the model directive using an explicit mutation declaration (also not created with model directive), but amplify will fail to create subscriptions in the build schema. 

I've tried a bunch of permutations and amplify push doesn't seem to play nice with a mixed subscription case where some mutations are defined in the model directive of types.

```graphql
schema {
mutation: Mutation
query: Query
subscription: Subscription
}

myModel @model(queries: { get: "getStuff" }){
...
}

Mutation {
doSomething(input: Shape): myModel
}

Subscription {
onDoSomething: myModel @aws_subscribe(mutations: ["doSomething"])
}
```

Do you know what I might be doing wrong? Subscription generation fails silently and the rest of the graphql build schema is generated fine. If i remove the custom subscription and subscribe to only mutations in the model directives, subscriptions are built. Thanks! 

Amplify version: 1.8.1 on MacOS, dev for JS

**Comment by attilah** [comment] 2019-07-12 09:30
@GeeeCoin Based on the information you posted I used the schema below:

```graphql
type myModel @model(queries: { get: "getStuff" })
{
  id: ID!
  name: String!
}

input Shape {
  id: ID!
  name: String!
}

type Mutation {
  doSomething(input: Shape): myModel
}

type Subscription {
  onDoSomething: myModel @aws_subscribe(mutations: ["doSomething"])
}
```

After I did a `amplify api gql-compile` command and checked the `build\schema.graphql` file and it did contain the `doSomething` mutation and the `onDoSomething` subscription as well. Upon pushing this API everything was fine and I was able to see the expected results in the AppSync Console.

What pieces are you exactly missing in the build files? When you define a custom query or mutation there will be no resolvers generated or attached to it, since these are custom resources, so you have to define them in `backend\api\<api name>\stacks\CustomResources.json` file and create the resolvers in the `resolvers` folder.

Here is the docs page for custom resolvers: https://aws-amplify.github.io/docs/cli-toolchain/graphql#overwriting-resolvers

Please get back to me if this answers / solves your problem or if there is something I'm missing.

**Comment by kaustavghosh06** [comment] 2019-07-18 19:36
Closing this issue since it's not reproducable as mentioned bby @attilah above. Please feel free to comment on this thread if you're still stuck with this.

**Closed by kaustavghosh06** 2019-07-18 19:36 UTC
Labels: graphql-transformer, pending-response, question
